gmsh-TingyuanDoc: src/mesh/BDS.h File Reference
BDS.h File Reference
#include <set>
#include <vector>
#include <algorithm>
#include <functional>
#include <cmath>
#include "GmshMessage.h"
Classes
class BDS_GeomEntity
class BDS_Point
class BDS_Edge
class BDS_Face
struct GeomLessThan
struct PointLessThan
struct PointLessThanLexicographic
struct EdgeLessThan
class BDS_SwapEdgeTest
class BDS_SwapEdgeTestRecover
class BDS_SwapEdgeTestQuality
class BDS_SwapEdgeTestNormals
struct EdgeToRecover
class BDS_Mesh
Functions
void normal_triangle (BDS_Point *p1, BDS_Point *p2, BDS_Point *p3, double c[3])
void outputScalarField (std::vector< BDS_Face * > &t, const char *fn, int param, GFace *gf=nullptr)
void recur_tag (BDS_Face *t, BDS_GeomEntity *g)
int Intersect_Edges_2d (double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4, double x[2])
double BDS_Face_Validity (GFace *gf, BDS_Face *f)
Function Documentation
BDS_Face_Validity()
double BDS_Face_Validity (GFace * gf, BDS_Face * f)
Definition at line 33 of file BDS.cpp.
Referenced by refineMeshBDS().
Intersect_Edges_2d()
int Intersect_Edges_2d (double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4, double x[2])
Definition at line 307 of file BDS.cpp.
Referenced by BDS_Mesh::recover_edge().
normal_triangle()
void normal_triangle (BDS_Point * p1, BDS_Point * p2, BDS_Point * p3, double c[3])
Definition at line 185 of file BDS.cpp.
Referenced by _cos_N(), and edgeSwapTestAngle().
outputScalarField()
void outputScalarField (std::vector< BDS_Face * > & t, const char * fn, int param, GFace * gf = nullptr)
Definition at line 46 of file BDS.cpp.
Referenced by meshGenerator(), meshGeneratorPeriodic(), BDS_Mesh::recover_edge(), recoverEdge(), and refineMeshBDS().
recur_tag()
void recur_tag (BDS_Face * t, BDS_GeomEntity * g)
Definition at line 605 of file BDS.cpp.
Referenced by meshGenerator(), and meshGeneratorPeriodic().