gmsh-TingyuanDoc: src/mesh/BackgroundMeshTools.cpp File Reference
BackgroundMeshTools.cpp File Reference
#include "BackgroundMeshTools.h"
#include "GFace.h"
#include "GVertex.h"
#include "GEdge.h"
#include "GEntity.h"
#include "Context.h"
#include "Field.h"
#include "GModel.h"
Functions
static double max_surf_curvature (const GEdge *ge, double u)
static double max_edge_curvature (const GVertex *gv)
static double LC_MVertex_CURV (GEntity *ge, double U, double V)
SMetric3 max_edge_curvature_metric (const GEdge *ge, double u)
static SMetric3 metric_based_on_surface_curvature (const GEdge *ge, double u, bool iso_surf)
static SMetric3 metric_based_on_surface_curvature (const GVertex *gv, bool iso_surf)
SMetric3 LC_MVertex_CURV_ANISO (GEntity *ge, double U, double V)
static double LC_MVertex_PNTS (GEntity *ge, double U, double V)
SMetric3 buildMetricTangentToCurve (SVector3 &t, double l_t, double l_n)
SMetric3 buildMetricTangentToSurface (SVector3 &t1, SVector3 &t2, double l_t1, double l_t2, double l_n)
double BGM_MeshSizeWithoutScaling (GEntity *ge, double U, double V, double X, double Y, double Z)
double BGM_MeshSize (GEntity *ge, double U, double V, double X, double Y, double Z)
SMetric3 BGM_MeshMetric (GEntity *ge, double U, double V, double X, double Y, double Z)
bool Extend1dMeshIn2dSurfaces (GFace *gf)
bool Extend2dMeshIn3dVolumes ()
SMetric3 max_edge_curvature_metric (const GVertex *gv)
SMetric3 metric_based_on_surface_curvature (const GFace *gf, double u, double v, bool surface_isotropic, double d_normal, double d_tangent_max)
Function Documentation
BGM_MeshMetric()
SMetric3 BGM_MeshMetric (GEntity * ge, double U, double V, double X, double Y, double Z)
Definition at line 284 of file BackgroundMeshTools.cpp.
Referenced by F_Lc_aniso::operator()().
BGM_MeshSize()
double BGM_MeshSize (GEntity * ge, double U, double V, double X, double Y, double Z)
Definition at line 255 of file BackgroundMeshTools.cpp.
Referenced by buildConsecutiveListOfVertices(), buildMeshGenerationDataStructures(), GFace::computeMeshSizeFieldAccuracy(), correctLC_(), createSizeFieldFromExistingMesh(), insertAPoint(), insertVerticesInRegion(), meshGenerator(), meshGeneratorPeriodic(), meshGRegionNetgen(), optimizeMeshGRegionNetgen::operator()(), F_LcB::operator()(), F_Lc::operator()(), remeshUnrecoveredEdges(), splitEdgePass(), and backgroundMesh::updateSizes().
BGM_MeshSizeWithoutScaling()
double BGM_MeshSizeWithoutScaling (GEntity * ge, double U, double V, double X, double Y, double Z)
Definition at line 211 of file BackgroundMeshTools.cpp.
Referenced by BGM_MeshSize().
buildMetricTangentToCurve()
SMetric3 buildMetricTangentToCurve (SVector3 & t, double l_t, double l_n)
Definition at line 169 of file BackgroundMeshTools.cpp.
Referenced by BoundaryLayerField::computeFor1dMesh(), max_edge_curvature_metric(), and BoundaryLayerField::operator()().
buildMetricTangentToSurface()
SMetric3 buildMetricTangentToSurface (SVector3 & t1, SVector3 & t2, double l_t1, double l_t2, double l_n)
Definition at line 194 of file BackgroundMeshTools.cpp.
Referenced by BoundaryLayerField::operator()().
Extend1dMeshIn2dSurfaces()
bool Extend1dMeshIn2dSurfaces (GFace * gf)
Definition at line 339 of file BackgroundMeshTools.cpp.
Referenced by buildMeshGenerationDataStructures(), insertVertexB(), NewGetLc(), optimalPointFrontal(), and optimalPointFrontalQuad().
Extend2dMeshIn3dVolumes()
bool Extend2dMeshIn3dVolumes ()
Definition at line 345 of file BackgroundMeshTools.cpp.
Referenced by insertVertexB(), and MTet4::setup().
LC_MVertex_CURV()
static double LC_MVertex_CURV (GEntity * ge, double U, double V) static
Definition at line 48 of file BackgroundMeshTools.cpp.
Referenced by BGM_MeshSizeWithoutScaling().
LC_MVertex_CURV_ANISO()
SMetric3 LC_MVertex_CURV_ANISO (GEntity * ge, double U, double V)
Definition at line 116 of file BackgroundMeshTools.cpp.
Referenced by BGM_MeshMetric().
LC_MVertex_PNTS()
static double LC_MVertex_PNTS (GEntity * ge, double U, double V) static
Definition at line 134 of file BackgroundMeshTools.cpp.
Referenced by BGM_MeshMetric(), and BGM_MeshSizeWithoutScaling().
max_edge_curvature()
static double max_edge_curvature (const GVertex * gv) static
Definition at line 29 of file BackgroundMeshTools.cpp.
Referenced by LC_MVertex_CURV().
max_edge_curvature_metric() [1/2]
SMetric3 max_edge_curvature_metric (const GEdge * ge, double u)
Definition at line 76 of file BackgroundMeshTools.cpp.
Referenced by metric_based_on_surface_curvature().
max_edge_curvature_metric() [2/2]
SMetric3 max_edge_curvature_metric (const GVertex * gv)
Definition at line 351 of file BackgroundMeshTools.cpp.
max_surf_curvature()
static double max_surf_curvature (const GEdge * ge, double u) static
Definition at line 15 of file BackgroundMeshTools.cpp.
Referenced by LC_MVertex_CURV(), and max_edge_curvature().
metric_based_on_surface_curvature() [1/3]
static SMetric3 metric_based_on_surface_curvature (const GEdge * ge, double u, bool iso_surf) static
Definition at line 90 of file BackgroundMeshTools.cpp.
Referenced by LC_MVertex_CURV_ANISO().
metric_based_on_surface_curvature() [2/3]
SMetric3 metric_based_on_surface_curvature (const GFace * gf, double u, double v, bool surface_isotropic, double d_normal, double d_tangent_max)
Definition at line 383 of file BackgroundMeshTools.cpp.
metric_based_on_surface_curvature() [3/3]
static SMetric3 metric_based_on_surface_curvature (const GVertex * gv, bool iso_surf) static
Definition at line 109 of file BackgroundMeshTools.cpp.