gmsh-TingyuanDoc: src/mesh/BackgroundMeshTools.h File Reference
BackgroundMeshTools.h File Reference
#include "STensor3.h"
Functions
SMetric3 buildMetricTangentToCurve (SVector3 &t, double l_t, double l_n)
SMetric3 buildMetricTangentToSurface (SVector3 &t1, SVector3 &t2, double l_t1, double l_t2, double l_n)
double BGM_MeshSize (GEntity *ge, double U, double V, double X, double Y, double Z)
double BGM_MeshSizeWithoutScaling (GEntity *ge, double U, double V, double X, double Y, double Z)
SMetric3 BGM_MeshMetric (GEntity *ge, double U, double V, double X, double Y, double Z)
bool Extend1dMeshIn2dSurfaces (GFace *gf)
bool Extend2dMeshIn3dVolumes ()
SMetric3 max_edge_curvature_metric (const GVertex *gv)
SMetric3 max_edge_curvature_metric (const GEdge *ge, double u, double &l)
SMetric3 metric_based_on_surface_curvature (const GFace *gf, double u, double v, bool surface_isotropic=false, double d_normal=1.e12, double d_tangent_max=1.e12)
Function Documentation
BGM_MeshMetric()
SMetric3 BGM_MeshMetric (GEntity * ge, double U, double V, double X, double Y, double Z)
Definition at line 284 of file BackgroundMeshTools.cpp.
Referenced by F_Lc_aniso::operator()().
BGM_MeshSize()
double BGM_MeshSize (GEntity * ge, double U, double V, double X, double Y, double Z)
Definition at line 255 of file BackgroundMeshTools.cpp.
Referenced by buildConsecutiveListOfVertices(), buildMeshGenerationDataStructures(), GFace::computeMeshSizeFieldAccuracy(), correctLC_(), createSizeFieldFromExistingMesh(), insertAPoint(), insertVerticesInRegion(), meshGenerator(), meshGeneratorPeriodic(), meshGRegionNetgen(), optimizeMeshGRegionNetgen::operator()(), F_LcB::operator()(), F_Lc::operator()(), remeshUnrecoveredEdges(), splitEdgePass(), and backgroundMesh::updateSizes().
BGM_MeshSizeWithoutScaling()
double BGM_MeshSizeWithoutScaling (GEntity * ge, double U, double V, double X, double Y, double Z)
Definition at line 211 of file BackgroundMeshTools.cpp.
Referenced by BGM_MeshSize().
buildMetricTangentToCurve()
SMetric3 buildMetricTangentToCurve (SVector3 & t, double l_t, double l_n)
Definition at line 169 of file BackgroundMeshTools.cpp.
Referenced by BoundaryLayerField::computeFor1dMesh(), max_edge_curvature_metric(), and BoundaryLayerField::operator()().
buildMetricTangentToSurface()
SMetric3 buildMetricTangentToSurface (SVector3 & t1, SVector3 & t2, double l_t1, double l_t2, double l_n)
Definition at line 194 of file BackgroundMeshTools.cpp.
Referenced by BoundaryLayerField::operator()().
Extend1dMeshIn2dSurfaces()
bool Extend1dMeshIn2dSurfaces (GFace * gf)
Definition at line 339 of file BackgroundMeshTools.cpp.
Referenced by buildMeshGenerationDataStructures(), insertVertexB(), NewGetLc(), optimalPointFrontal(), and optimalPointFrontalQuad().
Extend2dMeshIn3dVolumes()
bool Extend2dMeshIn3dVolumes ()
Definition at line 345 of file BackgroundMeshTools.cpp.
Referenced by insertVertexB(), and MTet4::setup().
max_edge_curvature_metric() [1/2]
SMetric3 max_edge_curvature_metric (const GEdge * ge, double u, double & l)
max_edge_curvature_metric() [2/2]
SMetric3 max_edge_curvature_metric (const GVertex * gv)
Definition at line 351 of file BackgroundMeshTools.cpp.
metric_based_on_surface_curvature()
SMetric3 metric_based_on_surface_curvature (const GFace * gf, double u, double v, bool surface_isotropic = false, double d_normal = 1.e12, double d_tangent_max = 1.e12)
Definition at line 383 of file BackgroundMeshTools.cpp.