gmsh-TingyuanDoc: src/mesh/BoundaryLayers.cpp File Reference
BoundaryLayers.cpp File Reference
#include "GModel.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "BoundaryLayers.h"
#include "ExtrudeParams.h"
#include "meshGEdge.h"
#include "meshGFace.h"
#include "GmshMessage.h"
#include "Field.h"
#include "Context.h"
Classes
class OctreePost
Typedefs
typedef std::set< std::pair< bool, std::pair< int, int > > > infoset
Functions
static double GetAveEdgeLength (std::vector< MVertex * > &elem_verts)
template<class T >
static void addExtrudeNormals (std::vector< T * > &elements, int invert, OctreePost *octree, bool gouraud, int index, bool skipScaleCalc)
template<class T >
static void addExtrudeNormals (std::set< T * > &entities, std::map< int, infoset > &infos, std::map< int, bool > &skipScaleCalcMap)
static void checkDepends (GModel *m, GFace *f, std::set< GFace * > &dep)
static unsigned int FixErasedExtrScaleFlags (GModel *m, std::map< int, bool > &faceSkipScaleCalc, std::map< int, bool > &edgeSkipScaleCalc)
int Mesh2DWithBoundaryLayers (GModel *m)
Typedef Documentation
infoset
typedef std::set<std::pair<bool, std::pair<int, int> > > infoset
Definition at line 121 of file BoundaryLayers.cpp.
Function Documentation
addExtrudeNormals() [1/2]
template<class T > static void addExtrudeNormals (std::set< T * > & entities, std::map< int, infoset > & infos, std::map< int, bool > & skipScaleCalcMap) static
Definition at line 130 of file BoundaryLayers.cpp.
addExtrudeNormals() [2/2]
template<class T > static void addExtrudeNormals (std::vector< T * > & elements, int invert, OctreePost * octree, bool gouraud, int index, bool skipScaleCalc) static
Definition at line 41 of file BoundaryLayers.cpp.
Referenced by addExtrudeNormals(), and Mesh2DWithBoundaryLayers().
checkDepends()
static void checkDepends (GModel * m, GFace * f, std::set< GFace * > & dep) static
Definition at line 243 of file BoundaryLayers.cpp.
Referenced by Mesh2DWithBoundaryLayers().
FixErasedExtrScaleFlags()
static unsigned int FixErasedExtrScaleFlags (GModel * m, std::map< int, bool > & faceSkipScaleCalc, std::map< int, bool > & edgeSkipScaleCalc) static
Definition at line 258 of file BoundaryLayers.cpp.
Referenced by Mesh2DWithBoundaryLayers().
GetAveEdgeLength()
static double GetAveEdgeLength (std::vector< MVertex * > & elem_verts) static
Definition at line 28 of file BoundaryLayers.cpp.
Referenced by addExtrudeNormals().
Mesh2DWithBoundaryLayers()
int Mesh2DWithBoundaryLayers (GModel * m)
Definition at line 304 of file BoundaryLayers.cpp.
Referenced by Mesh2D().