gmsh-TingyuanDoc: src/graphics/Camera.h File Reference
Camera.h File Reference
Classes
class XYZ
class Quaternion
class Camera
class mouseAndKeyboard
Functions
double length (XYZ &p)
void normalize (XYZ &p)
void rotate (const Quaternion &omega, XYZ axe)
XYZ operator* (const double &a, const XYZ &T)
XYZ operator+ (const XYZ &L, const XYZ &R)
XYZ operator- (const XYZ &L, const XYZ &R)
XYZ operator- (const XYZ &R)
double length (Quaternion &quat)
void normalize (Quaternion &quat)
Quaternion conjugate (Quaternion quat)
Quaternion mult (const Quaternion &A, const Quaternion &B)
Quaternion operator* (const Quaternion &A, const Quaternion &B)
Function Documentation
conjugate()
Quaternion conjugate (Quaternion quat)
Definition at line 474 of file Camera.cpp.
Referenced by Camera::move_and_look(), rotate(), and Camera::rotate().
length() [1/2]
double length (Quaternion & quat)
Definition at line 346 of file Camera.cpp.
Referenced by onelab::remoteNetworkClient::_get(), VertexArray::decodeHeader(), drawContext::drawArrow3d(), drawContext::drawCylinder(), drawContext::drawPlaneInBoundingBox(), drawContext::drawTaperedCylinder(), drawContext::drawVector(), emptyFieldBDF(), fillPointCloud(), PView::fillVertexArray(), VertexArray::fromChar(), meshGEdgeProcessing(), normalize(), F_Transfinite::operator()(), GmshSocket::SendMessage(), setLcs(), and onelab::remoteNetworkClient::waitOnSubClients().
length() [2/2]
double length (XYZ & p)
Definition at line 351 of file Camera.cpp.
mult()
Quaternion mult (const Quaternion & A, const Quaternion & B)
Definition at line 459 of file Camera.cpp.
Referenced by PViewDataGModel::addData(), GMSH_WarpPlugin::execute(), stepData< Real >::getData(), MElement::getJacobian(), gmshViewGetModelData(), tetgenmesh::lu_decmp(), operator*(), SPoint2::operator*(), SPoint3::operator*(), SPoint2::operator*=(), SPoint3::operator*=(), PViewDataGModel::readMSH(), rotate(), ScalarToAnyFunctionSpace< SVector3 >::ScalarToAnyFunctionSpace(), OctreePost::searchScalar(), OctreePost::searchTensor(), OctreePost::searchVector(), PViewDataList::writeMSH(), and PViewDataGModel::writeMSH().
normalize() [1/2]
void normalize (Quaternion & quat)
Definition at line 370 of file Camera.cpp.
Referenced by discreteFace::_computeSTLNormals(), addExtrudeNormals(), Camera::move_and_look(), Camera::rotate(), and Camera::update().
normalize() [2/2]
void normalize (XYZ & p)
Definition at line 379 of file Camera.cpp.
operator*() [1/2]
XYZ operator* (const double & a, const XYZ & T)
Definition at line 412 of file Camera.cpp.
operator*() [2/2]
Quaternion operator* (const Quaternion & A, const Quaternion & B)
Definition at line 469 of file Camera.cpp.
operator+()
XYZ operator+ (const XYZ & L, const XYZ & R)
Definition at line 421 of file Camera.cpp.
operator-() [1/2]
XYZ operator- (const XYZ & L, const XYZ & R)
Definition at line 429 of file Camera.cpp.
operator-() [2/2]
XYZ operator- (const XYZ & R)
Definition at line 437 of file Camera.cpp.
rotate()
void rotate (const Quaternion & omega, XYZ axe)
Definition at line 398 of file Camera.cpp.