gmsh-TingyuanDoc: src/post/ColorTable.h File Reference
ColorTable.h File Reference
#include <stdio.h>
#include <vector>
#include <string>
Classes
struct GmshColorTable
Macros
#define COLORTABLE_NBMAX_PARAM 10
#define COLORTABLE_NBMAX_COLOR 1024
#define COLORTABLE_RGB 1
#define COLORTABLE_HSV 2
#define COLORTABLE_NUMBER 0
#define COLORTABLE_INVERT 1
#define COLORTABLE_SWAP 2
#define COLORTABLE_ROTATION 3
#define COLORTABLE_MODE 4
#define COLORTABLE_CURVATURE 0
#define COLORTABLE_BIAS 1
#define COLORTABLE_ALPHA 2
#define COLORTABLE_BETA 3
#define COLORTABLE_ALPHAPOW 4
Functions
void ColorTable_InitParam (int number, GmshColorTable *ct)
void ColorTable_Recompute (GmshColorTable *ct)
void ColorTable_Copy (GmshColorTable *ct)
void ColorTable_Paste (GmshColorTable *ct)
void ColorTable_Print (GmshColorTable *ct, FILE *fp, std::vector< std::string > *vec=nullptr)
int ColorTable_IsAlpha (GmshColorTable *ct)
int ColorTable_Diff (GmshColorTable *ct1, GmshColorTable *ct2)
void RGB_to_HSV (double R, double G, double B, double *H, double *S, double *V)
void HSV_to_RGB (double H, double S, double V, double *R, double *G, double *B)
Macro Definition Documentation
COLORTABLE_ALPHA
#define COLORTABLE_ALPHA 2
Definition at line 41 of file ColorTable.h.
COLORTABLE_ALPHAPOW
#define COLORTABLE_ALPHAPOW 4
Definition at line 43 of file ColorTable.h.
COLORTABLE_BETA
#define COLORTABLE_BETA 3
Definition at line 42 of file ColorTable.h.
COLORTABLE_BIAS
#define COLORTABLE_BIAS 1
Definition at line 40 of file ColorTable.h.
COLORTABLE_CURVATURE
#define COLORTABLE_CURVATURE 0
Definition at line 39 of file ColorTable.h.
COLORTABLE_HSV
#define COLORTABLE_HSV 2
Definition at line 27 of file ColorTable.h.
COLORTABLE_INVERT
#define COLORTABLE_INVERT 1
Definition at line 32 of file ColorTable.h.
COLORTABLE_MODE
#define COLORTABLE_MODE 4
Definition at line 35 of file ColorTable.h.
COLORTABLE_NBMAX_COLOR
#define COLORTABLE_NBMAX_COLOR 1024
Definition at line 15 of file ColorTable.h.
COLORTABLE_NBMAX_PARAM
#define COLORTABLE_NBMAX_PARAM 10
Definition at line 14 of file ColorTable.h.
COLORTABLE_NUMBER
#define COLORTABLE_NUMBER 0
Definition at line 31 of file ColorTable.h.
COLORTABLE_RGB
#define COLORTABLE_RGB 1
Definition at line 26 of file ColorTable.h.
COLORTABLE_ROTATION
#define COLORTABLE_ROTATION 3
Definition at line 34 of file ColorTable.h.
COLORTABLE_SWAP
#define COLORTABLE_SWAP 2
Definition at line 33 of file ColorTable.h.
Function Documentation
ColorTable_Copy()
void ColorTable_Copy (GmshColorTable * ct)
Definition at line 1055 of file ColorTable.cpp.
ColorTable_Diff()
int ColorTable_Diff (GmshColorTable * ct1, GmshColorTable * ct2)
Definition at line 1071 of file ColorTable.cpp.
Referenced by PrintColorTable().
ColorTable_InitParam()
void ColorTable_InitParam (int number, GmshColorTable * ct)
Definition at line 22 of file ColorTable.cpp.
Referenced by PrintColorTable(), and PViewOptions::PViewOptions().
ColorTable_IsAlpha()
int ColorTable_IsAlpha (GmshColorTable * ct)
Definition at line 1112 of file ColorTable.cpp.
Referenced by drawPView::operator()().
ColorTable_Paste()
void ColorTable_Paste (GmshColorTable * ct)
Definition at line 1063 of file ColorTable.cpp.
ColorTable_Print()
void ColorTable_Print (GmshColorTable * ct, FILE * fp, std::vector< std::string > * vec = nullptr)
Definition at line 1079 of file ColorTable.cpp.
Referenced by PrintColorTable().
ColorTable_Recompute()
void ColorTable_Recompute (GmshColorTable * ct)
Definition at line 724 of file ColorTable.cpp.
Referenced by opt_view_colormap_alpha(), opt_view_colormap_alpha_power(), opt_view_colormap_beta(), opt_view_colormap_bias(), opt_view_colormap_curvature(), opt_view_colormap_invert(), opt_view_colormap_number(), opt_view_colormap_rotation(), opt_view_colormap_swap(), PrintColorTable(), and PViewOptions::PViewOptions().
HSV_to_RGB()
void HSV_to_RGB (double H, double S, double V, double * R, double * G, double * B)
Definition at line 1124 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
RGB_to_HSV()
void RGB_to_HSV (double R, double G, double B, double * H, double * S, double * V)
Definition at line 1173 of file ColorTable.cpp.