gmsh-TingyuanDoc: src/post/ColorTable.cpp File Reference
ColorTable.cpp File Reference
#include <string.h>
#include <algorithm>
#include "GmshMessage.h"
#include "ColorTable.h"
#include "Context.h"
#include "Numeric.h"
Functions
void ColorTable_InitParam (int number, GmshColorTable *ct)
static double gray (double s)
static double hot_r (double s)
static double hot_g (double s)
static double hot_b (double s)
static double cubic (double a, double b, double c, double d, double x)
void ColorTable_Recompute (GmshColorTable *ct)
void ColorTable_Copy (GmshColorTable *ct)
void ColorTable_Paste (GmshColorTable *ct)
int ColorTable_Diff (GmshColorTable *ct1, GmshColorTable *ct2)
void ColorTable_Print (GmshColorTable *ct, FILE *fp, std::vector< std::string > *vec)
int ColorTable_IsAlpha (GmshColorTable *ct)
void HSV_to_RGB (double H, double S, double V, double *R, double *G, double *B)
void RGB_to_HSV (double R, double G, double B, double *H, double *S, double *V)
Variables
static double _magma_data [][3]
static double _inferno_data [][3]
static double _plasma_data [][3]
static double _viridis_data [][3]
static double _turbo_data [][3]
static GmshColorTable clip
Function Documentation
ColorTable_Copy()
void ColorTable_Copy (GmshColorTable * ct)
Definition at line 1055 of file ColorTable.cpp.
ColorTable_Diff()
int ColorTable_Diff (GmshColorTable * ct1, GmshColorTable * ct2)
Definition at line 1071 of file ColorTable.cpp.
Referenced by PrintColorTable().
ColorTable_InitParam()
void ColorTable_InitParam (int number, GmshColorTable * ct)
Definition at line 22 of file ColorTable.cpp.
Referenced by PrintColorTable(), and PViewOptions::PViewOptions().
ColorTable_IsAlpha()
int ColorTable_IsAlpha (GmshColorTable * ct)
Definition at line 1112 of file ColorTable.cpp.
Referenced by drawPView::operator()().
ColorTable_Paste()
void ColorTable_Paste (GmshColorTable * ct)
Definition at line 1063 of file ColorTable.cpp.
ColorTable_Print()
void ColorTable_Print (GmshColorTable * ct, FILE * fp, std::vector< std::string > * vec)
Definition at line 1079 of file ColorTable.cpp.
Referenced by PrintColorTable().
ColorTable_Recompute()
void ColorTable_Recompute (GmshColorTable * ct)
Definition at line 724 of file ColorTable.cpp.
Referenced by opt_view_colormap_alpha(), opt_view_colormap_alpha_power(), opt_view_colormap_beta(), opt_view_colormap_bias(), opt_view_colormap_curvature(), opt_view_colormap_invert(), opt_view_colormap_number(), opt_view_colormap_rotation(), opt_view_colormap_swap(), PrintColorTable(), and PViewOptions::PViewOptions().
cubic()
static double cubic (double a, double b, double c, double d, double x) static
Definition at line 51 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
gray()
static double gray (double s) static
Definition at line 34 of file ColorTable.cpp.
Referenced by ColorTable_Recompute(), gl2psPrintPDFPixmap(), gl2psPrintPDFPixmapStreamData(), gl2psPrintPDFShader(), and gl2psPrintPDFShaderStreamData().
hot_b()
static double hot_b (double s) static
Definition at line 46 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
hot_g()
static double hot_g (double s) static
Definition at line 41 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
hot_r()
static double hot_r (double s) static
Definition at line 36 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
HSV_to_RGB()
void HSV_to_RGB (double H, double S, double V, double * R, double * G, double * B)
Definition at line 1124 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
RGB_to_HSV()
void RGB_to_HSV (double R, double G, double B, double * H, double * S, double * V)
Definition at line 1173 of file ColorTable.cpp.
Variable Documentation
_inferno_data
double _inferno_data[][3] static
Definition at line 200 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
_magma_data
double _magma_data[][3] static
Definition at line 70 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
_plasma_data
double _plasma_data[][3] static
Definition at line 330 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
_turbo_data
double _turbo_data[][3] static
Definition at line 594 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
_viridis_data
double _viridis_data[][3] static
Definition at line 460 of file ColorTable.cpp.
Referenced by ColorTable_Recompute().
clip
GmshColorTable clip static
Definition at line 1053 of file ColorTable.cpp.
Referenced by initMeshGRegion::_estimateIfClipped(), initPView::_estimateIfClipped(), ColorTable_Copy(), ColorTable_Paste(), evalClipPlane(), intersectClipPlane(), and isElementVisible().