gmsh-TingyuanDoc: src/common/CommandLine.cpp File Reference
CommandLine.cpp File Reference
#include <string>
#include <string.h>
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include "GmshConfig.h"
#include "GmshDefines.h"
#include "GmshVersion.h"
#include "GmshMessage.h"
#include "OpenFile.h"
#include "CommandLine.h"
#include "Context.h"
#include "Options.h"
#include "GModel.h"
#include "CreateFile.h"
#include "OS.h"
#include "GmshGlobal.h"
#include "StringUtils.h"
Functions
int GetGmshMajorVersion ()
int GetGmshMinorVersion ()
int GetGmshPatchVersion ()
const char * GetGmshExtraVersion ()
const char * GetGmshVersion ()
const char * GetGmshBuildDate ()
const char * GetGmshBuildHost ()
const char * GetGmshPackager ()
const char * GetGmshBuildOS ()
const char * GetGmshShortLicense ()
const char * GetGmshBuildOptions ()
std::vector< std::pair< std::string, std::string > > GetUsage ()
std::vector< std::pair< std::string, std::string > > GetShortcutsUsage (const std::string &ctrl)
std::vector< std::pair< std::string, std::string > > GetMouseUsage ()
void PrintUsage (const std::string &name)
std::vector< std::string > GetBuildInfo ()
void PrintBuildInfo ()
static bool GetGeometryOption (const std::vector< std::string > &argv, std::size_t &i, bool exitOnError)
static bool GetMeshOption (const std::vector< std::string > &argv, std::size_t &i, bool exitOnError)
static bool GetPostProcessingOption (const std::vector< std::string > &argv, std::size_t &i, bool exitOnError)
static bool GetSolverOption (const std::vector< std::string > &argv, std::size_t &i, bool exitOnError)
static bool GetOtherOption (const std::vector< std::string > &argv, std::size_t &i, bool exitOnError)
void GetOptions (bool readConfigFiles, bool exitOnError)
Function Documentation
GetBuildInfo()
std::vector<std::string> GetBuildInfo ()
Definition at line 364 of file CommandLine.cpp.
Referenced by opt_general_build_info(), and PrintBuildInfo().
GetGeometryOption()
static bool GetGeometryOption (const std::vector< std::string > & argv, std::size_t & i, bool exitOnError) static
Definition at line 422 of file CommandLine.cpp.
Referenced by GetOptions().
GetGmshBuildDate()
const char* GetGmshBuildDate ()
Definition at line 61 of file CommandLine.cpp.
GetGmshBuildHost()
const char* GetGmshBuildHost ()
Definition at line 62 of file CommandLine.cpp.
GetGmshBuildOptions()
const char* GetGmshBuildOptions ()
Definition at line 66 of file CommandLine.cpp.
GetGmshBuildOS()
const char* GetGmshBuildOS ()
Definition at line 64 of file CommandLine.cpp.
GetGmshExtraVersion()
const char* GetGmshExtraVersion ()
Definition at line 59 of file CommandLine.cpp.
GetGmshMajorVersion()
int GetGmshMajorVersion ()
Definition at line 56 of file CommandLine.cpp.
GetGmshMinorVersion()
int GetGmshMinorVersion ()
Definition at line 57 of file CommandLine.cpp.
GetGmshPackager()
const char* GetGmshPackager ()
Definition at line 63 of file CommandLine.cpp.
GetGmshPatchVersion()
int GetGmshPatchVersion ()
Definition at line 58 of file CommandLine.cpp.
GetGmshShortLicense()
const char* GetGmshShortLicense ()
Definition at line 65 of file CommandLine.cpp.
GetGmshVersion()
const char* GetGmshVersion ()
Definition at line 60 of file CommandLine.cpp.
GetMeshOption()
static bool GetMeshOption (const std::vector< std::string > & argv, std::size_t & i, bool exitOnError) static
Definition at line 464 of file CommandLine.cpp.
Referenced by GetOptions().
GetMouseUsage()
std::vector<std::pair<std::string, std::string> > GetMouseUsage ()
Definition at line 330 of file CommandLine.cpp.
Referenced by PrintOptionsDoc().
GetOptions()
void GetOptions (bool readConfigFiles, bool exitOnError)
Definition at line 1478 of file CommandLine.cpp.
Referenced by GmshInitialize().
GetOtherOption()
static bool GetOtherOption (const std::vector< std::string > & argv, std::size_t & i, bool exitOnError) static
Definition at line 1160 of file CommandLine.cpp.
Referenced by GetOptions().
GetPostProcessingOption()
static bool GetPostProcessingOption (const std::vector< std::string > & argv, std::size_t & i, bool exitOnError) static
Definition at line 1059 of file CommandLine.cpp.
Referenced by GetOptions().
GetShortcutsUsage()
std::vector<std::pair<std::string, std::string> > GetShortcutsUsage (const std::string & ctrl)
Definition at line 219 of file CommandLine.cpp.
Referenced by PrintOptionsDoc().
GetSolverOption()
static bool GetSolverOption (const std::vector< std::string > & argv, std::size_t & i, bool exitOnError) static
Definition at line 1092 of file CommandLine.cpp.
Referenced by GetOptions().
GetUsage()
std::vector<std::pair<std::string, std::string> > GetUsage ()
Definition at line 68 of file CommandLine.cpp.
Referenced by PrintOptionsDoc(), and PrintUsage().
PrintBuildInfo()
void PrintBuildInfo ()
Definition at line 416 of file CommandLine.cpp.
Referenced by GetOtherOption().
PrintUsage()
void PrintUsage (const std::string & name)
Definition at line 350 of file CommandLine.cpp.
Referenced by GetOptions(), GetOtherOption(), and GmshMainBatch().