gmsh-TingyuanDoc: src/numeric/ConjugateGradients.cpp File Reference
ConjugateGradients.cpp File Reference
#include <algorithm>
#include <math.h>
#include "GmshMessage.h"
#include "ConjugateGradients.h"
Functions
static double _norm (std::vector< double > &x)
static void scale (std::vector< double > &x, double s)
static void gmshLineSearch (void(*func)(std::vector< double > &x, double &Obj, bool needGrad, std::vector< double > &gradObj, void *), void *data, std::vector< double > &x, std::vector< double > &p, std::vector< double > &g, double &f, double stpmax, int &check)
double GradientDescent (void(*func)(std::vector< double > &x, double &Obj, bool needGrad, std::vector< double > &gradObj, void *), std::vector< double > &x, void *data)
Function Documentation
_norm()
static double _norm (std::vector< double > & x) static
Definition at line 15 of file ConjugateGradients.cpp.
Referenced by gmshLineSearch().
gmshLineSearch()
static void gmshLineSearch (void(*)(std::vector< double > &x, double &Obj, bool needGrad, std::vector< double > &gradObj, void *) func, void * data, std::vector< double > & x, std::vector< double > & p, std::vector< double > & g, double & f, double stpmax, int & check) static
Definition at line 26 of file ConjugateGradients.cpp.
Referenced by GradientDescent().
GradientDescent()
double GradientDescent (void(*)(std::vector< double > &x, double &Obj, bool needGrad, std::vector< double > &gradObj, void *) func, std::vector< double > & x, void * data)
Definition at line 120 of file ConjugateGradients.cpp.
scale()
static void scale (std::vector< double > & x, double s) static
Definition at line 21 of file ConjugateGradients.cpp.
Referenced by drawEllipseArray(), drawVectorArray(), GMSH_EigenvectorsPlugin::execute(), ExtrudeParams::Extrude(), JacobianBasis::getJacobianGeneral(), gmshGenerateOrderedPoints(), gmshGeneratePointsPyramidGeneral(), gmshLineSearch(), MElement::idealJacRange(), meshMetric::scaleMetric(), and PView::writeX3D().