gmsh-TingyuanDoc: src/common/CreateFile.h File Reference
CreateFile.h File Reference
#include <string>
Functions
int GetFileFormatFromExtension (const std::string &fileName, double *version=nullptr)
int GuessFileFormatFromFileName (const std::string &fileName, double *version=nullptr)
std::string GetDefaultFileExtension (int format, bool onlyMeshFormats=false)
std::string GetDefaultFileName (int format)
std::string GetKnownFileFormats (bool onlyMeshFormats=false)
void CreateOutputFile (const std::string &fileName, int format, bool status=true)
Function Documentation
CreateOutputFile()
void CreateOutputFile (const std::string & fileName, int format, bool status = true)
Definition at line 290 of file CreateFile.cpp.
Referenced by CreateOutputFile(), GetMeshOption(), GmshBatch(), GmshWriteFile(), and GModel::save().
GetDefaultFileExtension()
std::string GetDefaultFileExtension (int format, bool onlyMeshFormats = false)
Definition at line 107 of file CreateFile.cpp.
Referenced by GetDefaultFileName(), and GetKnownFileFormats().
GetDefaultFileName()
std::string GetDefaultFileName (int format)
Definition at line 165 of file CreateFile.cpp.
Referenced by CreateOutputFile(), and GmshBatch().
GetFileFormatFromExtension()
int GetFileFormatFromExtension (const std::string & fileName, double * version = nullptr)
Definition at line 34 of file CreateFile.cpp.
Referenced by GetMeshOption(), and GuessFileFormatFromFileName().
GetKnownFileFormats()
std::string GetKnownFileFormats (bool onlyMeshFormats = false)
Definition at line 173 of file CreateFile.cpp.
Referenced by GetUsage().
GuessFileFormatFromFileName()
int GuessFileFormatFromFileName (const std::string & fileName, double * version = nullptr)
Definition at line 101 of file CreateFile.cpp.
Referenced by CreateOutputFile().