gmsh-TingyuanDoc: src/common/CreateFile.cpp File Reference
CreateFile.cpp File Reference
#include "GmshConfig.h"
#include "GmshMessage.h"
#include "GModel.h"
#include "GmshDefines.h"
#include "StringUtils.h"
#include "Context.h"
#include "Options.h"
#include "OpenFile.h"
#include "CreateFile.h"
#include "OS.h"
Functions
int GetFileFormatFromExtension (const std::string &ext, double *version)
int GuessFileFormatFromFileName (const std::string &fileName, double *version)
std::string GetDefaultFileExtension (int format, bool onlyMeshFormats)
std::string GetDefaultFileName (int format)
std::string GetKnownFileFormats (bool onlyMeshFormats)
static void ChangePrintParameter (int frame)
void CreateOutputFile (const std::string &fileName, int format, bool status)
Function Documentation
ChangePrintParameter()
static void ChangePrintParameter (int frame) static
Definition at line 277 of file CreateFile.cpp.
Referenced by CreateOutputFile().
CreateOutputFile()
void CreateOutputFile (const std::string & fileName, int format, bool status)
Definition at line 290 of file CreateFile.cpp.
Referenced by CreateOutputFile(), GetMeshOption(), GmshBatch(), GmshWriteFile(), and GModel::save().
GetDefaultFileExtension()
std::string GetDefaultFileExtension (int format, bool onlyMeshFormats)
Definition at line 107 of file CreateFile.cpp.
Referenced by GetDefaultFileName(), and GetKnownFileFormats().
GetDefaultFileName()
std::string GetDefaultFileName (int format)
Definition at line 165 of file CreateFile.cpp.
Referenced by CreateOutputFile(), and GmshBatch().
GetFileFormatFromExtension()
int GetFileFormatFromExtension (const std::string & ext, double * version)
Definition at line 34 of file CreateFile.cpp.
Referenced by GetMeshOption(), and GuessFileFormatFromFileName().
GetKnownFileFormats()
std::string GetKnownFileFormats (bool onlyMeshFormats)
Definition at line 173 of file CreateFile.cpp.
Referenced by GetUsage().
GuessFileFormatFromFileName()
int GuessFileFormatFromFileName (const std::string & fileName, double * version)
Definition at line 101 of file CreateFile.cpp.
Referenced by CreateOutputFile().