gmsh-TingyuanDoc: src/geo/GEdge.cpp File Reference
GEdge.cpp File Reference
#include <sstream>
#include <algorithm>
#include <numeric>
#include "GmshConfig.h"
#include "GmshDefines.h"
#include "GmshMessage.h"
#include "GModel.h"
#include "GEdge.h"
#include "GFace.h"
#include "MLine.h"
#include "GaussLegendre1D.h"
#include "Context.h"
#include "closestPoint.h"
#include "discreteEdge.h"
#include "ExtrudeParams.h"
Classes
struct sortedPoint
struct vindexsort
Functions
double goldenSectionSearch (const GEdge *ge, const SPoint3 &q, double x1, double x2, double x3, double tau)
static double sqDistPointSegment (const SPoint3 &p, const SPoint3 &s0, const SPoint3 &s1)
static void _discretize (double tol, GEdge *edge, std::vector< sortedPoint > &upts, int pos0)
Variables
const double GOLDEN = (1.0 + std::sqrt(5.0)) / 2.0
const double GOLDEN2 = 2.0 - GOLDEN
Function Documentation
_discretize()
static void _discretize (double tol, GEdge * edge, std::vector< sortedPoint > & upts, int pos0) static
Definition at line 755 of file GEdge.cpp.
Referenced by GEdge::discretize().
goldenSectionSearch()
double goldenSectionSearch (const GEdge * ge, const SPoint3 & q, double x1, double x2, double x3, double tau)
Definition at line 532 of file GEdge.cpp.
Referenced by GEdge::closestPoint().
sqDistPointSegment()
static double sqDistPointSegment (const SPoint3 & p, const SPoint3 & s0, const SPoint3 & s1) static
Definition at line 743 of file GEdge.cpp.
Referenced by _discretize().
Variable Documentation
GOLDEN
const double GOLDEN = (1.0 + std::sqrt(5.0)) / 2.0
Definition at line 526 of file GEdge.cpp.
GOLDEN2
const double GOLDEN2 = 2.0 - GOLDEN
Definition at line 527 of file GEdge.cpp.
Referenced by goldenSectionSearch().