gmsh-TingyuanDoc: src/geo/GEdgeLoop.cpp File Reference
GEdgeLoop.cpp File Reference
#include <algorithm>
#include <functional>
#include "GEdgeLoop.h"
#include "GmshMessage.h"
Functions
int countInList (std::list< GEdge * > &wire, GEdge *ge)
GEdgeSigned nextOne (GEdgeSigned *thisOne, std::list< GEdge * > &wire)
static void loopTheLoop (std::list< GEdge * > &wire, std::list< GEdgeSigned > &loop, GEdge **degeneratedToInsert)
Function Documentation
countInList()
int countInList (std::list< GEdge * > & wire, GEdge * ge)
Definition at line 20 of file GEdgeLoop.cpp.
Referenced by nextOne().
loopTheLoop()
static void loopTheLoop (std::list< GEdge * > & wire, std::list< GEdgeSigned > & loop, GEdge ** degeneratedToInsert) static
Definition at line 112 of file GEdgeLoop.cpp.
Referenced by GEdgeLoop::recompute().
nextOne()
GEdgeSigned nextOne (GEdgeSigned * thisOne, std::list< GEdge * > & wire)
Definition at line 25 of file GEdgeLoop.cpp.
Referenced by loopTheLoop().