gmsh-TingyuanDoc: src/geo/GModelIO_VRML.cpp File Reference
GModelIO_VRML.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include "GModel.h"
#include "OS.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
Functions
static int skipUntil (FILE *fp, const char *key)
static int readVerticesVRML (FILE *fp, std::vector< MVertex * > &vertexVector, std::vector< MVertex * > &allVertexVector)
static int readElementsVRML (FILE *fp, std::vector< MVertex * > &vertexVector, int region, std::map< int, std::vector< MElement * > > elements[3], bool strips=false)
Function Documentation
readElementsVRML()
static int readElementsVRML (FILE * fp, std::vector< MVertex * > & vertexVector, int region, std::map< int, std::vector< MElement * > > elements[3], bool strips = false) static
Definition at line 43 of file GModelIO_VRML.cpp.
Referenced by GModel::readVRML().
readVerticesVRML()
static int readVerticesVRML (FILE * fp, std::vector< MVertex * > & vertexVector, std::vector< MVertex * > & allVertexVector) static
Definition at line 29 of file GModelIO_VRML.cpp.
Referenced by GModel::readVRML().
skipUntil()
static int skipUntil (FILE * fp, const char * key) static
Definition at line 14 of file GModelIO_VRML.cpp.
Referenced by GModel::readVRML().