gmsh-TingyuanDoc: src/geo/GModelIO_KEY.cpp File Reference
GModelIO_KEY.cpp File Reference
#include "GModel.h"
#include "OS.h"
#include "MPoint.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
Functions
static std::string physicalName (GModel *m, int dim, int num)
static int partID (int dim, int num)
template<class T >
static void writeElementsKEY (FILE *fp, GEntity *ge, std::vector< T * > &elements, bool saveAll)
Function Documentation
partID()
static int partID (int dim, int num) static
Definition at line 34 of file GModelIO_KEY.cpp.
Referenced by writeElementsKEY().
physicalName()
static std::string physicalName (GModel * m, int dim, int num) static
Definition at line 17 of file GModelIO_KEY.cpp.
Referenced by writeElementsKEY(), and GModel::writeKEY().
writeElementsKEY()
template<class T > static void writeElementsKEY (FILE * fp, GEntity * ge, std::vector< T * > & elements, bool saveAll) static
Definition at line 37 of file GModelIO_KEY.cpp.
Referenced by GModel::writeKEY().