gmsh-TingyuanDoc: src/geo/GModelVertexArrays.cpp File Reference
GModelVertexArrays.cpp File Reference
#include <cmath>
#include "GmshMessage.h"
#include "GmshDefines.h"
#include "GModel.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
#include "MTrihedron.h"
#include "MElementCut.h"
#include "Context.h"
#include "VertexArray.h"
#include "SmoothData.h"
Classes
class initMeshGEdge
class initSmoothNormalsGFace
class initMeshGFace
class initMeshGRegion
Functions
unsigned int getColorByEntity (GEntity *e)
static unsigned int getColorByElement (MElement *ele)
static double evalClipPlane (int clip, double x, double y, double z)
static double intersectClipPlane (int clip, MElement *ele)
bool isElementVisible (MElement *ele)
template<class T >
static bool areAllElementsVisible (std::vector< T * > &elements)
template<class T >
static bool areSomeElementsCurved (std::vector< T * > &elements)
template<class T >
static void addSmoothNormals (GEntity *e, std::vector< T * > &elements)
template<class T >
static void addElementsInArrays (GEntity *e, std::vector< T * > &elements, bool edges, bool faces)
Variables
static const double curvedRepTol = 1.e-5
Function Documentation
addElementsInArrays()
template<class T > static void addElementsInArrays (GEntity * e, std::vector< T * > & elements, bool edges, bool faces) static
Definition at line 189 of file GModelVertexArrays.cpp.
Referenced by initMeshGEdge::operator()(), initMeshGFace::operator()(), and initMeshGRegion::operator()().
addSmoothNormals()
template<class T > static void addSmoothNormals (GEntity * e, std::vector< T * > & elements) static
Definition at line 163 of file GModelVertexArrays.cpp.
Referenced by initSmoothNormalsGFace::operator()().
areAllElementsVisible()
template<class T > static bool areAllElementsVisible (std::vector< T * > & elements) static
Definition at line 148 of file GModelVertexArrays.cpp.
Referenced by initMeshGEdge::operator()(), initMeshGFace::operator()(), and initMeshGRegion::operator()().
areSomeElementsCurved()
template<class T > static bool areSomeElementsCurved (std::vector< T * > & elements) static
Definition at line 155 of file GModelVertexArrays.cpp.
Referenced by initMeshGEdge::_estimateNumLines(), initMeshGFace::operator()(), and initMeshGRegion::operator()().
evalClipPlane()
static double evalClipPlane (int clip, double x, double y, double z) static
Definition at line 81 of file GModelVertexArrays.cpp.
Referenced by intersectClipPlane().
getColorByElement()
static unsigned int getColorByElement (MElement * ele) static
Definition at line 46 of file GModelVertexArrays.cpp.
Referenced by addElementsInArrays().
getColorByEntity()
unsigned int getColorByEntity (GEntity * e)
Definition at line 25 of file GModelVertexArrays.cpp.
Referenced by drawArrays(), drawElementLabels(), drawVertexLabel(), drawVerticesPerElement(), drawVerticesPerEntity(), and getColorByElement().
intersectClipPlane()
static double intersectClipPlane (int clip, MElement * ele) static
Definition at line 89 of file GModelVertexArrays.cpp.
Referenced by isElementVisible().
isElementVisible()
bool isElementVisible (MElement * ele)
Definition at line 101 of file GModelVertexArrays.cpp.
Referenced by addElementsInArrays(), areAllElementsVisible(), drawBarycentricDual(), drawElementLabels(), drawGlyphs(), drawNormals(), drawTangents(), drawVerticesPerElement(), and drawVoronoiDual().
Variable Documentation
curvedRepTol
const double curvedRepTol = 1.e-5 static
Definition at line 23 of file GModelVertexArrays.cpp.
Referenced by addElementsInArrays(), and addSmoothNormals().