gmsh-TingyuanDoc: src/geo/GModelIO_BDF.cpp File Reference
GModelIO_BDF.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include "GModel.h"
#include "OS.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
Functions
static int getFormatBDF (char *buffer, int &keySize)
static double atofBDF (char *str)
static void copyChar (char *out, const char *in, int num)
static int readVertexBDF (FILE *fp, char *buffer, int keySize, int *num, double *x, double *y, double *z)
static bool emptyFieldBDF (char *field, int length)
static void readLineBDF (char *buffer, int format, std::vector< char * > &fields)
static int readElementBDF (FILE *fp, char *buffer, int keySize, int numVertices, int &num, int &region, std::vector< MVertex * > &vertices, std::map< int, MVertex * > &vertexMap)
Function Documentation
atofBDF()
static double atofBDF (char * str) static
Definition at line 39 of file GModelIO_BDF.cpp.
Referenced by readVertexBDF().
copyChar()
static void copyChar (char * out, const char * in, int num) static
Definition at line 64 of file GModelIO_BDF.cpp.
Referenced by readElementBDF(), and readVertexBDF().
emptyFieldBDF()
static bool emptyFieldBDF (char * field, int length) static
Definition at line 122 of file GModelIO_BDF.cpp.
Referenced by readLineBDF().
getFormatBDF()
static int getFormatBDF (char * buffer, int & keySize) static
Definition at line 18 of file GModelIO_BDF.cpp.
Referenced by readElementBDF(), and readVertexBDF().
readElementBDF()
static int readElementBDF (FILE * fp, char * buffer, int keySize, int numVertices, int & num, int & region, std::vector< MVertex * > & vertices, std::map< int, MVertex * > & vertexMap) static
Definition at line 149 of file GModelIO_BDF.cpp.
Referenced by GModel::readBDF().
readLineBDF()
static void readLineBDF (char * buffer, int format, std::vector< char * > & fields) static
Definition at line 131 of file GModelIO_BDF.cpp.
Referenced by readElementBDF().
readVertexBDF()
static int readVertexBDF (FILE * fp, char * buffer, int keySize, int * num, double * x, double * y, double * z) static
Definition at line 69 of file GModelIO_BDF.cpp.
Referenced by GModel::readBDF().