gmsh-TingyuanDoc: src/geo/GModelIO_INP.cpp File Reference
GModelIO_INP.cpp File Reference
#include "GModel.h"
#include "OS.h"
#include "MPoint.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
Functions
template<class T >
static void writeElementsINP (FILE *fp, GEntity *ge, std::vector< T * > &elements, bool saveAll)
static std::string physicalName (GModel *m, int dim, int num)
Function Documentation
physicalName()
static std::string physicalName (GModel * m, int dim, int num) static
Definition at line 35 of file GModelIO_INP.cpp.
Referenced by GModel::_readMSH4(), and GModel::writeINP().
writeElementsINP()
template<class T > static void writeElementsINP (FILE * fp, GEntity * ge, std::vector< T * > & elements, bool saveAll) static
Definition at line 18 of file GModelIO_INP.cpp.
Referenced by GModel::writeINP().