gmsh-TingyuanDoc: src/geo/GModelIO_X3D.cpp File Reference
GModelIO_X3D.cpp File Reference
#include <stdio.h>
#include <string>
#include <algorithm>
#include <sstream>
#include "GModel.h"
#include "OS.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MVertexRTree.h"
#include "discreteFace.h"
#include "StringUtils.h"
#include "Context.h"
Functions
static void writeX3dHeader (FILE *fp, std::vector< std::string > &metadata)
static void writeX3dTrailer (FILE *fp)
static void writeHTMLHeader (FILE *fp)
static void writeHTMLBody (FILE *fp, std::vector< std::string > &x3dfiles)
static void writeX3dFaces (FILE *fp, std::vector< GFace * > &faces, bool useIndexedSet, double scalingFactor, const std::string &name, bool useColor, std::vector< unsigned int > &colors)
static void writeX3dEdges (FILE *fp, std::vector< GEdge * > &edges, double scalingFactor, const std::string &name)
static std::string TagFileName (std::string const &name, int tag)
static std::string HtmlFileName (std::string const &name)
Function Documentation
HtmlFileName()
static std::string HtmlFileName (std::string const & name) static
Definition at line 466 of file GModelIO_X3D.cpp.
Referenced by GModel::writeX3D().
TagFileName()
static std::string TagFileName (std::string const & name, int tag) static
Definition at line 459 of file GModelIO_X3D.cpp.
Referenced by GModel::writeX3D().
writeHTMLBody()
static void writeHTMLBody (FILE * fp, std::vector< std::string > & x3dfiles) static
Definition at line 75 of file GModelIO_X3D.cpp.
Referenced by GModel::writeX3D().
writeHTMLHeader()
static void writeHTMLHeader (FILE * fp) static
Definition at line 47 of file GModelIO_X3D.cpp.
Referenced by GModel::writeX3D().
writeX3dEdges()
static void writeX3dEdges (FILE * fp, std::vector< GEdge * > & edges, double scalingFactor, const std::string & name) static
Definition at line 285 of file GModelIO_X3D.cpp.
Referenced by GModel::_writeX3dFile().
writeX3dFaces()
static void writeX3dFaces (FILE * fp, std::vector< GFace * > & faces, bool useIndexedSet, double scalingFactor, const std::string & name, bool useColor, std::vector< unsigned int > & colors) static
Definition at line 127 of file GModelIO_X3D.cpp.
Referenced by GModel::_writeX3dFile().
writeX3dHeader()
static void writeX3dHeader (FILE * fp, std::vector< std::string > & metadata) static
Definition at line 22 of file GModelIO_X3D.cpp.
Referenced by GModel::writeX3D().
writeX3dTrailer()
static void writeX3dTrailer (FILE * fp) static
Definition at line 41 of file GModelIO_X3D.cpp.
Referenced by GModel::writeX3D().