gmsh-TingyuanDoc: src/geo/GModelIO_RAD.cpp File Reference
GModelIO_RAD.cpp File Reference
#include "GModel.h"
#include "OS.h"
#include "MPoint.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
Functions
static std::string physicalName (GModel *m, int dim, int num)
static int partID (int dim, int num)
template<class T >
static void writeElementsRAD (FILE *fp, GEntity *ge, std::vector< T * > &elements, bool saveAll)
Function Documentation
partID()
static int partID (int dim, int num) static
Definition at line 35 of file GModelIO_RAD.cpp.
Referenced by writeElementsRAD().
physicalName()
static std::string physicalName (GModel * m, int dim, int num) static
Definition at line 18 of file GModelIO_RAD.cpp.
Referenced by writeElementsRAD(), and GModel::writeRAD().
writeElementsRAD()
template<class T > static void writeElementsRAD (FILE * fp, GEntity * ge, std::vector< T * > & elements, bool saveAll) static
Definition at line 38 of file GModelIO_RAD.cpp.
Referenced by GModel::writeRAD().