gmsh-TingyuanDoc: src/geo/GModelIO_GEO.cpp File Reference
GModelIO_GEO.cpp File Reference
#include <sstream>
#include <stdlib.h>
#include "GmshConfig.h"
#include "GmshMessage.h"
#include "GModel.h"
#include "GModelIO_GEO.h"
#include "Geo.h"
#include "GeoInterpolation.h"
#include "OS.h"
#include "OpenFile.h"
#include "Numeric.h"
#include "ListUtils.h"
#include "gmshVertex.h"
#include "gmshFace.h"
#include "gmshEdge.h"
#include "gmshRegion.h"
#include "Context.h"
#include "Parser.h"
Classes
struct VertexPtrLessThan
class writePhysicalGroupGEO
Functions
static bool SortCurvesConsecutive (const std::vector< Curve * > &e, std::vector< std::vector< Vertex * > > &vs)
bool sortEntities (const std::pair< int, int > &a, const std::pair< int, int > &b)
static bool skipRegion (GRegion *gr)
static bool skipFace (GFace *gf)
static bool skipEdge (GEdge *ge)
static bool skipVertex (GVertex *gv)
Function Documentation
skipEdge()
static bool skipEdge (GEdge * ge) static
Definition at line 1782 of file GModelIO_GEO.cpp.
Referenced by skipVertex(), GModel::writeGEO(), and GModel::writePY().
skipFace()
static bool skipFace (GFace * gf) static
Definition at line 1772 of file GModelIO_GEO.cpp.
Referenced by skipEdge(), GModel::writeGEO(), and GModel::writePY().
skipRegion()
static bool skipRegion (GRegion * gr) static
Definition at line 1766 of file GModelIO_GEO.cpp.
Referenced by skipFace(), GModel::writeGEO(), and GModel::writePY().
skipVertex()
static bool skipVertex (GVertex * gv) static
Definition at line 1792 of file GModelIO_GEO.cpp.
Referenced by GModel::writeGEO(), and GModel::writePY().
SortCurvesConsecutive()
static bool SortCurvesConsecutive (const std::vector< Curve * > & e, std::vector< std::vector< Vertex * > > & vs) static
Definition at line 429 of file GModelIO_GEO.cpp.
Referenced by GEO_Internals::addCurveLoops().
sortEntities()
bool sortEntities (const std::pair< int, int > & a, const std::pair< int, int > & b)
Definition at line 1362 of file GModelIO_GEO.cpp.
Referenced by GEO_Internals::synchronize().