gmsh-TingyuanDoc: src/geo/GModelCreateTopologyFromMesh.cpp File Reference
GModelCreateTopologyFromMesh.cpp File Reference
#include <stack>
#include <set>
#include <map>
#include <sstream>
#include "OS.h"
#include "GModel.h"
#include "discreteFace.h"
#include "discreteEdge.h"
#include "discreteVertex.h"
#include "MPoint.h"
#include "MVertex.h"
#include "MLine.h"
#include "MEdge.h"
#include "MFace.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
#include "Context.h"
Classes
class topoEdge
class topoFace
Typedefs
typedef std::map< MVertex *, std::set< GEdge * > > MVertexToGEdgesMap
typedef std::map< MVertex *, GVertex * > MVertexToGVertexMap
typedef std::map< GEdge *, std::set< GVertex * > > GEdgeToGVerticesMap
typedef std::map< std::set< GEdge * >, GVertex * > GEdgesToGVertexMap
typedef std::map< topoEdge, std::set< GFace * > > TEdgeToGFacesMap
typedef std::map< topoEdge, GEdge * > TEdgeToGEdgeMap
typedef std::map< GFace *, std::set< GEdge * > > GFaceToGEdgesMap
typedef std::map< std::set< GFace * >, GEdge * > GFacesToGEdgeMap
typedef std::map< topoFace, GFace * > TFaceToGFaceMap
typedef std::map< topoFace, std::pair< GRegion *, GRegion * > > TFaceToGRegionPairMap
typedef std::map< GRegion *, std::set< GFace * > > GRegionToGFacesMap
typedef std::set< std::pair< GRegion *, GRegion * > > GRegionPairSet
typedef std::map< std::pair< GRegion *, GRegion * >, GFace * > GRegionPairToGFaceMap
Functions
bool topoExists (GModel *gm)
std::vector< GEdge * > ensureSimplyConnectedEdge (GEdge *ge)
void assignFace (GFace *gf, std::set< MElement * > &_f)
void ensureManifoldFace (GFace *gf)
void ensureManifoldFaces (GModel *gm)
void createTopologyFromMesh1D (GModel *gm, int &num)
void createTopologyFromMesh2D (GModel *gm, int &num)
void createTopologyFromMesh3D (GModel *gm, int &num)
Typedef Documentation
GEdgesToGVertexMap
typedef std::map<std::set<GEdge *>, GVertex *> GEdgesToGVertexMap
Definition at line 209 of file GModelCreateTopologyFromMesh.cpp.
GEdgeToGVerticesMap
typedef std::map<GEdge *, std::set<GVertex *> > GEdgeToGVerticesMap
Definition at line 208 of file GModelCreateTopologyFromMesh.cpp.
GFacesToGEdgeMap
typedef std::map<std::set<GFace *>, GEdge *> GFacesToGEdgeMap
Definition at line 367 of file GModelCreateTopologyFromMesh.cpp.
GFaceToGEdgesMap
typedef std::map<GFace *, std::set<GEdge *> > GFaceToGEdgesMap
Definition at line 366 of file GModelCreateTopologyFromMesh.cpp.
GRegionPairSet
typedef std::set<std::pair<GRegion *, GRegion *> > GRegionPairSet
Definition at line 544 of file GModelCreateTopologyFromMesh.cpp.
GRegionPairToGFaceMap
typedef std::map<std::pair<GRegion *, GRegion *>, GFace *> GRegionPairToGFaceMap
Definition at line 546 of file GModelCreateTopologyFromMesh.cpp.
GRegionToGFacesMap
typedef std::map<GRegion *, std::set<GFace *> > GRegionToGFacesMap
Definition at line 543 of file GModelCreateTopologyFromMesh.cpp.
MVertexToGEdgesMap
typedef std::map<MVertex *, std::set<GEdge *> > MVertexToGEdgesMap
Definition at line 206 of file GModelCreateTopologyFromMesh.cpp.
MVertexToGVertexMap
typedef std::map<MVertex *, GVertex *> MVertexToGVertexMap
Definition at line 207 of file GModelCreateTopologyFromMesh.cpp.
TEdgeToGEdgeMap
typedef std::map<topoEdge, GEdge *> TEdgeToGEdgeMap
Definition at line 365 of file GModelCreateTopologyFromMesh.cpp.
TEdgeToGFacesMap
typedef std::map<topoEdge, std::set<GFace *> > TEdgeToGFacesMap
Definition at line 364 of file GModelCreateTopologyFromMesh.cpp.
TFaceToGFaceMap
typedef std::map<topoFace, GFace *> TFaceToGFaceMap
Definition at line 540 of file GModelCreateTopologyFromMesh.cpp.
TFaceToGRegionPairMap
typedef std::map<topoFace, std::pair<GRegion *, GRegion *> > TFaceToGRegionPairMap
Definition at line 542 of file GModelCreateTopologyFromMesh.cpp.
Function Documentation
assignFace()
void assignFace (GFace * gf, std::set< MElement * > & _f)
Definition at line 118 of file GModelCreateTopologyFromMesh.cpp.
Referenced by ensureManifoldFace().
createTopologyFromMesh1D()
void createTopologyFromMesh1D (GModel * gm, int & num)
Definition at line 211 of file GModelCreateTopologyFromMesh.cpp.
Referenced by GModel::createTopologyFromMesh().
createTopologyFromMesh2D()
void createTopologyFromMesh2D (GModel * gm, int & num)
Definition at line 369 of file GModelCreateTopologyFromMesh.cpp.
Referenced by GModel::createTopologyFromMesh().
createTopologyFromMesh3D()
void createTopologyFromMesh3D (GModel * gm, int & num)
Definition at line 548 of file GModelCreateTopologyFromMesh.cpp.
Referenced by GModel::createTopologyFromMesh().
ensureManifoldFace()
void ensureManifoldFace (GFace * gf)
Definition at line 130 of file GModelCreateTopologyFromMesh.cpp.
Referenced by ensureManifoldFaces().
ensureManifoldFaces()
void ensureManifoldFaces (GModel * gm)
Definition at line 199 of file GModelCreateTopologyFromMesh.cpp.
Referenced by GModel::createTopologyFromMesh().
ensureSimplyConnectedEdge()
std::vector<GEdge *> ensureSimplyConnectedEdge (GEdge * ge)
Definition at line 48 of file GModelCreateTopologyFromMesh.cpp.
Referenced by createTopologyFromMesh1D(), and createTopologyFromMesh2D().
topoExists()
bool topoExists (GModel * gm)
Definition at line 30 of file GModelCreateTopologyFromMesh.cpp.
Referenced by GModel::createTopologyFromMesh().