gmsh-TingyuanDoc: src/geo/GModelAutoExtrude.cpp File Reference
GModelAutoExtrude.cpp File Reference
#include <vector>
#include "GmshMessage.h"
#include "GModel.h"
#include "Context.h"
#include "ExtrudeParams.h"
Classes
class extrudeInfo
Functions
static bool sameDir (const SVector3 &v1, const SVector3 &v2)
static bool sortDirCount (const std::pair< SVector3, int > &a, const std::pair< SVector3, int > &b)
void getCandidateExtrudeInfo (GRegion *gr, std::vector< extrudeInfo > &info, std::vector< std::pair< SVector3, int >> &count)
Function Documentation
getCandidateExtrudeInfo()
void getCandidateExtrudeInfo (GRegion * gr, std::vector< extrudeInfo > & info, std::vector< std::pair< SVector3, int >> & count)
Definition at line 208 of file GModelAutoExtrude.cpp.
Referenced by GModel::addAutomaticExtrusionConstraints().
sameDir()
static bool sameDir (const SVector3 & v1, const SVector3 & v2) static
Definition at line 12 of file GModelAutoExtrude.cpp.
Referenced by GModel::addAutomaticExtrusionConstraints(), and getCandidateExtrudeInfo().
sortDirCount()
static bool sortDirCount (const std::pair< SVector3, int > & a, const std::pair< SVector3, int > & b) static
Definition at line 21 of file GModelAutoExtrude.cpp.
Referenced by GModel::addAutomaticExtrusionConstraints().