gmsh-TingyuanDoc: src/geo/GModelIO_MSH3.cpp File Reference
GModelIO_MSH3.cpp File Reference
#include <sstream>
#include <iomanip>
#include <ctime>
#include "GModel.h"
#include "OS.h"
#include "Context.h"
#include "GmshMessage.h"
#include "MElement.h"
#include "MPoint.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
#include "MTrihedron.h"
#include "StringUtils.h"
#include "discreteVertex.h"
#include "discreteEdge.h"
#include "discreteFace.h"
#include "discreteRegion.h"
Functions
static int readMSHPhysicals (FILE *fp, GEntity *ge)
static void readMSHEntities (FILE *fp, GModel *gm)
void readMSHPeriodicNodes (FILE *fp, GModel *gm)
static void writeMSHPhysicals (FILE *fp, GEntity *ge)
void writeMSHEntities (FILE *fp, GModel *gm)
static int getNumElementsMSH (GEntity *ge, bool saveAll, int saveSinglePartition)
static void writeElementMSH (FILE *fp, GModel *model, MElement *ele, bool binary, int elementary)
template<class T >
static void writeElementsMSH (FILE *fp, GModel *model, GEntity *ge, std::vector< T * > &ele, bool saveAll, int saveSinglePartition, bool binary)
void writeMSHPeriodicNodes (FILE *fp, std::vector< GEntity * > &entities, bool renumber, bool saveAll)
Function Documentation
getNumElementsMSH()
static int getNumElementsMSH (GEntity * ge, bool saveAll, int saveSinglePartition) static
Definition at line 633 of file GModelIO_MSH3.cpp.
Referenced by GModel::_writeMSH3().
readMSHEntities()
static void readMSHEntities (FILE * fp, GModel * gm) static
Definition at line 41 of file GModelIO_MSH3.cpp.
Referenced by GModel::_readMSH3().
readMSHPeriodicNodes()
void readMSHPeriodicNodes (FILE * fp, GModel * gm)
Definition at line 125 of file GModelIO_MSH3.cpp.
Referenced by GModel::_readMSH2(), and GModel::_readMSH3().
readMSHPhysicals()
static int readMSHPhysicals (FILE * fp, GEntity * ge) static
Definition at line 29 of file GModelIO_MSH3.cpp.
Referenced by readMSHEntities().
writeElementMSH()
static void writeElementMSH (FILE * fp, GModel * model, MElement * ele, bool binary, int elementary) static
Definition at line 646 of file GModelIO_MSH3.cpp.
Referenced by writeElementsMSH().
writeElementsMSH()
template<class T > static void writeElementsMSH (FILE * fp, GModel * model, GEntity * ge, std::vector< T * > & ele, bool saveAll, int saveSinglePartition, bool binary) static
Definition at line 661 of file GModelIO_MSH3.cpp.
Referenced by GModel::_writeMSH3().
writeMSHEntities()
void writeMSHEntities (FILE * fp, GModel * gm)
Definition at line 574 of file GModelIO_MSH3.cpp.
Referenced by GModel::_writeMSH2(), and GModel::_writeMSH3().
writeMSHPeriodicNodes()
void writeMSHPeriodicNodes (FILE * fp, std::vector< GEntity * > & entities, bool renumber, bool saveAll)
Definition at line 674 of file GModelIO_MSH3.cpp.
Referenced by GModel::_writeMSH2(), and GModel::_writeMSH3().
writeMSHPhysicals()
static void writeMSHPhysicals (FILE * fp, GEntity * ge) static
Definition at line 566 of file GModelIO_MSH3.cpp.
Referenced by writeMSHEntities().