gmsh-TingyuanDoc: src/geo/GModelIO_MSH2.cpp File Reference
GModelIO_MSH2.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include <map>
#include <string>
#include <sstream>
#include <cassert>
#include <iomanip>
#include "GModel.h"
#include "OS.h"
#include "GmshDefines.h"
#include "MPoint.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
#include "MElementCut.h"
#include "StringUtils.h"
#include "GmshMessage.h"
#include "Context.h"
#include "ghostEdge.h"
#include "ghostFace.h"
#include "ghostRegion.h"
Functions
void writeMSHPeriodicNodes (FILE *fp, std::vector< GEntity * > &entities, bool renumber, bool saveAll)
void readMSHPeriodicNodes (FILE *fp, GModel *gm)
void writeMSHEntities (FILE *fp, GModel *gm)
static bool getMeshVertices (int num, int *indices, std::map< int, MVertex * > &map, std::vector< MVertex * > &vertices)
static bool getMeshVertices (int num, int *indices, std::vector< MVertex * > &vec, std::vector< MVertex * > &vertices, int minVertex=0)
static MElement * createElementMSH2 (GModel *m, int num, int typeMSH, int physical, int reg, unsigned int part, std::vector< MVertex * > &v, std::map< int, std::vector< MElement * > > elements[10], std::map< int, std::map< int, std::string > > physicals[4], bool owner=false, MElement *parent=nullptr, MElement *d1=nullptr, MElement *d2=nullptr)
template<class T >
static void writeElementMSH (FILE *fp, GModel *model, GEntity *ge, T *ele, bool saveAll, double version, bool binary, int &num, int elementary, std::vector< int > &physicals, int parentNum=0, int dom1Num=0, int dom2Num=0)
template<class T >
static void writeElementsMSH (FILE *fp, GModel *model, GEntity *ge, std::vector< T * > &ele, bool saveAll, int saveSinglePartition, double version, bool binary, int &num, int elementary, std::vector< int > &physicals)
static int getNumElementsMSH (GEntity *ge, bool saveAll, int saveSinglePartition)
static int getNumElementsMSH (GModel *m, bool saveAll, int saveSinglePartition)
static int _getElementary (GEntity *ge)
Function Documentation
_getElementary()
static int _getElementary (GEntity * ge) static
Definition at line 869 of file GModelIO_MSH2.cpp.
Referenced by GModel::_writeMSH2().
createElementMSH2()
static MElement* createElementMSH2 (GModel * m, int num, int typeMSH, int physical, int reg, unsigned int part, std::vector< MVertex * > & v, std::map< int, std::vector< MElement * > > elements[10], std::map< int, std::map< int, std::string > > physicals[4], bool owner = false, MElement * parent = nullptr, MElement * d1 = nullptr, MElement * d2 = nullptr) static
Definition at line 70 of file GModelIO_MSH2.cpp.
Referenced by GModel::_readMSH2().
getMeshVertices() [1/2]
static bool getMeshVertices (int num, int * indices, std::map< int, MVertex * > & map, std::vector< MVertex * > & vertices) static
Definition at line 39 of file GModelIO_MSH2.cpp.
Referenced by GModel::_readMSH2().
getMeshVertices() [2/2]
static bool getMeshVertices (int num, int * indices, std::vector< MVertex * > & vec, std::vector< MVertex * > & vertices, int minVertex = 0) static
Definition at line 54 of file GModelIO_MSH2.cpp.
getNumElementsMSH() [1/2]
static int getNumElementsMSH (GEntity * ge, bool saveAll, int saveSinglePartition) static
Definition at line 788 of file GModelIO_MSH2.cpp.
Referenced by GModel::_writeMSH2(), GModel::_writePartitionedMSH2(), and getNumElementsMSH().
getNumElementsMSH() [2/2]
static int getNumElementsMSH (GModel * m, bool saveAll, int saveSinglePartition) static
Definition at line 812 of file GModelIO_MSH2.cpp.
readMSHPeriodicNodes()
void readMSHPeriodicNodes (FILE * fp, GModel * gm)
Definition at line 125 of file GModelIO_MSH3.cpp.
Referenced by GModel::_readMSH2(), and GModel::_readMSH3().
writeElementMSH()
template<class T > static void writeElementMSH (FILE * fp, GModel * model, GEntity * ge, T * ele, bool saveAll, double version, bool binary, int & num, int elementary, std::vector< int > & physicals, int parentNum = 0, int dom1Num = 0, int dom2Num = 0) static
Definition at line 695 of file GModelIO_MSH2.cpp.
Referenced by GModel::_writeMSH2(), and writeElementsMSH().
writeElementsMSH()
template<class T > static void writeElementsMSH (FILE * fp, GModel * model, GEntity * ge, std::vector< T * > & ele, bool saveAll, int saveSinglePartition, double version, bool binary, int & num, int elementary, std::vector< int > & physicals) static
Definition at line 736 of file GModelIO_MSH2.cpp.
Referenced by GModel::_writeMSH2().
writeMSHEntities()
void writeMSHEntities (FILE * fp, GModel * gm)
Definition at line 574 of file GModelIO_MSH3.cpp.
Referenced by GModel::_writeMSH2(), and GModel::_writeMSH3().
writeMSHPeriodicNodes()
void writeMSHPeriodicNodes (FILE * fp, std::vector< GEntity * > & entities, bool renumber, bool saveAll)
Definition at line 674 of file GModelIO_MSH3.cpp.
Referenced by GModel::_writeMSH2(), and GModel::_writeMSH3().