gmsh-TingyuanDoc: src/geo/GModelIO_MATLAB.cpp File Reference
GModelIO_MATLAB.cpp File Reference
#include <utility>
#include "GModel.h"
#include "OS.h"
#include "MPoint.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
#include "StringUtils.h"
Functions
std::string getMATLABName (int type)
void writeElementsMATLAB (FILE *fp, const GEntity *entity, int filetype, bool binary, int physical)
void storePairMATLAB (const GEntity *entity, int physical, std::vector< std::vector< std::pair< MElement *, int > > > &elems)
Function Documentation
getMATLABName()
std::string getMATLABName (int type)
Definition at line 161 of file GModelIO_MATLAB.cpp.
Referenced by GModel::writeMATLAB().
storePairMATLAB()
void storePairMATLAB (const GEntity * entity, int physical, std::vector< std::vector< std::pair< MElement *, int > > > & elems)
Definition at line 34 of file GModelIO_MATLAB.cpp.
Referenced by GModel::writeMATLAB().
writeElementsMATLAB()
void writeElementsMATLAB (FILE * fp, const GEntity * entity, int filetype, bool binary, int physical)
Definition at line 22 of file GModelIO_MATLAB.cpp.
Referenced by GModel::writeMATLAB().