gmsh-TingyuanDoc: src/numeric/GaussIntegration.h File Reference
GaussIntegration.h File Reference
Classes
class fullVector< scalar >
class fullMatrix< scalar >
struct IntPt
class gaussIntegration
Functions
int GaussLegendreTri (int n1, int n2, IntPt *pts)
int GaussLegendreTet (int n1, int n2, int n3, IntPt *pts)
int getNGQLPts (int order)
IntPt * getGQLPts (int order)
int getNGQTPts (int order, bool forceTensorRule=false)
IntPt * getGQTPts (int order, bool forceTensorRule=false)
int getNGQQPts (int order, bool forceTensorRule=false)
IntPt * getGQQPts (int order, bool forceTensorRule=false)
int getNGQTetPts (int order, bool forceTensorRule=false)
IntPt * getGQTetPts (int order, bool forceTensorRule=false)
int getNGQPriPts (int order, bool forceTensorRule=false)
IntPt * getGQPriPts (int order, bool forceTensorRule=false)
int getNGQPyrPts (int order)
IntPt * getGQPyrPts (int order)
int getNGQHPts (int order, bool forceTensorRule=false)
IntPt * getGQHPts (int order, bool forceTensorRule=false)
Function Documentation
GaussLegendreTet()
int GaussLegendreTet (int n1, int n2, int n3, IntPt * pts)
Definition at line 33 of file GaussLegendreSimplex.cpp.
Referenced by getGQTetPts().
GaussLegendreTri()
int GaussLegendreTri (int n1, int n2, IntPt * pts)
Definition at line 54 of file GaussLegendreSimplex.cpp.
Referenced by getGQTPts().
getGQHPts()
IntPt* getGQHPts (int order, bool forceTensorRule = false)
Definition at line 88 of file GaussQuadratureHex.cpp.
Referenced by gaussIntegration::get(), gaussIntegration::getHexahedron(), and MHexahedron::getIntegrationPoints().
getGQLPts()
IntPt* getGQLPts (int order)
Definition at line 12 of file GaussQuadratureLin.cpp.
Referenced by gaussIntegration::get(), MLine::getIntegrationPoints(), and gaussIntegration::getLine().
getGQPriPts()
IntPt* getGQPriPts (int order, bool forceTensorRule = false)
Definition at line 12 of file GaussQuadraturePri.cpp.
Referenced by gaussIntegration::get(), MPrism::getIntegrationPoints(), and gaussIntegration::getPrism().
getGQPyrPts()
IntPt* getGQPyrPts (int order)
Definition at line 13 of file GaussQuadraturePyr.cpp.
Referenced by gaussIntegration::get(), MPyramid::getIntegrationPoints(), and gaussIntegration::getPyramid().
getGQQPts()
IntPt* getGQQPts (int order, bool forceTensorRule = false)
Definition at line 99 of file GaussQuadratureQuad.cpp.
Referenced by gaussIntegration::get(), MQuadrangle::getIntegrationPoints(), and gaussIntegration::getQuad().
getGQTetPts()
IntPt* getGQTetPts (int order, bool forceTensorRule = false)
Definition at line 3346 of file GaussQuadratureTet.cpp.
Referenced by gaussIntegration::get(), MTetrahedron::getIntegrationPoints(), and gaussIntegration::getTetrahedron().
getGQTPts()
IntPt* getGQTPts (int order, bool forceTensorRule = false)
Definition at line 889 of file GaussQuadratureTri.cpp.
Referenced by gaussIntegration::get(), getGQPriPts(), MTriangle::getIntegrationPoints(), and gaussIntegration::getTriangle().
getNGQHPts()
int getNGQHPts (int order, bool forceTensorRule = false)
Definition at line 115 of file GaussQuadratureHex.cpp.
Referenced by gaussIntegration::get(), gaussIntegration::getHexahedron(), and MHexahedron::getIntegrationPoints().
getNGQLPts()
int getNGQLPts (int order)
Definition at line 33 of file GaussQuadratureLin.cpp.
Referenced by gaussIntegration::get(), MLine::getIntegrationPoints(), MSubLine::getIntegrationPoints(), MLineChild::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), and gaussIntegration::getLine().
getNGQPriPts()
int getNGQPriPts (int order, bool forceTensorRule = false)
Definition at line 47 of file GaussQuadraturePri.cpp.
Referenced by gaussIntegration::get(), MPrism::getIntegrationPoints(), and gaussIntegration::getPrism().
getNGQPyrPts()
int getNGQPyrPts (int order)
Definition at line 59 of file GaussQuadraturePyr.cpp.
Referenced by gaussIntegration::get(), getGQPyrPts(), MPyramid::getIntegrationPoints(), and gaussIntegration::getPyramid().
getNGQQPts()
int getNGQQPts (int order, bool forceTensorRule = false)
Definition at line 124 of file GaussQuadratureQuad.cpp.
Referenced by gaussIntegration::get(), MQuadrangle::getIntegrationPoints(), and gaussIntegration::getQuad().
getNGQTetPts()
int getNGQTetPts (int order, bool forceTensorRule = false)
Definition at line 3362 of file GaussQuadratureTet.cpp.
Referenced by gaussIntegration::get(), MSubTetrahedron::getIntegrationPoints(), MPolyhedron::getIntegrationPoints(), MTetrahedron::getIntegrationPoints(), and gaussIntegration::getTetrahedron().
getNGQTPts()
int getNGQTPts (int order, bool forceTensorRule = false)
Definition at line 904 of file GaussQuadratureTri.cpp.
Referenced by gaussIntegration::get(), getGQPriPts(), MTriangle::getIntegrationPoints(), MSubTriangle::getIntegrationPoints(), MPolygon::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), getNGQPriPts(), and gaussIntegration::getTriangle().