gmsh-TingyuanDoc: src/numeric/GaussIntegration.cpp File Reference
GaussIntegration.cpp File Reference
#include "GmshDefines.h"
#include "GaussIntegration.h"
#include "fullMatrix.h"
Functions
static void pts2fullMatrix (int npts, IntPt *pts, fullMatrix< double > &pMatrix, fullVector< double > &wMatrix)
Function Documentation
pts2fullMatrix()
static void pts2fullMatrix (int npts, IntPt * pts, fullMatrix< double > & pMatrix, fullVector< double > & wMatrix) static
Definition at line 10 of file GaussIntegration.cpp.
Referenced by gaussIntegration::get(), gaussIntegration::getHexahedron(), gaussIntegration::getLine(), gaussIntegration::getPrism(), gaussIntegration::getPyramid(), gaussIntegration::getQuad(), gaussIntegration::getTetrahedron(), and gaussIntegration::getTriangle().