gmsh-TingyuanDoc: src/numeric/GaussQuadratureLin.cpp File Reference
GaussQuadratureLin.cpp File Reference
#include <vector>
#include "GaussIntegration.h"
#include "GaussLegendre1D.h"
Functions
static std::vector< IntPt * > GQL (40, nullptr)
IntPt * getGQLPts (int order)
int getNGQLPts (int order)
Function Documentation
getGQLPts()
IntPt* getGQLPts (int order)
Definition at line 12 of file GaussQuadratureLin.cpp.
Referenced by gaussIntegration::get(), MLine::getIntegrationPoints(), and gaussIntegration::getLine().
getNGQLPts()
int getNGQLPts (int order)
Definition at line 33 of file GaussQuadratureLin.cpp.
Referenced by gaussIntegration::get(), MLine::getIntegrationPoints(), MSubLine::getIntegrationPoints(), MLineChild::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), and gaussIntegration::getLine().
GQL()
static std::vector<IntPt *> GQL (40 , nullptr) static
Referenced by getGQLPts(), and MPoint::getIntegrationPoints().