gmsh-TingyuanDoc: src/numeric/GaussQuadratureTri.cpp File Reference
GaussQuadratureTri.cpp File Reference
#include <vector>
#include "GaussIntegration.h"
#include "GaussLegendre1D.h"
Functions
static std::vector< IntPt * > GQTGL (40, nullptr)
IntPt * getGQTPts (int order, bool forceTensorRule)
int getNGQTPts (int order, bool forceTensorRule)
Variables
IntPt GQT1 [1]
IntPt GQT2 [3]
IntPt GQT3 [4]
IntPt GQT4 [6]
IntPt GQT5 [7]
IntPt GQT6 [12]
IntPt GQT7 [13]
IntPt GQT8 [16]
IntPt * GQT [9] = {GQT1, GQT1, GQT2, GQT3, GQT4, GQT5, GQT6, GQT7, GQT8}
int GQTnPt [9] = {1, 1, 3, 4, 6, 7, 12, 13, 16}
IntPt triP1Solin [1]
IntPt triP2Solin [3]
IntPt triP3Solin [4]
IntPt triP4Solin [6]
IntPt triP5Solin [7]
IntPt triP6Solin [12]
IntPt triP7Solin [13]
IntPt triP8Solin [16]
IntPt triP9Solin [19]
IntPt triP10Solin [25]
IntPt triP11Solin [27]
IntPt triP12Solin [33]
IntPt triP13Solin [37]
IntPt triP14Solin [42]
IntPt triP15Solin [48]
IntPt triP16Solin [52]
IntPt triP17Solin [61]
IntPt triP18Solin [70]
IntPt triP19Solin [73]
IntPt triP20Solin [79]
static IntPt * GQTSolin [21]
static int GQTnPtSolin [21]
Function Documentation
getGQTPts()
IntPt* getGQTPts (int order, bool forceTensorRule)
Definition at line 889 of file GaussQuadratureTri.cpp.
Referenced by gaussIntegration::get(), getGQPriPts(), MTriangle::getIntegrationPoints(), and gaussIntegration::getTriangle().
getNGQTPts()
int getNGQTPts (int order, bool forceTensorRule)
Definition at line 904 of file GaussQuadratureTri.cpp.
Referenced by gaussIntegration::get(), getGQPriPts(), MTriangle::getIntegrationPoints(), MSubTriangle::getIntegrationPoints(), MPolygon::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), getNGQPriPts(), and gaussIntegration::getTriangle().
GQTGL()
static std::vector<IntPt *> GQTGL (40 , nullptr) static
Referenced by getGQTPts().
Variable Documentation
GQT
IntPt* GQT[9] = {GQT1, GQT1, GQT2, GQT3, GQT4, GQT5, GQT6, GQT7, GQT8}
Definition at line 89 of file GaussQuadratureTri.cpp.
GQT1
IntPt GQT1[1]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, 0.500000000000000}}
Definition at line 10 of file GaussQuadratureTri.cpp.
GQT2
IntPt GQT2[3]
Initial value:
= {
  {{0.166666666666667, 0.166666666666667, 0.}, 0.166666666666667},
  {{0.666666666666667, 0.166666666666667, 0.}, 0.166666666666667},
  {{0.166666666666667, 0.666666666666667, 0.}, 0.166666666666667}}
Definition at line 12 of file GaussQuadratureTri.cpp.
GQT3
IntPt GQT3[4]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, -0.281250000000000},
  {{0.600000000000000, 0.200000000000000, 0.}, +0.260416666666667},
  {{0.200000000000000, 0.600000000000000, 0.}, +0.260416666666667},
  {{0.200000000000000, 0.200000000000000, 0.}, +0.260416666666667}}
Definition at line 17 of file GaussQuadratureTri.cpp.
GQT4
IntPt GQT4[6]
Initial value:
= {
  {{0.816847572980459, 0.091576213509771, 0.}, 0.054975871827661},
  {{0.091576213509771, 0.816847572980459, 0.}, 0.054975871827661},
  {{0.091576213509771, 0.091576213509771, 0.}, 0.054975871827661},
  {{0.108103018168070, 0.445948490915965, 0.}, 0.111690794839005},
  {{0.445948490915965, 0.108103018168070, 0.}, 0.111690794839005},
  {{0.445948490915965, 0.445948490915965, 0.}, 0.111690794839005}}
Definition at line 23 of file GaussQuadratureTri.cpp.
GQT5
IntPt GQT5[7]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, 0.112500000000000},
  {{0.797426985353087, 0.101286507323456, 0.}, 0.062969590272414},
  {{0.101286507323456, 0.797426985353087, 0.}, 0.062969590272414},
  {{0.101286507323456, 0.101286507323456, 0.}, 0.062969590272414},
  {{0.470142064105115, 0.059715871789770, 0.}, 0.066197076394253},
  {{0.059715871789770, 0.470142064105115, 0.}, 0.066197076394253},
  {{0.470142064105115, 0.470142064105115, 0.}, 0.066197076394253}}
Definition at line 31 of file GaussQuadratureTri.cpp.
GQT6
IntPt GQT6[12]
Initial value:
= {
  {{0.873821971016996, 0.063089014491502, 0.}, 0.025422453185104},
  {{0.063089014491502, 0.873821971016996, 0.}, 0.025422453185104},
  {{0.063089014491502, 0.063089014491502, 0.}, 0.025422453185104},
  {{0.501426509658179, 0.249286745170910, 0.}, 0.058393137863189},
  {{0.249286745170910, 0.501426509658179, 0.}, 0.058393137863189},
  {{0.249286745170910, 0.249286745170910, 0.}, 0.058393137863189},
  {{0.636502499121399, 0.310352451033785, 0.}, 0.041425537809187},
  {{0.310352451033785, 0.636502499121399, 0.}, 0.041425537809187},
  {{0.636502499121399, 0.053145049844816, 0.}, 0.041425537809187},
  {{0.310352451033785, 0.053145049844816, 0.}, 0.041425537809187},
  {{0.053145049844816, 0.310352451033785, 0.}, 0.041425537809187},
  {{0.053145049844816, 0.636502499121399, 0.}, 0.041425537809187}}
Definition at line 40 of file GaussQuadratureTri.cpp.
GQT7
IntPt GQT7[13]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, -0.074785022233841},
  {{0.479308067841920, 0.260345966079040, 0.}, +0.087807628716604},
  {{0.260345966079040, 0.479308067841920, 0.}, +0.087807628716604},
  {{0.260345966079040, 0.260345966079040, 0.}, +0.087807628716604},
  {{0.869739794195568, 0.065130102902216, 0.}, +0.026673617804419},
  {{0.065130102902216, 0.869739794195568, 0.}, +0.026673617804419},
  {{0.065130102902216, 0.065130102902216, 0.}, +0.026673617804419},
  {{0.048690315425316, 0.312865496004874, 0.}, +0.038556880445128},
  {{0.312865496004874, 0.048690315425316, 0.}, +0.038556880445128},
  {{0.638444188569810, 0.048690315425316, 0.}, +0.038556880445128},
  {{0.048690315425316, 0.638444188569810, 0.}, +0.038556880445128},
  {{0.312865496004874, 0.638444188569810, 0.}, +0.038556880445128},
  {{0.638444188569810, 0.312865496004874, 0.}, +0.038556880445128}
}
Definition at line 54 of file GaussQuadratureTri.cpp.
GQT8
IntPt GQT8[16]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, 0.072157803838894},
  {{0.081414823414554, 0.459292588292723, 0.}, 0.047545817133643},
  {{0.459292588292723, 0.081414823414554, 0.}, 0.047545817133643},
  {{0.459292588292723, 0.459292588292723, 0.}, 0.047545817133643},
  {{0.658861384496480, 0.170569307751760, 0.}, 0.051608685267359},
  {{0.170569307751760, 0.658861384496480, 0.}, 0.051608685267359},
  {{0.170569307751760, 0.170569307751760, 0.}, 0.051608685267359},
  {{0.898905543365938, 0.050547228317031, 0.}, 0.016229248811599},
  {{0.050547228317031, 0.898905543365938, 0.}, 0.016229248811599},
  {{0.050547228317031, 0.050547228317031, 0.}, 0.016229248811599},
  {{0.008394777409958, 0.728492392955404, 0.}, 0.013615157087217},
  {{0.728492392955404, 0.008394777409958, 0.}, 0.013615157087217},
  {{0.263112829634638, 0.008394777409958, 0.}, 0.013615157087217},
  {{0.008394777409958, 0.263112829634638, 0.}, 0.013615157087217},
  {{0.263112829634638, 0.728492392955404, 0.}, 0.013615157087217},
  {{0.728492392955404, 0.263112829634638, 0.}, 0.013615157087217}}
Definition at line 71 of file GaussQuadratureTri.cpp.
GQTnPt
int GQTnPt[9] = {1, 1, 3, 4, 6, 7, 12, 13, 16}
Definition at line 90 of file GaussQuadratureTri.cpp.
GQTnPtSolin
int GQTnPtSolin[21] static
Initial value:
= {1,  1,  3,  4,  6,  7,  12, 13, 16, 19, 25,
                              27, 33, 37, 42, 48, 52, 61, 70, 73, 79}
Definition at line 885 of file GaussQuadratureTri.cpp.
Referenced by getNGQTPts().
GQTSolin
IntPt* GQTSolin[21] static
Initial value:
= {
  triP1Solin,  triP1Solin,  triP2Solin,  triP3Solin,  triP4Solin,  triP5Solin,
  triP6Solin,  triP7Solin,  triP8Solin,  triP9Solin,  triP10Solin, triP11Solin,
  triP12Solin, triP13Solin, triP14Solin, triP15Solin, triP16Solin, triP17Solin,
  triP18Solin, triP19Solin, triP20Solin}
Definition at line 880 of file GaussQuadratureTri.cpp.
Referenced by getGQTPts().
triP10Solin
IntPt triP10Solin[25]
Initial value:
= {
  {{0.3333333333330, 0.3333333333330, 0.}, 0.04540899519140},
  {{0.4855776333840, 0.4855776333840, 0.}, 0.01836297887825},
  {{0.4855776333840, 0.0288447332327, 0.}, 0.01836297887825},
  {{0.0288447332327, 0.4855776333840, 0.}, 0.01836297887825},
  {{0.1094815754850, 0.1094815754850, 0.}, 0.02266052971775},
  {{0.1094815754850, 0.7810368490300, 0.}, 0.02266052971775},
  {{0.7810368490300, 0.1094815754850, 0.}, 0.02266052971775},
  {{0.3079398387640, 0.5503529418210, 0.}, 0.03637895842270},
  {{0.5503529418210, 0.1417072194150, 0.}, 0.03637895842270},
  {{0.1417072194150, 0.3079398387640, 0.}, 0.03637895842270},
  {{0.3079398387640, 0.1417072194150, 0.}, 0.03637895842270},
  {{0.5503529418210, 0.3079398387640, 0.}, 0.03637895842270},
  {{0.1417072194150, 0.5503529418210, 0.}, 0.03637895842270},
  {{0.2466725606400, 0.7283239045970, 0.}, 0.01416362126555},
  {{0.7283239045970, 0.0250035347627, 0.}, 0.01416362126555},
  {{0.0250035347627, 0.2466725606400, 0.}, 0.01416362126555},
  {{0.2466725606400, 0.0250035347627, 0.}, 0.01416362126555},
  {{0.7283239045970, 0.2466725606400, 0.}, 0.01416362126555},
  {{0.0250035347627, 0.7283239045970, 0.}, 0.01416362126555},
  {{0.0668032510122, 0.9236559335870, 0.}, 0.00471083348185},
  {{0.9236559335870, 0.0095408154003, 0.}, 0.00471083348185},
  {{0.0095408154003, 0.0668032510122, 0.}, 0.00471083348185},
  {{0.0668032510122, 0.0095408154003, 0.}, 0.00471083348185},
  {{0.9236559335870, 0.0668032510122, 0.}, 0.00471083348185},
  {{0.0095408154003, 0.9236559335870, 0.}, 0.00471083348185}}
Quadrature rule for an interpolation of order 10 on the triangle
Definition at line 249 of file GaussQuadratureTri.cpp.
triP11Solin
IntPt triP11Solin[27]
Initial value:
= {
  {{+0.5346110482710, +0.5346110482710, 0.}, 0.00046350316448},
  {{-0.0692220965415, +0.5346110482710, 0.}, 0.00046350316448},
  {{+0.5346110482710, -0.0692220965415, 0.}, 0.00046350316448},
  {{+0.3989693029660, +0.3989693029660, 0.}, 0.03857476745740},
  {{+0.2020613940680, +0.3989693029660, 0.}, 0.03857476745740},
  {{+0.3989693029660, +0.2020613940680, 0.}, 0.03857476745740},
  {{+0.2033099004310, +0.2033099004310, 0.}, 0.02966148869040},
  {{+0.5933801991370, +0.2033099004310, 0.}, 0.02966148869040},
  {{+0.2033099004310, +0.5933801991370, 0.}, 0.02966148869040},
  {{+0.1193509122830, +0.1193509122830, 0.}, 0.01809227025170},
  {{+0.7612981754350, +0.1193509122830, 0.}, 0.01809227025170},
  {{+0.1193509122830, +0.7612981754350, 0.}, 0.01809227025170},
  {{+0.0323649481113, +0.0323649481113, 0.}, 0.00682986550135},
  {{+0.9352701037770, +0.0323649481113, 0.}, 0.00682986550135},
  {{+0.0323649481113, +0.9352701037770, 0.}, 0.00682986550135},
  {{+0.5932012134280, +0.3566206482610, 0.}, 0.02616855598110},
  {{+0.0501781383105, +0.5932012134280, 0.}, 0.02616855598110},
  {{+0.3566206482610, +0.0501781383105, 0.}, 0.02616855598110},
  {{+0.0501781383105, +0.3566206482610, 0.}, 0.02616855598110},
  {{+0.3566206482610, +0.5932012134280, 0.}, 0.02616855598110},
  {{+0.5932012134280, +0.0501781383105, 0.}, 0.02616855598110},
  {{+0.8074890031600, +0.1714889803040, 0.}, 0.01035382981955},
  {{+0.0210220165362, +0.8074890031600, 0.}, 0.01035382981955},
  {{+0.1714889803040, +0.0210220165362, 0.}, 0.01035382981955},
  {{+0.0210220165362, +0.1714889803040, 0.}, 0.01035382981955},
  {{+0.1714889803040, +0.8074890031600, 0.}, 0.01035382981955},
  {{+0.8074890031600, +0.0210220165362, 0.}, 0.01035382981955}}
Quadrature rule for an interpolation of order 11 on the triangle
Definition at line 282 of file GaussQuadratureTri.cpp.
triP12Solin
IntPt triP12Solin[33]
Quadrature rule for an interpolation of order 12 on the triangle
Definition at line 317 of file GaussQuadratureTri.cpp.
triP13Solin
IntPt triP13Solin[37]
Quadrature rule for an interpolation of order 13 on the triangle
Definition at line 358 of file GaussQuadratureTri.cpp.
triP14Solin
IntPt triP14Solin[42]
Quadrature rule for an interpolation of order 14 on the triangle
Definition at line 403 of file GaussQuadratureTri.cpp.
triP15Solin
IntPt triP15Solin[48]
Quadrature rule for an interpolation of order 15 on the triangle
Definition at line 453 of file GaussQuadratureTri.cpp.
triP16Solin
IntPt triP16Solin[52]
Quadrature rule for an interpolation of order 16 on the triangle
Definition at line 509 of file GaussQuadratureTri.cpp.
triP17Solin
IntPt triP17Solin[61]
Quadrature rule for an interpolation of order 17 on the triangle
Definition at line 569 of file GaussQuadratureTri.cpp.
triP18Solin
IntPt triP18Solin[70]
Quadrature rule for an interpolation of order 18 on the triangle
Definition at line 638 of file GaussQuadratureTri.cpp.
triP19Solin
IntPt triP19Solin[73]
Quadrature rule for an interpolation of order 19 on the triangle
Definition at line 716 of file GaussQuadratureTri.cpp.
triP1Solin
IntPt triP1Solin[1]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, 0.500000000000000}}
Quadrature rule for an interpolation of order 1 on the triangle
Definition at line 96 of file GaussQuadratureTri.cpp.
triP20Solin
IntPt triP20Solin[79]
Quadrature rule for an interpolation of order 20 on the triangle
Definition at line 797 of file GaussQuadratureTri.cpp.
triP2Solin
IntPt triP2Solin[3]
Initial value:
= {
  {{0.166666666666667, 0.166666666666667, 0.}, 0.166666666666667},
  {{0.166666666666667, 0.666666666666667, 0.}, 0.166666666666667},
  {{0.666666666666667, 0.166666666666667, 0.}, 0.166666666666667}}
Quadrature rule for an interpolation of order 2 on the triangle
Definition at line 105 of file GaussQuadratureTri.cpp.
triP3Solin
IntPt triP3Solin[4]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, -0.281250000000000},
  {{0.200000000000000, 0.200000000000000, 0.}, 0.260416666666667},
  {{0.200000000000000, 0.600000000000000, 0.}, 0.260416666666667},
  {{0.600000000000000, 0.200000000000000, 0.}, 0.260416666666667}}
Quadrature rule for an interpolation of order 3 on the triangle
Definition at line 116 of file GaussQuadratureTri.cpp.
triP4Solin
IntPt triP4Solin[6]
Initial value:
= {
  {{0.445948490915965, 0.445948490915965, 0.}, 0.111690794839005},
  {{0.445948490915965, 0.108103018168070, 0.}, 0.111690794839005},
  {{0.108103018168070, 0.445948490915965, 0.}, 0.111690794839005},
  {{0.091576213509771, 0.091576213509771, 0.}, 0.054975871827661},
  {{0.091576213509771, 0.816847572980459, 0.}, 0.054975871827661},
  {{0.816847572980459, 0.091576213509771, 0.}, 0.054975871827661}}
Quadrature rule for an interpolation of order 4 on the triangle
Definition at line 128 of file GaussQuadratureTri.cpp.
triP5Solin
IntPt triP5Solin[7]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, 0.112500000000000},
  {{0.470142064105115, 0.470142064105115, 0.}, 0.066197076394253},
  {{0.470142064105115, 0.059715871789770, 0.}, 0.066197076394253},
  {{0.059715871789770, 0.470142064105115, 0.}, 0.066197076394253},
  {{0.101286507323456, 0.101286507323456, 0.}, 0.062969590272414},
  {{0.101286507323456, 0.797426985353087, 0.}, 0.062969590272414},
  {{0.797426985353087, 0.101286507323456, 0.}, 0.062969590272414}}
Quadrature rule for an interpolation of order 5 on the triangle
Definition at line 142 of file GaussQuadratureTri.cpp.
triP6Solin
IntPt triP6Solin[12]
Initial value:
= {
  {{0.249286745170910, 0.249286745170910, 0.}, 0.058393137863189},
  {{0.249286745170910, 0.501426509658179, 0.}, 0.058393137863189},
  {{0.501426509658179, 0.249286745170910, 0.}, 0.058393137863189},
  {{0.063089014491502, 0.063089014491502, 0.}, 0.025422453185104},
  {{0.063089014491502, 0.873821971016996, 0.}, 0.025422453185104},
  {{0.873821971016996, 0.063089014491502, 0.}, 0.025422453185104},
  {{0.310352451033785, 0.636502499121399, 0.}, 0.041425537809187},
  {{0.636502499121399, 0.053145049844816, 0.}, 0.041425537809187},
  {{0.053145049844816, 0.310352451033785, 0.}, 0.041425537809187},
  {{0.310352451033785, 0.053145049844816, 0.}, 0.041425537809187},
  {{0.636502499121399, 0.310352451033785, 0.}, 0.041425537809187},
  {{0.053145049844816, 0.636502499121399, 0.}, 0.041425537809187}}
Quadrature rule for an interpolation of order 6 on the triangle
Definition at line 157 of file GaussQuadratureTri.cpp.
triP7Solin
IntPt triP7Solin[13]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, -0.074785022233841},
  {{0.260345966079040, 0.260345966079040, 0.}, 0.087807628716604},
  {{0.260345966079040, 0.479308067841920, 0.}, 0.087807628716604},
  {{0.479308067841920, 0.260345966079040, 0.}, 0.087807628716604},
  {{0.065130102902216, 0.065130102902216, 0.}, 0.026673617804419},
  {{0.065130102902216, 0.869739794195568, 0.}, 0.026673617804419},
  {{0.869739794195568, 0.065130102902216, 0.}, 0.026673617804419},
  {{0.312865496004874, 0.638444188569810, 0.}, 0.038556880445128},
  {{0.638444188569810, 0.048690315425316, 0.}, 0.038556880445128},
  {{0.048690315425316, 0.312865496004874, 0.}, 0.038556880445128},
  {{0.312865496004874, 0.048690315425316, 0.}, 0.038556880445128},
  {{0.638444188569810, 0.312865496004874, 0.}, 0.038556880445128},
  {{0.048690315425316, 0.638444188569810, 0.}, 0.038556880445128}}
Quadrature rule for an interpolation of order 7 on the triangle
Definition at line 177 of file GaussQuadratureTri.cpp.
triP8Solin
IntPt triP8Solin[16]
Initial value:
= {
  {{0.333333333333333, 0.333333333333333, 0.}, 0.072157803838894},
  {{0.459292588292723, 0.459292588292723, 0.}, 0.047545817133643},
  {{0.459292588292723, 0.081414823414554, 0.}, 0.047545817133643},
  {{0.081414823414554, 0.459292588292723, 0.}, 0.047545817133643},
  {{0.170569307751760, 0.170569307751760, 0.}, 0.051608685267359},
  {{0.170569307751760, 0.658861384496480, 0.}, 0.051608685267359},
  {{0.658861384496480, 0.170569307751760, 0.}, 0.051608685267359},
  {{0.050547228317031, 0.050547228317031, 0.}, 0.016229248811599},
  {{0.050547228317031, 0.898905543365938, 0.}, 0.016229248811599},
  {{0.898905543365938, 0.050547228317031, 0.}, 0.016229248811599},
  {{0.263112829634638, 0.728492392955404, 0.}, 0.013615157087217},
  {{0.728492392955404, 0.008394777409958, 0.}, 0.013615157087217},
  {{0.008394777409958, 0.263112829634638, 0.}, 0.013615157087217},
  {{0.263112829634638, 0.008394777409958, 0.}, 0.013615157087217},
  {{0.728492392955404, 0.263112829634638, 0.}, 0.013615157087217},
  {{0.008394777409958, 0.728492392955404, 0.}, 0.013615157087217}}
Quadrature rule for an interpolation of order 8 on the triangle
Definition at line 198 of file GaussQuadratureTri.cpp.
triP9Solin
IntPt triP9Solin[19]
Initial value:
= {
  {{0.3333333333330, 0.3333333333333, 0.}, 0.04856789814140},
  {{0.4896825191990, 0.4896825191990, 0.}, 0.01566735011355},
  {{0.4896825191990, 0.0206349616025, 0.}, 0.01566735011355},
  {{0.0206349616025, 0.4896825191990, 0.}, 0.01566735011355},
  {{0.4370895914930, 0.4370895914930, 0.}, 0.03891377050240},
  {{0.4370895914930, 0.1258208170140, 0.}, 0.03891377050240},
  {{0.1258208170140, 0.4370895914930, 0.}, 0.03891377050240},
  {{0.1882035356190, 0.1882035356190, 0.}, 0.03982386946360},
  {{0.1882035356190, 0.6235929287620, 0.}, 0.03982386946360},
  {{0.6235929287620, 0.1882035356190, 0.}, 0.03982386946360},
  {{0.0447295133945, 0.0447295133945, 0.}, 0.01278883782935},
  {{0.0447295133945, 0.9105409732110, 0.}, 0.01278883782935},
  {{0.9105409732110, 0.0447295133945, 0.}, 0.01278883782935},
  {{0.2219629891610, 0.7411985987840, 0.}, 0.02164176968865},
  {{0.7411985987840, 0.0368384120547, 0.}, 0.02164176968865},
  {{0.0368384120547, 0.2219629891610, 0.}, 0.02164176968865},
  {{0.2219629891610, 0.0368384120547, 0.}, 0.02164176968865},
  {{0.7411985987840, 0.2219629891610, 0.}, 0.02164176968865},
  {{0.0368384120547, 0.7411985987840, 0.}, 0.02164176968865}}
Quadrature rule for an interpolation of order 9 on the triangle
Definition at line 222 of file GaussQuadratureTri.cpp.