gmsh-TingyuanDoc: src/numeric/GaussLegendreSimplex.cpp File Reference
GaussLegendreSimplex.cpp File Reference
#include <math.h>
#include "GaussIntegration.h"
#include "GaussLegendre1D.h"
Functions
static void brickToTet (double xi, double eta, double zeta, double *r, double *s, double *t, double *J)
void quadToTri (double xi, double eta, double *r, double *s, double *J)
double quadToTriJac (double, double eta)
int GaussLegendreTet (int n1, int n2, int n3, IntPt *pts)
int GaussLegendreTri (int n1, int n2, IntPt *pts)
Function Documentation
brickToTet()
static void brickToTet (double xi, double eta, double zeta, double * r, double * s, double * t, double * J) static
Definition at line 10 of file GaussLegendreSimplex.cpp.
Referenced by GaussLegendreTet().
GaussLegendreTet()
int GaussLegendreTet (int n1, int n2, int n3, IntPt * pts)
Definition at line 33 of file GaussLegendreSimplex.cpp.
Referenced by getGQTetPts().
GaussLegendreTri()
int GaussLegendreTri (int n1, int n2, IntPt * pts)
Definition at line 54 of file GaussLegendreSimplex.cpp.
Referenced by getGQTPts().
quadToTri()
void quadToTri (double xi, double eta, double * r, double * s, double * J)
Definition at line 22 of file GaussLegendreSimplex.cpp.
Referenced by copyMesh(), and GaussLegendreTri().
quadToTriJac()
double quadToTriJac (double , double eta)
Definition at line 31 of file GaussLegendreSimplex.cpp.