gmsh-TingyuanDoc: src/numeric/GaussQuadraturePyr.cpp File Reference
GaussQuadraturePyr.cpp File Reference
#include <vector>
#include "GaussIntegration.h"
#include "GaussLegendre1D.h"
#include "GaussJacobi1D.h"
Functions
static std::vector< IntPt * > GQPyr (40, nullptr)
IntPt * getGQPyrPts (int order)
int getNGQPyrPts (int order)
Function Documentation
getGQPyrPts()
IntPt* getGQPyrPts (int order)
Definition at line 13 of file GaussQuadraturePyr.cpp.
Referenced by gaussIntegration::get(), MPyramid::getIntegrationPoints(), and gaussIntegration::getPyramid().
getNGQPyrPts()
int getNGQPyrPts (int order)
Definition at line 59 of file GaussQuadraturePyr.cpp.
Referenced by gaussIntegration::get(), getGQPyrPts(), MPyramid::getIntegrationPoints(), and gaussIntegration::getPyramid().
GQPyr()
static std::vector<IntPt *> GQPyr (40 , nullptr) static
Referenced by getGQPyrPts().