gmsh-TingyuanDoc: src/numeric/GaussQuadraturePri.cpp File Reference
GaussQuadraturePri.cpp File Reference
#include <vector>
#include "GaussIntegration.h"
#include "GaussLegendre1D.h"
Functions
static std::vector< IntPt * > GQP (40, nullptr)
static std::vector< IntPt * > GQPGL (40, nullptr)
IntPt * getGQPriPts (int order, bool forceTensorRule)
int getNGQPriPts (int order, bool forceTensorRule)
Function Documentation
getGQPriPts()
IntPt* getGQPriPts (int order, bool forceTensorRule)
Definition at line 12 of file GaussQuadraturePri.cpp.
Referenced by gaussIntegration::get(), MPrism::getIntegrationPoints(), and gaussIntegration::getPrism().
getNGQPriPts()
int getNGQPriPts (int order, bool forceTensorRule)
Definition at line 47 of file GaussQuadraturePri.cpp.
Referenced by gaussIntegration::get(), MPrism::getIntegrationPoints(), and gaussIntegration::getPrism().
GQP()
static std::vector<IntPt *> GQP (40 , nullptr) static
Referenced by getGQPriPts().
GQPGL()
static std::vector<IntPt *> GQPGL (40 , nullptr)
Referenced by getGQPriPts().