gmsh-TingyuanDoc: src/mesh/Generator.h File Reference
Generator.h File Reference
Functions
void GenerateMesh (GModel *m, int dimension)
void OptimizeMesh (GModel *m, const std::string &how="", bool force=false, int niter=1)
void RecombineMesh (GModel *m)
void AdaptMesh (GModel *m)
void FixPeriodicMesh (GModel *m)
void GetStatistics (double stat[50], double quality[4][100]=0, bool visibleOnly=false)
Function Documentation
AdaptMesh()
void AdaptMesh (GModel * m)
Definition at line 1303 of file Generator.cpp.
Referenced by GModel::adaptMesh().
FixPeriodicMesh()
void FixPeriodicMesh (GModel * m)
Definition at line 1455 of file Generator.cpp.
Referenced by GenerateMesh(), GModel::optimizeMesh(), RefineMesh(), and GModel::setOrderN().
GenerateMesh()
void GenerateMesh (GModel * m, int dimension)
Definition at line 1649 of file Generator.cpp.
Referenced by GModel::adaptMesh(), and GModel::mesh().
GetStatistics()
void GetStatistics (double stat[50], double quality[4][100] = 0, bool visibleOnly = false)
OptimizeMesh()
void OptimizeMesh (GModel * m, const std::string & how = "", bool force = false, int niter = 1)
Definition at line 1101 of file Generator.cpp.
Referenced by GenerateMesh(), Mesh2D(), GModel::optimizeMesh(), and RefineMesh().
RecombineMesh()
void RecombineMesh (GModel * m)
Definition at line 1318 of file Generator.cpp.
Referenced by GModel::recombineMesh().