gmsh-TingyuanDoc: src/geo/Geo.cpp File Reference
Geo.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include "GmshMessage.h"
#include "GmshConfig.h"
#include "Numeric.h"
#include "GModel.h"
#include "GModelIO_GEO.h"
#include "GModelIO_OCC.h"
#include "Geo.h"
#include "GeoInterpolation.h"
#include "Context.h"
#include "MVertexRTree.h"
#include "fullMatrix.h"
Classes
class ShapeLessThan
struct PointSurface
struct CurveSurface
Functions
int CompareVertex (const void *a, const void *b)
static int ComparePosition (const void *a, const void *b)
int CompareSurfaceLoop (const void *a, const void *b)
int CompareEdgeLoop (const void *a, const void *b)
int CompareCurve (const void *a, const void *b)
int CompareSurface (const void *a, const void *b)
int CompareVolume (const void *a, const void *b)
int ComparePhysicalGroup (const void *a, const void *b)
Vertex * CreateVertex (int Num, double X, double Y, double Z, double lc, double u)
Vertex * CreateVertex (int Num, double u, double v, gmshSurface *surf, double lc)
void FreeVertex (void *a, void *b)
PhysicalGroup * CreatePhysicalGroup (int Num, int typ, List_T *intlist)
void FreePhysicalGroup (void *a, void *b)
EdgeLoop * CreateEdgeLoop (int Num, List_T *intlist)
void FreeEdgeLoop (void *a, void *b)
SurfaceLoop * CreateSurfaceLoop (int Num, List_T *intlist)
void FreeSurfaceLoop (void *a, void *b)
static void direction (Vertex *v1, Vertex *v2, double d[3])
bool EndCurve (Curve *c)
void EndSurface (Surface *s)
Curve * CreateCurve (int Num, int Typ, int Order, List_T *Liste, List_T *Knots, int p1, int p2, double u1, double u2, bool &ok)
void FreeCurve (void *a, void *b)
Surface * CreateSurface (int Num, int Typ)
void FreeSurface (void *a, void *b)
Volume * CreateVolume (int Num, int Typ)
void FreeVolume (void *a, void *b)
static int Compare2Lists (List_T *List1, List_T *List2, int(*fcmp)(const void *a, const void *b))
static Vertex * FindPoint (int inum, Tree_T *t)
Vertex * FindPoint (int inum)
static Curve * FindCurve (int inum, Tree_T *t)
Curve * FindCurve (int inum)
static Surface * FindSurface (int inum, Tree_T *t)
Surface * FindSurface (int inum)
Volume * FindVolume (int inum)
EdgeLoop * FindEdgeLoop (int inum)
SurfaceLoop * FindSurfaceLoop (int inum)
PhysicalGroup * FindPhysicalGroup (int num, int type)
static void CopyVertex (Vertex *v, Vertex *vv)
Vertex * DuplicateVertex (Vertex *v)
Vertex * DuplicateVertex (GVertex *gv)
static int CompareAbsCurve (const void *a, const void *b)
static void CopyCurve (Curve *c, Curve *cc)
Curve * DuplicateCurve (Curve *c)
Curve * DuplicateCurve (GEdge *ge)
static void CopySurface (Surface *s, Surface *ss)
Surface * DuplicateSurface (Surface *s)
Surface * DuplicateSurface (GFace *gf, std::map< int, int > &source)
static void CopyVolume (Volume *v, Volume *vv)
Volume * DuplicateVolume (Volume *v)
void DeletePoint (int ip, bool recursive)
void DeleteCurve (int ip, bool recursive)
void DeleteSurface (int is, bool recursive)
void DeleteVolume (int iv, bool recursive)
void DeletePhysicalPoint (int num)
void DeletePhysicalLine (int num)
void DeletePhysicalSurface (int num)
void DeletePhysicalVolume (int num)
Curve * CreateReversedCurve (Curve *c)
int RecognizeLineLoop (List_T *liste, int *loop)
int RecognizeSurfaceLoop (List_T *liste, int *loop)
void SetTranslationMatrix (double matrix[4][4], double T[3])
void SetSymmetryMatrix (double matrix[4][4], double A, double B, double C, double D)
void SetDilatationMatrix (double matrix[4][4], double T[3], double A, double B, double C)
static void GramSchmidt (double v1[3], double v2[3], double v3[3])
void SetRotationMatrix (double matrix[4][4], double Axe[3], double alpha)
static void vecmat4x4 (double mat[4][4], double vec[4], double res[4])
static void ApplyTransformationToPointAlways (double matrix[4][4], Vertex *v)
static void ApplyTransformationToPoint (double matrix[4][4], Vertex *v)
static void ApplyTransformationToCurve (double matrix[4][4], Curve *c)
static void ApplyTransformationToSurface (double matrix[4][4], Surface *s)
static void ApplyTransformationToVolume (double matrix[4][4], Volume *v)
static bool ApplicationOnShapes (double matrix[4][4], List_T *shapes)
bool TranslateShapes (double X, double Y, double Z, List_T *shapes)
bool DilatShapes (double X, double Y, double Z, double A, double B, double C, List_T *shapes)
bool RotateShapes (double Ax, double Ay, double Az, double Px, double Py, double Pz, double alpha, List_T *shapes)
bool SymmetryShapes (double A, double B, double C, double D, List_T *shapes)
static int CompareTwoPoints (const void *a, const void *b)
static int CompareTwoCurves (const void *a, const void *b)
static int CompareTwoSurfaces (const void *a, const void *b)
static void MaxNumPoint (void *a, void *b)
static void MaxNumCurve (void *a, void *b)
static void MaxNumSurface (void *a, void *b)
static void ReplaceDuplicatePointsNew (double tol=-1.)
static void ReplaceDuplicatePoints (std::map< int, int > *v_report=nullptr)
static void ReplaceDuplicateCurves (std::map< int, int > *c_report=nullptr)
static void RemoveDegenerateCurves ()
static void RemoveDegenerateVolumes ()
static void RemoveDegenerateSurfaces ()
static void ReplaceDuplicateSurfaces (std::map< int, int > *s_report=nullptr)
static void ReplaceAllDuplicates (std::vector< std::map< int, int > > &report)
void ReplaceAllDuplicates ()
void ReplaceAllDuplicatesNew (double tol)
void ProtudeXYZ (double &x, double &y, double &z, ExtrudeParams *e)
int ExtrudePoint (int type, int ip, double T0, double T1, double T2, double A0, double A1, double A2, double X0, double X1, double X2, double alpha, Curve **pc, Curve **prc, int final, ExtrudeParams *e)
int ExtrudeCurve (int type, int ic, double T0, double T1, double T2, double A0, double A1, double A2, double X0, double X1, double X2, double alpha, Surface **ps, int final, ExtrudeParams *e)
int ExtrudeSurface (int type, int is, double T0, double T1, double T2, double A0, double A1, double A2, double X0, double X1, double X2, double alpha, Volume **pv, ExtrudeParams *e)
void ExtrudeShapes (int type, List_T *list_in, double T0, double T1, double T2, double A0, double A1, double A2, double X0, double X1, double X2, double alpha, ExtrudeParams *e, List_T *list_out)
static bool projectPS (fullVector< double > &x, fullVector< double > &res, void *data)
bool ProjectPointOnSurface (Surface *s, Vertex &p, double uv[2])
static Curve * _create_splitted_curve (Curve *c, List_T *nodes)
bool SplitCurve (int line_id, List_T *vertices_id, List_T *curves)
static bool intersectCS (fullVector< double > &uvt, fullVector< double > &res, void *data)
bool IntersectCurvesWithSurface (List_T *curve_ids, int surface_id, List_T *shapes)
bool SortEdgesInLoop (int num, List_T *edges, bool reorient)
bool SetSurfaceGeneratrices (Surface *s, List_T *loops)
bool SetVolumeSurfaces (Volume *v, List_T *loops)
int NEWPOINT ()
int NEWCURVE ()
int NEWCURVELOOP ()
int NEWSURFACE ()
int NEWSURFACELOOP ()
int NEWVOLUME ()
int NEWREG ()
int NEWFIELD ()
int NEWPHYSICAL ()
Variables
static List_T * ListOfTransformedPoints = nullptr
Function Documentation
_create_splitted_curve()
static Curve* _create_splitted_curve (Curve * c, List_T * nodes) static
Definition at line 3406 of file Geo.cpp.
Referenced by SplitCurve().
ApplicationOnShapes()
static bool ApplicationOnShapes (double matrix[4][4], List_T * shapes) static
Definition at line 1454 of file Geo.cpp.
Referenced by DilatShapes(), RotateShapes(), SymmetryShapes(), and TranslateShapes().
ApplyTransformationToCurve()
static void ApplyTransformationToCurve (double matrix[4][4], Curve * c) static
Definition at line 1416 of file Geo.cpp.
Referenced by ApplicationOnShapes(), ApplyTransformationToSurface(), and ExtrudeCurve().
ApplyTransformationToPoint()
static void ApplyTransformationToPoint (double matrix[4][4], Vertex * v) static
Definition at line 1403 of file Geo.cpp.
Referenced by ApplicationOnShapes(), ApplyTransformationToCurve(), and ExtrudePoint().
ApplyTransformationToPointAlways()
static void ApplyTransformationToPointAlways (double matrix[4][4], Vertex * v) static
Definition at line 1389 of file Geo.cpp.
Referenced by ApplyTransformationToPoint(), and ProtudeXYZ().
ApplyTransformationToSurface()
static void ApplyTransformationToSurface (double matrix[4][4], Surface * s) static
Definition at line 1434 of file Geo.cpp.
Referenced by ApplicationOnShapes(), ApplyTransformationToVolume(), and ExtrudeSurface().
ApplyTransformationToVolume()
static void ApplyTransformationToVolume (double matrix[4][4], Volume * v) static
Definition at line 1445 of file Geo.cpp.
Referenced by ApplicationOnShapes().
Compare2Lists()
static int Compare2Lists (List_T * List1, List_T * List2, int(*)(const void *a, const void *b) fcmp) static
Definition at line 649 of file Geo.cpp.
Referenced by CompareTwoSurfaces(), RecognizeLineLoop(), and RecognizeSurfaceLoop().
CompareAbsCurve()
static int CompareAbsCurve (const void * a, const void * b) static
Definition at line 797 of file Geo.cpp.
Referenced by CompareTwoSurfaces(), and DeleteCurve().
CompareCurve()
int CompareCurve (const void * a, const void * b)
Definition at line 74 of file Geo.cpp.
Referenced by GEO_Internals::_allocateAll(), and ReplaceDuplicateCurves().
CompareEdgeLoop()
int CompareEdgeLoop (const void * a, const void * b)
Definition at line 67 of file Geo.cpp.
Referenced by GEO_Internals::_allocateAll().
ComparePhysicalGroup()
int ComparePhysicalGroup (const void * a, const void * b)
Definition at line 95 of file Geo.cpp.
Referenced by DeletePhysicalLine(), DeletePhysicalPoint(), DeletePhysicalSurface(), DeletePhysicalVolume(), and FindPhysicalGroup().
ComparePosition()
static int ComparePosition (const void * a, const void * b) static
Definition at line 37 of file Geo.cpp.
Referenced by CompareTwoPoints(), CreateCurve(), and ExtrudePoint().
CompareSurface()
int CompareSurface (const void * a, const void * b)
Definition at line 81 of file Geo.cpp.
Referenced by GEO_Internals::_allocateAll(), DeleteSurface(), RemoveDegenerateSurfaces(), and ReplaceDuplicateSurfaces().
CompareSurfaceLoop()
int CompareSurfaceLoop (const void * a, const void * b)
Definition at line 60 of file Geo.cpp.
Referenced by GEO_Internals::_allocateAll().
CompareTwoCurves()
static int CompareTwoCurves (const void * a, const void * b) static
Definition at line 1642 of file Geo.cpp.
Referenced by ReplaceDuplicateCurves().
CompareTwoPoints()
static int CompareTwoPoints (const void * a, const void * b) static
Definition at line 1629 of file Geo.cpp.
Referenced by ReplaceDuplicatePoints().
CompareTwoSurfaces()
static int CompareTwoSurfaces (const void * a, const void * b) static
Definition at line 1699 of file Geo.cpp.
Referenced by ReplaceDuplicateSurfaces().
CompareVertex()
int CompareVertex (const void * a, const void * b)
Definition at line 30 of file Geo.cpp.
Referenced by GEO_Internals::_allocateAll(), CompareTwoCurves(), DeletePoint(), InterpolateRuledSurface(), and ReplaceDuplicatePoints().
CompareVolume()
int CompareVolume (const void * a, const void * b)
Definition at line 88 of file Geo.cpp.
Referenced by GEO_Internals::_allocateAll().
CopyCurve()
static void CopyCurve (Curve * c, Curve * cc) static
Definition at line 804 of file Geo.cpp.
Referenced by DuplicateCurve().
CopySurface()
static void CopySurface (Surface * s, Surface * ss) static
Definition at line 869 of file Geo.cpp.
Referenced by DuplicateSurface().
CopyVertex()
static void CopyVertex (Vertex * v, Vertex * vv) static
Definition at line 769 of file Geo.cpp.
Referenced by DuplicateVertex().
CopyVolume()
static void CopyVolume (Volume * v, Volume * vv) static
Definition at line 926 of file Geo.cpp.
Referenced by DuplicateVolume().
CreateCurve()
Curve* CreateCurve (int Num, int Typ, int Order, List_T * Liste, List_T * Knots, int p1, int p2, double u1, double u2, bool & ok)
Definition at line 445 of file Geo.cpp.
Referenced by GEO_Internals::_addCompoundSpline(), _create_splitted_curve(), GEO_Internals::addBezier(), GEO_Internals::addBSpline(), GEO_Internals::addCircleArc(), GEO_Internals::addEllipseArc(), GEO_Internals::addLine(), GEO_Internals::addSpline(), CreateReversedCurve(), discreteEdge::discreteEdge(), DuplicateCurve(), GModel::exportDiscreteGEOInternals(), and ExtrudePoint().
CreateEdgeLoop()
EdgeLoop* CreateEdgeLoop (int Num, List_T * intlist)
Definition at line 168 of file Geo.cpp.
Referenced by GEO_Internals::addCurveLoop(), and GEO_Internals::addCurveLoops().
CreatePhysicalGroup()
PhysicalGroup* CreatePhysicalGroup (int Num, int typ, List_T * intlist)
Definition at line 142 of file Geo.cpp.
Referenced by GEO_Internals::modifyPhysicalGroup().
CreateReversedCurve()
Curve* CreateReversedCurve (Curve * c)
Definition at line 1147 of file Geo.cpp.
Referenced by GEO_Internals::_addCompoundSpline(), _create_splitted_curve(), GEO_Internals::addBezier(), GEO_Internals::addBSpline(), GEO_Internals::addCircleArc(), GEO_Internals::addEllipseArc(), GEO_Internals::addLine(), GEO_Internals::addSpline(), discreteEdge::discreteEdge(), DuplicateCurve(), GModel::exportDiscreteGEOInternals(), ExtrudePoint(), and SortEdgesInLoop().
CreateSurface()
Surface* CreateSurface (int Num, int Typ)
Definition at line 579 of file Geo.cpp.
Referenced by GEO_Internals::addDiscreteSurface(), GEO_Internals::addPlaneSurface(), GEO_Internals::addSurfaceFilling(), discreteFace::discreteFace(), DuplicateSurface(), GModel::exportDiscreteGEOInternals(), and ExtrudeCurve().
CreateSurfaceLoop()
SurfaceLoop* CreateSurfaceLoop (int Num, List_T * intlist)
Definition at line 193 of file Geo.cpp.
Referenced by GEO_Internals::addSurfaceLoop().
CreateVertex() [1/2]
Vertex* CreateVertex (int Num, double u, double v, gmshSurface * surf, double lc)
Definition at line 118 of file Geo.cpp.
CreateVertex() [2/2]
Vertex* CreateVertex (int Num, double X, double Y, double Z, double lc, double u)
Definition at line 106 of file Geo.cpp.
Referenced by GEO_Internals::_addCompoundSpline(), GEO_Internals::addVertex(), discreteVertex::discreteVertex(), DuplicateVertex(), GModel::exportDiscreteGEOInternals(), and IntersectCurvesWithSurface().
CreateVolume()
Volume* CreateVolume (int Num, int Typ)
Definition at line 617 of file Geo.cpp.
Referenced by GEO_Internals::addVolume(), discreteRegion::discreteRegion(), DuplicateVolume(), GModel::exportDiscreteGEOInternals(), and ExtrudeSurface().
DeleteCurve()
void DeleteCurve (int ip, bool recursive)
Definition at line 981 of file Geo.cpp.
Referenced by DeleteSurface(), DeleteVolume(), GEO_Internals::remove(), RemoveDegenerateCurves(), and SplitCurve().
DeletePhysicalLine()
void DeletePhysicalLine (int num)
Definition at line 1114 of file Geo.cpp.
Referenced by GEO_Internals::modifyPhysicalGroup().
DeletePhysicalPoint()
void DeletePhysicalPoint (int num)
Definition at line 1103 of file Geo.cpp.
Referenced by GEO_Internals::modifyPhysicalGroup().
DeletePhysicalSurface()
void DeletePhysicalSurface (int num)
Definition at line 1125 of file Geo.cpp.
Referenced by GEO_Internals::modifyPhysicalGroup().
DeletePhysicalVolume()
void DeletePhysicalVolume (int num)
Definition at line 1136 of file Geo.cpp.
Referenced by GEO_Internals::modifyPhysicalGroup().
DeletePoint()
void DeletePoint (int ip, bool recursive)
Definition at line 956 of file Geo.cpp.
Referenced by DeleteCurve(), DeleteSurface(), DeleteVolume(), and GEO_Internals::remove().
DeleteSurface()
void DeleteSurface (int is, bool recursive)
Definition at line 1018 of file Geo.cpp.
Referenced by DeleteVolume(), GEO_Internals::remove(), and RemoveDegenerateSurfaces().
DeleteVolume()
void DeleteVolume (int iv, bool recursive)
Definition at line 1064 of file Geo.cpp.
Referenced by GEO_Internals::remove(), and RemoveDegenerateVolumes().
DilatShapes()
bool DilatShapes (double X, double Y, double Z, double A, double B, double C, List_T * shapes)
Definition at line 1564 of file Geo.cpp.
Referenced by GEO_Internals::_transform().
direction()
static void direction (Vertex * v1, Vertex * v2, double d[3]) static
Definition at line 218 of file Geo.cpp.
Referenced by avl_foreach(), bestParabola(), changeReferential(), copyMesh(), EndCurve(), fillCorrespondingNodes(), HierarchicalBasisHcurlQuad::generateCurlBasis(), HierarchicalBasisHcurlQuad::generateHcurlBasis(), HierarchicalBasisHcurlBrick::generateHcurlBasis(), getNodeCopies(), goldenSection(), shortestParabola(), and signedDistancesPointsEllipseLine().
DuplicateCurve() [1/2]
Curve* DuplicateCurve (Curve * c)
Definition at line 830 of file Geo.cpp.
Referenced by GEO_Internals::copy(), DuplicateSurface(), and ExtrudeCurve().
DuplicateCurve() [2/2]
Curve* DuplicateCurve (GEdge * ge)
Definition at line 849 of file Geo.cpp.
DuplicateSurface() [1/2]
Surface* DuplicateSurface (GFace * gf, std::map< int, int > & source)
Definition at line 909 of file Geo.cpp.
DuplicateSurface() [2/2]
Surface* DuplicateSurface (Surface * s)
Definition at line 895 of file Geo.cpp.
Referenced by GEO_Internals::copy(), DuplicateVolume(), and ExtrudeSurface().
DuplicateVertex() [1/2]
Vertex* DuplicateVertex (GVertex * gv)
Definition at line 787 of file Geo.cpp.
DuplicateVertex() [2/2]
Vertex* DuplicateVertex (Vertex * v)
Definition at line 778 of file Geo.cpp.
Referenced by GEO_Internals::copy(), DuplicateCurve(), and ExtrudePoint().
DuplicateVolume()
Volume* DuplicateVolume (Volume * v)
Definition at line 942 of file Geo.cpp.
Referenced by GEO_Internals::copy().
EndCurve()
bool EndCurve (Curve * c)
Definition at line 225 of file Geo.cpp.
Referenced by GEO_Internals::addCircleArc(), GEO_Internals::addEllipseArc(), ApplicationOnShapes(), ApplyTransformationToCurve(), CopyCurve(), CreateCurve(), CreateReversedCurve(), GModel::exportDiscreteGEOInternals(), ExtrudePoint(), and ReplaceDuplicateCurves().
EndSurface()
void EndSurface (Surface * s)
Definition at line 426 of file Geo.cpp.
Referenced by GEO_Internals::addPlaneSurface(), GEO_Internals::addSurfaceFilling(), ApplyTransformationToSurface(), CopySurface(), GModel::exportDiscreteGEOInternals(), and ExtrudeCurve().
ExtrudeCurve()
int ExtrudeCurve (int type, int ic, double T0, double T1, double T2, double A0, double A1, double A2, double X0, double X1, double X2, double alpha, Surface ** ps, int final, ExtrudeParams * e)
Definition at line 2757 of file Geo.cpp.
Referenced by ExtrudeShapes(), and ExtrudeSurface().
ExtrudePoint()
int ExtrudePoint (int type, int ip, double T0, double T1, double T2, double A0, double A1, double A2, double X0, double X1, double X2, double alpha, Curve ** pc, Curve ** prc, int final, ExtrudeParams * e)
Definition at line 2570 of file Geo.cpp.
Referenced by ExtrudeCurve(), and ExtrudeShapes().
ExtrudeShapes()
void ExtrudeShapes (int type, List_T * list_in, double T0, double T1, double T2, double A0, double A1, double A2, double X0, double X1, double X2, double alpha, ExtrudeParams * e, List_T * list_out)
Definition at line 3221 of file Geo.cpp.
Referenced by GEO_Internals::_extrude().
ExtrudeSurface()
int ExtrudeSurface (int type, int is, double T0, double T1, double T2, double A0, double A1, double A2, double X0, double X1, double X2, double alpha, Volume ** pv, ExtrudeParams * e)
Definition at line 2987 of file Geo.cpp.
Referenced by ExtrudeShapes().
FindCurve() [1/2]
Curve* FindCurve (int inum)
Definition at line 703 of file Geo.cpp.
FindCurve() [2/2]
static Curve* FindCurve (int inum, Tree_T * t) static
Definition at line 694 of file Geo.cpp.
Referenced by GEO_Internals::_addCompoundSpline(), GEO_Internals::addBezier(), GEO_Internals::addBSpline(), GEO_Internals::addCircleArc(), GEO_Internals::addCurveLoops(), GEO_Internals::addEllipseArc(), GEO_Internals::addLine(), GEO_Internals::addSpline(), ApplicationOnShapes(), ApplyTransformationToSurface(), GEO_Internals::copy(), DeleteCurve(), GModel::exportDiscreteGEOInternals(), ExtrudeCurve(), ExtrudePoint(), ExtrudeShapes(), ExtrudeSurface(), FindCurve(), InterpolateCurve(), InterpolateExtrudedSurface(), IntersectCurvesWithSurface(), ReplaceDuplicateCurves(), GEO_Internals::setDegenerated(), GEO_Internals::setReverseMesh(), SetSurfaceGeneratrices(), GEO_Internals::setTransfiniteLine(), SortEdgesInLoop(), SplitCurve(), and GEO_Internals::synchronize().
FindEdgeLoop()
EdgeLoop* FindEdgeLoop (int inum)
Definition at line 733 of file Geo.cpp.
Referenced by GEO_Internals::addCurveLoop(), GEO_Internals::addSurfaceFilling(), and SetSurfaceGeneratrices().
FindPhysicalGroup()
PhysicalGroup* FindPhysicalGroup (int num, int type)
Definition at line 755 of file Geo.cpp.
Referenced by DeletePhysicalLine(), DeletePhysicalPoint(), DeletePhysicalSurface(), DeletePhysicalVolume(), and GEO_Internals::modifyPhysicalGroup().
FindPoint() [1/2]
Vertex* FindPoint (int inum)
Definition at line 689 of file Geo.cpp.
FindPoint() [2/2]
static Vertex* FindPoint (int inum, Tree_T * t) static
Definition at line 680 of file Geo.cpp.
Referenced by GEO_Internals::addSurfaceFilling(), GEO_Internals::addVertex(), ApplicationOnShapes(), GEO_Internals::copy(), CreateCurve(), DeletePoint(), GModel::exportDiscreteGEOInternals(), FindPoint(), GEO_Internals::getVertex(), GEO_Internals::mergeVertices(), GEO_Internals::newGeometryPolarSphere(), GEO_Internals::newGeometrySphere(), ReplaceDuplicatePoints(), ReplaceDuplicatePointsNew(), GEO_Internals::setMeshSize(), GEO_Internals::setTransfiniteSurface(), GEO_Internals::setTransfiniteVolume(), and GEO_Internals::synchronize().
FindSurface() [1/2]
Surface* FindSurface (int inum)
Definition at line 717 of file Geo.cpp.
FindSurface() [2/2]
static Surface* FindSurface (int inum, Tree_T * t) static
Definition at line 708 of file Geo.cpp.
Referenced by GEO_Internals::addDiscreteSurface(), GEO_Internals::addPlaneSurface(), GEO_Internals::addSurfaceFilling(), ApplicationOnShapes(), GEO_Internals::copy(), DeleteSurface(), GModel::exportDiscreteGEOInternals(), ExtrudeShapes(), ExtrudeSurface(), FindSurface(), IntersectCurvesWithSurface(), ReplaceDuplicateSurfaces(), discreteFace::resetMeshAttributes(), GEO_Internals::setMeshAlgorithm(), GEO_Internals::setMeshSizeFromBoundary(), GEO_Internals::setRecombine(), GEO_Internals::setReverseMesh(), GEO_Internals::setSmoothing(), GEO_Internals::setTransfiniteSurface(), SetVolumeSurfaces(), and GEO_Internals::synchronize().
FindSurfaceLoop()
SurfaceLoop* FindSurfaceLoop (int inum)
Definition at line 744 of file Geo.cpp.
Referenced by GEO_Internals::addSurfaceLoop(), and SetVolumeSurfaces().
FindVolume()
Volume* FindVolume (int inum)
Definition at line 722 of file Geo.cpp.
Referenced by GEO_Internals::addVolume(), ApplicationOnShapes(), GEO_Internals::copy(), DeleteVolume(), GEO_Internals::setRecombine(), GEO_Internals::setTransfiniteVolume(), GEO_Internals::setTransfiniteVolumeQuadTri(), and GEO_Internals::synchronize().
FreeCurve()
void FreeCurve (void * a, void * b)
Definition at line 567 of file Geo.cpp.
Referenced by GEO_Internals::_freeAll(), and CreateReversedCurve().
FreeEdgeLoop()
void FreeEdgeLoop (void * a, void * b)
Definition at line 183 of file Geo.cpp.
Referenced by GEO_Internals::_freeAll().
FreePhysicalGroup()
void FreePhysicalGroup (void * a, void * b)
Definition at line 158 of file Geo.cpp.
Referenced by GEO_Internals::_freeAll(), and GEO_Internals::resetPhysicalGroups().
FreeSurface()
void FreeSurface (void * a, void * b)
Definition at line 604 of file Geo.cpp.
Referenced by GEO_Internals::_freeAll().
FreeSurfaceLoop()
void FreeSurfaceLoop (void * a, void * b)
Definition at line 208 of file Geo.cpp.
Referenced by GEO_Internals::_freeAll().
FreeVertex()
void FreeVertex (void * a, void * b)
Definition at line 133 of file Geo.cpp.
Referenced by GEO_Internals::_freeAll().
FreeVolume()
void FreeVolume (void * a, void * b)
Definition at line 635 of file Geo.cpp.
Referenced by GEO_Internals::_freeAll().
GramSchmidt()
static void GramSchmidt (double v1[3], double v2[3], double v3[3]) static
Definition at line 1303 of file Geo.cpp.
Referenced by SetRotationMatrix().
intersectCS()
static bool intersectCS (fullVector< double > & uvt, fullVector< double > & res, void * data) static
Definition at line 3548 of file Geo.cpp.
Referenced by IntersectCurvesWithSurface().
IntersectCurvesWithSurface()
bool IntersectCurvesWithSurface (List_T * curve_ids, int surface_id, List_T * shapes)
Definition at line 3560 of file Geo.cpp.
Referenced by GEO_Internals::intersectCurvesWithSurface().
MaxNumCurve()
static void MaxNumCurve (void * a, void * b) static
Definition at line 1738 of file Geo.cpp.
Referenced by ReplaceDuplicateCurves().
MaxNumPoint()
static void MaxNumPoint (void * a, void * b) static
Definition at line 1731 of file Geo.cpp.
Referenced by ReplaceDuplicatePoints().
MaxNumSurface()
static void MaxNumSurface (void * a, void * b) static
Definition at line 1745 of file Geo.cpp.
Referenced by ReplaceDuplicateSurfaces().
NEWCURVE()
int NEWCURVE ()
Definition at line 3784 of file Geo.cpp.
Referenced by _create_splitted_curve(), DuplicateCurve(), and ExtrudePoint().
NEWCURVELOOP()
int NEWCURVELOOP ()
Definition at line 3796 of file Geo.cpp.
NEWFIELD()
int NEWFIELD ()
Definition at line 3866 of file Geo.cpp.
NEWPHYSICAL()
int NEWPHYSICAL ()
Definition at line 3875 of file Geo.cpp.
NEWPOINT()
int NEWPOINT ()
Definition at line 3776 of file Geo.cpp.
Referenced by DuplicateVertex(), and IntersectCurvesWithSurface().
NEWREG()
int NEWREG ()
Definition at line 3846 of file Geo.cpp.
Referenced by NEWCURVE(), NEWCURVELOOP(), NEWPHYSICAL(), NEWSURFACE(), NEWSURFACELOOP(), and NEWVOLUME().
NEWSURFACE()
int NEWSURFACE ()
Definition at line 3809 of file Geo.cpp.
Referenced by DuplicateSurface(), ExtrudeCurve(), and ExtrudeSurface().
NEWSURFACELOOP()
int NEWSURFACELOOP ()
Definition at line 3821 of file Geo.cpp.
NEWVOLUME()
int NEWVOLUME ()
Definition at line 3834 of file Geo.cpp.
Referenced by DuplicateVolume(), and ExtrudeSurface().
ProjectPointOnSurface()
bool ProjectPointOnSurface (Surface * s, Vertex & p, double uv[2])
Definition at line 3340 of file Geo.cpp.
Referenced by gmshFace::closestPoint().
projectPS()
static bool projectPS (fullVector< double > & x, fullVector< double > & res, void * data) static
Definition at line 3324 of file Geo.cpp.
Referenced by ProjectPointOnSurface().
ProtudeXYZ()
void ProtudeXYZ (double & x, double & y, double & z, ExtrudeParams * e)
Definition at line 2542 of file Geo.cpp.
Referenced by ExtrudeParams::Extrude().
RecognizeLineLoop()
int RecognizeLineLoop (List_T * liste, int * loop)
Definition at line 1214 of file Geo.cpp.
Referenced by scriptAddCurveLoop().
RecognizeSurfaceLoop()
int RecognizeSurfaceLoop (List_T * liste, int * loop)
Definition at line 1232 of file Geo.cpp.
Referenced by scriptAddSurfaceLoop().
RemoveDegenerateCurves()
static void RemoveDegenerateCurves () static
Definition at line 2216 of file Geo.cpp.
Referenced by ReplaceAllDuplicates().
RemoveDegenerateSurfaces()
static void RemoveDegenerateSurfaces () static
Definition at line 2297 of file Geo.cpp.
Referenced by ReplaceAllDuplicates().
RemoveDegenerateVolumes()
static void RemoveDegenerateVolumes () static
Definition at line 2255 of file Geo.cpp.
Referenced by ReplaceAllDuplicates().
ReplaceAllDuplicates() [1/2]
void ReplaceAllDuplicates ()
Definition at line 2527 of file Geo.cpp.
ReplaceAllDuplicates() [2/2]
static void ReplaceAllDuplicates (std::vector< std::map< int, int > > & report) static
Definition at line 2507 of file Geo.cpp.
Referenced by DilatShapes(), ExtrudeCurve(), ExtrudePoint(), ExtrudeSurface(), GEO_Internals::mergeVertices(), GEO_Internals::removeAllDuplicates(), ReplaceAllDuplicates(), RotateShapes(), SymmetryShapes(), and TranslateShapes().
ReplaceAllDuplicatesNew()
void ReplaceAllDuplicatesNew (double tol)
Definition at line 2534 of file Geo.cpp.
ReplaceDuplicateCurves()
static void ReplaceDuplicateCurves (std::map< int, int > * c_report = nullptr) static
Definition at line 2036 of file Geo.cpp.
Referenced by ReplaceAllDuplicates(), and ReplaceAllDuplicatesNew().
ReplaceDuplicatePoints()
static void ReplaceDuplicatePoints (std::map< int, int > * v_report = nullptr) static
Definition at line 1859 of file Geo.cpp.
Referenced by ReplaceAllDuplicates().
ReplaceDuplicatePointsNew()
static void ReplaceDuplicatePointsNew (double tol = -1.) static
Definition at line 1752 of file Geo.cpp.
Referenced by ReplaceAllDuplicatesNew(), and ReplaceDuplicatePoints().
ReplaceDuplicateSurfaces()
static void ReplaceDuplicateSurfaces (std::map< int, int > * s_report = nullptr) static
Definition at line 2370 of file Geo.cpp.
Referenced by ReplaceAllDuplicates(), and ReplaceAllDuplicatesNew().
RotateShapes()
bool RotateShapes (double Ax, double Ay, double Az, double Px, double Py, double Pz, double alpha, List_T * shapes)
Definition at line 1580 of file Geo.cpp.
Referenced by GEO_Internals::_transform().
SetDilatationMatrix()
void SetDilatationMatrix (double matrix[4][4], double T[3], double A, double B, double C)
Definition at line 1282 of file Geo.cpp.
Referenced by DilatShapes().
SetRotationMatrix()
void SetRotationMatrix (double matrix[4][4], double Axe[3], double alpha)
Definition at line 1316 of file Geo.cpp.
Referenced by ExtrudeCurve(), ExtrudePoint(), ExtrudeSurface(), ExtrudeParams::GetAffineTransform(), ProtudeXYZ(), and RotateShapes().
SetSurfaceGeneratrices()
bool SetSurfaceGeneratrices (Surface * s, List_T * loops)
Definition at line 3674 of file Geo.cpp.
Referenced by GEO_Internals::addPlaneSurface(), and GEO_Internals::addSurfaceFilling().
SetSymmetryMatrix()
void SetSymmetryMatrix (double matrix[4][4], double A, double B, double C, double D)
Definition at line 1258 of file Geo.cpp.
Referenced by SymmetryShapes().
SetTranslationMatrix()
void SetTranslationMatrix (double matrix[4][4], double T[3])
Definition at line 1250 of file Geo.cpp.
Referenced by ExtrudeCurve(), ExtrudePoint(), ExtrudeSurface(), ExtrudeParams::GetAffineTransform(), ProtudeXYZ(), RotateShapes(), and TranslateShapes().
SetVolumeSurfaces()
bool SetVolumeSurfaces (Volume * v, List_T * loops)
Definition at line 3734 of file Geo.cpp.
Referenced by GEO_Internals::addVolume().
SortEdgesInLoop()
bool SortEdgesInLoop (int num, List_T * edges, bool reorient)
Definition at line 3597 of file Geo.cpp.
Referenced by GEO_Internals::addCurveLoop().
SplitCurve()
bool SplitCurve (int line_id, List_T * vertices_id, List_T * curves)
Definition at line 3433 of file Geo.cpp.
Referenced by GEO_Internals::splitCurve().
SymmetryShapes()
bool SymmetryShapes (double A, double B, double C, double D, List_T * shapes)
Definition at line 1608 of file Geo.cpp.
Referenced by GEO_Internals::_transform().
TranslateShapes()
bool TranslateShapes (double X, double Y, double Z, List_T * shapes)
Definition at line 1549 of file Geo.cpp.
Referenced by GEO_Internals::_transform().
vecmat4x4()
static void vecmat4x4 (double mat[4][4], double vec[4], double res[4]) static
Definition at line 1381 of file Geo.cpp.
Referenced by ApplyTransformationToPointAlways().
Variable Documentation
ListOfTransformedPoints
List_T* ListOfTransformedPoints = nullptr static
Definition at line 28 of file Geo.cpp.
Referenced by ApplicationOnShapes(), ApplyTransformationToPoint(), ExtrudeCurve(), ExtrudePoint(), ExtrudeSurface(), and ProtudeXYZ().