gmsh-TingyuanDoc: src/geo/GeoInterpolation.h File Reference
GeoInterpolation.h File Reference
#include "SPoint2.h"
Functions
Vertex InterpolateCurve (Curve *Curve, double u, int derivee)
Vertex InterpolateSurface (Surface *s, double u, double v, int derivee, int u_v)
SPoint2 InterpolateCubicSpline (Vertex *v[4], double t, double mat[4][4], double t1, double t2, gmshSurface *s, int derivee)
Function Documentation
InterpolateCubicSpline()
SPoint2 InterpolateCubicSpline (Vertex * v[4], double t, double mat[4][4], double t1, double t2, gmshSurface * s, int derivee)
Definition at line 106 of file GeoInterpolation.cpp.
InterpolateCurve()
Vertex InterpolateCurve (Curve * Curve, double u, int derivee)
Definition at line 441 of file GeoInterpolation.cpp.
Referenced by GEO_Internals::_addCompoundSpline(), gmshFace::containsPoint(), gmshEdge::firstDer(), InterpolateCurve(), InterpolateExtrudedSurface(), InterpolateRuledSurface(), intersectCS(), IntersectCurvesWithSurface(), gmshFace::normal(), gmshEdge::point(), and gmshEdge::secondDer().
InterpolateSurface()
Vertex InterpolateSurface (Surface * s, double u, double v, int derivee, int u_v)
Definition at line 958 of file GeoInterpolation.cpp.
Referenced by gmshFace::firstDer(), InterpolateSurface(), intersectCS(), gmshFace::normal(), gmshFace::point(), ProjectPointOnSurface(), projectPS(), and gmshFace::secondDer().