gmsh-TingyuanDoc: src/common/GmshMessage.cpp File Reference
GmshMessage.cpp File Reference
#include "GmshConfig.h"
#include <unistd.h>
#include <clocale>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <time.h>
#include <sys/stat.h>
#include "GmshMessage.h"
#include "GmshSocket.h"
#include "GmshGlobal.h"
#include "GModel.h"
#include "Options.h"
#include "Context.h"
#include "OpenFile.h"
#include "StringUtils.h"
#include "OS.h"
#include "gmshLocalNetworkClient.h"
Functions
static void addGmshPathToEnvironmentVar (const std::string &name)
static int streamIsFile (FILE *stream)
static int streamIsVT100 (FILE *stream)
Function Documentation
addGmshPathToEnvironmentVar()
static void addGmshPathToEnvironmentVar (const std::string & name) static
Definition at line 104 of file GmshMessage.cpp.
Referenced by Msg::Initialize().
streamIsFile()
static int streamIsFile (FILE * stream) static
Definition at line 393 of file GmshMessage.cpp.
Referenced by Msg::Direct(), Msg::Error(), Msg::PrintErrorCounter(), Msg::ProgressMeter(), and Msg::Warning().
streamIsVT100()
static int streamIsVT100 (FILE * stream) static
Definition at line 403 of file GmshMessage.cpp.
Referenced by Msg::Direct(), Msg::Error(), Msg::PrintErrorCounter(), and Msg::Warning().