gmsh-TingyuanDoc: src/common/GmshGlobal.h File Reference
GmshGlobal.h File Reference
#include <string>
#include "GmshMessage.h"
Macros
#define GMSH_API
Functions
int GmshInitialize (int argc=0, char **argv=nullptr, bool readConfigFiles=false, bool exitOnCommandLineError=true)
int GmshSetMessageHandler (GmshMessage *callback)
GmshMessage * GmshGetMessageHandler ()
int GmshSetBoundingBox (double xmin, double xmax, double ymin, double ymax, double zmin, double zmax)
int GmshSetOption (const std::string &category, const std::string &name, std::string value, int index=0)
int GmshSetOption (const std::string &category, const std::string &name, double value, int index=0)
int GmshSetOption (const std::string &category, const std::string &name, unsigned int value, int index=0)
void GmshSetStringOption (const std::string &category, const std::string &name, std::string value, int index=0)
void GmshSetNumberOption (const std::string &category, const std::string &name, double value, int index=0)
void GmshSetColorOption (const std::string &category, const std::string &name, unsigned int value, int index=0)
int GmshGetOption (const std::string &category, const std::string &name, std::string &value, int index=0)
int GmshGetOption (const std::string &category, const std::string &name, double &value, int index=0)
int GmshGetOption (const std::string &category, const std::string &name, unsigned int &value, int index=0)
std::string GmshGetStringOption (const std::string &category, const std::string &name, int index=0)
double GmshGetNumberOption (const std::string &category, const std::string &name, int index=0)
unsigned int GmshGetColorOption (const std::string &category, const std::string &name, int index=0)
int GmshRestoreDefaultOptions ()
int GmshOpenProject (const std::string &fileName)
int GmshClearProject ()
int GmshMergeFile (const std::string &fileName)
int GmshMergePostProcessingFile (const std::string &fileName)
int GmshWriteFile (const std::string &fileName)
int GmshFinalize ()
int GmshBatch ()
int GmshFLTK (int argc=0, char **argv=nullptr)
GMSH_API int GmshMainBatch (int argc, char **argv)
GMSH_API int GmshMainFLTK (int argc, char **argv)
Macro Definition Documentation
GMSH_API
#define GMSH_API
Definition at line 66 of file GmshGlobal.h.
Function Documentation
GmshBatch()
int GmshBatch ()
Definition at line 278 of file GmshGlobal.cpp.
Referenced by GmshMainBatch(), and GmshMainFLTK().
GmshClearProject()
int GmshClearProject ()
Definition at line 219 of file GmshGlobal.cpp.
GmshFinalize()
int GmshFinalize ()
Definition at line 243 of file GmshGlobal.cpp.
Referenced by GmshMainBatch(), and GmshMainFLTK().
GmshFLTK()
int GmshFLTK (int argc = 0, char ** argv = nullptr)
Definition at line 388 of file GmshGlobal.cpp.
Referenced by GmshMainFLTK().
GmshGetColorOption()
unsigned int GmshGetColorOption (const std::string & category, const std::string & name, int index = 0)
Definition at line 198 of file GmshGlobal.cpp.
GmshGetMessageHandler()
GmshMessage* GmshGetMessageHandler ()
Definition at line 110 of file GmshGlobal.cpp.
GmshGetNumberOption()
double GmshGetNumberOption (const std::string & category, const std::string & name, int index = 0)
Definition at line 190 of file GmshGlobal.cpp.
GmshGetOption() [1/3]
int GmshGetOption (const std::string & category, const std::string & name, double & value, int index = 0)
Definition at line 168 of file GmshGlobal.cpp.
GmshGetOption() [2/3]
int GmshGetOption (const std::string & category, const std::string & name, std::string & value, int index = 0)
Definition at line 161 of file GmshGlobal.cpp.
GmshGetOption() [3/3]
int GmshGetOption (const std::string & category, const std::string & name, unsigned int & value, int index = 0)
Definition at line 175 of file GmshGlobal.cpp.
GmshGetStringOption()
std::string GmshGetStringOption (const std::string & category, const std::string & name, int index = 0)
Definition at line 182 of file GmshGlobal.cpp.
GmshInitialize()
int GmshInitialize (int argc = 0, char ** argv = nullptr, bool readConfigFiles = false, bool exitOnCommandLineError = true)
Definition at line 65 of file GmshGlobal.cpp.
Referenced by GmshMainBatch(), and GmshMainFLTK().
GmshMainBatch()
GMSH_API int GmshMainBatch (int argc, char ** argv)
Definition at line 485 of file GmshGlobal.cpp.
Referenced by main().
GmshMainFLTK()
GMSH_API int GmshMainFLTK (int argc, char ** argv)
Definition at line 505 of file GmshGlobal.cpp.
Referenced by main().
GmshMergeFile()
int GmshMergeFile (const std::string & fileName)
Definition at line 225 of file GmshGlobal.cpp.
GmshMergePostProcessingFile()
int GmshMergePostProcessingFile (const std::string & fileName)
Definition at line 230 of file GmshGlobal.cpp.
GmshOpenProject()
int GmshOpenProject (const std::string & fileName)
Definition at line 213 of file GmshGlobal.cpp.
GmshRestoreDefaultOptions()
int GmshRestoreDefaultOptions ()
Definition at line 206 of file GmshGlobal.cpp.
GmshSetBoundingBox()
int GmshSetBoundingBox (double xmin, double xmax, double ymin, double ymax, double zmin, double zmax)
Definition at line 112 of file GmshGlobal.cpp.
GmshSetColorOption()
void GmshSetColorOption (const std::string & category, const std::string & name, unsigned int value, int index = 0)
Definition at line 154 of file GmshGlobal.cpp.
GmshSetMessageHandler()
int GmshSetMessageHandler (GmshMessage * callback)
Definition at line 104 of file GmshGlobal.cpp.
GmshSetNumberOption()
void GmshSetNumberOption (const std::string & category, const std::string & name, double value, int index = 0)
Definition at line 147 of file GmshGlobal.cpp.
Referenced by GetOtherOption().
GmshSetOption() [1/3]
int GmshSetOption (const std::string & category, const std::string & name, double value, int index = 0)
Definition at line 126 of file GmshGlobal.cpp.
GmshSetOption() [2/3]
int GmshSetOption (const std::string & category, const std::string & name, std::string value, int index = 0)
Definition at line 119 of file GmshGlobal.cpp.
GmshSetOption() [3/3]
int GmshSetOption (const std::string & category, const std::string & name, unsigned int value, int index = 0)
Definition at line 133 of file GmshGlobal.cpp.
GmshSetStringOption()
void GmshSetStringOption (const std::string & category, const std::string & name, std::string value, int index = 0)
Definition at line 140 of file GmshGlobal.cpp.
Referenced by GetOtherOption().
GmshWriteFile()
int GmshWriteFile (const std::string & fileName)
Definition at line 237 of file GmshGlobal.cpp.