gmsh-TingyuanDoc: src/mesh/HighOrder.h File Reference
HighOrder.h File Reference
#include <vector>
Functions
void SetOrder1 (GModel *m, bool onlyVisible=false, bool skipDiscrete=false)
void SetOrderN (GModel *m, int order, bool linear=true, bool incomplete=false, bool onlyVisible=false)
void checkHighOrderTriangles (const char *cc, GModel *m, std::vector< MElement * > &bad, double &minJGlob)
void checkHighOrderTetrahedron (const char *cc, GModel *m, std::vector< MElement * > &bad, double &minJGlob)
Function Documentation
checkHighOrderTetrahedron()
void checkHighOrderTetrahedron (const char * cc, GModel * m, std::vector< MElement * > & bad, double & minJGlob)
Definition at line 1310 of file HighOrder.cpp.
Referenced by SetOrderN().
checkHighOrderTriangles()
void checkHighOrderTriangles (const char * cc, GModel * m, std::vector< MElement * > & bad, double & minJGlob)
Definition at line 1261 of file HighOrder.cpp.
Referenced by SetOrderN().
SetOrder1()
void SetOrder1 (GModel * m, bool onlyVisible = false, bool skipDiscrete = false)
Definition at line 1233 of file HighOrder.cpp.
Referenced by GenerateMesh(), and GModel::setOrderN().
SetOrderN()
void SetOrderN (GModel * m, int order, bool linear = true, bool incomplete = false, bool onlyVisible = false)
Definition at line 1396 of file HighOrder.cpp.
Referenced by GenerateMesh(), RefineMesh(), and GModel::setOrderN().