gmsh-TingyuanDoc: src/numeric/InnerVertexPlacement.h File Reference
InnerVertexPlacement.h File Reference
#include "fullMatrix.h"
Functions
fullMatrix< double > * getInnerVertexPlacement (int type, int order)
fullMatrix< double > gmshGenerateInnerVertexPlacementTriangle (int order)
fullMatrix< double > gmshGenerateInnerVertexPlacementQuadrangle (int order)
fullMatrix< double > gmshGenerateInnerVertexPlacementTetrahedron (int order)
fullMatrix< double > gmshGenerateInnerVertexPlacementHexahedron (int order)
fullMatrix< double > gmshGenerateInnerVertexPlacementPrism (int order)
fullMatrix< double > gmshGenerateInnerVertexPlacementPyramid (int order)
fullMatrix< double > gmshGenerateInnerVertexPlacementTriangleLinear (int order, int dir)
fullMatrix< double > gmshGenerateInnerVertexPlacementQuadrangleLinear (int order)
fullMatrix< double > gmshGenerateInnerVertexPlacementTetrahedronLinear (int order, int dir)
fullMatrix< double > gmshGenerateInnerVertexPlacementHexahedronLinear (int order, int dir)
fullMatrix< double > gmshGenerateInnerVertexPlacementPrismLinear (int order, int dir)
Function Documentation
getInnerVertexPlacement()
fullMatrix<double>* getInnerVertexPlacement (int type, int order)
Definition at line 33 of file InnerVertexPlacement.cpp.
Referenced by getFaceVertices(), and getVolumeVertices().
gmshGenerateInnerVertexPlacementHexahedron()
fullMatrix<double> gmshGenerateInnerVertexPlacementHexahedron (int order)
Definition at line 213 of file InnerVertexPlacement.cpp.
Referenced by getInnerVertexPlacement().
gmshGenerateInnerVertexPlacementHexahedronLinear()
fullMatrix<double> gmshGenerateInnerVertexPlacementHexahedronLinear (int order, int dir)
Definition at line 560 of file InnerVertexPlacement.cpp.
gmshGenerateInnerVertexPlacementPrism()
fullMatrix<double> gmshGenerateInnerVertexPlacementPrism (int order)
Definition at line 275 of file InnerVertexPlacement.cpp.
Referenced by getInnerVertexPlacement().
gmshGenerateInnerVertexPlacementPrismLinear()
fullMatrix<double> gmshGenerateInnerVertexPlacementPrismLinear (int order, int dir)
Definition at line 611 of file InnerVertexPlacement.cpp.
gmshGenerateInnerVertexPlacementPyramid()
fullMatrix<double> gmshGenerateInnerVertexPlacementPyramid (int order)
Definition at line 342 of file InnerVertexPlacement.cpp.
Referenced by getInnerVertexPlacement().
gmshGenerateInnerVertexPlacementQuadrangle()
fullMatrix<double> gmshGenerateInnerVertexPlacementQuadrangle (int order)
Definition at line 108 of file InnerVertexPlacement.cpp.
Referenced by getInnerVertexPlacement().
gmshGenerateInnerVertexPlacementQuadrangleLinear()
fullMatrix<double> gmshGenerateInnerVertexPlacementQuadrangleLinear (int order)
Definition at line 461 of file InnerVertexPlacement.cpp.
gmshGenerateInnerVertexPlacementTetrahedron()
fullMatrix<double> gmshGenerateInnerVertexPlacementTetrahedron (int order)
Definition at line 147 of file InnerVertexPlacement.cpp.
Referenced by getInnerVertexPlacement().
gmshGenerateInnerVertexPlacementTetrahedronLinear()
fullMatrix<double> gmshGenerateInnerVertexPlacementTetrahedronLinear (int order, int dir)
Definition at line 493 of file InnerVertexPlacement.cpp.
gmshGenerateInnerVertexPlacementTriangle()
fullMatrix<double> gmshGenerateInnerVertexPlacementTriangle (int order)
Definition at line 66 of file InnerVertexPlacement.cpp.
Referenced by getInnerVertexPlacement().
gmshGenerateInnerVertexPlacementTriangleLinear()
fullMatrix<double> gmshGenerateInnerVertexPlacementTriangleLinear (int order, int dir)
Definition at line 411 of file InnerVertexPlacement.cpp.