gmsh-TingyuanDoc: src/numeric/Iso.cpp File Reference
Iso.cpp File Reference
#include "Numeric.h"
Functions
static void affect (double *xi, double *yi, double *zi, int i, double *xp, double *yp, double *zp, int j)
double InterpolateIso (double *X, double *Y, double *Z, double *Val, double V, int I1, int I2, double *XI, double *YI, double *ZI)
int IsoLine (double *X, double *Y, double *Z, double *Val, double V, double *Xp, double *Yp, double *Zp)
int IsoTriangle (double *X, double *Y, double *Z, double *Val, double V, double *Xp, double *Yp, double *Zp)
int IsoSimplex (double *X, double *Y, double *Z, double *Val, double V, double *Xp, double *Yp, double *Zp, double n[3])
int CutLine (double *X, double *Y, double *Z, double *Val, double V1, double V2, double *Xp2, double *Yp2, double *Zp2, double *Vp2)
int CutTriangle (double *X, double *Y, double *Z, double *Val, double V1, double V2, double *Xp2, double *Yp2, double *Zp2, double *Vp2)
Function Documentation
affect()
static void affect (double * xi, double * yi, double * zi, int i, double * xp, double * yp, double * zp, int j) static
Definition at line 8 of file Iso.cpp.
Referenced by IsoSimplex().
CutLine()
int CutLine (double * X, double * Y, double * Z, double * Val, double V1, double V2, double * Xp2, double * Yp2, double * Zp2, double * Vp2)
Definition at line 180 of file Iso.cpp.
Referenced by addScalarLine().
CutTriangle()
int CutTriangle (double * X, double * Y, double * Z, double * Val, double V1, double V2, double * Xp2, double * Yp2, double * Zp2, double * Vp2)
Definition at line 233 of file Iso.cpp.
Referenced by addScalarTriangle().
InterpolateIso()
double InterpolateIso (double * X, double * Y, double * Z, double * Val, double V, int I1, int I2, double * XI, double * YI, double * ZI)
Definition at line 16 of file Iso.cpp.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), CutLine(), CutTriangle(), IsoLine(), IsoSimplex(), and IsoTriangle().
IsoLine()
int IsoLine (double * X, double * Y, double * Z, double * Val, double V, double * Xp, double * Yp, double * Zp)
Definition at line 36 of file Iso.cpp.
Referenced by addScalarLine().
IsoSimplex()
int IsoSimplex (double * X, double * Y, double * Z, double * Val, double V, double * Xp, double * Yp, double * Zp, double n[3])
Definition at line 75 of file Iso.cpp.
Referenced by addScalarTetrahedron().
IsoTriangle()
int IsoTriangle (double * X, double * Y, double * Z, double * Val, double V, double * Xp, double * Yp, double * Zp)
Definition at line 50 of file Iso.cpp.
Referenced by addScalarTriangle().