gmsh-TingyuanDoc: src/plugin/Lambda2.cpp File Reference
Lambda2.cpp File Reference
#include "Lambda2.h"
#include "Numeric.h"
Functions
GMSH_Plugin * GMSH_RegisterLambda2Plugin ()
static int inv3x3tran (double mat[3][3], double inv[3][3], double *det)
static void eigen (std::vector< double > &inList, int inNb, std::vector< double > &outList, int *outNb, int nbTime, int nbNod, int nbComp, int lam)
Variables
StringXNumber Lambda2Options_Number []
Function Documentation
eigen()
static void eigen (std::vector< double > & inList, int inNb, std::vector< double > & outList, int * outNb, int nbTime, int nbNod, int nbComp, int lam) static
Definition at line 69 of file Lambda2.cpp.
Referenced by GMSH_Lambda2Plugin::execute().
GMSH_RegisterLambda2Plugin()
GMSH_Plugin* GMSH_RegisterLambda2Plugin ()
Definition at line 14 of file Lambda2.cpp.
Referenced by PluginManager::registerDefaultPlugins().
inv3x3tran()
static int inv3x3tran (double mat[3][3], double inv[3][3], double * det) static
Definition at line 47 of file Lambda2.cpp.
Referenced by eigen().
Variable Documentation
Lambda2Options_Number
StringXNumber Lambda2Options_Number[]
Initial value:
= {
  {GMSH_FULLRC, "Eigenvalue", nullptr, 2.},
  {GMSH_FULLRC, "View", nullptr, -1.}}
Definition at line 9 of file Lambda2.cpp.
Referenced by GMSH_Lambda2Plugin::execute(), GMSH_Lambda2Plugin::getNbOptions(), and GMSH_Lambda2Plugin::getOption().