gmsh-TingyuanDoc: src/plugin/Levelset.cpp File Reference
Levelset.cpp File Reference
#include "Levelset.h"
#include "MakeSimplex.h"
#include "Numeric.h"
#include "Iso.h"
#include "adaptiveData.h"
#include "GmshDefines.h"
#include "PViewOptions.h"
Functions
static int numSimplexDec (int type)
static void getSimplexDec (int numNodes, int numEdges, int type, int i, int &n0, int &n1, int &n2, int &n3, int &nn, int &ne)
static void affect (double *xpi, double *ypi, double *zpi, double valpi[12][9], int epi[12], int i, double *xp, double *yp, double *zp, double valp[12][9], int ep[12], int j, int nb)
static void removeIdenticalNodes (int *np, int numComp, double xp[12], double yp[12], double zp[12], double valp[12][9], int ep[12])
static void reorderQuad (int numComp, double xp[12], double yp[12], double zp[12], double valp[12][9], int ep[12])
static void reorderPrism (int numComp, double xp[12], double yp[12], double zp[12], double valp[12][9], int ep[12], int nbCut)
static bool recur_sign_change (adaptiveTriangle *t, const GMSH_LevelsetPlugin *plug)
static bool recur_sign_change (adaptiveQuadrangle *q, const GMSH_LevelsetPlugin *plug)
static bool recur_sign_change (adaptiveTetrahedron *t, const GMSH_LevelsetPlugin *plug)
static bool recur_sign_change (adaptiveHexahedron *t, const GMSH_LevelsetPlugin *plug)
static bool recur_sign_change (adaptivePrism *t, const GMSH_LevelsetPlugin *plug)
static bool recur_sign_change (adaptivePyramid *t, const GMSH_LevelsetPlugin *plug)
Variables
static const int exn [13][12][2]
Function Documentation
affect()
static void affect (double * xpi, double * ypi, double * zpi, double valpi[12][9], int epi[12], int i, double * xp, double * yp, double * zp, double valp[12][9], int ep[12], int j, int nb) static
Definition at line 111 of file Levelset.cpp.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), removeIdenticalNodes(), reorderPrism(), and reorderQuad().
getSimplexDec()
static void getSimplexDec (int numNodes, int numEdges, int type, int i, int & n0, int & n1, int & n2, int & n3, int & nn, int & ne) static
Definition at line 60 of file Levelset.cpp.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements().
numSimplexDec()
static int numSimplexDec (int type) static
Definition at line 49 of file Levelset.cpp.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements().
recur_sign_change() [1/6]
static bool recur_sign_change (adaptiveHexahedron * t, const GMSH_LevelsetPlugin * plug) static
Definition at line 743 of file Levelset.cpp.
recur_sign_change() [2/6]
static bool recur_sign_change (adaptivePrism * t, const GMSH_LevelsetPlugin * plug) static
Definition at line 795 of file Levelset.cpp.
recur_sign_change() [3/6]
static bool recur_sign_change (adaptivePyramid * t, const GMSH_LevelsetPlugin * plug) static
Definition at line 841 of file Levelset.cpp.
recur_sign_change() [4/6]
static bool recur_sign_change (adaptiveQuadrangle * q, const GMSH_LevelsetPlugin * plug) static
Definition at line 665 of file Levelset.cpp.
recur_sign_change() [5/6]
static bool recur_sign_change (adaptiveTetrahedron * t, const GMSH_LevelsetPlugin * plug) static
Definition at line 700 of file Levelset.cpp.
recur_sign_change() [6/6]
static bool recur_sign_change (adaptiveTriangle * t, const GMSH_LevelsetPlugin * plug) static
Definition at line 632 of file Levelset.cpp.
Referenced by GMSH_LevelsetPlugin::assignSpecificVisibility(), and recur_sign_change().
removeIdenticalNodes()
static void removeIdenticalNodes (int * np, int numComp, double xp[12], double yp[12], double zp[12], double valp[12][9], int ep[12]) static
Definition at line 122 of file Levelset.cpp.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements().
reorderPrism()
static void reorderPrism (int numComp, double xp[12], double yp[12], double zp[12], double valp[12][9], int ep[12], int nbCut) static
Definition at line 160 of file Levelset.cpp.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements().
reorderQuad()
static void reorderQuad (int numComp, double xp[12], double yp[12], double zp[12], double valp[12][9], int ep[12]) static
Definition at line 150 of file Levelset.cpp.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements().
Variable Documentation
exn
const int exn[13][12][2] static
Definition at line 14 of file Levelset.cpp.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), and reorderPrism().