gmsh-TingyuanDoc: src/geo/MEdge.h File Reference
MEdge.h File Reference
#include "MVertex.h"
#include "SVector3.h"
#include <iostream>
Classes
class MEdge
struct MEdgeEqual
struct MEdgeLessThan
class MEdgeN
Functions
bool operator== (const MEdge &e1, const MEdge &e2)
bool operator!= (const MEdge &e1, const MEdge &e2)
bool SortEdgeConsecutive (const std::vector< MEdge > &, std::vector< std::vector< MVertex * > > &vs)
Function Documentation
operator!=()
bool operator!= (const MEdge & e1, const MEdge & e2) inline
Definition at line 112 of file MEdge.h.
operator==()
bool operator== (const MEdge & e1, const MEdge & e2) inline
Definition at line 106 of file MEdge.h.
SortEdgeConsecutive()
bool SortEdgeConsecutive (const std::vector< MEdge > & , std::vector< std::vector< MVertex * > > & vs)
Definition at line 68 of file MEdge.cpp.
Referenced by classifyFaces(), computeParametrization(), discreteEdge::createGeometry(), GMSH_BoundaryAnglesPlugin::execute(), and isTriangulationParametrizable().