gmsh-TingyuanDoc: src/geo/MElementOctree.cpp File Reference
MElementOctree.cpp File Reference
#include "GModel.h"
#include "MElement.h"
#include "MElementOctree.h"
#include "Octree.h"
#include "Context.h"
#include "fullMatrix.h"
#include "bezierBasis.h"
#include "BasisFactory.h"
#include "SBoundingBox3d.h"
Functions
void MElementBB (void *a, double *min, double *max)
static void MElementCentroid (void *a, double *x)
int MElementInEle (void *a, double *x)
Function Documentation
MElementBB()
void MElementBB (void * a, double * min, double * max)
Definition at line 17 of file MElementOctree.cpp.
Referenced by filterOverlappingElements(), and MElementOctree::MElementOctree().
MElementCentroid()
static void MElementCentroid (void * a, double * x) static
Definition at line 64 of file MElementOctree.cpp.
Referenced by MElementOctree::MElementOctree().
MElementInEle()
int MElementInEle (void * a, double * x)
Definition at line 84 of file MElementOctree.cpp.
Referenced by MElementOctree::find(), MElementOctree::findAll(), and MElementOctree::MElementOctree().