gmsh-TingyuanDoc: src/geo/MEdge.cpp File Reference
MEdge.cpp File Reference
#include <algorithm>
#include "MEdge.h"
#include "Numeric.h"
#include "GmshDefines.h"
#include "ElementType.h"
#include "nodalBasis.h"
#include "BasisFactory.h"
Functions
bool SortEdgeConsecutive (const std::vector< MEdge > &e, std::vector< std::vector< MVertex * > > &vs)
Function Documentation
SortEdgeConsecutive()
bool SortEdgeConsecutive (const std::vector< MEdge > & e, std::vector< std::vector< MVertex * > > & vs)
Definition at line 68 of file MEdge.cpp.
Referenced by classifyFaces(), computeParametrization(), discreteEdge::createGeometry(), GMSH_BoundaryAnglesPlugin::execute(), and isTriangulationParametrizable().