gmsh-TingyuanDoc: src/geo/MFace.cpp File Reference
MFace.cpp File Reference
#include <vector>
#include <algorithm>
#include "GmshConfig.h"
#include "MFace.h"
#include "Numeric.h"
#include "ElementType.h"
#include "nodalBasis.h"
#include "BasisFactory.h"
Functions
bool compare (const MVertex *const v0, const MVertex *const v1)
void sortVertices (const std::vector< MVertex * > &v, std::vector< char > &s)
Function Documentation
compare()
bool compare (const MVertex *const v0, const MVertex *const v1)
Definition at line 15 of file MFace.cpp.
Referenced by avl_delete(), avl_insert(), avl_lookup(), GFace2PolyMesh(), gl2psTraverseBspTree(), and sortVertices().
sortVertices()
void sortVertices (const std::vector< MVertex * > & v, std::vector< char > & s)
Definition at line 20 of file MFace.cpp.
Referenced by MFace::MFace().