gmsh-TingyuanDoc: src/geo/MHexahedron.cpp File Reference
MHexahedron.cpp File Reference
#include <limits>
#include "MHexahedron.h"
#include "Numeric.h"
#include "Context.h"
#include "BasisFactory.h"
#include "polynomialBasis.h"
#include "MQuadrangle.h"
#include "pointsGenerators.h"
Functions
static void _myGetEdgeRep (MHexahedron *hex, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
void _myGetFaceRep (MHexahedron *hex, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
void _getIndicesReversedHex (int order, IndicesReversed &indices)
Function Documentation
_getIndicesReversedHex()
void _getIndicesReversedHex (int order, IndicesReversed & indices)
Definition at line 430 of file MHexahedron.cpp.
Referenced by MHexahedronN::reverse().
_myGetEdgeRep()
static void _myGetEdgeRep (MHexahedron * hex, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 114 of file MHexahedron.cpp.
Referenced by MHexahedron20::getEdgeRep(), MHexahedron27::getEdgeRep(), and MHexahedronN::getEdgeRep().
_myGetFaceRep()
void _myGetFaceRep (MHexahedron * hex, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges)
Definition at line 194 of file MHexahedron.cpp.
Referenced by MHexahedron::getFaceRep(), MHexahedron20::getFaceRep(), MHexahedron27::getFaceRep(), and MHexahedronN::getFaceRep().