gmsh-TingyuanDoc: src/geo/MPrism.cpp File Reference
MPrism.cpp File Reference
#include "MPrism.h"
#include "Numeric.h"
#include "BasisFactory.h"
#include "Context.h"
#include "pointsGenerators.h"
#include "nodalBasis.h"
Functions
static void _myGetEdgeRep (MPrism *pri, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
static void _myGetFaceRep (MPrism *pri, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
static void _addEdgeNodes (int num, bool reverse, int order, const std::vector< MVertex * > &vs, int &ind, std::vector< MVertex * > &v)
static void _addFaceNodes (int num, int order, const std::vector< MVertex * > &vs, int &ind, std::vector< MVertex * > &v)
void _getIndicesReversedPri (int order, IndicesReversed &indices)
Function Documentation
_addEdgeNodes()
static void _addEdgeNodes (int num, bool reverse, int order, const std::vector< MVertex * > & vs, int & ind, std::vector< MVertex * > & v) static
Definition at line 482 of file MPrism.cpp.
Referenced by MPrismN::getFaceVertices().
_addFaceNodes()
static void _addFaceNodes (int num, int order, const std::vector< MVertex * > & vs, int & ind, std::vector< MVertex * > & v) static
Definition at line 495 of file MPrism.cpp.
Referenced by MPrismN::getFaceVertices().
_getIndicesReversedPri()
void _getIndicesReversedPri (int order, IndicesReversed & indices)
Definition at line 559 of file MPrism.cpp.
Referenced by MPrismN::reverse().
_myGetEdgeRep()
static void _myGetEdgeRep (MPrism * pri, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 100 of file MPrism.cpp.
Referenced by MPrism15::getEdgeRep(), MPrism18::getEdgeRep(), and MPrismN::getEdgeRep().
_myGetFaceRep()
static void _myGetFaceRep (MPrism * pri, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 180 of file MPrism.cpp.
Referenced by MPrism::getFaceRep(), MPrism15::getFaceRep(), MPrism18::getFaceRep(), and MPrismN::getFaceRep().