gmsh-TingyuanDoc: src/geo/MPyramid.cpp File Reference
MPyramid.cpp File Reference
#include "MPyramid.h"
#include "Numeric.h"
#include "Context.h"
#include "BergotBasis.h"
#include "BasisFactory.h"
#include "pointsGenerators.h"
Functions
static void _myGetFaceRep (MPyramid *pyr, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
void _getIndicesReversedPyr (int order, IndicesReversed &indices)
Function Documentation
_getIndicesReversedPyr()
void _getIndicesReversedPyr (int order, IndicesReversed & indices)
Definition at line 396 of file MPyramid.cpp.
Referenced by MPyramidN::reverse().
_myGetFaceRep()
static void _myGetFaceRep (MPyramid * pyr, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 124 of file MPyramid.cpp.
Referenced by MPyramid::getFaceRep(), and MPyramidN::getFaceRep().