gmsh-TingyuanDoc: src/geo/MQuadrangle.cpp File Reference
MQuadrangle.cpp File Reference
#include "GmshConfig.h"
#include "MQuadrangle.h"
#include "GaussLegendre1D.h"
#include "Context.h"
#include "Numeric.h"
#include "BasisFactory.h"
#include "pointsGenerators.h"
#include <cstring>
Functions
static void _myGetEdgeRep (MQuadrangle *q, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
static void _myGetFaceRep (MQuadrangle *t, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
Function Documentation
_myGetEdgeRep()
static void _myGetEdgeRep (MQuadrangle * q, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 86 of file MQuadrangle.cpp.
Referenced by MQuadrangle8::getEdgeRep(), MQuadrangle9::getEdgeRep(), and MQuadrangleN::getEdgeRep().
_myGetFaceRep()
static void _myGetFaceRep (MQuadrangle * t, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 187 of file MQuadrangle.cpp.
Referenced by MQuadrangle::getFaceRep(), MQuadrangle8::getFaceRep(), MQuadrangle9::getFaceRep(), and MQuadrangleN::getFaceRep().