gmsh-TingyuanDoc: src/geo/MTetrahedron.cpp File Reference
MTetrahedron.cpp File Reference
#include "GmshConfig.h"
#include "MTetrahedron.h"
#include "Numeric.h"
#include "Context.h"
#include "BasisFactory.h"
#include "pointsGenerators.h"
Macros
#define SQU(a) ((a) * (a))
Functions
static void _myGetEdgeRep (MTetrahedron *tet, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
static void _myGetFaceRep (MTetrahedron *tet, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
void _getIndicesReversedTet (int order, IndicesReversed &indices)
Macro Definition Documentation
SQU
#define SQU (a) ((a) * (a))
Definition at line 20 of file MTetrahedron.cpp.
Function Documentation
_getIndicesReversedTet()
void _getIndicesReversedTet (int order, IndicesReversed & indices)
Definition at line 348 of file MTetrahedron.cpp.
Referenced by MTetrahedronN::reverse().
_myGetEdgeRep()
static void _myGetEdgeRep (MTetrahedron * tet, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 151 of file MTetrahedron.cpp.
Referenced by MTetrahedron10::getEdgeRep(), and MTetrahedronN::getEdgeRep().
_myGetFaceRep()
static void _myGetFaceRep (MTetrahedron * tet, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 214 of file MTetrahedron.cpp.
Referenced by MTetrahedron10::getFaceRep(), and MTetrahedronN::getFaceRep().