gmsh-TingyuanDoc: src/geo/MTriangle.cpp File Reference
MTriangle.cpp File Reference
#include "GmshConfig.h"
#include "MTriangle.h"
#include "Numeric.h"
#include "Context.h"
#include "BasisFactory.h"
#include "pointsGenerators.h"
#include <cmath>
#include <cstring>
Functions
static void _myGetEdgeRep (MTriangle *t, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
static void _myGetFaceRep (MTriangle *t, int num, double *x, double *y, double *z, SVector3 *n, int numSubEdges)
Function Documentation
_myGetEdgeRep()
static void _myGetEdgeRep (MTriangle * t, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 186 of file MTriangle.cpp.
Referenced by MTriangle6::getEdgeRep(), and MTriangleN::getEdgeRep().
_myGetFaceRep()
static void _myGetFaceRep (MTriangle * t, int num, double * x, double * y, double * z, SVector3 * n, int numSubEdges) static
Definition at line 267 of file MTriangle.cpp.
Referenced by MTriangle6::getFaceRep(), and MTriangleN::getFaceRep().