gmsh-TingyuanDoc: src/geo/MVertex.h File Reference
MVertex.h File Reference
#include <cmath>
#include <stdio.h>
#include <set>
#include <map>
#include <fstream>
#include "SPoint2.h"
#include "SPoint3.h"
#include "MVertexBoundaryLayerData.h"
Classes
class MVertex
class MEdgeVertex
class MFaceVertex
class MVertexPtrLessThanLexicographic
struct MVertexPtrLessThan
struct MVertexPtrEqual
struct MVertexPtrHash
Functions
bool reparamMeshEdgeOnFace (MVertex *v1, MVertex *v2, GFace *gf, SPoint2 &param1, SPoint2 &param2)
bool reparamMeshVertexOnFace (MVertex const *v, const GFace *gf, SPoint2 &param, bool onSurface=true, bool failOnSeam=true, int dir=1)
bool reparamMeshVertexOnEdge (MVertex *v, const GEdge *ge, double &param)
double angle3Vertices (const MVertex *p1, const MVertex *p2, const MVertex *p3)
double distance (MVertex *v1, MVertex *v2)
Function Documentation
angle3Vertices()
double angle3Vertices (const MVertex * p1, const MVertex * p2, const MVertex * p3)
Definition at line 16 of file MVertex.cpp.
Referenced by qmTriangle::eta(), qmQuadrangle::eta(), getAcuteCorners(), and RecombineTriangle::RecombineTriangle().
distance()
double distance (MVertex * v1, MVertex * v2) inline
Definition at line 245 of file MVertex.h.
Referenced by _removeDiamonds(), adaptiveElements< T >::buildMapping(), buildMeshGenerationDataStructures(), computeDistanceRatio(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::computeInitialDistances(), createPoints(), GFace::delEdge(), GRegion::delFace(), GMSH_DistancePlugin::execute(), filterPoints(), robin_hood::detail::Table< IsFlat, MaxLoadFactor100, Key, T, Hash, KeyEqual >::findIdx(), GetAveEdgeLength(), gmshBeam2d::gmshBeam2d(), insertVertexB(), EmbeddedCompatibilityTest::operator()(), gLevelsetShamrock::operator()(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::searchLevel(), PViewData::searchScalarClosest(), PViewData::searchTensorClosest(), PViewData::searchVectorClosest(), sortVertices(), and writeX3dHeader().
reparamMeshEdgeOnFace()
bool reparamMeshEdgeOnFace (MVertex * v1, MVertex * v2, GFace * gf, SPoint2 & param1, SPoint2 & param2)
Definition at line 474 of file MVertex.cpp.
Referenced by _relocate(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), getEdgeVerticesOnGeo(), SurfaceProjector::initialize(), parametricCoordinates(), backgroundMesh::propagateCrossField(), and backgroundMesh::propagateCrossFieldByDistance().
reparamMeshVertexOnEdge()
bool reparamMeshVertexOnEdge (MVertex * v, const GEdge * ge, double & param)
Definition at line 592 of file MVertex.cpp.
Referenced by _getAdditionalNodesOnBoundary(), crossField2d::crossField2d(), GeomMeshMatcher::forceTomatch(), getEdgeVerticesOnGeo(), and getNodeCopies().
reparamMeshVertexOnFace()
bool reparamMeshVertexOnFace (MVertex const * v, const GFace * gf, SPoint2 & param, bool onSurface = true, bool failOnSeam = true, int dir = 1)
Definition at line 522 of file MVertex.cpp.
Referenced by _getAdditionalNodesOnBoundary(), _relocateVertex(), backgroundMesh::backgroundMesh(), buildMeshGenerationDataStructures(), directions_storage(), getFaceVerticesOnGeo(), getGFaceNormalFromBary(), getNodeCopies(), improved_translate(), meshGenerator(), MeshTransfiniteSurface(), parametricCoordinates(), propagateValuesOnFace(), TRIANGLE_VALIDITY(), backgroundMesh::updateSizes(), and GModel::writeCELUM().