gmsh-TingyuanDoc: src/geo/MVertex.cpp File Reference
MVertex.cpp File Reference
#include <string.h>
#include <cmath>
#include "MVertex.h"
#include "GModel.h"
#include "GVertex.h"
#include "GEdge.h"
#include "GFace.h"
#include "GmshMessage.h"
#include "StringUtils.h"
Functions
double angle3Vertices (const MVertex *p1, const MVertex *p2, const MVertex *p3)
static void double_to_char8 (double val, char *str)
static void getAllParameters (MVertex *v, GFace *gf, std::vector< SPoint2 > &params)
bool reparamMeshEdgeOnFace (MVertex *v1, MVertex *v2, GFace *gf, SPoint2 &param1, SPoint2 &param2)
bool reparamMeshVertexOnFace (MVertex const *v, const GFace *gf, SPoint2 &param, bool onSurface, bool failOnSeam, int dir)
bool reparamMeshVertexOnEdge (MVertex *v, const GEdge *ge, double &param)
Function Documentation
angle3Vertices()
double angle3Vertices (const MVertex * p1, const MVertex * p2, const MVertex * p3)
Definition at line 16 of file MVertex.cpp.
Referenced by qmTriangle::eta(), qmQuadrangle::eta(), getAcuteCorners(), and RecombineTriangle::RecombineTriangle().
double_to_char8()
static void double_to_char8 (double val, char * str) static
Definition at line 308 of file MVertex.cpp.
Referenced by MVertex::writeBDF().
getAllParameters()
static void getAllParameters (MVertex * v, GFace * gf, std::vector< SPoint2 > & params) static
Definition at line 425 of file MVertex.cpp.
Referenced by reparamMeshEdgeOnFace().
reparamMeshEdgeOnFace()
bool reparamMeshEdgeOnFace (MVertex * v1, MVertex * v2, GFace * gf, SPoint2 & param1, SPoint2 & param2)
Definition at line 474 of file MVertex.cpp.
Referenced by _relocate(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), getEdgeVerticesOnGeo(), SurfaceProjector::initialize(), parametricCoordinates(), backgroundMesh::propagateCrossField(), and backgroundMesh::propagateCrossFieldByDistance().
reparamMeshVertexOnEdge()
bool reparamMeshVertexOnEdge (MVertex * v, const GEdge * ge, double & param)
Definition at line 592 of file MVertex.cpp.
Referenced by _getAdditionalNodesOnBoundary(), crossField2d::crossField2d(), GeomMeshMatcher::forceTomatch(), getEdgeVerticesOnGeo(), and getNodeCopies().
reparamMeshVertexOnFace()
bool reparamMeshVertexOnFace (MVertex const * v, const GFace * gf, SPoint2 & param, bool onSurface, bool failOnSeam, int dir)
Definition at line 522 of file MVertex.cpp.
Referenced by _getAdditionalNodesOnBoundary(), _relocateVertex(), backgroundMesh::backgroundMesh(), buildMeshGenerationDataStructures(), directions_storage(), getFaceVerticesOnGeo(), getGFaceNormalFromBary(), getNodeCopies(), improved_translate(), meshGenerator(), MeshTransfiniteSurface(), parametricCoordinates(), propagateValuesOnFace(), TRIANGLE_VALIDITY(), backgroundMesh::updateSizes(), and GModel::writeCELUM().