gmsh-TingyuanDoc: src/common/MallocUtils.h File Reference
MallocUtils.h File Reference
#include <stdlib.h>
Functions
void * Malloc (size_t size)
void * Calloc (size_t num, size_t size)
void * Realloc (void *ptr, size_t size)
void Free (void *ptr)
Function Documentation
Calloc()
void* Calloc (size_t num, size_t size)
Definition at line 22 of file MallocUtils.cpp.
Free()
void Free (void * ptr)
Definition at line 40 of file MallocUtils.cpp.
Referenced by create_gif(), create_yuv(), freeLink(), List_Delete(), ppm_freecolorhash(), ppm_freecolorhist(), treat_Struct_FullName_dot_tSTRING_Float(), treat_Struct_FullName_dot_tSTRING_Float_getDim(), treat_Struct_FullName_dot_tSTRING_ListOfFloat(), treat_Struct_FullName_dot_tSTRING_ListOfString(), treat_Struct_FullName_dot_tSTRING_String(), treat_Struct_FullName_Float(), treat_Struct_FullName_String(), Tree_Delete(), and Tree_Suppress().
Malloc()
void* Malloc (size_t size)
Definition at line 12 of file MallocUtils.cpp.
Referenced by create_gif(), create_yuv(), gmshViewGetModelData(), List_Create(), List_Realloc(), ppm_addtocolorhash(), ppm_alloccolorhash(), ppm_colorhashtocolorhist(), ppm_colorhisttocolorhash(), ppm_computecolorhash(), treat_Struct_FullName_dot_tSTRING_String(), treat_Struct_FullName_String(), Tree_Add(), and Tree_Create().
Realloc()
void* Realloc (void * ptr, size_t size)
Definition at line 32 of file MallocUtils.cpp.
Referenced by List_Realloc().