gmsh-TingyuanDoc: src/post/OctreePost.cpp File Reference
OctreePost.cpp File Reference
#include "Octree.h"
#include "OctreePost.h"
#include "PView.h"
#include "PViewData.h"
#include "PViewDataList.h"
#include "PViewDataGModel.h"
#include "Numeric.h"
#include "GmshMessage.h"
#include "shapeFunctions.h"
#include "GModel.h"
#include "MElement.h"
#include "Context.h"
#include "SBoundingBox3d.h"
Functions
static void minmax (int n, double *X, double *Y, double *Z, double *min, double *max)
static void centroid (int n, double *X, double *Y, double *Z, double *c)
static void pntBB (void *a, double *min, double *max)
static void linBB (void *a, double *min, double *max)
static void triBB (void *a, double *min, double *max)
static void quaBB (void *a, double *min, double *max)
static void tetBB (void *a, double *min, double *max)
static void hexBB (void *a, double *min, double *max)
static void priBB (void *a, double *min, double *max)
static void pyrBB (void *a, double *min, double *max)
static int pntInEle (void *a, double *x)
static int linInEle (void *a, double *x)
static int triInEle (void *a, double *x)
static int quaInEle (void *a, double *x)
static int tetInEle (void *a, double *x)
static int hexInEle (void *a, double *x)
static int priInEle (void *a, double *x)
static int pyrInEle (void *a, double *x)
static void pntCentroid (void *a, double *x)
static void linCentroid (void *a, double *x)
static void triCentroid (void *a, double *x)
static void quaCentroid (void *a, double *x)
static void tetCentroid (void *a, double *x)
static void hexCentroid (void *a, double *x)
static void priCentroid (void *a, double *x)
static void pyrCentroid (void *a, double *x)
static void addListOfStuff (Octree *o, std::vector< double > &l, int nbelm)
static void * getElement (double P[3], Octree *octree, int nbNod, int qn, double *qx, double *qy, double *qz)
static MElement * getElement (double P[3], GModel *m, int qn, double *qx, double *qy, double *qz, int dim)
Function Documentation
addListOfStuff()
static void addListOfStuff (Octree * o, std::vector< double > & l, int nbelm) static
Definition at line 231 of file OctreePost.cpp.
Referenced by OctreePost::_create().
centroid()
static void centroid (int n, double * X, double * Y, double * Z, double * c) static
Definition at line 61 of file OctreePost.cpp.
Referenced by hexCentroid(), linCentroid(), Octree_Insert(), pntCentroid(), priCentroid(), pyrCentroid(), quaCentroid(), tetCentroid(), and triCentroid().
getElement() [1/2]
static MElement* getElement (double P[3], GModel * m, int qn, double * qx, double * qy, double * qz, int dim) static
Definition at line 449 of file OctreePost.cpp.
getElement() [2/2]
static void* getElement (double P[3], Octree * octree, int nbNod, int qn, double * qx, double * qy, double * qz) static
Definition at line 421 of file OctreePost.cpp.
Referenced by OctreePost::searchScalar(), OctreePost::searchTensor(), and OctreePost::searchVector().
hexBB()
static void hexBB (void * a, double * min, double * max) static
Definition at line 107 of file OctreePost.cpp.
Referenced by OctreePost::_create().
hexCentroid()
static void hexCentroid (void * a, double * x) static
Definition at line 213 of file OctreePost.cpp.
Referenced by OctreePost::_create().
hexInEle()
static int hexInEle (void * a, double * x) static
Definition at line 159 of file OctreePost.cpp.
Referenced by OctreePost::_create().
linBB()
static void linBB (void * a, double * min, double * max) static
Definition at line 83 of file OctreePost.cpp.
Referenced by OctreePost::_create().
linCentroid()
static void linCentroid (void * a, double * x) static
Definition at line 189 of file OctreePost.cpp.
Referenced by OctreePost::_create().
linInEle()
static int linInEle (void * a, double * x) static
Definition at line 127 of file OctreePost.cpp.
Referenced by OctreePost::_create().
minmax()
static void minmax (int n, double * X, double * Y, double * Z, double * min, double * max) static
Definition at line 22 of file OctreePost.cpp.
Referenced by hexBB(), linBB(), GMSH_SpanningTreePlugin::Sort::operator()(), pntBB(), priBB(), pyrBB(), quaBB(), tetBB(), and triBB().
pntBB()
static void pntBB (void * a, double * min, double * max) static
Definition at line 77 of file OctreePost.cpp.
Referenced by OctreePost::_create().
pntCentroid()
static void pntCentroid (void * a, double * x) static
Definition at line 183 of file OctreePost.cpp.
Referenced by OctreePost::_create().
pntInEle()
static int pntInEle (void * a, double * x) static
Definition at line 125 of file OctreePost.cpp.
Referenced by OctreePost::_create().
priBB()
static void priBB (void * a, double * min, double * max) static
Definition at line 113 of file OctreePost.cpp.
Referenced by OctreePost::_create().
priCentroid()
static void priCentroid (void * a, double * x) static
Definition at line 219 of file OctreePost.cpp.
Referenced by OctreePost::_create().
priInEle()
static int priInEle (void * a, double * x) static
Definition at line 167 of file OctreePost.cpp.
Referenced by OctreePost::_create().
pyrBB()
static void pyrBB (void * a, double * min, double * max) static
Definition at line 119 of file OctreePost.cpp.
Referenced by OctreePost::_create().
pyrCentroid()
static void pyrCentroid (void * a, double * x) static
Definition at line 225 of file OctreePost.cpp.
Referenced by OctreePost::_create().
pyrInEle()
static int pyrInEle (void * a, double * x) static
Definition at line 175 of file OctreePost.cpp.
Referenced by OctreePost::_create().
quaBB()
static void quaBB (void * a, double * min, double * max) static
Definition at line 95 of file OctreePost.cpp.
Referenced by OctreePost::_create().
quaCentroid()
static void quaCentroid (void * a, double * x) static
Definition at line 201 of file OctreePost.cpp.
Referenced by OctreePost::_create().
quaInEle()
static int quaInEle (void * a, double * x) static
Definition at line 143 of file OctreePost.cpp.
Referenced by OctreePost::_create().
tetBB()
static void tetBB (void * a, double * min, double * max) static
Definition at line 101 of file OctreePost.cpp.
Referenced by OctreePost::_create().
tetCentroid()
static void tetCentroid (void * a, double * x) static
Definition at line 207 of file OctreePost.cpp.
Referenced by OctreePost::_create().
tetInEle()
static int tetInEle (void * a, double * x) static
Definition at line 151 of file OctreePost.cpp.
Referenced by OctreePost::_create().
triBB()
static void triBB (void * a, double * min, double * max) static
Definition at line 89 of file OctreePost.cpp.
Referenced by OctreePost::_create().
triCentroid()
static void triCentroid (void * a, double * x) static
Definition at line 195 of file OctreePost.cpp.
Referenced by OctreePost::_create().
triInEle()
static int triInEle (void * a, double * x) static
Definition at line 135 of file OctreePost.cpp.
Referenced by OctreePost::_create().