gmsh-TingyuanDoc: src/common/OctreeInternals.h File Reference
OctreeInternals.h File Reference
#include <vector>
Classes
struct elem
struct bucket
struct global
class Octree
Typedefs
typedef void(* BBFunction) (void *, double *, double *)
typedef int(* InEleFunction) (void *, double *)
typedef void(* CentroidFunction) (void *, double *)
typedef struct elem Elem
typedef Elem * ELink
typedef struct bucket octantBucket
typedef struct global globalInfo
Functions
void refineOctants (octantBucket *buckets, globalInfo *globalPara)
int addElement2Bucket (octantBucket *bucket, void *element, double *minBB, double *maxBB, double *ele_centroid, globalInfo *globalPara)
int subdivideOctantBucket (octantBucket *bucket, globalInfo *globalPara)
int initializeOctantBuckets (double *orig, double *size, int maxElem, octantBucket **buckets, globalInfo **globalPara)
int checkElementInBucket (octantBucket *bucket, void *element)
octantBucket * findElementBucket (octantBucket *buckets, double *pt)
void * searchElement (octantBucket *buckets, double *pt, globalInfo *globalPara, BBFunction BBElement, InEleFunction xyzInElement)
int xyzInElementBB (double *xyz, void *region, BBFunction BBElement)
void insertOneBB (void *, double *, double *, octantBucket *)
void * searchAllElements (octantBucket *_buckets_head, double *_pt, globalInfo *_globalPara, BBFunction BBElement, InEleFunction xyzInElement, std::vector< void * > *_elements)
Typedef Documentation
BBFunction
typedef void(* BBFunction) (void *, double *, double *)
Definition at line 12 of file OctreeInternals.h.
CentroidFunction
typedef void(* CentroidFunction) (void *, double *)
Definition at line 14 of file OctreeInternals.h.
Elem
typedef struct elem Elem
ELink
typedef Elem* ELink
Definition at line 24 of file OctreeInternals.h.
globalInfo
typedef struct global globalInfo
Definition at line 24 of file OctreeInternals.h.
InEleFunction
typedef int(* InEleFunction) (void *, double *)
Definition at line 13 of file OctreeInternals.h.
octantBucket
typedef struct bucket octantBucket
Definition at line 24 of file OctreeInternals.h.
Function Documentation
addElement2Bucket()
int addElement2Bucket (octantBucket * bucket, void * element, double * minBB, double * maxBB, double * ele_centroid, globalInfo * globalPara)
Definition at line 111 of file OctreeInternals.cpp.
Referenced by Octree_Insert().
checkElementInBucket()
int checkElementInBucket (octantBucket * bucket, void * element)
Definition at line 191 of file OctreeInternals.cpp.
Referenced by addElement2Bucket().
findElementBucket()
octantBucket* findElementBucket (octantBucket * buckets, double * pt)
Definition at line 204 of file OctreeInternals.cpp.
Referenced by addElement2Bucket(), Octree_Insert(), searchAllElements(), and searchElement().
initializeOctantBuckets()
int initializeOctantBuckets (double * orig, double * size, int maxElem, octantBucket ** buckets, globalInfo ** globalPara)
Definition at line 13 of file OctreeInternals.cpp.
Referenced by Octree_Create().
insertOneBB()
void insertOneBB (void * , double * , double * , octantBucket *)
Definition at line 371 of file OctreeInternals.cpp.
Referenced by insertOneBB(), and Octree_Arrange().
refineOctants()
void refineOctants (octantBucket * buckets, globalInfo * globalPara)
searchAllElements()
void* searchAllElements (octantBucket * _buckets_head, double * _pt, globalInfo * _globalPara, BBFunction BBElement, InEleFunction xyzInElement, std::vector< void * > * _elements)
Definition at line 396 of file OctreeInternals.cpp.
Referenced by Octree_SearchAll().
searchElement()
void* searchElement (octantBucket * buckets, double * pt, globalInfo * globalPara, BBFunction BBElement, InEleFunction xyzInElement)
Definition at line 290 of file OctreeInternals.cpp.
Referenced by Octree_Search().
subdivideOctantBucket()
int subdivideOctantBucket (octantBucket * bucket, globalInfo * globalPara)
Definition at line 236 of file OctreeInternals.cpp.
Referenced by addElement2Bucket().
xyzInElementBB()
int xyzInElementBB (double * xyz, void * region, BBFunction BBElement)
Definition at line 354 of file OctreeInternals.cpp.
Referenced by searchAllElements(), and searchElement().