gmsh-TingyuanDoc: src/common/Octree.cpp File Reference
Octree.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <vector>
#include "Octree.h"
Functions
Octree * Octree_Create (int maxElements, double origin[3], double size[3], void(*BB)(void *, double *, double *), void(*Centroid)(void *, double *), int(*InEle)(void *, double *))
void free_buckets (octantBucket *bucket)
void Octree_Delete (Octree *myOctree)
void Octree_Insert (void *element, Octree *myOctree)
void Octree_Arrange (Octree *myOctree)
void * Octree_Search (double *pt, Octree *myOctree)
void Octree_SearchAll (double *pt, Octree *myOctree, std::vector< void * > *output)
Function Documentation
free_buckets()
void free_buckets (octantBucket * bucket)
Definition at line 25 of file Octree.cpp.
Referenced by Octree_Delete().
Octree_Arrange()
void Octree_Arrange (Octree * myOctree)
Definition at line 67 of file Octree.cpp.
Referenced by OctreePost::_create(), and MElementOctree::MElementOctree().
Octree_Create()
Octree* Octree_Create (int maxElements, double origin[3], double size[3], void(*)(void *, double *, double *) BB, void(*)(void *, double *) Centroid, int(*)(void *, double *) InEle)
Definition at line 11 of file Octree.cpp.
Referenced by OctreePost::_create(), and MElementOctree::MElementOctree().
Octree_Delete()
void Octree_Delete (Octree * myOctree)
Definition at line 46 of file Octree.cpp.
Referenced by MElementOctree::~MElementOctree(), and OctreePost::~OctreePost().
Octree_Insert()
void Octree_Insert (void * element, Octree * myOctree)
Definition at line 55 of file Octree.cpp.
Referenced by addListOfStuff(), and MElementOctree::MElementOctree().
Octree_Search()
void* Octree_Search (double * pt, Octree * myOctree)
Definition at line 81 of file Octree.cpp.
Referenced by MElementOctree::find(), getElement(), and DocRecord::printMedialAxis().
Octree_SearchAll()
void Octree_SearchAll (double * pt, Octree * myOctree, std::vector< void * > * output)
Definition at line 88 of file Octree.cpp.
Referenced by MElementOctree::find(), MElementOctree::findAll(), and getElement().