gmsh-TingyuanDoc: src/common/OpenFile.cpp File Reference
OpenFile.cpp File Reference
#include <sstream>
#include <string.h>
#include "GmshConfig.h"
#include <stdint.h>
#include "GmshMessage.h"
#include "GModelIO_GEO.h"
#include "Options.h"
#include "GModel.h"
#include "Numeric.h"
#include "Context.h"
#include "OpenFile.h"
#include "CommandLine.h"
#include "OS.h"
#include "StringUtils.h"
#include "GeomMeshMatcher.h"
Macros
#define SQU(a) ((a) * (a))
Functions
static void FinishUpBoundingBox ()
void SetBoundingBox (double xmin, double xmax, double ymin, double ymax, double zmin, double zmax)
void SetBoundingBox (bool aroundVisible)
void ResetTemporaryBoundingBox ()
void AddToTemporaryBoundingBox (double x, double y, double z)
int ParseFile (const std::string &fileName, bool close, bool errorIfMissing)
static bool DoSystemUncompress (const std::string &fileName, const std::string &noExt)
void ParseString (const std::string &str, bool inCurrentModelDir)
int MergeFile (const std::string &fileName, bool errorIfMissing, bool setBoundingBox, bool importPhysicalsInOnelab, int partitionToRead)
int MergePostProcessingFile (const std::string &fileName, int showViews, bool showLastStep, bool errorIfMissing)
void DeleteAllModelsAndViews ()
void ClearProject ()
void OpenProject (const std::string &fileName, bool errorIfMissing)
void OpenProjectMacFinder (const char *fileName)
Variables
static SBoundingBox3d temp_bb
static std::vector< FILE * > openedFiles
Macro Definition Documentation
SQU
#define SQU (a) ((a) * (a))
Definition at line 63 of file OpenFile.cpp.
Function Documentation
AddToTemporaryBoundingBox()
void AddToTemporaryBoundingBox (double x, double y, double z)
Definition at line 163 of file OpenFile.cpp.
ClearProject()
void ClearProject ()
Definition at line 697 of file OpenFile.cpp.
Referenced by GmshClearProject().
DeleteAllModelsAndViews()
void DeleteAllModelsAndViews ()
Definition at line 664 of file OpenFile.cpp.
Referenced by ClearProject(), and GmshFinalize().
DoSystemUncompress()
static bool DoSystemUncompress (const std::string & fileName, const std::string & noExt) static
Definition at line 242 of file OpenFile.cpp.
Referenced by MergeFile().
FinishUpBoundingBox()
static void FinishUpBoundingBox () static
Definition at line 64 of file OpenFile.cpp.
Referenced by SetBoundingBox().
MergeFile()
int MergeFile (const std::string & fileName, bool errorIfMissing, bool setBoundingBox, bool importPhysicalsInOnelab, int partitionToRead)
Definition at line 298 of file OpenFile.cpp.
Referenced by GmshBatch(), GmshFLTK(), GmshMergeFile(), GModel::load(), MergeFile(), MergePostProcessingFile(), and OpenProject().
MergePostProcessingFile()
int MergePostProcessingFile (const std::string & fileName, int showViews, bool showLastStep, bool errorIfMissing)
Definition at line 574 of file OpenFile.cpp.
Referenced by GmshBatch(), GmshFLTK(), and GmshMergePostProcessingFile().
OpenProject()
void OpenProject (const std::string & fileName, bool errorIfMissing)
Definition at line 718 of file OpenFile.cpp.
Referenced by GetMeshOption(), GmshBatch(), GmshFLTK(), GmshOpenProject(), OpenProjectMacFinder(), scriptAddCommand(), and scriptRemoveLastCommand().
OpenProjectMacFinder()
void OpenProjectMacFinder (const char * fileName)
Definition at line 799 of file OpenFile.cpp.
ParseFile()
int ParseFile (const std::string & fileName, bool close, bool errorIfMissing)
Definition at line 177 of file OpenFile.cpp.
Referenced by GetOptions(), GetOtherOption(), and GModel::readGEO().
ParseString()
void ParseString (const std::string & str, bool inCurrentModelDir)
Definition at line 259 of file OpenFile.cpp.
Referenced by ChangePrintParameter(), and GetOtherOption().
ResetTemporaryBoundingBox()
void ResetTemporaryBoundingBox ()
Definition at line 161 of file OpenFile.cpp.
Referenced by OpenProject().
SetBoundingBox() [1/2]
void SetBoundingBox (bool aroundVisible)
Definition at line 127 of file OpenFile.cpp.
SetBoundingBox() [2/2]
void SetBoundingBox (double xmin, double xmax, double ymin, double ymax, double zmin, double zmax)
Definition at line 115 of file OpenFile.cpp.
Referenced by GMSH_LongituteLatitudePlugin::execute(), PView::fillVertexArray(), GmshSetBoundingBox(), MergeFile(), and GEO_Internals::synchronize().
Variable Documentation
openedFiles
std::vector<FILE *> openedFiles static
Definition at line 175 of file OpenFile.cpp.
Referenced by DeleteAllModelsAndViews(), OpenProject(), and ParseFile().
temp_bb
SBoundingBox3d temp_bb static
Definition at line 159 of file OpenFile.cpp.
Referenced by AddToTemporaryBoundingBox(), and ResetTemporaryBoundingBox().