gmsh-TingyuanDoc: src/common/Options.h File Reference
Options.h File Reference
#include <string>
#include "ColorTable.h"
Classes
struct StringX4Int
struct StringXString
struct StringXNumber
struct StringXColor
Macros
#define GMSH_SET (1 << 0)
#define GMSH_GET (1 << 1)
#define GMSH_GUI (1 << 2)
#define GMSH_SET_DEFAULT (1 << 3)
#define GMSH_GET_DEFAULT (1 << 4)
#define GMSH_SESSIONRC (1 << 0)
#define GMSH_OPTIONSRC (1 << 1)
#define GMSH_FULLRC (1 << 2)
#define GMSH_DEPRECATED (1 << 3)
#define OPT_ARGS_STR int num, int action, const std::string &val
#define OPT_ARGS_NUM int num, int action, double val
#define OPT_ARGS_COL int num, int action, unsigned int val
Functions
std::string opt_general_axes_label0 (OPT_ARGS_STR)
std::string opt_general_axes_label1 (OPT_ARGS_STR)
std::string opt_general_axes_label2 (OPT_ARGS_STR)
std::string opt_general_axes_format0 (OPT_ARGS_STR)
std::string opt_general_axes_format1 (OPT_ARGS_STR)
std::string opt_general_axes_format2 (OPT_ARGS_STR)
std::string opt_general_background_image_filename (OPT_ARGS_STR)
std::string opt_general_display (OPT_ARGS_STR)
std::string opt_general_version (OPT_ARGS_STR)
std::string opt_general_build_options (OPT_ARGS_STR)
std::string opt_general_build_info (OPT_ARGS_STR)
std::string opt_general_filename (OPT_ARGS_STR)
std::string opt_general_executable_filename (OPT_ARGS_STR)
std::string opt_general_default_filename (OPT_ARGS_STR)
std::string opt_general_tmp_filename (OPT_ARGS_STR)
std::string opt_general_error_filename (OPT_ARGS_STR)
std::string opt_general_session_filename (OPT_ARGS_STR)
std::string opt_general_options_filename (OPT_ARGS_STR)
std::string opt_general_recent_file0 (OPT_ARGS_STR)
std::string opt_general_recent_file1 (OPT_ARGS_STR)
std::string opt_general_recent_file2 (OPT_ARGS_STR)
std::string opt_general_recent_file3 (OPT_ARGS_STR)
std::string opt_general_recent_file4 (OPT_ARGS_STR)
std::string opt_general_recent_file5 (OPT_ARGS_STR)
std::string opt_general_recent_file6 (OPT_ARGS_STR)
std::string opt_general_recent_file7 (OPT_ARGS_STR)
std::string opt_general_recent_file8 (OPT_ARGS_STR)
std::string opt_general_recent_file9 (OPT_ARGS_STR)
std::string opt_general_scripting_languages (OPT_ARGS_STR)
std::string opt_general_editor (OPT_ARGS_STR)
std::string opt_general_watch_file_pattern (OPT_ARGS_STR)
std::string opt_general_gui_theme (OPT_ARGS_STR)
std::string opt_general_graphics_font (OPT_ARGS_STR)
std::string opt_general_graphics_font_title (OPT_ARGS_STR)
std::string opt_general_graphics_font_engine (OPT_ARGS_STR)
std::string opt_geometry_double_clicked_point_command (OPT_ARGS_STR)
std::string opt_geometry_double_clicked_curve_command (OPT_ARGS_STR)
std::string opt_geometry_double_clicked_surface_command (OPT_ARGS_STR)
std::string opt_geometry_double_clicked_volume_command (OPT_ARGS_STR)
std::string opt_geometry_occ_target_unit (OPT_ARGS_STR)
std::string opt_geometry_pipe_default_trihedron (OPT_ARGS_STR)
std::string opt_solver_socket_name (OPT_ARGS_STR)
std::string opt_solver_name (OPT_ARGS_STR)
std::string opt_solver_name0 (OPT_ARGS_STR)
std::string opt_solver_name1 (OPT_ARGS_STR)
std::string opt_solver_name2 (OPT_ARGS_STR)
std::string opt_solver_name3 (OPT_ARGS_STR)
std::string opt_solver_name4 (OPT_ARGS_STR)
std::string opt_solver_name5 (OPT_ARGS_STR)
std::string opt_solver_name6 (OPT_ARGS_STR)
std::string opt_solver_name7 (OPT_ARGS_STR)
std::string opt_solver_name8 (OPT_ARGS_STR)
std::string opt_solver_name9 (OPT_ARGS_STR)
std::string opt_solver_extension (OPT_ARGS_STR)
std::string opt_solver_extension0 (OPT_ARGS_STR)
std::string opt_solver_extension1 (OPT_ARGS_STR)
std::string opt_solver_extension2 (OPT_ARGS_STR)
std::string opt_solver_extension3 (OPT_ARGS_STR)
std::string opt_solver_extension4 (OPT_ARGS_STR)
std::string opt_solver_extension5 (OPT_ARGS_STR)
std::string opt_solver_extension6 (OPT_ARGS_STR)
std::string opt_solver_extension7 (OPT_ARGS_STR)
std::string opt_solver_extension8 (OPT_ARGS_STR)
std::string opt_solver_extension9 (OPT_ARGS_STR)
std::string opt_solver_executable (OPT_ARGS_STR)
std::string opt_solver_executable0 (OPT_ARGS_STR)
std::string opt_solver_executable1 (OPT_ARGS_STR)
std::string opt_solver_executable2 (OPT_ARGS_STR)
std::string opt_solver_executable3 (OPT_ARGS_STR)
std::string opt_solver_executable4 (OPT_ARGS_STR)
std::string opt_solver_executable5 (OPT_ARGS_STR)
std::string opt_solver_executable6 (OPT_ARGS_STR)
std::string opt_solver_executable7 (OPT_ARGS_STR)
std::string opt_solver_executable8 (OPT_ARGS_STR)
std::string opt_solver_executable9 (OPT_ARGS_STR)
std::string opt_solver_remote_login (OPT_ARGS_STR)
std::string opt_solver_remote_login0 (OPT_ARGS_STR)
std::string opt_solver_remote_login1 (OPT_ARGS_STR)
std::string opt_solver_remote_login2 (OPT_ARGS_STR)
std::string opt_solver_remote_login3 (OPT_ARGS_STR)
std::string opt_solver_remote_login4 (OPT_ARGS_STR)
std::string opt_solver_remote_login5 (OPT_ARGS_STR)
std::string opt_solver_remote_login6 (OPT_ARGS_STR)
std::string opt_solver_remote_login7 (OPT_ARGS_STR)
std::string opt_solver_remote_login8 (OPT_ARGS_STR)
std::string opt_solver_remote_login9 (OPT_ARGS_STR)
std::string opt_solver_octave_interpreter (OPT_ARGS_STR)
std::string opt_solver_python_interpreter (OPT_ARGS_STR)
std::string opt_post_double_clicked_graph_point_command (OPT_ARGS_STR)
std::string opt_view_name (OPT_ARGS_STR)
std::string opt_view_format (OPT_ARGS_STR)
std::string opt_view_filename (OPT_ARGS_STR)
std::string opt_view_double_clicked_command (OPT_ARGS_STR)
std::string opt_view_group (OPT_ARGS_STR)
std::string opt_view_axes_label0 (OPT_ARGS_STR)
std::string opt_view_axes_label1 (OPT_ARGS_STR)
std::string opt_view_axes_label2 (OPT_ARGS_STR)
std::string opt_view_axes_format0 (OPT_ARGS_STR)
std::string opt_view_axes_format1 (OPT_ARGS_STR)
std::string opt_view_axes_format2 (OPT_ARGS_STR)
std::string opt_view_gen_raise0 (OPT_ARGS_STR)
std::string opt_view_gen_raise1 (OPT_ARGS_STR)
std::string opt_view_gen_raise2 (OPT_ARGS_STR)
std::string opt_view_stipple0 (OPT_ARGS_STR)
std::string opt_view_stipple1 (OPT_ARGS_STR)
std::string opt_view_stipple2 (OPT_ARGS_STR)
std::string opt_view_stipple3 (OPT_ARGS_STR)
std::string opt_view_stipple4 (OPT_ARGS_STR)
std::string opt_view_stipple5 (OPT_ARGS_STR)
std::string opt_view_stipple6 (OPT_ARGS_STR)
std::string opt_view_stipple7 (OPT_ARGS_STR)
std::string opt_view_stipple8 (OPT_ARGS_STR)
std::string opt_view_stipple9 (OPT_ARGS_STR)
std::string opt_view_attributes (OPT_ARGS_STR)
std::string opt_print_parameter_command (OPT_ARGS_STR)
double opt_general_abort_on_error (OPT_ARGS_NUM)
double opt_general_initial_context (OPT_ARGS_NUM)
double opt_general_show_options_on_startup (OPT_ARGS_NUM)
double opt_general_show_messages_on_startup (OPT_ARGS_NUM)
double opt_general_fontsize (OPT_ARGS_NUM)
double opt_general_gui_color_scheme (OPT_ARGS_NUM)
double opt_general_gui_refresh_rate (OPT_ARGS_NUM)
double opt_general_graphics_fontsize (OPT_ARGS_NUM)
double opt_general_graphics_fontsize_title (OPT_ARGS_NUM)
double opt_general_graphics_position0 (OPT_ARGS_NUM)
double opt_general_graphics_position1 (OPT_ARGS_NUM)
double opt_general_graphics_size0 (OPT_ARGS_NUM)
double opt_general_graphics_size1 (OPT_ARGS_NUM)
double opt_general_context_position0 (OPT_ARGS_NUM)
double opt_general_context_position1 (OPT_ARGS_NUM)
double opt_general_file_chooser_position0 (OPT_ARGS_NUM)
double opt_general_file_chooser_position1 (OPT_ARGS_NUM)
double opt_general_polygon_offset_always (OPT_ARGS_NUM)
double opt_general_polygon_offset_factor (OPT_ARGS_NUM)
double opt_general_polygon_offset_units (OPT_ARGS_NUM)
double opt_general_system_menu_bar (OPT_ARGS_NUM)
double opt_general_native_file_chooser (OPT_ARGS_NUM)
double opt_general_show_module_menu (OPT_ARGS_NUM)
double opt_general_message_size (OPT_ARGS_NUM)
double opt_general_message_fontsize (OPT_ARGS_NUM)
double opt_general_detached_menu (OPT_ARGS_NUM)
double opt_general_detached_process (OPT_ARGS_NUM)
double opt_general_menu_size0 (OPT_ARGS_NUM)
double opt_general_menu_size1 (OPT_ARGS_NUM)
double opt_general_menu_position0 (OPT_ARGS_NUM)
double opt_general_menu_position1 (OPT_ARGS_NUM)
double opt_general_option_position0 (OPT_ARGS_NUM)
double opt_general_option_position1 (OPT_ARGS_NUM)
double opt_general_plugin_position0 (OPT_ARGS_NUM)
double opt_general_plugin_position1 (OPT_ARGS_NUM)
double opt_general_plugin_size0 (OPT_ARGS_NUM)
double opt_general_plugin_size1 (OPT_ARGS_NUM)
double opt_general_field_position0 (OPT_ARGS_NUM)
double opt_general_field_position1 (OPT_ARGS_NUM)
double opt_general_field_size0 (OPT_ARGS_NUM)
double opt_general_field_size1 (OPT_ARGS_NUM)
double opt_general_extra_position0 (OPT_ARGS_NUM)
double opt_general_extra_position1 (OPT_ARGS_NUM)
double opt_general_extra_size0 (OPT_ARGS_NUM)
double opt_general_extra_size1 (OPT_ARGS_NUM)
double opt_general_statistics_position0 (OPT_ARGS_NUM)
double opt_general_statistics_position1 (OPT_ARGS_NUM)
double opt_general_visibility_position0 (OPT_ARGS_NUM)
double opt_general_visibility_position1 (OPT_ARGS_NUM)
double opt_general_clip_position0 (OPT_ARGS_NUM)
double opt_general_clip_position1 (OPT_ARGS_NUM)
double opt_general_manip_position0 (OPT_ARGS_NUM)
double opt_general_manip_position1 (OPT_ARGS_NUM)
double opt_general_hot_position0 (OPT_ARGS_NUM)
double opt_general_hot_position1 (OPT_ARGS_NUM)
double opt_general_high_resolution_graphics (OPT_ARGS_NUM)
double opt_general_session_save (OPT_ARGS_NUM)
double opt_general_options_save (OPT_ARGS_NUM)
double opt_general_rotation0 (OPT_ARGS_NUM)
double opt_general_rotation1 (OPT_ARGS_NUM)
double opt_general_rotation2 (OPT_ARGS_NUM)
double opt_general_rotation_center0 (OPT_ARGS_NUM)
double opt_general_rotation_center1 (OPT_ARGS_NUM)
double opt_general_rotation_center2 (OPT_ARGS_NUM)
double opt_general_quaternion0 (OPT_ARGS_NUM)
double opt_general_quaternion1 (OPT_ARGS_NUM)
double opt_general_quaternion2 (OPT_ARGS_NUM)
double opt_general_quaternion3 (OPT_ARGS_NUM)
double opt_general_translation0 (OPT_ARGS_NUM)
double opt_general_translation1 (OPT_ARGS_NUM)
double opt_general_translation2 (OPT_ARGS_NUM)
double opt_general_scale0 (OPT_ARGS_NUM)
double opt_general_scale1 (OPT_ARGS_NUM)
double opt_general_scale2 (OPT_ARGS_NUM)
double opt_general_clip_factor (OPT_ARGS_NUM)
double opt_general_display_border_factor (OPT_ARGS_NUM)
double opt_general_point_size (OPT_ARGS_NUM)
double opt_general_line_width (OPT_ARGS_NUM)
double opt_general_shine (OPT_ARGS_NUM)
double opt_general_shine_exponent (OPT_ARGS_NUM)
double opt_general_color_scheme (OPT_ARGS_NUM)
double opt_general_background_gradient (OPT_ARGS_NUM)
double opt_general_background_image_position0 (OPT_ARGS_NUM)
double opt_general_background_image_position1 (OPT_ARGS_NUM)
double opt_general_background_image_size0 (OPT_ARGS_NUM)
double opt_general_background_image_size1 (OPT_ARGS_NUM)
double opt_general_background_image_3d (OPT_ARGS_NUM)
double opt_general_background_image_page (OPT_ARGS_NUM)
double opt_general_verbosity (OPT_ARGS_NUM)
double opt_general_progress_meter_step (OPT_ARGS_NUM)
double opt_general_nopopup (OPT_ARGS_NUM)
double opt_general_non_modal_windows (OPT_ARGS_NUM)
double opt_general_terminal (OPT_ARGS_NUM)
double opt_general_tooltips (OPT_ARGS_NUM)
double opt_general_input_scrolling (OPT_ARGS_NUM)
double opt_general_confirm_overwrite (OPT_ARGS_NUM)
double opt_general_orthographic (OPT_ARGS_NUM)
double opt_general_mouse_selection (OPT_ARGS_NUM)
double opt_general_mouse_hover_meshes (OPT_ARGS_NUM)
double opt_general_mouse_invert_zoom (OPT_ARGS_NUM)
double opt_general_draw_bounding_box (OPT_ARGS_NUM)
double opt_general_draw_oriented_bounding_box (OPT_ARGS_NUM)
double opt_general_fast_redraw (OPT_ARGS_NUM)
double opt_general_xmin (OPT_ARGS_NUM)
double opt_general_xmax (OPT_ARGS_NUM)
double opt_general_ymin (OPT_ARGS_NUM)
double opt_general_ymax (OPT_ARGS_NUM)
double opt_general_zmin (OPT_ARGS_NUM)
double opt_general_zmax (OPT_ARGS_NUM)
double opt_general_lc (OPT_ARGS_NUM)
double opt_general_axes (OPT_ARGS_NUM)
double opt_general_axes_mikado (OPT_ARGS_NUM)
double opt_general_axes_auto_position (OPT_ARGS_NUM)
double opt_general_axes_xmin (OPT_ARGS_NUM)
double opt_general_axes_xmax (OPT_ARGS_NUM)
double opt_general_axes_ymin (OPT_ARGS_NUM)
double opt_general_axes_ymax (OPT_ARGS_NUM)
double opt_general_axes_zmin (OPT_ARGS_NUM)
double opt_general_axes_zmax (OPT_ARGS_NUM)
double opt_general_axes_tics0 (OPT_ARGS_NUM)
double opt_general_axes_tics1 (OPT_ARGS_NUM)
double opt_general_axes_tics2 (OPT_ARGS_NUM)
double opt_general_axes_force_value (OPT_ARGS_NUM)
double opt_general_axes_value_xmin (OPT_ARGS_NUM)
double opt_general_axes_value_xmax (OPT_ARGS_NUM)
double opt_general_axes_value_ymin (OPT_ARGS_NUM)
double opt_general_axes_value_ymax (OPT_ARGS_NUM)
double opt_general_axes_value_zmin (OPT_ARGS_NUM)
double opt_general_axes_value_zmax (OPT_ARGS_NUM)
double opt_general_small_axes (OPT_ARGS_NUM)
double opt_general_small_axes_position0 (OPT_ARGS_NUM)
double opt_general_small_axes_position1 (OPT_ARGS_NUM)
double opt_general_small_axes_size (OPT_ARGS_NUM)
double opt_general_quadric_subdivisions (OPT_ARGS_NUM)
double opt_general_double_buffer (OPT_ARGS_NUM)
double opt_general_antialiasing (OPT_ARGS_NUM)
double opt_general_alpha_blending (OPT_ARGS_NUM)
double opt_general_vector_type (OPT_ARGS_NUM)
double opt_general_arrow_head_radius (OPT_ARGS_NUM)
double opt_general_arrow_stem_length (OPT_ARGS_NUM)
double opt_general_arrow_stem_radius (OPT_ARGS_NUM)
double opt_general_trackball (OPT_ARGS_NUM)
double opt_general_trackball_hyperbolic_sheet (OPT_ARGS_NUM)
double opt_general_gamepad (OPT_ARGS_NUM)
double opt_general_rotation_center_cg (OPT_ARGS_NUM)
double opt_general_zoom_factor (OPT_ARGS_NUM)
double opt_general_expert_mode (OPT_ARGS_NUM)
double opt_general_stereo_mode (OPT_ARGS_NUM)
double opt_general_camera_mode (OPT_ARGS_NUM)
double opt_general_eye_sep_ratio (OPT_ARGS_NUM)
double opt_general_focallength_ratio (OPT_ARGS_NUM)
double opt_general_camera_aperture (OPT_ARGS_NUM)
double opt_general_clip0a (OPT_ARGS_NUM)
double opt_general_clip0b (OPT_ARGS_NUM)
double opt_general_clip0c (OPT_ARGS_NUM)
double opt_general_clip0d (OPT_ARGS_NUM)
double opt_general_clip1a (OPT_ARGS_NUM)
double opt_general_clip1b (OPT_ARGS_NUM)
double opt_general_clip1c (OPT_ARGS_NUM)
double opt_general_clip1d (OPT_ARGS_NUM)
double opt_general_clip2a (OPT_ARGS_NUM)
double opt_general_clip2b (OPT_ARGS_NUM)
double opt_general_clip2c (OPT_ARGS_NUM)
double opt_general_clip2d (OPT_ARGS_NUM)
double opt_general_clip3a (OPT_ARGS_NUM)
double opt_general_clip3b (OPT_ARGS_NUM)
double opt_general_clip3c (OPT_ARGS_NUM)
double opt_general_clip3d (OPT_ARGS_NUM)
double opt_general_clip4a (OPT_ARGS_NUM)
double opt_general_clip4b (OPT_ARGS_NUM)
double opt_general_clip4c (OPT_ARGS_NUM)
double opt_general_clip4d (OPT_ARGS_NUM)
double opt_general_clip5a (OPT_ARGS_NUM)
double opt_general_clip5b (OPT_ARGS_NUM)
double opt_general_clip5c (OPT_ARGS_NUM)
double opt_general_clip5d (OPT_ARGS_NUM)
double opt_general_clip_whole_elements (OPT_ARGS_NUM)
double opt_general_clip_only_draw_intersecting_volume (OPT_ARGS_NUM)
double opt_general_clip_only_volume (OPT_ARGS_NUM)
double opt_general_light0 (OPT_ARGS_NUM)
double opt_general_light00 (OPT_ARGS_NUM)
double opt_general_light01 (OPT_ARGS_NUM)
double opt_general_light02 (OPT_ARGS_NUM)
double opt_general_light03 (OPT_ARGS_NUM)
double opt_general_light1 (OPT_ARGS_NUM)
double opt_general_light10 (OPT_ARGS_NUM)
double opt_general_light11 (OPT_ARGS_NUM)
double opt_general_light12 (OPT_ARGS_NUM)
double opt_general_light13 (OPT_ARGS_NUM)
double opt_general_light2 (OPT_ARGS_NUM)
double opt_general_light20 (OPT_ARGS_NUM)
double opt_general_light21 (OPT_ARGS_NUM)
double opt_general_light22 (OPT_ARGS_NUM)
double opt_general_light23 (OPT_ARGS_NUM)
double opt_general_light3 (OPT_ARGS_NUM)
double opt_general_light30 (OPT_ARGS_NUM)
double opt_general_light31 (OPT_ARGS_NUM)
double opt_general_light32 (OPT_ARGS_NUM)
double opt_general_light33 (OPT_ARGS_NUM)
double opt_general_light4 (OPT_ARGS_NUM)
double opt_general_light40 (OPT_ARGS_NUM)
double opt_general_light41 (OPT_ARGS_NUM)
double opt_general_light42 (OPT_ARGS_NUM)
double opt_general_light43 (OPT_ARGS_NUM)
double opt_general_light5 (OPT_ARGS_NUM)
double opt_general_light50 (OPT_ARGS_NUM)
double opt_general_light51 (OPT_ARGS_NUM)
double opt_general_light52 (OPT_ARGS_NUM)
double opt_general_light53 (OPT_ARGS_NUM)
double opt_general_num_threads (OPT_ARGS_NUM)
double opt_geometry_transform (OPT_ARGS_NUM)
double opt_geometry_transform00 (OPT_ARGS_NUM)
double opt_geometry_transform01 (OPT_ARGS_NUM)
double opt_geometry_transform02 (OPT_ARGS_NUM)
double opt_geometry_transform10 (OPT_ARGS_NUM)
double opt_geometry_transform11 (OPT_ARGS_NUM)
double opt_geometry_transform12 (OPT_ARGS_NUM)
double opt_geometry_transform20 (OPT_ARGS_NUM)
double opt_geometry_transform21 (OPT_ARGS_NUM)
double opt_geometry_transform22 (OPT_ARGS_NUM)
double opt_geometry_offset0 (OPT_ARGS_NUM)
double opt_geometry_offset1 (OPT_ARGS_NUM)
double opt_geometry_offset2 (OPT_ARGS_NUM)
double opt_geometry_auto_coherence (OPT_ARGS_NUM)
double opt_geometry_oriented_physicals (OPT_ARGS_NUM)
double opt_geometry_highlight_orphans (OPT_ARGS_NUM)
double opt_geometry_tolerance (OPT_ARGS_NUM)
double opt_geometry_tolerance_boolean (OPT_ARGS_NUM)
double opt_geometry_normals (OPT_ARGS_NUM)
double opt_geometry_tangents (OPT_ARGS_NUM)
double opt_geometry_points (OPT_ARGS_NUM)
double opt_geometry_curves (OPT_ARGS_NUM)
double opt_geometry_surfaces (OPT_ARGS_NUM)
double opt_geometry_volumes (OPT_ARGS_NUM)
double opt_geometry_point_labels (OPT_ARGS_NUM)
double opt_geometry_curve_labels (OPT_ARGS_NUM)
double opt_geometry_surface_labels (OPT_ARGS_NUM)
double opt_geometry_volume_labels (OPT_ARGS_NUM)
double opt_geometry_label_type (OPT_ARGS_NUM)
double opt_geometry_point_size (OPT_ARGS_NUM)
double opt_geometry_point_sel_size (OPT_ARGS_NUM)
double opt_geometry_point_type (OPT_ARGS_NUM)
double opt_geometry_reparam_on_face_robust (OPT_ARGS_NUM)
double opt_geometry_curve_width (OPT_ARGS_NUM)
double opt_geometry_curve_sel_width (OPT_ARGS_NUM)
double opt_geometry_curve_type (OPT_ARGS_NUM)
double opt_geometry_surface_type (OPT_ARGS_NUM)
double opt_geometry_light (OPT_ARGS_NUM)
double opt_geometry_light_two_side (OPT_ARGS_NUM)
double opt_geometry_occ_auto_embed (OPT_ARGS_NUM)
double opt_geometry_occ_safe_unbind (OPT_ARGS_NUM)
double opt_geometry_occ_auto_fix (OPT_ARGS_NUM)
double opt_geometry_occ_bounds_use_stl (OPT_ARGS_NUM)
double opt_geometry_occ_disable_stl (OPT_ARGS_NUM)
double opt_geometry_occ_fix_degenerated (OPT_ARGS_NUM)
double opt_geometry_occ_fix_small_edges (OPT_ARGS_NUM)
double opt_geometry_occ_fix_small_faces (OPT_ARGS_NUM)
double opt_geometry_occ_sew_faces (OPT_ARGS_NUM)
double opt_geometry_occ_make_solids (OPT_ARGS_NUM)
double opt_geometry_occ_union_unify (OPT_ARGS_NUM)
double opt_geometry_occ_parallel (OPT_ARGS_NUM)
double opt_geometry_occ_boolean_preserve_numbering (OPT_ARGS_NUM)
double opt_geometry_occ_scaling (OPT_ARGS_NUM)
double opt_geometry_occ_export_only_visible (OPT_ARGS_NUM)
double opt_geometry_occ_import_labels (OPT_ARGS_NUM)
double opt_geometry_occ_thrusections_degree (OPT_ARGS_NUM)
double opt_geometry_occ_use_generic_closest_point (OPT_ARGS_NUM)
double opt_geometry_old_circle (OPT_ARGS_NUM)
double opt_geometry_old_newreg (OPT_ARGS_NUM)
double opt_geometry_old_ruled_surface (OPT_ARGS_NUM)
double opt_geometry_num_sub_edges (OPT_ARGS_NUM)
double opt_geometry_extrude_spline_points (OPT_ARGS_NUM)
double opt_geometry_extrude_return_lateral (OPT_ARGS_NUM)
double opt_geometry_scaling_factor (OPT_ARGS_NUM)
double opt_geometry_snap_points (OPT_ARGS_NUM)
double opt_geometry_snap0 (OPT_ARGS_NUM)
double opt_geometry_snap1 (OPT_ARGS_NUM)
double opt_geometry_snap2 (OPT_ARGS_NUM)
double opt_geometry_clip (OPT_ARGS_NUM)
double opt_geometry_copy_meshing_method (OPT_ARGS_NUM)
double opt_geometry_double_clicked_entity_tag (OPT_ARGS_NUM)
double opt_geometry_exact_extrusion (OPT_ARGS_NUM)
double opt_geometry_match_geom_and_mesh (OPT_ARGS_NUM)
double opt_geometry_match_mesh_scale_factor (OPT_ARGS_NUM)
double opt_geometry_match_mesh_tolerance (OPT_ARGS_NUM)
double opt_mesh_label_sampling (OPT_ARGS_NUM)
double opt_mesh_optimize (OPT_ARGS_NUM)
double opt_mesh_optimize_threshold (OPT_ARGS_NUM)
double opt_mesh_optimize_netgen (OPT_ARGS_NUM)
double opt_mesh_refine_steps (OPT_ARGS_NUM)
double opt_mesh_normals (OPT_ARGS_NUM)
double opt_mesh_num_sub_edges (OPT_ARGS_NUM)
double opt_mesh_tangents (OPT_ARGS_NUM)
double opt_mesh_explode (OPT_ARGS_NUM)
double opt_mesh_scaling_factor (OPT_ARGS_NUM)
double opt_mesh_lc_min (OPT_ARGS_NUM)
double opt_mesh_lc_max (OPT_ARGS_NUM)
double opt_mesh_tolerance_edge_length (OPT_ARGS_NUM)
double opt_mesh_tolerance_initial_delaunay (OPT_ARGS_NUM)
double opt_mesh_lc_factor (OPT_ARGS_NUM)
double opt_mesh_lc_from_curvature (OPT_ARGS_NUM)
double opt_mesh_lc_from_curvature_iso (OPT_ARGS_NUM)
double opt_mesh_lc_from_points (OPT_ARGS_NUM)
double opt_mesh_lc_from_parametric_points (OPT_ARGS_NUM)
double opt_mesh_lc_extend_from_boundary (OPT_ARGS_NUM)
double opt_mesh_lc_integration_precision (OPT_ARGS_NUM)
double opt_mesh_rand_factor (OPT_ARGS_NUM)
double opt_mesh_rand_factor3d (OPT_ARGS_NUM)
double opt_mesh_quality_inf (OPT_ARGS_NUM)
double opt_mesh_quality_sup (OPT_ARGS_NUM)
double opt_mesh_quality_type (OPT_ARGS_NUM)
double opt_mesh_radius_inf (OPT_ARGS_NUM)
double opt_mesh_radius_sup (OPT_ARGS_NUM)
double opt_mesh_label_type (OPT_ARGS_NUM)
double opt_mesh_first_element_tag (OPT_ARGS_NUM)
double opt_mesh_first_node_tag (OPT_ARGS_NUM)
double opt_mesh_nodes (OPT_ARGS_NUM)
double opt_mesh_lines (OPT_ARGS_NUM)
double opt_mesh_triangles (OPT_ARGS_NUM)
double opt_mesh_quadrangles (OPT_ARGS_NUM)
double opt_mesh_tetrahedra (OPT_ARGS_NUM)
double opt_mesh_hexahedra (OPT_ARGS_NUM)
double opt_mesh_prisms (OPT_ARGS_NUM)
double opt_mesh_pyramids (OPT_ARGS_NUM)
double opt_mesh_trihedra (OPT_ARGS_NUM)
double opt_mesh_transfinite_tri (OPT_ARGS_NUM)
double opt_mesh_surface_edges (OPT_ARGS_NUM)
double opt_mesh_surface_faces (OPT_ARGS_NUM)
double opt_mesh_volume_edges (OPT_ARGS_NUM)
double opt_mesh_volume_faces (OPT_ARGS_NUM)
double opt_mesh_node_labels (OPT_ARGS_NUM)
double opt_mesh_line_labels (OPT_ARGS_NUM)
double opt_mesh_surface_labels (OPT_ARGS_NUM)
double opt_mesh_volume_labels (OPT_ARGS_NUM)
double opt_mesh_node_size (OPT_ARGS_NUM)
double opt_mesh_node_type (OPT_ARGS_NUM)
double opt_mesh_line_width (OPT_ARGS_NUM)
double opt_mesh_smooth_normals (OPT_ARGS_NUM)
double opt_mesh_smooth_ratio (OPT_ARGS_NUM)
double opt_mesh_angle_smooth_normals (OPT_ARGS_NUM)
double opt_mesh_aniso_max (OPT_ARGS_NUM)
double opt_mesh_light (OPT_ARGS_NUM)
double opt_mesh_light_lines (OPT_ARGS_NUM)
double opt_mesh_light_two_side (OPT_ARGS_NUM)
double opt_mesh_file_format (OPT_ARGS_NUM)
double opt_mesh_newton_convergence_test_xyz (OPT_ARGS_NUM)
double opt_mesh_msh_file_version (OPT_ARGS_NUM)
double opt_mesh_med_file_minor_version (OPT_ARGS_NUM)
double opt_mesh_med_import_groups_of_nodes (OPT_ARGS_NUM)
double opt_mesh_med_single_model (OPT_ARGS_NUM)
double opt_mesh_partition_split_mesh_files (OPT_ARGS_NUM)
double opt_mesh_partition_save_topology_file (OPT_ARGS_NUM)
double opt_mesh_partition_num (OPT_ARGS_NUM)
double opt_mesh_partition_metis_algorithm (OPT_ARGS_NUM)
double opt_mesh_partition_metis_edge_matching (OPT_ARGS_NUM)
double opt_mesh_partition_metis_refinement_algorithm (OPT_ARGS_NUM)
double opt_mesh_partition_metis_max_load_imbalance (OPT_ARGS_NUM)
double opt_mesh_partition_metis_objective (OPT_ARGS_NUM)
double opt_mesh_partition_metis_min_conn (OPT_ARGS_NUM)
double opt_mesh_partition_hex_weight (OPT_ARGS_NUM)
double opt_mesh_partition_pri_weight (OPT_ARGS_NUM)
double opt_mesh_partition_pyr_weight (OPT_ARGS_NUM)
double opt_mesh_partition_trih_weight (OPT_ARGS_NUM)
double opt_mesh_partition_qua_weight (OPT_ARGS_NUM)
double opt_mesh_partition_tet_weight (OPT_ARGS_NUM)
double opt_mesh_partition_tri_weight (OPT_ARGS_NUM)
double opt_mesh_partition_line_weight (OPT_ARGS_NUM)
double opt_mesh_partition_create_topology (OPT_ARGS_NUM)
double opt_mesh_partition_create_physicals (OPT_ARGS_NUM)
double opt_mesh_partition_create_ghost_cells (OPT_ARGS_NUM)
double opt_mesh_partition_old_style_msh2 (OPT_ARGS_NUM)
double opt_mesh_partition_convert_msh2 (OPT_ARGS_NUM)
double opt_mesh_create_topology_msh2 (OPT_ARGS_NUM)
double opt_mesh_binary (OPT_ARGS_NUM)
double opt_mesh_smooth_cross_field (OPT_ARGS_NUM)
double opt_mesh_cross_field_closest_point (OPT_ARGS_NUM)
double opt_mesh_bdf_field_format (OPT_ARGS_NUM)
double opt_mesh_stl_remove_duplicate_triangles (OPT_ARGS_NUM)
double opt_mesh_stl_one_solid_per_surface (OPT_ARGS_NUM)
double opt_mesh_stl_linear_deflection (OPT_ARGS_NUM)
double opt_mesh_stl_linear_deflection_relative (OPT_ARGS_NUM)
double opt_mesh_stl_angular_deflection (OPT_ARGS_NUM)
double opt_mesh_boundary_layer_fan_elements (OPT_ARGS_NUM)
double opt_mesh_nb_smoothing (OPT_ARGS_NUM)
double opt_mesh_algo2d (OPT_ARGS_NUM)
double opt_mesh_algo3d (OPT_ARGS_NUM)
double opt_mesh_algo_switch_on_failure (OPT_ARGS_NUM)
double opt_mesh_algo_recombine (OPT_ARGS_NUM)
double opt_mesh_max_retries (OPT_ARGS_NUM)
double opt_mesh_recombine_all (OPT_ARGS_NUM)
double opt_mesh_recombine_optimize_topology (OPT_ARGS_NUM)
double opt_mesh_recombine_node_repositioning (OPT_ARGS_NUM)
double opt_mesh_recombine_minimum_quality (OPT_ARGS_NUM)
double opt_mesh_recombine3d_all (OPT_ARGS_NUM)
double opt_mesh_recombine3d_level (OPT_ARGS_NUM)
double opt_mesh_recombine3d_conformity (OPT_ARGS_NUM)
double opt_mesh_flexible_transfinite (OPT_ARGS_NUM)
double opt_mesh_algo_subdivide (OPT_ARGS_NUM)
double opt_mesh_mesh_only_visible (OPT_ARGS_NUM)
double opt_mesh_mesh_only_empty (OPT_ARGS_NUM)
double opt_mesh_min_line_nodes (OPT_ARGS_NUM)
double opt_mesh_min_circle_nodes (OPT_ARGS_NUM)
double opt_mesh_allow_swap_edge_angle (OPT_ARGS_NUM)
double opt_mesh_min_curve_nodes (OPT_ARGS_NUM)
double opt_mesh_order (OPT_ARGS_NUM)
double opt_mesh_ho_optimize (OPT_ARGS_NUM)
double opt_mesh_ho_periodic (OPT_ARGS_NUM)
double opt_mesh_ho_save_periodic (OPT_ARGS_NUM)
double opt_mesh_ho_nlayers (OPT_ARGS_NUM)
double opt_mesh_ho_threshold_min (OPT_ARGS_NUM)
double opt_mesh_ho_threshold_max (OPT_ARGS_NUM)
double opt_mesh_ho_poisson (OPT_ARGS_NUM)
double opt_mesh_ho_prim_surf_mesh (OPT_ARGS_NUM)
double opt_mesh_ho_dist_cad (OPT_ARGS_NUM)
double opt_mesh_ho_iter_max (OPT_ARGS_NUM)
double opt_mesh_ho_pass_max (OPT_ARGS_NUM)
double opt_mesh_ho_fast_new_algo (OPT_ARGS_NUM)
double opt_mesh_ho_curve_outer_BL (OPT_ARGS_NUM)
double opt_mesh_ho_max_rho (OPT_ARGS_NUM)
double opt_mesh_ho_max_angle (OPT_ARGS_NUM)
double opt_mesh_ho_max_in_angle (OPT_ARGS_NUM)
double opt_mesh_ho_fix_bnd_nodes (OPT_ARGS_NUM)
double opt_mesh_second_order_linear (OPT_ARGS_NUM)
double opt_mesh_second_order_incomplete (OPT_ARGS_NUM)
double opt_mesh_cgns_import_order (OPT_ARGS_NUM)
double opt_mesh_cgns_import_ignore_bc (OPT_ARGS_NUM)
double opt_mesh_cgns_import_ignore_solution (OPT_ARGS_NUM)
double opt_mesh_cgns_construct_topology (OPT_ARGS_NUM)
double opt_mesh_cgns_export_cpex0045 (OPT_ARGS_NUM)
double opt_mesh_cgns_export_structured (OPT_ARGS_NUM)
double opt_mesh_dual (OPT_ARGS_NUM)
double opt_mesh_voronoi (OPT_ARGS_NUM)
double opt_mesh_draw_skin_only (OPT_ARGS_NUM)
double opt_mesh_save_all (OPT_ARGS_NUM)
double opt_mesh_save_element_tag_type (OPT_ARGS_NUM)
double opt_mesh_save_parametric (OPT_ARGS_NUM)
double opt_mesh_save_without_orphans (OPT_ARGS_NUM)
double opt_mesh_save_topology (OPT_ARGS_NUM)
double opt_mesh_read_groups_of_elements (OPT_ARGS_NUM)
double opt_mesh_save_groups_of_elements (OPT_ARGS_NUM)
double opt_mesh_save_groups_of_nodes (OPT_ARGS_NUM)
double opt_mesh_color_carousel (OPT_ARGS_NUM)
double opt_mesh_compound_classify (OPT_ARGS_NUM)
double opt_mesh_compound_lc_factor (OPT_ARGS_NUM)
double opt_mesh_random_seed (OPT_ARGS_NUM)
double opt_mesh_switch_elem_tags (OPT_ARGS_NUM)
double opt_mesh_zone_definition (OPT_ARGS_NUM)
double opt_mesh_nb_nodes (OPT_ARGS_NUM)
double opt_mesh_nb_triangles (OPT_ARGS_NUM)
double opt_mesh_nb_quadrangles (OPT_ARGS_NUM)
double opt_mesh_nb_tetrahedra (OPT_ARGS_NUM)
double opt_mesh_nb_hexahedra (OPT_ARGS_NUM)
double opt_mesh_nb_prisms (OPT_ARGS_NUM)
double opt_mesh_nb_pyramids (OPT_ARGS_NUM)
double opt_mesh_nb_trihedra (OPT_ARGS_NUM)
double opt_mesh_cpu_time (OPT_ARGS_NUM)
double opt_mesh_clip (OPT_ARGS_NUM)
double opt_mesh_ignore_periodicity (OPT_ARGS_NUM)
double opt_mesh_preserve_numbering_msh2 (OPT_ARGS_NUM)
double opt_mesh_max_iter_delaunay_3d (OPT_ARGS_NUM)
double opt_mesh_max_num_threads_1d (OPT_ARGS_NUM)
double opt_mesh_max_num_threads_2d (OPT_ARGS_NUM)
double opt_mesh_max_num_threads_3d (OPT_ARGS_NUM)
double opt_mesh_angle_tolerance_facet_overlap (OPT_ARGS_NUM)
double opt_mesh_tolerance_reference_element (OPT_ARGS_NUM)
double opt_mesh_renumber (OPT_ARGS_NUM)
double opt_mesh_unv_strict_format (OPT_ARGS_NUM)
double opt_mesh_reparam_max_triangles (OPT_ARGS_NUM)
double opt_mesh_ignore_parametrization (OPT_ARGS_NUM)
double opt_mesh_quadqs_sizemap_method (OPT_ARGS_NUM)
double opt_mesh_quadqs_topo_optim_methods (OPT_ARGS_NUM)
double opt_mesh_quadqs_remeshing_boldness (OPT_ARGS_NUM)
double opt_mesh_quadqs_scaling_on_triangulation (OPT_ARGS_NUM)
double opt_mesh_old_initial_delaunay_2d (OPT_ARGS_NUM)
double opt_solver_listen (OPT_ARGS_NUM)
double opt_solver_timeout (OPT_ARGS_NUM)
double opt_solver_plugins (OPT_ARGS_NUM)
double opt_solver_auto_load_database (OPT_ARGS_NUM)
double opt_solver_auto_save_database (OPT_ARGS_NUM)
double opt_solver_auto_archive_output_files (OPT_ARGS_NUM)
double opt_solver_auto_check (OPT_ARGS_NUM)
double opt_solver_auto_mesh (OPT_ARGS_NUM)
double opt_solver_auto_merge_file (OPT_ARGS_NUM)
double opt_solver_auto_show_views (OPT_ARGS_NUM)
double opt_solver_auto_show_last_step (OPT_ARGS_NUM)
double opt_solver_show_invisible_parameters (OPT_ARGS_NUM)
double opt_post_horizontal_scales (OPT_ARGS_NUM)
double opt_post_binary (OPT_ARGS_NUM)
double opt_post_link (OPT_ARGS_NUM)
double opt_post_smooth (OPT_ARGS_NUM)
double opt_post_anim_delay (OPT_ARGS_NUM)
double opt_post_anim_cycle (OPT_ARGS_NUM)
double opt_post_anim_step (OPT_ARGS_NUM)
double opt_post_combine_remove_orig (OPT_ARGS_NUM)
double opt_post_combine_copy_options (OPT_ARGS_NUM)
double opt_post_plugins (OPT_ARGS_NUM)
double opt_post_nb_views (OPT_ARGS_NUM)
double opt_post_file_format (OPT_ARGS_NUM)
double opt_post_force_node_data (OPT_ARGS_NUM)
double opt_post_force_element_data (OPT_ARGS_NUM)
double opt_post_save_mesh (OPT_ARGS_NUM)
double opt_post_save_interpolation_matrices (OPT_ARGS_NUM)
double opt_post_double_clicked_graph_point_x (OPT_ARGS_NUM)
double opt_post_double_clicked_graph_point_y (OPT_ARGS_NUM)
double opt_post_double_clicked_view (OPT_ARGS_NUM)
double opt_view_nb_timestep (OPT_ARGS_NUM)
double opt_view_nb_non_empty_timestep (OPT_ARGS_NUM)
double opt_view_timestep (OPT_ARGS_NUM)
double opt_view_time (OPT_ARGS_NUM)
double opt_view_min (OPT_ARGS_NUM)
double opt_view_max (OPT_ARGS_NUM)
double opt_view_min_visible (OPT_ARGS_NUM)
double opt_view_max_visible (OPT_ARGS_NUM)
double opt_view_custom_min (OPT_ARGS_NUM)
double opt_view_custom_max (OPT_ARGS_NUM)
double opt_view_custom_abscissa_min (OPT_ARGS_NUM)
double opt_view_custom_abscissa_max (OPT_ARGS_NUM)
double opt_view_xmin (OPT_ARGS_NUM)
double opt_view_xmax (OPT_ARGS_NUM)
double opt_view_ymin (OPT_ARGS_NUM)
double opt_view_ymax (OPT_ARGS_NUM)
double opt_view_zmin (OPT_ARGS_NUM)
double opt_view_zmax (OPT_ARGS_NUM)
double opt_view_offset0 (OPT_ARGS_NUM)
double opt_view_offset1 (OPT_ARGS_NUM)
double opt_view_offset2 (OPT_ARGS_NUM)
double opt_view_raise0 (OPT_ARGS_NUM)
double opt_view_raise1 (OPT_ARGS_NUM)
double opt_view_raise2 (OPT_ARGS_NUM)
double opt_view_normal_raise (OPT_ARGS_NUM)
double opt_view_transform00 (OPT_ARGS_NUM)
double opt_view_transform01 (OPT_ARGS_NUM)
double opt_view_transform02 (OPT_ARGS_NUM)
double opt_view_transform10 (OPT_ARGS_NUM)
double opt_view_transform11 (OPT_ARGS_NUM)
double opt_view_transform12 (OPT_ARGS_NUM)
double opt_view_transform20 (OPT_ARGS_NUM)
double opt_view_transform21 (OPT_ARGS_NUM)
double opt_view_transform22 (OPT_ARGS_NUM)
double opt_view_arrow_size_min (OPT_ARGS_NUM)
double opt_view_arrow_size_max (OPT_ARGS_NUM)
double opt_view_normals (OPT_ARGS_NUM)
double opt_view_tangents (OPT_ARGS_NUM)
double opt_view_displacement_factor (OPT_ARGS_NUM)
double opt_view_fake_transparency (OPT_ARGS_NUM)
double opt_view_use_stipple (OPT_ARGS_NUM)
double opt_view_explode (OPT_ARGS_NUM)
double opt_view_visible (OPT_ARGS_NUM)
double opt_view_intervals_type (OPT_ARGS_NUM)
double opt_view_saturate_values (OPT_ARGS_NUM)
double opt_view_max_recursion_level (OPT_ARGS_NUM)
double opt_view_adapt_visualization_grid (OPT_ARGS_NUM)
double opt_view_target_error (OPT_ARGS_NUM)
double opt_view_colormap_alpha (OPT_ARGS_NUM)
double opt_view_colormap_alpha_power (OPT_ARGS_NUM)
double opt_view_colormap_beta (OPT_ARGS_NUM)
double opt_view_colormap_bias (OPT_ARGS_NUM)
double opt_view_colormap_curvature (OPT_ARGS_NUM)
double opt_view_colormap_invert (OPT_ARGS_NUM)
double opt_view_colormap_number (OPT_ARGS_NUM)
double opt_view_colormap_rotation (OPT_ARGS_NUM)
double opt_view_colormap_swap (OPT_ARGS_NUM)
double opt_view_external_view (OPT_ARGS_NUM)
double opt_view_gen_raise_view (OPT_ARGS_NUM)
double opt_view_gen_raise_factor (OPT_ARGS_NUM)
double opt_view_use_gen_raise (OPT_ARGS_NUM)
double opt_view_type (OPT_ARGS_NUM)
double opt_view_axes (OPT_ARGS_NUM)
double opt_view_axes_mikado (OPT_ARGS_NUM)
double opt_view_axes_auto_position (OPT_ARGS_NUM)
double opt_view_axes_tics0 (OPT_ARGS_NUM)
double opt_view_axes_tics1 (OPT_ARGS_NUM)
double opt_view_axes_tics2 (OPT_ARGS_NUM)
double opt_view_axes_xmin (OPT_ARGS_NUM)
double opt_view_axes_ymin (OPT_ARGS_NUM)
double opt_view_axes_zmin (OPT_ARGS_NUM)
double opt_view_axes_xmax (OPT_ARGS_NUM)
double opt_view_axes_ymax (OPT_ARGS_NUM)
double opt_view_axes_zmax (OPT_ARGS_NUM)
double opt_view_position0 (OPT_ARGS_NUM)
double opt_view_position1 (OPT_ARGS_NUM)
double opt_view_auto_position (OPT_ARGS_NUM)
double opt_view_sampling (OPT_ARGS_NUM)
double opt_view_size0 (OPT_ARGS_NUM)
double opt_view_size1 (OPT_ARGS_NUM)
double opt_view_nb_iso (OPT_ARGS_NUM)
double opt_view_boundary (OPT_ARGS_NUM)
double opt_view_light (OPT_ARGS_NUM)
double opt_view_light_two_side (OPT_ARGS_NUM)
double opt_view_light_lines (OPT_ARGS_NUM)
double opt_view_smooth_normals (OPT_ARGS_NUM)
double opt_view_angle_smooth_normals (OPT_ARGS_NUM)
double opt_view_show_element (OPT_ARGS_NUM)
double opt_view_show_time (OPT_ARGS_NUM)
double opt_view_show_scale (OPT_ARGS_NUM)
double opt_view_draw_strings (OPT_ARGS_NUM)
double opt_view_draw_points (OPT_ARGS_NUM)
double opt_view_draw_quadrangles (OPT_ARGS_NUM)
double opt_view_draw_lines (OPT_ARGS_NUM)
double opt_view_draw_triangles (OPT_ARGS_NUM)
double opt_view_draw_tetrahedra (OPT_ARGS_NUM)
double opt_view_draw_hexahedra (OPT_ARGS_NUM)
double opt_view_draw_prisms (OPT_ARGS_NUM)
double opt_view_draw_pyramids (OPT_ARGS_NUM)
double opt_view_draw_trihedra (OPT_ARGS_NUM)
double opt_view_draw_scalars (OPT_ARGS_NUM)
double opt_view_draw_vectors (OPT_ARGS_NUM)
double opt_view_draw_tensors (OPT_ARGS_NUM)
double opt_view_draw_skin_only (OPT_ARGS_NUM)
double opt_view_scale_type (OPT_ARGS_NUM)
double opt_view_tensor_type (OPT_ARGS_NUM)
double opt_view_range_type (OPT_ARGS_NUM)
double opt_view_abscissa_range_type (OPT_ARGS_NUM)
double opt_view_vector_type (OPT_ARGS_NUM)
double opt_view_glyph_location (OPT_ARGS_NUM)
double opt_view_center_glyphs (OPT_ARGS_NUM)
double opt_view_point_size (OPT_ARGS_NUM)
double opt_view_line_width (OPT_ARGS_NUM)
double opt_view_point_type (OPT_ARGS_NUM)
double opt_view_line_type (OPT_ARGS_NUM)
double opt_view_clip (OPT_ARGS_NUM)
double opt_view_force_num_components (OPT_ARGS_NUM)
double opt_view_component_map0 (OPT_ARGS_NUM)
double opt_view_component_map1 (OPT_ARGS_NUM)
double opt_view_component_map2 (OPT_ARGS_NUM)
double opt_view_component_map3 (OPT_ARGS_NUM)
double opt_view_component_map4 (OPT_ARGS_NUM)
double opt_view_component_map5 (OPT_ARGS_NUM)
double opt_view_component_map6 (OPT_ARGS_NUM)
double opt_view_component_map7 (OPT_ARGS_NUM)
double opt_view_component_map8 (OPT_ARGS_NUM)
double opt_view_closed (OPT_ARGS_NUM)
double opt_print_file_format (OPT_ARGS_NUM)
double opt_print_eps_compress (OPT_ARGS_NUM)
double opt_print_eps_ps3shading (OPT_ARGS_NUM)
double opt_print_eps_quality (OPT_ARGS_NUM)
double opt_print_eps_occlusion_culling (OPT_ARGS_NUM)
double opt_print_eps_best_root (OPT_ARGS_NUM)
double opt_print_eps_line_width_factor (OPT_ARGS_NUM)
double opt_print_eps_point_size_factor (OPT_ARGS_NUM)
double opt_print_jpeg_quality (OPT_ARGS_NUM)
double opt_print_jpeg_smoothing (OPT_ARGS_NUM)
double opt_print_geo_labels (OPT_ARGS_NUM)
double opt_print_geo_only_physicals (OPT_ARGS_NUM)
double opt_print_pos_elementary (OPT_ARGS_NUM)
double opt_print_pos_element (OPT_ARGS_NUM)
double opt_print_pos_gamma (OPT_ARGS_NUM)
double opt_print_pos_eta (OPT_ARGS_NUM)
double opt_print_pos_SICN (OPT_ARGS_NUM)
double opt_print_pos_SIGE (OPT_ARGS_NUM)
double opt_print_pos_disto (OPT_ARGS_NUM)
double opt_print_gif_dither (OPT_ARGS_NUM)
double opt_print_gif_sort (OPT_ARGS_NUM)
double opt_print_gif_interlace (OPT_ARGS_NUM)
double opt_print_gif_transparent (OPT_ARGS_NUM)
double opt_print_background (OPT_ARGS_NUM)
double opt_print_pgf_two_dim (OPT_ARGS_NUM)
double opt_print_pgf_export_axis (OPT_ARGS_NUM)
double opt_print_pgf_horiz_bar (OPT_ARGS_NUM)
double opt_print_text (OPT_ARGS_NUM)
double opt_print_tex_as_equation (OPT_ARGS_NUM)
double opt_print_tex_force_fontsize (OPT_ARGS_NUM)
double opt_print_tex_width_in_mm (OPT_ARGS_NUM)
double opt_print_composite_windows (OPT_ARGS_NUM)
double opt_print_delete_tmp_files (OPT_ARGS_NUM)
double opt_print_height (OPT_ARGS_NUM)
double opt_print_width (OPT_ARGS_NUM)
double opt_print_parameter (OPT_ARGS_NUM)
double opt_print_parameter_first (OPT_ARGS_NUM)
double opt_print_parameter_last (OPT_ARGS_NUM)
double opt_print_parameter_steps (OPT_ARGS_NUM)
double opt_print_x3d_compatibility (OPT_ARGS_NUM)
double opt_print_x3d_transparency (OPT_ARGS_NUM)
double opt_print_x3d_remove_inner_borders (OPT_ARGS_NUM)
double opt_print_x3d_precision (OPT_ARGS_NUM)
double opt_print_x3d_surfaces (OPT_ARGS_NUM)
double opt_print_x3d_edges (OPT_ARGS_NUM)
double opt_print_x3d_vertices (OPT_ARGS_NUM)
double opt_print_x3d_volumes (OPT_ARGS_NUM)
double opt_print_x3d_colorize (OPT_ARGS_NUM)
unsigned int opt_general_color_background (OPT_ARGS_COL)
unsigned int opt_general_color_background_gradient (OPT_ARGS_COL)
unsigned int opt_general_color_foreground (OPT_ARGS_COL)
unsigned int opt_general_color_text (OPT_ARGS_COL)
unsigned int opt_general_color_axes (OPT_ARGS_COL)
unsigned int opt_general_color_small_axes (OPT_ARGS_COL)
unsigned int opt_general_color_ambient_light (OPT_ARGS_COL)
unsigned int opt_general_color_diffuse_light (OPT_ARGS_COL)
unsigned int opt_general_color_specular_light (OPT_ARGS_COL)
unsigned int opt_geometry_color_points (OPT_ARGS_COL)
unsigned int opt_geometry_color_curves (OPT_ARGS_COL)
unsigned int opt_geometry_color_surfaces (OPT_ARGS_COL)
unsigned int opt_geometry_color_volumes (OPT_ARGS_COL)
unsigned int opt_geometry_color_selection (OPT_ARGS_COL)
unsigned int opt_geometry_color_highlight0 (OPT_ARGS_COL)
unsigned int opt_geometry_color_highlight1 (OPT_ARGS_COL)
unsigned int opt_geometry_color_highlight2 (OPT_ARGS_COL)
unsigned int opt_geometry_color_tangents (OPT_ARGS_COL)
unsigned int opt_geometry_color_normals (OPT_ARGS_COL)
unsigned int opt_geometry_color_projection (OPT_ARGS_COL)
unsigned int opt_mesh_color_nodes (OPT_ARGS_COL)
unsigned int opt_mesh_color_nodes_sup (OPT_ARGS_COL)
unsigned int opt_mesh_color_lines (OPT_ARGS_COL)
unsigned int opt_mesh_color_triangles (OPT_ARGS_COL)
unsigned int opt_mesh_color_quadrangles (OPT_ARGS_COL)
unsigned int opt_mesh_color_tetrahedra (OPT_ARGS_COL)
unsigned int opt_mesh_color_hexahedra (OPT_ARGS_COL)
unsigned int opt_mesh_color_prisms (OPT_ARGS_COL)
unsigned int opt_mesh_color_pyramid (OPT_ARGS_COL)
unsigned int opt_mesh_color_trihedron (OPT_ARGS_COL)
unsigned int opt_mesh_color_tangents (OPT_ARGS_COL)
unsigned int opt_mesh_color_normals (OPT_ARGS_COL)
unsigned int opt_mesh_color_0 (OPT_ARGS_COL)
unsigned int opt_mesh_color_1 (OPT_ARGS_COL)
unsigned int opt_mesh_color_2 (OPT_ARGS_COL)
unsigned int opt_mesh_color_3 (OPT_ARGS_COL)
unsigned int opt_mesh_color_4 (OPT_ARGS_COL)
unsigned int opt_mesh_color_5 (OPT_ARGS_COL)
unsigned int opt_mesh_color_6 (OPT_ARGS_COL)
unsigned int opt_mesh_color_7 (OPT_ARGS_COL)
unsigned int opt_mesh_color_8 (OPT_ARGS_COL)
unsigned int opt_mesh_color_9 (OPT_ARGS_COL)
unsigned int opt_mesh_color_10 (OPT_ARGS_COL)
unsigned int opt_mesh_color_11 (OPT_ARGS_COL)
unsigned int opt_mesh_color_12 (OPT_ARGS_COL)
unsigned int opt_mesh_color_13 (OPT_ARGS_COL)
unsigned int opt_mesh_color_14 (OPT_ARGS_COL)
unsigned int opt_mesh_color_15 (OPT_ARGS_COL)
unsigned int opt_mesh_color_16 (OPT_ARGS_COL)
unsigned int opt_mesh_color_17 (OPT_ARGS_COL)
unsigned int opt_mesh_color_18 (OPT_ARGS_COL)
unsigned int opt_mesh_color_19 (OPT_ARGS_COL)
unsigned int opt_view_color_points (OPT_ARGS_COL)
unsigned int opt_view_color_lines (OPT_ARGS_COL)
unsigned int opt_view_color_triangles (OPT_ARGS_COL)
unsigned int opt_view_color_quadrangles (OPT_ARGS_COL)
unsigned int opt_view_color_tetrahedra (OPT_ARGS_COL)
unsigned int opt_view_color_hexahedra (OPT_ARGS_COL)
unsigned int opt_view_color_prisms (OPT_ARGS_COL)
unsigned int opt_view_color_pyramids (OPT_ARGS_COL)
unsigned int opt_view_color_trihedra (OPT_ARGS_COL)
unsigned int opt_view_color_tangents (OPT_ARGS_COL)
unsigned int opt_view_color_normals (OPT_ARGS_COL)
unsigned int opt_view_color_text2d (OPT_ARGS_COL)
unsigned int opt_view_color_text3d (OPT_ARGS_COL)
unsigned int opt_view_color_axes (OPT_ARGS_COL)
unsigned int opt_view_color_background2d (OPT_ARGS_COL)
void InitOptions (int num)
void InitOptionsGUI (int num)
void ReInitOptions (int num)
void PrintOptions (int num, int level, int diff, int help, const char *filename, std::vector< std::string > *vec=nullptr)
void PrintOptionsDoc ()
bool StringOption (int action, const char *category, int num, const char *name, std::string &val, bool warnIfUnknown=true)
bool NumberOption (int action, const char *category, int num, const char *name, double &val, bool warnIfUnknown=true)
bool ColorOption (int action, const char *category, int num, const char *name, unsigned int &val, bool warnIfUnknown=true)
GmshColorTable * GetColorTable (int num)
int GetColorForString (int alpha, const char *string, int *FlagError)
bool GetRGBForString (const char *string, int &r, int &g, int &b)
Macro Definition Documentation
GMSH_DEPRECATED
#define GMSH_DEPRECATED (1 << 3)
Definition at line 22 of file Options.h.
GMSH_FULLRC
#define GMSH_FULLRC (1 << 2)
Definition at line 21 of file Options.h.
GMSH_GET
#define GMSH_GET (1 << 1)
Definition at line 14 of file Options.h.
GMSH_GET_DEFAULT
#define GMSH_GET_DEFAULT (1 << 4)
Definition at line 17 of file Options.h.
GMSH_GUI
#define GMSH_GUI (1 << 2)
Definition at line 15 of file Options.h.
GMSH_OPTIONSRC
#define GMSH_OPTIONSRC (1 << 1)
Definition at line 20 of file Options.h.
GMSH_SESSIONRC
#define GMSH_SESSIONRC (1 << 0)
Definition at line 19 of file Options.h.
GMSH_SET
#define GMSH_SET (1 << 0)
Definition at line 13 of file Options.h.
GMSH_SET_DEFAULT
#define GMSH_SET_DEFAULT (1 << 3)
Definition at line 16 of file Options.h.
OPT_ARGS_COL
#define OPT_ARGS_COL int num, int action, unsigned int val
Definition at line 28 of file Options.h.
OPT_ARGS_NUM
#define OPT_ARGS_NUM int num, int action, double val
Definition at line 27 of file Options.h.
OPT_ARGS_STR
#define OPT_ARGS_STR int num, int action, const std::string &val
Definition at line 26 of file Options.h.
Function Documentation
ColorOption()
bool ColorOption (int action, const char * category, int num, const char * name, unsigned int & val, bool warnIfUnknown = true)
Definition at line 287 of file Options.cpp.
Referenced by GmshGetColorOption(), GmshGetOption(), GmshSetColorOption(), and GmshSetOption().
GetColorForString()
int GetColorForString (int alpha, const char * string, int * FlagError)
Definition at line 331 of file Options.cpp.
GetColorTable()
GmshColorTable* GetColorTable (int num)
Definition at line 566 of file Options.cpp.
Referenced by assembleColmapStr().
GetRGBForString()
bool GetRGBForString (const char * string, int & r, int & g, int & b)
Definition at line 344 of file Options.cpp.
InitOptions()
void InitOptions (int num)
Definition at line 472 of file Options.cpp.
Referenced by GmshInitialize(), GmshMainFLTK(), and ReInitOptions().
InitOptionsGUI()
void InitOptionsGUI (int num)
Definition at line 521 of file Options.cpp.
Referenced by GmshRestoreDefaultOptions().
NumberOption()
bool NumberOption (int action, const char * category, int num, const char * name, double & val, bool warnIfUnknown = true)
Definition at line 185 of file Options.cpp.
Referenced by GmshGetNumberOption(), GmshGetOption(), GmshSetNumberOption(), GmshSetOption(), and treat_Struct_FullName_dot_tSTRING_Float().
opt_general_abort_on_error()
double opt_general_abort_on_error (OPT_ARGS_NUM)
Definition at line 2157 of file Options.cpp.
opt_general_alpha_blending()
double opt_general_alpha_blending (OPT_ARGS_NUM)
Definition at line 3367 of file Options.cpp.
opt_general_antialiasing()
double opt_general_antialiasing (OPT_ARGS_NUM)
Definition at line 3344 of file Options.cpp.
opt_general_arrow_head_radius()
double opt_general_arrow_head_radius (OPT_ARGS_NUM)
Definition at line 3389 of file Options.cpp.
opt_general_arrow_stem_length()
double opt_general_arrow_stem_length (OPT_ARGS_NUM)
Definition at line 3399 of file Options.cpp.
opt_general_arrow_stem_radius()
double opt_general_arrow_stem_radius (OPT_ARGS_NUM)
Definition at line 3409 of file Options.cpp.
opt_general_axes()
double opt_general_axes (OPT_ARGS_NUM)
Definition at line 3087 of file Options.cpp.
Referenced by CreateOutputFile().
opt_general_axes_auto_position()
double opt_general_axes_auto_position (OPT_ARGS_NUM)
Definition at line 3114 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_general_axes_force_value()
double opt_general_axes_force_value (OPT_ARGS_NUM)
Definition at line 3226 of file Options.cpp.
opt_general_axes_format0()
std::string opt_general_axes_format0 (OPT_ARGS_STR)
Definition at line 1114 of file Options.cpp.
opt_general_axes_format1()
std::string opt_general_axes_format1 (OPT_ARGS_STR)
Definition at line 1125 of file Options.cpp.
opt_general_axes_format2()
std::string opt_general_axes_format2 (OPT_ARGS_STR)
Definition at line 1136 of file Options.cpp.
opt_general_axes_label0()
std::string opt_general_axes_label0 (OPT_ARGS_STR)
Definition at line 1081 of file Options.cpp.
opt_general_axes_label1()
std::string opt_general_axes_label1 (OPT_ARGS_STR)
Definition at line 1092 of file Options.cpp.
opt_general_axes_label2()
std::string opt_general_axes_label2 (OPT_ARGS_STR)
Definition at line 1103 of file Options.cpp.
opt_general_axes_mikado()
double opt_general_axes_mikado (OPT_ARGS_NUM)
Definition at line 3103 of file Options.cpp.
opt_general_axes_tics0()
double opt_general_axes_tics0 (OPT_ARGS_NUM)
Definition at line 3127 of file Options.cpp.
opt_general_axes_tics1()
double opt_general_axes_tics1 (OPT_ARGS_NUM)
Definition at line 3138 of file Options.cpp.
opt_general_axes_tics2()
double opt_general_axes_tics2 (OPT_ARGS_NUM)
Definition at line 3149 of file Options.cpp.
opt_general_axes_value_xmax()
double opt_general_axes_value_xmax (OPT_ARGS_NUM)
Definition at line 3238 of file Options.cpp.
opt_general_axes_value_xmin()
double opt_general_axes_value_xmin (OPT_ARGS_NUM)
Definition at line 3232 of file Options.cpp.
opt_general_axes_value_ymax()
double opt_general_axes_value_ymax (OPT_ARGS_NUM)
Definition at line 3250 of file Options.cpp.
opt_general_axes_value_ymin()
double opt_general_axes_value_ymin (OPT_ARGS_NUM)
Definition at line 3244 of file Options.cpp.
opt_general_axes_value_zmax()
double opt_general_axes_value_zmax (OPT_ARGS_NUM)
Definition at line 3262 of file Options.cpp.
opt_general_axes_value_zmin()
double opt_general_axes_value_zmin (OPT_ARGS_NUM)
Definition at line 3256 of file Options.cpp.
opt_general_axes_xmax()
double opt_general_axes_xmax (OPT_ARGS_NUM)
Definition at line 3171 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_general_axes_xmin()
double opt_general_axes_xmin (OPT_ARGS_NUM)
Definition at line 3160 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_general_axes_ymax()
double opt_general_axes_ymax (OPT_ARGS_NUM)
Definition at line 3193 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_general_axes_ymin()
double opt_general_axes_ymin (OPT_ARGS_NUM)
Definition at line 3182 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_general_axes_zmax()
double opt_general_axes_zmax (OPT_ARGS_NUM)
Definition at line 3215 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_general_axes_zmin()
double opt_general_axes_zmin (OPT_ARGS_NUM)
Definition at line 3204 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_general_background_gradient()
double opt_general_background_gradient (OPT_ARGS_NUM)
Definition at line 3462 of file Options.cpp.
opt_general_background_image_3d()
double opt_general_background_image_3d (OPT_ARGS_NUM)
Definition at line 3501 of file Options.cpp.
opt_general_background_image_filename()
std::string opt_general_background_image_filename (OPT_ARGS_STR)
Definition at line 1153 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_background_image_page()
double opt_general_background_image_page (OPT_ARGS_NUM)
Definition at line 3507 of file Options.cpp.
opt_general_background_image_position0()
double opt_general_background_image_position0 (OPT_ARGS_NUM)
Definition at line 3477 of file Options.cpp.
opt_general_background_image_position1()
double opt_general_background_image_position1 (OPT_ARGS_NUM)
Definition at line 3483 of file Options.cpp.
opt_general_background_image_size0()
double opt_general_background_image_size0 (OPT_ARGS_NUM)
Definition at line 3489 of file Options.cpp.
opt_general_background_image_size1()
double opt_general_background_image_size1 (OPT_ARGS_NUM)
Definition at line 3495 of file Options.cpp.
opt_general_build_info()
std::string opt_general_build_info (OPT_ARGS_STR)
Definition at line 1181 of file Options.cpp.
opt_general_build_options()
std::string opt_general_build_options (OPT_ARGS_STR)
Definition at line 1174 of file Options.cpp.
opt_general_camera_aperture()
double opt_general_camera_aperture (OPT_ARGS_NUM)
Definition at line 3630 of file Options.cpp.
opt_general_camera_mode()
double opt_general_camera_mode (OPT_ARGS_NUM)
Definition at line 3641 of file Options.cpp.
Referenced by GetOtherOption(), opt_general_gamepad(), and opt_general_stereo_mode().
opt_general_clip0a()
double opt_general_clip0a (OPT_ARGS_NUM)
Definition at line 3654 of file Options.cpp.
opt_general_clip0b()
double opt_general_clip0b (OPT_ARGS_NUM)
Definition at line 3664 of file Options.cpp.
opt_general_clip0c()
double opt_general_clip0c (OPT_ARGS_NUM)
Definition at line 3674 of file Options.cpp.
opt_general_clip0d()
double opt_general_clip0d (OPT_ARGS_NUM)
Definition at line 3684 of file Options.cpp.
opt_general_clip1a()
double opt_general_clip1a (OPT_ARGS_NUM)
Definition at line 3694 of file Options.cpp.
opt_general_clip1b()
double opt_general_clip1b (OPT_ARGS_NUM)
Definition at line 3704 of file Options.cpp.
opt_general_clip1c()
double opt_general_clip1c (OPT_ARGS_NUM)
Definition at line 3714 of file Options.cpp.
opt_general_clip1d()
double opt_general_clip1d (OPT_ARGS_NUM)
Definition at line 3724 of file Options.cpp.
opt_general_clip2a()
double opt_general_clip2a (OPT_ARGS_NUM)
Definition at line 3734 of file Options.cpp.
opt_general_clip2b()
double opt_general_clip2b (OPT_ARGS_NUM)
Definition at line 3744 of file Options.cpp.
opt_general_clip2c()
double opt_general_clip2c (OPT_ARGS_NUM)
Definition at line 3754 of file Options.cpp.
opt_general_clip2d()
double opt_general_clip2d (OPT_ARGS_NUM)
Definition at line 3764 of file Options.cpp.
opt_general_clip3a()
double opt_general_clip3a (OPT_ARGS_NUM)
Definition at line 3774 of file Options.cpp.
opt_general_clip3b()
double opt_general_clip3b (OPT_ARGS_NUM)
Definition at line 3784 of file Options.cpp.
opt_general_clip3c()
double opt_general_clip3c (OPT_ARGS_NUM)
Definition at line 3794 of file Options.cpp.
opt_general_clip3d()
double opt_general_clip3d (OPT_ARGS_NUM)
Definition at line 3804 of file Options.cpp.
opt_general_clip4a()
double opt_general_clip4a (OPT_ARGS_NUM)
Definition at line 3814 of file Options.cpp.
opt_general_clip4b()
double opt_general_clip4b (OPT_ARGS_NUM)
Definition at line 3824 of file Options.cpp.
opt_general_clip4c()
double opt_general_clip4c (OPT_ARGS_NUM)
Definition at line 3834 of file Options.cpp.
opt_general_clip4d()
double opt_general_clip4d (OPT_ARGS_NUM)
Definition at line 3844 of file Options.cpp.
opt_general_clip5a()
double opt_general_clip5a (OPT_ARGS_NUM)
Definition at line 3854 of file Options.cpp.
opt_general_clip5b()
double opt_general_clip5b (OPT_ARGS_NUM)
Definition at line 3864 of file Options.cpp.
opt_general_clip5c()
double opt_general_clip5c (OPT_ARGS_NUM)
Definition at line 3874 of file Options.cpp.
opt_general_clip5d()
double opt_general_clip5d (OPT_ARGS_NUM)
Definition at line 3884 of file Options.cpp.
opt_general_clip_factor()
double opt_general_clip_factor (OPT_ARGS_NUM)
Definition at line 2826 of file Options.cpp.
opt_general_clip_only_draw_intersecting_volume()
double opt_general_clip_only_draw_intersecting_volume (OPT_ARGS_NUM)
Definition at line 3907 of file Options.cpp.
opt_general_clip_only_volume()
double opt_general_clip_only_volume (OPT_ARGS_NUM)
Definition at line 3919 of file Options.cpp.
opt_general_clip_position0()
double opt_general_clip_position0 (OPT_ARGS_NUM)
Definition at line 2539 of file Options.cpp.
opt_general_clip_position1()
double opt_general_clip_position1 (OPT_ARGS_NUM)
Definition at line 2545 of file Options.cpp.
opt_general_clip_whole_elements()
double opt_general_clip_whole_elements (OPT_ARGS_NUM)
Definition at line 3894 of file Options.cpp.
opt_general_color_ambient_light()
unsigned int opt_general_color_ambient_light (OPT_ARGS_COL)
Definition at line 9552 of file Options.cpp.
opt_general_color_axes()
unsigned int opt_general_color_axes (OPT_ARGS_COL)
Definition at line 9530 of file Options.cpp.
opt_general_color_background()
unsigned int opt_general_color_background (OPT_ARGS_COL)
Definition at line 9486 of file Options.cpp.
opt_general_color_background_gradient()
unsigned int opt_general_color_background_gradient (OPT_ARGS_COL)
Definition at line 9500 of file Options.cpp.
opt_general_color_diffuse_light()
unsigned int opt_general_color_diffuse_light (OPT_ARGS_COL)
Definition at line 9563 of file Options.cpp.
opt_general_color_foreground()
unsigned int opt_general_color_foreground (OPT_ARGS_COL)
Definition at line 9510 of file Options.cpp.
opt_general_color_scheme()
double opt_general_color_scheme (OPT_ARGS_NUM)
Definition at line 3419 of file Options.cpp.
opt_general_color_small_axes()
unsigned int opt_general_color_small_axes (OPT_ARGS_COL)
Definition at line 9541 of file Options.cpp.
opt_general_color_specular_light()
unsigned int opt_general_color_specular_light (OPT_ARGS_COL)
Definition at line 9574 of file Options.cpp.
opt_general_color_text()
unsigned int opt_general_color_text (OPT_ARGS_COL)
Definition at line 9519 of file Options.cpp.
opt_general_confirm_overwrite()
double opt_general_confirm_overwrite (OPT_ARGS_NUM)
Definition at line 2603 of file Options.cpp.
opt_general_context_position0()
double opt_general_context_position0 (OPT_ARGS_NUM)
Definition at line 2303 of file Options.cpp.
opt_general_context_position1()
double opt_general_context_position1 (OPT_ARGS_NUM)
Definition at line 2309 of file Options.cpp.
opt_general_default_filename()
std::string opt_general_default_filename (OPT_ARGS_STR)
Definition at line 1206 of file Options.cpp.
opt_general_detached_menu()
double opt_general_detached_menu (OPT_ARGS_NUM)
Definition at line 2368 of file Options.cpp.
opt_general_detached_process()
double opt_general_detached_process (OPT_ARGS_NUM)
Definition at line 2382 of file Options.cpp.
opt_general_display()
std::string opt_general_display (OPT_ARGS_STR)
Definition at line 1147 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_display_border_factor()
double opt_general_display_border_factor (OPT_ARGS_NUM)
Definition at line 2843 of file Options.cpp.
opt_general_double_buffer()
double opt_general_double_buffer (OPT_ARGS_NUM)
Definition at line 3322 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_draw_bounding_box()
double opt_general_draw_bounding_box (OPT_ARGS_NUM)
Definition at line 3038 of file Options.cpp.
opt_general_draw_oriented_bounding_box()
double opt_general_draw_oriented_bounding_box (OPT_ARGS_NUM)
opt_general_editor()
std::string opt_general_editor (OPT_ARGS_STR)
Definition at line 1313 of file Options.cpp.
opt_general_error_filename()
std::string opt_general_error_filename (OPT_ARGS_STR)
Definition at line 1223 of file Options.cpp.
opt_general_executable_filename()
std::string opt_general_executable_filename (OPT_ARGS_STR)
Definition at line 1201 of file Options.cpp.
opt_general_expert_mode()
double opt_general_expert_mode (OPT_ARGS_NUM)
Definition at line 3569 of file Options.cpp.
opt_general_extra_position0()
double opt_general_extra_position0 (OPT_ARGS_NUM)
Definition at line 2491 of file Options.cpp.
opt_general_extra_position1()
double opt_general_extra_position1 (OPT_ARGS_NUM)
Definition at line 2497 of file Options.cpp.
opt_general_extra_size0()
double opt_general_extra_size0 (OPT_ARGS_NUM)
Definition at line 2503 of file Options.cpp.
opt_general_extra_size1()
double opt_general_extra_size1 (OPT_ARGS_NUM)
Definition at line 2509 of file Options.cpp.
opt_general_eye_sep_ratio()
double opt_general_eye_sep_ratio (OPT_ARGS_NUM)
Definition at line 3608 of file Options.cpp.
opt_general_fast_redraw()
double opt_general_fast_redraw (OPT_ARGS_NUM)
Definition at line 3025 of file Options.cpp.
opt_general_field_position0()
double opt_general_field_position0 (OPT_ARGS_NUM)
Definition at line 2467 of file Options.cpp.
opt_general_field_position1()
double opt_general_field_position1 (OPT_ARGS_NUM)
Definition at line 2473 of file Options.cpp.
opt_general_field_size0()
double opt_general_field_size0 (OPT_ARGS_NUM)
Definition at line 2479 of file Options.cpp.
opt_general_field_size1()
double opt_general_field_size1 (OPT_ARGS_NUM)
Definition at line 2485 of file Options.cpp.
opt_general_file_chooser_position0()
double opt_general_file_chooser_position0 (OPT_ARGS_NUM)
Definition at line 2315 of file Options.cpp.
opt_general_file_chooser_position1()
double opt_general_file_chooser_position1 (OPT_ARGS_NUM)
Definition at line 2321 of file Options.cpp.
opt_general_filename()
std::string opt_general_filename (OPT_ARGS_STR)
Definition at line 1196 of file Options.cpp.
opt_general_focallength_ratio()
double opt_general_focallength_ratio (OPT_ARGS_NUM)
Definition at line 3619 of file Options.cpp.
opt_general_fontsize()
double opt_general_fontsize (OPT_ARGS_NUM)
Definition at line 2181 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_gamepad()
double opt_general_gamepad (OPT_ARGS_NUM)
Definition at line 3530 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_graphics_font()
std::string opt_general_graphics_font (OPT_ARGS_STR)
Definition at line 1336 of file Options.cpp.
opt_general_graphics_font_engine()
std::string opt_general_graphics_font_engine (OPT_ARGS_STR)
Definition at line 1370 of file Options.cpp.
opt_general_graphics_font_title()
std::string opt_general_graphics_font_title (OPT_ARGS_STR)
Definition at line 1353 of file Options.cpp.
opt_general_graphics_fontsize()
double opt_general_graphics_fontsize (OPT_ARGS_NUM)
Definition at line 2208 of file Options.cpp.
opt_general_graphics_fontsize_title()
double opt_general_graphics_fontsize_title (OPT_ARGS_NUM)
Definition at line 2219 of file Options.cpp.
opt_general_graphics_position0()
double opt_general_graphics_position0 (OPT_ARGS_NUM)
Definition at line 2263 of file Options.cpp.
opt_general_graphics_position1()
double opt_general_graphics_position1 (OPT_ARGS_NUM)
Definition at line 2269 of file Options.cpp.
opt_general_graphics_size0()
double opt_general_graphics_size0 (OPT_ARGS_NUM)
Definition at line 2275 of file Options.cpp.
opt_general_graphics_size1()
double opt_general_graphics_size1 (OPT_ARGS_NUM)
Definition at line 2289 of file Options.cpp.
opt_general_gui_color_scheme()
double opt_general_gui_color_scheme (OPT_ARGS_NUM)
Definition at line 2187 of file Options.cpp.
opt_general_gui_refresh_rate()
double opt_general_gui_refresh_rate (OPT_ARGS_NUM)
Definition at line 2202 of file Options.cpp.
opt_general_gui_theme()
std::string opt_general_gui_theme (OPT_ARGS_STR)
Definition at line 1330 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_high_resolution_graphics()
double opt_general_high_resolution_graphics (OPT_ARGS_NUM)
Definition at line 2575 of file Options.cpp.
opt_general_hot_position0()
double opt_general_hot_position0 (OPT_ARGS_NUM)
Definition at line 2563 of file Options.cpp.
opt_general_hot_position1()
double opt_general_hot_position1 (OPT_ARGS_NUM)
Definition at line 2569 of file Options.cpp.
opt_general_initial_context()
double opt_general_initial_context (OPT_ARGS_NUM)
Definition at line 2163 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_input_scrolling()
double opt_general_input_scrolling (OPT_ARGS_NUM)
Definition at line 2956 of file Options.cpp.
opt_general_lc()
double opt_general_lc (OPT_ARGS_NUM)
Definition at line 3085 of file Options.cpp.
opt_general_light0()
double opt_general_light0 (OPT_ARGS_NUM)
Definition at line 3930 of file Options.cpp.
opt_general_light00()
double opt_general_light00 (OPT_ARGS_NUM)
Definition at line 3936 of file Options.cpp.
opt_general_light01()
double opt_general_light01 (OPT_ARGS_NUM)
Definition at line 3952 of file Options.cpp.
opt_general_light02()
double opt_general_light02 (OPT_ARGS_NUM)
Definition at line 3968 of file Options.cpp.
opt_general_light03()
double opt_general_light03 (OPT_ARGS_NUM)
Definition at line 3984 of file Options.cpp.
opt_general_light1()
double opt_general_light1 (OPT_ARGS_NUM)
Definition at line 3995 of file Options.cpp.
opt_general_light10()
double opt_general_light10 (OPT_ARGS_NUM)
Definition at line 4001 of file Options.cpp.
opt_general_light11()
double opt_general_light11 (OPT_ARGS_NUM)
Definition at line 4007 of file Options.cpp.
opt_general_light12()
double opt_general_light12 (OPT_ARGS_NUM)
Definition at line 4013 of file Options.cpp.
opt_general_light13()
double opt_general_light13 (OPT_ARGS_NUM)
Definition at line 4019 of file Options.cpp.
opt_general_light2()
double opt_general_light2 (OPT_ARGS_NUM)
Definition at line 4025 of file Options.cpp.
opt_general_light20()
double opt_general_light20 (OPT_ARGS_NUM)
Definition at line 4031 of file Options.cpp.
opt_general_light21()
double opt_general_light21 (OPT_ARGS_NUM)
Definition at line 4037 of file Options.cpp.
opt_general_light22()
double opt_general_light22 (OPT_ARGS_NUM)
Definition at line 4043 of file Options.cpp.
opt_general_light23()
double opt_general_light23 (OPT_ARGS_NUM)
Definition at line 4049 of file Options.cpp.
opt_general_light3()
double opt_general_light3 (OPT_ARGS_NUM)
Definition at line 4055 of file Options.cpp.
opt_general_light30()
double opt_general_light30 (OPT_ARGS_NUM)
Definition at line 4061 of file Options.cpp.
opt_general_light31()
double opt_general_light31 (OPT_ARGS_NUM)
Definition at line 4067 of file Options.cpp.
opt_general_light32()
double opt_general_light32 (OPT_ARGS_NUM)
Definition at line 4073 of file Options.cpp.
opt_general_light33()
double opt_general_light33 (OPT_ARGS_NUM)
Definition at line 4079 of file Options.cpp.
opt_general_light4()
double opt_general_light4 (OPT_ARGS_NUM)
Definition at line 4085 of file Options.cpp.
opt_general_light40()
double opt_general_light40 (OPT_ARGS_NUM)
Definition at line 4091 of file Options.cpp.
opt_general_light41()
double opt_general_light41 (OPT_ARGS_NUM)
Definition at line 4097 of file Options.cpp.
opt_general_light42()
double opt_general_light42 (OPT_ARGS_NUM)
Definition at line 4103 of file Options.cpp.
opt_general_light43()
double opt_general_light43 (OPT_ARGS_NUM)
Definition at line 4109 of file Options.cpp.
opt_general_light5()
double opt_general_light5 (OPT_ARGS_NUM)
Definition at line 4115 of file Options.cpp.
opt_general_light50()
double opt_general_light50 (OPT_ARGS_NUM)
Definition at line 4121 of file Options.cpp.
opt_general_light51()
double opt_general_light51 (OPT_ARGS_NUM)
Definition at line 4127 of file Options.cpp.
opt_general_light52()
double opt_general_light52 (OPT_ARGS_NUM)
Definition at line 4133 of file Options.cpp.
opt_general_light53()
double opt_general_light53 (OPT_ARGS_NUM)
Definition at line 4139 of file Options.cpp.
opt_general_line_width()
double opt_general_line_width (OPT_ARGS_NUM)
Definition at line 2866 of file Options.cpp.
opt_general_manip_position0()
double opt_general_manip_position0 (OPT_ARGS_NUM)
Definition at line 2551 of file Options.cpp.
opt_general_manip_position1()
double opt_general_manip_position1 (OPT_ARGS_NUM)
Definition at line 2557 of file Options.cpp.
opt_general_menu_position0()
double opt_general_menu_position0 (OPT_ARGS_NUM)
Definition at line 2411 of file Options.cpp.
opt_general_menu_position1()
double opt_general_menu_position1 (OPT_ARGS_NUM)
Definition at line 2421 of file Options.cpp.
opt_general_menu_size0()
double opt_general_menu_size0 (OPT_ARGS_NUM)
Definition at line 2388 of file Options.cpp.
opt_general_menu_size1()
double opt_general_menu_size1 (OPT_ARGS_NUM)
Definition at line 2402 of file Options.cpp.
opt_general_message_fontsize()
double opt_general_message_fontsize (OPT_ARGS_NUM)
Definition at line 2354 of file Options.cpp.
opt_general_message_size()
double opt_general_message_size (OPT_ARGS_NUM)
Definition at line 2345 of file Options.cpp.
opt_general_mouse_hover_meshes()
double opt_general_mouse_hover_meshes (OPT_ARGS_NUM)
Definition at line 3003 of file Options.cpp.
opt_general_mouse_invert_zoom()
double opt_general_mouse_invert_zoom (OPT_ARGS_NUM)
Definition at line 3014 of file Options.cpp.
opt_general_mouse_selection()
double opt_general_mouse_selection (OPT_ARGS_NUM)
Definition at line 2980 of file Options.cpp.
opt_general_native_file_chooser()
double opt_general_native_file_chooser (OPT_ARGS_NUM)
Definition at line 2333 of file Options.cpp.
opt_general_non_modal_windows()
double opt_general_non_modal_windows (OPT_ARGS_NUM)
Definition at line 2920 of file Options.cpp.
opt_general_nopopup()
double opt_general_nopopup (OPT_ARGS_NUM)
Definition at line 2914 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_num_threads()
double opt_general_num_threads (OPT_ARGS_NUM)
Definition at line 4145 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_option_position0()
double opt_general_option_position0 (OPT_ARGS_NUM)
Definition at line 2431 of file Options.cpp.
opt_general_option_position1()
double opt_general_option_position1 (OPT_ARGS_NUM)
Definition at line 2437 of file Options.cpp.
opt_general_options_filename()
std::string opt_general_options_filename (OPT_ARGS_STR)
Definition at line 1235 of file Options.cpp.
opt_general_options_save()
double opt_general_options_save (OPT_ARGS_NUM)
Definition at line 2592 of file Options.cpp.
opt_general_orthographic()
double opt_general_orthographic (OPT_ARGS_NUM)
Definition at line 2962 of file Options.cpp.
Referenced by assemble3d().
opt_general_plugin_position0()
double opt_general_plugin_position0 (OPT_ARGS_NUM)
Definition at line 2443 of file Options.cpp.
opt_general_plugin_position1()
double opt_general_plugin_position1 (OPT_ARGS_NUM)
Definition at line 2449 of file Options.cpp.
opt_general_plugin_size0()
double opt_general_plugin_size0 (OPT_ARGS_NUM)
Definition at line 2455 of file Options.cpp.
opt_general_plugin_size1()
double opt_general_plugin_size1 (OPT_ARGS_NUM)
Definition at line 2461 of file Options.cpp.
opt_general_point_size()
double opt_general_point_size (OPT_ARGS_NUM)
Definition at line 2855 of file Options.cpp.
opt_general_polygon_offset_always()
double opt_general_polygon_offset_always (OPT_ARGS_NUM)
Definition at line 2230 of file Options.cpp.
opt_general_polygon_offset_factor()
double opt_general_polygon_offset_factor (OPT_ARGS_NUM)
Definition at line 2241 of file Options.cpp.
opt_general_polygon_offset_units()
double opt_general_polygon_offset_units (OPT_ARGS_NUM)
Definition at line 2252 of file Options.cpp.
opt_general_progress_meter_step()
double opt_general_progress_meter_step (OPT_ARGS_NUM)
Definition at line 2908 of file Options.cpp.
opt_general_quadric_subdivisions()
double opt_general_quadric_subdivisions (OPT_ARGS_NUM)
Definition at line 3309 of file Options.cpp.
opt_general_quaternion0()
double opt_general_quaternion0 (OPT_ARGS_NUM)
Definition at line 2686 of file Options.cpp.
opt_general_quaternion1()
double opt_general_quaternion1 (OPT_ARGS_NUM)
Definition at line 2700 of file Options.cpp.
opt_general_quaternion2()
double opt_general_quaternion2 (OPT_ARGS_NUM)
Definition at line 2714 of file Options.cpp.
opt_general_quaternion3()
double opt_general_quaternion3 (OPT_ARGS_NUM)
Definition at line 2728 of file Options.cpp.
opt_general_recent_file0()
std::string opt_general_recent_file0 (OPT_ARGS_STR)
Definition at line 1241 of file Options.cpp.
opt_general_recent_file1()
std::string opt_general_recent_file1 (OPT_ARGS_STR)
Definition at line 1247 of file Options.cpp.
opt_general_recent_file2()
std::string opt_general_recent_file2 (OPT_ARGS_STR)
Definition at line 1253 of file Options.cpp.
opt_general_recent_file3()
std::string opt_general_recent_file3 (OPT_ARGS_STR)
Definition at line 1259 of file Options.cpp.
opt_general_recent_file4()
std::string opt_general_recent_file4 (OPT_ARGS_STR)
Definition at line 1265 of file Options.cpp.
opt_general_recent_file5()
std::string opt_general_recent_file5 (OPT_ARGS_STR)
Definition at line 1271 of file Options.cpp.
opt_general_recent_file6()
std::string opt_general_recent_file6 (OPT_ARGS_STR)
Definition at line 1277 of file Options.cpp.
opt_general_recent_file7()
std::string opt_general_recent_file7 (OPT_ARGS_STR)
Definition at line 1283 of file Options.cpp.
opt_general_recent_file8()
std::string opt_general_recent_file8 (OPT_ARGS_STR)
Definition at line 1289 of file Options.cpp.
opt_general_recent_file9()
std::string opt_general_recent_file9 (OPT_ARGS_STR)
Definition at line 1295 of file Options.cpp.
opt_general_rotation0()
double opt_general_rotation0 (OPT_ARGS_NUM)
Definition at line 2614 of file Options.cpp.
opt_general_rotation1()
double opt_general_rotation1 (OPT_ARGS_NUM)
Definition at line 2627 of file Options.cpp.
opt_general_rotation2()
double opt_general_rotation2 (OPT_ARGS_NUM)
Definition at line 2640 of file Options.cpp.
opt_general_rotation_center0()
double opt_general_rotation_center0 (OPT_ARGS_NUM)
Definition at line 2653 of file Options.cpp.
opt_general_rotation_center1()
double opt_general_rotation_center1 (OPT_ARGS_NUM)
Definition at line 2664 of file Options.cpp.
opt_general_rotation_center2()
double opt_general_rotation_center2 (OPT_ARGS_NUM)
Definition at line 2675 of file Options.cpp.
opt_general_rotation_center_cg()
double opt_general_rotation_center_cg (OPT_ARGS_NUM)
Definition at line 3550 of file Options.cpp.
opt_general_scale0()
double opt_general_scale0 (OPT_ARGS_NUM)
Definition at line 2784 of file Options.cpp.
opt_general_scale1()
double opt_general_scale1 (OPT_ARGS_NUM)
Definition at line 2798 of file Options.cpp.
opt_general_scale2()
double opt_general_scale2 (OPT_ARGS_NUM)
Definition at line 2812 of file Options.cpp.
opt_general_scripting_languages()
std::string opt_general_scripting_languages (OPT_ARGS_STR)
Definition at line 1301 of file Options.cpp.
opt_general_session_filename()
std::string opt_general_session_filename (OPT_ARGS_STR)
Definition at line 1229 of file Options.cpp.
opt_general_session_save()
double opt_general_session_save (OPT_ARGS_NUM)
Definition at line 2581 of file Options.cpp.
opt_general_shine()
double opt_general_shine (OPT_ARGS_NUM)
Definition at line 2877 of file Options.cpp.
opt_general_shine_exponent()
double opt_general_shine_exponent (OPT_ARGS_NUM)
Definition at line 2887 of file Options.cpp.
opt_general_show_messages_on_startup()
double opt_general_show_messages_on_startup (OPT_ARGS_NUM)
Definition at line 2175 of file Options.cpp.
opt_general_show_module_menu()
double opt_general_show_module_menu (OPT_ARGS_NUM)
Definition at line 2339 of file Options.cpp.
opt_general_show_options_on_startup()
double opt_general_show_options_on_startup (OPT_ARGS_NUM)
Definition at line 2169 of file Options.cpp.
opt_general_small_axes()
double opt_general_small_axes (OPT_ARGS_NUM)
Definition at line 3268 of file Options.cpp.
Referenced by CreateOutputFile().
opt_general_small_axes_position0()
double opt_general_small_axes_position0 (OPT_ARGS_NUM)
Definition at line 3281 of file Options.cpp.
opt_general_small_axes_position1()
double opt_general_small_axes_position1 (OPT_ARGS_NUM)
Definition at line 3292 of file Options.cpp.
opt_general_small_axes_size()
double opt_general_small_axes_size (OPT_ARGS_NUM)
Definition at line 3303 of file Options.cpp.
opt_general_statistics_position0()
double opt_general_statistics_position0 (OPT_ARGS_NUM)
Definition at line 2515 of file Options.cpp.
opt_general_statistics_position1()
double opt_general_statistics_position1 (OPT_ARGS_NUM)
Definition at line 2521 of file Options.cpp.
opt_general_stereo_mode()
double opt_general_stereo_mode (OPT_ARGS_NUM)
Definition at line 3597 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_system_menu_bar()
double opt_general_system_menu_bar (OPT_ARGS_NUM)
Definition at line 2327 of file Options.cpp.
opt_general_terminal()
double opt_general_terminal (OPT_ARGS_NUM)
Definition at line 2926 of file Options.cpp.
opt_general_tmp_filename()
std::string opt_general_tmp_filename (OPT_ARGS_STR)
Definition at line 1217 of file Options.cpp.
opt_general_tooltips()
double opt_general_tooltips (OPT_ARGS_NUM)
Definition at line 2937 of file Options.cpp.
opt_general_trackball()
double opt_general_trackball (OPT_ARGS_NUM)
Definition at line 3513 of file Options.cpp.
opt_general_trackball_hyperbolic_sheet()
double opt_general_trackball_hyperbolic_sheet (OPT_ARGS_NUM)
Definition at line 3524 of file Options.cpp.
opt_general_translation0()
double opt_general_translation0 (OPT_ARGS_NUM)
Definition at line 2742 of file Options.cpp.
opt_general_translation1()
double opt_general_translation1 (OPT_ARGS_NUM)
Definition at line 2756 of file Options.cpp.
opt_general_translation2()
double opt_general_translation2 (OPT_ARGS_NUM)
Definition at line 2770 of file Options.cpp.
opt_general_vector_type()
double opt_general_vector_type (OPT_ARGS_NUM)
Definition at line 3373 of file Options.cpp.
opt_general_verbosity()
double opt_general_verbosity (OPT_ARGS_NUM)
Definition at line 2898 of file Options.cpp.
opt_general_version()
std::string opt_general_version (OPT_ARGS_STR)
Definition at line 1172 of file Options.cpp.
opt_general_visibility_position0()
double opt_general_visibility_position0 (OPT_ARGS_NUM)
Definition at line 2527 of file Options.cpp.
opt_general_visibility_position1()
double opt_general_visibility_position1 (OPT_ARGS_NUM)
Definition at line 2533 of file Options.cpp.
opt_general_watch_file_pattern()
std::string opt_general_watch_file_pattern (OPT_ARGS_STR)
Definition at line 1324 of file Options.cpp.
Referenced by GetOtherOption().
opt_general_xmax()
double opt_general_xmax (OPT_ARGS_NUM)
Definition at line 3055 of file Options.cpp.
opt_general_xmin()
double opt_general_xmin (OPT_ARGS_NUM)
Definition at line 3049 of file Options.cpp.
opt_general_ymax()
double opt_general_ymax (OPT_ARGS_NUM)
Definition at line 3067 of file Options.cpp.
opt_general_ymin()
double opt_general_ymin (OPT_ARGS_NUM)
Definition at line 3061 of file Options.cpp.
opt_general_zmax()
double opt_general_zmax (OPT_ARGS_NUM)
Definition at line 3079 of file Options.cpp.
opt_general_zmin()
double opt_general_zmin (OPT_ARGS_NUM)
Definition at line 3073 of file Options.cpp.
opt_general_zoom_factor()
double opt_general_zoom_factor (OPT_ARGS_NUM)
Definition at line 3563 of file Options.cpp.
opt_geometry_auto_coherence()
double opt_geometry_auto_coherence (OPT_ARGS_NUM)
Definition at line 4289 of file Options.cpp.
opt_geometry_clip()
double opt_geometry_clip (OPT_ARGS_NUM)
Definition at line 4804 of file Options.cpp.
opt_geometry_color_curves()
unsigned int opt_geometry_color_curves (OPT_ARGS_COL)
Definition at line 9595 of file Options.cpp.
opt_geometry_color_highlight0()
unsigned int opt_geometry_color_highlight0 (OPT_ARGS_COL)
Definition at line 9635 of file Options.cpp.
opt_geometry_color_highlight1()
unsigned int opt_geometry_color_highlight1 (OPT_ARGS_COL)
Definition at line 9645 of file Options.cpp.
opt_geometry_color_highlight2()
unsigned int opt_geometry_color_highlight2 (OPT_ARGS_COL)
Definition at line 9655 of file Options.cpp.
opt_geometry_color_normals()
unsigned int opt_geometry_color_normals (OPT_ARGS_COL)
Definition at line 9675 of file Options.cpp.
opt_geometry_color_points()
unsigned int opt_geometry_color_points (OPT_ARGS_COL)
Definition at line 9585 of file Options.cpp.
opt_geometry_color_projection()
unsigned int opt_geometry_color_projection (OPT_ARGS_COL)
Definition at line 9685 of file Options.cpp.
opt_geometry_color_selection()
unsigned int opt_geometry_color_selection (OPT_ARGS_COL)
Definition at line 9625 of file Options.cpp.
opt_geometry_color_surfaces()
unsigned int opt_geometry_color_surfaces (OPT_ARGS_COL)
Definition at line 9605 of file Options.cpp.
opt_geometry_color_tangents()
unsigned int opt_geometry_color_tangents (OPT_ARGS_COL)
Definition at line 9665 of file Options.cpp.
opt_geometry_color_volumes()
unsigned int opt_geometry_color_volumes (OPT_ARGS_COL)
Definition at line 9615 of file Options.cpp.
opt_geometry_copy_meshing_method()
double opt_geometry_copy_meshing_method (OPT_ARGS_NUM)
Definition at line 4814 of file Options.cpp.
opt_geometry_curve_labels()
double opt_geometry_curve_labels (OPT_ARGS_NUM)
Definition at line 4411 of file Options.cpp.
opt_geometry_curve_sel_width()
double opt_geometry_curve_sel_width (OPT_ARGS_NUM)
Definition at line 4506 of file Options.cpp.
opt_geometry_curve_type()
double opt_geometry_curve_type (OPT_ARGS_NUM)
Definition at line 4517 of file Options.cpp.
opt_geometry_curve_width()
double opt_geometry_curve_width (OPT_ARGS_NUM)
Definition at line 4495 of file Options.cpp.
opt_geometry_curves()
double opt_geometry_curves (OPT_ARGS_NUM)
Definition at line 4367 of file Options.cpp.
opt_geometry_double_clicked_curve_command()
std::string opt_geometry_double_clicked_curve_command (OPT_ARGS_STR)
Definition at line 1409 of file Options.cpp.
opt_geometry_double_clicked_entity_tag()
double opt_geometry_double_clicked_entity_tag (OPT_ARGS_NUM)
Definition at line 4820 of file Options.cpp.
opt_geometry_double_clicked_point_command()
std::string opt_geometry_double_clicked_point_command (OPT_ARGS_STR)
Definition at line 1403 of file Options.cpp.
opt_geometry_double_clicked_surface_command()
std::string opt_geometry_double_clicked_surface_command (OPT_ARGS_STR)
Definition at line 1415 of file Options.cpp.
opt_geometry_double_clicked_volume_command()
std::string opt_geometry_double_clicked_volume_command (OPT_ARGS_STR)
Definition at line 1421 of file Options.cpp.
opt_geometry_exact_extrusion()
double opt_geometry_exact_extrusion (OPT_ARGS_NUM)
Definition at line 4826 of file Options.cpp.
opt_geometry_extrude_return_lateral()
double opt_geometry_extrude_return_lateral (OPT_ARGS_NUM)
Definition at line 4753 of file Options.cpp.
opt_geometry_extrude_spline_points()
double opt_geometry_extrude_spline_points (OPT_ARGS_NUM)
Definition at line 4747 of file Options.cpp.
opt_geometry_highlight_orphans()
double opt_geometry_highlight_orphans (OPT_ARGS_NUM)
Definition at line 4306 of file Options.cpp.
opt_geometry_label_type()
double opt_geometry_label_type (OPT_ARGS_NUM)
Definition at line 4444 of file Options.cpp.
opt_geometry_light()
double opt_geometry_light (OPT_ARGS_NUM)
Definition at line 4546 of file Options.cpp.
opt_geometry_light_two_side()
double opt_geometry_light_two_side (OPT_ARGS_NUM)
Definition at line 4557 of file Options.cpp.
opt_geometry_match_geom_and_mesh()
double opt_geometry_match_geom_and_mesh (OPT_ARGS_NUM)
Definition at line 4832 of file Options.cpp.
Referenced by GetGeometryOption().
opt_geometry_match_mesh_scale_factor()
double opt_geometry_match_mesh_scale_factor (OPT_ARGS_NUM)
Definition at line 4838 of file Options.cpp.
opt_geometry_match_mesh_tolerance()
double opt_geometry_match_mesh_tolerance (OPT_ARGS_NUM)
Definition at line 4845 of file Options.cpp.
opt_geometry_normals()
double opt_geometry_normals (OPT_ARGS_NUM)
Definition at line 4334 of file Options.cpp.
opt_geometry_num_sub_edges()
double opt_geometry_num_sub_edges (OPT_ARGS_NUM)
Definition at line 4731 of file Options.cpp.
opt_geometry_occ_auto_embed()
double opt_geometry_occ_auto_embed (OPT_ARGS_NUM)
Definition at line 4568 of file Options.cpp.
opt_geometry_occ_auto_fix()
double opt_geometry_occ_auto_fix (OPT_ARGS_NUM)
Definition at line 4580 of file Options.cpp.
opt_geometry_occ_boolean_preserve_numbering()
double opt_geometry_occ_boolean_preserve_numbering (OPT_ARGS_NUM)
Definition at line 4676 of file Options.cpp.
opt_geometry_occ_bounds_use_stl()
double opt_geometry_occ_bounds_use_stl (OPT_ARGS_NUM)
Definition at line 4586 of file Options.cpp.
opt_geometry_occ_disable_stl()
double opt_geometry_occ_disable_stl (OPT_ARGS_NUM)
Definition at line 4592 of file Options.cpp.
opt_geometry_occ_export_only_visible()
double opt_geometry_occ_export_only_visible (OPT_ARGS_NUM)
Definition at line 4695 of file Options.cpp.
opt_geometry_occ_fix_degenerated()
double opt_geometry_occ_fix_degenerated (OPT_ARGS_NUM)
Definition at line 4598 of file Options.cpp.
opt_geometry_occ_fix_small_edges()
double opt_geometry_occ_fix_small_edges (OPT_ARGS_NUM)
Definition at line 4610 of file Options.cpp.
opt_geometry_occ_fix_small_faces()
double opt_geometry_occ_fix_small_faces (OPT_ARGS_NUM)
Definition at line 4622 of file Options.cpp.
opt_geometry_occ_import_labels()
double opt_geometry_occ_import_labels (OPT_ARGS_NUM)
Definition at line 4701 of file Options.cpp.
opt_geometry_occ_make_solids()
double opt_geometry_occ_make_solids (OPT_ARGS_NUM)
Definition at line 4646 of file Options.cpp.
opt_geometry_occ_parallel()
double opt_geometry_occ_parallel (OPT_ARGS_NUM)
Definition at line 4670 of file Options.cpp.
opt_geometry_occ_safe_unbind()
double opt_geometry_occ_safe_unbind (OPT_ARGS_NUM)
Definition at line 4574 of file Options.cpp.
opt_geometry_occ_scaling()
double opt_geometry_occ_scaling (OPT_ARGS_NUM)
Definition at line 4683 of file Options.cpp.
opt_geometry_occ_sew_faces()
double opt_geometry_occ_sew_faces (OPT_ARGS_NUM)
Definition at line 4634 of file Options.cpp.
opt_geometry_occ_target_unit()
std::string opt_geometry_occ_target_unit (OPT_ARGS_STR)
Definition at line 1427 of file Options.cpp.
opt_geometry_occ_thrusections_degree()
double opt_geometry_occ_thrusections_degree (OPT_ARGS_NUM)
Definition at line 4664 of file Options.cpp.
opt_geometry_occ_union_unify()
double opt_geometry_occ_union_unify (OPT_ARGS_NUM)
Definition at line 4658 of file Options.cpp.
opt_geometry_occ_use_generic_closest_point()
double opt_geometry_occ_use_generic_closest_point (OPT_ARGS_NUM)
Definition at line 4707 of file Options.cpp.
opt_geometry_offset0()
double opt_geometry_offset0 (OPT_ARGS_NUM)
Definition at line 4274 of file Options.cpp.
opt_geometry_offset1()
double opt_geometry_offset1 (OPT_ARGS_NUM)
Definition at line 4279 of file Options.cpp.
opt_geometry_offset2()
double opt_geometry_offset2 (OPT_ARGS_NUM)
Definition at line 4284 of file Options.cpp.
opt_geometry_old_circle()
double opt_geometry_old_circle (OPT_ARGS_NUM)
Definition at line 4713 of file Options.cpp.
opt_geometry_old_newreg()
double opt_geometry_old_newreg (OPT_ARGS_NUM)
Definition at line 4725 of file Options.cpp.
opt_geometry_old_ruled_surface()
double opt_geometry_old_ruled_surface (OPT_ARGS_NUM)
Definition at line 4719 of file Options.cpp.
opt_geometry_oriented_physicals()
double opt_geometry_oriented_physicals (OPT_ARGS_NUM)
Definition at line 4300 of file Options.cpp.
opt_geometry_pipe_default_trihedron()
std::string opt_geometry_pipe_default_trihedron (OPT_ARGS_STR)
Definition at line 1433 of file Options.cpp.
opt_geometry_point_labels()
double opt_geometry_point_labels (OPT_ARGS_NUM)
Definition at line 4400 of file Options.cpp.
opt_geometry_point_sel_size()
double opt_geometry_point_sel_size (OPT_ARGS_NUM)
Definition at line 4472 of file Options.cpp.
opt_geometry_point_size()
double opt_geometry_point_size (OPT_ARGS_NUM)
Definition at line 4461 of file Options.cpp.
opt_geometry_point_type()
double opt_geometry_point_type (OPT_ARGS_NUM)
Definition at line 4483 of file Options.cpp.
opt_geometry_points()
double opt_geometry_points (OPT_ARGS_NUM)
Definition at line 4356 of file Options.cpp.
opt_geometry_reparam_on_face_robust()
double opt_geometry_reparam_on_face_robust (OPT_ARGS_NUM)
Definition at line 2849 of file Options.cpp.
opt_geometry_scaling_factor()
double opt_geometry_scaling_factor (OPT_ARGS_NUM)
Definition at line 4759 of file Options.cpp.
Referenced by GetGeometryOption().
opt_geometry_snap0()
double opt_geometry_snap0 (OPT_ARGS_NUM)
Definition at line 4771 of file Options.cpp.
opt_geometry_snap1()
double opt_geometry_snap1 (OPT_ARGS_NUM)
Definition at line 4782 of file Options.cpp.
opt_geometry_snap2()
double opt_geometry_snap2 (OPT_ARGS_NUM)
Definition at line 4793 of file Options.cpp.
opt_geometry_snap_points()
double opt_geometry_snap_points (OPT_ARGS_NUM)
Definition at line 4765 of file Options.cpp.
opt_geometry_surface_labels()
double opt_geometry_surface_labels (OPT_ARGS_NUM)
Definition at line 4422 of file Options.cpp.
opt_geometry_surface_type()
double opt_geometry_surface_type (OPT_ARGS_NUM)
Definition at line 4529 of file Options.cpp.
opt_geometry_surfaces()
double opt_geometry_surfaces (OPT_ARGS_NUM)
Definition at line 4378 of file Options.cpp.
opt_geometry_tangents()
double opt_geometry_tangents (OPT_ARGS_NUM)
Definition at line 4345 of file Options.cpp.
opt_geometry_tolerance()
double opt_geometry_tolerance (OPT_ARGS_NUM)
Definition at line 4317 of file Options.cpp.
Referenced by GetGeometryOption().
opt_geometry_tolerance_boolean()
double opt_geometry_tolerance_boolean (OPT_ARGS_NUM)
Definition at line 4328 of file Options.cpp.
opt_geometry_transform()
double opt_geometry_transform (OPT_ARGS_NUM)
Definition at line 4157 of file Options.cpp.
opt_geometry_transform00()
double opt_geometry_transform00 (OPT_ARGS_NUM)
Definition at line 4209 of file Options.cpp.
opt_geometry_transform01()
double opt_geometry_transform01 (OPT_ARGS_NUM)
Definition at line 4214 of file Options.cpp.
opt_geometry_transform02()
double opt_geometry_transform02 (OPT_ARGS_NUM)
Definition at line 4219 of file Options.cpp.
opt_geometry_transform10()
double opt_geometry_transform10 (OPT_ARGS_NUM)
Definition at line 4224 of file Options.cpp.
opt_geometry_transform11()
double opt_geometry_transform11 (OPT_ARGS_NUM)
Definition at line 4229 of file Options.cpp.
opt_geometry_transform12()
double opt_geometry_transform12 (OPT_ARGS_NUM)
Definition at line 4234 of file Options.cpp.
opt_geometry_transform20()
double opt_geometry_transform20 (OPT_ARGS_NUM)
Definition at line 4239 of file Options.cpp.
opt_geometry_transform21()
double opt_geometry_transform21 (OPT_ARGS_NUM)
Definition at line 4244 of file Options.cpp.
opt_geometry_transform22()
double opt_geometry_transform22 (OPT_ARGS_NUM)
Definition at line 4249 of file Options.cpp.
opt_geometry_volume_labels()
double opt_geometry_volume_labels (OPT_ARGS_NUM)
Definition at line 4433 of file Options.cpp.
opt_geometry_volumes()
double opt_geometry_volumes (OPT_ARGS_NUM)
Definition at line 4389 of file Options.cpp.
opt_mesh_algo2d()
double opt_mesh_algo2d (OPT_ARGS_NUM)
Definition at line 5889 of file Options.cpp.
Referenced by GModel::adaptMesh(), and GetMeshOption().
opt_mesh_algo3d()
double opt_mesh_algo3d (OPT_ARGS_NUM)
Definition at line 6058 of file Options.cpp.
Referenced by GModel::adaptMesh(), and GetMeshOption().
opt_mesh_algo_recombine()
double opt_mesh_algo_recombine (OPT_ARGS_NUM)
Definition at line 5945 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_algo_subdivide()
double opt_mesh_algo_subdivide (OPT_ARGS_NUM)
Definition at line 6038 of file Options.cpp.
opt_mesh_algo_switch_on_failure()
double opt_mesh_algo_switch_on_failure (OPT_ARGS_NUM)
Definition at line 5931 of file Options.cpp.
opt_mesh_allow_swap_edge_angle()
double opt_mesh_allow_swap_edge_angle (OPT_ARGS_NUM)
Definition at line 6135 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_angle_smooth_normals()
double opt_mesh_angle_smooth_normals (OPT_ARGS_NUM)
Definition at line 5611 of file Options.cpp.
opt_mesh_angle_tolerance_facet_overlap()
double opt_mesh_angle_tolerance_facet_overlap (OPT_ARGS_NUM)
Definition at line 6647 of file Options.cpp.
opt_mesh_aniso_max()
double opt_mesh_aniso_max (OPT_ARGS_NUM)
Definition at line 5605 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_bdf_field_format()
double opt_mesh_bdf_field_format (OPT_ARGS_NUM)
Definition at line 5831 of file Options.cpp.
opt_mesh_binary()
double opt_mesh_binary (OPT_ARGS_NUM)
Definition at line 5803 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_boundary_layer_fan_elements()
double opt_mesh_boundary_layer_fan_elements (OPT_ARGS_NUM)
Definition at line 5809 of file Options.cpp.
opt_mesh_cgns_construct_topology()
double opt_mesh_cgns_construct_topology (OPT_ARGS_NUM)
Definition at line 6334 of file Options.cpp.
opt_mesh_cgns_export_cpex0045()
double opt_mesh_cgns_export_cpex0045 (OPT_ARGS_NUM)
Definition at line 6342 of file Options.cpp.
opt_mesh_cgns_export_structured()
double opt_mesh_cgns_export_structured (OPT_ARGS_NUM)
Definition at line 6350 of file Options.cpp.
opt_mesh_cgns_import_ignore_bc()
double opt_mesh_cgns_import_ignore_bc (OPT_ARGS_NUM)
Definition at line 6318 of file Options.cpp.
opt_mesh_cgns_import_ignore_solution()
double opt_mesh_cgns_import_ignore_solution (OPT_ARGS_NUM)
Definition at line 6326 of file Options.cpp.
opt_mesh_cgns_import_order()
double opt_mesh_cgns_import_order (OPT_ARGS_NUM)
Definition at line 6309 of file Options.cpp.
opt_mesh_clip()
double opt_mesh_clip (OPT_ARGS_NUM)
Definition at line 6601 of file Options.cpp.
opt_mesh_color_0()
unsigned int opt_mesh_color_0 (OPT_ARGS_COL)
Definition at line 9889 of file Options.cpp.
opt_mesh_color_1()
unsigned int opt_mesh_color_1 (OPT_ARGS_COL)
Definition at line 9893 of file Options.cpp.
opt_mesh_color_10()
unsigned int opt_mesh_color_10 (OPT_ARGS_COL)
Definition at line 9929 of file Options.cpp.
opt_mesh_color_11()
unsigned int opt_mesh_color_11 (OPT_ARGS_COL)
Definition at line 9933 of file Options.cpp.
opt_mesh_color_12()
unsigned int opt_mesh_color_12 (OPT_ARGS_COL)
Definition at line 9937 of file Options.cpp.
opt_mesh_color_13()
unsigned int opt_mesh_color_13 (OPT_ARGS_COL)
Definition at line 9941 of file Options.cpp.
opt_mesh_color_14()
unsigned int opt_mesh_color_14 (OPT_ARGS_COL)
Definition at line 9945 of file Options.cpp.
opt_mesh_color_15()
unsigned int opt_mesh_color_15 (OPT_ARGS_COL)
Definition at line 9949 of file Options.cpp.
opt_mesh_color_16()
unsigned int opt_mesh_color_16 (OPT_ARGS_COL)
Definition at line 9953 of file Options.cpp.
opt_mesh_color_17()
unsigned int opt_mesh_color_17 (OPT_ARGS_COL)
Definition at line 9957 of file Options.cpp.
opt_mesh_color_18()
unsigned int opt_mesh_color_18 (OPT_ARGS_COL)
Definition at line 9961 of file Options.cpp.
opt_mesh_color_19()
unsigned int opt_mesh_color_19 (OPT_ARGS_COL)
Definition at line 9965 of file Options.cpp.
opt_mesh_color_2()
unsigned int opt_mesh_color_2 (OPT_ARGS_COL)
Definition at line 9897 of file Options.cpp.
opt_mesh_color_3()
unsigned int opt_mesh_color_3 (OPT_ARGS_COL)
Definition at line 9901 of file Options.cpp.
opt_mesh_color_4()
unsigned int opt_mesh_color_4 (OPT_ARGS_COL)
Definition at line 9905 of file Options.cpp.
opt_mesh_color_5()
unsigned int opt_mesh_color_5 (OPT_ARGS_COL)
Definition at line 9909 of file Options.cpp.
opt_mesh_color_6()
unsigned int opt_mesh_color_6 (OPT_ARGS_COL)
Definition at line 9913 of file Options.cpp.
opt_mesh_color_7()
unsigned int opt_mesh_color_7 (OPT_ARGS_COL)
Definition at line 9917 of file Options.cpp.
opt_mesh_color_8()
unsigned int opt_mesh_color_8 (OPT_ARGS_COL)
Definition at line 9921 of file Options.cpp.
opt_mesh_color_9()
unsigned int opt_mesh_color_9 (OPT_ARGS_COL)
Definition at line 9925 of file Options.cpp.
opt_mesh_color_carousel()
double opt_mesh_color_carousel (OPT_ARGS_NUM)
Definition at line 6425 of file Options.cpp.
Referenced by GMSH_SimplePartitionPlugin::run().
opt_mesh_color_hexahedra()
unsigned int opt_mesh_color_hexahedra (OPT_ARGS_COL)
Definition at line 9783 of file Options.cpp.
opt_mesh_color_lines()
unsigned int opt_mesh_color_lines (OPT_ARGS_COL)
Definition at line 9715 of file Options.cpp.
opt_mesh_color_nodes()
unsigned int opt_mesh_color_nodes (OPT_ARGS_COL)
Definition at line 9695 of file Options.cpp.
opt_mesh_color_nodes_sup()
unsigned int opt_mesh_color_nodes_sup (OPT_ARGS_COL)
Definition at line 9705 of file Options.cpp.
opt_mesh_color_normals()
unsigned int opt_mesh_color_normals (OPT_ARGS_COL)
Definition at line 9861 of file Options.cpp.
opt_mesh_color_prisms()
unsigned int opt_mesh_color_prisms (OPT_ARGS_COL)
Definition at line 9800 of file Options.cpp.
opt_mesh_color_pyramid()
unsigned int opt_mesh_color_pyramid (OPT_ARGS_COL)
Definition at line 9817 of file Options.cpp.
opt_mesh_color_quadrangles()
unsigned int opt_mesh_color_quadrangles (OPT_ARGS_COL)
Definition at line 9749 of file Options.cpp.
opt_mesh_color_tangents()
unsigned int opt_mesh_color_tangents (OPT_ARGS_COL)
Definition at line 9851 of file Options.cpp.
opt_mesh_color_tetrahedra()
unsigned int opt_mesh_color_tetrahedra (OPT_ARGS_COL)
Definition at line 9766 of file Options.cpp.
opt_mesh_color_triangles()
unsigned int opt_mesh_color_triangles (OPT_ARGS_COL)
Definition at line 9732 of file Options.cpp.
opt_mesh_color_trihedron()
unsigned int opt_mesh_color_trihedron (OPT_ARGS_COL)
Definition at line 9834 of file Options.cpp.
opt_mesh_compound_classify()
double opt_mesh_compound_classify (OPT_ARGS_NUM)
Definition at line 6448 of file Options.cpp.
opt_mesh_compound_lc_factor()
double opt_mesh_compound_lc_factor (OPT_ARGS_NUM)
Definition at line 6454 of file Options.cpp.
opt_mesh_cpu_time()
double opt_mesh_cpu_time (OPT_ARGS_NUM)
Definition at line 6547 of file Options.cpp.
opt_mesh_create_topology_msh2()
double opt_mesh_create_topology_msh2 (OPT_ARGS_NUM)
Definition at line 5797 of file Options.cpp.
opt_mesh_cross_field_closest_point()
double opt_mesh_cross_field_closest_point (OPT_ARGS_NUM)
Definition at line 5825 of file Options.cpp.
opt_mesh_draw_skin_only()
double opt_mesh_draw_skin_only (OPT_ARGS_NUM)
Definition at line 6370 of file Options.cpp.
opt_mesh_dual()
double opt_mesh_dual (OPT_ARGS_NUM)
Definition at line 6358 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_explode()
double opt_mesh_explode (OPT_ARGS_NUM)
Definition at line 4950 of file Options.cpp.
opt_mesh_file_format()
double opt_mesh_file_format (OPT_ARGS_NUM)
Definition at line 5668 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_first_element_tag()
double opt_mesh_first_element_tag (OPT_ARGS_NUM)
Definition at line 5254 of file Options.cpp.
opt_mesh_first_node_tag()
double opt_mesh_first_node_tag (OPT_ARGS_NUM)
Definition at line 5262 of file Options.cpp.
opt_mesh_flexible_transfinite()
double opt_mesh_flexible_transfinite (OPT_ARGS_NUM)
Definition at line 6030 of file Options.cpp.
opt_mesh_hexahedra()
double opt_mesh_hexahedra (OPT_ARGS_NUM)
Definition at line 5353 of file Options.cpp.
opt_mesh_ho_curve_outer_BL()
double opt_mesh_ho_curve_outer_BL (OPT_ARGS_NUM)
Definition at line 6252 of file Options.cpp.
opt_mesh_ho_dist_cad()
double opt_mesh_ho_dist_cad (OPT_ARGS_NUM)
Definition at line 6214 of file Options.cpp.
opt_mesh_ho_fast_new_algo()
double opt_mesh_ho_fast_new_algo (OPT_ARGS_NUM)
Definition at line 6245 of file Options.cpp.
opt_mesh_ho_fix_bnd_nodes()
double opt_mesh_ho_fix_bnd_nodes (OPT_ARGS_NUM)
Definition at line 6276 of file Options.cpp.
opt_mesh_ho_iter_max()
double opt_mesh_ho_iter_max (OPT_ARGS_NUM)
Definition at line 6220 of file Options.cpp.
opt_mesh_ho_max_angle()
double opt_mesh_ho_max_angle (OPT_ARGS_NUM)
Definition at line 6264 of file Options.cpp.
opt_mesh_ho_max_in_angle()
double opt_mesh_ho_max_in_angle (OPT_ARGS_NUM)
Definition at line 6270 of file Options.cpp.
opt_mesh_ho_max_rho()
double opt_mesh_ho_max_rho (OPT_ARGS_NUM)
Definition at line 6258 of file Options.cpp.
opt_mesh_ho_nlayers()
double opt_mesh_ho_nlayers (OPT_ARGS_NUM)
Definition at line 6190 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_ho_optimize()
double opt_mesh_ho_optimize (OPT_ARGS_NUM)
Definition at line 6167 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_ho_pass_max()
double opt_mesh_ho_pass_max (OPT_ARGS_NUM)
Definition at line 6226 of file Options.cpp.
opt_mesh_ho_periodic()
double opt_mesh_ho_periodic (OPT_ARGS_NUM)
Definition at line 6178 of file Options.cpp.
opt_mesh_ho_poisson()
double opt_mesh_ho_poisson (OPT_ARGS_NUM)
Definition at line 6232 of file Options.cpp.
opt_mesh_ho_prim_surf_mesh()
double opt_mesh_ho_prim_surf_mesh (OPT_ARGS_NUM)
Definition at line 6208 of file Options.cpp.
opt_mesh_ho_save_periodic()
double opt_mesh_ho_save_periodic (OPT_ARGS_NUM)
Definition at line 6184 of file Options.cpp.
opt_mesh_ho_threshold_max()
double opt_mesh_ho_threshold_max (OPT_ARGS_NUM)
Definition at line 6202 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_ho_threshold_min()
double opt_mesh_ho_threshold_min (OPT_ARGS_NUM)
Definition at line 6196 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_ignore_parametrization()
double opt_mesh_ignore_parametrization (OPT_ARGS_NUM)
Definition at line 6676 of file Options.cpp.
opt_mesh_ignore_periodicity()
double opt_mesh_ignore_periodicity (OPT_ARGS_NUM)
Definition at line 6617 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_label_sampling()
double opt_mesh_label_sampling (OPT_ARGS_NUM)
Definition at line 5573 of file Options.cpp.
opt_mesh_label_type()
double opt_mesh_label_type (OPT_ARGS_NUM)
Definition at line 5237 of file Options.cpp.
opt_mesh_lc_extend_from_boundary()
double opt_mesh_lc_extend_from_boundary (OPT_ARGS_NUM)
Definition at line 5110 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_lc_factor()
double opt_mesh_lc_factor (OPT_ARGS_NUM)
Definition at line 4976 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_lc_from_curvature()
double opt_mesh_lc_from_curvature (OPT_ARGS_NUM)
Definition at line 5049 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_lc_from_curvature_iso()
double opt_mesh_lc_from_curvature_iso (OPT_ARGS_NUM)
Definition at line 5066 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_lc_from_parametric_points()
double opt_mesh_lc_from_parametric_points (OPT_ARGS_NUM)
Definition at line 5094 of file Options.cpp.
opt_mesh_lc_from_points()
double opt_mesh_lc_from_points (OPT_ARGS_NUM)
Definition at line 5077 of file Options.cpp.
Referenced by GModel::adaptMesh().
opt_mesh_lc_integration_precision()
double opt_mesh_lc_integration_precision (OPT_ARGS_NUM)
Definition at line 5126 of file Options.cpp.
Referenced by GModel::adaptMesh(), and GetMeshOption().
opt_mesh_lc_max()
double opt_mesh_lc_max (OPT_ARGS_NUM)
Definition at line 5012 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_lc_min()
double opt_mesh_lc_min (OPT_ARGS_NUM)
Definition at line 4997 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_light()
double opt_mesh_light (OPT_ARGS_NUM)
Definition at line 5626 of file Options.cpp.
opt_mesh_light_lines()
double opt_mesh_light_lines (OPT_ARGS_NUM)
Definition at line 5639 of file Options.cpp.
opt_mesh_light_two_side()
double opt_mesh_light_two_side (OPT_ARGS_NUM)
Definition at line 5657 of file Options.cpp.
opt_mesh_line_labels()
double opt_mesh_line_labels (OPT_ARGS_NUM)
Definition at line 5506 of file Options.cpp.
opt_mesh_line_width()
double opt_mesh_line_width (OPT_ARGS_NUM)
Definition at line 5562 of file Options.cpp.
opt_mesh_lines()
double opt_mesh_lines (OPT_ARGS_NUM)
Definition at line 5281 of file Options.cpp.
Referenced by GetMeshOption(), and GetOtherOption().
opt_mesh_max_iter_delaunay_3d()
double opt_mesh_max_iter_delaunay_3d (OPT_ARGS_NUM)
Definition at line 6623 of file Options.cpp.
opt_mesh_max_num_threads_1d()
double opt_mesh_max_num_threads_1d (OPT_ARGS_NUM)
Definition at line 6629 of file Options.cpp.
opt_mesh_max_num_threads_2d()
double opt_mesh_max_num_threads_2d (OPT_ARGS_NUM)
Definition at line 6635 of file Options.cpp.
opt_mesh_max_num_threads_3d()
double opt_mesh_max_num_threads_3d (OPT_ARGS_NUM)
Definition at line 6641 of file Options.cpp.
opt_mesh_max_retries()
double opt_mesh_max_retries (OPT_ARGS_NUM)
Definition at line 5939 of file Options.cpp.
opt_mesh_med_file_minor_version()
double opt_mesh_med_file_minor_version (OPT_ARGS_NUM)
Definition at line 5687 of file Options.cpp.
opt_mesh_med_import_groups_of_nodes()
double opt_mesh_med_import_groups_of_nodes (OPT_ARGS_NUM)
Definition at line 5693 of file Options.cpp.
opt_mesh_med_single_model()
double opt_mesh_med_single_model (OPT_ARGS_NUM)
Definition at line 5699 of file Options.cpp.
opt_mesh_mesh_only_empty()
double opt_mesh_mesh_only_empty (OPT_ARGS_NUM)
Definition at line 6102 of file Options.cpp.
opt_mesh_mesh_only_visible()
double opt_mesh_mesh_only_visible (OPT_ARGS_NUM)
Definition at line 6091 of file Options.cpp.
opt_mesh_min_circle_nodes()
double opt_mesh_min_circle_nodes (OPT_ARGS_NUM)
Definition at line 6124 of file Options.cpp.
opt_mesh_min_curve_nodes()
double opt_mesh_min_curve_nodes (OPT_ARGS_NUM)
Definition at line 6141 of file Options.cpp.
opt_mesh_min_line_nodes()
double opt_mesh_min_line_nodes (OPT_ARGS_NUM)
Definition at line 6113 of file Options.cpp.
opt_mesh_msh_file_version()
double opt_mesh_msh_file_version (OPT_ARGS_NUM)
Definition at line 5681 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_nb_hexahedra()
double opt_mesh_nb_hexahedra (OPT_ARGS_NUM)
Definition at line 6519 of file Options.cpp.
opt_mesh_nb_nodes()
double opt_mesh_nb_nodes (OPT_ARGS_NUM)
Definition at line 6491 of file Options.cpp.
opt_mesh_nb_prisms()
double opt_mesh_nb_prisms (OPT_ARGS_NUM)
Definition at line 6526 of file Options.cpp.
opt_mesh_nb_pyramids()
double opt_mesh_nb_pyramids (OPT_ARGS_NUM)
Definition at line 6533 of file Options.cpp.
opt_mesh_nb_quadrangles()
double opt_mesh_nb_quadrangles (OPT_ARGS_NUM)
Definition at line 6505 of file Options.cpp.
opt_mesh_nb_smoothing()
double opt_mesh_nb_smoothing (OPT_ARGS_NUM)
Definition at line 5878 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_nb_tetrahedra()
double opt_mesh_nb_tetrahedra (OPT_ARGS_NUM)
Definition at line 6512 of file Options.cpp.
opt_mesh_nb_triangles()
double opt_mesh_nb_triangles (OPT_ARGS_NUM)
Definition at line 6498 of file Options.cpp.
opt_mesh_nb_trihedra()
double opt_mesh_nb_trihedra (OPT_ARGS_NUM)
Definition at line 6540 of file Options.cpp.
opt_mesh_newton_convergence_test_xyz()
double opt_mesh_newton_convergence_test_xyz (OPT_ARGS_NUM)
Definition at line 5674 of file Options.cpp.
opt_mesh_node_labels()
double opt_mesh_node_labels (OPT_ARGS_NUM)
Definition at line 5495 of file Options.cpp.
opt_mesh_node_size()
double opt_mesh_node_size (OPT_ARGS_NUM)
Definition at line 5539 of file Options.cpp.
opt_mesh_node_type()
double opt_mesh_node_type (OPT_ARGS_NUM)
Definition at line 5550 of file Options.cpp.
opt_mesh_nodes()
double opt_mesh_nodes (OPT_ARGS_NUM)
Definition at line 5270 of file Options.cpp.
Referenced by GetMeshOption(), and GetOtherOption().
opt_mesh_normals()
double opt_mesh_normals (OPT_ARGS_NUM)
Definition at line 4911 of file Options.cpp.
opt_mesh_num_sub_edges()
double opt_mesh_num_sub_edges (OPT_ARGS_NUM)
Definition at line 4922 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_old_initial_delaunay_2d()
double opt_mesh_old_initial_delaunay_2d (OPT_ARGS_NUM)
Definition at line 6708 of file Options.cpp.
opt_mesh_optimize()
double opt_mesh_optimize (OPT_ARGS_NUM)
Definition at line 4851 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_optimize_netgen()
double opt_mesh_optimize_netgen (OPT_ARGS_NUM)
Definition at line 4878 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_optimize_threshold()
double opt_mesh_optimize_threshold (OPT_ARGS_NUM)
Definition at line 4867 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_order()
double opt_mesh_order (OPT_ARGS_NUM)
Definition at line 6152 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_convert_msh2()
double opt_mesh_partition_convert_msh2 (OPT_ARGS_NUM)
Definition at line 5791 of file Options.cpp.
opt_mesh_partition_create_ghost_cells()
double opt_mesh_partition_create_ghost_cells (OPT_ARGS_NUM)
Definition at line 5779 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_create_physicals()
double opt_mesh_partition_create_physicals (OPT_ARGS_NUM)
Definition at line 5767 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_create_topology()
double opt_mesh_partition_create_topology (OPT_ARGS_NUM)
Definition at line 5773 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_hex_weight()
double opt_mesh_partition_hex_weight (OPT_ARGS_NUM)
Definition at line 5719 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_line_weight()
double opt_mesh_partition_line_weight (OPT_ARGS_NUM)
Definition at line 5761 of file Options.cpp.
opt_mesh_partition_metis_algorithm()
double opt_mesh_partition_metis_algorithm (OPT_ARGS_NUM)
Definition at line 6564 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_metis_edge_matching()
double opt_mesh_partition_metis_edge_matching (OPT_ARGS_NUM)
Definition at line 6570 of file Options.cpp.
opt_mesh_partition_metis_max_load_imbalance()
double opt_mesh_partition_metis_max_load_imbalance (OPT_ARGS_NUM)
Definition at line 6583 of file Options.cpp.
opt_mesh_partition_metis_min_conn()
double opt_mesh_partition_metis_min_conn (OPT_ARGS_NUM)
Definition at line 6595 of file Options.cpp.
opt_mesh_partition_metis_objective()
double opt_mesh_partition_metis_objective (OPT_ARGS_NUM)
Definition at line 6589 of file Options.cpp.
opt_mesh_partition_metis_refinement_algorithm()
double opt_mesh_partition_metis_refinement_algorithm (OPT_ARGS_NUM)
Definition at line 6576 of file Options.cpp.
opt_mesh_partition_num()
double opt_mesh_partition_num (OPT_ARGS_NUM)
Definition at line 6554 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_old_style_msh2()
double opt_mesh_partition_old_style_msh2 (OPT_ARGS_NUM)
Definition at line 5785 of file Options.cpp.
opt_mesh_partition_pri_weight()
double opt_mesh_partition_pri_weight (OPT_ARGS_NUM)
Definition at line 5725 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_pyr_weight()
double opt_mesh_partition_pyr_weight (OPT_ARGS_NUM)
Definition at line 5731 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_qua_weight()
double opt_mesh_partition_qua_weight (OPT_ARGS_NUM)
Definition at line 5743 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_save_topology_file()
double opt_mesh_partition_save_topology_file (OPT_ARGS_NUM)
Definition at line 5712 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_split_mesh_files()
double opt_mesh_partition_split_mesh_files (OPT_ARGS_NUM)
Definition at line 5705 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_tet_weight()
double opt_mesh_partition_tet_weight (OPT_ARGS_NUM)
Definition at line 5749 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_tri_weight()
double opt_mesh_partition_tri_weight (OPT_ARGS_NUM)
Definition at line 5755 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_partition_trih_weight()
double opt_mesh_partition_trih_weight (OPT_ARGS_NUM)
Definition at line 5737 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_preserve_numbering_msh2()
double opt_mesh_preserve_numbering_msh2 (OPT_ARGS_NUM)
Definition at line 6611 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_prisms()
double opt_mesh_prisms (OPT_ARGS_NUM)
Definition at line 5372 of file Options.cpp.
opt_mesh_pyramids()
double opt_mesh_pyramids (OPT_ARGS_NUM)
Definition at line 5391 of file Options.cpp.
opt_mesh_quadqs_remeshing_boldness()
double opt_mesh_quadqs_remeshing_boldness (OPT_ARGS_NUM)
Definition at line 6689 of file Options.cpp.
opt_mesh_quadqs_scaling_on_triangulation()
double opt_mesh_quadqs_scaling_on_triangulation (OPT_ARGS_NUM)
Definition at line 6703 of file Options.cpp.
opt_mesh_quadqs_sizemap_method()
double opt_mesh_quadqs_sizemap_method (OPT_ARGS_NUM)
Definition at line 6683 of file Options.cpp.
opt_mesh_quadqs_topo_optim_methods()
double opt_mesh_quadqs_topo_optim_methods (OPT_ARGS_NUM)
Definition at line 6696 of file Options.cpp.
opt_mesh_quadrangles()
double opt_mesh_quadrangles (OPT_ARGS_NUM)
Definition at line 5315 of file Options.cpp.
opt_mesh_quality_inf()
double opt_mesh_quality_inf (OPT_ARGS_NUM)
Definition at line 5177 of file Options.cpp.
opt_mesh_quality_sup()
double opt_mesh_quality_sup (OPT_ARGS_NUM)
Definition at line 5192 of file Options.cpp.
opt_mesh_quality_type()
double opt_mesh_quality_type (OPT_ARGS_NUM)
Definition at line 5158 of file Options.cpp.
opt_mesh_radius_inf()
double opt_mesh_radius_inf (OPT_ARGS_NUM)
Definition at line 5207 of file Options.cpp.
opt_mesh_radius_sup()
double opt_mesh_radius_sup (OPT_ARGS_NUM)
Definition at line 5222 of file Options.cpp.
opt_mesh_rand_factor()
double opt_mesh_rand_factor (OPT_ARGS_NUM)
Definition at line 5137 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_rand_factor3d()
double opt_mesh_rand_factor3d (OPT_ARGS_NUM)
Definition at line 5147 of file Options.cpp.
opt_mesh_random_seed()
double opt_mesh_random_seed (OPT_ARGS_NUM)
Definition at line 6460 of file Options.cpp.
opt_mesh_read_groups_of_elements()
double opt_mesh_read_groups_of_elements (OPT_ARGS_NUM)
Definition at line 6407 of file Options.cpp.
opt_mesh_recombine3d_all()
double opt_mesh_recombine3d_all (OPT_ARGS_NUM)
Definition at line 6005 of file Options.cpp.
opt_mesh_recombine3d_conformity()
double opt_mesh_recombine3d_conformity (OPT_ARGS_NUM)
Definition at line 6022 of file Options.cpp.
opt_mesh_recombine3d_level()
double opt_mesh_recombine3d_level (OPT_ARGS_NUM)
Definition at line 6016 of file Options.cpp.
opt_mesh_recombine_all()
double opt_mesh_recombine_all (OPT_ARGS_NUM)
Definition at line 5965 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_recombine_minimum_quality()
double opt_mesh_recombine_minimum_quality (OPT_ARGS_NUM)
Definition at line 5997 of file Options.cpp.
opt_mesh_recombine_node_repositioning()
double opt_mesh_recombine_node_repositioning (OPT_ARGS_NUM)
Definition at line 5989 of file Options.cpp.
opt_mesh_recombine_optimize_topology()
double opt_mesh_recombine_optimize_topology (OPT_ARGS_NUM)
Definition at line 5981 of file Options.cpp.
opt_mesh_refine_steps()
double opt_mesh_refine_steps (OPT_ARGS_NUM)
Definition at line 4894 of file Options.cpp.
opt_mesh_renumber()
double opt_mesh_renumber (OPT_ARGS_NUM)
Definition at line 4905 of file Options.cpp.
opt_mesh_reparam_max_triangles()
double opt_mesh_reparam_max_triangles (OPT_ARGS_NUM)
Definition at line 6670 of file Options.cpp.
opt_mesh_save_all()
double opt_mesh_save_all (OPT_ARGS_NUM)
Definition at line 6376 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_save_element_tag_type()
double opt_mesh_save_element_tag_type (OPT_ARGS_NUM)
Definition at line 6382 of file Options.cpp.
opt_mesh_save_groups_of_elements()
double opt_mesh_save_groups_of_elements (OPT_ARGS_NUM)
Definition at line 6413 of file Options.cpp.
opt_mesh_save_groups_of_nodes()
double opt_mesh_save_groups_of_nodes (OPT_ARGS_NUM)
Definition at line 6419 of file Options.cpp.
opt_mesh_save_parametric()
double opt_mesh_save_parametric (OPT_ARGS_NUM)
Definition at line 6388 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_save_topology()
double opt_mesh_save_topology (OPT_ARGS_NUM)
Definition at line 6401 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_save_without_orphans()
double opt_mesh_save_without_orphans (OPT_ARGS_NUM)
Definition at line 6394 of file Options.cpp.
opt_mesh_scaling_factor()
double opt_mesh_scaling_factor (OPT_ARGS_NUM)
Definition at line 4965 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_second_order_incomplete()
double opt_mesh_second_order_incomplete (OPT_ARGS_NUM)
Definition at line 6293 of file Options.cpp.
opt_mesh_second_order_linear()
double opt_mesh_second_order_linear (OPT_ARGS_NUM)
Definition at line 6282 of file Options.cpp.
opt_mesh_smooth_cross_field()
double opt_mesh_smooth_cross_field (OPT_ARGS_NUM)
Definition at line 5819 of file Options.cpp.
opt_mesh_smooth_normals()
double opt_mesh_smooth_normals (OPT_ARGS_NUM)
Definition at line 5584 of file Options.cpp.
opt_mesh_smooth_ratio()
double opt_mesh_smooth_ratio (OPT_ARGS_NUM)
Definition at line 5599 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_stl_angular_deflection()
double opt_mesh_stl_angular_deflection (OPT_ARGS_NUM)
Definition at line 5872 of file Options.cpp.
opt_mesh_stl_linear_deflection()
double opt_mesh_stl_linear_deflection (OPT_ARGS_NUM)
Definition at line 5858 of file Options.cpp.
opt_mesh_stl_linear_deflection_relative()
double opt_mesh_stl_linear_deflection_relative (OPT_ARGS_NUM)
Definition at line 5864 of file Options.cpp.
opt_mesh_stl_one_solid_per_surface()
double opt_mesh_stl_one_solid_per_surface (OPT_ARGS_NUM)
Definition at line 5850 of file Options.cpp.
opt_mesh_stl_remove_duplicate_triangles()
double opt_mesh_stl_remove_duplicate_triangles (OPT_ARGS_NUM)
Definition at line 5842 of file Options.cpp.
opt_mesh_surface_edges()
double opt_mesh_surface_edges (OPT_ARGS_NUM)
Definition at line 5435 of file Options.cpp.
Referenced by GetMeshOption(), and GetOtherOption().
opt_mesh_surface_faces()
double opt_mesh_surface_faces (OPT_ARGS_NUM)
Definition at line 5450 of file Options.cpp.
Referenced by GetMeshOption(), and GetOtherOption().
opt_mesh_surface_labels()
double opt_mesh_surface_labels (OPT_ARGS_NUM)
Definition at line 5517 of file Options.cpp.
opt_mesh_switch_elem_tags()
double opt_mesh_switch_elem_tags (OPT_ARGS_NUM)
Definition at line 6466 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_tangents()
double opt_mesh_tangents (OPT_ARGS_NUM)
Definition at line 4939 of file Options.cpp.
opt_mesh_tetrahedra()
double opt_mesh_tetrahedra (OPT_ARGS_NUM)
Definition at line 5334 of file Options.cpp.
opt_mesh_tolerance_edge_length()
double opt_mesh_tolerance_edge_length (OPT_ARGS_NUM)
Definition at line 5027 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_tolerance_initial_delaunay()
double opt_mesh_tolerance_initial_delaunay (OPT_ARGS_NUM)
Definition at line 5038 of file Options.cpp.
opt_mesh_tolerance_reference_element()
double opt_mesh_tolerance_reference_element (OPT_ARGS_NUM)
Definition at line 6658 of file Options.cpp.
opt_mesh_transfinite_tri()
double opt_mesh_transfinite_tri (OPT_ARGS_NUM)
Definition at line 5429 of file Options.cpp.
opt_mesh_triangles()
double opt_mesh_triangles (OPT_ARGS_NUM)
Definition at line 5296 of file Options.cpp.
opt_mesh_trihedra()
double opt_mesh_trihedra (OPT_ARGS_NUM)
Definition at line 5410 of file Options.cpp.
opt_mesh_unv_strict_format()
double opt_mesh_unv_strict_format (OPT_ARGS_NUM)
Definition at line 6664 of file Options.cpp.
opt_mesh_volume_edges()
double opt_mesh_volume_edges (OPT_ARGS_NUM)
Definition at line 5465 of file Options.cpp.
Referenced by GetMeshOption(), and GetOtherOption().
opt_mesh_volume_faces()
double opt_mesh_volume_faces (OPT_ARGS_NUM)
Definition at line 5480 of file Options.cpp.
Referenced by GetMeshOption(), and GetOtherOption().
opt_mesh_volume_labels()
double opt_mesh_volume_labels (OPT_ARGS_NUM)
Definition at line 5528 of file Options.cpp.
opt_mesh_voronoi()
double opt_mesh_voronoi (OPT_ARGS_NUM)
Definition at line 6364 of file Options.cpp.
Referenced by GetMeshOption().
opt_mesh_zone_definition()
double opt_mesh_zone_definition (OPT_ARGS_NUM)
Definition at line 6472 of file Options.cpp.
opt_post_anim_cycle()
double opt_post_anim_cycle (OPT_ARGS_NUM)
Definition at line 6846 of file Options.cpp.
opt_post_anim_delay()
double opt_post_anim_delay (OPT_ARGS_NUM)
Definition at line 6834 of file Options.cpp.
opt_post_anim_step()
double opt_post_anim_step (OPT_ARGS_NUM)
Definition at line 6865 of file Options.cpp.
opt_post_binary()
double opt_post_binary (OPT_ARGS_NUM)
Definition at line 6810 of file Options.cpp.
opt_post_combine_copy_options()
double opt_post_combine_copy_options (OPT_ARGS_NUM)
Definition at line 6890 of file Options.cpp.
opt_post_combine_remove_orig()
double opt_post_combine_remove_orig (OPT_ARGS_NUM)
Definition at line 6879 of file Options.cpp.
opt_post_double_clicked_graph_point_command()
std::string opt_post_double_clicked_graph_point_command (OPT_ARGS_STR)
Definition at line 1700 of file Options.cpp.
opt_post_double_clicked_graph_point_x()
double opt_post_double_clicked_graph_point_x (OPT_ARGS_NUM)
Definition at line 6942 of file Options.cpp.
opt_post_double_clicked_graph_point_y()
double opt_post_double_clicked_graph_point_y (OPT_ARGS_NUM)
Definition at line 6948 of file Options.cpp.
opt_post_double_clicked_view()
double opt_post_double_clicked_view (OPT_ARGS_NUM)
Definition at line 6954 of file Options.cpp.
opt_post_file_format()
double opt_post_file_format (OPT_ARGS_NUM)
Definition at line 6911 of file Options.cpp.
opt_post_force_element_data()
double opt_post_force_element_data (OPT_ARGS_NUM)
Definition at line 6923 of file Options.cpp.
opt_post_force_node_data()
double opt_post_force_node_data (OPT_ARGS_NUM)
Definition at line 6917 of file Options.cpp.
opt_post_horizontal_scales()
double opt_post_horizontal_scales (OPT_ARGS_NUM)
Definition at line 6799 of file Options.cpp.
opt_post_link()
double opt_post_link (OPT_ARGS_NUM)
Definition at line 6816 of file Options.cpp.
Referenced by GetPostProcessingOption().
opt_post_nb_views()
double opt_post_nb_views (OPT_ARGS_NUM)
Definition at line 6902 of file Options.cpp.
Referenced by CreateOutputFile().
opt_post_plugins()
double opt_post_plugins (OPT_ARGS_NUM)
Definition at line 6896 of file Options.cpp.
opt_post_save_interpolation_matrices()
double opt_post_save_interpolation_matrices (OPT_ARGS_NUM)
Definition at line 6935 of file Options.cpp.
opt_post_save_mesh()
double opt_post_save_mesh (OPT_ARGS_NUM)
Definition at line 6929 of file Options.cpp.
opt_post_smooth()
double opt_post_smooth (OPT_ARGS_NUM)
Definition at line 6828 of file Options.cpp.
Referenced by GetPostProcessingOption().
opt_print_background()
double opt_print_background (OPT_ARGS_NUM)
Definition at line 9321 of file Options.cpp.
opt_print_composite_windows()
double opt_print_composite_windows (OPT_ARGS_NUM)
Definition at line 9367 of file Options.cpp.
opt_print_delete_tmp_files()
double opt_print_delete_tmp_files (OPT_ARGS_NUM)
Definition at line 9373 of file Options.cpp.
Referenced by CreateOutputFile().
opt_print_eps_best_root()
double opt_print_eps_best_root (OPT_ARGS_NUM)
Definition at line 9213 of file Options.cpp.
opt_print_eps_compress()
double opt_print_eps_compress (OPT_ARGS_NUM)
Definition at line 9189 of file Options.cpp.
opt_print_eps_line_width_factor()
double opt_print_eps_line_width_factor (OPT_ARGS_NUM)
Definition at line 9219 of file Options.cpp.
opt_print_eps_occlusion_culling()
double opt_print_eps_occlusion_culling (OPT_ARGS_NUM)
Definition at line 9207 of file Options.cpp.
opt_print_eps_point_size_factor()
double opt_print_eps_point_size_factor (OPT_ARGS_NUM)
Definition at line 9225 of file Options.cpp.
opt_print_eps_ps3shading()
double opt_print_eps_ps3shading (OPT_ARGS_NUM)
Definition at line 9195 of file Options.cpp.
opt_print_eps_quality()
double opt_print_eps_quality (OPT_ARGS_NUM)
Definition at line 9201 of file Options.cpp.
opt_print_file_format()
double opt_print_file_format (OPT_ARGS_NUM)
Definition at line 9183 of file Options.cpp.
opt_print_geo_labels()
double opt_print_geo_labels (OPT_ARGS_NUM)
Definition at line 9243 of file Options.cpp.
opt_print_geo_only_physicals()
double opt_print_geo_only_physicals (OPT_ARGS_NUM)
Definition at line 9249 of file Options.cpp.
opt_print_gif_dither()
double opt_print_gif_dither (OPT_ARGS_NUM)
Definition at line 9297 of file Options.cpp.
opt_print_gif_interlace()
double opt_print_gif_interlace (OPT_ARGS_NUM)
Definition at line 9309 of file Options.cpp.
opt_print_gif_sort()
double opt_print_gif_sort (OPT_ARGS_NUM)
Definition at line 9303 of file Options.cpp.
opt_print_gif_transparent()
double opt_print_gif_transparent (OPT_ARGS_NUM)
Definition at line 9315 of file Options.cpp.
opt_print_height()
double opt_print_height (OPT_ARGS_NUM)
Definition at line 9379 of file Options.cpp.
opt_print_jpeg_quality()
double opt_print_jpeg_quality (OPT_ARGS_NUM)
Definition at line 9231 of file Options.cpp.
opt_print_jpeg_smoothing()
double opt_print_jpeg_smoothing (OPT_ARGS_NUM)
Definition at line 9237 of file Options.cpp.
opt_print_parameter()
double opt_print_parameter (OPT_ARGS_NUM)
Definition at line 9391 of file Options.cpp.
Referenced by ChangePrintParameter().
opt_print_parameter_command()
std::string opt_print_parameter_command (OPT_ARGS_STR)
Definition at line 2149 of file Options.cpp.
opt_print_parameter_first()
double opt_print_parameter_first (OPT_ARGS_NUM)
Definition at line 9397 of file Options.cpp.
opt_print_parameter_last()
double opt_print_parameter_last (OPT_ARGS_NUM)
Definition at line 9403 of file Options.cpp.
opt_print_parameter_steps()
double opt_print_parameter_steps (OPT_ARGS_NUM)
Definition at line 9409 of file Options.cpp.
opt_print_pgf_export_axis()
double opt_print_pgf_export_axis (OPT_ARGS_NUM)
Definition at line 9332 of file Options.cpp.
Referenced by print_pgf().
opt_print_pgf_horiz_bar()
double opt_print_pgf_horiz_bar (OPT_ARGS_NUM)
Definition at line 9337 of file Options.cpp.
Referenced by assembleColbarStr(), and assemblePostAxis().
opt_print_pgf_two_dim()
double opt_print_pgf_two_dim (OPT_ARGS_NUM)
Definition at line 9327 of file Options.cpp.
Referenced by print_pgf().
opt_print_pos_disto()
double opt_print_pos_disto (OPT_ARGS_NUM)
Definition at line 9291 of file Options.cpp.
opt_print_pos_element()
double opt_print_pos_element (OPT_ARGS_NUM)
Definition at line 9261 of file Options.cpp.
opt_print_pos_elementary()
double opt_print_pos_elementary (OPT_ARGS_NUM)
Definition at line 9255 of file Options.cpp.
opt_print_pos_eta()
double opt_print_pos_eta (OPT_ARGS_NUM)
Definition at line 9273 of file Options.cpp.
opt_print_pos_gamma()
double opt_print_pos_gamma (OPT_ARGS_NUM)
Definition at line 9267 of file Options.cpp.
opt_print_pos_SICN()
double opt_print_pos_SICN (OPT_ARGS_NUM)
Definition at line 9279 of file Options.cpp.
opt_print_pos_SIGE()
double opt_print_pos_SIGE (OPT_ARGS_NUM)
Definition at line 9285 of file Options.cpp.
opt_print_tex_as_equation()
double opt_print_tex_as_equation (OPT_ARGS_NUM)
Definition at line 9349 of file Options.cpp.
opt_print_tex_force_fontsize()
double opt_print_tex_force_fontsize (OPT_ARGS_NUM)
Definition at line 9355 of file Options.cpp.
opt_print_tex_width_in_mm()
double opt_print_tex_width_in_mm (OPT_ARGS_NUM)
Definition at line 9361 of file Options.cpp.
opt_print_text()
double opt_print_text (OPT_ARGS_NUM)
Definition at line 9343 of file Options.cpp.
opt_print_width()
double opt_print_width (OPT_ARGS_NUM)
Definition at line 9385 of file Options.cpp.
opt_print_x3d_colorize()
double opt_print_x3d_colorize (OPT_ARGS_NUM)
Definition at line 9463 of file Options.cpp.
opt_print_x3d_compatibility()
double opt_print_x3d_compatibility (OPT_ARGS_NUM)
Definition at line 9415 of file Options.cpp.
opt_print_x3d_edges()
double opt_print_x3d_edges (OPT_ARGS_NUM)
Definition at line 9445 of file Options.cpp.
opt_print_x3d_precision()
double opt_print_x3d_precision (OPT_ARGS_NUM)
Definition at line 9433 of file Options.cpp.
opt_print_x3d_remove_inner_borders()
double opt_print_x3d_remove_inner_borders (OPT_ARGS_NUM)
Definition at line 9427 of file Options.cpp.
opt_print_x3d_surfaces()
double opt_print_x3d_surfaces (OPT_ARGS_NUM)
Definition at line 9439 of file Options.cpp.
opt_print_x3d_transparency()
double opt_print_x3d_transparency (OPT_ARGS_NUM)
Definition at line 9421 of file Options.cpp.
opt_print_x3d_vertices()
double opt_print_x3d_vertices (OPT_ARGS_NUM)
Definition at line 9451 of file Options.cpp.
opt_print_x3d_volumes()
double opt_print_x3d_volumes (OPT_ARGS_NUM)
Definition at line 9457 of file Options.cpp.
opt_solver_auto_archive_output_files()
double opt_solver_auto_archive_output_files (OPT_ARGS_NUM)
Definition at line 6755 of file Options.cpp.
opt_solver_auto_check()
double opt_solver_auto_check (OPT_ARGS_NUM)
Definition at line 6762 of file Options.cpp.
opt_solver_auto_load_database()
double opt_solver_auto_load_database (OPT_ARGS_NUM)
Definition at line 6743 of file Options.cpp.
opt_solver_auto_merge_file()
double opt_solver_auto_merge_file (OPT_ARGS_NUM)
Definition at line 6774 of file Options.cpp.
opt_solver_auto_mesh()
double opt_solver_auto_mesh (OPT_ARGS_NUM)
Definition at line 6768 of file Options.cpp.
opt_solver_auto_save_database()
double opt_solver_auto_save_database (OPT_ARGS_NUM)
Definition at line 6749 of file Options.cpp.
opt_solver_auto_show_last_step()
double opt_solver_auto_show_last_step (OPT_ARGS_NUM)
Definition at line 6786 of file Options.cpp.
opt_solver_auto_show_views()
double opt_solver_auto_show_views (OPT_ARGS_NUM)
Definition at line 6780 of file Options.cpp.
opt_solver_executable()
std::string opt_solver_executable (OPT_ARGS_STR)
Definition at line 1564 of file Options.cpp.
Referenced by MergeFile(), opt_solver_executable0(), opt_solver_executable1(), opt_solver_executable2(), opt_solver_executable3(), opt_solver_executable4(), opt_solver_executable5(), opt_solver_executable6(), opt_solver_executable7(), opt_solver_executable8(), and opt_solver_executable9().
opt_solver_executable0()
std::string opt_solver_executable0 (OPT_ARGS_STR)
Definition at line 1571 of file Options.cpp.
opt_solver_executable1()
std::string opt_solver_executable1 (OPT_ARGS_STR)
Definition at line 1576 of file Options.cpp.
opt_solver_executable2()
std::string opt_solver_executable2 (OPT_ARGS_STR)
Definition at line 1581 of file Options.cpp.
opt_solver_executable3()
std::string opt_solver_executable3 (OPT_ARGS_STR)
Definition at line 1586 of file Options.cpp.
opt_solver_executable4()
std::string opt_solver_executable4 (OPT_ARGS_STR)
Definition at line 1591 of file Options.cpp.
opt_solver_executable5()
std::string opt_solver_executable5 (OPT_ARGS_STR)
Definition at line 1596 of file Options.cpp.
opt_solver_executable6()
std::string opt_solver_executable6 (OPT_ARGS_STR)
Definition at line 1601 of file Options.cpp.
opt_solver_executable7()
std::string opt_solver_executable7 (OPT_ARGS_STR)
Definition at line 1606 of file Options.cpp.
opt_solver_executable8()
std::string opt_solver_executable8 (OPT_ARGS_STR)
Definition at line 1611 of file Options.cpp.
opt_solver_executable9()
std::string opt_solver_executable9 (OPT_ARGS_STR)
Definition at line 1616 of file Options.cpp.
opt_solver_extension()
std::string opt_solver_extension (OPT_ARGS_STR)
Definition at line 1507 of file Options.cpp.
Referenced by opt_solver_extension0(), opt_solver_extension1(), opt_solver_extension2(), opt_solver_extension3(), opt_solver_extension4(), opt_solver_extension5(), opt_solver_extension6(), opt_solver_extension7(), opt_solver_extension8(), and opt_solver_extension9().
opt_solver_extension0()
std::string opt_solver_extension0 (OPT_ARGS_STR)
Definition at line 1514 of file Options.cpp.
opt_solver_extension1()
std::string opt_solver_extension1 (OPT_ARGS_STR)
Definition at line 1519 of file Options.cpp.
opt_solver_extension2()
std::string opt_solver_extension2 (OPT_ARGS_STR)
Definition at line 1524 of file Options.cpp.
opt_solver_extension3()
std::string opt_solver_extension3 (OPT_ARGS_STR)
Definition at line 1529 of file Options.cpp.
opt_solver_extension4()
std::string opt_solver_extension4 (OPT_ARGS_STR)
Definition at line 1534 of file Options.cpp.
opt_solver_extension5()
std::string opt_solver_extension5 (OPT_ARGS_STR)
Definition at line 1539 of file Options.cpp.
opt_solver_extension6()
std::string opt_solver_extension6 (OPT_ARGS_STR)
Definition at line 1544 of file Options.cpp.
opt_solver_extension7()
std::string opt_solver_extension7 (OPT_ARGS_STR)
Definition at line 1549 of file Options.cpp.
opt_solver_extension8()
std::string opt_solver_extension8 (OPT_ARGS_STR)
Definition at line 1554 of file Options.cpp.
opt_solver_extension9()
std::string opt_solver_extension9 (OPT_ARGS_STR)
Definition at line 1559 of file Options.cpp.
opt_solver_listen()
double opt_solver_listen (OPT_ARGS_NUM)
Definition at line 6715 of file Options.cpp.
Referenced by GetSolverOption().
opt_solver_name()
std::string opt_solver_name (OPT_ARGS_STR)
Definition at line 1450 of file Options.cpp.
Referenced by opt_solver_name0(), opt_solver_name1(), opt_solver_name2(), opt_solver_name3(), opt_solver_name4(), opt_solver_name5(), opt_solver_name6(), opt_solver_name7(), opt_solver_name8(), and opt_solver_name9().
opt_solver_name0()
std::string opt_solver_name0 (OPT_ARGS_STR)
Definition at line 1457 of file Options.cpp.
opt_solver_name1()
std::string opt_solver_name1 (OPT_ARGS_STR)
Definition at line 1462 of file Options.cpp.
opt_solver_name2()
std::string opt_solver_name2 (OPT_ARGS_STR)
Definition at line 1467 of file Options.cpp.
opt_solver_name3()
std::string opt_solver_name3 (OPT_ARGS_STR)
Definition at line 1472 of file Options.cpp.
opt_solver_name4()
std::string opt_solver_name4 (OPT_ARGS_STR)
Definition at line 1477 of file Options.cpp.
opt_solver_name5()
std::string opt_solver_name5 (OPT_ARGS_STR)
Definition at line 1482 of file Options.cpp.
opt_solver_name6()
std::string opt_solver_name6 (OPT_ARGS_STR)
Definition at line 1487 of file Options.cpp.
opt_solver_name7()
std::string opt_solver_name7 (OPT_ARGS_STR)
Definition at line 1492 of file Options.cpp.
opt_solver_name8()
std::string opt_solver_name8 (OPT_ARGS_STR)
Definition at line 1497 of file Options.cpp.
opt_solver_name9()
std::string opt_solver_name9 (OPT_ARGS_STR)
Definition at line 1502 of file Options.cpp.
opt_solver_octave_interpreter()
std::string opt_solver_octave_interpreter (OPT_ARGS_STR)
Definition at line 1689 of file Options.cpp.
Referenced by GetSolverOption().
opt_solver_plugins()
double opt_solver_plugins (OPT_ARGS_NUM)
Definition at line 6737 of file Options.cpp.
opt_solver_python_interpreter()
std::string opt_solver_python_interpreter (OPT_ARGS_STR)
Definition at line 1678 of file Options.cpp.
Referenced by GetSolverOption().
opt_solver_remote_login()
std::string opt_solver_remote_login (OPT_ARGS_STR)
Definition at line 1621 of file Options.cpp.
Referenced by opt_solver_remote_login0(), opt_solver_remote_login1(), opt_solver_remote_login2(), opt_solver_remote_login3(), opt_solver_remote_login4(), opt_solver_remote_login5(), opt_solver_remote_login6(), opt_solver_remote_login7(), opt_solver_remote_login8(), and opt_solver_remote_login9().
opt_solver_remote_login0()
std::string opt_solver_remote_login0 (OPT_ARGS_STR)
Definition at line 1628 of file Options.cpp.
opt_solver_remote_login1()
std::string opt_solver_remote_login1 (OPT_ARGS_STR)
Definition at line 1633 of file Options.cpp.
opt_solver_remote_login2()
std::string opt_solver_remote_login2 (OPT_ARGS_STR)
Definition at line 1638 of file Options.cpp.
opt_solver_remote_login3()
std::string opt_solver_remote_login3 (OPT_ARGS_STR)
Definition at line 1643 of file Options.cpp.
opt_solver_remote_login4()
std::string opt_solver_remote_login4 (OPT_ARGS_STR)
Definition at line 1648 of file Options.cpp.
opt_solver_remote_login5()
std::string opt_solver_remote_login5 (OPT_ARGS_STR)
Definition at line 1653 of file Options.cpp.
opt_solver_remote_login6()
std::string opt_solver_remote_login6 (OPT_ARGS_STR)
Definition at line 1658 of file Options.cpp.
opt_solver_remote_login7()
std::string opt_solver_remote_login7 (OPT_ARGS_STR)
Definition at line 1663 of file Options.cpp.
opt_solver_remote_login8()
std::string opt_solver_remote_login8 (OPT_ARGS_STR)
Definition at line 1668 of file Options.cpp.
opt_solver_remote_login9()
std::string opt_solver_remote_login9 (OPT_ARGS_STR)
Definition at line 1673 of file Options.cpp.
opt_solver_show_invisible_parameters()
double opt_solver_show_invisible_parameters (OPT_ARGS_NUM)
Definition at line 6792 of file Options.cpp.
opt_solver_socket_name()
std::string opt_solver_socket_name (OPT_ARGS_STR)
Definition at line 1439 of file Options.cpp.
Referenced by GetSolverOption().
opt_solver_timeout()
double opt_solver_timeout (OPT_ARGS_NUM)
Definition at line 6726 of file Options.cpp.
opt_view_abscissa_range_type()
double opt_view_abscissa_range_type (OPT_ARGS_NUM)
Definition at line 8615 of file Options.cpp.
opt_view_adapt_visualization_grid()
double opt_view_adapt_visualization_grid (OPT_ARGS_NUM)
Definition at line 7689 of file Options.cpp.
opt_view_angle_smooth_normals()
double opt_view_angle_smooth_normals (OPT_ARGS_NUM)
Definition at line 8184 of file Options.cpp.
opt_view_arrow_size_max()
double opt_view_arrow_size_max (OPT_ARGS_NUM)
Definition at line 7535 of file Options.cpp.
opt_view_arrow_size_min()
double opt_view_arrow_size_min (OPT_ARGS_NUM)
Definition at line 7520 of file Options.cpp.
opt_view_attributes()
std::string opt_view_attributes (OPT_ARGS_STR)
Definition at line 2138 of file Options.cpp.
opt_view_auto_position()
double opt_view_auto_position (OPT_ARGS_NUM)
Definition at line 7783 of file Options.cpp.
opt_view_axes()
double opt_view_axes (OPT_ARGS_NUM)
Definition at line 7881 of file Options.cpp.
opt_view_axes_auto_position()
double opt_view_axes_auto_position (OPT_ARGS_NUM)
Definition at line 7917 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_view_axes_format0()
std::string opt_view_axes_format0 (OPT_ARGS_STR)
Definition at line 1844 of file Options.cpp.
opt_view_axes_format1()
std::string opt_view_axes_format1 (OPT_ARGS_STR)
Definition at line 1860 of file Options.cpp.
opt_view_axes_format2()
std::string opt_view_axes_format2 (OPT_ARGS_STR)
Definition at line 1876 of file Options.cpp.
opt_view_axes_label0()
std::string opt_view_axes_label0 (OPT_ARGS_STR)
Definition at line 1796 of file Options.cpp.
opt_view_axes_label1()
std::string opt_view_axes_label1 (OPT_ARGS_STR)
Definition at line 1812 of file Options.cpp.
opt_view_axes_label2()
std::string opt_view_axes_label2 (OPT_ARGS_STR)
Definition at line 1828 of file Options.cpp.
opt_view_axes_mikado()
double opt_view_axes_mikado (OPT_ARGS_NUM)
Definition at line 7901 of file Options.cpp.
opt_view_axes_tics0()
double opt_view_axes_tics0 (OPT_ARGS_NUM)
Definition at line 8030 of file Options.cpp.
opt_view_axes_tics1()
double opt_view_axes_tics1 (OPT_ARGS_NUM)
Definition at line 8046 of file Options.cpp.
opt_view_axes_tics2()
double opt_view_axes_tics2 (OPT_ARGS_NUM)
Definition at line 8062 of file Options.cpp.
opt_view_axes_xmax()
double opt_view_axes_xmax (OPT_ARGS_NUM)
Definition at line 7950 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_view_axes_xmin()
double opt_view_axes_xmin (OPT_ARGS_NUM)
Definition at line 7934 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_view_axes_ymax()
double opt_view_axes_ymax (OPT_ARGS_NUM)
Definition at line 7982 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_view_axes_ymin()
double opt_view_axes_ymin (OPT_ARGS_NUM)
Definition at line 7966 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_view_axes_zmax()
double opt_view_axes_zmax (OPT_ARGS_NUM)
Definition at line 8014 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_view_axes_zmin()
double opt_view_axes_zmin (OPT_ARGS_NUM)
Definition at line 7998 of file Options.cpp.
Referenced by getMinMaxOfAxis().
opt_view_boundary()
double opt_view_boundary (OPT_ARGS_NUM)
Definition at line 8096 of file Options.cpp.
opt_view_center_glyphs()
double opt_view_center_glyphs (OPT_ARGS_NUM)
Definition at line 8691 of file Options.cpp.
opt_view_clip()
double opt_view_clip (OPT_ARGS_NUM)
Definition at line 9068 of file Options.cpp.
opt_view_closed()
double opt_view_closed (OPT_ARGS_NUM)
Definition at line 9167 of file Options.cpp.
opt_view_color_axes()
unsigned int opt_view_color_axes (OPT_ARGS_COL)
Definition at line 10213 of file Options.cpp.
opt_view_color_background2d()
unsigned int opt_view_color_background2d (OPT_ARGS_COL)
Definition at line 10230 of file Options.cpp.
opt_view_color_hexahedra()
unsigned int opt_view_color_hexahedra (OPT_ARGS_COL)
Definition at line 10065 of file Options.cpp.
opt_view_color_lines()
unsigned int opt_view_color_lines (OPT_ARGS_COL)
Definition at line 9989 of file Options.cpp.
opt_view_color_normals()
unsigned int opt_view_color_normals (OPT_ARGS_COL)
Definition at line 10160 of file Options.cpp.
opt_view_color_points()
unsigned int opt_view_color_points (OPT_ARGS_COL)
Definition at line 9970 of file Options.cpp.
opt_view_color_prisms()
unsigned int opt_view_color_prisms (OPT_ARGS_COL)
Definition at line 10084 of file Options.cpp.
opt_view_color_pyramids()
unsigned int opt_view_color_pyramids (OPT_ARGS_COL)
Definition at line 10103 of file Options.cpp.
opt_view_color_quadrangles()
unsigned int opt_view_color_quadrangles (OPT_ARGS_COL)
Definition at line 10027 of file Options.cpp.
opt_view_color_tangents()
unsigned int opt_view_color_tangents (OPT_ARGS_COL)
Definition at line 10141 of file Options.cpp.
opt_view_color_tetrahedra()
unsigned int opt_view_color_tetrahedra (OPT_ARGS_COL)
Definition at line 10046 of file Options.cpp.
opt_view_color_text2d()
unsigned int opt_view_color_text2d (OPT_ARGS_COL)
Definition at line 10179 of file Options.cpp.
opt_view_color_text3d()
unsigned int opt_view_color_text3d (OPT_ARGS_COL)
Definition at line 10196 of file Options.cpp.
opt_view_color_triangles()
unsigned int opt_view_color_triangles (OPT_ARGS_COL)
Definition at line 10008 of file Options.cpp.
opt_view_color_trihedra()
unsigned int opt_view_color_trihedra (OPT_ARGS_COL)
Definition at line 10122 of file Options.cpp.
opt_view_colormap_alpha()
double opt_view_colormap_alpha (OPT_ARGS_NUM)
Definition at line 8781 of file Options.cpp.
opt_view_colormap_alpha_power()
double opt_view_colormap_alpha_power (OPT_ARGS_NUM)
Definition at line 8801 of file Options.cpp.
opt_view_colormap_beta()
double opt_view_colormap_beta (OPT_ARGS_NUM)
Definition at line 8821 of file Options.cpp.
opt_view_colormap_bias()
double opt_view_colormap_bias (OPT_ARGS_NUM)
Definition at line 8841 of file Options.cpp.
opt_view_colormap_curvature()
double opt_view_colormap_curvature (OPT_ARGS_NUM)
Definition at line 8861 of file Options.cpp.
opt_view_colormap_invert()
double opt_view_colormap_invert (OPT_ARGS_NUM)
Definition at line 8881 of file Options.cpp.
opt_view_colormap_number()
double opt_view_colormap_number (OPT_ARGS_NUM)
Definition at line 8901 of file Options.cpp.
opt_view_colormap_rotation()
double opt_view_colormap_rotation (OPT_ARGS_NUM)
Definition at line 8924 of file Options.cpp.
opt_view_colormap_swap()
double opt_view_colormap_swap (OPT_ARGS_NUM)
Definition at line 8944 of file Options.cpp.
opt_view_component_map0()
double opt_view_component_map0 (OPT_ARGS_NUM)
Definition at line 9130 of file Options.cpp.
opt_view_component_map1()
double opt_view_component_map1 (OPT_ARGS_NUM)
Definition at line 9134 of file Options.cpp.
opt_view_component_map2()
double opt_view_component_map2 (OPT_ARGS_NUM)
Definition at line 9138 of file Options.cpp.
opt_view_component_map3()
double opt_view_component_map3 (OPT_ARGS_NUM)
Definition at line 9142 of file Options.cpp.
opt_view_component_map4()
double opt_view_component_map4 (OPT_ARGS_NUM)
Definition at line 9146 of file Options.cpp.
opt_view_component_map5()
double opt_view_component_map5 (OPT_ARGS_NUM)
Definition at line 9150 of file Options.cpp.
opt_view_component_map6()
double opt_view_component_map6 (OPT_ARGS_NUM)
Definition at line 9154 of file Options.cpp.
opt_view_component_map7()
double opt_view_component_map7 (OPT_ARGS_NUM)
Definition at line 9158 of file Options.cpp.
opt_view_component_map8()
double opt_view_component_map8 (OPT_ARGS_NUM)
Definition at line 9162 of file Options.cpp.
opt_view_custom_abscissa_max()
double opt_view_custom_abscissa_max (OPT_ARGS_NUM)
Definition at line 7152 of file Options.cpp.
opt_view_custom_abscissa_min()
double opt_view_custom_abscissa_min (OPT_ARGS_NUM)
Definition at line 7138 of file Options.cpp.
opt_view_custom_max()
double opt_view_custom_max (OPT_ARGS_NUM)
Definition at line 7120 of file Options.cpp.
Referenced by assembleColbarStr().
opt_view_custom_min()
double opt_view_custom_min (OPT_ARGS_NUM)
Definition at line 7101 of file Options.cpp.
Referenced by assembleColbarStr().
opt_view_displacement_factor()
double opt_view_displacement_factor (OPT_ARGS_NUM)
Definition at line 7580 of file Options.cpp.
opt_view_double_clicked_command()
std::string opt_view_double_clicked_command (OPT_ARGS_STR)
Definition at line 1763 of file Options.cpp.
opt_view_draw_hexahedra()
double opt_view_draw_hexahedra (OPT_ARGS_NUM)
Definition at line 8388 of file Options.cpp.
opt_view_draw_lines()
double opt_view_draw_lines (OPT_ARGS_NUM)
Definition at line 8292 of file Options.cpp.
opt_view_draw_points()
double opt_view_draw_points (OPT_ARGS_NUM)
Definition at line 8268 of file Options.cpp.
opt_view_draw_prisms()
double opt_view_draw_prisms (OPT_ARGS_NUM)
Definition at line 8412 of file Options.cpp.
opt_view_draw_pyramids()
double opt_view_draw_pyramids (OPT_ARGS_NUM)
Definition at line 8436 of file Options.cpp.
opt_view_draw_quadrangles()
double opt_view_draw_quadrangles (OPT_ARGS_NUM)
Definition at line 8340 of file Options.cpp.
opt_view_draw_scalars()
double opt_view_draw_scalars (OPT_ARGS_NUM)
Definition at line 8484 of file Options.cpp.
opt_view_draw_skin_only()
double opt_view_draw_skin_only (OPT_ARGS_NUM)
Definition at line 8556 of file Options.cpp.
opt_view_draw_strings()
double opt_view_draw_strings (OPT_ARGS_NUM)
Definition at line 8253 of file Options.cpp.
opt_view_draw_tensors()
double opt_view_draw_tensors (OPT_ARGS_NUM)
Definition at line 8532 of file Options.cpp.
opt_view_draw_tetrahedra()
double opt_view_draw_tetrahedra (OPT_ARGS_NUM)
Definition at line 8364 of file Options.cpp.
opt_view_draw_triangles()
double opt_view_draw_triangles (OPT_ARGS_NUM)
Definition at line 8316 of file Options.cpp.
opt_view_draw_trihedra()
double opt_view_draw_trihedra (OPT_ARGS_NUM)
Definition at line 8460 of file Options.cpp.
opt_view_draw_vectors()
double opt_view_draw_vectors (OPT_ARGS_NUM)
Definition at line 8508 of file Options.cpp.
opt_view_explode()
double opt_view_explode (OPT_ARGS_NUM)
Definition at line 7616 of file Options.cpp.
opt_view_external_view()
double opt_view_external_view (OPT_ARGS_NUM)
Definition at line 8964 of file Options.cpp.
opt_view_fake_transparency()
double opt_view_fake_transparency (OPT_ARGS_NUM)
Definition at line 7598 of file Options.cpp.
opt_view_filename()
std::string opt_view_filename (OPT_ARGS_STR)
Definition at line 1785 of file Options.cpp.
opt_view_force_num_components()
double opt_view_force_num_components (OPT_ARGS_NUM)
Definition at line 9084 of file Options.cpp.
opt_view_format()
std::string opt_view_format (OPT_ARGS_STR)
Definition at line 1748 of file Options.cpp.
opt_view_gen_raise0()
std::string opt_view_gen_raise0 (OPT_ARGS_STR)
Definition at line 1892 of file Options.cpp.
opt_view_gen_raise1()
std::string opt_view_gen_raise1 (OPT_ARGS_STR)
Definition at line 1910 of file Options.cpp.
opt_view_gen_raise2()
std::string opt_view_gen_raise2 (OPT_ARGS_STR)
Definition at line 1928 of file Options.cpp.
opt_view_gen_raise_factor()
double opt_view_gen_raise_factor (OPT_ARGS_NUM)
Definition at line 9014 of file Options.cpp.
opt_view_gen_raise_view()
double opt_view_gen_raise_view (OPT_ARGS_NUM)
Definition at line 8989 of file Options.cpp.
opt_view_glyph_location()
double opt_view_glyph_location (OPT_ARGS_NUM)
Definition at line 8671 of file Options.cpp.
opt_view_group()
std::string opt_view_group (OPT_ARGS_STR)
Definition at line 1774 of file Options.cpp.
opt_view_intervals_type()
double opt_view_intervals_type (OPT_ARGS_NUM)
Definition at line 7650 of file Options.cpp.
Referenced by print_pgf().
opt_view_light()
double opt_view_light (OPT_ARGS_NUM)
Definition at line 8116 of file Options.cpp.
opt_view_light_lines()
double opt_view_light_lines (OPT_ARGS_NUM)
Definition at line 8151 of file Options.cpp.
opt_view_light_two_side()
double opt_view_light_two_side (OPT_ARGS_NUM)
Definition at line 8136 of file Options.cpp.
opt_view_line_type()
double opt_view_line_type (OPT_ARGS_NUM)
Definition at line 8761 of file Options.cpp.
opt_view_line_width()
double opt_view_line_width (OPT_ARGS_NUM)
Definition at line 8726 of file Options.cpp.
opt_view_max()
double opt_view_max (OPT_ARGS_NUM)
Definition at line 7059 of file Options.cpp.
Referenced by assembleColbarStr().
opt_view_max_recursion_level()
double opt_view_max_recursion_level (OPT_ARGS_NUM)
Definition at line 7717 of file Options.cpp.
opt_view_max_visible()
double opt_view_max_visible (OPT_ARGS_NUM)
Definition at line 7086 of file Options.cpp.
opt_view_min()
double opt_view_min (OPT_ARGS_NUM)
Definition at line 7047 of file Options.cpp.
Referenced by assembleColbarStr().
opt_view_min_visible()
double opt_view_min_visible (OPT_ARGS_NUM)
Definition at line 7071 of file Options.cpp.
opt_view_name()
std::string opt_view_name (OPT_ARGS_STR)
Definition at line 1715 of file Options.cpp.
opt_view_nb_iso()
double opt_view_nb_iso (OPT_ARGS_NUM)
Definition at line 8078 of file Options.cpp.
Referenced by assembleColmapStr().
opt_view_nb_non_empty_timestep()
double opt_view_nb_non_empty_timestep (OPT_ARGS_NUM)
Definition at line 6979 of file Options.cpp.
Referenced by CreateOutputFile().
opt_view_nb_timestep()
double opt_view_nb_timestep (OPT_ARGS_NUM)
Definition at line 6960 of file Options.cpp.
Referenced by MergePostProcessingFile().
opt_view_normal_raise()
double opt_view_normal_raise (OPT_ARGS_NUM)
Definition at line 7340 of file Options.cpp.
opt_view_normals()
double opt_view_normals (OPT_ARGS_NUM)
Definition at line 7550 of file Options.cpp.
opt_view_offset0()
double opt_view_offset0 (OPT_ARGS_NUM)
Definition at line 7232 of file Options.cpp.
opt_view_offset1()
double opt_view_offset1 (OPT_ARGS_NUM)
Definition at line 7250 of file Options.cpp.
opt_view_offset2()
double opt_view_offset2 (OPT_ARGS_NUM)
Definition at line 7268 of file Options.cpp.
opt_view_point_size()
double opt_view_point_size (OPT_ARGS_NUM)
Definition at line 8711 of file Options.cpp.
opt_view_point_type()
double opt_view_point_type (OPT_ARGS_NUM)
Definition at line 8741 of file Options.cpp.
opt_view_position0()
double opt_view_position0 (OPT_ARGS_NUM)
Definition at line 7803 of file Options.cpp.
opt_view_position1()
double opt_view_position1 (OPT_ARGS_NUM)
Definition at line 7818 of file Options.cpp.
opt_view_raise0()
double opt_view_raise0 (OPT_ARGS_NUM)
Definition at line 7286 of file Options.cpp.
opt_view_raise1()
double opt_view_raise1 (OPT_ARGS_NUM)
Definition at line 7304 of file Options.cpp.
opt_view_raise2()
double opt_view_raise2 (OPT_ARGS_NUM)
Definition at line 7322 of file Options.cpp.
opt_view_range_type()
double opt_view_range_type (OPT_ARGS_NUM)
Definition at line 8594 of file Options.cpp.
Referenced by assembleColbarStr().
opt_view_sampling()
double opt_view_sampling (OPT_ARGS_NUM)
Definition at line 7833 of file Options.cpp.
opt_view_saturate_values()
double opt_view_saturate_values (OPT_ARGS_NUM)
Definition at line 7670 of file Options.cpp.
opt_view_scale_type()
double opt_view_scale_type (OPT_ARGS_NUM)
Definition at line 8574 of file Options.cpp.
Referenced by assembleColbarStr().
opt_view_show_element()
double opt_view_show_element (OPT_ARGS_NUM)
Definition at line 8202 of file Options.cpp.
opt_view_show_scale()
double opt_view_show_scale (OPT_ARGS_NUM)
Definition at line 8238 of file Options.cpp.
Referenced by CreateOutputFile().
opt_view_show_time()
double opt_view_show_time (OPT_ARGS_NUM)
Definition at line 8220 of file Options.cpp.
opt_view_size0()
double opt_view_size0 (OPT_ARGS_NUM)
Definition at line 7851 of file Options.cpp.
opt_view_size1()
double opt_view_size1 (OPT_ARGS_NUM)
Definition at line 7866 of file Options.cpp.
opt_view_smooth_normals()
double opt_view_smooth_normals (OPT_ARGS_NUM)
Definition at line 8166 of file Options.cpp.
opt_view_stipple0()
std::string opt_view_stipple0 (OPT_ARGS_STR)
Definition at line 1988 of file Options.cpp.
opt_view_stipple1()
std::string opt_view_stipple1 (OPT_ARGS_STR)
Definition at line 2003 of file Options.cpp.
opt_view_stipple2()
std::string opt_view_stipple2 (OPT_ARGS_STR)
Definition at line 2018 of file Options.cpp.
opt_view_stipple3()
std::string opt_view_stipple3 (OPT_ARGS_STR)
Definition at line 2033 of file Options.cpp.
opt_view_stipple4()
std::string opt_view_stipple4 (OPT_ARGS_STR)
Definition at line 2048 of file Options.cpp.
opt_view_stipple5()
std::string opt_view_stipple5 (OPT_ARGS_STR)
Definition at line 2063 of file Options.cpp.
opt_view_stipple6()
std::string opt_view_stipple6 (OPT_ARGS_STR)
Definition at line 2078 of file Options.cpp.
opt_view_stipple7()
std::string opt_view_stipple7 (OPT_ARGS_STR)
Definition at line 2093 of file Options.cpp.
opt_view_stipple8()
std::string opt_view_stipple8 (OPT_ARGS_STR)
Definition at line 2108 of file Options.cpp.
opt_view_stipple9()
std::string opt_view_stipple9 (OPT_ARGS_STR)
Definition at line 2123 of file Options.cpp.
opt_view_tangents()
double opt_view_tangents (OPT_ARGS_NUM)
Definition at line 7565 of file Options.cpp.
opt_view_target_error()
double opt_view_target_error (OPT_ARGS_NUM)
Definition at line 7740 of file Options.cpp.
opt_view_tensor_type()
double opt_view_tensor_type (OPT_ARGS_NUM)
Definition at line 8631 of file Options.cpp.
opt_view_time()
double opt_view_time (OPT_ARGS_NUM)
Definition at line 7021 of file Options.cpp.
opt_view_timestep()
double opt_view_timestep (OPT_ARGS_NUM)
Definition at line 6993 of file Options.cpp.
Referenced by MergeFile(), MergePostProcessingFile(), and opt_view_time().
opt_view_transform00()
double opt_view_transform00 (OPT_ARGS_NUM)
Definition at line 7358 of file Options.cpp.
opt_view_transform01()
double opt_view_transform01 (OPT_ARGS_NUM)
Definition at line 7376 of file Options.cpp.
opt_view_transform02()
double opt_view_transform02 (OPT_ARGS_NUM)
Definition at line 7394 of file Options.cpp.
opt_view_transform10()
double opt_view_transform10 (OPT_ARGS_NUM)
Definition at line 7412 of file Options.cpp.
opt_view_transform11()
double opt_view_transform11 (OPT_ARGS_NUM)
Definition at line 7430 of file Options.cpp.
opt_view_transform12()
double opt_view_transform12 (OPT_ARGS_NUM)
Definition at line 7448 of file Options.cpp.
opt_view_transform20()
double opt_view_transform20 (OPT_ARGS_NUM)
Definition at line 7466 of file Options.cpp.
opt_view_transform21()
double opt_view_transform21 (OPT_ARGS_NUM)
Definition at line 7484 of file Options.cpp.
opt_view_transform22()
double opt_view_transform22 (OPT_ARGS_NUM)
Definition at line 7502 of file Options.cpp.
opt_view_type()
double opt_view_type (OPT_ARGS_NUM)
Definition at line 7763 of file Options.cpp.
opt_view_use_gen_raise()
double opt_view_use_gen_raise (OPT_ARGS_NUM)
Definition at line 9032 of file Options.cpp.
opt_view_use_stipple()
double opt_view_use_stipple (OPT_ARGS_NUM)
Definition at line 9052 of file Options.cpp.
opt_view_vector_type()
double opt_view_vector_type (OPT_ARGS_NUM)
Definition at line 8651 of file Options.cpp.
opt_view_visible()
double opt_view_visible (OPT_ARGS_NUM)
Definition at line 7634 of file Options.cpp.
Referenced by CreateOutputFile(), GetOtherOption(), and GetPostProcessingOption().
opt_view_xmax()
double opt_view_xmax (OPT_ARGS_NUM)
Definition at line 7177 of file Options.cpp.
opt_view_xmin()
double opt_view_xmin (OPT_ARGS_NUM)
Definition at line 7166 of file Options.cpp.
opt_view_ymax()
double opt_view_ymax (OPT_ARGS_NUM)
Definition at line 7199 of file Options.cpp.
opt_view_ymin()
double opt_view_ymin (OPT_ARGS_NUM)
Definition at line 7188 of file Options.cpp.
opt_view_zmax()
double opt_view_zmax (OPT_ARGS_NUM)
Definition at line 7221 of file Options.cpp.
opt_view_zmin()
double opt_view_zmin (OPT_ARGS_NUM)
Definition at line 7210 of file Options.cpp.
PrintOptions()
void PrintOptions (int num, int level, int diff, int help, const char * filename, std::vector< std::string > * vec = nullptr)
Definition at line 636 of file Options.cpp.
Referenced by CreateOutputFile(), GetOtherOption(), and initPView::operator()().
PrintOptionsDoc()
void PrintOptionsDoc ()
Definition at line 793 of file Options.cpp.
Referenced by GmshMainFLTK().
ReInitOptions()
void ReInitOptions (int num)
Definition at line 504 of file Options.cpp.
Referenced by GmshRestoreDefaultOptions().
StringOption()
bool StringOption (int action, const char * category, int num, const char * name, std::string & val, bool warnIfUnknown = true)
Definition at line 63 of file Options.cpp.
Referenced by GmshGetOption(), GmshGetStringOption(), GmshSetOption(), GmshSetStringOption(), and treat_Struct_FullName_dot_tSTRING_String().