gmsh-TingyuanDoc: src/post/PViewX3D.cpp File Reference
PViewX3D.cpp File Reference
#include <iostream>
#include <limits>
#include <ctime>
#include <math.h>
#include "GmshConfig.h"
#include "GmshMessage.h"
#include "PView.h"
#include "PViewData.h"
#include "PViewOptions.h"
#include "PViewDataList.h"
#include "PViewDataGModel.h"
#include "VertexArray.h"
#include "StringUtils.h"
#include "Context.h"
#include "OS.h"
#include "SBoundingBox3d.h"
#include "PViewX3D.h"
Functions
static bool almostEqual (double x, double y)
bool compare_xmin_triangle (const TriangleToSort *first, const TriangleToSort *second)
bool compare_ymin_triangle (const TriangleToSort *first, const TriangleToSort *second)
bool compare_zmin_triangle (const TriangleToSort *first, const TriangleToSort *second)
bool compare_xmax_triangle (const TriangleToSort *first, const TriangleToSort *second)
bool compare_ymax_triangle (const TriangleToSort *first, const TriangleToSort *second)
bool compare_zmax_triangle (const TriangleToSort *first, const TriangleToSort *second)
static void writeX3DScale (FILE *fp, PView *p, double xmin, double ymin, double width, double height, double tic, int horizontal, double font_size)
static void writeX3DScaleBar (FILE *fp, PView *p, double xmin, double ymin, double width, double height, double tic, int horizontal)
static void writeX3DScaleValues (FILE *fp, PView *p, double xmin, double ymin, double width, double height, double tic, int horizontal, double font_size)
static void writeX3DScaleLabel (FILE *fp, PView *p, double xmin, double ymin, double width, double height, double tic, int horizontal, double font_size)
static void writeX3DStringCenter (FILE *fp, char *label, double x, double y, double z, double font_size)
Function Documentation
almostEqual()
static bool almostEqual (double x, double y) static
Definition at line 31 of file PViewX3D.cpp.
Referenced by PView::writeX3D().
compare_xmax_triangle()
bool compare_xmax_triangle (const TriangleToSort * first, const TriangleToSort * second)
Definition at line 54 of file PViewX3D.cpp.
Referenced by PView::writeX3D().
compare_xmin_triangle()
bool compare_xmin_triangle (const TriangleToSort * first, const TriangleToSort * second)
Definition at line 36 of file PViewX3D.cpp.
Referenced by PView::writeX3D().
compare_ymax_triangle()
bool compare_ymax_triangle (const TriangleToSort * first, const TriangleToSort * second)
Definition at line 60 of file PViewX3D.cpp.
Referenced by PView::writeX3D().
compare_ymin_triangle()
bool compare_ymin_triangle (const TriangleToSort * first, const TriangleToSort * second)
Definition at line 42 of file PViewX3D.cpp.
Referenced by PView::writeX3D().
compare_zmax_triangle()
bool compare_zmax_triangle (const TriangleToSort * first, const TriangleToSort * second)
Definition at line 66 of file PViewX3D.cpp.
Referenced by PView::writeX3D().
compare_zmin_triangle()
bool compare_zmin_triangle (const TriangleToSort * first, const TriangleToSort * second)
Definition at line 48 of file PViewX3D.cpp.
Referenced by PView::writeX3D().
writeX3DScale()
static void writeX3DScale (FILE * fp, PView * p, double xmin, double ymin, double width, double height, double tic, int horizontal, double font_size) static
Definition at line 635 of file PViewX3D.cpp.
Referenced by PView::writeX3D().
writeX3DScaleBar()
static void writeX3DScaleBar (FILE * fp, PView * p, double xmin, double ymin, double width, double height, double tic, int horizontal) static
Definition at line 667 of file PViewX3D.cpp.
Referenced by writeX3DScale().
writeX3DScaleLabel()
static void writeX3DScaleLabel (FILE * fp, PView * p, double xmin, double ymin, double width, double height, double tic, int horizontal, double font_size) static
Definition at line 827 of file PViewX3D.cpp.
Referenced by writeX3DScale().
writeX3DScaleValues()
static void writeX3DScaleValues (FILE * fp, PView * p, double xmin, double ymin, double width, double height, double tic, int horizontal, double font_size) static
Definition at line 751 of file PViewX3D.cpp.
Referenced by writeX3DScale().
writeX3DStringCenter()
static void writeX3DStringCenter (FILE * fp, char * label, double x, double y, double z, double font_size) static
Definition at line 864 of file PViewX3D.cpp.
Referenced by writeX3DScaleLabel(), and writeX3DScaleValues().