gmsh-TingyuanDoc: src/post/PViewVertexArrays.cpp File Reference
PViewVertexArrays.cpp File Reference
#include <string.h>
#include <algorithm>
#include "GmshMessage.h"
#include "GmshDefines.h"
#include "onelab.h"
#include "Iso.h"
#include "MEdge.h"
#include "MFace.h"
#include "PView.h"
#include "PViewOptions.h"
#include "PViewData.h"
#include "PViewDataRemote.h"
#include "Numeric.h"
#include "VertexArray.h"
#include "SmoothData.h"
#include "Context.h"
#include "OpenFile.h"
#include "mathEvaluator.h"
#include "Options.h"
#include "StringUtils.h"
#include "fullMatrix.h"
Classes
class initPView
Functions
static void saturate (int nb, double **val, double vmin, double vmax, int i0=0, int i1=1, int i2=2, int i3=3, int i4=4, int i5=5, int i6=6, int i7=7)
static double saturateVector (double *val, int numComp2, double *val2, double min, double max)
static SVector3 normal3 (double **xyz, int i0=0, int i1=1, int i2=2)
static SVector3 getPointNormal (PView *p, double v)
static void getLineNormal (PView *p, double x[2], double y[2], double z[2], double *v, SVector3 n[2], bool computeNormal)
static bool getExternalValues (PView *p, int index, int ient, int iele, int numNodes, int numComp, double **val, int &numComp2, double **val2)
static void applyGeneralRaise (PView *p, int numNodes, int numComp, double **vals, double **xyz)
void changeCoordinates (PView *p, int ient, int iele, int numNodes, int type, int numComp, double **xyz, double **val)
static double evalClipPlane (int clip, double x, double y, double z)
static double intersectClipPlane (int clip, int numNodes, double **xyz)
bool isElementVisible (PViewOptions *opt, int dim, int numNodes, double **xyz)
static void addOutlinePoint (PView *p, double **xyz, unsigned int color, bool pre, int i0=0)
static void addScalarPoint (PView *p, double **xyz, double **val, bool pre, int i0=0, bool unique=false)
static void addOutlineLine (PView *p, double **xyz, unsigned int color, bool pre, int i0=0, int i1=1)
static void addScalarLine (PView *p, double **xyz, double **val, bool pre, int i0=0, int i1=1, bool unique=false)
static void addOutlineTriangle (PView *p, double **xyz, unsigned int color, bool pre, int i0=0, int i1=1, int i2=2)
static void addScalarTriangle (PView *p, double **xyz, double **val, bool pre, int i0=0, int i1=1, int i2=2, bool unique=false, bool skin=false)
static void addOutlineQuadrangle (PView *p, double **xyz, unsigned int color, bool pre, int i0=0, int i1=1, int i2=2, int i3=3)
static void addScalarQuadrangle (PView *p, double **xyz, double **val, bool pre, int i0=0, int i1=1, int i2=2, int i3=3, bool unique=false)
static void addOutlinePolygon (PView *p, double **xyz, unsigned int color, bool pre, int numNodes)
static void addScalarPolygon (PView *p, double **xyz, double **val, bool pre, int numNodes)
static void addOutlineTetrahedron (PView *p, double **xyz, unsigned int color, bool pre)
static void addScalarTetrahedron (PView *p, double **xyz, double **val, bool pre, int i0=0, int i1=1, int i2=2, int i3=3)
static void addOutlineHexahedron (PView *p, double **xyz, unsigned int color, bool pre)
static void addScalarHexahedron (PView *p, double **xyz, double **val, bool pre)
static void addOutlinePrism (PView *p, double **xyz, unsigned int color, bool pre)
static void addScalarPrism (PView *p, double **xyz, double **val, bool pre)
static void addOutlinePyramid (PView *p, double **xyz, unsigned int color, bool pre)
static void addScalarPyramid (PView *p, double **xyz, double **val, bool pre)
static void addOutlineTrihedron (PView *p, double **xyz, unsigned int color, bool pre)
static void addScalarTrihedron (PView *p, double **xyz, double **val, bool pre, int i0=0, int i1=1, int i2=2, int i3=3, bool unique=false)
static void addOutlinePolyhedron (PView *p, double **xyz, unsigned int color, bool pre, int numNodes)
static void addScalarPolyhedron (PView *p, double **xyz, double **val, bool pre, int numNodes)
static void addOutlineElement (PView *p, int type, double **xyz, bool pre, int numNodes)
static void addScalarElement (PView *p, int type, double **xyz, double **val, bool pre, int numNodes)
static void addVectorElement (PView *p, int ient, int iele, int numNodes, int type, double **xyz, double **val, bool pre)
static void addTriangle (PView *p, PViewOptions *opt, double *x0, double *x1, double *x2, SPoint3 &xx, double val)
static void addTensorElement (PView *p, int iEnt, int iEle, int numNodes, int type, double **xyz, double **val, bool pre)
static void addElementsInArrays (PView *p, bool preprocessNormalsOnly)
Function Documentation
addElementsInArrays()
static void addElementsInArrays (PView * p, bool preprocessNormalsOnly) static
Definition at line 1283 of file PViewVertexArrays.cpp.
Referenced by initPView::operator()().
addOutlineElement()
static void addOutlineElement (PView * p, int type, double ** xyz, bool pre, int numNodes) static
Definition at line 922 of file PViewVertexArrays.cpp.
Referenced by addElementsInArrays().
addOutlineHexahedron()
static void addOutlineHexahedron (PView * p, double ** xyz, unsigned int color, bool pre) static
Definition at line 763 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement().
addOutlineLine()
static void addOutlineLine (PView * p, double ** xyz, unsigned int color, bool pre, int i0 = 0, int i1 = 1) static
Definition at line 344 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement().
addOutlinePoint()
static void addOutlinePoint (PView * p, double ** xyz, unsigned int color, bool pre, int i0 = 0) static
Definition at line 315 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement().
addOutlinePolygon()
static void addOutlinePolygon (PView * p, double ** xyz, unsigned int color, bool pre, int numNodes) static
Definition at line 645 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement().
addOutlinePolyhedron()
static void addOutlinePolyhedron (PView * p, double ** xyz, unsigned int color, bool pre, int numNodes) static
Definition at line 877 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement().
addOutlinePrism()
static void addOutlinePrism (PView * p, double ** xyz, unsigned int color, bool pre) static
Definition at line 797 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement().
addOutlinePyramid()
static void addOutlinePyramid (PView * p, double ** xyz, unsigned int color, bool pre) static
Definition at line 833 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement().
addOutlineQuadrangle()
static void addOutlineQuadrangle (PView * p, double ** xyz, unsigned int color, bool pre, int i0 = 0, int i1 = 1, int i2 = 2, int i3 = 3) static
Definition at line 595 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement(), addOutlineHexahedron(), addOutlinePrism(), addOutlinePyramid(), and addOutlineTrihedron().
addOutlineTetrahedron()
static void addOutlineTetrahedron (PView * p, double ** xyz, unsigned int color, bool pre) static
Definition at line 695 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement().
addOutlineTriangle()
static void addOutlineTriangle (PView * p, double ** xyz, unsigned int color, bool pre, int i0 = 0, int i1 = 1, int i2 = 2) static
Definition at line 440 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement(), addOutlinePolygon(), addOutlinePolyhedron(), addOutlinePrism(), addOutlinePyramid(), and addOutlineTetrahedron().
addOutlineTrihedron()
static void addOutlineTrihedron (PView * p, double ** xyz, unsigned int color, bool pre) static
Definition at line 864 of file PViewVertexArrays.cpp.
Referenced by addOutlineElement().
addScalarElement()
static void addScalarElement (PView * p, int type, double ** xyz, double ** val, bool pre, int numNodes) static
Definition at line 951 of file PViewVertexArrays.cpp.
Referenced by addElementsInArrays(), addTensorElement(), and addVectorElement().
addScalarHexahedron()
static void addScalarHexahedron (PView * p, double ** xyz, double ** val, bool pre) static
Definition at line 774 of file PViewVertexArrays.cpp.
Referenced by addScalarElement().
addScalarLine()
static void addScalarLine (PView * p, double ** xyz, double ** val, bool pre, int i0 = 0, int i1 = 1, bool unique = false) static
Definition at line 363 of file PViewVertexArrays.cpp.
Referenced by addScalarElement(), addScalarPolygon(), addScalarQuadrangle(), and addScalarTriangle().
addScalarPoint()
static void addScalarPoint (PView * p, double ** xyz, double ** val, bool pre, int i0 = 0, bool unique = false) static
Definition at line 324 of file PViewVertexArrays.cpp.
Referenced by addScalarElement(), and addScalarLine().
addScalarPolygon()
static void addScalarPolygon (PView * p, double ** xyz, double ** val, bool pre, int numNodes) static
Definition at line 652 of file PViewVertexArrays.cpp.
Referenced by addScalarElement().
addScalarPolyhedron()
static void addScalarPolyhedron (PView * p, double ** xyz, double ** val, bool pre, int numNodes) static
Definition at line 910 of file PViewVertexArrays.cpp.
Referenced by addScalarElement().
addScalarPrism()
static void addScalarPrism (PView * p, double ** xyz, double ** val, bool pre) static
Definition at line 810 of file PViewVertexArrays.cpp.
Referenced by addScalarElement().
addScalarPyramid()
static void addScalarPyramid (PView * p, double ** xyz, double ** val, bool pre) static
Definition at line 843 of file PViewVertexArrays.cpp.
Referenced by addScalarElement().
addScalarQuadrangle()
static void addScalarQuadrangle (PView * p, double ** xyz, double ** val, bool pre, int i0 = 0, int i1 = 1, int i2 = 2, int i3 = 3, bool unique = false) static
Definition at line 624 of file PViewVertexArrays.cpp.
Referenced by addScalarElement(), addScalarHexahedron(), addScalarPrism(), addScalarPyramid(), and addScalarTrihedron().
addScalarTetrahedron()
static void addScalarTetrahedron (PView * p, double ** xyz, double ** val, bool pre, int i0 = 0, int i1 = 1, int i2 = 2, int i3 = 3) static
Definition at line 703 of file PViewVertexArrays.cpp.
Referenced by addScalarElement(), addScalarHexahedron(), addScalarPolyhedron(), addScalarPrism(), and addScalarPyramid().
addScalarTriangle()
static void addScalarTriangle (PView * p, double ** xyz, double ** val, bool pre, int i0 = 0, int i1 = 1, int i2 = 2, bool unique = false, bool skin = false) static
Definition at line 468 of file PViewVertexArrays.cpp.
Referenced by addScalarElement(), addScalarPolygon(), addScalarPrism(), addScalarPyramid(), addScalarQuadrangle(), and addScalarTetrahedron().
addScalarTrihedron()
static void addScalarTrihedron (PView * p, double ** xyz, double ** val, bool pre, int i0 = 0, int i1 = 1, int i2 = 2, int i3 = 3, bool unique = false) static
Definition at line 870 of file PViewVertexArrays.cpp.
Referenced by addScalarElement().
addTensorElement()
static void addTensorElement (PView * p, int iEnt, int iEle, int numNodes, int type, double ** xyz, double ** val, bool pre) static
Definition at line 1127 of file PViewVertexArrays.cpp.
Referenced by addElementsInArrays().
addTriangle()
static void addTriangle (PView * p, PViewOptions * opt, double * x0, double * x1, double * x2, SPoint3 & xx, double val) static
Definition at line 1098 of file PViewVertexArrays.cpp.
Referenced by addTensorElement().
addVectorElement()
static void addVectorElement (PView * p, int ient, int iele, int numNodes, int type, double ** xyz, double ** val, bool pre) static
Definition at line 969 of file PViewVertexArrays.cpp.
Referenced by addElementsInArrays(), and addTensorElement().
applyGeneralRaise()
static void applyGeneralRaise (PView * p, int numNodes, int numComp, double ** vals, double ** xyz) static
Definition at line 176 of file PViewVertexArrays.cpp.
Referenced by changeCoordinates().
changeCoordinates()
void changeCoordinates (PView * p, int ient, int iele, int numNodes, int type, int numComp, double ** xyz, double ** val)
Definition at line 193 of file PViewVertexArrays.cpp.
Referenced by addElementsInArrays(), and drawGlyphs().
evalClipPlane()
static double evalClipPlane (int clip, double x, double y, double z) static
Definition at line 274 of file PViewVertexArrays.cpp.
Referenced by intersectClipPlane().
getExternalValues()
static bool getExternalValues (PView * p, int index, int ient, int iele, int numNodes, int numComp, double ** val, int & numComp2, double ** val2) static
Definition at line 133 of file PViewVertexArrays.cpp.
Referenced by addVectorElement(), and changeCoordinates().
getLineNormal()
static void getLineNormal (PView * p, double x[2], double y[2], double z[2], double * v, SVector3 n[2], bool computeNormal) static
Definition at line 89 of file PViewVertexArrays.cpp.
Referenced by addOutlineLine(), addOutlineQuadrangle(), addOutlineTriangle(), addScalarLine(), addScalarTriangle(), and addVectorElement().
getPointNormal()
static SVector3 getPointNormal (PView * p, double v) static
Definition at line 75 of file PViewVertexArrays.cpp.
Referenced by addOutlinePoint(), addScalarLine(), and addScalarPoint().
intersectClipPlane()
static double intersectClipPlane (int clip, int numNodes, double ** xyz) static
Definition at line 282 of file PViewVertexArrays.cpp.
Referenced by isElementVisible().
isElementVisible()
bool isElementVisible (PViewOptions * opt, int dim, int numNodes, double ** xyz)
Definition at line 292 of file PViewVertexArrays.cpp.
Referenced by addElementsInArrays().
normal3()
static SVector3 normal3 (double ** xyz, int i0 = 0, int i1 = 1, int i2 = 2) static
Definition at line 64 of file PViewVertexArrays.cpp.
Referenced by addOutlineQuadrangle(), addOutlineTriangle(), addScalarTriangle(), and changeCoordinates().
saturate()
static void saturate (int nb, double ** val, double vmin, double vmax, int i0 = 0, int i1 = 1, int i2 = 2, int i3 = 3, int i4 = 4, int i5 = 5, int i6 = 6, int i7 = 7) static
Definition at line 28 of file PViewVertexArrays.cpp.
Referenced by addScalarLine(), addScalarPoint(), addScalarTetrahedron(), and addScalarTriangle().
saturateVector()
static double saturateVector (double * val, int numComp2, double * val2, double min, double max) static
Definition at line 41 of file PViewVertexArrays.cpp.
Referenced by addVectorElement().