gmsh-TingyuanDoc: src/post/PView.h File Reference
PView.h File Reference
#include <vector>
#include <map>
#include <string>
#include "MVertex.h"
#include "MElement.h"
#include "SPoint3.h"
Classes
class PView
class nameData
Namespaces
onelab
Macros
#define PVIEW_NMAX 8
Functions
void changeCoordinates (PView *p, int ient, int iele, int numNodes, int type, int numComp, double **xyz, double **val)
bool isElementVisible (PViewOptions *opt, int dim, int numNodes, double **xyz)
Macro Definition Documentation
PVIEW_NMAX
#define PVIEW_NMAX 8
Definition at line 180 of file PView.h.
Function Documentation
changeCoordinates()
void changeCoordinates (PView * p, int ient, int iele, int numNodes, int type, int numComp, double ** xyz, double ** val)
Definition at line 193 of file PViewVertexArrays.cpp.
Referenced by addElementsInArrays(), and drawGlyphs().
isElementVisible()
bool isElementVisible (PViewOptions * opt, int dim, int numNodes, double ** xyz)
Definition at line 292 of file PViewVertexArrays.cpp.
Referenced by addElementsInArrays().