gmsh-TingyuanDoc: src/post/PViewDataListIO.cpp File Reference
PViewDataListIO.cpp File Reference
#include <string.h>
#include <set>
#include "PViewDataList.h"
#include "MElement.h"
#include "Numeric.h"
#include "StringUtils.h"
#include "GmshMessage.h"
#include "GmshDefines.h"
#include "MVertexRTree.h"
#include "Context.h"
#include "adaptiveData.h"
#include "OS.h"
Classes
class nodeData
Functions
static void dVecRead (std::vector< double > &v, int n, FILE *fp, bool binary, int swap)
static void cVecRead (std::vector< char > &v, int n, FILE *fp, bool binary, int swap, bool oldStyle)
static void dVecWrite (std::vector< double > &v, FILE *fp, bool binary)
static void cVecWrite (std::vector< char > &v, FILE *fp, bool binary)
static void writeTimePOS (FILE *fp, std::vector< double > &list)
static void writeElementPOS (FILE *fp, const char *str, int nbnod, int nb, std::vector< double > &list)
static void writeTextPOS (FILE *fp, int nbc, int nb, std::vector< double > &TD, std::vector< char > &TC)
static void createVertices (std::vector< double > &list, int nbelm, int nbnod, std::vector< MVertex * > &nodes)
static void createElements (std::vector< double > &list, int nbelm, int nbnod, MVertexRTree &pos, std::vector< MElement * > &elements, int type, std::map< MVertex *, nodeData > *vertexData)
Function Documentation
createElements()
static void createElements (std::vector< double > & list, int nbelm, int nbnod, MVertexRTree & pos, std::vector< MElement * > & elements, int type, std::map< MVertex *, nodeData > * vertexData) static
Definition at line 553 of file PViewDataListIO.cpp.
Referenced by PViewDataList::writeMSH().
createVertices()
static void createVertices (std::vector< double > & list, int nbelm, int nbnod, std::vector< MVertex * > & nodes) static
Definition at line 527 of file PViewDataListIO.cpp.
Referenced by PViewDataList::writeMSH().
cVecRead()
static void cVecRead (std::vector< char > & v, int n, FILE * fp, bool binary, int swap, bool oldStyle) static
Definition at line 38 of file PViewDataListIO.cpp.
Referenced by PViewDataList::readPOS().
cVecWrite()
static void cVecWrite (std::vector< char > & v, FILE * fp, bool binary) static
Definition at line 81 of file PViewDataListIO.cpp.
Referenced by PViewDataList::writePOS().
dVecRead()
static void dVecRead (std::vector< double > & v, int n, FILE * fp, bool binary, int swap) static
Definition at line 19 of file PViewDataListIO.cpp.
Referenced by PViewDataList::readPOS().
dVecWrite()
static void dVecWrite (std::vector< double > & v, FILE * fp, bool binary) static
Definition at line 72 of file PViewDataListIO.cpp.
Referenced by PViewDataList::writePOS().
writeElementPOS()
static void writeElementPOS (FILE * fp, const char * str, int nbnod, int nb, std::vector< double > & list) static
Definition at line 349 of file PViewDataListIO.cpp.
Referenced by PViewDataList::writePOS().
writeTextPOS()
static void writeTextPOS (FILE * fp, int nbc, int nb, std::vector< double > & TD, std::vector< char > & TC) static
Definition at line 373 of file PViewDataListIO.cpp.
Referenced by PViewDataList::writePOS().
writeTimePOS()
static void writeTimePOS (FILE * fp, std::vector< double > & list) static
Definition at line 337 of file PViewDataListIO.cpp.
Referenced by PViewDataList::writePOS().