gmsh-TingyuanDoc: src/post/PViewDataList.cpp File Reference
PViewDataList.cpp File Reference
#include <algorithm>
#include "PView.h"
#include "PViewDataList.h"
#include "GmshMessage.h"
#include "GmshDefines.h"
#include "BasisFactory.h"
#include "Numeric.h"
#include "SmoothData.h"
#include "Context.h"
#include "polynomialBasis.h"
Functions
static void generateConnectivities (std::vector< double > &list, int nbList, int nbTimeStep, int nbVert, int nbComp, smooth_data &data)
static void smoothList (std::vector< double > &list, int nbList, int nbTimeStep, int nbVert, int nbComp, smooth_data &data)
static void dVecMerge (std::vector< double > &v, std::vector< double > &dest)
Function Documentation
dVecMerge()
static void dVecMerge (std::vector< double > & v, std::vector< double > & dest) static
Definition at line 693 of file PViewDataList.cpp.
Referenced by PViewDataList::combineSpace(), and PViewDataList::combineTime().
generateConnectivities()
static void generateConnectivities (std::vector< double > & list, int nbList, int nbTimeStep, int nbVert, int nbComp, smooth_data & data) static
Definition at line 610 of file PViewDataList.cpp.
Referenced by PViewDataList::smooth().
smoothList()
static void smoothList (std::vector< double > & list, int nbList, int nbTimeStep, int nbVert, int nbComp, smooth_data & data) static
Definition at line 632 of file PViewDataList.cpp.
Referenced by PViewDataList::smooth().