gmsh-TingyuanDoc: src/graphics/ReadImg.cpp File Reference
ReadImg.cpp File Reference
#include <string.h>
#include "ReadImg.h"
#include "GmshMessage.h"
#include "PView.h"
#include "PViewDataList.h"
#include "GmshConfig.h"
Functions
int read_pnm (std::string fileName)
int read_jpeg (std::string fileName)
int read_png (std::string fileName)
int read_bmp (std::string fileName)
Function Documentation
read_bmp()
int read_bmp (std::string fileName)
Definition at line 167 of file ReadImg.cpp.
Referenced by MergeFile().
read_jpeg()
int read_jpeg (std::string fileName)
Definition at line 165 of file ReadImg.cpp.
Referenced by MergeFile().
read_png()
int read_png (std::string fileName)
Definition at line 166 of file ReadImg.cpp.
Referenced by MergeFile().
read_pnm()
int read_pnm (std::string fileName)
Definition at line 164 of file ReadImg.cpp.
Referenced by MergeFile().