gmsh-TingyuanDoc: src/geo/STensor3.cpp File Reference
STensor3.cpp File Reference
#include <algorithm>
#include "STensor3.h"
#include "fullMatrix.h"
Functions
SMetric3 intersection (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 intersection_alauzet (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 intersection_conserveM1 (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 intersection_conserve_mostaniso (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 intersection_conserve_mostaniso_2d (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 interpolation (const SMetric3 &m1, const SMetric3 &m2, const double t)
SMetric3 interpolation (const SMetric3 &m1, const SMetric3 &m2, const SMetric3 &m3, const double u, const double v)
SMetric3 interpolation (const SMetric3 &m1, const SMetric3 &m2, const SMetric3 &m3, const SMetric3 &m4, const double u, const double v, const double w)
Function Documentation
interpolation() [1/3]
SMetric3 interpolation (const SMetric3 & m1, const SMetric3 & m2, const double t)
Definition at line 260 of file STensor3.cpp.
Referenced by meshMetric::operator()(), and meshMetric::scaleMetric().
interpolation() [2/3]
SMetric3 interpolation (const SMetric3 & m1, const SMetric3 & m2, const SMetric3 & m3, const double u, const double v)
Definition at line 270 of file STensor3.cpp.
interpolation() [3/3]
SMetric3 interpolation (const SMetric3 & m1, const SMetric3 & m2, const SMetric3 & m3, const SMetric3 & m4, const double u, const double v, const double w)
Definition at line 284 of file STensor3.cpp.
intersection()
SMetric3 intersection (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 119 of file STensor3.cpp.
Referenced by BGM_MeshMetric(), max_edge_curvature_metric(), and MinAnisoField::operator()().
intersection_alauzet()
SMetric3 intersection_alauzet (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 146 of file STensor3.cpp.
Referenced by IntersectAnisoField::operator()().
intersection_conserve_mostaniso()
SMetric3 intersection_conserve_mostaniso (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 216 of file STensor3.cpp.
Referenced by meshMetric::operator()(), MinAnisoField::operator()(), and meshMetric::updateMetrics().
intersection_conserve_mostaniso_2d()
SMetric3 intersection_conserve_mostaniso_2d (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 236 of file STensor3.cpp.
Referenced by meshMetric::updateMetrics().
intersection_conserveM1()
SMetric3 intersection_conserveM1 (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 164 of file STensor3.cpp.
Referenced by intersection_conserve_mostaniso(), intersection_conserve_mostaniso_2d(), metric_based_on_surface_curvature(), F_Lc_aniso::operator()(), and BoundaryLayerField::operator()().