gmsh-TingyuanDoc: src/geo/STensor3.h File Reference
STensor3.h File Reference
#include "SVector3.h"
#include "Numeric.h"
#include "GmshMessage.h"
Classes
class fullVector< scalar >
class fullMatrix< scalar >
class SMetric3
class STensor3
Functions
double dot (const SVector3 &a, const SMetric3 &m, const SVector3 &b)
SMetric3 intersection_conserveM1 (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 intersection_conserve_mostaniso (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 intersection_conserve_mostaniso_2d (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 intersection (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 intersection_alauzet (const SMetric3 &m1, const SMetric3 &m2)
SMetric3 interpolation (const SMetric3 &m1, const SMetric3 &m2, const double t)
SMetric3 interpolation (const SMetric3 &m1, const SMetric3 &m2, const SMetric3 &m3, const double u, const double v)
SMetric3 interpolation (const SMetric3 &m1, const SMetric3 &m2, const SMetric3 &m3, const SMetric3 &m4, const double u, const double v, const double w)
void tensprod (const SVector3 &a, const SVector3 &b, STensor3 &c)
double dot (const STensor3 &a, const STensor3 &b)
SVector3 operator* (const STensor3 &t, const SVector3 &v)
SVector3 operator* (const SVector3 &v, const STensor3 &t)
STensor3 operator* (const STensor3 &t, double m)
STensor3 operator* (double m, const STensor3 &t)
Function Documentation
dot() [1/2]
double dot (const STensor3 & a, const STensor3 & b) inline
Definition at line 295 of file STensor3.h.
dot() [2/2]
double dot (const SVector3 & a, const SMetric3 & m, const SVector3 & b) inline
Definition at line 71 of file STensor3.h.
Referenced by MPolygon::_initVertices(), _relocateVertexOfPyramid(), addTriangle(), angle3Vertices(), qmHexahedron::angles(), blyr_manager::blyr_manager(), buildMetric(), discreteFace::param::checkPlanar(), blyr_manager::classify_ridges(), SOrientedBoundingBox::compare(), meshMetric::computeMetricEigenDir(), GFace::curvatureDiv(), decasteljau(), drawVoronoiDual(), qmQuadrangle::eta(), GMSH_CrackPlugin::execute(), FixPeriodicMesh(), BilinearTermContract< T2 >::get(), BilinearTermContractWithLaw< T2 >::get(), LaplaceTerm< T1, T1 >::get(), LoadTerm< T1 >::get(), LagrangeMultiplierTerm< T1 >::get(), LagMultTerm::get(), LoadTermOnBorder< T1 >::get(), cartesianBox< scalar >::getCellContainingPoint(), getGFaceOrientation(), MSubTriangle::getGradShapeFunctions(), MSubLine::getGradShapeFunctions(), GFace::getMetricEigenVectors(), intersect(), intersection(), intersection_alauzet(), intersection_conserveM1(), discreteFace::intersectionWithCircle(), SOrientedBoundingBox::intersects(), myAngle(), qmTriangle::NCJ(), qmQuadrangle::NCJ(), F_Lc_aniso::operator()(), myLine::orthogonalProjection(), prismNCJ(), projection(), quadsToTriangles(), RecombineTriangle::RecombineTriangle(), GEdge::refineProjection(), signedDistancePointLine(), signedDistancePointTriangle(), signedDistancesPointsTriangle(), sqDistPointSegment(), transformPointsIntoOrthoBasis(), and TRIANGLE_VALIDITY().
interpolation() [1/3]
SMetric3 interpolation (const SMetric3 & m1, const SMetric3 & m2, const double t)
Definition at line 260 of file STensor3.cpp.
Referenced by meshMetric::operator()(), and meshMetric::scaleMetric().
interpolation() [2/3]
SMetric3 interpolation (const SMetric3 & m1, const SMetric3 & m2, const SMetric3 & m3, const double u, const double v)
Definition at line 270 of file STensor3.cpp.
interpolation() [3/3]
SMetric3 interpolation (const SMetric3 & m1, const SMetric3 & m2, const SMetric3 & m3, const SMetric3 & m4, const double u, const double v, const double w)
Definition at line 284 of file STensor3.cpp.
intersection()
SMetric3 intersection (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 119 of file STensor3.cpp.
Referenced by BGM_MeshMetric(), max_edge_curvature_metric(), and MinAnisoField::operator()().
intersection_alauzet()
SMetric3 intersection_alauzet (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 146 of file STensor3.cpp.
Referenced by IntersectAnisoField::operator()().
intersection_conserve_mostaniso()
SMetric3 intersection_conserve_mostaniso (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 216 of file STensor3.cpp.
Referenced by meshMetric::operator()(), MinAnisoField::operator()(), and meshMetric::updateMetrics().
intersection_conserve_mostaniso_2d()
SMetric3 intersection_conserve_mostaniso_2d (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 236 of file STensor3.cpp.
Referenced by meshMetric::updateMetrics().
intersection_conserveM1()
SMetric3 intersection_conserveM1 (const SMetric3 & m1, const SMetric3 & m2)
Definition at line 164 of file STensor3.cpp.
Referenced by intersection_conserve_mostaniso(), intersection_conserve_mostaniso_2d(), metric_based_on_surface_curvature(), F_Lc_aniso::operator()(), and BoundaryLayerField::operator()().
operator*() [1/4]
SVector3 operator* (const STensor3 & t, const SVector3 & v) inline
Definition at line 303 of file STensor3.h.
operator*() [2/4]
STensor3 operator* (const STensor3 & t, double m) inline
Definition at line 319 of file STensor3.h.
operator*() [3/4]
SVector3 operator* (const SVector3 & v, const STensor3 & t) inline
Definition at line 311 of file STensor3.h.
operator*() [4/4]
STensor3 operator* (double m, const STensor3 & t) inline
Definition at line 326 of file STensor3.h.
tensprod()
void tensprod (const SVector3 & a, const SVector3 & b, STensor3 & c) inline
Definition at line 289 of file STensor3.h.
Referenced by ScalarToAnyFunctionSpace< SVector3 >::gradf(), xFemFunctionSpace< T >::gradf(), and ScalarToAnyFunctionSpace< SVector3 >::gradfuvw().