gmsh-TingyuanDoc: src/geo/SVector3.h File Reference
SVector3.h File Reference
#include "SPoint3.h"
#include <string>
#include <stdio.h>
#include <array>
Classes
class SVector3
Functions
double dot (const SVector3 &a, const SVector3 &b)
double norm (const SVector3 &v)
double normSq (const SVector3 &v)
SVector3 crossprod (const SVector3 &a, const SVector3 &b)
double angle (const SVector3 &a, const SVector3 &b)
double signedAngle (const SVector3 &a, const SVector3 &b, const SVector3 &n)
SVector3 operator* (double m, const SVector3 &v)
SVector3 operator* (const SVector3 &v, double m)
SVector3 operator* (const SVector3 &v1, const SVector3 &v2)
SVector3 operator+ (const SVector3 &a, const SVector3 &b)
SPoint3 operator+ (const SPoint3 &a, const SVector3 &b)
SVector3 operator- (const SVector3 &a, const SVector3 &b)
SPoint3 operator- (const SPoint3 &a, const SVector3 &b)
SVector3 operator- (const SVector3 &a)
void buildOrthoBasis_naive (SVector3 &dir, SVector3 &dir1, SVector3 &dir2)
void buildOrthoBasis (SVector3 &normal, SVector3 &tangent, SVector3 &binormal)
void buildOrthoBasis2 (SVector3 &normal, SVector3 &tangent, SVector3 &binormal)
Function Documentation
angle()
double angle (const SVector3 & a, const SVector3 & b) inline
Definition at line 157 of file SVector3.h.
Referenced by GEO_Internals::_extrude(), _recombineIntoQuads(), drawContext::addQuaternionFromAxisAndAngle(), qmHexahedron::angles(), centroidOfOrientedBox(), blyr_manager::classify_ridges(), computeAffineTransformation(), computeParametrization(), blyr_ridge::computeType(), gmshFace::containsPoint(), qmTriangle::eta(), qmQuadrangle::eta(), faceIsValidQuad(), backgroundMesh::getAngle(), gl2psAddText(), gl2psTextOpt(), gl2psTextOptColor(), gl2psTextOptColorBL(), gLevelsetCone::gLevelsetCone(), gLevelsetShamrock::gLevelsetShamrock(), improved_translate(), gmshFace::normal(), crossField2d::normalizeAngle(), backgroundMesh::propagateCrossField(), backgroundMesh::propagateCrossFieldByDistance(), GEO_Internals::revolve(), GEO_Internals::rotate(), scriptProtude(), scriptRotate(), GEO_Internals::setRecombine(), and GEO_Internals::twist().
buildOrthoBasis()
void buildOrthoBasis (SVector3 & normal, SVector3 & tangent, SVector3 & binormal) inline
Definition at line 257 of file SVector3.h.
Referenced by transformPointsIntoOrthoBasis().
buildOrthoBasis2()
void buildOrthoBasis2 (SVector3 & normal, SVector3 & tangent, SVector3 & binormal) inline
Definition at line 279 of file SVector3.h.
buildOrthoBasis_naive()
void buildOrthoBasis_naive (SVector3 & dir, SVector3 & dir1, SVector3 & dir2) inline
Definition at line 212 of file SVector3.h.
Referenced by buildOrthoBasis(), and buildOrthoBasis2().
crossprod()
SVector3 crossprod (const SVector3 & a, const SVector3 & b) inline
Definition at line 150 of file SVector3.h.
Referenced by discreteFace::_computeSTLNormals(), MElement::_getFaceRep(), _myGetFaceRep(), addExtrudeNormals(), addTriangle(), angle(), angle3Vertices(), buildMetricTangentToCurve(), buildMetricTangentToSurface(), buildOrthoBasis(), buildOrthoBasis2(), changeCoordinates(), discreteFace::closestPoint(), GFace::computeMeanPlane(), GEdge::curvature(), GFace::curvatureDiv(), decasteljau(), drawNormalVectorGlyphs(), qmQuadrangle::eta(), GMSH_CrackPlugin::execute(), MFaceN::frame(), MTetrahedron::getEdgeRep(), MQuadrangle::getEdgeRep(), MTriangle::getEdgeRep(), MHexahedron::getEdgeRep(), MSubTriangle::getGradShapeFunctions(), getLineNormal(), GFace::getMetricEigenVectors(), MTriangle::getVolume(), improved_translate(), insertVertexB(), discreteFace::intersectionWithCircle(), SOrientedBoundingBox::intersects(), metric_based_on_surface_curvature(), minimizeTutteEnergyProj(), myAngle(), myLine::myLine(), qmTriangle::NCJ(), qmQuadrangle::NCJ(), discreteFace::normal(), MEdge::normal(), PolyMesh::normal(), MFaceN::normal(), GFace::normal(), normal3(), oneSidedHausdorffDistance(), optimalPointFrontalB(), prismNCJ(), backgroundMesh::propagateCrossField(), RecombineTriangle::RecombineTriangle(), signedAngle(), signedDistancePointTriangle(), signedDistancesPointsTriangle(), sqDistPointSegment(), MFace::tangent(), and TRIANGLE_VALIDITY().
dot()
double dot (const SVector3 & a, const SVector3 & b) inline
Definition at line 141 of file SVector3.h.
Referenced by angle(), norm(), normSq(), and signedAngle().
norm()
double norm (const SVector3 & v) inline
Definition at line 146 of file SVector3.h.
Referenced by angle().
normSq()
double normSq (const SVector3 & v) inline
Definition at line 148 of file SVector3.h.
Referenced by elasticitySolver::computeDisplacementError(), elasticitySolver::computeL2Norm(), and GFace::getMetricEigenVectors().
operator*() [1/3]
SVector3 operator* (const SVector3 & v, double m) inline
Definition at line 177 of file SVector3.h.
operator*() [2/3]
SVector3 operator* (const SVector3 & v1, const SVector3 & v2) inline
Definition at line 182 of file SVector3.h.
operator*() [3/3]
SVector3 operator* (double m, const SVector3 & v) inline
Definition at line 172 of file SVector3.h.
operator+() [1/2]
SPoint3 operator+ (const SPoint3 & a, const SVector3 & b) inline
Definition at line 192 of file SVector3.h.
operator+() [2/2]
SVector3 operator+ (const SVector3 & a, const SVector3 & b) inline
Definition at line 187 of file SVector3.h.
operator-() [1/3]
SPoint3 operator- (const SPoint3 & a, const SVector3 & b) inline
Definition at line 202 of file SVector3.h.
operator-() [2/3]
SVector3 operator- (const SVector3 & a) inline
Definition at line 207 of file SVector3.h.
operator-() [3/3]
SVector3 operator- (const SVector3 & a, const SVector3 & b) inline
Definition at line 197 of file SVector3.h.
signedAngle()
double signedAngle (const SVector3 & a, const SVector3 & b, const SVector3 & n) inline
Definition at line 164 of file SVector3.h.
Referenced by GMSH_BoundaryAnglesPlugin::execute().