gmsh-TingyuanDoc: src/plugin/Skin.cpp File Reference
Skin.cpp File Reference
#include <set>
#include "Skin.h"
#include "Context.h"
#include "GmshDefines.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MLine.h"
#include "MFace.h"
#include "MEdge.h"
#include "discreteFace.h"
#include "discreteEdge.h"
Classes
class ElmData
class ElmDataLessThan
Functions
GMSH_Plugin * GMSH_RegisterSkinPlugin ()
static int getBoundary (int type, const int(**boundary)[6][4])
static void getBoundaryFromMesh (GModel *m, int visible)
Variables
StringXNumber SkinOptions_Number []
Function Documentation
getBoundary()
static int getBoundary (int type, const int(**) boundary[6][4]) static
Definition at line 165 of file Skin.cpp.
Referenced by GMSH_SkinPlugin::execute().
getBoundaryFromMesh()
static void getBoundaryFromMesh (GModel * m, int visible) static
Definition at line 189 of file Skin.cpp.
Referenced by GMSH_SkinPlugin::execute().
GMSH_RegisterSkinPlugin()
GMSH_Plugin* GMSH_RegisterSkinPlugin ()
Definition at line 23 of file Skin.cpp.
Referenced by PluginManager::registerDefaultPlugins().
Variable Documentation
SkinOptions_Number
StringXNumber SkinOptions_Number[]
Initial value:
= {{GMSH_FULLRC, "Visible", nullptr, 1.},
                                      {GMSH_FULLRC, "FromMesh", nullptr, 0.},
                                      {GMSH_FULLRC, "View", nullptr, -1.}}
Definition at line 18 of file Skin.cpp.
Referenced by GMSH_SkinPlugin::execute(), GMSH_SkinPlugin::getNbOptions(), and GMSH_SkinPlugin::getOption().