gmsh-TingyuanDoc: src/common/StringUtils.cpp File Reference
StringUtils.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <regex>
#include "StringUtils.h"
#include "GmshMessage.h"
#include "OS.h"
Functions
void SwapBytes (char *array, int size, int n)
std::string ExtractDoubleQuotedString (const char *str, int len)
std::string SanitizeTeXString (const char *in, int equation)
std::string FixWindowsPath (const std::string &in)
std::string FixRelativePath (const std::string &reference, const std::string &in)
std::vector< std::string > SplitFileName (const std::string &fileName)
std::string GetFileNameWithoutPath (const std::string &fileName)
std::string ConvertFileToString (const std::string &fileName)
void ReplaceSubStringInPlace (const std::string &olds, const std::string &news, std::string &str)
std::string ReplaceSubString (const std::string &olds, const std::string &news, const std::string &str)
void ConvertToHTML (std::string &str)
bool SplitOptionName (const std::string &fullName, std::string &category, std::string &name, int &index)
std::string RemoveWhiteSpace (const std::string &s)
static std::string getNextTokenInString (const std::string &msg, std::string::size_type &first, char separator)
std::vector< std::string > SplitString (const std::string &msg, char separator, bool removeWhiteSpace)
bool IsOnelabName (const std::string &name, std::string &cleanName)
Function Documentation
ConvertFileToString()
std::string ConvertFileToString (const std::string & fileName)
Definition at line 119 of file StringUtils.cpp.
Referenced by initPView::operator()().
ConvertToHTML()
void ConvertToHTML (std::string & str)
Definition at line 148 of file StringUtils.cpp.
ExtractDoubleQuotedString()
std::string ExtractDoubleQuotedString (const char * str, int len)
Definition at line 27 of file StringUtils.cpp.
Referenced by GModel::_readMSH2(), GModel::_readMSH3(), GModel::_readMSH4(), and PView::readMSH().
FixRelativePath()
std::string FixRelativePath (const std::string & reference, const std::string & in)
Definition at line 77 of file StringUtils.cpp.
Referenced by drawContext::drawBackgroundImage(), drawContext::drawImage(), and ParseString().
FixWindowsPath()
std::string FixWindowsPath (const std::string & in)
Definition at line 65 of file StringUtils.cpp.
GetFileNameWithoutPath()
std::string GetFileNameWithoutPath (const std::string & fileName)
Definition at line 113 of file StringUtils.cpp.
getNextTokenInString()
static std::string getNextTokenInString (const std::string & msg, std::string::size_type & first, char separator) static
Definition at line 188 of file StringUtils.cpp.
Referenced by SplitString().
IsOnelabName()
bool IsOnelabName (const std::string & name, std::string & cleanName)
Definition at line 225 of file StringUtils.cpp.
Referenced by GetOtherOption().
RemoveWhiteSpace()
std::string RemoveWhiteSpace (const std::string & s)
Definition at line 182 of file StringUtils.cpp.
Referenced by SplitString().
ReplaceSubString()
std::string ReplaceSubString (const std::string & olds, const std::string & news, const std::string & str)
Definition at line 140 of file StringUtils.cpp.
Referenced by api(), and opt_general_build_info().
ReplaceSubStringInPlace()
void ReplaceSubStringInPlace (const std::string & olds, const std::string & news, std::string & str)
Definition at line 130 of file StringUtils.cpp.
Referenced by ConvertToHTML(), ReplaceSubString(), and scriptAddFieldOption().
SanitizeTeXString()
std::string SanitizeTeXString (const char * in, int equation)
Definition at line 39 of file StringUtils.cpp.
Referenced by drawContext::drawString().
SplitFileName()
std::vector<std::string> SplitFileName (const std::string & fileName)
Definition at line 93 of file StringUtils.cpp.
Referenced by addGmshPathToEnvironmentVar(), CreateOutputFile(), GMSH_BoundaryAnglesPlugin::execute(), FixRelativePath(), drawContext::generateTextureForImage(), GetDefaultFileName(), GetFileNameWithoutPath(), GuessFileFormatFromFileName(), HtmlFileName(), MergeFile(), print_pgf(), PluginManager::registerDefaultPlugins(), scriptAddCommand(), GModel::setFileName(), SystemCallExe(), TagFileName(), PView::write(), writeHTMLBody(), and PViewDataGModel::writeMSH().
SplitOptionName()
bool SplitOptionName (const std::string & fullName, std::string & category, std::string & name, int & index)
Definition at line 156 of file StringUtils.cpp.
Referenced by GetOtherOption().
SplitString()
std::vector<std::string> SplitString (const std::string & msg, char separator, bool removeWhiteSpace)
Definition at line 210 of file StringUtils.cpp.
Referenced by drawEntityLabel(), and opt_general_scripting_languages().
SwapBytes()
void SwapBytes (char * array, int size, int n)
Definition at line 16 of file StringUtils.cpp.
Referenced by GModel::_readMSH2(), GModel::_readMSH3(), cVecRead(), dVecRead(), PViewDataGModel::readMSH(), readMSH4BoundingEntities(), readMSH4Elements(), readMSH4Entities(), readMSH4EntityInfo(), readMSH4GhostElements(), readMSH4Nodes(), readMSH4PeriodicNodes(), readMSH4Physicals(), GModel::readPLY(), GModel::readSTL(), GModel::readVTK(), MVertex::writeVTK(), MElement::writeVTK(), and GModel::writeVTK().