gmsh-TingyuanDoc: src/graphics/Trackball.h File Reference
Trackball.h File Reference
Functions
void trackball (double q[4], double p1x, double p1y, double p2x, double p2y)
void add_quats (double *q1, double *q2, double *dest)
void build_rotmatrix (double m[16], double q[4])
void axis_to_quat (double a[3], double phi, double q[4])
double trackballsize ()
Function Documentation
add_quats()
void add_quats (double * q1, double * q2, double * dest)
axis_to_quat()
void axis_to_quat (double a[3], double phi, double q[4])
Definition at line 213 of file Trackball.cpp.
Referenced by drawContext::addQuaternionFromAxisAndAngle(), drawContext::setQuaternionFromEulerAngles(), and trackball().
build_rotmatrix()
void build_rotmatrix (double m[16], double q[4])
Definition at line 323 of file Trackball.cpp.
Referenced by drawContext::buildRotationMatrix().
trackball()
void trackball (double q[4], double p1x, double p1y, double p2x, double p2y)
Definition at line 166 of file Trackball.cpp.
Referenced by drawContext::addQuaternion().
trackballsize()
double trackballsize ()