gmsh-TingyuanDoc: src/common/TreeUtils.h File Reference
TreeUtils.h File Reference
#include "avl.h"
#include "ListUtils.h"
Classes
class Tree_T
Functions
Tree_T * Tree_Create (int size, int(*fcmp)(const void *a, const void *b))
void Tree_Delete (Tree_T *Tree)
void Tree_Delete (Tree_T *Tree, void(*freefn)(void *))
void * Tree_Add (Tree_T *tree, void *data)
int Tree_Nbr (Tree_T *Tree)
int Tree_Insert (Tree_T *Tree, void *data)
int Tree_Search (Tree_T *Tree, void *data)
int Tree_Query (Tree_T *Tree, void *data)
void * Tree_PQuery (Tree_T *Tree, void *data)
int Tree_Suppress (Tree_T *Tree, void *data)
int Tree_Size (Tree_T *tree)
void Tree_Action (Tree_T *tree, void(*action)(void *data, void *dummy))
List_T * Tree2List (Tree_T *pTree)
Function Documentation
Tree2List()
List_T* Tree2List (Tree_T * pTree)
Definition at line 110 of file TreeUtils.cpp.
Referenced by ApplicationOnShapes(), DeleteCurve(), DeletePoint(), DeleteSurface(), RecognizeLineLoop(), RecognizeSurfaceLoop(), RemoveDegenerateCurves(), RemoveDegenerateSurfaces(), RemoveDegenerateVolumes(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicatePointsNew(), ReplaceDuplicateSurfaces(), GEO_Internals::setRecombine(), GEO_Internals::setReverseMesh(), GEO_Internals::setSmoothing(), GEO_Internals::setTransfiniteLine(), GEO_Internals::setTransfiniteSurface(), GEO_Internals::setTransfiniteVolume(), GEO_Internals::setTransfiniteVolumeQuadTri(), SplitCurve(), and GEO_Internals::synchronize().
Tree_Action()
void Tree_Action (Tree_T * tree, void(*)(void *data, void *dummy) action)
Definition at line 100 of file TreeUtils.cpp.
Referenced by GEO_Internals::_freeAll(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicateSurfaces(), and Tree2List().
Tree_Add()
void* Tree_Add (Tree_T * tree, void * data)
Definition at line 37 of file TreeUtils.cpp.
Referenced by GEO_Internals::_addCompoundSpline(), _create_splitted_curve(), GEO_Internals::addBezier(), GEO_Internals::addBSpline(), GEO_Internals::addCircleArc(), GEO_Internals::addCurveLoop(), GEO_Internals::addCurveLoops(), GEO_Internals::addDiscreteSurface(), GEO_Internals::addEllipseArc(), GEO_Internals::addLine(), GEO_Internals::addPlaneSurface(), GEO_Internals::addSpline(), GEO_Internals::addSurfaceFilling(), GEO_Internals::addSurfaceLoop(), GEO_Internals::addVertex(), GEO_Internals::addVolume(), allEdgesLinked(), allFacesLinked(), createEdgeLinks(), createFaceLinks(), CreateReversedCurve(), DeleteCurve(), DeletePoint(), DeleteSurface(), DeleteVolume(), discreteEdge::discreteEdge(), discreteFace::discreteFace(), discreteRegion::discreteRegion(), discreteVertex::discreteVertex(), GModel::exportDiscreteGEOInternals(), ExtrudeCurve(), ExtrudePoint(), ExtrudeSurface(), recurFindLinkedEdges(), recurFindLinkedFaces(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicatePointsNew(), ReplaceDuplicateSurfaces(), and Tree_Insert().
Tree_Create()
Tree_T* Tree_Create (int size, int(*)(const void *a, const void *b) fcmp)
Definition at line 15 of file TreeUtils.cpp.
Referenced by GEO_Internals::_allocateAll(), allEdgesLinked(), allFacesLinked(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), and ReplaceDuplicateSurfaces().
Tree_Delete() [1/2]
void Tree_Delete (Tree_T * Tree)
Definition at line 23 of file TreeUtils.cpp.
Referenced by GEO_Internals::_freeAll(), allEdgesLinked(), allFacesLinked(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), and ReplaceDuplicateSurfaces().
Tree_Delete() [2/2]
void Tree_Delete (Tree_T * Tree, void(*)(void *) freefn)
Definition at line 30 of file TreeUtils.cpp.
Tree_Insert()
int Tree_Insert (Tree_T * Tree, void * data)
Definition at line 52 of file TreeUtils.cpp.
Referenced by DuplicateCurve(), DuplicateSurface(), DuplicateVertex(), DuplicateVolume(), IntersectCurvesWithSurface(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), and ReplaceDuplicateSurfaces().
Tree_Nbr()
int Tree_Nbr (Tree_T * Tree)
Definition at line 46 of file TreeUtils.cpp.
Referenced by allEdgesLinked(), allFacesLinked(), GModel::exportDiscreteGEOInternals(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicatePointsNew(), ReplaceDuplicateSurfaces(), GEO_Internals::synchronize(), and Tree2List().
Tree_PQuery()
void* Tree_PQuery (Tree_T * Tree, void * data)
Definition at line 77 of file TreeUtils.cpp.
Referenced by createEdgeLinks(), createFaceLinks(), CreateReversedCurve(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), and ReplaceDuplicateSurfaces().
Tree_Query()
int Tree_Query (Tree_T * Tree, void * data)
Definition at line 68 of file TreeUtils.cpp.
Referenced by ExtrudePoint(), FindCurve(), FindEdgeLoop(), FindPoint(), FindSurface(), FindSurfaceLoop(), FindVolume(), orientAndSortEdges(), recurFindLinkedEdges(), recurFindLinkedFaces(), and ReplaceDuplicatePoints().
Tree_Search()
int Tree_Search (Tree_T * Tree, void * data)
Definition at line 61 of file TreeUtils.cpp.
Referenced by allEdgesLinked(), allFacesLinked(), recurFindLinkedEdges(), recurFindLinkedFaces(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicateSurfaces(), and Tree_Insert().
Tree_Size()
int Tree_Size (Tree_T * tree)
Definition at line 94 of file TreeUtils.cpp.
Referenced by Tree2List().
Tree_Suppress()
int Tree_Suppress (Tree_T * Tree, void * data)
Definition at line 85 of file TreeUtils.cpp.
Referenced by allEdgesLinked(), allFacesLinked(), DeleteCurve(), DeletePoint(), DeleteSurface(), DeleteVolume(), ExtrudeSurface(), recurFindLinkedEdges(), recurFindLinkedFaces(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicatePointsNew(), and ReplaceDuplicateSurfaces().