gmsh-TingyuanDoc: picojson::input< Iter > Class Template Reference
picojson::input< Iter > Class Template Reference
#include <picojson.h>
Public Member Functions
input (const Iter &first, const Iter &last)
int getc ()
void ungetc ()
Iter cur () const
int line () const
void skip_ws ()
bool expect (const int expected)
bool match (const std::string &pattern)
Protected Attributes
Iter cur_
Iter end_
bool consumed_
int line_
Detailed Description
template<typename Iter>
class picojson::input< Iter >
Definition at line 637 of file picojson.h.
Constructor & Destructor Documentation
input()
template<typename Iter > picojson::input< Iter >::input (const Iter & first, const Iter & last) inline
Definition at line 644 of file picojson.h.
Member Function Documentation
cur()
template<typename Iter > Iter picojson::input< Iter >::cur () const inline
Definition at line 663 of file picojson.h.
Referenced by picojson::_parse().
expect()
template<typename Iter > bool picojson::input< Iter >::expect (const int expected) inline
Definition at line 683 of file picojson.h.
Referenced by picojson::_parse_array(), and picojson::_parse_object().
getc()
template<typename Iter > int picojson::input< Iter >::getc () inline
Definition at line 646 of file picojson.h.
Referenced by picojson::_parse(), picojson::_parse_codepoint(), picojson::_parse_number(), picojson::_parse_quadhex(), picojson::_parse_string(), picojson::input< Iter >::expect(), picojson::input< Iter >::match(), and picojson::input< Iter >::skip_ws().
line()
template<typename Iter > int picojson::input< Iter >::line () const inline
Definition at line 671 of file picojson.h.
Referenced by picojson::_parse().
match()
template<typename Iter > bool picojson::input< Iter >::match (const std::string & pattern) inline
Definition at line 691 of file picojson.h.
skip_ws()
template<typename Iter > void picojson::input< Iter >::skip_ws () inline
Definition at line 674 of file picojson.h.
Referenced by picojson::_parse(), and picojson::input< Iter >::expect().
ungetc()
template<typename Iter > void picojson::input< Iter >::ungetc () inline
Definition at line 660 of file picojson.h.
Referenced by picojson::_parse(), picojson::_parse_codepoint(), picojson::_parse_number(), picojson::_parse_quadhex(), picojson::_parse_string(), picojson::input< Iter >::expect(), picojson::input< Iter >::match(), and picojson::input< Iter >::skip_ws().
Member Data Documentation
consumed_
template<typename Iter > bool picojson::input< Iter >::consumed_ protected
Definition at line 640 of file picojson.h.
Referenced by picojson::input< Iter >::cur(), picojson::input< Iter >::getc(), and picojson::input< Iter >::ungetc().
cur_
template<typename Iter > Iter picojson::input< Iter >::cur_ protected
Definition at line 639 of file picojson.h.
Referenced by picojson::input< Iter >::cur(), and picojson::input< Iter >::getc().
end_
template<typename Iter > Iter picojson::input< Iter >::end_ protected
Definition at line 639 of file picojson.h.
Referenced by picojson::input< Iter >::getc().
line_
template<typename Iter > int picojson::input< Iter >::line_ protected
Definition at line 641 of file picojson.h.
Referenced by picojson::input< Iter >::getc(), and picojson::input< Iter >::line().
The documentation for this class was generated from the following file:
src/common/picojson.h