gmsh-TingyuanDoc: onelab::parameter Class Reference
onelab::parameter Class Reference abstract
#include <onelab.h>
Public Member Functions
parameter (const std::string &name="", const std::string &label="", const std::string &help="")
virtual ~parameter ()
void setName (const std::string &name)
void setLabel (const std::string &label)
void setHelp (const std::string &help)
void setChanged (int changed, const std::string &client="")
void setChangedValue (int value)
void setNeverChanged (bool never)
void setVisible (bool visible)
void setReadOnly (bool readOnly)
void setAttribute (const std::string &key, const std::string &value)
void setAttributes (const std::map< std::string, std::string > &attributes)
void setClients (const std::map< std::string, int > &clients)
void addClient (const std::string &client, int changed)
void addClients (const std::map< std::string, int > &clients)
bool hasClient (const std::string &client)
int getNumClients ()
virtual std::string getType () const =0
const std::string & getName () const
const std::string & getLabel () const
const std::string & getHelp () const
std::string getPath () const
std::string getShortName () const
int getChanged (const std::string &client="") const
int getChangedValue () const
bool getNeverChanged () const
bool getVisible () const
bool getReadOnly () const
std::string getAttribute (const std::string &key) const
const std::map< std::string, std::string > & getAttributes () const
const std::map< std::string, int > & getClients () const
std::string sanitize (const std::string &in) const
virtual std::string toChar () const
virtual std::string::size_type fromChar (const std::string &msg)
std::string sanitizeJSON (const std::string &in) const
virtual std::string toJSON () const
virtual bool fromJSON (const picojson::value::object &par)
Static Public Member Functions
static char charSep ()
static double maxNumber ()
static std::string version ()
static int defaultChangedValue ()
static std::string getNextToken (const std::string &msg, std::string::size_type &first, char separator=charSep())
static std::vector< std::string > split (const std::string &msg, char separator=charSep())
static std::string trim (const std::string &str, const std::string &whitespace=" \t\n")
static void getInfoFromChar (const std::string &msg, std::string &version, std::string &type, std::string &name)
static bool fromFile (std::vector< std::string > &msg, FILE *fp)
static bool toFile (const std::vector< std::string > &msg, FILE *fp, const std::string &creator)
Protected Attributes
std::map< std::string, std::string > _attributes
Private Attributes
std::string _name
std::string _label
std::string _help
std::map< std::string, int > _clients
int _changedValue
bool _visible
bool _readOnly
Detailed Description
Definition at line 48 of file onelab.h.
Constructor & Destructor Documentation
parameter()
onelab::parameter::parameter (const std::string & name = "", const std::string & label = "", const std::string & help = "") inline
Definition at line 82 of file onelab.h.
~parameter()
virtual onelab::parameter::~parameter () inline virtual
Definition at line 89 of file onelab.h.
Member Function Documentation
addClient()
void onelab::parameter::addClient (const std::string & client, int changed) inline
Definition at line 123 of file onelab.h.
Referenced by fromChar(), and fromJSON().
addClients()
void onelab::parameter::addClients (const std::map< std::string, int > & clients) inline
Definition at line 127 of file onelab.h.
Referenced by onelab::number::update(), and onelab::string::update().
charSep()
static char onelab::parameter::charSep () inline static
Definition at line 203 of file onelab.h.
Referenced by onelab::remoteNetworkClient::runNonBlockingSubClient(), sanitize(), toChar(), onelab::number::toChar(), and onelab::string::toChar().
defaultChangedValue()
static int onelab::parameter::defaultChangedValue () inline static
Definition at line 206 of file onelab.h.
Referenced by onelab::parameterSpace::_get(), onelab::parameterSpace::_getPtr(), onelab::parameterSpace::_set(), parameter(), and setNeverChanged().
fromChar()
virtual std::string::size_type onelab::parameter::fromChar (const std::string & msg) inline virtual
Reimplemented in onelab::string, and onelab::number.
Definition at line 271 of file onelab.h.
Referenced by onelab::number::fromChar(), and onelab::string::fromChar().
fromFile()
static bool onelab::parameter::fromFile (std::vector< std::string > & msg, FILE * fp) inline static
Definition at line 303 of file onelab.h.
Referenced by onelab::client::fromFile(), and onelab::server::fromFile().
fromJSON()
virtual bool onelab::parameter::fromJSON (const picojson::value::object & par) inline virtual
Reimplemented in onelab::string, and onelab::number.
Definition at line 369 of file onelab.h.
Referenced by onelab::number::fromJSON(), and onelab::string::fromJSON().
getAttribute()
std::string onelab::parameter::getAttribute (const std::string & key) const inline
Definition at line 192 of file onelab.h.
Referenced by getShortName().
getAttributes()
const std::map<std::string, std::string>& onelab::parameter::getAttributes () const inline
Definition at line 198 of file onelab.h.
Referenced by onelab::number::update(), and onelab::string::update().
getChanged()
int onelab::parameter::getChanged (const std::string & client = "") const inline
Definition at line 171 of file onelab.h.
getChangedValue()
int onelab::parameter::getChangedValue () const inline
Definition at line 188 of file onelab.h.
Referenced by toChar(), toJSON(), onelab::number::update(), and onelab::string::update().
getClients()
const std::map<std::string, int>& onelab::parameter::getClients () const inline
Definition at line 202 of file onelab.h.
Referenced by toChar(), toJSON(), onelab::number::update(), and onelab::string::update().
getHelp()
const std::string& onelab::parameter::getHelp () const inline
Definition at line 139 of file onelab.h.
Referenced by toChar(), toJSON(), onelab::number::update(), and onelab::string::update().
getInfoFromChar()
static void onelab::parameter::getInfoFromChar (const std::string & msg, std::string & version, std::string & type, std::string & name) inline static
Definition at line 295 of file onelab.h.
Referenced by onelab::parameterSpace::fromChar(), and onelab::client::fromChar().
getLabel()
const std::string& onelab::parameter::getLabel () const inline
Definition at line 138 of file onelab.h.
Referenced by toChar(), toJSON(), onelab::number::update(), and onelab::string::update().
getName()
const std::string& onelab::parameter::getName () const inline
Definition at line 137 of file onelab.h.
Referenced by onelab::parameterLessThan::operator()(), toChar(), and toJSON().
getNeverChanged()
bool onelab::parameter::getNeverChanged () const inline
Definition at line 189 of file onelab.h.
Referenced by onelab::number::update(), and onelab::string::update().
getNextToken()
static std::string onelab::parameter::getNextToken (const std::string & msg, std::string::size_type & first, char separator = charSep()) inline static
Definition at line 207 of file onelab.h.
Referenced by fromChar(), onelab::number::fromChar(), onelab::string::fromChar(), getInfoFromChar(), and split().
getNumClients()
int onelab::parameter::getNumClients () inline
Definition at line 135 of file onelab.h.
getPath()
std::string onelab::parameter::getPath () const inline
Definition at line 140 of file onelab.h.
getReadOnly()
bool onelab::parameter::getReadOnly () const inline
Definition at line 191 of file onelab.h.
Referenced by toChar(), toJSON(), onelab::number::update(), and onelab::string::update().
getShortName()
std::string onelab::parameter::getShortName () const inline
Definition at line 145 of file onelab.h.
getType()
virtual std::string onelab::parameter::getType () const pure virtual
Implemented in onelab::string, and onelab::number.
Referenced by fromChar(), toChar(), and toJSON().
getVisible()
bool onelab::parameter::getVisible () const inline
Definition at line 190 of file onelab.h.
Referenced by toChar(), toJSON(), onelab::number::update(), and onelab::string::update().
hasClient()
bool onelab::parameter::hasClient (const std::string & client) inline
Definition at line 131 of file onelab.h.
maxNumber()
static double onelab::parameter::maxNumber () inline static
Definition at line 204 of file onelab.h.
Referenced by Msg::ExchangeOnelabParameter().
sanitize()
std::string onelab::parameter::sanitize (const std::string & in) const inline
Definition at line 246 of file onelab.h.
Referenced by toChar(), onelab::number::toChar(), and onelab::string::toChar().
sanitizeJSON()
std::string onelab::parameter::sanitizeJSON (const std::string & in) const inline
Definition at line 332 of file onelab.h.
Referenced by toJSON(), onelab::number::toJSON(), and onelab::string::toJSON().
setAttribute()
void onelab::parameter::setAttribute (const std::string & key, const std::string & value) inline
Definition at line 111 of file onelab.h.
Referenced by fromChar(), fromJSON(), and Msg::ImportPhysicalGroupsInOnelab().
setAttributes()
void onelab::parameter::setAttributes (const std::map< std::string, std::string > & attributes) inline
Definition at line 115 of file onelab.h.
Referenced by onelab::number::update(), and onelab::string::update().
setChanged()
void onelab::parameter::setChanged (int changed, const std::string & client = "") inline
Definition at line 93 of file onelab.h.
Referenced by onelab::number::update(), and onelab::string::update().
setChangedValue()
void onelab::parameter::setChangedValue (int value) inline
Definition at line 104 of file onelab.h.
Referenced by fromChar(), fromJSON(), Msg::ImportPhysicalGroupsInOnelab(), and Msg::SetOnelabAction().
setClients()
void onelab::parameter::setClients (const std::map< std::string, int > & clients) inline
Definition at line 119 of file onelab.h.
setHelp()
void onelab::parameter::setHelp (const std::string & help) inline
Definition at line 92 of file onelab.h.
Referenced by fromChar(), fromJSON(), onelab::number::update(), and onelab::string::update().
setLabel()
void onelab::parameter::setLabel (const std::string & label) inline
Definition at line 91 of file onelab.h.
Referenced by fromChar(), fromJSON(), onelab::number::update(), and onelab::string::update().
setName()
void onelab::parameter::setName (const std::string & name) inline
Definition at line 90 of file onelab.h.
Referenced by fromChar(), and fromJSON().
setNeverChanged()
void onelab::parameter::setNeverChanged (bool never) inline
Definition at line 105 of file onelab.h.
setReadOnly()
void onelab::parameter::setReadOnly (bool readOnly) inline
Definition at line 110 of file onelab.h.
Referenced by fromChar(), fromJSON(), Msg::ImportPhysicalGroupsInOnelab(), onelab::number::update(), and onelab::string::update().
setVisible()
void onelab::parameter::setVisible (bool visible) inline
Definition at line 109 of file onelab.h.
Referenced by fromChar(), fromJSON(), Msg::ImportPhysicalGroupsInOnelab(), Msg::SetOnelabAction(), Msg::SetOnelabNumber(), onelab::number::update(), and onelab::string::update().
split()
static std::vector<std::string> onelab::parameter::split (const std::string & msg, char separator = charSep()) inline static
Definition at line 228 of file onelab.h.
toChar()
virtual std::string onelab::parameter::toChar () const inline virtual
Reimplemented in onelab::string, and onelab::number.
Definition at line 253 of file onelab.h.
Referenced by onelab::number::toChar(), and onelab::string::toChar().
toFile()
static bool onelab::parameter::toFile (const std::vector< std::string > & msg, FILE * fp, const std::string & creator) inline static
Definition at line 318 of file onelab.h.
Referenced by onelab::client::toFile(), and onelab::server::toFile().
toJSON()
virtual std::string onelab::parameter::toJSON () const inline virtual
Reimplemented in onelab::string, and onelab::number.
Definition at line 337 of file onelab.h.
Referenced by onelab::number::toJSON(), and onelab::string::toJSON().
trim()
static std::string onelab::parameter::trim (const std::string & str, const std::string & whitespace = " \t\n") inline static
Definition at line 237 of file onelab.h.
version()
static std::string onelab::parameter::version () inline static
Definition at line 205 of file onelab.h.
Referenced by fromChar(), onelab::parameterSpace::fromChar(), onelab::client::fromChar(), onelab::parameterSpace::fromJSON(), getInfoFromChar(), toChar(), and onelab::parameterSpace::toJSON().
Member Data Documentation
_attributes
std::map<std::string, std::string> onelab::parameter::_attributes protected
Definition at line 79 of file onelab.h.
Referenced by getAttribute(), getAttributes(), setAttribute(), setAttributes(), toChar(), and toJSON().
_changedValue
int onelab::parameter::_changedValue private
Definition at line 71 of file onelab.h.
Referenced by getChangedValue(), getNeverChanged(), parameter(), setChangedValue(), and setNeverChanged().
_clients
std::map<std::string, int> onelab::parameter::_clients private
Definition at line 67 of file onelab.h.
Referenced by addClient(), addClients(), getChanged(), getClients(), getNumClients(), hasClient(), setChanged(), and setClients().
_help
std::string onelab::parameter::_help private
Definition at line 60 of file onelab.h.
Referenced by getHelp(), and setHelp().
_label
std::string onelab::parameter::_label private
Definition at line 58 of file onelab.h.
Referenced by getLabel(), getShortName(), and setLabel().
_name
std::string onelab::parameter::_name private
Definition at line 55 of file onelab.h.
Referenced by getName(), getPath(), getShortName(), and setName().
_readOnly
bool onelab::parameter::_readOnly private
Definition at line 75 of file onelab.h.
Referenced by getReadOnly(), and setReadOnly().
_visible
bool onelab::parameter::_visible private
Definition at line 73 of file onelab.h.
Referenced by getVisible(), and setVisible().
The documentation for this class was generated from the following file:
src/common/onelab.h