gmsh-TingyuanDoc: MElement Class Reference
MElement Class Reference abstract
#include <MElement.h>
Public Member Functions
MElement (std::size_t num=0, int part=0)
virtual ~MElement ()
double getTolerance () const
virtual std::size_t getNum () const
void forceNum (std::size_t num)
virtual int getDim () const =0
virtual int getPolynomialOrder () const
virtual bool getIsAssimilatedSerendipity () const
virtual bool getIsOnlySerendipity () const
virtual int getPartition () const
virtual void setPartition (int num)
virtual char getVisibility () const
virtual void setVisibility (char val)
virtual std::size_t getNumVertices () const =0
virtual const MVertex * getVertex (int num) const =0
virtual MVertex * getVertex (int num)=0
void getVertices (std::vector< MVertex * > &verts)
virtual void setVertex (int num, MVertex *v)
virtual void getVertexInfo (const MVertex *vertex, int &ithVertex) const
virtual MVertex * getVertexUNV (int num)
virtual MVertex * getVertexVTK (int num)
virtual MVertex * getVertexMATLAB (int num)
virtual MVertex * getVertexTOCHNOG (int num)
virtual MVertex * getVertexBDF (int num)
virtual MVertex * getVertexDIFF (int num)
virtual MVertex * getVertexINP (int num)
virtual MVertex * getVertexKEY (int num)
virtual MVertex * getVertexRAD (int num)
virtual MVertex * getVertexNEU (int num)
virtual int getNumEdgeVertices () const
virtual int getNumFaceVertices () const
virtual int getNumVolumeVertices () const
std::size_t getNumPrimaryVertices () const
virtual int getNumEdges () const =0
virtual MEdge getEdge (int num) const =0
virtual MEdgeN getHighOrderEdge (int num, int sign)
MEdgeN getHighOrderEdge (const MEdge &edge)
virtual bool getEdgeInfo (const MEdge &edge, int &ithEdge, int &sign) const
virtual int numEdge2numVertex (int numEdge, int numVert) const
virtual MEdge getEdgeSolin (int numEdge)
virtual int getNumEdgesRep (bool curved)=0
virtual void getEdgeRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)=0
virtual int getNumFaces ()=0
virtual MFace getFace (int num) const =0
virtual MFaceN getHighOrderFace (int num, int sign, int rot)
MFaceN getHighOrderFace (const MFace &face)
virtual bool getFaceInfo (const MFace &face, int &ithFace, int &sign, int &rot) const
virtual MFace getFaceSolin (int numFace)
virtual int getNumFacesRep (bool curved)=0
virtual void getFaceRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)=0
virtual void getEdgeVertices (const int num, std::vector< MVertex * > &v) const
virtual void getFaceVertices (const int num, std::vector< MVertex * > &v) const
virtual MElement * getParent () const
virtual void setParent (MElement *p, bool owner=false)
virtual void updateParent (GModel *gm)
virtual int getNumChildren () const
virtual MElement * getChild (int i) const
virtual bool ownsParent () const
virtual const MElement * getBaseElement () const
virtual MElement * getBaseElement ()
virtual MElement * getDomain (int i) const
virtual void setDomain (MElement *e, int i)
virtual int getType () const =0
virtual double maxEdge ()
virtual double minEdge ()
double maxDistToStraight () const
double skewness ()
virtual double gammaShapeMeasure ()
virtual double etaShapeMeasure ()
double minSICNShapeMeasure ()
double minSIGEShapeMeasure ()
double distoShapeMeasure ()
double minIsotropyMeasure (bool knownValid=false, bool reversedOk=false)
double minScaledJacobian (bool knownValid=false, bool reversedOk=false)
virtual double angleShapeMeasure ()
virtual void scaledJacRange (double &jmin, double &jmax, GEntity *ge=nullptr) const
virtual void idealJacRange (double &jmin, double &jmax, GEntity *ge=nullptr)
virtual void signedInvCondNumRange (double &iCNMin, double &iCNMax, GEntity *ge=nullptr)
virtual void signedInvGradErrorRange (double &minSIGE, double &maxSIGE)
virtual double getInnerRadius ()
virtual double getOuterRadius ()
virtual SPoint3 barycenter (bool primary=false) const
virtual SPoint3 fastBarycenter (bool primary=false) const
virtual SPoint3 barycenterUVW () const
virtual SPoint3 barycenter_infty () const
virtual void reverse ()
virtual double getVolume ()
virtual int getVolumeSign ()
virtual bool setVolumePositive ()
int getValidity ()
virtual std::string getInfoString (bool multline)
virtual const nodalBasis * getFunctionSpace (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getFuncSpaceData (int order=-1, bool serendip=false) const
virtual const JacobianBasis * getJacobianFuncSpace (int orderElement=-1) const
virtual const FuncSpaceData getJacobianFuncSpaceData (int orderElement=-1) const
virtual void getNode (int num, double &u, double &v, double &w) const
virtual void getShapeFunctions (double u, double v, double w, double s[], int order=-1) const
virtual void getGradShapeFunctions (double u, double v, double w, double s[][3], int order=-1) const
virtual void getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order=-1) const
virtual void getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order=-1) const
virtual double getJacobian (const fullMatrix< double > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double *jac) const
virtual double getJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobian (double u, double v, double w, fullMatrix< double > &j) const
virtual double getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobianDeterminant (double u, double v, double w) const
void getSignedJacobian (fullVector< double > &jacobian, int o=-1) const
void getNodesCoord (fullMatrix< double > &nodesXYZ) const
void getNodesCoordNonSerendip (fullMatrix< double > &nodesXYZ) const
bezierCoeff * getBezierVerticesCoord () const
virtual std::size_t getNumShapeFunctions () const
virtual std::size_t getNumPrimaryShapeFunctions () const
virtual const MVertex * getShapeFunctionNode (int i) const
virtual MVertex * getShapeFunctionNode (int i)
virtual double getEigenvaluesMetric (double u, double v, double w, double values[3]) const
virtual void pnt (double u, double v, double w, SPoint3 &p) const
virtual void pnt (double u, double v, double w, double *p) const
virtual void pnt (const std::vector< double > &sf, SPoint3 &p) const
virtual void primaryPnt (double u, double v, double w, SPoint3 &p)
virtual void xyz2uvw (double xyz[3], double uvw[3]) const
virtual void movePointFromParentSpaceToElementSpace (double &u, double &v, double &w) const
virtual void movePointFromElementSpaceToParentSpace (double &u, double &v, double &w) const
virtual bool isInside (double u, double v, double w) const =0
double interpolate (double val[], double u, double v, double w, int stride=1, int order=-1)
void interpolateGrad (double val[], double u, double v, double w, double f[], int stride=1, double invjac[3][3]=nullptr, int order=-1)
void interpolateCurl (double val[], double u, double v, double w, double f[], int stride=3, int order=-1)
double interpolateDiv (double val[], double u, double v, double w, int stride=3, int order=-1)
virtual void getIntegrationPoints (int pOrder, int *npts, IntPt **pts)
double integrate (double val[], int pOrder, int stride=1, int order=-1)
double integrateCirc (double val[], int edge, int pOrder, int order=-1)
double integrateFlux (double val[], int face, int pOrder, int order=-1)
virtual void writeMSH2 (FILE *fp, double version=1.0, bool binary=false, int num=0, int elementary=1, int physical=1, int parentNum=0, int dom1Num=0, int dom2Num=0, std::vector< short > *ghosts=nullptr)
virtual void writeMSH3 (FILE *fp, bool binary=false, int elementary=1, std::vector< short > *ghosts=nullptr)
virtual void writePOS (FILE *fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor=1.0, int elementary=1)
virtual void writeSTL (FILE *fp, bool binary=false, double scalingFactor=1.0)
virtual void writeX3D (FILE *fp, double scalingFactor=1.0)
virtual void writeVRML (FILE *fp)
virtual void writePLY2 (FILE *fp)
virtual void writeUNV (FILE *fp, int num=0, int elementary=1, int physical=1)
virtual void writeVTK (FILE *fp, bool binary=false, bool bigEndian=false)
virtual void writeMATLAB (FILE *fp, int filetype, int elementary=0, int physical=0, bool binary=false)
virtual void writeTOCHNOG (FILE *fp, int num)
virtual void writeMESH (FILE *fp, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeNEU (FILE *fp, unsigned gambitType, int adjust, int phys=0)
virtual void writeIR3 (FILE *fp, int elementTagType, int num, int elementary, int physical)
virtual void writeBDF (FILE *fp, int format=0, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeDIFF (FILE *fp, int num, bool binary=false, int physical_property=1)
virtual void writeINP (FILE *fp, int num)
virtual void writeKEY (FILE *fp, int pid, int num)
virtual void writeRAD (FILE *fp, int num)
virtual void writeSU2 (FILE *fp, int num)
virtual int getTypeForMSH () const
virtual int getTypeForUNV () const
virtual int getTypeForVTK () const
virtual const char * getStringForTOCHNOG () const
virtual const char * getStringForPOS () const
virtual const char * getStringForBDF () const
virtual const char * getStringForDIFF () const
virtual const char * getStringForINP () const
virtual const char * getStringForKEY () const
virtual const char * getStringForRAD () const
std::string getName ()
virtual std::size_t getNumVerticesForMSH ()
virtual void getVerticesIdForMSH (std::vector< int > &verts)
virtual MElement * copy (std::map< int, MVertex * > &vertexMap, std::map< MElement *, MElement * > &newParents, std::map< MElement *, MElement * > &newDomains)
virtual int numCommonNodesInDualGraph (const MElement *const other) const =0
Static Public Member Functions
static unsigned int getInfoMSH (const int typeMSH, const char **const name=nullptr)
Protected Member Functions
void _getEdgeRep (MVertex *v0, MVertex *v1, double *x, double *y, double *z, SVector3 *n, int faceIndex=-1)
void _getFaceRep (MVertex *v0, MVertex *v1, MVertex *v2, double *x, double *y, double *z, SVector3 *n)
Static Protected Member Functions
static bool _getFaceInfo (const MFace &face, const MFace &other, int &sign, int &rot)
Static Protected Attributes
static double _isInsideTolerance
Private Attributes
std::size_t _num
short _partition
char _visible
Detailed Description
Definition at line 30 of file MElement.h.
Constructor & Destructor Documentation
MElement()
MElement::MElement (std::size_t num = 0, int part = 0)
Definition at line 40 of file MElement.cpp.
~MElement()
virtual MElement::~MElement () inline virtual
Definition at line 61 of file MElement.h.
Member Function Documentation
_getEdgeRep()
void MElement::_getEdgeRep (MVertex * v0, MVertex * v1, double * x, double * y, double * z, SVector3 * n, int faceIndex = -1) protected
Definition at line 107 of file MElement.cpp.
Referenced by MLine::getEdgeRep(), MPolyhedron::getEdgeRep(), MTrihedron::getEdgeRep(), MPyramid::getEdgeRep(), and MPolygon::getEdgeRep().
_getFaceInfo()
bool MElement::_getFaceInfo (const MFace & face, const MFace & other, int & sign, int & rot) static protected
Definition at line 66 of file MElement.cpp.
Referenced by MPrism::getFaceInfo(), MTriangle::getFaceInfo(), MTetrahedron::getFaceInfo(), MQuadrangle::getFaceInfo(), MHexahedron::getFaceInfo(), and MPyramid::getFaceInfo().
_getFaceRep()
void MElement::_getFaceRep (MVertex * v0, MVertex * v1, MVertex * v2, double * x, double * y, double * z, SVector3 * n) protected
Definition at line 146 of file MElement.cpp.
Referenced by MTetrahedron::getFaceRep(), MTriangle::getFaceRep(), MQuadrangle::getFaceRep(), MPolyhedron::getFaceRep(), MHexahedron::getFaceRep(), MTrihedron::getFaceRep(), MPrism::getFaceRep(), MPyramid::getFaceRep(), and MPolygon::getFaceRep().
angleShapeMeasure()
virtual double MElement::angleShapeMeasure () inline virtual
Reimplemented in MQuadrangle, MHexahedron, and MTriangle.
Definition at line 281 of file MElement.h.
barycenter()
SPoint3 MElement::barycenter (bool primary = false) const virtual
Definition at line 520 of file MElement.cpp.
Referenced by addElementsInArrays(), addSmoothNormals(), BarycentricRefineMesh(), GModel::checkMeshCoherence(), drawBarycentricDual(), drawElementLabels(), drawNormals(), drawTangents(), GMSH_CrackPlugin::execute(), getInfoString(), idealJacRange(), MakeMeshConformal(), GMSH_SimplePartitionPlugin::run(), scaledJacRange(), search4Triangle(), signedInvCondNumRange(), and Subdivide().
barycenter_infty()
SPoint3 MElement::barycenter_infty () const virtual
Definition at line 499 of file MElement.cpp.
barycenterUVW()
SPoint3 MElement::barycenterUVW () const virtual
Reimplemented in MQuadrangleN, MQuadrangle9, MQuadrangle8, MHexahedron, MTetrahedron, MPrism, MPyramid, MTriangle, MTrihedron, MQuadrangle, MLine, and MPoint.
Definition at line 550 of file MElement.cpp.
Referenced by elasticitySolver::computeEffectiveStiffness(), and elasticitySolver::computeEffectiveStrain().
copy()
MElement * MElement::copy (std::map< int, MVertex * > & vertexMap, std::map< MElement *, MElement * > & newParents, std::map< MElement *, MElement * > & newDomains) virtual
Definition at line 2486 of file MElement.cpp.
Referenced by copy(), and meshMetric::meshMetric().
distoShapeMeasure()
double MElement::distoShapeMeasure () inline
Definition at line 273 of file MElement.h.
Referenced by checkHighOrderTetrahedron(), checkHighOrderTriangles(), isElementVisible(), and writePOS().
etaShapeMeasure()
virtual double MElement::etaShapeMeasure () inline virtual
Reimplemented in MTetrahedron, MQuadrangle, and MTriangle.
Definition at line 260 of file MElement.h.
fastBarycenter()
SPoint3 MElement::fastBarycenter (bool primary = false) const virtual
Definition at line 536 of file MElement.cpp.
forceNum()
void MElement::forceNum (std::size_t num)
Definition at line 54 of file MElement.cpp.
Referenced by GModel::renumberMeshElements().
gammaShapeMeasure()
virtual double MElement::gammaShapeMeasure () inline virtual
Reimplemented in MTetrahedron, MPrism, MQuadrangle, and MTriangle.
Definition at line 259 of file MElement.h.
Referenced by getInfoString(), isElementVisible(), and writePOS().
getBaseElement() [1/2]
virtual MElement* MElement::getBaseElement () inline virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 240 of file MElement.h.
getBaseElement() [2/2]
virtual const MElement* MElement::getBaseElement () const inline virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 239 of file MElement.h.
getBezierVerticesCoord()
bezierCoeff * MElement::getBezierVerticesCoord () const
Definition at line 998 of file MElement.cpp.
Referenced by MElementBB().
getChild()
virtual MElement* MElement::getChild (int i) const inline virtual
Reimplemented in MPolygon, and MPolyhedron.
Definition at line 235 of file MElement.h.
Referenced by PViewDataGModel::_getNode(), copy(), PViewDataGModel::getNumNodes(), GMSH_DistancePlugin::printView(), and writeMSH2().
getDim()
virtual int MElement::getDim () const pure virtual
Implemented in MPolygon, MPyramid, MTrihedron, MPrism, MTetrahedron, MHexahedron, MQuadrangle, MPolyhedron, MTriangle, MLine, and MPoint.
Referenced by _computeDeterminantAndRegularize(), _getQualityFunctionSpace(), addElementsInArrays(), addExtrudeNormals(), GModel::checkMeshCoherence(), createElementMSH2(), createTopologyFromMesh2D(), drawBarycentricDual(), meshMetric::exportInfo(), MElementOctree::find(), MElementOctree::findAll(), getColorByElement(), PViewDataGModel::getDimension(), getEigenvaluesMetric(), MSubTriangle::getGradShapeFunctions(), MSubLine::getGradShapeFunctions(), getHighOrderFace(), getInfoString(), getJacobian(), getNode(), getVolume(), idealJacRange(), isElementVisible(), MSubTetrahedron::isInside(), MSubTriangle::isInside(), MSubLine::isInside(), MSubPoint::isInside(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), GModel::readDIFF(), GModel::readUNV(), rtree_callback(), jacobianBasedQuality::sampleICNMeasure(), jacobianBasedQuality::sampleIGEMeasure(), setVolumePositive(), signedInvCondNumRange(), GModel::writeDIFF(), writeKEY(), GModel::writeKEY(), writeRAD(), GModel::writeRAD(), and xyz2uvw().
getDomain()
virtual MElement* MElement::getDomain (int i) const inline virtual
Reimplemented in MLineBorder, MPolygonBorder, and MTriangleBorder.
Definition at line 243 of file MElement.h.
Referenced by GModel::_writeMSH2(), buildCutMesh(), and copy().
getEdge()
virtual MEdge MElement::getEdge (int num) const pure virtual
Implemented in MPolygon, MPolyhedron, MPyramid, MTrihedron, MHexahedron, MPrism, MTriangle, MQuadrangle, MTetrahedron, MLine, and MPoint.
Referenced by addExtrudeNormals(), GFace::computeMeshSizeFieldAccuracy(), drawBarycentricDual(), drawTangents(), ensureManifoldFace(), GMSH_BoundaryAnglesPlugin::execute(), getBoundaryFromMesh(), getEdgeSolin(), MSubTriangle::getGradShapeFunctions(), MSubLine::getGradShapeFunctions(), idealJacRange(), makeSimplyConnected(), maxEdge(), minEdge(), EmbeddedCompatibilityTest::operator()(), overlap2D(), setHighOrderFromExistingMesh(), and topoEdge::topoEdge().
getEdgeInfo()
bool MElement::getEdgeInfo (const MEdge & edge, int & ithEdge, int & sign) const virtual
Definition at line 189 of file MElement.cpp.
Referenced by getHighOrderEdge().
getEdgeRep()
virtual void MElement::getEdgeRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) pure virtual
Implemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MTetrahedronN, MPrism18, MQuadrangle9, MTriangleN, MPyramidN, MHexahedron20, MPrism15, MTetrahedron10, MPolygon, MQuadrangle8, MLineN, MTriangle6, MLine3, MPyramid, MHexahedron, MPrism, MTriangle, MQuadrangle, MTrihedron, MPolyhedron, MTetrahedron, MLine, and MPoint.
Referenced by addElementsInArrays().
getEdgeSolin()
virtual MEdge MElement::getEdgeSolin (int numEdge) inline virtual
Reimplemented in MPrism, MHexahedron, MTetrahedron, MQuadrangle, and MTriangle.
Definition at line 186 of file MElement.h.
getEdgeVertices()
virtual void MElement::getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MHexahedron20, MPrism15, MPyramidN, MTetrahedron10, MPolygon, MQuadrangle8, MLineN, MTriangle6, MLine3, MPyramid, MPolyhedron, MTrihedron, MHexahedron, MPrism, MTriangle, MQuadrangle, MTetrahedron, and MLine.
Definition at line 221 of file MElement.h.
Referenced by createTopologyFromMesh2D(), getEdgeVertices(), integrateCirc(), and setHighOrderFromExistingMesh().
getEigenvaluesMetric()
double MElement::getEigenvaluesMetric (double u, double v, double w, double values[3]) const virtual
Definition at line 1022 of file MElement.cpp.
getFace()
virtual MFace MElement::getFace (int num) const pure virtual
Implemented in MPolygon, MPyramid, MPolyhedron, MPrism, MTrihedron, MHexahedron, MTriangle, MQuadrangle, MTetrahedron, MLine, and MPoint.
Referenced by _getEdgeRep(), MPolygon::_initVertices(), addExtrudeNormals(), buildUniqueFaces(), drawBarycentricDual(), drawNormals(), getBoundaryFromMesh(), getFaceSolin(), getFaceVertices(), getGFaceOrientation(), makeSimplyConnected(), EmbeddedCompatibilityTest::operator()(), GModel::setAllVolumesPositiveTopology(), setHighOrderFromExistingMesh(), signedInvCondNumRange(), skewness(), topoFace::topoFace(), and writeSTL().
getFaceInfo()
virtual bool MElement::getFaceInfo (const MFace & face, int & ithFace, int & sign, int & rot) const inline virtual
Reimplemented in MPyramid, MHexahedron, MQuadrangle, MTetrahedron, MPrism, and MTriangle.
Definition at line 205 of file MElement.h.
Referenced by getHighOrderFace().
getFaceRep()
virtual void MElement::getFaceRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) pure virtual
Implemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MTetrahedronN, MPrism18, MQuadrangle9, MTriangleN, MHexahedron20, MPyramidN, MPrism15, MTetrahedron10, MPolygon, MQuadrangle8, MTriangle6, MPyramid, MPrism, MTrihedron, MHexahedron, MPolyhedron, MQuadrangle, MTetrahedron, MTriangle, MLine, and MPoint.
Referenced by addElementsInArrays(), and addSmoothNormals().
getFaceSolin()
virtual MFace MElement::getFaceSolin (int numFace) inline virtual
Reimplemented in MQuadrangle, MPrism, MHexahedron, MTetrahedron, and MTriangle.
Definition at line 213 of file MElement.h.
getFaceVertices()
virtual void MElement::getFaceVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MHexahedron20, MPrism15, MPyramidN, MTetrahedron10, MPolygon, MQuadrangle8, MTriangle6, MPyramid, MTrihedron, MPrism, MPolyhedron, MHexahedron, MTetrahedron, MTriangle, and MQuadrangle.
Definition at line 225 of file MElement.h.
Referenced by createTopologyFromMesh3D(), integrateFlux(), and setHighOrderFromExistingMesh().
getFuncSpaceData()
const FuncSpaceData MElement::getFuncSpaceData (int order = -1, bool serendip = false) const virtual
Definition at line 673 of file MElement.cpp.
Referenced by getBezierVerticesCoord().
getFunctionSpace()
const nodalBasis * MElement::getFunctionSpace (int order = -1, bool serendip = false) const virtual
Reimplemented in MSubPoint, MLineChild, MPolygon, MSubLine, MSubTriangle, MPolyhedron, and MSubTetrahedron.
Definition at line 666 of file MElement.cpp.
Referenced by PViewDataGModel::finalize(), MSubTetrahedron::getFunctionSpace(), MPolyhedron::getFunctionSpace(), MSubTriangle::getFunctionSpace(), MSubLine::getFunctionSpace(), MPolygon::getFunctionSpace(), MLineChild::getFunctionSpace(), MSubPoint::getFunctionSpace(), getGradShapeFunctions(), getHessShapeFunctions(), getHighOrderFace(), getNode(), MPrismN::getNode(), getShapeFunctions(), getThirdDerivativeShapeFunctions(), interpVerticesInExistingEdge(), maxDistToStraight(), MPyramidN::MPyramidN(), elasticityMixedTerm::setPolynomialBasis(), and xyz2uvw().
getGradShapeFunctions()
void MElement::getGradShapeFunctions (double u, double v, double w, double s[][3], int order = -1) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, MSubTetrahedron, MLineChild, MPolygon, MPolyhedron, and MPoint.
Definition at line 468 of file MElement.cpp.
Referenced by elasticityTerm::createData(), helmholtzTerm< double >::elementMatrix(), MSubTetrahedron::getGradShapeFunctions(), MPolyhedron::getGradShapeFunctions(), MSubTriangle::getGradShapeFunctions(), MSubLine::getGradShapeFunctions(), MPolygon::getGradShapeFunctions(), MSubPoint::getGradShapeFunctions(), MLineChild::getGradShapeFunctions(), getJacobian(), getPrimaryJacobian(), ScalarLagrangeFunctionSpaceOfElement::gradf(), ScalarLagrangeFunctionSpace::gradf(), ScalarLagrangeFunctionSpaceOfElement::gradfuvw(), ScalarLagrangeFunctionSpace::gradfuvw(), FuncGradDisc::gradient(), SElement::gradNodalFunctions(), and interpolateGrad().
getHessShapeFunctions()
void MElement::getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order = -1) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, MSubTetrahedron, MLineChild, MPolygon, and MPolyhedron.
Definition at line 478 of file MElement.cpp.
Referenced by MSubTetrahedron::getHessShapeFunctions(), MPolyhedron::getHessShapeFunctions(), MSubTriangle::getHessShapeFunctions(), MSubLine::getHessShapeFunctions(), MPolygon::getHessShapeFunctions(), MSubPoint::getHessShapeFunctions(), MLineChild::getHessShapeFunctions(), ScalarLagrangeFunctionSpaceOfElement::hessfuvw(), and ScalarLagrangeFunctionSpace::hessfuvw().
getHighOrderEdge() [1/2]
MEdgeN MElement::getHighOrderEdge (const MEdge & edge) inline
Definition at line 170 of file MElement.h.
getHighOrderEdge() [2/2]
MEdgeN MElement::getHighOrderEdge (int num, int sign) virtual
Definition at line 171 of file MElement.cpp.
Referenced by getHighOrderEdge().
getHighOrderFace() [1/2]
MFaceN MElement::getHighOrderFace (const MFace & face) inline
Definition at line 197 of file MElement.h.
getHighOrderFace() [2/2]
MFaceN MElement::getHighOrderFace (int num, int sign, int rot) virtual
Reimplemented in MQuadrangleN, MQuadrangle9, MTriangleN, MQuadrangle8, MTriangle6, MQuadrangle, and MTriangle.
Definition at line 207 of file MElement.cpp.
Referenced by getHighOrderFace().
getInfoMSH()
unsigned int MElement::getInfoMSH (const int typeMSH, const char **const name = nullptr) static
Definition at line 2057 of file MElement.cpp.
Referenced by _addElements(), GModel::_readMSH2(), MElementFactory::create(), getInfoString(), getName(), readMSH4Elements(), and writeMSH4Elements().
getInfoString()
std::string MElement::getInfoString (bool multline) virtual
Definition at line 616 of file MElement.cpp.
getInnerRadius()
virtual double MElement::getInnerRadius () inline virtual
Reimplemented in MQuadrangle, MTetrahedron, MHexahedron, MPrism, MTriangle, and MLine.
Definition at line 292 of file MElement.h.
Referenced by addElementsInArrays(), addSmoothNormals(), and getInfoString().
getIntegrationPoints()
virtual void MElement::getIntegrationPoints (int pOrder, int * npts, IntPt ** pts) inline virtual
Reimplemented in MLineBorder, MTriangleBorder, MSubPoint, MLineChild, MPolygon, MSubLine, MSubTriangle, MHexahedron, MPrism, MTetrahedron, MPyramid, MPolyhedron, MQuadrangle, MTriangle, MLine, MSubTetrahedron, and MPoint.
Definition at line 436 of file MElement.h.
Referenced by thermicSolver::computeL2Norm(), elasticitySolver::computeL2Norm(), thermicSolver::computeLagNorm(), GRegion::computeSolidProperties(), elasticityTerm::createData(), helmholtzTerm< double >::elementMatrix(), elasticityMixedTerm::elementMatrix(), distanceTerm::elementVector(), elasticityTerm::elementVector(), GMSH_GaussPointsPlugin::execute(), MSubTetrahedron::getIntegrationPoints(), MSubTriangle::getIntegrationPoints(), MSubLine::getIntegrationPoints(), GaussQuadrature::getIntPoints(), getVolume(), integrate(), and femTerm< scalar >::neumannNodalBC().
getIsAssimilatedSerendipity()
virtual bool MElement::getIsAssimilatedSerendipity () const inline virtual
Definition at line 81 of file MElement.h.
Referenced by MPyramidN::getEdgeRep(), MPyramidN::getFaceRep(), MPyramidN::getFaceVertices(), MTetrahedronN::getFaceVertices(), MHexahedronN::getFaceVertices(), MPyramidN::getNumEdgesRep(), MPyramidN::getNumFacesRep(), MPyramidN::getNumFaceVertices(), MTriangleN::getNumFaceVertices(), MTetrahedronN::getNumFaceVertices(), MQuadrangleN::getNumFaceVertices(), MPrismN::getNumFaceVertices(), MHexahedronN::getNumFaceVertices(), MPyramidN::getNumVolumeVertices(), MTetrahedronN::getNumVolumeVertices(), MPrismN::getNumVolumeVertices(), and MHexahedronN::getNumVolumeVertices().
getIsOnlySerendipity()
virtual bool MElement::getIsOnlySerendipity () const inline virtual
Definition at line 86 of file MElement.h.
Referenced by createTopologyFromMesh2D(), and createTopologyFromMesh3D().
getJacobian() [1/5]
double MElement::getJacobian (const fullMatrix< double > & gsf, double jac[3][3]) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 868 of file MElement.cpp.
Referenced by _myGetFaceRep(), qmTriangle::angles(), qmQuadrangle::angles(), thermicSolver::computeL2Norm(), elasticitySolver::computeL2Norm(), thermicSolver::computeLagNorm(), GRegion::computeSolidProperties(), helmholtzTerm< double >::elementMatrix(), elasticityTerm::elementMatrix(), elasticityMixedTerm::elementMatrix(), distanceTerm::elementVector(), elasticityTerm::elementVector(), ScalarTermConstant< T2 >::get(), BilinearTermBase::get(), LinearTermBase< T2 >::get(), LaplaceTerm< T1, T1 >::get(), IsotropicElasticTerm::get(), LoadTerm< T1 >::get(), LagrangeMultiplierTerm< T1 >::get(), LagMultTerm::get(), LoadTermOnBorder< T1 >::get(), getEigenvaluesMetric(), MSubTriangle::getGradShapeFunctions(), MSubLine::getGradShapeFunctions(), MSubTetrahedron::getIntegrationPoints(), MPolyhedron::getIntegrationPoints(), MSubTriangle::getIntegrationPoints(), MSubLine::getIntegrationPoints(), MPolygon::getIntegrationPoints(), MSubPoint::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), MSubTetrahedron::getJacobian(), MSubTriangle::getJacobian(), MSubLine::getJacobian(), getJacobian(), MSubPoint::getJacobian(), getJacobianDeterminant(), ScalarLagrangeFunctionSpaceOfElement::gradf(), ScalarLagrangeFunctionSpace::gradf(), FuncGradDisc::gradient(), interpolateCurl(), interpolateDiv(), interpolateGrad(), femTerm< scalar >::neumannNodalBC(), and xyz2uvw().
getJacobian() [2/5]
double MElement::getJacobian (const std::vector< SVector3 > & gsf, double * jac) const virtual
Definition at line 908 of file MElement.cpp.
getJacobian() [3/5]
double MElement::getJacobian (const std::vector< SVector3 > & gsf, double jac[3][3]) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 888 of file MElement.cpp.
getJacobian() [4/5]
double MElement::getJacobian (double u, double v, double w, double jac[3][3]) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 845 of file MElement.cpp.
getJacobian() [5/5]
double MElement::getJacobian (double u, double v, double w, fullMatrix< double > & j) const
Definition at line 926 of file MElement.cpp.
getJacobianDeterminant()
double MElement::getJacobianDeterminant (double u, double v, double w) const inline
Definition at line 376 of file MElement.h.
Referenced by getVolume(), and integrate().
getJacobianFuncSpace()
const JacobianBasis * MElement::getJacobianFuncSpace (int orderElement = -1) const virtual
Reimplemented in MSubPoint, MLineChild, MPolygon, MSubLine, MSubTriangle, MPolyhedron, MSubTetrahedron, and MPoint.
Definition at line 679 of file MElement.cpp.
Referenced by MSubTetrahedron::getJacobianFuncSpace(), MPolyhedron::getJacobianFuncSpace(), MSubTriangle::getJacobianFuncSpace(), MSubLine::getJacobianFuncSpace(), MPolygon::getJacobianFuncSpace(), MLineChild::getJacobianFuncSpace(), MSubPoint::getJacobianFuncSpace(), getSignedJacobian(), idealJacRange(), jacobianBasedQuality::minMaxJacobianDeterminant(), qmTriangle::NCJRange(), qmQuadrangle::NCJRange(), and scaledJacRange().
getJacobianFuncSpaceData()
const FuncSpaceData MElement::getJacobianFuncSpaceData (int orderElement = -1) const virtual
Definition at line 686 of file MElement.cpp.
getName()
std::string MElement::getName ()
Definition at line 2472 of file MElement.cpp.
Referenced by _getQualityFunctionSpace(), and jacobianBasedQuality::minMaxJacobianDeterminant().
getNode()
void MElement::getNode (int num, double & u, double & v, double & w) const virtual
Reimplemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MHexahedron20, MPrism15, MPyramidN, MTetrahedron10, MQuadrangle8, MTriangle6, MLineN, MLine3, MTetrahedron, MPrism, MTriangle, MHexahedron, MPyramid, MTrihedron, MQuadrangle, MLine, and MPoint.
Definition at line 448 of file MElement.cpp.
Referenced by barycenterUVW(), MLine3::getNode(), MLineN::getNode(), MTriangle6::getNode(), MQuadrangle8::getNode(), MTetrahedron10::getNode(), MPyramidN::getNode(), MPrism15::getNode(), MHexahedron20::getNode(), MTriangleN::getNode(), MQuadrangle9::getNode(), MTetrahedronN::getNode(), MPrism18::getNode(), MQuadrangleN::getNode(), MHexahedron27::getNode(), and MHexahedronN::getNode().
getNodesCoord()
void MElement::getNodesCoord (fullMatrix< double > & nodesXYZ) const
Definition at line 969 of file MElement.cpp.
Referenced by getNodesCoordNonSerendip(), getSignedJacobian(), idealJacRange(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), jacobianBasedQuality::minMaxJacobianDeterminant(), jacobianBasedQuality::sampleICNMeasure(), jacobianBasedQuality::sampleIGEMeasure(), jacobianBasedQuality::sampleJacobianDeterminant(), scaledJacRange(), and signedInvCondNumRange().
getNodesCoordNonSerendip()
void MElement::getNodesCoordNonSerendip (fullMatrix< double > & nodesXYZ) const
Definition at line 980 of file MElement.cpp.
getNum()
virtual std::size_t MElement::getNum () const inline virtual
Definition at line 68 of file MElement.h.
Referenced by OctreePost::_getValue(), GMSH_ShowNeighborElementsPlugin::_init(), addToMap(), GModel::alignPeriodicBoundaries(), buildCutMesh(), checkConformity(), GModel::checkMeshCoherence(), copy(), drawElementLabels(), GMSH_NewViewPlugin::elementData(), GMSH_GaussPointsPlugin::execute(), FixPeriodicMesh(), getEdgeInfo(), MTriangle::getFaceInfo(), MPrism::getFaceInfo(), MTetrahedron::getFaceInfo(), MQuadrangle::getFaceInfo(), MHexahedron::getFaceInfo(), MPyramid::getFaceInfo(), getInfoString(), FunctionSpaceBase::getKeysOnVertex(), GModel::getMeshElementIndex(), PViewDataGModel::getNumValues(), PViewDataGModel::getValue(), GModel::makeDiscreteFacesSimplyConnected(), GModel::makeDiscreteRegionsSimplyConnected(), compareTet4Ptr::operator()(), MElementPtrLessThan::operator()(), MElementPtrEqual::operator()(), MElementPtrHash::operator()(), GModel::rebuildMeshElementCache(), GModel::renumberMeshElements(), GModel::setMeshElementIndex(), PViewDataGModel::setValue(), PViewDataGModel::skipElement(), PViewDataGModel::smooth(), jacobianBasedQuality::testAllMeasures(), GModel::writeINP(), GModel::writeKEY(), PViewDataGModel::writeMSH(), writeMSH3(), writeMSH4Elements(), GModel::writeNEU(), writePOS(), GModel::writeRAD(), GModel::writeTOCHNOG(), and GModel::writeUNV().
getNumChildren()
virtual int MElement::getNumChildren () const inline virtual
Reimplemented in MPolygon, and MPolyhedron.
Definition at line 234 of file MElement.h.
Referenced by PViewDataGModel::_getNode(), copy(), PViewDataGModel::getNumNodes(), GMSH_DistancePlugin::printView(), and writeMSH2().
getNumEdges()
virtual int MElement::getNumEdges () const pure virtual
Implemented in MPolygon, MPolyhedron, MPyramid, MTrihedron, MHexahedron, MPrism, MTriangle, MQuadrangle, MTetrahedron, MLine, and MPoint.
Referenced by GFace::computeMeshSizeFieldAccuracy(), createTopologyFromMesh2D(), drawBarycentricDual(), ensureManifoldFace(), GMSH_BoundaryAnglesPlugin::execute(), getBoundaryFromMesh(), getEdgeInfo(), getEdgeVertices(), PViewDataGModel::getNumEdges(), idealJacRange(), integrateCirc(), makeSimplyConnected(), maxEdge(), minEdge(), overlap2D(), and setHighOrderFromExistingMesh().
getNumEdgesRep()
virtual int MElement::getNumEdgesRep (bool curved) pure virtual
Implemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MTetrahedronN, MPrism18, MQuadrangle9, MTriangleN, MPyramidN, MHexahedron20, MPrism15, MTetrahedron10, MPolygon, MQuadrangle8, MLineN, MTriangle6, MLine3, MPyramid, MHexahedron, MPrism, MTriangle, MQuadrangle, MTrihedron, MPolyhedron, MTetrahedron, MLine, and MPoint.
Referenced by addElementsInArrays().
getNumEdgeVertices()
virtual int MElement::getNumEdgeVertices () const inline virtual
Reimplemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MHexahedron20, MPrism15, MPyramidN, MTetrahedron10, MQuadrangle8, MLineN, MTriangle6, and MLine3.
Definition at line 155 of file MElement.h.
Referenced by getNumPrimaryVertices(), and setHighOrderFromExistingMesh().
getNumFaces()
virtual int MElement::getNumFaces () pure virtual
Implemented in MPolygon, MPyramid, MPolyhedron, MTrihedron, MHexahedron, MPrism, MTriangle, MQuadrangle, MTetrahedron, MLine, and MPoint.
Referenced by buildUniqueFaces(), createTopologyFromMesh3D(), drawBarycentricDual(), getBoundaryFromMesh(), getFaceVertices(), integrateFlux(), makeSimplyConnected(), GModel::setAllVolumesPositiveTopology(), and skewness().
getNumFacesRep()
virtual int MElement::getNumFacesRep (bool curved) pure virtual
Implemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MTetrahedronN, MPrism18, MQuadrangle9, MTriangleN, MHexahedron20, MPyramidN, MPrism15, MTetrahedron10, MPolygon, MQuadrangle8, MTriangle6, MPyramid, MPrism, MTrihedron, MHexahedron, MPolyhedron, MQuadrangle, MTetrahedron, MTriangle, MLine, and MPoint.
Referenced by addElementsInArrays(), and addSmoothNormals().
getNumFaceVertices()
virtual int MElement::getNumFaceVertices () const inline virtual
Reimplemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MPyramidN, and MPolygon.
Definition at line 156 of file MElement.h.
Referenced by getNumPrimaryVertices().
getNumPrimaryShapeFunctions()
virtual std::size_t MElement::getNumPrimaryShapeFunctions () const inline virtual
Reimplemented in MSubPoint, MPolygon, MSubLine, MSubTriangle, MPolyhedron, and MSubTetrahedron.
Definition at line 388 of file MElement.h.
Referenced by MSubTetrahedron::getNumPrimaryShapeFunctions(), MPolyhedron::getNumPrimaryShapeFunctions(), MSubTriangle::getNumPrimaryShapeFunctions(), MSubLine::getNumPrimaryShapeFunctions(), MPolygon::getNumPrimaryShapeFunctions(), MSubPoint::getNumPrimaryShapeFunctions(), getPrimaryJacobian(), and primaryPnt().
getNumPrimaryVertices()
std::size_t MElement::getNumPrimaryVertices () const inline
Definition at line 160 of file MElement.h.
Referenced by qmTriangle::angles(), barycenter(), GMSH_CrackPlugin::execute(), fastBarycenter(), getFaceVertices(), getHighOrderEdge(), PViewDataGModel::getNode(), PViewDataGModel::getNumNodes(), getNumPrimaryShapeFunctions(), getVolumeVertices(), GMSH_DistancePlugin::printView(), setBLData(), setHighOrderFromExistingMesh(), and signedInvCondNumRange().
getNumShapeFunctions()
virtual std::size_t MElement::getNumShapeFunctions () const inline virtual
Reimplemented in MSubPoint, MPolygon, MSubLine, MSubTriangle, MPolyhedron, and MSubTetrahedron.
Definition at line 387 of file MElement.h.
Referenced by elasticityTerm::createData(), helmholtzTerm< double >::elementMatrix(), elasticityTerm::elementMatrix(), distanceTerm::elementVector(), laplaceTerm::elementVector(), elasticityTerm::elementVector(), ScalarLagrangeFunctionSpaceOfElement::f(), ScalarLagrangeFunctionSpace::f(), ScalarLagrangeFunctionSpace::fuvw(), MSubLine::getGradShapeFunctions(), getJacobian(), elasticityTerm::getLocalDofC(), elasticityTerm::getLocalDofR(), ScalarLagrangeFunctionSpaceOfElement::getNumKeys(), ScalarLagrangeFunctionSpace::getNumKeys(), MSubTetrahedron::getNumShapeFunctions(), MPolyhedron::getNumShapeFunctions(), MSubTriangle::getNumShapeFunctions(), MSubLine::getNumShapeFunctions(), MPolygon::getNumShapeFunctions(), MSubPoint::getNumShapeFunctions(), ScalarLagrangeFunctionSpaceOfElement::gradf(), ScalarLagrangeFunctionSpace::gradf(), ScalarLagrangeFunctionSpaceOfElement::gradfuvw(), ScalarLagrangeFunctionSpace::gradfuvw(), FuncGradDisc::gradient(), ScalarLagrangeFunctionSpaceOfElement::hessfuvw(), ScalarLagrangeFunctionSpace::hessfuvw(), interpolate(), interpolateGrad(), femTerm< scalar >::neumannNodalBC(), FuncGradDisc::operator()(), pnt(), helmholtzTerm< double >::sizeOfC(), elasticityTerm::sizeOfC(), helmholtzTerm< double >::sizeOfR(), elasticityTerm::sizeOfR(), and xyz2uvw().
getNumVertices()
virtual std::size_t MElement::getNumVertices () const pure virtual
Implemented in MHexahedronN, MPrismN, MQuadrangleN, MHexahedron27, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MPrism15, MHexahedron20, MPyramidN, MTetrahedron10, MPolygon, MLineN, MQuadrangle8, MTriangle6, MLine3, MPyramid, MTrihedron, MPrism, MTetrahedron, MHexahedron, MQuadrangle, MTriangle, MPolyhedron, MLine, and MPoint.
Referenced by PViewDataGModel::_getNode(), OctreePost::_getValue(), GMSH_ShowNeighborElementsPlugin::_init(), _isModelOkForTopologicalOpti(), _removeTwoQuadsNodes(), addExtrudeNormals(), GFace::alignElementsWithMaster(), barycenter(), barycenter_infty(), barycenterUVW(), GRegion::bounds(), GEdge::bounds(), GFace::bounds(), GModel::checkMeshCoherence(), elasticitySolver::computeDisplacementError(), elasticitySolver::computeEffectiveStiffness(), elasticitySolver::computeEffectiveStrain(), copy(), drawVerticesPerElement(), GMSH_CrackPlugin::execute(), GMSH_InvisiblePlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_DistancePlugin::execute(), meshMetric::exportInfo(), fastBarycenter(), fillv_(), FixNodalDofs(), FixPeriodicMesh(), getColorByElement(), getExtrudedVertices(), getGFaceNormalFromBary(), getGFaceNormalFromVert(), getHighOrderFace(), getInfoString(), getJacobian(), GModel::getMeshVerticesForPhysicalGroup(), getNodesCoord(), getNodesCoordNonSerendip(), SElement::getNumNodalShapeFunctions(), SElement::getNumNodalTestFunctions(), PViewDataGModel::getNumNodes(), getNumPrimaryVertices(), getNumShapeFunctions(), getNumVerticesForMSH(), getSignedJacobian(), getVertices(), GModel::indexMeshVertices(), groupOfElements::insert(), intersectClipPlane(), MElementBB(), MElementCentroid(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), jacobianBasedQuality::minMaxJacobianDeterminant(), meshMetric::operator()(), parametricCoordinates(), GMSH_DistancePlugin::printView(), GModel::pruneMeshVertexAssociations(), GModel::readPLY(), GModel::removeDuplicateMeshVertices(), GModel::renumberMeshVertices(), jacobianBasedQuality::sampleICNMeasure(), jacobianBasedQuality::sampleIGEMeasure(), jacobianBasedQuality::sampleJacobianDeterminant(), setBLData(), PViewDataGModel::smooth(), surfaceFaceUV(), writeBDF(), writeDIFF(), GModel::writeDIFF(), writeINP(), GModel::writeINP(), writeIR3(), writeKEY(), GModel::writeKEY(), writeMATLAB(), writeMESH(), writeMSH4Elements(), writeNEU(), writePLY2(), writePOS(), writeRAD(), GModel::writeRAD(), writeSTL(), writeSU2(), writeTOCHNOG(), GModel::writeTOCHNOG(), writeUNV(), GModel::writeUNV(), writeVRML(), writeVTK(), and writeX3D().
getNumVerticesForMSH()
virtual std::size_t MElement::getNumVerticesForMSH () inline virtual
Reimplemented in MPolygon, and MPolyhedron.
Definition at line 503 of file MElement.h.
Referenced by getVerticesIdForMSH(), and writeMSH2().
getNumVolumeVertices()
virtual int MElement::getNumVolumeVertices () const inline virtual
Reimplemented in MHexahedronN, MPrismN, MHexahedron27, MTetrahedronN, MPyramidN, and MPolyhedron.
Definition at line 157 of file MElement.h.
Referenced by getNumPrimaryVertices().
getOuterRadius()
virtual double MElement::getOuterRadius () inline virtual
Reimplemented in MQuadrangle, MTetrahedron, and MTriangle.
Definition at line 297 of file MElement.h.
Referenced by getInfoString().
getParent()
virtual MElement* MElement::getParent () const inline virtual
Reimplemented in MLineBorder, MPolygonBorder, MTriangleBorder, MSubPoint, MLineChild, MSubLine, MPolygon, MSubTriangle, MPolyhedron, and MSubTetrahedron.
Definition at line 231 of file MElement.h.
Referenced by buildCutMesh(), elasticitySolver::computeDisplacementError(), thermicSolver::computeLagNorm(), copy(), ScalarLagrangeFunctionSpaceOfElement::f(), ScalarLagrangeFunctionSpace::f(), xFemFunctionSpace< T >::f(), FilteredFunctionSpace< T, F >::f(), FilterElementsCutByLevelSet::FilterElementsCutByLevelSet(), ScalarLagrangeFunctionSpace::fuvw(), IsotropicElasticTerm::get(), LoadTerm< T1 >::get(), xFemFunctionSpace< T >::getKeys(), FilteredFunctionSpace< T, F >::getKeys(), ScalarLagrangeFunctionSpace::getNumKeys(), xFemFunctionSpace< T >::getNumKeys(), FilteredFunctionSpace< T, F >::getNumKeys(), SElement::getNumNodalShapeFunctions(), SElement::getNumNodalTestFunctions(), MTriangleBorder::getParent(), MPolygonBorder::getParent(), MLineBorder::getParent(), SElement::getVertex(), ScalarLagrangeFunctionSpaceOfElement::gradf(), ScalarLagrangeFunctionSpace::gradf(), xFemFunctionSpace< T >::gradf(), FilteredFunctionSpace< T, F >::gradf(), ScalarLagrangeFunctionSpaceOfElement::gradfuvw(), ScalarLagrangeFunctionSpace::gradfuvw(), FuncGradDisc::gradient(), ScalarLagrangeFunctionSpaceOfElement::hessfuvw(), ScalarLagrangeFunctionSpace::hessfuvw(), groupOfElements::insert(), movePointFromElementSpaceToParentSpace(), movePointFromParentSpaceToElementSpace(), FuncGradDisc::operator()(), writeElementsMSH(), and writeMSH3().
getPartition()
virtual int MElement::getPartition () const inline virtual
Definition at line 92 of file MElement.h.
Referenced by buildCutMesh(), drawElementLabels(), GMSH_CrackPlugin::execute(), getColorByElement(), getInfoString(), getNumElementsMSH(), GModel::makeDiscreteFacesSimplyConnected(), GModel::makeDiscreteRegionsSimplyConnected(), Less_Partition::operator()(), setHighOrder(), and writeMSH3().
getPolynomialOrder()
virtual int MElement::getPolynomialOrder () const inline virtual
Reimplemented in MHexahedronN, MPrismN, MQuadrangleN, MHexahedron27, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MPrism15, MHexahedron20, MPyramidN, MTetrahedron10, MLineN, MQuadrangle8, MTriangle6, and MLine3.
Definition at line 78 of file MElement.h.
Referenced by _getQualityFunctionSpace(), addElementsInArrays(), addSmoothNormals(), thermicSolver::computeL2Norm(), elasticitySolver::computeL2Norm(), thermicSolver::computeLagNorm(), GRegion::computeSolidProperties(), elasticityTerm::createData(), createTopologyFromMesh2D(), createTopologyFromMesh3D(), helmholtzTerm< double >::elementMatrix(), elasticityMixedTerm::elementMatrix(), distanceTerm::elementVector(), elasticityTerm::elementVector(), PViewDataGModel::finalize(), getBezierVerticesCoord(), getEdgeVertices(), getHighOrderEdge(), getHighOrderFace(), getInfoString(), GaussQuadrature::getIntPoints(), getJacobianFuncSpaceData(), getNodesCoordNonSerendip(), getOrder(), getVolume(), integrateCirc(), integrateFlux(), MElementBB(), femTerm< scalar >::neumannNodalBC(), elasticityMixedTerm::setPolynomialBasis(), signedInvGradErrorRange(), and xyz2uvw().
getPrimaryJacobian()
double MElement::getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 939 of file MElement.cpp.
Referenced by qmTriangle::angles(), qmQuadrangle::angles(), MSubTetrahedron::getPrimaryJacobian(), MSubTriangle::getPrimaryJacobian(), MSubLine::getPrimaryJacobian(), and MSubPoint::getPrimaryJacobian().
getShapeFunctionNode() [1/2]
virtual MVertex* MElement::getShapeFunctionNode (int i) inline virtual
Reimplemented in MSubPoint, MPolygon, MSubLine, MSubTriangle, MPolyhedron, and MSubTetrahedron.
Definition at line 396 of file MElement.h.
getShapeFunctionNode() [2/2]
virtual const MVertex* MElement::getShapeFunctionNode (int i) const inline virtual
Reimplemented in MSubPoint, MPolygon, MSubLine, MSubTriangle, MPolyhedron, and MSubTetrahedron.
Definition at line 392 of file MElement.h.
Referenced by laplaceTerm::elementVector(), getJacobian(), helmholtzTerm< double >::getLocalDofC(), elasticityTerm::getLocalDofC(), helmholtzTerm< double >::getLocalDofR(), elasticityTerm::getLocalDofR(), elasticityMixedTerm::getLocalDofR(), getNodesCoord(), getPrimaryJacobian(), MSubTetrahedron::getShapeFunctionNode(), MPolyhedron::getShapeFunctionNode(), MSubTriangle::getShapeFunctionNode(), MSubLine::getShapeFunctionNode(), MPolygon::getShapeFunctionNode(), MSubPoint::getShapeFunctionNode(), FuncGradDisc::gradient(), femTerm< scalar >::neumannNodalBC(), FuncGradDisc::operator()(), pnt(), primaryPnt(), and xyz2uvw().
getShapeFunctions()
void MElement::getShapeFunctions (double u, double v, double w, double s[], int order = -1) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, MSubTetrahedron, MLineChild, MPolygon, MPolyhedron, and MPoint.
Definition at line 458 of file MElement.cpp.
Referenced by helmholtzTerm< double >::elementMatrix(), elasticityMixedTerm::elementMatrix(), distanceTerm::elementVector(), ScalarLagrangeFunctionSpaceOfElement::f(), ScalarLagrangeFunctionSpace::f(), ScalarLagrangeFunctionSpace::fuvw(), MSubTetrahedron::getShapeFunctions(), MPolyhedron::getShapeFunctions(), MSubTriangle::getShapeFunctions(), MSubLine::getShapeFunctions(), MPolygon::getShapeFunctions(), MSubPoint::getShapeFunctions(), MLineChild::getShapeFunctions(), SElement::gradNodalFunctions(), interpolate(), femTerm< scalar >::neumannNodalBC(), SElement::nodalFunctions(), FuncGradDisc::operator()(), pnt(), primaryPnt(), and xyz2uvw().
getSignedJacobian()
void MElement::getSignedJacobian (fullVector< double > & jacobian, int o = -1) const
Definition at line 961 of file MElement.cpp.
getStringForBDF()
virtual const char* MElement::getStringForBDF () const inline virtual
Reimplemented in MQuadrangle9, MHexahedron20, MPrism15, MTetrahedron10, MQuadrangle8, MTriangle6, MPyramid, MPrism, MHexahedron, MQuadrangle, MTetrahedron, MTriangle, and MLine.
Definition at line 493 of file MElement.h.
Referenced by writeBDF().
getStringForDIFF()
virtual const char* MElement::getStringForDIFF () const inline virtual
Reimplemented in MHexahedron27, MQuadrangle9, MHexahedron20, MTetrahedron10, MQuadrangle8, MTriangle6, MHexahedron, MQuadrangle, MTetrahedron, and MTriangle.
Definition at line 494 of file MElement.h.
Referenced by writeDIFF(), and GModel::writeDIFF().
getStringForINP()
virtual const char* MElement::getStringForINP () const inline virtual
Reimplemented in MHexahedron27, MQuadrangle9, MHexahedron20, MPrism15, MTetrahedron10, MQuadrangle8, MTriangle6, MLine3, MPrism, MHexahedron, MQuadrangle, MTetrahedron, MTriangle, and MLine.
Definition at line 495 of file MElement.h.
getStringForKEY()
virtual const char* MElement::getStringForKEY () const inline virtual
Reimplemented in MHexahedron27, MHexahedron20, MPrism15, MTetrahedron10, MQuadrangle8, MTriangle6, MLine3, MPrism, MHexahedron, MTriangle, MQuadrangle, MTetrahedron, and MLine.
Definition at line 496 of file MElement.h.
getStringForPOS()
virtual const char* MElement::getStringForPOS () const inline virtual
Reimplemented in MPrismN, MHexahedron27, MQuadrangleN, MPrism18, MQuadrangle9, MTetrahedron10, MTriangle6, MLine3, MPyramid, MPrism, MHexahedron, MQuadrangle, MTetrahedron, MTriangle, MLine, and MPoint.
Definition at line 492 of file MElement.h.
Referenced by writePOS().
getStringForRAD()
virtual const char* MElement::getStringForRAD () const inline virtual
Reimplemented in MHexahedron27, MHexahedron20, MTetrahedron10, MLine3, MPrism, MHexahedron, MTriangle, MQuadrangle, MTetrahedron, and MLine.
Definition at line 497 of file MElement.h.
getStringForTOCHNOG()
virtual const char* MElement::getStringForTOCHNOG () const inline virtual
Reimplemented in MHexahedron27, MQuadrangle9, MTetrahedron10, MTriangle6, MLine3, MHexahedron, MTriangle, MQuadrangle, MTetrahedron, and MLine.
Definition at line 491 of file MElement.h.
Referenced by writeTOCHNOG().
getThirdDerivativeShapeFunctions()
void MElement::getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order = -1) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 488 of file MElement.cpp.
Referenced by MSubTetrahedron::getThirdDerivativeShapeFunctions(), MSubTriangle::getThirdDerivativeShapeFunctions(), MSubLine::getThirdDerivativeShapeFunctions(), and MSubPoint::getThirdDerivativeShapeFunctions().
getTolerance()
double MElement::getTolerance () const
Definition at line 61 of file MElement.cpp.
Referenced by MPoint::isInside(), MLine::isInside(), MSubTetrahedron::isInside(), MTrihedron::isInside(), MTriangle::isInside(), MQuadrangle::isInside(), MPyramid::isInside(), MPrism::isInside(), MTetrahedron::isInside(), MHexahedron::isInside(), MSubTriangle::isInside(), MSubLine::isInside(), and MSubPoint::isInside().
getType()
virtual int MElement::getType () const pure virtual
Implemented in MPolygon, MPyramid, MTrihedron, MPolyhedron, MPrism, MHexahedron, MTetrahedron, MTriangle, MQuadrangle, MLine, and MPoint.
Referenced by _getQualityFunctionSpace(), GModel::_readMSH2(), checkConformity(), computeLevelset(), createTopologyFromMesh3D(), GMSH_CrackPlugin::execute(), GMSH_DistancePlugin::execute(), FuncSpaceData::FuncSpaceData(), getBezierVerticesCoord(), getColorByElement(), getEigenvaluesMetric(), getFaceVertices(), getFunctionSpace(), getHighOrderFace(), getIntegrationPoints(), getJacobianFuncSpace(), getJacobianFuncSpaceData(), getNodesCoordNonSerendip(), PViewDataGModel::getType(), getVolumeVertices(), integrateFlux(), GModel::makeDiscreteFacesSimplyConnected(), GModel::makeDiscreteRegionsSimplyConnected(), jacobianBasedQuality::minIGEMeasure(), MLine::numCommonNodesInDualGraph(), MTriangle::numCommonNodesInDualGraph(), MQuadrangle::numCommonNodesInDualGraph(), MTrihedron::numCommonNodesInDualGraph(), MPyramid::numCommonNodesInDualGraph(), MTetrahedron::numCommonNodesInDualGraph(), MHexahedron::numCommonNodesInDualGraph(), MPrism::numCommonNodesInDualGraph(), GMSH_DistancePlugin::printView(), GModel::readDIFF(), GModel::readPLY(), GModel::readUNV(), jacobianBasedQuality::sampleIGEMeasure(), jacobianBasedQuality::sampleJacobianDeterminant(), jacobianBasedQuality::testAllMeasures(), writeSTL(), and writeX3D().
getTypeForMSH()
virtual int MElement::getTypeForMSH () const inline virtual
Reimplemented in MHexahedronN, MPrismN, MHexahedron27, MQuadrangleN, MLineBorder, MPolygonBorder, MPrism18, MTetrahedronN, MTriangleBorder, MQuadrangle9, MTriangleN, MSubPoint, MLineChild, MHexahedron20, MPrism15, MPyramidN, MTetrahedron10, MPolygon, MSubLine, MQuadrangle8, MTriangle6, MLineN, MLine3, MSubTriangle, MPyramid, MTrihedron, MPolyhedron, MPrism, MHexahedron, MTetrahedron, MTriangle, MQuadrangle, MLine, MSubTetrahedron, and MPoint.
Definition at line 488 of file MElement.h.
Referenced by copy(), elasticityTerm::createData(), elasticityTerm::elementMatrix(), GMSH_CrackPlugin::execute(), ScalarLagrangeFunctionSpaceOfElement::f(), LoadTermOnBorder< T1 >::get(), getFunctionSpace(), getInfoString(), getIsAssimilatedSerendipity(), getIsOnlySerendipity(), getJacobianFuncSpace(), getName(), PViewDataGModel::getNode(), PViewDataGModel::getNumNodes(), ScalarLagrangeFunctionSpaceOfElement::gradf(), ScalarLagrangeFunctionSpaceOfElement::gradfuvw(), ScalarLagrangeFunctionSpaceOfElement::hessfuvw(), GModel::makeDiscreteFacesSimplyConnected(), GModel::makeDiscreteRegionsSimplyConnected(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), jacobianBasedQuality::sampleICNMeasure(), jacobianBasedQuality::sampleIGEMeasure(), jacobianBasedQuality::sampleJacobianDeterminant(), signedInvCondNumRange(), storePairMATLAB(), jacobianBasedQuality::testAllMeasures(), writeElementsMATLAB(), writeMATLAB(), writeMESH(), writeMSH2(), and writeMSH3().
getTypeForUNV()
virtual int MElement::getTypeForUNV () const inline virtual
Reimplemented in MHexahedron20, MPrism15, MTetrahedron10, MQuadrangle8, MTriangle6, MLine3, MPrism, MHexahedron, MTetrahedron, MTriangle, MQuadrangle, and MLine.
Definition at line 489 of file MElement.h.
Referenced by writeUNV().
getTypeForVTK()
virtual int MElement::getTypeForVTK () const inline virtual
Reimplemented in MQuadrangleN, MHexahedron27, MPrism18, MTriangleN, MQuadrangle9, MHexahedron20, MPrism15, MTetrahedron10, MQuadrangle8, MTriangle6, MLine3, MPyramid, MPrism, MHexahedron, MQuadrangle, MTetrahedron, MTriangle, MLine, and MPoint.
Definition at line 490 of file MElement.h.
Referenced by writeSU2(), and writeVTK().
getValidity()
int MElement::getValidity ()
Definition at line 600 of file MElement.cpp.
getVertex() [1/2]
virtual const MVertex* MElement::getVertex (int num) const pure virtual
Implemented in MHexahedronN, MPrismN, MQuadrangleN, MHexahedron27, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MPrism15, MHexahedron20, MPyramidN, MTetrahedron10, MPolygon, MLineN, MQuadrangle8, MTriangle6, MLine3, MPyramid, MTrihedron, MPrism, MPolyhedron, MTetrahedron, MHexahedron, MQuadrangle, MTriangle, MLine, and MPoint.
Referenced by PViewDataGModel::_getNode(), OctreePost::_getValue(), GMSH_ShowNeighborElementsPlugin::_init(), _isModelOkForTopologicalOpti(), _recombineIntoQuads(), _removeTwoQuadsNodes(), addExtrudeNormals(), GFace::alignElementsWithMaster(), GModel::alignPeriodicBoundaries(), barycenter(), barycenter_infty(), GRegion::bounds(), GEdge::bounds(), GFace::bounds(), GModel::checkMeshCoherence(), elasticitySolver::computeDisplacementError(), elasticitySolver::computeEffectiveStiffness(), elasticitySolver::computeEffectiveStrain(), computeLevelset(), copy(), drawVerticesPerElement(), edge_angle::edge_angle(), GMSH_CrackPlugin::execute(), GMSH_InvisiblePlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_DistancePlugin::execute(), meshMetric::exportInfo(), fastBarycenter(), fillv_(), FilterElementsCutByLevelSet::FilterElementsCutByLevelSet(), discreteFace::firstDer(), FixNodalDofs(), FixPeriodicMesh(), getAdditionalEntities(), backgroundMesh::getAngle(), getColorByElement(), getEdgeInfo(), getExtrudedVertices(), getGFaceNormalFromBary(), getGFaceNormalFromVert(), getHighOrderEdge(), getHighOrderFace(), getInfoString(), GModel::getMeshVerticesForPhysicalGroup(), PViewDataGModel::getNode(), getShapeFunctionNode(), backgroundMesh::getSmoothness(), SElement::getVertex(), getVertexBDF(), getVertexDIFF(), getVertexINP(), getVertexKEY(), getVertexMATLAB(), getVertexNEU(), getVertexRAD(), getVertexTOCHNOG(), getVertexUNV(), getVertexVTK(), getVertices(), getVerticesIdForMSH(), idealJacRange(), GlobalBackgroundMesh::importGModelMeshes(), GModel::indexMeshVertices(), groupOfElements::insert(), intersectClipPlane(), maxDistToStraight(), MElementBB(), MElementCentroid(), MYxyz2uvw(), backgroundMesh::operator()(), meshMetric::operator()(), gLevelsetYarn::operator()(), parametricCoordinates(), GMSH_DistancePlugin::printView(), GModel::pruneMeshVertexAssociations(), GModel::readPLY(), RecombineTriangle::RecombineTriangle(), GModel::removeDuplicateMeshVertices(), GModel::renumberMeshVertices(), scaledJacRange(), meshMetric::scaleMetric(), setBLData(), signedInvCondNumRange(), PViewDataGModel::smooth(), GModel::writeDIFF(), GModel::writeINP(), writeIR3(), GModel::writeKEY(), writeMATLAB(), writeMESH(), writeMSH2(), writeMSH4Elements(), writePLY2(), writePOS(), GModel::writeRAD(), writeSTL(), GModel::writeTOCHNOG(), GModel::writeUNV(), writeVRML(), and writeX3D().
getVertex() [2/2]
virtual MVertex* MElement::getVertex (int num) pure virtual
Implemented in MHexahedronN, MPrismN, MQuadrangleN, MHexahedron27, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MPrism15, MHexahedron20, MPyramidN, MTetrahedron10, MPolygon, MLineN, MQuadrangle8, MTriangle6, MLine3, MPyramid, MTrihedron, MPrism, MTetrahedron, MHexahedron, MPolyhedron, MQuadrangle, MTriangle, MLine, and MPoint.
getVertexBDF()
virtual MVertex* MElement::getVertexBDF (int num) inline virtual
Reimplemented in MPrism15, MHexahedron20, and MTetrahedron10.
Definition at line 133 of file MElement.h.
Referenced by writeBDF().
getVertexDIFF()
virtual MVertex* MElement::getVertexDIFF (int num) inline virtual
Reimplemented in MHexahedron27, MQuadrangle9, MHexahedron20, MTetrahedron10, MQuadrangle8, MHexahedron, and MQuadrangle.
Definition at line 136 of file MElement.h.
Referenced by writeDIFF().
getVertexInfo()
virtual void MElement::getVertexInfo (const MVertex * vertex, int & ithVertex) const inline virtual
Reimplemented in MLine.
Definition at line 115 of file MElement.h.
getVertexINP()
virtual MVertex* MElement::getVertexINP (int num) inline virtual
Reimplemented in MHexahedron27, MPrism15, MHexahedron20, MTetrahedron10, and MLine3.
Definition at line 139 of file MElement.h.
Referenced by writeINP().
getVertexKEY()
virtual MVertex* MElement::getVertexKEY (int num) inline virtual
Reimplemented in MHexahedron27, MPrism15, MHexahedron20, MTetrahedron10, and MLine3.
Definition at line 142 of file MElement.h.
Referenced by writeKEY().
getVertexMATLAB()
virtual MVertex* MElement::getVertexMATLAB (int num) inline virtual
Definition at line 127 of file MElement.h.
Referenced by writeMATLAB().
getVertexNEU()
virtual MVertex* MElement::getVertexNEU (int num) inline virtual
Reimplemented in MHexahedron, and MPyramid.
Definition at line 148 of file MElement.h.
Referenced by writeNEU().
getVertexRAD()
virtual MVertex* MElement::getVertexRAD (int num) inline virtual
Reimplemented in MHexahedron20, MTetrahedron10, and MLine3.
Definition at line 145 of file MElement.h.
Referenced by writeRAD().
getVertexTOCHNOG()
virtual MVertex* MElement::getVertexTOCHNOG (int num) inline virtual
Definition at line 130 of file MElement.h.
Referenced by writeTOCHNOG().
getVertexUNV()
virtual MVertex* MElement::getVertexUNV (int num) inline virtual
Reimplemented in MPrism15, MHexahedron20, MTetrahedron10, MQuadrangle8, MTriangle6, and MLine3.
Definition at line 121 of file MElement.h.
Referenced by writeUNV().
getVertexVTK()
virtual MVertex* MElement::getVertexVTK (int num) inline virtual
Reimplemented in MPrism18, MHexahedron27, MHexahedron20, MPrism15, MTetrahedron10, and MPrism.
Definition at line 124 of file MElement.h.
Referenced by writeSU2(), and writeVTK().
getVertices()
void MElement::getVertices (std::vector< MVertex * > & verts) inline
Definition at line 103 of file MElement.h.
Referenced by GMSH_CrackPlugin::execute(), getEdgeVertices(), getFaceVertices(), getHighOrderFace(), getVolumeVertices(), GModel::makeDiscreteFacesSimplyConnected(), GModel::makeDiscreteRegionsSimplyConnected(), MElementPtrLessThanVertices::operator()(), and setHighOrderFromExistingMesh().
getVerticesIdForMSH()
void MElement::getVerticesIdForMSH (std::vector< int > & verts) virtual
Reimplemented in MPolygon, and MPolyhedron.
Definition at line 2479 of file MElement.cpp.
Referenced by writeMSH2(), and writeMSH3().
getVisibility()
char MElement::getVisibility () const virtual
Definition at line 165 of file MElement.cpp.
Referenced by getColorByElement(), isElementVisible(), and PViewDataGModel::skipElement().
getVolume()
double MElement::getVolume () virtual
Reimplemented in MTriangle, MQuadrangle, MTetrahedron, MTrihedron, MPolyhedron, and MLine.
Definition at line 567 of file MElement.cpp.
Referenced by GModel::checkMeshCoherence(), elasticitySolver::computeEffectiveStiffness(), elasticitySolver::computeEffectiveStrain(), getInfoString(), MQuadrangle::getVolume(), MTriangle::getVolume(), getVolumeSign(), and meshMetric::scaleMetric().
getVolumeSign()
int MElement::getVolumeSign () virtual
Reimplemented in MTetrahedron, MPrism, MHexahedron, MPyramid, and MTrihedron.
Definition at line 580 of file MElement.cpp.
Referenced by elasticitySolver::computeEffectiveStiffness(), elasticitySolver::computeEffectiveStrain(), and setVolumePositive().
idealJacRange()
void MElement::idealJacRange (double & jmin, double & jmax, GEntity * ge = nullptr) virtual
Definition at line 337 of file MElement.cpp.
integrate()
double MElement::integrate (double val[], int pOrder, int stride = 1, int order = -1)
Definition at line 1279 of file MElement.cpp.
Referenced by integrateCirc(), and integrateFlux().
integrateCirc()
double MElement::integrateCirc (double val[], int edge, int pOrder, int order = -1)
Definition at line 1296 of file MElement.cpp.
integrateFlux()
double MElement::integrateFlux (double val[], int face, int pOrder, int order = -1)
Definition at line 1322 of file MElement.cpp.
interpolate()
double MElement::interpolate (double val[], double u, double v, double w, int stride = 1, int order = -1)
Definition at line 1216 of file MElement.cpp.
Referenced by OctreePost::_getValue(), PViewDataGModel::getNode(), cartesianBox< scalar >::getValueContainingPoint(), integrate(), and meshMetric::operator()().
interpolateCurl()
void MElement::interpolateCurl (double val[], double u, double v, double w, double f[], int stride = 3, int order = -1)
Definition at line 1253 of file MElement.cpp.
interpolateDiv()
double MElement::interpolateDiv (double val[], double u, double v, double w, int stride = 3, int order = -1)
Definition at line 1267 of file MElement.cpp.
interpolateGrad()
void MElement::interpolateGrad (double val[], double u, double v, double w, double f[], int stride = 1, double invjac[3][3] = nullptr, int order = -1)
Definition at line 1230 of file MElement.cpp.
Referenced by OctreePost::_getValue(), elasticitySolver::computeEffectiveStiffness(), elasticitySolver::computeEffectiveStrain(), backgroundMesh::getSmoothness(), interpolateCurl(), and interpolateDiv().
isInside()
virtual bool MElement::isInside (double u, double v, double w) const pure virtual
Implemented in MLineBorder, MTriangleBorder, MSubPoint, MLineChild, MPolygon, MSubLine, MSubTriangle, MHexahedron, MTetrahedron, MPrism, MPolyhedron, MPyramid, MQuadrangle, MTriangle, MTrihedron, MSubTetrahedron, MLine, and MPoint.
Referenced by MElementInEle().
maxDistToStraight()
double MElement::maxDistToStraight () const
Definition at line 256 of file MElement.cpp.
Referenced by addElementsInArrays(), and addSmoothNormals().
maxEdge()
double MElement::maxEdge () virtual
Definition at line 246 of file MElement.cpp.
Referenced by OctreePost::_getValue(), getInfoString(), backgroundMesh::getSmoothness(), and isElementVisible().
minEdge()
double MElement::minEdge () virtual
Definition at line 236 of file MElement.cpp.
Referenced by getInfoString().
minIsotropyMeasure()
double MElement::minIsotropyMeasure (bool knownValid = false, bool reversedOk = false)
Definition at line 280 of file MElement.cpp.
minScaledJacobian()
double MElement::minScaledJacobian (bool knownValid = false, bool reversedOk = false)
Definition at line 289 of file MElement.cpp.
minSICNShapeMeasure()
double MElement::minSICNShapeMeasure () inline
Definition at line 261 of file MElement.h.
Referenced by isElementVisible(), and writePOS().
minSIGEShapeMeasure()
double MElement::minSIGEShapeMeasure () inline
Definition at line 267 of file MElement.h.
Referenced by isElementVisible(), and writePOS().
movePointFromElementSpaceToParentSpace()
void MElement::movePointFromElementSpaceToParentSpace (double & u, double & v, double & w) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 1202 of file MElement.cpp.
movePointFromParentSpaceToElementSpace()
void MElement::movePointFromParentSpaceToElementSpace (double & u, double & v, double & w) const virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 1188 of file MElement.cpp.
Referenced by ScalarLagrangeFunctionSpaceOfElement::f(), LoadTermOnBorder< T1 >::get(), ScalarLagrangeFunctionSpaceOfElement::gradf(), ScalarLagrangeFunctionSpaceOfElement::gradfuvw(), and ScalarLagrangeFunctionSpaceOfElement::hessfuvw().
numCommonNodesInDualGraph()
virtual int MElement::numCommonNodesInDualGraph (const MElement *const other) const pure virtual
Implemented in MPolygon, MPrism, MHexahedron, MTetrahedron, MPyramid, MPolyhedron, MTrihedron, MQuadrangle, MTriangle, MLine, and MPoint.
numEdge2numVertex()
virtual int MElement::numEdge2numVertex (int numEdge, int numVert) const inline virtual
Reimplemented in MPyramid, MHexahedron, MPrism, MTriangle, MQuadrangle, and MTetrahedron.
Definition at line 179 of file MElement.h.
Referenced by getEdgeInfo(), and getHighOrderEdge().
ownsParent()
virtual bool MElement::ownsParent () const inline virtual
Reimplemented in MSubPoint, MLineChild, MSubLine, MPolygon, MSubTriangle, MPolyhedron, and MSubTetrahedron.
Definition at line 236 of file MElement.h.
Referenced by buildCutMesh(), and copy().
pnt() [1/3]
void MElement::pnt (const std::vector< double > & sf, SPoint3 & p) const virtual
Definition at line 1102 of file MElement.cpp.
pnt() [2/3]
void MElement::pnt (double u, double v, double w, double * p) const virtual
Definition at line 1086 of file MElement.cpp.
pnt() [3/3]
void MElement::pnt (double u, double v, double w, SPoint3 & p) const virtual
Definition at line 1072 of file MElement.cpp.
Referenced by _myGetEdgeRep(), _myGetFaceRep(), thermicSolver::computeL2Norm(), elasticitySolver::computeL2Norm(), thermicSolver::computeLagNorm(), GRegion::computeSolidProperties(), helmholtzTerm< double >::elementMatrix(), GMSH_GaussPointsPlugin::execute(), xFemFunctionSpace< T >::f(), LoadTerm< T1 >::get(), LoadTermOnBorder< T1 >::get(), getBezierVerticesCoord(), MLine3::getEdgeRep(), MLineN::getEdgeRep(), MPyramidN::getEdgeRep(), MPolyhedron::getIntegrationPoints(), MPolygon::getIntegrationPoints(), MLineChild::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), getNodesCoordNonSerendip(), xFemFunctionSpace< T >::gradf(), SElement::gradNodalFunctions(), interpVerticesInExistingEdge(), MSubTetrahedron::isInside(), MSubTriangle::isInside(), MSubLine::isInside(), MSubPoint::isInside(), MSubTetrahedron::movePointFromElementSpaceToParentSpace(), MSubTriangle::movePointFromElementSpaceToParentSpace(), MSubLine::movePointFromElementSpaceToParentSpace(), movePointFromElementSpaceToParentSpace(), MSubPoint::movePointFromElementSpaceToParentSpace(), MSubTetrahedron::movePointFromParentSpaceToElementSpace(), MSubTriangle::movePointFromParentSpaceToElementSpace(), MSubLine::movePointFromParentSpaceToElementSpace(), movePointFromParentSpaceToElementSpace(), MSubPoint::movePointFromParentSpaceToElementSpace(), femTerm< scalar >::neumannNodalBC(), SElement::nodalFunctions(), and Subdivide().
primaryPnt()
void MElement::primaryPnt (double u, double v, double w, SPoint3 & p) virtual
Definition at line 1114 of file MElement.cpp.
reverse()
virtual void MElement::reverse () inline virtual
Reimplemented in MHexahedronN, MPrismN, MQuadrangleN, MHexahedron27, MPrism18, MTetrahedronN, MTriangleN, MQuadrangle9, MHexahedron20, MPrism15, MPyramidN, MTetrahedron10, MQuadrangle8, MPolygon, MTriangle6, MLineN, MQuadrangle, MPyramid, MHexahedron, MPrism, MTriangle, MTetrahedron, MTrihedron, MPolyhedron, and MLine.
Definition at line 308 of file MElement.h.
Referenced by FixPeriodicMesh(), orientMeshGEdge::operator()(), orientMeshGFace::operator()(), PViewDataGModel::reverseElement(), GModel::setAllVolumesPositiveTopology(), setVolumePositive(), writeBDF(), writeDIFF(), writeIR3(), writeMATLAB(), writeMESH(), writeMSH2(), writeNEU(), and writeUNV().
scaledJacRange()
void MElement::scaledJacRange (double & jmin, double & jmax, GEntity * ge = nullptr) const virtual
Definition at line 298 of file MElement.cpp.
Referenced by distoShapeMeasure().
setDomain()
virtual void MElement::setDomain (MElement * e, int i) inline virtual
Reimplemented in MLineBorder, MPolygonBorder, and MTriangleBorder.
Definition at line 244 of file MElement.h.
Referenced by copy().
setParent()
virtual void MElement::setParent (MElement * p, bool owner = false) inline virtual
Reimplemented in MSubPoint, MLineChild, MSubLine, MPolygon, MSubTriangle, MPolyhedron, and MSubTetrahedron.
Definition at line 232 of file MElement.h.
setPartition()
virtual void MElement::setPartition (int num) inline virtual
Definition at line 93 of file MElement.h.
Referenced by GModel::_readMSH4(), modifyInitialMeshForBoundaryLayers(), and GMSH_SimplePartitionPlugin::run().
setVertex()
virtual void MElement::setVertex (int num, MVertex * v) inline virtual
Reimplemented in MHexahedronN, MPrismN, MQuadrangleN, MHexahedron27, MPrism18, MTetrahedronN, MQuadrangle9, MTriangleN, MPrism15, MHexahedron20, MPyramidN, MTetrahedron10, MLineN, MQuadrangle8, MTriangle6, MLine3, MPyramid, MTrihedron, MPrism, MTetrahedron, MHexahedron, MQuadrangle, MTriangle, MLine, and MPoint.
Definition at line 109 of file MElement.h.
Referenced by GMSH_CrackPlugin::execute(), and GModel::removeDuplicateMeshVertices().
setVisibility()
virtual void MElement::setVisibility (char val) inline virtual
Definition at line 97 of file MElement.h.
Referenced by GMSH_ShowNeighborElementsPlugin::_init(), GMSH_ShowNeighborElementsPlugin::_showLayers(), and GMSH_InvisiblePlugin::execute().
setVolumePositive()
bool MElement::setVolumePositive () virtual
Reimplemented in MTrihedron.
Definition at line 591 of file MElement.cpp.
Referenced by buildCutMesh().
signedInvCondNumRange()
void MElement::signedInvCondNumRange (double & iCNMin, double & iCNMax, GEntity * ge = nullptr) virtual
Definition at line 389 of file MElement.cpp.
Referenced by getInfoString(), and minSICNShapeMeasure().
signedInvGradErrorRange()
void MElement::signedInvGradErrorRange (double & minSIGE, double & maxSIGE) virtual
Definition at line 440 of file MElement.cpp.
Referenced by getInfoString(), and minSIGEShapeMeasure().
skewness()
double MElement::skewness ()
Definition at line 2751 of file MElement.cpp.
updateParent()
virtual void MElement::updateParent (GModel * gm) inline virtual
Reimplemented in MSubPoint, MSubLine, MSubTriangle, and MSubTetrahedron.
Definition at line 233 of file MElement.h.
writeBDF()
void MElement::writeBDF (FILE * fp, int format = 0, int elementTagType = 1, int elementary = 1, int physical = 0) virtual
Definition at line 1818 of file MElement.cpp.
writeDIFF()
void MElement::writeDIFF (FILE * fp, int num, bool binary = false, int physical_property = 1) virtual
Definition at line 1877 of file MElement.cpp.
Referenced by GModel::writeDIFF().
writeINP()
void MElement::writeINP (FILE * fp, int num) virtual
Definition at line 1898 of file MElement.cpp.
writeIR3()
void MElement::writeIR3 (FILE * fp, int elementTagType, int num, int elementary, int physical) virtual
Definition at line 1800 of file MElement.cpp.
writeKEY()
void MElement::writeKEY (FILE * fp, int pid, int num) virtual
Definition at line 1912 of file MElement.cpp.
writeMATLAB()
void MElement::writeMATLAB (FILE * fp, int filetype, int elementary = 0, int physical = 0, bool binary = false) virtual
Definition at line 1711 of file MElement.cpp.
Referenced by writeElementsMATLAB().
writeMESH()
void MElement::writeMESH (FILE * fp, int elementTagType = 1, int elementary = 1, int physical = 0) virtual
Definition at line 1766 of file MElement.cpp.
writeMSH2()
void MElement::writeMSH2 (FILE * fp, double version = 1.0, bool binary = false, int num = 0, int elementary = 1, int physical = 1, int parentNum = 0, int dom1Num = 0, int dom2Num = 0, std::vector< short > * ghosts = nullptr) virtual
Definition at line 1368 of file MElement.cpp.
Referenced by writeMSH2().
writeMSH3()
void MElement::writeMSH3 (FILE * fp, bool binary = false, int elementary = 1, std::vector< short > * ghosts = nullptr) virtual
Definition at line 1473 of file MElement.cpp.
Referenced by writeElementMSH().
writeNEU()
void MElement::writeNEU (FILE * fp, unsigned gambitType, int adjust, int phys = 0) virtual
Definition at line 1786 of file MElement.cpp.
writePLY2()
void MElement::writePLY2 (FILE * fp) virtual
Definition at line 1661 of file MElement.cpp.
writePOS()
void MElement::writePOS (FILE * fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor = 1.0, int elementary = 1) virtual
Definition at line 1515 of file MElement.cpp.
Referenced by _removeTwoQuadsNodes().
writeRAD()
void MElement::writeRAD (FILE * fp, int num) virtual
Definition at line 1959 of file MElement.cpp.
writeSTL()
void MElement::writeSTL (FILE * fp, bool binary = false, double scalingFactor = 1.0) virtual
Definition at line 1593 of file MElement.cpp.
writeSU2()
void MElement::writeSU2 (FILE * fp, int num) virtual
Definition at line 2046 of file MElement.cpp.
writeTOCHNOG()
void MElement::writeTOCHNOG (FILE * fp, int num) virtual
Definition at line 1676 of file MElement.cpp.
writeUNV()
void MElement::writeUNV (FILE * fp, int num = 0, int elementary = 1, int physical = 1) virtual
Definition at line 1741 of file MElement.cpp.
Referenced by GModel::writeUNV().
writeVRML()
void MElement::writeVRML (FILE * fp) virtual
Definition at line 1669 of file MElement.cpp.
writeVTK()
void MElement::writeVTK (FILE * fp, bool binary = false, bool bigEndian = false) virtual
Definition at line 1689 of file MElement.cpp.
writeX3D()
void MElement::writeX3D (FILE * fp, double scalingFactor = 1.0) virtual
Definition at line 1643 of file MElement.cpp.
xyz2uvw()
void MElement::xyz2uvw (double xyz[3], double uvw[3]) const virtual
Reimplemented in MTetrahedronN, MSubPoint, MTriangleN, MTetrahedron10, MSubLine, MTriangle6, MSubTriangle, MTetrahedron, MSubTetrahedron, and MTriangle.
Definition at line 1128 of file MElement.cpp.
Referenced by OctreePost::_getValue(), backgroundMesh::getAngle(), MPolyhedron::getIntegrationPoints(), MPolygon::getIntegrationPoints(), MLineChild::getIntegrationPoints(), MSubPoint::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), GModel::getMeshElementByCoord(), cartesianBox< scalar >::getValueContainingPoint(), FuncGradDisc::gradient(), MSubTetrahedron::isInside(), MPolyhedron::isInside(), MSubTriangle::isInside(), MSubLine::isInside(), MPolygon::isInside(), MLineChild::isInside(), MSubPoint::isInside(), MTriangleBorder::isInside(), MLineBorder::isInside(), MElementInEle(), MSubTetrahedron::movePointFromElementSpaceToParentSpace(), MSubTriangle::movePointFromElementSpaceToParentSpace(), MSubLine::movePointFromElementSpaceToParentSpace(), movePointFromElementSpaceToParentSpace(), MSubPoint::movePointFromElementSpaceToParentSpace(), MSubTetrahedron::movePointFromParentSpaceToElementSpace(), MSubTriangle::movePointFromParentSpaceToElementSpace(), MSubLine::movePointFromParentSpaceToElementSpace(), movePointFromParentSpaceToElementSpace(), MSubPoint::movePointFromParentSpaceToElementSpace(), FuncGradDisc::operator()(), backgroundMesh::operator()(), meshMetric::operator()(), discreteFace::trianglePosition(), MSubTetrahedron::xyz2uvw(), MSubTriangle::xyz2uvw(), MTriangle6::xyz2uvw(), MSubLine::xyz2uvw(), MTetrahedron10::xyz2uvw(), MTriangleN::xyz2uvw(), MSubPoint::xyz2uvw(), and MTetrahedronN::xyz2uvw().
Member Data Documentation
_isInsideTolerance
double MElement::_isInsideTolerance static protected
Definition at line 44 of file MElement.h.
_num
std::size_t MElement::_num private
Definition at line 35 of file MElement.h.
Referenced by forceNum(), getNum(), MElement(), writeBDF(), writeMSH2(), writeNEU(), and writeUNV().
_partition
short MElement::_partition private
Definition at line 37 of file MElement.h.
Referenced by copy(), getPartition(), MElement(), setPartition(), writeBDF(), writeIR3(), writeMESH(), and writeMSH2().
_visible
char MElement::_visible private
Definition at line 39 of file MElement.h.
Referenced by getVisibility(), and setVisibility().
The documentation for this class was generated from the following files:
src/geo/MElement.h
src/geo/MElement.cpp