gmsh-TingyuanDoc: MEdge Class Reference
MEdge Class Reference
#include <MEdge.h>
Public Member Functions
MEdge ()
MEdge (MVertex *v0, MVertex *v1)
std::size_t getNumVertices () const
MVertex * getVertex (std::size_t i) const
MVertex * getSortedVertex (std::size_t i) const
MVertex * getMinVertex () const
MVertex * getMaxVertex () const
int computeCorrespondence (MEdge &other)
bool alignWith (MEdge &other)
SVector3 scaledTangent () const
SVector3 tangent () const
double length () const
SVector3 normal () const
SPoint3 barycenter () const
SPoint3 interpolate (const double &t) const
bool isInside (MVertex *v) const
Private Attributes
MVertex * _v [2]
char _si [2]
Detailed Description
Definition at line 14 of file MEdge.h.
Constructor & Destructor Documentation
MEdge() [1/2]
MEdge::MEdge () inline
Definition at line 20 of file MEdge.h.
MEdge() [2/2]
MEdge::MEdge (MVertex * v0, MVertex * v1) inline
Definition at line 25 of file MEdge.h.
Member Function Documentation
alignWith()
bool MEdge::alignWith (MEdge & other) inline
Definition at line 53 of file MEdge.h.
barycenter()
SPoint3 MEdge::barycenter () const inline
Definition at line 96 of file MEdge.h.
Referenced by drawBarycentricDual(), and drawVoronoiDual().
computeCorrespondence()
int MEdge::computeCorrespondence (MEdge & other) inline
Definition at line 44 of file MEdge.h.
Referenced by GModel::alignPeriodicBoundaries(), and alignWith().
getMaxVertex()
MVertex* MEdge::getMaxVertex () const inline
Definition at line 42 of file MEdge.h.
Referenced by operator!=(), MEdgeHash::operator()(), MEdgeDataLessThan::operator()(), MEdgeLessThan::operator()(), and operator==().
getMinVertex()
MVertex* MEdge::getMinVertex () const inline
Definition at line 41 of file MEdge.h.
Referenced by operator!=(), MEdgeHash::operator()(), MEdgeDataLessThan::operator()(), MEdgeLessThan::operator()(), and operator==().
getNumVertices()
std::size_t MEdge::getNumVertices () const inline
Definition at line 38 of file MEdge.h.
getSortedVertex()
MVertex* MEdge::getSortedVertex (std::size_t i) const inline
Definition at line 40 of file MEdge.h.
Referenced by edgeContainerB::H().
getVertex()
MVertex* MEdge::getVertex (std::size_t i) const inline
Definition at line 39 of file MEdge.h.
Referenced by MPolygon::_initVertices(), _relocate(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), classifyFaces(), computeCorrespondence(), computeEdgeCut(), computeParametrization(), drawVoronoiDual(), GMSH_MeshSubEntitiesPlugin::execute(), MElement::getEdgeInfo(), MPolyhedron::getEdgeRep(), MTrihedron::getEdgeRep(), MPyramid::getEdgeRep(), MPolygon::getEdgeRep(), MTriangle::getInnerRadius(), MPrism::getInnerRadius(), MTetrahedron::getInnerRadius(), MTriangle::getOuterRadius(), intersectEdge2d(), MElement::maxEdge(), MElement::minEdge(), RecombineTriangle::RecombineTriangle(), setHighOrderFromExistingMesh(), setLcs(), and topoEdge::topoEdge().
interpolate()
SPoint3 MEdge::interpolate (const double & t) const inline
Definition at line 97 of file MEdge.h.
Referenced by barycenter().
isInside()
bool MEdge::isInside (MVertex * v) const
Definition at line 16 of file MEdge.cpp.
Referenced by MPolygon::_initVertices().
length()
double MEdge::length () const inline
Definition at line 76 of file MEdge.h.
Referenced by MElement::idealJacRange().
normal()
SVector3 MEdge::normal () const inline
Definition at line 82 of file MEdge.h.
Referenced by MElement::_getEdgeRep(), MLine3::getEdgeRep(), and MLineN::getEdgeRep().
scaledTangent()
SVector3 MEdge::scaledTangent () const inline
Definition at line 64 of file MEdge.h.
tangent()
SVector3 MEdge::tangent () const inline
Definition at line 69 of file MEdge.h.
Referenced by addExtrudeNormals(), drawTangents(), MSubTriangle::getGradShapeFunctions(), MSubLine::getGradShapeFunctions(), and normal().
Member Data Documentation
_si
char MEdge::_si[2] private
Definition at line 17 of file MEdge.h.
Referenced by alignWith(), getMaxVertex(), getMinVertex(), getSortedVertex(), and MEdge().
_v
MVertex* MEdge::_v[2] private
Definition at line 16 of file MEdge.h.
Referenced by alignWith(), computeCorrespondence(), getMaxVertex(), getMinVertex(), getSortedVertex(), getVertex(), interpolate(), isInside(), length(), MEdge(), scaledTangent(), and tangent().
The documentation for this class was generated from the following files:
src/geo/MEdge.h
src/geo/MEdge.cpp