gmsh-TingyuanDoc: MPrism Class Reference
MPrism Class Reference
#include <MPrism.h>
Public Member Functions
MPrism (MVertex *v0, MVertex *v1, MVertex *v2, MVertex *v3, MVertex *v4, MVertex *v5, int num=0, int part=0)
MPrism (const std::vector< MVertex * > &v, int num=0, int part=0)
~MPrism ()
virtual int getDim () const
virtual std::size_t getNumVertices () const
virtual double getInnerRadius ()
virtual MVertex * getVertex (int num)
virtual const MVertex * getVertex (int num) const
virtual void setVertex (int num, MVertex *v)
virtual int getNumEdges () const
virtual MEdge getEdge (int num) const
virtual int numEdge2numVertex (int numEdge, int numVert) const
virtual int getNumEdgesRep (bool curved)
virtual void getEdgeRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getEdgeVertices (const int num, std::vector< MVertex * > &v) const
virtual int getNumFaces ()
virtual bool getFaceInfo (const MFace &face, int &ithFace, int &sign, int &rot) const
virtual MFace getFace (int num) const
virtual int getNumFacesRep (bool curved)
virtual void getFaceRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getFaceVertices (const int num, std::vector< MVertex * > &v) const
virtual int getType () const
virtual int getTypeForMSH () const
virtual int getTypeForUNV () const
virtual int getTypeForVTK () const
virtual const char * getStringForPOS () const
virtual const char * getStringForBDF () const
virtual const char * getStringForINP () const
virtual const char * getStringForKEY () const
virtual const char * getStringForRAD () const
virtual void reverse ()
virtual double gammaShapeMeasure ()
virtual int getVolumeSign ()
virtual void getNode (int num, double &u, double &v, double &w) const
virtual SPoint3 barycenterUVW () const
virtual bool isInside (double u, double v, double w) const
virtual void getIntegrationPoints (int pOrder, int *npts, IntPt **pts)
virtual int numCommonNodesInDualGraph (const MElement *const other) const
virtual MEdge getEdgeSolin (int num)
virtual MFace getFaceSolin (int num)
virtual MVertex * getVertexVTK (int num)
Public Member Functions inherited from MElement
MElement (std::size_t num=0, int part=0)
virtual ~MElement ()
double getTolerance () const
virtual std::size_t getNum () const
void forceNum (std::size_t num)
virtual int getPolynomialOrder () const
virtual bool getIsAssimilatedSerendipity () const
virtual bool getIsOnlySerendipity () const
virtual int getPartition () const
virtual void setPartition (int num)
virtual char getVisibility () const
virtual void setVisibility (char val)
void getVertices (std::vector< MVertex * > &verts)
virtual void getVertexInfo (const MVertex *vertex, int &ithVertex) const
virtual MVertex * getVertexUNV (int num)
virtual MVertex * getVertexMATLAB (int num)
virtual MVertex * getVertexTOCHNOG (int num)
virtual MVertex * getVertexBDF (int num)
virtual MVertex * getVertexDIFF (int num)
virtual MVertex * getVertexINP (int num)
virtual MVertex * getVertexKEY (int num)
virtual MVertex * getVertexRAD (int num)
virtual MVertex * getVertexNEU (int num)
virtual int getNumEdgeVertices () const
virtual int getNumFaceVertices () const
virtual int getNumVolumeVertices () const
std::size_t getNumPrimaryVertices () const
virtual MEdgeN getHighOrderEdge (int num, int sign)
MEdgeN getHighOrderEdge (const MEdge &edge)
virtual bool getEdgeInfo (const MEdge &edge, int &ithEdge, int &sign) const
virtual MFaceN getHighOrderFace (int num, int sign, int rot)
MFaceN getHighOrderFace (const MFace &face)
virtual MElement * getParent () const
virtual void setParent (MElement *p, bool owner=false)
virtual void updateParent (GModel *gm)
virtual int getNumChildren () const
virtual MElement * getChild (int i) const
virtual bool ownsParent () const
virtual const MElement * getBaseElement () const
virtual MElement * getBaseElement ()
virtual MElement * getDomain (int i) const
virtual void setDomain (MElement *e, int i)
virtual double maxEdge ()
virtual double minEdge ()
double maxDistToStraight () const
double skewness ()
virtual double etaShapeMeasure ()
double minSICNShapeMeasure ()
double minSIGEShapeMeasure ()
double distoShapeMeasure ()
double minIsotropyMeasure (bool knownValid=false, bool reversedOk=false)
double minScaledJacobian (bool knownValid=false, bool reversedOk=false)
virtual double angleShapeMeasure ()
virtual void scaledJacRange (double &jmin, double &jmax, GEntity *ge=nullptr) const
virtual void idealJacRange (double &jmin, double &jmax, GEntity *ge=nullptr)
virtual void signedInvCondNumRange (double &iCNMin, double &iCNMax, GEntity *ge=nullptr)
virtual void signedInvGradErrorRange (double &minSIGE, double &maxSIGE)
virtual double getOuterRadius ()
virtual SPoint3 barycenter (bool primary=false) const
virtual SPoint3 fastBarycenter (bool primary=false) const
virtual SPoint3 barycenter_infty () const
virtual double getVolume ()
virtual bool setVolumePositive ()
int getValidity ()
virtual std::string getInfoString (bool multline)
virtual const nodalBasis * getFunctionSpace (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getFuncSpaceData (int order=-1, bool serendip=false) const
virtual const JacobianBasis * getJacobianFuncSpace (int orderElement=-1) const
virtual const FuncSpaceData getJacobianFuncSpaceData (int orderElement=-1) const
virtual void getShapeFunctions (double u, double v, double w, double s[], int order=-1) const
virtual void getGradShapeFunctions (double u, double v, double w, double s[][3], int order=-1) const
virtual void getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order=-1) const
virtual void getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order=-1) const
virtual double getJacobian (const fullMatrix< double > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double *jac) const
virtual double getJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobian (double u, double v, double w, fullMatrix< double > &j) const
virtual double getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobianDeterminant (double u, double v, double w) const
void getSignedJacobian (fullVector< double > &jacobian, int o=-1) const
void getNodesCoord (fullMatrix< double > &nodesXYZ) const
void getNodesCoordNonSerendip (fullMatrix< double > &nodesXYZ) const
bezierCoeff * getBezierVerticesCoord () const
virtual std::size_t getNumShapeFunctions () const
virtual std::size_t getNumPrimaryShapeFunctions () const
virtual const MVertex * getShapeFunctionNode (int i) const
virtual MVertex * getShapeFunctionNode (int i)
virtual double getEigenvaluesMetric (double u, double v, double w, double values[3]) const
virtual void pnt (double u, double v, double w, SPoint3 &p) const
virtual void pnt (double u, double v, double w, double *p) const
virtual void pnt (const std::vector< double > &sf, SPoint3 &p) const
virtual void primaryPnt (double u, double v, double w, SPoint3 &p)
virtual void xyz2uvw (double xyz[3], double uvw[3]) const
virtual void movePointFromParentSpaceToElementSpace (double &u, double &v, double &w) const
virtual void movePointFromElementSpaceToParentSpace (double &u, double &v, double &w) const
double interpolate (double val[], double u, double v, double w, int stride=1, int order=-1)
void interpolateGrad (double val[], double u, double v, double w, double f[], int stride=1, double invjac[3][3]=nullptr, int order=-1)
void interpolateCurl (double val[], double u, double v, double w, double f[], int stride=3, int order=-1)
double interpolateDiv (double val[], double u, double v, double w, int stride=3, int order=-1)
double integrate (double val[], int pOrder, int stride=1, int order=-1)
double integrateCirc (double val[], int edge, int pOrder, int order=-1)
double integrateFlux (double val[], int face, int pOrder, int order=-1)
virtual void writeMSH2 (FILE *fp, double version=1.0, bool binary=false, int num=0, int elementary=1, int physical=1, int parentNum=0, int dom1Num=0, int dom2Num=0, std::vector< short > *ghosts=nullptr)
virtual void writeMSH3 (FILE *fp, bool binary=false, int elementary=1, std::vector< short > *ghosts=nullptr)
virtual void writePOS (FILE *fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor=1.0, int elementary=1)
virtual void writeSTL (FILE *fp, bool binary=false, double scalingFactor=1.0)
virtual void writeX3D (FILE *fp, double scalingFactor=1.0)
virtual void writeVRML (FILE *fp)
virtual void writePLY2 (FILE *fp)
virtual void writeUNV (FILE *fp, int num=0, int elementary=1, int physical=1)
virtual void writeVTK (FILE *fp, bool binary=false, bool bigEndian=false)
virtual void writeMATLAB (FILE *fp, int filetype, int elementary=0, int physical=0, bool binary=false)
virtual void writeTOCHNOG (FILE *fp, int num)
virtual void writeMESH (FILE *fp, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeNEU (FILE *fp, unsigned gambitType, int adjust, int phys=0)
virtual void writeIR3 (FILE *fp, int elementTagType, int num, int elementary, int physical)
virtual void writeBDF (FILE *fp, int format=0, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeDIFF (FILE *fp, int num, bool binary=false, int physical_property=1)
virtual void writeINP (FILE *fp, int num)
virtual void writeKEY (FILE *fp, int pid, int num)
virtual void writeRAD (FILE *fp, int num)
virtual void writeSU2 (FILE *fp, int num)
virtual const char * getStringForTOCHNOG () const
virtual const char * getStringForDIFF () const
std::string getName ()
virtual std::size_t getNumVerticesForMSH ()
virtual void getVerticesIdForMSH (std::vector< int > &verts)
virtual MElement * copy (std::map< int, MVertex * > &vertexMap, std::map< MElement *, MElement * > &newParents, std::map< MElement *, MElement * > &newDomains)
Static Public Member Functions
static int edges_prism (const int edge, const int vert)
static int faces_prism (const int face, const int vert)
static int faces2edge_prism (const int face, const int edge)
static int faceClosureEdge2edge (const int face, const int edge)
Static Public Member Functions inherited from MElement
static unsigned int getInfoMSH (const int typeMSH, const char **const name=nullptr)
Protected Member Functions
void _getEdgeVertices (const int num, std::vector< MVertex * > &v) const
void _getFaceVertices (const int num, std::vector< MVertex * > &v) const
Protected Member Functions inherited from MElement
void _getEdgeRep (MVertex *v0, MVertex *v1, double *x, double *y, double *z, SVector3 *n, int faceIndex=-1)
void _getFaceRep (MVertex *v0, MVertex *v1, MVertex *v2, double *x, double *y, double *z, SVector3 *n)
Protected Attributes
MVertex * _v [6]
Additional Inherited Members
Static Protected Member Functions inherited from MElement
static bool _getFaceInfo (const MFace &face, const MFace &other, int &sign, int &rot)
Static Protected Attributes inherited from MElement
static double _isInsideTolerance
Detailed Description
Definition at line 34 of file MPrism.h.
Constructor & Destructor Documentation
MPrism() [1/2]
MPrism::MPrism (MVertex * v0, MVertex * v1, MVertex * v2, MVertex * v3, MVertex * v4, MVertex * v5, int num = 0, int part = 0) inline
Definition at line 51 of file MPrism.h.
MPrism() [2/2]
MPrism::MPrism (const std::vector< MVertex * > & v, int num = 0, int part = 0) inline
Definition at line 62 of file MPrism.h.
~MPrism()
MPrism::~MPrism () inline
Definition at line 67 of file MPrism.h.
Member Function Documentation
_getEdgeVertices()
void MPrism::_getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline protected
Definition at line 37 of file MPrism.h.
Referenced by getEdgeVertices(), MPrism15::getEdgeVertices(), MPrism18::getEdgeVertices(), and MPrismN::getEdgeVertices().
_getFaceVertices()
void MPrism::_getFaceVertices (const int num, std::vector< MVertex * > & v) const inline protected
Definition at line 42 of file MPrism.h.
Referenced by getFaceVertices(), MPrism15::getFaceVertices(), MPrism18::getFaceVertices(), and MPrismN::getFaceVertices().
barycenterUVW()
virtual SPoint3 MPrism::barycenterUVW () const inline virtual
Reimplemented from MElement.
Definition at line 172 of file MPrism.h.
edges_prism()
static int MPrism::edges_prism (const int edge, const int vert) inline static
Definition at line 182 of file MPrism.h.
Referenced by _getEdgeVertices(), getEdge(), getEdgeRep(), gmshGenerateMonomialsPrism(), and numEdge2numVertex().
faceClosureEdge2edge()
static int MPrism::faceClosureEdge2edge (const int face, const int edge) inline static
Definition at line 205 of file MPrism.h.
Referenced by ClosureGen::getFaceClosurePrism().
faces2edge_prism()
static int MPrism::faces2edge_prism (const int face, const int edge) inline static
Definition at line 194 of file MPrism.h.
Referenced by retrieveFaceBoundaryVertices().
faces_prism()
static int MPrism::faces_prism (const int face, const int vert) inline static
Definition at line 188 of file MPrism.h.
Referenced by _getFaceVertices(), _myGetFaceRep(), Cell::findBdCellOrientation(), Cell::findBdElement(), getFace(), ClosureGen::getFaceClosurePrism(), gmshGenerateMonomialsPrism(), and retrieveFaceBoundaryVertices().
gammaShapeMeasure()
double MPrism::gammaShapeMeasure () virtual
Reimplemented from MElement.
Definition at line 550 of file MPrism.cpp.
getDim()
virtual int MPrism::getDim () const inline virtual
Implements MElement.
Definition at line 68 of file MPrism.h.
getEdge()
virtual MEdge MPrism::getEdge (int num) const inline virtual
Implements MElement.
Definition at line 75 of file MPrism.h.
Referenced by getInnerRadius().
getEdgeRep()
void MPrism::getEdgeRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Implements MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 19 of file MPrism.cpp.
Referenced by MPrism15::getEdgeRep(), MPrism18::getEdgeRep(), and MPrismN::getEdgeRep().
getEdgeSolin()
virtual MEdge MPrism::getEdgeSolin (int num) inline virtual
Reimplemented from MElement.
Definition at line 218 of file MPrism.h.
getEdgeVertices()
virtual void MPrism::getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 86 of file MPrism.h.
getFace()
virtual MFace MPrism::getFace (int num) const inline virtual
Implements MElement.
Definition at line 94 of file MPrism.h.
Referenced by getFaceInfo(), MakeMeshConformal(), and Subdivide().
getFaceInfo()
bool MPrism::getFaceInfo (const MFace & face, int & ithFace, int & sign, int & rot) const virtual
Reimplemented from MElement.
Definition at line 79 of file MPrism.cpp.
getFaceRep()
void MPrism::getFaceRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Implements MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 398 of file MPrism.cpp.
Referenced by MPrism15::getFaceRep(), MPrism18::getFaceRep(), and MPrismN::getFaceRep().
getFaceSolin()
virtual MFace MPrism::getFaceSolin (int num) inline virtual
Reimplemented from MElement.
Definition at line 224 of file MPrism.h.
getFaceVertices()
virtual void MPrism::getFaceVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 106 of file MPrism.h.
getInnerRadius()
double MPrism::getInnerRadius () virtual
Reimplemented from MElement.
Definition at line 65 of file MPrism.cpp.
getIntegrationPoints()
void MPrism::getIntegrationPoints (int pOrder, int * npts, IntPt ** pts) virtual
Reimplemented from MElement.
Definition at line 59 of file MPrism.cpp.
getNode()
virtual void MPrism::getNode (int num, double & u, double & v, double & w) const inline virtual
Reimplemented from MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 132 of file MPrism.h.
Referenced by MPrism15::getNode(), and MPrism18::getNode().
getNumEdges()
virtual int MPrism::getNumEdges () const inline virtual
Implements MElement.
Definition at line 74 of file MPrism.h.
getNumEdgesRep()
virtual int MPrism::getNumEdgesRep (bool curved) inline virtual
Implements MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 83 of file MPrism.h.
getNumFaces()
virtual int MPrism::getNumFaces () inline virtual
Implements MElement.
Definition at line 91 of file MPrism.h.
Referenced by MakeMeshConformal().
getNumFacesRep()
int MPrism::getNumFacesRep (bool curved) virtual
Implements MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 452 of file MPrism.cpp.
Referenced by MPrism15::getNumFacesRep(), MPrism18::getNumFacesRep(), and MPrismN::getNumFacesRep().
getNumVertices()
virtual std::size_t MPrism::getNumVertices () const inline virtual
Implements MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 69 of file MPrism.h.
Referenced by Subdivide().
getStringForBDF()
virtual const char* MPrism::getStringForBDF () const inline virtual
Reimplemented from MElement.
Reimplemented in MPrism15.
Definition at line 116 of file MPrism.h.
getStringForINP()
virtual const char* MPrism::getStringForINP () const inline virtual
Reimplemented from MElement.
Reimplemented in MPrism15.
Definition at line 117 of file MPrism.h.
getStringForKEY()
virtual const char* MPrism::getStringForKEY () const inline virtual
Reimplemented from MElement.
Reimplemented in MPrism15.
Definition at line 118 of file MPrism.h.
getStringForPOS()
virtual const char* MPrism::getStringForPOS () const inline virtual
Reimplemented from MElement.
Reimplemented in MPrismN, and MPrism18.
Definition at line 115 of file MPrism.h.
getStringForRAD()
virtual const char* MPrism::getStringForRAD () const inline virtual
Reimplemented from MElement.
Definition at line 119 of file MPrism.h.
getType()
virtual int MPrism::getType () const inline virtual
Implements MElement.
Definition at line 111 of file MPrism.h.
getTypeForMSH()
virtual int MPrism::getTypeForMSH () const inline virtual
Reimplemented from MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 112 of file MPrism.h.
getTypeForUNV()
virtual int MPrism::getTypeForUNV () const inline virtual
Reimplemented from MElement.
Reimplemented in MPrism15.
Definition at line 113 of file MPrism.h.
getTypeForVTK()
virtual int MPrism::getTypeForVTK () const inline virtual
Reimplemented from MElement.
Reimplemented in MPrism18, and MPrism15.
Definition at line 114 of file MPrism.h.
getVertex() [1/2]
virtual MVertex* MPrism::getVertex (int num) inline virtual
Implements MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 71 of file MPrism.h.
Referenced by getFaceRep(), getInnerRadius(), getVertexVTK(), qmPrism::minNCJ(), setHighOrder(), and Subdivide().
getVertex() [2/2]
virtual const MVertex* MPrism::getVertex (int num) const inline virtual
Implements MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 72 of file MPrism.h.
getVertexVTK()
virtual MVertex* MPrism::getVertexVTK (int num) inline virtual
Reimplemented from MElement.
Reimplemented in MPrism18, and MPrism15.
Definition at line 236 of file MPrism.h.
getVolumeSign()
int MPrism::getVolumeSign () virtual
Reimplemented from MElement.
Definition at line 38 of file MPrism.cpp.
isInside()
virtual bool MPrism::isInside (double u, double v, double w) const inline virtual
Implements MElement.
Definition at line 173 of file MPrism.h.
numCommonNodesInDualGraph()
int MPrism::numCommonNodesInDualGraph (const MElement *const other) const virtual
Implements MElement.
Definition at line 89 of file MPrism.cpp.
numEdge2numVertex()
virtual int MPrism::numEdge2numVertex (int numEdge, int numVert) const inline virtual
Reimplemented from MElement.
Definition at line 79 of file MPrism.h.
reverse()
virtual void MPrism::reverse () inline virtual
Reimplemented from MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 120 of file MPrism.h.
setVertex()
virtual void MPrism::setVertex (int num, MVertex * v) inline virtual
Reimplemented from MElement.
Reimplemented in MPrismN, MPrism18, and MPrism15.
Definition at line 73 of file MPrism.h.
Member Data Documentation
_v
MVertex* MPrism::_v[6] protected
Definition at line 36 of file MPrism.h.
Referenced by _getEdgeVertices(), _getFaceVertices(), getEdge(), getEdgeRep(), getEdgeSolin(), getFace(), getFaceRep(), getFaceSolin(), getVertex(), MPrism15::getVertex(), MPrism18::getVertex(), MPrismN::getVertex(), getVolumeSign(), MPrism(), reverse(), MPrism15::reverse(), MPrism18::reverse(), MPrismN::reverse(), setVertex(), MPrism15::setVertex(), MPrism18::setVertex(), and MPrismN::setVertex().
The documentation for this class was generated from the following files:
src/geo/MPrism.h
src/geo/MPrism.cpp