gmsh-TingyuanDoc: SElement Class Reference
SElement Class Reference
#include <SElement.h>
Public Member Functions
SElement (MElement *e)
~SElement ()
MElement * getMeshElement () const
int getNumNodalShapeFunctions () const
MVertex * getVertex (int i) const
int getNumNodalTestFunctions () const
void nodalShapeFunctions (double u, double v, double w, double s[])
void gradNodalShapeFunctions (double u, double v, double w, double invjac[3][3], double grad[][3])
void nodalTestFunctions (double u, double v, double w, double s[])
void gradNodalTestFunctions (double u, double v, double w, double invjac[3][3], double grad[][3])
Static Public Member Functions
static void setShapeEnrichement (simpleFunction< double > *f)
static void setTestEnrichement (simpleFunction< double > *f)
static const simpleFunction< double > * getShapeEnrichement ()
static const simpleFunction< double > * getTestEnrichement ()
Private Member Functions
void nodalFunctions (double u, double v, double w, double s[], simpleFunction< double > *_enrichement)
void gradNodalFunctions (double u, double v, double w, double invjac[3][3], double grad[][3], simpleFunction< double > *_enrichment)
Private Attributes
MElement * _e
Static Private Attributes
static simpleFunction< double > * _enrichement_s = nullptr
static simpleFunction< double > * _enrichement_t = nullptr
Detailed Description
Definition at line 18 of file SElement.h.
Constructor & Destructor Documentation
SElement()
SElement::SElement (MElement * e) inline
Definition at line 33 of file SElement.h.
~SElement()
SElement::~SElement () inline
Definition at line 34 of file SElement.h.
Member Function Documentation
getMeshElement()
MElement* SElement::getMeshElement () const inline
Definition at line 35 of file SElement.h.
Referenced by helmholtzTerm< double >::elementMatrix(), elasticityTerm::elementMatrix(), elasticityMixedTerm::elementMatrix(), distanceTerm::elementVector(), laplaceTerm::elementVector(), elasticityTerm::elementVector(), helmholtzTerm< double >::getLocalDofC(), elasticityTerm::getLocalDofC(), helmholtzTerm< double >::getLocalDofR(), elasticityTerm::getLocalDofR(), elasticityMixedTerm::getLocalDofR(), elasticityMixedTerm::setPolynomialBasis(), helmholtzTerm< double >::sizeOfC(), elasticityTerm::sizeOfC(), helmholtzTerm< double >::sizeOfR(), and elasticityTerm::sizeOfR().
getNumNodalShapeFunctions()
int SElement::getNumNodalShapeFunctions () const
Definition at line 101 of file SElement.cpp.
Referenced by gradNodalFunctions(), and nodalFunctions().
getNumNodalTestFunctions()
int SElement::getNumNodalTestFunctions () const
Definition at line 107 of file SElement.cpp.
getShapeEnrichement()
static const simpleFunction<double>* SElement::getShapeEnrichement () inline static
Definition at line 44 of file SElement.h.
Referenced by elasticityTerm::elementMatrix().
getTestEnrichement()
static const simpleFunction<double>* SElement::getTestEnrichement () inline static
Definition at line 48 of file SElement.h.
Referenced by elasticityTerm::elementMatrix().
getVertex()
MVertex* SElement::getVertex (int i) const inline
Definition at line 53 of file SElement.h.
gradNodalFunctions()
void SElement::gradNodalFunctions (double u, double v, double w, double invjac[3][3], double grad[][3], simpleFunction< double > * _enrichment) private
Definition at line 28 of file SElement.cpp.
Referenced by gradNodalShapeFunctions(), and gradNodalTestFunctions().
gradNodalShapeFunctions()
void SElement::gradNodalShapeFunctions (double u, double v, double w, double invjac[3][3], double grad[][3])
Definition at line 79 of file SElement.cpp.
Referenced by elasticityMixedTerm::elementMatrix().
gradNodalTestFunctions()
void SElement::gradNodalTestFunctions (double u, double v, double w, double invjac[3][3], double grad[][3])
Definition at line 85 of file SElement.cpp.
nodalFunctions()
void SElement::nodalFunctions (double u, double v, double w, double s[], simpleFunction< double > * _enrichement) private
Definition at line 63 of file SElement.cpp.
Referenced by nodalShapeFunctions(), and nodalTestFunctions().
nodalShapeFunctions()
void SElement::nodalShapeFunctions (double u, double v, double w, double s[])
Definition at line 91 of file SElement.cpp.
nodalTestFunctions()
void SElement::nodalTestFunctions (double u, double v, double w, double s[])
Definition at line 96 of file SElement.cpp.
Referenced by elasticityTerm::elementVector().
setShapeEnrichement()
static void SElement::setShapeEnrichement (simpleFunction< double > * f) inline static
Definition at line 36 of file SElement.h.
setTestEnrichement()
static void SElement::setTestEnrichement (simpleFunction< double > * f) inline static
Definition at line 40 of file SElement.h.
Member Data Documentation
_e
MElement* SElement::_e private
Definition at line 21 of file SElement.h.
Referenced by getMeshElement(), getNumNodalShapeFunctions(), getNumNodalTestFunctions(), getVertex(), gradNodalFunctions(), and nodalFunctions().
_enrichement_s
simpleFunction< double > * SElement::_enrichement_s = nullptr static private
Definition at line 24 of file SElement.h.
Referenced by getShapeEnrichement(), gradNodalFunctions(), gradNodalShapeFunctions(), nodalShapeFunctions(), and setShapeEnrichement().
_enrichement_t
simpleFunction< double > * SElement::_enrichement_t = nullptr static private
Definition at line 24 of file SElement.h.
Referenced by getTestEnrichement(), gradNodalTestFunctions(), nodalTestFunctions(), and setTestEnrichement().
The documentation for this class was generated from the following files:
src/solver/SElement.h
src/solver/SElement.cpp