gmsh-TingyuanDoc: MVertex Class Reference
MVertex Class Reference
#include <MVertex.h>
Public Member Functions
MVertex (double x, double y, double z, GEntity *ge=nullptr, std::size_t num=0)
virtual ~MVertex ()
void deleteLast ()
virtual char getVisibility ()
virtual void setVisibility (char val)
int getPolynomialOrder ()
void setPolynomialOrder (int order)
double x () const
double y () const
double z () const
double & x ()
double & y ()
double & z ()
SPoint3 point () const
void setXYZ (double x, double y, double z)
void setXYZ (const SPoint3 &pt)
GEntity * onWhat () const
void setEntity (GEntity *ge)
std::size_t getNum () const
void forceNum (std::size_t num)
long int getIndex () const
void setIndex (long int index)
virtual bool getParameter (int i, double &par) const
virtual bool setParameter (int i, double par)
double distance (MVertex *const v)
void writeMSH (FILE *fp, bool binary=false, bool saveParametric=false, double scalingFactor=1.0)
void writeMSH2 (FILE *fp, bool binary=false, bool saveParametric=false, double scalingFactor=1.0)
void writePLY2 (FILE *fp)
void writeVRML (FILE *fp, double scalingFactor=1.0)
void writeUNV (FILE *fp, bool officialExponentFormat, double scalingFactor=1.0)
void writeVTK (FILE *fp, bool binary=false, double scalingFactor=1.0, bool bigEndian=false)
void writeMATLAB (FILE *fp, int type, bool binary, double scalingFactor=1.0)
void writeTOCHNOG (FILE *fp, int dim, double scalingFactor=1.0)
void writeMESH (FILE *fp, double scalingFactor=1.0)
void writeOFF (FILE *fp, double scalingFactor=1.0)
void writeNEU (FILE *fp, int dim, double scalingFactor=1.0)
void writeBDF (FILE *fp, int format=0, double scalingFactor=1.0)
void writeINP (FILE *fp, double scalingFactor=1.0)
void writeKEY (FILE *fp, double scalingFactor=1.0)
void writeRAD (FILE *fp, double scalingFactor=1.0)
void writeDIFF (FILE *fp, bool binary, double scalingFactor=1.0)
void writeSU2 (FILE *fp, int dim, double scalingFactor=1.0)
Protected Attributes
std::size_t _num
long int _index
char _visible
char _order
double _x
double _y
double _z
GEntity * _ge
Detailed Description
Definition at line 24 of file MVertex.h.
Constructor & Destructor Documentation
MVertex()
MVertex::MVertex (double x, double y, double z, GEntity * ge = nullptr, std::size_t num = 0)
Definition at line 26 of file MVertex.cpp.
~MVertex()
virtual MVertex::~MVertex () inline virtual
Definition at line 48 of file MVertex.h.
Member Function Documentation
deleteLast()
void MVertex::deleteLast ()
Definition at line 41 of file MVertex.cpp.
distance()
double MVertex::distance (MVertex *const v) inline
Definition at line 105 of file MVertex.h.
Referenced by MLine::getInnerRadius(), MTriangle::getInnerRadius(), MPrism::getInnerRadius(), MTetrahedron::getInnerRadius(), MLine::getLength(), MTriangle::getOuterRadius(), MQuadrangle::getVolume(), MElement::maxEdge(), MeshTransfiniteSurface(), MeshTransfiniteVolume(), MElement::minEdge(), and optimize1DMeshAtAcuteCorners().
forceNum()
void MVertex::forceNum (std::size_t num)
Definition at line 48 of file MVertex.cpp.
Referenced by GModel::renumberMeshVertices().
getIndex()
long int MVertex::getIndex () const inline
Definition at line 93 of file MVertex.h.
Referenced by buildCutMesh(), copy_periodicity(), bidimMeshData::getIndex(), PViewDataGModel::getNode(), MPolyhedron::getVerticesIdForMSH(), MPolygon::getVerticesIdForMSH(), MElement::getVerticesIdForMSH(), GModel::indexMeshVertices(), insertVerticesInRegion(), GModel::removeDuplicateMeshVertices(), MTet4::setup(), GModel::writeCELUM(), GModel::writeDIFF(), MElement::writeKEY(), GModel::writeMAIL(), MElement::writeMATLAB(), MElement::writeMESH(), PViewDataList::writeMSH(), PViewDataGModel::writeMSH(), writeMSHPeriodicNodes(), MElement::writePLY2(), MElement::writeRAD(), MElement::writeSU2(), MElement::writeVRML(), and MElement::writeVTK().
getNum()
std::size_t MVertex::getNum () const inline
Definition at line 86 of file MVertex.h.
Referenced by _getAdditionalNodesOnBoundary(), OctreePost::_getValue(), GModel::addMVertexToVertexCache(), addToMap(), GModel::alignPeriodicBoundaries(), dofManager< double >::assemble(), buildCutMesh(), checkConformity(), GModel::checkMeshCoherence(), compare(), MElement::copy(), frameSolver2d::createDofs(), createTopologyFromMesh1D(), drawVertexLabel(), FilterElementsCutByLevelSet::FilterElementsCutByLevelSet(), FixPeriodicMesh(), dofManager< double >::fixVertex(), GeomMeshMatcher::forceTomatch(), dofManager< double >::getDofValue(), getEdgeVerticesOnGeo(), meshMetric::getGradient(), MElement::getInfoString(), ScalarLagrangeFunctionSpaceOfElement::getKeys(), ScalarLagrangeFunctionSpace::getKeys(), FunctionSpaceBase::getKeysOnVertex(), meshMetric::getLaplacian(), helmholtzTerm< double >::getLocalDofC(), elasticityTerm::getLocalDofC(), helmholtzTerm< double >::getLocalDofR(), elasticityTerm::getLocalDofR(), elasticityMixedTerm::getLocalDofR(), GModel::getMEdge(), GModel::getMFace(), getMinMaxVert(), PViewDataGModel::getValue(), GModel::indexMeshVertices(), MVertexRTree::insert(), dofManager< double >::isFixed(), meshGenerator(), meshGeneratorPeriodic(), GMSH_NewViewPlugin::nodeData(), dofManager< double >::numberVertex(), MEdgeHash::operator()(), MEdgeLessThan::operator()(), MFaceLessThan::operator()(), vertex_comparator::operator()(), MVertexPtrLessThan::operator()(), MVertexPtrEqual::operator()(), MVertexPtrHash::operator()(), compareMTriangleLexicographic::operator()(), blyr_mvertex::operator<(), faceXtet::operator<(), edgeXface::operator<(), faceXtet::operator==(), edgeXface::operator==(), PolyMesh2GFace(), Field::putOnNewView(), GModel::readPLY(), recoverEdges(), GModel::renumberMeshVertices(), reparamMeshVertexOnFace(), PViewDataGModel::sendToServer(), PViewDataGModel::setValue(), PViewDataGModel::smooth(), frameSolver2d::solve(), SortEdgeConsecutive(), swapquad::swapquad(), topoEdge::topoEdge(), topoFace::topoFace(), GModel::writeCELUM(), PViewDataGModel::writeMSH(), writeMSH4Elements(), writeMSH4EntityNodes(), and writeMSHPeriodicNodes().
getParameter()
virtual bool MVertex::getParameter (int i, double & par) const inline virtual
Reimplemented in MFaceVertex, and MEdgeVertex.
Definition at line 97 of file MVertex.h.
Referenced by _relocate(), _relocateVertex(), _tryToCollapseThatVertex(), bowyerWatsonParallelogramsConstrained(), buildConsecutiveListOfVertices(), GFace::computeMeshSizeFieldAccuracy(), copyMesh(), createSizeFieldFromExistingMesh(), filterPoints(), getAllParameters(), getGFaceNormalFromVert(), MElement::idealJacRange(), GlobalBackgroundMesh::importGModelMeshes(), SurfaceProjector::initialize(), meshGenerator(), meshGeneratorPeriodic(), MVertexPtrLessThanParam::operator()(), optimize1DMeshAtAcuteCorners(), GEdge::relocateMeshVertices(), GFace::relocateMeshVertices(), remeshUnrecoveredEdges(), reparamMeshVertexOnEdge(), reparamMeshVertexOnFace(), MElement::scaledJacRange(), MElement::signedInvCondNumRange(), transferSeamGEdgesVerticesToGFace(), backgroundMesh::updateSizes(), writeMSH(), writeMSH2(), and writeMSH4EntityNodes().
getPolynomialOrder()
int MVertex::getPolynomialOrder () inline
Definition at line 56 of file MVertex.h.
Referenced by drawVertexLabel(), drawVerticesPerElement(), and drawVerticesPerEntity().
getVisibility()
virtual char MVertex::getVisibility () inline virtual
Definition at line 52 of file MVertex.h.
Referenced by drawVertexLabel(), drawVerticesPerElement(), and drawVerticesPerEntity().
onWhat()
GEntity* MVertex::onWhat () const inline
Definition at line 82 of file MVertex.h.
Referenced by _isModelOkForTopologicalOpti(), _relocate(), _relocateVertex(), _relocateVertexGolden(), _relocateVertexOfPyramid(), _removeTwoQuadsNodes(), GModel::_storeVerticesInEntities(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), bidimMeshData::addVertex(), GModel::alignPeriodicBoundaries(), are_all_on_surface(), backgroundMesh::backgroundMesh(), buildConsecutiveListOfVertices(), checkConformity(), classifyFaces(), collapseVertex(), createSizeFieldFromExistingMesh(), drawVerticesPerElement(), GMSH_MeshSubEntitiesPlugin::execute(), GMSH_CurvedBndDistPlugin::execute(), GMSH_BubblesPlugin::execute(), blyr_manager::extrude_vertices_on_edges(), filterPoints(), GeomMeshMatcher::forceTomatch(), getAcuteCorners(), getAdditionalEntities(), getAllParameters(), getColorByElement(), getGFaceNormalFromVert(), bidimMeshData::getIndex(), MElement::idealJacRange(), SurfaceProjector::initialize(), insertVertexB(), insertVerticesInRegion(), meshGenerator(), meshGeneratorPeriodic(), optimize1DMeshAtAcuteCorners(), quadMeshRemoveHalfOfOneDMesh::quadMeshRemoveHalfOfOneDMesh(), RecombineTriangle::RecombineTriangle(), relocateSlaveVertices(), remeshUnrecoveredEdges(), reparamMeshVertexOnFace(), MElement::scaledJacRange(), setBLData(), MElement::signedInvCondNumRange(), smoothVertex(), smoothVertexOptimize(), backgroundMesh::updateSizes(), writeMSH(), and writeMSH2().
point()
SPoint3 MVertex::point () const inline
Definition at line 67 of file MVertex.h.
Referenced by GRegion::bounds(), GEdge::bounds(), GFace::bounds(), computeDiscreteCurvatures(), MLine3::discretize(), MLineN::discretize(), getAllParameters(), getEdgeVerticesOnGeo(), GRegion::getOBB(), GEdge::getOBB(), GFace::getOBB(), SurfaceProjector::initialize(), MElement::maxDistToStraight(), meshGeneratorPeriodic(), qmTriangle::NCJRange(), qmQuadrangle::NCJRange(), optimize1DMeshAtAcuteCorners(), transferSeamGEdgesVerticesToGFace(), and GEntity::updateCorrespondingVertices().
setEntity()
void MVertex::setEntity (GEntity * ge) inline
Definition at line 83 of file MVertex.h.
Referenced by classifyFaces(), GMSH_MeshSubEntitiesPlugin::execute(), GModel::pruneMeshVertexAssociations(), and readMSH4Nodes().
setIndex()
void MVertex::setIndex (long int index) inline
Definition at line 94 of file MVertex.h.
Referenced by bidimMeshData::addVertex(), GModel::indexMeshVertices(), insertVerticesInRegion(), GModel::removeDuplicateMeshVertices(), PViewDataGModel::tagNode(), and GModel::writeCELUM().
setParameter()
virtual bool MVertex::setParameter (int i, double par) inline virtual
Reimplemented in MFaceVertex, and MEdgeVertex.
Definition at line 102 of file MVertex.h.
Referenced by _isItAGoodIdeaToMoveThatVertex(), _relocate(), _relocateVertex(), _tryToCollapseThatVertex(), GlobalBackgroundMesh::importGModelMeshes(), optimize1DMeshAtAcuteCorners(), and transferSeamGEdgesVerticesToGFace().
setPolynomialOrder()
void MVertex::setPolynomialOrder (int order) inline
Definition at line 57 of file MVertex.h.
Referenced by MLine3::MLine3().
setVisibility()
virtual void MVertex::setVisibility (char val) inline virtual
Definition at line 53 of file MVertex.h.
setXYZ() [1/2]
void MVertex::setXYZ (const SPoint3 & pt) inline
Definition at line 74 of file MVertex.h.
setXYZ() [2/2]
void MVertex::setXYZ (double x, double y, double z) inline
Definition at line 68 of file MVertex.h.
Referenced by _isItAGoodIdeaToMoveThatVertex(), LaplaceSmoothing(), optimize1DMeshAtAcuteCorners(), and relocateSlaveVertices().
writeBDF()
void MVertex::writeBDF (FILE * fp, int format = 0, double scalingFactor = 1.0)
Definition at line 335 of file MVertex.cpp.
writeDIFF()
void MVertex::writeDIFF (FILE * fp, bool binary, double scalingFactor = 1.0)
Definition at line 388 of file MVertex.cpp.
Referenced by GModel::writeDIFF().
writeINP()
void MVertex::writeINP (FILE * fp, double scalingFactor = 1.0)
Definition at line 364 of file MVertex.cpp.
writeKEY()
void MVertex::writeKEY (FILE * fp, double scalingFactor = 1.0)
Definition at line 372 of file MVertex.cpp.
writeMATLAB()
void MVertex::writeMATLAB (FILE * fp, int type, bool binary, double scalingFactor = 1.0)
Definition at line 243 of file MVertex.cpp.
writeMESH()
void MVertex::writeMESH (FILE * fp, double scalingFactor = 1.0)
Definition at line 274 of file MVertex.cpp.
writeMSH()
void MVertex::writeMSH (FILE * fp, bool binary = false, bool saveParametric = false, double scalingFactor = 1.0)
Definition at line 55 of file MVertex.cpp.
writeMSH2()
void MVertex::writeMSH2 (FILE * fp, bool binary = false, bool saveParametric = false, double scalingFactor = 1.0)
Definition at line 124 of file MVertex.cpp.
writeNEU()
void MVertex::writeNEU (FILE * fp, int dim, double scalingFactor = 1.0)
Definition at line 291 of file MVertex.cpp.
writeOFF()
void MVertex::writeOFF (FILE * fp, double scalingFactor = 1.0)
Definition at line 283 of file MVertex.cpp.
writePLY2()
void MVertex::writePLY2 (FILE * fp)
Definition at line 184 of file MVertex.cpp.
writeRAD()
void MVertex::writeRAD (FILE * fp, double scalingFactor = 1.0)
Definition at line 380 of file MVertex.cpp.
writeSU2()
void MVertex::writeSU2 (FILE * fp, int dim, double scalingFactor = 1.0)
Definition at line 396 of file MVertex.cpp.
writeTOCHNOG()
void MVertex::writeTOCHNOG (FILE * fp, int dim, double scalingFactor = 1.0)
Definition at line 255 of file MVertex.cpp.
writeUNV()
void MVertex::writeUNV (FILE * fp, bool officialExponentFormat, double scalingFactor = 1.0)
Definition at line 199 of file MVertex.cpp.
writeVRML()
void MVertex::writeVRML (FILE * fp, double scalingFactor = 1.0)
Definition at line 191 of file MVertex.cpp.
writeVTK()
void MVertex::writeVTK (FILE * fp, bool binary = false, double scalingFactor = 1.0, bool bigEndian = false)
Definition at line 225 of file MVertex.cpp.
x() [1/2]
double& MVertex::x () inline
Definition at line 63 of file MVertex.h.
x() [2/2]
double MVertex::x () const inline
Definition at line 60 of file MVertex.h.
Referenced by _getAdditionalNodesOnBoundary(), MElement::_getEdgeRep(), MElement::_getFaceRep(), _isItAGoodIdeaToMoveThatVertex(), _relocate(), _relocateVertex(), _relocateVertex2(), _relocateVertexGolden(), _relocateVertexOfPyramid(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), _tryToCollapseThatVertex(), _tryToCollapseThatVertex2(), blyr_manager::add_external_corner(), blyr_manager::add_fan(), blyr_manager::add_one_normal(), addExtrudeNormals(), angle3Vertices(), HilbertSort::Apply(), approximationError(), MFace::barycenter(), MElement::barycenter(), MElement::barycenter_infty(), blyr_manager::blyr_manager(), buildConsecutiveListOfVertices(), buildCutMesh(), GFace::buildSTLTriangulation(), GModel::checkMeshCoherence(), discreteFace::param::checkPlanar(), MTet4::circumcenter(), MTriangle::circumcenter(), blyr_manager::classify_ridges(), classifyFaces(), discreteFace::closestPoint(), closestVertexFinder::closestVertexFinder(), collapseVertex(), meshMetric::computeHessian(), computeLevelset(), GFace::computeMeshSizeFieldAccuracy(), computeParametrization(), frameSolver2d::computeStiffnessMatrix(), meshMetric::computeValues(), MElement::copy(), copy_vertices(), GEntity::copyMasterCoordinates(), copyMesh(), createSizeFieldFromExistingMesh(), createTopologyFromMesh1D(), delaunayTriangulation(), MLineN::discretize(), distance(), distance(), drawVertexLabel(), drawVerticesPerElement(), drawVerticesPerEntity(), drawVoronoiDual(), edge_angle::edge_angle(), GMSH_CrackPlugin::execute(), GMSH_InvisiblePlugin::execute(), GMSH_DistancePlugin::execute(), meshMetric::exportInfo(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), extrudeMesh(), MElement::fastBarycenter(), filterPoints(), discreteFace::firstDer(), GeomMeshMatcher::forceTomatch(), qmTriangle::gamma(), getAllParameters(), MTetrahedron::getEdgeRep(), MQuadrangle::getEdgeRep(), MTriangle::getEdgeRep(), MPrism::getEdgeRep(), MHexahedron::getEdgeRep(), getEdgeVerticesOnGeo(), getElement(), getExtrudedVertices(), getFaceVerticesOnGeo(), getGEdge(), getGFace(), getGVertex(), MQuadrangle::getInnerRadius(), MLineChild::getIntegrationPoints(), MSubPoint::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), MElement::getJacobian(), MTetrahedron::getMat(), PViewDataGModel::getNode(), MElement::getNodesCoord(), MTetrahedron::getOuterRadius(), MElement::getPrimaryJacobian(), MTet4::getVolume(), MPyramid::getVolumeSign(), MHexahedron::getVolumeSign(), MPrism::getVolumeSign(), getVolumeVertices(), FuncGradDisc::gradient(), GlobalBackgroundMesh::importGModelMeshes(), MTri3::inCircumCircle(), inCircumCircleXY(), MTet4::inCircumSphere(), initialSquare(), MVertexRTree::insert(), insertVertexB(), insertVerticesInRegion(), MFace::interpolate(), interpVerticesInExistingFace(), intersectClipPlane(), intersectEdge2d(), discreteFace::intersectionWithCircle(), invMapXY(), MEdge::isInside(), MPolyhedron::isInside(), MPolygon::isInside(), MLineChild::isInside(), MTriangleBorder::isInside(), MLineBorder::isInside(), LaplaceSmoothing(), MElementBB(), MElementCentroid(), meshGenerator(), meshGeneratorPeriodic(), modifyInitialMeshForBoundaryLayers(), MTri3::MTri3(), MYxyz2uvw(), qmTriangle::NCJRange(), qmQuadrangle::NCJRange(), discreteFace::normal(), objective_function(), meshGEdge::operator()(), FuncGradDisc::operator()(), EmbeddedCompatibilityTest::operator()(), MVertexPtrLessThanLexicographic::operator()(), gLevelsetYarn::operator()(), optimalPointFrontalB(), orientationTest(), MElement::pnt(), discreteFace::point(), PolyMesh2GFace(), MElement::primaryPnt(), backgroundMesh::print(), prismNCJ(), backgroundMesh::propagate1dMesh(), Field::putOnNewView(), qmTetrahedron::qm(), quadMeshRemoveHalfOfOneDMesh::quadMeshRemoveHalfOfOneDMesh(), GModel::readSTL(), RecombineTriangle::RecombineTriangle(), recoverEdgeBySwaps(), GVertex::relocateMeshVertices(), GEdge::relocateMeshVertices(), GFace::relocateMeshVertices(), remeshUnrecoveredEdges(), reparamMeshEdgeOnFace(), reparamMeshVertexOnEdge(), reparamMeshVertexOnFace(), MFaceN::repositionInnerVertices(), GModel::scaleMesh(), search4Triangle(), setLcs(), PViewDataGModel::setNode(), MTet4::setup(), setXYZ(), smoothing_objective_function_3D(), smoothVertex(), smoothVertexOptimize(), transferDataStructure(), transfiniteHex(), transform(), TRIANGLE_VALIDITY(), GEntity::updateCorrespondingVertices(), backgroundMesh::updateSizes(), faceXtet::visible(), writeBDF(), writeDIFF(), writeINP(), writeKEY(), GModel::writeMAIL(), writeMATLAB(), writeMESH(), writeMSH(), PViewDataList::writeMSH(), writeMSH2(), writeMSH4EntityNodes(), writeNEU(), writeOFF(), GModel::writeP3D(), writePLY2(), writeRAD(), MElement::writeSTL(), writeSU2(), writeTOCHNOG(), writeUNV(), writeVRML(), writeVTK(), MTriangle::xyz2uvw(), MTetrahedron::xyz2uvw(), and MElement::xyz2uvw().
y() [1/2]
double& MVertex::y () inline
Definition at line 64 of file MVertex.h.
y() [2/2]
double MVertex::y () const inline
Definition at line 61 of file MVertex.h.
Referenced by _getAdditionalNodesOnBoundary(), MElement::_getEdgeRep(), MElement::_getFaceRep(), _isItAGoodIdeaToMoveThatVertex(), _relocate(), _relocateVertex(), _relocateVertex2(), _relocateVertexGolden(), _relocateVertexOfPyramid(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), _tryToCollapseThatVertex(), _tryToCollapseThatVertex2(), blyr_manager::add_external_corner(), blyr_manager::add_fan(), blyr_manager::add_one_normal(), addExtrudeNormals(), angle3Vertices(), HilbertSort::Apply(), approximationError(), MFace::barycenter(), MElement::barycenter(), MElement::barycenter_infty(), blyr_manager::blyr_manager(), buildConsecutiveListOfVertices(), buildCutMesh(), GFace::buildSTLTriangulation(), GModel::checkMeshCoherence(), discreteFace::param::checkPlanar(), MTet4::circumcenter(), MTriangle::circumcenter(), blyr_manager::classify_ridges(), classifyFaces(), discreteFace::closestPoint(), closestVertexFinder::closestVertexFinder(), collapseVertex(), meshMetric::computeHessian(), computeLevelset(), GFace::computeMeshSizeFieldAccuracy(), computeParametrization(), frameSolver2d::computeStiffnessMatrix(), meshMetric::computeValues(), MElement::copy(), copy_vertices(), GEntity::copyMasterCoordinates(), copyMesh(), createSizeFieldFromExistingMesh(), createTopologyFromMesh1D(), delaunayTriangulation(), MLineN::discretize(), distance(), distance(), drawVertexLabel(), drawVerticesPerElement(), drawVerticesPerEntity(), drawVoronoiDual(), edge_angle::edge_angle(), GMSH_CrackPlugin::execute(), GMSH_InvisiblePlugin::execute(), GMSH_DistancePlugin::execute(), meshMetric::exportInfo(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), extrudeMesh(), MElement::fastBarycenter(), filterPoints(), discreteFace::firstDer(), GeomMeshMatcher::forceTomatch(), qmTriangle::gamma(), getAllParameters(), MTetrahedron::getEdgeRep(), MQuadrangle::getEdgeRep(), MTriangle::getEdgeRep(), MPrism::getEdgeRep(), MHexahedron::getEdgeRep(), getEdgeVerticesOnGeo(), getElement(), getExtrudedVertices(), getFaceVerticesOnGeo(), getGEdge(), getGFace(), getGVertex(), MQuadrangle::getInnerRadius(), MLineChild::getIntegrationPoints(), MSubPoint::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), MElement::getJacobian(), MTetrahedron::getMat(), PViewDataGModel::getNode(), MElement::getNodesCoord(), MTetrahedron::getOuterRadius(), MElement::getPrimaryJacobian(), MTet4::getVolume(), MPyramid::getVolumeSign(), MHexahedron::getVolumeSign(), MPrism::getVolumeSign(), getVolumeVertices(), FuncGradDisc::gradient(), GlobalBackgroundMesh::importGModelMeshes(), MTri3::inCircumCircle(), inCircumCircleXY(), MTet4::inCircumSphere(), initialSquare(), MVertexRTree::insert(), insertVertexB(), insertVerticesInRegion(), MFace::interpolate(), interpVerticesInExistingFace(), intersectClipPlane(), intersectEdge2d(), discreteFace::intersectionWithCircle(), invMapXY(), MEdge::isInside(), MPolyhedron::isInside(), MPolygon::isInside(), MLineChild::isInside(), MTriangleBorder::isInside(), MLineBorder::isInside(), LaplaceSmoothing(), MElementBB(), MElementCentroid(), meshGenerator(), meshGeneratorPeriodic(), modifyInitialMeshForBoundaryLayers(), MTri3::MTri3(), MYxyz2uvw(), qmTriangle::NCJRange(), qmQuadrangle::NCJRange(), discreteFace::normal(), objective_function(), meshGEdge::operator()(), FuncGradDisc::operator()(), EmbeddedCompatibilityTest::operator()(), MVertexPtrLessThanLexicographic::operator()(), gLevelsetYarn::operator()(), optimalPointFrontalB(), orientationTest(), MElement::pnt(), discreteFace::point(), PolyMesh2GFace(), MElement::primaryPnt(), backgroundMesh::print(), prismNCJ(), backgroundMesh::propagate1dMesh(), Field::putOnNewView(), qmTetrahedron::qm(), quadMeshRemoveHalfOfOneDMesh::quadMeshRemoveHalfOfOneDMesh(), RecombineTriangle::RecombineTriangle(), recoverEdgeBySwaps(), GVertex::relocateMeshVertices(), GEdge::relocateMeshVertices(), GFace::relocateMeshVertices(), remeshUnrecoveredEdges(), reparamMeshEdgeOnFace(), reparamMeshVertexOnEdge(), reparamMeshVertexOnFace(), MFaceN::repositionInnerVertices(), GModel::scaleMesh(), search4Triangle(), setLcs(), PViewDataGModel::setNode(), MTet4::setup(), setXYZ(), smoothing_objective_function_3D(), smoothVertex(), smoothVertexOptimize(), transferDataStructure(), transfiniteHex(), transform(), TRIANGLE_VALIDITY(), GEntity::updateCorrespondingVertices(), backgroundMesh::updateSizes(), faceXtet::visible(), writeBDF(), writeDIFF(), writeINP(), writeKEY(), GModel::writeMAIL(), writeMATLAB(), writeMESH(), writeMSH(), PViewDataList::writeMSH(), writeMSH2(), writeMSH4EntityNodes(), writeNEU(), writeOFF(), GModel::writeP3D(), writePLY2(), writeRAD(), MElement::writeSTL(), writeSU2(), writeTOCHNOG(), writeUNV(), writeVRML(), writeVTK(), MTriangle::xyz2uvw(), MTetrahedron::xyz2uvw(), and MElement::xyz2uvw().
z() [1/2]
double& MVertex::z () inline
Definition at line 65 of file MVertex.h.
z() [2/2]
double MVertex::z () const inline
Definition at line 62 of file MVertex.h.
Referenced by _getAdditionalNodesOnBoundary(), MElement::_getEdgeRep(), MElement::_getFaceRep(), _isItAGoodIdeaToMoveThatVertex(), _relocate(), _relocateVertex(), _relocateVertex2(), _relocateVertexGolden(), _relocateVertexOfPyramid(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), _tryToCollapseThatVertex(), _tryToCollapseThatVertex2(), blyr_manager::add_external_corner(), blyr_manager::add_fan(), blyr_manager::add_one_normal(), addExtrudeNormals(), angle3Vertices(), HilbertSort::Apply(), approximationError(), MFace::barycenter(), MElement::barycenter(), MElement::barycenter_infty(), blyr_manager::blyr_manager(), buildConsecutiveListOfVertices(), buildCutMesh(), GFace::buildSTLTriangulation(), GModel::checkMeshCoherence(), MTet4::circumcenter(), MTriangle::circumcenter(), blyr_manager::classify_ridges(), classifyFaces(), discreteFace::closestPoint(), closestVertexFinder::closestVertexFinder(), collapseVertex(), meshMetric::computeHessian(), computeLevelset(), GFace::computeMeshSizeFieldAccuracy(), computeParametrization(), meshMetric::computeValues(), MElement::copy(), copy_vertices(), GEntity::copyMasterCoordinates(), copyMesh(), createSizeFieldFromExistingMesh(), createTopologyFromMesh1D(), delaunayTriangulation(), MLineN::discretize(), distance(), distance(), drawVertexLabel(), drawVerticesPerElement(), drawVerticesPerEntity(), drawVoronoiDual(), edge_angle::edge_angle(), GMSH_CrackPlugin::execute(), GMSH_InvisiblePlugin::execute(), GMSH_DistancePlugin::execute(), meshMetric::exportInfo(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), extrudeMesh(), MElement::fastBarycenter(), filterPoints(), discreteFace::firstDer(), GeomMeshMatcher::forceTomatch(), qmTriangle::gamma(), getAllParameters(), MTetrahedron::getEdgeRep(), MQuadrangle::getEdgeRep(), MTriangle::getEdgeRep(), MHexahedron::getEdgeRep(), MPrism::getEdgeRep(), getEdgeVerticesOnGeo(), getElement(), getExtrudedVertices(), getFaceVerticesOnGeo(), getGEdge(), getGFace(), getGVertex(), MQuadrangle::getInnerRadius(), MLineChild::getIntegrationPoints(), MSubPoint::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), MElement::getJacobian(), MTetrahedron::getMat(), PViewDataGModel::getNode(), MElement::getNodesCoord(), MTetrahedron::getOuterRadius(), MElement::getPrimaryJacobian(), MTet4::getVolume(), MPyramid::getVolumeSign(), MHexahedron::getVolumeSign(), MPrism::getVolumeSign(), getVolumeVertices(), FuncGradDisc::gradient(), GlobalBackgroundMesh::importGModelMeshes(), MTri3::inCircumCircle(), MTet4::inCircumSphere(), initialSquare(), MVertexRTree::insert(), insertVertexB(), insertVerticesInRegion(), MFace::interpolate(), interpVerticesInExistingFace(), intersectClipPlane(), discreteFace::intersectionWithCircle(), MEdge::isInside(), MPolyhedron::isInside(), MPolygon::isInside(), MLineChild::isInside(), MTriangleBorder::isInside(), MLineBorder::isInside(), LaplaceSmoothing(), MElementBB(), MElementCentroid(), meshGenerator(), meshGeneratorPeriodic(), modifyInitialMeshForBoundaryLayers(), MTri3::MTri3(), qmTriangle::NCJRange(), qmQuadrangle::NCJRange(), discreteFace::normal(), objective_function(), meshGEdge::operator()(), FuncGradDisc::operator()(), EmbeddedCompatibilityTest::operator()(), MVertexPtrLessThanLexicographic::operator()(), gLevelsetYarn::operator()(), optimalPointFrontalB(), MElement::pnt(), discreteFace::point(), PolyMesh2GFace(), MElement::primaryPnt(), backgroundMesh::print(), prismNCJ(), backgroundMesh::propagate1dMesh(), Field::putOnNewView(), qmTetrahedron::qm(), quadMeshRemoveHalfOfOneDMesh::quadMeshRemoveHalfOfOneDMesh(), RecombineTriangle::RecombineTriangle(), GVertex::relocateMeshVertices(), GEdge::relocateMeshVertices(), GFace::relocateMeshVertices(), remeshUnrecoveredEdges(), reparamMeshEdgeOnFace(), reparamMeshVertexOnEdge(), reparamMeshVertexOnFace(), MFaceN::repositionInnerVertices(), GModel::scaleMesh(), setLcs(), PViewDataGModel::setNode(), MTet4::setup(), setXYZ(), smoothing_objective_function_3D(), smoothVertex(), smoothVertexOptimize(), transferDataStructure(), transfiniteHex(), transform(), TRIANGLE_VALIDITY(), GEntity::updateCorrespondingVertices(), backgroundMesh::updateSizes(), faceXtet::visible(), writeBDF(), writeDIFF(), writeINP(), writeKEY(), GModel::writeMAIL(), writeMATLAB(), writeMESH(), writeMSH(), PViewDataList::writeMSH(), writeMSH2(), writeMSH4EntityNodes(), writeNEU(), writeOFF(), GModel::writeP3D(), writePLY2(), writeRAD(), MElement::writeSTL(), writeSU2(), writeTOCHNOG(), writeUNV(), writeVRML(), writeVTK(), MTriangle::xyz2uvw(), MTetrahedron::xyz2uvw(), and MElement::xyz2uvw().
Member Data Documentation
_ge
GEntity* MVertex::_ge protected
Definition at line 43 of file MVertex.h.
Referenced by onWhat(), setEntity(), and writeMESH().
_index
long int MVertex::_index protected
Definition at line 37 of file MVertex.h.
Referenced by getIndex(), MVertex(), setIndex(), writeBDF(), writeDIFF(), writeINP(), writeKEY(), writeMATLAB(), writeMESH(), writeMSH(), writeMSH2(), writeNEU(), writeOFF(), writePLY2(), writeRAD(), writeSU2(), writeTOCHNOG(), writeUNV(), writeVRML(), and writeVTK().
_num
std::size_t MVertex::_num protected
Definition at line 29 of file MVertex.h.
Referenced by deleteLast(), forceNum(), getNum(), and MVertex().
_order
char MVertex::_order protected
Definition at line 39 of file MVertex.h.
Referenced by getPolynomialOrder(), and setPolynomialOrder().
_visible
char MVertex::_visible protected
Definition at line 39 of file MVertex.h.
Referenced by getVisibility(), and setVisibility().
_x
double MVertex::_x protected
Definition at line 41 of file MVertex.h.
Referenced by distance(), point(), setXYZ(), and x().
_y
double MVertex::_y protected
Definition at line 41 of file MVertex.h.
Referenced by distance(), point(), setXYZ(), and y().
_z
double MVertex::_z protected
Definition at line 41 of file MVertex.h.
Referenced by distance(), point(), setXYZ(), and z().
The documentation for this class was generated from the following files:
src/geo/MVertex.h
src/geo/MVertex.cpp