gmsh-TingyuanDoc: PixelBuffer Class Reference
PixelBuffer Class Reference
#include <PixelBuffer.h>
Public Member Functions
PixelBuffer (int width, int height, GLenum format, GLenum type)
~PixelBuffer ()
int getWidth ()
int getHeight ()
int getNumComp ()
int getDataSize ()
GLenum getFormat ()
GLenum getType ()
void * getPixels ()
void copyPixels (int x, int y, PixelBuffer *buffer)
void fill (int offscreen)
Private Attributes
int _width
int _height
int _numComp
int _dataSize
GLenum _format
GLenum _type
unsigned char * _pixels
Detailed Description
Definition at line 32 of file PixelBuffer.h.
Constructor & Destructor Documentation
PixelBuffer()
PixelBuffer::PixelBuffer (int width, int height, GLenum format, GLenum type) inline
Definition at line 39 of file PixelBuffer.h.
~PixelBuffer()
PixelBuffer::~PixelBuffer () inline
Definition at line 69 of file PixelBuffer.h.
Member Function Documentation
copyPixels()
void PixelBuffer::copyPixels (int x, int y, PixelBuffer * buffer) inline
Definition at line 77 of file PixelBuffer.h.
fill()
void PixelBuffer::fill (int offscreen) inline
Definition at line 95 of file PixelBuffer.h.
Referenced by CreateOutputFile().
getDataSize()
int PixelBuffer::getDataSize () inline
Definition at line 73 of file PixelBuffer.h.
Referenced by copyPixels().
getFormat()
GLenum PixelBuffer::getFormat () inline
Definition at line 74 of file PixelBuffer.h.
Referenced by copyPixels(), create_ppm(), and create_yuv().
getHeight()
int PixelBuffer::getHeight () inline
Definition at line 71 of file PixelBuffer.h.
Referenced by copyPixels(), create_gif(), create_ppm(), create_yuv(), and print_pgf().
getNumComp()
int PixelBuffer::getNumComp () inline
Definition at line 72 of file PixelBuffer.h.
Referenced by copyPixels(), and create_gif().
getPixels()
void* PixelBuffer::getPixels () inline
Definition at line 76 of file PixelBuffer.h.
Referenced by copyPixels(), create_gif(), create_ppm(), create_yuv(), and CreateOutputFile().
getType()
GLenum PixelBuffer::getType () inline
Definition at line 75 of file PixelBuffer.h.
Referenced by copyPixels(), create_ppm(), and create_yuv().
getWidth()
int PixelBuffer::getWidth () inline
Definition at line 70 of file PixelBuffer.h.
Referenced by copyPixels(), create_gif(), create_ppm(), create_yuv(), and print_pgf().
Member Data Documentation
_dataSize
int PixelBuffer::_dataSize private
Definition at line 34 of file PixelBuffer.h.
Referenced by copyPixels(), getDataSize(), and PixelBuffer().
_format
GLenum PixelBuffer::_format private
Definition at line 35 of file PixelBuffer.h.
Referenced by copyPixels(), fill(), getFormat(), and PixelBuffer().
_height
int PixelBuffer::_height private
Definition at line 34 of file PixelBuffer.h.
Referenced by copyPixels(), fill(), getHeight(), and PixelBuffer().
_numComp
int PixelBuffer::_numComp private
Definition at line 34 of file PixelBuffer.h.
Referenced by copyPixels(), getNumComp(), and PixelBuffer().
_pixels
unsigned char* PixelBuffer::_pixels private
Definition at line 36 of file PixelBuffer.h.
Referenced by copyPixels(), fill(), getPixels(), PixelBuffer(), and ~PixelBuffer().
_type
GLenum PixelBuffer::_type private
Definition at line 35 of file PixelBuffer.h.
Referenced by copyPixels(), fill(), getType(), and PixelBuffer().
_width
int PixelBuffer::_width private
Definition at line 34 of file PixelBuffer.h.
Referenced by copyPixels(), fill(), getWidth(), and PixelBuffer().
The documentation for this class was generated from the following file:
src/graphics/PixelBuffer.h