gmsh-TingyuanDoc: tetContainer Class Reference
tetContainer Class Reference
Public Member Functions
std::size_t size (int thread) const
Tet * operator() (int thread, int j) const
tetContainer (int nbThreads, int preallocSizePerThread)
Tet * newTet (int thread)
~tetContainer ()
Private Attributes
std::vector< aBunchOfStuff< Tet > * > _perThread
Detailed Description
Definition at line 303 of file delaunay3d.cpp.
Constructor & Destructor Documentation
tetContainer()
tetContainer::tetContainer (int nbThreads, int preallocSizePerThread) inline
Definition at line 313 of file delaunay3d.cpp.
~tetContainer()
tetContainer::~tetContainer () inline
Definition at line 321 of file delaunay3d.cpp.
Member Function Documentation
newTet()
Tet* tetContainer::newTet (int thread) inline
Definition at line 320 of file delaunay3d.cpp.
Referenced by delaunayTrgl(), and initialCube().
operator()()
Tet* tetContainer::operator() (int thread, int j) const inline
Definition at line 312 of file delaunay3d.cpp.
size()
std::size_t tetContainer::size (int thread) const inline
Definition at line 307 of file delaunay3d.cpp.
Referenced by delaunayTriangulation(), and randomTet().
Member Data Documentation
_perThread
std::vector<aBunchOfStuff<Tet> *> tetContainer::_perThread private
Definition at line 304 of file delaunay3d.cpp.
Referenced by newTet(), operator()(), size(), tetContainer(), and ~tetContainer().
The documentation for this class was generated from the following file:
src/mesh/delaunay3d.cpp