gmsh-TingyuanDoc: Dof Class Reference
Dof Class Reference
#include <dofManager.h>
Public Member Functions
Dof (long int entity, int type)
long int getEntity () const
int getType () const
bool operator< (const Dof &other) const
bool operator== (const Dof &other) const
Static Public Member Functions
static int createTypeWithTwoInts (int i1, int i2)
static void getTwoIntsFromType (int t, int &i1, int &i2)
Protected Attributes
long int _entity
int _type
Detailed Description
Definition at line 19 of file dofManager.h.
Constructor & Destructor Documentation
Dof()
Dof::Dof (long int entity, int type) inline
Definition at line 25 of file dofManager.h.
Member Function Documentation
createTypeWithTwoInts()
static int Dof::createTypeWithTwoInts (int i1, int i2) inline static
Definition at line 28 of file dofManager.h.
Referenced by dofManager< double >::assemble(), frameSolver2d::createDofs(), dofManager< double >::fixVertex(), dofManager< double >::getDofValue(), ScalarToAnyFunctionSpace< SVector3 >::getKeys(), xFemFunctionSpace< T >::getKeys(), helmholtzTerm< double >::getLocalDofC(), elasticityTerm::getLocalDofC(), helmholtzTerm< double >::getLocalDofR(), elasticityTerm::getLocalDofR(), elasticityMixedTerm::getLocalDofR(), dofManager< double >::isFixed(), dofManager< double >::numberVertex(), and frameSolver2d::solve().
getEntity()
long int Dof::getEntity () const inline
Definition at line 26 of file dofManager.h.
Referenced by FixNodalDofs(), FilterNodeEnriched::operator()(), and FilterElementsCutByLevelSet::operator()().
getTwoIntsFromType()
static void Dof::getTwoIntsFromType (int t, int & i1, int & i2) inline static
Definition at line 32 of file dofManager.h.
Referenced by ScalarToAnyFunctionSpace< SVector3 >::getKeys(), xFemFunctionSpace< T >::getKeys(), FilterNodeEnriched::operator()(), FilterElementsCutByLevelSet::operator()(), and FilterDofComponent::operator()().
getType()
int Dof::getType () const inline
Definition at line 27 of file dofManager.h.
Referenced by FilterNodeEnriched::operator()(), FilterElementsCutByLevelSet::operator()(), and FilterDofComponent::operator()().
operator<()
bool Dof::operator< (const Dof & other) const inline
Definition at line 37 of file dofManager.h.
operator==()
bool Dof::operator== (const Dof & other) const inline
Definition at line 44 of file dofManager.h.
Member Data Documentation
_entity
long int Dof::_entity protected
Definition at line 22 of file dofManager.h.
Referenced by getEntity(), operator<(), and operator==().
_type
int Dof::_type protected
Definition at line 23 of file dofManager.h.
Referenced by getType(), operator<(), and operator==().
The documentation for this class was generated from the following file:
src/solver/dofManager.h