gmsh-TingyuanDoc: MElementOctree Class Reference
MElementOctree Class Reference
#include <MElementOctree.h>
Public Member Functions
MElementOctree (GModel *)
MElementOctree (const std::vector< MElement * > &)
~MElementOctree ()
MElement * find (double x, double y, double z, int dim=-1, bool strict=false) const
std::vector< MElement * > findAll (double x, double y, double z, int dim, bool strict=false) const
Private Attributes
Octree * _octree
GModel * _gm
std::vector< MElement * > _elems
Detailed Description
Definition at line 15 of file MElementOctree.h.
Constructor & Destructor Documentation
MElementOctree() [1/2]
MElementOctree::MElementOctree (GModel * m)
Definition at line 92 of file MElementOctree.cpp.
MElementOctree() [2/2]
MElementOctree::MElementOctree (const std::vector< MElement * > & v)
Definition at line 121 of file MElementOctree.cpp.
~MElementOctree()
MElementOctree::~MElementOctree ()
Definition at line 143 of file MElementOctree.cpp.
Member Function Documentation
find()
MElement * MElementOctree::find (double x, double y, double z, int dim = -1, bool strict = false) const
Definition at line 205 of file MElementOctree.cpp.
Referenced by discreteFace::containsParam(), discreteFace::curvatures(), discreteFace::firstDer(), backgroundMesh::getAngle(), backgroundMesh::getMeshElementByCoord(), GModel::getMeshElementByCoord(), backgroundMesh::getSmoothness(), backgroundMesh::inDomain(), discreteFace::intersectionWithCircle(), discreteFace::normal(), backgroundMesh::operator()(), meshMetric::operator()(), discreteFace::point(), and discreteFace::trianglePosition().
findAll()
std::vector< MElement * > MElementOctree::findAll (double x, double y, double z, int dim, bool strict = false) const
Definition at line 145 of file MElementOctree.cpp.
Referenced by GModel::getMeshElementsByCoord().
Member Data Documentation
_elems
std::vector<MElement *> MElementOctree::_elems private
Definition at line 19 of file MElementOctree.h.
Referenced by find(), and findAll().
_gm
GModel* MElementOctree::_gm private
Definition at line 18 of file MElementOctree.h.
Referenced by find(), and findAll().
_octree
Octree* MElementOctree::_octree private
Definition at line 17 of file MElementOctree.h.
Referenced by find(), findAll(), MElementOctree(), and ~MElementOctree().
The documentation for this class was generated from the following files:
src/geo/MElementOctree.h
src/geo/MElementOctree.cpp