gmsh-TingyuanDoc: GeomMeshMatcher Class Reference
GeomMeshMatcher Class Reference
#include <GeomMeshMatcher.h>
Public Member Functions
int match (GModel *geom, GModel *mesh)
int forceTomatch (GModel *geom, GModel *mesh, const double TOL)
Static Public Member Functions
static GeomMeshMatcher * instance ()
static void destroy ()
Private Member Functions
std::vector< Pair< GVertex *, GVertex * > > * matchVertices (GModel *m1, GModel *m2, bool &ok)
std::vector< Pair< GEdge *, GEdge * > > * matchEdges (GModel *m1, GModel *m2, std::vector< Pair< GVertex *, GVertex * > > *coresp_v, bool &ok)
std::vector< Pair< GFace *, GFace * > > * matchFaces (GModel *m1, GModel *m2, std::vector< Pair< GEdge *, GEdge * > > *coresp_e, bool &ok)
std::vector< Pair< GRegion *, GRegion * > > * matchRegions (GModel *m1, GModel *m2, std::vector< Pair< GFace *, GFace * > > *coresp_f, bool &ok)
GeomMeshMatcher ()
~GeomMeshMatcher ()
Static Private Attributes
static GeomMeshMatcher * _gmm_instance = nullptr
Detailed Description
Definition at line 21 of file GeomMeshMatcher.h.
Constructor & Destructor Documentation
GeomMeshMatcher()
GeomMeshMatcher::GeomMeshMatcher () inline private
Definition at line 35 of file GeomMeshMatcher.h.
Referenced by instance().
~GeomMeshMatcher()
GeomMeshMatcher::~GeomMeshMatcher () inline private
Definition at line 36 of file GeomMeshMatcher.h.
Member Function Documentation
destroy()
void GeomMeshMatcher::destroy () static
Definition at line 405 of file GeomMeshMatcher.cpp.
forceTomatch()
int GeomMeshMatcher::forceTomatch (GModel * geom, GModel * mesh, const double TOL)
Definition at line 480 of file GeomMeshMatcher.cpp.
instance()
GeomMeshMatcher * GeomMeshMatcher::instance () static
Definition at line 397 of file GeomMeshMatcher.cpp.
Referenced by MergeFile().
match()
int GeomMeshMatcher::match (GModel * geom, GModel * mesh)
Definition at line 850 of file GeomMeshMatcher.cpp.
Referenced by MergeFile().
matchEdges()
std::vector< Pair< GEdge *, GEdge * > > * GeomMeshMatcher::matchEdges (GModel * m1, GModel * m2, std::vector< Pair< GVertex *, GVertex * > > * coresp_v, bool & ok) private
Definition at line 124 of file GeomMeshMatcher.cpp.
Referenced by match().
matchFaces()
std::vector< Pair< GFace *, GFace * > > * GeomMeshMatcher::matchFaces (GModel * m1, GModel * m2, std::vector< Pair< GEdge *, GEdge * > > * coresp_e, bool & ok) private
Definition at line 217 of file GeomMeshMatcher.cpp.
Referenced by match().
matchRegions()
std::vector< Pair< GRegion *, GRegion * > > * GeomMeshMatcher::matchRegions (GModel * m1, GModel * m2, std::vector< Pair< GFace *, GFace * > > * coresp_f, bool & ok) private
Definition at line 296 of file GeomMeshMatcher.cpp.
Referenced by match().
matchVertices()
std::vector< Pair< GVertex *, GVertex * > > * GeomMeshMatcher::matchVertices (GModel * m1, GModel * m2, bool & ok) private
Definition at line 75 of file GeomMeshMatcher.cpp.
Referenced by match().
Member Data Documentation
_gmm_instance
GeomMeshMatcher * GeomMeshMatcher::_gmm_instance = nullptr static private
Definition at line 34 of file GeomMeshMatcher.h.
Referenced by destroy(), and instance().
The documentation for this class was generated from the following files:
src/geo/GeomMeshMatcher.h
src/geo/GeomMeshMatcher.cpp