gmsh-TingyuanDoc: Range< T > Class Template Reference
Range< T > Class Template Reference
#include <Range.h>
Public Member Functions
Range ()
Range (const T &low, const T &high)
T low () const
void low (const T &low)
T high () const
void high (const T &high)
int contains (const T &value) const
int contains (const Range< T > &range) const
int operator== (const Range< T > &range) const
Private Attributes
T Low
T High
Detailed Description
template<class T>
class Range< T >
Definition at line 10 of file Range.h.
Constructor & Destructor Documentation
Range() [1/2]
template<class T > Range< T >::Range () inline
Definition at line 16 of file Range.h.
Range() [2/2]
template<class T > Range< T >::Range (const T & low, const T & high) inline
Definition at line 17 of file Range.h.
Member Function Documentation
contains() [1/2]
template<class T > int Range< T >::contains (const Range< T > & range) const
Definition at line 32 of file Range.h.
contains() [2/2]
template<class T > int Range< T >::contains (const T & value) const
Definition at line 27 of file Range.h.
high() [1/2]
template<class T > T Range< T >::high () const inline
Definition at line 20 of file Range.h.
Referenced by GEdge::bounds(), bowyerWatsonFrontal(), buildConsecutiveListOfVertices(), GFace::buildRepresentationCross(), GFace::buildSTLTriangulation(), GEdge::closestPoint(), GFace::closestPoint(), GFace::computeMeanPlane(), Range< T >::contains(), GEdge::containsParam(), GFace::containsParam(), copyMesh(), blyr_manager::extrude_vertices_on_edges(), extrudeMesh(), faceIsValidQuad(), fillPointCloud(), GFace::fillPointCloud(), getAllParameters(), GRegion::getOBB(), GEdge::getOBB(), GFace::getOBB(), LC_MVertex_PNTS(), max_edge_curvature(), max_edge_curvature_metric(), meshGEdgeTargetNumberOfPoints(), meshGeneratorPeriodic(), GFace::moveToValidRange(), meshGEdge::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), F_Transfinite::operator()(), Range< T >::operator==(), GEdge::refineProjection(), remeshUnrecoveredEdges(), reparamMeshVertexOnEdge(), GEdge::secondDer(), GFace::setMeshMaster(), GModel::snapVertices(), trueBoundary(), DistanceField::update(), GEdge::XYZToU(), and GFace::XYZtoUV().
high() [2/2]
template<class T > void Range< T >::high (const T & high) inline
Definition at line 21 of file Range.h.
Referenced by Range< T >::high().
low() [1/2]
template<class T > T Range< T >::low () const inline
Definition at line 18 of file Range.h.
Referenced by GEdge::bounds(), buildConsecutiveListOfVertices(), GFace::buildRepresentationCross(), GFace::buildSTLTriangulation(), GEdge::closestPoint(), GFace::closestPoint(), GFace::computeMeanPlane(), Range< T >::contains(), GEdge::containsParam(), GFace::containsParam(), copyMesh(), blyr_manager::extrude_vertices_on_edges(), extrudeMesh(), faceIsValidQuad(), fillPointCloud(), GFace::fillPointCloud(), getAllParameters(), GRegion::getOBB(), GEdge::getOBB(), GFace::getOBB(), LC_MVertex_PNTS(), max_edge_curvature(), max_edge_curvature_metric(), meshGEdgeTargetNumberOfPoints(), meshGeneratorPeriodic(), GFace::moveToValidRange(), meshGEdge::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), F_Transfinite::operator()(), Range< T >::operator==(), GEdge::refineProjection(), remeshUnrecoveredEdges(), reparamMeshVertexOnEdge(), gmshVertex::reparamOnFace(), GEdge::secondDer(), GFace::setMeshMaster(), GModel::snapVertices(), trueBoundary(), DistanceField::update(), GEdge::XYZToU(), and GFace::XYZtoUV().
low() [2/2]
template<class T > void Range< T >::low (const T & low) inline
Definition at line 19 of file Range.h.
Referenced by Range< T >::low().
operator==()
template<class T > int Range< T >::operator== (const Range< T > & range) const
Definition at line 37 of file Range.h.
Member Data Documentation
High
template<class T > T Range< T >::High private
Definition at line 13 of file Range.h.
Referenced by Range< T >::high().
Low
template<class T > T Range< T >::Low private
Definition at line 12 of file Range.h.
Referenced by Range< T >::low().
The documentation for this class was generated from the following file:
src/geo/Range.h