gmsh-TingyuanDoc: GEO_Internals Class Reference
GEO_Internals Class Reference
#include <GModelIO_GEO.h>
Public Member Functions
GEO_Internals ()
~GEO_Internals ()
void destroy ()
bool getChanged () const
void setMaxTag (int dim, int val)
int getMaxTag (int dim) const
bool addVertex (int &tag, double x, double y, double z, double lc)
bool addVertex (int &tag, double x, double y, gmshSurface *s, double lc)
bool addLine (int &tag, int startTag, int endTag)
bool addLine (int &tag, const std::vector< int > &pointTags)
bool addCircleArc (int &tag, int startTag, int centerTag, int endTag, double nx=0., double ny=0., double nz=0.)
bool addEllipseArc (int &tag, int startTag, int centerTag, int majorTag, int endTag, double nx=0., double ny=0., double nz=0.)
bool addSpline (int &tag, const std::vector< int > &pointTags)
bool addBezier (int &tag, const std::vector< int > &pointTags)
bool addBSpline (int &tag, const std::vector< int > &pointTags, const std::vector< double > &seqknots=std::vector< double >())
bool addCompoundSpline (int &tag, const std::vector< int > &curveTags, int numPoints)
bool addCompoundBSpline (int &tag, const std::vector< int > &curveTags, int numPoints)
bool addCurveLoop (int &tag, const std::vector< int > &curveTags, bool reorient=false)
bool addCurveLoops (const std::vector< int > &curveTags, std::vector< int > &curveLoopTags)
bool addPlaneSurface (int &tag, const std::vector< int > &wireTags)
bool addDiscreteSurface (int &tag)
bool addSurfaceFilling (int &tag, const std::vector< int > &wireTags, int sphereCenterTag=-1)
bool addSurfaceLoop (int &tag, const std::vector< int > &surfaceTags)
bool addVolume (int &tag, const std::vector< int > &shellTags)
bool extrude (const std::vector< std::pair< int, int > > &inDimTags, double dx, double dy, double dz, std::vector< std::pair< int, int > > &outDimTags, ExtrudeParams *e=0)
bool revolve (const std::vector< std::pair< int, int > > &inDimTags, double x, double y, double z, double ax, double ay, double az, double angle, std::vector< std::pair< int, int > > &outDimTags, ExtrudeParams *e=0)
bool twist (const std::vector< std::pair< int, int > > &inDimTags, double x, double y, double z, double dx, double dy, double dz, double ax, double ay, double az, double angle, std::vector< std::pair< int, int > > &outDimTags, ExtrudeParams *e=0)
bool boundaryLayer (const std::vector< std::pair< int, int > > &inDimTags, std::vector< std::pair< int, int > > &outDimTags, ExtrudeParams *e=0)
bool translate (const std::vector< std::pair< int, int > > &dimTags, double dx, double dy, double dz)
bool rotate (const std::vector< std::pair< int, int > > &dimTags, double x, double y, double z, double ax, double ay, double az, double angle)
bool dilate (const std::vector< std::pair< int, int > > &dimTags, double x, double y, double z, double a, double b, double c)
bool symmetry (const std::vector< std::pair< int, int > > &dimTags, double a, double b, double c, double d)
bool splitCurve (int tag, const std::vector< int > &pointTags, std::vector< int > &curveTags)
bool intersectCurvesWithSurface (const std::vector< int > &curveTags, int surfaceTag, std::vector< int > &pointTags)
bool copy (const std::vector< std::pair< int, int > > &inDimTags, std::vector< std::pair< int, int > > &outDimTags)
bool remove (int dim, int tag, bool recursive=false)
bool remove (const std::vector< std::pair< int, int > > &dimTags, bool recursive=false)
void resetPhysicalGroups ()
bool modifyPhysicalGroup (int dim, int tag, int op, const std::vector< int > &tags)
int getMaxPhysicalTag () const
void setMaxPhysicalTag (int val)
void removeAllDuplicates ()
bool mergeVertices (const std::vector< int > &tags)
void setCompoundMesh (int dim, const std::vector< int > &tags)
void setMeshSize (int dim, int tag, double size)
void setDegenerated (int dim, int tag)
void setTransfiniteLine (int tag, int nPoints, int type, double coef)
void setTransfiniteSurface (int tag, int arrangement, const std::vector< int > &cornerTags)
void setTransfiniteVolume (int tag, const std::vector< int > &cornerTags)
void setTransfiniteVolumeQuadTri (int tag)
void setRecombine (int dim, int tag, double angle)
void setSmoothing (int tag, int val)
void setReverseMesh (int dim, int tag, bool val=1)
void setMeshAlgorithm (int dim, int tag, int val)
void setMeshSizeFromBoundary (int dim, int tag, int val)
void synchronize (GModel *model, bool resetMeshAttributes=true)
bool getVertex (int tag, double &x, double &y, double &z)
gmshSurface * newGeometrySphere (int tag, int centerTag, int pointTag)
gmshSurface * newGeometryPolarSphere (int tag, int centerTag, int pointTag)
Public Attributes
Tree_T * Points
Tree_T * Curves
Tree_T * EdgeLoops
Tree_T * Surfaces
Tree_T * SurfaceLoops
Tree_T * Volumes
Tree_T * DelPoints
Tree_T * DelCurves
Tree_T * DelSurfaces
Tree_T * DelVolumes
List_T * PhysicalGroups
List_T * DelPhysicalGroups
Private Member Functions
void _allocateAll ()
void _freeAll ()
bool _transform (int mode, const std::vector< std::pair< int, int > > &dimTags, double x, double y, double z, double dx, double dy, double dz, double a, double b, double c, double d)
bool _extrude (int mode, const std::vector< std::pair< int, int > > &inDimTags, double x, double y, double z, double dx, double dy, double dz, double ax, double ay, double az, double angle, std::vector< std::pair< int, int > > &outDimTags, ExtrudeParams *e=0)
bool _addCompoundSpline (int &tag, const std::vector< int > &curveTags, int numPoints, bool bspline)
Private Attributes
std::multimap< int, std::vector< int > > _meshCompounds
int _maxPointNum
int _maxLineNum
int _maxLineLoopNum
int _maxSurfaceNum
int _maxSurfaceLoopNum
int _maxVolumeNum
int _maxPhysicalNum
bool _changed
Detailed Description
Definition at line 15 of file GModelIO_GEO.h.
Constructor & Destructor Documentation
GEO_Internals()
GEO_Internals::GEO_Internals () inline
Definition at line 41 of file GModelIO_GEO.h.
~GEO_Internals()
GEO_Internals::~GEO_Internals () inline
Definition at line 42 of file GModelIO_GEO.h.
Member Function Documentation
_addCompoundSpline()
bool GEO_Internals::_addCompoundSpline (int & tag, const std::vector< int > & curveTags, int numPoints, bool bspline) private
Definition at line 336 of file GModelIO_GEO.cpp.
Referenced by addCompoundBSpline(), and addCompoundSpline().
_allocateAll()
void GEO_Internals::_allocateAll () private
Definition at line 29 of file GModelIO_GEO.cpp.
Referenced by destroy(), and GEO_Internals().
_extrude()
bool GEO_Internals::_extrude (int mode, const std::vector< std::pair< int, int > > & inDimTags, double x, double y, double z, double dx, double dy, double dz, double ax, double ay, double az, double angle, std::vector< std::pair< int, int > > & outDimTags, ExtrudeParams * e = 0) private
Definition at line 722 of file GModelIO_GEO.cpp.
Referenced by boundaryLayer(), extrude(), revolve(), and twist().
_freeAll()
void GEO_Internals::_freeAll () private
Definition at line 52 of file GModelIO_GEO.cpp.
Referenced by destroy(), and ~GEO_Internals().
_transform()
bool GEO_Internals::_transform (int mode, const std::vector< std::pair< int, int > > & dimTags, double x, double y, double z, double dx, double dy, double dz, double a, double b, double c, double d) private
Definition at line 812 of file GModelIO_GEO.cpp.
Referenced by dilate(), rotate(), symmetry(), and translate().
addBezier()
bool GEO_Internals::addBezier (int & tag, const std::vector< int > & pointTags)
Definition at line 271 of file GModelIO_GEO.cpp.
addBSpline()
bool GEO_Internals::addBSpline (int & tag, const std::vector< int > & pointTags, const std::vector< double > & seqknots = std::vector<double>())
Definition at line 297 of file GModelIO_GEO.cpp.
addCircleArc()
bool GEO_Internals::addCircleArc (int & tag, int startTag, int centerTag, int endTag, double nx = 0., double ny = 0., double nz = 0.)
Definition at line 175 of file GModelIO_GEO.cpp.
addCompoundBSpline()
bool GEO_Internals::addCompoundBSpline (int & tag, const std::vector< int > & curveTags, int numPoints)
Definition at line 394 of file GModelIO_GEO.cpp.
addCompoundSpline()
bool GEO_Internals::addCompoundSpline (int & tag, const std::vector< int > & curveTags, int numPoints)
Definition at line 387 of file GModelIO_GEO.cpp.
addCurveLoop()
bool GEO_Internals::addCurveLoop (int & tag, const std::vector< int > & curveTags, bool reorient = false)
Definition at line 401 of file GModelIO_GEO.cpp.
addCurveLoops()
bool GEO_Internals::addCurveLoops (const std::vector< int > & curveTags, std::vector< int > & curveLoopTags)
Definition at line 529 of file GModelIO_GEO.cpp.
addDiscreteSurface()
bool GEO_Internals::addDiscreteSurface (int & tag)
Definition at line 617 of file GModelIO_GEO.cpp.
addEllipseArc()
bool GEO_Internals::addEllipseArc (int & tag, int startTag, int centerTag, int majorTag, int endTag, double nx = 0., double ny = 0., double nz = 0.)
Definition at line 209 of file GModelIO_GEO.cpp.
addLine() [1/2]
bool GEO_Internals::addLine (int & tag, const std::vector< int > & pointTags)
Definition at line 149 of file GModelIO_GEO.cpp.
addLine() [2/2]
bool GEO_Internals::addLine (int & tag, int startTag, int endTag)
Definition at line 141 of file GModelIO_GEO.cpp.
addPlaneSurface()
bool GEO_Internals::addPlaneSurface (int & tag, const std::vector< int > & wireTags)
Definition at line 592 of file GModelIO_GEO.cpp.
addSpline()
bool GEO_Internals::addSpline (int & tag, const std::vector< int > & pointTags)
Definition at line 245 of file GModelIO_GEO.cpp.
addSurfaceFilling()
bool GEO_Internals::addSurfaceFilling (int & tag, const std::vector< int > & wireTags, int sphereCenterTag = -1)
Definition at line 630 of file GModelIO_GEO.cpp.
addSurfaceLoop()
bool GEO_Internals::addSurfaceLoop (int & tag, const std::vector< int > & surfaceTags)
Definition at line 680 of file GModelIO_GEO.cpp.
addVertex() [1/2]
bool GEO_Internals::addVertex (int & tag, double x, double y, double z, double lc)
Definition at line 112 of file GModelIO_GEO.cpp.
addVertex() [2/2]
bool GEO_Internals::addVertex (int & tag, double x, double y, gmshSurface * s, double lc)
Definition at line 126 of file GModelIO_GEO.cpp.
addVolume()
bool GEO_Internals::addVolume (int & tag, const std::vector< int > & shellTags)
Definition at line 701 of file GModelIO_GEO.cpp.
boundaryLayer()
bool GEO_Internals::boundaryLayer (const std::vector< std::pair< int, int > > & inDimTags, std::vector< std::pair< int, int > > & outDimTags, ExtrudeParams * e = 0)
Definition at line 804 of file GModelIO_GEO.cpp.
copy()
bool GEO_Internals::copy (const std::vector< std::pair< int, int > > & inDimTags, std::vector< std::pair< int, int > > & outDimTags)
Definition at line 913 of file GModelIO_GEO.cpp.
destroy()
void GEO_Internals::destroy () inline
Definition at line 43 of file GModelIO_GEO.h.
Referenced by OpenProject().
dilate()
bool GEO_Internals::dilate (const std::vector< std::pair< int, int > > & dimTags, double x, double y, double z, double a, double b, double c)
Definition at line 855 of file GModelIO_GEO.cpp.
extrude()
bool GEO_Internals::extrude (const std::vector< std::pair< int, int > > & inDimTags, double dx, double dy, double dz, std::vector< std::pair< int, int > > & outDimTags, ExtrudeParams * e = 0)
Definition at line 774 of file GModelIO_GEO.cpp.
getChanged()
bool GEO_Internals::getChanged () const inline
Definition at line 50 of file GModelIO_GEO.h.
getMaxPhysicalTag()
int GEO_Internals::getMaxPhysicalTag () const inline
Definition at line 132 of file GModelIO_GEO.h.
Referenced by NEWPHYSICAL(), and scriptAddRemovePhysicalGroup().
getMaxTag()
int GEO_Internals::getMaxTag (int dim) const
Definition at line 99 of file GModelIO_GEO.cpp.
Referenced by _addCompoundSpline(), addBezier(), addBSpline(), addCircleArc(), addCurveLoop(), addCurveLoops(), addDiscreteSurface(), addEllipseArc(), addLine(), addPlaneSurface(), addSpline(), addSurfaceFilling(), addSurfaceLoop(), addVertex(), addVolume(), DeleteCurve(), DeletePoint(), DeleteSurface(), DeleteVolume(), NEWCURVE(), NEWCURVELOOP(), NEWPOINT(), NEWSURFACE(), NEWSURFACELOOP(), NEWVOLUME(), scriptAddCurveLoop(), scriptAddPipe(), and scriptAddSurfaceLoop().
getVertex()
bool GEO_Internals::getVertex (int tag, double & x, double & y, double & z)
Definition at line 1616 of file GModelIO_GEO.cpp.
intersectCurvesWithSurface()
bool GEO_Internals::intersectCurvesWithSurface (const std::vector< int > & curveTags, int surfaceTag, std::vector< int > & pointTags)
Definition at line 889 of file GModelIO_GEO.cpp.
mergeVertices()
bool GEO_Internals::mergeVertices (const std::vector< int > & tags)
Definition at line 1083 of file GModelIO_GEO.cpp.
modifyPhysicalGroup()
bool GEO_Internals::modifyPhysicalGroup (int dim, int tag, int op, const std::vector< int > & tags)
Definition at line 1000 of file GModelIO_GEO.cpp.
newGeometryPolarSphere()
gmshSurface * GEO_Internals::newGeometryPolarSphere (int tag, int centerTag, int pointTag)
Definition at line 1648 of file GModelIO_GEO.cpp.
newGeometrySphere()
gmshSurface * GEO_Internals::newGeometrySphere (int tag, int centerTag, int pointTag)
Definition at line 1628 of file GModelIO_GEO.cpp.
remove() [1/2]
bool GEO_Internals::remove (const std::vector< std::pair< int, int > > & dimTags, bool recursive = false)
Definition at line 984 of file GModelIO_GEO.cpp.
remove() [2/2]
bool GEO_Internals::remove (int dim, int tag, bool recursive = false)
Definition at line 969 of file GModelIO_GEO.cpp.
Referenced by remove().
removeAllDuplicates()
void GEO_Internals::removeAllDuplicates ()
Definition at line 1077 of file GModelIO_GEO.cpp.
resetPhysicalGroups()
void GEO_Internals::resetPhysicalGroups ()
Definition at line 992 of file GModelIO_GEO.cpp.
revolve()
bool GEO_Internals::revolve (const std::vector< std::pair< int, int > > & inDimTags, double x, double y, double z, double ax, double ay, double az, double angle, std::vector< std::pair< int, int > > & outDimTags, ExtrudeParams * e = 0)
Definition at line 783 of file GModelIO_GEO.cpp.
rotate()
bool GEO_Internals::rotate (const std::vector< std::pair< int, int > > & dimTags, double x, double y, double z, double ax, double ay, double az, double angle)
Definition at line 848 of file GModelIO_GEO.cpp.
setCompoundMesh()
void GEO_Internals::setCompoundMesh (int dim, const std::vector< int > & tags)
Definition at line 1111 of file GModelIO_GEO.cpp.
setDegenerated()
void GEO_Internals::setDegenerated (int dim, int tag)
Definition at line 1128 of file GModelIO_GEO.cpp.
setMaxPhysicalTag()
void GEO_Internals::setMaxPhysicalTag (int val) inline
Definition at line 133 of file GModelIO_GEO.h.
Referenced by CreatePhysicalGroup().
setMaxTag()
void GEO_Internals::setMaxTag (int dim, int val)
Definition at line 87 of file GModelIO_GEO.cpp.
Referenced by CreateCurve(), CreateEdgeLoop(), CreateSurface(), CreateSurfaceLoop(), CreateVertex(), CreateVolume(), DeleteCurve(), DeletePoint(), DeleteSurface(), DeleteVolume(), ExtrudeSurface(), MaxNumCurve(), MaxNumPoint(), MaxNumSurface(), MergeFile(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), and ReplaceDuplicateSurfaces().
setMeshAlgorithm()
void GEO_Internals::setMeshAlgorithm (int dim, int tag, int val)
Definition at line 1344 of file GModelIO_GEO.cpp.
setMeshSize()
void GEO_Internals::setMeshSize (int dim, int tag, double size)
Definition at line 1117 of file GModelIO_GEO.cpp.
setMeshSizeFromBoundary()
void GEO_Internals::setMeshSizeFromBoundary (int dim, int tag, int val)
Definition at line 1353 of file GModelIO_GEO.cpp.
setRecombine()
void GEO_Internals::setRecombine (int dim, int tag, double angle)
Definition at line 1252 of file GModelIO_GEO.cpp.
setReverseMesh()
void GEO_Internals::setReverseMesh (int dim, int tag, bool val = 1)
Definition at line 1309 of file GModelIO_GEO.cpp.
setSmoothing()
void GEO_Internals::setSmoothing (int tag, int val)
Definition at line 1291 of file GModelIO_GEO.cpp.
setTransfiniteLine()
void GEO_Internals::setTransfiniteLine (int tag, int nPoints, int type, double coef)
Definition at line 1136 of file GModelIO_GEO.cpp.
setTransfiniteSurface()
void GEO_Internals::setTransfiniteSurface (int tag, int arrangement, const std::vector< int > & cornerTags)
Definition at line 1163 of file GModelIO_GEO.cpp.
setTransfiniteVolume()
void GEO_Internals::setTransfiniteVolume (int tag, const std::vector< int > & cornerTags)
Definition at line 1201 of file GModelIO_GEO.cpp.
setTransfiniteVolumeQuadTri()
void GEO_Internals::setTransfiniteVolumeQuadTri (int tag)
Definition at line 1234 of file GModelIO_GEO.cpp.
splitCurve()
bool GEO_Internals::splitCurve (int tag, const std::vector< int > & pointTags, std::vector< int > & curveTags)
Definition at line 868 of file GModelIO_GEO.cpp.
symmetry()
bool GEO_Internals::symmetry (const std::vector< std::pair< int, int > > & dimTags, double a, double b, double c, double d)
Definition at line 862 of file GModelIO_GEO.cpp.
synchronize()
void GEO_Internals::synchronize (GModel * model, bool resetMeshAttributes = true)
Definition at line 1370 of file GModelIO_GEO.cpp.
Referenced by addEmbedded(), addPeriodicEdge(), addPeriodicFace(), getAllElementaryTags(), getAllPhysicalTags(), getBoundingBox(), getElementaryTagsForPhysicalGroups(), getElementaryTagsInBoundingBox(), getParentTags(), GModel::readGEO(), removeEmbedded(), scriptAddCommand(), setColor(), and setVisibility().
translate()
bool GEO_Internals::translate (const std::vector< std::pair< int, int > > & dimTags, double dx, double dy, double dz)
Definition at line 842 of file GModelIO_GEO.cpp.
twist()
bool GEO_Internals::twist (const std::vector< std::pair< int, int > > & inDimTags, double x, double y, double z, double dx, double dy, double dz, double ax, double ay, double az, double angle, std::vector< std::pair< int, int > > & outDimTags, ExtrudeParams * e = 0)
Definition at line 793 of file GModelIO_GEO.cpp.
Member Data Documentation
_changed
bool GEO_Internals::_changed private
Definition at line 28 of file GModelIO_GEO.h.
Referenced by _addCompoundSpline(), _allocateAll(), _extrude(), _freeAll(), _transform(), addBezier(), addBSpline(), addCircleArc(), addCurveLoop(), addCurveLoops(), addDiscreteSurface(), addEllipseArc(), addLine(), addPlaneSurface(), addSpline(), addSurfaceFilling(), addSurfaceLoop(), addVertex(), addVolume(), copy(), getChanged(), intersectCurvesWithSurface(), mergeVertices(), modifyPhysicalGroup(), remove(), removeAllDuplicates(), resetPhysicalGroups(), setCompoundMesh(), setDegenerated(), setMeshAlgorithm(), setMeshSize(), setMeshSizeFromBoundary(), setRecombine(), setReverseMesh(), setSmoothing(), setTransfiniteLine(), setTransfiniteSurface(), setTransfiniteVolume(), setTransfiniteVolumeQuadTri(), splitCurve(), and synchronize().
_maxLineLoopNum
int GEO_Internals::_maxLineLoopNum private
Definition at line 24 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), getMaxTag(), and setMaxTag().
_maxLineNum
int GEO_Internals::_maxLineNum private
Definition at line 24 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), getMaxTag(), and setMaxTag().
_maxPhysicalNum
int GEO_Internals::_maxPhysicalNum private
Definition at line 25 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), getMaxPhysicalTag(), and setMaxPhysicalTag().
_maxPointNum
int GEO_Internals::_maxPointNum private
Definition at line 24 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), getMaxTag(), and setMaxTag().
_maxSurfaceLoopNum
int GEO_Internals::_maxSurfaceLoopNum private
Definition at line 25 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), getMaxTag(), and setMaxTag().
_maxSurfaceNum
int GEO_Internals::_maxSurfaceNum private
Definition at line 24 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), getMaxTag(), and setMaxTag().
_maxVolumeNum
int GEO_Internals::_maxVolumeNum private
Definition at line 25 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), getMaxTag(), and setMaxTag().
_meshCompounds
std::multimap<int, std::vector<int> > GEO_Internals::_meshCompounds private
Definition at line 23 of file GModelIO_GEO.h.
Referenced by setCompoundMesh(), and synchronize().
Curves
Tree_T * GEO_Internals::Curves
Definition at line 18 of file GModelIO_GEO.h.
Referenced by _addCompoundSpline(), _allocateAll(), _freeAll(), addBezier(), addBSpline(), addCircleArc(), addEllipseArc(), addLine(), addSpline(), discreteEdge::discreteEdge(), GModel::exportDiscreteGEOInternals(), setReverseMesh(), setTransfiniteLine(), and synchronize().
DelCurves
Tree_T * GEO_Internals::DelCurves
Definition at line 19 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), and ReplaceDuplicateCurves().
DelPhysicalGroups
List_T * GEO_Internals::DelPhysicalGroups
Definition at line 20 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), and resetPhysicalGroups().
DelPoints
Tree_T* GEO_Internals::DelPoints
Definition at line 19 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), and ReplaceDuplicatePoints().
DelSurfaces
Tree_T * GEO_Internals::DelSurfaces
Definition at line 19 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), and ReplaceDuplicateSurfaces().
DelVolumes
Tree_T * GEO_Internals::DelVolumes
Definition at line 19 of file GModelIO_GEO.h.
Referenced by _allocateAll(), and _freeAll().
EdgeLoops
Tree_T * GEO_Internals::EdgeLoops
Definition at line 18 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), addCurveLoop(), and addCurveLoops().
PhysicalGroups
List_T* GEO_Internals::PhysicalGroups
Definition at line 20 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), modifyPhysicalGroup(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicateSurfaces(), resetPhysicalGroups(), SplitCurve(), and synchronize().
Points
Tree_T* GEO_Internals::Points
Definition at line 18 of file GModelIO_GEO.h.
Referenced by _addCompoundSpline(), _allocateAll(), _freeAll(), addVertex(), discreteVertex::discreteVertex(), GModel::exportDiscreteGEOInternals(), and synchronize().
SurfaceLoops
Tree_T * GEO_Internals::SurfaceLoops
Definition at line 18 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), and addSurfaceLoop().
Surfaces
Tree_T * GEO_Internals::Surfaces
Definition at line 18 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), addDiscreteSurface(), addPlaneSurface(), addSurfaceFilling(), discreteFace::discreteFace(), GModel::exportDiscreteGEOInternals(), setRecombine(), setReverseMesh(), setSmoothing(), setTransfiniteSurface(), and synchronize().
Volumes
Tree_T * GEO_Internals::Volumes
Definition at line 18 of file GModelIO_GEO.h.
Referenced by _allocateAll(), _freeAll(), addVolume(), discreteRegion::discreteRegion(), GModel::exportDiscreteGEOInternals(), setRecombine(), setTransfiniteVolume(), setTransfiniteVolumeQuadTri(), and synchronize().
The documentation for this class was generated from the following files:
src/geo/GModelIO_GEO.h
src/geo/GModelIO_GEO.cpp