gmsh-TingyuanDoc: gLevelsetPoints Class Reference
gLevelsetPoints Class Reference
#include <gmshLevelset.h>
Public Member Functions
gLevelsetPoints (fullMatrix< double > &_centers, int tag=0)
gLevelsetPoints (const gLevelsetPoints &lv)
virtual gLevelset * clone () const
virtual double operator() (double x, double y, double z) const
void computeLS (std::vector< MVertex * > &vert)
int type () const
Public Member Functions inherited from gLevelsetPrimitive
gLevelsetPrimitive ()
gLevelsetPrimitive (const gLevelsetPrimitive &lv)
gLevelsetPrimitive (int tag)
std::vector< gLevelset * > getChildren () const
double choose (double d1, double d2) const
virtual bool isPrimitive () const
Public Member Functions inherited from gLevelset
gLevelset (int tag=0)
gLevelset (const gLevelset &)
virtual ~gLevelset ()
bool isInsideDomain (const double &x, const double &y, const double &z) const
bool isOutsideDomain (const double &x, const double &y, const double &z) const
bool isOnBorder (const double &x, const double &y, const double &z) const
void setTag (int t)
virtual int getTag () const
void getPrimitives (std::vector< gLevelset * > &primitives)
void getPrimitivesPO (std::vector< gLevelset * > &primitives)
void getRPN (std::vector< gLevelset * > &gLsRPN)
double H (const double &x, const double &y, const double &z) const
void print () const
Public Member Functions inherited from simpleFunction< double >
simpleFunction (double val=0.0)
virtual ~simpleFunction ()
virtual bool hasDerivatives ()
virtual void setElement (MElement *e) const
virtual void gradient (double x, double y, double z, double &dfdx, double &dfdy, double &dfdz) const
virtual void hessian (double x, double y, double z, double &dfdxx, double &dfdxy, double &dfdxz, double &dfdyx, double &dfdyy, double &dfdyz, double &dfdzx, double &dfdzy, double &dfdzz) const
Protected Member Functions
fullMatrix< double > generateRbfMat (int p, int index, const fullMatrix< double > &nodes1, const fullMatrix< double > &nodes2) const
void RbfOp (int p, int index, const fullMatrix< double > &cntrs, const fullMatrix< double > &nodes, fullMatrix< double > &D, bool isLocal=false) const
void evalRbfDer (int p, int index, const fullMatrix< double > &cntrs, const fullMatrix< double > &nodes, const fullMatrix< double > &fValues, fullMatrix< double > &fApprox, bool isLocal=false) const
void setup_level_set (const fullMatrix< double > &cntrs, fullMatrix< double > &level_set_nodes, fullMatrix< double > &level_set_funvals)
Protected Attributes
fullMatrix< double > points
fullMatrix< double > surf
fullMatrix< double > matAInv
double delta
std::map< SPoint3, double > mapP
Protected Attributes inherited from gLevelset
int tag_
Protected Attributes inherited from simpleFunction< double >
double _val
bool _hasDerivatives
Additional Inherited Members
Static Public Member Functions inherited from gLevelset
static gLevelset * find (int tag)
static void add (gLevelset *l)
Static Protected Attributes inherited from gLevelset
static const short insideDomain = -1
static int maxTag_ = 0
static std::set< gLevelset *, gLevelsetLessThan > all_
Detailed Description
Definition at line 217 of file gmshLevelset.h.
Constructor & Destructor Documentation
gLevelsetPoints() [1/2]
gLevelsetPoints::gLevelsetPoints (fullMatrix< double > & _centers, int tag = 0)
Definition at line 545 of file gmshLevelset.cpp.
Referenced by clone().
gLevelsetPoints() [2/2]
gLevelsetPoints::gLevelsetPoints (const gLevelsetPoints & lv)
Definition at line 560 of file gmshLevelset.cpp.
Member Function Documentation
clone()
virtual gLevelset* gLevelsetPoints::clone () const inline virtual
Reimplemented from gLevelset.
Definition at line 243 of file gmshLevelset.h.
computeLS()
void gLevelsetPoints::computeLS (std::vector< MVertex * > & vert)
Definition at line 585 of file gmshLevelset.cpp.
evalRbfDer()
void gLevelsetPoints::evalRbfDer (int p, int index, const fullMatrix< double > & cntrs, const fullMatrix< double > & nodes, const fullMatrix< double > & fValues, fullMatrix< double > & fApprox, bool isLocal = false) const protected
Definition at line 470 of file gmshLevelset.cpp.
Referenced by computeLS(), and setup_level_set().
generateRbfMat()
fullMatrix< double > gLevelsetPoints::generateRbfMat (int p, int index, const fullMatrix< double > & nodes1, const fullMatrix< double > & nodes2) const protected
Definition at line 431 of file gmshLevelset.cpp.
Referenced by gLevelsetPoints(), and RbfOp().
operator()()
double gLevelsetPoints::operator() (double x, double y, double z) const virtual
Implements gLevelsetPrimitive.
Definition at line 566 of file gmshLevelset.cpp.
RbfOp()
void gLevelsetPoints::RbfOp (int p, int index, const fullMatrix< double > & cntrs, const fullMatrix< double > & nodes, fullMatrix< double > & D, bool isLocal = false) const protected
Definition at line 451 of file gmshLevelset.cpp.
Referenced by evalRbfDer().
setup_level_set()
void gLevelsetPoints::setup_level_set (const fullMatrix< double > & cntrs, fullMatrix< double > & level_set_nodes, fullMatrix< double > & level_set_funvals) protected
Definition at line 483 of file gmshLevelset.cpp.
Referenced by gLevelsetPoints().
type()
int gLevelsetPoints::type () const inline virtual
Implements gLevelsetPrimitive.
Definition at line 247 of file gmshLevelset.h.
Member Data Documentation
delta
double gLevelsetPoints::delta protected
Definition at line 222 of file gmshLevelset.h.
Referenced by generateRbfMat(), and setup_level_set().
mapP
std::map<SPoint3, double> gLevelsetPoints::mapP protected
Definition at line 223 of file gmshLevelset.h.
Referenced by computeLS(), and operator()().
matAInv
fullMatrix<double> gLevelsetPoints::matAInv protected
Definition at line 221 of file gmshLevelset.h.
Referenced by gLevelsetPoints(), and RbfOp().
points
fullMatrix<double> gLevelsetPoints::points protected
Definition at line 219 of file gmshLevelset.h.
Referenced by computeLS(), and gLevelsetPoints().
surf
fullMatrix<double> gLevelsetPoints::surf protected
Definition at line 220 of file gmshLevelset.h.
Referenced by computeLS(), and gLevelsetPoints().
The documentation for this class was generated from the following files:
src/geo/gmshLevelset.h
src/geo/gmshLevelset.cpp