gmsh-TingyuanDoc: FunctionSpaceBase Class Reference
FunctionSpaceBase Class Reference abstract
#include <functionSpace.h>
Public Member Functions
virtual ~FunctionSpaceBase ()
virtual int getId (void) const =0
virtual int getNumKeys (MElement *ele) const =0
virtual void getKeys (MElement *ele, std::vector< Dof > &keys) const =0
virtual void getKeysOnVertex (MElement *ele, MVertex *v, const std::vector< int > &comp, std::vector< Dof > &keys) const
virtual FunctionSpaceBase * clone (const int id) const
Detailed Description
Definition at line 61 of file functionSpace.h.
Constructor & Destructor Documentation
~FunctionSpaceBase()
virtual FunctionSpaceBase::~FunctionSpaceBase () inline virtual
Definition at line 63 of file functionSpace.h.
Member Function Documentation
clone()
virtual FunctionSpaceBase* FunctionSpaceBase::clone (const int id) const inline virtual
Definition at line 76 of file functionSpace.h.
getId()
virtual int FunctionSpaceBase::getId (void) const pure virtual
Implemented in FunctionSpace< T >, FunctionSpace< T1 >, FunctionSpace< T2 >, FunctionSpace< double >, and FunctionSpace< SVector3 >.
getKeys()
virtual void FunctionSpaceBase::getKeys (MElement * ele, std::vector< Dof > & keys) const pure virtual
Implemented in FunctionSpace< T1 >, FunctionSpace< T2 >, FunctionSpace< double >, FunctionSpace< SVector3 >, FunctionSpace< T >, FilteredFunctionSpace< T, F >, xFemFunctionSpace< T >, CompositeFunctionSpace< T >, ScalarToAnyFunctionSpace< T >, ScalarToAnyFunctionSpace< SVector3 >, ScalarLagrangeFunctionSpace, ScalarLagrangeFunctionSpaceOfElement, and SolverField< T >.
Referenced by Assemble(), FixNodalDofs(), and NumberDofs().
getKeysOnVertex()
virtual void FunctionSpaceBase::getKeysOnVertex (MElement * ele, MVertex * v, const std::vector< int > & comp, std::vector< Dof > & keys) const inline virtual
Definition at line 68 of file functionSpace.h.
getNumKeys()
virtual int FunctionSpaceBase::getNumKeys (MElement * ele) const pure virtual
Implemented in FunctionSpace< T1 >, FunctionSpace< T2 >, FunctionSpace< double >, FunctionSpace< SVector3 >, FunctionSpace< T >, FilteredFunctionSpace< T, F >, xFemFunctionSpace< T >, CompositeFunctionSpace< T >, ScalarToAnyFunctionSpace< T >, ScalarToAnyFunctionSpace< SVector3 >, ScalarLagrangeFunctionSpace, ScalarLagrangeFunctionSpaceOfElement, and SolverField< T >.
The documentation for this class was generated from the following file:
src/solver/functionSpace.h