gmsh-TingyuanDoc: qmQuadrangle Class Reference
qmQuadrangle Class Reference
#include <qualityMeasures.h>
Static Public Member Functions
static double gamma (MQuadrangle *el)
static double eta (MQuadrangle *el)
static double angles (MQuadrangle *e)
static double minNCJ (const MQuadrangle *e)
static void NCJRange (const MQuadrangle *e, double &valMin, double &valMax)
static int numNCJVal ()
static void NCJ (const SPoint3 &p0, const SPoint3 &p1, const SPoint3 &p2, const SPoint3 &p3, const SVector3 &normal, std::vector< double > &ncj)
static void NCJAndGradients (const SPoint3 &p0, const SPoint3 &p1, const SPoint3 &p2, const SPoint3 &p3, const SVector3 &normal, std::vector< double > &NCJ, std::vector< double > &dNCJ)
Detailed Description
Definition at line 49 of file qualityMeasures.h.
Member Function Documentation
angles()
double qmQuadrangle::angles (MQuadrangle * e) static
Definition at line 435 of file qualityMeasures.cpp.
Referenced by MQuadrangle::angleShapeMeasure().
eta()
double qmQuadrangle::eta (MQuadrangle * el) static
Definition at line 392 of file qualityMeasures.cpp.
Referenced by MQuadrangle::etaShapeMeasure(), and gamma().
gamma()
static double qmQuadrangle::gamma (MQuadrangle * el) inline static
Definition at line 51 of file qualityMeasures.h.
Referenced by MQuadrangle::gammaShapeMeasure().
minNCJ()
static double qmQuadrangle::minNCJ (const MQuadrangle * e) static
NCJ()
void qmQuadrangle::NCJ (const SPoint3 & p0, const SPoint3 & p1, const SPoint3 & p2, const SPoint3 & p3, const SVector3 & normal, std::vector< double > & ncj) static
Definition at line 515 of file qualityMeasures.cpp.
Referenced by NCJAndGradients(), and NCJRange().
NCJAndGradients()
void qmQuadrangle::NCJAndGradients (const SPoint3 & p0, const SPoint3 & p1, const SPoint3 & p2, const SPoint3 & p3, const SVector3 & normal, std::vector< double > & NCJ, std::vector< double > & dNCJ) static
std::vector<double> dNCJLoc = (iV == 0) ? dNCJ0 : (iV == 1) ? dNCJ1 : dNCJ2; / std::cout << "DBGTT: -> dNCJ/dp" << ig << " (local) = (" << dNCJLoc[ind2] << ", " << dNCJLoc[ind2+1] << ", " << dNCJLoc[ind2+2] < ")\n";
Definition at line 534 of file qualityMeasures.cpp.
NCJRange()
void qmQuadrangle::NCJRange (const MQuadrangle * e, double & valMin, double & valMax) static
Definition at line 493 of file qualityMeasures.cpp.
numNCJVal()
static int qmQuadrangle::numNCJVal () inline static
Definition at line 56 of file qualityMeasures.h.
The documentation for this class was generated from the following files:
src/mesh/qualityMeasures.h
src/mesh/qualityMeasures.cpp