gmsh-TingyuanDoc: MEdgeVertex Class Reference
MEdgeVertex Class Reference
#include <MVertex.h>
Public Member Functions
MEdgeVertex (double x, double y, double z, GEntity *ge, double u, std::size_t num=0, double lc=-1.0)
virtual ~MEdgeVertex ()
virtual bool getParameter (int i, double &par) const
virtual bool setParameter (int i, double par)
double getLc () const
Public Member Functions inherited from MVertex
MVertex (double x, double y, double z, GEntity *ge=nullptr, std::size_t num=0)
virtual ~MVertex ()
void deleteLast ()
virtual char getVisibility ()
virtual void setVisibility (char val)
int getPolynomialOrder ()
void setPolynomialOrder (int order)
double x () const
double y () const
double z () const
double & x ()
double & y ()
double & z ()
SPoint3 point () const
void setXYZ (double x, double y, double z)
void setXYZ (const SPoint3 &pt)
GEntity * onWhat () const
void setEntity (GEntity *ge)
std::size_t getNum () const
void forceNum (std::size_t num)
long int getIndex () const
void setIndex (long int index)
double distance (MVertex *const v)
void writeMSH (FILE *fp, bool binary=false, bool saveParametric=false, double scalingFactor=1.0)
void writeMSH2 (FILE *fp, bool binary=false, bool saveParametric=false, double scalingFactor=1.0)
void writePLY2 (FILE *fp)
void writeVRML (FILE *fp, double scalingFactor=1.0)
void writeUNV (FILE *fp, bool officialExponentFormat, double scalingFactor=1.0)
void writeVTK (FILE *fp, bool binary=false, double scalingFactor=1.0, bool bigEndian=false)
void writeMATLAB (FILE *fp, int type, bool binary, double scalingFactor=1.0)
void writeTOCHNOG (FILE *fp, int dim, double scalingFactor=1.0)
void writeMESH (FILE *fp, double scalingFactor=1.0)
void writeOFF (FILE *fp, double scalingFactor=1.0)
void writeNEU (FILE *fp, int dim, double scalingFactor=1.0)
void writeBDF (FILE *fp, int format=0, double scalingFactor=1.0)
void writeINP (FILE *fp, double scalingFactor=1.0)
void writeKEY (FILE *fp, double scalingFactor=1.0)
void writeRAD (FILE *fp, double scalingFactor=1.0)
void writeDIFF (FILE *fp, bool binary, double scalingFactor=1.0)
void writeSU2 (FILE *fp, int dim, double scalingFactor=1.0)
Public Attributes
MVertexBoundaryLayerData * bl_data
Protected Attributes
double _u
double _lc
Protected Attributes inherited from MVertex
std::size_t _num
long int _index
char _visible
char _order
double _x
double _y
double _z
GEntity * _ge
Detailed Description
Definition at line 137 of file MVertex.h.
Constructor & Destructor Documentation
MEdgeVertex()
MEdgeVertex::MEdgeVertex (double x, double y, double z, GEntity * ge, double u, std::size_t num = 0, double lc = -1.0) inline
Definition at line 144 of file MVertex.h.
~MEdgeVertex()
virtual MEdgeVertex::~MEdgeVertex () inline virtual
Definition at line 149 of file MVertex.h.
Member Function Documentation
getLc()
double MEdgeVertex::getLc () const inline
Definition at line 165 of file MVertex.h.
Referenced by remeshUnrecoveredEdges().
getParameter()
virtual bool MEdgeVertex::getParameter (int i, double & par) const inline virtual
Reimplemented from MVertex.
Definition at line 153 of file MVertex.h.
Referenced by filterPoints(), and relocateSlaveVertices().
setParameter()
virtual bool MEdgeVertex::setParameter (int i, double par) inline virtual
Reimplemented from MVertex.
Definition at line 159 of file MVertex.h.
Referenced by relocateSlaveVertices().
Member Data Documentation
_lc
double MEdgeVertex::_lc protected
Definition at line 139 of file MVertex.h.
Referenced by getLc().
_u
double MEdgeVertex::_u protected
Definition at line 139 of file MVertex.h.
Referenced by getParameter(), and setParameter().
bl_data
MVertexBoundaryLayerData* MEdgeVertex::bl_data
Definition at line 142 of file MVertex.h.
Referenced by extrudeMesh(), setBLData(), and ~MEdgeVertex().
The documentation for this class was generated from the following file:
src/geo/MVertex.h