gmsh-TingyuanDoc: FuncSpaceData Class Reference
FuncSpaceData Class Reference
#include <FuncSpaceData.h>
Public Member Functions
FuncSpaceData ()
FuncSpaceData (const FuncSpaceData &fsd, int order)
FuncSpaceData (const FuncSpaceData &fsd, int nij, int nk)
FuncSpaceData (const MElement *el)
FuncSpaceData (const MElement *el, int order, bool serendip)
FuncSpaceData (const MElement *el, bool pyr, int nij, int nk, bool serendip)
FuncSpaceData (int tag)
FuncSpaceData (int type, int order, bool serendip)
FuncSpaceData (int type, bool pyr, int nij, int nk, bool serendip)
void print () const
int getType () const
int getDimension () const
int getSpaceOrder () const
int getNij () const
int getNk () const
bool getSerendipity () const
bool getPyramidalSpace () const
void getOrderForBezier (int[3], int exponentZ=-1) const
FuncSpaceData getForNonSerendipitySpace () const
bool operator< (const FuncSpaceData &other) const
bool operator== (const FuncSpaceData &other) const
Private Attributes
int _parentType
int _spaceOrder
bool _serendipity
int _nij
int _nk
bool _pyramidalSpace
Detailed Description
Definition at line 16 of file FuncSpaceData.h.
Constructor & Destructor Documentation
FuncSpaceData() [1/9]
FuncSpaceData::FuncSpaceData () inline
Definition at line 36 of file FuncSpaceData.h.
Referenced by getForNonSerendipitySpace().
FuncSpaceData() [2/9]
FuncSpaceData::FuncSpaceData (const FuncSpaceData & fsd, int order)
Definition at line 9 of file FuncSpaceData.cpp.
FuncSpaceData() [3/9]
FuncSpaceData::FuncSpaceData (const FuncSpaceData & fsd, int nij, int nk)
Definition at line 16 of file FuncSpaceData.cpp.
FuncSpaceData() [4/9]
FuncSpaceData::FuncSpaceData (const MElement * el)
Definition at line 24 of file FuncSpaceData.cpp.
FuncSpaceData() [5/9]
FuncSpaceData::FuncSpaceData (const MElement * el, int order, bool serendip)
Definition at line 31 of file FuncSpaceData.cpp.
FuncSpaceData() [6/9]
FuncSpaceData::FuncSpaceData (const MElement * el, bool pyr, int nij, int nk, bool serendip)
Definition at line 37 of file FuncSpaceData.cpp.
FuncSpaceData() [7/9]
FuncSpaceData::FuncSpaceData (int tag)
Definition at line 46 of file FuncSpaceData.cpp.
FuncSpaceData() [8/9]
FuncSpaceData::FuncSpaceData (int type, int order, bool serendip)
Definition at line 55 of file FuncSpaceData.cpp.
FuncSpaceData() [9/9]
FuncSpaceData::FuncSpaceData (int type, bool pyr, int nij, int nk, bool serendip)
Definition at line 61 of file FuncSpaceData.cpp.
Member Function Documentation
getDimension()
int FuncSpaceData::getDimension () const inline
Definition at line 66 of file FuncSpaceData.h.
getForNonSerendipitySpace()
FuncSpaceData FuncSpaceData::getForNonSerendipitySpace () const
Definition at line 90 of file FuncSpaceData.cpp.
Referenced by BasisFactory::getBezierBasis(), BasisFactory::getGradientBasis(), and BasisFactory::getJacobianBasis().
getNij()
int FuncSpaceData::getNij () const inline
Definition at line 81 of file FuncSpaceData.h.
Referenced by bezierCoeff::_computeCoefficients(), bezierBasis::_constructPyr(), bezierBasisRaiser::_fillRaiserDataPyr(), bezierCoeff::_subdividePyramid(), bezierCoeff::getIdxCornerCoeff(), gmshGenerateMonomials(), gmshGenerateOrderedMonomials(), gmshGenerateOrderedPoints(), and gmshGeneratePoints().
getNk()
int FuncSpaceData::getNk () const inline
Definition at line 82 of file FuncSpaceData.h.
Referenced by bezierCoeff::_computeCoefficients(), bezierBasis::_constructPyr(), bezierBasisRaiser::_fillRaiserDataPyr(), bezierCoeff::_subdividePyramid(), bezierCoeff::getIdxCornerCoeff(), gmshGenerateMonomials(), gmshGenerateOrderedMonomials(), gmshGenerateOrderedPoints(), and gmshGeneratePoints().
getOrderForBezier()
void FuncSpaceData::getOrderForBezier (int order[3], int exponentZ = -1) const
Definition at line 69 of file FuncSpaceData.cpp.
getPyramidalSpace()
bool FuncSpaceData::getPyramidalSpace () const inline
Definition at line 84 of file FuncSpaceData.h.
Referenced by bezierBasis::_constructPyr(), bezierBasisRaiser::_fillRaiserDataPyr(), bezierCoeff::getIdxCornerCoeff(), gmshGenerateMonomials(), gmshGenerateOrderedMonomials(), gmshGenerateOrderedPoints(), and gmshGeneratePoints().
getSerendipity()
bool FuncSpaceData::getSerendipity () const inline
Definition at line 83 of file FuncSpaceData.h.
Referenced by bezierCoeff::bezierCoeff(), gmshGenerateMonomials(), gmshGenerateOrderedMonomials(), and gmshGeneratePoints().
getSpaceOrder()
int FuncSpaceData::getSpaceOrder () const inline
Definition at line 80 of file FuncSpaceData.h.
Referenced by bezierCoeff::_computeCoefficients(), bezierBasis::_construct(), bezierCoeff::getIdxCornerCoeff(), JacobianBasis::getJacOrder(), bezierBasis::getOrder(), GradientBasis::getPolynomialOrder(), bezierCoeff::getPolynomialOrder(), gmshGenerateMonomials(), gmshGenerateOrderedMonomials(), gmshGenerateOrderedPoints(), and gmshGeneratePoints().
getType()
int FuncSpaceData::getType () const inline
Definition at line 65 of file FuncSpaceData.h.
Referenced by bezierCoeff::_computeCoefficients(), bezierBasis::_construct(), bezierBasis::_constructPyr(), bezierBasisRaiser::_fillRaiserDataPyr(), bezierBasis::bezierBasis(), bezierCoeff::getIdxCornerCoeff(), getOrderForBezier(), bezierBasis::getType(), gmshGenerateMonomials(), gmshGenerateOrderedMonomials(), gmshGenerateOrderedPoints(), gmshGeneratePoints(), GradientBasis::GradientBasis(), JacobianBasis::JacobianBasis(), GradientBasis::mapFromIdealElement(), and bezierCoeff::subdivide().
operator<()
bool FuncSpaceData::operator< (const FuncSpaceData & other) const inline
Definition at line 92 of file FuncSpaceData.h.
operator==()
bool FuncSpaceData::operator== (const FuncSpaceData & other) const inline
Definition at line 112 of file FuncSpaceData.h.
print()
void FuncSpaceData::print () const inline
Definition at line 57 of file FuncSpaceData.h.
Member Data Documentation
_nij
int FuncSpaceData::_nij private
Definition at line 26 of file FuncSpaceData.h.
Referenced by getForNonSerendipitySpace(), getNij(), getOrderForBezier(), operator<(), operator==(), and print().
_nk
int FuncSpaceData::_nk private
Definition at line 26 of file FuncSpaceData.h.
Referenced by getForNonSerendipitySpace(), getNk(), getOrderForBezier(), operator<(), operator==(), and print().
_parentType
int FuncSpaceData::_parentType private
Definition at line 21 of file FuncSpaceData.h.
Referenced by FuncSpaceData(), getDimension(), getForNonSerendipitySpace(), getType(), operator<(), operator==(), and print().
_pyramidalSpace
bool FuncSpaceData::_pyramidalSpace private
Definition at line 27 of file FuncSpaceData.h.
Referenced by getForNonSerendipitySpace(), getOrderForBezier(), getPyramidalSpace(), operator<(), operator==(), and print().
_serendipity
bool FuncSpaceData::_serendipity private
Definition at line 22 of file FuncSpaceData.h.
Referenced by getForNonSerendipitySpace(), getSerendipity(), and print().
_spaceOrder
int FuncSpaceData::_spaceOrder private
Definition at line 21 of file FuncSpaceData.h.
Referenced by getForNonSerendipitySpace(), getOrderForBezier(), getSpaceOrder(), operator<(), operator==(), and print().
The documentation for this class was generated from the following files:
src/numeric/FuncSpaceData.h
src/numeric/FuncSpaceData.cpp