gmsh-TingyuanDoc: partitionRegion Class Reference
partitionRegion Class Reference
#include <partitionRegion.h>
Public Member Functions
partitionRegion (GModel *model, int num, const std::vector< int > &partitions)
partitionRegion (GModel *model, int num)
partitionRegion (GModel *model, const std::vector< int > &partitions)
virtual ~partitionRegion ()
virtual GeomType geomType () const
virtual void setParentEntity (GEntity *r)
virtual GEntity * getParentEntity ()
virtual void setPartitions (std::vector< int > &partitions)
virtual const std::vector< int > & getPartitions () const
virtual int getPartition (std::size_t index) const
virtual std::size_t numPartitions () const
Public Member Functions inherited from discreteRegion
discreteRegion (GModel *model, int num)
discreteRegion (GModel *model)
virtual ~discreteRegion ()
virtual bool haveParametrization ()
int createGeometry ()
Public Member Functions inherited from GRegion
GRegion (GModel *model, int tag)
virtual ~GRegion ()
virtual void deleteMesh ()
virtual int dim () const
virtual void setVisibility (char val, bool recursive=false)
virtual void setColor (unsigned int val, bool recursive=false)
void addEmbeddedVertex (GVertex *v)
void addEmbeddedEdge (GEdge *e)
void addEmbeddedFace (GFace *f)
int delFace (GFace *face)
virtual std::vector< GFace * > faces () const
virtual std::vector< int > faceOrientations () const
void set (std::vector< GFace * > const &f)
void setOrientations (const std::vector< int > &f)
void setFace (GFace *const f, int const orientation)
void setBoundFaces (const std::set< int > &tagFaces)
void setBoundFaces (const std::vector< int > &tagFaces, const std::vector< int > &signFaces)
std::vector< GVertex * > & embeddedVertices ()
std::vector< GEdge * > & embeddedEdges ()
std::vector< GFace * > & embeddedFaces ()
std::vector< MVertex * > getEmbeddedMeshVertices () const
virtual std::vector< GEdge * > const & edges () const
virtual std::vector< GVertex * > vertices () const
virtual SBoundingBox3d bounds (bool fast=false)
virtual SOrientedBoundingBox getOBB ()
bool edgeConnected (GRegion *r) const
double computeSolidProperties (std::vector< double > cg, std::vector< double > inertia)
virtual std::string getAdditionalInfoString (bool multline=false)
virtual void writeGEO (FILE *fp)
virtual void writePY (FILE *fp)
virtual void getElementTypes (std::vector< int > &types) const
std::size_t getNumMeshElements () const
std::size_t getNumMeshElementsByType (const int familyType) const
std::size_t getNumMeshParentElements ()
void getNumMeshElements (unsigned *const c) const
MElement *const * getStartElementType (int type) const
MElement * getMeshElement (std::size_t index) const
MElement * getMeshElementByType (const int familyType, const std::size_t index) const
virtual void resetMeshAttributes ()
virtual double getMeshSize () const
void addTetrahedron (MTetrahedron *t)
void addHexahedron (MHexahedron *h)
void addPrism (MPrism *p)
void addPyramid (MPyramid *p)
void addPolyhedron (MPolyhedron *p)
void addTrihedron (MTrihedron *t)
void addElement (int type, MElement *e)
void removeElement (int type, MElement *e)
void removeElements (int type)
BoundaryLayerColumns * getColumns ()
virtual bool reorder (const int elementType, const std::vector< std::size_t > &ordering)
bool setOutwardOrientationMeshConstraint ()
virtual bool isFullyDiscrete ()
Public Member Functions inherited from GEntity
void addVerticesInSet (std::set< MVertex * > &, bool closure) const
virtual std::string getTypeString ()
GEntity (GModel *m, int t)
virtual ~GEntity ()
virtual void mesh (bool verbose)
void deleteVertexArrays ()
virtual std::list< GRegion * > regions () const
virtual bool isOrphan ()
std::vector< GRegion * > bindingsGetRegions ()
std::vector< GFace * > bindingsGetFaces ()
std::vector< GEdge * > bindingsGetEdges () const
std::vector< GVertex * > bindingsGetVertices ()
virtual bool continuous (int dim) const
virtual bool periodic (int dim) const
virtual double period (int dim) const
virtual bool degenerate (int dim) const
virtual Range< double > parBounds (int i) const
virtual double tolerance () const
virtual bool containsPoint (const SPoint3 &pt) const
virtual ModelType getNativeType () const
virtual void * getNativePtr () const
virtual int getNativeInt () const
GModel * model () const
int tag () const
void setTag (int tag)
virtual void addPhysicalEntity (int physicalTag)
virtual std::vector< int > getPhysicalEntities ()
GEntity * getMeshMaster () const
void setMeshMaster (GEntity *)
void setMeshMaster (GEntity *, const std::vector< double > &, bool updateCorrespondingVertices=true)
void updateCorrespondingVertices ()
void copyMasterCoordinates ()
virtual void alignElementsWithMaster ()
virtual char getVisibility ()
virtual char getSelection ()
virtual void setSelection (char val)
virtual unsigned int getColor ()
virtual void setColor (unsigned color, bool recursive=false)
virtual bool useColor ()
virtual std::string getInfoString (bool additional=true, bool multiline=false)
virtual double getMeshSizeFactor () const
bool getAllElementsVisible ()
void setAllElementsVisible (bool val)
std::size_t getNumMeshVertices ()
MVertex * getMeshVertex (std::size_t index)
void addMeshVertex (MVertex *v)
void removeMeshVertex (MVertex *v)
virtual void relocateMeshVertices ()
GVertex * cast2Vertex ()
GEdge * cast2Edge ()
GFace * cast2Face ()
GRegion * cast2Region ()
Private Attributes
std::vector< int > _partitions
GEntity * _parentEntity
Additional Inherited Members
Public Types inherited from GEntity
enum ModelType {
UnknownModel, GmshModel, OpenCascadeModel, AcisModel,
ParasolidModel
}
enum GeomType {
Unknown, Point, BoundaryLayerPoint, Line,
Circle, Ellipse, Conic, Parabola,
Hyperbola, TrimmedCurve, OffsetCurve, BSpline,
Bezier, ParametricCurve, BoundaryLayerCurve, DiscreteCurve,
Plane, Nurb, Cylinder, Sphere,
Cone, Torus, RuledSurface, ParametricSurface,
BSplineSurface, BezierSurface, SurfaceOfRevolution, BoundaryLayerSurface,
DiscreteSurface, DiscreteDiskSurface, Volume, DiscreteVolume,
PartitionPoint, PartitionCurve, PartitionSurface, PartitionVolume,
GhostCurve, GhostSurface, GhostVolume
}
enum MeshGenerationStatus { PENDING, DONE, FAILED }
Public Attributes inherited from GRegion
struct {
int recombine3D
char method
ExtrudeParams * extrude
std::vector< GVertex * > corners
int QuadTri
double meshSize
} meshAttributes
std::vector< std::vector< std::vector< MVertex * > > > transfinite_vertices
std::vector< MTetrahedron * > tetrahedra
std::vector< MHexahedron * > hexahedra
std::vector< MPrism * > prisms
std::vector< MPyramid * > pyramids
std::vector< MTrihedron * > trihedra
std::vector< MPolyhedron * > polyhedra
Public Attributes inherited from GEntity
std::vector< MVertex * > mesh_vertices
std::vector< GEntity * > compound
std::map< GVertex *, GVertex * > vertexCounterparts
std::vector< int > physicals
VertexArray * va_lines
VertexArray * va_triangles
std::set< MElement * > curvedBLElements
std::vector< double > affineTransform
std::map< MVertex *, MVertex * > correspondingVertices
std::map< MVertex *, MVertex * > correspondingHighOrderVertices
Protected Attributes inherited from GRegion
std::vector< GFace * > l_faces
std::vector< GVertex * > embedded_vertices
std::vector< GFace * > embedded_faces
std::vector< GEdge * > embedded_edges
std::vector< int > l_dirs
BoundaryLayerColumns _columns
Protected Attributes inherited from GEntity
SOrientedBoundingBox * _obb
Detailed Description
Definition at line 12 of file partitionRegion.h.
Constructor & Destructor Documentation
partitionRegion() [1/3]
partitionRegion::partitionRegion (GModel * model, int num, const std::vector< int > & partitions) inline
Definition at line 18 of file partitionRegion.h.
partitionRegion() [2/3]
partitionRegion::partitionRegion (GModel * model, int num) inline
Definition at line 23 of file partitionRegion.h.
partitionRegion() [3/3]
partitionRegion::partitionRegion (GModel * model, const std::vector< int > & partitions) inline
Definition at line 27 of file partitionRegion.h.
~partitionRegion()
virtual partitionRegion::~partitionRegion () inline virtual
Definition at line 31 of file partitionRegion.h.
Member Function Documentation
geomType()
virtual GeomType partitionRegion::geomType () const inline virtual
Reimplemented from discreteRegion.
Definition at line 32 of file partitionRegion.h.
getParentEntity()
virtual GEntity* partitionRegion::getParentEntity () inline virtual
Reimplemented from GRegion.
Definition at line 34 of file partitionRegion.h.
Referenced by writeMSH4Entities().
getPartition()
virtual int partitionRegion::getPartition (std::size_t index) const inline virtual
Definition at line 40 of file partitionRegion.h.
Referenced by GModel::_readMSH4(), and Less_partitionRegion::operator()().
getPartitions()
virtual const std::vector<int>& partitionRegion::getPartitions () const inline virtual
Definition at line 39 of file partitionRegion.h.
Referenced by getEntitiesToSave(), and writeMSH4Entities().
numPartitions()
virtual std::size_t partitionRegion::numPartitions () const inline virtual
Definition at line 44 of file partitionRegion.h.
Referenced by GModel::_readMSH4(), and Less_partitionRegion::operator()().
setParentEntity()
virtual void partitionRegion::setParentEntity (GEntity * r) inline virtual
Definition at line 33 of file partitionRegion.h.
setPartitions()
virtual void partitionRegion::setPartitions (std::vector< int > & partitions) inline virtual
Definition at line 35 of file partitionRegion.h.
Member Data Documentation
_parentEntity
GEntity* partitionRegion::_parentEntity private
Definition at line 15 of file partitionRegion.h.
Referenced by getParentEntity(), and setParentEntity().
_partitions
std::vector<int> partitionRegion::_partitions private
Definition at line 14 of file partitionRegion.h.
Referenced by getPartition(), getPartitions(), numPartitions(), and setPartitions().
The documentation for this class was generated from the following file:
src/geo/partitionRegion.h