gmsh-TingyuanDoc: MathEvalExpression Class Reference
MathEvalExpression Class Reference
Public Member Functions
MathEvalExpression ()
~MathEvalExpression ()
bool set_function (const std::string &f)
double evaluate (double x, double y, double z)
Private Attributes
mathEvaluator * _f
std::set< int > _fields
Detailed Description
Definition at line 975 of file Field.cpp.
Constructor & Destructor Documentation
MathEvalExpression()
MathEvalExpression::MathEvalExpression () inline
Definition at line 981 of file Field.cpp.
~MathEvalExpression()
MathEvalExpression::~MathEvalExpression () inline
Definition at line 982 of file Field.cpp.
Member Function Documentation
evaluate()
double MathEvalExpression::evaluate (double x, double y, double z) inline
Definition at line 1026 of file Field.cpp.
Referenced by MathEvalField::operator()(), and ParametricField::operator()().
set_function()
bool MathEvalExpression::set_function (const std::string & f) inline
Definition at line 986 of file Field.cpp.
Referenced by MathEvalField::operator()().
Member Data Documentation
_f
mathEvaluator* MathEvalExpression::_f private
Definition at line 977 of file Field.cpp.
Referenced by evaluate(), set_function(), and ~MathEvalExpression().
_fields
std::set<int> MathEvalExpression::_fields private
Definition at line 978 of file Field.cpp.
Referenced by evaluate(), and set_function().
The documentation for this class was generated from the following file:
src/mesh/Field.cpp