gmsh-TingyuanDoc: element Class Reference
element Class Reference abstract
#include <shapeFunctions.h>
Public Member Functions
element (double *x, double *y, double *z, int numNodes=0)
virtual ~element ()
virtual void getXYZ (int num, double &x, double &y, double &z)
double getTolerance () const
virtual int getDimension ()=0
virtual int getNumNodes ()=0
virtual void getNode (int num, double &u, double &v, double &w)=0
virtual int getNumEdges ()=0
virtual void getEdge (int num, int &start, int &end)=0
virtual int getNumGaussPoints ()=0
virtual void getGaussPoint (int num, double &u, double &v, double &w, double &weight)=0
virtual void getShapeFunction (int num, double u, double v, double w, double &s)=0
virtual void getGradShapeFunction (int num, double u, double v, double w, double s[3])=0
double getJacobian (double u, double v, double w, double jac[3][3])
double interpolate (double val[], double u, double v, double w, int stride=1)
void interpolateGrad (double val[], double u, double v, double w, double f[3], int stride=1, double invjac[3][3]=nullptr)
void interpolateCurl (double val[], double u, double v, double w, double f[3], int stride=3)
double interpolateDiv (double val[], double u, double v, double w, int stride=3)
double integrate (double val[], int stride=1)
double integrateLevelsetPositive (double val[])
virtual double integrateCirculation (double val[])
virtual double integrateFlux (double val[])
virtual void xyz2uvw (double xyz[3], double uvw[3])
virtual int isInside (double u, double v, double w)=0
double maxEdgeLength ()
Protected Attributes
bool _ownData
double * _x
double * _y
double * _z
Detailed Description
Definition at line 12 of file shapeFunctions.h.
Constructor & Destructor Documentation
element()
element::element (double * x, double * y, double * z, int numNodes = 0) inline
Definition at line 18 of file shapeFunctions.h.
~element()
virtual element::~element () inline virtual
Definition at line 38 of file shapeFunctions.h.
Member Function Documentation
getDimension()
virtual int element::getDimension () pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
Referenced by getJacobian().
getEdge()
virtual void element::getEdge (int num, int & start, int & end) pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
Referenced by maxEdgeLength().
getGaussPoint()
virtual void element::getGaussPoint (int num, double & u, double & v, double & w, double & weight) pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
Referenced by integrate().
getGradShapeFunction()
virtual void element::getGradShapeFunction (int num, double u, double v, double w, double s[3]) pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
Referenced by getJacobian(), and interpolateGrad().
getJacobian()
double element::getJacobian (double u, double v, double w, double jac[3][3]) inline
Definition at line 66 of file shapeFunctions.h.
Referenced by integrate(), interpolateCurl(), interpolateDiv(), interpolateGrad(), and xyz2uvw().
getNode()
virtual void element::getNode (int num, double & u, double & v, double & w) pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
Referenced by GMSH_CurlPlugin::execute(), GMSH_GradientPlugin::execute(), and GMSH_DivergencePlugin::execute().
getNumEdges()
virtual int element::getNumEdges () pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
Referenced by GMSH_CurvedBndDistPlugin::execute(), and maxEdgeLength().
getNumGaussPoints()
virtual int element::getNumGaussPoints () pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
Referenced by integrate().
getNumNodes()
virtual int element::getNumNodes () pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
Referenced by GMSH_NearToFarFieldPlugin::getFarFieldJin(), GMSH_NearToFarFieldPlugin::getFarFieldMonk(), getJacobian(), getXYZ(), integrateLevelsetPositive(), interpolate(), interpolateGrad(), and xyz2uvw().
getShapeFunction()
virtual void element::getShapeFunction (int num, double u, double v, double w, double & s) pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
Referenced by interpolate(), and xyz2uvw().
getTolerance()
double element::getTolerance () const
Definition at line 9 of file shapeFunctions.cpp.
Referenced by point::isInside(), line::isInside(), triangle::isInside(), quadrangle::isInside(), tetrahedron::isInside(), hexahedron::isInside(), prism::isInside(), and pyramid::isInside().
getXYZ()
virtual void element::getXYZ (int num, double & x, double & y, double & z) inline virtual
Definition at line 46 of file shapeFunctions.h.
Referenced by GMSH_NearToFarFieldPlugin::getFarFieldJin(), and GMSH_NearToFarFieldPlugin::getFarFieldMonk().
integrate()
double element::integrate (double val[], int stride = 1) inline
Definition at line 212 of file shapeFunctions.h.
Referenced by GMSH_IntegratePlugin::execute(), GMSH_NearToFarFieldPlugin::getFarFieldJin(), GMSH_NearToFarFieldPlugin::getFarFieldMonk(), line::integrateCirculation(), triangle::integrateFlux(), quadrangle::integrateFlux(), and integrateLevelsetPositive().
integrateCirculation()
virtual double element::integrateCirculation (double val[]) inline virtual
Reimplemented in line.
Definition at line 238 of file shapeFunctions.h.
Referenced by GMSH_IntegratePlugin::execute().
integrateFlux()
virtual double element::integrateFlux (double val[]) inline virtual
Reimplemented in quadrangle, and triangle.
Definition at line 243 of file shapeFunctions.h.
Referenced by GMSH_IntegratePlugin::execute().
integrateLevelsetPositive()
double element::integrateLevelsetPositive (double val[]) inline
Definition at line 224 of file shapeFunctions.h.
interpolate()
double element::interpolate (double val[], double u, double v, double w, int stride = 1) inline
Definition at line 155 of file shapeFunctions.h.
Referenced by OctreePost::_getValue(), approximationError(), and integrate().
interpolateCurl()
void element::interpolateCurl (double val[], double u, double v, double w, double f[3], int stride = 3) inline
Definition at line 188 of file shapeFunctions.h.
Referenced by GMSH_CurlPlugin::execute().
interpolateDiv()
double element::interpolateDiv (double val[], double u, double v, double w, int stride = 3) inline
Definition at line 201 of file shapeFunctions.h.
Referenced by GMSH_DivergencePlugin::execute().
interpolateGrad()
void element::interpolateGrad (double val[], double u, double v, double w, double f[3], int stride = 1, double invjac[3][3] = nullptr) inline
Definition at line 167 of file shapeFunctions.h.
Referenced by OctreePost::_getValue(), GMSH_GradientPlugin::execute(), interpolateCurl(), and interpolateDiv().
isInside()
virtual int element::isInside (double u, double v, double w) pure virtual
Implemented in pyramid, prism, hexahedron, tetrahedron, quadrangle, triangle, line, and point.
maxEdgeLength()
double element::maxEdgeLength () inline
Definition at line 290 of file shapeFunctions.h.
Referenced by OctreePost::_getValue().
xyz2uvw()
virtual void element::xyz2uvw (double xyz[3], double uvw[3]) inline virtual
Reimplemented in tetrahedron, triangle, and point.
Definition at line 248 of file shapeFunctions.h.
Referenced by OctreePost::_getValue(), hexInEle(), linInEle(), priInEle(), pyrInEle(), and quaInEle().
Member Data Documentation
_ownData
bool element::_ownData protected
Definition at line 14 of file shapeFunctions.h.
Referenced by element(), and ~element().
_x
double* element::_x protected
Definition at line 15 of file shapeFunctions.h.
Referenced by element(), getJacobian(), getXYZ(), line::integrateCirculation(), triangle::integrateFlux(), quadrangle::integrateFlux(), maxEdgeLength(), xyz2uvw(), triangle::xyz2uvw(), tetrahedron::xyz2uvw(), and ~element().
_y
double * element::_y protected
Definition at line 15 of file shapeFunctions.h.
Referenced by element(), getJacobian(), getXYZ(), line::integrateCirculation(), triangle::integrateFlux(), quadrangle::integrateFlux(), maxEdgeLength(), xyz2uvw(), triangle::xyz2uvw(), tetrahedron::xyz2uvw(), and ~element().
_z
double * element::_z protected
Definition at line 15 of file shapeFunctions.h.
Referenced by element(), getJacobian(), getXYZ(), line::integrateCirculation(), triangle::integrateFlux(), quadrangle::integrateFlux(), maxEdgeLength(), xyz2uvw(), triangle::xyz2uvw(), tetrahedron::xyz2uvw(), and ~element().
The documentation for this class was generated from the following files:
src/post/shapeFunctions.h
src/post/shapeFunctions.cpp