gmsh-TingyuanDoc: MLine Class Reference
MLine Class Reference
#include <MLine.h>
Public Member Functions
MLine (MVertex *v0, MVertex *v1, int num=0, int part=0)
MLine (const std::vector< MVertex * > &v, int num=0, int part=0)
~MLine ()
virtual int getDim () const
virtual std::size_t getNumVertices () const
virtual MVertex * getVertex (int num)
virtual const MVertex * getVertex (int num) const
virtual void setVertex (int num, MVertex *v)
virtual double getInnerRadius ()
virtual double getLength ()
virtual double getVolume ()
virtual void getVertexInfo (const MVertex *vertex, int &ithVertex) const
virtual int getNumEdges () const
virtual MEdge getEdge (int num) const
virtual int getNumEdgesRep (bool curved)
virtual void getEdgeRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getEdgeVertices (const int num, std::vector< MVertex * > &v) const
virtual int getNumFaces ()
virtual MFace getFace (int num) const
virtual int getNumFacesRep (bool curved)
virtual void getFaceRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual int getType () const
virtual int getTypeForMSH () const
virtual int getTypeForUNV () const
virtual int getTypeForVTK () const
virtual const char * getStringForPOS () const
virtual const char * getStringForBDF () const
virtual const char * getStringForINP () const
virtual const char * getStringForKEY () const
virtual const char * getStringForRAD () const
virtual const char * getStringForTOCHNOG () const
virtual void reverse ()
virtual bool isInside (double u, double v, double w) const
virtual void getNode (int num, double &u, double &v, double &w) const
virtual SPoint3 barycenterUVW () const
virtual void getIntegrationPoints (int pOrder, int *npts, IntPt **pts)
virtual void discretize (double tol, std::vector< SPoint3 > &dpts, std::vector< double > &ts)
virtual int numCommonNodesInDualGraph (const MElement *const other) const
Public Member Functions inherited from MElement
MElement (std::size_t num=0, int part=0)
virtual ~MElement ()
double getTolerance () const
virtual std::size_t getNum () const
void forceNum (std::size_t num)
virtual int getPolynomialOrder () const
virtual bool getIsAssimilatedSerendipity () const
virtual bool getIsOnlySerendipity () const
virtual int getPartition () const
virtual void setPartition (int num)
virtual char getVisibility () const
virtual void setVisibility (char val)
void getVertices (std::vector< MVertex * > &verts)
virtual MVertex * getVertexUNV (int num)
virtual MVertex * getVertexVTK (int num)
virtual MVertex * getVertexMATLAB (int num)
virtual MVertex * getVertexTOCHNOG (int num)
virtual MVertex * getVertexBDF (int num)
virtual MVertex * getVertexDIFF (int num)
virtual MVertex * getVertexINP (int num)
virtual MVertex * getVertexKEY (int num)
virtual MVertex * getVertexRAD (int num)
virtual MVertex * getVertexNEU (int num)
virtual int getNumEdgeVertices () const
virtual int getNumFaceVertices () const
virtual int getNumVolumeVertices () const
std::size_t getNumPrimaryVertices () const
virtual MEdgeN getHighOrderEdge (int num, int sign)
MEdgeN getHighOrderEdge (const MEdge &edge)
virtual bool getEdgeInfo (const MEdge &edge, int &ithEdge, int &sign) const
virtual int numEdge2numVertex (int numEdge, int numVert) const
virtual MEdge getEdgeSolin (int numEdge)
virtual MFaceN getHighOrderFace (int num, int sign, int rot)
MFaceN getHighOrderFace (const MFace &face)
virtual bool getFaceInfo (const MFace &face, int &ithFace, int &sign, int &rot) const
virtual MFace getFaceSolin (int numFace)
virtual void getFaceVertices (const int num, std::vector< MVertex * > &v) const
virtual MElement * getParent () const
virtual void setParent (MElement *p, bool owner=false)
virtual void updateParent (GModel *gm)
virtual int getNumChildren () const
virtual MElement * getChild (int i) const
virtual bool ownsParent () const
virtual const MElement * getBaseElement () const
virtual MElement * getBaseElement ()
virtual MElement * getDomain (int i) const
virtual void setDomain (MElement *e, int i)
virtual double maxEdge ()
virtual double minEdge ()
double maxDistToStraight () const
double skewness ()
virtual double gammaShapeMeasure ()
virtual double etaShapeMeasure ()
double minSICNShapeMeasure ()
double minSIGEShapeMeasure ()
double distoShapeMeasure ()
double minIsotropyMeasure (bool knownValid=false, bool reversedOk=false)
double minScaledJacobian (bool knownValid=false, bool reversedOk=false)
virtual double angleShapeMeasure ()
virtual void scaledJacRange (double &jmin, double &jmax, GEntity *ge=nullptr) const
virtual void idealJacRange (double &jmin, double &jmax, GEntity *ge=nullptr)
virtual void signedInvCondNumRange (double &iCNMin, double &iCNMax, GEntity *ge=nullptr)
virtual void signedInvGradErrorRange (double &minSIGE, double &maxSIGE)
virtual double getOuterRadius ()
virtual SPoint3 barycenter (bool primary=false) const
virtual SPoint3 fastBarycenter (bool primary=false) const
virtual SPoint3 barycenter_infty () const
virtual int getVolumeSign ()
virtual bool setVolumePositive ()
int getValidity ()
virtual std::string getInfoString (bool multline)
virtual const nodalBasis * getFunctionSpace (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getFuncSpaceData (int order=-1, bool serendip=false) const
virtual const JacobianBasis * getJacobianFuncSpace (int orderElement=-1) const
virtual const FuncSpaceData getJacobianFuncSpaceData (int orderElement=-1) const
virtual void getShapeFunctions (double u, double v, double w, double s[], int order=-1) const
virtual void getGradShapeFunctions (double u, double v, double w, double s[][3], int order=-1) const
virtual void getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order=-1) const
virtual void getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order=-1) const
virtual double getJacobian (const fullMatrix< double > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double *jac) const
virtual double getJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobian (double u, double v, double w, fullMatrix< double > &j) const
virtual double getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobianDeterminant (double u, double v, double w) const
void getSignedJacobian (fullVector< double > &jacobian, int o=-1) const
void getNodesCoord (fullMatrix< double > &nodesXYZ) const
void getNodesCoordNonSerendip (fullMatrix< double > &nodesXYZ) const
bezierCoeff * getBezierVerticesCoord () const
virtual std::size_t getNumShapeFunctions () const
virtual std::size_t getNumPrimaryShapeFunctions () const
virtual const MVertex * getShapeFunctionNode (int i) const
virtual MVertex * getShapeFunctionNode (int i)
virtual double getEigenvaluesMetric (double u, double v, double w, double values[3]) const
virtual void pnt (double u, double v, double w, SPoint3 &p) const
virtual void pnt (double u, double v, double w, double *p) const
virtual void pnt (const std::vector< double > &sf, SPoint3 &p) const
virtual void primaryPnt (double u, double v, double w, SPoint3 &p)
virtual void xyz2uvw (double xyz[3], double uvw[3]) const
virtual void movePointFromParentSpaceToElementSpace (double &u, double &v, double &w) const
virtual void movePointFromElementSpaceToParentSpace (double &u, double &v, double &w) const
double interpolate (double val[], double u, double v, double w, int stride=1, int order=-1)
void interpolateGrad (double val[], double u, double v, double w, double f[], int stride=1, double invjac[3][3]=nullptr, int order=-1)
void interpolateCurl (double val[], double u, double v, double w, double f[], int stride=3, int order=-1)
double interpolateDiv (double val[], double u, double v, double w, int stride=3, int order=-1)
double integrate (double val[], int pOrder, int stride=1, int order=-1)
double integrateCirc (double val[], int edge, int pOrder, int order=-1)
double integrateFlux (double val[], int face, int pOrder, int order=-1)
virtual void writeMSH2 (FILE *fp, double version=1.0, bool binary=false, int num=0, int elementary=1, int physical=1, int parentNum=0, int dom1Num=0, int dom2Num=0, std::vector< short > *ghosts=nullptr)
virtual void writeMSH3 (FILE *fp, bool binary=false, int elementary=1, std::vector< short > *ghosts=nullptr)
virtual void writePOS (FILE *fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor=1.0, int elementary=1)
virtual void writeSTL (FILE *fp, bool binary=false, double scalingFactor=1.0)
virtual void writeX3D (FILE *fp, double scalingFactor=1.0)
virtual void writeVRML (FILE *fp)
virtual void writePLY2 (FILE *fp)
virtual void writeUNV (FILE *fp, int num=0, int elementary=1, int physical=1)
virtual void writeVTK (FILE *fp, bool binary=false, bool bigEndian=false)
virtual void writeMATLAB (FILE *fp, int filetype, int elementary=0, int physical=0, bool binary=false)
virtual void writeTOCHNOG (FILE *fp, int num)
virtual void writeMESH (FILE *fp, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeNEU (FILE *fp, unsigned gambitType, int adjust, int phys=0)
virtual void writeIR3 (FILE *fp, int elementTagType, int num, int elementary, int physical)
virtual void writeBDF (FILE *fp, int format=0, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeDIFF (FILE *fp, int num, bool binary=false, int physical_property=1)
virtual void writeINP (FILE *fp, int num)
virtual void writeKEY (FILE *fp, int pid, int num)
virtual void writeRAD (FILE *fp, int num)
virtual void writeSU2 (FILE *fp, int num)
virtual const char * getStringForDIFF () const
std::string getName ()
virtual std::size_t getNumVerticesForMSH ()
virtual void getVerticesIdForMSH (std::vector< int > &verts)
virtual MElement * copy (std::map< int, MVertex * > &vertexMap, std::map< MElement *, MElement * > &newParents, std::map< MElement *, MElement * > &newDomains)
Protected Member Functions
void _getEdgeVertices (std::vector< MVertex * > &v) const
Protected Member Functions inherited from MElement
void _getEdgeRep (MVertex *v0, MVertex *v1, double *x, double *y, double *z, SVector3 *n, int faceIndex=-1)
void _getFaceRep (MVertex *v0, MVertex *v1, MVertex *v2, double *x, double *y, double *z, SVector3 *n)
Protected Attributes
MVertex * _v [2]
Additional Inherited Members
Static Public Member Functions inherited from MElement
static unsigned int getInfoMSH (const int typeMSH, const char **const name=nullptr)
Static Protected Member Functions inherited from MElement
static bool _getFaceInfo (const MFace &face, const MFace &other, int &sign, int &rot)
Static Protected Attributes inherited from MElement
static double _isInsideTolerance
Detailed Description
Definition at line 21 of file MLine.h.
Constructor & Destructor Documentation
MLine() [1/2]
MLine::MLine (MVertex * v0, MVertex * v1, int num = 0, int part = 0) inline
Definition at line 31 of file MLine.h.
Referenced by MSubLine::getBaseElement().
MLine() [2/2]
MLine::MLine (const std::vector< MVertex * > & v, int num = 0, int part = 0) inline
Definition at line 37 of file MLine.h.
~MLine()
MLine::~MLine () inline
Definition at line 42 of file MLine.h.
Member Function Documentation
_getEdgeVertices()
void MLine::_getEdgeVertices (std::vector< MVertex * > & v) const inline protected
Definition at line 24 of file MLine.h.
Referenced by getEdgeVertices(), MLine3::getEdgeVertices(), and MLineN::getEdgeVertices().
barycenterUVW()
virtual SPoint3 MLine::barycenterUVW () const inline virtual
Reimplemented from MElement.
Definition at line 107 of file MLine.h.
discretize()
void MLine::discretize (double tol, std::vector< SPoint3 > & dpts, std::vector< double > & ts) virtual
Reimplemented in MLineN, and MLine3.
Definition at line 77 of file MLine.cpp.
getDim()
virtual int MLine::getDim () const inline virtual
Implements MElement.
Definition at line 43 of file MLine.h.
Referenced by MSubLine::getGradShapeFunctions(), and MSubLine::isInside().
getEdge()
virtual MEdge MLine::getEdge (int num) const inline virtual
Implements MElement.
Definition at line 56 of file MLine.h.
Referenced by MLinePtrLessThan::operator()(), and MLinePtrEqual::operator()().
getEdgeRep()
virtual void MLine::getEdgeRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) inline virtual
Implements MElement.
Reimplemented in MLineN, and MLine3.
Definition at line 58 of file MLine.h.
Referenced by MLine3::getEdgeRep(), and MLineN::getEdgeRep().
getEdgeVertices()
virtual void MLine::getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MElement.
Reimplemented in MLineN, and MLine3.
Definition at line 63 of file MLine.h.
getFace()
virtual MFace MLine::getFace (int num) const inline virtual
Implements MElement.
Definition at line 69 of file MLine.h.
getFaceRep()
virtual void MLine::getFaceRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) inline virtual
Implements MElement.
Definition at line 71 of file MLine.h.
getInnerRadius()
double MLine::getInnerRadius () virtual
Reimplemented from MElement.
Definition at line 21 of file MLine.cpp.
getIntegrationPoints()
void MLine::getIntegrationPoints (int pOrder, int * npts, IntPt ** pts) virtual
Reimplemented from MElement.
Reimplemented in MLineBorder, MLineChild, and MSubLine.
Definition at line 15 of file MLine.cpp.
Referenced by MLineChild::getIntegrationPoints(), and MLineBorder::getIntegrationPoints().
getLength()
double MLine::getLength () virtual
Definition at line 23 of file MLine.cpp.
Referenced by getVolume().
getNode()
virtual void MLine::getNode (int num, double & u, double & v, double & w) const inline virtual
Reimplemented from MElement.
Reimplemented in MLineN, and MLine3.
Definition at line 98 of file MLine.h.
Referenced by MLine3::getNode(), and MLineN::getNode().
getNumEdges()
virtual int MLine::getNumEdges () const inline virtual
Implements MElement.
Definition at line 55 of file MLine.h.
getNumEdgesRep()
virtual int MLine::getNumEdgesRep (bool curved) inline virtual
Implements MElement.
Reimplemented in MLineN, and MLine3.
Definition at line 57 of file MLine.h.
getNumFaces()
virtual int MLine::getNumFaces () inline virtual
Implements MElement.
Definition at line 68 of file MLine.h.
getNumFacesRep()
virtual int MLine::getNumFacesRep (bool curved) inline virtual
Implements MElement.
Definition at line 70 of file MLine.h.
getNumVertices()
virtual std::size_t MLine::getNumVertices () const inline virtual
Implements MElement.
Reimplemented in MLineN, and MLine3.
Definition at line 44 of file MLine.h.
Referenced by FixPeriodicMesh(), and Subdivide().
getStringForBDF()
virtual const char* MLine::getStringForBDF () const inline virtual
Reimplemented from MElement.
Definition at line 80 of file MLine.h.
getStringForINP()
virtual const char* MLine::getStringForINP () const inline virtual
Reimplemented from MElement.
Reimplemented in MLine3.
Definition at line 81 of file MLine.h.
getStringForKEY()
virtual const char* MLine::getStringForKEY () const inline virtual
Reimplemented from MElement.
Reimplemented in MLine3.
Definition at line 82 of file MLine.h.
getStringForPOS()
virtual const char* MLine::getStringForPOS () const inline virtual
Reimplemented from MElement.
Reimplemented in MLine3.
Definition at line 79 of file MLine.h.
getStringForRAD()
virtual const char* MLine::getStringForRAD () const inline virtual
Reimplemented from MElement.
Reimplemented in MLine3.
Definition at line 83 of file MLine.h.
getStringForTOCHNOG()
virtual const char* MLine::getStringForTOCHNOG () const inline virtual
Reimplemented from MElement.
Reimplemented in MLine3.
Definition at line 84 of file MLine.h.
getType()
virtual int MLine::getType () const inline virtual
Implements MElement.
Definition at line 75 of file MLine.h.
Referenced by GMSH_CrackPlugin::execute().
getTypeForMSH()
virtual int MLine::getTypeForMSH () const inline virtual
Reimplemented from MElement.
Reimplemented in MLineBorder, MLineChild, MSubLine, MLineN, and MLine3.
Definition at line 76 of file MLine.h.
getTypeForUNV()
virtual int MLine::getTypeForUNV () const inline virtual
Reimplemented from MElement.
Reimplemented in MLine3.
Definition at line 77 of file MLine.h.
getTypeForVTK()
virtual int MLine::getTypeForVTK () const inline virtual
Reimplemented from MElement.
Reimplemented in MLine3.
Definition at line 78 of file MLine.h.
getVertex() [1/2]
virtual MVertex* MLine::getVertex (int num) inline virtual
Implements MElement.
Reimplemented in MLineN, and MLine3.
Definition at line 45 of file MLine.h.
Referenced by GModel::alignPeriodicBoundaries(), blyr_manager::classify_ridges(), classifyFaces(), frameSolver2d::computeStiffnessMatrix(), createTopologyFromMesh1D(), discretize(), ensureSimplyConnectedEdge(), blyr_manager::extrude_one_external(), blyr_manager::extrude_ridges(), blyr_manager::extrude_ridges_on_faces(), blyr_manager::extrude_vertices_on_edges(), findInEdgeSearchStructure(), FixPeriodicMesh(), getGEdge(), MLineChild::getIntegrationPoints(), gmshBeam2d::gmshBeam2d(), MLineChild::isInside(), MLineBorder::isInside(), gmshBeam2d::isRigid(), setHighOrder(), gmshBeam2d::setRotationTag(), and Subdivide().
getVertex() [2/2]
virtual const MVertex* MLine::getVertex (int num) const inline virtual
Implements MElement.
Reimplemented in MLineN, and MLine3.
Definition at line 46 of file MLine.h.
getVertexInfo()
virtual void MLine::getVertexInfo (const MVertex * vertex, int & ithVertex) const inline virtual
Reimplemented from MElement.
Definition at line 51 of file MLine.h.
getVolume()
double MLine::getVolume () virtual
Reimplemented from MElement.
Definition at line 25 of file MLine.cpp.
isInside()
virtual bool MLine::isInside (double u, double v, double w) const inline virtual
Implements MElement.
Reimplemented in MLineBorder, MLineChild, and MSubLine.
Definition at line 91 of file MLine.h.
Referenced by MLineChild::isInside(), and MLineBorder::isInside().
numCommonNodesInDualGraph()
virtual int MLine::numCommonNodesInDualGraph (const MElement *const other) const inline virtual
Implements MElement.
Definition at line 111 of file MLine.h.
reverse()
virtual void MLine::reverse () inline virtual
Reimplemented from MElement.
Reimplemented in MLineN.
Definition at line 85 of file MLine.h.
Referenced by GModel::alignPeriodicBoundaries().
setVertex()
virtual void MLine::setVertex (int num, MVertex * v) inline virtual
Reimplemented from MElement.
Reimplemented in MLineN, and MLine3.
Definition at line 47 of file MLine.h.
Referenced by blyr_manager::extrude_vertices_on_edges().
Member Data Documentation
_v
MVertex* MLine::_v[2] protected
Definition at line 23 of file MLine.h.
Referenced by _getEdgeVertices(), getEdge(), getEdgeRep(), MLine3::getEdgeRep(), MLineN::getEdgeRep(), getInnerRadius(), MLineBorder::getIntegrationPoints(), getLength(), getVertex(), MLine3::getVertex(), MLineN::getVertex(), getVertexInfo(), MLine(), reverse(), MLineN::reverse(), setVertex(), MLine3::setVertex(), and MLineN::setVertex().
The documentation for this class was generated from the following files:
src/geo/MLine.h
src/geo/MLine.cpp