gmsh-TingyuanDoc: MLine3 Class Reference
MLine3 Class Reference
#include <MLine.h>
Public Member Functions
MLine3 (MVertex *v0, MVertex *v1, MVertex *v2, int num=0, int part=0)
MLine3 (const std::vector< MVertex * > &v, int num=0, int part=0)
~MLine3 ()
virtual int getPolynomialOrder () const
virtual std::size_t getNumVertices () const
virtual MVertex * getVertex (int num)
virtual const MVertex * getVertex (int num) const
virtual void setVertex (int num, MVertex *v)
virtual MVertex * getVertexUNV (int num)
virtual MVertex * getVertexINP (int num)
virtual MVertex * getVertexKEY (int num)
virtual MVertex * getVertexRAD (int num)
virtual int getNumEdgeVertices () const
virtual int getNumEdgesRep (bool curved)
virtual void getEdgeRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getEdgeVertices (const int num, std::vector< MVertex * > &v) const
virtual int getTypeForMSH () const
virtual int getTypeForUNV () const
virtual int getTypeForVTK () const
virtual const char * getStringForPOS () const
virtual const char * getStringForINP () const
virtual const char * getStringForKEY () const
virtual const char * getStringForRAD () const
virtual const char * getStringForTOCHNOG () const
virtual void getNode (int num, double &u, double &v, double &w) const
virtual void discretize (double tol, std::vector< SPoint3 > &dpts, std::vector< double > &ts)
Public Member Functions inherited from MLine
MLine (MVertex *v0, MVertex *v1, int num=0, int part=0)
MLine (const std::vector< MVertex * > &v, int num=0, int part=0)
~MLine ()
virtual int getDim () const
virtual double getInnerRadius ()
virtual double getLength ()
virtual double getVolume ()
virtual void getVertexInfo (const MVertex *vertex, int &ithVertex) const
virtual int getNumEdges () const
virtual MEdge getEdge (int num) const
virtual int getNumFaces ()
virtual MFace getFace (int num) const
virtual int getNumFacesRep (bool curved)
virtual void getFaceRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual int getType () const
virtual const char * getStringForBDF () const
virtual void reverse ()
virtual bool isInside (double u, double v, double w) const
virtual SPoint3 barycenterUVW () const
virtual void getIntegrationPoints (int pOrder, int *npts, IntPt **pts)
virtual int numCommonNodesInDualGraph (const MElement *const other) const
Public Member Functions inherited from MElement
MElement (std::size_t num=0, int part=0)
virtual ~MElement ()
double getTolerance () const
virtual std::size_t getNum () const
void forceNum (std::size_t num)
virtual bool getIsAssimilatedSerendipity () const
virtual bool getIsOnlySerendipity () const
virtual int getPartition () const
virtual void setPartition (int num)
virtual char getVisibility () const
virtual void setVisibility (char val)
void getVertices (std::vector< MVertex * > &verts)
virtual MVertex * getVertexVTK (int num)
virtual MVertex * getVertexMATLAB (int num)
virtual MVertex * getVertexTOCHNOG (int num)
virtual MVertex * getVertexBDF (int num)
virtual MVertex * getVertexDIFF (int num)
virtual MVertex * getVertexNEU (int num)
virtual int getNumFaceVertices () const
virtual int getNumVolumeVertices () const
std::size_t getNumPrimaryVertices () const
virtual MEdgeN getHighOrderEdge (int num, int sign)
MEdgeN getHighOrderEdge (const MEdge &edge)
virtual bool getEdgeInfo (const MEdge &edge, int &ithEdge, int &sign) const
virtual int numEdge2numVertex (int numEdge, int numVert) const
virtual MEdge getEdgeSolin (int numEdge)
virtual MFaceN getHighOrderFace (int num, int sign, int rot)
MFaceN getHighOrderFace (const MFace &face)
virtual bool getFaceInfo (const MFace &face, int &ithFace, int &sign, int &rot) const
virtual MFace getFaceSolin (int numFace)
virtual void getFaceVertices (const int num, std::vector< MVertex * > &v) const
virtual MElement * getParent () const
virtual void setParent (MElement *p, bool owner=false)
virtual void updateParent (GModel *gm)
virtual int getNumChildren () const
virtual MElement * getChild (int i) const
virtual bool ownsParent () const
virtual const MElement * getBaseElement () const
virtual MElement * getBaseElement ()
virtual MElement * getDomain (int i) const
virtual void setDomain (MElement *e, int i)
virtual double maxEdge ()
virtual double minEdge ()
double maxDistToStraight () const
double skewness ()
virtual double gammaShapeMeasure ()
virtual double etaShapeMeasure ()
double minSICNShapeMeasure ()
double minSIGEShapeMeasure ()
double distoShapeMeasure ()
double minIsotropyMeasure (bool knownValid=false, bool reversedOk=false)
double minScaledJacobian (bool knownValid=false, bool reversedOk=false)
virtual double angleShapeMeasure ()
virtual void scaledJacRange (double &jmin, double &jmax, GEntity *ge=nullptr) const
virtual void idealJacRange (double &jmin, double &jmax, GEntity *ge=nullptr)
virtual void signedInvCondNumRange (double &iCNMin, double &iCNMax, GEntity *ge=nullptr)
virtual void signedInvGradErrorRange (double &minSIGE, double &maxSIGE)
virtual double getOuterRadius ()
virtual SPoint3 barycenter (bool primary=false) const
virtual SPoint3 fastBarycenter (bool primary=false) const
virtual SPoint3 barycenter_infty () const
virtual int getVolumeSign ()
virtual bool setVolumePositive ()
int getValidity ()
virtual std::string getInfoString (bool multline)
virtual const nodalBasis * getFunctionSpace (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getFuncSpaceData (int order=-1, bool serendip=false) const
virtual const JacobianBasis * getJacobianFuncSpace (int orderElement=-1) const
virtual const FuncSpaceData getJacobianFuncSpaceData (int orderElement=-1) const
virtual void getShapeFunctions (double u, double v, double w, double s[], int order=-1) const
virtual void getGradShapeFunctions (double u, double v, double w, double s[][3], int order=-1) const
virtual void getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order=-1) const
virtual void getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order=-1) const
virtual double getJacobian (const fullMatrix< double > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double *jac) const
virtual double getJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobian (double u, double v, double w, fullMatrix< double > &j) const
virtual double getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobianDeterminant (double u, double v, double w) const
void getSignedJacobian (fullVector< double > &jacobian, int o=-1) const
void getNodesCoord (fullMatrix< double > &nodesXYZ) const
void getNodesCoordNonSerendip (fullMatrix< double > &nodesXYZ) const
bezierCoeff * getBezierVerticesCoord () const
virtual std::size_t getNumShapeFunctions () const
virtual std::size_t getNumPrimaryShapeFunctions () const
virtual const MVertex * getShapeFunctionNode (int i) const
virtual MVertex * getShapeFunctionNode (int i)
virtual double getEigenvaluesMetric (double u, double v, double w, double values[3]) const
virtual void pnt (double u, double v, double w, SPoint3 &p) const
virtual void pnt (double u, double v, double w, double *p) const
virtual void pnt (const std::vector< double > &sf, SPoint3 &p) const
virtual void primaryPnt (double u, double v, double w, SPoint3 &p)
virtual void xyz2uvw (double xyz[3], double uvw[3]) const
virtual void movePointFromParentSpaceToElementSpace (double &u, double &v, double &w) const
virtual void movePointFromElementSpaceToParentSpace (double &u, double &v, double &w) const
double interpolate (double val[], double u, double v, double w, int stride=1, int order=-1)
void interpolateGrad (double val[], double u, double v, double w, double f[], int stride=1, double invjac[3][3]=nullptr, int order=-1)
void interpolateCurl (double val[], double u, double v, double w, double f[], int stride=3, int order=-1)
double interpolateDiv (double val[], double u, double v, double w, int stride=3, int order=-1)
double integrate (double val[], int pOrder, int stride=1, int order=-1)
double integrateCirc (double val[], int edge, int pOrder, int order=-1)
double integrateFlux (double val[], int face, int pOrder, int order=-1)
virtual void writeMSH2 (FILE *fp, double version=1.0, bool binary=false, int num=0, int elementary=1, int physical=1, int parentNum=0, int dom1Num=0, int dom2Num=0, std::vector< short > *ghosts=nullptr)
virtual void writeMSH3 (FILE *fp, bool binary=false, int elementary=1, std::vector< short > *ghosts=nullptr)
virtual void writePOS (FILE *fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor=1.0, int elementary=1)
virtual void writeSTL (FILE *fp, bool binary=false, double scalingFactor=1.0)
virtual void writeX3D (FILE *fp, double scalingFactor=1.0)
virtual void writeVRML (FILE *fp)
virtual void writePLY2 (FILE *fp)
virtual void writeUNV (FILE *fp, int num=0, int elementary=1, int physical=1)
virtual void writeVTK (FILE *fp, bool binary=false, bool bigEndian=false)
virtual void writeMATLAB (FILE *fp, int filetype, int elementary=0, int physical=0, bool binary=false)
virtual void writeTOCHNOG (FILE *fp, int num)
virtual void writeMESH (FILE *fp, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeNEU (FILE *fp, unsigned gambitType, int adjust, int phys=0)
virtual void writeIR3 (FILE *fp, int elementTagType, int num, int elementary, int physical)
virtual void writeBDF (FILE *fp, int format=0, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeDIFF (FILE *fp, int num, bool binary=false, int physical_property=1)
virtual void writeINP (FILE *fp, int num)
virtual void writeKEY (FILE *fp, int pid, int num)
virtual void writeRAD (FILE *fp, int num)
virtual void writeSU2 (FILE *fp, int num)
virtual const char * getStringForDIFF () const
std::string getName ()
virtual std::size_t getNumVerticesForMSH ()
virtual void getVerticesIdForMSH (std::vector< int > &verts)
virtual MElement * copy (std::map< int, MVertex * > &vertexMap, std::map< MElement *, MElement * > &newParents, std::map< MElement *, MElement * > &newDomains)
Protected Attributes
MVertex * _vs [1]
Protected Attributes inherited from MLine
MVertex * _v [2]
Additional Inherited Members
Static Public Member Functions inherited from MElement
static unsigned int getInfoMSH (const int typeMSH, const char **const name=nullptr)
Protected Member Functions inherited from MLine
void _getEdgeVertices (std::vector< MVertex * > &v) const
Protected Member Functions inherited from MElement
void _getEdgeRep (MVertex *v0, MVertex *v1, double *x, double *y, double *z, SVector3 *n, int faceIndex=-1)
void _getFaceRep (MVertex *v0, MVertex *v1, MVertex *v2, double *x, double *y, double *z, SVector3 *n)
Static Protected Member Functions inherited from MElement
static bool _getFaceInfo (const MFace &face, const MFace &other, int &sign, int &rot)
Static Protected Attributes inherited from MElement
static double _isInsideTolerance
Detailed Description
Definition at line 128 of file MLine.h.
Constructor & Destructor Documentation
MLine3() [1/2]
MLine3::MLine3 (MVertex * v0, MVertex * v1, MVertex * v2, int num = 0, int part = 0) inline
Definition at line 133 of file MLine.h.
MLine3() [2/2]
MLine3::MLine3 (const std::vector< MVertex * > & v, int num = 0, int part = 0) inline
Definition at line 139 of file MLine.h.
~MLine3()
MLine3::~MLine3 () inline
Definition at line 145 of file MLine.h.
Member Function Documentation
discretize()
void MLine3::discretize (double tol, std::vector< SPoint3 > & dpts, std::vector< double > & ts) virtual
Reimplemented from MLine.
Definition at line 88 of file MLine.cpp.
getEdgeRep()
void MLine3::getEdgeRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Reimplemented from MLine.
Definition at line 32 of file MLine.cpp.
getEdgeVertices()
virtual void MLine3::getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MLine.
Definition at line 175 of file MLine.h.
getNode()
virtual void MLine3::getNode (int num, double & u, double & v, double & w) const inline virtual
Reimplemented from MLine.
Definition at line 189 of file MLine.h.
getNumEdgesRep()
int MLine3::getNumEdgesRep (bool curved) virtual
Reimplemented from MLine.
Definition at line 27 of file MLine.cpp.
getNumEdgeVertices()
virtual int MLine3::getNumEdgeVertices () const inline virtual
Reimplemented from MElement.
Definition at line 171 of file MLine.h.
getNumVertices()
virtual std::size_t MLine3::getNumVertices () const inline virtual
Reimplemented from MLine.
Definition at line 147 of file MLine.h.
getPolynomialOrder()
virtual int MLine3::getPolynomialOrder () const inline virtual
Reimplemented from MElement.
Definition at line 146 of file MLine.h.
getStringForINP()
virtual const char* MLine3::getStringForINP () const inline virtual
Reimplemented from MLine.
Definition at line 185 of file MLine.h.
getStringForKEY()
virtual const char* MLine3::getStringForKEY () const inline virtual
Reimplemented from MLine.
Definition at line 186 of file MLine.h.
getStringForPOS()
virtual const char* MLine3::getStringForPOS () const inline virtual
Reimplemented from MLine.
Definition at line 184 of file MLine.h.
getStringForRAD()
virtual const char* MLine3::getStringForRAD () const inline virtual
Reimplemented from MLine.
Definition at line 187 of file MLine.h.
getStringForTOCHNOG()
virtual const char* MLine3::getStringForTOCHNOG () const inline virtual
Reimplemented from MLine.
Definition at line 188 of file MLine.h.
getTypeForMSH()
virtual int MLine3::getTypeForMSH () const inline virtual
Reimplemented from MLine.
Definition at line 181 of file MLine.h.
getTypeForUNV()
virtual int MLine3::getTypeForUNV () const inline virtual
Reimplemented from MLine.
Definition at line 182 of file MLine.h.
getTypeForVTK()
virtual int MLine3::getTypeForVTK () const inline virtual
Reimplemented from MLine.
Definition at line 183 of file MLine.h.
getVertex() [1/2]
virtual MVertex* MLine3::getVertex (int num) inline virtual
Reimplemented from MLine.
Definition at line 148 of file MLine.h.
Referenced by discretize(), and getVertexUNV().
getVertex() [2/2]
virtual const MVertex* MLine3::getVertex (int num) const inline virtual
Reimplemented from MLine.
Definition at line 152 of file MLine.h.
getVertexINP()
virtual MVertex* MLine3::getVertexINP (int num) inline virtual
Reimplemented from MElement.
Definition at line 168 of file MLine.h.
getVertexKEY()
virtual MVertex* MLine3::getVertexKEY (int num) inline virtual
Reimplemented from MElement.
Definition at line 169 of file MLine.h.
getVertexRAD()
virtual MVertex* MLine3::getVertexRAD (int num) inline virtual
Reimplemented from MElement.
Definition at line 170 of file MLine.h.
getVertexUNV()
virtual MVertex* MLine3::getVertexUNV (int num) inline virtual
Reimplemented from MElement.
Definition at line 163 of file MLine.h.
Referenced by getVertexINP(), getVertexKEY(), and getVertexRAD().
setVertex()
virtual void MLine3::setVertex (int num, MVertex * v) inline virtual
Reimplemented from MLine.
Definition at line 156 of file MLine.h.
Member Data Documentation
_vs
MVertex* MLine3::_vs[1] protected
Definition at line 130 of file MLine.h.
Referenced by getEdgeVertices(), getVertex(), MLine3(), and setVertex().
The documentation for this class was generated from the following files:
src/geo/MLine.h
src/geo/MLine.cpp