gmsh-TingyuanDoc: SBoundingBox3d Class Reference
SBoundingBox3d Class Reference
#include <SBoundingBox3d.h>
Public Member Functions
SBoundingBox3d ()
SBoundingBox3d (const SPoint3 &pt)
SBoundingBox3d (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax)
bool empty ()
void reset ()
void operator+= (const SPoint3 &pt)
void operator+= (const SBoundingBox3d &box)
void operator*= (double scale)
void scale (double sx, double sy, double sz)
SPoint3 min () const
SPoint3 max () const
SPoint3 center () const
double diag () const
void makeCube ()
void thicken (double factor)
bool contains (const SBoundingBox3d &bound)
bool contains (const SPoint3 &p)
bool contains (double x, double y, double z)
bool transform (const std::vector< double > &tfo)
Private Attributes
SPoint3 MinPt
SPoint3 MaxPt
Detailed Description
Definition at line 21 of file SBoundingBox3d.h.
Constructor & Destructor Documentation
SBoundingBox3d() [1/3]
SBoundingBox3d::SBoundingBox3d () inline
Definition at line 26 of file SBoundingBox3d.h.
SBoundingBox3d() [2/3]
SBoundingBox3d::SBoundingBox3d (const SPoint3 & pt) inline
Definition at line 30 of file SBoundingBox3d.h.
SBoundingBox3d() [3/3]
SBoundingBox3d::SBoundingBox3d (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax) inline
Definition at line 31 of file SBoundingBox3d.h.
Member Function Documentation
center()
SPoint3 SBoundingBox3d::center () const inline
Definition at line 92 of file SBoundingBox3d.h.
Referenced by addPoints(), AddToTemporaryBoundingBox(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), makeCube(), meshGRegionNetgen(), optimizeMeshGRegionNetgen::operator()(), drawGRegion::operator()(), operator*=(), scale(), and PView::writeX3D().
contains() [1/3]
bool SBoundingBox3d::contains (const SBoundingBox3d & bound) inline
Definition at line 110 of file SBoundingBox3d.h.
contains() [2/3]
bool SBoundingBox3d::contains (const SPoint3 & p) inline
Definition at line 118 of file SBoundingBox3d.h.
contains() [3/3]
bool SBoundingBox3d::contains (double x, double y, double z) inline
Definition at line 125 of file SBoundingBox3d.h.
diag()
double SBoundingBox3d::diag () const inline
Definition at line 93 of file SBoundingBox3d.h.
Referenced by discreteFace::param::checkPlanar(), initialCube(), GFace::setMeshMaster(), thicken(), and PView::writeX3D().
empty()
bool SBoundingBox3d::empty () inline
Definition at line 36 of file SBoundingBox3d.h.
Referenced by AddToTemporaryBoundingBox(), GFace::buildRepresentationCross(), GModel::checkMeshCoherence(), MergePostProcessingFile(), drawPView::operator()(), drawPViewBoundingBox::operator()(), opt_general_xmax(), opt_general_xmin(), opt_general_ymax(), opt_general_ymin(), opt_general_zmax(), opt_general_zmin(), GModel::removeDuplicateMeshVertices(), SetBoundingBox(), and writeMSH4BoundingBox().
makeCube()
void SBoundingBox3d::makeCube () inline
Definition at line 94 of file SBoundingBox3d.h.
Referenced by meshGenerator(), meshGeneratorPeriodic(), and minmax().
max()
SPoint3 SBoundingBox3d::max () const inline
Definition at line 91 of file SBoundingBox3d.h.
Referenced by OctreePost::_create(), addPoints(), AddToTemporaryBoundingBox(), GFace::buildRepresentationCross(), GModel::checkMeshCoherence(), GFace::computeMeanPlane(), GMSH_ProbePlugin::draw(), GMSH_CutPlanePlugin::draw(), drawContext::drawAxes(), GMSH_BubblesPlugin::execute(), GMSH_DistancePlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GModel::getEntitiesInBox(), getGraphData(), getLineNormal(), GFaceInitialMesh(), initialCube(), initialSquare(), MElementBB(), MElementOctree::MElementOctree(), meshGenerator(), meshGeneratorPeriodic(), minmax(), HilbertSort::MultiscaleSortHilbert(), HilbertSortB::MultiscaleSortHilbert(), drawPViewBoundingBox::operator()(), OctreeField::operator()(), opt_general_xmax(), opt_general_ymax(), opt_general_zmax(), GModel::readSTL(), GModel::removeDuplicateMeshVertices(), GMSH_SimplePartitionPlugin::run(), SetBoundingBox(), GFace::setMeshMaster(), GRegion::setOutwardOrientationMeshConstraint(), VertexArray::toChar(), OctreeField::update(), PViewDataList::writeMSH(), and writeMSH4BoundingBox().
min()
SPoint3 SBoundingBox3d::min () const inline
Definition at line 90 of file SBoundingBox3d.h.
Referenced by OctreePost::_create(), AddToTemporaryBoundingBox(), GFace::buildRepresentationCross(), GModel::checkMeshCoherence(), GFace::computeMeanPlane(), GMSH_ProbePlugin::draw(), GMSH_CutPlanePlugin::draw(), drawContext::drawAxes(), GMSH_BubblesPlugin::execute(), GMSH_DistancePlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GModel::getEntitiesInBox(), getGraphData(), getLineNormal(), GFaceInitialMesh(), initialCube(), initialSquare(), MElementBB(), MElementOctree::MElementOctree(), meshGenerator(), meshGeneratorPeriodic(), minmax(), HilbertSort::MultiscaleSortHilbert(), HilbertSortB::MultiscaleSortHilbert(), drawPViewBoundingBox::operator()(), OctreeField::operator()(), opt_general_xmin(), opt_general_ymin(), opt_general_zmin(), GModel::readSTL(), GModel::removeDuplicateMeshVertices(), GMSH_SimplePartitionPlugin::run(), SetBoundingBox(), GFace::setMeshMaster(), GRegion::setOutwardOrientationMeshConstraint(), VertexArray::toChar(), OctreeField::update(), PViewDataList::writeMSH(), and writeMSH4BoundingBox().
operator*=()
void SBoundingBox3d::operator*= (double scale) inline
Definition at line 66 of file SBoundingBox3d.h.
operator+=() [1/2]
void SBoundingBox3d::operator+= (const SBoundingBox3d & box) inline
Definition at line 61 of file SBoundingBox3d.h.
operator+=() [2/2]
void SBoundingBox3d::operator+= (const SPoint3 & pt) inline
Definition at line 48 of file SBoundingBox3d.h.
reset()
void SBoundingBox3d::reset () inline
Definition at line 43 of file SBoundingBox3d.h.
Referenced by addElementsInArrays(), PViewDataList::finalize(), and ResetTemporaryBoundingBox().
scale()
void SBoundingBox3d::scale (double sx, double sy, double sz) inline
Definition at line 76 of file SBoundingBox3d.h.
Referenced by makeCube(), and operator*=().
thicken()
void SBoundingBox3d::thicken (double factor) inline
Definition at line 103 of file SBoundingBox3d.h.
Referenced by OctreePost::_create(), MElementBB(), MElementOctree::MElementOctree(), and minmax().
transform()
bool SBoundingBox3d::transform (const std::vector< double > & tfo) inline
Definition at line 132 of file SBoundingBox3d.h.
Referenced by GFace::setMeshMaster().
Member Data Documentation
MaxPt
SPoint3 SBoundingBox3d::MaxPt private
Definition at line 23 of file SBoundingBox3d.h.
Referenced by center(), contains(), diag(), empty(), makeCube(), max(), operator*=(), operator+=(), reset(), scale(), thicken(), and transform().
MinPt
SPoint3 SBoundingBox3d::MinPt private
Definition at line 23 of file SBoundingBox3d.h.
Referenced by center(), contains(), diag(), empty(), makeCube(), min(), operator*=(), operator+=(), reset(), scale(), thicken(), and transform().
The documentation for this class was generated from the following file:
src/geo/SBoundingBox3d.h