gmsh-TingyuanDoc: PViewData Class Reference
PViewData Class Reference abstract
#include <PViewData.h>
Public Member Functions
PViewData ()
virtual ~PViewData ()
virtual bool getDirty ()
virtual void setDirty (bool val)
virtual bool finalize (bool computeMinMax=true, const std::string &interpolationScheme="")
virtual std::string getName ()
virtual void setName (const std::string &val)
virtual std::string getFileName (int step=-1)
virtual void setFileName (const std::string &val)
virtual bool hasFileName (const std::string &val)
virtual int getFileIndex ()
virtual void setFileIndex (int val)
virtual int getNumTimeSteps ()=0
virtual int getFirstNonEmptyTimeStep (int start=0)
virtual double getTime (int step)
virtual double getMin (int step=-1, bool onlyVisible=false, int tensorRep=0, int forceNumComponents=0, int componentMap[9]=nullptr)=0
virtual double getMax (int step=-1, bool onlyVisible=false, int tensorRep=0, int forceNumComponents=0, int componentMap[9]=nullptr)=0
virtual void setMin (double min)=0
virtual void setMax (double max)=0
virtual SBoundingBox3d getBoundingBox (int step=-1)=0
virtual void setBoundingBox (SBoundingBox3d &box)=0
virtual int getNumScalars (int step=-1)
virtual int getNumVectors (int step=-1)
virtual int getNumTensors (int step=-1)
virtual int getNumPoints (int step=-1)
virtual int getNumLines (int step=-1)
virtual int getNumTriangles (int step=-1)
virtual int getNumQuadrangles (int step=-1)
virtual int getNumPolygons (int step=-1)
virtual int getNumTetrahedra (int step=-1)
virtual int getNumHexahedra (int step=-1)
virtual int getNumPrisms (int step=-1)
virtual int getNumPyramids (int step=-1)
virtual int getNumTrihedra (int step=-1)
virtual int getNumPolyhedra (int step=-1)
virtual int getNumEntities (int step=-1)
virtual int getNumElements (int step=-1, int ent=-1)
virtual int getDimension (int step, int ent, int ele)
virtual int getNumNodes (int step, int ent, int ele)
virtual int getNode (int step, int ent, int ele, int nod, double &x, double &y, double &z)
virtual void setNode (int step, int ent, int ele, int nod, double x, double y, double z)
virtual void tagNode (int step, int ent, int ele, int nod, int tag)
virtual int getNumComponents (int step, int ent, int ele)
virtual int getNumValues (int step, int ent, int ele)
virtual void getValue (int step, int ent, int ele, int idx, double &val)
virtual void getValue (int step, int ent, int ele, int nod, int comp, double &val)
virtual void setValue (int step, int ent, int ele, int nod, int comp, double val)
void getScalarValue (int step, int ent, int ele, int nod, double &val, int tensorRep=0, int forceNumComponents=0, int componentMap[9]=nullptr)
virtual int getNumEdges (int step, int ent, int ele)
virtual int getType (int step, int ent, int ele)
virtual int getNumStrings2D ()
virtual int getNumStrings3D ()
virtual void getString2D (int i, int step, std::string &str, double &x, double &y, double &style)
virtual void getString3D (int i, int step, std::string &str, double &x, double &y, double &z, double &style)
virtual void reverseElement (int step, int ent, int ele)
virtual bool empty ()
virtual bool skipEntity (int step, int ent)
virtual bool skipElement (int step, int ent, int ele, bool checkVisibility=false, int samplingRate=1)
virtual bool hasTimeStep (int step)
virtual bool hasPartition (int step, int part)
virtual bool hasMultipleMeshes ()
virtual bool hasModel (GModel *model, int step=-1)
virtual bool isNodeData ()
virtual bool useGaussPoints ()
void initAdaptiveData (int step, int level, double tol)
void initAdaptiveDataLight (int step, int level, double tol)
void saveAdaptedViewForVTK (const std::string &guifileName, int useDefaultName, int step, int level, double tol, int npart, bool isBinary)
void destroyAdaptiveData ()
adaptiveData * getAdaptiveData ()
void setInterpolationMatrices (int type, const fullMatrix< double > &coefVal, const fullMatrix< double > &expVal)
void setInterpolationMatrices (int type, const fullMatrix< double > &coefVal, const fullMatrix< double > &expVal, const fullMatrix< double > &coefGeo, const fullMatrix< double > &expGeo)
int getInterpolationMatrices (int type, std::vector< fullMatrix< double > * > &p)
bool haveInterpolationMatrices (int type=0)
void deleteInterpolationMatrices (int type=0)
std::string getInterpolationSchemeName ()
void setInterpolationSchemeName (std::string name)
virtual void smooth ()
virtual bool combineTime (nameData &nd)
virtual bool combineSpace (nameData &nd)
virtual void setXY (std::vector< double > &x, std::vector< double > &y)
virtual void setXYZV (std::vector< double > &x, std::vector< double > &y, std::vector< double > &z, std::vector< double > &v)
virtual bool isRemote ()
virtual int fillRemoteVertexArrays (std::string &options)
virtual bool isListBased ()
virtual double getMemoryInMb ()
virtual GModel * getModel (int step)
virtual GEntity * getEntity (int step, int entity)
virtual MElement * getElement (int step, int entity, int element)
double findClosestNode (double &xn, double &yn, double &zn, int step)
bool searchScalar (double x, double y, double z, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchVector (double x, double y, double z, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchTensor (double x, double y, double z, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchScalarClosest (double x, double y, double z, double &distance, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchVectorClosest (double x, double y, double z, double &distance, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchTensorClosest (double x, double y, double z, double &distance, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
virtual bool writeSTL (const std::string &fileName)
virtual bool writeTXT (const std::string &fileName)
virtual bool writePOS (const std::string &fileName, bool binary=false, bool parsed=true, bool append=false)
virtual bool writeMSH (const std::string &fileName, double version=2.2, bool binary=false, bool saveMesh=true, bool multipleView=false, int partitionNum=-1, bool saveInterpolationMatrices=true, bool forceNodeData=false, bool forceElementData=false)
virtual bool writeMED (const std::string &fileName)
virtual bool toVector (std::vector< std::vector< double > > &vec)
virtual bool fromVector (const std::vector< std::vector< double > > &vec)
virtual void importLists (int N[24], std::vector< double > *V[24])
virtual void getListPointers (int N[24], std::vector< double > *V[24])
virtual void sendToServer (const std::string &name)
Static Public Member Functions
static void removeInterpolationScheme (const std::string &name)
static void removeAllInterpolationSchemes ()
static void addMatrixToInterpolationScheme (const std::string &name, int type, fullMatrix< double > &mat)
static int getSizeInterpolationScheme ()
Protected Attributes
adaptiveData * _adaptive
interpolationMatrices _interpolation
std::string _interpolationSchemeName
Static Protected Attributes
static std::map< std::string, interpolationMatrices > _interpolationSchemes
Private Attributes
bool _dirty
std::string _name
std::string _fileName
std::set< std::string > _fileNames
int _fileIndex
OctreePost * _octree
SPoint3Cloud _pc
SPoint3CloudAdaptor< SPoint3Cloud > _pc2kdtree
SPoint3KDTree * _kdtree
Detailed Description
Definition at line 29 of file PViewData.h.
Constructor & Destructor Documentation
PViewData()
PViewData::PViewData ()
Definition at line 15 of file PViewData.cpp.
~PViewData()
PViewData::~PViewData () virtual
Definition at line 21 of file PViewData.cpp.
Member Function Documentation
addMatrixToInterpolationScheme()
void PViewData::addMatrixToInterpolationScheme (const std::string & name, int type, fullMatrix< double > & mat) static
Definition at line 219 of file PViewData.cpp.
Referenced by PView::readMSH().
combineSpace()
bool PViewData::combineSpace (nameData & nd) virtual
Reimplemented in PViewDataList.
Definition at line 242 of file PViewData.cpp.
Referenced by PView::combine().
combineTime()
bool PViewData::combineTime (nameData & nd) virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 236 of file PViewData.cpp.
Referenced by PView::combine().
deleteInterpolationMatrices()
void PViewData::deleteInterpolationMatrices (int type = 0)
Definition at line 194 of file PViewData.cpp.
destroyAdaptiveData()
void PViewData::destroyAdaptiveData ()
Definition at line 79 of file PViewData.cpp.
Referenced by PView::combine(), GMSH_LongituteLatitudePlugin::execute(), and saveAdaptedViewForVTK().
empty()
bool PViewData::empty () virtual
Definition at line 85 of file PViewData.cpp.
Referenced by fromVector(), and PViewDataGModel::getBoundingBox().
fillRemoteVertexArrays()
virtual int PViewData::fillRemoteVertexArrays (std::string & options) inline virtual
Reimplemented in PViewDataRemote.
Definition at line 282 of file PViewData.h.
Referenced by GMSH_PostPlugin::executeRemote(), and initPView::operator()().
finalize()
bool PViewData::finalize (bool computeMinMax = true, const std::string & interpolationScheme = "") virtual
Reimplemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
Definition at line 30 of file PViewData.cpp.
Referenced by GMSH_LongituteLatitudePlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), PViewDataList::finalize(), and PViewDataGModel::finalize().
findClosestNode()
double PViewData::findClosestNode (double & xn, double & yn, double & zn, int step)
Definition at line 248 of file PViewData.cpp.
Referenced by searchScalarClosest(), searchTensorClosest(), and searchVectorClosest().
fromVector()
bool PViewData::fromVector (const std::vector< std::vector< double > > & vec) virtual
Definition at line 238 of file PViewDataIO.cpp.
getAdaptiveData()
adaptiveData* PViewData::getAdaptiveData () inline
Definition at line 238 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::execute(), PView::getData(), PViewDataGModel::getNumNodes(), and GMSH_PostPlugin::getPossiblyAdaptiveData().
getBoundingBox()
virtual SBoundingBox3d PViewData::getBoundingBox (int step = -1) pure virtual
Implemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
Referenced by GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), getGraphData(), getLineNormal(), drawPViewBoundingBox::operator()(), and PView::writeX3D().
getDimension()
virtual int PViewData::getDimension (int step, int ent, int ele) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 134 of file PViewData.h.
Referenced by addElementsInArrays(), drawGlyphs(), GMSH_IntegratePlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), getGraphData(), and writeSTL().
getDirty()
virtual bool PViewData::getDirty () inline virtual
Definition at line 62 of file PViewData.h.
Referenced by drawContext::drawGraph2d(), drawContext::drawScales(), drawPView::operator()(), initPView::operator()(), and PView::writeX3D().
getElement()
MElement * PViewData::getElement (int step, int entity, int element) virtual
Reimplemented in PViewDataGModel.
Definition at line 148 of file PViewData.cpp.
getEntity()
GEntity * PViewData::getEntity (int step, int entity) virtual
Reimplemented in PViewDataGModel.
Definition at line 142 of file PViewData.cpp.
Referenced by GMSH_MathEvalPlugin::execute().
getFileIndex()
virtual int PViewData::getFileIndex () inline virtual
Definition at line 86 of file PViewData.h.
Referenced by PViewDataGModel::smooth().
getFileName()
virtual std::string PViewData::getFileName (int step = -1) inline virtual
Reimplemented in PViewDataGModel.
Definition at line 74 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::execute(), and PViewDataGModel::getFileName().
getFirstNonEmptyTimeStep()
virtual int PViewData::getFirstNonEmptyTimeStep (int start = 0) inline virtual
Reimplemented in PViewDataGModel.
Definition at line 91 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), drawScaleLabel(), GMSH_IntegratePlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_LevelsetPlugin::execute(), findClosestNode(), writePOS(), and writeSTL().
getInterpolationMatrices()
int PViewData::getInterpolationMatrices (int type, std::vector< fullMatrix< double > * > & p)
Definition at line 176 of file PViewData.cpp.
Referenced by PViewDataList::_getRawData(), PViewDataList::_setLast(), PViewDataList::_stat(), and adaptiveData::adaptiveData().
getInterpolationSchemeName()
std::string PViewData::getInterpolationSchemeName () inline
Definition at line 258 of file PViewData.h.
getListPointers()
void PViewData::getListPointers (int N[24], std::vector< double > * V[24]) virtual
Reimplemented in PViewDataList.
Definition at line 282 of file PViewDataIO.cpp.
getMax()
virtual double PViewData::getMax (int step = -1, bool onlyVisible = false, int tensorRep = 0, int forceNumComponents = 0, int componentMap[9] = nullptr) pure virtual
Implemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
Referenced by adaptiveElements< T >::addInViewForVTK(), drawGraph(), drawScale(), getExternalValues(), drawPView::operator()(), initPView::operator()(), and writeX3DScale().
getMemoryInMb()
virtual double PViewData::getMemoryInMb () inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 288 of file PViewData.h.
Referenced by PView::getMemoryInMb().
getMin()
virtual double PViewData::getMin (int step = -1, bool onlyVisible = false, int tensorRep = 0, int forceNumComponents = 0, int componentMap[9] = nullptr) pure virtual
Implemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
Referenced by adaptiveElements< T >::addInViewForVTK(), drawGraph(), drawScale(), getExternalValues(), drawPView::operator()(), initPView::operator()(), and writeX3DScale().
getModel()
GModel * PViewData::getModel (int step) virtual
Reimplemented in PViewDataGModel.
Definition at line 136 of file PViewData.cpp.
getName()
virtual std::string PViewData::getName () inline virtual
Definition at line 70 of file PViewData.h.
Referenced by _addModelData(), adaptiveData::adaptiveData(), adaptiveData::changeResolutionForVTK(), PView::combine(), drawGraphAxes(), drawScaleLabel(), drawContext::drawScales(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_Lambda2Plugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_ProbePlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_AnnotatePlugin::execute(), GMSH_CutParametricPlugin::execute(), GMSH_CutGridPlugin::GenerateView(), GMSH_CutBoxPlugin::GenerateView(), GMSH_PostPlugin::getPossiblyAdaptiveData(), PViewLessThanName::operator()(), PViewDataList::writeMSH(), PViewDataGModel::writeMSH(), PViewDataList::writePOS(), writePOS(), PView::writeX3D(), and writeX3DScaleLabel().
getNode()
virtual int PViewData::getNode (int step, int ent, int ele, int nod, double & x, double & y, double & z) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 141 of file PViewData.h.
Referenced by addElementsInArrays(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), addVectorElement(), drawGlyphs(), GMSH_IntegratePlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_LongituteLatitudePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), findClosestNode(), fromVector(), getGraphData(), writePOS(), writeSTL(), and writeTXT().
getNumComponents()
virtual int PViewData::getNumComponents (int step, int ent, int ele) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 152 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), addElementsInArrays(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), addVectorElement(), adaptiveData::changeResolutionForVTK(), drawGlyphs(), GMSH_SkinPlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_LongituteLatitudePlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), fromVector(), getExternalValues(), getGraphData(), getScalarValue(), toVector(), writePOS(), and writeTXT().
getNumEdges()
virtual int PViewData::getNumEdges (int step, int ent, int ele) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 180 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), adaptiveElements< T >::countElmLev0(), GMSH_IntegratePlugin::execute(), and GMSH_WarpPlugin::execute().
getNumElements()
virtual int PViewData::getNumElements (int step = -1, int ent = -1) inline virtual
Reimplemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
Definition at line 131 of file PViewData.h.
Referenced by addElementsInArrays(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), adaptiveElements< T >::countElmLev0(), drawGlyphs(), drawContext::drawScales(), empty(), GMSH_IntegratePlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_LongituteLatitudePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), findClosestNode(), fromVector(), getExternalValues(), getGraphData(), toVector(), writePOS(), writeSTL(), writeTXT(), and PView::writeX3D().
getNumEntities()
virtual int PViewData::getNumEntities (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 127 of file PViewData.h.
Referenced by addElementsInArrays(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), adaptiveElements< T >::countElmLev0(), drawGlyphs(), GMSH_IntegratePlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_LongituteLatitudePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), findClosestNode(), fromVector(), getGraphData(), toVector(), writePOS(), writeSTL(), and writeTXT().
getNumHexahedra()
virtual int PViewData::getNumHexahedra (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 120 of file PViewData.h.
Referenced by initPView::_estimateNumTriangles(), adaptiveData::adaptiveData(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), and GetStatistics().
getNumLines()
virtual int PViewData::getNumLines (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 115 of file PViewData.h.
Referenced by initPView::_estimateNumLines(), adaptiveData::adaptiveData(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), and GetStatistics().
getNumNodes()
virtual int PViewData::getNumNodes (int step, int ent, int ele) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 137 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), addElementsInArrays(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), drawGlyphs(), GMSH_IntegratePlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_LongituteLatitudePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), findClosestNode(), fromVector(), getExternalValues(), getGraphData(), toVector(), writePOS(), writeSTL(), and writeTXT().
getNumPoints()
virtual int PViewData::getNumPoints (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 114 of file PViewData.h.
Referenced by initPView::_estimateNumPoints(), adaptiveData::adaptiveData(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), GMSH_NearestNeighborPlugin::execute(), and GetStatistics().
getNumPolygons()
virtual int PViewData::getNumPolygons (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 118 of file PViewData.h.
Referenced by initPView::_estimateNumTriangles().
getNumPolyhedra()
virtual int PViewData::getNumPolyhedra (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 124 of file PViewData.h.
Referenced by initPView::_estimateNumTriangles().
getNumPrisms()
virtual int PViewData::getNumPrisms (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 121 of file PViewData.h.
Referenced by initPView::_estimateNumTriangles(), adaptiveData::adaptiveData(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), and GetStatistics().
getNumPyramids()
virtual int PViewData::getNumPyramids (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 122 of file PViewData.h.
Referenced by initPView::_estimateNumTriangles(), adaptiveData::adaptiveData(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), and GetStatistics().
getNumQuadrangles()
virtual int PViewData::getNumQuadrangles (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 117 of file PViewData.h.
Referenced by initPView::_estimateNumTriangles(), adaptiveData::adaptiveData(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), GetStatistics(), and writeSTL().
getNumScalars()
virtual int PViewData::getNumScalars (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 111 of file PViewData.h.
Referenced by GMSH_CutParametricPlugin::execute(), GMSH_CutGridPlugin::GenerateView(), and GMSH_CutBoxPlugin::GenerateView().
getNumStrings2D()
virtual int PViewData::getNumStrings2D () inline virtual
Reimplemented in PViewDataList.
Definition at line 186 of file PViewData.h.
Referenced by drawContext::drawText2d(), empty(), and GetStatistics().
getNumStrings3D()
virtual int PViewData::getNumStrings3D () inline virtual
Reimplemented in PViewDataList.
Definition at line 187 of file PViewData.h.
Referenced by empty(), GetStatistics(), and drawPView::operator()().
getNumTensors()
virtual int PViewData::getNumTensors (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 113 of file PViewData.h.
Referenced by initPView::_estimateNumEllipses(), GMSH_CutParametricPlugin::execute(), GMSH_CutGridPlugin::GenerateView(), and GMSH_CutBoxPlugin::GenerateView().
getNumTetrahedra()
virtual int PViewData::getNumTetrahedra (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 119 of file PViewData.h.
Referenced by initPView::_estimateNumTriangles(), adaptiveData::adaptiveData(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), and GetStatistics().
getNumTimeSteps()
virtual int PViewData::getNumTimeSteps () pure virtual
Implemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), drawGraphAxes(), drawScaleLabel(), GMSH_SphericalRaisePlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_LongituteLatitudePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_ProbePlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_AnnotatePlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GMSH_CutParametricPlugin::execute(), fromVector(), GMSH_CutGridPlugin::GenerateView(), GMSH_CutBoxPlugin::GenerateView(), getGraphData(), GMSH_PostPlugin::getPossiblyAdaptiveData(), hasTimeStep(), drawPView::operator()(), initPView::operator()(), toVector(), writePOS(), writeTXT(), and writeX3DScaleLabel().
getNumTriangles()
virtual int PViewData::getNumTriangles (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 116 of file PViewData.h.
Referenced by initPView::_estimateNumTriangles(), adaptiveData::adaptiveData(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), GetStatistics(), and writeSTL().
getNumTrihedra()
virtual int PViewData::getNumTrihedra (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 123 of file PViewData.h.
Referenced by initPView::_estimateNumTriangles().
getNumValues()
virtual int PViewData::getNumValues (int step, int ent, int ele) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 156 of file PViewData.h.
Referenced by adaptiveElements< T >::addInView(), and adaptiveElements< T >::addInViewForVTK().
getNumVectors()
virtual int PViewData::getNumVectors (int step = -1) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 112 of file PViewData.h.
Referenced by initPView::_estimateNumVectors(), GMSH_CutParametricPlugin::execute(), GMSH_CutGridPlugin::GenerateView(), and GMSH_CutBoxPlugin::GenerateView().
getScalarValue()
void PViewData::getScalarValue (int step, int ent, int ele, int nod, double & val, int tensorRep = 0, int forceNumComponents = 0, int componentMap[9] = nullptr)
Definition at line 97 of file PViewData.cpp.
Referenced by GMSH_MinMaxPlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_LevelsetPlugin::execute(), PViewDataGModel::finalize(), PViewDataList::getMax(), PViewDataGModel::getMax(), PViewDataList::getMin(), and PViewDataGModel::getMin().
getSizeInterpolationScheme()
int PViewData::getSizeInterpolationScheme () static
Definition at line 226 of file PViewData.cpp.
getString2D()
virtual void PViewData::getString2D (int i, int step, std::string & str, double & x, double & y, double & style) inline virtual
Reimplemented in PViewDataList.
Definition at line 190 of file PViewData.h.
Referenced by drawContext::drawText2d().
getString3D()
virtual void PViewData::getString3D (int i, int step, std::string & str, double & x, double & y, double & z, double & style) inline virtual
Reimplemented in PViewDataList.
Definition at line 194 of file PViewData.h.
Referenced by drawPView::operator()().
getTime()
virtual double PViewData::getTime (int step) inline virtual
Reimplemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
Definition at line 94 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), drawGraphAxes(), drawScaleLabel(), drawContext::drawScales(), GMSH_SkinPlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_ProbePlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_AnnotatePlugin::execute(), getGraphData(), writeTXT(), PView::writeX3D(), and writeX3DScaleLabel().
getType()
virtual int PViewData::getType (int step, int ent, int ele) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 183 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), addElementsInArrays(), drawGlyphs(), GMSH_IntegratePlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_Scal2TensPlugin::execute(), getGraphData(), and writePOS().
getValue() [1/2]
virtual void PViewData::getValue (int step, int ent, int ele, int idx, double & val) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 159 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), addElementsInArrays(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), addVectorElement(), drawGlyphs(), GMSH_SkinPlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_LongituteLatitudePlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), getExternalValues(), getGraphData(), getScalarValue(), toVector(), writePOS(), and writeTXT().
getValue() [2/2]
virtual void PViewData::getValue (int step, int ent, int ele, int nod, int comp, double & val) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 163 of file PViewData.h.
hasFileName()
virtual bool PViewData::hasFileName (const std::string & val) inline virtual
Definition at line 80 of file PViewData.h.
hasModel()
virtual bool PViewData::hasModel (GModel * model, int step = -1) inline virtual
Reimplemented in PViewDataGModel.
Definition at line 217 of file PViewData.h.
hasMultipleMeshes()
virtual bool PViewData::hasMultipleMeshes () inline virtual
Reimplemented in PViewDataGModel.
Definition at line 216 of file PViewData.h.
Referenced by GMSH_SkinPlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_LevelsetPlugin::execute(), getGraphData(), and writePOS().
hasPartition()
virtual bool PViewData::hasPartition (int step, int part) inline virtual
Reimplemented in PViewDataGModel.
Definition at line 215 of file PViewData.h.
hasTimeStep()
virtual bool PViewData::hasTimeStep (int step) inline virtual
Reimplemented in PViewDataGModel.
Definition at line 211 of file PViewData.h.
Referenced by GMSH_LevelsetPlugin::_cutAndAddElements(), addVectorElement(), GMSH_SkinPlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_LevelsetPlugin::execute(), getGraphData(), and writePOS().
haveInterpolationMatrices()
bool PViewData::haveInterpolationMatrices (int type = 0)
Definition at line 186 of file PViewData.cpp.
Referenced by OctreePost::_create(), PViewDataList::_getRawData(), PViewDataList::_setLast(), PViewDataList::_stat(), PViewDataGModel::finalize(), PViewDataList::writeMSH(), PViewDataGModel::writeMSH(), PViewDataList::writePOS(), and writePOS().
importLists()
void PViewData::importLists (int N[24], std::vector< double > * V[24]) virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 277 of file PViewDataIO.cpp.
initAdaptiveData()
void PViewData::initAdaptiveData (int step, int level, double tol)
Definition at line 37 of file PViewData.cpp.
Referenced by _addModelData(), PView::combine(), and PView::PView().
initAdaptiveDataLight()
void PViewData::initAdaptiveDataLight (int step, int level, double tol)
Definition at line 47 of file PViewData.cpp.
Referenced by saveAdaptedViewForVTK().
isListBased()
virtual bool PViewData::isListBased () inline virtual
Reimplemented in PViewDataList.
Definition at line 285 of file PViewData.h.
isNodeData()
virtual bool PViewData::isNodeData () inline virtual
Reimplemented in PViewDataGModel.
Definition at line 218 of file PViewData.h.
Referenced by GMSH_LongituteLatitudePlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), and GMSH_ModifyComponentsPlugin::execute().
isRemote()
virtual bool PViewData::isRemote () inline virtual
Reimplemented in PViewDataRemote.
Definition at line 281 of file PViewData.h.
Referenced by PView::getData(), and initPView::operator()().
removeAllInterpolationSchemes()
void PViewData::removeAllInterpolationSchemes () static
Definition at line 209 of file PViewData.cpp.
Referenced by DeleteAllModelsAndViews().
removeInterpolationScheme()
void PViewData::removeInterpolationScheme (const std::string & name) static
Definition at line 199 of file PViewData.cpp.
Referenced by PView::readMSH().
reverseElement()
virtual void PViewData::reverseElement (int step, int ent, int ele) inline virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 200 of file PViewData.h.
Referenced by GMSH_TransformPlugin::execute().
saveAdaptedViewForVTK()
void PViewData::saveAdaptedViewForVTK (const std::string & guifileName, int useDefaultName, int step, int level, double tol, int npart, bool isBinary)
Definition at line 61 of file PViewData.cpp.
Referenced by PView::writeAdapt().
searchScalar()
bool PViewData::searchScalar (double x, double y, double z, double * values, int step = -1, double * size = nullptr, int qn = 0, double * qx = nullptr, double * qy = nullptr, double * qz = nullptr, bool grad = false, int dim = -1)
Definition at line 322 of file PViewData.cpp.
Referenced by PViewEvaluator::operator()(), and searchScalarClosest().
searchScalarClosest()
bool PViewData::searchScalarClosest (double x, double y, double z, double & distance, double * values, int step = -1, double * size = nullptr, int qn = 0, double * qx = nullptr, double * qy = nullptr, double * qz = nullptr, bool grad = false, int dim = -1)
Definition at line 338 of file PViewData.cpp.
searchTensor()
bool PViewData::searchTensor (double x, double y, double z, double * values, int step = -1, double * size = nullptr, int qn = 0, double * qx = nullptr, double * qy = nullptr, double * qz = nullptr, bool grad = false, int dim = -1)
Definition at line 402 of file PViewData.cpp.
Referenced by searchTensorClosest().
searchTensorClosest()
bool PViewData::searchTensorClosest (double x, double y, double z, double & distance, double * values, int step = -1, double * size = nullptr, int qn = 0, double * qx = nullptr, double * qy = nullptr, double * qz = nullptr, bool grad = false, int dim = -1)
Definition at line 418 of file PViewData.cpp.
searchVector()
bool PViewData::searchVector (double x, double y, double z, double * values, int step = -1, double * size = nullptr, int qn = 0, double * qx = nullptr, double * qy = nullptr, double * qz = nullptr, bool grad = false, int dim = -1)
Definition at line 362 of file PViewData.cpp.
Referenced by searchVectorClosest().
searchVectorClosest()
bool PViewData::searchVectorClosest (double x, double y, double z, double & distance, double * values, int step = -1, double * size = nullptr, int qn = 0, double * qx = nullptr, double * qy = nullptr, double * qz = nullptr, bool grad = false, int dim = -1)
Definition at line 378 of file PViewData.cpp.
sendToServer()
void PViewData::sendToServer (const std::string & name) virtual
Reimplemented in PViewDataGModel.
Definition at line 287 of file PViewDataIO.cpp.
Referenced by PView::sendToServer().
setBoundingBox()
virtual void PViewData::setBoundingBox (SBoundingBox3d & box) pure virtual
Implemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
Referenced by GMSH_LongituteLatitudePlugin::execute().
setDirty()
virtual void PViewData::setDirty (bool val) inline virtual
Definition at line 63 of file PViewData.h.
Referenced by adaptiveData::changeResolution(), PViewDataRemote::fillRemoteVertexArrays(), and PView::fillVertexArray().
setFileIndex()
virtual void PViewData::setFileIndex (int val) inline virtual
Definition at line 87 of file PViewData.h.
Referenced by PView::readMSH(), and PView::readPOS().
setFileName()
virtual void PViewData::setFileName (const std::string & val) inline virtual
Definition at line 75 of file PViewData.h.
Referenced by _addModelData(), PViewDataList::combineSpace(), PViewDataList::combineTime(), PViewDataGModel::combineTime(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_GaussPointsPlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_Lambda2Plugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_DiscretizationErrorPlugin::execute(), GMSH_ProbePlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_SummationPlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_DistancePlugin::execute(), GMSH_AnnotatePlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GMSH_CutParametricPlugin::execute(), GMSH_CutGridPlugin::GenerateView(), GMSH_CutBoxPlugin::GenerateView(), PView::PView(), PView::readMSH(), PView::readPCH(), GModel::readPLY(), and PView::readPOS().
setInterpolationMatrices() [1/2]
void PViewData::setInterpolationMatrices (int type, const fullMatrix< double > & coefVal, const fullMatrix< double > & expVal)
Definition at line 154 of file PViewData.cpp.
Referenced by PViewDataGModel::finalize(), and PViewDataList::setOrder2().
setInterpolationMatrices() [2/2]
void PViewData::setInterpolationMatrices (int type, const fullMatrix< double > & coefVal, const fullMatrix< double > & expVal, const fullMatrix< double > & coefGeo, const fullMatrix< double > & expGeo)
Definition at line 163 of file PViewData.cpp.
setInterpolationSchemeName()
void PViewData::setInterpolationSchemeName (std::string name) inline
Definition at line 259 of file PViewData.h.
Referenced by PViewDataGModel::finalize().
setMax()
virtual void PViewData::setMax (double max) pure virtual
Implemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
setMin()
virtual void PViewData::setMin (double min) pure virtual
Implemented in PViewDataGModel, PViewDataList, and PViewDataRemote.
setName()
virtual void PViewData::setName (const std::string & val) inline virtual
Definition at line 71 of file PViewData.h.
Referenced by _addModelData(), adaptiveData::adaptiveData(), PViewDataList::combineSpace(), PViewDataList::combineTime(), PViewDataGModel::combineTime(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_GaussPointsPlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_Lambda2Plugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_DiscretizationErrorPlugin::execute(), GMSH_ProbePlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_SummationPlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_DistancePlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_AnnotatePlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GMSH_CutParametricPlugin::execute(), PView::fillVertexArray(), GMSH_CutGridPlugin::GenerateView(), GMSH_CutBoxPlugin::GenerateView(), PView::PView(), PView::readMSH(), GModel::readPLY(), and PViewDataList::readPOS().
setNode()
void PViewData::setNode (int step, int ent, int ele, int nod, double x, double y, double z) virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 124 of file PViewData.cpp.
Referenced by GMSH_LongituteLatitudePlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_TransformPlugin::execute(), and GMSH_WarpPlugin::execute().
setValue()
void PViewData::setValue (int step, int ent, int ele, int nod, int comp, double val) virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 130 of file PViewData.cpp.
Referenced by GMSH_LongituteLatitudePlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), and fromVector().
setXY()
virtual void PViewData::setXY (std::vector< double > & x, std::vector< double > & y) inline virtual
Reimplemented in PViewDataList.
Definition at line 272 of file PViewData.h.
Referenced by PView::PView().
setXYZV()
virtual void PViewData::setXYZV (std::vector< double > & x, std::vector< double > & y, std::vector< double > & z, std::vector< double > & v) inline virtual
Reimplemented in PViewDataList.
Definition at line 275 of file PViewData.h.
Referenced by PView::PView().
skipElement()
bool PViewData::skipElement (int step, int ent, int ele, bool checkVisibility = false, int samplingRate = 1) virtual
Reimplemented in PViewDataGModel.
Definition at line 90 of file PViewData.cpp.
Referenced by addElementsInArrays(), adaptiveElements< T >::addInView(), adaptiveElements< T >::addInViewForVTK(), adaptiveElements< T >::countElmLev0(), drawGlyphs(), GMSH_IntegratePlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_LongituteLatitudePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), fromVector(), getExternalValues(), getGraphData(), PViewDataGModel::skipElement(), toVector(), writePOS(), writeSTL(), and writeTXT().
skipEntity()
virtual bool PViewData::skipEntity (int step, int ent) inline virtual
Reimplemented in PViewDataGModel.
Definition at line 206 of file PViewData.h.
Referenced by addElementsInArrays(), drawGlyphs(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), and getGraphData().
smooth()
void PViewData::smooth () virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 231 of file PViewData.cpp.
Referenced by GMSH_SmoothPlugin::execute().
tagNode()
virtual void PViewData::tagNode (int step, int ent, int ele, int nod, int tag) inline virtual
Reimplemented in PViewDataGModel.
Definition at line 148 of file PViewData.h.
Referenced by GMSH_LongituteLatitudePlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), and GMSH_ModifyComponentsPlugin::execute().
toVector()
bool PViewData::toVector (std::vector< std::vector< double > > & vec) virtual
Definition at line 217 of file PViewDataIO.cpp.
Referenced by sendToServer().
useGaussPoints()
virtual bool PViewData::useGaussPoints () inline virtual
Reimplemented in PViewDataGModel.
Definition at line 221 of file PViewData.h.
Referenced by addElementsInArrays().
writeMED()
bool PViewData::writeMED (const std::string & fileName) virtual
Reimplemented in PViewDataGModel.
Definition at line 211 of file PViewDataIO.cpp.
Referenced by PView::write().
writeMSH()
bool PViewData::writeMSH (const std::string & fileName, double version = 2.2, bool binary = false, bool saveMesh = true, bool multipleView = false, int partitionNum = -1, bool saveInterpolationMatrices = true, bool forceNodeData = false, bool forceElementData = false) virtual
Reimplemented in PViewDataGModel, and PViewDataList.
Definition at line 202 of file PViewDataIO.cpp.
Referenced by frameSolver2d::exportFrameData(), PView::write(), and PViewDataList::writeMSH().
writePOS()
bool PViewData::writePOS (const std::string & fileName, bool binary = false, bool parsed = true, bool append = false) virtual
Reimplemented in PViewDataList.
Definition at line 106 of file PViewDataIO.cpp.
Referenced by PView::write(), PViewDataList::writePOS(), and writePOS().
writeSTL()
bool PViewData::writeSTL (const std::string & fileName) virtual
Definition at line 15 of file PViewDataIO.cpp.
Referenced by PView::write().
writeTXT()
bool PViewData::writeTXT (const std::string & fileName) virtual
Definition at line 74 of file PViewDataIO.cpp.
Referenced by PView::write().
Member Data Documentation
_adaptive
adaptiveData* PViewData::_adaptive protected
Definition at line 49 of file PViewData.h.
Referenced by destroyAdaptiveData(), getAdaptiveData(), initAdaptiveData(), initAdaptiveDataLight(), saveAdaptedViewForVTK(), PViewDataList::writeMSH(), PViewDataList::writePOS(), writePOS(), and ~PViewData().
_dirty
bool PViewData::_dirty private
Definition at line 32 of file PViewData.h.
Referenced by finalize(), getDirty(), and setDirty().
_fileIndex
int PViewData::_fileIndex private
Definition at line 39 of file PViewData.h.
Referenced by getFileIndex(), and setFileIndex().
_fileName
std::string PViewData::_fileName private
Definition at line 36 of file PViewData.h.
Referenced by getFileName(), and setFileName().
_fileNames
std::set<std::string> PViewData::_fileNames private
Definition at line 37 of file PViewData.h.
Referenced by hasFileName(), and setFileName().
_interpolation
interpolationMatrices PViewData::_interpolation protected
Definition at line 51 of file PViewData.h.
Referenced by PViewDataList::combineSpace(), PViewDataList::combineTime(), PViewDataGModel::combineTime(), deleteInterpolationMatrices(), getInterpolationMatrices(), haveInterpolationMatrices(), initAdaptiveData(), initAdaptiveDataLight(), setInterpolationMatrices(), PViewDataList::writeMSH(), PViewDataGModel::writeMSH(), and ~PViewData().
_interpolationSchemeName
std::string PViewData::_interpolationSchemeName protected
Definition at line 55 of file PViewData.h.
Referenced by getInterpolationSchemeName(), and setInterpolationSchemeName().
_interpolationSchemes
std::map< std::string, interpolationMatrices > PViewData::_interpolationSchemes static protected
Definition at line 53 of file PViewData.h.
Referenced by addMatrixToInterpolationScheme(), PViewDataGModel::finalize(), getSizeInterpolationScheme(), removeAllInterpolationSchemes(), and removeInterpolationScheme().
_kdtree
SPoint3KDTree* PViewData::_kdtree private
Definition at line 45 of file PViewData.h.
Referenced by findClosestNode(), and ~PViewData().
_name
std::string PViewData::_name private
Definition at line 34 of file PViewData.h.
Referenced by findClosestNode(), getName(), searchScalar(), searchTensor(), searchVector(), and setName().
_octree
OctreePost* PViewData::_octree private
Definition at line 41 of file PViewData.h.
Referenced by searchScalar(), searchTensor(), searchVector(), and ~PViewData().
_pc
SPoint3Cloud PViewData::_pc private
Definition at line 43 of file PViewData.h.
Referenced by findClosestNode().
_pc2kdtree
SPoint3CloudAdaptor<SPoint3Cloud> PViewData::_pc2kdtree private
Definition at line 44 of file PViewData.h.
Referenced by findClosestNode().
The documentation for this class was generated from the following files:
src/post/PViewData.h
src/post/PViewData.cpp
src/post/PViewDataIO.cpp