gmsh-TingyuanDoc: onelab::localClient Class Reference
onelab::localClient Class Reference
#include <onelab.h>
Public Member Functions
localClient (const std::string &name)
virtual ~localClient ()
virtual bool clear (const std::string &name="")
virtual bool set (const number &p)
virtual bool set (const string &p)
virtual bool get (std::vector< number > &ps, const std::string &name="")
virtual bool get (std::vector< string > &ps, const std::string &name="")
virtual bool setAndAppendChoices (const number &p)
virtual bool setAndAppendChoices (const string &p)
virtual bool getWithoutChoices (std::vector< number > &ps, const std::string &name="")
virtual bool getWithoutChoices (std::vector< string > &ps, const std::string &name="")
Public Member Functions inherited from onelab::client
client (const std::string &name)
virtual ~client ()
std::string getName ()
void setId (int id)
int getId ()
void setIndex (int index)
int getIndex ()
virtual bool run ()
virtual bool isNetworkClient ()
virtual bool kill ()
virtual void sendInfo (const std::string &msg)
virtual void sendWarning (const std::string &msg)
virtual void sendError (const std::string &msg)
virtual void sendProgress (const std::string &msg)
virtual void sendMergeFileRequest (const std::string &msg)
virtual void sendOpenProjectRequest (const std::string &msg)
virtual void sendParseStringRequest (const std::string &msg)
virtual void sendVertexArray (const std::string &msg)
std::vector< std::string > toChar ()
bool fromChar (const std::vector< std::string > &msg)
bool toFile (FILE *fp)
bool fromFile (FILE *fp)
Private Member Functions
template<class T >
bool _set (const T &p)
template<class T >
bool _get (std::vector< T > &ps, const std::string &name="")
Additional Inherited Members
Protected Attributes inherited from onelab::client
std::string _name
int _id
int _index
Detailed Description
Definition at line 1393 of file onelab.h.
Constructor & Destructor Documentation
localClient()
onelab::localClient::localClient (const std::string & name) inline
Definition at line 1408 of file onelab.h.
~localClient()
virtual onelab::localClient::~localClient () inline virtual
Definition at line 1412 of file onelab.h.
Member Function Documentation
_get()
template<class T > bool onelab::localClient::_get (std::vector< T > & ps, const std::string & name = "") inline private
Definition at line 1401 of file onelab.h.
Referenced by get(), getWithoutChoices(), and setAndAppendChoices().
_set()
template<class T > bool onelab::localClient::_set (const T & p) inline private
Definition at line 1395 of file onelab.h.
Referenced by set(), and setAndAppendChoices().
clear()
virtual bool onelab::localClient::clear (const std::string & name = "") inline virtual
Implements onelab::client.
Definition at line 1413 of file onelab.h.
get() [1/2]
virtual bool onelab::localClient::get (std::vector< number > & ps, const std::string & name = "") inline virtual
Implements onelab::client.
Definition at line 1420 of file onelab.h.
get() [2/2]
virtual bool onelab::localClient::get (std::vector< string > & ps, const std::string & name = "") inline virtual
Implements onelab::client.
Definition at line 1424 of file onelab.h.
getWithoutChoices() [1/2]
virtual bool onelab::localClient::getWithoutChoices (std::vector< number > & ps, const std::string & name = "") inline virtual
Implements onelab::client.
Definition at line 1452 of file onelab.h.
getWithoutChoices() [2/2]
virtual bool onelab::localClient::getWithoutChoices (std::vector< string > & ps, const std::string & name = "") inline virtual
Implements onelab::client.
Definition at line 1460 of file onelab.h.
set() [1/2]
virtual bool onelab::localClient::set (const number & p) inline virtual
Implements onelab::client.
Definition at line 1418 of file onelab.h.
set() [2/2]
virtual bool onelab::localClient::set (const string & p) inline virtual
Implements onelab::client.
Definition at line 1419 of file onelab.h.
setAndAppendChoices() [1/2]
virtual bool onelab::localClient::setAndAppendChoices (const number & p) inline virtual
Implements onelab::client.
Definition at line 1428 of file onelab.h.
setAndAppendChoices() [2/2]
virtual bool onelab::localClient::setAndAppendChoices (const string & p) inline virtual
Implements onelab::client.
Definition at line 1440 of file onelab.h.
The documentation for this class was generated from the following file:
src/common/onelab.h