gmsh-TingyuanDoc: blyr_manager Class Reference
blyr_manager Class Reference
Public Member Functions
blyr_manager (GRegion *gr, std::vector< GFace * > &bls, double t)
blyr_ridge * getRidge (GEdge *ge)
void classify_ridges ()
void classify_corners ()
void add_fan (const blyr_mvertex &v)
void add_external_corner (const blyr_mvertex &v)
void add_one_normal (const blyr_mvertex &v)
void extrude_vertex_on_both_surfaces_of_a_ridge (const blyr_mvertex &v, blyr_ridge *ridge, std::vector< blyr_mvertex > &new_vertices)
void extrude_ridges_on_faces ()
void extrude_vertices_on_faces ()
void extrude_one_external ()
void extrude_vertices_basic ()
void extrude_vertices ()
void extrude_vertices_on_edges ()
void extrude_triangles ()
void extrude_ridges ()
void extrude_external_corners ()
double blyr_thickness (double x, double y, double z)
Private Attributes
double _thickness
double _threshold_angle
GRegion * _gr
std::vector< GFace * > _faces
std::vector< blyr_ridge > _ridges
std::set< blyr_mvertex > _vertices
Detailed Description
Definition at line 167 of file meshGRegionBoundaryLayer.cpp.
Constructor & Destructor Documentation
blyr_manager()
blyr_manager::blyr_manager (GRegion * gr, std::vector< GFace * > & bls, double t) inline
Definition at line 189 of file meshGRegionBoundaryLayer.cpp.
Member Function Documentation
add_external_corner()
void blyr_manager::add_external_corner (const blyr_mvertex & v) inline
Definition at line 417 of file meshGRegionBoundaryLayer.cpp.
add_fan()
void blyr_manager::add_fan (const blyr_mvertex & v) inline
Definition at line 366 of file meshGRegionBoundaryLayer.cpp.
add_one_normal()
void blyr_manager::add_one_normal (const blyr_mvertex & v) inline
Definition at line 542 of file meshGRegionBoundaryLayer.cpp.
Referenced by extrude_vertices(), and extrude_vertices_basic().
blyr_thickness()
double blyr_manager::blyr_thickness (double x, double y, double z) inline
Definition at line 1260 of file meshGRegionBoundaryLayer.cpp.
Referenced by add_external_corner(), add_fan(), add_one_normal(), extrude_one_external(), extrude_vertex_on_both_surfaces_of_a_ridge(), and extrude_vertices_on_edges().
classify_corners()
void blyr_manager::classify_corners () inline
Definition at line 360 of file meshGRegionBoundaryLayer.cpp.
classify_ridges()
void blyr_manager::classify_ridges () inline
Definition at line 290 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
extrude_external_corners()
void blyr_manager::extrude_external_corners () inline
TEMPORARY --> SHOULD BE A TET BUT I PREFER THAT FOR NOW FOR VIZU
Definition at line 1244 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
extrude_one_external()
void blyr_manager::extrude_one_external () inline
Definition at line 664 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
extrude_ridges()
void blyr_manager::extrude_ridges () inline
Definition at line 1176 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
extrude_ridges_on_faces()
void blyr_manager::extrude_ridges_on_faces () inline
Definition at line 605 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
extrude_triangles()
void blyr_manager::extrude_triangles () inline
Definition at line 1155 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
extrude_vertex_on_both_surfaces_of_a_ridge()
void blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge (const blyr_mvertex & v, blyr_ridge * ridge, std::vector< blyr_mvertex > & new_vertices) inline
Definition at line 554 of file meshGRegionBoundaryLayer.cpp.
Referenced by extrude_vertices_on_faces().
extrude_vertices()
void blyr_manager::extrude_vertices () inline
Definition at line 799 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
extrude_vertices_basic()
void blyr_manager::extrude_vertices_basic () inline
Definition at line 791 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
extrude_vertices_on_edges()
void blyr_manager::extrude_vertices_on_edges () inline
Definition at line 895 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
extrude_vertices_on_faces()
void blyr_manager::extrude_vertices_on_faces () inline
Definition at line 632 of file meshGRegionBoundaryLayer.cpp.
Referenced by createBoundaryLayerOneLayer().
getRidge()
blyr_ridge* blyr_manager::getRidge (GEdge * ge) inline
Definition at line 281 of file meshGRegionBoundaryLayer.cpp.
Referenced by extrude_one_external(), extrude_vertices(), extrude_vertices_on_edges(), and extrude_vertices_on_faces().
Member Data Documentation
_faces
std::vector<GFace *> blyr_manager::_faces private
Definition at line 180 of file meshGRegionBoundaryLayer.cpp.
Referenced by extrude_triangles(), and extrude_vertices_on_edges().
_gr
GRegion* blyr_manager::_gr private
Definition at line 177 of file meshGRegionBoundaryLayer.cpp.
Referenced by add_external_corner(), add_fan(), add_one_normal(), blyr_manager(), extrude_external_corners(), extrude_ridges(), extrude_triangles(), extrude_vertex_on_both_surfaces_of_a_ridge(), and extrude_vertices_on_edges().
_ridges
std::vector<blyr_ridge> blyr_manager::_ridges private
Definition at line 183 of file meshGRegionBoundaryLayer.cpp.
Referenced by add_fan(), blyr_manager(), classify_ridges(), extrude_ridges(), extrude_ridges_on_faces(), and getRidge().
_thickness
double blyr_manager::_thickness private
Definition at line 171 of file meshGRegionBoundaryLayer.cpp.
Referenced by blyr_thickness().
_threshold_angle
double blyr_manager::_threshold_angle private
Definition at line 174 of file meshGRegionBoundaryLayer.cpp.
Referenced by blyr_manager(), and classify_ridges().
_vertices
std::set<blyr_mvertex> blyr_manager::_vertices private
Definition at line 186 of file meshGRegionBoundaryLayer.cpp.
Referenced by blyr_manager(), classify_corners(), classify_ridges(), extrude_external_corners(), extrude_one_external(), extrude_ridges(), extrude_ridges_on_faces(), extrude_triangles(), extrude_vertices(), extrude_vertices_basic(), extrude_vertices_on_edges(), and extrude_vertices_on_faces().
The documentation for this class was generated from the following file:
src/mesh/meshGRegionBoundaryLayer.cpp