gmsh-TingyuanDoc: MTetrahedron10 Class Reference
MTetrahedron10 Class Reference
#include <MTetrahedron.h>
Public Member Functions
MTetrahedron10 (MVertex *v0, MVertex *v1, MVertex *v2, MVertex *v3, MVertex *v4, MVertex *v5, MVertex *v6, MVertex *v7, MVertex *v8, MVertex *v9, int num=0, int part=0)
MTetrahedron10 (const std::vector< MVertex * > &v, int num=0, int part=0)
~MTetrahedron10 ()
virtual int getPolynomialOrder () const
virtual std::size_t getNumVertices () const
virtual MVertex * getVertex (int num)
virtual const MVertex * getVertex (int num) const
virtual void setVertex (int num, MVertex *v)
virtual MVertex * getVertexUNV (int num)
virtual MVertex * getVertexBDF (int num)
virtual MVertex * getVertexVTK (int num)
virtual MVertex * getVertexDIFF (int num)
virtual MVertex * getVertexINP (int num)
virtual MVertex * getVertexKEY (int num)
virtual MVertex * getVertexRAD (int num)
virtual int getNumEdgeVertices () const
virtual void getEdgeRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual int getNumEdgesRep (bool curved)
virtual void getFaceRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual int getNumFacesRep (bool curved)
virtual void getEdgeVertices (const int num, std::vector< MVertex * > &v) const
virtual void getFaceVertices (const int num, std::vector< MVertex * > &v) const
virtual int getTypeForMSH () const
virtual int getTypeForUNV () const
virtual int getTypeForVTK () const
virtual const char * getStringForPOS () const
virtual const char * getStringForBDF () const
virtual const char * getStringForDIFF () const
virtual const char * getStringForINP () const
virtual const char * getStringForKEY () const
virtual const char * getStringForRAD () const
virtual const char * getStringForTOCHNOG () const
virtual void reverse ()
virtual void getNode (int num, double &u, double &v, double &w) const
void xyz2uvw (double xyz[3], double uvw[3]) const
Public Member Functions inherited from MTetrahedron
MTetrahedron (MVertex *v0, MVertex *v1, MVertex *v2, MVertex *v3, int num=0, int part=0)
MTetrahedron (const std::vector< MVertex * > &v, int num=0, int part=0)
~MTetrahedron ()
virtual int getDim () const
virtual int getNumEdges () const
virtual MEdge getEdge (int num) const
virtual int numEdge2numVertex (int numEdge, int numVert) const
virtual int getNumFaces ()
virtual MFace getFace (int num) const
virtual bool getFaceInfo (const MFace &face, int &ithFace, int &sign, int &rot) const
virtual int getType () const
void getMat (double mat[3][3]) const
virtual double getVolume ()
virtual int getVolumeSign ()
virtual double gammaShapeMeasure ()
virtual double getInnerRadius ()
virtual double getOuterRadius ()
virtual double etaShapeMeasure ()
virtual SPoint3 barycenterUVW () const
virtual bool isInside (double u, double v, double w) const
virtual void getIntegrationPoints (int pOrder, int *npts, IntPt **pts)
virtual SPoint3 circumcenter ()
virtual int numCommonNodesInDualGraph (const MElement *const other) const
virtual MEdge getEdgeSolin (int num)
virtual MFace getFaceSolin (int num)
Public Member Functions inherited from MElement
MElement (std::size_t num=0, int part=0)
virtual ~MElement ()
double getTolerance () const
virtual std::size_t getNum () const
void forceNum (std::size_t num)
virtual bool getIsAssimilatedSerendipity () const
virtual bool getIsOnlySerendipity () const
virtual int getPartition () const
virtual void setPartition (int num)
virtual char getVisibility () const
virtual void setVisibility (char val)
void getVertices (std::vector< MVertex * > &verts)
virtual void getVertexInfo (const MVertex *vertex, int &ithVertex) const
virtual MVertex * getVertexMATLAB (int num)
virtual MVertex * getVertexTOCHNOG (int num)
virtual MVertex * getVertexNEU (int num)
virtual int getNumFaceVertices () const
virtual int getNumVolumeVertices () const
std::size_t getNumPrimaryVertices () const
virtual MEdgeN getHighOrderEdge (int num, int sign)
MEdgeN getHighOrderEdge (const MEdge &edge)
virtual bool getEdgeInfo (const MEdge &edge, int &ithEdge, int &sign) const
virtual MFaceN getHighOrderFace (int num, int sign, int rot)
MFaceN getHighOrderFace (const MFace &face)
virtual MElement * getParent () const
virtual void setParent (MElement *p, bool owner=false)
virtual void updateParent (GModel *gm)
virtual int getNumChildren () const
virtual MElement * getChild (int i) const
virtual bool ownsParent () const
virtual const MElement * getBaseElement () const
virtual MElement * getBaseElement ()
virtual MElement * getDomain (int i) const
virtual void setDomain (MElement *e, int i)
virtual double maxEdge ()
virtual double minEdge ()
double maxDistToStraight () const
double skewness ()
double minSICNShapeMeasure ()
double minSIGEShapeMeasure ()
double distoShapeMeasure ()
double minIsotropyMeasure (bool knownValid=false, bool reversedOk=false)
double minScaledJacobian (bool knownValid=false, bool reversedOk=false)
virtual double angleShapeMeasure ()
virtual void scaledJacRange (double &jmin, double &jmax, GEntity *ge=nullptr) const
virtual void idealJacRange (double &jmin, double &jmax, GEntity *ge=nullptr)
virtual void signedInvCondNumRange (double &iCNMin, double &iCNMax, GEntity *ge=nullptr)
virtual void signedInvGradErrorRange (double &minSIGE, double &maxSIGE)
virtual SPoint3 barycenter (bool primary=false) const
virtual SPoint3 fastBarycenter (bool primary=false) const
virtual SPoint3 barycenter_infty () const
virtual bool setVolumePositive ()
int getValidity ()
virtual std::string getInfoString (bool multline)
virtual const nodalBasis * getFunctionSpace (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getFuncSpaceData (int order=-1, bool serendip=false) const
virtual const JacobianBasis * getJacobianFuncSpace (int orderElement=-1) const
virtual const FuncSpaceData getJacobianFuncSpaceData (int orderElement=-1) const
virtual void getShapeFunctions (double u, double v, double w, double s[], int order=-1) const
virtual void getGradShapeFunctions (double u, double v, double w, double s[][3], int order=-1) const
virtual void getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order=-1) const
virtual void getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order=-1) const
virtual double getJacobian (const fullMatrix< double > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double *jac) const
virtual double getJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobian (double u, double v, double w, fullMatrix< double > &j) const
virtual double getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobianDeterminant (double u, double v, double w) const
void getSignedJacobian (fullVector< double > &jacobian, int o=-1) const
void getNodesCoord (fullMatrix< double > &nodesXYZ) const
void getNodesCoordNonSerendip (fullMatrix< double > &nodesXYZ) const
bezierCoeff * getBezierVerticesCoord () const
virtual std::size_t getNumShapeFunctions () const
virtual std::size_t getNumPrimaryShapeFunctions () const
virtual const MVertex * getShapeFunctionNode (int i) const
virtual MVertex * getShapeFunctionNode (int i)
virtual double getEigenvaluesMetric (double u, double v, double w, double values[3]) const
virtual void pnt (double u, double v, double w, SPoint3 &p) const
virtual void pnt (double u, double v, double w, double *p) const
virtual void pnt (const std::vector< double > &sf, SPoint3 &p) const
virtual void primaryPnt (double u, double v, double w, SPoint3 &p)
virtual void movePointFromParentSpaceToElementSpace (double &u, double &v, double &w) const
virtual void movePointFromElementSpaceToParentSpace (double &u, double &v, double &w) const
double interpolate (double val[], double u, double v, double w, int stride=1, int order=-1)
void interpolateGrad (double val[], double u, double v, double w, double f[], int stride=1, double invjac[3][3]=nullptr, int order=-1)
void interpolateCurl (double val[], double u, double v, double w, double f[], int stride=3, int order=-1)
double interpolateDiv (double val[], double u, double v, double w, int stride=3, int order=-1)
double integrate (double val[], int pOrder, int stride=1, int order=-1)
double integrateCirc (double val[], int edge, int pOrder, int order=-1)
double integrateFlux (double val[], int face, int pOrder, int order=-1)
virtual void writeMSH2 (FILE *fp, double version=1.0, bool binary=false, int num=0, int elementary=1, int physical=1, int parentNum=0, int dom1Num=0, int dom2Num=0, std::vector< short > *ghosts=nullptr)
virtual void writeMSH3 (FILE *fp, bool binary=false, int elementary=1, std::vector< short > *ghosts=nullptr)
virtual void writePOS (FILE *fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor=1.0, int elementary=1)
virtual void writeSTL (FILE *fp, bool binary=false, double scalingFactor=1.0)
virtual void writeX3D (FILE *fp, double scalingFactor=1.0)
virtual void writeVRML (FILE *fp)
virtual void writePLY2 (FILE *fp)
virtual void writeUNV (FILE *fp, int num=0, int elementary=1, int physical=1)
virtual void writeVTK (FILE *fp, bool binary=false, bool bigEndian=false)
virtual void writeMATLAB (FILE *fp, int filetype, int elementary=0, int physical=0, bool binary=false)
virtual void writeTOCHNOG (FILE *fp, int num)
virtual void writeMESH (FILE *fp, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeNEU (FILE *fp, unsigned gambitType, int adjust, int phys=0)
virtual void writeIR3 (FILE *fp, int elementTagType, int num, int elementary, int physical)
virtual void writeBDF (FILE *fp, int format=0, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeDIFF (FILE *fp, int num, bool binary=false, int physical_property=1)
virtual void writeINP (FILE *fp, int num)
virtual void writeKEY (FILE *fp, int pid, int num)
virtual void writeRAD (FILE *fp, int num)
virtual void writeSU2 (FILE *fp, int num)
std::string getName ()
virtual std::size_t getNumVerticesForMSH ()
virtual void getVerticesIdForMSH (std::vector< int > &verts)
virtual MElement * copy (std::map< int, MVertex * > &vertexMap, std::map< MElement *, MElement * > &newParents, std::map< MElement *, MElement * > &newDomains)
Protected Attributes
MVertex * _vs [6]
Protected Attributes inherited from MTetrahedron
MVertex * _v [4]
Additional Inherited Members
Static Public Member Functions inherited from MTetrahedron
static int edges_tetra (const int edge, const int vert)
static int faces_tetra (const int face, const int vert)
static int faces2edge_tetra (const int face, const int edge)
Static Public Member Functions inherited from MElement
static unsigned int getInfoMSH (const int typeMSH, const char **const name=nullptr)
Protected Member Functions inherited from MTetrahedron
void _getEdgeVertices (const int num, std::vector< MVertex * > &v) const
void _getFaceVertices (const int num, std::vector< MVertex * > &v) const
Protected Member Functions inherited from MElement
void _getEdgeRep (MVertex *v0, MVertex *v1, double *x, double *y, double *z, SVector3 *n, int faceIndex=-1)
void _getFaceRep (MVertex *v0, MVertex *v1, MVertex *v2, double *x, double *y, double *z, SVector3 *n)
Static Protected Member Functions inherited from MElement
static bool _getFaceInfo (const MFace &face, const MFace &other, int &sign, int &rot)
Static Protected Attributes inherited from MElement
static double _isInsideTolerance
Detailed Description
Definition at line 233 of file MTetrahedron.h.
Constructor & Destructor Documentation
MTetrahedron10() [1/2]
MTetrahedron10::MTetrahedron10 (MVertex * v0, MVertex * v1, MVertex * v2, MVertex * v3, MVertex * v4, MVertex * v5, MVertex * v6, MVertex * v7, MVertex * v8, MVertex * v9, int num = 0, int part = 0) inline
Definition at line 238 of file MTetrahedron.h.
MTetrahedron10() [2/2]
MTetrahedron10::MTetrahedron10 (const std::vector< MVertex * > & v, int num = 0, int part = 0) inline
Definition at line 251 of file MTetrahedron.h.
~MTetrahedron10()
MTetrahedron10::~MTetrahedron10 () inline
Definition at line 257 of file MTetrahedron.h.
Member Function Documentation
getEdgeRep()
void MTetrahedron10::getEdgeRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Reimplemented from MTetrahedron.
Definition at line 186 of file MTetrahedron.cpp.
getEdgeVertices()
virtual void MTetrahedron10::getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MTetrahedron.
Definition at line 301 of file MTetrahedron.h.
getFaceRep()
void MTetrahedron10::getFaceRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Reimplemented from MTetrahedron.
Definition at line 323 of file MTetrahedron.cpp.
getFaceVertices()
virtual void MTetrahedron10::getFaceVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MTetrahedron.
Definition at line 307 of file MTetrahedron.h.
getNode()
virtual void MTetrahedron10::getNode (int num, double & u, double & v, double & w) const inline virtual
Reimplemented from MTetrahedron.
Definition at line 342 of file MTetrahedron.h.
getNumEdgesRep()
int MTetrahedron10::getNumEdgesRep (bool curved) virtual
Reimplemented from MTetrahedron.
Definition at line 141 of file MTetrahedron.cpp.
getNumEdgeVertices()
virtual int MTetrahedron10::getNumEdgeVertices () const inline virtual
Reimplemented from MElement.
Definition at line 294 of file MTetrahedron.h.
getNumFacesRep()
int MTetrahedron10::getNumFacesRep (bool curved) virtual
Reimplemented from MTetrahedron.
Definition at line 209 of file MTetrahedron.cpp.
getNumVertices()
virtual std::size_t MTetrahedron10::getNumVertices () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 259 of file MTetrahedron.h.
getPolynomialOrder()
virtual int MTetrahedron10::getPolynomialOrder () const inline virtual
Reimplemented from MElement.
Definition at line 258 of file MTetrahedron.h.
getStringForBDF()
virtual const char* MTetrahedron10::getStringForBDF () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 323 of file MTetrahedron.h.
getStringForDIFF()
virtual const char* MTetrahedron10::getStringForDIFF () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 324 of file MTetrahedron.h.
getStringForINP()
virtual const char* MTetrahedron10::getStringForINP () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 325 of file MTetrahedron.h.
getStringForKEY()
virtual const char* MTetrahedron10::getStringForKEY () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 326 of file MTetrahedron.h.
getStringForPOS()
virtual const char* MTetrahedron10::getStringForPOS () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 322 of file MTetrahedron.h.
getStringForRAD()
virtual const char* MTetrahedron10::getStringForRAD () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 327 of file MTetrahedron.h.
getStringForTOCHNOG()
virtual const char* MTetrahedron10::getStringForTOCHNOG () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 328 of file MTetrahedron.h.
getTypeForMSH()
virtual int MTetrahedron10::getTypeForMSH () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 316 of file MTetrahedron.h.
getTypeForUNV()
virtual int MTetrahedron10::getTypeForUNV () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 317 of file MTetrahedron.h.
getTypeForVTK()
virtual int MTetrahedron10::getTypeForVTK () const inline virtual
Reimplemented from MTetrahedron.
Definition at line 321 of file MTetrahedron.h.
getVertex() [1/2]
virtual MVertex* MTetrahedron10::getVertex (int num) inline virtual
Reimplemented from MTetrahedron.
Definition at line 260 of file MTetrahedron.h.
Referenced by getVertexBDF(), getVertexUNV(), and getVertexVTK().
getVertex() [2/2]
virtual const MVertex* MTetrahedron10::getVertex (int num) const inline virtual
Reimplemented from MTetrahedron.
Definition at line 264 of file MTetrahedron.h.
getVertexBDF()
virtual MVertex* MTetrahedron10::getVertexBDF (int num) inline virtual
Reimplemented from MElement.
Definition at line 280 of file MTetrahedron.h.
Referenced by getVertexDIFF(), getVertexINP(), getVertexKEY(), and getVertexRAD().
getVertexDIFF()
virtual MVertex* MTetrahedron10::getVertexDIFF (int num) inline virtual
Reimplemented from MElement.
Definition at line 290 of file MTetrahedron.h.
getVertexINP()
virtual MVertex* MTetrahedron10::getVertexINP (int num) inline virtual
Reimplemented from MElement.
Definition at line 291 of file MTetrahedron.h.
getVertexKEY()
virtual MVertex* MTetrahedron10::getVertexKEY (int num) inline virtual
Reimplemented from MElement.
Definition at line 292 of file MTetrahedron.h.
getVertexRAD()
virtual MVertex* MTetrahedron10::getVertexRAD (int num) inline virtual
Reimplemented from MElement.
Definition at line 293 of file MTetrahedron.h.
getVertexUNV()
virtual MVertex* MTetrahedron10::getVertexUNV (int num) inline virtual
Reimplemented from MElement.
Definition at line 275 of file MTetrahedron.h.
getVertexVTK()
virtual MVertex* MTetrahedron10::getVertexVTK (int num) inline virtual
Reimplemented from MElement.
Definition at line 285 of file MTetrahedron.h.
reverse()
virtual void MTetrahedron10::reverse () inline virtual
Reimplemented from MTetrahedron.
Definition at line 329 of file MTetrahedron.h.
setVertex()
virtual void MTetrahedron10::setVertex (int num, MVertex * v) inline virtual
Reimplemented from MTetrahedron.
Definition at line 268 of file MTetrahedron.h.
xyz2uvw()
void MTetrahedron10::xyz2uvw (double xyz[3], double uvw[3]) const inline virtual
Reimplemented from MTetrahedron.
Definition at line 347 of file MTetrahedron.h.
Member Data Documentation
_vs
MVertex* MTetrahedron10::_vs[6] protected
Definition at line 235 of file MTetrahedron.h.
Referenced by getEdgeVertices(), getFaceVertices(), getVertex(), MTetrahedron10(), reverse(), and setVertex().
The documentation for this class was generated from the following files:
src/geo/MTetrahedron.h
src/geo/MTetrahedron.cpp