gmsh-TingyuanDoc: GEntity Class Reference
GEntity Class Reference
#include <GEntity.h>
Public Types
enum ModelType {
UnknownModel, GmshModel, OpenCascadeModel, AcisModel,
ParasolidModel
}
enum GeomType {
Unknown, Point, BoundaryLayerPoint, Line,
Circle, Ellipse, Conic, Parabola,
Hyperbola, TrimmedCurve, OffsetCurve, BSpline,
Bezier, ParametricCurve, BoundaryLayerCurve, DiscreteCurve,
Plane, Nurb, Cylinder, Sphere,
Cone, Torus, RuledSurface, ParametricSurface,
BSplineSurface, BezierSurface, SurfaceOfRevolution, BoundaryLayerSurface,
DiscreteSurface, DiscreteDiskSurface, Volume, DiscreteVolume,
PartitionPoint, PartitionCurve, PartitionSurface, PartitionVolume,
GhostCurve, GhostSurface, GhostVolume
}
enum MeshGenerationStatus { PENDING, DONE, FAILED }
Public Member Functions
void addVerticesInSet (std::set< MVertex * > &, bool closure) const
virtual std::string getTypeString ()
GEntity (GModel *m, int t)
virtual ~GEntity ()
virtual void mesh (bool verbose)
virtual void deleteMesh ()
void deleteVertexArrays ()
virtual int dim () const
virtual GEntity * getParentEntity ()
virtual std::list< GRegion * > regions () const
virtual std::vector< GFace * > faces () const
virtual std::vector< GEdge * > const & edges () const
virtual std::vector< GVertex * > vertices () const
virtual bool isOrphan ()
std::vector< GRegion * > bindingsGetRegions ()
std::vector< GFace * > bindingsGetFaces ()
std::vector< GEdge * > bindingsGetEdges () const
std::vector< GVertex * > bindingsGetVertices ()
virtual GeomType geomType () const
virtual bool continuous (int dim) const
virtual bool periodic (int dim) const
virtual double period (int dim) const
virtual bool degenerate (int dim) const
virtual bool haveParametrization ()
virtual bool isFullyDiscrete ()
virtual Range< double > parBounds (int i) const
virtual double tolerance () const
virtual bool containsPoint (const SPoint3 &pt) const
virtual ModelType getNativeType () const
virtual void * getNativePtr () const
virtual int getNativeInt () const
GModel * model () const
int tag () const
void setTag (int tag)
virtual void addPhysicalEntity (int physicalTag)
virtual std::vector< int > getPhysicalEntities ()
GEntity * getMeshMaster () const
void setMeshMaster (GEntity *)
void setMeshMaster (GEntity *, const std::vector< double > &, bool updateCorrespondingVertices=true)
void updateCorrespondingVertices ()
void copyMasterCoordinates ()
virtual void alignElementsWithMaster ()
virtual SBoundingBox3d bounds (bool fast=false)
virtual SOrientedBoundingBox getOBB ()
virtual char getVisibility ()
virtual void setVisibility (char val, bool recursive=false)
virtual char getSelection ()
virtual void setSelection (char val)
virtual unsigned int getColor ()
virtual void setColor (unsigned color, bool recursive=false)
virtual bool useColor ()
virtual std::string getInfoString (bool additional=true, bool multiline=false)
virtual std::string getAdditionalInfoString (bool multline=false)
virtual void resetMeshAttributes ()
virtual double getMeshSize () const
virtual double getMeshSizeFactor () const
virtual void getElementTypes (std::vector< int > &types) const
virtual std::size_t getNumMeshElements () const
virtual std::size_t getNumMeshElementsByType (const int familyType) const
virtual std::size_t getNumMeshParentElements ()
virtual void getNumMeshElements (unsigned *const c) const
virtual MElement *const * getStartElementType (int type) const
virtual MElement * getMeshElement (std::size_t index) const
virtual MElement * getMeshElementByType (const int familyType, const std::size_t index) const
bool getAllElementsVisible ()
void setAllElementsVisible (bool val)
std::size_t getNumMeshVertices ()
MVertex * getMeshVertex (std::size_t index)
void addMeshVertex (MVertex *v)
void removeMeshVertex (MVertex *v)
virtual void addElement (int type, MElement *e)
virtual void removeElement (int type, MElement *e)
virtual void removeElements (int type)
virtual void relocateMeshVertices ()
GVertex * cast2Vertex ()
GEdge * cast2Edge ()
GFace * cast2Face ()
GRegion * cast2Region ()
virtual bool reorder (const int elementType, const std::vector< std::size_t > &ordering)
Public Attributes
std::vector< MVertex * > mesh_vertices
std::vector< GEntity * > compound
std::map< GVertex *, GVertex * > vertexCounterparts
std::vector< int > physicals
VertexArray * va_lines
VertexArray * va_triangles
std::set< MElement * > curvedBLElements
std::vector< double > affineTransform
std::map< MVertex *, MVertex * > correspondingVertices
std::map< MVertex *, MVertex * > correspondingHighOrderVertices
Protected Attributes
SOrientedBoundingBox * _obb
Private Attributes
GModel * _model
int _tag
GEntity * _meshMaster
char _visible
char _selection
char _allElementsVisible
unsigned int _color
Detailed Description
Definition at line 31 of file GEntity.h.
Member Enumeration Documentation
GeomType
enum GEntity::GeomType
Enumerator
Unknown
Point
BoundaryLayerPoint
Line
Circle
Ellipse
Conic
Parabola
Hyperbola
TrimmedCurve
OffsetCurve
BSpline
Bezier
ParametricCurve
BoundaryLayerCurve
DiscreteCurve
Plane
Nurb
Cylinder
Sphere
Cone
Torus
RuledSurface
ParametricSurface
BSplineSurface
BezierSurface
SurfaceOfRevolution
BoundaryLayerSurface
DiscreteSurface
DiscreteDiskSurface
Volume
DiscreteVolume
PartitionPoint
PartitionCurve
PartitionSurface
PartitionVolume
GhostCurve
GhostSurface
GhostVolume
Definition at line 88 of file GEntity.h.
MeshGenerationStatus
enum GEntity::MeshGenerationStatus
Enumerator
PENDING
DONE
FAILED
Definition at line 130 of file GEntity.h.
ModelType
enum GEntity::ModelType
Enumerator
UnknownModel
GmshModel
OpenCascadeModel
AcisModel
ParasolidModel
Definition at line 79 of file GEntity.h.
Constructor & Destructor Documentation
GEntity()
GEntity::GEntity (GModel * m, int t)
Definition at line 19 of file GEntity.cpp.
~GEntity()
virtual GEntity::~GEntity () inline virtual
Definition at line 184 of file GEntity.h.
Member Function Documentation
addElement()
virtual void GEntity::addElement (int type, MElement * e) inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 387 of file GEntity.h.
Referenced by readMSH4Elements().
addMeshVertex()
void GEntity::addMeshVertex (MVertex * v) inline
Definition at line 382 of file GEntity.h.
Referenced by insertVerticesInRegion(), readMSH4Nodes(), and subdivide_pyramid().
addPhysicalEntity()
virtual void GEntity::addPhysicalEntity (int physicalTag) inline virtual
Definition at line 284 of file GEntity.h.
Referenced by readMSH4Physicals().
addVerticesInSet()
void GEntity::addVerticesInSet (std::set< MVertex * > & vtcs, bool closure) const
Definition at line 166 of file GEntity.cpp.
Referenced by closestVertexFinder::closestVertexFinder(), and updateCorrespondingVertices().
alignElementsWithMaster()
virtual void GEntity::alignElementsWithMaster () inline virtual
Reimplemented in GFace.
Definition at line 298 of file GEntity.h.
bindingsGetEdges()
std::vector<GEdge *> GEntity::bindingsGetEdges () const inline
Definition at line 234 of file GEntity.h.
bindingsGetFaces()
std::vector<GFace *> GEntity::bindingsGetFaces () inline
Definition at line 233 of file GEntity.h.
bindingsGetRegions()
std::vector<GRegion *> GEntity::bindingsGetRegions () inline
Definition at line 227 of file GEntity.h.
bindingsGetVertices()
std::vector<GVertex *> GEntity::bindingsGetVertices () inline
Definition at line 235 of file GEntity.h.
bounds()
virtual SBoundingBox3d GEntity::bounds (bool fast = false) inline virtual
Reimplemented in GFace, GEdge, GRegion, GVertex, and discreteFace.
Definition at line 301 of file GEntity.h.
Referenced by getBoundingBox().
cast2Edge()
GEdge * GEntity::cast2Edge ()
Definition at line 123 of file GEntity.cpp.
Referenced by closestPointFinder::closestPointFinder(), and GMSH_CurvedBndDistPlugin::execute().
cast2Face()
GFace * GEntity::cast2Face ()
Definition at line 124 of file GEntity.cpp.
cast2Region()
GRegion * GEntity::cast2Region ()
Definition at line 125 of file GEntity.cpp.
cast2Vertex()
GVertex * GEntity::cast2Vertex ()
Definition at line 122 of file GEntity.cpp.
containsPoint()
virtual bool GEntity::containsPoint (const SPoint3 & pt) const inline virtual
Reimplemented in GEdge, xyFace, and gmshFace.
Definition at line 265 of file GEntity.h.
Referenced by GFace::buildRepresentationCross().
continuous()
virtual bool GEntity::continuous (int dim) const inline virtual
Definition at line 241 of file GEntity.h.
copyMasterCoordinates()
void GEntity::copyMasterCoordinates ()
Definition at line 240 of file GEntity.cpp.
degenerate()
virtual bool GEntity::degenerate (int dim) const inline virtual
Reimplemented in xyFace, gmshFace, gmshEdge, and xyEdge.
Definition at line 248 of file GEntity.h.
Referenced by allFacesLinked(), createFaceLinks(), DuplicateCurve(), ExtrudeCurve(), meshGEdgeProcessing(), meshGEdge::operator()(), GEdgeLoop::recompute(), and recurFindLinkedFaces().
deleteMesh()
virtual void GEntity::deleteMesh () inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 190 of file GEntity.h.
Referenced by GModel::deleteMesh().
deleteVertexArrays()
void GEntity::deleteVertexArrays ()
Definition at line 27 of file GEntity.cpp.
Referenced by BarycentricRefineMesh(), deleteHighOrderVertices(), GVertex::deleteMesh(), GRegion::deleteMesh(), GEdge::deleteMesh(), GFace::deleteMesh(), initMeshGEdge::operator()(), initMeshGRegion::operator()(), setFirstOrder(), setHighOrder(), and Subdivide().
dim()
virtual int GEntity::dim () const inline virtual
Reimplemented in GFace, GEdge, GVertex, and GRegion.
Definition at line 196 of file GEntity.h.
Referenced by _associateEntityWithElementVertices(), _getAdditionalNodesOnBoundary(), _getElementary(), _getEntitiesForElementTypes(), _isModelOkForTopologicalOpti(), _relocateVertex(), _relocateVertexGolden(), _relocateVertexOfPyramid(), addElementsInArrays(), bidimMeshData::addVertex(), addVerticesInSet(), GModel::alignPeriodicBoundaries(), backgroundMesh::backgroundMesh(), BGM_MeshMetric(), BGM_MeshSizeWithoutScaling(), buildConsecutiveListOfVertices(), checkConformity(), closestPointFinder::closestPointFinder(), collapseVertex(), createSizeFieldFromExistingMesh(), GModel::deleteMesh(), drawEntityLabel(), GMSH_MeshSubEntitiesPlugin::execute(), GMSH_CurvedBndDistPlugin::execute(), GMSH_BubblesPlugin::execute(), GMSH_DistancePlugin::execute(), filterPoints(), GeomMeshMatcher::forceTomatch(), getAcuteCorners(), getAdditionalEntities(), getAllParameters(), getBoundaryFromMesh(), getColorByElement(), bidimMeshData::getIndex(), getInfoString(), getNumElementsMSH(), MElement::idealJacRange(), insertVertexB(), LC_MVertex_CURV(), LC_MVertex_CURV_ANISO(), LC_MVertex_PNTS(), meshGenerator(), meshGeneratorPeriodic(), GEntityPtrFullLessThan::operator()(), GEntityPtrFullEqual::operator()(), GEntityPtrFullHash::operator()(), optimize1DMeshAtAcuteCorners(), readMSH4BoundingEntities(), readMSH4Physicals(), RecombineTriangle::RecombineTriangle(), reparamMeshVertexOnFace(), MElement::scaledJacRange(), setBLData(), setMeshMaster(), MElement::signedInvCondNumRange(), smoothVertex(), smoothVertexOptimize(), backgroundMesh::updateSizes(), GModel::writeDIFF(), writeElementMSH(), writeElementsINP(), writeElementsKEY(), writeElementsMSH(), writeElementsRAD(), MVertex::writeMSH(), MVertex::writeMSH2(), writeMSH4Entities(), writeMSH4EntityNodes(), writeMSH4PeriodicNodes(), and writeMSHPeriodicNodes().
edges()
virtual std::vector<GEdge *> const& GEntity::edges () const inline virtual
Reimplemented in GFace, GRegion, and GVertex.
Definition at line 211 of file GEntity.h.
Referenced by _getAdditionalNodesOnBoundary(), addVerticesInSet(), bindingsGetEdges(), build_chords(), GModel::deleteMesh(), and MeshSetTransfiniteFacesAutomatic().
faces()
virtual std::vector<GFace *> GEntity::faces () const inline virtual
Reimplemented in GEdge, GRegion, and GVertex.
Definition at line 208 of file GEntity.h.
Referenced by _getAdditionalNodesOnBoundary(), addVerticesInSet(), bindingsGetFaces(), and GModel::deleteMesh().
geomType()
virtual GeomType GEntity::geomType () const inline virtual
Reimplemented in GVertex, discreteFace, xyFace, ghostRegion, ghostFace, ghostEdge, partitionEdge, partitionRegion, partitionVertex, gmshFace, partitionFace, gmshVertex, discreteEdge, discreteRegion, gmshEdge, gmshRegion, and xyEdge.
Definition at line 238 of file GEntity.h.
Referenced by addBoundaryLayerPoints(), algoDelaunay2D(), GRegion::bounds(), GEdge::bounds(), GFace::bounds(), GFace::buildRepresentationCross(), GFace::buildSTLTriangulation(), GEdge::closestPoint(), GFace::closestPoint(), computeEquidistantParameters(), GFace::computeMeanPlane(), GEdge::containsParam(), GFace::containsParam(), GEdge::containsPoint(), copyMesh(), GEdge::curvature(), GFace::curvatureDiv(), GFace::curvatureMax(), GFace::curvatures(), extrudeMesh(), getAllParameters(), getDegeneratedVertices(), getFaceVerticesOnGeo(), GModel::getMeshStatus(), getNodeCopies(), getNumElementsMSH(), GEdge::getOBB(), getTypeString(), GRegion::isFullyDiscrete(), GFace::isFullyDiscrete(), GEdge::length(), Mesh2DWithBoundaryLayers(), MeshExtrudedCurve(), MeshExtrudedSurface(), meshGEdgeProcessing(), MeshTransfiniteSurface(), metric_based_on_surface_curvature(), minimizeTutteEnergyProj(), GFace::normal(), meshGEdge::operator()(), meshGFace::operator()(), meshGRegionExtruded::operator()(), optimizeMeshGRegionNetgen::operator()(), orientMeshGFace::operator()(), drawGEdge::operator()(), optimalPointFrontalB(), GFace::parFromPoint(), GEdge::parFromPoint(), readMSH4Elements(), readMSH4GhostElements(), recombineIntoQuads(), GEdge::refineProjection(), reparamMeshVertexOnFace(), GEdge::reparamOnFace(), GEdge::secondDer(), SurfaceProjector::setAnalyticalProjection(), splitEdgePass(), writeElementMSH(), writeElementsMSH(), GRegion::writeGEO(), GEdge::writeGEO(), GFace::writeGEO(), GRegion::writePY(), GEdge::writePY(), GFace::writePY(), GEdge::XYZToU(), and GFace::XYZtoUV().
getAdditionalInfoString()
virtual std::string GEntity::getAdditionalInfoString (bool multline = false) inline virtual
Reimplemented in GFace, GEdge, GRegion, GVertex, and gmshEdge.
Definition at line 332 of file GEntity.h.
Referenced by getInfoString().
getAllElementsVisible()
bool GEntity::getAllElementsVisible () inline
Definition at line 372 of file GEntity.h.
Referenced by drawMeshGEdge::operator()(), and drawMeshGRegion::operator()().
getColor()
virtual unsigned int GEntity::getColor () inline virtual
Definition at line 318 of file GEntity.h.
Referenced by GFace::fillVertexArray(), getColorByEntity(), drawGVertex::operator()(), drawGEdge::operator()(), and drawGRegion::operator()().
getElementTypes()
virtual void GEntity::getElementTypes (std::vector< int > & types) const inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 345 of file GEntity.h.
getInfoString()
std::string GEntity::getInfoString (bool additional = true, bool multiline = false) virtual
Definition at line 53 of file GEntity.cpp.
Referenced by drawEntityLabel().
getMeshElement()
virtual MElement* GEntity::getMeshElement (std::size_t index) const inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 363 of file GEntity.h.
Referenced by GMSH_ShowNeighborElementsPlugin::_init(), groupOfElements::addElementary(), GFace::alignElementsWithMaster(), GMSH_DistancePlugin::execute(), getAdditionalEntities(), getBoundaryFromMesh(), getNumElementsMSH(), getOrder(), femTerm< scalar >::neumannNodalBC(), femTerm< scalar >::neumannNormalNodalBC(), gLevelsetYarn::operator()(), GModel::removeDuplicateMeshVertices(), GModel::renumberMeshElements(), GModel::renumberMeshVertices(), GMSH_SimplePartitionPlugin::run(), storePairMATLAB(), GModel::writeDIFF(), and writeElementsMATLAB().
getMeshElementByType()
virtual MElement* GEntity::getMeshElementByType (const int familyType, const std::size_t index) const inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 365 of file GEntity.h.
getMeshMaster()
GEntity* GEntity::getMeshMaster () const inline
Definition at line 291 of file GEntity.h.
Referenced by GFace::alignElementsWithMaster(), GModel::alignPeriodicBoundaries(), FixPeriodicMesh(), GEdge::getAdditionalInfoString(), GFace::getAdditionalInfoString(), Mesh0D(), MeshExtrudedCurve(), MeshExtrudedSurface(), meshGEdge::operator()(), meshGFace::operator()(), orientMeshGFace::operator()(), relocateSlaveVertices(), GFace::setMeshMaster(), writeMSH4PeriodicNodes(), and writeMSHPeriodicNodes().
getMeshSize()
virtual double GEntity::getMeshSize () const inline virtual
Reimplemented in GFace, and GRegion.
Definition at line 341 of file GEntity.h.
Referenced by BGM_MeshMetric(), and BGM_MeshSizeWithoutScaling().
getMeshSizeFactor()
virtual double GEntity::getMeshSizeFactor () const inline virtual
Reimplemented in GFace.
Definition at line 342 of file GEntity.h.
Referenced by BGM_MeshSize().
getMeshVertex()
MVertex* GEntity::getMeshVertex (std::size_t index) inline
Definition at line 379 of file GEntity.h.
Referenced by bowyerWatsonParallelogramsConstrained(), GEdge::getOBB(), GFace::getOBB(), GModel::renumberMeshVertices(), and writeMSH4EntityNodes().
getNativeInt()
virtual int GEntity::getNativeInt () const inline virtual
Definition at line 274 of file GEntity.h.
getNativePtr()
virtual void* GEntity::getNativePtr () const inline virtual
Reimplemented in xyFace, gmshFace, gmshVertex, gmshEdge, gmshRegion, and xyEdge.
Definition at line 271 of file GEntity.h.
Referenced by gmshVertex::reparamOnFace(), and gmshEdge::reparamOnFace().
getNativeType()
virtual ModelType GEntity::getNativeType () const inline virtual
Reimplemented in xyFace, gmshFace, gmshVertex, gmshEdge, gmshRegion, and xyEdge.
Definition at line 268 of file GEntity.h.
Referenced by GFace::buildRepresentationCross(), getInfoString(), Mesh2DWithBoundaryLayers(), meshGFace::operator()(), refineMeshBDS(), reparamMeshVertexOnFace(), swapEdgePass(), GEO_Internals::synchronize(), GVertex::writePY(), GRegion::writePY(), GEdge::writePY(), and GFace::writePY().
getNumMeshElements() [1/2]
virtual std::size_t GEntity::getNumMeshElements () const inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 348 of file GEntity.h.
Referenced by GMSH_ShowNeighborElementsPlugin::_init(), groupOfElements::addElementary(), GFace::alignElementsWithMaster(), GMSH_DistancePlugin::execute(), getBoundaryFromMesh(), getNumElementsMSH(), getOrder(), femTerm< scalar >::neumannNodalBC(), femTerm< scalar >::neumannNormalNodalBC(), gLevelsetYarn::operator()(), GModel::removeDuplicateMeshVertices(), GModel::renumberMeshElements(), GModel::renumberMeshVertices(), GMSH_SimplePartitionPlugin::run(), storePairMATLAB(), GModel::writeDIFF(), and writeElementsMATLAB().
getNumMeshElements() [2/2]
virtual void GEntity::getNumMeshElements (unsigned *const c) const inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 354 of file GEntity.h.
getNumMeshElementsByType()
virtual std::size_t GEntity::getNumMeshElementsByType (const int familyType) const inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 349 of file GEntity.h.
getNumMeshParentElements()
virtual std::size_t GEntity::getNumMeshParentElements () inline virtual
Reimplemented in GFace, GEdge, and GRegion.
Definition at line 353 of file GEntity.h.
getNumMeshVertices()
std::size_t GEntity::getNumMeshVertices () inline
Definition at line 376 of file GEntity.h.
Referenced by bowyerWatsonParallelogramsConstrained(), getAdditionalEntities(), getEdgeVerticesOnGeo(), GEdge::getOBB(), GFace::getOBB(), GModel::renumberMeshVertices(), and writeMSH4EntityNodes().
getOBB()
virtual SOrientedBoundingBox GEntity::getOBB () inline virtual
Reimplemented in GFace, GEdge, and GRegion.
Definition at line 304 of file GEntity.h.
getParentEntity()
virtual GEntity* GEntity::getParentEntity () inline virtual
Reimplemented in GFace, GEdge, GVertex, GRegion, partitionEdge, partitionFace, partitionRegion, and partitionVertex.
Definition at line 199 of file GEntity.h.
Referenced by _getElementary(), getNumElementsMSH(), getParentTags(), writeElementMSH(), and writeElementsMSH().
getPhysicalEntities()
virtual std::vector<int> GEntity::getPhysicalEntities () inline virtual
Definition at line 288 of file GEntity.h.
Referenced by GMSH_DistancePlugin::execute(), and writeMSH4Physicals().
getSelection()
virtual char GEntity::getSelection () inline virtual
Definition at line 314 of file GEntity.h.
Referenced by drawArrays(), getColorByEntity(), getVisibility(), drawGVertex::operator()(), drawGEdge::operator()(), and drawGRegion::operator()().
getStartElementType()
virtual MElement* const* GEntity::getStartElementType (int type) const inline virtual
Reimplemented in GFace, GEdge, and GRegion.
Definition at line 357 of file GEntity.h.
getTypeString()
virtual std::string GEntity::getTypeString () inline virtual
Definition at line 133 of file GEntity.h.
Referenced by getInfoString(), Mesh2DWithBoundaryLayers(), meshGEdge::operator()(), and meshGFace::operator()().
getVisibility()
char GEntity::getVisibility () virtual
Definition at line 35 of file GEntity.cpp.
Referenced by deleteHighOrderVertices(), getBoundaryFromMesh(), GModel::getMeshStatus(), Mesh3D(), meshGEdgeProcessing(), meshGEdge::operator()(), meshGFace::operator()(), meshGRegion::operator()(), drawGVertex::operator()(), drawGEdge::operator()(), initMeshGEdge::operator()(), drawMeshGVertex::operator()(), initMeshGRegion::operator()(), drawGRegion::operator()(), drawMeshGEdge::operator()(), drawMeshGRegion::operator()(), OptimizeMesh(), and setFirstOrder().
haveParametrization()
virtual bool GEntity::haveParametrization () inline virtual
Reimplemented in discreteFace, partitionEdge, gmshFace, partitionFace, discreteEdge, discreteRegion, and gmshEdge.
Definition at line 251 of file GEntity.h.
Referenced by bowyerWatsonParallelograms(), getAllParameters(), getEdgeVertices(), getFaceVertices(), getNodeCopies(), MElement::idealJacRange(), SurfaceProjector::initialize(), GRegion::isFullyDiscrete(), isFullyDiscrete(), MElement::scaledJacRange(), and MElement::signedInvCondNumRange().
isFullyDiscrete()
virtual bool GEntity::isFullyDiscrete () inline virtual
Reimplemented in GFace, and GRegion.
Definition at line 256 of file GEntity.h.
Referenced by deleteHighOrderVertices(), deMeshGEdge::operator()(), and setFirstOrder().
isOrphan()
virtual bool GEntity::isOrphan () inline virtual
Reimplemented in GEdge, GFace, and GVertex.
Definition at line 224 of file GEntity.h.
Referenced by GModel::renumberMeshElements(), and GModel::renumberMeshVertices().
mesh()
virtual void GEntity::mesh (bool verbose) inline virtual
Reimplemented in GFace, GEdge, discreteFace, and discreteEdge.
Definition at line 187 of file GEntity.h.
model()
GModel* GEntity::model () const inline
Definition at line 277 of file GEntity.h.
Referenced by _recombineIntoQuads(), addBoundaryLayerPoints(), ghostEdge::addElement(), ghostFace::addElement(), ghostRegion::addElement(), addElementsInArrays(), addExtrudeNormals(), ghostRegion::addHexahedron(), ghostEdge::addLine(), ghostFace::addPolygon(), ghostRegion::addPolyhedron(), ghostRegion::addPrism(), ghostRegion::addPyramid(), ghostFace::addQuadrangle(), addSmoothNormals(), ghostRegion::addTetrahedron(), ghostFace::addTriangle(), ghostRegion::addTrihedron(), BGM_MeshMetric(), BGM_MeshSizeWithoutScaling(), discreteFace::createGeometry(), GVertex::deleteMesh(), GRegion::deleteMesh(), GEdge::deleteMesh(), GFace::deleteMesh(), discreteEdge::discreteEdge(), discreteFace::discreteFace(), discreteRegion::discreteRegion(), drawArrays(), drawEntityLabel(), ensureManifoldFace(), ensureSimplyConnectedEdge(), getInfoString(), getNodeCopies(), GFaceInitialMesh(), insertVerticesInRegion(), GVertex::isOrphan(), GFace::isOrphan(), GEdge::isOrphan(), MeshDelaunayVolume(), MeshExtrudedCurve(), MeshExtrudedSurface(), meshGenerator(), meshPolygon(), modifyInitialMeshForBoundaryLayers(), meshGEdge::operator()(), meshGFace::operator()(), meshGRegion::operator()(), meshGRegionExtruded::operator()(), optimizeMeshGRegion::operator()(), optimizeMeshGRegionNetgen::operator()(), orientMeshGFace::operator()(), drawGVertex::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), drawMeshGVertex::operator()(), drawGRegion::operator()(), drawMeshGEdge::operator()(), drawMeshGRegion::operator()(), phase1(), phase2(), phase3(), recombineIntoQuads(), gmshRegion::resetMeshAttributes(), gmshFace::resetMeshAttributes(), discreteFace::resetMeshAttributes(), gmshRegion::resetNativePtr(), gmshFace::resetNativePtr(), GFace::setBoundEdges(), GRegion::setBoundFaces(), GFace::setMeshMaster(), splitElementsInBoundaryLayerIfNeeded(), writeElementsKEY(), and writeElementsRAD().
parBounds()
virtual Range<double> GEntity::parBounds (int i) const inline virtual
Reimplemented in discreteEdge, GEdge, discreteFace, gmshEdge, gmshFace, xyFace, and xyEdge.
Definition at line 259 of file GEntity.h.
Referenced by bowyerWatsonFrontal(), GFace::buildRepresentationCross(), GFace::buildSTLTriangulation(), GFace::closestPoint(), GFace::containsParam(), GFace::fillPointCloud(), meshGeneratorPeriodic(), GFace::moveToValidRange(), gmshVertex::reparamOnFace(), splitEdgePass(), and GFace::XYZtoUV().
period()
virtual double GEntity::period (int dim) const inline virtual
Definition at line 245 of file GEntity.h.
Referenced by GFace::moveToValidRange().
periodic()
virtual bool GEntity::periodic (int dim) const inline virtual
Reimplemented in GEdge.
Definition at line 244 of file GEntity.h.
Referenced by SurfaceProjector::initialize(), GFace::moveToValidRange(), and meshGFace::operator()().
regions()
virtual std::list<GRegion *> GEntity::regions () const inline virtual
Reimplemented in GEdge, GFace, and GVertex.
Definition at line 202 of file GEntity.h.
Referenced by bindingsGetRegions(), and GModel::deleteMesh().
relocateMeshVertices()
virtual void GEntity::relocateMeshVertices () inline virtual
Reimplemented in GFace, GEdge, and GVertex.
Definition at line 394 of file GEntity.h.
removeElement()
virtual void GEntity::removeElement (int type, MElement * e) inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 389 of file GEntity.h.
removeElements()
virtual void GEntity::removeElements (int type) inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 391 of file GEntity.h.
removeMeshVertex()
void GEntity::removeMeshVertex (MVertex * v)
Definition at line 116 of file GEntity.cpp.
reorder()
virtual bool GEntity::reorder (const int elementType, const std::vector< std::size_t > & ordering) inline virtual
Reimplemented in GFace, GEdge, GRegion, and GVertex.
Definition at line 412 of file GEntity.h.
resetMeshAttributes()
virtual void GEntity::resetMeshAttributes () inline virtual
Reimplemented in GFace, GEdge, GRegion, discreteFace, gmshFace, GVertex, gmshEdge, gmshRegion, and gmshVertex.
Definition at line 338 of file GEntity.h.
setAllElementsVisible()
void GEntity::setAllElementsVisible (bool val) inline
Definition at line 373 of file GEntity.h.
Referenced by initMeshGEdge::operator()(), and initMeshGRegion::operator()().
setColor()
virtual void GEntity::setColor (unsigned color, bool recursive = false) inline virtual
Definition at line 319 of file GEntity.h.
Referenced by GRegion::setColor(), GEdge::setColor(), GFace::setColor(), and setColor().
setMeshMaster() [1/2]
void GEntity::setMeshMaster (GEntity * gMaster)
Definition at line 128 of file GEntity.cpp.
Referenced by readMSH4PeriodicNodes(), readMSHPeriodicNodes(), GFace::setMeshMaster(), GEdge::setMeshMaster(), and setMeshMaster().
setMeshMaster() [2/2]
void GEntity::setMeshMaster (GEntity * gMaster, const std::vector< double > & tfo, bool updateCorrespondingVertices = true)
Definition at line 139 of file GEntity.cpp.
setSelection()
virtual void GEntity::setSelection (char val) inline virtual
Definition at line 315 of file GEntity.h.
setTag()
void GEntity::setTag (int tag) inline
Definition at line 281 of file GEntity.h.
Referenced by GModel::changeEntityTag(), GeomMeshMatcher::matchFaces(), and GeomMeshMatcher::matchRegions().
setVisibility()
virtual void GEntity::setVisibility (char val, bool recursive = false) inline virtual
Reimplemented in GFace, GEdge, and GRegion.
Definition at line 308 of file GEntity.h.
Referenced by GRegion::setVisibility(), GEdge::setVisibility(), GFace::setVisibility(), and setVisibility().
tag()
int GEntity::tag () const inline
Definition at line 280 of file GEntity.h.
Referenced by discreteFace::_createGeometryFromSTL(), discreteFace::_debugParametrization(), _getAdditionalNodesOnBoundary(), _getElementary(), _recombineIntoQuads(), addBoundaryLayerPoints(), GVertex::addElement(), GRegion::addElement(), GEdge::addElement(), GFace::addElement(), GModel::alignPeriodicBoundaries(), allEdgesLinked(), allFacesLinked(), BGM_MeshSizeWithoutScaling(), blyr_manager::blyr_manager(), bowyerWatsonParallelograms(), buildBackgroundMesh(), buildConsecutiveListOfVertices(), splitQuadRecovery::buildPyramids(), classifyFaces(), SurfaceProjector::closestPoint(), GFace::computeMeanPlane(), copy_vertices(), copyMesh(), createBoundaryLayerOneLayer(), createEdgeLinks(), createFaceLinks(), discreteRegion::createGeometry(), discreteEdge::createGeometry(), createHexPri(), createPoints(), createPriPyrTet(), createQuaTri(), createTopologyFromMesh1D(), discreteFace::curvatures(), GModel::deleteMesh(), drawElementLabels(), drawEntityLabel(), drawVertexLabel(), ensureManifoldFace(), ensureSimplyConnectedEdge(), GMSH_BoundaryAnglesPlugin::execute(), GModel::exportDiscreteGEOInternals(), blyr_manager::extrude_one_external(), blyr_manager::extrude_vertices_on_edges(), ExtrudeCurve(), extrudeMesh(), ExtrudePoint(), ExtrudeSurface(), faceIsValidQuad(), extrudeInfo::fillExtrudeParams(), discreteFace::firstDer(), FixPeriodicMesh(), GeomMeshMatcher::forceTomatch(), GEdge::getAdditionalInfoString(), GFace::getAdditionalInfoString(), GModel::getBoundaryTags(), getCandidateExtrudeInfo(), getColorByEntity(), getEdgeVertices(), getEdgeVerticesOnGeo(), getInfoString(), getParentTags(), blyr_manager::getRidge(), GModel::getTagsForPhysicalName(), GOrientedTransfiniteFace::getVertex(), GFaceDelaunayRefinement(), GOrientedTransfiniteFace::GOrientedTransfiniteFace(), insertVerticesInRegion(), GEdge::isMeshDegenerated(), GeomMeshMatcher::matchEdges(), GeomMeshMatcher::matchFaces(), GFace::mesh(), Mesh2DWithBoundaryLayers(), Mesh3D(), MeshExtrudedCurve(), MeshExtrudedSurface(), meshGEdgeProcessing(), meshGenerator(), meshGeneratorPeriodic(), meshGRegionNetgen(), MeshTransfiniteSurface(), MeshTransfiniteVolume(), gmshFace::normal(), discreteFace::normal(), meshGEdge::operator()(), meshGFace::operator()(), meshGRegionExtruded::operator()(), optimizeMeshGRegion::operator()(), orientMeshGFace::operator()(), optimizeMeshGRegionNetgen::operator()(), drawGVertex::operator()(), EmbeddedCompatibilityTest::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), F_Transfinite::operator()(), drawMeshGVertex::operator()(), GEntityPtrLessThan::operator()(), drawGRegion::operator()(), GEntityPtrFullLessThan::operator()(), GEntityPtrFullEqual::operator()(), drawMeshGEdge::operator()(), GEntityPtrFullHash::operator()(), drawMeshGRegion::operator()(), blyr_ridge::operator<(), optimize1DMeshAtAcuteCorners(), orientAndSortEdges(), GEdgeSigned::print(), extrudeInfo::print(), backgroundMesh::propagateCrossField(), quad_face_opposite_edge(), readMSH4BoundingEntities(), GModel::readSTL(), RecombineMesh(), recoverEdge(), recurFindLinkedEdges(), recurFindLinkedFaces(), refineMeshBDS(), relocateSlaveVertices(), RelocateVertices(), GModel::remove(), GVertex::removeElement(), GRegion::removeElement(), GEdge::removeElement(), GFace::removeElement(), GVertex::removeElements(), GRegion::removeElements(), GEdge::removeElements(), GFace::removeElements(), reparamMeshVertexOnFace(), discreteFace::resetMeshAttributes(), GFace::setBoundEdges(), GRegion::setBoundFaces(), GFace::setMeshMaster(), GEdge::setMeshMaster(), setMeshMaster(), GRegion::setOutwardOrientationMeshConstraint(), setTag(), BoundaryLayerField::setupFor1d(), SubdivideExtrudedMesh(), GEO_Internals::synchronize(), transferSeamGEdgesVerticesToGFace(), trueBoundary(), GModel::writeDIFF(), writeElementsINP(), writeElementsKEY(), writeElementsMATLAB(), writeElementsMSH(), writeElementsRAD(), gmshVertex::writeGEO(), gmshEdge::writeGEO(), GVertex::writeGEO(), GRegion::writeGEO(), GEdge::writeGEO(), GFace::writeGEO(), MVertex::writeMESH(), MVertex::writeMSH(), MVertex::writeMSH2(), writeMSH4Entities(), writeMSH4EntityNodes(), writeMSH4Parametrizations(), writeMSH4PeriodicNodes(), writeMSHPeriodicNodes(), discreteEdge::writeParametrization(), gmshVertex::writePY(), GVertex::writePY(), GRegion::writePY(), GEdge::writePY(), GFace::writePY(), discreteVertex::x(), GEdge::XYZToU(), GFace::XYZtoUV(), discreteVertex::y(), and discreteVertex::z().
tolerance()
virtual double GEntity::tolerance () const inline virtual
Definition at line 262 of file GEntity.h.
Referenced by GEdge::closestPointWithTol().
updateCorrespondingVertices()
void GEntity::updateCorrespondingVertices ()
Definition at line 197 of file GEntity.cpp.
Referenced by setMeshMaster().
useColor()
bool GEntity::useColor () virtual
Definition at line 43 of file GEntity.cpp.
Referenced by GFace::fillVertexArray(), getColorByEntity(), getInfoString(), drawGVertex::operator()(), drawGEdge::operator()(), and drawGRegion::operator()().
vertices()
virtual std::vector<GVertex *> GEntity::vertices () const inline virtual
Reimplemented in GFace, GEdge, and GRegion.
Definition at line 218 of file GEntity.h.
Referenced by _getAdditionalNodesOnBoundary(), addVerticesInSet(), and bindingsGetVertices().
Member Data Documentation
_allElementsVisible
char GEntity::_allElementsVisible private
Definition at line 46 of file GEntity.h.
Referenced by getAllElementsVisible(), and setAllElementsVisible().
_color
unsigned int GEntity::_color private
Definition at line 49 of file GEntity.h.
Referenced by GEntity(), getColor(), getInfoString(), setColor(), and useColor().
_meshMaster
GEntity* GEntity::_meshMaster private
Definition at line 40 of file GEntity.h.
Referenced by copyMasterCoordinates(), getMeshMaster(), setMeshMaster(), and updateCorrespondingVertices().
_model
GModel* GEntity::_model private
Definition at line 34 of file GEntity.h.
Referenced by model().
_obb
SOrientedBoundingBox* GEntity::_obb protected
Definition at line 52 of file GEntity.h.
Referenced by GRegion::getOBB(), GEdge::getOBB(), and GFace::getOBB().
_selection
char GEntity::_selection private
Definition at line 43 of file GEntity.h.
Referenced by getSelection(), and setSelection().
_tag
int GEntity::_tag private
Definition at line 37 of file GEntity.h.
Referenced by setTag(), and tag().
_visible
char GEntity::_visible private
Definition at line 43 of file GEntity.h.
Referenced by getVisibility(), and setVisibility().
affineTransform
std::vector<double> GEntity::affineTransform
Definition at line 403 of file GEntity.h.
Referenced by copyMasterCoordinates(), copyMesh(), MeshExtrudedCurve(), MeshExtrudedSurface(), relocateSlaveVertices(), setMeshMaster(), updateCorrespondingVertices(), writeMSH4PeriodicNodes(), and writeMSHPeriodicNodes().
compound
std::vector<GEntity *> GEntity::compound
Definition at line 59 of file GEntity.h.
Referenced by _recombineIntoQuads(), GFace::getEmbeddedEdges(), GFace::getEmbeddedMeshVertices(), GFace::getEmbeddedVertices(), GEdge::mesh(), GFace::mesh(), and quadMeshRemoveHalfOfOneDMesh::quadMeshRemoveHalfOfOneDMesh().
correspondingHighOrderVertices
std::map<MVertex *, MVertex *> GEntity::correspondingHighOrderVertices
Definition at line 409 of file GEntity.h.
Referenced by copyMasterCoordinates(), GEdge::deleteMesh(), GFace::deleteMesh(), FixPeriodicMesh(), relocateSlaveVertices(), Subdivide(), writeMSH4PeriodicNodes(), and writeMSHPeriodicNodes().
correspondingVertices
std::map<MVertex *, MVertex *> GEntity::correspondingVertices
Definition at line 406 of file GEntity.h.
Referenced by GFace::alignElementsWithMaster(), GModel::alignPeriodicBoundaries(), copyMasterCoordinates(), copyMesh(), GEdge::deleteMesh(), GFace::deleteMesh(), fillCorrespondingNodes(), FixPeriodicMesh(), Mesh0D(), readMSH4PeriodicNodes(), readMSHPeriodicNodes(), relocateSlaveVertices(), GModel::removeDuplicateMeshVertices(), Subdivide(), updateCorrespondingVertices(), writeMSH4PeriodicNodes(), and writeMSHPeriodicNodes().
curvedBLElements
std::set<MElement *> GEntity::curvedBLElements
Definition at line 71 of file GEntity.h.
mesh_vertices
std::vector<MVertex *> GEntity::mesh_vertices
Definition at line 56 of file GEntity.h.
Referenced by _deleteUnusedVertices(), _getAdditionalNodesOnBoundary(), GModel::_readMSH2(), _removeDiamonds(), _removeTwoQuadsNodes(), GModel::_storeElementsInEntities(), GModel::_storeVerticesInEntities(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), blyr_manager::add_external_corner(), blyr_manager::add_fan(), blyr_manager::add_one_normal(), addMeshVertex(), addVerticesInSet(), BarycentricRefineMesh(), BDS2GMSH(), bowyerWatsonFrontal(), bowyerWatsonParallelograms(), buildConsecutiveListOfVertices(), splitQuadRecovery::buildPyramids(), classifyFaces(), computeEdgeLoops(), copy_vertices(), copyMesh(), createBoundaryLayerOneLayer(), createElements(), createPoints(), createTopologyFromMesh1D(), deleteHighOrderVertices(), GVertex::deleteMesh(), GRegion::deleteMesh(), GEdge::deleteMesh(), GFace::deleteMesh(), deleteUnusedVertices(), drawVerticesPerEntity(), GMSH_CrackPlugin::execute(), GMSH_DistancePlugin::execute(), blyr_manager::extrude_one_external(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), extrudeMesh(), fillCorrespondingNodes(), filterPoints(), findTransfiniteCorners(), GeomMeshMatcher::forceTomatch(), getEdgeVerticesOnGeo(), getMeshVertex(), getNumMeshVertices(), insertAllVertices(), insertAPoint(), insertVerticesInRegion(), GEdge::isMeshDegenerated(), LaplaceSmoothing(), GModel::makeDiscreteRegionsSimplyConnected(), MakeMeshConformal(), Mesh0D(), MeshExtrudedSurface(), meshGenerator(), meshGeneratorPeriodic(), MeshTransfiniteSurface(), MeshTransfiniteVolume(), meshGEdge::operator()(), meshGFace::operator()(), PolyMesh2GFace(), DocRecord::printMedialAxis(), GModel::readP3D(), recoverEdge(), GVertex::relocateMeshVertices(), GEdge::relocateMeshVertices(), GFace::relocateMeshVertices(), GModel::removeDuplicateMeshVertices(), removeMeshVertex(), reparamMeshVertexOnEdge(), gmshVertex::setPosition(), discreteVertex::setPosition(), GEdge::storeSTLAsMesh(), GFace::storeSTLAsMesh(), Subdivide(), transferSeamGEdgesVerticesToGFace(), DistanceField::update(), discreteVertex::x(), discreteVertex::y(), discreteVertex::z(), ghostEdge::~ghostEdge(), ghostFace::~ghostFace(), and ghostRegion::~ghostRegion().
physicals
std::vector<int> GEntity::physicals
Definition at line 65 of file GEntity.h.
Referenced by GModel::_storePhysicalTagsInEntities(), addPhysicalEntity(), GModel::addPhysicalGroup(), drawElementLabels(), drawEntityLabel(), drawVertexLabel(), GMSH_MeshSubEntitiesPlugin::execute(), GMSH_CrackPlugin::execute(), GMSH_MathEvalPlugin::execute(), getColorByEntity(), getInfoString(), getNumElementsMSH(), getPhysicalEntities(), GeomMeshMatcher::matchEdges(), GeomMeshMatcher::matchFaces(), GeomMeshMatcher::matchRegions(), GeomMeshMatcher::matchVertices(), readMSHPhysicals(), GModel::renumberMeshElements(), GModel::renumberMeshVertices(), skipEdge(), skipFace(), skipRegion(), skipVertex(), GEO_Internals::synchronize(), GModel::writeDIFF(), writeElementsINP(), writeElementsKEY(), writeElementsMSH(), writeElementsRAD(), writeElementsTOCHNOG(), writeMSHPhysicals(), and GModel::writeOFF().
va_lines
VertexArray* GEntity::va_lines
Definition at line 68 of file GEntity.h.
Referenced by addElementsInArrays(), deleteVertexArrays(), getElement(), initMeshGEdge::operator()(), initMeshGRegion::operator()(), drawMeshGEdge::operator()(), and drawMeshGRegion::operator()().
va_triangles
VertexArray * GEntity::va_triangles
Definition at line 68 of file GEntity.h.
Referenced by addElementsInArrays(), deleteVertexArrays(), getElement(), initMeshGRegion::operator()(), and drawMeshGRegion::operator()().
vertexCounterparts
std::map<GVertex *, GVertex *> GEntity::vertexCounterparts
Definition at line 62 of file GEntity.h.
Referenced by copyMesh(), FixPeriodicMesh(), GFace::setMeshMaster(), and GEdge::setMeshMaster().
The documentation for this class was generated from the following files:
src/geo/GEntity.h
src/geo/GEntity.cpp