gmsh-TingyuanDoc: HierarchicalBasisHcurlTetra Class Reference
HierarchicalBasisHcurlTetra Class Reference
#include <HierarchicalBasisHcurlTetra.h>
Public Member Functions
HierarchicalBasisHcurlTetra (int order)
virtual ~HierarchicalBasisHcurlTetra ()
virtual unsigned int getNumberOfOrientations () const
virtual void generateBasis (double const &u, double const &v, double const &w, std::vector< std::vector< double > > &vertexBasis, std::vector< std::vector< double > > &edgeBasis, std::vector< std::vector< double > > &faceBasis, std::vector< std::vector< double > > &bubbleBasis, std::string typeFunction)
virtual void orientEdge (int const &flagOrientation, int const &edgeNumber, std::vector< std::vector< double > > &edgeBasis, const std::vector< std::vector< double > > &eTablePositiveFlag, const std::vector< std::vector< double > > &eTableNegativeFlag)
virtual void orientEdgeFunctionsForNegativeFlag (std::vector< std::vector< double > > &edgeFunctions)
virtual void orientFace (int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, const std::vector< std::vector< double > > &quadFaceFunctionsAllOrientation, const std::vector< std::vector< double > > &triFaceFunctionsAllOrientation, std::vector< std::vector< double > > &fTableCopy)
virtual void getKeysInfo (std::vector< int > &functionTypeInfo, std::vector< int > &orderInfo)
Public Member Functions inherited from HierarchicalBasisHcurl
virtual ~HierarchicalBasisHcurl ()=0
virtual void generateBasis (double const &u, double const &v, double const &w, std::vector< double > &vertexBasis, std::vector< double > &edgeBasis, std::vector< double > &faceBasis, std::vector< double > &bubbleBasis)
virtual void orientFace (int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, const std::vector< double > &quadFaceFunctionsAllOrientations, const std::vector< double > &triFaceFunctionsAllOrientations, std::vector< double > &fTableCopy)
virtual void orientEdge (int const &flagOrientation, int const &edgeNumber, std::vector< double > &edgeFunctions, const std::vector< double > &eTablePositiveFlag, const std::vector< double > &eTableNegativeFlag)
virtual void orientEdgeFunctionsForNegativeFlag (std::vector< double > &edgeFunctions)
virtual void addAllOrientedFaceFunctions (double const &u, double const &v, double const &w, const std::vector< double > &faceFunctions, std::vector< double > &quadFaceFunctionsAllOrientations, std::vector< double > &triFaceFunctionsAllOrientations)
virtual void addAllOrientedFaceFunctions (double const &u, double const &v, double const &w, const std::vector< std::vector< double > > &faceFunctions, std::vector< std::vector< double > > &quadFaceFunctionsAllOrientations, std::vector< std::vector< double > > &triFaceFunctionsAllOrientations, std::string typeFunction)
Public Member Functions inherited from HierarchicalBasis
virtual ~HierarchicalBasis ()=0
int getnVertexFunction () const
int getnEdgeFunction () const
int getnTriFaceFunction () const
int getnQuadFaceFunction () const
int getnBubbleFunction () const
int getNumTriFace () const
int getNumQuadFace () const
int getNumEdge () const
int numberOrientationQuadFace (int const &flag1, int const &flag2, int const &flag3)
int numberOrientationTriFace (int const &flag1, int const &flag2)
Private Member Functions
virtual void generateHcurlBasis (double const &u, double const &v, double const &w, std::vector< std::vector< double > > &edgeBasis, std::vector< std::vector< double > > &faceBasis, std::vector< std::vector< double > > &bubbleBasis)
virtual void generateCurlBasis (double const &u, double const &v, double const &w, std::vector< std::vector< double > > &edgeBasis, std::vector< std::vector< double > > &faceBasis, std::vector< std::vector< double > > &bubbleBasis)
void gradient (const double &lambda1, const double &lambda2, const std::vector< double > &dlambda1, const std::vector< double > &dlambda2, std::vector< double > &result)
void curlFunction (const double &a, const std::vector< double > &nD, const std::vector< double > &grad, std::vector< double > &result)
virtual void orientOneFace (double const &u, double const &v, double const &w, int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, std::vector< std::vector< double > > &faceFunctions, std::string typeFunction)
Static Private Member Functions
static double _affineCoordinate (const int &j, const double &u, const double &v, const double &w)
static double dotProduct (const std::vector< double > &u, const std::vector< double > &v)
Private Attributes
int _pb
int _pOrderEdge [6]
int _pOrderFace [4]
Additional Inherited Members
Protected Member Functions inherited from HierarchicalBasisHcurl
virtual void orientOneFace (double const &u, double const &v, double const &w, int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, std::vector< double > &faceFunctions)
Protected Attributes inherited from HierarchicalBasis
int _nvertex
int _nedge
int _nfaceQuad
int _nfaceTri
int _nVertexFunction
int _nEdgeFunction
int _nQuadFaceFunction
int _nTriFaceFunction
int _nBubbleFunction
Detailed Description
Definition at line 53 of file HierarchicalBasisHcurlTetra.h.
Constructor & Destructor Documentation
HierarchicalBasisHcurlTetra()
HierarchicalBasisHcurlTetra::HierarchicalBasisHcurlTetra (int order)
Definition at line 14 of file HierarchicalBasisHcurlTetra.cpp.
~HierarchicalBasisHcurlTetra()
HierarchicalBasisHcurlTetra::~HierarchicalBasisHcurlTetra () virtual
Definition at line 37 of file HierarchicalBasisHcurlTetra.cpp.
Member Function Documentation
_affineCoordinate()
double HierarchicalBasisHcurlTetra::_affineCoordinate (const int & j, const double & u, const double & v, const double & w) static private
Definition at line 44 of file HierarchicalBasisHcurlTetra.cpp.
Referenced by generateCurlBasis(), generateHcurlBasis(), and orientOneFace().
curlFunction()
void HierarchicalBasisHcurlTetra::curlFunction (const double & a, const std::vector< double > & nD, const std::vector< double > & grad, std::vector< double > & result) inline private
Definition at line 950 of file HierarchicalBasisHcurlTetra.cpp.
Referenced by generateCurlBasis(), and orientOneFace().
dotProduct()
double HierarchicalBasisHcurlTetra::dotProduct (const std::vector< double > & u, const std::vector< double > & v) static private
Definition at line 58 of file HierarchicalBasisHcurlTetra.cpp.
Referenced by generateCurlBasis(), and generateHcurlBasis().
generateBasis()
virtual void HierarchicalBasisHcurlTetra::generateBasis (double const & u, double const & v, double const & w, std::vector< std::vector< double > > & vertexBasis, std::vector< std::vector< double > > & edgeBasis, std::vector< std::vector< double > > & faceBasis, std::vector< std::vector< double > > & bubbleBasis, std::string typeFunction) inline virtual
Implements HierarchicalBasisHcurl.
Definition at line 58 of file HierarchicalBasisHcurlTetra.h.
generateCurlBasis()
void HierarchicalBasisHcurlTetra::generateCurlBasis (double const & u, double const & v, double const & w, std::vector< std::vector< double > > & edgeBasis, std::vector< std::vector< double > > & faceBasis, std::vector< std::vector< double > > & bubbleBasis) private virtual
Definition at line 968 of file HierarchicalBasisHcurlTetra.cpp.
Referenced by generateBasis().
generateHcurlBasis()
void HierarchicalBasisHcurlTetra::generateHcurlBasis (double const & u, double const & v, double const & w, std::vector< std::vector< double > > & edgeBasis, std::vector< std::vector< double > > & faceBasis, std::vector< std::vector< double > > & bubbleBasis) private virtual
Definition at line 64 of file HierarchicalBasisHcurlTetra.cpp.
Referenced by generateBasis().
getKeysInfo()
void HierarchicalBasisHcurlTetra::getKeysInfo (std::vector< int > & functionTypeInfo, std::vector< int > & orderInfo) virtual
Implements HierarchicalBasisHcurl.
Definition at line 1562 of file HierarchicalBasisHcurlTetra.cpp.
getNumberOfOrientations()
unsigned int HierarchicalBasisHcurlTetra::getNumberOfOrientations () const virtual
Implements HierarchicalBasis.
Definition at line 39 of file HierarchicalBasisHcurlTetra.cpp.
gradient()
void HierarchicalBasisHcurlTetra::gradient (const double & lambda1, const double & lambda2, const std::vector< double > & dlambda1, const std::vector< double > & dlambda2, std::vector< double > & result) inline private
Definition at line 958 of file HierarchicalBasisHcurlTetra.cpp.
Referenced by generateCurlBasis().
orientEdge()
void HierarchicalBasisHcurlTetra::orientEdge (int const & flagOrientation, int const & edgeNumber, std::vector< std::vector< double > > & edgeBasis, const std::vector< std::vector< double > > & eTablePositiveFlag, const std::vector< std::vector< double > > & eTableNegativeFlag) virtual
Implements HierarchicalBasisHcurl.
Definition at line 443 of file HierarchicalBasisHcurlTetra.cpp.
orientEdgeFunctionsForNegativeFlag()
void HierarchicalBasisHcurlTetra::orientEdgeFunctionsForNegativeFlag (std::vector< std::vector< double > > & edgeFunctions) virtual
Implements HierarchicalBasisHcurl.
Definition at line 474 of file HierarchicalBasisHcurlTetra.cpp.
orientFace()
void HierarchicalBasisHcurlTetra::orientFace (int const & flag1, int const & flag2, int const & flag3, int const & faceNumber, const std::vector< std::vector< double > > & quadFaceFunctionsAllOrientation, const std::vector< std::vector< double > > & triFaceFunctionsAllOrientation, std::vector< std::vector< double > > & fTableCopy) virtual
Implements HierarchicalBasisHcurl.
Definition at line 926 of file HierarchicalBasisHcurlTetra.cpp.
orientOneFace()
void HierarchicalBasisHcurlTetra::orientOneFace (double const & u, double const & v, double const & w, int const & flag1, int const & flag2, int const & flag3, int const & faceNumber, std::vector< std::vector< double > > & faceFunctions, std::string typeFunction) private virtual
Implements HierarchicalBasisHcurl.
Definition at line 494 of file HierarchicalBasisHcurlTetra.cpp.
Member Data Documentation
_pb
int HierarchicalBasisHcurlTetra::_pb private
Definition at line 92 of file HierarchicalBasisHcurlTetra.h.
Referenced by generateCurlBasis(), generateHcurlBasis(), getKeysInfo(), and HierarchicalBasisHcurlTetra().
_pOrderEdge
int HierarchicalBasisHcurlTetra::_pOrderEdge[6] private
Definition at line 93 of file HierarchicalBasisHcurlTetra.h.
Referenced by generateCurlBasis(), generateHcurlBasis(), getKeysInfo(), HierarchicalBasisHcurlTetra(), orientEdge(), and orientEdgeFunctionsForNegativeFlag().
_pOrderFace
int HierarchicalBasisHcurlTetra::_pOrderFace[4] private
Definition at line 95 of file HierarchicalBasisHcurlTetra.h.
Referenced by generateCurlBasis(), generateHcurlBasis(), getKeysInfo(), HierarchicalBasisHcurlTetra(), orientFace(), and orientOneFace().
The documentation for this class was generated from the following files:
src/numeric/HierarchicalBasisHcurlTetra.h
src/numeric/HierarchicalBasisHcurlTetra.cpp