gmsh-TingyuanDoc: SPoint3 Class Reference
SPoint3 Class Reference
#include <SPoint3.h>
Public Member Functions
SPoint3 ()
SPoint3 (double x, double y, double z)
SPoint3 (const double *p)
SPoint3 (const SPoint3 &pt)
virtual ~SPoint3 ()
void setPosition (double xx, double yy, double zz)
void setPosition (const SPoint3 &pt, const SPoint3 &dir, const double dist_)
void getPosition (double *xx, double *yy, double *zz) const
void position (double *) const
double x (void) const
double y (void) const
double z (void) const
double & operator[] (int)
double operator[] (int) const
SPoint3 & operator= (const SPoint3 &p)
void operator+= (const SPoint3 &p)
void operator-= (const SPoint3 &p)
void operator*= (double mult)
void operator/= (double mult)
SPoint3 operator* (double mult)
operator double * ()
double distance (const SPoint3 &p) const
bool operator< (const SPoint3 &p) const
const double * data () const
double * data ()
bool transform (const std::vector< double > &tfo)
operator std::array< double, 3 > () const
Protected Attributes
double P [3]
Detailed Description
Definition at line 14 of file SPoint3.h.
Constructor & Destructor Documentation
SPoint3() [1/4]
SPoint3::SPoint3 () inline
Definition at line 19 of file SPoint3.h.
Referenced by operator*().
SPoint3() [2/4]
SPoint3::SPoint3 (double x, double y, double z) inline
Definition at line 20 of file SPoint3.h.
SPoint3() [3/4]
SPoint3::SPoint3 (const double * p) inline
Definition at line 26 of file SPoint3.h.
SPoint3() [4/4]
SPoint3::SPoint3 (const SPoint3 & pt) inline
Definition at line 32 of file SPoint3.h.
~SPoint3()
virtual SPoint3::~SPoint3 () inline virtual
Definition at line 38 of file SPoint3.h.
Member Function Documentation
data() [1/2]
double* SPoint3::data () inline
Definition at line 77 of file SPoint3.h.
data() [2/2]
const double* SPoint3::data () const inline
Definition at line 76 of file SPoint3.h.
Referenced by SVector3::data().
distance()
double SPoint3::distance (const SPoint3 & p) const inline
Definition at line 176 of file SPoint3.h.
Referenced by closestPoint(), GFace::closestPoint(), discreteEdge::createGeometry(), discreteEdge::curvature(), SBoundingBox3d::diag(), distance(), eyeChanged(), GFace::fillPointCloud(), getGraphData(), MQuadrangle::getInnerRadius(), meshGeneratorPeriodic(), middlePoint(), GFace::setMeshMaster(), signedDistancePointLine(), signedDistancePointTriangle(), and signedDistancesPointsTriangle().
getPosition()
void SPoint3::getPosition (double * xx, double * yy, double * zz) const inline
Definition at line 111 of file SPoint3.h.
operator double *()
SPoint3::operator double * () inline
Definition at line 64 of file SPoint3.h.
operator std::array< double, 3 >()
SPoint3::operator std::array< double, 3 > () const inline
Definition at line 91 of file SPoint3.h.
operator*()
SPoint3 SPoint3::operator* (double mult) inline
Definition at line 167 of file SPoint3.h.
operator*=()
void SPoint3::operator*= (double mult) inline
Definition at line 153 of file SPoint3.h.
operator+=()
void SPoint3::operator+= (const SPoint3 & p) inline
Definition at line 139 of file SPoint3.h.
operator-=()
void SPoint3::operator-= (const SPoint3 & p) inline
Definition at line 146 of file SPoint3.h.
operator/=()
void SPoint3::operator/= (double mult) inline
Definition at line 160 of file SPoint3.h.
operator<()
bool SPoint3::operator< (const SPoint3 & p) const inline
Definition at line 67 of file SPoint3.h.
operator=()
SPoint3 & SPoint3::operator= (const SPoint3 & p) inline
Definition at line 131 of file SPoint3.h.
operator[]() [1/2]
double & SPoint3::operator[] (int i) inline
Definition at line 172 of file SPoint3.h.
operator[]() [2/2]
double SPoint3::operator[] (int i) const inline
Definition at line 174 of file SPoint3.h.
position()
void SPoint3::position (double * p) const inline
Definition at line 118 of file SPoint3.h.
setPosition() [1/2]
void SPoint3::setPosition (const SPoint3 & pt, const SPoint3 & dir, const double dist_) inline
Definition at line 40 of file SPoint3.h.
setPosition() [2/2]
void SPoint3::setPosition (double xx, double yy, double zz) inline
Definition at line 104 of file SPoint3.h.
Referenced by GModel::getMeshElementByCoord().
transform()
bool SPoint3::transform (const std::vector< double > & tfo) inline
Definition at line 78 of file SPoint3.h.
Referenced by GFace::setMeshMaster(), GEdge::setMeshMaster(), and SBoundingBox3d::transform().
x()
double SPoint3::x (void) const inline
Definition at line 125 of file SPoint3.h.
Referenced by _closestPoint(), OctreePost::_create(), discreteFace::_debugParametrization(), _isItAGoodIdeaToMoveThatVertex(), _kaboom(), _myGetEdgeRep(), _myGetFaceRep(), cartesianBox< scalar >::_printNodes(), blyr_manager::add_external_corner(), addExtrudeNormals(), addPoints(), AddToTemporaryBoundingBox(), addTriangle(), approximationError(), BarycentricRefineMesh(), blyr_manager::blyr_manager(), GFace::buildRepresentationCross(), changeReferential(), GModel::checkMeshCoherence(), gmshFace::closestPoint(), xyFace::closestPoint(), discreteFace::closestPoint(), computeAffineTransformation(), elasticitySolver::computeEffectiveStiffness(), elasticitySolver::computeEffectiveStrain(), thermicSolver::computeL2Norm(), elasticitySolver::computeL2Norm(), thermicSolver::computeLagNorm(), SBoundingBox3d::contains(), gmshFace::containsPoint(), GEdge::containsPoint(), createPoints(), CreateVertex(), distance(), GMSH_ProbePlugin::draw(), GMSH_CutPlanePlugin::draw(), drawContext::drawAxes(), drawBarycentricDual(), drawElementLabels(), drawNormals(), drawNumberGlyphs(), drawTangents(), drawVoronoiDual(), helmholtzTerm< double >::elementMatrix(), laplaceTerm::elementVector(), SBoundingBox3d::empty(), GMSH_GaussPointsPlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_DiscretizationErrorPlugin::execute(), GMSH_BubblesPlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), xFemFunctionSpace< T >::f(), GFace::fillVertexArray(), discreteEdge::firstDer(), LoadTerm< T1 >::get(), LoadTermOnBorder< T1 >::get(), backgroundMesh::getAngle(), MLine3::getEdgeRep(), MLineN::getEdgeRep(), GModel::getEntitiesInBox(), getGraphData(), MPolyhedron::getIntegrationPoints(), MPolygon::getIntegrationPoints(), MLineChild::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), getLineNormal(), GModel::getMeshElementByCoord(), GModel::getMeshElementsByCoord(), JacobianBasis::getMetricMinAndGradients(), MTetrahedron::getOuterRadius(), cartesianBox< scalar >::getValueContainingPoint(), GFaceInitialMesh(), xFemFunctionSpace< T >::gradf(), SElement::gradNodalFunctions(), initialCube(), initialSquare(), InterpolateBezier(), InterpolateCurve(), InterpolateSurface(), InterpolateUBS(), interpVerticesInExistingEdge(), intersection_segments(), MSubTetrahedron::isInside(), MSubTriangle::isInside(), MSubLine::isInside(), MSubPoint::isInside(), LaplaceSmoothing(), MakeMeshConformal(), MElementBB(), MElementOctree::MElementOctree(), meshGenerator(), meshGeneratorPeriodic(), meshGRegionNetgen(), minimizeTutteEnergyProj(), minmax(), MSubTetrahedron::movePointFromElementSpaceToParentSpace(), MSubTriangle::movePointFromElementSpaceToParentSpace(), MSubLine::movePointFromElementSpaceToParentSpace(), MElement::movePointFromElementSpaceToParentSpace(), MSubPoint::movePointFromElementSpaceToParentSpace(), MSubTetrahedron::movePointFromParentSpaceToElementSpace(), MSubTriangle::movePointFromParentSpaceToElementSpace(), MSubLine::movePointFromParentSpaceToElementSpace(), MElement::movePointFromParentSpaceToElementSpace(), MSubPoint::movePointFromParentSpaceToElementSpace(), HilbertSort::MultiscaleSortHilbert(), HilbertSortB::MultiscaleSortHilbert(), myPlane::myPlane(), femTerm< scalar >::neumannNodalBC(), SElement::nodalFunctions(), closestPointFinder::operator()(), closestVertexFinder::operator()(), optimizeMeshGRegionNetgen::operator()(), compareAngle::operator()(), backgroundMesh::operator()(), surfaceFunctorPlane::operator()(), ElementDataLessThan< N >::operator()(), ElmDataLessThan::operator()(), drawGFace::operator()(), drawGRegion::operator()(), drawPView::operator()(), drawPViewBoundingBox::operator()(), OctreeField::operator()(), operator+(), operator-(), opt_general_xmax(), opt_general_xmin(), myLine::orthogonalProjection(), gmshFace::parFromPoint(), xyFace::parFromPoint(), GFace::parFromPoint(), GEdge::parFromPoint(), discreteEdge::point(), projectPointToPlane(), propagateValuesOnFace(), drawContext::recenterForRotationCenterChange(), SurfaceProjector::setAnalyticalProjection(), SetBoundingBox(), GFace::setMeshMaster(), GRegion::setOutwardOrientationMeshConstraint(), MVertex::setXYZ(), signedDistancesPointsEllipseLine(), SPoint3(), GEdge::storeSTLAsMesh(), GFace::storeSTLAsMesh(), Subdivide(), subdivide_pyramid(), VertexArray::toChar(), transferSeamGEdgesVerticesToGFace(), OctreeField::update(), writeMSH4BoundingBox(), PView::writeX3D(), writeX3dEdges(), and SVector3::x().
y()
double SPoint3::y (void) const inline
Definition at line 127 of file SPoint3.h.
Referenced by _closestPoint(), OctreePost::_create(), discreteFace::_debugParametrization(), _isItAGoodIdeaToMoveThatVertex(), _kaboom(), _myGetEdgeRep(), _myGetFaceRep(), cartesianBox< scalar >::_printNodes(), blyr_manager::add_external_corner(), addExtrudeNormals(), addPoints(), AddToTemporaryBoundingBox(), addTriangle(), approximationError(), BarycentricRefineMesh(), blyr_manager::blyr_manager(), GFace::buildRepresentationCross(), changeReferential(), GModel::checkMeshCoherence(), gmshFace::closestPoint(), xyFace::closestPoint(), discreteFace::closestPoint(), computeAffineTransformation(), elasticitySolver::computeEffectiveStiffness(), elasticitySolver::computeEffectiveStrain(), thermicSolver::computeL2Norm(), elasticitySolver::computeL2Norm(), thermicSolver::computeLagNorm(), SBoundingBox3d::contains(), gmshFace::containsPoint(), GEdge::containsPoint(), createPoints(), CreateVertex(), distance(), GMSH_ProbePlugin::draw(), GMSH_CutPlanePlugin::draw(), drawContext::drawAxes(), drawBarycentricDual(), drawElementLabels(), drawNormals(), drawNumberGlyphs(), drawTangents(), drawVoronoiDual(), helmholtzTerm< double >::elementMatrix(), laplaceTerm::elementVector(), SBoundingBox3d::empty(), GMSH_GaussPointsPlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_DiscretizationErrorPlugin::execute(), GMSH_BubblesPlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), xFemFunctionSpace< T >::f(), GFace::fillVertexArray(), discreteEdge::firstDer(), LoadTerm< T1 >::get(), LoadTermOnBorder< T1 >::get(), backgroundMesh::getAngle(), MLine3::getEdgeRep(), MLineN::getEdgeRep(), GModel::getEntitiesInBox(), getGraphData(), MPolyhedron::getIntegrationPoints(), MPolygon::getIntegrationPoints(), MLineChild::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), getLineNormal(), GModel::getMeshElementByCoord(), GModel::getMeshElementsByCoord(), JacobianBasis::getMetricMinAndGradients(), MTetrahedron::getOuterRadius(), cartesianBox< scalar >::getValueContainingPoint(), GFaceInitialMesh(), xFemFunctionSpace< T >::gradf(), SElement::gradNodalFunctions(), initialCube(), initialSquare(), InterpolateBezier(), InterpolateCurve(), InterpolateSurface(), InterpolateUBS(), interpVerticesInExistingEdge(), intersection_segments(), MSubTetrahedron::isInside(), MSubTriangle::isInside(), MSubLine::isInside(), MSubPoint::isInside(), LaplaceSmoothing(), MakeMeshConformal(), MElementBB(), MElementOctree::MElementOctree(), meshGenerator(), meshGeneratorPeriodic(), meshGRegionNetgen(), minimizeTutteEnergyProj(), minmax(), MSubTetrahedron::movePointFromElementSpaceToParentSpace(), MSubTriangle::movePointFromElementSpaceToParentSpace(), MSubLine::movePointFromElementSpaceToParentSpace(), MElement::movePointFromElementSpaceToParentSpace(), MSubPoint::movePointFromElementSpaceToParentSpace(), MSubTetrahedron::movePointFromParentSpaceToElementSpace(), MSubTriangle::movePointFromParentSpaceToElementSpace(), MSubLine::movePointFromParentSpaceToElementSpace(), MElement::movePointFromParentSpaceToElementSpace(), MSubPoint::movePointFromParentSpaceToElementSpace(), HilbertSort::MultiscaleSortHilbert(), HilbertSortB::MultiscaleSortHilbert(), myPlane::myPlane(), femTerm< scalar >::neumannNodalBC(), SElement::nodalFunctions(), closestPointFinder::operator()(), closestVertexFinder::operator()(), optimizeMeshGRegionNetgen::operator()(), compareAngle::operator()(), backgroundMesh::operator()(), surfaceFunctorPlane::operator()(), ElementDataLessThan< N >::operator()(), ElmDataLessThan::operator()(), drawGFace::operator()(), drawGRegion::operator()(), drawPView::operator()(), drawPViewBoundingBox::operator()(), OctreeField::operator()(), operator+(), operator-(), opt_general_ymax(), opt_general_ymin(), myLine::orthogonalProjection(), gmshFace::parFromPoint(), xyFace::parFromPoint(), GFace::parFromPoint(), GEdge::parFromPoint(), discreteEdge::point(), projectPointToPlane(), propagateValuesOnFace(), drawContext::recenterForRotationCenterChange(), SurfaceProjector::setAnalyticalProjection(), SetBoundingBox(), GFace::setMeshMaster(), GRegion::setOutwardOrientationMeshConstraint(), MVertex::setXYZ(), signedDistancesPointsEllipseLine(), SPoint3(), GEdge::storeSTLAsMesh(), GFace::storeSTLAsMesh(), Subdivide(), subdivide_pyramid(), VertexArray::toChar(), transferSeamGEdgesVerticesToGFace(), OctreeField::update(), writeMSH4BoundingBox(), PView::writeX3D(), writeX3dEdges(), and SVector3::y().
z()
double SPoint3::z (void) const inline
Definition at line 129 of file SPoint3.h.
Referenced by _closestPoint(), OctreePost::_create(), discreteFace::_debugParametrization(), _isItAGoodIdeaToMoveThatVertex(), _kaboom(), _myGetEdgeRep(), _myGetFaceRep(), cartesianBox< scalar >::_printNodes(), blyr_manager::add_external_corner(), addExtrudeNormals(), AddToTemporaryBoundingBox(), addTriangle(), approximationError(), BarycentricRefineMesh(), blyr_manager::blyr_manager(), changeReferential(), GModel::checkMeshCoherence(), gmshFace::closestPoint(), discreteFace::closestPoint(), computeAffineTransformation(), elasticitySolver::computeEffectiveStiffness(), elasticitySolver::computeEffectiveStrain(), thermicSolver::computeL2Norm(), elasticitySolver::computeL2Norm(), thermicSolver::computeLagNorm(), SBoundingBox3d::contains(), gmshFace::containsPoint(), GEdge::containsPoint(), createPoints(), CreateVertex(), distance(), GMSH_ProbePlugin::draw(), GMSH_CutPlanePlugin::draw(), drawContext::drawAxes(), drawBarycentricDual(), drawElementLabels(), drawNormals(), drawNumberGlyphs(), drawTangents(), drawVoronoiDual(), helmholtzTerm< double >::elementMatrix(), SBoundingBox3d::empty(), GMSH_GaussPointsPlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_DiscretizationErrorPlugin::execute(), GMSH_BubblesPlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), xFemFunctionSpace< T >::f(), GFace::fillVertexArray(), discreteEdge::firstDer(), LoadTerm< T1 >::get(), LoadTermOnBorder< T1 >::get(), MLine3::getEdgeRep(), MLineN::getEdgeRep(), GModel::getEntitiesInBox(), getGraphData(), MPolyhedron::getIntegrationPoints(), MPolygon::getIntegrationPoints(), MLineChild::getIntegrationPoints(), MTriangleBorder::getIntegrationPoints(), MLineBorder::getIntegrationPoints(), getLineNormal(), GModel::getMeshElementByCoord(), GModel::getMeshElementsByCoord(), MTetrahedron::getOuterRadius(), cartesianBox< scalar >::getValueContainingPoint(), xFemFunctionSpace< T >::gradf(), SElement::gradNodalFunctions(), initialCube(), InterpolateBezier(), InterpolateCurve(), InterpolateSurface(), InterpolateUBS(), interpVerticesInExistingEdge(), intersection_segments(), MSubTetrahedron::isInside(), MSubTriangle::isInside(), MSubLine::isInside(), MSubPoint::isInside(), LaplaceSmoothing(), MakeMeshConformal(), MElementBB(), MElementOctree::MElementOctree(), meshGRegionNetgen(), minimizeTutteEnergyProj(), minmax(), MSubTetrahedron::movePointFromElementSpaceToParentSpace(), MSubTriangle::movePointFromElementSpaceToParentSpace(), MSubLine::movePointFromElementSpaceToParentSpace(), MElement::movePointFromElementSpaceToParentSpace(), MSubPoint::movePointFromElementSpaceToParentSpace(), MSubTetrahedron::movePointFromParentSpaceToElementSpace(), MSubTriangle::movePointFromParentSpaceToElementSpace(), MSubLine::movePointFromParentSpaceToElementSpace(), MElement::movePointFromParentSpaceToElementSpace(), MSubPoint::movePointFromParentSpaceToElementSpace(), HilbertSort::MultiscaleSortHilbert(), HilbertSortB::MultiscaleSortHilbert(), myPlane::myPlane(), femTerm< scalar >::neumannNodalBC(), SElement::nodalFunctions(), closestPointFinder::operator()(), closestVertexFinder::operator()(), optimizeMeshGRegionNetgen::operator()(), compareAngle::operator()(), surfaceFunctorPlane::operator()(), ElementDataLessThan< N >::operator()(), ElmDataLessThan::operator()(), drawGFace::operator()(), drawGRegion::operator()(), drawPView::operator()(), drawPViewBoundingBox::operator()(), OctreeField::operator()(), operator+(), operator-(), opt_general_zmax(), opt_general_zmin(), myLine::orthogonalProjection(), gmshFace::parFromPoint(), GFace::parFromPoint(), GEdge::parFromPoint(), discreteEdge::point(), projectPointToPlane(), propagateValuesOnFace(), drawContext::recenterForRotationCenterChange(), SurfaceProjector::setAnalyticalProjection(), SetBoundingBox(), GFace::setMeshMaster(), GRegion::setOutwardOrientationMeshConstraint(), MVertex::setXYZ(), signedDistancesPointsEllipseLine(), SPoint3(), GEdge::storeSTLAsMesh(), GFace::storeSTLAsMesh(), Subdivide(), subdivide_pyramid(), VertexArray::toChar(), transferSeamGEdgesVerticesToGFace(), OctreeField::update(), writeMSH4BoundingBox(), PView::writeX3D(), writeX3dEdges(), and SVector3::z().
Member Data Documentation
P
double SPoint3::P[3] protected
Definition at line 16 of file SPoint3.h.
Referenced by c(), data(), discreteFrechetDistance(), distance(), getPosition(), operator double *(), operator std::array< double, 3 >(), operator*(), operator*=(), operator+=(), operator-=(), operator/=(), operator<(), operator=(), operator[](), position(), setPosition(), SPoint3(), transform(), x(), y(), and z().
The documentation for this class was generated from the following file:
src/geo/SPoint3.h