gmsh-TingyuanDoc: fullVector< scalar > Class Template Reference
fullVector< scalar > Class Template Reference
#include <MElement.h>
Public Member Functions
fullVector (void)
fullVector (int r)
fullVector (scalar *original, int r)
fullVector (const fullVector< scalar > &other)
~fullVector ()
int size () const
const scalar * getDataPtr () const
scalar * getDataPtr ()
scalar operator() (int i) const
scalar & operator() (int i)
fullVector< scalar > & operator= (const fullVector< scalar > &other)
void copy (const fullVector< scalar > &v, int i0, int ni, int desti0)
void set (int r, scalar v)
scalar norm () const
bool resize (int r, bool resetValue=true)
void setAsProxy (const fullVector< scalar > &original, int r_start, int r)
void setAsProxy (const fullMatrix< scalar > &original, int c)
void setAsProxy (scalar *data, int r)
void scale (const scalar s)
void setAll (const scalar &m)
void setAll (const fullVector< scalar > &m)
scalar operator* (const fullVector< scalar > &other)
void axpy (const fullVector< scalar > &x, scalar alpha=1.)
void multTByT (const fullVector< scalar > &x)
void print (const std::string name="", const std::string format="") const
void binarySave (FILE *f) const
void binaryLoad (FILE *f)
bool getOwnData () const
void setOwnData (bool ownData)
std::complex< double > norm () const
void print (const std::string name, const std::string format) const
Private Attributes
int _r
scalar * _data
bool _ownData
Friends
class fullMatrix< scalar >
Detailed Description
template<class scalar>
class fullVector< scalar >
Definition at line 26 of file MElement.h.
Constructor & Destructor Documentation
fullVector() [1/4]
template<class scalar > fullVector< scalar >::fullVector (void) inline
Definition at line 44 of file fullMatrix.h.
fullVector() [2/4]
template<class scalar > fullVector< scalar >::fullVector (int r) inline
Definition at line 46 of file fullMatrix.h.
fullVector() [3/4]
template<class scalar > fullVector< scalar >::fullVector (scalar * original, int r) inline
Definition at line 53 of file fullMatrix.h.
fullVector() [4/4]
template<class scalar > fullVector< scalar >::fullVector (const fullVector< scalar > & other) inline
Definition at line 60 of file fullMatrix.h.
~fullVector()
template<class scalar > fullVector< scalar >::~fullVector () inline
Definition at line 65 of file fullMatrix.h.
Member Function Documentation
axpy()
template<class scalar > void fullVector< scalar >::axpy (const fullVector< scalar > & x, scalar alpha = 1.) inline
Definition at line 194 of file fullMatrix.h.
Referenced by jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), and jacobianBasedQuality::_coeffDataICN::_computeLowerBound().
binaryLoad()
template<class scalar > void fullVector< scalar >::binaryLoad (FILE * f) inline
Definition at line 213 of file fullMatrix.h.
binarySave()
template<class scalar > void fullVector< scalar >::binarySave (FILE * f) const inline
Definition at line 212 of file fullMatrix.h.
copy()
template<class scalar > void fullVector< scalar >::copy (const fullVector< scalar > & v, int i0, int ni, int desti0) inline
Definition at line 86 of file fullMatrix.h.
getDataPtr() [1/2]
template<class scalar > scalar* fullVector< scalar >::getDataPtr () inline
Definition at line 71 of file fullMatrix.h.
getDataPtr() [2/2]
template<class scalar > const scalar* fullVector< scalar >::getDataPtr () const inline
Definition at line 70 of file fullMatrix.h.
Referenced by bezierCoeff::bezierCoeff(), and MElement::signedInvCondNumRange().
getOwnData()
template<class scalar > bool fullVector< scalar >::getOwnData () const inline
Definition at line 217 of file fullMatrix.h.
multTByT()
template<class scalar > void fullVector< scalar >::multTByT (const fullVector< scalar > & x) inline
Definition at line 207 of file fullMatrix.h.
norm() [1/2]
template<class scalar > scalar fullVector< scalar >::norm () const
Referenced by intersectCurveSurfaceData::apply(), SOrientedBoundingBox::buildOBB(), computeEquidistantParameters(), computeGLLParametersP6(), and newton_fd().
norm() [2/2]
std::complex< double > fullVector< std::complex< double > >::norm () const
Definition at line 443 of file fullMatrix.cpp.
operator()() [1/2]
template<class scalar > scalar& fullVector< scalar >::operator() (int i) inline
Definition at line 73 of file fullMatrix.h.
operator()() [2/2]
template<class scalar > scalar fullVector< scalar >::operator() (int i) const inline
Definition at line 72 of file fullMatrix.h.
operator*()
template<class scalar > scalar fullVector< scalar >::operator* (const fullVector< scalar > & other) inline
Definition at line 181 of file fullMatrix.h.
operator=()
template<class scalar > fullVector<scalar>& fullVector< scalar >::operator= (const fullVector< scalar > & other) inline
Definition at line 74 of file fullMatrix.h.
print() [1/2]
void fullVector< int >::print (const std::string name, const std::string format) const
Definition at line 463 of file fullMatrix.cpp.
print() [2/2]
template<class scalar > void fullVector< scalar >::print (const std::string name = "", const std::string format = "") const
resize()
template<class scalar > bool fullVector< scalar >::resize (int r, bool resetValue = true) inline
Definition at line 103 of file fullMatrix.h.
Referenced by _computeICN(), _computeIGE(), jacobianBasedQuality::_coeffDataICN::_computeLowerBound(), bezierBasisRaiser::computeCoeff(), CondNumBasis::CondNumBasis(), gaussIntegration::get(), LinearTermBase< T2 >::get(), LoadTerm< T1 >::get(), LoadTermOnBorder< T1 >::get(), bezierCoeff::getCornerCoeffs(), gmshGenerateOrderedPointsLine(), fullMatrix< double >::invert(), JacobianBasis::JacobianBasis(), fullVector< double >::operator=(), pts2fullMatrix(), and jacobianBasedQuality::sampleJacobianDeterminant().
scale()
template<class scalar > void fullVector< scalar >::scale (const scalar s) inline
Definition at line 144 of file fullMatrix.h.
Referenced by SOrientedBoundingBox::buildOBB(), distanceTerm::elementVector(), laplaceTerm::elementVector(), femTerm< scalar >::elementVector(), elasticityTerm::elementVector(), DummyfemTerm::elementVector(), LoadTerm< T1 >::get(), LoadTermOnBorder< T1 >::get(), JacobianBasis::getJacobianGeneral(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), and MElement::scaledJacRange().
set()
template<class scalar > void fullVector< scalar >::set (int r, scalar v) inline
Definition at line 91 of file fullMatrix.h.
Referenced by fullVector< double >::setAll().
setAll() [1/2]
template<class scalar > void fullVector< scalar >::setAll (const fullVector< scalar > & m) inline
Definition at line 167 of file fullMatrix.h.
setAll() [2/2]
template<class scalar > void fullVector< scalar >::setAll (const scalar & m) inline
Definition at line 158 of file fullMatrix.h.
Referenced by SOrientedBoundingBox::buildOBB(), fullVector< double >::fullVector(), LinearTermBase< T2 >::get(), CondNumBasis::getInvCondNumGeneral(), fullVector< double >::operator=(), and fullVector< double >::resize().
setAsProxy() [1/3]
template<class scalar > void fullVector< scalar >::setAsProxy (const fullMatrix< scalar > & original, int c) inline
Definition at line 129 of file fullMatrix.h.
setAsProxy() [2/3]
template<class scalar > void fullVector< scalar >::setAsProxy (const fullVector< scalar > & original, int r_start, int r) inline
Definition at line 119 of file fullMatrix.h.
Referenced by bezierCoeff::_computeCoefficients(), jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), jacobianBasedQuality::_coeffDataICN::_computeLowerBound(), and bezierCoeff::setVectorAsProxy().
setAsProxy() [3/3]
template<class scalar > void fullVector< scalar >::setAsProxy (scalar * data, int r) inline
Definition at line 137 of file fullMatrix.h.
setOwnData()
template<class scalar > void fullVector< scalar >::setOwnData (bool ownData) inline
Definition at line 218 of file fullMatrix.h.
size()
template<class scalar > int fullVector< scalar >::size () const inline
Definition at line 69 of file fullMatrix.h.
Referenced by jacobianBasedQuality::_coeffDataIGE::_computeAtCorner(), jacobianBasedQuality::_coeffDataICN::_computeAtCorner(), jacobianBasedQuality::_computeBoundRational(), _computeICN(), _computeIGE(), jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), jacobianBasedQuality::_coeffDataICN::_computeLowerBound(), bezierCoeff::bezierCoeff(), BilinearTermContract< T2 >::get(), PlusTerm< T2 >::get(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), jacobianBasedQuality::minMaxJacobianDeterminant(), newton_fd(), jacobianBasedQuality::sampleICNMeasure(), jacobianBasedQuality::sampleIGEMeasure(), and jacobianBasedQuality::sampleJacobianDeterminant().
Friends And Related Function Documentation
fullMatrix< scalar >
template<class scalar > friend class fullMatrix< scalar > friend
Definition at line 35 of file fullMatrix.h.
Member Data Documentation
_data
template<class scalar > scalar* fullVector< scalar >::_data private
Definition at line 34 of file fullMatrix.h.
Referenced by fullVector< double >::axpy(), fullVector< double >::binaryLoad(), fullVector< double >::binarySave(), fullMatrix< double >::eig(), fullVector< double >::fullVector(), fullVector< double >::getDataPtr(), fullMatrix< double >::invert(), fullMatrix< double >::luSolve(), fullMatrix< double >::mult(), fullMatrix< double >::multAddy(), fullVector< double >::multTByT(), fullVector< double >::operator()(), fullVector< double >::operator*(), fullVector< double >::operator=(), fullVector< double >::resize(), fullVector< double >::scale(), fullVector< double >::setAll(), fullVector< double >::setAsProxy(), and fullVector< double >::~fullVector().
_ownData
template<class scalar > bool fullVector< scalar >::_ownData private
Definition at line 35 of file fullMatrix.h.
Referenced by fullVector< double >::fullVector(), fullVector< double >::getOwnData(), fullVector< double >::resize(), fullVector< double >::setAsProxy(), fullVector< double >::setOwnData(), and fullVector< double >::~fullVector().
_r
template<class scalar > int fullVector< scalar >::_r private
Definition at line 33 of file fullMatrix.h.
Referenced by fullVector< double >::axpy(), fullVector< double >::binaryLoad(), fullVector< double >::binarySave(), fullMatrix< double >::eig(), fullVector< double >::fullVector(), fullMatrix< double >::luSolve(), fullMatrix< double >::mult(), fullMatrix< double >::multAddy(), fullVector< double >::multTByT(), fullVector< double >::operator*(), fullVector< double >::operator=(), fullVector< double >::resize(), fullVector< double >::scale(), fullVector< double >::set(), fullVector< double >::setAll(), fullVector< double >::setAsProxy(), and fullVector< double >::size().
The documentation for this class was generated from the following files:
src/geo/MElement.h
src/numeric/fullMatrix.h