gmsh-TingyuanDoc: onelab::parameterSpace Class Reference
onelab::parameterSpace Class Reference
#include <onelab.h>
Public Member Functions
parameterSpace ()
~parameterSpace ()
void clear (const std::string &name="", const std::string &client="")
bool set (const number &p, const std::string &client="")
bool set (const string &p, const std::string &client="")
bool get (std::vector< number > &ps, const std::string &name="", const std::string &client="")
bool get (std::vector< string > &ps, const std::string &name="", const std::string &client="")
void getPtr (number **ptr, const std::string &name, const std::string &client="")
void getPtr (string **ptr, const std::string &name, const std::string &client="")
void getAllParameters (std::set< parameter *, parameterLessThan > &ps) const
int getNumParameters ()
void getParameterNames (std::vector< std::string > &names, const std::string &search="") const
bool hasClient (const std::string &client) const
int getChanged (const std::string &client="") const
void setChanged (int changed, const std::string &client="")
void thresholdChanged (int threshold, const std::string &client="")
std::vector< std::string > toChar (const std::string &client="") const
bool fromChar (const std::vector< std::string > &msg, const std::string &client="")
bool toJSON (std::string &json, const std::string &creator="", const std::string &client="") const
bool fromJSON (const std::string &json, const std::string &client="")
bool fromJSON (const picojson::value::object &par, const std::string &client="")
Private Member Functions
template<class T >
bool _clear (const std::string &name, const std::string &client, std::set< T *, parameterLessThan > &ps)
template<class T >
bool _set (const T &p, const std::string &client, std::set< T *, parameterLessThan > &ps)
template<class T >
bool _get (std::vector< T > &p, const std::string &name, const std::string &client, std::set< T *, parameterLessThan > &ps)
template<class T >
T * _getPtr (std::string name, const std::string client, std::set< T *, parameterLessThan > ps)
Private Attributes
std::set< number *, parameterLessThan > _numbers
std::set< string *, parameterLessThan > _strings
std::mutex _mutex
Detailed Description
Definition at line 842 of file onelab.h.
Constructor & Destructor Documentation
parameterSpace()
onelab::parameterSpace::parameterSpace () inline
Definition at line 948 of file onelab.h.
~parameterSpace()
onelab::parameterSpace::~parameterSpace () inline
Definition at line 949 of file onelab.h.
Member Function Documentation
_clear()
template<class T > bool onelab::parameterSpace::_clear (const std::string & name, const std::string & client, std::set< T *, parameterLessThan > & ps) inline private
Definition at line 850 of file onelab.h.
Referenced by clear().
_get()
template<class T > bool onelab::parameterSpace::_get (std::vector< T > & p, const std::string & name, const std::string & client, std::set< T *, parameterLessThan > & ps) inline private
Definition at line 909 of file onelab.h.
Referenced by get().
_getPtr()
template<class T > T* onelab::parameterSpace::_getPtr (std::string name, const std::string client, std::set< T *, parameterLessThan > ps) inline private
Definition at line 931 of file onelab.h.
Referenced by getPtr().
_set()
template<class T > bool onelab::parameterSpace::_set (const T & p, const std::string & client, std::set< T *, parameterLessThan > & ps) inline private
Definition at line 885 of file onelab.h.
Referenced by set().
clear()
void onelab::parameterSpace::clear (const std::string & name = "", const std::string & client = "") inline
Definition at line 950 of file onelab.h.
Referenced by onelab::server::clear(), and ~parameterSpace().
fromChar()
bool onelab::parameterSpace::fromChar (const std::vector< std::string > & msg, const std::string & client = "") inline
Definition at line 1074 of file onelab.h.
Referenced by onelab::server::fromChar().
fromJSON() [1/2]
bool onelab::parameterSpace::fromJSON (const picojson::value::object & par, const std::string & client = "") inline
Definition at line 1176 of file onelab.h.
fromJSON() [2/2]
bool onelab::parameterSpace::fromJSON (const std::string & json, const std::string & client = "") inline
Definition at line 1122 of file onelab.h.
Referenced by onelab::server::fromJSON().
get() [1/2]
bool onelab::parameterSpace::get (std::vector< number > & ps, const std::string & name = "", const std::string & client = "") inline
Definition at line 972 of file onelab.h.
Referenced by onelab::server::get().
get() [2/2]
bool onelab::parameterSpace::get (std::vector< string > & ps, const std::string & name = "", const std::string & client = "") inline
Definition at line 977 of file onelab.h.
getAllParameters()
void onelab::parameterSpace::getAllParameters (std::set< parameter *, parameterLessThan > & ps) const inline
Definition at line 992 of file onelab.h.
Referenced by clear(), getChanged(), hasClient(), setChanged(), thresholdChanged(), toChar(), and toJSON().
getChanged()
int onelab::parameterSpace::getChanged (const std::string & client = "") const inline
Definition at line 1031 of file onelab.h.
Referenced by onelab::server::getChanged().
getNumParameters()
int onelab::parameterSpace::getNumParameters () inline
Definition at line 997 of file onelab.h.
Referenced by onelab::server::getNumParameters().
getParameterNames()
void onelab::parameterSpace::getParameterNames (std::vector< std::string > & names, const std::string & search = "") const inline
Definition at line 998 of file onelab.h.
Referenced by onelab::server::getParameterNames().
getPtr() [1/2]
void onelab::parameterSpace::getPtr (number ** ptr, const std::string & name, const std::string & client = "") inline
Definition at line 982 of file onelab.h.
getPtr() [2/2]
void onelab::parameterSpace::getPtr (string ** ptr, const std::string & name, const std::string & client = "") inline
Definition at line 987 of file onelab.h.
hasClient()
bool onelab::parameterSpace::hasClient (const std::string & client) const inline
Definition at line 1021 of file onelab.h.
set() [1/2]
bool onelab::parameterSpace::set (const number & p, const std::string & client = "") inline
Definition at line 964 of file onelab.h.
Referenced by fromChar(), fromJSON(), and onelab::server::set().
set() [2/2]
bool onelab::parameterSpace::set (const string & p, const std::string & client = "") inline
Definition at line 968 of file onelab.h.
setChanged()
void onelab::parameterSpace::setChanged (int changed, const std::string & client = "") inline
Definition at line 1043 of file onelab.h.
Referenced by onelab::server::setChanged().
thresholdChanged()
void onelab::parameterSpace::thresholdChanged (int threshold, const std::string & client = "") inline
Definition at line 1050 of file onelab.h.
Referenced by onelab::server::thresholdChanged().
toChar()
std::vector<std::string> onelab::parameterSpace::toChar (const std::string & client = "") const inline
Definition at line 1061 of file onelab.h.
Referenced by onelab::server::toChar().
toJSON()
bool onelab::parameterSpace::toJSON (std::string & json, const std::string & creator = "", const std::string & client = "") const inline
Definition at line 1096 of file onelab.h.
Referenced by onelab::server::toJSON().
Member Data Documentation
_mutex
std::mutex onelab::parameterSpace::_mutex private
Definition at line 846 of file onelab.h.
Referenced by _get(), _getPtr(), and _set().
_numbers
std::set<number *, parameterLessThan> onelab::parameterSpace::_numbers private
Definition at line 844 of file onelab.h.
Referenced by clear(), get(), getAllParameters(), getNumParameters(), getParameterNames(), getPtr(), and set().
_strings
std::set<string *, parameterLessThan> onelab::parameterSpace::_strings private
Definition at line 845 of file onelab.h.
Referenced by clear(), get(), getAllParameters(), getNumParameters(), getParameterNames(), getPtr(), and set().
The documentation for this class was generated from the following file:
src/common/onelab.h