gmsh-TingyuanDoc: gLevelsetQuadric Class Reference
gLevelsetQuadric Class Reference abstract
#include <gmshLevelset.h>
Public Member Functions
gLevelsetQuadric (int tag=0)
gLevelsetQuadric (const gLevelsetQuadric &)
virtual ~gLevelsetQuadric ()
double operator() (double x, double y, double z) const
virtual int type () const =0
Public Member Functions inherited from gLevelsetPrimitive
gLevelsetPrimitive ()
gLevelsetPrimitive (const gLevelsetPrimitive &lv)
gLevelsetPrimitive (int tag)
std::vector< gLevelset * > getChildren () const
double choose (double d1, double d2) const
virtual bool isPrimitive () const
Public Member Functions inherited from gLevelset
gLevelset (int tag=0)
gLevelset (const gLevelset &)
virtual ~gLevelset ()
virtual gLevelset * clone () const
bool isInsideDomain (const double &x, const double &y, const double &z) const
bool isOutsideDomain (const double &x, const double &y, const double &z) const
bool isOnBorder (const double &x, const double &y, const double &z) const
void setTag (int t)
virtual int getTag () const
void getPrimitives (std::vector< gLevelset * > &primitives)
void getPrimitivesPO (std::vector< gLevelset * > &primitives)
void getRPN (std::vector< gLevelset * > &gLsRPN)
double H (const double &x, const double &y, const double &z) const
void print () const
Public Member Functions inherited from simpleFunction< double >
simpleFunction (double val=0.0)
virtual ~simpleFunction ()
virtual bool hasDerivatives ()
virtual void setElement (MElement *e) const
virtual void gradient (double x, double y, double z, double &dfdx, double &dfdy, double &dfdz) const
virtual void hessian (double x, double y, double z, double &dfdxx, double &dfdxy, double &dfdxz, double &dfdyx, double &dfdyy, double &dfdyz, double &dfdzx, double &dfdzy, double &dfdzz) const
Protected Member Functions
void translate (const double transl[3])
void rotate (const double rotate[3][3])
void computeRotationMatrix (const double dir[3], double t[3][3])
void computeRotationMatrix (const double dir1[3], const double dir2[3], double t[3][3])
void Ax (const double x[3], double res[3], double fact=1.0)
void xAx (const double x[3], double &res, double fact=1.0)
void init ()
Protected Attributes
double A [3][3]
double B [3]
double C
Protected Attributes inherited from gLevelset
int tag_
Protected Attributes inherited from simpleFunction< double >
double _val
bool _hasDerivatives
Additional Inherited Members
Static Public Member Functions inherited from gLevelset
static gLevelset * find (int tag)
static void add (gLevelset *l)
Static Protected Attributes inherited from gLevelset
static const short insideDomain = -1
static int maxTag_ = 0
static std::set< gLevelset *, gLevelsetLessThan > all_
Detailed Description
Definition at line 250 of file gmshLevelset.h.
Constructor & Destructor Documentation
gLevelsetQuadric() [1/2]
gLevelsetQuadric::gLevelsetQuadric (int tag = 0) inline
Definition at line 263 of file gmshLevelset.h.
gLevelsetQuadric() [2/2]
gLevelsetQuadric::gLevelsetQuadric (const gLevelsetQuadric & lv)
Definition at line 610 of file gmshLevelset.cpp.
~gLevelsetQuadric()
virtual gLevelsetQuadric::~gLevelsetQuadric () inline virtual
Definition at line 265 of file gmshLevelset.h.
Member Function Documentation
Ax()
void gLevelsetQuadric::Ax (const double x[3], double res[3], double fact = 1.0) protected
Definition at line 620 of file gmshLevelset.cpp.
Referenced by translate().
computeRotationMatrix() [1/2]
void gLevelsetQuadric::computeRotationMatrix (const double dir1[3], const double dir2[3], double t[3][3]) protected
Definition at line 701 of file gmshLevelset.cpp.
computeRotationMatrix() [2/2]
void gLevelsetQuadric::computeRotationMatrix (const double dir[3], double t[3][3]) protected
Definition at line 677 of file gmshLevelset.cpp.
Referenced by gLevelsetCone::gLevelsetCone(), gLevelsetEllipsoid::gLevelsetEllipsoid(), gLevelsetGenCylinder::gLevelsetGenCylinder(), and gLevelsetGeneralQuadric::gLevelsetGeneralQuadric().
init()
void gLevelsetQuadric::init () protected
Definition at line 732 of file gmshLevelset.cpp.
Referenced by gLevelsetQuadric().
operator()()
double gLevelsetQuadric::operator() (double x, double y, double z) const virtual
Implements gLevelsetPrimitive.
Definition at line 741 of file gmshLevelset.cpp.
rotate()
void gLevelsetQuadric::rotate (const double rotate[3][3]) protected
Definition at line 648 of file gmshLevelset.cpp.
Referenced by gLevelsetCone::gLevelsetCone(), gLevelsetEllipsoid::gLevelsetEllipsoid(), gLevelsetGenCylinder::gLevelsetGenCylinder(), and gLevelsetGeneralQuadric::gLevelsetGeneralQuadric().
translate()
void gLevelsetQuadric::translate (const double transl[3]) protected
Definition at line 635 of file gmshLevelset.cpp.
Referenced by gLevelsetCone::gLevelsetCone(), gLevelsetEllipsoid::gLevelsetEllipsoid(), gLevelsetGenCylinder::gLevelsetGenCylinder(), and gLevelsetGeneralQuadric::gLevelsetGeneralQuadric().
type()
virtual int gLevelsetQuadric::type () const pure virtual
Implements gLevelsetPrimitive.
Implemented in gLevelsetGeneralQuadric, gLevelsetCone, gLevelsetEllipsoid, and gLevelsetGenCylinder.
xAx()
void gLevelsetQuadric::xAx (const double x[3], double & res, double fact = 1.0) protected
Definition at line 628 of file gmshLevelset.cpp.
Referenced by translate().
Member Data Documentation
A
double gLevelsetQuadric::A[3][3] protected
Definition at line 252 of file gmshLevelset.h.
Referenced by Ax(), gLevelsetCone::gLevelsetCone(), gLevelsetEllipsoid::gLevelsetEllipsoid(), gLevelsetGenCylinder::gLevelsetGenCylinder(), gLevelsetGeneralQuadric::gLevelsetGeneralQuadric(), gLevelsetQuadric(), init(), operator()(), rotate(), and xAx().
B
double gLevelsetQuadric::B[3] protected
Definition at line 252 of file gmshLevelset.h.
Referenced by gLevelsetGeneralQuadric::gLevelsetGeneralQuadric(), gLevelsetQuadric(), init(), operator()(), rotate(), and translate().
C
double gLevelsetQuadric::C protected
Definition at line 252 of file gmshLevelset.h.
Referenced by gLevelsetEllipsoid::gLevelsetEllipsoid(), gLevelsetGenCylinder::gLevelsetGenCylinder(), gLevelsetGeneralQuadric::gLevelsetGeneralQuadric(), gLevelsetQuadric(), init(), operator()(), and translate().
The documentation for this class was generated from the following files:
src/geo/gmshLevelset.h
src/geo/gmshLevelset.cpp