gmsh-TingyuanDoc: SPoint2 Class Reference
SPoint2 Class Reference
#include <SPoint2.h>
Public Member Functions
SPoint2 (double x=0.0, double y=0.0)
SPoint2 (double *p)
SPoint2 (const SPoint2 &pt)
virtual ~SPoint2 ()
void setPosition (double xx, double yy)
void getPosition (double *xx, double *yy) const
void position (double *) const
double x (void) const
double y (void) const
double & operator[] (int)
double operator[] (int) const
double distance (const SPoint2 &p) const
SPoint2 & operator= (const SPoint2 &p)
void operator+= (const SPoint2 &p)
void operator-= (const SPoint2 &p)
void operator*= (double mult)
SPoint2 operator* (double mult) const
operator double * ()
bool operator< (const SPoint2 &other) const
const double * data () const
double * data ()
Protected Attributes
double P [2]
Detailed Description
Definition at line 12 of file SPoint2.h.
Constructor & Destructor Documentation
SPoint2() [1/3]
SPoint2::SPoint2 (double x = 0.0, double y = 0.0) inline
Definition at line 17 of file SPoint2.h.
Referenced by operator*().
SPoint2() [2/3]
SPoint2::SPoint2 (double * p) inline
Definition at line 22 of file SPoint2.h.
SPoint2() [3/3]
SPoint2::SPoint2 (const SPoint2 & pt) inline
Definition at line 27 of file SPoint2.h.
~SPoint2()
virtual SPoint2::~SPoint2 () inline virtual
Definition at line 32 of file SPoint2.h.
Member Function Documentation
data() [1/2]
double* SPoint2::data () inline
Definition at line 55 of file SPoint2.h.
data() [2/2]
const double* SPoint2::data () const inline
Definition at line 54 of file SPoint2.h.
distance()
double SPoint2::distance (const SPoint2 & p) const inline
Definition at line 124 of file SPoint2.h.
Referenced by meshGeneratorPeriodic().
getPosition()
void SPoint2::getPosition (double * xx, double * yy) const inline
Definition at line 74 of file SPoint2.h.
operator double *()
SPoint2::operator double * () inline
Definition at line 46 of file SPoint2.h.
operator*()
SPoint2 SPoint2::operator* (double mult) const inline
Definition at line 119 of file SPoint2.h.
operator*=()
void SPoint2::operator*= (double mult) inline
Definition at line 113 of file SPoint2.h.
operator+=()
void SPoint2::operator+= (const SPoint2 & p) inline
Definition at line 101 of file SPoint2.h.
operator-=()
void SPoint2::operator-= (const SPoint2 & p) inline
Definition at line 107 of file SPoint2.h.
operator<()
bool SPoint2::operator< (const SPoint2 & other) const inline
Definition at line 47 of file SPoint2.h.
operator=()
SPoint2 & SPoint2::operator= (const SPoint2 & p) inline
Definition at line 90 of file SPoint2.h.
operator[]() [1/2]
double & SPoint2::operator[] (int i) inline
Definition at line 97 of file SPoint2.h.
operator[]() [2/2]
double SPoint2::operator[] (int i) const inline
Definition at line 99 of file SPoint2.h.
position()
void SPoint2::position (double * p) const inline
Definition at line 80 of file SPoint2.h.
setPosition()
void SPoint2::setPosition (double xx, double yy) inline
Definition at line 68 of file SPoint2.h.
Referenced by GFace::buildRepresentationCross(), and relocateSlaveVertices().
x()
double SPoint2::x (void) const inline
Definition at line 86 of file SPoint2.h.
Referenced by discreteFace::_debugParametrization(), _getAdditionalNodesOnBoundary(), _isItAGoodIdeaToMoveThatVertex(), _relocate(), blyr_manager::add_external_corner(), backgroundMesh::backgroundMesh(), bestParabola(), buildConsecutiveListOfVertices(), buildMeshGenerationDataStructures(), GFace::buildRepresentationCross(), centroidOfPolygon(), computeNeighbor(), computePointsUsingScaledCrossFieldPlanarP2(), discreteFace::containsParam(), GFace::containsParam(), GFace::curvatureDiv(), directions_storage(), distance(), getIntersection(), gmshPolarSphere::getMetricEigenvalue(), getNodeCopies(), improved_translate(), SurfaceProjector::initialize(), InterpolateBezier(), intersection_segments(), LENGTH(), DocRecord::makePosView(), metric_based_on_surface_curvature(), MYxyz2uvw(), gmshFace::normal(), operator+(), operator-(), outputScalarField(), gmshSurface::point(), GFace::point(), DocRecord::printMedialAxis(), backgroundMesh::propagateCrossFieldByDistance(), propagateValuesOnFace(), SPoint2(), GFace::storeSTLAsMesh(), triangleQualityP2(), backgroundMesh::updateSizes(), gmshVertex::writeGEO(), and gmshVertex::writePY().
y()
double SPoint2::y (void) const inline
Definition at line 88 of file SPoint2.h.
Referenced by discreteFace::_debugParametrization(), _getAdditionalNodesOnBoundary(), _isItAGoodIdeaToMoveThatVertex(), _relocate(), blyr_manager::add_external_corner(), backgroundMesh::backgroundMesh(), bestParabola(), buildConsecutiveListOfVertices(), GFace::buildRepresentationCross(), centroidOfPolygon(), computeNeighbor(), computePointsUsingScaledCrossFieldPlanarP2(), discreteFace::containsParam(), GFace::containsParam(), GFace::curvatureDiv(), directions_storage(), distance(), getIntersection(), gmshPolarSphere::getMetricEigenvalue(), getNodeCopies(), improved_translate(), SurfaceProjector::initialize(), InterpolateBezier(), intersection_segments(), LENGTH(), DocRecord::makePosView(), metric_based_on_surface_curvature(), MYxyz2uvw(), gmshFace::normal(), operator+(), operator-(), outputScalarField(), gmshSurface::point(), GFace::point(), DocRecord::printMedialAxis(), backgroundMesh::propagateCrossFieldByDistance(), propagateValuesOnFace(), SPoint2(), GFace::storeSTLAsMesh(), triangleQualityP2(), backgroundMesh::updateSizes(), gmshVertex::writeGEO(), and gmshVertex::writePY().
Member Data Documentation
P
double SPoint2::P[2] protected
Definition at line 14 of file SPoint2.h.
Referenced by data(), distance(), getPosition(), operator double *(), operator*(), operator*=(), operator+=(), operator-=(), operator<(), operator=(), operator[](), position(), setPosition(), SPoint2(), x(), and y().
The documentation for this class was generated from the following file:
src/geo/SPoint2.h