gmsh-TingyuanDoc: discreteList Class Reference
discreteList Class Reference
Public Member Functions
int insertPoint (int pos, const SPoint3 &pt, double t)
void sort (std::vector< SPoint3 > &spts, std::vector< double > &ts)
discreteList ()
Private Attributes
std::vector< std::pair< SPoint3, double > > _pts
std::vector< int > _next
Detailed Description
Definition at line 15 of file gmshEdgeDiscretize.cpp.
Constructor & Destructor Documentation
discreteList()
discreteList::discreteList () inline
Definition at line 38 of file gmshEdgeDiscretize.cpp.
Member Function Documentation
insertPoint()
int discreteList::insertPoint (int pos, const SPoint3 & pt, double t) inline
Definition at line 20 of file gmshEdgeDiscretize.cpp.
Referenced by decasteljau(), and discretizeBezier().
sort()
void discreteList::sort (std::vector< SPoint3 > & spts, std::vector< double > & ts) inline
Definition at line 27 of file gmshEdgeDiscretize.cpp.
Referenced by discretizeCurve().
Member Data Documentation
_next
std::vector<int> discreteList::_next private
Definition at line 17 of file gmshEdgeDiscretize.cpp.
Referenced by discreteList(), insertPoint(), and sort().
_pts
std::vector<std::pair<SPoint3, double> > discreteList::_pts private
Definition at line 16 of file gmshEdgeDiscretize.cpp.
Referenced by insertPoint(), and sort().
The documentation for this class was generated from the following file:
src/geo/gmshEdgeDiscretize.cpp