gmsh-TingyuanDoc: MTet4 Class Reference
MTet4 Class Reference
#include <meshGRegionDelaunayInsertion.h>
Public Member Functions
~MTet4 ()
MTet4 ()
MTet4 (MTetrahedron *t, double qual)
MTet4 (MTetrahedron *t, const qmTetrahedron::Measures &qm)
void circumcenter (double *res)
void setup (MTetrahedron *t, std::vector< double > &sizes, std::vector< double > &sizesBGM)
void setup (MTetrahedron *t, std::vector< double > &sizes, std::vector< double > &sizesBGM, double lcA, double lcB)
GRegion * onWhat () const
void setOnWhat (GRegion *g)
bool isDeleted () const
void forceRadius (double r)
double getRadius () const
double getQuality () const
void setQuality (const double &q)
MTetrahedron * tet () const
MTetrahedron *& tet ()
void setTet (MTetrahedron *t)
void setNeigh (int iN, MTet4 *n)
MTet4 * getNeigh (int iN) const
int inCircumSphere (const double *p) const
int inCircumSphere (double x, double y, double z) const
int inCircumSphere (const MVertex *v) const
double getVolume () const
void setDeleted (bool const d)
bool assertNeigh () const
bool isNeigh (const MTet4 *t) const
Static Public Attributes
static int radiusNorm = 2
Private Attributes
bool deleted
double circum_radius
MTetrahedron * base
MTet4 * neigh [4]
GRegion * gr
Friends
class MTet4Factory
Detailed Description
Definition at line 46 of file meshGRegionDelaunayInsertion.h.
Constructor & Destructor Documentation
~MTet4()
MTet4::~MTet4 () inline
Definition at line 58 of file meshGRegionDelaunayInsertion.h.
MTet4() [1/3]
MTet4::MTet4 () inline
Definition at line 59 of file meshGRegionDelaunayInsertion.h.
MTet4() [2/3]
MTet4::MTet4 (MTetrahedron * t, double qual) inline
Definition at line 63 of file meshGRegionDelaunayInsertion.h.
MTet4() [3/3]
MTet4::MTet4 (MTetrahedron * t, const qmTetrahedron::Measures & qm) inline
Definition at line 68 of file meshGRegionDelaunayInsertion.h.
Member Function Documentation
assertNeigh()
bool MTet4::assertNeigh () const inline
Definition at line 195 of file meshGRegionDelaunayInsertion.h.
circumcenter()
void MTet4::circumcenter (double * res) inline
Definition at line 75 of file meshGRegionDelaunayInsertion.h.
Referenced by MTetrahedron::circumcenter(), and setup().
forceRadius()
void MTet4::forceRadius (double r) inline
Definition at line 163 of file meshGRegionDelaunayInsertion.h.
Referenced by MTet4Factory::changeTetRadius().
getNeigh()
MTet4* MTet4::getNeigh (int iN) const inline
Definition at line 171 of file meshGRegionDelaunayInsertion.h.
Referenced by buildEdgeCavity(), buildVertexCavity_recur(), computeNeighboringTetsOfACavity(), extendCavity(), faceSwap(), findCavity(), insertVertexB(), makeCavityStarShaped(), non_recursive_classify(), and removeFromCavity().
getQuality()
double MTet4::getQuality () const inline
Definition at line 165 of file meshGRegionDelaunayInsertion.h.
Referenced by faceSwap().
getRadius()
double MTet4::getRadius () const inline
Definition at line 164 of file meshGRegionDelaunayInsertion.h.
Referenced by insertVerticesInRegion(), and compareTet4Ptr::operator()().
getVolume()
double MTet4::getVolume () const inline
Definition at line 182 of file meshGRegionDelaunayInsertion.h.
inCircumSphere() [1/3]
int MTet4::inCircumSphere (const double * p) const
Definition at line 150 of file meshGRegionDelaunayInsertion.cpp.
Referenced by findCavity(), and inCircumSphere().
inCircumSphere() [2/3]
int MTet4::inCircumSphere (const MVertex * v) const inline
Definition at line 178 of file meshGRegionDelaunayInsertion.h.
inCircumSphere() [3/3]
int MTet4::inCircumSphere (double x, double y, double z) const inline
Definition at line 173 of file meshGRegionDelaunayInsertion.h.
isDeleted()
bool MTet4::isDeleted () const inline
Definition at line 162 of file meshGRegionDelaunayInsertion.h.
Referenced by buildEdgeCavity(), buildVertexCavity_recur(), collapseVertex(), connectTets_vector2_templ(), findCavity(), insertVerticesInRegion(), and smoothVertex().
isNeigh()
bool MTet4::isNeigh (const MTet4 * t) const inline
Definition at line 202 of file meshGRegionDelaunayInsertion.h.
Referenced by assertNeigh().
onWhat()
GRegion* MTet4::onWhat () const inline
Definition at line 160 of file meshGRegionDelaunayInsertion.h.
Referenced by faceSwap(), findCavity(), insertVertexB(), insertVerticesInRegion(), makeCavityStarShaped(), and non_recursive_classify().
setDeleted()
void MTet4::setDeleted (bool const d) inline
Definition at line 194 of file meshGRegionDelaunayInsertion.h.
Referenced by extendCavity(), faceSwap(), findCavity(), MTet4Factory::Free(), and removeFromCavity().
setNeigh()
void MTet4::setNeigh (int iN, MTet4 * n) inline
Definition at line 170 of file meshGRegionDelaunayInsertion.h.
Referenced by connectTets_vector2_templ().
setOnWhat()
void MTet4::setOnWhat (GRegion * g) inline
Definition at line 161 of file meshGRegionDelaunayInsertion.h.
Referenced by collapseVertex(), edgeSplit(), edgeSwap(), faceSwap(), insertVertexB(), non_recursive_classify(), and optimizeMesh().
setQuality()
void MTet4::setQuality (const double & q) inline
Definition at line 166 of file meshGRegionDelaunayInsertion.h.
Referenced by collapseVertex().
setTet()
void MTet4::setTet (MTetrahedron * t) inline
Definition at line 169 of file meshGRegionDelaunayInsertion.h.
setup() [1/2]
void MTet4::setup (MTetrahedron * t, std::vector< double > & sizes, std::vector< double > & sizesBGM) inline
Definition at line 88 of file meshGRegionDelaunayInsertion.h.
Referenced by MTet4Factory::Create().
setup() [2/2]
void MTet4::setup (MTetrahedron * t, std::vector< double > & sizes, std::vector< double > & sizesBGM, double lcA, double lcB) inline
Definition at line 125 of file meshGRegionDelaunayInsertion.h.
tet() [1/2]
MTetrahedron*& MTet4::tet () inline
Definition at line 168 of file meshGRegionDelaunayInsertion.h.
tet() [2/2]
MTetrahedron* MTet4::tet () const inline
Definition at line 167 of file meshGRegionDelaunayInsertion.h.
Referenced by buildEdgeCavity(), buildVertexCavity_recur(), collapseVertex(), faceSwap(), faceXtet::faceXtet(), MTet4Factory::Free(), insertVerticesInRegion(), non_recursive_classify(), compareTet4Ptr::operator()(), smoothVertex(), smoothVertexOptimize(), and faceXtet::visible().
Friends And Related Function Documentation
MTet4Factory
friend class MTet4Factory friend
Definition at line 47 of file meshGRegionDelaunayInsertion.h.
Member Data Documentation
base
MTetrahedron* MTet4::base private
Definition at line 52 of file meshGRegionDelaunayInsertion.h.
Referenced by circumcenter(), getVolume(), inCircumSphere(), setTet(), setup(), and tet().
circum_radius
double MTet4::circum_radius private
Definition at line 51 of file meshGRegionDelaunayInsertion.h.
Referenced by forceRadius(), getQuality(), getRadius(), MTet4(), setQuality(), and setup().
deleted
bool MTet4::deleted private
Definition at line 50 of file meshGRegionDelaunayInsertion.h.
Referenced by assertNeigh(), isDeleted(), setDeleted(), and setup().
gr
GRegion* MTet4::gr private
Definition at line 54 of file meshGRegionDelaunayInsertion.h.
Referenced by onWhat(), and setOnWhat().
neigh
MTet4* MTet4::neigh[4] private
Definition at line 53 of file meshGRegionDelaunayInsertion.h.
Referenced by assertNeigh(), getNeigh(), isNeigh(), MTet4(), setNeigh(), and setup().
radiusNorm
int MTet4::radiusNorm = 2 static
Definition at line 57 of file meshGRegionDelaunayInsertion.h.
The documentation for this class was generated from the following files:
src/mesh/meshGRegionDelaunayInsertion.h
src/mesh/meshGRegionDelaunayInsertion.cpp