gmsh-TingyuanDoc: PViewDataGModel Class Reference
PViewDataGModel Class Reference
#include <PViewDataGModel.h>
Public Types
enum DataType {
NodeData = 1, ElementData = 2, ElementNodeData = 3, GaussPointData = 4,
BeamData = 5
}
Public Member Functions
PViewDataGModel (DataType type=NodeData)
~PViewDataGModel ()
bool finalize (bool computeMinMax=true, const std::string &interpolationScheme="")
std::string getFileName (int step=-1)
int getNumTimeSteps ()
int getFirstNonEmptyTimeStep (int start=0)
double getTime (int step)
double getMin (int step=-1, bool onlyVisible=false, int tensorRep=0, int forceNumComponents=0, int componentMap[9]=nullptr)
double getMax (int step=-1, bool onlyVisible=false, int tensorRep=0, int forceNumComponents=0, int componentMap[9]=nullptr)
void setMin (double min)
void setMax (double max)
SBoundingBox3d getBoundingBox (int step=-1)
void setBoundingBox (SBoundingBox3d &box)
int getNumScalars (int step=-1)
int getNumVectors (int step=-1)
int getNumTensors (int step=-1)
int getNumPoints (int step=-1)
int getNumLines (int step=-1)
int getNumTriangles (int step=-1)
int getNumQuadrangles (int step=-1)
int getNumPolygons (int step=-1)
int getNumTetrahedra (int step=-1)
int getNumHexahedra (int step=-1)
int getNumPrisms (int step=-1)
int getNumPyramids (int step=-1)
int getNumTrihedra (int step=-1)
int getNumPolyhedra (int step=-1)
int getNumEntities (int step=-1)
int getNumElements (int step=-1, int ent=-1)
int getDimension (int step, int ent, int ele)
int getNumNodes (int step, int ent, int ele)
int getNode (int step, int ent, int ele, int nod, double &x, double &y, double &z)
void setNode (int step, int ent, int ele, int nod, double x, double y, double z)
void tagNode (int step, int ent, int ele, int nod, int tag)
int getNumComponents (int step, int ent, int ele)
int getNumValues (int step, int ent, int ele)
void getValue (int step, int ent, int ele, int idx, double &val)
void getValue (int step, int ent, int ele, int node, int comp, double &val)
void setValue (int step, int ent, int ele, int node, int comp, double val)
int getNumEdges (int step, int ent, int ele)
int getType (int step, int ent, int ele)
void reverseElement (int step, int ent, int ele)
void smooth ()
double getMemoryInMb ()
bool combineTime (nameData &nd)
bool skipEntity (int step, int ent)
bool skipElement (int step, int ent, int ele, bool checkVisibility=false, int samplingRate=1)
bool hasTimeStep (int step)
bool hasPartition (int step, int part)
bool hasMultipleMeshes ()
bool hasModel (GModel *model, int step=-1)
bool isNodeData ()
bool useGaussPoints ()
GModel * getModel (int step)
GEntity * getEntity (int step, int ent)
MElement * getElement (int step, int entity, int element)
DataType getType ()
bool getValueByIndex (int step, int dataIndex, int node, int comp, double &val)
bool addData (GModel *model, const std::map< int, std::vector< double > > &data, int step, double time, int partition, int numComp)
bool addData (GModel *model, const std::vector< std::size_t > &tags, const std::vector< std::vector< double > > &data, int step, double time, int partition, int numComp)
bool addData (GModel *model, const std::vector< std::size_t > &tags, const std::vector< double > &data, int step, double time, int partition, int numComp)
void destroyData ()
bool readMSH (const std::string &viewName, const std::string &fileName, int fileIndex, FILE *fp, bool binary, bool swap, int step, double time, int partition, int numComp, int numNodes, const std::string &interpolationScheme)
virtual bool writeMSH (const std::string &fileName, double version=2.2, bool binary=false, bool savemesh=true, bool multipleView=false, int partitionNum=-1, bool saveInterpolationMatrices=true, bool forceNodeData=false, bool forceElementData=false)
bool readCGNS (const std::pair< std::string, std::string > &solFieldName, const std::string &fileName, int index, int fileIndex, int baseIndex, const std::vector< std::vector< MVertex * > > &vertPerZone, const std::vector< std::vector< MElement * > > &eltPerZone)
bool readMED (const std::string &fileName, int fileIndex)
bool writeMED (const std::string &fileName)
bool readPCH (const std::string &fileName, int fileIndex)
void importLists (int N[24], std::vector< double > *V[24])
stepData< double > * getStepData (int step)
void sendToServer (const std::string &name)
Public Member Functions inherited from PViewData
PViewData ()
virtual ~PViewData ()
virtual bool getDirty ()
virtual void setDirty (bool val)
virtual std::string getName ()
virtual void setName (const std::string &val)
virtual void setFileName (const std::string &val)
virtual bool hasFileName (const std::string &val)
virtual int getFileIndex ()
virtual void setFileIndex (int val)
void getScalarValue (int step, int ent, int ele, int nod, double &val, int tensorRep=0, int forceNumComponents=0, int componentMap[9]=nullptr)
virtual int getNumStrings2D ()
virtual int getNumStrings3D ()
virtual void getString2D (int i, int step, std::string &str, double &x, double &y, double &style)
virtual void getString3D (int i, int step, std::string &str, double &x, double &y, double &z, double &style)
virtual bool empty ()
void initAdaptiveData (int step, int level, double tol)
void initAdaptiveDataLight (int step, int level, double tol)
void saveAdaptedViewForVTK (const std::string &guifileName, int useDefaultName, int step, int level, double tol, int npart, bool isBinary)
void destroyAdaptiveData ()
adaptiveData * getAdaptiveData ()
void setInterpolationMatrices (int type, const fullMatrix< double > &coefVal, const fullMatrix< double > &expVal)
void setInterpolationMatrices (int type, const fullMatrix< double > &coefVal, const fullMatrix< double > &expVal, const fullMatrix< double > &coefGeo, const fullMatrix< double > &expGeo)
int getInterpolationMatrices (int type, std::vector< fullMatrix< double > * > &p)
bool haveInterpolationMatrices (int type=0)
void deleteInterpolationMatrices (int type=0)
std::string getInterpolationSchemeName ()
void setInterpolationSchemeName (std::string name)
virtual bool combineSpace (nameData &nd)
virtual void setXY (std::vector< double > &x, std::vector< double > &y)
virtual void setXYZV (std::vector< double > &x, std::vector< double > &y, std::vector< double > &z, std::vector< double > &v)
virtual bool isRemote ()
virtual int fillRemoteVertexArrays (std::string &options)
virtual bool isListBased ()
double findClosestNode (double &xn, double &yn, double &zn, int step)
bool searchScalar (double x, double y, double z, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchVector (double x, double y, double z, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchTensor (double x, double y, double z, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchScalarClosest (double x, double y, double z, double &distance, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchVectorClosest (double x, double y, double z, double &distance, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
bool searchTensorClosest (double x, double y, double z, double &distance, double *values, int step=-1, double *size=nullptr, int qn=0, double *qx=nullptr, double *qy=nullptr, double *qz=nullptr, bool grad=false, int dim=-1)
virtual bool writeSTL (const std::string &fileName)
virtual bool writeTXT (const std::string &fileName)
virtual bool writePOS (const std::string &fileName, bool binary=false, bool parsed=true, bool append=false)
virtual bool toVector (std::vector< std::vector< double > > &vec)
virtual bool fromVector (const std::vector< std::vector< double > > &vec)
virtual void getListPointers (int N[24], std::vector< double > *V[24])
Private Member Functions
MElement * _getElement (int step, int ent, int ele)
MVertex * _getNode (MElement *e, int nod)
Private Attributes
std::vector< stepData< double > * > _steps
double _min
double _max
DataType _type
Additional Inherited Members
Static Public Member Functions inherited from PViewData
static void removeInterpolationScheme (const std::string &name)
static void removeAllInterpolationSchemes ()
static void addMatrixToInterpolationScheme (const std::string &name, int type, fullMatrix< double > &mat)
static int getSizeInterpolationScheme ()
Protected Attributes inherited from PViewData
adaptiveData * _adaptive
interpolationMatrices _interpolation
std::string _interpolationSchemeName
Static Protected Attributes inherited from PViewData
static std::map< std::string, interpolationMatrices > _interpolationSchemes
Detailed Description
Definition at line 191 of file PViewDataGModel.h.
Member Enumeration Documentation
DataType
enum PViewDataGModel::DataType
Enumerator
NodeData
ElementData
ElementNodeData
GaussPointData
BeamData
Definition at line 193 of file PViewDataGModel.h.
Constructor & Destructor Documentation
PViewDataGModel()
PViewDataGModel::PViewDataGModel (DataType type = NodeData)
Definition at line 21 of file PViewDataGModel.cpp.
~PViewDataGModel()
PViewDataGModel::~PViewDataGModel ()
Definition at line 26 of file PViewDataGModel.cpp.
Member Function Documentation
_getElement()
MElement * PViewDataGModel::_getElement (int step, int ent, int ele) private
Definition at line 255 of file PViewDataGModel.cpp.
Referenced by getDimension(), getNode(), getNumEdges(), getNumNodes(), getNumValues(), getType(), getValue(), reverseElement(), setNode(), setValue(), skipElement(), and tagNode().
_getNode()
MVertex * PViewDataGModel::_getNode (MElement * e, int nod) private
Definition at line 534 of file PViewDataGModel.cpp.
Referenced by getNode(), getValue(), setNode(), setValue(), skipElement(), and tagNode().
addData() [1/3]
bool PViewDataGModel::addData (GModel * model, const std::map< int, std::vector< double > > & data, int step, double time, int partition, int numComp)
Definition at line 19 of file PViewDataGModelIO.cpp.
Referenced by _addModelData(), PView::addStep(), PView::PView(), and readPCH().
addData() [2/3]
bool PViewDataGModel::addData (GModel * model, const std::vector< std::size_t > & tags, const std::vector< double > & data, int step, double time, int partition, int numComp)
Definition at line 90 of file PViewDataGModelIO.cpp.
addData() [3/3]
bool PViewDataGModel::addData (GModel * model, const std::vector< std::size_t > & tags, const std::vector< std::vector< double > > & data, int step, double time, int partition, int numComp)
Definition at line 52 of file PViewDataGModelIO.cpp.
combineTime()
bool PViewDataGModel::combineTime (nameData & nd) virtual
Reimplemented from PViewData.
Definition at line 764 of file PViewDataGModel.cpp.
destroyData()
void PViewDataGModel::destroyData ()
Definition at line 130 of file PViewDataGModelIO.cpp.
finalize()
bool PViewDataGModel::finalize (bool computeMinMax = true, const std::string & interpolationScheme = "") virtual
Reimplemented from PViewData.
Definition at line 88 of file PViewDataGModel.cpp.
Referenced by addData(), combineTime(), importLists(), readMSH(), and smooth().
getBoundingBox()
SBoundingBox3d PViewDataGModel::getBoundingBox (int step = -1) virtual
Implements PViewData.
Definition at line 337 of file PViewDataGModel.cpp.
getDimension()
int PViewDataGModel::getDimension (int step, int ent, int ele) virtual
Reimplemented from PViewData.
Definition at line 515 of file PViewDataGModel.cpp.
getElement()
MElement * PViewDataGModel::getElement (int step, int entity, int element) virtual
Reimplemented from PViewData.
Definition at line 507 of file PViewDataGModel.cpp.
getEntity()
GEntity * PViewDataGModel::getEntity (int step, int ent) virtual
Reimplemented from PViewData.
Definition at line 502 of file PViewDataGModel.cpp.
getFileName()
std::string PViewDataGModel::getFileName (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 264 of file PViewDataGModel.cpp.
Referenced by smooth().
getFirstNonEmptyTimeStep()
int PViewDataGModel::getFirstNonEmptyTimeStep (int start = 0) virtual
Reimplemented from PViewData.
Definition at line 272 of file PViewDataGModel.cpp.
getMax()
double PViewDataGModel::getMax (int step = -1, bool onlyVisible = false, int tensorRep = 0, int forceNumComponents = 0, int componentMap[9] = nullptr) virtual
Implements PViewData.
Definition at line 311 of file PViewDataGModel.cpp.
Referenced by finalize(), and readMSH().
getMemoryInMb()
double PViewDataGModel::getMemoryInMb () virtual
Reimplemented from PViewData.
Definition at line 756 of file PViewDataGModel.cpp.
getMin()
double PViewDataGModel::getMin (int step = -1, bool onlyVisible = false, int tensorRep = 0, int forceNumComponents = 0, int componentMap[9] = nullptr) virtual
Implements PViewData.
Definition at line 285 of file PViewDataGModel.cpp.
Referenced by finalize(), and readMSH().
getModel()
GModel* PViewDataGModel::getModel (int step) inline virtual
Reimplemented from PViewData.
Definition at line 272 of file PViewDataGModel.h.
Referenced by hasModel(), hasMultipleMeshes(), OctreePost::searchScalar(), OctreePost::searchTensor(), OctreePost::searchVector(), and writeMSH().
getNode()
int PViewDataGModel::getNode (int step, int ent, int ele, int nod, double & x, double & y, double & z) virtual
Reimplemented from PViewData.
Definition at line 546 of file PViewDataGModel.cpp.
getNumComponents()
int PViewDataGModel::getNumComponents (int step, int ent, int ele) virtual
Reimplemented from PViewData.
Definition at line 597 of file PViewDataGModel.cpp.
Referenced by OctreePost::_getValue(), getNumScalars(), getNumTensors(), getNumValues(), and getNumVectors().
getNumEdges()
int PViewDataGModel::getNumEdges (int step, int ent, int ele) virtual
Reimplemented from PViewData.
Definition at line 695 of file PViewDataGModel.cpp.
getNumElements()
int PViewDataGModel::getNumElements (int step = -1, int ent = -1) virtual
Reimplemented from PViewData.
Definition at line 492 of file PViewDataGModel.cpp.
Referenced by finalize(), getMax(), getMin(), getNumScalars(), getNumTensors(), getNumVectors(), and smooth().
getNumEntities()
int PViewDataGModel::getNumEntities (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 484 of file PViewDataGModel.cpp.
Referenced by finalize(), getMax(), getMin(), and smooth().
getNumHexahedra()
int PViewDataGModel::getNumHexahedra (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 434 of file PViewDataGModel.cpp.
getNumLines()
int PViewDataGModel::getNumLines (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 384 of file PViewDataGModel.cpp.
getNumNodes()
int PViewDataGModel::getNumNodes (int step, int ent, int ele) virtual
Reimplemented from PViewData.
Definition at line 520 of file PViewDataGModel.cpp.
Referenced by finalize(), getMax(), getMin(), getNumValues(), and skipElement().
getNumPoints()
int PViewDataGModel::getNumPoints (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 374 of file PViewDataGModel.cpp.
getNumPolygons()
int PViewDataGModel::getNumPolygons (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 414 of file PViewDataGModel.cpp.
getNumPolyhedra()
int PViewDataGModel::getNumPolyhedra (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 474 of file PViewDataGModel.cpp.
getNumPrisms()
int PViewDataGModel::getNumPrisms (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 444 of file PViewDataGModel.cpp.
getNumPyramids()
int PViewDataGModel::getNumPyramids (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 454 of file PViewDataGModel.cpp.
getNumQuadrangles()
int PViewDataGModel::getNumQuadrangles (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 404 of file PViewDataGModel.cpp.
getNumScalars()
int PViewDataGModel::getNumScalars (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 350 of file PViewDataGModel.cpp.
getNumTensors()
int PViewDataGModel::getNumTensors (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 366 of file PViewDataGModel.cpp.
getNumTetrahedra()
int PViewDataGModel::getNumTetrahedra (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 424 of file PViewDataGModel.cpp.
getNumTimeSteps()
int PViewDataGModel::getNumTimeSteps () virtual
Implements PViewData.
Definition at line 270 of file PViewDataGModel.cpp.
Referenced by OctreePost::_getValue(), PView::addStep(), finalize(), hasPartition(), hasTimeStep(), OctreePost::searchScalar(), OctreePost::searchTensor(), OctreePost::searchVector(), skipElement(), and skipEntity().
getNumTriangles()
int PViewDataGModel::getNumTriangles (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 394 of file PViewDataGModel.cpp.
getNumTrihedra()
int PViewDataGModel::getNumTrihedra (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 464 of file PViewDataGModel.cpp.
getNumValues()
int PViewDataGModel::getNumValues (int step, int ent, int ele) virtual
Reimplemented from PViewData.
Definition at line 602 of file PViewDataGModel.cpp.
getNumVectors()
int PViewDataGModel::getNumVectors (int step = -1) virtual
Reimplemented from PViewData.
Definition at line 358 of file PViewDataGModel.cpp.
getStepData()
stepData<double>* PViewDataGModel::getStepData (int step) inline
Definition at line 321 of file PViewDataGModel.h.
Referenced by gmshViewGetModelData().
getTime()
double PViewDataGModel::getTime (int step) virtual
Reimplemented from PViewData.
Definition at line 279 of file PViewDataGModel.cpp.
Referenced by smooth(), and writeMSH().
getType() [1/2]
DataType PViewDataGModel::getType () inline
Definition at line 277 of file PViewDataGModel.h.
getType() [2/2]
int PViewDataGModel::getType (int step, int ent, int ele) virtual
Reimplemented from PViewData.
Definition at line 700 of file PViewDataGModel.cpp.
Referenced by _addModelData(), OctreePost::_getValue(), PView::combine(), and gmshViewGetModelData().
getValue() [1/2]
void PViewDataGModel::getValue (int step, int ent, int ele, int idx, double & val) virtual
Reimplemented from PViewData.
Definition at line 621 of file PViewDataGModel.cpp.
getValue() [2/2]
void PViewDataGModel::getValue (int step, int ent, int ele, int node, int comp, double & val) virtual
Reimplemented from PViewData.
Definition at line 639 of file PViewDataGModel.cpp.
getValueByIndex()
bool PViewDataGModel::getValueByIndex (int step, int dataIndex, int node, int comp, double & val)
Definition at line 863 of file PViewDataGModel.cpp.
Referenced by OctreePost::_getValue(), and smooth().
hasModel()
bool PViewDataGModel::hasModel (GModel * model, int step = -1) virtual
Reimplemented from PViewData.
Definition at line 853 of file PViewDataGModel.cpp.
hasMultipleMeshes()
bool PViewDataGModel::hasMultipleMeshes () virtual
Reimplemented from PViewData.
Definition at line 844 of file PViewDataGModel.cpp.
Referenced by writeMSH().
hasPartition()
bool PViewDataGModel::hasPartition (int step, int part) virtual
Reimplemented from PViewData.
Definition at line 837 of file PViewDataGModel.cpp.
hasTimeStep()
bool PViewDataGModel::hasTimeStep (int step) virtual
Reimplemented from PViewData.
Definition at line 830 of file PViewDataGModel.cpp.
Referenced by OctreePost::_getValue(), and combineTime().
importLists()
void PViewDataGModel::importLists (int N[24], std::vector< double > * V[24]) virtual
Reimplemented from PViewData.
Definition at line 418 of file PViewDataGModelIO.cpp.
isNodeData()
bool PViewDataGModel::isNodeData () inline virtual
Reimplemented from PViewData.
Definition at line 270 of file PViewDataGModel.h.
readCGNS()
bool PViewDataGModel::readCGNS (const std::pair< std::string, std::string > & solFieldName, const std::string & fileName, int index, int fileIndex, int baseIndex, const std::vector< std::vector< MVertex * > > & vertPerZone, const std::vector< std::vector< MElement * > > & eltPerZone)
Definition at line 627 of file PViewDataGModelIO_CGNS.cpp.
readMED()
bool PViewDataGModel::readMED (const std::string & fileName, int fileIndex)
Definition at line 1091 of file PViewDataGModelIO.cpp.
readMSH()
bool PViewDataGModel::readMSH (const std::string & viewName, const std::string & fileName, int fileIndex, FILE * fp, bool binary, bool swap, int step, double time, int partition, int numComp, int numNodes, const std::string & interpolationScheme)
Definition at line 135 of file PViewDataGModelIO.cpp.
Referenced by PView::readMSH().
readPCH()
bool PViewDataGModel::readPCH (const std::string & fileName, int fileIndex)
Definition at line 1107 of file PViewDataGModelIO.cpp.
Referenced by PView::readPCH().
reverseElement()
void PViewDataGModel::reverseElement (int step, int ent, int ele) virtual
Reimplemented from PViewData.
Definition at line 705 of file PViewDataGModel.cpp.
sendToServer()
void PViewDataGModel::sendToServer (const std::string & name) virtual
Reimplemented from PViewData.
Definition at line 1118 of file PViewDataGModelIO.cpp.
setBoundingBox()
void PViewDataGModel::setBoundingBox (SBoundingBox3d & box) inline virtual
Implements PViewData.
Definition at line 228 of file PViewDataGModel.h.
setMax()
void PViewDataGModel::setMax (double max) inline virtual
Implements PViewData.
Definition at line 226 of file PViewDataGModel.h.
setMin()
void PViewDataGModel::setMin (double min) inline virtual
Implements PViewData.
Definition at line 225 of file PViewDataGModel.h.
setNode()
void PViewDataGModel::setNode (int step, int ent, int ele, int nod, double x, double y, double z) virtual
Reimplemented from PViewData.
Definition at line 580 of file PViewDataGModel.cpp.
setValue()
void PViewDataGModel::setValue (int step, int ent, int ele, int node, int comp, double val) virtual
Reimplemented from PViewData.
Definition at line 667 of file PViewDataGModel.cpp.
skipElement()
bool PViewDataGModel::skipElement (int step, int ent, int ele, bool checkVisibility = false, int samplingRate = 1) virtual
Reimplemented from PViewData.
Definition at line 812 of file PViewDataGModel.cpp.
Referenced by finalize(), getMax(), and getMin().
skipEntity()
bool PViewDataGModel::skipEntity (int step, int ent) virtual
Reimplemented from PViewData.
Definition at line 806 of file PViewDataGModel.cpp.
Referenced by getMax(), and getMin().
smooth()
void PViewDataGModel::smooth () virtual
Reimplemented from PViewData.
Definition at line 710 of file PViewDataGModel.cpp.
tagNode()
void PViewDataGModel::tagNode (int step, int ent, int ele, int nod, int tag) virtual
Reimplemented from PViewData.
Definition at line 590 of file PViewDataGModel.cpp.
useGaussPoints()
bool PViewDataGModel::useGaussPoints () inline virtual
Reimplemented from PViewData.
Definition at line 271 of file PViewDataGModel.h.
writeMED()
bool PViewDataGModel::writeMED (const std::string & fileName) virtual
Reimplemented from PViewData.
Definition at line 1098 of file PViewDataGModelIO.cpp.
writeMSH()
bool PViewDataGModel::writeMSH (const std::string & fileName, double version = 2.2, bool binary = false, bool savemesh = true, bool multipleView = false, int partitionNum = -1, bool saveInterpolationMatrices = true, bool forceNodeData = false, bool forceElementData = false) virtual
Reimplemented from PViewData.
Definition at line 215 of file PViewDataGModelIO.cpp.
Member Data Documentation
_max
double PViewDataGModel::_max private
Definition at line 205 of file PViewDataGModel.h.
Referenced by finalize(), getMax(), readMSH(), and setMax().
_min
double PViewDataGModel::_min private
Definition at line 205 of file PViewDataGModel.h.
Referenced by finalize(), getMin(), readMSH(), and setMin().
_steps
std::vector<stepData<double> *> PViewDataGModel::_steps private
Definition at line 203 of file PViewDataGModel.h.
Referenced by _getElement(), addData(), combineTime(), destroyData(), finalize(), getBoundingBox(), getElement(), getEntity(), getFileName(), getFirstNonEmptyTimeStep(), getMax(), getMemoryInMb(), getMin(), getModel(), getNode(), getNumComponents(), getNumElements(), getNumEntities(), getNumHexahedra(), getNumLines(), getNumNodes(), getNumPoints(), getNumPolygons(), getNumPolyhedra(), getNumPrisms(), getNumPyramids(), getNumQuadrangles(), getNumScalars(), getNumTensors(), getNumTetrahedra(), getNumTimeSteps(), getNumTriangles(), getNumTrihedra(), getNumValues(), getNumVectors(), getStepData(), getTime(), getValue(), getValueByIndex(), hasModel(), hasMultipleMeshes(), hasPartition(), hasTimeStep(), importLists(), readMSH(), sendToServer(), setValue(), skipElement(), skipEntity(), smooth(), writeMSH(), and ~PViewDataGModel().
_type
DataType PViewDataGModel::_type private
Definition at line 207 of file PViewDataGModel.h.
Referenced by addData(), finalize(), getNode(), getNumNodes(), getNumValues(), getType(), getValue(), getValueByIndex(), isNodeData(), readMSH(), sendToServer(), setValue(), skipElement(), smooth(), useGaussPoints(), and writeMSH().
The documentation for this class was generated from the following files:
src/post/PViewDataGModel.h
src/post/PViewDataGModel.cpp
src/post/PViewDataGModelIO.cpp
src/post/PViewDataGModelIO_CGNS.cpp