gmsh-TingyuanDoc: MEdgeN Class Reference
MEdgeN Class Reference
#include <MEdge.h>
Public Member Functions
MEdgeN ()
MEdgeN (const std::vector< MVertex * > &v)
std::size_t getNumVertices () const
MVertex * getVertex (std::size_t i) const
const std::vector< MVertex * > & getVertices () const
int getPolynomialOrder () const
MEdge getEdge () const
SPoint3 pnt (double u) const
SVector3 tangent (double u) const
double interpolate (const double val[], double u, int stride=1) const
Private Attributes
std::vector< MVertex * > _v
Detailed Description
Definition at line 136 of file MEdge.h.
Constructor & Destructor Documentation
MEdgeN() [1/2]
MEdgeN::MEdgeN () inline
Definition at line 141 of file MEdge.h.
MEdgeN() [2/2]
MEdgeN::MEdgeN (const std::vector< MVertex * > & v)
Definition at line 156 of file MEdge.cpp.
Member Function Documentation
getEdge()
MEdge MEdgeN::getEdge () const
Definition at line 162 of file MEdge.cpp.
getNumVertices()
std::size_t MEdgeN::getNumVertices () const inline
Definition at line 143 of file MEdge.h.
Referenced by getPolynomialOrder().
getPolynomialOrder()
int MEdgeN::getPolynomialOrder () const inline
Definition at line 146 of file MEdge.h.
Referenced by interpolate(), pnt(), and tangent().
getVertex()
MVertex* MEdgeN::getVertex (std::size_t i) const inline
Definition at line 144 of file MEdge.h.
getVertices()
const std::vector<MVertex *>& MEdgeN::getVertices () const inline
Definition at line 145 of file MEdge.h.
interpolate()
double MEdgeN::interpolate (const double val[], double u, int stride = 1) const
Definition at line 198 of file MEdge.cpp.
pnt()
SPoint3 MEdgeN::pnt (double u) const
Definition at line 164 of file MEdge.cpp.
tangent()
SVector3 MEdgeN::tangent (double u) const
Definition at line 181 of file MEdge.cpp.
Member Data Documentation
_v
std::vector<MVertex *> MEdgeN::_v private
Definition at line 138 of file MEdge.h.
Referenced by getEdge(), getNumVertices(), getVertex(), getVertices(), MEdgeN(), pnt(), and tangent().
The documentation for this class was generated from the following files:
src/geo/MEdge.h
src/geo/MEdge.cpp