gmsh-TingyuanDoc: partitionVertex Class Reference
partitionVertex Class Reference
#include <partitionVertex.h>
Public Member Functions
partitionVertex (GModel *model, int num, const std::vector< int > &partitions)
partitionVertex (GModel *model, int num)
partitionVertex (GModel *model, const std::vector< int > &partitions)
virtual ~partitionVertex ()
virtual GeomType geomType () const
virtual void setParentEntity (GEntity *v)
virtual GEntity * getParentEntity ()
virtual void setPartitions (std::vector< int > &partitions)
virtual const std::vector< int > & getPartitions () const
virtual int getPartition (std::size_t index) const
virtual std::size_t numPartitions () const
Public Member Functions inherited from discreteVertex
discreteVertex (GModel *m, int num, double x=0., double y=0., double z=0.)
discreteVertex (GModel *m)
virtual ~discreteVertex ()
virtual GPoint point () const
virtual double x () const
virtual double y () const
virtual double z () const
virtual void setPosition (GPoint &p)
Public Member Functions inherited from GVertex
GVertex (GModel *m, int tag, double ms=MAX_LC)
virtual ~GVertex ()
virtual void deleteMesh ()
virtual void resetMeshAttributes ()
virtual SPoint3 xyz () const
void addEdge (GEdge *e)
void delEdge (GEdge *e)
virtual std::list< GRegion * > regions () const
virtual std::vector< GEdge * > const & edges () const
virtual std::size_t numEdges () const
virtual std::vector< GFace * > faces () const
virtual int dim () const
virtual bool isOrphan ()
virtual double prescribedMeshSizeAtVertex () const
virtual void setPrescribedMeshSizeAtVertex (double l)
virtual SBoundingBox3d bounds (bool fast=false)
virtual SPoint2 reparamOnFace (const GFace *gf, int) const
virtual std::string getAdditionalInfoString (bool multline=false)
virtual void writeGEO (FILE *fp, const std::string &meshSizeParameter="")
virtual void writePY (FILE *fp, const std::string &meshSizeParameter="")
virtual void getElementTypes (std::vector< int > &types) const
std::size_t getNumMeshElements () const
std::size_t getNumMeshElementsByType (const int familyType) const
void getNumMeshElements (unsigned *const c) const
MElement * getMeshElement (std::size_t index) const
MElement * getMeshElementByType (const int familyType, const std::size_t index) const
bool isOnSeam (const GFace *gf) const
void relocateMeshVertices ()
void addPoint (MPoint *p)
void addElement (int type, MElement *e)
void removeElement (int type, MElement *e)
void removeElements (int type)
virtual bool reorder (const int elementType, const std::vector< std::size_t > &ordering)
Public Member Functions inherited from GEntity
void addVerticesInSet (std::set< MVertex * > &, bool closure) const
virtual std::string getTypeString ()
GEntity (GModel *m, int t)
virtual ~GEntity ()
virtual void mesh (bool verbose)
void deleteVertexArrays ()
virtual std::vector< GVertex * > vertices () const
std::vector< GRegion * > bindingsGetRegions ()
std::vector< GFace * > bindingsGetFaces ()
std::vector< GEdge * > bindingsGetEdges () const
std::vector< GVertex * > bindingsGetVertices ()
virtual bool continuous (int dim) const
virtual bool periodic (int dim) const
virtual double period (int dim) const
virtual bool degenerate (int dim) const
virtual bool haveParametrization ()
virtual bool isFullyDiscrete ()
virtual Range< double > parBounds (int i) const
virtual double tolerance () const
virtual bool containsPoint (const SPoint3 &pt) const
virtual ModelType getNativeType () const
virtual void * getNativePtr () const
virtual int getNativeInt () const
GModel * model () const
int tag () const
void setTag (int tag)
virtual void addPhysicalEntity (int physicalTag)
virtual std::vector< int > getPhysicalEntities ()
GEntity * getMeshMaster () const
void setMeshMaster (GEntity *)
void setMeshMaster (GEntity *, const std::vector< double > &, bool updateCorrespondingVertices=true)
void updateCorrespondingVertices ()
void copyMasterCoordinates ()
virtual void alignElementsWithMaster ()
virtual SOrientedBoundingBox getOBB ()
virtual char getVisibility ()
virtual void setVisibility (char val, bool recursive=false)
virtual char getSelection ()
virtual void setSelection (char val)
virtual unsigned int getColor ()
virtual void setColor (unsigned color, bool recursive=false)
virtual bool useColor ()
virtual std::string getInfoString (bool additional=true, bool multiline=false)
virtual double getMeshSize () const
virtual double getMeshSizeFactor () const
virtual std::size_t getNumMeshParentElements ()
virtual MElement *const * getStartElementType (int type) const
bool getAllElementsVisible ()
void setAllElementsVisible (bool val)
std::size_t getNumMeshVertices ()
MVertex * getMeshVertex (std::size_t index)
void addMeshVertex (MVertex *v)
void removeMeshVertex (MVertex *v)
GVertex * cast2Vertex ()
GEdge * cast2Edge ()
GFace * cast2Face ()
GRegion * cast2Region ()
Private Attributes
std::vector< int > _partitions
GEntity * _parentEntity
Additional Inherited Members
Public Types inherited from GEntity
enum ModelType {
UnknownModel, GmshModel, OpenCascadeModel, AcisModel,
ParasolidModel
}
enum GeomType {
Unknown, Point, BoundaryLayerPoint, Line,
Circle, Ellipse, Conic, Parabola,
Hyperbola, TrimmedCurve, OffsetCurve, BSpline,
Bezier, ParametricCurve, BoundaryLayerCurve, DiscreteCurve,
Plane, Nurb, Cylinder, Sphere,
Cone, Torus, RuledSurface, ParametricSurface,
BSplineSurface, BezierSurface, SurfaceOfRevolution, BoundaryLayerSurface,
DiscreteSurface, DiscreteDiskSurface, Volume, DiscreteVolume,
PartitionPoint, PartitionCurve, PartitionSurface, PartitionVolume,
GhostCurve, GhostSurface, GhostVolume
}
enum MeshGenerationStatus { PENDING, DONE, FAILED }
Public Attributes inherited from GVertex
std::vector< MPoint * > points
Public Attributes inherited from GEntity
std::vector< MVertex * > mesh_vertices
std::vector< GEntity * > compound
std::map< GVertex *, GVertex * > vertexCounterparts
std::vector< int > physicals
VertexArray * va_lines
VertexArray * va_triangles
std::set< MElement * > curvedBLElements
std::vector< double > affineTransform
std::map< MVertex *, MVertex * > correspondingVertices
std::map< MVertex *, MVertex * > correspondingHighOrderVertices
Protected Attributes inherited from GVertex
std::vector< GEdge * > l_edges
double meshSize
Protected Attributes inherited from GEntity
SOrientedBoundingBox * _obb
Detailed Description
Definition at line 12 of file partitionVertex.h.
Constructor & Destructor Documentation
partitionVertex() [1/3]
partitionVertex::partitionVertex (GModel * model, int num, const std::vector< int > & partitions) inline
Definition at line 18 of file partitionVertex.h.
partitionVertex() [2/3]
partitionVertex::partitionVertex (GModel * model, int num) inline
Definition at line 23 of file partitionVertex.h.
partitionVertex() [3/3]
partitionVertex::partitionVertex (GModel * model, const std::vector< int > & partitions) inline
Definition at line 27 of file partitionVertex.h.
~partitionVertex()
virtual partitionVertex::~partitionVertex () inline virtual
Definition at line 31 of file partitionVertex.h.
Member Function Documentation
geomType()
virtual GeomType partitionVertex::geomType () const inline virtual
Reimplemented from GVertex.
Definition at line 32 of file partitionVertex.h.
getParentEntity()
virtual GEntity* partitionVertex::getParentEntity () inline virtual
Reimplemented from GVertex.
Definition at line 34 of file partitionVertex.h.
Referenced by writeMSH4Entities().
getPartition()
virtual int partitionVertex::getPartition (std::size_t index) const inline virtual
Definition at line 40 of file partitionVertex.h.
Referenced by GModel::_readMSH4(), and partitionVertexPtrLessThan::operator()().
getPartitions()
virtual const std::vector<int>& partitionVertex::getPartitions () const inline virtual
Definition at line 39 of file partitionVertex.h.
Referenced by getEntitiesToSave(), and writeMSH4Entities().
numPartitions()
virtual std::size_t partitionVertex::numPartitions () const inline virtual
Definition at line 44 of file partitionVertex.h.
Referenced by GModel::_readMSH4(), and partitionVertexPtrLessThan::operator()().
setParentEntity()
virtual void partitionVertex::setParentEntity (GEntity * v) inline virtual
Definition at line 33 of file partitionVertex.h.
setPartitions()
virtual void partitionVertex::setPartitions (std::vector< int > & partitions) inline virtual
Definition at line 35 of file partitionVertex.h.
Member Data Documentation
_parentEntity
GEntity* partitionVertex::_parentEntity private
Definition at line 15 of file partitionVertex.h.
Referenced by getParentEntity(), and setParentEntity().
_partitions
std::vector<int> partitionVertex::_partitions private
Definition at line 14 of file partitionVertex.h.
Referenced by getPartition(), getPartitions(), numPartitions(), and setPartitions().
The documentation for this class was generated from the following file:
src/geo/partitionVertex.h