gmsh-TingyuanDoc: MVertexRTree Class Reference
MVertexRTree Class Reference
#include <MVertexRTree.h>
Public Member Functions
MVertexRTree (double tolerance=1.e-8)
~MVertexRTree ()
MVertex * insert (MVertex *v, bool warnIfExists=false, std::set< MVertex *, MVertexPtrLessThan > *duplicates=nullptr)
int insert (std::vector< MVertex * > &v, bool warnIfExists=false, std::set< MVertex *, MVertexPtrLessThan > *duplicates=nullptr)
MVertex * find (double x, double y, double z)
std::size_t size ()
Static Private Member Functions
static bool rtree_callback (MVertex *v, void *ctx)
Private Attributes
RTree< MVertex *, double, 3, double > * _rtree
double _tol
Detailed Description
Definition at line 16 of file MVertexRTree.h.
Constructor & Destructor Documentation
MVertexRTree()
MVertexRTree::MVertexRTree (double tolerance = 1.e-8) inline
Definition at line 28 of file MVertexRTree.h.
~MVertexRTree()
MVertexRTree::~MVertexRTree () inline
Definition at line 33 of file MVertexRTree.h.
Member Function Documentation
find()
MVertex* MVertexRTree::find (double x, double y, double z) inline
Definition at line 70 of file MVertexRTree.h.
Referenced by copyMesh(), createElements(), extrudeMesh(), getExtrudedVertices(), GModel::readSTL(), and ReplaceDuplicatePointsNew().
insert() [1/2]
MVertex* MVertexRTree::insert (MVertex * v, bool warnIfExists = false, std::set< MVertex *, MVertexPtrLessThan > * duplicates = nullptr) inline
Definition at line 38 of file MVertexRTree.h.
Referenced by GModel::checkMeshCoherence(), copyMesh(), extrudeMesh(), insert(), insertAllVertices(), MeshExtrudedSurface(), GModel::readSTL(), GModel::removeDuplicateMeshVertices(), ReplaceDuplicatePointsNew(), and PViewDataList::writeMSH().
insert() [2/2]
int MVertexRTree::insert (std::vector< MVertex * > & v, bool warnIfExists = false, std::set< MVertex *, MVertexPtrLessThan > * duplicates = nullptr) inline
Definition at line 62 of file MVertexRTree.h.
rtree_callback()
static bool MVertexRTree::rtree_callback (MVertex * v, void * ctx) inline static private
Definition at line 20 of file MVertexRTree.h.
Referenced by find(), and insert().
size()
std::size_t MVertexRTree::size () inline
Definition at line 78 of file MVertexRTree.h.
Member Data Documentation
_rtree
RTree<MVertex *, double, 3, double>* MVertexRTree::_rtree private
Definition at line 18 of file MVertexRTree.h.
Referenced by find(), insert(), MVertexRTree(), size(), and ~MVertexRTree().
_tol
double MVertexRTree::_tol private
Definition at line 19 of file MVertexRTree.h.
Referenced by find(), insert(), and MVertexRTree().
The documentation for this class was generated from the following file:
src/geo/MVertexRTree.h