gmsh-TingyuanDoc: GMSH_AnnotatePlugin Class Reference
GMSH_AnnotatePlugin Class Reference
#include <Annotate.h>
Public Member Functions
GMSH_AnnotatePlugin ()
std::string getName () const
std::string getShortHelp () const
std::string getHelp () const
int getNbOptions () const
StringXNumber * getOption (int iopt)
int getNbOptionsStr () const
StringXString * getOptionStr (int iopt)
PView * execute (PView *)
Public Member Functions inherited from GMSH_PostPlugin
GMSH_PLUGIN_TYPE getType () const
virtual int run ()
virtual PView * executeRemote (PView *)
virtual PView * getView (int index, PView *view)
virtual PViewDataList * getDataList (PView *view, bool showError=true)
virtual PViewData * getPossiblyAdaptiveData (PView *view)
virtual void assignSpecificVisibility () const
virtual bool geometricalFilter (fullMatrix< double > *) const
Public Member Functions inherited from GMSH_Plugin
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
std::string serialize ()
Static Public Member Functions
static double callbackX (int, int, double)
static double callbackY (int, int, double)
static double callbackZ (int, int, double)
static double callback3D (int, int, double)
static double callbackFontSize (int, int, double)
static std::string callbackText (int, int, const std::string &)
static std::string callbackFont (int, int, const std::string &)
static std::string callbackAlign (int, int, const std::string &)
static void draw (void *context)
Static Public Member Functions inherited from GMSH_Plugin
static void setDrawFunction (void(*fct)(void *))
Static Private Member Functions
static double callback (int num, int action, double value, double *opt, double step, double min, double max)
static std::string callbackStr (int num, int action, const std::string &value, std::string &opt)
Additional Inherited Members
Public Types inherited from GMSH_Plugin
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Public Attributes inherited from GMSH_Plugin
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes inherited from GMSH_Plugin
static void(* draw)(void *) = nullptr
Detailed Description
Definition at line 16 of file Annotate.h.
Constructor & Destructor Documentation
GMSH_AnnotatePlugin()
GMSH_AnnotatePlugin::GMSH_AnnotatePlugin () inline
Definition at line 24 of file Annotate.h.
Member Function Documentation
callback()
double GMSH_AnnotatePlugin::callback (int num, int action, double value, double * opt, double step, double min, double max) static private
Definition at line 96 of file Annotate.cpp.
Referenced by callback3D(), callbackFontSize(), callbackX(), callbackY(), and callbackZ().
callback3D()
double GMSH_AnnotatePlugin::callback3D (int num, int action, double value) static
Definition at line 150 of file Annotate.cpp.
callbackAlign()
std::string GMSH_AnnotatePlugin::callbackAlign (int num, int action, const std::string & value) static
Definition at line 173 of file Annotate.cpp.
callbackFont()
std::string GMSH_AnnotatePlugin::callbackFont (int num, int action, const std::string & value) static
Definition at line 167 of file Annotate.cpp.
callbackFontSize()
double GMSH_AnnotatePlugin::callbackFontSize (int num, int action, double value) static
Definition at line 155 of file Annotate.cpp.
callbackStr()
std::string GMSH_AnnotatePlugin::callbackStr (int num, int action, const std::string & value, std::string & opt) static private
Definition at line 111 of file Annotate.cpp.
Referenced by callbackAlign(), callbackFont(), and callbackText().
callbackText()
std::string GMSH_AnnotatePlugin::callbackText (int num, int action, const std::string & value) static
Definition at line 161 of file Annotate.cpp.
callbackX()
double GMSH_AnnotatePlugin::callbackX (int num, int action, double value) static
Definition at line 120 of file Annotate.cpp.
callbackY()
double GMSH_AnnotatePlugin::callbackY (int num, int action, double value) static
Definition at line 130 of file Annotate.cpp.
callbackZ()
double GMSH_AnnotatePlugin::callbackZ (int num, int action, double value) static
Definition at line 140 of file Annotate.cpp.
draw()
void GMSH_AnnotatePlugin::draw (void * context) static
Definition at line 44 of file Annotate.cpp.
execute()
PView * GMSH_AnnotatePlugin::execute (PView * v) virtual
Implements GMSH_PostPlugin.
Definition at line 214 of file Annotate.cpp.
getHelp()
std::string GMSH_AnnotatePlugin::getHelp () const virtual
Implements GMSH_Plugin.
Definition at line 179 of file Annotate.cpp.
getName()
std::string GMSH_AnnotatePlugin::getName () const inline virtual
Implements GMSH_Plugin.
Definition at line 25 of file Annotate.h.
getNbOptions()
int GMSH_AnnotatePlugin::getNbOptions () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 194 of file Annotate.cpp.
getNbOptionsStr()
int GMSH_AnnotatePlugin::getNbOptionsStr () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 204 of file Annotate.cpp.
getOption()
StringXNumber * GMSH_AnnotatePlugin::getOption (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 199 of file Annotate.cpp.
getOptionStr()
StringXString * GMSH_AnnotatePlugin::getOptionStr (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 209 of file Annotate.cpp.
getShortHelp()
std::string GMSH_AnnotatePlugin::getShortHelp () const inline virtual
Implements GMSH_Plugin.
Definition at line 26 of file Annotate.h.
The documentation for this class was generated from the following files:
src/plugin/Annotate.h
src/plugin/Annotate.cpp