gmsh-TingyuanDoc: nanoflann::PooledAllocator Class Reference
nanoflann::PooledAllocator Class Reference
nanoflann C++ library for ANN » Memory allocation
#include <nanoflann.hpp>
Public Member Functions
PooledAllocator ()
~PooledAllocator ()
void free_all ()
void * malloc (const size_t req_size)
template<typename T >
T * allocate (const size_t count=1)
Public Attributes
size_t usedMemory
size_t wastedMemory
Private Member Functions
void internal_init ()
Private Attributes
size_t remaining
void * base
void * loc
Detailed Description
Definition at line 467 of file nanoflann.hpp.
Constructor & Destructor Documentation
PooledAllocator()
nanoflann::PooledAllocator::PooledAllocator () inline
Default constructor. Initializes a new pool.
Definition at line 494 of file nanoflann.hpp.
~PooledAllocator()
nanoflann::PooledAllocator::~PooledAllocator () inline
Destructor. Frees all the memory allocated in this pool.
Definition at line 501 of file nanoflann.hpp.
Member Function Documentation
allocate()
template<typename T > T* nanoflann::PooledAllocator::allocate (const size_t count = 1) inline
Allocates (using this pool) a generic type T.
Params: count = number of instances to allocate. Returns: pointer (of type T*) to memory buffer
Definition at line 573 of file nanoflann.hpp.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::divideTree(), and nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::load_tree().
free_all()
void nanoflann::PooledAllocator::free_all () inline
Frees all allocated memory chunks
Definition at line 506 of file nanoflann.hpp.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::freeIndex().
internal_init()
void nanoflann::PooledAllocator::internal_init () inline private
Definition at line 479 of file nanoflann.hpp.
malloc()
void* nanoflann::PooledAllocator::malloc (const size_t req_size) inline
Returns a pointer to a piece of new memory of the given size in bytes allocated from the pool.
Definition at line 520 of file nanoflann.hpp.
Member Data Documentation
base
void* nanoflann::PooledAllocator::base private
Definition at line 476 of file nanoflann.hpp.
loc
void* nanoflann::PooledAllocator::loc private
Definition at line 477 of file nanoflann.hpp.
remaining
size_t nanoflann::PooledAllocator::remaining private
Definition at line 475 of file nanoflann.hpp.
usedMemory
size_t nanoflann::PooledAllocator::usedMemory
Definition at line 488 of file nanoflann.hpp.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::usedMemory().
wastedMemory
size_t nanoflann::PooledAllocator::wastedMemory
Definition at line 489 of file nanoflann.hpp.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::usedMemory().
The documentation for this class was generated from the following file:
src/numeric/nanoflann.hpp