gmsh-TingyuanDoc: GMSH_CutParametricPlugin Class Reference
GMSH_CutParametricPlugin Class Reference
#include <CutParametric.h>
Public Member Functions
GMSH_CutParametricPlugin ()
std::string getName () const
std::string getShortHelp () const
std::string getHelp () const
int getNbOptions () const
StringXNumber * getOption (int iopt)
int getNbOptionsStr () const
StringXString * getOptionStr (int iopt)
PView * execute (PView *)
Public Member Functions inherited from GMSH_PostPlugin
GMSH_PLUGIN_TYPE getType () const
virtual int run ()
virtual PView * executeRemote (PView *)
virtual PView * getView (int index, PView *view)
virtual PViewDataList * getDataList (PView *view, bool showError=true)
virtual PViewData * getPossiblyAdaptiveData (PView *view)
virtual void assignSpecificVisibility () const
virtual bool geometricalFilter (fullMatrix< double > *) const
Public Member Functions inherited from GMSH_Plugin
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
std::string serialize ()
Static Public Member Functions
static double callbackMinU (int, int, double)
static double callbackMaxU (int, int, double)
static double callbackNU (int, int, double)
static double callbackMinV (int, int, double)
static double callbackMaxV (int, int, double)
static double callbackNV (int, int, double)
static double callbackConnect (int, int, double)
static std::string callbackX (int, int, const std::string &)
static std::string callbackY (int, int, const std::string &)
static std::string callbackZ (int, int, const std::string &)
static void draw (void *context)
Static Public Member Functions inherited from GMSH_Plugin
static void setDrawFunction (void(*fct)(void *))
Static Private Member Functions
static double callback (int num, int action, double value, double *opt, double step, double min, double max)
static std::string callbackStr (int num, int action, const std::string &value, std::string &opt)
static int fillXYZ ()
Static Private Attributes
static int recompute = 1
static std::vector< double > x
static std::vector< double > y
static std::vector< double > z
Additional Inherited Members
Public Types inherited from GMSH_Plugin
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Public Attributes inherited from GMSH_Plugin
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes inherited from GMSH_Plugin
static void(* draw)(void *) = nullptr
Detailed Description
Definition at line 17 of file CutParametric.h.
Constructor & Destructor Documentation
GMSH_CutParametricPlugin()
GMSH_CutParametricPlugin::GMSH_CutParametricPlugin () inline
Definition at line 28 of file CutParametric.h.
Member Function Documentation
callback()
double GMSH_CutParametricPlugin::callback (int num, int action, double value, double * opt, double step, double min, double max) static private
Definition at line 145 of file CutParametric.cpp.
Referenced by callbackConnect(), callbackMaxU(), callbackMaxV(), callbackMinU(), callbackMinV(), callbackNU(), and callbackNV().
callbackConnect()
double GMSH_CutParametricPlugin::callbackConnect (int num, int action, double value) static
Definition at line 207 of file CutParametric.cpp.
callbackMaxU()
double GMSH_CutParametricPlugin::callbackMaxU (int num, int action, double value) static
Definition at line 177 of file CutParametric.cpp.
callbackMaxV()
double GMSH_CutParametricPlugin::callbackMaxV (int num, int action, double value) static
Definition at line 195 of file CutParametric.cpp.
callbackMinU()
double GMSH_CutParametricPlugin::callbackMinU (int num, int action, double value) static
Definition at line 171 of file CutParametric.cpp.
callbackMinV()
double GMSH_CutParametricPlugin::callbackMinV (int num, int action, double value) static
Definition at line 189 of file CutParametric.cpp.
callbackNU()
double GMSH_CutParametricPlugin::callbackNU (int num, int action, double value) static
Definition at line 183 of file CutParametric.cpp.
callbackNV()
double GMSH_CutParametricPlugin::callbackNV (int num, int action, double value) static
Definition at line 201 of file CutParametric.cpp.
callbackStr()
std::string GMSH_CutParametricPlugin::callbackStr (int num, int action, const std::string & value, std::string & opt) static private
Definition at line 161 of file CutParametric.cpp.
Referenced by callbackX(), callbackY(), and callbackZ().
callbackX()
std::string GMSH_CutParametricPlugin::callbackX (int num, int action, const std::string & value) static
Definition at line 214 of file CutParametric.cpp.
callbackY()
std::string GMSH_CutParametricPlugin::callbackY (int num, int action, const std::string & value) static
Definition at line 220 of file CutParametric.cpp.
callbackZ()
std::string GMSH_CutParametricPlugin::callbackZ (int num, int action, const std::string & value) static
Definition at line 226 of file CutParametric.cpp.
draw()
void GMSH_CutParametricPlugin::draw (void * context) static
Definition at line 101 of file CutParametric.cpp.
execute()
PView * GMSH_CutParametricPlugin::execute (PView * v) virtual
Implements GMSH_PostPlugin.
Definition at line 322 of file CutParametric.cpp.
fillXYZ()
int GMSH_CutParametricPlugin::fillXYZ () static private
Definition at line 71 of file CutParametric.cpp.
Referenced by draw(), and execute().
getHelp()
std::string GMSH_CutParametricPlugin::getHelp () const virtual
Implements GMSH_Plugin.
Definition at line 232 of file CutParametric.cpp.
getName()
std::string GMSH_CutParametricPlugin::getName () const inline virtual
Implements GMSH_Plugin.
Definition at line 29 of file CutParametric.h.
getNbOptions()
int GMSH_CutParametricPlugin::getNbOptions () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 245 of file CutParametric.cpp.
getNbOptionsStr()
int GMSH_CutParametricPlugin::getNbOptionsStr () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 255 of file CutParametric.cpp.
getOption()
StringXNumber * GMSH_CutParametricPlugin::getOption (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 250 of file CutParametric.cpp.
getOptionStr()
StringXString * GMSH_CutParametricPlugin::getOptionStr (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 260 of file CutParametric.cpp.
getShortHelp()
std::string GMSH_CutParametricPlugin::getShortHelp () const inline virtual
Implements GMSH_Plugin.
Definition at line 30 of file CutParametric.h.
Member Data Documentation
recompute
int GMSH_CutParametricPlugin::recompute = 1 static private
Definition at line 24 of file CutParametric.h.
Referenced by callback(), callbackStr(), and draw().
x
std::vector< double > GMSH_CutParametricPlugin::x static private
Definition at line 25 of file CutParametric.h.
Referenced by draw(), execute(), and fillXYZ().
y
std::vector< double > GMSH_CutParametricPlugin::y static private
Definition at line 25 of file CutParametric.h.
Referenced by draw(), execute(), and fillXYZ().
z
std::vector< double > GMSH_CutParametricPlugin::z static private
Definition at line 25 of file CutParametric.h.
Referenced by draw(), execute(), and fillXYZ().
The documentation for this class was generated from the following files:
src/plugin/CutParametric.h
src/plugin/CutParametric.cpp