gmsh-TingyuanDoc: MTri3 Class Reference
MTri3 Class Reference
#include <meshGFaceDelaunayInsertion.h>
Public Member Functions
bool isDeleted () const
void forceRadius (double r)
double getRadius () const
MVertex * otherSide (int i)
MTri3 (MTriangle *t, double lc, SMetric3 *m=nullptr, bidimMeshData *data=nullptr, GFace *gf=nullptr)
void setTri (MTriangle *t)
MTriangle * tri () const
void setNeigh (int iN, MTri3 *n)
MTri3 * getNeigh (int iN) const
int inCircumCircle (const double *p) const
int inCircumCircle (double x, double y) const
int inCircumCircle (const MVertex *v) const
void setDeleted (bool d)
bool assertNeigh () const
bool isNeigh (const MTri3 *t) const
Static Public Attributes
static int radiusNorm = 2
2 is euclidian norm, -1 is infinite norm , 3 quality
Protected Attributes
bool deleted
double circum_radius
MTriangle * base
MTri3 * neigh [3]
Detailed Description
Definition at line 78 of file meshGFaceDelaunayInsertion.h.
Constructor & Destructor Documentation
MTri3()
MTri3::MTri3 (MTriangle * t, double lc, SMetric3 * m = nullptr, bidimMeshData * data = nullptr, GFace * gf = nullptr)
Definition at line 411 of file meshGFaceDelaunayInsertion.cpp.
Member Function Documentation
assertNeigh()
bool MTri3::assertNeigh () const inline
Definition at line 119 of file meshGFaceDelaunayInsertion.h.
forceRadius()
void MTri3::forceRadius (double r) inline
Definition at line 89 of file meshGFaceDelaunayInsertion.h.
getNeigh()
MTri3* MTri3::getNeigh (int iN) const inline
Definition at line 107 of file meshGFaceDelaunayInsertion.h.
Referenced by delaunayMeshIn2D(), insertVertexB(), isActive(), recurFindCavity(), recurFindCavityAniso(), search4Triangle(), swapedge(), and updateActiveEdges().
getRadius()
double MTri3::getRadius () const inline
Definition at line 90 of file meshGFaceDelaunayInsertion.h.
Referenced by bowyerWatson(), bowyerWatsonFrontal(), bowyerWatsonFrontalLayers(), isActive(), compareTri3Ptr::operator()(), and updateActiveEdges().
inCircumCircle() [1/3]
int MTri3::inCircumCircle (const double * p) const
Definition at line 483 of file meshGFaceDelaunayInsertion.cpp.
Referenced by inCircumCircle().
inCircumCircle() [2/3]
int MTri3::inCircumCircle (const MVertex * v) const inline
Definition at line 114 of file meshGFaceDelaunayInsertion.h.
inCircumCircle() [3/3]
int MTri3::inCircumCircle (double x, double y) const inline
Definition at line 109 of file meshGFaceDelaunayInsertion.h.
isDeleted()
bool MTri3::isDeleted () const inline
Definition at line 88 of file meshGFaceDelaunayInsertion.h.
Referenced by _printTris(), bowyerWatson(), bowyerWatsonFrontal(), bowyerWatsonFrontalLayers(), bowyerWatsonParallelograms(), bowyerWatsonParallelogramsConstrained(), isActive(), recurFindCavity(), recurFindCavityAniso(), transferDataStructure(), and updateActiveEdges().
isNeigh()
bool MTri3::isNeigh (const MTri3 * t) const inline
Definition at line 126 of file meshGFaceDelaunayInsertion.h.
Referenced by assertNeigh().
otherSide()
MVertex* MTri3::otherSide (int i) inline
Definition at line 91 of file meshGFaceDelaunayInsertion.h.
setDeleted()
void MTri3::setDeleted (bool d) inline
Definition at line 118 of file meshGFaceDelaunayInsertion.h.
Referenced by recurFindCavity(), and recurFindCavityAniso().
setNeigh()
void MTri3::setNeigh (int iN, MTri3 * n) inline
Definition at line 106 of file meshGFaceDelaunayInsertion.h.
Referenced by connectTris().
setTri()
void MTri3::setTri (MTriangle * t) inline
Definition at line 104 of file meshGFaceDelaunayInsertion.h.
Referenced by swapedge().
tri()
MTriangle* MTri3::tri () const inline
Definition at line 105 of file meshGFaceDelaunayInsertion.h.
Referenced by bowyerWatson(), bowyerWatsonParallelograms(), bowyerWatsonParallelogramsConstrained(), delaunayMeshIn2D(), edgeXface::edgeXface(), insertAPoint(), insertVertexB(), isActive(), compareTri3Ptr::operator()(), optimalPointFrontal(), optimalPointFrontalB(), optimalPointFrontalQuad(), otherSide(), recurFindCavity(), recurFindCavityAniso(), search4Triangle(), swapedge(), transferDataStructure(), and updateActiveEdges().
Member Data Documentation
base
MTriangle* MTri3::base protected
Definition at line 82 of file meshGFaceDelaunayInsertion.h.
Referenced by inCircumCircle(), MTri3(), otherSide(), setTri(), and tri().
circum_radius
double MTri3::circum_radius protected
Definition at line 81 of file meshGFaceDelaunayInsertion.h.
Referenced by forceRadius(), getRadius(), and MTri3().
deleted
bool MTri3::deleted protected
Definition at line 80 of file meshGFaceDelaunayInsertion.h.
Referenced by assertNeigh(), isDeleted(), and setDeleted().
neigh
MTri3* MTri3::neigh[3] protected
Definition at line 83 of file meshGFaceDelaunayInsertion.h.
Referenced by assertNeigh(), getNeigh(), isNeigh(), MTri3(), otherSide(), and setNeigh().
radiusNorm
int MTri3::radiusNorm = 2 static
2 is euclidian norm, -1 is infinite norm , 3 quality
Definition at line 87 of file meshGFaceDelaunayInsertion.h.
Referenced by bowyerWatsonFrontalLayers(), and MTri3().
The documentation for this class was generated from the following files:
src/mesh/meshGFaceDelaunayInsertion.h
src/mesh/meshGFaceDelaunayInsertion.cpp