gmsh-TingyuanDoc: Barycenter Class Reference
Barycenter Class Reference
#include <VertexArray.h>
Public Member Functions
Barycenter (double x, double y, double z)
float x () const
float y () const
float z () const
void operator+= (const Barycenter &p)
Private Attributes
float _x
float _y
float _z
Detailed Description
Definition at line 97 of file VertexArray.h.
Constructor & Destructor Documentation
Barycenter()
Barycenter::Barycenter (double x, double y, double z) inline
Definition at line 102 of file VertexArray.h.
Member Function Documentation
operator+=()
void Barycenter::operator+= (const Barycenter & p) inline
Definition at line 109 of file VertexArray.h.
x()
float Barycenter::x () const inline
Definition at line 106 of file VertexArray.h.
Referenced by BarycenterLessThan::operator()(), BarycenterHash::operator()(), BarycenterEqual::operator()(), and operator+=().
y()
float Barycenter::y () const inline
Definition at line 107 of file VertexArray.h.
Referenced by BarycenterLessThan::operator()(), BarycenterHash::operator()(), BarycenterEqual::operator()(), and operator+=().
z()
float Barycenter::z () const inline
Definition at line 108 of file VertexArray.h.
Referenced by BarycenterLessThan::operator()(), BarycenterHash::operator()(), BarycenterEqual::operator()(), and operator+=().
Member Data Documentation
_x
float Barycenter::_x private
Definition at line 99 of file VertexArray.h.
Referenced by operator+=(), and x().
_y
float Barycenter::_y private
Definition at line 99 of file VertexArray.h.
Referenced by operator+=(), and y().
_z
float Barycenter::_z private
Definition at line 99 of file VertexArray.h.
Referenced by operator+=(), and z().
The documentation for this class was generated from the following file:
src/common/VertexArray.h