gmsh-TingyuanDoc: FieldManager Class Reference
FieldManager Class Reference
#include <Field.h>
Public Member Functions
void initialize ()
void reset ()
Field * get (int id)
Field * newField (int id, const std::string &type_name)
void deleteField (int id)
int newId ()
int maxId ()
FieldManager ()
~FieldManager ()
void setBackgroundMesh (int iView)
void setBackgroundField (Field *BGF)
void setBackgroundFieldId (int id)
void addBoundaryLayerFieldId (int id)
void addBoundaryLayerFieldId (std::vector< int > &tags)
int getBackgroundField ()
int getNumBoundaryLayerFields ()
int getBoundaryLayerField (int i)
Public Attributes
std::map< std::string, FieldFactory * > mapTypeName
Private Attributes
int _backgroundField
std::vector< int > _boundaryLayerFields
Detailed Description
Definition at line 145 of file Field.h.
Constructor & Destructor Documentation
FieldManager()
FieldManager::FieldManager ()
Definition at line 3170 of file Field.cpp.
~FieldManager()
FieldManager::~FieldManager ()
Definition at line 3217 of file Field.cpp.
Member Function Documentation
addBoundaryLayerFieldId() [1/2]
void FieldManager::addBoundaryLayerFieldId (int id) inline
Definition at line 166 of file Field.h.
Referenced by addBoundaryLayerFieldId().
addBoundaryLayerFieldId() [2/2]
void FieldManager::addBoundaryLayerFieldId (std::vector< int > & tags) inline
Definition at line 173 of file Field.h.
deleteField()
void FieldManager::deleteField (int id)
Definition at line 118 of file Field.cpp.
get()
Field * FieldManager::get (int id)
Definition at line 74 of file Field.cpp.
Referenced by _recombineIntoQuads(), addBoundaryLayerPoints(), addExtrudeNormals(), BGM_MeshMetric(), BGM_MeshSizeWithoutScaling(), GModel::computeSizeField(), MathEvalExpression::evaluate(), MathEvalExpressionAniso::evaluate(), GMSH_MeshSizeFieldViewPlugin::execute(), F_Lc_aniso::operator()(), LonLatField::operator()(), ThresholdField::operator()(), GradientField::operator()(), CurvatureField::operator()(), MaxEigenHessianField::operator()(), LaplacianField::operator()(), MeanField::operator()(), ParametricField::operator()(), MinAnisoField::operator()(), IntersectAnisoField::operator()(), MinField::operator()(), MaxField::operator()(), RestrictField::operator()(), splitElementsInBoundaryLayerIfNeeded(), and OctreeField::update().
getBackgroundField()
int FieldManager::getBackgroundField () inline
Definition at line 178 of file Field.h.
Referenced by _recombineIntoQuads(), addExtrudeNormals(), BGM_MeshMetric(), BGM_MeshSizeWithoutScaling(), and quadqsCleanup().
getBoundaryLayerField()
int FieldManager::getBoundaryLayerField (int i) inline
Definition at line 183 of file Field.h.
Referenced by addBoundaryLayerPoints(), F_Lc_aniso::operator()(), and splitElementsInBoundaryLayerIfNeeded().
getNumBoundaryLayerFields()
int FieldManager::getNumBoundaryLayerFields () inline
Definition at line 179 of file Field.h.
Referenced by addBoundaryLayerPoints(), Mesh1D(), Mesh2D(), F_Lc_aniso::operator()(), and splitElementsInBoundaryLayerIfNeeded().
initialize()
void FieldManager::initialize ()
Definition at line 3211 of file Field.cpp.
Referenced by Mesh0D(), Mesh1D(), Mesh2D(), and Mesh3D().
maxId()
int FieldManager::maxId ()
Definition at line 110 of file Field.cpp.
newField()
Field * FieldManager::newField (int id, const std::string & type_name)
Definition at line 81 of file Field.cpp.
Referenced by GModel::computeSizeField(), and setBackgroundMesh().
newId()
int FieldManager::newId ()
Definition at line 98 of file Field.cpp.
Referenced by GModel::computeSizeField(), setBackgroundField(), and setBackgroundMesh().
reset()
void FieldManager::reset ()
Definition at line 68 of file Field.cpp.
Referenced by GModel::adaptMesh(), GModel::destroy(), and quadqsCleanup().
setBackgroundField()
void FieldManager::setBackgroundField (Field * BGF)
Definition at line 3224 of file Field.cpp.
Referenced by GModel::adaptMesh(), GmshBatch(), and GmshFLTK().
setBackgroundFieldId()
void FieldManager::setBackgroundFieldId (int id) inline
Definition at line 165 of file Field.h.
setBackgroundMesh()
void FieldManager::setBackgroundMesh (int iView)
Definition at line 3280 of file Field.cpp.
Referenced by GmshBatch(), and GmshFLTK().
Member Data Documentation
_backgroundField
int FieldManager::_backgroundField private
Definition at line 147 of file Field.h.
Referenced by FieldManager(), getBackgroundField(), setBackgroundField(), setBackgroundFieldId(), and setBackgroundMesh().
_boundaryLayerFields
std::vector<int> FieldManager::_boundaryLayerFields private
Definition at line 148 of file Field.h.
Referenced by addBoundaryLayerFieldId(), getBoundaryLayerField(), and getNumBoundaryLayerFields().
mapTypeName
std::map<std::string, FieldFactory *> FieldManager::mapTypeName
Definition at line 151 of file Field.h.
Referenced by FieldManager(), newField(), PrintOptionsDoc(), and ~FieldManager().
The documentation for this class was generated from the following files:
src/mesh/Field.h
src/mesh/Field.cpp