gmsh-TingyuanDoc: globalVTKData Class Reference
globalVTKData Class Reference
#include <adaptiveData.h>
Public Member Functions
globalVTKData ()
~globalVTKData ()
Static Public Member Functions
static void clearGlobalConnectivity ()
static void clearGlobalCellType ()
static void clearGlobalCoords ()
static void clearGlobalValues ()
static void clearGlobalData ()
Static Public Attributes
static std::vector< vectInt > vtkGlobalConnectivity
static std::vector< int > vtkGlobalCellType
static std::vector< PCoords > vtkGlobalCoords
static std::vector< PValues > vtkGlobalValues
Detailed Description
Definition at line 442 of file adaptiveData.h.
Constructor & Destructor Documentation
globalVTKData()
globalVTKData::globalVTKData ()
~globalVTKData()
globalVTKData::~globalVTKData () inline
Definition at line 482 of file adaptiveData.h.
Member Function Documentation
clearGlobalCellType()
static void globalVTKData::clearGlobalCellType () inline static
Definition at line 460 of file adaptiveData.h.
Referenced by clearGlobalData().
clearGlobalConnectivity()
static void globalVTKData::clearGlobalConnectivity () inline static
Definition at line 451 of file adaptiveData.h.
Referenced by clearGlobalData().
clearGlobalCoords()
static void globalVTKData::clearGlobalCoords () inline static
Definition at line 465 of file adaptiveData.h.
Referenced by clearGlobalData().
clearGlobalData()
static void globalVTKData::clearGlobalData () inline static
Definition at line 475 of file adaptiveData.h.
Referenced by adaptiveData::changeResolutionForVTK(), and ~globalVTKData().
clearGlobalValues()
static void globalVTKData::clearGlobalValues () inline static
Definition at line 470 of file adaptiveData.h.
Referenced by clearGlobalData().
Member Data Documentation
vtkGlobalCellType
std::vector< int > globalVTKData::vtkGlobalCellType static
Definition at line 446 of file adaptiveData.h.
Referenced by adaptiveElements< T >::addInViewForVTK(), and clearGlobalCellType().
vtkGlobalConnectivity
std::vector< vectInt > globalVTKData::vtkGlobalConnectivity static
Definition at line 445 of file adaptiveData.h.
Referenced by adaptiveElements< T >::addInViewForVTK(), and clearGlobalConnectivity().
vtkGlobalCoords
std::vector< PCoords > globalVTKData::vtkGlobalCoords static
Definition at line 447 of file adaptiveData.h.
Referenced by adaptiveElements< T >::addInViewForVTK(), and clearGlobalCoords().
vtkGlobalValues
std::vector< PValues > globalVTKData::vtkGlobalValues static
Definition at line 449 of file adaptiveData.h.
Referenced by adaptiveElements< T >::addInViewForVTK(), and clearGlobalValues().
The documentation for this class was generated from the following files:
src/post/adaptiveData.h
src/post/adaptiveData.cpp