gmsh-TingyuanDoc: SMetric3 Class Reference
SMetric3 Class Reference
#include <STensor3.h>
Public Member Functions
SMetric3 (const double v=1.0)
SMetric3 (const SMetric3 &m)
SMetric3 (const double l1, const double l2, const double l3, const SVector3 &t1, const SVector3 &t2, const SVector3 &t3)
int getIndex (int i, int j) const
void getMat (fullMatrix< double > &mat) const
void setMat (const fullMatrix< double > &mat)
double & operator() (int i, int j)
double operator() (int i, int j) const
SMetric3 invert () const
double determinant () const
SMetric3 operator+ (const SMetric3 &other) const
SMetric3 & operator+= (const SMetric3 &other)
SMetric3 & operator*= (const double &other)
SMetric3 & operator*= (const SMetric3 &other)
SMetric3 transform (fullMatrix< double > &V)
void eig (fullMatrix< double > &V, fullVector< double > &S, bool s=false) const
void print (const char *) const
Protected Attributes
double _val [6]
Detailed Description
Definition at line 17 of file STensor3.h.
Constructor & Destructor Documentation
SMetric3() [1/3]
SMetric3::SMetric3 (const double v = 1.0) inline
Definition at line 25 of file STensor3.h.
SMetric3() [2/3]
SMetric3::SMetric3 (const SMetric3 & m) inline
Definition at line 30 of file STensor3.h.
SMetric3() [3/3]
SMetric3::SMetric3 (const double l1, const double l2, const double l3, const SVector3 & t1, const SVector3 & t2, const SVector3 & t3)
Definition at line 10 of file STensor3.cpp.
Member Function Documentation
determinant()
double SMetric3::determinant () const
Definition at line 74 of file STensor3.cpp.
Referenced by automaticMeshSizeField::operator()(), and meshMetric::scaleMetric().
eig()
void SMetric3::eig (fullMatrix< double > & V, fullVector< double > & S, bool s = false) const
Definition at line 104 of file STensor3.cpp.
Referenced by meshMetric::computeMetricFrey(), meshMetric::computeMetricHessian(), meshMetric::computeMetricLevelSet(), intersection(), intersection_alauzet(), intersection_conserve_mostaniso(), intersection_conserve_mostaniso_2d(), intersection_conserveM1(), MinAnisoField::operator()(), IntersectAnisoField::operator()(), and meshMetric::scaleMetric().
getIndex()
int SMetric3::getIndex (int i, int j) const inline
Definition at line 37 of file STensor3.h.
Referenced by getMat(), operator()(), and setMat().
getMat()
void SMetric3::getMat (fullMatrix< double > & mat) const
Definition at line 51 of file STensor3.cpp.
Referenced by meshMetric::computeMetricEigenDir(), determinant(), eig(), invert(), operator*=(), and transform().
invert()
SMetric3 SMetric3::invert () const
Definition at line 64 of file STensor3.cpp.
Referenced by interpolation(), intersection(), and intersection_alauzet().
operator()() [1/2]
double& SMetric3::operator() (int i, int j) inline
Definition at line 44 of file STensor3.h.
operator()() [2/2]
double SMetric3::operator() (int i, int j) const inline
Definition at line 45 of file STensor3.h.
operator*=() [1/2]
SMetric3& SMetric3::operator*= (const double & other) inline
Definition at line 59 of file STensor3.h.
operator*=() [2/2]
SMetric3 & SMetric3::operator*= (const SMetric3 & other)
Definition at line 82 of file STensor3.cpp.
operator+()
SMetric3 SMetric3::operator+ (const SMetric3 & other) const inline
Definition at line 48 of file STensor3.h.
operator+=()
SMetric3& SMetric3::operator+= (const SMetric3 & other) inline
Definition at line 54 of file STensor3.h.
print()
void SMetric3::print (const char * s) const
Definition at line 112 of file STensor3.cpp.
Referenced by automaticMeshSizeField::operator()().
setMat()
void SMetric3::setMat (const fullMatrix< double > & mat)
Definition at line 58 of file STensor3.cpp.
Referenced by invert(), operator*=(), and transform().
transform()
SMetric3 SMetric3::transform (fullMatrix< double > & V)
Definition at line 92 of file STensor3.cpp.
Referenced by circumCenterMetricXYZ().
Member Data Documentation
_val
double SMetric3::_val[6] protected
Definition at line 21 of file STensor3.h.
Referenced by getMat(), operator()(), operator*=(), operator+(), operator+=(), setMat(), and SMetric3().
The documentation for this class was generated from the following files:
src/geo/STensor3.h
src/geo/STensor3.cpp