gmsh-TingyuanDoc: BasisFactory Class Reference
BasisFactory Class Reference
#include <BasisFactory.h>
Static Public Member Functions
static const nodalBasis * getNodalBasis (int tag)
static const JacobianBasis * getJacobianBasis (int tag, FuncSpaceData)
static const JacobianBasis * getJacobianBasis (int tag, int order)
static const JacobianBasis * getJacobianBasis (int tag)
static const CondNumBasis * getCondNumBasis (int tag, int cnOrder=-1)
static const GradientBasis * getGradientBasis (int tag, FuncSpaceData)
static const GradientBasis * getGradientBasis (int tag, int order)
static const GradientBasis * getGradientBasis (int tag)
static const bezierBasis * getBezierBasis (FuncSpaceData)
static const bezierBasis * getBezierBasis (int parentType, int order)
static const bezierBasis * getBezierBasis (int tag)
static void clearAll ()
Static Private Attributes
static std::map< int, nodalBasis * > fs
static std::map< int, CondNumBasis * > cs
static std::map< FuncSpaceData, JacobianBasis * > js
static std::map< FuncSpaceData, bezierBasis * > bs
static std::map< FuncSpaceData, GradientBasis * > gs
Detailed Description
Definition at line 17 of file BasisFactory.h.
Member Function Documentation
clearAll()
void BasisFactory::clearAll () static
Definition at line 150 of file BasisFactory.cpp.
Referenced by GmshFinalize().
getBezierBasis() [1/3]
const bezierBasis * BasisFactory::getBezierBasis (FuncSpaceData fsd) static
Definition at line 128 of file BasisFactory.cpp.
Referenced by bezierCoeff::_computeCoefficients(), getBezierBasis(), and MElement::getBezierVerticesCoord().
getBezierBasis() [2/3]
const bezierBasis * BasisFactory::getBezierBasis (int parentType, int order) static
Definition at line 140 of file BasisFactory.cpp.
getBezierBasis() [3/3]
const bezierBasis * BasisFactory::getBezierBasis (int tag) static
Definition at line 145 of file BasisFactory.cpp.
getCondNumBasis()
const CondNumBasis * BasisFactory::getCondNumBasis (int tag, int cnOrder = -1) static
Definition at line 95 of file BasisFactory.cpp.
Referenced by MElement::signedInvCondNumRange().
getGradientBasis() [1/3]
const GradientBasis * BasisFactory::getGradientBasis (int tag) static
Definition at line 123 of file BasisFactory.cpp.
getGradientBasis() [2/3]
const GradientBasis * BasisFactory::getGradientBasis (int tag, FuncSpaceData fsd) static
Definition at line 105 of file BasisFactory.cpp.
Referenced by CondNumBasis::CondNumBasis(), getGradientBasis(), JacobianBasis::JacobianBasis(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), jacobianBasedQuality::sampleICNMeasure(), and jacobianBasedQuality::sampleIGEMeasure().
getGradientBasis() [3/3]
const GradientBasis * BasisFactory::getGradientBasis (int tag, int order) static
Definition at line 117 of file BasisFactory.cpp.
getJacobianBasis() [1/3]
const JacobianBasis * BasisFactory::getJacobianBasis (int tag) static
Definition at line 84 of file BasisFactory.cpp.
getJacobianBasis() [2/3]
const JacobianBasis * BasisFactory::getJacobianBasis (int tag, FuncSpaceData fsd) static
Definition at line 62 of file BasisFactory.cpp.
Referenced by getJacobianBasis(), MPoint::getJacobianFuncSpace(), MElement::getJacobianFuncSpace(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), jacobianBasedQuality::sampleICNMeasure(), jacobianBasedQuality::sampleIGEMeasure(), and jacobianBasedQuality::sampleJacobianDeterminant().
getJacobianBasis() [3/3]
const JacobianBasis * BasisFactory::getJacobianBasis (int tag, int order) static
Definition at line 74 of file BasisFactory.cpp.
getNodalBasis()
const nodalBasis * BasisFactory::getNodalBasis (int tag) static
Definition at line 23 of file BasisFactory.cpp.
Referenced by CondNumBasis::CondNumBasis(), GMSH_CurvedBndDistPlugin::execute(), MFaceN::frame(), ClosureGen::generateFaceClosureHex(), ClosureGen::generateFaceClosurePyr(), MElement::getFunctionSpace(), MElement::getNodesCoordNonSerendip(), GradientBasis::GradientBasis(), incompleteBasis::incompleteBasis(), MEdgeN::interpolate(), JacobianBasis::JacobianBasis(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), MFaceN::normal(), MEdgeN::pnt(), MFaceN::pnt(), PViewDataList::setOrder2(), MEdgeN::tangent(), and MFaceN::tangent().
Member Data Documentation
bs
std::map< FuncSpaceData, bezierBasis * > BasisFactory::bs static private
Definition at line 22 of file BasisFactory.h.
Referenced by clearAll(), and getBezierBasis().
cs
std::map< int, CondNumBasis * > BasisFactory::cs static private
Definition at line 20 of file BasisFactory.h.
Referenced by clearAll(), and getCondNumBasis().
fs
std::map< int, nodalBasis * > BasisFactory::fs static private
Definition at line 19 of file BasisFactory.h.
Referenced by clearAll(), and getNodalBasis().
gs
std::map< FuncSpaceData, GradientBasis * > BasisFactory::gs static private
Definition at line 23 of file BasisFactory.h.
Referenced by clearAll(), and getGradientBasis().
js
std::map< FuncSpaceData, JacobianBasis * > BasisFactory::js static private
Definition at line 21 of file BasisFactory.h.
Referenced by clearAll(), and getJacobianBasis().
The documentation for this class was generated from the following files:
src/numeric/BasisFactory.h
src/numeric/BasisFactory.cpp