gmsh-TingyuanDoc: GPoint Class Reference
GPoint Class Reference
#include <GPoint.h>
Public Member Functions
double x () const
double y () const
double z () const
double & x ()
double & y ()
double & z ()
double u () const
double v () const
const GEntity * g () const
GPoint (double _x=0, double _y=0, double _z=0, const GEntity *onwhat=nullptr)
GPoint (double _x, double _y, double _z, const GEntity *onwhat, double p)
GPoint (double _x, double _y, double _z, const GEntity *onwhat, double p[2])
GPoint (double _x, double _y, double _z, const GEntity *onwhat, double p1, double p2)
double distance (GPoint &p)
bool succeeded () const
bool setNoSuccess ()
Private Attributes
double X
double Y
double Z
const GEntity * e
double par [2]
bool success
Detailed Description
Definition at line 13 of file GPoint.h.
Constructor & Destructor Documentation
GPoint() [1/4]
GPoint::GPoint (double _x = 0, double _y = 0, double _z = 0, const GEntity * onwhat = nullptr) inline
Definition at line 30 of file GPoint.h.
GPoint() [2/4]
GPoint::GPoint (double _x, double _y, double _z, const GEntity * onwhat, double p) inline
Definition at line 37 of file GPoint.h.
GPoint() [3/4]
GPoint::GPoint (double _x, double _y, double _z, const GEntity * onwhat, double p[2]) inline
Definition at line 43 of file GPoint.h.
GPoint() [4/4]
GPoint::GPoint (double _x, double _y, double _z, const GEntity * onwhat, double p1, double p2) inline
Definition at line 49 of file GPoint.h.
Member Function Documentation
distance()
double GPoint::distance (GPoint & p) inline
Definition at line 56 of file GPoint.h.
Referenced by GFace::fillPointCloud(), and GEdge::getAdditionalInfoString().
g()
const GEntity* GPoint::g () const inline
Definition at line 29 of file GPoint.h.
Referenced by GeomMeshMatcher::forceTomatch(), and getFaceVerticesOnGeo().
setNoSuccess()
bool GPoint::setNoSuccess () inline
Definition at line 64 of file GPoint.h.
Referenced by failedProjection(), discreteFace::intersectionWithCircle(), and discreteFace::point().
succeeded()
bool GPoint::succeeded () const inline
Definition at line 63 of file GPoint.h.
Referenced by _isItAGoodIdeaToMoveThatVertex(), _relocate(), _relocateVertex2(), SurfaceProjector::closestPoint(), computeEdgeLinearLength(), computeEquidistantParameters(), getFaceVerticesOnGeo(), GFaceDelaunayRefinement(), SurfaceProjector::initialize(), insertAPoint(), middlePoint(), minimizeTutteEnergyParam(), optimalPointFrontalB(), optimize1DMeshAtAcuteCorners(), PolyMesh2GFace(), GFace::setMeshMaster(), and splitEdgePass().
u()
double GPoint::u () const inline
Definition at line 27 of file GPoint.h.
Referenced by quadMeshRemoveHalfOfOneDMesh::_subdivide(), _tryToCollapseThatVertex(), computeEquidistantParameters(), copy_vertices(), copyMesh(), blyr_manager::extrude_one_external(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), GeomMeshMatcher::forceTomatch(), getCentroidUV(), getFaceVerticesOnGeo(), GFaceDelaunayRefinement(), SurfaceProjector::initialize(), meshGeneratorPeriodic(), middlePoint(), minimizeTutteEnergyProj(), optimize1DMeshAtAcuteCorners(), discreteFace::parFromPoint(), PolyMesh2GFace(), relocateSlaveVertices(), discreteEdge::reparamOnFace(), and Subdivide().
v()
double GPoint::v () const inline
Definition at line 28 of file GPoint.h.
Referenced by quadMeshRemoveHalfOfOneDMesh::_subdivide(), _tryToCollapseThatVertex(), computeEquidistantParameters(), copy_vertices(), copyMesh(), blyr_manager::extrude_one_external(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), GeomMeshMatcher::forceTomatch(), getCentroidUV(), getFaceVerticesOnGeo(), GFaceDelaunayRefinement(), SurfaceProjector::initialize(), meshGeneratorPeriodic(), middlePoint(), minimizeTutteEnergyProj(), discreteFace::parFromPoint(), PolyMesh2GFace(), relocateSlaveVertices(), discreteEdge::reparamOnFace(), and Subdivide().
x() [1/2]
double& GPoint::x () inline
Definition at line 24 of file GPoint.h.
x() [2/2]
double GPoint::x () const inline
Definition at line 21 of file GPoint.h.
Referenced by _isItAGoodIdeaToMoveThatVertex(), _printTris(), _relocate(), _relocateVertex2(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), _tryToCollapseThatVertex(), _tryToCollapseThatVertex2(), BDS_Mesh::add_point(), GEdge::bounds(), GFace::buildRepresentationCross(), GFace::buildSTLTriangulation(), GFace::closestPoint(), computeEdgeLinearLength(), GFace::computeMeanPlane(), copy_vertices(), copyMesh(), correctLC_(), distance(), blyr_manager::extrude_one_external(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), faceCircumCenter(), faceQuality(), fillPointCloud(), GFace::fillVertexArray(), GeomMeshMatcher::forceTomatch(), getCentroidUV(), getEdgeVerticesOnGeo(), getFaceVerticesOnGeo(), getGEdge(), getGFace(), GRegion::getOBB(), GEdge::getOBB(), GFace::getOBB(), SurfaceProjector::initialize(), insertAPoint(), DocRecord::makePosView(), Mesh2DWithBoundaryLayers(), meshGeneratorPeriodic(), MeshTransfiniteSurface(), middlePoint(), minimizeTutteEnergyParam(), minimizeTutteEnergyProj(), gmshFace::normal(), objective_function(), meshGEdge::operator()(), surfaceFunctorGFace::operator()(), curveFunctorGEdge::operator()(), F_LcB::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), BoundaryLayerField::operator()(), optimize1DMeshAtAcuteCorners(), outputScalarField(), PolyMesh2GFace(), GEdge::position(), backgroundMesh::print(), DocRecord::printMedialAxis(), GEdge::relocateMeshVertices(), GFace::relocateMeshVertices(), relocateSlaveVertices(), remeshUnrecoveredEdges(), discreteEdge::reparamOnFace(), GEdge::reparamOnFace(), GFace::setMeshMaster(), gmshVertex::setPosition(), discreteVertex::setPosition(), GModel::snapVertices(), splitAllEdgesConnectedToSingularity(), splitEdgePass(), GFace::storeSTLAsMesh(), Subdivide(), GEdge::writeGEO(), writeSTLfaces(), writeX3dFaces(), and GFace::XYZtoUV().
y() [1/2]
double& GPoint::y () inline
Definition at line 25 of file GPoint.h.
y() [2/2]
double GPoint::y () const inline
Definition at line 22 of file GPoint.h.
Referenced by _isItAGoodIdeaToMoveThatVertex(), _printTris(), _relocate(), _relocateVertex2(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), _tryToCollapseThatVertex(), _tryToCollapseThatVertex2(), BDS_Mesh::add_point(), GEdge::bounds(), GFace::buildRepresentationCross(), GFace::buildSTLTriangulation(), GFace::closestPoint(), computeEdgeLinearLength(), GFace::computeMeanPlane(), copy_vertices(), copyMesh(), correctLC_(), distance(), blyr_manager::extrude_one_external(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), faceCircumCenter(), faceQuality(), fillPointCloud(), GFace::fillVertexArray(), GeomMeshMatcher::forceTomatch(), getCentroidUV(), getEdgeVerticesOnGeo(), getFaceVerticesOnGeo(), getGEdge(), getGFace(), GRegion::getOBB(), GEdge::getOBB(), GFace::getOBB(), SurfaceProjector::initialize(), insertAPoint(), DocRecord::makePosView(), Mesh2DWithBoundaryLayers(), meshGeneratorPeriodic(), MeshTransfiniteSurface(), middlePoint(), minimizeTutteEnergyParam(), minimizeTutteEnergyProj(), gmshFace::normal(), objective_function(), meshGEdge::operator()(), surfaceFunctorGFace::operator()(), curveFunctorGEdge::operator()(), F_LcB::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), BoundaryLayerField::operator()(), optimize1DMeshAtAcuteCorners(), outputScalarField(), PolyMesh2GFace(), GEdge::position(), backgroundMesh::print(), DocRecord::printMedialAxis(), GEdge::relocateMeshVertices(), GFace::relocateMeshVertices(), relocateSlaveVertices(), remeshUnrecoveredEdges(), discreteEdge::reparamOnFace(), GEdge::reparamOnFace(), GFace::setMeshMaster(), gmshVertex::setPosition(), discreteVertex::setPosition(), GModel::snapVertices(), splitAllEdgesConnectedToSingularity(), splitEdgePass(), GFace::storeSTLAsMesh(), Subdivide(), GEdge::writeGEO(), writeSTLfaces(), writeX3dFaces(), and GFace::XYZtoUV().
z() [1/2]
double& GPoint::z () inline
Definition at line 26 of file GPoint.h.
z() [2/2]
double GPoint::z () const inline
Definition at line 23 of file GPoint.h.
Referenced by _isItAGoodIdeaToMoveThatVertex(), _printTris(), _relocate(), _relocateVertex2(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), _tryToCollapseThatVertex(), _tryToCollapseThatVertex2(), BDS_Mesh::add_point(), GEdge::bounds(), GFace::buildRepresentationCross(), GFace::buildSTLTriangulation(), GFace::closestPoint(), computeEdgeLinearLength(), GFace::computeMeanPlane(), copy_vertices(), copyMesh(), correctLC_(), distance(), blyr_manager::extrude_one_external(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), blyr_manager::extrude_vertices_on_edges(), faceCircumCenter(), faceQuality(), fillPointCloud(), GFace::fillVertexArray(), GeomMeshMatcher::forceTomatch(), getCentroidUV(), getEdgeVerticesOnGeo(), getFaceVerticesOnGeo(), getGEdge(), getGFace(), GRegion::getOBB(), GEdge::getOBB(), GFace::getOBB(), SurfaceProjector::initialize(), insertAPoint(), DocRecord::makePosView(), Mesh2DWithBoundaryLayers(), meshGeneratorPeriodic(), MeshTransfiniteSurface(), middlePoint(), minimizeTutteEnergyParam(), minimizeTutteEnergyProj(), gmshFace::normal(), objective_function(), meshGEdge::operator()(), surfaceFunctorGFace::operator()(), curveFunctorGEdge::operator()(), F_LcB::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), BoundaryLayerField::operator()(), optimize1DMeshAtAcuteCorners(), outputScalarField(), PolyMesh2GFace(), GEdge::position(), backgroundMesh::print(), DocRecord::printMedialAxis(), GEdge::relocateMeshVertices(), GFace::relocateMeshVertices(), relocateSlaveVertices(), remeshUnrecoveredEdges(), discreteEdge::reparamOnFace(), GEdge::reparamOnFace(), GFace::setMeshMaster(), gmshVertex::setPosition(), discreteVertex::setPosition(), GModel::snapVertices(), splitAllEdgesConnectedToSingularity(), splitEdgePass(), GFace::storeSTLAsMesh(), Subdivide(), GEdge::writeGEO(), writeSTLfaces(), writeX3dFaces(), and GFace::XYZtoUV().
Member Data Documentation
e
const GEntity* GPoint::e private
Definition at line 16 of file GPoint.h.
Referenced by g().
par
double GPoint::par[2] private
Definition at line 17 of file GPoint.h.
Referenced by GPoint(), u(), and v().
success
bool GPoint::success private
Definition at line 18 of file GPoint.h.
Referenced by setNoSuccess(), and succeeded().
X
double GPoint::X private
Definition at line 15 of file GPoint.h.
Referenced by distance(), and x().
Y
double GPoint::Y private
Definition at line 15 of file GPoint.h.
Referenced by distance(), and y().
Z
double GPoint::Z private
Definition at line 15 of file GPoint.h.
Referenced by distance(), and z().
The documentation for this class was generated from the following file:
src/geo/GPoint.h