gmsh-TingyuanDoc: BergotBasis Class Reference
BergotBasis Class Reference
#include <BergotBasis.h>
Public Member Functions
BergotBasis (int p, bool incpl=false)
virtual ~BergotBasis ()
void f (double u, double v, double w, double *val) const
void df (double u, double v, double w, double grads[][3]) const
void initialize ()
bool validIJ (int i, int j) const
Private Attributes
int order
bool incomplete
serendipity interpolation
Detailed Description
Definition at line 17 of file BergotBasis.h.
Constructor & Destructor Documentation
BergotBasis()
BergotBasis::BergotBasis (int p, bool incpl = false)
Definition at line 11 of file BergotBasis.cpp.
~BergotBasis()
BergotBasis::~BergotBasis () virtual
Definition at line 18 of file BergotBasis.cpp.
Member Function Documentation
df()
void BergotBasis::df (double u, double v, double w, double grads[][3]) const
Definition at line 80 of file BergotBasis.cpp.
Referenced by pyramidalBasis::df().
f()
void BergotBasis::f (double u, double v, double w, double * val) const
Definition at line 33 of file BergotBasis.cpp.
Referenced by pyramidalBasis::f(), and pyramidalBasis::pyramidalBasis().
initialize()
void BergotBasis::initialize () inline
Definition at line 25 of file BergotBasis.h.
validIJ()
bool BergotBasis::validIJ (int i, int j) const
Definition at line 20 of file BergotBasis.cpp.
Referenced by df(), f(), and pyramidalBasis::pyramidalBasis().
Member Data Documentation
incomplete
bool BergotBasis::incomplete private
serendipity interpolation
Definition at line 32 of file BergotBasis.h.
Referenced by BergotBasis(), and validIJ().
order
int BergotBasis::order private
maximal order of surrounding functional spaces (on triangle / quad)
Definition at line 30 of file BergotBasis.h.
Referenced by BergotBasis(), df(), f(), and validIJ().
The documentation for this class was generated from the following files:
src/numeric/BergotBasis.h
src/numeric/BergotBasis.cpp