gmsh-TingyuanDoc: CTX Class Reference
CTX Class Reference
#include <Context.h>
Public Member Functions
CTX ()
~CTX ()
void init ()
unsigned int packColor (int R, int G, int B, int A)
int unpackRed (unsigned int X)
int unpackGreen (unsigned int X)
int unpackBlue (unsigned int X)
int unpackAlpha (unsigned int X)
Static Public Member Functions
static CTX * instance ()
Public Attributes
int debugSurface
std::vector< std::string > files
std::string bgmFileName
std::string outputFileName
std::string defaultFileName
std::string tmpFileName
std::string sessionFileName
std::string optionsFileName
std::string errorFileName
std::string meshStatReportFileName
std::string exeFileName
std::string homeDir
std::vector< std::string > recentFiles
int createAppendMeshStatReport
int abortOnError
int launchSolverAtStartup
int sessionSave
int optionsSave
int confirmOverwrite
std::string display
std::string guiTheme
int guiColorScheme
int guiRefreshRate
int terminal
int numThreads
int detachedProcess
int numWindows
int numTiles
std::string editor
std::string watchFilePattern
std::vector< std::string > scriptLang
int tooltips
int inputScrolling
int glPosition [2]
int glSize [2]
int msgSize
int menuPosition [2]
int menuSize [2]
int detachedMenu
int optPosition [2]
int visPosition [2]
int hotPosition [2]
int clipPosition [2]
int manipPosition [2]
int statPosition [2]
int ctxPosition [2]
int pluginPosition [2]
int pluginSize [2]
int fieldPosition [2]
int fieldSize [2]
int fileChooserPosition [2]
int extraPosition [2]
int extraSize [2]
int systemMenuBar
int nativeFileChooser
int showModuleMenu
int highResolutionGraphics
int batch
int batchAfterMesh
double batchSomeValue
int initialContext
int showOptionsOnStartup
int showMessagesOnStartup
int noPopup
int nonModalWindows
double clipFactor
double displayBorderFactor
int useTrackball
int trackballHyperbolicSheet
GamePad * gamepad
double rotationCenter [3]
int rotationCenterCg
double min [3]
double max [3]
double cg [3]
double lc
int db
int antialiasing
int stereo
int camera
bool fileread
double eye_sep_ratio
double focallength_ratio
double camera_aperture
int ortho
int drawBBox
int drawRotationCenter
int fastRedraw
int smallAxes
int smallAxesSize
int smallAxesPos [2]
int axes
int axesAutoPosition
int axesMikado
int axesForceValue
double axesPosition [6]
double axesValue [6]
double axesTics [3]
std::string axesLabel [3]
std::string axesFormat [3]
int lock
int alpha
double zoomFactor
int bgGradient
std::string bgImageFileName
double bgImagePosition [2]
double bgImageSize [2]
int bgImage3d
int bgImagePage
int fontSize
int deltaFontSize
std::string glFont
std::string glFontTitle
std::string glFontEngine
int glFontEnum
int glFontEnumTitle
int glFontSize
int glFontSizeTitle
int msgFontSize
double pointSize
double lineWidth
double highResolutionPointSizeFactor
int light [6]
double lightPosition [6][4]
double shine
double shineExponent
double clipPlane [6][4]
int clipWholeElements
int clipOnlyDrawIntersectingVolume
int clipOnlyVolume
int polygonOffset
int polygonOffsetAlways
double polygonOffsetFactor
double polygonOffsetUnits
int colorScheme
int quadricSubdivisions
int vectorType
double arrowRelHeadRadius
double arrowRelStemRadius
double arrowRelStemLength
double meshTimer [3]
int forcedBBox
int mouseSelection
int mouseHoverMeshes
int pickElements
int mouseInvertZoom
int expertMode
int printing
int hideUnselected
double tmpRotation [3]
double tmpTranslation [3]
double tmpScale [3]
double tmpQuaternion [4]
contextGeometryOptions geom
contextMeshOptions mesh
struct {
int draw
int link
int horizontalScales
int binary
int smooth
int animCycle
int animStep
int combineTime
int combineRemoveOrig
int combineCopyOptions
int fileFormat
int plugins
int forceNodeData
int forceElementData
int saveMesh
int saveInterpolationMatrices
double animDelay
std::string doubleClickedGraphPointCommand
double doubleClickedGraphPointX
double doubleClickedGraphPointY
int doubleClickedView
} post
struct {
int plugins
int listen
double timeout
std::string socketName
std::string pythonInterpreter
std::string octaveInterpreter
std::string name [NUM_SOLVERS]
std::string extension [NUM_SOLVERS]
std::string executable [NUM_SOLVERS]
std::string remoteLogin [NUM_SOLVERS]
int autoSaveDatabase
int autoLoadDatabase
int autoArchiveOutputFiles
int autoMesh
int autoMergeFile
int autoShowViews
int autoShowLastStep
int autoCheck
int showInvisibleParameters
} solver
struct {
int fileFormat
int epsQuality
int epsCompress
int epsPS3Shading
int epsOcclusionCulling
int epsBestRoot
double epsLineWidthFactor
double epsPointSizeFactor
int jpegQuality
int jpegSmoothing
int geoLabels
int geoOnlyPhysicals
int text
int texAsEquation
int texForceFontSize
double texWidthInMm
int gifDither
int gifSort
int gifInterlace
int gifTransparent
int posElementary
int posElement
int posGamma
int posEta
int posSICN
int posSIGE
int posDisto
int compositeWindows
int deleteTmpFiles
int background
int width
int height
double parameter
double parameterFirst
double parameterLast
double parameterSteps
int pgfTwoDim
int pgfExportAxis
int pgfHorizBar
std::string parameterCommand
int x3dCompatibility
int x3dRemoveInnerBorders
double x3dPrecision
double x3dTransparency
int x3dSurfaces
int x3dEdges
int x3dVertices
int x3dVolumes
int x3dColorize
} print
struct {
unsigned int bg
unsigned int bgGrad
unsigned int fg
unsigned int text
unsigned int axes
unsigned int smallAxes
unsigned int ambientLight [6]
unsigned int diffuseLight [6]
unsigned int specularLight [6]
struct {
unsigned int point
unsigned int curve
unsigned int surface
unsigned int volume
unsigned int selection
unsigned int highlight [3]
unsigned int projection
unsigned int tangents
unsigned int normals
} geom
struct {
unsigned int node
unsigned int nodeSup
unsigned int line
unsigned int triangle
unsigned int quadrangle
unsigned int tetrahedron
unsigned int hexahedron
unsigned int prism
unsigned int pyramid
unsigned int trihedron
unsigned int carousel [20]
unsigned int tangents
unsigned int normals
} mesh
} color
int bigEndian
Static Private Attributes
static CTX * _instance = nullptr
Detailed Description
Definition at line 127 of file Context.h.
Constructor & Destructor Documentation
CTX()
CTX::CTX ()
Definition at line 17 of file Context.cpp.
Referenced by instance().
~CTX()
CTX::~CTX ()
Definition at line 25 of file Context.cpp.
Member Function Documentation
init()
void CTX::init ()
Definition at line 30 of file Context.cpp.
Referenced by CTX(), and InitOptions().
instance()
CTX * CTX::instance () static
Definition at line 122 of file Context.cpp.
Referenced by VertexArray::_addElement(), _checkInit(), OctreePost::_create(), drawGFace::_drawVertexArray(), initMeshGRegion::_estimateIfClipped(), initPView::_estimateIfClipped(), initMeshGEdge::_estimateNumLines(), initMeshGFace::_estimateNumLines(), initMeshGRegion::_estimateNumLines(), initMeshGFace::_estimateNumTriangles(), initMeshGRegion::_estimateNumTriangles(), _getElementary(), _opt_geometry_offset(), _opt_geometry_transform(), GModel::_readMSH2(), GModel::_readMSH3(), quadMeshRemoveHalfOfOneDMesh::_subdivide(), GModel::_writeMSH2(), GModel::_writePartitionedMSH4(), AdaptMesh(), GModel::adaptMesh(), VertexArray::add(), addElementsInArrays(), addGmshPathToEnvironmentVar(), addGraphPoint(), drawContext::addQuaternion(), addSmoothNormals(), AddToTemporaryBoundingBox(), Camera::affiche(), almostEqual(), ApplicationOnShapes(), assemble2d(), assemble3d(), assembleColmapStr(), backgroundMesh::backgroundMesh(), BGM_MeshMetric(), BGM_MeshSize(), BGM_MeshSizeWithoutScaling(), buildBackgroundMesh(), GModel::buildCutGModel(), buildMetricTangentToSurface(), GFace::buildRepresentationCross(), drawContext::buildRotationMatrix(), GMSH_ProbePlugin::callback(), GMSH_CutPlanePlugin::callbackD(), GMSH_CutSpherePlugin::callbackR(), GMSH_CutSpherePlugin::callbackX(), GMSH_AnnotatePlugin::callbackX(), GMSH_ParticlesPlugin::callbackX0(), GMSH_StreamLinesPlugin::callbackX0(), GMSH_CutGridPlugin::callbackX0(), GMSH_CutBoxPlugin::callbackX0(), GMSH_ParticlesPlugin::callbackX1(), GMSH_StreamLinesPlugin::callbackX1(), GMSH_CutGridPlugin::callbackX1(), GMSH_CutBoxPlugin::callbackX1(), GMSH_ParticlesPlugin::callbackX2(), GMSH_StreamLinesPlugin::callbackX2(), GMSH_CutGridPlugin::callbackX2(), GMSH_CutBoxPlugin::callbackX2(), GMSH_CutBoxPlugin::callbackX3(), GMSH_CutSpherePlugin::callbackY(), GMSH_AnnotatePlugin::callbackY(), GMSH_ParticlesPlugin::callbackY0(), GMSH_StreamLinesPlugin::callbackY0(), GMSH_CutGridPlugin::callbackY0(), GMSH_CutBoxPlugin::callbackY0(), GMSH_ParticlesPlugin::callbackY1(), GMSH_StreamLinesPlugin::callbackY1(), GMSH_CutGridPlugin::callbackY1(), GMSH_CutBoxPlugin::callbackY1(), GMSH_ParticlesPlugin::callbackY2(), GMSH_StreamLinesPlugin::callbackY2(), GMSH_CutGridPlugin::callbackY2(), GMSH_CutBoxPlugin::callbackY2(), GMSH_CutBoxPlugin::callbackY3(), GMSH_CutSpherePlugin::callbackZ(), GMSH_AnnotatePlugin::callbackZ(), GMSH_ParticlesPlugin::callbackZ0(), GMSH_StreamLinesPlugin::callbackZ0(), GMSH_CutGridPlugin::callbackZ0(), GMSH_CutBoxPlugin::callbackZ0(), GMSH_StreamLinesPlugin::callbackZ1(), GMSH_ParticlesPlugin::callbackZ1(), GMSH_CutGridPlugin::callbackZ1(), GMSH_CutBoxPlugin::callbackZ1(), GMSH_ParticlesPlugin::callbackZ2(), GMSH_StreamLinesPlugin::callbackZ2(), GMSH_CutGridPlugin::callbackZ2(), GMSH_CutBoxPlugin::callbackZ2(), GMSH_CutBoxPlugin::callbackZ3(), ChangePrintParameter(), discreteFace::param::checkPlanar(), classifyFaces(), ClearProject(), ColorOption(), ColorTable_IsAlpha(), ColorTable_Print(), ColorTable_Recompute(), ComparePosition(), BoundaryLayerField::computeFor1dMesh(), GFace::computeMeanPlane(), meshMetric::computeMetric(), meshMetric::computeMetricEigenDir(), computeNodalSizes(), CopyCurve(), CopySurface(), CopyVolume(), correctLC_(), createElementMSH2(), CreateOutputFile(), drawContext::createQuadricsAndDisplayLists(), GModel::createTopologyFromMesh(), CurvatureField::CurvatureField(), Msg::Debug(), delaunayTriangulation(), DeleteAllModelsAndViews(), GModel::destroy(), DilatShapes(), Msg::Direct(), GMSH_ProbePlugin::draw(), GMSH_CutSpherePlugin::draw(), GMSH_CutPlanePlugin::draw(), GMSH_AnnotatePlugin::draw(), GMSH_StreamLinesPlugin::draw(), GMSH_ParticlesPlugin::draw(), GMSH_CutParametricPlugin::draw(), GMSH_CutGridPlugin::draw(), GMSH_CutBoxPlugin::draw(), drawContext::draw2d(), drawContext::draw3d(), drawArrays(), drawContext::drawAxes(), drawContext::drawBackgroundGradient(), drawContext::drawBackgroundImage(), drawBarycentricDual(), drawContext::drawBox(), drawContext::drawContext(), drawContext::drawCylinder(), drawElementLabels(), drawEntityLabel(), drawContext::drawGeom(), drawContext::drawGraph2d(), drawGraphAxes(), drawGraphCurves(), drawContext::drawMesh(), drawNormals(), drawNormalVectorGlyphs(), drawContext::drawPlaneInBoundingBox(), drawContext::drawPost(), drawScaleLabel(), drawContext::drawScales(), drawScaleValues(), drawSimpleVector(), drawContext::drawSmallAxes(), drawContext::drawString(), drawContext::drawStringCenter(), drawContext::drawStringRight(), drawTangents(), drawTangentVectorGlyphs(), drawContext::drawTaperedCylinder(), drawTics(), drawContext::drawVector(), drawVertexLabel(), drawVerticesPerElement(), drawVerticesPerEntity(), drawVoronoiDual(), edgeSwapTest(), EndCurve(), Msg::Error(), evalClipPlane(), GMSH_CrackPlugin::execute(), GMSH_MeshSubEntitiesPlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_DiscretizationErrorPlugin::execute(), GMSH_ShowNeighborElementsPlugin::execute(), Extend2dMeshIn3dVolumes(), ExtrudeCurve(), ExtrudePoint(), ExtrudeShapes(), ExtrudeSurface(), eyeChanged(), BoundaryLayerField::fanSize(), GFace::fillVertexArray(), GModel::fillVertexArrays(), filterPoints(), PViewDataList::finalize(), MElementOctree::find(), MElementOctree::findAll(), quadMeshRemoveHalfOfOneDMesh::finish(), FinishUpBoundingBox(), FixPeriodicMesh(), GenerateMesh(), GEntity::GEntity(), Msg::GetAnswer(), getColorByElement(), getColorByEntity(), GetColorForString(), MTetrahedron::getEdgeRep(), MQuadrangle::getEdgeRep(), MTriangle::getEdgeRep(), MHexahedron::getEdgeRep(), MLine3::getEdgeRep(), MTriangle6::getEdgeRep(), MLineN::getEdgeRep(), MQuadrangle8::getEdgeRep(), MTetrahedron10::getEdgeRep(), MPrism15::getEdgeRep(), MHexahedron20::getEdgeRep(), MPyramidN::getEdgeRep(), MTriangleN::getEdgeRep(), MQuadrangle9::getEdgeRep(), MPrism18::getEdgeRep(), MTetrahedronN::getEdgeRep(), MQuadrangleN::getEdgeRep(), MHexahedron27::getEdgeRep(), MPrismN::getEdgeRep(), MHexahedronN::getEdgeRep(), getElement(), getEntitiesToSave(), MQuadrangle::getFaceRep(), MHexahedron::getFaceRep(), MPrism::getFaceRep(), MPyramid::getFaceRep(), MTriangle6::getFaceRep(), MQuadrangle8::getFaceRep(), MTetrahedron10::getFaceRep(), MPrism15::getFaceRep(), MPyramidN::getFaceRep(), MHexahedron20::getFaceRep(), MTriangleN::getFaceRep(), MQuadrangle9::getFaceRep(), MPrism18::getFaceRep(), MTetrahedronN::getFaceRep(), MQuadrangleN::getFaceRep(), MHexahedron27::getFaceRep(), MPrismN::getFaceRep(), MHexahedronN::getFaceRep(), GetGeometryOption(), GEntity::getInfoString(), GFace::getMeshingAlgo(), GetMeshOption(), GFace::getMeshSizeFromBoundary(), GModel::getMeshStatus(), getMinMaxOfAxis(), MLine3::getNumEdgesRep(), MTriangle6::getNumEdgesRep(), MLineN::getNumEdgesRep(), MQuadrangle8::getNumEdgesRep(), MTetrahedron10::getNumEdgesRep(), MPrism15::getNumEdgesRep(), MHexahedron20::getNumEdgesRep(), MPyramidN::getNumEdgesRep(), MTriangleN::getNumEdgesRep(), MQuadrangle9::getNumEdgesRep(), MPrism18::getNumEdgesRep(), MTetrahedronN::getNumEdgesRep(), MQuadrangleN::getNumEdgesRep(), MHexahedron27::getNumEdgesRep(), MPrismN::getNumEdgesRep(), MHexahedronN::getNumEdgesRep(), getNumElementsMSH(), MQuadrangle::getNumFacesRep(), MHexahedron::getNumFacesRep(), MPrism::getNumFacesRep(), MPyramid::getNumFacesRep(), MTriangle6::getNumFacesRep(), MQuadrangle8::getNumFacesRep(), MTetrahedron10::getNumFacesRep(), MPrism15::getNumFacesRep(), MHexahedron20::getNumFacesRep(), MPyramidN::getNumFacesRep(), MTriangleN::getNumFacesRep(), MQuadrangle9::getNumFacesRep(), MPrism18::getNumFacesRep(), MTetrahedronN::getNumFacesRep(), MQuadrangleN::getNumFacesRep(), MHexahedron27::getNumFacesRep(), MPrismN::getNumFacesRep(), MHexahedronN::getNumFacesRep(), GetOptions(), GetOtherOption(), GetPostProcessingOption(), GetSolverOption(), GetStatistics(), Msg::GetString(), element::getTolerance(), MElement::getTolerance(), Msg::GetValue(), MElement::getVisibility(), GEntity::getVisibility(), GModel::GModel(), GmshBatch(), GmshFLTK(), GmshMainBatch(), GmshMainFLTK(), GmshMergePostProcessingFile(), GradientField::GradientField(), Msg::Info(), Camera::init(), Msg::Initialize(), InitOptions(), drawContext::initPosition(), drawContext::initProjection(), drawContext::initRenderModel(), insertAPoint(), insertVerticesInRegion(), InterpolateRuledSurface(), InterpolateSurface(), isElementVisible(), LaplacianField::LaplacianField(), LC_MVertex_CURV(), LC_MVertex_CURV_ANISO(), LC_MVertex_PNTS(), Camera::lookAtCg(), GeomMeshMatcher::match(), GeomMeshMatcher::matchVertices(), max_edge_curvature_metric(), MaxEigenHessianField::MaxEigenHessianField(), MeanField::MeanField(), MergeFile(), GEdge::mesh(), GFace::mesh(), GModel::mesh(), Mesh1D(), Mesh2D(), Mesh2DWithBoundaryLayers(), Mesh3D(), MeshDelaunayVolume(), MeshExtrudedSurface(), meshGEdgeProcessing(), meshGenerator(), meshGeneratorPeriodic(), MeshSetTransfiniteFacesAutomatic(), MeshTransfiniteSurface(), metric_based_on_surface_curvature(), gmshEdge::minimumDrawSegments(), gmshEdge::minimumMeshSegments(), minmax(), needPolygonOffset(), NEWCURVE(), NEWCURVELOOP(), NEWPHYSICAL(), NEWSURFACE(), NEWSURFACELOOP(), NEWVOLUME(), OpenProject(), OpenProjectMacFinder(), meshGEdge::operator()(), meshGFace::operator()(), meshGRegion::operator()(), meshGRegionExtruded::operator()(), drawGVertex::operator()(), meshMetric::operator()(), drawGEdge::operator()(), F_Transfinite::operator()(), BoundaryLayerField::operator()(), initMeshGEdge::operator()(), drawGFace::operator()(), initMeshGFace::operator()(), drawMeshGVertex::operator()(), initMeshGRegion::operator()(), drawGRegion::operator()(), drawMeshGEdge::operator()(), drawPView::operator()(), drawMeshGFace::operator()(), drawMeshGRegion::operator()(), drawPViewBoundingBox::operator()(), initPView::operator()(), ExtendField::operator()(), opt_general_abort_on_error(), opt_general_alpha_blending(), opt_general_antialiasing(), opt_general_arrow_head_radius(), opt_general_arrow_stem_length(), opt_general_arrow_stem_radius(), opt_general_axes(), opt_general_axes_auto_position(), opt_general_axes_force_value(), opt_general_axes_format0(), opt_general_axes_format1(), opt_general_axes_format2(), opt_general_axes_label0(), opt_general_axes_label1(), opt_general_axes_label2(), opt_general_axes_mikado(), opt_general_axes_tics0(), opt_general_axes_tics1(), opt_general_axes_tics2(), opt_general_axes_value_xmax(), opt_general_axes_value_xmin(), opt_general_axes_value_ymax(), opt_general_axes_value_ymin(), opt_general_axes_value_zmax(), opt_general_axes_value_zmin(), opt_general_axes_xmax(), opt_general_axes_xmin(), opt_general_axes_ymax(), opt_general_axes_ymin(), opt_general_axes_zmax(), opt_general_axes_zmin(), opt_general_background_gradient(), opt_general_background_image_3d(), opt_general_background_image_filename(), opt_general_background_image_page(), opt_general_background_image_position0(), opt_general_background_image_position1(), opt_general_background_image_size0(), opt_general_background_image_size1(), opt_general_camera_aperture(), opt_general_camera_mode(), opt_general_clip0a(), opt_general_clip0b(), opt_general_clip0c(), opt_general_clip0d(), opt_general_clip1a(), opt_general_clip1b(), opt_general_clip1c(), opt_general_clip1d(), opt_general_clip2a(), opt_general_clip2b(), opt_general_clip2c(), opt_general_clip2d(), opt_general_clip3a(), opt_general_clip3b(), opt_general_clip3c(), opt_general_clip3d(), opt_general_clip4a(), opt_general_clip4b(), opt_general_clip4c(), opt_general_clip4d(), opt_general_clip5a(), opt_general_clip5b(), opt_general_clip5c(), opt_general_clip5d(), opt_general_clip_factor(), opt_general_clip_only_draw_intersecting_volume(), opt_general_clip_only_volume(), opt_general_clip_position0(), opt_general_clip_position1(), opt_general_clip_whole_elements(), opt_general_color_ambient_light(), opt_general_color_axes(), opt_general_color_background(), opt_general_color_background_gradient(), opt_general_color_diffuse_light(), opt_general_color_foreground(), opt_general_color_scheme(), opt_general_color_small_axes(), opt_general_color_specular_light(), opt_general_color_text(), opt_general_confirm_overwrite(), opt_general_context_position0(), opt_general_context_position1(), opt_general_default_filename(), opt_general_detached_menu(), opt_general_detached_process(), opt_general_display(), opt_general_display_border_factor(), opt_general_double_buffer(), opt_general_draw_bounding_box(), opt_general_editor(), opt_general_error_filename(), opt_general_executable_filename(), opt_general_expert_mode(), opt_general_extra_position0(), opt_general_extra_position1(), opt_general_extra_size0(), opt_general_extra_size1(), opt_general_eye_sep_ratio(), opt_general_fast_redraw(), opt_general_field_position0(), opt_general_field_position1(), opt_general_field_size0(), opt_general_field_size1(), opt_general_file_chooser_position0(), opt_general_file_chooser_position1(), opt_general_focallength_ratio(), opt_general_fontsize(), opt_general_gamepad(), opt_general_graphics_font(), opt_general_graphics_font_engine(), opt_general_graphics_font_title(), opt_general_graphics_fontsize(), opt_general_graphics_fontsize_title(), opt_general_graphics_position0(), opt_general_graphics_position1(), opt_general_graphics_size0(), opt_general_graphics_size1(), opt_general_gui_color_scheme(), opt_general_gui_refresh_rate(), opt_general_gui_theme(), opt_general_high_resolution_graphics(), opt_general_hot_position0(), opt_general_hot_position1(), opt_general_initial_context(), opt_general_input_scrolling(), opt_general_lc(), opt_general_light0(), opt_general_light00(), opt_general_light01(), opt_general_light02(), opt_general_light03(), opt_general_light1(), opt_general_light10(), opt_general_light11(), opt_general_light12(), opt_general_light13(), opt_general_light2(), opt_general_light20(), opt_general_light21(), opt_general_light22(), opt_general_light23(), opt_general_light3(), opt_general_light30(), opt_general_light31(), opt_general_light32(), opt_general_light33(), opt_general_light4(), opt_general_light40(), opt_general_light41(), opt_general_light42(), opt_general_light43(), opt_general_light5(), opt_general_light50(), opt_general_light51(), opt_general_light52(), opt_general_light53(), opt_general_line_width(), opt_general_manip_position0(), opt_general_manip_position1(), opt_general_menu_position0(), opt_general_menu_position1(), opt_general_menu_size0(), opt_general_menu_size1(), opt_general_message_fontsize(), opt_general_message_size(), opt_general_mouse_hover_meshes(), opt_general_mouse_invert_zoom(), opt_general_mouse_selection(), opt_general_native_file_chooser(), opt_general_non_modal_windows(), opt_general_nopopup(), opt_general_num_threads(), opt_general_option_position0(), opt_general_option_position1(), opt_general_options_filename(), opt_general_options_save(), opt_general_orthographic(), opt_general_plugin_position0(), opt_general_plugin_position1(), opt_general_plugin_size0(), opt_general_plugin_size1(), opt_general_point_size(), opt_general_polygon_offset_always(), opt_general_polygon_offset_factor(), opt_general_polygon_offset_units(), opt_general_quadric_subdivisions(), opt_general_quaternion0(), opt_general_quaternion1(), opt_general_quaternion2(), opt_general_quaternion3(), opt_general_recent_file0(), opt_general_recent_file1(), opt_general_recent_file2(), opt_general_recent_file3(), opt_general_recent_file4(), opt_general_recent_file5(), opt_general_recent_file6(), opt_general_recent_file7(), opt_general_recent_file8(), opt_general_recent_file9(), opt_general_rotation0(), opt_general_rotation1(), opt_general_rotation2(), opt_general_rotation_center0(), opt_general_rotation_center1(), opt_general_rotation_center2(), opt_general_rotation_center_cg(), opt_general_scale0(), opt_general_scale1(), opt_general_scale2(), opt_general_scripting_languages(), opt_general_session_filename(), opt_general_session_save(), opt_general_shine(), opt_general_shine_exponent(), opt_general_show_messages_on_startup(), opt_general_show_module_menu(), opt_general_show_options_on_startup(), opt_general_small_axes(), opt_general_small_axes_position0(), opt_general_small_axes_position1(), opt_general_small_axes_size(), opt_general_statistics_position0(), opt_general_statistics_position1(), opt_general_stereo_mode(), opt_general_system_menu_bar(), opt_general_terminal(), opt_general_tmp_filename(), opt_general_tooltips(), opt_general_trackball(), opt_general_trackball_hyperbolic_sheet(), opt_general_translation0(), opt_general_translation1(), opt_general_translation2(), opt_general_vector_type(), opt_general_visibility_position0(), opt_general_visibility_position1(), opt_general_watch_file_pattern(), opt_general_zoom_factor(), opt_geometry_auto_coherence(), opt_geometry_clip(), opt_geometry_color_curves(), opt_geometry_color_highlight0(), opt_geometry_color_highlight1(), opt_geometry_color_highlight2(), opt_geometry_color_normals(), opt_geometry_color_points(), opt_geometry_color_projection(), opt_geometry_color_selection(), opt_geometry_color_surfaces(), opt_geometry_color_tangents(), opt_geometry_color_volumes(), opt_geometry_copy_meshing_method(), opt_geometry_curve_labels(), opt_geometry_curve_sel_width(), opt_geometry_curve_type(), opt_geometry_curve_width(), opt_geometry_curves(), opt_geometry_double_clicked_curve_command(), opt_geometry_double_clicked_entity_tag(), opt_geometry_double_clicked_point_command(), opt_geometry_double_clicked_surface_command(), opt_geometry_double_clicked_volume_command(), opt_geometry_exact_extrusion(), opt_geometry_extrude_return_lateral(), opt_geometry_extrude_spline_points(), opt_geometry_highlight_orphans(), opt_geometry_label_type(), opt_geometry_light(), opt_geometry_light_two_side(), opt_geometry_match_geom_and_mesh(), opt_geometry_match_mesh_scale_factor(), opt_geometry_match_mesh_tolerance(), opt_geometry_normals(), opt_geometry_num_sub_edges(), opt_geometry_occ_auto_embed(), opt_geometry_occ_auto_fix(), opt_geometry_occ_boolean_preserve_numbering(), opt_geometry_occ_bounds_use_stl(), opt_geometry_occ_disable_stl(), opt_geometry_occ_export_only_visible(), opt_geometry_occ_fix_degenerated(), opt_geometry_occ_fix_small_edges(), opt_geometry_occ_fix_small_faces(), opt_geometry_occ_import_labels(), opt_geometry_occ_make_solids(), opt_geometry_occ_parallel(), opt_geometry_occ_safe_unbind(), opt_geometry_occ_scaling(), opt_geometry_occ_sew_faces(), opt_geometry_occ_target_unit(), opt_geometry_occ_thrusections_degree(), opt_geometry_occ_union_unify(), opt_geometry_occ_use_generic_closest_point(), opt_geometry_old_circle(), opt_geometry_old_newreg(), opt_geometry_old_ruled_surface(), opt_geometry_oriented_physicals(), opt_geometry_pipe_default_trihedron(), opt_geometry_point_labels(), opt_geometry_point_sel_size(), opt_geometry_point_size(), opt_geometry_point_type(), opt_geometry_points(), opt_geometry_reparam_on_face_robust(), opt_geometry_scaling_factor(), opt_geometry_snap0(), opt_geometry_snap1(), opt_geometry_snap2(), opt_geometry_snap_points(), opt_geometry_surface_labels(), opt_geometry_surface_type(), opt_geometry_surfaces(), opt_geometry_tangents(), opt_geometry_tolerance(), opt_geometry_tolerance_boolean(), opt_geometry_transform(), opt_geometry_volume_labels(), opt_geometry_volumes(), opt_mesh_algo2d(), opt_mesh_algo3d(), opt_mesh_algo_recombine(), opt_mesh_algo_subdivide(), opt_mesh_algo_switch_on_failure(), opt_mesh_allow_swap_edge_angle(), opt_mesh_angle_smooth_normals(), opt_mesh_angle_tolerance_facet_overlap(), opt_mesh_aniso_max(), opt_mesh_bdf_field_format(), opt_mesh_binary(), opt_mesh_boundary_layer_fan_elements(), opt_mesh_cgns_construct_topology(), opt_mesh_cgns_export_cpex0045(), opt_mesh_cgns_export_structured(), opt_mesh_cgns_import_ignore_bc(), opt_mesh_cgns_import_ignore_solution(), opt_mesh_cgns_import_order(), opt_mesh_clip(), opt_mesh_color_(), opt_mesh_color_carousel(), opt_mesh_color_hexahedra(), opt_mesh_color_lines(), opt_mesh_color_nodes(), opt_mesh_color_nodes_sup(), opt_mesh_color_normals(), opt_mesh_color_prisms(), opt_mesh_color_pyramid(), opt_mesh_color_quadrangles(), opt_mesh_color_tangents(), opt_mesh_color_tetrahedra(), opt_mesh_color_triangles(), opt_mesh_color_trihedron(), opt_mesh_compound_classify(), opt_mesh_compound_lc_factor(), opt_mesh_create_topology_msh2(), opt_mesh_cross_field_closest_point(), opt_mesh_draw_skin_only(), opt_mesh_dual(), opt_mesh_explode(), opt_mesh_file_format(), opt_mesh_first_element_tag(), opt_mesh_first_node_tag(), opt_mesh_flexible_transfinite(), opt_mesh_hexahedra(), opt_mesh_ho_curve_outer_BL(), opt_mesh_ho_dist_cad(), opt_mesh_ho_fast_new_algo(), opt_mesh_ho_fix_bnd_nodes(), opt_mesh_ho_iter_max(), opt_mesh_ho_max_angle(), opt_mesh_ho_max_in_angle(), opt_mesh_ho_max_rho(), opt_mesh_ho_nlayers(), opt_mesh_ho_optimize(), opt_mesh_ho_pass_max(), opt_mesh_ho_periodic(), opt_mesh_ho_poisson(), opt_mesh_ho_prim_surf_mesh(), opt_mesh_ho_save_periodic(), opt_mesh_ho_threshold_max(), opt_mesh_ho_threshold_min(), opt_mesh_ignore_parametrization(), opt_mesh_ignore_periodicity(), opt_mesh_label_sampling(), opt_mesh_label_type(), opt_mesh_lc_extend_from_boundary(), opt_mesh_lc_factor(), opt_mesh_lc_from_curvature(), opt_mesh_lc_from_curvature_iso(), opt_mesh_lc_from_parametric_points(), opt_mesh_lc_from_points(), opt_mesh_lc_integration_precision(), opt_mesh_lc_max(), opt_mesh_lc_min(), opt_mesh_light(), opt_mesh_light_lines(), opt_mesh_light_two_side(), opt_mesh_line_labels(), opt_mesh_line_width(), opt_mesh_lines(), opt_mesh_max_iter_delaunay_3d(), opt_mesh_max_num_threads_1d(), opt_mesh_max_num_threads_2d(), opt_mesh_max_num_threads_3d(), opt_mesh_max_retries(), opt_mesh_med_file_minor_version(), opt_mesh_med_import_groups_of_nodes(), opt_mesh_med_single_model(), opt_mesh_mesh_only_empty(), opt_mesh_mesh_only_visible(), opt_mesh_min_circle_nodes(), opt_mesh_min_curve_nodes(), opt_mesh_min_line_nodes(), opt_mesh_msh_file_version(), opt_mesh_nb_smoothing(), opt_mesh_newton_convergence_test_xyz(), opt_mesh_node_labels(), opt_mesh_node_size(), opt_mesh_node_type(), opt_mesh_nodes(), opt_mesh_normals(), opt_mesh_num_sub_edges(), opt_mesh_old_initial_delaunay_2d(), opt_mesh_optimize(), opt_mesh_optimize_netgen(), opt_mesh_optimize_threshold(), opt_mesh_order(), opt_mesh_partition_convert_msh2(), opt_mesh_partition_create_ghost_cells(), opt_mesh_partition_create_physicals(), opt_mesh_partition_create_topology(), opt_mesh_partition_hex_weight(), opt_mesh_partition_line_weight(), opt_mesh_partition_metis_algorithm(), opt_mesh_partition_metis_edge_matching(), opt_mesh_partition_metis_max_load_imbalance(), opt_mesh_partition_metis_min_conn(), opt_mesh_partition_metis_objective(), opt_mesh_partition_metis_refinement_algorithm(), opt_mesh_partition_num(), opt_mesh_partition_old_style_msh2(), opt_mesh_partition_pri_weight(), opt_mesh_partition_pyr_weight(), opt_mesh_partition_qua_weight(), opt_mesh_partition_save_topology_file(), opt_mesh_partition_split_mesh_files(), opt_mesh_partition_tet_weight(), opt_mesh_partition_tri_weight(), opt_mesh_partition_trih_weight(), opt_mesh_preserve_numbering_msh2(), opt_mesh_prisms(), opt_mesh_pyramids(), opt_mesh_quadqs_remeshing_boldness(), opt_mesh_quadqs_scaling_on_triangulation(), opt_mesh_quadqs_sizemap_method(), opt_mesh_quadqs_topo_optim_methods(), opt_mesh_quadrangles(), opt_mesh_quality_inf(), opt_mesh_quality_sup(), opt_mesh_quality_type(), opt_mesh_radius_inf(), opt_mesh_radius_sup(), opt_mesh_rand_factor(), opt_mesh_rand_factor3d(), opt_mesh_random_seed(), opt_mesh_read_groups_of_elements(), opt_mesh_recombine3d_all(), opt_mesh_recombine3d_conformity(), opt_mesh_recombine3d_level(), opt_mesh_recombine_all(), opt_mesh_recombine_minimum_quality(), opt_mesh_recombine_node_repositioning(), opt_mesh_recombine_optimize_topology(), opt_mesh_refine_steps(), opt_mesh_renumber(), opt_mesh_reparam_max_triangles(), opt_mesh_save_all(), opt_mesh_save_element_tag_type(), opt_mesh_save_groups_of_elements(), opt_mesh_save_groups_of_nodes(), opt_mesh_save_parametric(), opt_mesh_save_topology(), opt_mesh_save_without_orphans(), opt_mesh_scaling_factor(), opt_mesh_second_order_incomplete(), opt_mesh_second_order_linear(), opt_mesh_smooth_cross_field(), opt_mesh_smooth_normals(), opt_mesh_smooth_ratio(), opt_mesh_stl_angular_deflection(), opt_mesh_stl_linear_deflection(), opt_mesh_stl_linear_deflection_relative(), opt_mesh_stl_one_solid_per_surface(), opt_mesh_stl_remove_duplicate_triangles(), opt_mesh_surface_edges(), opt_mesh_surface_faces(), opt_mesh_surface_labels(), opt_mesh_switch_elem_tags(), opt_mesh_tangents(), opt_mesh_tetrahedra(), opt_mesh_tolerance_edge_length(), opt_mesh_tolerance_initial_delaunay(), opt_mesh_tolerance_reference_element(), opt_mesh_transfinite_tri(), opt_mesh_triangles(), opt_mesh_trihedra(), opt_mesh_unv_strict_format(), opt_mesh_volume_edges(), opt_mesh_volume_faces(), opt_mesh_volume_labels(), opt_mesh_voronoi(), opt_mesh_zone_definition(), opt_post_anim_cycle(), opt_post_anim_delay(), opt_post_anim_step(), opt_post_binary(), opt_post_combine_copy_options(), opt_post_combine_remove_orig(), opt_post_double_clicked_graph_point_command(), opt_post_double_clicked_graph_point_x(), opt_post_double_clicked_graph_point_y(), opt_post_double_clicked_view(), opt_post_file_format(), opt_post_force_element_data(), opt_post_force_node_data(), opt_post_horizontal_scales(), opt_post_link(), opt_post_plugins(), opt_post_save_interpolation_matrices(), opt_post_save_mesh(), opt_post_smooth(), opt_print_background(), opt_print_composite_windows(), opt_print_delete_tmp_files(), opt_print_eps_best_root(), opt_print_eps_compress(), opt_print_eps_line_width_factor(), opt_print_eps_occlusion_culling(), opt_print_eps_point_size_factor(), opt_print_eps_ps3shading(), opt_print_eps_quality(), opt_print_file_format(), opt_print_geo_labels(), opt_print_geo_only_physicals(), opt_print_gif_dither(), opt_print_gif_interlace(), opt_print_gif_sort(), opt_print_gif_transparent(), opt_print_height(), opt_print_jpeg_quality(), opt_print_jpeg_smoothing(), opt_print_parameter(), opt_print_parameter_command(), opt_print_parameter_first(), opt_print_parameter_last(), opt_print_parameter_steps(), opt_print_pgf_export_axis(), opt_print_pgf_horiz_bar(), opt_print_pgf_two_dim(), opt_print_pos_disto(), opt_print_pos_element(), opt_print_pos_elementary(), opt_print_pos_eta(), opt_print_pos_gamma(), opt_print_pos_SICN(), opt_print_pos_SIGE(), opt_print_tex_as_equation(), opt_print_tex_force_fontsize(), opt_print_tex_width_in_mm(), opt_print_text(), opt_print_width(), opt_print_x3d_colorize(), opt_print_x3d_compatibility(), opt_print_x3d_edges(), opt_print_x3d_precision(), opt_print_x3d_remove_inner_borders(), opt_print_x3d_surfaces(), opt_print_x3d_transparency(), opt_print_x3d_vertices(), opt_print_x3d_volumes(), opt_solver_auto_archive_output_files(), opt_solver_auto_check(), opt_solver_auto_load_database(), opt_solver_auto_merge_file(), opt_solver_auto_mesh(), opt_solver_auto_save_database(), opt_solver_auto_show_last_step(), opt_solver_auto_show_views(), opt_solver_executable(), opt_solver_extension(), opt_solver_listen(), opt_solver_name(), opt_solver_octave_interpreter(), opt_solver_plugins(), opt_solver_python_interpreter(), opt_solver_remote_login(), opt_solver_show_invisible_parameters(), opt_solver_socket_name(), opt_solver_timeout(), OptimizeMesh(), optimizeMesh(), GModel::optimizeMesh(), ParseString(), PolyMesh2GFace(), PrintColorOptions(), PrintColorOptionsDoc(), Msg::PrintErrorCounter(), PrintMesh2dStatistics(), Msg::PrintTimers(), Msg::ProgressMeter(), quadMeshRemoveHalfOfOneDMesh::quadMeshRemoveHalfOfOneDMesh(), QuadqsContextUpdater::QuadqsContextUpdater(), readMSH4Parametrizations(), GModel::readSTL(), GModel::readUNV(), drawContext::recenterForRotationCenterChange(), GOrientedTransfiniteFace::recombined(), recombineIntoQuads(), RecombineMesh(), GModel::recombineMesh(), RefineMesh(), GModel::refineMesh(), GEdge::refineProjection(), PluginManager::registerDefaultPlugins(), GModel::removeDuplicateMeshElements(), GModel::removeDuplicateMeshVertices(), GModel::renumberMeshElements(), GModel::renumberMeshVertices(), gmshEdge::reparamOnFace(), ReplaceAllDuplicates(), ReplaceAllDuplicatesNew(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicatePointsNew(), ReplaceDuplicateSurfaces(), RotateShapes(), GMSH_SimplePartitionPlugin::run(), sameDir(), scriptAddBox(), scriptAddCircle(), scriptAddCircleArc(), scriptAddCommand(), scriptAddCone(), scriptAddCurve(), scriptAddCurveLoop(), scriptAddCylinder(), scriptAddDisk(), scriptAddEllipse(), scriptAddEllipseArc(), scriptAddField(), scriptAddFieldOption(), scriptAddParameter(), scriptAddPipe(), scriptAddPoint(), scriptAddRectangle(), scriptAddRemovePhysicalGroup(), scriptAddSphere(), scriptAddSurface(), scriptAddSurfaceLoop(), scriptAddTorus(), scriptAddVolume(), scriptAddWedge(), scriptBoolean(), scriptCoherence(), scriptDeleteEntities(), scriptDeleteField(), scriptDilate(), scriptEmbed(), scriptExtrude(), scriptFillet(), scriptMirror(), scriptProtude(), scriptRecombineSurface(), scriptRotate(), scriptSetBackgroundField(), scriptSetCompound(), scriptSetFactory(), scriptSetMeshSize(), scriptSetTransfiniteLine(), scriptSetTransfiniteSurface(), scriptSetTransfiniteVolume(), scriptSetVisibility(), scriptSetVisibilityAll(), scriptSplitCurve(), scriptTranslate(), drawContext::select(), SetBoundingBox(), SetDefaultColorOptions(), GMSH_Plugin::setDrawFunction(), setLcs(), GFace::setMeshMaster(), GEdge::setMeshMaster(), setMeshSizeFromCurvePoints(), SetOrderN(), GModel::setOrderN(), QuadqsContextUpdater::setQuadqsOptions(), PViewDataList::smooth(), GModel::snapVertices(), splitElementsInBoundaryLayerIfNeeded(), StartupMessage(), Msg::StatusBar(), SubdivideExtrudedMesh(), SymmetryShapes(), GEO_Internals::synchronize(), SystemCallExe(), tb_project_to_sphere(), TooManyElements(), trackball(), transferSeamGEdgesVerticesToGFace(), TranslateShapes(), Camera::update(), backgroundMesh::updateSizes(), GEntity::useColor(), Msg::Warning(), PView::write(), writeElementMSH(), writeElementsMSH(), GModel::writeMESH(), PViewDataList::writeMSH(), MElement::writeMSH2(), writeMSH4Entities(), writeMSH4Nodes(), writeMSH4PeriodicNodes(), writeMSHPeriodicNodes(), GModel::writeOCCBREP(), GModel::writeOCCSTEP(), GModel::writeUNV(), PView::writeX3D(), writeX3dFaces(), and GFace::XYZtoUV().
packColor()
unsigned int CTX::packColor (int R, int G, int B, int A)
Definition at line 128 of file Context.cpp.
Referenced by ColorOption(), ColorTable_Recompute(), GEntity::GEntity(), GetColorForString(), and PrintColorOptions().
unpackAlpha()
int CTX::unpackAlpha (unsigned int X)
Definition at line 160 of file Context.cpp.
Referenced by VertexArray::add(), assembleColmapStr(), ColorTable_IsAlpha(), ColorTable_Print(), drawGraphAxes(), and GEntity::useColor().
unpackBlue()
int CTX::unpackBlue (unsigned int X)
Definition at line 152 of file Context.cpp.
Referenced by VertexArray::add(), assembleColmapStr(), ColorTable_Print(), GEntity::getInfoString(), drawContext::initRenderModel(), GEntity::useColor(), and writeX3dFaces().
unpackGreen()
int CTX::unpackGreen (unsigned int X)
Definition at line 144 of file Context.cpp.
Referenced by VertexArray::add(), assembleColmapStr(), ColorTable_Print(), GEntity::getInfoString(), drawContext::initRenderModel(), GEntity::useColor(), and writeX3dFaces().
unpackRed()
int CTX::unpackRed (unsigned int X)
Definition at line 136 of file Context.cpp.
Referenced by VertexArray::add(), assembleColmapStr(), ColorTable_Print(), GEntity::getInfoString(), drawContext::initRenderModel(), GEntity::useColor(), and writeX3dFaces().
Member Data Documentation
_instance
CTX * CTX::_instance = nullptr static private
Definition at line 129 of file Context.h.
Referenced by instance().
abortOnError
int CTX::abortOnError
Definition at line 153 of file Context.h.
Referenced by opt_general_abort_on_error(), and QuadqsContextUpdater::setQuadqsOptions().
alpha
int CTX::alpha
Definition at line 254 of file Context.h.
Referenced by opt_general_alpha_blending().
ambientLight
unsigned int CTX::ambientLight[6]
Definition at line 359 of file Context.h.
Referenced by drawContext::initRenderModel(), and opt_general_color_ambient_light().
animCycle
int CTX::animCycle
Definition at line 317 of file Context.h.
Referenced by CreateOutputFile(), and opt_post_anim_cycle().
animDelay
double CTX::animDelay
Definition at line 321 of file Context.h.
Referenced by CreateOutputFile(), and opt_post_anim_delay().
animStep
int CTX::animStep
Definition at line 317 of file Context.h.
Referenced by ChangePrintParameter(), CreateOutputFile(), and opt_post_anim_step().
antialiasing
int CTX::antialiasing
Definition at line 236 of file Context.h.
Referenced by opt_general_antialiasing(), and opt_general_double_buffer().
arrowRelHeadRadius
double CTX::arrowRelHeadRadius
Definition at line 288 of file Context.h.
Referenced by drawSimpleVector(), and opt_general_arrow_head_radius().
arrowRelStemLength
double CTX::arrowRelStemLength
Definition at line 288 of file Context.h.
Referenced by drawSimpleVector(), and opt_general_arrow_stem_length().
arrowRelStemRadius
double CTX::arrowRelStemRadius
Definition at line 288 of file Context.h.
Referenced by drawContext::drawPlaneInBoundingBox(), drawSimpleVector(), and opt_general_arrow_stem_radius().
autoArchiveOutputFiles
int CTX::autoArchiveOutputFiles
Definition at line 334 of file Context.h.
Referenced by opt_solver_auto_archive_output_files().
autoCheck
int CTX::autoCheck
Definition at line 335 of file Context.h.
Referenced by opt_solver_auto_check().
autoLoadDatabase
int CTX::autoLoadDatabase
Definition at line 333 of file Context.h.
Referenced by opt_solver_auto_load_database().
autoMergeFile
int CTX::autoMergeFile
Definition at line 334 of file Context.h.
Referenced by opt_solver_auto_merge_file().
autoMesh
int CTX::autoMesh
Definition at line 334 of file Context.h.
Referenced by opt_solver_auto_mesh().
autoSaveDatabase
int CTX::autoSaveDatabase
Definition at line 333 of file Context.h.
Referenced by opt_solver_auto_save_database().
autoShowLastStep
int CTX::autoShowLastStep
Definition at line 335 of file Context.h.
Referenced by GmshMergePostProcessingFile(), and opt_solver_auto_show_last_step().
autoShowViews
int CTX::autoShowViews
Definition at line 335 of file Context.h.
Referenced by GmshMergePostProcessingFile(), and opt_solver_auto_show_views().
axes [1/2]
int CTX::axes
Definition at line 248 of file Context.h.
Referenced by drawContext::drawAxes(), opt_general_axes(), and opt_general_color_axes().
axes [2/2]
unsigned int CTX::axes
Definition at line 358 of file Context.h.
axesAutoPosition
int CTX::axesAutoPosition
Definition at line 248 of file Context.h.
Referenced by opt_general_axes_auto_position().
axesForceValue
int CTX::axesForceValue
Definition at line 248 of file Context.h.
Referenced by opt_general_axes_force_value().
axesFormat
std::string CTX::axesFormat[3]
Definition at line 250 of file Context.h.
Referenced by opt_general_axes_format0(), opt_general_axes_format1(), and opt_general_axes_format2().
axesLabel
std::string CTX::axesLabel[3]
Definition at line 250 of file Context.h.
Referenced by assemble2d(), assemble3d(), opt_general_axes_label0(), opt_general_axes_label1(), and opt_general_axes_label2().
axesMikado
int CTX::axesMikado
Definition at line 248 of file Context.h.
Referenced by opt_general_axes_mikado().
axesPosition
double CTX::axesPosition[6]
Definition at line 249 of file Context.h.
Referenced by opt_general_axes_xmax(), opt_general_axes_xmin(), opt_general_axes_ymax(), opt_general_axes_ymin(), opt_general_axes_zmax(), and opt_general_axes_zmin().
axesTics
double CTX::axesTics[3]
Definition at line 249 of file Context.h.
Referenced by opt_general_axes_tics0(), opt_general_axes_tics1(), and opt_general_axes_tics2().
axesValue
double CTX::axesValue[6]
Definition at line 249 of file Context.h.
Referenced by opt_general_axes_value_xmax(), opt_general_axes_value_xmin(), opt_general_axes_value_ymax(), opt_general_axes_value_ymin(), opt_general_axes_value_zmax(), and opt_general_axes_value_zmin().
background
int CTX::background
Definition at line 347 of file Context.h.
Referenced by CreateOutputFile(), drawContext::initProjection(), and opt_print_background().
batch
int CTX::batch
Definition at line 203 of file Context.h.
Referenced by GetGeometryOption(), GetMeshOption(), GetOtherOption(), GetSolverOption(), GmshBatch(), and init().
batchAfterMesh
int CTX::batchAfterMesh
Definition at line 205 of file Context.h.
Referenced by GetMeshOption(), and init().
batchSomeValue
double CTX::batchSomeValue
Definition at line 207 of file Context.h.
Referenced by GetMeshOption(), and init().
bg
unsigned int CTX::bg
Definition at line 358 of file Context.h.
Referenced by drawContext::drawBackgroundGradient(), drawContext::drawVector(), drawContext::initProjection(), and opt_general_color_background().
bgGrad
unsigned int CTX::bgGrad
Definition at line 358 of file Context.h.
Referenced by drawContext::drawBackgroundGradient(), drawContext::initProjection(), and opt_general_color_background_gradient().
bgGradient
int CTX::bgGradient
Definition at line 258 of file Context.h.
Referenced by opt_general_background_gradient().
bgImage3d
int CTX::bgImage3d
Definition at line 262 of file Context.h.
Referenced by drawContext::drawBackgroundImage(), and opt_general_background_image_3d().
bgImageFileName
std::string CTX::bgImageFileName
Definition at line 260 of file Context.h.
Referenced by drawContext::drawBackgroundImage(), and opt_general_background_image_filename().
bgImagePage
int CTX::bgImagePage
Definition at line 262 of file Context.h.
Referenced by opt_general_background_image_page().
bgImagePosition
double CTX::bgImagePosition[2]
Definition at line 261 of file Context.h.
Referenced by drawContext::drawBackgroundImage(), opt_general_background_image_position0(), and opt_general_background_image_position1().
bgImageSize
double CTX::bgImageSize[2]
Definition at line 261 of file Context.h.
Referenced by drawContext::drawBackgroundImage(), opt_general_background_image_size0(), and opt_general_background_image_size1().
bgmFileName
std::string CTX::bgmFileName
Definition at line 141 of file Context.h.
Referenced by GetMeshOption(), GmshBatch(), GmshFLTK(), and init().
bigEndian
int CTX::bigEndian
Definition at line 373 of file Context.h.
Referenced by CreateOutputFile(), init(), packColor(), unpackAlpha(), unpackBlue(), unpackGreen(), and unpackRed().
binary
int CTX::binary
Definition at line 316 of file Context.h.
Referenced by CreateOutputFile(), opt_post_binary(), and PView::write().
camera
int CTX::camera
Definition at line 236 of file Context.h.
Referenced by opt_general_camera_mode().
camera_aperture
double CTX::camera_aperture
Definition at line 238 of file Context.h.
Referenced by Camera::affiche(), Camera::init(), opt_general_camera_aperture(), and Camera::update().
carousel
unsigned int CTX::carousel[20]
Definition at line 368 of file Context.h.
cg
double CTX::cg[3]
Definition at line 231 of file Context.h.
Referenced by AddToTemporaryBoundingBox(), FinishUpBoundingBox(), init(), drawContext::initProjection(), Camera::lookAtCg(), and drawContext::recenterForRotationCenterChange().
clipFactor
double CTX::clipFactor
Definition at line 217 of file Context.h.
Referenced by drawContext::initProjection(), and opt_general_clip_factor().
clipOnlyDrawIntersectingVolume
int CTX::clipOnlyDrawIntersectingVolume
Definition at line 278 of file Context.h.
Referenced by isElementVisible(), and opt_general_clip_only_draw_intersecting_volume().
clipOnlyVolume
int CTX::clipOnlyVolume
Definition at line 278 of file Context.h.
Referenced by isElementVisible(), and opt_general_clip_only_volume().
clipPlane
double CTX::clipPlane[6][4]
Definition at line 277 of file Context.h.
Referenced by evalClipPlane(), drawPViewBoundingBox::operator()(), opt_general_clip0a(), opt_general_clip0b(), opt_general_clip0c(), opt_general_clip0d(), opt_general_clip1a(), opt_general_clip1b(), opt_general_clip1c(), opt_general_clip1d(), opt_general_clip2a(), opt_general_clip2b(), opt_general_clip2c(), opt_general_clip2d(), opt_general_clip3a(), opt_general_clip3b(), opt_general_clip3c(), opt_general_clip3d(), opt_general_clip4a(), opt_general_clip4b(), opt_general_clip4c(), opt_general_clip4d(), opt_general_clip5a(), opt_general_clip5b(), opt_general_clip5c(), and opt_general_clip5d().
clipPosition
int CTX::clipPosition[2]
Definition at line 187 of file Context.h.
Referenced by opt_general_clip_position0(), and opt_general_clip_position1().
clipWholeElements
int CTX::clipWholeElements
Definition at line 278 of file Context.h.
Referenced by opt_general_clip_whole_elements().
color
struct { ... } CTX::color
Referenced by GFace::fillVertexArray(), getColorByElement(), getColorByEntity(), init(), drawContext::initRenderModel(), drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), drawGRegion::operator()(), drawMeshGFace::operator()(), drawMeshGRegion::operator()(), opt_general_color_ambient_light(), opt_general_color_axes(), opt_general_color_background(), opt_general_color_background_gradient(), opt_general_color_diffuse_light(), opt_general_color_foreground(), opt_general_color_small_axes(), opt_general_color_specular_light(), opt_general_color_text(), opt_geometry_color_curves(), opt_geometry_color_highlight0(), opt_geometry_color_highlight1(), opt_geometry_color_highlight2(), opt_geometry_color_normals(), opt_geometry_color_points(), opt_geometry_color_projection(), opt_geometry_color_selection(), opt_geometry_color_surfaces(), opt_geometry_color_tangents(), opt_geometry_color_volumes(), opt_mesh_color_(), opt_mesh_color_hexahedra(), opt_mesh_color_lines(), opt_mesh_color_nodes(), opt_mesh_color_nodes_sup(), opt_mesh_color_normals(), opt_mesh_color_prisms(), opt_mesh_color_pyramid(), opt_mesh_color_quadrangles(), opt_mesh_color_tangents(), opt_mesh_color_tetrahedra(), opt_mesh_color_triangles(), and opt_mesh_color_trihedron().
colorScheme
int CTX::colorScheme
Definition at line 283 of file Context.h.
Referenced by opt_general_color_scheme().
combineCopyOptions
int CTX::combineCopyOptions
Definition at line 318 of file Context.h.
Referenced by GmshFLTK(), and opt_post_combine_copy_options().
combineRemoveOrig
int CTX::combineRemoveOrig
Definition at line 318 of file Context.h.
Referenced by GmshFLTK(), and opt_post_combine_remove_orig().
combineTime
int CTX::combineTime
Definition at line 318 of file Context.h.
Referenced by GetPostProcessingOption(), and GmshFLTK().
compositeWindows
int CTX::compositeWindows
Definition at line 347 of file Context.h.
Referenced by opt_print_composite_windows().
confirmOverwrite
int CTX::confirmOverwrite
Definition at line 159 of file Context.h.
Referenced by opt_general_confirm_overwrite().
createAppendMeshStatReport
int CTX::createAppendMeshStatReport
Definition at line 151 of file Context.h.
Referenced by GetMeshOption(), and init().
ctxPosition
int CTX::ctxPosition[2]
Definition at line 189 of file Context.h.
Referenced by opt_general_context_position0(), and opt_general_context_position1().
curve
unsigned int CTX::curve
Definition at line 361 of file Context.h.
db
int CTX::db
Definition at line 236 of file Context.h.
Referenced by opt_general_antialiasing(), and opt_general_double_buffer().
debugSurface
int CTX::debugSurface
Definition at line 138 of file Context.h.
Referenced by GetMeshOption(), init(), meshGenerator(), and meshGeneratorPeriodic().
defaultFileName
std::string CTX::defaultFileName
Definition at line 141 of file Context.h.
Referenced by opt_general_default_filename().
deleteTmpFiles
int CTX::deleteTmpFiles
Definition at line 347 of file Context.h.
Referenced by opt_print_delete_tmp_files().
deltaFontSize
int CTX::deltaFontSize
Definition at line 264 of file Context.h.
Referenced by GetOtherOption(), and init().
detachedMenu
int CTX::detachedMenu
Definition at line 186 of file Context.h.
Referenced by opt_general_detached_menu().
detachedProcess
int CTX::detachedProcess
Definition at line 171 of file Context.h.
Referenced by init(), and opt_general_detached_process().
diffuseLight
unsigned int CTX::diffuseLight[6]
Definition at line 359 of file Context.h.
Referenced by drawContext::initRenderModel(), and opt_general_color_diffuse_light().
display
std::string CTX::display
Definition at line 161 of file Context.h.
Referenced by opt_general_display().
displayBorderFactor
double CTX::displayBorderFactor
Definition at line 219 of file Context.h.
Referenced by drawContext::initProjection(), and opt_general_display_border_factor().
doubleClickedGraphPointCommand
std::string CTX::doubleClickedGraphPointCommand
Definition at line 322 of file Context.h.
Referenced by opt_post_double_clicked_graph_point_command().
doubleClickedGraphPointX
double CTX::doubleClickedGraphPointX
Definition at line 323 of file Context.h.
Referenced by opt_post_double_clicked_graph_point_x().
doubleClickedGraphPointY
double CTX::doubleClickedGraphPointY
Definition at line 323 of file Context.h.
Referenced by opt_post_double_clicked_graph_point_y().
doubleClickedView
int CTX::doubleClickedView
Definition at line 324 of file Context.h.
Referenced by opt_post_double_clicked_view().
draw
int CTX::draw
Definition at line 316 of file Context.h.
Referenced by drawContext::draw2d(), drawContext::drawAxes(), drawContext::drawGeom(), drawContext::drawMesh(), drawContext::drawPost(), and GMSH_Plugin::setDrawFunction().
drawBBox
int CTX::drawBBox
Definition at line 242 of file Context.h.
Referenced by drawContext::drawPost(), opt_general_draw_bounding_box(), and GMSH_Plugin::setDrawFunction().
drawRotationCenter
int CTX::drawRotationCenter
Definition at line 242 of file Context.h.
Referenced by init().
editor
std::string CTX::editor
Definition at line 175 of file Context.h.
Referenced by opt_general_editor().
epsBestRoot
int CTX::epsBestRoot
Definition at line 340 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_eps_best_root().
epsCompress
int CTX::epsCompress
Definition at line 339 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_eps_compress().
epsLineWidthFactor
double CTX::epsLineWidthFactor
Definition at line 341 of file Context.h.
Referenced by drawContext::drawAxes(), drawGraphAxes(), drawGraphCurves(), drawContext::drawMesh(), drawContext::drawSmallAxes(), drawGEdge::operator()(), drawGFace::operator()(), drawPView::operator()(), drawPViewBoundingBox::operator()(), and opt_print_eps_line_width_factor().
epsOcclusionCulling
int CTX::epsOcclusionCulling
Definition at line 340 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_eps_occlusion_culling().
epsPointSizeFactor
double CTX::epsPointSizeFactor
Definition at line 341 of file Context.h.
Referenced by drawArrays(), drawGraphAxes(), drawGraphCurves(), drawContext::drawMesh(), drawGVertex::operator()(), drawPView::operator()(), and opt_print_eps_point_size_factor().
epsPS3Shading
int CTX::epsPS3Shading
Definition at line 339 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_eps_ps3shading().
epsQuality
int CTX::epsQuality
Definition at line 339 of file Context.h.
Referenced by CreateOutputFile(), drawContext::drawString(), and opt_print_eps_quality().
errorFileName
std::string CTX::errorFileName
Definition at line 142 of file Context.h.
Referenced by opt_general_error_filename().
executable
std::string CTX::executable[NUM_SOLVERS]
Definition at line 332 of file Context.h.
Referenced by opt_solver_executable().
exeFileName
std::string CTX::exeFileName
Definition at line 145 of file Context.h.
Referenced by Msg::Initialize(), and opt_general_executable_filename().
expertMode
int CTX::expertMode
Definition at line 298 of file Context.h.
Referenced by opt_general_expert_mode().
extension
std::string CTX::extension[NUM_SOLVERS]
Definition at line 331 of file Context.h.
Referenced by opt_solver_extension().
extraPosition
int CTX::extraPosition[2]
Definition at line 191 of file Context.h.
Referenced by opt_general_extra_position0(), and opt_general_extra_position1().
extraSize
int CTX::extraSize[2]
Definition at line 191 of file Context.h.
Referenced by opt_general_extra_size0(), and opt_general_extra_size1().
eye_sep_ratio
double CTX::eye_sep_ratio
Definition at line 238 of file Context.h.
Referenced by Camera::affiche(), Camera::init(), opt_general_eye_sep_ratio(), and Camera::update().
fastRedraw
int CTX::fastRedraw
Definition at line 244 of file Context.h.
Referenced by opt_general_fast_redraw().
fg
unsigned int CTX::fg
Definition at line 358 of file Context.h.
Referenced by GMSH_ProbePlugin::draw(), GMSH_CutSpherePlugin::draw(), GMSH_CutPlanePlugin::draw(), GMSH_AnnotatePlugin::draw(), GMSH_ParticlesPlugin::draw(), GMSH_StreamLinesPlugin::draw(), GMSH_CutParametricPlugin::draw(), GMSH_CutGridPlugin::draw(), GMSH_CutBoxPlugin::draw(), drawContext::drawAxes(), drawBarycentricDual(), drawVoronoiDual(), getColorByElement(), getColorByEntity(), drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), drawGRegion::operator()(), drawPViewBoundingBox::operator()(), and opt_general_color_foreground().
fieldPosition
int CTX::fieldPosition[2]
Definition at line 190 of file Context.h.
Referenced by opt_general_field_position0(), and opt_general_field_position1().
fieldSize
int CTX::fieldSize[2]
Definition at line 190 of file Context.h.
Referenced by opt_general_field_size0(), and opt_general_field_size1().
fileChooserPosition
int CTX::fileChooserPosition[2]
Definition at line 191 of file Context.h.
Referenced by opt_general_file_chooser_position0(), and opt_general_file_chooser_position1().
fileFormat
int CTX::fileFormat
Definition at line 319 of file Context.h.
Referenced by CreateOutputFile(), drawContext::drawString(), GmshBatch(), opt_post_file_format(), and opt_print_file_format().
fileread
bool CTX::fileread
Definition at line 237 of file Context.h.
Referenced by init(), and MergeFile().
files
std::vector<std::string> CTX::files
Definition at line 140 of file Context.h.
Referenced by GetOptions(), GetOtherOption(), GmshBatch(), and GmshFLTK().
focallength_ratio
double CTX::focallength_ratio
Definition at line 238 of file Context.h.
Referenced by Camera::affiche(), Camera::init(), opt_general_focallength_ratio(), and Camera::update().
fontSize
int CTX::fontSize
Definition at line 264 of file Context.h.
Referenced by opt_general_fontsize().
forcedBBox
int CTX::forcedBBox
Definition at line 292 of file Context.h.
Referenced by init().
forceElementData
int CTX::forceElementData
Definition at line 319 of file Context.h.
Referenced by opt_post_force_element_data(), and PView::write().
forceNodeData
int CTX::forceNodeData
Definition at line 319 of file Context.h.
Referenced by opt_post_force_node_data(), and PView::write().
gamepad
GamePad* CTX::gamepad
Definition at line 223 of file Context.h.
Referenced by init(), opt_general_gamepad(), and ~CTX().
geoLabels
int CTX::geoLabels
Definition at line 342 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_geo_labels().
geom [1/2]
contextGeometryOptions CTX::geom
Definition at line 311 of file Context.h.
Referenced by _opt_geometry_offset(), _opt_geometry_transform(), GFace::buildRepresentationCross(), ComparePosition(), drawEntityLabel(), drawContext::drawGeom(), GMSH_DiscretizationErrorPlugin::execute(), ExtrudePoint(), ExtrudeSurface(), GFace::fillVertexArray(), FinishUpBoundingBox(), getColorByElement(), getColorByEntity(), getElement(), GetGeometryOption(), init(), GeomMeshMatcher::match(), GeomMeshMatcher::matchVertices(), MergeFile(), meshGEdgeProcessing(), gmshEdge::minimumDrawSegments(), needPolygonOffset(), drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), drawGRegion::operator()(), opt_geometry_auto_coherence(), opt_geometry_clip(), opt_geometry_color_curves(), opt_geometry_color_highlight0(), opt_geometry_color_highlight1(), opt_geometry_color_highlight2(), opt_geometry_color_normals(), opt_geometry_color_points(), opt_geometry_color_projection(), opt_geometry_color_selection(), opt_geometry_color_surfaces(), opt_geometry_color_tangents(), opt_geometry_color_volumes(), opt_geometry_copy_meshing_method(), opt_geometry_curve_labels(), opt_geometry_curve_sel_width(), opt_geometry_curve_type(), opt_geometry_curve_width(), opt_geometry_curves(), opt_geometry_double_clicked_curve_command(), opt_geometry_double_clicked_entity_tag(), opt_geometry_double_clicked_point_command(), opt_geometry_double_clicked_surface_command(), opt_geometry_double_clicked_volume_command(), opt_geometry_exact_extrusion(), opt_geometry_extrude_return_lateral(), opt_geometry_extrude_spline_points(), opt_geometry_highlight_orphans(), opt_geometry_label_type(), opt_geometry_light(), opt_geometry_light_two_side(), opt_geometry_match_geom_and_mesh(), opt_geometry_match_mesh_scale_factor(), opt_geometry_match_mesh_tolerance(), opt_geometry_normals(), opt_geometry_num_sub_edges(), opt_geometry_occ_auto_embed(), opt_geometry_occ_auto_fix(), opt_geometry_occ_boolean_preserve_numbering(), opt_geometry_occ_bounds_use_stl(), opt_geometry_occ_disable_stl(), opt_geometry_occ_export_only_visible(), opt_geometry_occ_fix_degenerated(), opt_geometry_occ_fix_small_edges(), opt_geometry_occ_fix_small_faces(), opt_geometry_occ_import_labels(), opt_geometry_occ_make_solids(), opt_geometry_occ_parallel(), opt_geometry_occ_safe_unbind(), opt_geometry_occ_scaling(), opt_geometry_occ_sew_faces(), opt_geometry_occ_target_unit(), opt_geometry_occ_thrusections_degree(), opt_geometry_occ_union_unify(), opt_geometry_occ_use_generic_closest_point(), opt_geometry_old_circle(), opt_geometry_old_newreg(), opt_geometry_old_ruled_surface(), opt_geometry_oriented_physicals(), opt_geometry_pipe_default_trihedron(), opt_geometry_point_labels(), opt_geometry_point_sel_size(), opt_geometry_point_size(), opt_geometry_point_type(), opt_geometry_points(), opt_geometry_reparam_on_face_robust(), opt_geometry_scaling_factor(), opt_geometry_snap0(), opt_geometry_snap1(), opt_geometry_snap2(), opt_geometry_snap_points(), opt_geometry_surface_labels(), opt_geometry_surface_type(), opt_geometry_surfaces(), opt_geometry_tangents(), opt_geometry_tolerance(), opt_geometry_tolerance_boolean(), opt_geometry_transform(), opt_geometry_volume_labels(), opt_geometry_volumes(), ReplaceAllDuplicatesNew(), ReplaceDuplicatePointsNew(), sameDir(), GFace::setMeshMaster(), GEdge::setMeshMaster(), GModel::snapVertices(), GEO_Internals::synchronize(), transferSeamGEdgesVerticesToGFace(), and PViewDataList::writeMSH().
geom [2/2]
struct { ... } CTX::geom
geoOnlyPhysicals
int CTX::geoOnlyPhysicals
Definition at line 342 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_geo_only_physicals().
gifDither
int CTX::gifDither
Definition at line 345 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_gif_dither().
gifInterlace
int CTX::gifInterlace
Definition at line 345 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_gif_interlace().
gifSort
int CTX::gifSort
Definition at line 345 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_gif_sort().
gifTransparent
int CTX::gifTransparent
Definition at line 345 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_gif_transparent().
glFont
std::string CTX::glFont
Definition at line 266 of file Context.h.
Referenced by opt_general_graphics_font().
glFontEngine
std::string CTX::glFontEngine
Definition at line 266 of file Context.h.
Referenced by opt_general_graphics_font_engine().
glFontEnum
int CTX::glFontEnum
Definition at line 267 of file Context.h.
Referenced by init(), and opt_general_graphics_font().
glFontEnumTitle
int CTX::glFontEnumTitle
Definition at line 267 of file Context.h.
Referenced by opt_general_graphics_font_title().
glFontSize
int CTX::glFontSize
Definition at line 267 of file Context.h.
Referenced by drawContext::drawBox(), drawContext::drawSmallAxes(), drawContext::drawString(), drawVertexLabel(), drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), drawGRegion::operator()(), and opt_general_graphics_fontsize().
glFontSizeTitle
int CTX::glFontSizeTitle
Definition at line 267 of file Context.h.
Referenced by opt_general_graphics_fontsize_title().
glFontTitle
std::string CTX::glFontTitle
Definition at line 266 of file Context.h.
Referenced by opt_general_graphics_font_title().
glPosition
int CTX::glPosition[2]
Definition at line 185 of file Context.h.
Referenced by opt_general_graphics_position0(), and opt_general_graphics_position1().
glSize
int CTX::glSize[2]
Definition at line 185 of file Context.h.
Referenced by drawContext::drawContext(), opt_general_graphics_size0(), and opt_general_graphics_size1().
guiColorScheme
int CTX::guiColorScheme
Definition at line 165 of file Context.h.
Referenced by opt_general_gui_color_scheme().
guiRefreshRate
int CTX::guiRefreshRate
Definition at line 165 of file Context.h.
Referenced by opt_general_gui_refresh_rate().
guiTheme
std::string CTX::guiTheme
Definition at line 163 of file Context.h.
Referenced by opt_general_gui_theme().
height
int CTX::height
Definition at line 348 of file Context.h.
Referenced by opt_print_height().
hexahedron
unsigned int CTX::hexahedron
Definition at line 367 of file Context.h.
hideUnselected
int CTX::hideUnselected
Definition at line 306 of file Context.h.
Referenced by init().
highlight
unsigned int CTX::highlight[3]
Definition at line 362 of file Context.h.
highResolutionGraphics
int CTX::highResolutionGraphics
Definition at line 199 of file Context.h.
Referenced by opt_general_high_resolution_graphics().
highResolutionPointSizeFactor
double CTX::highResolutionPointSizeFactor
Definition at line 272 of file Context.h.
homeDir
std::string CTX::homeDir
Definition at line 147 of file Context.h.
Referenced by ClearProject(), CreateOutputFile(), GetOptions(), init(), initPView::operator()(), ParseString(), and scriptAddCommand().
horizontalScales
int CTX::horizontalScales
Definition at line 316 of file Context.h.
Referenced by drawContext::drawScales(), opt_post_horizontal_scales(), and PView::writeX3D().
hotPosition
int CTX::hotPosition[2]
Definition at line 187 of file Context.h.
Referenced by opt_general_hot_position0(), and opt_general_hot_position1().
initialContext
int CTX::initialContext
Definition at line 209 of file Context.h.
Referenced by opt_general_initial_context().
inputScrolling
int CTX::inputScrolling
Definition at line 183 of file Context.h.
Referenced by opt_general_input_scrolling().
jpegQuality
int CTX::jpegQuality
Definition at line 342 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_jpeg_quality().
jpegSmoothing
int CTX::jpegSmoothing
Definition at line 342 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_jpeg_smoothing().
launchSolverAtStartup
int CTX::launchSolverAtStartup
Definition at line 155 of file Context.h.
Referenced by GetSolverOption(), init(), and MergeFile().
lc
double CTX::lc
Definition at line 234 of file Context.h.
Referenced by VertexArray::add(), AddToTemporaryBoundingBox(), BGM_MeshMetric(), BGM_MeshSize(), GMSH_ProbePlugin::callback(), ComparePosition(), GFace::computeMeanPlane(), CurvatureField::CurvatureField(), GMSH_SkinPlugin::execute(), eyeChanged(), FinishUpBoundingBox(), GradientField::GradientField(), init(), drawContext::initProjection(), LaplacianField::LaplacianField(), LC_MVertex_PNTS(), MaxEigenHessianField::MaxEigenHessianField(), MeanField::MeanField(), MeshExtrudedSurface(), meshGEdgeProcessing(), meshGRegionExtruded::operator()(), opt_general_lc(), GEdge::refineProjection(), ReplaceAllDuplicatesNew(), ReplaceDuplicatePointsNew(), sameDir(), GFace::setMeshMaster(), GEdge::setMeshMaster(), PViewDataList::smooth(), and SubdivideExtrudedMesh().
light
int CTX::light[6]
Definition at line 274 of file Context.h.
Referenced by drawContext::drawAxes(), drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), drawGRegion::operator()(), opt_general_light0(), opt_general_light1(), opt_general_light2(), opt_general_light3(), opt_general_light4(), opt_general_light5(), opt_geometry_light(), and opt_mesh_light().
lightPosition
double CTX::lightPosition[6][4]
Definition at line 275 of file Context.h.
Referenced by drawContext::initRenderModel(), opt_general_light00(), opt_general_light01(), opt_general_light02(), opt_general_light03(), opt_general_light10(), opt_general_light11(), opt_general_light12(), opt_general_light13(), opt_general_light20(), opt_general_light21(), opt_general_light22(), opt_general_light23(), opt_general_light30(), opt_general_light31(), opt_general_light32(), opt_general_light33(), opt_general_light40(), opt_general_light41(), opt_general_light42(), opt_general_light43(), opt_general_light50(), opt_general_light51(), opt_general_light52(), and opt_general_light53().
line
unsigned int CTX::line
Definition at line 366 of file Context.h.
lineWidth
double CTX::lineWidth
Definition at line 271 of file Context.h.
Referenced by drawContext::drawMesh(), drawContext::drawPlaneInBoundingBox(), opt_general_line_width(), and opt_mesh_line_width().
link
int CTX::link
Definition at line 316 of file Context.h.
Referenced by opt_post_link().
listen
int CTX::listen
Definition at line 328 of file Context.h.
Referenced by GmshFLTK(), and opt_solver_listen().
lock
int CTX::lock
Definition at line 252 of file Context.h.
Referenced by GenerateMesh(), init(), and OpenProject().
manipPosition
int CTX::manipPosition[2]
Definition at line 188 of file Context.h.
Referenced by opt_general_manip_position0(), and opt_general_manip_position1().
max
double CTX::max[3]
Definition at line 229 of file Context.h.
Referenced by drawContext::drawAxes(), FinishUpBoundingBox(), getMinMaxOfAxis(), init(), drawContext::initProjection(), Camera::lookAtCg(), and SetBoundingBox().
menuPosition
int CTX::menuPosition[2]
Definition at line 185 of file Context.h.
Referenced by opt_general_menu_position0(), and opt_general_menu_position1().
menuSize
int CTX::menuSize[2]
Definition at line 185 of file Context.h.
Referenced by opt_general_menu_size0(), and opt_general_menu_size1().
mesh [1/2]
contextMeshOptions CTX::mesh
Definition at line 313 of file Context.h.
Referenced by OctreePost::_create(), initMeshGFace::_estimateNumLines(), GModel::adaptMesh(), addElementsInArrays(), addSmoothNormals(), backgroundMesh::backgroundMesh(), BGM_MeshMetric(), BGM_MeshSize(), buildBackgroundMesh(), GModel::buildCutGModel(), classifyFaces(), meshMetric::computeMetric(), meshMetric::computeMetricEigenDir(), CreateOutputFile(), GModel::createTopologyFromMesh(), delaunayTriangulation(), GModel::destroy(), drawContext::draw3d(), drawArrays(), drawContext::drawAxes(), drawElementLabels(), drawContext::drawMesh(), drawNormals(), drawTangents(), drawVertexLabel(), drawVerticesPerElement(), drawVerticesPerEntity(), GMSH_CrackPlugin::execute(), GMSH_MeshSubEntitiesPlugin::execute(), GMSH_ShowNeighborElementsPlugin::execute(), Extend2dMeshIn3dVolumes(), BoundaryLayerField::fanSize(), filterPoints(), MElementOctree::find(), MElementOctree::findAll(), quadMeshRemoveHalfOfOneDMesh::finish(), GenerateMesh(), getColorByElement(), getColorByEntity(), MLine3::getEdgeRep(), MLineN::getEdgeRep(), MPyramidN::getEdgeRep(), GFace::getMeshingAlgo(), GetMeshOption(), GFace::getMeshSizeFromBoundary(), GModel::getMeshStatus(), MLine3::getNumEdgesRep(), MTriangle6::getNumEdgesRep(), MLineN::getNumEdgesRep(), MQuadrangle8::getNumEdgesRep(), MTetrahedron10::getNumEdgesRep(), MPrism15::getNumEdgesRep(), MHexahedron20::getNumEdgesRep(), MPyramidN::getNumEdgesRep(), MTriangleN::getNumEdgesRep(), MQuadrangle9::getNumEdgesRep(), MPrism18::getNumEdgesRep(), MTetrahedronN::getNumEdgesRep(), MQuadrangleN::getNumEdgesRep(), MHexahedron27::getNumEdgesRep(), MPrismN::getNumEdgesRep(), MHexahedronN::getNumEdgesRep(), element::getTolerance(), MElement::getTolerance(), GModel::GModel(), init(), insertAPoint(), insertVerticesInRegion(), isElementVisible(), LC_MVertex_CURV(), LC_MVertex_CURV_ANISO(), max_edge_curvature_metric(), MergeFile(), GEdge::mesh(), GFace::mesh(), GModel::mesh(), Mesh1D(), Mesh2D(), Mesh3D(), MeshDelaunayVolume(), meshGEdgeProcessing(), meshGenerator(), meshGeneratorPeriodic(), MeshTransfiniteSurface(), metric_based_on_surface_curvature(), gmshEdge::minimumMeshSegments(), minmax(), needPolygonOffset(), meshGEdge::operator()(), meshGFace::operator()(), meshMetric::operator()(), F_Transfinite::operator()(), BoundaryLayerField::operator()(), initMeshGEdge::operator()(), initMeshGFace::operator()(), drawMeshGVertex::operator()(), initMeshGRegion::operator()(), drawMeshGEdge::operator()(), drawMeshGFace::operator()(), drawMeshGRegion::operator()(), ExtendField::operator()(), opt_mesh_algo2d(), opt_mesh_algo3d(), opt_mesh_algo_recombine(), opt_mesh_algo_subdivide(), opt_mesh_algo_switch_on_failure(), opt_mesh_allow_swap_edge_angle(), opt_mesh_angle_smooth_normals(), opt_mesh_angle_tolerance_facet_overlap(), opt_mesh_aniso_max(), opt_mesh_bdf_field_format(), opt_mesh_binary(), opt_mesh_boundary_layer_fan_elements(), opt_mesh_cgns_construct_topology(), opt_mesh_cgns_export_cpex0045(), opt_mesh_cgns_export_structured(), opt_mesh_cgns_import_ignore_bc(), opt_mesh_cgns_import_ignore_solution(), opt_mesh_cgns_import_order(), opt_mesh_clip(), opt_mesh_color_(), opt_mesh_color_carousel(), opt_mesh_color_hexahedra(), opt_mesh_color_lines(), opt_mesh_color_nodes(), opt_mesh_color_nodes_sup(), opt_mesh_color_normals(), opt_mesh_color_prisms(), opt_mesh_color_pyramid(), opt_mesh_color_quadrangles(), opt_mesh_color_tangents(), opt_mesh_color_tetrahedra(), opt_mesh_color_triangles(), opt_mesh_color_trihedron(), opt_mesh_compound_classify(), opt_mesh_compound_lc_factor(), opt_mesh_create_topology_msh2(), opt_mesh_cross_field_closest_point(), opt_mesh_draw_skin_only(), opt_mesh_dual(), opt_mesh_explode(), opt_mesh_file_format(), opt_mesh_first_element_tag(), opt_mesh_first_node_tag(), opt_mesh_flexible_transfinite(), opt_mesh_hexahedra(), opt_mesh_ho_curve_outer_BL(), opt_mesh_ho_dist_cad(), opt_mesh_ho_fast_new_algo(), opt_mesh_ho_fix_bnd_nodes(), opt_mesh_ho_iter_max(), opt_mesh_ho_max_angle(), opt_mesh_ho_max_in_angle(), opt_mesh_ho_max_rho(), opt_mesh_ho_nlayers(), opt_mesh_ho_optimize(), opt_mesh_ho_pass_max(), opt_mesh_ho_periodic(), opt_mesh_ho_poisson(), opt_mesh_ho_prim_surf_mesh(), opt_mesh_ho_save_periodic(), opt_mesh_ho_threshold_max(), opt_mesh_ho_threshold_min(), opt_mesh_ignore_parametrization(), opt_mesh_ignore_periodicity(), opt_mesh_label_sampling(), opt_mesh_label_type(), opt_mesh_lc_extend_from_boundary(), opt_mesh_lc_factor(), opt_mesh_lc_from_curvature(), opt_mesh_lc_from_curvature_iso(), opt_mesh_lc_from_parametric_points(), opt_mesh_lc_from_points(), opt_mesh_lc_integration_precision(), opt_mesh_lc_max(), opt_mesh_lc_min(), opt_mesh_light(), opt_mesh_light_lines(), opt_mesh_light_two_side(), opt_mesh_line_labels(), opt_mesh_line_width(), opt_mesh_lines(), opt_mesh_max_iter_delaunay_3d(), opt_mesh_max_num_threads_1d(), opt_mesh_max_num_threads_2d(), opt_mesh_max_num_threads_3d(), opt_mesh_max_retries(), opt_mesh_med_file_minor_version(), opt_mesh_med_import_groups_of_nodes(), opt_mesh_med_single_model(), opt_mesh_mesh_only_empty(), opt_mesh_mesh_only_visible(), opt_mesh_min_circle_nodes(), opt_mesh_min_curve_nodes(), opt_mesh_min_line_nodes(), opt_mesh_msh_file_version(), opt_mesh_nb_smoothing(), opt_mesh_newton_convergence_test_xyz(), opt_mesh_node_labels(), opt_mesh_node_size(), opt_mesh_node_type(), opt_mesh_nodes(), opt_mesh_normals(), opt_mesh_num_sub_edges(), opt_mesh_old_initial_delaunay_2d(), opt_mesh_optimize(), opt_mesh_optimize_netgen(), opt_mesh_optimize_threshold(), opt_mesh_order(), opt_mesh_partition_convert_msh2(), opt_mesh_partition_create_ghost_cells(), opt_mesh_partition_create_physicals(), opt_mesh_partition_create_topology(), opt_mesh_partition_hex_weight(), opt_mesh_partition_line_weight(), opt_mesh_partition_metis_algorithm(), opt_mesh_partition_metis_edge_matching(), opt_mesh_partition_metis_max_load_imbalance(), opt_mesh_partition_metis_min_conn(), opt_mesh_partition_metis_objective(), opt_mesh_partition_metis_refinement_algorithm(), opt_mesh_partition_num(), opt_mesh_partition_old_style_msh2(), opt_mesh_partition_pri_weight(), opt_mesh_partition_pyr_weight(), opt_mesh_partition_qua_weight(), opt_mesh_partition_save_topology_file(), opt_mesh_partition_split_mesh_files(), opt_mesh_partition_tet_weight(), opt_mesh_partition_tri_weight(), opt_mesh_partition_trih_weight(), opt_mesh_preserve_numbering_msh2(), opt_mesh_prisms(), opt_mesh_pyramids(), opt_mesh_quadqs_remeshing_boldness(), opt_mesh_quadqs_scaling_on_triangulation(), opt_mesh_quadqs_sizemap_method(), opt_mesh_quadqs_topo_optim_methods(), opt_mesh_quadrangles(), opt_mesh_quality_inf(), opt_mesh_quality_sup(), opt_mesh_quality_type(), opt_mesh_radius_inf(), opt_mesh_radius_sup(), opt_mesh_rand_factor(), opt_mesh_rand_factor3d(), opt_mesh_random_seed(), opt_mesh_read_groups_of_elements(), opt_mesh_recombine3d_all(), opt_mesh_recombine3d_conformity(), opt_mesh_recombine3d_level(), opt_mesh_recombine_all(), opt_mesh_recombine_minimum_quality(), opt_mesh_recombine_node_repositioning(), opt_mesh_recombine_optimize_topology(), opt_mesh_refine_steps(), opt_mesh_renumber(), opt_mesh_reparam_max_triangles(), opt_mesh_save_all(), opt_mesh_save_element_tag_type(), opt_mesh_save_groups_of_elements(), opt_mesh_save_groups_of_nodes(), opt_mesh_save_parametric(), opt_mesh_save_topology(), opt_mesh_save_without_orphans(), opt_mesh_scaling_factor(), opt_mesh_second_order_incomplete(), opt_mesh_second_order_linear(), opt_mesh_smooth_cross_field(), opt_mesh_smooth_normals(), opt_mesh_smooth_ratio(), opt_mesh_stl_angular_deflection(), opt_mesh_stl_linear_deflection(), opt_mesh_stl_linear_deflection_relative(), opt_mesh_stl_one_solid_per_surface(), opt_mesh_stl_remove_duplicate_triangles(), opt_mesh_surface_edges(), opt_mesh_surface_faces(), opt_mesh_surface_labels(), opt_mesh_switch_elem_tags(), opt_mesh_tangents(), opt_mesh_tetrahedra(), opt_mesh_tolerance_edge_length(), opt_mesh_tolerance_initial_delaunay(), opt_mesh_tolerance_reference_element(), opt_mesh_transfinite_tri(), opt_mesh_triangles(), opt_mesh_trihedra(), opt_mesh_unv_strict_format(), opt_mesh_volume_edges(), opt_mesh_volume_faces(), opt_mesh_volume_labels(), opt_mesh_voronoi(), opt_mesh_zone_definition(), OptimizeMesh(), optimizeMesh(), GModel::optimizeMesh(), PolyMesh2GFace(), quadMeshRemoveHalfOfOneDMesh::quadMeshRemoveHalfOfOneDMesh(), GModel::readUNV(), GOrientedTransfiniteFace::recombined(), RecombineMesh(), GModel::recombineMesh(), RefineMesh(), GModel::refineMesh(), GModel::renumberMeshElements(), GModel::renumberMeshVertices(), GMSH_SimplePartitionPlugin::run(), scriptAddCommand(), GMSH_Plugin::setDrawFunction(), GModel::setOrderN(), QuadqsContextUpdater::setQuadqsOptions(), TooManyElements(), backgroundMesh::updateSizes(), PView::write(), GModel::writeMESH(), MElement::writeMSH2(), writeMSH4Nodes(), and GFace::XYZtoUV().
mesh [2/2]
struct { ... } CTX::mesh
meshStatReportFileName
std::string CTX::meshStatReportFileName
Definition at line 143 of file Context.h.
Referenced by GetMeshOption().
meshTimer
double CTX::meshTimer[3]
Definition at line 290 of file Context.h.
Referenced by GetStatistics(), init(), Mesh1D(), Mesh2D(), and Mesh3D().
min
double CTX::min[3]
Definition at line 229 of file Context.h.
Referenced by drawContext::drawAxes(), FinishUpBoundingBox(), getMinMaxOfAxis(), init(), drawContext::initProjection(), Camera::lookAtCg(), and SetBoundingBox().
mouseHoverMeshes
int CTX::mouseHoverMeshes
Definition at line 294 of file Context.h.
Referenced by opt_general_mouse_hover_meshes().
mouseInvertZoom
int CTX::mouseInvertZoom
Definition at line 296 of file Context.h.
Referenced by opt_general_mouse_invert_zoom().
mouseSelection
int CTX::mouseSelection
Definition at line 294 of file Context.h.
Referenced by opt_general_mouse_selection().
msgFontSize
int CTX::msgFontSize
Definition at line 269 of file Context.h.
Referenced by opt_general_message_fontsize().
msgSize
int CTX::msgSize
Definition at line 185 of file Context.h.
Referenced by opt_general_message_size().
name
std::string CTX::name[NUM_SOLVERS]
Definition at line 331 of file Context.h.
Referenced by opt_solver_name().
nativeFileChooser
int CTX::nativeFileChooser
Definition at line 195 of file Context.h.
Referenced by opt_general_native_file_chooser().
node
unsigned int CTX::node
Definition at line 366 of file Context.h.
nodeSup
unsigned int CTX::nodeSup
Definition at line 366 of file Context.h.
nonModalWindows
int CTX::nonModalWindows
Definition at line 215 of file Context.h.
Referenced by opt_general_non_modal_windows().
noPopup
int CTX::noPopup
Definition at line 213 of file Context.h.
Referenced by GmshMainBatch(), and opt_general_nopopup().
normals
unsigned int CTX::normals
Definition at line 363 of file Context.h.
Referenced by drawGFace::operator()(), drawMeshGFace::operator()(), opt_geometry_normals(), and opt_mesh_normals().
numThreads
int CTX::numThreads
Definition at line 169 of file Context.h.
Referenced by GModel::_writePartitionedMSH4(), addElementsInArrays(), Mesh1D(), Mesh2D(), opt_general_num_threads(), and StartupMessage().
numTiles
int CTX::numTiles
Definition at line 173 of file Context.h.
Referenced by GetOtherOption(), and init().
numWindows
int CTX::numWindows
Definition at line 173 of file Context.h.
Referenced by GetOtherOption(), and init().
octaveInterpreter
std::string CTX::octaveInterpreter
Definition at line 330 of file Context.h.
Referenced by opt_solver_octave_interpreter(), and SystemCallExe().
optionsFileName
std::string CTX::optionsFileName
Definition at line 142 of file Context.h.
Referenced by opt_general_options_filename().
optionsSave
int CTX::optionsSave
Definition at line 157 of file Context.h.
Referenced by opt_general_options_save().
optPosition
int CTX::optPosition[2]
Definition at line 187 of file Context.h.
Referenced by opt_general_option_position0(), and opt_general_option_position1().
ortho
int CTX::ortho
Definition at line 240 of file Context.h.
Referenced by opt_general_orthographic().
outputFileName
std::string CTX::outputFileName
Definition at line 141 of file Context.h.
Referenced by GetOtherOption(), GmshBatch(), and init().
parameter
double CTX::parameter
Definition at line 349 of file Context.h.
Referenced by opt_print_parameter().
parameterCommand
std::string CTX::parameterCommand
Definition at line 351 of file Context.h.
Referenced by ChangePrintParameter(), and opt_print_parameter_command().
parameterFirst
double CTX::parameterFirst
Definition at line 349 of file Context.h.
Referenced by ChangePrintParameter(), and opt_print_parameter_first().
parameterLast
double CTX::parameterLast
Definition at line 349 of file Context.h.
Referenced by ChangePrintParameter(), and opt_print_parameter_last().
parameterSteps
double CTX::parameterSteps
Definition at line 349 of file Context.h.
Referenced by ChangePrintParameter(), CreateOutputFile(), and opt_print_parameter_steps().
pgfExportAxis
int CTX::pgfExportAxis
Definition at line 350 of file Context.h.
Referenced by opt_print_pgf_export_axis().
pgfHorizBar
int CTX::pgfHorizBar
Definition at line 350 of file Context.h.
Referenced by opt_print_pgf_horiz_bar().
pgfTwoDim
int CTX::pgfTwoDim
Definition at line 350 of file Context.h.
Referenced by opt_print_pgf_two_dim().
pickElements
int CTX::pickElements
Definition at line 294 of file Context.h.
Referenced by addElementsInArrays(), drawArrays(), init(), opt_mesh_color_carousel(), and drawContext::select().
pluginPosition
int CTX::pluginPosition[2]
Definition at line 190 of file Context.h.
Referenced by opt_general_plugin_position0(), and opt_general_plugin_position1().
plugins
int CTX::plugins
Definition at line 319 of file Context.h.
Referenced by opt_post_plugins(), opt_solver_plugins(), and PluginManager::registerDefaultPlugins().
pluginSize
int CTX::pluginSize[2]
Definition at line 190 of file Context.h.
Referenced by opt_general_plugin_size0(), and opt_general_plugin_size1().
point
unsigned int CTX::point
Definition at line 361 of file Context.h.
pointSize
double CTX::pointSize
Definition at line 271 of file Context.h.
Referenced by addGraphPoint(), GMSH_CutParametricPlugin::draw(), drawGraphAxes(), drawGraphCurves(), drawGVertex::operator()(), opt_general_point_size(), and opt_geometry_point_size().
polygonOffset
int CTX::polygonOffset
Definition at line 280 of file Context.h.
Referenced by drawContext::draw3d(), drawArrays(), and init().
polygonOffsetAlways
int CTX::polygonOffsetAlways
Definition at line 280 of file Context.h.
Referenced by drawContext::draw3d(), and opt_general_polygon_offset_always().
polygonOffsetFactor
double CTX::polygonOffsetFactor
Definition at line 281 of file Context.h.
Referenced by opt_general_polygon_offset_factor().
polygonOffsetUnits
double CTX::polygonOffsetUnits
Definition at line 281 of file Context.h.
Referenced by opt_general_polygon_offset_units().
posDisto
int CTX::posDisto
Definition at line 346 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_pos_disto().
posElement
int CTX::posElement
Definition at line 346 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_pos_element().
posElementary
int CTX::posElementary
Definition at line 346 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_pos_elementary().
posEta
int CTX::posEta
Definition at line 346 of file Context.h.
Referenced by opt_print_pos_eta().
posGamma
int CTX::posGamma
Definition at line 346 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_pos_gamma().
posSICN
int CTX::posSICN
Definition at line 346 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_pos_SICN().
posSIGE
int CTX::posSIGE
Definition at line 346 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_pos_SIGE().
post
struct { ... } CTX::post
Referenced by ChangePrintParameter(), CreateOutputFile(), drawContext::drawPost(), GetPostProcessingOption(), GmshFLTK(), init(), opt_post_anim_cycle(), opt_post_anim_delay(), opt_post_anim_step(), opt_post_binary(), opt_post_combine_copy_options(), opt_post_combine_remove_orig(), opt_post_double_clicked_graph_point_command(), opt_post_double_clicked_graph_point_x(), opt_post_double_clicked_graph_point_y(), opt_post_double_clicked_view(), opt_post_file_format(), opt_post_force_element_data(), opt_post_force_node_data(), opt_post_horizontal_scales(), opt_post_link(), opt_post_plugins(), opt_post_save_interpolation_matrices(), opt_post_save_mesh(), opt_post_smooth(), GMSH_Plugin::setDrawFunction(), and PView::write().
print
struct { ... } CTX::print
Referenced by almostEqual(), ChangePrintParameter(), CreateOutputFile(), drawGraphCurves(), drawContext::drawMesh(), drawContext::drawString(), drawContext::initProjection(), drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), drawPView::operator()(), opt_print_background(), opt_print_composite_windows(), opt_print_delete_tmp_files(), opt_print_eps_best_root(), opt_print_eps_compress(), opt_print_eps_line_width_factor(), opt_print_eps_occlusion_culling(), opt_print_eps_point_size_factor(), opt_print_eps_ps3shading(), opt_print_eps_quality(), opt_print_file_format(), opt_print_geo_labels(), opt_print_geo_only_physicals(), opt_print_gif_dither(), opt_print_gif_interlace(), opt_print_gif_sort(), opt_print_gif_transparent(), opt_print_height(), opt_print_jpeg_quality(), opt_print_jpeg_smoothing(), opt_print_parameter(), opt_print_parameter_command(), opt_print_parameter_first(), opt_print_parameter_last(), opt_print_parameter_steps(), opt_print_pgf_export_axis(), opt_print_pgf_horiz_bar(), opt_print_pgf_two_dim(), opt_print_pos_disto(), opt_print_pos_element(), opt_print_pos_elementary(), opt_print_pos_eta(), opt_print_pos_gamma(), opt_print_pos_SICN(), opt_print_pos_SIGE(), opt_print_tex_as_equation(), opt_print_tex_force_fontsize(), opt_print_tex_width_in_mm(), opt_print_text(), opt_print_width(), opt_print_x3d_colorize(), opt_print_x3d_compatibility(), opt_print_x3d_edges(), opt_print_x3d_precision(), opt_print_x3d_remove_inner_borders(), opt_print_x3d_surfaces(), opt_print_x3d_transparency(), opt_print_x3d_vertices(), opt_print_x3d_volumes(), and PView::writeX3D().
printing
int CTX::printing
Definition at line 304 of file Context.h.
Referenced by CreateOutputFile(), init(), and drawContext::initProjection().
prism
unsigned int CTX::prism
Definition at line 367 of file Context.h.
projection
unsigned int CTX::projection
Definition at line 362 of file Context.h.
pyramid
unsigned int CTX::pyramid
Definition at line 367 of file Context.h.
pythonInterpreter
std::string CTX::pythonInterpreter
Definition at line 330 of file Context.h.
Referenced by opt_solver_python_interpreter(), and SystemCallExe().
quadrangle
unsigned int CTX::quadrangle
Definition at line 366 of file Context.h.
quadricSubdivisions
int CTX::quadricSubdivisions
Definition at line 285 of file Context.h.
Referenced by opt_general_quadric_subdivisions().
recentFiles
std::vector<std::string> CTX::recentFiles
Definition at line 149 of file Context.h.
Referenced by init(), OpenProject(), opt_general_recent_file0(), opt_general_recent_file1(), opt_general_recent_file2(), opt_general_recent_file3(), opt_general_recent_file4(), opt_general_recent_file5(), opt_general_recent_file6(), opt_general_recent_file7(), opt_general_recent_file8(), and opt_general_recent_file9().
remoteLogin
std::string CTX::remoteLogin[NUM_SOLVERS]
Definition at line 332 of file Context.h.
Referenced by opt_solver_remote_login().
rotationCenter
double CTX::rotationCenter[3]
Definition at line 225 of file Context.h.
Referenced by opt_general_rotation_center0(), opt_general_rotation_center1(), and opt_general_rotation_center2().
rotationCenterCg
int CTX::rotationCenterCg
Definition at line 227 of file Context.h.
Referenced by opt_general_rotation_center_cg().
saveInterpolationMatrices
int CTX::saveInterpolationMatrices
Definition at line 320 of file Context.h.
Referenced by opt_post_save_interpolation_matrices(), and PView::write().
saveMesh
int CTX::saveMesh
Definition at line 320 of file Context.h.
Referenced by opt_post_save_mesh(), and PView::write().
scriptLang
std::vector<std::string> CTX::scriptLang
Definition at line 179 of file Context.h.
Referenced by opt_general_scripting_languages().
selection
unsigned int CTX::selection
Definition at line 362 of file Context.h.
sessionFileName
std::string CTX::sessionFileName
Definition at line 142 of file Context.h.
Referenced by opt_general_session_filename().
sessionSave
int CTX::sessionSave
Definition at line 157 of file Context.h.
Referenced by opt_general_session_save().
shine
double CTX::shine
Definition at line 275 of file Context.h.
Referenced by drawContext::initRenderModel(), and opt_general_shine().
shineExponent
double CTX::shineExponent
Definition at line 275 of file Context.h.
Referenced by opt_general_shine_exponent().
showInvisibleParameters
int CTX::showInvisibleParameters
Definition at line 335 of file Context.h.
Referenced by opt_solver_show_invisible_parameters().
showMessagesOnStartup
int CTX::showMessagesOnStartup
Definition at line 211 of file Context.h.
Referenced by opt_general_show_messages_on_startup().
showModuleMenu
int CTX::showModuleMenu
Definition at line 197 of file Context.h.
Referenced by opt_general_show_module_menu().
showOptionsOnStartup
int CTX::showOptionsOnStartup
Definition at line 211 of file Context.h.
Referenced by opt_general_show_options_on_startup().
smallAxes [1/2]
int CTX::smallAxes
Definition at line 246 of file Context.h.
Referenced by drawContext::drawSmallAxes(), opt_general_color_small_axes(), and opt_general_small_axes().
smallAxes [2/2]
unsigned int CTX::smallAxes
Definition at line 358 of file Context.h.
smallAxesPos
int CTX::smallAxesPos[2]
Definition at line 246 of file Context.h.
Referenced by drawContext::drawSmallAxes(), opt_general_small_axes_position0(), and opt_general_small_axes_position1().
smallAxesSize
int CTX::smallAxesSize
Definition at line 246 of file Context.h.
Referenced by drawContext::drawSmallAxes(), and opt_general_small_axes_size().
smooth
int CTX::smooth
Definition at line 317 of file Context.h.
Referenced by PViewDataList::finalize(), and opt_post_smooth().
socketName
std::string CTX::socketName
Definition at line 330 of file Context.h.
Referenced by opt_solver_socket_name().
solver
struct { ... } CTX::solver
Referenced by GmshMergePostProcessingFile(), opt_solver_auto_archive_output_files(), opt_solver_auto_check(), opt_solver_auto_load_database(), opt_solver_auto_merge_file(), opt_solver_auto_mesh(), opt_solver_auto_save_database(), opt_solver_auto_show_last_step(), opt_solver_auto_show_views(), opt_solver_executable(), opt_solver_extension(), opt_solver_listen(), opt_solver_name(), opt_solver_octave_interpreter(), opt_solver_plugins(), opt_solver_python_interpreter(), opt_solver_remote_login(), opt_solver_show_invisible_parameters(), opt_solver_socket_name(), opt_solver_timeout(), and SystemCallExe().
specularLight
unsigned int CTX::specularLight[6]
Definition at line 359 of file Context.h.
Referenced by drawContext::initRenderModel(), and opt_general_color_specular_light().
statPosition
int CTX::statPosition[2]
Definition at line 189 of file Context.h.
Referenced by opt_general_statistics_position0(), and opt_general_statistics_position1().
stereo
int CTX::stereo
Definition at line 236 of file Context.h.
Referenced by drawContext::draw2d(), and opt_general_stereo_mode().
surface
unsigned int CTX::surface
Definition at line 361 of file Context.h.
systemMenuBar
int CTX::systemMenuBar
Definition at line 193 of file Context.h.
Referenced by opt_general_system_menu_bar().
tangents
unsigned int CTX::tangents
Definition at line 363 of file Context.h.
Referenced by drawGEdge::operator()(), drawMeshGEdge::operator()(), opt_geometry_tangents(), and opt_mesh_tangents().
terminal
int CTX::terminal
Definition at line 167 of file Context.h.
Referenced by _checkInit(), GetOptions(), GmshMainBatch(), GmshMainFLTK(), init(), opt_general_terminal(), and Msg::ProgressMeter().
tetrahedron
unsigned int CTX::tetrahedron
Definition at line 367 of file Context.h.
texAsEquation
int CTX::texAsEquation
Definition at line 343 of file Context.h.
Referenced by drawContext::drawString(), and opt_print_tex_as_equation().
texForceFontSize
int CTX::texForceFontSize
Definition at line 343 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_tex_force_fontsize().
text [1/2]
int CTX::text
Definition at line 343 of file Context.h.
Referenced by CreateOutputFile(), drawScaleValues(), drawContext::drawString(), opt_general_color_text(), and opt_print_text().
text [2/2]
unsigned int CTX::text
Definition at line 358 of file Context.h.
texWidthInMm
double CTX::texWidthInMm
Definition at line 344 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_tex_width_in_mm().
timeout
double CTX::timeout
Definition at line 329 of file Context.h.
Referenced by opt_solver_timeout().
tmpFileName
std::string CTX::tmpFileName
Definition at line 141 of file Context.h.
Referenced by initPView::operator()(), opt_general_tmp_filename(), ParseString(), and scriptAddCommand().
tmpQuaternion
double CTX::tmpQuaternion[4]
Definition at line 309 of file Context.h.
Referenced by drawContext::drawContext(), opt_general_quaternion0(), opt_general_quaternion1(), opt_general_quaternion2(), and opt_general_quaternion3().
tmpRotation
double CTX::tmpRotation[3]
Definition at line 309 of file Context.h.
Referenced by drawContext::drawContext(), opt_general_rotation0(), opt_general_rotation1(), and opt_general_rotation2().
tmpScale
double CTX::tmpScale[3]
Definition at line 309 of file Context.h.
Referenced by drawContext::drawContext(), opt_general_scale0(), opt_general_scale1(), and opt_general_scale2().
tmpTranslation
double CTX::tmpTranslation[3]
Definition at line 309 of file Context.h.
Referenced by drawContext::drawContext(), opt_general_translation0(), opt_general_translation1(), and opt_general_translation2().
tooltips
int CTX::tooltips
Definition at line 181 of file Context.h.
Referenced by opt_general_tooltips().
trackballHyperbolicSheet
int CTX::trackballHyperbolicSheet
Definition at line 221 of file Context.h.
Referenced by opt_general_trackball_hyperbolic_sheet().
triangle
unsigned int CTX::triangle
Definition at line 366 of file Context.h.
trihedron
unsigned int CTX::trihedron
Definition at line 367 of file Context.h.
useTrackball
int CTX::useTrackball
Definition at line 221 of file Context.h.
Referenced by opt_general_trackball().
vectorType
int CTX::vectorType
Definition at line 287 of file Context.h.
Referenced by opt_general_vector_type().
visPosition
int CTX::visPosition[2]
Definition at line 187 of file Context.h.
Referenced by opt_general_visibility_position0(), and opt_general_visibility_position1().
volume
unsigned int CTX::volume
Definition at line 361 of file Context.h.
watchFilePattern
std::string CTX::watchFilePattern
Definition at line 177 of file Context.h.
Referenced by opt_general_watch_file_pattern().
width
int CTX::width
Definition at line 348 of file Context.h.
Referenced by opt_print_width().
x3dColorize
int CTX::x3dColorize
Definition at line 354 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_x3d_colorize().
x3dCompatibility
int CTX::x3dCompatibility
Definition at line 352 of file Context.h.
Referenced by opt_print_x3d_compatibility(), and PView::writeX3D().
x3dEdges
int CTX::x3dEdges
Definition at line 354 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_x3d_edges().
x3dPrecision
double CTX::x3dPrecision
Definition at line 353 of file Context.h.
Referenced by almostEqual(), and opt_print_x3d_precision().
x3dRemoveInnerBorders
int CTX::x3dRemoveInnerBorders
Definition at line 352 of file Context.h.
Referenced by opt_print_x3d_remove_inner_borders(), and PView::writeX3D().
x3dSurfaces
int CTX::x3dSurfaces
Definition at line 354 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_x3d_surfaces().
x3dTransparency
double CTX::x3dTransparency
Definition at line 353 of file Context.h.
Referenced by opt_print_x3d_transparency(), and PView::writeX3D().
x3dVertices
int CTX::x3dVertices
Definition at line 354 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_x3d_vertices().
x3dVolumes
int CTX::x3dVolumes
Definition at line 354 of file Context.h.
Referenced by CreateOutputFile(), and opt_print_x3d_volumes().
zoomFactor
double CTX::zoomFactor
Definition at line 256 of file Context.h.
Referenced by opt_general_zoom_factor().
The documentation for this class was generated from the following files:
src/common/Context.h
src/common/Context.cpp