gmsh-TingyuanDoc: qmTriangle Class Reference
qmTriangle Class Reference
#include <qualityMeasures.h>
Static Public Member Functions
static double gamma (MTriangle *f)
static double gamma (BDS_Face *f)
static double gamma (const BDS_Point *p1, const BDS_Point *p2, const BDS_Point *p3)
static double gamma (const MVertex *v1, const MVertex *v2, const MVertex *v3)
static double gamma (const double *d1, const double *d2, const double *d3)
static double gamma (const double &x1, const double &y1, const double &z1, const double &x2, const double &y2, const double &z2, const double &x3, const double &y3, const double &z3)
static double eta (MTriangle *el)
static double angles (MTriangle *e)
static double minNCJ (const MTriangle *e)
static void NCJRange (const MTriangle *e, double &valMin, double &valMax)
static int numNCJVal ()
static void NCJ (const SPoint3 &p0, const SPoint3 &p1, const SPoint3 &p2, const SVector3 &normal, std::vector< double > &NCJ)
static void NCJAndGradients (const SPoint3 &p0, const SPoint3 &p1, const SPoint3 &p2, const SVector3 &normal, std::vector< double > &NCJ, std::vector< double > &dNCJ)
Detailed Description
Definition at line 25 of file qualityMeasures.h.
Member Function Documentation
angles()
double qmTriangle::angles (MTriangle * e) static
Definition at line 200 of file qualityMeasures.cpp.
Referenced by MTriangle::angleShapeMeasure().
eta()
double qmTriangle::eta (MTriangle * el) static
Definition at line 187 of file qualityMeasures.cpp.
Referenced by MTriangle::etaShapeMeasure().
gamma() [1/6]
double qmTriangle::gamma (BDS_Face * f) static
Definition at line 139 of file qualityMeasures.cpp.
gamma() [2/6]
double qmTriangle::gamma (const BDS_Point * p1, const BDS_Point * p2, const BDS_Point * p3) static
Definition at line 133 of file qualityMeasures.cpp.
gamma() [3/6]
double qmTriangle::gamma (const double & x1, const double & y1, const double & z1, const double & x2, const double & y2, const double & z2, const double & x3, const double & y3, const double & z3) static
Definition at line 160 of file qualityMeasures.cpp.
gamma() [4/6]
static double qmTriangle::gamma (const double * d1, const double * d2, const double * d3) static
gamma() [5/6]
double qmTriangle::gamma (const MVertex * v1, const MVertex * v2, const MVertex * v3) static
Definition at line 151 of file qualityMeasures.cpp.
gamma() [6/6]
double qmTriangle::gamma (MTriangle * f) static
Definition at line 146 of file qualityMeasures.cpp.
Referenced by BDS_Face_Validity(), computeElementShapes(), edgeSwapTest(), faceQuality(), gamma(), MTriangle::gammaShapeMeasure(), BDS_SwapEdgeTestQuality::operator()(), and BDS_SwapEdgeTestNormals::operator()().
minNCJ()
static double qmTriangle::minNCJ (const MTriangle * e) static
NCJ()
void qmTriangle::NCJ (const SPoint3 & p0, const SPoint3 & p1, const SPoint3 & p2, const SVector3 & normal, std::vector< double > & NCJ) static
Definition at line 290 of file qualityMeasures.cpp.
Referenced by NCJAndGradients(), and NCJRange().
NCJAndGradients()
void qmTriangle::NCJAndGradients (const SPoint3 & p0, const SPoint3 & p1, const SPoint3 & p2, const SVector3 & normal, std::vector< double > & NCJ, std::vector< double > & dNCJ) static
std::vector<double> dNCJLoc = (iV == 0) ? dNCJ0 : (iV == 1) ? dNCJ1 : dNCJ2; / std::cout << "DBGTT: -> dNCJ/dp" << ig << " (local) = (" << dNCJLoc[ind2] << ", " << dNCJLoc[ind2+1] << ", " << dNCJLoc[ind2+2] < ")\n";
Definition at line 310 of file qualityMeasures.cpp.
NCJRange()
void qmTriangle::NCJRange (const MTriangle * e, double & valMin, double & valMax) static
Definition at line 269 of file qualityMeasures.cpp.
numNCJVal()
static int qmTriangle::numNCJVal () inline static
Definition at line 40 of file qualityMeasures.h.
The documentation for this class was generated from the following files:
src/mesh/qualityMeasures.h
src/mesh/qualityMeasures.cpp