gmsh-TingyuanDoc: smooth_data Class Reference
smooth_data Class Reference
#include <SmoothData.h>
Public Types
typedef std::set< xyzv, lessthanxyzv >::iterator iter
Public Member Functions
iter begin ()
iter end ()
smooth_data ()
void add (double x, double y, double z, int n, double *vals)
bool get (double x, double y, double z, int n, double *vals) const
void add_scale (double x, double y, double z, double scale_val)
bool get_scale (double x, double y, double z, double *scale_val) const
void normalize ()
bool exportview (const std::string &filename) const
Private Attributes
std::set< xyzv, lessthanxyzv > c
Detailed Description
Definition at line 53 of file SmoothData.h.
Member Typedef Documentation
iter
typedef std::set<xyzv, lessthanxyzv>::iterator smooth_data::iter
Definition at line 58 of file SmoothData.h.
Constructor & Destructor Documentation
smooth_data()
smooth_data::smooth_data () inline
Definition at line 61 of file SmoothData.h.
Member Function Documentation
add()
void smooth_data::add (double x, double y, double z, int n, double * vals)
Definition at line 79 of file SmoothData.cpp.
Referenced by addExtrudeNormals(), and generateConnectivities().
add_scale()
void smooth_data::add_scale (double x, double y, double z, double scale_val)
Definition at line 96 of file SmoothData.cpp.
Referenced by addExtrudeNormals().
begin()
iter smooth_data::begin () inline
Definition at line 59 of file SmoothData.h.
end()
iter smooth_data::end () inline
Definition at line 60 of file SmoothData.h.
Referenced by addExtrudeNormals().
exportview()
bool smooth_data::exportview (const std::string & filename) const
Definition at line 138 of file SmoothData.cpp.
get()
bool smooth_data::get (double x, double y, double z, int n, double * vals) const
Definition at line 112 of file SmoothData.cpp.
Referenced by addExtrudeNormals(), ExtrudeParams::Extrude(), and smoothList().
get_scale()
bool smooth_data::get_scale (double x, double y, double z, double * scale_val) const
Definition at line 121 of file SmoothData.cpp.
Referenced by ExtrudeParams::Extrude().
normalize()
void smooth_data::normalize ()
Definition at line 129 of file SmoothData.cpp.
Referenced by addExtrudeNormals().
Member Data Documentation
c
std::set<xyzv, lessthanxyzv> smooth_data::c private
Definition at line 55 of file SmoothData.h.
Referenced by add(), add_scale(), begin(), end(), exportview(), get(), get_scale(), and normalize().
The documentation for this class was generated from the following files:
src/common/SmoothData.h
src/common/SmoothData.cpp