gmsh-TingyuanDoc: GMSH_PostPlugin Class Reference
GMSH_PostPlugin Class Reference abstract
#include <Plugin.h>
Inherits GMSH_Plugin.
Inherited by GMSH_AnalyseMeshQualityPlugin, GMSH_AnnotatePlugin, GMSH_BoundaryAnglesPlugin, GMSH_BubblesPlugin, GMSH_CrackPlugin, GMSH_CurlPlugin, GMSH_CurvedBndDistPlugin, GMSH_CutBoxPlugin, GMSH_CutGridPlugin, GMSH_CutParametricPlugin, GMSH_CVTRemeshPlugin, GMSH_DiscretizationErrorPlugin, GMSH_DistancePlugin, GMSH_DivergencePlugin, GMSH_EigenvaluesPlugin, GMSH_EigenvectorsPlugin, GMSH_ExtractEdgesPlugin, GMSH_ExtractElementsPlugin, GMSH_FieldFromAmplitudePhasePlugin, GMSH_GaussPointsPlugin, GMSH_GradientPlugin, GMSH_HarmonicToTimePlugin, GMSH_IntegratePlugin, GMSH_InvisiblePlugin, GMSH_Lambda2Plugin, GMSH_LevelsetPlugin, GMSH_LongituteLatitudePlugin, GMSH_MakeSimplexPlugin, GMSH_MathEvalPlugin, GMSH_MeshSizeFieldViewPlugin, GMSH_MeshSubEntitiesPlugin, GMSH_MeshVolumePlugin, GMSH_MinMaxPlugin, GMSH_ModifyComponentsPlugin, GMSH_ModulusPhasePlugin, GMSH_NearestNeighborPlugin, GMSH_NearToFarFieldPlugin, GMSH_NewViewPlugin, GMSH_ParticlesPlugin, GMSH_ProbePlugin, GMSH_RemovePlugin, GMSH_Scal2TensPlugin, GMSH_Scal2VecPlugin, GMSH_ShowNeighborElementsPlugin, GMSH_SkinPlugin, GMSH_SmoothPlugin, GMSH_SphericalRaisePlugin, GMSH_StreamLinesPlugin, GMSH_SummationPlugin, GMSH_TetrahedralizePlugin, GMSH_TransformPlugin, GMSH_TriangulatePlugin, GMSH_VoroMetalPlugin, and GMSH_WarpPlugin.
Public Member Functions
GMSH_PLUGIN_TYPE getType () const
virtual int run ()
virtual PView * execute (PView *)=0
virtual PView * executeRemote (PView *)
virtual PView * getView (int index, PView *view)
virtual PViewDataList * getDataList (PView *view, bool showError=true)
virtual PViewData * getPossiblyAdaptiveData (PView *view)
virtual void assignSpecificVisibility () const
virtual bool geometricalFilter (fullMatrix< double > *) const
Public Member Functions inherited from GMSH_Plugin
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual std::string getName () const =0
virtual std::string getShortHelp () const =0
virtual std::string getHelp () const =0
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
virtual int getNbOptions () const
virtual StringXNumber * getOption (int iopt)
virtual int getNbOptionsStr () const
virtual StringXString * getOptionStr (int iopt)
std::string serialize ()
Additional Inherited Members
Public Types inherited from GMSH_Plugin
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Static Public Member Functions inherited from GMSH_Plugin
static void setDrawFunction (void(*fct)(void *))
Public Attributes inherited from GMSH_Plugin
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes inherited from GMSH_Plugin
static void(* draw)(void *) = nullptr
Detailed Description
Definition at line 83 of file Plugin.h.
Member Function Documentation
assignSpecificVisibility()
virtual void GMSH_PostPlugin::assignSpecificVisibility () const inline virtual
Reimplemented in GMSH_LevelsetPlugin.
Definition at line 111 of file Plugin.h.
Referenced by adaptiveElements< T >::adapt().
execute()
virtual PView* GMSH_PostPlugin::execute (PView *) pure virtual
Implemented in GMSH_VoroMetalPlugin, GMSH_AnalyseMeshQualityPlugin, GMSH_CutParametricPlugin, GMSH_ShowNeighborElementsPlugin, GMSH_CutBoxPlugin, GMSH_CutGridPlugin, GMSH_NearToFarFieldPlugin, GMSH_BoundaryAnglesPlugin, GMSH_AnnotatePlugin, GMSH_LevelsetPlugin, GMSH_CutPlanePlugin, GMSH_CutSpherePlugin, GMSH_DistancePlugin, GMSH_ParticlesPlugin, GMSH_Scal2TensPlugin, GMSH_StreamLinesPlugin, GMSH_SummationPlugin, GMSH_BubblesPlugin, GMSH_FieldFromAmplitudePhasePlugin, GMSH_MathEvalPlugin, GMSH_ModifyComponentsPlugin, GMSH_NewViewPlugin, GMSH_Scal2VecPlugin, GMSH_DiscretizationErrorPlugin, GMSH_ProbePlugin, GMSH_CurlPlugin, GMSH_CVTRemeshPlugin, GMSH_DivergencePlugin, GMSH_EigenvaluesPlugin, GMSH_EigenvectorsPlugin, GMSH_ExtractEdgesPlugin, GMSH_ExtractElementsPlugin, GMSH_GradientPlugin, GMSH_HarmonicToTimePlugin, GMSH_InvisiblePlugin, GMSH_MakeSimplexPlugin, GMSH_MeshSizeFieldViewPlugin, GMSH_ModulusPhasePlugin, GMSH_NearestNeighborPlugin, GMSH_RemovePlugin, GMSH_TransformPlugin, GMSH_WarpPlugin, GMSH_CurvedBndDistPlugin, GMSH_IsosurfacePlugin, GMSH_Lambda2Plugin, GMSH_MeshVolumePlugin, GMSH_CrackPlugin, GMSH_GaussPointsPlugin, GMSH_IntegratePlugin, GMSH_LongituteLatitudePlugin, GMSH_MeshSubEntitiesPlugin, GMSH_MinMaxPlugin, GMSH_SkinPlugin, GMSH_SmoothPlugin, GMSH_SphericalRaisePlugin, GMSH_TetrahedralizePlugin, and GMSH_TriangulatePlugin.
Referenced by run().
executeRemote()
PView * GMSH_PostPlugin::executeRemote (PView * view) virtual
Definition at line 57 of file Plugin.cpp.
geometricalFilter()
virtual bool GMSH_PostPlugin::geometricalFilter (fullMatrix< double > *) const inline virtual
Reimplemented in GMSH_CutPlanePlugin.
Definition at line 112 of file Plugin.h.
getDataList()
PViewDataList * GMSH_PostPlugin::getDataList (PView * view, bool showError = true) virtual
Definition at line 107 of file Plugin.cpp.
Referenced by GMSH_GaussPointsPlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_Lambda2Plugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_CurvedBndDistPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_MakeSimplexPlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_RemovePlugin::execute(), GMSH_DiscretizationErrorPlugin::execute(), GMSH_ProbePlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_SummationPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_DistancePlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_AnnotatePlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GMSH_CutParametricPlugin::execute(), GMSH_CutGridPlugin::GenerateView(), and GMSH_CutBoxPlugin::GenerateView().
getPossiblyAdaptiveData()
PViewData * GMSH_PostPlugin::getPossiblyAdaptiveData (PView * view) virtual
Definition at line 94 of file Plugin.cpp.
Referenced by GMSH_IntegratePlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_SummationPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_CutParametricPlugin::execute(), GMSH_CutGridPlugin::GenerateView(), and GMSH_CutBoxPlugin::GenerateView().
getType()
GMSH_PLUGIN_TYPE GMSH_PostPlugin::getType () const inline virtual
Implements GMSH_Plugin.
Definition at line 85 of file Plugin.h.
getView()
PView * GMSH_PostPlugin::getView (int index, PView * view) virtual
Definition at line 81 of file Plugin.cpp.
Referenced by GMSH_IntegratePlugin::execute(), GMSH_LongituteLatitudePlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_SmoothPlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_Lambda2Plugin::execute(), GMSH_IsosurfacePlugin::execute(), GMSH_RemovePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_MakeSimplexPlugin::execute(), GMSH_MeshSizeFieldViewPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_ProbePlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_SummationPlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_CutSpherePlugin::execute(), GMSH_CutPlanePlugin::execute(), GMSH_AnnotatePlugin::execute(), GMSH_CutGridPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GMSH_CutBoxPlugin::execute(), and GMSH_CutParametricPlugin::execute().
run()
virtual int GMSH_PostPlugin::run () inline virtual
Implements GMSH_Plugin.
Definition at line 90 of file Plugin.h.
The documentation for this class was generated from the following files:
src/plugin/Plugin.h
src/plugin/Plugin.cpp