gmsh-TingyuanDoc: fullMatrix< scalar > Class Template Reference
fullMatrix< scalar > Class Template Reference
#include <MElement.h>
Public Member Functions
fullMatrix (scalar *original, int r, int c)
fullMatrix (fullMatrix< scalar > &original, int c_start, int c)
fullMatrix (int r, int c, bool init0=true)
fullMatrix (int r, int c, scalar *data)
fullMatrix (const fullMatrix< scalar > &other)
fullMatrix ()
~fullMatrix ()
int size1 () const
int size2 () const
scalar get (int r, int c) const
const scalar * getDataPtr () const
scalar * getDataPtr ()
void set (int r, int c, scalar v)
scalar norm () const
bool resize (int r, int c, bool resetValue=true)
void reshape (int nbRows, int nbColumns)
void setAsProxy (const fullMatrix< scalar > &original)
void setAsProxy (const fullMatrix< scalar > &original, int c_start, int c)
void setAsProxy (scalar *data, int r, int c)
fullMatrix< scalar > & operator= (const fullMatrix< scalar > &other)
void operator+= (const fullMatrix< scalar > &other)
scalar operator() (int i, int j) const
scalar & operator() (int i, int j)
void copy (const fullMatrix< scalar > &a, int i0, int ni, int j0, int nj, int desti0, int destj0)
void copy (const fullMatrix< scalar > &a)
void copyOneColumn (const fullVector< scalar > &x, const int ind) const
void setAll (const scalar &m)
void setAll (const fullMatrix< scalar > &m)
void scale (const scalar s)
void add (const double &a)
void add (const fullMatrix< scalar > &m)
void add (const fullMatrix< scalar > &m, const scalar &a)
void mult (const fullVector< scalar > &x, fullVector< scalar > &y) const
void multAddy (const fullVector< scalar > &x, fullVector< scalar > &y) const
void mult (const fullMatrix< scalar > &b, fullMatrix< scalar > &c) const
void multTByT (const fullMatrix< scalar > &a)
void multOnBlock (const fullMatrix< scalar > &b, const int ncol, const int fcol, const int alpha, const int beta, fullVector< scalar > &c) const
void multWithATranspose (const fullVector< scalar > &x, scalar alpha, scalar beta, fullVector< scalar > &y) const
fullMatrix< scalar > transpose () const
void transposeInPlace ()
void gemm (const fullMatrix< scalar > &a, const fullMatrix< scalar > &b, scalar alpha=1., scalar beta=1., bool transposeA=false, bool transposeB=false)
void axpy (const fullMatrix< scalar > &x, scalar alpha=1.)
bool luSolve (const fullVector< scalar > &rhs, fullVector< scalar > &result)
bool luFactor (fullVector< int > &ipiv)
bool luSubstitute (const fullVector< scalar > &rhs, fullVector< int > &ipiv, fullVector< scalar > &result)
bool invert (fullMatrix< scalar > &result) const
bool invertInPlace ()
scalar determinant () const
void swap (scalar *a, int inca, scalar *b, int incb, int n)
void eigSort (int n, scalar *wr, scalar *wi, scalar *VL, scalar *VR)
bool eig (fullVector< double > &eigenValReal, fullVector< double > &eigenValImag, fullMatrix< scalar > &leftEigenVect, fullMatrix< scalar > &rightEigenVect, bool sortRealPart=false)
bool svd (fullMatrix< scalar > &V, fullVector< scalar > &S)
void print (const std::string &name="", const std::string &format="") const
void binarySave (FILE *f) const
void binaryLoad (FILE *f)
bool getOwnData () const
void setOwnData (bool ownData)
void print (const std::string &name, const std::string &format) const
Private Attributes
bool _ownData
int _r
int _c
scalar * _data
Friends
class fullVector< scalar >
Detailed Description
template<class scalar>
class fullMatrix< scalar >
Definition at line 27 of file MElement.h.
Constructor & Destructor Documentation
fullMatrix() [1/6]
template<class scalar > fullMatrix< scalar >::fullMatrix (scalar * original, int r, int c) inline
Definition at line 237 of file fullMatrix.h.
fullMatrix() [2/6]
template<class scalar > fullMatrix< scalar >::fullMatrix (fullMatrix< scalar > & original, int c_start, int c) inline
Definition at line 244 of file fullMatrix.h.
fullMatrix() [3/6]
template<class scalar > fullMatrix< scalar >::fullMatrix (int r, int c, bool init0 = true) inline
Definition at line 251 of file fullMatrix.h.
fullMatrix() [4/6]
template<class scalar > fullMatrix< scalar >::fullMatrix (int r, int c, scalar * data) inline
Definition at line 257 of file fullMatrix.h.
fullMatrix() [5/6]
template<class scalar > fullMatrix< scalar >::fullMatrix (const fullMatrix< scalar > & other) inline
Definition at line 262 of file fullMatrix.h.
fullMatrix() [6/6]
template<class scalar > fullMatrix< scalar >::fullMatrix () inline
Definition at line 268 of file fullMatrix.h.
~fullMatrix()
template<class scalar > fullMatrix< scalar >::~fullMatrix () inline
Definition at line 269 of file fullMatrix.h.
Member Function Documentation
add() [1/3]
template<class scalar > void fullMatrix< scalar >::add (const double & a) inline
Definition at line 463 of file fullMatrix.h.
Referenced by fullMatrix< double >::gemm(), gmshGenerateMonomialsHexahedron(), gmshGenerateMonomialsPrism(), gmshGenerateMonomialsPyramid(), gmshGenerateMonomialsQuadrangle(), gmshGenerateMonomialsTetrahedron(), gmshGenerateMonomialsTriangle(), gmshGenerateOrderedPoints(), gmshGeneratePointsHexahedron(), gmshGeneratePointsLine(), gmshGeneratePointsPrism(), and gmshGeneratePointsQuadrangle().
add() [2/3]
template<class scalar > void fullMatrix< scalar >::add (const fullMatrix< scalar > & m) inline
Definition at line 467 of file fullMatrix.h.
add() [3/3]
template<class scalar > void fullMatrix< scalar >::add (const fullMatrix< scalar > & m, const scalar & a) inline
Definition at line 477 of file fullMatrix.h.
axpy()
template<class scalar > void fullMatrix< scalar >::axpy (const fullMatrix< scalar > & x, scalar alpha = 1.) inline
Definition at line 595 of file fullMatrix.h.
binaryLoad()
template<class scalar > void fullMatrix< scalar >::binaryLoad (FILE * f) inline
Definition at line 786 of file fullMatrix.h.
binarySave()
template<class scalar > void fullMatrix< scalar >::binarySave (FILE * f) const inline
Definition at line 785 of file fullMatrix.h.
copy() [1/2]
template<class scalar > void fullMatrix< scalar >::copy (const fullMatrix< scalar > & a) inline
Definition at line 401 of file fullMatrix.h.
copy() [2/2]
template<class scalar > void fullMatrix< scalar >::copy (const fullMatrix< scalar > & a, int i0, int ni, int j0, int nj, int desti0, int destj0) inline
Definition at line 394 of file fullMatrix.h.
Referenced by gmshGenerateMonomialsHexahedron(), gmshGenerateMonomialsPyramid(), gmshGenerateMonomialsQuadrangle(), gmshGenerateMonomialsTetrahedron(), gmshGenerateMonomialsTriangle(), JacobianBasis::JacobianBasis(), and fullMatrix< double >::operator=().
copyOneColumn()
template<class scalar > void fullMatrix< scalar >::copyOneColumn (const fullVector< scalar > & x, const int ind) const inline
Definition at line 417 of file fullMatrix.h.
determinant()
template<class scalar > scalar fullMatrix< scalar >::determinant () const inline
Definition at line 681 of file fullMatrix.h.
Referenced by SMetric3::determinant().
eig()
template<class scalar > bool fullMatrix< scalar >::eig (fullVector< double > & eigenValReal, fullVector< double > & eigenValImag, fullMatrix< scalar > & leftEigenVect, fullMatrix< scalar > & rightEigenVect, bool sortRealPart = false) inline
Definition at line 727 of file fullMatrix.h.
Referenced by addTensorElement(), SOrientedBoundingBox::buildOBB(), meshMetric::computeMetricEigenDir(), ComputeScalarRep(), MElement::getEigenvaluesMetric(), and GFace::getMetricEigenVectors().
eigSort()
template<class scalar > void fullMatrix< scalar >::eigSort (int n, scalar * wr, scalar * wi, scalar * VL, scalar * VR) inline
Definition at line 703 of file fullMatrix.h.
Referenced by fullMatrix< double >::eig().
gemm()
template<class scalar > void fullMatrix< scalar >::gemm (const fullMatrix< scalar > & a, const fullMatrix< scalar > & b, scalar alpha = 1., scalar beta = 1., bool transposeA = false, bool transposeB = false) inline
Definition at line 580 of file fullMatrix.h.
Referenced by computeAffineTransformation(), meshMetric::computeHessian(), meshMetric::computeMetricEigenDir(), elasticityTerm::elementMatrix(), elasticityMixedTerm::elementMatrix(), gLevelsetPoints::evalRbfDer(), dofTraits< fullMatrix< T > >::gemm(), and IsotropicElasticTerm::get().
get()
template<class scalar > scalar fullMatrix< scalar >::get (int r, int c) const inline
Definition at line 276 of file fullMatrix.h.
getDataPtr() [1/2]
template<class scalar > scalar* fullMatrix< scalar >::getDataPtr () inline
Definition at line 288 of file fullMatrix.h.
getDataPtr() [2/2]
template<class scalar > const scalar* fullMatrix< scalar >::getDataPtr () const inline
Definition at line 287 of file fullMatrix.h.
Referenced by bezierCoeff::bezierCoeff().
getOwnData()
template<class scalar > bool fullMatrix< scalar >::getOwnData () const inline
Definition at line 790 of file fullMatrix.h.
invert()
template<class scalar > bool fullMatrix< scalar >::invert (fullMatrix< scalar > & result) const inline
Definition at line 641 of file fullMatrix.h.
Referenced by bezierBasis::_construct(), bezierBasis::_constructPyr(), createMatLob2LagP6(), and pyramidalBasis::pyramidalBasis().
invertInPlace()
template<class scalar > bool fullMatrix< scalar >::invertInPlace () inline
Definition at line 662 of file fullMatrix.h.
Referenced by gLevelsetPoints::gLevelsetPoints(), SMetric3::invert(), invertAffineTransformation(), and gLevelsetPoints::RbfOp().
luFactor()
template<class scalar > bool fullMatrix< scalar >::luFactor (fullVector< int > & ipiv) inline
Definition at line 624 of file fullMatrix.h.
luSolve()
template<class scalar > bool fullMatrix< scalar >::luSolve (const fullVector< scalar > & rhs, fullVector< scalar > & result) inline
Definition at line 603 of file fullMatrix.h.
Referenced by computeEquidistantParameters(), computeGLLParametersP6(), meshMetric::computeHessian(), and newton_fd().
luSubstitute()
template<class scalar > bool fullMatrix< scalar >::luSubstitute (const fullVector< scalar > & rhs, fullVector< int > & ipiv, fullVector< scalar > & result) inline
Definition at line 632 of file fullMatrix.h.
mult() [1/2]
template<class scalar > void fullMatrix< scalar >::mult (const fullMatrix< scalar > & b, fullMatrix< scalar > & c) const inline
Definition at line 516 of file fullMatrix.h.
mult() [2/2]
template<class scalar > void fullMatrix< scalar >::mult (const fullVector< scalar > & x, fullVector< scalar > & y) const inline
Definition at line 487 of file fullMatrix.h.
Referenced by bezierCoeff::_computeCoefficients(), adaptiveElements< T >::adapt(), adaptiveElements< T >::adaptForVTK(), SOrientedBoundingBox::buildOBB(), computeAffineTransformation(), computeShapeFunctions(), computeShapeFunctionsPyramid(), frameSolver2d::computeStiffnessMatrix(), createMatLob2LagP6(), fullMatrix< double >::gemm(), GradientBasis::getAllGradientsFromNodes(), GradientBasis::getAllIdealGradientsFromNodes(), getEdgeVerticesOnGeo(), GradientBasis::getGradientsFromNodes(), GradientBasis::getIdealGradientsFromNodes(), CondNumBasis::getInvCondNumAndGradientsGeneral(), CondNumBasis::getInvCondNumGeneral(), JacobianBasis::getJacobianGeneral(), JacobianBasis::getSignedJacAndGradientsGeneral(), JacobianBasis::primJac2Jac(), and SMetric3::transform().
multAddy()
template<class scalar > void fullMatrix< scalar >::multAddy (const fullVector< scalar > & x, fullVector< scalar > & y) const inline
Definition at line 502 of file fullMatrix.h.
multOnBlock()
template<class scalar > void fullMatrix< scalar >::multOnBlock (const fullMatrix< scalar > & b, const int ncol, const int fcol, const int alpha, const int beta, fullVector< scalar > & c) const inline
Definition at line 536 of file fullMatrix.h.
multTByT()
template<class scalar > void fullMatrix< scalar >::multTByT (const fullMatrix< scalar > & a) inline
Definition at line 532 of file fullMatrix.h.
multWithATranspose()
template<class scalar > void fullMatrix< scalar >::multWithATranspose (const fullVector< scalar > & x, scalar alpha, scalar beta, fullVector< scalar > & y) const inline
Definition at line 548 of file fullMatrix.h.
norm()
template<class scalar > scalar fullMatrix< scalar >::norm () const inline
Definition at line 300 of file fullMatrix.h.
operator()() [1/2]
template<class scalar > scalar& fullMatrix< scalar >::operator() (int i, int j) inline
Definition at line 383 of file fullMatrix.h.
operator()() [2/2]
template<class scalar > scalar fullMatrix< scalar >::operator() (int i, int j) const inline
Definition at line 372 of file fullMatrix.h.
operator+=()
template<class scalar > void fullMatrix< scalar >::operator+= (const fullMatrix< scalar > & other) inline
Definition at line 364 of file fullMatrix.h.
operator=()
template<class scalar > fullMatrix<scalar>& fullMatrix< scalar >::operator= (const fullMatrix< scalar > & other) inline
Definition at line 359 of file fullMatrix.h.
print() [1/2]
void fullMatrix< int >::print (const std::string & name, const std::string & format) const
Definition at line 496 of file fullMatrix.cpp.
print() [2/2]
template<class scalar > void fullMatrix< scalar >::print (const std::string & name = "", const std::string & format = "") const
Referenced by incompleteBasis::_computeCoefficientsTriangle().
reshape()
template<class scalar > void fullMatrix< scalar >::reshape (int nbRows, int nbColumns) inline
Definition at line 324 of file fullMatrix.h.
resize()
template<class scalar > bool fullMatrix< scalar >::resize (int r, int c, bool resetValue = true) inline
Definition at line 307 of file fullMatrix.h.
Referenced by incompleteBasis::_computeCoefficientsTriangle(), _computeCoeffLengthVectors(), bezierCoeff::_subdivideHexahedron(), bezierCoeff::_subdividePrism(), bezierCoeff::_subdividePyramid(), bezierCoeff::_subdivideQuadrangle(), incompleteBasis::df(), pyramidalBasis::df(), polynomialBasis::df(), gLevelsetPoints::evalRbfDer(), incompleteBasis::f(), pyramidalBasis::f(), polynomialBasis::f(), gaussIntegration::get(), BilinearTermBase::get(), BilinearTermContract< T2 >::get(), LaplaceTerm< T1, T1 >::get(), IsotropicElasticTerm::get(), LagrangeMultiplierTerm< T1 >::get(), LagMultTerm::get(), bezierCoeff::getCornerCoeffs(), MElement::getNodesCoordNonSerendip(), gLevelsetPoints::gLevelsetPoints(), gmshGenerateOrderedMonomials(), GradientBasis::GradientBasis(), JacobianBasis::JacobianBasis(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), pts2fullMatrix(), pyramidalBasis::pyramidalBasis(), jacobianBasedQuality::sampleIGEMeasure(), gLevelsetPoints::setup_level_set(), and MElement::signedInvCondNumRange().
scale()
template<class scalar > void fullMatrix< scalar >::scale (const scalar s) inline
Definition at line 447 of file fullMatrix.h.
Referenced by SOrientedBoundingBox::buildOBB(), meshMetric::computeMetricEigenDir(), DummyfemTerm::elementMatrix(), fullMatrix< double >::gemm(), gmshGenerateOrderedPoints(), gmshGeneratePointsHexahedron(), gmshGeneratePointsLine(), gmshGeneratePointsPrism(), gmshGeneratePointsQuadrangle(), gmshGeneratePointsTetrahedron(), gmshGeneratePointsTriangle(), and IsotropicElasticTerm::IsotropicElasticTerm().
set()
template<class scalar > void fullMatrix< scalar >::set (int r, int c, scalar v) inline
Definition at line 289 of file fullMatrix.h.
Referenced by PView::readMSH().
setAll() [1/2]
template<class scalar > void fullMatrix< scalar >::setAll (const fullMatrix< scalar > & m) inline
Definition at line 431 of file fullMatrix.h.
setAll() [2/2]
template<class scalar > void fullMatrix< scalar >::setAll (const scalar & m) inline
Definition at line 422 of file fullMatrix.h.
Referenced by fullMatrix< double >::copy(), discreteFrechetDistance(), helmholtzTerm< double >::elementMatrix(), elasticityTerm::elementMatrix(), elasticityMixedTerm::elementMatrix(), fullMatrix< double >::fullMatrix(), BilinearTermBase::get(), BilinearTermContract< T2 >::get(), LaplaceTerm< T1, T1 >::get(), IsotropicElasticTerm::get(), LagrangeMultiplierTerm< T1 >::get(), LagMultTerm::get(), CondNumBasis::getInvCondNumAndGradientsGeneral(), JacobianBasis::getJacobianGeneral(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), and fullMatrix< double >::resize().
setAsProxy() [1/3]
template<class scalar > void fullMatrix< scalar >::setAsProxy (const fullMatrix< scalar > & original) inline
Definition at line 335 of file fullMatrix.h.
Referenced by GradientBasis::getAllGradientsFromNodes(), GradientBasis::getAllIdealGradientsFromNodes(), gmshGenerateMonomialsPrism(), gmshGenerateMonomialsPyramid(), gmshGenerateOrderedPoints(), gmshGeneratePointsPrism(), and bezierCoeff::setMatrixAsProxy().
setAsProxy() [2/3]
template<class scalar > void fullMatrix< scalar >::setAsProxy (const fullMatrix< scalar > & original, int c_start, int c) inline
Definition at line 343 of file fullMatrix.h.
setAsProxy() [3/3]
template<class scalar > void fullMatrix< scalar >::setAsProxy (scalar * data, int r, int c) inline
Definition at line 351 of file fullMatrix.h.
setOwnData()
template<class scalar > void fullMatrix< scalar >::setOwnData (bool ownData) inline
Definition at line 791 of file fullMatrix.h.
size1()
template<class scalar > int fullMatrix< scalar >::size1 () const inline
Definition at line 274 of file fullMatrix.h.
Referenced by _computeCoeffLengthVectors(), _computeICN(), _computeIGE(), jacobianBasedQuality::_coeffDataICN::_computeLowerBound(), bezierBasisRaiser::_fillRaiserData(), bezierBasisRaiser::_fillRaiserDataPyr(), _getIndicesReversedHex(), _getIndicesReversedPri(), _getIndicesReversedPyr(), _getIndicesReversedTet(), femTerm< scalar >::addToMatrix(), bezierCoeff::bezierCoeff(), computeShapeFunctions(), computeShapeFunctionsPyramid(), CondNumBasis::CondNumBasis(), incompleteBasis::dddf(), polynomialBasis::dddf(), incompleteBasis::ddf(), polynomialBasis::ddf(), incompleteBasis::df(), pyramidalBasis::df(), polynomialBasis::df(), MLineN::discretize(), gLevelsetPoints::evalRbfDer(), polynomialBasis::evaluateMonomials(), incompleteBasis::f(), pyramidalBasis::f(), polynomialBasis::f(), nodalBasis::forwardRenumbering(), nodalBasis::forwardTransformation(), ClosureGen::generateFaceClosureHex(), ClosureGen::generateFaceClosureHexFull(), ClosureGen::generateFaceClosurePyr(), gLevelsetPoints::generateRbfMat(), GMSH_CutPlanePlugin::geometricalFilter(), MElement::getBezierVerticesCoord(), getFaceVerticesOnExtrudedGeo(), getFaceVerticesOnGeo(), MElement::getNodesCoordNonSerendip(), bezierBasis::getNumCoeff(), GradientBasis::getNumSamplingPoints(), incompleteBasis::getNumShapeFunctions(), polynomialBasis::getNumShapeFunctions(), pyramidalBasis::getNumShapeFunctions(), getVolumeVertices(), gLevelsetPoints::gLevelsetPoints(), gmshGenerateMonomialsHexahedron(), gmshGenerateMonomialsPrism(), gmshGenerateMonomialsPyramid(), gmshGenerateMonomialsTetrahedron(), gmshGenerateOrderedPoints(), gmshGeneratePointsPyramid(), gmshGeneratePointsPyramidGeneral(), GradientBasis::GradientBasis(), interpVerticesInExistingFace(), JacobianBasis::JacobianBasis(), MElement::maxDistToStraight(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), printNodes(), pyramidalBasis::pyramidalBasis(), gLevelsetPoints::RbfOp(), jacobianBasedQuality::sampleIGEMeasure(), PViewFactory::setEntry(), DocRecord::setPoints(), elasticityMixedTerm::setPolynomialBasis(), and gLevelsetPoints::setup_level_set().
size2()
template<class scalar > int fullMatrix< scalar >::size2 () const inline
Definition at line 275 of file fullMatrix.h.
Referenced by _computeICN(), jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), jacobianBasedQuality::_coeffDataICN::_computeLowerBound(), bezierCoeff::_copyHex(), bezierCoeff::_copyLine(), bezierCoeff::_copyPyr(), bezierCoeff::_copyQuad(), bezierCoeff::_subdivide(), femTerm< scalar >::addToMatrix(), bezierCoeff::bezierCoeff(), computeShapeFunctions(), CondNumBasis::CondNumBasis(), polynomialBasis::dddf(), polynomialBasis::ddf(), polynomialBasis::df(), gLevelsetPoints::evalRbfDer(), polynomialBasis::f(), MElement::getBezierVerticesCoord(), bezierBasis::getDim(), getFaceVerticesOnGeo(), MElement::getJacobian(), JacobianBasis::getJacobianGeneral(), GradientBasis::getNumMapNodes(), getVolumeVertices(), GradientBasis::GradientBasis(), interpVerticesInExistingFace(), JacobianBasis::JacobianBasis(), MElement::maxDistToStraight(), jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), MFaceN::repositionInnerVertices(), and PViewFactory::setEntry().
svd()
template<class scalar > bool fullMatrix< scalar >::svd (fullMatrix< scalar > & V, fullVector< scalar > & S) inline
Definition at line 761 of file fullMatrix.h.
Referenced by fullMatrix< double >::svd().
swap()
template<class scalar > void fullMatrix< scalar >::swap (scalar * a, int inca, scalar * b, int incb, int n) inline
Definition at line 694 of file fullMatrix.h.
Referenced by fullMatrix< double >::eigSort().
transpose()
template<class scalar > fullMatrix<scalar> fullMatrix< scalar >::transpose () const inline
Definition at line 558 of file fullMatrix.h.
Referenced by Assemble(), SOrientedBoundingBox::buildOBB(), fullMatrix< double >::gemm(), and SMetric3::transform().
transposeInPlace()
template<class scalar > void fullMatrix< scalar >::transposeInPlace () inline
Definition at line 565 of file fullMatrix.h.
Referenced by SMetric3::SMetric3().
Friends And Related Function Documentation
fullVector< scalar >
template<class scalar > friend class fullVector< scalar > friend
Definition at line 228 of file fullMatrix.h.
Member Data Documentation
_c
template<class scalar > int fullMatrix< scalar >::_c private
Definition at line 227 of file fullMatrix.h.
Referenced by fullMatrix< double >::add(), fullMatrix< double >::axpy(), fullMatrix< double >::binaryLoad(), fullMatrix< double >::binarySave(), fullMatrix< double >::copy(), fullMatrix< double >::copyOneColumn(), fullMatrix< double >::determinant(), fullMatrix< double >::eig(), fullMatrix< double >::fullMatrix(), fullMatrix< double >::gemm(), fullMatrix< double >::get(), fullMatrix< double >::invert(), fullMatrix< double >::invertInPlace(), fullMatrix< double >::luSolve(), fullMatrix< double >::mult(), fullMatrix< double >::multAddy(), fullMatrix< double >::multOnBlock(), fullMatrix< double >::multTByT(), fullMatrix< double >::multWithATranspose(), fullMatrix< double >::norm(), fullMatrix< double >::operator()(), fullMatrix< double >::operator+=(), fullMatrix< double >::reshape(), fullMatrix< double >::resize(), fullMatrix< double >::scale(), fullMatrix< double >::set(), fullMatrix< double >::setAll(), fullMatrix< double >::setAsProxy(), fullMatrix< double >::size2(), fullMatrix< double >::svd(), fullMatrix< double >::transpose(), and fullMatrix< double >::transposeInPlace().
_data
template<class scalar > scalar* fullMatrix< scalar >::_data private
Definition at line 228 of file fullMatrix.h.
Referenced by fullMatrix< double >::add(), fullMatrix< double >::axpy(), fullMatrix< double >::binaryLoad(), fullMatrix< double >::binarySave(), fullMatrix< double >::copy(), fullMatrix< double >::copyOneColumn(), fullMatrix< double >::determinant(), fullMatrix< double >::eig(), fullMatrix< double >::fullMatrix(), fullMatrix< double >::getDataPtr(), fullMatrix< double >::invert(), fullMatrix< double >::invertInPlace(), fullMatrix< double >::luSolve(), fullMatrix< double >::mult(), fullMatrix< double >::multAddy(), fullMatrix< double >::multTByT(), fullMatrix< double >::operator()(), fullMatrix< double >::operator+=(), fullMatrix< double >::resize(), fullMatrix< double >::scale(), fullMatrix< double >::setAll(), fullVector< double >::setAsProxy(), fullMatrix< double >::setAsProxy(), fullMatrix< double >::svd(), fullMatrix< double >::transposeInPlace(), and fullMatrix< double >::~fullMatrix().
_ownData
template<class scalar > bool fullMatrix< scalar >::_ownData private
Definition at line 226 of file fullMatrix.h.
Referenced by fullMatrix< double >::copy(), fullMatrix< double >::fullMatrix(), fullMatrix< double >::getOwnData(), fullMatrix< double >::resize(), fullMatrix< double >::setAsProxy(), fullMatrix< double >::setOwnData(), and fullMatrix< double >::~fullMatrix().
_r
template<class scalar > int fullMatrix< scalar >::_r private
Definition at line 227 of file fullMatrix.h.
Referenced by fullMatrix< double >::add(), fullMatrix< double >::axpy(), fullMatrix< double >::binaryLoad(), fullMatrix< double >::binarySave(), fullMatrix< double >::copy(), fullMatrix< double >::copyOneColumn(), fullMatrix< double >::determinant(), fullMatrix< double >::eig(), fullMatrix< double >::fullMatrix(), fullMatrix< double >::gemm(), fullMatrix< double >::get(), fullMatrix< double >::invert(), fullMatrix< double >::invertInPlace(), fullMatrix< double >::luSolve(), fullMatrix< double >::mult(), fullMatrix< double >::multAddy(), fullMatrix< double >::multTByT(), fullMatrix< double >::multWithATranspose(), fullMatrix< double >::norm(), fullMatrix< double >::operator()(), fullMatrix< double >::operator+=(), fullMatrix< double >::reshape(), fullMatrix< double >::resize(), fullMatrix< double >::scale(), fullMatrix< double >::set(), fullMatrix< double >::setAll(), fullVector< double >::setAsProxy(), fullMatrix< double >::setAsProxy(), fullMatrix< double >::size1(), fullMatrix< double >::svd(), fullMatrix< double >::transpose(), and fullMatrix< double >::transposeInPlace().
The documentation for this class was generated from the following files:
src/geo/MElement.h
src/numeric/fullMatrix.h