gmsh-TingyuanDoc: GMSH_CutSpherePlugin Class Reference
GMSH_CutSpherePlugin Class Reference
#include <CutSphere.h>
Public Member Functions
GMSH_CutSpherePlugin ()
std::string getName () const
std::string getShortHelp () const
std::string getHelp () const
int getNbOptions () const
StringXNumber * getOption (int iopt)
PView * execute (PView *)
Public Member Functions inherited from GMSH_LevelsetPlugin
GMSH_LevelsetPlugin ()
void assignSpecificVisibility () const
Public Member Functions inherited from GMSH_PostPlugin
GMSH_PLUGIN_TYPE getType () const
virtual int run ()
virtual PView * executeRemote (PView *)
virtual PView * getView (int index, PView *view)
virtual PViewDataList * getDataList (PView *view, bool showError=true)
virtual PViewData * getPossiblyAdaptiveData (PView *view)
virtual bool geometricalFilter (fullMatrix< double > *) const
Public Member Functions inherited from GMSH_Plugin
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
virtual int getNbOptionsStr () const
virtual StringXString * getOptionStr (int iopt)
std::string serialize ()
Static Public Member Functions
static double callbackX (int, int, double)
static double callbackY (int, int, double)
static double callbackZ (int, int, double)
static double callbackR (int, int, double)
static double callbackVol (int, int, double)
static double callbackRecur (int, int, double)
static double callbackTarget (int, int, double)
static void draw (void *context)
Static Public Member Functions inherited from GMSH_Plugin
static void setDrawFunction (void(*fct)(void *))
Private Member Functions
double levelset (double x, double y, double z, double val) const
Static Private Member Functions
static double callback (int num, int action, double value, double *opt, double step, double min, double max)
Additional Inherited Members
Public Types inherited from GMSH_Plugin
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Public Attributes inherited from GMSH_Plugin
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes inherited from GMSH_Plugin
static void(* draw)(void *) = nullptr
Protected Types inherited from GMSH_LevelsetPlugin
enum ORIENTATION { NONE, PLANE, SPHERE, MAP }
Protected Attributes inherited from GMSH_LevelsetPlugin
double _ref [3]
double _targetError
int _valueTimeStep
int _valueView
int _valueIndependent
int _recurLevel
int _extractVolume
ORIENTATION _orientation
Detailed Description
Definition at line 15 of file CutSphere.h.
Constructor & Destructor Documentation
GMSH_CutSpherePlugin()
GMSH_CutSpherePlugin::GMSH_CutSpherePlugin () inline
Definition at line 21 of file CutSphere.h.
Member Function Documentation
callback()
double GMSH_CutSpherePlugin::callback (int num, int action, double value, double * opt, double step, double min, double max) static private
Definition at line 48 of file CutSphere.cpp.
Referenced by callbackR(), callbackRecur(), callbackTarget(), callbackVol(), callbackX(), callbackY(), and callbackZ().
callbackR()
double GMSH_CutSpherePlugin::callbackR (int num, int action, double value) static
Definition at line 84 of file CutSphere.cpp.
callbackRecur()
double GMSH_CutSpherePlugin::callbackRecur (int num, int action, double value) static
Definition at line 96 of file CutSphere.cpp.
callbackTarget()
double GMSH_CutSpherePlugin::callbackTarget (int num, int action, double value) static
Definition at line 102 of file CutSphere.cpp.
callbackVol()
double GMSH_CutSpherePlugin::callbackVol (int num, int action, double value) static
Definition at line 90 of file CutSphere.cpp.
callbackX()
double GMSH_CutSpherePlugin::callbackX (int num, int action, double value) static
Definition at line 63 of file CutSphere.cpp.
callbackY()
double GMSH_CutSpherePlugin::callbackY (int num, int action, double value) static
Definition at line 70 of file CutSphere.cpp.
callbackZ()
double GMSH_CutSpherePlugin::callbackZ (int num, int action, double value) static
Definition at line 77 of file CutSphere.cpp.
draw()
void GMSH_CutSpherePlugin::draw (void * context) static
Definition at line 32 of file CutSphere.cpp.
execute()
PView * GMSH_CutSpherePlugin::execute (PView * v) virtual
Reimplemented from GMSH_LevelsetPlugin.
Definition at line 139 of file CutSphere.cpp.
getHelp()
std::string GMSH_CutSpherePlugin::getHelp () const virtual
Implements GMSH_Plugin.
Definition at line 108 of file CutSphere.cpp.
getName()
std::string GMSH_CutSpherePlugin::getName () const inline virtual
Implements GMSH_Plugin.
Definition at line 22 of file CutSphere.h.
getNbOptions()
int GMSH_CutSpherePlugin::getNbOptions () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 119 of file CutSphere.cpp.
getOption()
StringXNumber * GMSH_CutSpherePlugin::getOption (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 124 of file CutSphere.cpp.
getShortHelp()
std::string GMSH_CutSpherePlugin::getShortHelp () const inline virtual
Implements GMSH_Plugin.
Definition at line 23 of file CutSphere.h.
levelset()
double GMSH_CutSpherePlugin::levelset (double x, double y, double z, double val) const private virtual
Implements GMSH_LevelsetPlugin.
Definition at line 129 of file CutSphere.cpp.
The documentation for this class was generated from the following files:
src/plugin/CutSphere.h
src/plugin/CutSphere.cpp