gmsh-TingyuanDoc: drawContext Class Reference
drawContext Class Reference
#include <drawContext.h>
Public Types
enum RenderMode { GMSH_RENDER = 1, GMSH_SELECT = 2, GMSH_FEEDBACK = 3 }
Public Member Functions
drawContext (openglWindow *window=nullptr, drawTransform *transform=nullptr)
~drawContext ()
double highResolutionPixelFactor ()
void copyViewAttributes (drawContext *other)
void setTransform (drawTransform *transform)
drawTransform * getTransform ()
void transform (double &x, double &y, double &z)
void transformOneForm (double &x, double &y, double &z)
void transformTwoForm (double &x, double &y, double &z)
void hide (GModel *m)
void hide (PView *v)
void show (GModel *m)
void show (PView *v)
void showAll ()
bool isVisible (GModel *m)
bool isVisible (PView *v)
void createQuadricsAndDisplayLists ()
void invalidateQuadricsAndDisplayLists ()
bool generateTextureForImage (const std::string &name, int page, GLuint &imageTexture, GLuint &imageW, GLuint &imageH)
void invalidateBgImageTexture ()
void buildRotationMatrix ()
void setQuaternion (double p1x, double p1y, double p2x, double p2y)
void addQuaternion (double p1x, double p1y, double p2x, double p2y)
void addQuaternionFromAxisAndAngle (double axis[3], double angle)
void setQuaternionFromEulerAngles ()
void setEulerAnglesFromRotationMatrix ()
void initProjection (int xpick=0, int ypick=0, int wpick=0, int hpick=0)
void initRenderModel ()
void initPosition (bool saveMatrices)
void unproject (double winx, double winy, double p[3], double d[3])
void viewport2World (double vp[3], double xyz[3])
void world2Viewport (double xyz[3], double vp[3])
bool select (int type, bool multiple, bool mesh, bool post, int x, int y, int w, int h, std::vector< GVertex * > &vertices, std::vector< GEdge * > &edges, std::vector< GFace * > &faces, std::vector< GRegion * > &regions, std::vector< MElement * > &elements, std::vector< SPoint2 > &points, std::vector< PView * > &views)
void recenterForRotationCenterChange (SPoint3 newRotationCenter)
int fix2dCoordinates (double *x, double *y)
void draw3d ()
void draw2d ()
void drawGeom ()
void drawMesh ()
void drawPost ()
void drawBackgroundGradient ()
void drawBackgroundImage (bool moving)
void drawText2d ()
void drawGraph2d (bool inModelCoordinates)
void drawAxis (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, int nticks, int mikado)
void drawAxes (int mode, double tics[3], std::string format[3], std::string label[3], double bb[6], int mikado, double value_bb[6])
void drawAxes (int mode, double tics[3], std::string format[3], std::string label[3], SBoundingBox3d &bb, int mikado, SBoundingBox3d &value_bb)
void drawAxes ()
void drawSmallAxes ()
void drawTrackball ()
void drawScales ()
void drawString (const std::string &s, double x, double y, double z, const std::string &font_name, int font_enum, int font_size, int align, int line_num=0)
void drawString (const std::string &s, double x, double y, double z, int line_num=0)
void drawStringCenter (const std::string &s, double x, double y, double z, int line_num=0)
void drawStringRight (const std::string &s, double x, double y, double z, int line_num=0)
void drawString (const std::string &s, double x, double y, double z, double style, int line_num=0)
void drawImage (const std::string &s, double x, double y, double z, int align=0)
void drawSphere (double R, double x, double y, double z, int n1, int n2, int light)
void drawCube (double x, double y, double z, double val[9], int light)
void drawEllipsoid (double x, double y, double z, float v0[3], float v1[3], float v2[3], int light)
void drawEllipse (double x, double y, double z, float v0[3], float v1[3], int light)
void drawSphere (double size, double x, double y, double z, int light)
void drawCylinder (double width, double *x, double *y, double *z, int light)
void drawTaperedCylinder (double width, double val1, double val2, double ValMin, double ValMax, double *x, double *y, double *z, int light)
void drawArrow3d (double x, double y, double z, double dx, double dy, double dz, double length, int light)
void drawVector (int Type, int Fill, double x, double y, double z, double dx, double dy, double dz, int light)
void drawBox (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, bool labels=true)
void drawPlaneInBoundingBox (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, double a, double b, double c, double d, int shade=0)
Static Public Member Functions
static void setGlobal (drawContextGlobal *global)
static drawContextGlobal * global ()
static void setDrawGeomTransientFunction (void(*fct)(void *))
Public Attributes
Camera camera
double r [3]
double t [3]
double s [3]
double quaternion [4]
int viewport [4]
double rot [16]
double t_init [3]
double vxmin
double vxmax
double vymin
double vymax
double pixel_equiv_x
double pixel_equiv_y
double model [16]
double proj [16]
int render_mode
Static Public Attributes
static void(* drawGeomTransient)(void *) = nullptr
Private Attributes
drawTransform * _transform
GLUquadricObj * _quadric
GLuint _displayLists
std::set< GModel * > _hiddenModels
std::set< PView * > _hiddenViews
GLuint _bgImageTexture
GLuint _bgImageW
GLuint _bgImageH
openglWindow * _openglWindow
std::map< std::string, imgtex > _imageTextures
Static Private Attributes
static drawContextGlobal * _global = nullptr
Detailed Description
Definition at line 120 of file drawContext.h.
Member Enumeration Documentation
RenderMode
enum drawContext::RenderMode
Enumerator
GMSH_RENDER
GMSH_SELECT
GMSH_FEEDBACK
Definition at line 145 of file drawContext.h.
Constructor & Destructor Documentation
drawContext()
drawContext::drawContext (openglWindow * window = nullptr, drawTransform * transform = nullptr)
Definition at line 45 of file drawContext.cpp.
~drawContext()
drawContext::~drawContext ()
Definition at line 71 of file drawContext.cpp.
Member Function Documentation
addQuaternion()
void drawContext::addQuaternion (double p1x, double p1y, double p2x, double p2y)
Definition at line 195 of file drawContext.cpp.
addQuaternionFromAxisAndAngle()
void drawContext::addQuaternionFromAxisAndAngle (double axis[3], double angle)
Definition at line 203 of file drawContext.cpp.
buildRotationMatrix()
void drawContext::buildRotationMatrix ()
Definition at line 157 of file drawContext.cpp.
Referenced by initPosition().
copyViewAttributes()
void drawContext::copyViewAttributes (drawContext * other) inline
Definition at line 153 of file drawContext.h.
createQuadricsAndDisplayLists()
void drawContext::createQuadricsAndDisplayLists ()
Definition at line 103 of file drawContext.cpp.
Referenced by draw3d().
draw2d()
void drawContext::draw2d ()
Definition at line 329 of file drawContext.cpp.
draw3d()
void drawContext::draw3d ()
Definition at line 277 of file drawContext.cpp.
drawArrow3d()
void drawContext::drawArrow3d (double x, double y, double z, double dx, double dy, double dz, double length, int light)
Definition at line 689 of file drawGlyph.cpp.
Referenced by drawPlaneInBoundingBox(), and drawVector().
drawAxes() [1/3]
void drawContext::drawAxes ()
Definition at line 295 of file drawAxes.cpp.
Referenced by draw3d(), and drawAxes().
drawAxes() [2/3]
void drawContext::drawAxes (int mode, double tics[3], std::string format[3], std::string label[3], double bb[6], int mikado, double value_bb[6])
Definition at line 176 of file drawAxes.cpp.
Referenced by drawPView::operator()().
drawAxes() [3/3]
void drawContext::drawAxes (int mode, double tics[3], std::string format[3], std::string label[3], SBoundingBox3d & bb, int mikado, SBoundingBox3d & value_bb)
Definition at line 283 of file drawAxes.cpp.
drawAxis()
void drawContext::drawAxis (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, int nticks, int mikado)
Definition at line 146 of file drawAxes.cpp.
Referenced by drawAxes().
drawBackgroundGradient()
void drawContext::drawBackgroundGradient ()
Definition at line 355 of file drawContext.cpp.
Referenced by initProjection().
drawBackgroundImage()
void drawContext::drawBackgroundImage (bool moving)
Definition at line 464 of file drawContext.cpp.
Referenced by draw3d(), and initProjection().
drawBox()
void drawContext::drawBox (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, bool labels = true)
Definition at line 787 of file drawGlyph.cpp.
Referenced by drawAxes(), and drawPViewBoundingBox::operator()().
drawCube()
void drawContext::drawCube (double x, double y, double z, double val[9], int light)
Definition at line 316 of file drawGlyph.cpp.
drawCylinder()
void drawContext::drawCylinder (double width, double * x, double * y, double * z, int light)
Definition at line 490 of file drawGlyph.cpp.
Referenced by drawArrays(), drawAxis(), drawPlaneInBoundingBox(), and drawGEdge::operator()().
drawEllipse()
void drawContext::drawEllipse (double x, double y, double z, float v0[3], float v1[3], int light)
Definition at line 401 of file drawGlyph.cpp.
Referenced by drawEllipseArray().
drawEllipsoid()
void drawContext::drawEllipsoid (double x, double y, double z, float v0[3], float v1[3], float v2[3], int light)
Definition at line 428 of file drawGlyph.cpp.
Referenced by drawEllipseArray().
drawGeom()
void drawContext::drawGeom ()
Definition at line 480 of file drawGeom.cpp.
Referenced by draw3d(), and select().
drawGraph2d()
void drawContext::drawGraph2d (bool inModelCoordinates)
Definition at line 574 of file drawGraph2d.cpp.
Referenced by draw2d(), draw3d(), and select().
drawImage()
void drawContext::drawImage (const std::string & s, double x, double y, double z, int align = 0)
Definition at line 180 of file drawGlyph.cpp.
Referenced by drawString().
drawMesh()
void drawContext::drawMesh ()
Definition at line 680 of file drawMesh.cpp.
Referenced by draw3d(), and select().
drawPlaneInBoundingBox()
void drawContext::drawPlaneInBoundingBox (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, double a, double b, double c, double d, int shade = 0)
Definition at line 824 of file drawGlyph.cpp.
Referenced by GMSH_CutPlanePlugin::draw(), drawAxes(), and drawPViewBoundingBox::operator()().
drawPost()
void drawContext::drawPost ()
Definition at line 615 of file drawPost.cpp.
Referenced by draw3d(), and select().
drawScales()
void drawContext::drawScales ()
Definition at line 272 of file drawScales.cpp.
Referenced by draw2d().
drawSmallAxes()
void drawContext::drawSmallAxes ()
Definition at line 364 of file drawAxes.cpp.
Referenced by draw2d().
drawSphere() [1/2]
void drawContext::drawSphere (double R, double x, double y, double z, int n1, int n2, int light)
Definition at line 390 of file drawGlyph.cpp.
Referenced by addGraphPoint(), GMSH_ProbePlugin::draw(), GMSH_CutSpherePlugin::draw(), GMSH_ParticlesPlugin::draw(), GMSH_StreamLinesPlugin::draw(), GMSH_CutParametricPlugin::draw(), GMSH_CutGridPlugin::draw(), GMSH_CutBoxPlugin::draw(), drawArrays(), drawAxes(), drawVerticesPerElement(), drawVerticesPerEntity(), drawGVertex::operator()(), and drawGRegion::operator()().
drawSphere() [2/2]
void drawContext::drawSphere (double size, double x, double y, double z, int light)
Definition at line 442 of file drawGlyph.cpp.
drawString() [1/3]
void drawContext::drawString (const std::string & s, double x, double y, double z, const std::string & font_name, int font_enum, int font_size, int align, int line_num = 0)
Definition at line 16 of file drawGlyph.cpp.
Referenced by addGraphPoint(), GMSH_AnnotatePlugin::draw(), GMSH_CutGridPlugin::draw(), GMSH_CutBoxPlugin::draw(), drawBox(), drawElementLabels(), drawEntityLabel(), drawGraphAxes(), drawNumberGlyphs(), drawScaleLabel(), drawScaleValues(), drawSmallAxes(), drawString(), drawStringCenter(), drawStringRight(), drawText2d(), drawTics(), drawVertexLabel(), and drawPView::operator()().
drawString() [2/3]
void drawContext::drawString (const std::string & s, double x, double y, double z, double style, int line_num = 0)
Definition at line 161 of file drawGlyph.cpp.
drawString() [3/3]
void drawContext::drawString (const std::string & s, double x, double y, double z, int line_num = 0)
Definition at line 140 of file drawGlyph.cpp.
drawStringCenter()
void drawContext::drawStringCenter (const std::string & s, double x, double y, double z, int line_num = 0)
Definition at line 147 of file drawGlyph.cpp.
Referenced by drawGraphAxes(), drawNumberGlyphs(), and drawScaleValues().
drawStringRight()
void drawContext::drawStringRight (const std::string & s, double x, double y, double z, int line_num = 0)
Definition at line 154 of file drawGlyph.cpp.
Referenced by drawGraphAxes(), and drawNumberGlyphs().
drawTaperedCylinder()
void drawContext::drawTaperedCylinder (double width, double val1, double val2, double ValMin, double ValMax, double * x, double * y, double * z, int light)
Definition at line 455 of file drawGlyph.cpp.
Referenced by drawArrays().
drawText2d()
void drawContext::drawText2d ()
Definition at line 34 of file drawGraph2d.cpp.
Referenced by draw2d(), and select().
drawTrackball()
void drawContext::drawTrackball ()
drawVector()
void drawContext::drawVector (int Type, int Fill, double x, double y, double z, double dx, double dy, double dz, int light)
Definition at line 714 of file drawGlyph.cpp.
Referenced by drawArrays(), drawNormals(), drawNormalVectorGlyphs(), drawTangents(), drawTangentVectorGlyphs(), drawVectorArray(), drawGEdge::operator()(), and drawGFace::operator()().
fix2dCoordinates()
int drawContext::fix2dCoordinates (double * x, double * y)
Definition at line 15 of file drawGraph2d.cpp.
Referenced by GMSH_AnnotatePlugin::draw(), drawBackgroundImage(), drawGraph2d(), drawScales(), drawSmallAxes(), and drawText2d().
generateTextureForImage()
bool drawContext::generateTextureForImage (const std::string & name, int page, GLuint & imageTexture, GLuint & imageW, GLuint & imageH)
Definition at line 402 of file drawContext.cpp.
Referenced by drawBackgroundImage(), and drawImage().
getTransform()
drawTransform* drawContext::getTransform () inline
Definition at line 172 of file drawContext.h.
global()
drawContextGlobal * drawContext::global () static
Definition at line 85 of file drawContext.cpp.
Referenced by CreateOutputFile(), drawGraph2d(), drawGraphAxes(), drawScaleLabel(), drawScales(), drawScaleValues(), drawString(), drawTics(), GMSH_ShowNeighborElementsPlugin::execute(), PixelBuffer::fill(), getStyle(), OpenProjectMacFinder(), opt_general_color_axes(), opt_general_color_small_axes(), opt_general_color_text(), opt_general_graphics_font_engine(), opt_mesh_color_carousel(), opt_view_color_axes(), opt_view_color_background2d(), opt_view_color_text2d(), opt_view_color_text3d(), GMSH_Plugin::setDrawFunction(), and setGlobal().
hide() [1/2]
void drawContext::hide (GModel * m) inline
Definition at line 185 of file drawContext.h.
hide() [2/2]
void drawContext::hide (PView * v) inline
Definition at line 186 of file drawContext.h.
highResolutionPixelFactor()
double drawContext::highResolutionPixelFactor ()
Definition at line 73 of file drawContext.cpp.
Referenced by addGraphPoint(), drawGraphAxes(), drawGraphCurves(), drawImage(), drawString(), drawGVertex::operator()(), and unproject().
initPosition()
void drawContext::initPosition (bool saveMatrices)
Definition at line 786 of file drawContext.cpp.
Referenced by draw3d(), and select().
initProjection()
void drawContext::initProjection (int xpick = 0, int ypick = 0, int wpick = 0, int hpick = 0)
Definition at line 554 of file drawContext.cpp.
Referenced by draw3d(), and select().
initRenderModel()
void drawContext::initRenderModel ()
Definition at line 696 of file drawContext.cpp.
Referenced by draw3d().
invalidateBgImageTexture()
void drawContext::invalidateBgImageTexture ()
Definition at line 396 of file drawContext.cpp.
invalidateQuadricsAndDisplayLists()
void drawContext::invalidateQuadricsAndDisplayLists ()
Definition at line 91 of file drawContext.cpp.
Referenced by ~drawContext().
isVisible() [1/2]
bool drawContext::isVisible (GModel * m) inline
Definition at line 202 of file drawContext.h.
Referenced by drawGeom(), drawGraph2d(), drawMesh(), drawScales(), drawText2d(), and drawPView::operator()().
isVisible() [2/2]
bool drawContext::isVisible (PView * v) inline
Definition at line 206 of file drawContext.h.
recenterForRotationCenterChange()
void drawContext::recenterForRotationCenterChange (SPoint3 newRotationCenter)
Definition at line 1119 of file drawContext.cpp.
select()
bool drawContext::select (int type, bool multiple, bool mesh, bool post, int x, int y, int w, int h, std::vector< GVertex * > & vertices, std::vector< GEdge * > & edges, std::vector< GFace * > & faces, std::vector< GRegion * > & regions, std::vector< MElement * > & elements, std::vector< SPoint2 > & points, std::vector< PView * > & views)
Definition at line 917 of file drawContext.cpp.
setDrawGeomTransientFunction()
void drawContext::setDrawGeomTransientFunction (void(*)(void *) fct) static
Definition at line 38 of file drawContext.cpp.
setEulerAnglesFromRotationMatrix()
void drawContext::setEulerAnglesFromRotationMatrix ()
Definition at line 235 of file drawContext.cpp.
Referenced by buildRotationMatrix().
setGlobal()
static void drawContext::setGlobal (drawContextGlobal * global) inline static
Definition at line 169 of file drawContext.h.
Referenced by opt_general_graphics_font_engine().
setQuaternion()
void drawContext::setQuaternion (double p1x, double p1y, double p2x, double p2y)
Definition at line 211 of file drawContext.cpp.
setQuaternionFromEulerAngles()
void drawContext::setQuaternionFromEulerAngles ()
Definition at line 219 of file drawContext.cpp.
Referenced by buildRotationMatrix().
setTransform()
void drawContext::setTransform (drawTransform * transform) inline
Definition at line 171 of file drawContext.h.
show() [1/2]
void drawContext::show (GModel * m) inline
Definition at line 187 of file drawContext.h.
show() [2/2]
void drawContext::show (PView * v) inline
Definition at line 192 of file drawContext.h.
showAll()
void drawContext::showAll () inline
Definition at line 197 of file drawContext.h.
transform()
void drawContext::transform (double & x, double & y, double & z) inline
Definition at line 173 of file drawContext.h.
Referenced by drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), drawGRegion::operator()(), and setTransform().
transformOneForm()
void drawContext::transformOneForm (double & x, double & y, double & z) inline
Definition at line 177 of file drawContext.h.
Referenced by drawGEdge::operator()().
transformTwoForm()
void drawContext::transformTwoForm (double & x, double & y, double & z) inline
Definition at line 181 of file drawContext.h.
Referenced by drawGFace::operator()().
unproject()
void drawContext::unproject (double winx, double winy, double p[3], double d[3])
Definition at line 827 of file drawContext.cpp.
viewport2World()
void drawContext::viewport2World (double vp[3], double xyz[3])
Definition at line 861 of file drawContext.cpp.
Referenced by drawString(), and drawTics().
world2Viewport()
void drawContext::world2Viewport (double xyz[3], double vp[3])
Definition at line 872 of file drawContext.cpp.
Referenced by drawTics().
Member Data Documentation
_bgImageH
GLuint drawContext::_bgImageH private
Definition at line 128 of file drawContext.h.
Referenced by drawBackgroundImage(), and drawContext().
_bgImageTexture
GLuint drawContext::_bgImageTexture private
Definition at line 128 of file drawContext.h.
Referenced by drawBackgroundImage(), drawContext(), and invalidateBgImageTexture().
_bgImageW
GLuint drawContext::_bgImageW private
Definition at line 128 of file drawContext.h.
Referenced by drawBackgroundImage(), and drawContext().
_displayLists
GLuint drawContext::_displayLists private
Definition at line 125 of file drawContext.h.
Referenced by createQuadricsAndDisplayLists(), drawArrow3d(), drawContext(), drawEllipse(), drawEllipsoid(), drawSphere(), and invalidateQuadricsAndDisplayLists().
_global
drawContextGlobal * drawContext::_global = nullptr static private
Definition at line 122 of file drawContext.h.
Referenced by global(), and setGlobal().
_hiddenModels
std::set<GModel *> drawContext::_hiddenModels private
Definition at line 126 of file drawContext.h.
Referenced by hide(), isVisible(), show(), and showAll().
_hiddenViews
std::set<PView *> drawContext::_hiddenViews private
Definition at line 127 of file drawContext.h.
Referenced by hide(), isVisible(), show(), and showAll().
_imageTextures
std::map<std::string, imgtex> drawContext::_imageTextures private
Definition at line 130 of file drawContext.h.
Referenced by drawImage().
_openglWindow
openglWindow* drawContext::_openglWindow private
Definition at line 129 of file drawContext.h.
Referenced by highResolutionPixelFactor().
_quadric
GLUquadricObj* drawContext::_quadric private
Definition at line 124 of file drawContext.h.
Referenced by createQuadricsAndDisplayLists(), drawContext(), drawCylinder(), drawSphere(), drawTaperedCylinder(), and invalidateQuadricsAndDisplayLists().
_transform
drawTransform* drawContext::_transform private
Definition at line 123 of file drawContext.h.
Referenced by getTransform(), setTransform(), transform(), transformOneForm(), and transformTwoForm().
camera
Camera drawContext::camera
Definition at line 133 of file drawContext.h.
Referenced by addQuaternion(), copyViewAttributes(), draw3d(), drawSmallAxes(), and initProjection().
drawGeomTransient
void(* drawContext::drawGeomTransient)(void *) = nullptr static
Definition at line 294 of file drawContext.h.
Referenced by drawGeom(), and setDrawGeomTransientFunction().
model
double drawContext::model[16]
Definition at line 142 of file drawContext.h.
Referenced by CreateOutputFile(), initPosition(), recenterForRotationCenterChange(), unproject(), viewport2World(), and world2Viewport().
pixel_equiv_x
double drawContext::pixel_equiv_x
Definition at line 141 of file drawContext.h.
Referenced by addGraphPoint(), GMSH_ProbePlugin::draw(), GMSH_AnnotatePlugin::draw(), drawAxes(), drawBox(), drawContext(), drawCylinder(), drawEllipseArray(), drawGraph2d(), drawGraphAxes(), drawImage(), drawNormals(), drawNormalVectorGlyphs(), drawPlaneInBoundingBox(), drawSphere(), drawTangents(), drawTangentVectorGlyphs(), drawTaperedCylinder(), drawVectorArray(), drawVertexLabel(), initProjection(), drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), and drawGRegion::operator()().
pixel_equiv_y
double drawContext::pixel_equiv_y
Definition at line 141 of file drawContext.h.
Referenced by drawContext(), drawImage(), and initProjection().
proj
double drawContext::proj[16]
Definition at line 143 of file drawContext.h.
Referenced by CreateOutputFile(), initPosition(), recenterForRotationCenterChange(), unproject(), viewport2World(), and world2Viewport().
quaternion
double drawContext::quaternion[4]
Definition at line 136 of file drawContext.h.
Referenced by addQuaternion(), addQuaternionFromAxisAndAngle(), buildRotationMatrix(), copyViewAttributes(), drawContext(), setQuaternion(), and setQuaternionFromEulerAngles().
r
double drawContext::r[3]
Definition at line 134 of file drawContext.h.
Referenced by buildRotationMatrix(), copyViewAttributes(), CreateOutputFile(), drawBackgroundGradient(), drawContext(), initRenderModel(), select(), setEulerAnglesFromRotationMatrix(), and setQuaternionFromEulerAngles().
render_mode
int drawContext::render_mode
Definition at line 146 of file drawContext.h.
Referenced by addGraphPoint(), drawArrays(), drawContext(), drawText2d(), initProjection(), drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), drawMeshGVertex::operator()(), drawGRegion::operator()(), drawMeshGEdge::operator()(), drawPView::operator()(), drawMeshGFace::operator()(), drawMeshGRegion::operator()(), and select().
rot
double drawContext::rot[16]
Definition at line 138 of file drawContext.h.
Referenced by buildRotationMatrix(), copyViewAttributes(), drawSmallAxes(), eyeChanged(), initPosition(), and setEulerAnglesFromRotationMatrix().
s
double drawContext::s[3]
Definition at line 135 of file drawContext.h.
Referenced by addGraphPoint(), copyViewAttributes(), GMSH_ProbePlugin::draw(), GMSH_AnnotatePlugin::draw(), drawAxes(), drawBox(), drawContext(), drawCylinder(), drawEllipseArray(), drawEntityLabel(), drawGraph2d(), drawGraphAxes(), drawImage(), drawNormals(), drawNormalVectorGlyphs(), drawPlaneInBoundingBox(), drawSphere(), drawString(), drawStringCenter(), drawStringRight(), drawTangents(), drawTangentVectorGlyphs(), drawTaperedCylinder(), drawVectorArray(), drawVertexLabel(), initPosition(), initProjection(), initRenderModel(), drawGEdge::operator()(), drawGFace::operator()(), mousePosition::recenter(), recenterForRotationCenterChange(), and mousePosition::set().
t
double drawContext::t[3]
Definition at line 135 of file drawContext.h.
Referenced by copyViewAttributes(), drawContext(), initPosition(), initRenderModel(), mousePosition::recenter(), recenterForRotationCenterChange(), and mousePosition::set().
t_init
double drawContext::t_init[3]
Definition at line 139 of file drawContext.h.
Referenced by copyViewAttributes(), initProjection(), recenterForRotationCenterChange(), and mousePosition::set().
viewport
int drawContext::viewport[4]
Definition at line 137 of file drawContext.h.
Referenced by GMSH_AnnotatePlugin::draw(), draw2d(), drawBackgroundGradient(), drawBackgroundImage(), drawContext(), drawGraph2d(), drawImage(), drawScales(), fix2dCoordinates(), initProjection(), recenterForRotationCenterChange(), select(), mousePosition::set(), viewport2World(), and world2Viewport().
vxmax
double drawContext::vxmax
Definition at line 140 of file drawContext.h.
Referenced by drawContext(), initProjection(), recenterForRotationCenterChange(), and mousePosition::set().
vxmin
double drawContext::vxmin
Definition at line 140 of file drawContext.h.
Referenced by drawContext(), initProjection(), recenterForRotationCenterChange(), and mousePosition::set().
vymax
double drawContext::vymax
Definition at line 140 of file drawContext.h.
Referenced by drawContext(), initProjection(), recenterForRotationCenterChange(), and mousePosition::set().
vymin
double drawContext::vymin
Definition at line 140 of file drawContext.h.
Referenced by drawContext(), initProjection(), recenterForRotationCenterChange(), and mousePosition::set().
The documentation for this class was generated from the following files:
src/graphics/drawContext.h
src/graphics/drawAxes.cpp
src/graphics/drawContext.cpp
src/graphics/drawGeom.cpp
src/graphics/drawGlyph.cpp
src/graphics/drawGraph2d.cpp
src/graphics/drawMesh.cpp
src/graphics/drawPost.cpp
src/graphics/drawScales.cpp