gmsh-TingyuanDoc: VertexArray Class Reference
VertexArray Class Reference
#include <VertexArray.h>
Public Member Functions
VertexArray (int numVerticesPerElement, int numElements)
~VertexArray ()
int getNumVertices ()
int getNumVerticesPerElement ()
int getNumElementPointers ()
float * getVertexArray (int i=0)
std::vector< float >::iterator firstVertex ()
std::vector< float >::iterator lastVertex ()
normal_type * getNormalArray (int i=0)
std::vector< normal_type >::iterator firstNormal ()
std::vector< normal_type >::iterator lastNormal ()
unsigned char * getColorArray (int i=0)
std::vector< unsigned char >::iterator firstColor ()
std::vector< unsigned char >::iterator lastColor ()
MElement ** getElementPointerArray (int i=0)
std::vector< MElement * >::iterator firstElementPointer ()
std::vector< MElement * >::iterator lastElementPointer ()
void add (double *x, double *y, double *z, SVector3 *n, unsigned int *col, MElement *ele=nullptr, bool unique=true, bool boundary=false)
void add (double *x, double *y, double *z, SVector3 *n, unsigned char *r=nullptr, unsigned char *g=nullptr, unsigned char *b=nullptr, unsigned char *a=nullptr, MElement *ele=nullptr, bool unique=true, bool boundary=false)
void finalize ()
void sort (double x, double y, double z)
double getMemoryInMb ()
char * toChar (int num, const std::string &name, int type, double min, double max, int numsteps, double time, const SBoundingBox3d &bbox, int &len)
void fromChar (int length, const char *bytes, int swap)
void merge (VertexArray *va)
Static Public Member Functions
static int decodeHeader (int length, const char *bytes, int swap, std::string &name, int &tag, int &type, double &min, double &max, int &numSteps, double &time, double &xmin, double &ymin, double &zmin, double &xmax, double &ymax, double &zmax)
Private Member Functions
void _addVertex (float x, float y, float z)
void _addNormal (float nx, float ny, float nz)
void _addColor (unsigned char r, unsigned char g, unsigned char b, unsigned char a)
void _addElement (MElement *ele)
Private Attributes
int _numVerticesPerElement
std::vector< float > _vertices
std::vector< normal_type > _normals
std::vector< unsigned char > _colors
std::vector< MElement * > _elements
std::set< ElementData< 3 >, ElementDataLessThan< 3 > > _data3
std::set< Barycenter, BarycenterLessThan > _barycenters
Detailed Description
Definition at line 151 of file VertexArray.h.
Constructor & Destructor Documentation
VertexArray()
VertexArray::VertexArray (int numVerticesPerElement, int numElements)
Definition at line 17 of file VertexArray.cpp.
~VertexArray()
VertexArray::~VertexArray () inline
Definition at line 172 of file VertexArray.h.
Member Function Documentation
_addColor()
void VertexArray::_addColor (unsigned char r, unsigned char g, unsigned char b, unsigned char a) private
Definition at line 67 of file VertexArray.cpp.
Referenced by add(), and finalize().
_addElement()
void VertexArray::_addElement (MElement * ele) private
Definition at line 76 of file VertexArray.cpp.
Referenced by add(), and finalize().
_addNormal()
void VertexArray::_addNormal (float nx, float ny, float nz) private
Definition at line 49 of file VertexArray.cpp.
Referenced by add(), and finalize().
_addVertex()
void VertexArray::_addVertex (float x, float y, float z) private
Definition at line 42 of file VertexArray.cpp.
Referenced by add(), and finalize().
add() [1/2]
void VertexArray::add (double * x, double * y, double * z, SVector3 * n, unsigned char * r = nullptr, unsigned char * g = nullptr, unsigned char * b = nullptr, unsigned char * a = nullptr, MElement * ele = nullptr, bool unique = true, bool boundary = false)
Definition at line 99 of file VertexArray.cpp.
add() [2/2]
void VertexArray::add (double * x, double * y, double * z, SVector3 * n, unsigned int * col, MElement * ele = nullptr, bool unique = true, bool boundary = false)
Definition at line 81 of file VertexArray.cpp.
Referenced by addElementsInArrays(), addOutlineLine(), addOutlinePoint(), addOutlineQuadrangle(), addOutlineTriangle(), addScalarLine(), addScalarPoint(), addScalarTetrahedron(), addScalarTriangle(), addTensorElement(), addTriangle(), addVectorElement(), and GFace::fillVertexArray().
decodeHeader()
int VertexArray::decodeHeader (int length, const char * bytes, int swap, std::string & name, int & tag, int & type, double & min, double & max, int & numSteps, double & time, double & xmin, double & ymin, double & zmin, double & xmax, double & ymax, double & zmax) static
Definition at line 273 of file VertexArray.cpp.
Referenced by PView::fillVertexArray(), and fromChar().
finalize()
void VertexArray::finalize ()
Definition at line 138 of file VertexArray.cpp.
Referenced by GFace::fillVertexArray(), initMeshGEdge::operator()(), initMeshGRegion::operator()(), and initPView::operator()().
firstColor()
std::vector<unsigned char>::iterator VertexArray::firstColor () inline
Definition at line 193 of file VertexArray.h.
Referenced by merge().
firstElementPointer()
std::vector<MElement *>::iterator VertexArray::firstElementPointer () inline
Definition at line 198 of file VertexArray.h.
Referenced by merge().
firstNormal()
std::vector<normal_type>::iterator VertexArray::firstNormal () inline
Definition at line 188 of file VertexArray.h.
Referenced by merge().
firstVertex()
std::vector<float>::iterator VertexArray::firstVertex () inline
Definition at line 183 of file VertexArray.h.
Referenced by merge().
fromChar()
void VertexArray::fromChar (int length, const char * bytes, int swap)
Definition at line 313 of file VertexArray.cpp.
Referenced by PView::fillVertexArray().
getColorArray()
unsigned char* VertexArray::getColorArray (int i = 0) inline
Definition at line 192 of file VertexArray.h.
Referenced by drawGFace::_drawVertexArray(), drawArrays(), drawEllipseArray(), drawVectorArray(), and PView::writeX3D().
getElementPointerArray()
MElement** VertexArray::getElementPointerArray (int i = 0) inline
Definition at line 197 of file VertexArray.h.
Referenced by getElement().
getMemoryInMb()
double VertexArray::getMemoryInMb ()
Definition at line 34 of file VertexArray.cpp.
Referenced by PView::getMemoryInMb(), and initPView::operator()().
getNormalArray()
normal_type* VertexArray::getNormalArray (int i = 0) inline
Definition at line 187 of file VertexArray.h.
Referenced by drawGFace::_drawVertexArray(), and drawArrays().
getNumElementPointers()
int VertexArray::getNumElementPointers () inline
Definition at line 178 of file VertexArray.h.
Referenced by drawArrays(), and getElement().
getNumVertices()
int VertexArray::getNumVertices () inline
Definition at line 174 of file VertexArray.h.
Referenced by drawGFace::_drawVertexArray(), drawArrays(), drawEllipseArray(), drawVectorArray(), merge(), drawPView::operator()(), initPView::operator()(), sort(), and PView::writeX3D().
getNumVerticesPerElement()
int VertexArray::getNumVerticesPerElement () inline
Definition at line 176 of file VertexArray.h.
Referenced by add(), drawArrays(), drawEllipseArray(), drawVectorArray(), and sort().
getVertexArray()
float* VertexArray::getVertexArray (int i = 0) inline
Definition at line 182 of file VertexArray.h.
Referenced by drawGFace::_drawVertexArray(), drawArrays(), drawEllipseArray(), drawVectorArray(), and PView::writeX3D().
lastColor()
std::vector<unsigned char>::iterator VertexArray::lastColor () inline
Definition at line 194 of file VertexArray.h.
Referenced by merge().
lastElementPointer()
std::vector<MElement *>::iterator VertexArray::lastElementPointer () inline
Definition at line 202 of file VertexArray.h.
Referenced by merge().
lastNormal()
std::vector<normal_type>::iterator VertexArray::lastNormal () inline
Definition at line 189 of file VertexArray.h.
Referenced by merge().
lastVertex()
std::vector<float>::iterator VertexArray::lastVertex () inline
Definition at line 184 of file VertexArray.h.
Referenced by merge().
merge()
void VertexArray::merge (VertexArray * va)
Definition at line 343 of file VertexArray.cpp.
sort()
void VertexArray::sort (double x, double y, double z)
Definition at line 185 of file VertexArray.cpp.
Referenced by drawPView::operator()().
toChar()
char * VertexArray::toChar (int num, const std::string & name, int type, double min, double max, int numsteps, double time, const SBoundingBox3d & bbox, int & len)
Definition at line 234 of file VertexArray.cpp.
Member Data Documentation
_barycenters
std::set<Barycenter, BarycenterLessThan> VertexArray::_barycenters private
Definition at line 159 of file VertexArray.h.
Referenced by add(), and finalize().
_colors
std::vector<unsigned char> VertexArray::_colors private
Definition at line 156 of file VertexArray.h.
Referenced by _addColor(), firstColor(), fromChar(), getColorArray(), getMemoryInMb(), lastColor(), merge(), sort(), toChar(), and VertexArray().
_data3
std::set<ElementData<3>, ElementDataLessThan<3> > VertexArray::_data3 private
Definition at line 158 of file VertexArray.h.
Referenced by add(), and finalize().
_elements
std::vector<MElement *> VertexArray::_elements private
Definition at line 157 of file VertexArray.h.
Referenced by _addElement(), firstElementPointer(), getElementPointerArray(), getNumElementPointers(), lastElementPointer(), and merge().
_normals
std::vector<normal_type> VertexArray::_normals private
Definition at line 155 of file VertexArray.h.
Referenced by _addNormal(), firstNormal(), fromChar(), getMemoryInMb(), getNormalArray(), lastNormal(), merge(), sort(), toChar(), and VertexArray().
_numVerticesPerElement
int VertexArray::_numVerticesPerElement private
Definition at line 153 of file VertexArray.h.
Referenced by getNumVerticesPerElement(), and VertexArray().
_vertices
std::vector<float> VertexArray::_vertices private
Definition at line 154 of file VertexArray.h.
Referenced by _addVertex(), firstVertex(), fromChar(), getMemoryInMb(), getNumVertices(), getVertexArray(), lastVertex(), merge(), sort(), toChar(), and VertexArray().
The documentation for this class was generated from the following files:
src/common/VertexArray.h
src/common/VertexArray.cpp