gmsh-TingyuanDoc: drawTransform Class Reference
drawTransform Class Reference
#include <drawContext.h>
Public Member Functions
drawTransform ()
virtual ~drawTransform ()
virtual void transform (double &x, double &y, double &z)
virtual void transformOneForm (double &x, double &y, double &z)
virtual void transformTwoForm (double &x, double &y, double &z)
virtual void setMatrix (double mat[3][3], double tra[3])
Detailed Description
Definition at line 46 of file drawContext.h.
Constructor & Destructor Documentation
drawTransform()
drawTransform::drawTransform () inline
Definition at line 48 of file drawContext.h.
~drawTransform()
virtual drawTransform::~drawTransform () inline virtual
Definition at line 49 of file drawContext.h.
Member Function Documentation
setMatrix()
virtual void drawTransform::setMatrix (double mat[3][3], double tra[3]) inline virtual
Reimplemented in drawTransformScaled.
Definition at line 53 of file drawContext.h.
Referenced by _opt_geometry_offset(), and _opt_geometry_transform().
transform()
virtual void drawTransform::transform (double & x, double & y, double & z) inline virtual
Reimplemented in drawTransformScaled.
Definition at line 50 of file drawContext.h.
Referenced by drawContext::transform().
transformOneForm()
virtual void drawTransform::transformOneForm (double & x, double & y, double & z) inline virtual
Definition at line 51 of file drawContext.h.
Referenced by drawContext::transformOneForm().
transformTwoForm()
virtual void drawTransform::transformTwoForm (double & x, double & y, double & z) inline virtual
Definition at line 52 of file drawContext.h.
Referenced by drawContext::transformTwoForm().
The documentation for this class was generated from the following file:
src/graphics/drawContext.h