gmsh-TingyuanDoc: Cell Class Reference
Cell Class Reference
#include <Cell.h>
Public Types
typedef std::map< Cell *, BdInfo, CellPtrLessThan >::iterator biter
typedef std::map< Cell *, int, CellPtrLessThan >::iterator citer
Public Member Functions
Cell (MElement *element, int domain)
Cell (Cell *parent, int i)
virtual ~Cell ()
int getDomain () const
void setDomain (int domain)
int getNum () const
void setNum (int num)
int getTypeMSH () const
virtual int getDim () const
bool inSubdomain () const
void getMeshVertices (std::vector< MVertex * > &v) const
void setImmune (bool immune)
bool getImmune () const
int getNumSortedVertices () const
int getSortedVertex (int vertex) const
int getNumVertices () const
MVertex * getMeshVertex (int vertex) const
void findBdElement (int i, std::vector< MVertex * > &vertices) const
int getNumBdElements () const
int findBdCellOrientation (Cell *cell, int i) const
void increaseGlobalNum ()
void saveCellBoundary ()
void restoreCellBoundary ()
virtual bool hasVertex (int vertex) const
biter firstBoundary (bool orig=false)
biter lastBoundary ()
biter firstCoboundary (bool orig=false)
biter lastCoboundary ()
int getBoundarySize (bool orig=false)
int getCoboundarySize (bool orig=false)
void getBoundary (std::map< Cell *, short int, CellPtrLessThan > &boundary, bool orig=false)
void getCoboundary (std::map< Cell *, short int, CellPtrLessThan > &coboundary, bool orig=false)
void addBoundaryCell (int orientation, Cell *cell, bool other)
void addCoboundaryCell (int orientation, Cell *cell, bool other)
void removeBoundaryCell (Cell *cell, bool other)
void removeCoboundaryCell (Cell *cell, bool other)
bool hasBoundary (Cell *cell, bool orig=false)
bool hasCoboundary (Cell *cell, bool orig=false)
virtual void printCell ()
virtual void printBoundary ()
virtual void printCoboundary ()
bool isCombined () const
virtual void getCells (std::map< Cell *, int, CellPtrLessThan > &cells)
virtual int getNumCells () const
bool operator== (const Cell &c2) const
Static Public Member Functions
static std::pair< Cell *, bool > createCell (MElement *element, int domain)
static std::pair< Cell *, bool > createCell (Cell *parent, int i)
Protected Member Functions
Cell ()
Protected Attributes
int _num
char _domain
bool _combined
bool _immune
std::map< Cell *, BdInfo, CellPtrLessThan > _bd
std::map< Cell *, BdInfo, CellPtrLessThan > _cbd
Static Protected Attributes
static int _globalNum = 0
Private Member Functions
bool _sortVertexIndices ()
Private Attributes
char _dim
std::vector< MVertex * > _v
std::vector< char > _si
Detailed Description
Definition at line 42 of file Cell.h.
Member Typedef Documentation
biter
typedef std::map<Cell *, BdInfo, CellPtrLessThan>::iterator Cell::biter
Definition at line 108 of file Cell.h.
citer
typedef std::map<Cell *, int, CellPtrLessThan>::iterator Cell::citer
Definition at line 149 of file Cell.h.
Constructor & Destructor Documentation
Cell() [1/3]
Cell::Cell () inline protected
Definition at line 58 of file Cell.h.
Referenced by createCell().
Cell() [2/3]
Cell::Cell (MElement * element, int domain)
Definition at line 73 of file Cell.cpp.
Cell() [3/3]
Cell::Cell (Cell * parent, int i)
Definition at line 87 of file Cell.cpp.
~Cell()
virtual Cell::~Cell () inline virtual
Definition at line 75 of file Cell.h.
Member Function Documentation
_sortVertexIndices()
bool Cell::_sortVertexIndices () inline private
Definition at line 99 of file Cell.cpp.
Referenced by Cell(), and createCell().
addBoundaryCell()
void Cell::addBoundaryCell (int orientation, Cell * cell, bool other)
Definition at line 543 of file Cell.cpp.
Referenced by CellComplex::_insertCells(), addCoboundaryCell(), CellComplex::coherent(), and CombinedCell::CombinedCell().
addCoboundaryCell()
void Cell::addCoboundaryCell (int orientation, Cell * cell, bool other)
Definition at line 560 of file Cell.cpp.
Referenced by addBoundaryCell(), CellComplex::coherent(), and CombinedCell::CombinedCell().
createCell() [1/2]
std::pair< Cell *, bool > Cell::createCell (Cell * parent, int i) static
Definition at line 60 of file Cell.cpp.
createCell() [2/2]
std::pair< Cell *, bool > Cell::createCell (MElement * element, int domain) static
Definition at line 45 of file Cell.cpp.
Referenced by CellComplex::_insertCells().
findBdCellOrientation()
int Cell::findBdCellOrientation (Cell * cell, int i) const
Definition at line 194 of file Cell.cpp.
Referenced by CellComplex::_insertCells().
findBdElement()
void Cell::findBdElement (int i, std::vector< MVertex * > & vertices) const
Definition at line 122 of file Cell.cpp.
Referenced by Cell(), and createCell().
firstBoundary()
Cell::biter Cell::firstBoundary (bool orig = false)
Definition at line 625 of file Cell.cpp.
Referenced by CellComplex::cocombine(), CombinedCell::CombinedCell(), CellComplex::coreduction(), getBoundary(), printBoundary(), restoreCellBoundary(), and saveCellBoundary().
firstCoboundary()
Cell::biter Cell::firstCoboundary (bool orig = false)
Definition at line 637 of file Cell.cpp.
Referenced by CellComplex::combine(), CombinedCell::CombinedCell(), getCoboundary(), printCoboundary(), CellComplex::reduction(), restoreCellBoundary(), and saveCellBoundary().
getBoundary()
void Cell::getBoundary (std::map< Cell *, short int, CellPtrLessThan > & boundary, bool orig = false)
Definition at line 673 of file Cell.cpp.
Referenced by CellComplex::coherent(), CellComplex::combine(), CellComplex::coreduction(), and CellComplex::removeCell().
getBoundarySize()
int Cell::getBoundarySize (bool orig = false)
Definition at line 649 of file Cell.cpp.
Referenced by CellComplex::cocombine(), and CellComplex::coreduction().
getCells()
virtual void Cell::getCells (std::map< Cell *, int, CellPtrLessThan > & cells) inline virtual
Reimplemented in CombinedCell.
Definition at line 150 of file Cell.h.
Referenced by CombinedCell::CombinedCell().
getCoboundary()
void Cell::getCoboundary (std::map< Cell *, short int, CellPtrLessThan > & coboundary, bool orig = false)
Definition at line 684 of file Cell.cpp.
Referenced by CellComplex::cocombine(), CellComplex::coherent(), CellComplex::coreduction(), and CellComplex::removeCell().
getCoboundarySize()
int Cell::getCoboundarySize (bool orig = false)
Definition at line 661 of file Cell.cpp.
Referenced by CellComplex::combine(), and CellComplex::reduction().
getDim()
virtual int Cell::getDim () const inline virtual
Reimplemented in CombinedCell.
Definition at line 82 of file Cell.h.
Referenced by CellComplex::_immunizeCells(), CellComplex::_insertCells(), CellComplex::_omitCell(), CellComplex::_removeCells(), Cell(), CellComplex::coherent(), createCell(), CellComplex::hasCell(), CellComplex::insertCell(), printCell(), and CellComplex::removeCell().
getDomain()
int Cell::getDomain () const inline
Definition at line 77 of file Cell.h.
Referenced by Cell(), createCell(), and CellComplex::inSameDomain().
getImmune()
bool Cell::getImmune () const inline
Definition at line 87 of file Cell.h.
Referenced by CellComplex::cocombine(), CellComplex::combine(), CombinedCell::CombinedCell(), CellComplex::coreduction(), and CellComplex::reduction().
getMeshVertex()
MVertex* Cell::getMeshVertex (int vertex) const inline
Definition at line 92 of file Cell.h.
Referenced by printCell().
getMeshVertices()
void Cell::getMeshVertices (std::vector< MVertex * > & v) const inline
Definition at line 84 of file Cell.h.
Referenced by findBdCellOrientation().
getNum()
int Cell::getNum () const inline
Definition at line 79 of file Cell.h.
Referenced by findBdCellOrientation(), getSortedVertex(), hasVertex(), CellPtrLessThan::operator()(), operator==(), CombinedCell::operator==(), and printCell().
getNumBdElements()
int Cell::getNumBdElements () const
Definition at line 171 of file Cell.cpp.
Referenced by CellComplex::_insertCells(), and CellComplex::_removeCells().
getNumCells()
virtual int Cell::getNumCells () const inline virtual
Reimplemented in CombinedCell.
Definition at line 155 of file Cell.h.
Referenced by CombinedCell::CombinedCell().
getNumSortedVertices()
int Cell::getNumSortedVertices () const inline
Definition at line 89 of file Cell.h.
Referenced by CellPtrLessThan::operator()().
getNumVertices()
int Cell::getNumVertices () const inline
Definition at line 91 of file Cell.h.
Referenced by findBdCellOrientation(), findBdElement(), getNumBdElements(), getTypeMSH(), and printCell().
getSortedVertex()
int Cell::getSortedVertex (int vertex) const inline
Definition at line 117 of file Cell.cpp.
Referenced by CellPtrLessThan::operator()().
getTypeMSH()
int Cell::getTypeMSH () const
Definition at line 462 of file Cell.cpp.
hasBoundary()
bool Cell::hasBoundary (Cell * cell, bool orig = false)
Definition at line 597 of file Cell.cpp.
Referenced by CellComplex::coherent().
hasCoboundary()
bool Cell::hasCoboundary (Cell * cell, bool orig = false)
Definition at line 611 of file Cell.cpp.
Referenced by CellComplex::coherent().
hasVertex()
bool Cell::hasVertex (int vertex) const virtual
Reimplemented in CombinedCell.
Definition at line 485 of file Cell.cpp.
increaseGlobalNum()
void Cell::increaseGlobalNum () inline
Definition at line 98 of file Cell.h.
Referenced by CellComplex::CellComplex().
inSubdomain()
bool Cell::inSubdomain () const inline
Definition at line 83 of file Cell.h.
Referenced by CellComplex::getACell(), CellComplex::getCells(), CellComplex::getDomain(), printCell(), CellComplex::removeCell(), CellComplex::removeSubdomain(), and CellComplex::restoreComplex().
isCombined()
bool Cell::isCombined () const inline
Definition at line 147 of file Cell.h.
Referenced by CellComplex::cocombine(), CellComplex::combine(), printCell(), and CellComplex::restoreComplex().
lastBoundary()
Cell::biter Cell::lastBoundary ()
Definition at line 635 of file Cell.cpp.
Referenced by CombinedCell::CombinedCell(), getBoundary(), printBoundary(), restoreCellBoundary(), and saveCellBoundary().
lastCoboundary()
Cell::biter Cell::lastCoboundary ()
Definition at line 647 of file Cell.cpp.
Referenced by CombinedCell::CombinedCell(), getCoboundary(), printCoboundary(), restoreCellBoundary(), and saveCellBoundary().
operator==()
bool Cell::operator== (const Cell & c2) const inline
Definition at line 157 of file Cell.h.
printBoundary()
void Cell::printBoundary () virtual
Definition at line 695 of file Cell.cpp.
Referenced by CellComplex::printComplex().
printCell()
void Cell::printCell () virtual
Definition at line 506 of file Cell.cpp.
Referenced by CellComplex::insertCell(), printBoundary(), printCoboundary(), and CellComplex::printComplex().
printCoboundary()
void Cell::printCoboundary () virtual
Definition at line 707 of file Cell.cpp.
Referenced by CellComplex::printComplex().
removeBoundaryCell()
void Cell::removeBoundaryCell (Cell * cell, bool other)
Definition at line 577 of file Cell.cpp.
Referenced by CellComplex::coherent(), CombinedCell::CombinedCell(), and CellComplex::removeCell().
removeCoboundaryCell()
void Cell::removeCoboundaryCell (Cell * cell, bool other)
Definition at line 587 of file Cell.cpp.
Referenced by CellComplex::coherent(), CombinedCell::CombinedCell(), and CellComplex::removeCell().
restoreCellBoundary()
void Cell::restoreCellBoundary ()
Definition at line 527 of file Cell.cpp.
Referenced by CellComplex::restoreComplex().
saveCellBoundary()
void Cell::saveCellBoundary ()
Definition at line 517 of file Cell.cpp.
Referenced by CellComplex::CellComplex().
setDomain()
void Cell::setDomain (int domain) inline
Definition at line 78 of file Cell.h.
Referenced by CellComplex::_insertCells().
setImmune()
void Cell::setImmune (bool immune) inline
Definition at line 86 of file Cell.h.
setNum()
void Cell::setNum (int num) inline
Definition at line 80 of file Cell.h.
Referenced by CellComplex::CellComplex().
Member Data Documentation
_bd
std::map<Cell *, BdInfo, CellPtrLessThan> Cell::_bd protected
Definition at line 55 of file Cell.h.
Referenced by addBoundaryCell(), firstBoundary(), getBoundarySize(), hasBoundary(), lastBoundary(), removeBoundaryCell(), and restoreCellBoundary().
_cbd
std::map<Cell *, BdInfo, CellPtrLessThan> Cell::_cbd protected
Definition at line 56 of file Cell.h.
Referenced by addCoboundaryCell(), firstCoboundary(), getCoboundarySize(), hasCoboundary(), lastCoboundary(), removeCoboundaryCell(), and restoreCellBoundary().
_combined
bool Cell::_combined protected
Definition at line 50 of file Cell.h.
Referenced by Cell(), CombinedCell::CombinedCell(), createCell(), and isCombined().
_dim
char Cell::_dim private
Definition at line 61 of file Cell.h.
Referenced by Cell(), createCell(), findBdCellOrientation(), findBdElement(), getDim(), getNumBdElements(), and getTypeMSH().
_domain
char Cell::_domain protected
Definition at line 47 of file Cell.h.
Referenced by Cell(), CombinedCell::CombinedCell(), createCell(), getDomain(), inSubdomain(), and setDomain().
_globalNum
int Cell::_globalNum = 0 static protected
Definition at line 44 of file Cell.h.
Referenced by CombinedCell::CombinedCell(), and increaseGlobalNum().
_immune
bool Cell::_immune protected
Definition at line 52 of file Cell.h.
Referenced by Cell(), CombinedCell::CombinedCell(), createCell(), getImmune(), and setImmune().
_num
int Cell::_num protected
Definition at line 46 of file Cell.h.
Referenced by Cell(), CombinedCell::CombinedCell(), createCell(), getNum(), and setNum().
_si
std::vector<char> Cell::_si private
Definition at line 64 of file Cell.h.
Referenced by _sortVertexIndices(), getNumSortedVertices(), getSortedVertex(), and hasVertex().
_v
std::vector<MVertex *> Cell::_v private
Definition at line 62 of file Cell.h.
Referenced by _sortVertexIndices(), Cell(), createCell(), findBdCellOrientation(), findBdElement(), getMeshVertex(), getMeshVertices(), getNumVertices(), getSortedVertex(), and hasVertex().
The documentation for this class was generated from the following files:
src/geo/Cell.h
src/geo/Cell.cpp