gmsh-TingyuanDoc: GEdgeLoop Class Reference
GEdgeLoop Class Reference
#include <GEdgeLoop.h>
Public Types
typedef std::list< GEdgeSigned >::iterator iter
typedef std::list< GEdgeSigned >::const_iterator citer
Public Member Functions
GEdgeLoop ()
GEdgeLoop (const std::vector< GEdge * > &wire)
bool check ()
void add (int ori, GEdge *ge)
void recompute (const std::vector< GEdge * > &wire)
iter begin ()
iter end ()
citer begin () const
citer end () const
void erase (iter it)
int count (GEdge *) const
int count () const
void print () const
void getEdges (std::vector< GEdge * > &edges) const
void getSigns (std::vector< int > &signs) const
void reverse ()
Private Attributes
std::list< GEdgeSigned > loop
Detailed Description
Definition at line 36 of file GEdgeLoop.h.
Member Typedef Documentation
citer
typedef std::list<GEdgeSigned>::const_iterator GEdgeLoop::citer
Definition at line 42 of file GEdgeLoop.h.
iter
typedef std::list<GEdgeSigned>::iterator GEdgeLoop::iter
Definition at line 41 of file GEdgeLoop.h.
Constructor & Destructor Documentation
GEdgeLoop() [1/2]
GEdgeLoop::GEdgeLoop () inline
Definition at line 43 of file GEdgeLoop.h.
GEdgeLoop() [2/2]
GEdgeLoop::GEdgeLoop (const std::vector< GEdge * > & wire)
Definition at line 171 of file GEdgeLoop.cpp.
Member Function Documentation
add()
void GEdgeLoop::add (int ori, GEdge * ge) inline
Definition at line 46 of file GEdgeLoop.h.
begin() [1/2]
iter GEdgeLoop::begin () inline
Definition at line 48 of file GEdgeLoop.h.
Referenced by buildConsecutiveListOfVertices(), check(), count(), findTransfiniteCorners(), getEdges(), getSigns(), and print().
begin() [2/2]
citer GEdgeLoop::begin () const inline
Definition at line 50 of file GEdgeLoop.h.
check()
bool GEdgeLoop::check ()
Definition at line 176 of file GEdgeLoop.cpp.
count() [1/2]
int GEdgeLoop::count () const inline
Definition at line 54 of file GEdgeLoop.h.
Referenced by count().
count() [2/2]
int GEdgeLoop::count (GEdge * ge) const
Definition at line 86 of file GEdgeLoop.cpp.
end() [1/2]
iter GEdgeLoop::end () inline
Definition at line 49 of file GEdgeLoop.h.
Referenced by buildConsecutiveListOfVertices(), check(), count(), findTransfiniteCorners(), getEdges(), getSigns(), and print().
end() [2/2]
citer GEdgeLoop::end () const inline
Definition at line 51 of file GEdgeLoop.h.
erase()
void GEdgeLoop::erase (iter it) inline
Definition at line 52 of file GEdgeLoop.h.
getEdges()
void GEdgeLoop::getEdges (std::vector< GEdge * > & edges) const
Definition at line 100 of file GEdgeLoop.cpp.
Referenced by GFace::setBoundEdges().
getSigns()
void GEdgeLoop::getSigns (std::vector< int > & signs) const
Definition at line 106 of file GEdgeLoop.cpp.
Referenced by GFace::setBoundEdges().
print()
void GEdgeLoop::print () const
Definition at line 95 of file GEdgeLoop.cpp.
recompute()
void GEdgeLoop::recompute (const std::vector< GEdge * > & wire)
Definition at line 137 of file GEdgeLoop.cpp.
Referenced by GEdgeLoop().
reverse()
void GEdgeLoop::reverse ()
Definition at line 189 of file GEdgeLoop.cpp.
Member Data Documentation
loop
std::list<GEdgeSigned> GEdgeLoop::loop private
Definition at line 38 of file GEdgeLoop.h.
Referenced by add(), begin(), check(), count(), end(), erase(), recompute(), and reverse().
The documentation for this class was generated from the following files:
src/geo/GEdgeLoop.h
src/geo/GEdgeLoop.cpp