gmsh-TingyuanDoc: simpleFunction< scalar > Class Template Reference
simpleFunction< scalar > Class Template Reference
#include <GModel.h>
Public Member Functions
simpleFunction (scalar val=0.0)
virtual ~simpleFunction ()
virtual bool hasDerivatives ()
virtual scalar operator() (double x, double y, double z) const
virtual void setElement (MElement *e) const
virtual void gradient (double x, double y, double z, scalar &dfdx, scalar &dfdy, scalar &dfdz) const
virtual void hessian (double x, double y, double z, scalar &dfdxx, scalar &dfdxy, scalar &dfdxz, scalar &dfdyx, scalar &dfdyy, scalar &dfdyz, scalar &dfdzx, scalar &dfdzy, scalar &dfdzz) const
Protected Attributes
scalar _val
bool _hasDerivatives
Detailed Description
template<class scalar>
class simpleFunction< scalar >
Definition at line 30 of file GModel.h.
Constructor & Destructor Documentation
simpleFunction()
template<class scalar > simpleFunction< scalar >::simpleFunction (scalar val = 0.0) inline
Definition at line 20 of file simpleFunction.h.
~simpleFunction()
template<class scalar > virtual simpleFunction< scalar >::~simpleFunction () inline virtual
Definition at line 21 of file simpleFunction.h.
Member Function Documentation
gradient()
template<class scalar > virtual void simpleFunction< scalar >::gradient (double x, double y, double z, scalar & dfdx, scalar & dfdy, scalar & dfdz) const inline virtual
Reimplemented in gLevelsetNACA00, gLevelsetMathEvalAll, gLevelsetSphere, FuncGradDisc, and FuncHeaviside.
Definition at line 25 of file simpleFunction.h.
Referenced by meshMetric::computeMetricEigenDir(), meshMetric::computeMetricFrey(), meshMetric::computeMetricHessian(), meshMetric::computeMetricIsoLinInterp(), meshMetric::computeMetricLevelSet(), and SElement::gradNodalFunctions().
hasDerivatives()
template<class scalar > virtual bool simpleFunction< scalar >::hasDerivatives () inline virtual
Definition at line 22 of file simpleFunction.h.
Referenced by meshMetric::addMetric(), and meshMetric::operator()().
hessian()
template<class scalar > virtual void simpleFunction< scalar >::hessian (double x, double y, double z, scalar & dfdxx, scalar & dfdxy, scalar & dfdxz, scalar & dfdyx, scalar & dfdyy, scalar & dfdyz, scalar & dfdzx, scalar & dfdzy, scalar & dfdzz) const inline virtual
Reimplemented in gLevelsetNACA00, gLevelsetMathEvalAll, and gLevelsetSphere.
Definition at line 30 of file simpleFunction.h.
Referenced by meshMetric::computeMetricEigenDir(), meshMetric::computeMetricFrey(), meshMetric::computeMetricHessian(), meshMetric::computeMetricIsoLinInterp(), and meshMetric::computeMetricLevelSet().
operator()()
template<class scalar > virtual scalar simpleFunction< scalar >::operator() (double x, double y, double z) const inline virtual
Reimplemented in gLevelsetPrimitive, gLevelsetImproved, gLevelsetReverse, gLevelsetTools, gLevelsetYarn, gLevelsetNACA00, gLevelsetSimpleFunction, gLevelsetMathEvalAll, gLevelsetMathEval, gLevelsetShamrock, gLevelsetPopcorn, gLevelsetQuadric, gLevelsetPoints, gLevelsetPlane, gLevelsetSphere, gLevelset, constantPerElement< scalar >, FuncGradDisc, FuncHeaviside, simpleFunctionPython, PViewEvaluator, and backgroundMesh.
Definition at line 23 of file simpleFunction.h.
setElement()
template<class scalar > virtual void simpleFunction< scalar >::setElement (MElement * e) const inline virtual
Reimplemented in simpleFunctionOnElement< scalar >, simpleFunctionOnElement< double >, and constantPerElement< scalar >.
Definition at line 24 of file simpleFunction.h.
Member Data Documentation
_hasDerivatives
template<class scalar > bool simpleFunction< scalar >::_hasDerivatives protected
Definition at line 17 of file simpleFunction.h.
Referenced by simpleFunction< SVector3 >::hasDerivatives().
_val
template<class scalar > scalar simpleFunction< scalar >::_val protected
Definition at line 16 of file simpleFunction.h.
Referenced by simpleFunction< SVector3 >::operator()().
The documentation for this class was generated from the following files:
src/geo/GModel.h
src/numeric/simpleFunction.h