gmsh-TingyuanDoc: linearSystemCSRGmm< scalar > Class Template Reference
linearSystemCSRGmm< scalar > Class Template Reference
#include <linearSystemCSR.h>
Public Member Functions
linearSystemCSRGmm (const std::string &method="gmres", double tol=1e-8, int noisy=0)
virtual ~linearSystemCSRGmm ()
void setPrec (double p)
void setNoisy (int n)
void setGmres (int n)
virtual int systemSolve ()
Public Member Functions inherited from linearSystemCSR< scalar >
int getNNZ ()
int getNbUnk ()
linearSystemCSR ()
virtual bool isAllocated () const
virtual void allocate (int)
virtual void clear ()
virtual ~linearSystemCSR ()
virtual void insertInSparsityPattern (int i, int j)
virtual void preAllocateEntries ()
virtual void addToMatrix (int il, int ic, const scalar &val)
virtual void getMatrix (INDEX_TYPE *&jptr, INDEX_TYPE *&ai, double *&a)
virtual void getFromMatrix (int row, int col, scalar &val) const
virtual void addToRightHandSide (int row, const scalar &val, int ith=0)
virtual void addToSolution (int row, const scalar &val)
virtual void getFromRightHandSide (int row, scalar &val) const
virtual void getFromSolution (int row, scalar &val) const
virtual void zeroMatrix ()
virtual void zeroRightHandSide ()
virtual void zeroSolution ()
virtual double normInfRightHandSide () const
void preAllocateEntries ()
void preAllocateEntries ()
void allocate (int nbRows)
void allocate (int nbRows)
void getMatrix (INDEX_TYPE *&jptr, INDEX_TYPE *&ai, double *&a)
void getMatrix (INDEX_TYPE *&jptr, INDEX_TYPE *&ai, double *&a)
Public Member Functions inherited from linearSystem< scalar >
linearSystem ()
virtual ~linearSystem ()
Public Member Functions inherited from linearSystemBase
virtual ~linearSystemBase ()
virtual int matMult ()
void setParameter (const std::string &key, std::string value)
std::string getParameter (const std::string &key) const
virtual double normInfSolution () const
Private Attributes
std::string _method
double _tol
int _noisy
Additional Inherited Members
Protected Attributes inherited from linearSystemCSR< scalar >
bool sorted
bool _entriesPreAllocated
char * something
CSRList_T * _a
CSRList_T * _ai
CSRList_T * _ptr
CSRList_T * _jptr
std::vector< scalar > * _b
std::vector< scalar > * _x
sparsityPattern _sparsity
Protected Attributes inherited from linearSystemBase
std::map< std::string, std::string > _parameters
Detailed Description
template<class scalar>
class linearSystemCSRGmm< scalar >
Definition at line 176 of file linearSystemCSR.h.
Constructor & Destructor Documentation
linearSystemCSRGmm()
template<class scalar > linearSystemCSRGmm< scalar >::linearSystemCSRGmm (const std::string & method = "gmres", double tol = 1e-8, int noisy = 0) inline
Definition at line 183 of file linearSystemCSR.h.
~linearSystemCSRGmm()
template<class scalar > virtual linearSystemCSRGmm< scalar >::~linearSystemCSRGmm () inline virtual
Definition at line 186 of file linearSystemCSR.h.
Member Function Documentation
setGmres()
template<class scalar > void linearSystemCSRGmm< scalar >::setGmres (int n) inline
Definition at line 189 of file linearSystemCSR.h.
Referenced by frameSolver2d::solve(), and thermicSolver::solve().
setNoisy()
template<class scalar > void linearSystemCSRGmm< scalar >::setNoisy (int n) inline
Definition at line 188 of file linearSystemCSR.h.
Referenced by frameSolver2d::solve(), and thermicSolver::solve().
setPrec()
template<class scalar > void linearSystemCSRGmm< scalar >::setPrec (double p) inline
Definition at line 187 of file linearSystemCSR.h.
systemSolve()
template<class scalar > virtual int linearSystemCSRGmm< scalar >::systemSolve () inline virtual
Implements linearSystemBase.
Definition at line 190 of file linearSystemCSR.h.
Member Data Documentation
_method
template<class scalar > std::string linearSystemCSRGmm< scalar >::_method private
Definition at line 178 of file linearSystemCSR.h.
Referenced by linearSystemCSRGmm< scalar >::setGmres().
_noisy
template<class scalar > int linearSystemCSRGmm< scalar >::_noisy private
Definition at line 180 of file linearSystemCSR.h.
Referenced by linearSystemCSRGmm< scalar >::setNoisy().
_tol
template<class scalar > double linearSystemCSRGmm< scalar >::_tol private
Definition at line 179 of file linearSystemCSR.h.
Referenced by linearSystemCSRGmm< scalar >::setPrec().
The documentation for this class was generated from the following file:
src/solver/linearSystemCSR.h