gmsh-TingyuanDoc: MakeSimplex Class Reference
MakeSimplex Class Reference
#include <MakeSimplex.h>
Public Member Functions
MakeSimplex (int numNodes, int numComponents, int numTimeSteps=1)
int numSimplices ()
int numSimplexNodes ()
void decompose (int num, double *x, double *y, double *z, double *val, double *xn, double *yn, double *zn, double *valn)
Private Member Functions
void reorder (int map[4], int n, double *x, double *y, double *z, double *val, double *xn, double *yn, double *zn, double *valn)
Private Attributes
int _numNodes
int _numComponents
int _numTimeSteps
Detailed Description
Definition at line 29 of file MakeSimplex.h.
Constructor & Destructor Documentation
MakeSimplex()
MakeSimplex::MakeSimplex (int numNodes, int numComponents, int numTimeSteps = 1)
Definition at line 109 of file MakeSimplex.cpp.
Member Function Documentation
decompose()
void MakeSimplex::decompose (int num, double * x, double * y, double * z, double * val, double * xn, double * yn, double * zn, double * valn)
Definition at line 154 of file MakeSimplex.cpp.
Referenced by decomposeList().
numSimplexNodes()
int MakeSimplex::numSimplexNodes ()
Definition at line 127 of file MakeSimplex.cpp.
Referenced by decomposeList().
numSimplices()
int MakeSimplex::numSimplices ()
Definition at line 116 of file MakeSimplex.cpp.
Referenced by decompose(), and decomposeList().
reorder()
void MakeSimplex::reorder (int map[4], int n, double * x, double * y, double * z, double * val, double * xn, double * yn, double * zn, double * valn) private
Definition at line 135 of file MakeSimplex.cpp.
Referenced by decompose().
Member Data Documentation
_numComponents
int MakeSimplex::_numComponents private
Definition at line 34 of file MakeSimplex.h.
Referenced by reorder().
_numNodes
int MakeSimplex::_numNodes private
Definition at line 32 of file MakeSimplex.h.
Referenced by decompose(), numSimplexNodes(), numSimplices(), and reorder().
_numTimeSteps
int MakeSimplex::_numTimeSteps private
Definition at line 36 of file MakeSimplex.h.
Referenced by reorder().
The documentation for this class was generated from the following files:
src/plugin/MakeSimplex.h
src/plugin/MakeSimplex.cpp