gmsh-TingyuanDoc: NameSpaces Class Reference
NameSpaces Class Reference
#include <Parser.h>
Public Member Functions
NameSpaces ()
~NameSpaces ()
int defStruct (std::string &key_namespace, std::string &key_name, std::map< std::string, std::vector< double > > &fopt, std::map< std::string, std::vector< std::string > > &copt, int &tag_out, int member_ValMax, bool append=false)
int getTag (std::string &key_namespace, std::string &key_name, double &out) const
int getMember (std::string &key_namespace, std::string &key_name, std::string &key_member, double &out, int index=0) const
int getMember (std::string &key_namespace, std::string &key_name, std::string &key_member, const std::string *&out, int index=0) const
int getMember_Dim (std::string &key_namespace, std::string &key_name, std::string &key_member, int &out) const
int getMember_Vector (std::string &key_namespace, std::string &key_name, std::string &key_member, const std::vector< double > *&out_vector) const
int getMember_Vector (std::string &key_namespace, std::string &key_name, std::string &key_member, const std::vector< std::string > *&out_vector) const
int get_key_struct_from_tag (std::string &key_namespace, int tag, const std::string *&key_struct) const
int getMember_ValMax (std::string &key_namespace, std::string &key_name)
void sprint (std::vector< std::string > &strs_out) const
Public Member Functions inherited from Map< std::string, Structs >
Map ()
~Map ()
Structs * Find (std::string key)
const Structs * Find (std::string key) const
Structs & operator[] (std::string key)
std::map< std::string, Structs > & get ()
const std::map< std::string, Structs > & get () const
int count (const std::string key) const
int size () const
void clear ()
Additional Inherited Members
Public Attributes inherited from Map< std::string, Structs >
std::map< std::string, Structs > _map
Detailed Description
Definition at line 272 of file Parser.h.
Constructor & Destructor Documentation
NameSpaces()
NameSpaces::NameSpaces () inline
Definition at line 274 of file Parser.h.
~NameSpaces()
NameSpaces::~NameSpaces () inline
Definition at line 275 of file Parser.h.
Member Function Documentation
defStruct()
int NameSpaces::defStruct (std::string & key_namespace, std::string & key_name, std::map< std::string, std::vector< double > > & fopt, std::map< std::string, std::vector< std::string > > & copt, int & tag_out, int member_ValMax, bool append = false) inline
Definition at line 277 of file Parser.h.
get_key_struct_from_tag()
int NameSpaces::get_key_struct_from_tag (std::string & key_namespace, int tag, const std::string *& key_struct) const inline
Definition at line 407 of file Parser.h.
getMember() [1/2]
int NameSpaces::getMember (std::string & key_namespace, std::string & key_name, std::string & key_member, const std::string *& out, int index = 0) const inline
Definition at line 327 of file Parser.h.
getMember() [2/2]
int NameSpaces::getMember (std::string & key_namespace, std::string & key_name, std::string & key_member, double & out, int index = 0) const inline
Definition at line 308 of file Parser.h.
Referenced by treat_Struct_FullName_dot_tSTRING_Float(), and treat_Struct_FullName_dot_tSTRING_String().
getMember_Dim()
int NameSpaces::getMember_Dim (std::string & key_namespace, std::string & key_name, std::string & key_member, int & out) const inline
Definition at line 347 of file Parser.h.
Referenced by treat_Struct_FullName_dot_tSTRING_Float_getDim().
getMember_ValMax()
int NameSpaces::getMember_ValMax (std::string & key_namespace, std::string & key_name) inline
Definition at line 417 of file Parser.h.
getMember_Vector() [1/2]
int NameSpaces::getMember_Vector (std::string & key_namespace, std::string & key_name, std::string & key_member, const std::vector< double > *& out_vector) const inline
Definition at line 365 of file Parser.h.
Referenced by treat_Struct_FullName_dot_tSTRING_ListOfFloat(), and treat_Struct_FullName_dot_tSTRING_ListOfString().
getMember_Vector() [2/2]
int NameSpaces::getMember_Vector (std::string & key_namespace, std::string & key_name, std::string & key_member, const std::vector< std::string > *& out_vector) const inline
Definition at line 386 of file Parser.h.
getTag()
int NameSpaces::getTag (std::string & key_namespace, std::string & key_name, double & out) const inline
Definition at line 295 of file Parser.h.
Referenced by treat_Struct_FullName_Float().
sprint()
void NameSpaces::sprint (std::vector< std::string > & strs_out) const inline
Definition at line 424 of file Parser.h.
Referenced by PrintParserSymbols().
The documentation for this class was generated from the following file:
src/parser/Parser.h