gmsh-TingyuanDoc: FunctionSpace< T > Class Template Reference
FunctionSpace< T > Class Template Reference abstract
#include <functionSpace.h>
Public Types
typedef TensorialTraits< T >::ValType ValType
typedef TensorialTraits< T >::GradType GradType
typedef TensorialTraits< T >::HessType HessType
typedef TensorialTraits< T >::ThirdDevType ThirdDevType
Public Member Functions
virtual int getId (void) const
virtual void f (MElement *ele, double u, double v, double w, std::vector< ValType > &vals) const =0
virtual void fuvw (MElement *ele, double u, double v, double w, std::vector< ValType > &vals) const
virtual void gradf (MElement *ele, double u, double v, double w, std::vector< GradType > &grads) const =0
virtual void gradfuvw (MElement *ele, double u, double v, double w, std::vector< GradType > &grads) const
virtual void hessfuvw (MElement *ele, double u, double v, double w, std::vector< HessType > &hess) const =0
virtual void hessf (MElement *ele, double u, double v, double w, std::vector< HessType > &hess) const
virtual void thirdDevfuvw (MElement *ele, double u, double v, double w, std::vector< ThirdDevType > &third) const
virtual void thirdDevf (MElement *ele, double u, double v, double w, std::vector< ThirdDevType > &third) const
virtual int getNumKeys (MElement *ele) const =0
virtual void getKeys (MElement *ele, std::vector< Dof > &keys) const =0
Public Member Functions inherited from FunctionSpaceBase
virtual ~FunctionSpaceBase ()
virtual void getKeysOnVertex (MElement *ele, MVertex *v, const std::vector< int > &comp, std::vector< Dof > &keys) const
virtual FunctionSpaceBase * clone (const int id) const
Protected Attributes
int _iField
Detailed Description
template<class T>
class FunctionSpace< T >
Definition at line 82 of file functionSpace.h.
Member Typedef Documentation
GradType
template<class T > typedef TensorialTraits<T>::GradType FunctionSpace< T >::GradType
Definition at line 87 of file functionSpace.h.
HessType
template<class T > typedef TensorialTraits<T>::HessType FunctionSpace< T >::HessType
Definition at line 88 of file functionSpace.h.
ThirdDevType
template<class T > typedef TensorialTraits<T>::ThirdDevType FunctionSpace< T >::ThirdDevType
Definition at line 89 of file functionSpace.h.
ValType
template<class T > typedef TensorialTraits<T>::ValType FunctionSpace< T >::ValType
Definition at line 86 of file functionSpace.h.
Member Function Documentation
f()
template<class T > virtual void FunctionSpace< T >::f (MElement * ele, double u, double v, double w, std::vector< ValType > & vals) const pure virtual
Implemented in FilteredFunctionSpace< T, F >, xFemFunctionSpace< T >, CompositeFunctionSpace< T >, ScalarToAnyFunctionSpace< T >, ScalarToAnyFunctionSpace< SVector3 >, ScalarLagrangeFunctionSpace, ScalarLagrangeFunctionSpaceOfElement, and SolverField< T >.
Referenced by ScalarToAnyFunctionSpace< SVector3 >::f().
fuvw()
template<class T > virtual void FunctionSpace< T >::fuvw (MElement * ele, double u, double v, double w, std::vector< ValType > & vals) const inline virtual
Reimplemented in ScalarLagrangeFunctionSpace.
Definition at line 93 of file functionSpace.h.
getId()
template<class T > virtual int FunctionSpace< T >::getId (void) const inline virtual
Implements FunctionSpaceBase.
Definition at line 90 of file functionSpace.h.
getKeys()
template<class T > virtual void FunctionSpace< T >::getKeys (MElement * ele, std::vector< Dof > & keys) const pure virtual
Implements FunctionSpaceBase.
Implemented in FilteredFunctionSpace< T, F >, xFemFunctionSpace< T >, CompositeFunctionSpace< T >, ScalarToAnyFunctionSpace< T >, ScalarToAnyFunctionSpace< SVector3 >, ScalarLagrangeFunctionSpace, ScalarLagrangeFunctionSpaceOfElement, and SolverField< T >.
Referenced by ScalarToAnyFunctionSpace< SVector3 >::getKeys().
getNumKeys()
template<class T > virtual int FunctionSpace< T >::getNumKeys (MElement * ele) const pure virtual
Implements FunctionSpaceBase.
Implemented in FilteredFunctionSpace< T, F >, xFemFunctionSpace< T >, CompositeFunctionSpace< T >, ScalarToAnyFunctionSpace< T >, ScalarToAnyFunctionSpace< SVector3 >, ScalarLagrangeFunctionSpace, ScalarLagrangeFunctionSpaceOfElement, and SolverField< T >.
Referenced by ScalarToAnyFunctionSpace< SVector3 >::getKeys(), and ScalarToAnyFunctionSpace< SVector3 >::getNumKeys().
gradf()
template<class T > virtual void FunctionSpace< T >::gradf (MElement * ele, double u, double v, double w, std::vector< GradType > & grads) const pure virtual
Implemented in FilteredFunctionSpace< T, F >, xFemFunctionSpace< T >, CompositeFunctionSpace< T >, ScalarToAnyFunctionSpace< T >, ScalarToAnyFunctionSpace< SVector3 >, ScalarLagrangeFunctionSpace, ScalarLagrangeFunctionSpaceOfElement, and SolverField< T >.
Referenced by ScalarToAnyFunctionSpace< SVector3 >::gradf().
gradfuvw()
template<class T > virtual void FunctionSpace< T >::gradfuvw (MElement * ele, double u, double v, double w, std::vector< GradType > & grads) const inline virtual
Reimplemented in ScalarToAnyFunctionSpace< T >, ScalarToAnyFunctionSpace< SVector3 >, ScalarLagrangeFunctionSpace, and ScalarLagrangeFunctionSpaceOfElement.
Definition at line 99 of file functionSpace.h.
Referenced by ScalarToAnyFunctionSpace< SVector3 >::gradfuvw().
hessf()
template<class T > virtual void FunctionSpace< T >::hessf (MElement * ele, double u, double v, double w, std::vector< HessType > & hess) const inline virtual
Definition at line 105 of file functionSpace.h.
hessfuvw()
template<class T > virtual void FunctionSpace< T >::hessfuvw (MElement * ele, double u, double v, double w, std::vector< HessType > & hess) const pure virtual
Implemented in FilteredFunctionSpace< T, F >, xFemFunctionSpace< T >, CompositeFunctionSpace< T >, ScalarToAnyFunctionSpace< T >, ScalarToAnyFunctionSpace< SVector3 >, ScalarLagrangeFunctionSpace, ScalarLagrangeFunctionSpaceOfElement, and SolverField< T >.
Referenced by ScalarToAnyFunctionSpace< SVector3 >::hessfuvw().
thirdDevf()
template<class T > virtual void FunctionSpace< T >::thirdDevf (MElement * ele, double u, double v, double w, std::vector< ThirdDevType > & third) const inline virtual
Definition at line 112 of file functionSpace.h.
thirdDevfuvw()
template<class T > virtual void FunctionSpace< T >::thirdDevfuvw (MElement * ele, double u, double v, double w, std::vector< ThirdDevType > & third) const inline virtual
Definition at line 109 of file functionSpace.h.
Member Data Documentation
_iField
template<class T > int FunctionSpace< T >::_iField protected
Definition at line 84 of file functionSpace.h.
Referenced by FunctionSpace< SVector3 >::getId().
The documentation for this class was generated from the following file:
src/solver/functionSpace.h