gmsh-TingyuanDoc: Map< K, T > Class Template Reference
Map< K, T > Class Template Reference
#include <Parser.h>
Public Member Functions
Map ()
~Map ()
T * Find (K key)
const T * Find (K key) const
T & operator[] (K key)
std::map< K, T > & get ()
const std::map< K, T > & get () const
int count (const std::string key) const
int size () const
void clear ()
Public Attributes
std::map< K, T > _map
Detailed Description
template<class K, class T>
class Map< K, T >
Definition at line 183 of file Parser.h.
Constructor & Destructor Documentation
Map()
template<class K , class T > Map< K, T >::Map () inline
Definition at line 185 of file Parser.h.
~Map()
template<class K , class T > Map< K, T >::~Map () inline
Definition at line 186 of file Parser.h.
Member Function Documentation
clear()
template<class K , class T > void Map< K, T >::clear () inline
Definition at line 211 of file Parser.h.
Referenced by DeleteAllModelsAndViews(), and OpenProject().
count()
template<class K , class T > int Map< K, T >::count (const std::string key) const inline
Definition at line 209 of file Parser.h.
Referenced by NameSpaces::defStruct().
Find() [1/2]
template<class K , class T > T* Map< K, T >::Find (K key) inline
Definition at line 188 of file Parser.h.
Referenced by NameSpaces::getMember(), NameSpaces::getMember_Dim(), NameSpaces::getMember_ValMax(), NameSpaces::getMember_Vector(), and NameSpaces::getTag().
Find() [2/2]
template<class K , class T > const T* Map< K, T >::Find (K key) const inline
Definition at line 197 of file Parser.h.
get() [1/2]
template<class K , class T > std::map<K, T>& Map< K, T >::get () inline
Definition at line 207 of file Parser.h.
get() [2/2]
template<class K , class T > const std::map<K, T>& Map< K, T >::get () const inline
Definition at line 208 of file Parser.h.
operator[]()
template<class K , class T > T& Map< K, T >::operator[] (K key) inline
Definition at line 206 of file Parser.h.
size()
template<class K , class T > int Map< K, T >::size () const inline
Definition at line 210 of file Parser.h.
Referenced by PrintParserSymbols().
Member Data Documentation
_map
template<class K , class T > std::map<K, T> Map< K, T >::_map
Definition at line 214 of file Parser.h.
Referenced by Map< std::string, Struct >::clear(), Map< std::string, Struct >::count(), Map< std::string, Struct >::Find(), Map< std::string, Struct >::get(), Map< std::string, Struct >::operator[](), and Map< std::string, Struct >::size().
The documentation for this class was generated from the following file:
src/parser/Parser.h