gmsh-TingyuanDoc: gmshVertex Class Reference
gmshVertex Class Reference
#include <gmshVertex.h>
Public Member Functions
gmshVertex (GModel *m, Vertex *v)
virtual ~gmshVertex ()
virtual void resetMeshAttributes ()
virtual GPoint point () const
virtual double x () const
virtual double y () const
virtual double z () const
virtual void setPosition (GPoint &p)
virtual GeomType geomType () const
virtual ModelType getNativeType () const
virtual void * getNativePtr () const
virtual void setPrescribedMeshSizeAtVertex (double l)
virtual SPoint2 reparamOnFace (const GFace *gf, int) const
virtual void writeGEO (FILE *fp, const std::string &meshSizeParameter="")
virtual void writePY (FILE *fp, const std::string &meshSizeParameter="")
void resetNativePtr (Vertex *v)
Public Member Functions inherited from GVertex
GVertex (GModel *m, int tag, double ms=MAX_LC)
virtual ~GVertex ()
virtual void deleteMesh ()
virtual SPoint3 xyz () const
void addEdge (GEdge *e)
void delEdge (GEdge *e)
virtual std::list< GRegion * > regions () const
virtual std::vector< GEdge * > const & edges () const
virtual std::size_t numEdges () const
virtual std::vector< GFace * > faces () const
virtual int dim () const
virtual GEntity * getParentEntity ()
virtual bool isOrphan ()
virtual double prescribedMeshSizeAtVertex () const
virtual SBoundingBox3d bounds (bool fast=false)
virtual std::string getAdditionalInfoString (bool multline=false)
virtual void getElementTypes (std::vector< int > &types) const
std::size_t getNumMeshElements () const
std::size_t getNumMeshElementsByType (const int familyType) const
void getNumMeshElements (unsigned *const c) const
MElement * getMeshElement (std::size_t index) const
MElement * getMeshElementByType (const int familyType, const std::size_t index) const
bool isOnSeam (const GFace *gf) const
void relocateMeshVertices ()
void addPoint (MPoint *p)
void addElement (int type, MElement *e)
void removeElement (int type, MElement *e)
void removeElements (int type)
virtual bool reorder (const int elementType, const std::vector< std::size_t > &ordering)
Public Member Functions inherited from GEntity
void addVerticesInSet (std::set< MVertex * > &, bool closure) const
virtual std::string getTypeString ()
GEntity (GModel *m, int t)
virtual ~GEntity ()
virtual void mesh (bool verbose)
void deleteVertexArrays ()
virtual std::vector< GVertex * > vertices () const
std::vector< GRegion * > bindingsGetRegions ()
std::vector< GFace * > bindingsGetFaces ()
std::vector< GEdge * > bindingsGetEdges () const
std::vector< GVertex * > bindingsGetVertices ()
virtual bool continuous (int dim) const
virtual bool periodic (int dim) const
virtual double period (int dim) const
virtual bool degenerate (int dim) const
virtual bool haveParametrization ()
virtual bool isFullyDiscrete ()
virtual Range< double > parBounds (int i) const
virtual double tolerance () const
virtual bool containsPoint (const SPoint3 &pt) const
virtual int getNativeInt () const
GModel * model () const
int tag () const
void setTag (int tag)
virtual void addPhysicalEntity (int physicalTag)
virtual std::vector< int > getPhysicalEntities ()
GEntity * getMeshMaster () const
void setMeshMaster (GEntity *)
void setMeshMaster (GEntity *, const std::vector< double > &, bool updateCorrespondingVertices=true)
void updateCorrespondingVertices ()
void copyMasterCoordinates ()
virtual void alignElementsWithMaster ()
virtual SOrientedBoundingBox getOBB ()
virtual char getVisibility ()
virtual void setVisibility (char val, bool recursive=false)
virtual char getSelection ()
virtual void setSelection (char val)
virtual unsigned int getColor ()
virtual void setColor (unsigned color, bool recursive=false)
virtual bool useColor ()
virtual std::string getInfoString (bool additional=true, bool multiline=false)
virtual double getMeshSize () const
virtual double getMeshSizeFactor () const
virtual std::size_t getNumMeshParentElements ()
virtual MElement *const * getStartElementType (int type) const
bool getAllElementsVisible ()
void setAllElementsVisible (bool val)
std::size_t getNumMeshVertices ()
MVertex * getMeshVertex (std::size_t index)
void addMeshVertex (MVertex *v)
void removeMeshVertex (MVertex *v)
GVertex * cast2Vertex ()
GEdge * cast2Edge ()
GFace * cast2Face ()
GRegion * cast2Region ()
Private Attributes
Vertex * _v
Additional Inherited Members
Public Types inherited from GEntity
enum ModelType {
UnknownModel, GmshModel, OpenCascadeModel, AcisModel,
ParasolidModel
}
enum GeomType {
Unknown, Point, BoundaryLayerPoint, Line,
Circle, Ellipse, Conic, Parabola,
Hyperbola, TrimmedCurve, OffsetCurve, BSpline,
Bezier, ParametricCurve, BoundaryLayerCurve, DiscreteCurve,
Plane, Nurb, Cylinder, Sphere,
Cone, Torus, RuledSurface, ParametricSurface,
BSplineSurface, BezierSurface, SurfaceOfRevolution, BoundaryLayerSurface,
DiscreteSurface, DiscreteDiskSurface, Volume, DiscreteVolume,
PartitionPoint, PartitionCurve, PartitionSurface, PartitionVolume,
GhostCurve, GhostSurface, GhostVolume
}
enum MeshGenerationStatus { PENDING, DONE, FAILED }
Public Attributes inherited from GVertex
std::vector< MPoint * > points
Public Attributes inherited from GEntity
std::vector< MVertex * > mesh_vertices
std::vector< GEntity * > compound
std::map< GVertex *, GVertex * > vertexCounterparts
std::vector< int > physicals
VertexArray * va_lines
VertexArray * va_triangles
std::set< MElement * > curvedBLElements
std::vector< double > affineTransform
std::map< MVertex *, MVertex * > correspondingVertices
std::map< MVertex *, MVertex * > correspondingHighOrderVertices
Protected Attributes inherited from GVertex
std::vector< GEdge * > l_edges
double meshSize
Protected Attributes inherited from GEntity
SOrientedBoundingBox * _obb
Detailed Description
Definition at line 13 of file gmshVertex.h.
Constructor & Destructor Documentation
gmshVertex()
gmshVertex::gmshVertex (GModel * m, Vertex * v)
Definition at line 15 of file gmshVertex.cpp.
~gmshVertex()
virtual gmshVertex::~gmshVertex () inline virtual
Definition at line 19 of file gmshVertex.h.
Member Function Documentation
geomType()
GEntity::GeomType gmshVertex::geomType () const virtual
Reimplemented from GVertex.
Definition at line 47 of file gmshVertex.cpp.
getNativePtr()
virtual void* gmshVertex::getNativePtr () const inline virtual
Reimplemented from GEntity.
Definition at line 28 of file gmshVertex.h.
getNativeType()
virtual ModelType gmshVertex::getNativeType () const inline virtual
Reimplemented from GEntity.
Definition at line 27 of file gmshVertex.h.
point()
GPoint gmshVertex::point () const virtual
Implements GVertex.
Definition at line 24 of file gmshVertex.cpp.
reparamOnFace()
SPoint2 gmshVertex::reparamOnFace (const GFace * gf, int dir) const virtual
Reimplemented from GVertex.
Definition at line 61 of file gmshVertex.cpp.
resetMeshAttributes()
void gmshVertex::resetMeshAttributes () virtual
Reimplemented from GVertex.
Definition at line 22 of file gmshVertex.cpp.
Referenced by gmshVertex().
resetNativePtr()
void gmshVertex::resetNativePtr (Vertex * v)
Definition at line 20 of file gmshVertex.cpp.
setPosition()
void gmshVertex::setPosition (GPoint & p) virtual
Reimplemented from GVertex.
Definition at line 35 of file gmshVertex.cpp.
setPrescribedMeshSizeAtVertex()
void gmshVertex::setPrescribedMeshSizeAtVertex (double l) virtual
Reimplemented from GVertex.
Definition at line 55 of file gmshVertex.cpp.
writeGEO()
void gmshVertex::writeGEO (FILE * fp, const std::string & meshSizeParameter = "") virtual
Reimplemented from GVertex.
Definition at line 149 of file gmshVertex.cpp.
writePY()
void gmshVertex::writePY (FILE * fp, const std::string & meshSizeParameter = "") virtual
Reimplemented from GVertex.
Definition at line 174 of file gmshVertex.cpp.
x()
double gmshVertex::x () const virtual
Implements GVertex.
Definition at line 29 of file gmshVertex.cpp.
Referenced by writeGEO(), and writePY().
y()
double gmshVertex::y () const virtual
Implements GVertex.
Definition at line 31 of file gmshVertex.cpp.
Referenced by writeGEO(), and writePY().
z()
double gmshVertex::z () const virtual
Implements GVertex.
Definition at line 33 of file gmshVertex.cpp.
Referenced by writeGEO(), and writePY().
Member Data Documentation
_v
Vertex* gmshVertex::_v private
Definition at line 15 of file gmshVertex.h.
Referenced by geomType(), getNativePtr(), point(), reparamOnFace(), resetMeshAttributes(), resetNativePtr(), setPosition(), setPrescribedMeshSizeAtVertex(), writeGEO(), writePY(), x(), y(), and z().
The documentation for this class was generated from the following files:
src/geo/gmshVertex.h
src/geo/gmshVertex.cpp