gmsh-TingyuanDoc: PluginManager Class Reference
PluginManager Class Reference
#include <PluginManager.h>
Public Member Functions
virtual ~PluginManager ()
void registerDefaultPlugins ()
void addPlugin (const std::string &fileName)
void uninstallPlugin (const std::string &pluginName)
void setPluginOption (const std::string &pluginName, const std::string &option, double value)
void setPluginOption (const std::string &pluginName, const std::string &option, const std::string &value)
std::map< std::string, GMSH_Plugin * >::iterator begin ()
std::map< std::string, GMSH_Plugin * >::iterator end ()
GMSH_Plugin * find (const std::string &pluginName)
GMSH_SolverPlugin * findSolverPlugin ()
int action (const std::string &pluginName, const std::string &action, void *data)
Static Public Member Functions
static PluginManager * instance ()
Private Member Functions
PluginManager ()
Private Attributes
std::map< std::string, GMSH_Plugin * > allPlugins
Static Private Attributes
static PluginManager * _instance = nullptr
Detailed Description
Definition at line 15 of file PluginManager.h.
Constructor & Destructor Documentation
PluginManager()
PluginManager::PluginManager () inline private
Definition at line 17 of file PluginManager.h.
Referenced by instance().
~PluginManager()
PluginManager::~PluginManager () virtual
Definition at line 92 of file PluginManager.cpp.
Member Function Documentation
action()
int PluginManager::action (const std::string & pluginName, const std::string & action, void * data)
Definition at line 119 of file PluginManager.cpp.
addPlugin()
void PluginManager::addPlugin (const std::string & fileName)
Definition at line 319 of file PluginManager.cpp.
Referenced by registerDefaultPlugins().
begin()
std::map<std::string, GMSH_Plugin *>::iterator PluginManager::begin () inline
Definition at line 44 of file PluginManager.h.
end()
std::map<std::string, GMSH_Plugin *>::iterator PluginManager::end () inline
Definition at line 48 of file PluginManager.h.
Referenced by PrintOptionsDoc().
find()
GMSH_Plugin * PluginManager::find (const std::string & pluginName)
Definition at line 99 of file PluginManager.cpp.
Referenced by action(), and setPluginOption().
findSolverPlugin()
GMSH_SolverPlugin * PluginManager::findSolverPlugin ()
Definition at line 106 of file PluginManager.cpp.
instance()
PluginManager * PluginManager::instance () static
Definition at line 169 of file PluginManager.cpp.
Referenced by GmshFinalize(), GmshInitialize(), GmshMainFLTK(), and PrintOptionsDoc().
registerDefaultPlugins()
void PluginManager::registerDefaultPlugins ()
Definition at line 175 of file PluginManager.cpp.
Referenced by GmshInitialize(), and GmshMainFLTK().
setPluginOption() [1/2]
void PluginManager::setPluginOption (const std::string & pluginName, const std::string & option, const std::string & value)
Definition at line 135 of file PluginManager.cpp.
setPluginOption() [2/2]
void PluginManager::setPluginOption (const std::string & pluginName, const std::string & option, double value)
Definition at line 152 of file PluginManager.cpp.
uninstallPlugin()
void PluginManager::uninstallPlugin (const std::string & pluginName) inline
Definition at line 35 of file PluginManager.h.
Member Data Documentation
_instance
PluginManager * PluginManager::_instance = nullptr static private
Definition at line 18 of file PluginManager.h.
Referenced by instance(), and ~PluginManager().
allPlugins
std::map<std::string, GMSH_Plugin *> PluginManager::allPlugins private
Definition at line 19 of file PluginManager.h.
Referenced by addPlugin(), begin(), end(), find(), findSolverPlugin(), registerDefaultPlugins(), and ~PluginManager().
The documentation for this class was generated from the following files:
src/plugin/PluginManager.h
src/plugin/PluginManager.cpp