gmsh-TingyuanDoc: qmTetrahedron Class Reference
qmTetrahedron Class Reference
#include <qualityMeasures.h>
Public Types
enum Measures { QMTET_GAMMA, QMTET_ETA, QMTET_ONE, QMTET_COND }
Static Public Member Functions
static double qm (MTetrahedron *t, const Measures &cr, double *volume=nullptr)
static double qm (const BDS_Point *p1, const BDS_Point *p2, const BDS_Point *p3)
static double qm (const MVertex *v1, const MVertex *v2, const MVertex *v3, const MVertex *v4, const Measures &cr, double *volume=nullptr)
static double qm (const double &x1, const double &y1, const double &z1, const double &x2, const double &y2, const double &z2, const double &x3, const double &y3, const double &z3, const double &x4, const double &y4, const double &z4, const Measures &cr, double *volume=nullptr)
static double eta (const double &x1, const double &y1, const double &z1, const double &x2, const double &y2, const double &z2, const double &x3, const double &y3, const double &z3, const double &x4, const double &y4, const double &z4, double *volume=nullptr)
static double gamma (const double &x1, const double &y1, const double &z1, const double &x2, const double &y2, const double &z2, const double &x3, const double &y3, const double &z3, const double &x4, const double &y4, const double &z4, double *volume=nullptr)
static double cond (const double &x1, const double &y1, const double &z1, const double &x2, const double &y2, const double &z2, const double &x3, const double &y3, const double &z3, const double &x4, const double &y4, const double &z4, double *volume=nullptr)
static double minNCJ (const MTetrahedron *e)
static int numNCJVal ()
Detailed Description
Definition at line 66 of file qualityMeasures.h.
Member Enumeration Documentation
Measures
enum qmTetrahedron::Measures
Enumerator
QMTET_GAMMA
QMTET_ETA
QMTET_ONE
QMTET_COND
Definition at line 68 of file qualityMeasures.h.
Member Function Documentation
cond()
double qmTetrahedron::cond (const double & x1, const double & y1, const double & z1, const double & x2, const double & y2, const double & z2, const double & x3, const double & y3, const double & z3, const double & x4, const double & y4, const double & z4, double * volume = nullptr) static
condition number is defined as (see Knupp & Freitag in IJNME)
Definition at line 727 of file qualityMeasures.cpp.
Referenced by qm().
eta()
double qmTetrahedron::eta (const double & x1, const double & y1, const double & z1, const double & x2, const double & y2, const double & z2, const double & x3, const double & y3, const double & z3, const double & x4, const double & y4, const double & z4, double * volume = nullptr) static
Definition at line 651 of file qualityMeasures.cpp.
Referenced by qm().
gamma()
double qmTetrahedron::gamma (const double & x1, const double & y1, const double & z1, const double & x2, const double & y2, const double & z2, const double & x3, const double & y3, const double & z3, const double & x4, const double & y4, const double & z4, double * volume = nullptr) static
Definition at line 674 of file qualityMeasures.cpp.
Referenced by objective_function(), and qm().
minNCJ()
static double qmTetrahedron::minNCJ (const MTetrahedron * e) static
numNCJVal()
static int qmTetrahedron::numNCJVal () inline static
Definition at line 99 of file qualityMeasures.h.
qm() [1/4]
static double qmTetrahedron::qm (const BDS_Point * p1, const BDS_Point * p2, const BDS_Point * p3) static
qm() [2/4]
double qmTetrahedron::qm (const double & x1, const double & y1, const double & z1, const double & x2, const double & y2, const double & z2, const double & x3, const double & y3, const double & z3, const double & x4, const double & y4, const double & z4, const Measures & cr, double * volume = nullptr) static
Definition at line 630 of file qualityMeasures.cpp.
qm() [3/4]
double qmTetrahedron::qm (const MVertex * v1, const MVertex * v2, const MVertex * v3, const MVertex * v4, const Measures & cr, double * volume = nullptr) static
Definition at line 622 of file qualityMeasures.cpp.
qm() [4/4]
double qmTetrahedron::qm (MTetrahedron * t, const Measures & cr, double * volume = nullptr) static
Definition at line 616 of file qualityMeasures.cpp.
Referenced by collapseVertex(), edgeSwap(), MTetrahedron::etaShapeMeasure(), faceSwap(), MTetrahedron::gammaShapeMeasure(), MTet4::MTet4(), qm(), smoothing_objective_function_3D(), smoothVertex(), and smoothVertexOptimize().
The documentation for this class was generated from the following files:
src/mesh/qualityMeasures.h
src/mesh/qualityMeasures.cpp