gmsh-TingyuanDoc: bezierCoeff Class Reference
bezierCoeff Class Reference
#include <bezierBasis.h>
Public Member Functions
bezierCoeff ()
bezierCoeff (const bezierCoeff &other, bool swap=false)
bezierCoeff (const FuncSpaceData fsData, const fullVector< double > &orderedLagCoeff, int numOfPool=-1)
bezierCoeff (const FuncSpaceData fsData, const fullMatrix< double > &orderedLagCoeff, int numOfPool=-1)
~bezierCoeff ()
void updateDataPtr (long diff)
int getPolynomialOrder () const
int getNumCoeff () const
int getNumColumns () const
int getNumCornerCoeff () const
int getIdxCornerCoeff (int i) const
double getCornerCoeff (int k) const
double getCornerCoeff (int k, int j) const
void getCornerCoeffs (fullVector< double > &) const
void getCornerCoeffs (fullMatrix< double > &) const
double * getDataPtr ()
const bezierBasis * getBezierBasis () const
void setMatrixAsProxy (fullMatrix< double > &m) const
void setVectorAsProxy (fullVector< double > &v) const
void subdivide (std::vector< bezierCoeff * > &subCoeff) const
double operator() (int i) const
double operator() (int i, int j) const
double & operator() (int i)
double & operator() (int i, int j)
Static Public Member Functions
static void usePools (std::size_t size0, std::size_t size1)
static void releasePools ()
Private Types
enum SubdivisionTet {
subdivU, subdivV, subdivW, node0CrossEdge12,
node3CrossEdge12, node1CrossEdge03, node2CrossEdge03
}
Private Member Functions
void _computeCoefficients (const double *lagCoeffData)
Static Private Member Functions
static void _subdivideTet (SubdivisionTet which, int n, bezierCoeff &coeff)
static void _subdivide (fullMatrix< double > &coeff, int npts, int start)
static void _subdivide (fullMatrix< double > &coeff, int npts, int start, int inc)
static void _subdivideTriangle (const bezierCoeff &coeff, int start, std::vector< bezierCoeff * > &subCoeff)
static void _subdivideTetrahedron (const bezierCoeff &coeff, std::vector< bezierCoeff * > &vSubCoeff)
static void _subdivideQuadrangle (const bezierCoeff &coeff, std::vector< bezierCoeff * > &subCoeff)
static void _subdivideHexahedron (const bezierCoeff &coeff, std::vector< bezierCoeff * > &subCoeff)
static void _subdividePrism (const bezierCoeff &coeff, std::vector< bezierCoeff * > &subCoeff)
static void _subdividePyramid (const bezierCoeff &coeff, std::vector< bezierCoeff * > &subCoeff)
static void _copy (const bezierCoeff &from, int start, int num, bezierCoeff &to)
static void _copyLine (const fullMatrix< double > &allSub, int n, int starti, bezierCoeff &sub)
static void _copyQuad (const fullMatrix< double > &allSub, int n, int starti, int startj, bezierCoeff &sub)
static void _copyHex (const fullMatrix< double > &allSub, int n, int starti, int startj, int startk, bezierCoeff &sub)
static void _copyPyr (const fullMatrix< double > &allSub, int nij, int nk, int starti, int startj, int startk, bezierCoeff &sub)
static int _ij2Index (int i, int j, int n)
static int _ijk2Index (int i, int j, int k, int n)
Private Attributes
int _numPool
FuncSpaceData _funcSpaceData
const bezierBasis * _basis
int _r
int _c
double * _data
bool _ownData
Static Private Attributes
static bezierCoeffMemoryPool * _pool0 = nullptr
static bezierCoeffMemoryPool * _pool1 = nullptr
static fullMatrix< double > _sub = fullMatrix<double>()
Detailed Description
Definition at line 127 of file bezierBasis.h.
Member Enumeration Documentation
SubdivisionTet
enum bezierCoeff::SubdivisionTet private
Enumerator
subdivU
subdivV
subdivW
node0CrossEdge12
node3CrossEdge12
node1CrossEdge03
node2CrossEdge03
Definition at line 204 of file bezierBasis.h.
Constructor & Destructor Documentation
bezierCoeff() [1/4]
bezierCoeff::bezierCoeff () inline
Definition at line 145 of file bezierBasis.h.
bezierCoeff() [2/4]
bezierCoeff::bezierCoeff (const bezierCoeff & other, bool swap = false)
Definition at line 696 of file bezierBasis.cpp.
bezierCoeff() [3/4]
bezierCoeff::bezierCoeff (const FuncSpaceData fsData, const fullVector< double > & orderedLagCoeff, int numOfPool = -1)
Definition at line 656 of file bezierBasis.cpp.
bezierCoeff() [4/4]
bezierCoeff::bezierCoeff (const FuncSpaceData fsData, const fullMatrix< double > & orderedLagCoeff, int numOfPool = -1)
Definition at line 616 of file bezierBasis.cpp.
~bezierCoeff()
bezierCoeff::~bezierCoeff ()
Definition at line 723 of file bezierBasis.cpp.
Member Function Documentation
_computeCoefficients()
void bezierCoeff::_computeCoefficients (const double * lagCoeffData) private
Definition at line 738 of file bezierBasis.cpp.
Referenced by bezierCoeff().
_copy()
void bezierCoeff::_copy (const bezierCoeff & from, int start, int num, bezierCoeff & to) static private
Definition at line 1389 of file bezierBasis.cpp.
Referenced by _subdivideTetrahedron(), and _subdivideTriangle().
_copyHex()
void bezierCoeff::_copyHex (const fullMatrix< double > & allSub, int n, int starti, int startj, int startk, bezierCoeff & sub) static private
Definition at line 1421 of file bezierBasis.cpp.
Referenced by _subdivideHexahedron().
_copyLine()
void bezierCoeff::_copyLine (const fullMatrix< double > & allSub, int n, int starti, bezierCoeff & sub) static private
Definition at line 1398 of file bezierBasis.cpp.
Referenced by _subdividePrism().
_copyPyr()
void bezierCoeff::_copyPyr (const fullMatrix< double > & allSub, int nij, int nk, int starti, int startj, int startk, bezierCoeff & sub) static private
Definition at line 1437 of file bezierBasis.cpp.
Referenced by _subdividePyramid().
_copyQuad()
void bezierCoeff::_copyQuad (const fullMatrix< double > & allSub, int n, int starti, int startj, bezierCoeff & sub) static private
Definition at line 1407 of file bezierBasis.cpp.
Referenced by _subdivideQuadrangle().
_ij2Index()
static int bezierCoeff::_ij2Index (int i, int j, int n) inline static private
Definition at line 240 of file bezierBasis.h.
Referenced by _subdivideTriangle().
_ijk2Index()
static int bezierCoeff::_ijk2Index (int i, int j, int k, int n) inline static private
Definition at line 244 of file bezierBasis.h.
Referenced by _subdivideTet().
_subdivide() [1/2]
void bezierCoeff::_subdivide (fullMatrix< double > & coeff, int npts, int start) static private
Definition at line 973 of file bezierBasis.cpp.
Referenced by _subdivideHexahedron(), _subdividePrism(), _subdividePyramid(), and _subdivideQuadrangle().
_subdivide() [2/2]
void bezierCoeff::_subdivide (fullMatrix< double > & coeff, int npts, int start, int inc) static private
Definition at line 986 of file bezierBasis.cpp.
_subdivideHexahedron()
void bezierCoeff::_subdivideHexahedron (const bezierCoeff & coeff, std::vector< bezierCoeff * > & subCoeff) static private
Definition at line 1272 of file bezierBasis.cpp.
Referenced by subdivide().
_subdividePrism()
void bezierCoeff::_subdividePrism (const bezierCoeff & coeff, std::vector< bezierCoeff * > & subCoeff) static private
Definition at line 1308 of file bezierBasis.cpp.
Referenced by subdivide().
_subdividePyramid()
void bezierCoeff::_subdividePyramid (const bezierCoeff & coeff, std::vector< bezierCoeff * > & subCoeff) static private
Definition at line 1344 of file bezierBasis.cpp.
Referenced by subdivide().
_subdivideQuadrangle()
void bezierCoeff::_subdivideQuadrangle (const bezierCoeff & coeff, std::vector< bezierCoeff * > & subCoeff) static private
Definition at line 1249 of file bezierBasis.cpp.
Referenced by subdivide().
_subdivideTet()
void bezierCoeff::_subdivideTet (SubdivisionTet which, int n, bezierCoeff & coeff) static private
Definition at line 1086 of file bezierBasis.cpp.
Referenced by _subdivideTetrahedron().
_subdivideTetrahedron()
void bezierCoeff::_subdivideTetrahedron (const bezierCoeff & coeff, std::vector< bezierCoeff * > & vSubCoeff) static private
Definition at line 1206 of file bezierBasis.cpp.
Referenced by subdivide().
_subdivideTriangle()
void bezierCoeff::_subdivideTriangle (const bezierCoeff & coeff, int start, std::vector< bezierCoeff * > & subCoeff) static private
Definition at line 1001 of file bezierBasis.cpp.
Referenced by _subdividePrism(), and subdivide().
getBezierBasis()
const bezierBasis* bezierCoeff::getBezierBasis () const inline
Definition at line 184 of file bezierBasis.h.
Referenced by jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), and jacobianBasedQuality::_coeffDataICN::_computeLowerBound().
getCornerCoeff() [1/2]
double bezierCoeff::getCornerCoeff (int k) const inline
Definition at line 173 of file bezierBasis.h.
Referenced by jacobianBasedQuality::_coeffDataJac::_coeffDataJac(), and getCornerCoeffs().
getCornerCoeff() [2/2]
double bezierCoeff::getCornerCoeff (int k, int j) const inline
Definition at line 177 of file bezierBasis.h.
getCornerCoeffs() [1/2]
void bezierCoeff::getCornerCoeffs (fullMatrix< double > & m) const
Definition at line 928 of file bezierBasis.cpp.
getCornerCoeffs() [2/2]
void bezierCoeff::getCornerCoeffs (fullVector< double > & v) const
Definition at line 921 of file bezierBasis.cpp.
Referenced by jacobianBasedQuality::_coeffDataIGE::_computeAtCorner(), and jacobianBasedQuality::_coeffDataICN::_computeAtCorner().
getDataPtr()
double* bezierCoeff::getDataPtr () inline
Definition at line 183 of file bezierBasis.h.
Referenced by MElement::idealJacRange(), and MElement::scaledJacRange().
getIdxCornerCoeff()
int bezierCoeff::getIdxCornerCoeff (int i) const
Definition at line 846 of file bezierBasis.cpp.
Referenced by getCornerCoeff(), and getCornerCoeffs().
getNumCoeff()
int bezierCoeff::getNumCoeff () const inline
Definition at line 169 of file bezierBasis.h.
Referenced by jacobianBasedQuality::_coeffDataJac::_coeffDataJac(), MElement::idealJacRange(), MElementBB(), and MElement::scaledJacRange().
getNumColumns()
int bezierCoeff::getNumColumns () const inline
Definition at line 170 of file bezierBasis.h.
Referenced by _subdivideTet().
getNumCornerCoeff()
int bezierCoeff::getNumCornerCoeff () const inline
Definition at line 171 of file bezierBasis.h.
Referenced by jacobianBasedQuality::_coeffDataJac::_coeffDataJac(), and getCornerCoeffs().
getPolynomialOrder()
int bezierCoeff::getPolynomialOrder () const inline
Definition at line 165 of file bezierBasis.h.
Referenced by _subdivideHexahedron(), _subdividePrism(), _subdivideQuadrangle(), _subdivideTetrahedron(), and _subdivideTriangle().
operator()() [1/4]
double& bezierCoeff::operator() (int i) inline
Definition at line 200 of file bezierBasis.h.
operator()() [2/4]
double bezierCoeff::operator() (int i) const inline
Definition at line 197 of file bezierBasis.h.
operator()() [3/4]
double& bezierCoeff::operator() (int i, int j) inline
Definition at line 201 of file bezierBasis.h.
operator()() [4/4]
double bezierCoeff::operator() (int i, int j) const inline
Definition at line 198 of file bezierBasis.h.
releasePools()
void bezierCoeff::releasePools () static
Definition at line 830 of file bezierBasis.cpp.
setMatrixAsProxy()
void bezierCoeff::setMatrixAsProxy (fullMatrix< double > & m) const inline
Definition at line 186 of file bezierBasis.h.
Referenced by jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), and jacobianBasedQuality::_coeffDataICN::_computeLowerBound().
setVectorAsProxy()
void bezierCoeff::setVectorAsProxy (fullVector< double > & v) const inline
Definition at line 190 of file bezierBasis.h.
Referenced by jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), and jacobianBasedQuality::_coeffDataICN::_computeLowerBound().
subdivide()
void bezierCoeff::subdivide (std::vector< bezierCoeff * > & subCoeff) const
Definition at line 938 of file bezierBasis.cpp.
Referenced by jacobianBasedQuality::_coeffDataJac::getSubCoeff(), jacobianBasedQuality::_coeffDataIGE::getSubCoeff(), and jacobianBasedQuality::_coeffDataICN::getSubCoeff().
updateDataPtr()
void bezierCoeff::updateDataPtr (long diff)
Definition at line 838 of file bezierBasis.cpp.
usePools()
void bezierCoeff::usePools (std::size_t size0, std::size_t size1) static
Definition at line 818 of file bezierBasis.cpp.
Referenced by jacobianBasedQuality::minICNMeasure(), jacobianBasedQuality::minIGEMeasure(), and jacobianBasedQuality::minMaxJacobianDeterminant().
Member Data Documentation
_basis
const bezierBasis* bezierCoeff::_basis private
Definition at line 131 of file bezierBasis.h.
Referenced by _computeCoefficients(), bezierCoeff(), getBezierBasis(), and getNumCornerCoeff().
_c
int bezierCoeff::_c private
Definition at line 132 of file bezierBasis.h.
Referenced by _computeCoefficients(), _copy(), _subdivideHexahedron(), _subdividePrism(), _subdividePyramid(), _subdivideQuadrangle(), _subdivideTriangle(), bezierCoeff(), getCornerCoeffs(), getNumColumns(), and setMatrixAsProxy().
_data
double* bezierCoeff::_data private
Definition at line 133 of file bezierBasis.h.
Referenced by _computeCoefficients(), bezierCoeff(), getCornerCoeff(), getCornerCoeffs(), getDataPtr(), operator()(), setMatrixAsProxy(), setVectorAsProxy(), updateDataPtr(), and ~bezierCoeff().
_funcSpaceData
FuncSpaceData bezierCoeff::_funcSpaceData private
Definition at line 130 of file bezierBasis.h.
Referenced by _computeCoefficients(), _subdividePyramid(), bezierCoeff(), getIdxCornerCoeff(), getPolynomialOrder(), and subdivide().
_numPool
int bezierCoeff::_numPool private
Definition at line 129 of file bezierBasis.h.
Referenced by bezierCoeff(), and ~bezierCoeff().
_ownData
bool bezierCoeff::_ownData private
Definition at line 134 of file bezierBasis.h.
Referenced by bezierCoeff(), updateDataPtr(), and ~bezierCoeff().
_pool0
bezierCoeffMemoryPool * bezierCoeff::_pool0 = nullptr static private
Definition at line 136 of file bezierBasis.h.
Referenced by bezierCoeff(), releasePools(), usePools(), and ~bezierCoeff().
_pool1
bezierCoeffMemoryPool * bezierCoeff::_pool1 = nullptr static private
Definition at line 137 of file bezierBasis.h.
Referenced by bezierCoeff(), releasePools(), usePools(), and ~bezierCoeff().
_r
int bezierCoeff::_r private
Definition at line 132 of file bezierBasis.h.
Referenced by _computeCoefficients(), bezierCoeff(), getCornerCoeff(), getCornerCoeffs(), getIdxCornerCoeff(), getNumCoeff(), operator()(), setMatrixAsProxy(), and setVectorAsProxy().
_sub
fullMatrix< double > bezierCoeff::_sub = fullMatrix<double>() static private
Definition at line 138 of file bezierBasis.h.
Referenced by _subdivideHexahedron(), _subdividePrism(), _subdividePyramid(), and _subdivideQuadrangle().
The documentation for this class was generated from the following files:
src/numeric/bezierBasis.h
src/numeric/bezierBasis.cpp