gmsh-TingyuanDoc: linearSystemBase Class Reference
linearSystemBase Class Reference abstract
#include <linearSystem.h>
Public Member Functions
virtual ~linearSystemBase ()
virtual bool isAllocated () const =0
virtual void allocate (int nbRows)=0
virtual void preAllocateEntries ()
virtual void clear ()=0
virtual void zeroMatrix ()=0
virtual void zeroRightHandSide ()=0
virtual void zeroSolution ()=0
virtual int systemSolve ()=0
virtual int matMult ()
void setParameter (const std::string &key, std::string value)
std::string getParameter (const std::string &key) const
virtual void insertInSparsityPattern (int _row, int _col)
virtual double normInfRightHandSide () const =0
virtual double normInfSolution () const
Protected Attributes
std::map< std::string, std::string > _parameters
Detailed Description
Definition at line 14 of file linearSystem.h.
Constructor & Destructor Documentation
~linearSystemBase()
virtual linearSystemBase::~linearSystemBase () inline virtual
Definition at line 19 of file linearSystem.h.
Member Function Documentation
allocate()
virtual void linearSystemBase::allocate (int nbRows) pure virtual
Implemented in linearSystemCSR< scalar >, linearSystemCSR< scalar >, linearSystemCSR< scalar >, linearSystemPETSc< scalar >, linearSystemGmm< scalar >, and linearSystemFull< scalar >.
Referenced by dofManager< double >::assemble(), and dofManager< double >::insertInSparsityPattern().
clear()
virtual void linearSystemBase::clear () pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemGmm< scalar >, linearSystemCSR< scalar >, and linearSystemFull< scalar >.
getParameter()
std::string linearSystemBase::getParameter (const std::string & key) const
Definition at line 17 of file linearSystem.cpp.
insertInSparsityPattern()
virtual void linearSystemBase::insertInSparsityPattern (int _row, int _col) inline virtual
Reimplemented in linearSystemCSR< scalar >.
Definition at line 33 of file linearSystem.h.
Referenced by computeParametrization(), and dofManager< double >::insertInSparsityPattern().
isAllocated()
virtual bool linearSystemBase::isAllocated () const pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemGmm< scalar >, linearSystemCSR< scalar >, and linearSystemFull< scalar >.
Referenced by dofManager< double >::assemble(), elasticitySolver::exportKb(), dofManager< double >::insertInSparsityPattern(), and setParameter().
matMult()
virtual int linearSystemBase::matMult () inline virtual
Reimplemented in linearSystemPETSc< scalar >.
Definition at line 29 of file linearSystem.h.
normInfRightHandSide()
virtual double linearSystemBase::normInfRightHandSide () const pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemCSR< scalar >, linearSystemGmm< scalar >, and linearSystemFull< scalar >.
normInfSolution()
virtual double linearSystemBase::normInfSolution () const inline virtual
Definition at line 35 of file linearSystem.h.
preAllocateEntries()
virtual void linearSystemBase::preAllocateEntries () inline virtual
Reimplemented in linearSystemCSR< scalar >, linearSystemCSR< scalar >, and linearSystemCSR< scalar >.
Definition at line 22 of file linearSystem.h.
setParameter()
void linearSystemBase::setParameter (const std::string & key, std::string value)
Definition at line 10 of file linearSystem.cpp.
Referenced by computeParametrization().
systemSolve()
virtual int linearSystemBase::systemSolve () pure virtual
Implemented in linearSystemCSRGmm< scalar >, linearSystemPETSc< scalar >, linearSystemGmm< scalar >, and linearSystemFull< scalar >.
Referenced by dofManager< double >::systemSolve().
zeroMatrix()
virtual void linearSystemBase::zeroMatrix () pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemCSR< scalar >, linearSystemGmm< scalar >, and linearSystemFull< scalar >.
Referenced by dofManager< double >::systemClear().
zeroRightHandSide()
virtual void linearSystemBase::zeroRightHandSide () pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemCSR< scalar >, linearSystemGmm< scalar >, and linearSystemFull< scalar >.
Referenced by dofManager< double >::systemClear().
zeroSolution()
virtual void linearSystemBase::zeroSolution () pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemCSR< scalar >, linearSystemGmm< scalar >, and linearSystemFull< scalar >.
Member Data Documentation
_parameters
std::map<std::string, std::string> linearSystemBase::_parameters protected
Definition at line 16 of file linearSystem.h.
Referenced by getParameter(), and setParameter().
The documentation for this class was generated from the following files:
src/solver/linearSystem.h
src/solver/linearSystem.cpp