gmsh-TingyuanDoc: GMSH_Plugin Class Reference
GMSH_Plugin Class Reference abstract
#include <Plugin.h>
Public Types
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Public Member Functions
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual GMSH_PLUGIN_TYPE getType () const =0
virtual std::string getName () const =0
virtual std::string getShortHelp () const =0
virtual std::string getHelp () const =0
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
virtual int getNbOptions () const
virtual StringXNumber * getOption (int iopt)
virtual int getNbOptionsStr () const
virtual StringXString * getOptionStr (int iopt)
std::string serialize ()
virtual int run ()=0
Static Public Member Functions
static void setDrawFunction (void(*fct)(void *))
Public Attributes
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes
static void(* draw)(void *) = nullptr
Detailed Description
Definition at line 26 of file Plugin.h.
Member Enumeration Documentation
GMSH_PLUGIN_TYPE
enum GMSH_Plugin::GMSH_PLUGIN_TYPE
Enumerator
GMSH_CAD_PLUGIN
GMSH_MESH_PLUGIN
GMSH_POST_PLUGIN
GMSH_SOLVER_PLUGIN
Definition at line 29 of file Plugin.h.
Constructor & Destructor Documentation
GMSH_Plugin()
GMSH_Plugin::GMSH_Plugin () inline
Definition at line 42 of file Plugin.h.
~GMSH_Plugin()
virtual GMSH_Plugin::~GMSH_Plugin () inline virtual
Definition at line 43 of file Plugin.h.
Member Function Documentation
catchErrorMessage()
void GMSH_Plugin::catchErrorMessage (char * errorMessage) const virtual
Definition at line 38 of file Plugin.cpp.
getAuthor()
virtual std::string GMSH_Plugin::getAuthor () const inline virtual
Reimplemented in GMSH_VoroMetalPlugin, GMSH_AnalyseMeshQualityPlugin, GMSH_SpanningTreePlugin, GMSH_ShowNeighborElementsPlugin, GMSH_NearToFarFieldPlugin, GMSH_BoundaryAnglesPlugin, GMSH_DistancePlugin, GMSH_CurvedBndDistPlugin, GMSH_DiscretizationErrorPlugin, GMSH_CutMeshPlugin, GMSH_Lambda2Plugin, GMSH_MeshVolumePlugin, and GMSH_LongituteLatitudePlugin.
Definition at line 50 of file Plugin.h.
Referenced by PluginManager::addPlugin().
getCopyright()
virtual std::string GMSH_Plugin::getCopyright () const inline virtual
Definition at line 51 of file Plugin.h.
getHelp()
virtual std::string GMSH_Plugin::getHelp () const pure virtual
Implemented in GMSH_VoroMetalPlugin, GMSH_AnalyseMeshQualityPlugin, GMSH_SpanningTreePlugin, GMSH_CutParametricPlugin, GMSH_CutBoxPlugin, GMSH_ShowNeighborElementsPlugin, GMSH_CutGridPlugin, GMSH_CutPlanePlugin, GMSH_NearToFarFieldPlugin, GMSH_AnnotatePlugin, GMSH_BoundaryAnglesPlugin, GMSH_CutSpherePlugin, GMSH_DistancePlugin, GMSH_ParticlesPlugin, GMSH_StreamLinesPlugin, GMSH_ProbePlugin, GMSH_Scal2TensPlugin, GMSH_SummationPlugin, GMSH_BubblesPlugin, GMSH_CurlPlugin, GMSH_CurvedBndDistPlugin, GMSH_CVTRemeshPlugin, GMSH_DiscretizationErrorPlugin, GMSH_DivergencePlugin, GMSH_EigenvaluesPlugin, GMSH_EigenvectorsPlugin, GMSH_ExtractEdgesPlugin, GMSH_ExtractElementsPlugin, GMSH_FieldFromAmplitudePhasePlugin, GMSH_GradientPlugin, GMSH_HarmonicToTimePlugin, GMSH_InvisiblePlugin, GMSH_MakeSimplexPlugin, GMSH_MathEvalPlugin, GMSH_MeshSizeFieldViewPlugin, GMSH_ModifyComponentsPlugin, GMSH_ModulusPhasePlugin, GMSH_NearestNeighborPlugin, GMSH_NewViewPlugin, GMSH_RemovePlugin, GMSH_Scal2VecPlugin, GMSH_TransformPlugin, GMSH_WarpPlugin, GMSH_IsosurfacePlugin, GMSH_CrackPlugin, GMSH_CutMeshPlugin, GMSH_GaussPointsPlugin, GMSH_IntegratePlugin, GMSH_Lambda2Plugin, GMSH_MeshSubEntitiesPlugin, GMSH_MeshVolumePlugin, GMSH_MinMaxPlugin, GMSH_SimplePartitionPlugin, GMSH_SkinPlugin, GMSH_SmoothPlugin, GMSH_SphericalRaisePlugin, GMSH_TetrahedralizePlugin, GMSH_TriangulatePlugin, and GMSH_LongituteLatitudePlugin.
Referenced by PrintOptionsDoc().
getName()
virtual std::string GMSH_Plugin::getName () const pure virtual
Implemented in GMSH_VoroMetalPlugin, GMSH_AnalyseMeshQualityPlugin, GMSH_SpanningTreePlugin, GMSH_CutParametricPlugin, GMSH_CutBoxPlugin, GMSH_ShowNeighborElementsPlugin, GMSH_CutGridPlugin, GMSH_AnnotatePlugin, GMSH_DistancePlugin, GMSH_CutPlanePlugin, GMSH_NearToFarFieldPlugin, GMSH_BoundaryAnglesPlugin, GMSH_CutSpherePlugin, GMSH_ProbePlugin, GMSH_IsosurfacePlugin, GMSH_ParticlesPlugin, GMSH_StreamLinesPlugin, GMSH_BubblesPlugin, GMSH_CrackPlugin, GMSH_CurlPlugin, GMSH_CurvedBndDistPlugin, GMSH_CutMeshPlugin, GMSH_CVTRemeshPlugin, GMSH_DiscretizationErrorPlugin, GMSH_DivergencePlugin, GMSH_EigenvaluesPlugin, GMSH_EigenvectorsPlugin, GMSH_ExtractEdgesPlugin, GMSH_ExtractElementsPlugin, GMSH_FieldFromAmplitudePhasePlugin, GMSH_GaussPointsPlugin, GMSH_GradientPlugin, GMSH_HarmonicToTimePlugin, GMSH_IntegratePlugin, GMSH_InvisiblePlugin, GMSH_Lambda2Plugin, GMSH_MakeSimplexPlugin, GMSH_MathEvalPlugin, GMSH_MeshSizeFieldViewPlugin, GMSH_MeshSubEntitiesPlugin, GMSH_MeshVolumePlugin, GMSH_MinMaxPlugin, GMSH_ModifyComponentsPlugin, GMSH_ModulusPhasePlugin, GMSH_NearestNeighborPlugin, GMSH_NewViewPlugin, GMSH_RemovePlugin, GMSH_Scal2TensPlugin, GMSH_Scal2VecPlugin, GMSH_SimplePartitionPlugin, GMSH_SkinPlugin, GMSH_SmoothPlugin, GMSH_SphericalRaisePlugin, GMSH_SummationPlugin, GMSH_TetrahedralizePlugin, GMSH_TransformPlugin, GMSH_TriangulatePlugin, GMSH_WarpPlugin, and GMSH_LongituteLatitudePlugin.
Referenced by PluginManager::addPlugin(), catchErrorMessage(), PrintOptionsDoc(), and serialize().
getNbOptions()
virtual int GMSH_Plugin::getNbOptions () const inline virtual
Reimplemented in GMSH_VoroMetalPlugin, GMSH_AnalyseMeshQualityPlugin, GMSH_SpanningTreePlugin, GMSH_CutParametricPlugin, GMSH_ShowNeighborElementsPlugin, GMSH_CutBoxPlugin, GMSH_CutGridPlugin, GMSH_NearToFarFieldPlugin, GMSH_BoundaryAnglesPlugin, GMSH_CutPlanePlugin, GMSH_AnnotatePlugin, GMSH_CutSpherePlugin, GMSH_DistancePlugin, GMSH_ParticlesPlugin, GMSH_StreamLinesPlugin, GMSH_DiscretizationErrorPlugin, GMSH_ProbePlugin, GMSH_Scal2TensPlugin, GMSH_SummationPlugin, GMSH_BubblesPlugin, GMSH_CurlPlugin, GMSH_CVTRemeshPlugin, GMSH_DivergencePlugin, GMSH_EigenvaluesPlugin, GMSH_EigenvectorsPlugin, GMSH_ExtractEdgesPlugin, GMSH_ExtractElementsPlugin, GMSH_FieldFromAmplitudePhasePlugin, GMSH_GradientPlugin, GMSH_HarmonicToTimePlugin, GMSH_InvisiblePlugin, GMSH_MakeSimplexPlugin, GMSH_MathEvalPlugin, GMSH_MeshSizeFieldViewPlugin, GMSH_ModifyComponentsPlugin, GMSH_ModulusPhasePlugin, GMSH_NearestNeighborPlugin, GMSH_NewViewPlugin, GMSH_RemovePlugin, GMSH_Scal2VecPlugin, GMSH_TransformPlugin, GMSH_WarpPlugin, GMSH_IsosurfacePlugin, GMSH_CutMeshPlugin, GMSH_Lambda2Plugin, GMSH_MeshVolumePlugin, GMSH_CrackPlugin, GMSH_GaussPointsPlugin, GMSH_IntegratePlugin, GMSH_LongituteLatitudePlugin, GMSH_MeshSubEntitiesPlugin, GMSH_MinMaxPlugin, GMSH_SimplePartitionPlugin, GMSH_SkinPlugin, GMSH_SmoothPlugin, GMSH_SphericalRaisePlugin, GMSH_TetrahedralizePlugin, and GMSH_TriangulatePlugin.
Definition at line 61 of file Plugin.h.
Referenced by GMSH_PostPlugin::executeRemote(), PrintOptionsDoc(), serialize(), and PluginManager::setPluginOption().
getNbOptionsStr()
virtual int GMSH_Plugin::getNbOptionsStr () const inline virtual
Reimplemented in GMSH_VoroMetalPlugin, GMSH_SpanningTreePlugin, GMSH_CutParametricPlugin, GMSH_NearToFarFieldPlugin, GMSH_BoundaryAnglesPlugin, GMSH_AnnotatePlugin, GMSH_Scal2TensPlugin, GMSH_SummationPlugin, GMSH_BubblesPlugin, GMSH_FieldFromAmplitudePhasePlugin, GMSH_MathEvalPlugin, GMSH_ModifyComponentsPlugin, GMSH_NewViewPlugin, GMSH_Scal2VecPlugin, and GMSH_SimplePartitionPlugin.
Definition at line 65 of file Plugin.h.
Referenced by PrintOptionsDoc(), serialize(), and PluginManager::setPluginOption().
getOption()
virtual StringXNumber* GMSH_Plugin::getOption (int iopt) inline virtual
Reimplemented in GMSH_AnalyseMeshQualityPlugin, GMSH_ShowNeighborElementsPlugin, GMSH_VoroMetalPlugin, GMSH_SpanningTreePlugin, GMSH_CutParametricPlugin, GMSH_CutBoxPlugin, GMSH_CutGridPlugin, GMSH_NearToFarFieldPlugin, GMSH_BoundaryAnglesPlugin, GMSH_CutPlanePlugin, GMSH_AnnotatePlugin, GMSH_CutSpherePlugin, GMSH_DistancePlugin, GMSH_ParticlesPlugin, GMSH_StreamLinesPlugin, GMSH_DiscretizationErrorPlugin, GMSH_ProbePlugin, GMSH_Scal2TensPlugin, GMSH_SummationPlugin, GMSH_BubblesPlugin, GMSH_CurlPlugin, GMSH_CVTRemeshPlugin, GMSH_DivergencePlugin, GMSH_EigenvaluesPlugin, GMSH_EigenvectorsPlugin, GMSH_ExtractEdgesPlugin, GMSH_ExtractElementsPlugin, GMSH_FieldFromAmplitudePhasePlugin, GMSH_GradientPlugin, GMSH_HarmonicToTimePlugin, GMSH_InvisiblePlugin, GMSH_MakeSimplexPlugin, GMSH_MathEvalPlugin, GMSH_MeshSizeFieldViewPlugin, GMSH_ModifyComponentsPlugin, GMSH_ModulusPhasePlugin, GMSH_NearestNeighborPlugin, GMSH_NewViewPlugin, GMSH_RemovePlugin, GMSH_Scal2VecPlugin, GMSH_TransformPlugin, GMSH_WarpPlugin, GMSH_IsosurfacePlugin, GMSH_CutMeshPlugin, GMSH_Lambda2Plugin, GMSH_MeshVolumePlugin, GMSH_CrackPlugin, GMSH_GaussPointsPlugin, GMSH_IntegratePlugin, GMSH_LongituteLatitudePlugin, GMSH_MeshSubEntitiesPlugin, GMSH_MinMaxPlugin, GMSH_SimplePartitionPlugin, GMSH_SkinPlugin, GMSH_SmoothPlugin, GMSH_SphericalRaisePlugin, GMSH_TetrahedralizePlugin, and GMSH_TriangulatePlugin.
Definition at line 62 of file Plugin.h.
Referenced by GMSH_PostPlugin::executeRemote(), PrintOptionsDoc(), serialize(), and PluginManager::setPluginOption().
getOptionStr()
virtual StringXString* GMSH_Plugin::getOptionStr (int iopt) inline virtual
Reimplemented in GMSH_VoroMetalPlugin, GMSH_SpanningTreePlugin, GMSH_CutParametricPlugin, GMSH_NearToFarFieldPlugin, GMSH_BoundaryAnglesPlugin, GMSH_AnnotatePlugin, GMSH_Scal2TensPlugin, GMSH_SummationPlugin, GMSH_BubblesPlugin, GMSH_FieldFromAmplitudePhasePlugin, GMSH_MathEvalPlugin, GMSH_ModifyComponentsPlugin, GMSH_NewViewPlugin, GMSH_Scal2VecPlugin, and GMSH_SimplePartitionPlugin.
Definition at line 66 of file Plugin.h.
Referenced by PrintOptionsDoc(), serialize(), and PluginManager::setPluginOption().
getShortHelp()
virtual std::string GMSH_Plugin::getShortHelp () const pure virtual
Implemented in GMSH_VoroMetalPlugin, GMSH_AnalyseMeshQualityPlugin, GMSH_SpanningTreePlugin, GMSH_CutParametricPlugin, GMSH_CutBoxPlugin, GMSH_ShowNeighborElementsPlugin, GMSH_CutGridPlugin, GMSH_AnnotatePlugin, GMSH_DistancePlugin, GMSH_CutPlanePlugin, GMSH_NearToFarFieldPlugin, GMSH_BoundaryAnglesPlugin, GMSH_CutSpherePlugin, GMSH_ProbePlugin, GMSH_ParticlesPlugin, GMSH_StreamLinesPlugin, GMSH_IsosurfacePlugin, GMSH_BubblesPlugin, GMSH_CrackPlugin, GMSH_CurlPlugin, GMSH_CurvedBndDistPlugin, GMSH_CutMeshPlugin, GMSH_CVTRemeshPlugin, GMSH_DiscretizationErrorPlugin, GMSH_DivergencePlugin, GMSH_EigenvaluesPlugin, GMSH_EigenvectorsPlugin, GMSH_ExtractEdgesPlugin, GMSH_ExtractElementsPlugin, GMSH_FieldFromAmplitudePhasePlugin, GMSH_GaussPointsPlugin, GMSH_GradientPlugin, GMSH_HarmonicToTimePlugin, GMSH_IntegratePlugin, GMSH_InvisiblePlugin, GMSH_Lambda2Plugin, GMSH_MakeSimplexPlugin, GMSH_MathEvalPlugin, GMSH_MeshSizeFieldViewPlugin, GMSH_MeshSubEntitiesPlugin, GMSH_MeshVolumePlugin, GMSH_MinMaxPlugin, GMSH_ModifyComponentsPlugin, GMSH_ModulusPhasePlugin, GMSH_NearestNeighborPlugin, GMSH_NewViewPlugin, GMSH_RemovePlugin, GMSH_Scal2TensPlugin, GMSH_Scal2VecPlugin, GMSH_SimplePartitionPlugin, GMSH_SkinPlugin, GMSH_SmoothPlugin, GMSH_SphericalRaisePlugin, GMSH_SummationPlugin, GMSH_TetrahedralizePlugin, GMSH_TransformPlugin, GMSH_TriangulatePlugin, GMSH_WarpPlugin, and GMSH_LongituteLatitudePlugin.
getType()
virtual GMSH_PLUGIN_TYPE GMSH_Plugin::getType () const pure virtual
Implemented in GMSH_MeshPlugin, GMSH_SolverPlugin, and GMSH_PostPlugin.
Referenced by PluginManager::findSolverPlugin().
run()
virtual int GMSH_Plugin::run () pure virtual
Implemented in GMSH_MeshPlugin, GMSH_SolverPlugin, GMSH_PostPlugin, GMSH_SpanningTreePlugin, GMSH_SimplePartitionPlugin, and GMSH_CutMeshPlugin.
Referenced by PluginManager::action().
serialize()
std::string GMSH_Plugin::serialize ()
Definition at line 44 of file Plugin.cpp.
Referenced by GMSH_PostPlugin::executeRemote().
setDrawFunction()
void GMSH_Plugin::setDrawFunction (void(*)(void *) fct) static
Definition at line 21 of file Plugin.cpp.
Referenced by GMSH_CutBoxPlugin::callback(), GMSH_CutGridPlugin::callback(), GMSH_StreamLinesPlugin::callback(), GMSH_ParticlesPlugin::callback(), GMSH_CutSpherePlugin::callback(), GMSH_CutPlanePlugin::callback(), GMSH_ProbePlugin::callback(), GMSH_AnnotatePlugin::callback(), GMSH_CutParametricPlugin::callback(), GMSH_AnnotatePlugin::callbackStr(), and GMSH_CutParametricPlugin::callbackStr().
Member Data Documentation
dialogBox
PluginDialogBox* GMSH_Plugin::dialogBox
Definition at line 37 of file Plugin.h.
draw
void(* GMSH_Plugin::draw)(void *) = nullptr static
Definition at line 77 of file Plugin.h.
Referenced by GMSH_CutBoxPlugin::callback(), GMSH_CutGridPlugin::callback(), GMSH_ParticlesPlugin::callback(), GMSH_StreamLinesPlugin::callback(), GMSH_CutPlanePlugin::callback(), GMSH_CutSpherePlugin::callback(), GMSH_ProbePlugin::callback(), GMSH_AnnotatePlugin::callback(), GMSH_CutParametricPlugin::callback(), GMSH_AnnotatePlugin::callbackStr(), GMSH_CutParametricPlugin::callbackStr(), drawContext::drawPost(), and setDrawFunction().
hlib
void* GMSH_Plugin::hlib
Definition at line 40 of file Plugin.h.
Referenced by PluginManager::addPlugin().
The documentation for this class was generated from the following files:
src/plugin/Plugin.h
src/plugin/Plugin.cpp