gmsh-TingyuanDoc: Msg Class Reference
Msg Class Reference
#include <GmshMessage.h>
Public Member Functions
Msg ()
Static Public Member Functions
static void Initialize (int argc, char **argv)
static void Finalize ()
static void Exit (int level)
static int GetCommRank ()
static int GetCommSize ()
static void SetCommRank (int val)
static void SetCommSize (int val)
static void SetCallback (GmshMessage *callback)
static GmshMessage * GetCallback ()
static void Barrier ()
static int GetNumThreads ()
static void SetNumThreads (int num)
static int GetMaxThreads ()
static int GetThreadNum ()
static void SetVerbosity (int val)
static void SetLogFile (const std::string &name)
static int GetVerbosity ()
static std::string GetLaunchDate ()
static std::string GetCommandLineFull ()
static std::vector< std::string > & GetCommandLineArgs ()
static std::map< std::string, std::vector< double > > & GetCommandLineNumbers ()
static std::map< std::string, std::string > & GetCommandLineStrings ()
static std::string PrintResources (bool printDate, bool printWallTime, bool printCpu, bool printMem)
static void Error (const char *fmt,...)
static void Warning (const char *fmt,...)
static void Info (const char *fmt,...)
static void RequestRender ()
static void Direct (const char *fmt,...)
static void Auto (const char *fmt,...)
static void StatusBar (bool log, const char *fmt,...)
static void StatusGl (const char *fmt,...)
static void SetWindowTitle (const std::string &title)
static void Debug (const char *fmt,...)
static void StartProgressMeter (int ntotal)
static void ProgressMeter (int n, bool log, const char *fmt,...)
static void StopProgressMeter ()
static void SetProgressMeterStep (int step)
static int GetProgressMeterStep ()
static void SetInfoCpu (bool val)
static void SetInfoMem (bool val)
static double & Timer (const std::string &str)
static void PrintTimers ()
static void ResetErrorCounter ()
static void PrintErrorCounter (const char *title)
static int GetWarningCount ()
static int GetErrorCount ()
static std::string GetFirstWarning ()
static std::string GetFirstError ()
static std::string GetLastError ()
static double GetValue (const char *text, double defaultval)
static std::string GetString (const char *text, const std::string &defaultval)
static int GetAnswer (const char *question, int defaultval, const char *zero, const char *one, const char *two=nullptr)
static void InitializeOnelab (const std::string &name, const std::string &sockname="")
static void FinalizeOnelab ()
static void SetExecutableName (const std::string &name)
static std::string GetExecutableName ()
static void LoadOnelabClient (const std::string &name, const std::string &sockName)
static int GetNumOnelabClients ()
static GmshClient * GetGmshClient ()
static bool UseOnelab ()
static void SetOnelabNumber (const std::string &name, double val, bool visible=true, bool persistent=false, bool readOnly=false, int changedValue=3)
static void SetOnelabNumber (const std::string &name, const std::vector< double > &val, bool visible=true)
static void SetOnelabString (const std::string &name, const std::string &val, bool visible=true, bool persistent=false, bool readOnly=false, int changedValue=3, const std::string &kind="")
static double GetOnelabNumber (const std::string &name, double defaultValue=0., bool errorIfMissing=false)
static std::string GetOnelabString (const std::string &name, const std::string &defaultValue="", bool errorIfMissing=false)
static void AddOnelabStringChoice (const std::string &name, const std::string &kind, const std::string &value, bool updateValue=true, bool readOnly=false, bool visible=true)
static void SetOnelabAction (const std::string &action)
static std::string GetOnelabAction ()
static void ExchangeOnelabParameter (const std::string &key, std::vector< double > &val, std::map< std::string, std::vector< double > > &fopt, std::map< std::string, std::vector< std::string > > &copt)
static void ExchangeOnelabParameter (const std::string &key, std::string &val, std::map< std::string, std::vector< double > > &fopt, std::map< std::string, std::vector< std::string > > &copt)
static void UndefineOnelabParameter (const std::string &name)
static void RunOnelabClient (const std::string &name, const std::string &exe="")
static void SetOnelabChanged (int value, const std::string &client="Gmsh")
static void ImportPhysicalGroupsInOnelab ()
Static Private Attributes
static int _commRank = 0
static int _commSize = 1
static int _verbosity = 5
static int _progressMeterStep = 10
static std::atomic< int > _progressMeterCurrent
static int _progressMeterTotal = 0
static std::map< std::string, double > _timers
static bool _infoCpu = false
static bool _infoMem = false
static double _startTime = 0.
static int _warningCount = 0
static int _errorCount = 0
static int _atLeastOneErrorInRun = 0
static std::string _firstWarning
static std::string _firstError
static std::string _lastError
static GmshMessage * _callback = nullptr
static std::vector< std::string > _commandLineArgs
static std::string _launchDate
static std::map< std::string, std::vector< double > > _commandLineNumbers
static std::map< std::string, std::string > _commandLineStrings
static GmshClient * _client = nullptr
static std::string _execName
static std::string _logFileName
static FILE * _logFile = nullptr
Detailed Description
Definition at line 31 of file GmshMessage.h.
Constructor & Destructor Documentation
Msg()
Msg::Msg () inline
Definition at line 75 of file GmshMessage.h.
Member Function Documentation
AddOnelabStringChoice()
void Msg::AddOnelabStringChoice (const std::string & name, const std::string & kind, const std::string & value, bool updateValue = true, bool readOnly = false, bool visible = true) static
Definition at line 1045 of file GmshMessage.cpp.
Referenced by MergeFile(), and ParseFile().
Auto()
void Msg::Auto (const char * fmt, ...) static
Definition at line 671 of file GmshMessage.cpp.
Barrier()
void Msg::Barrier () static
Definition at line 1619 of file GmshMessage.cpp.
Debug()
void Msg::Debug (const char * fmt, ...) static
Definition at line 752 of file GmshMessage.cpp.
Referenced by CellComplex::_omitCell(), GModel::_readMSH2(), GModel::_readMSH3(), GModel::_readMSH4(), _recombineIntoQuads(), CellComplex::_removeCells(), GModel::addMVertexToVertexCache(), GModel::alignPeriodicBoundaries(), backgroundMesh::backgroundMesh(), blyr_manager::blyr_manager(), bowyerWatson(), bowyerWatsonFrontal(), bowyerWatsonFrontalLayers(), bowyerWatsonParallelograms(), build_chords(), buildBackgroundMesh(), buildConsecutiveListOfVertices(), CellComplex::CellComplex(), SurfaceProjector::clear(), CellComplex::cocombine(), CellComplex::coherent(), CellComplex::combine(), GFace::computeMeanPlane(), computeParametrization(), CellComplex::coreduceComplex(), CellComplex::coreduction(), create_gif(), discreteEdge::createGeometry(), createTopologyFromMesh1D(), GModel::current(), GModel::destroy(), drawContext::drawBackgroundImage(), drawGlyphs(), drawContext::drawImage(), drawContext::drawMesh(), drawContext::drawPost(), GModel::exportDiscreteGEOInternals(), ExtrudeCurve(), ExtrudePoint(), ExtrudeSurface(), faceIsValidQuad(), PView::fillVertexArray(), GModel::fillVertexArrays(), PViewData::findClosestNode(), fixDelaunayCavity(), CellComplex::getACell(), getCandidateExtrudeInfo(), backgroundMesh::getMeshElementByCoord(), GModel::getMeshElementByCoord(), GModel::getMeshElementByTag(), GModel::getMeshElementsByCoord(), GModel::getMeshVertexByTag(), GOrientedTransfiniteFace::GOrientedTransfiniteFace(), GlobalBackgroundMesh::importGModelMeshes(), PViewData::initAdaptiveData(), PViewData::initAdaptiveDataLight(), SurfaceProjector::initialize(), insertAPoint(), CellComplex::insertCell(), insertVerticesInRegion(), InterpolateCurve(), InterpolateSurface(), GEdge::isMeshDegenerated(), laplaceSmoothing(), libOLwrapper::libOLwrapper(), loopTheLoop(), GeomMeshMatcher::matchEdges(), GeomMeshMatcher::matchFaces(), meshGEdgeProcessing(), meshGenerator(), meshGeneratorPeriodic(), MeshSetTransfiniteFacesAutomatic(), MeshTransfiniteSurface(), modifyInitialMeshToRemoveDegeneracies(), gmshFace::normal(), OpenProjectMacFinder(), meshGEdge::operator()(), meshGFace::operator()(), drawPView::operator()(), initPView::operator()(), optimize1DMeshAtAcuteCorners(), OptimizeMesh(), PView::readMSH(), PViewDataGModel::readMSH(), readMSH4Elements(), readMSH4Nodes(), GModel::readPLY(), PView::readPOS(), PViewDataList::readPOS(), GModel::readSTL(), GModel::rebuildMeshElementCache(), GModel::rebuildMeshVertexCache(), recombineIntoQuads(), BDS_Mesh::recover_edge(), CellComplex::reduction(), refineMeshBDS(), RelocateVertices(), CellComplex::removeCell(), removeDiamonds(), removeTwoQuadsNodes(), GModel::renumberMeshVertices(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicateSurfaces(), QuadqsContextUpdater::restoreInitialOption(), scriptAddCommand(), searchAllElements(), PViewData::searchScalar(), PViewData::searchTensor(), PViewData::searchVector(), GRegion::setOutwardOrientationMeshConstraint(), QuadqsContextUpdater::setQuadqsOptions(), SortCurvesConsecutive(), SortEdgeConsecutive(), SortEdgesInLoop(), SplitOptionName(), GEO_Internals::synchronize(), sys3x3_with_tol(), transferSeamGEdgesVerticesToGFace(), VertexArray::VertexArray(), CellComplex::~CellComplex(), GlobalBackgroundMesh::~GlobalBackgroundMesh(), libOLwrapper::~libOLwrapper(), and PView::~PView().
Direct()
void Msg::Direct (const char * fmt, ...) static
Definition at line 634 of file GmshMessage.cpp.
Referenced by ColorTable_Print(), GetOtherOption(), GmshBatch(), PrintBuildInfo(), PrintColorOptions(), PrintColorTable(), PrintNumberOptions(), PrintOptionCategory(), PrintStringOptions(), and PrintUsage().
Error()
void Msg::Error (const char * fmt, ...) static
Definition at line 482 of file GmshMessage.cpp.
Referenced by GEO_Internals::_addCompoundSpline(), _addElements(), _addModelData(), _checkInit(), jacobianBasedQuality::_computeBoundRational(), bezierBasis::_construct(), bezierBasis::_constructPyr(), OctreePost::_create(), _create_splitted_curve(), OCC_Internals::_error(), bezierBasisRaiser::_fillRaiserDataPyr(), _getEntities(), _getEntitiesForElementTypes(), PViewDataList::_getRawData(), CellComplex::_insertCells(), dofManagerBase::_parallelFinalize(), _printTris(), GModel::_readMSH2(), GModel::_readMSH3(), GModel::_readMSH4(), _recombineIntoQuads(), CellComplex::_removeCells(), _removeTwoQuadsNodes(), _sort2_xkws(), jacobianBasedQuality::_subdivideDomainsMinOrMax(), GModel::_writeMSH2(), GModel::_writeMSH3(), GModel::_writeMSH4(), GModel::_writePartitionedMSH3(), adaptiveElements< T >::adapt(), adaptiveElements< T >::adaptForVTK(), GModel::adaptMesh(), BDS_Mesh::add_edge(), GModel::addAutomaticExtrusionConstraints(), GEO_Internals::addBezier(), addBoundaryLayerPoints(), GEO_Internals::addBSpline(), GEO_Internals::addCircleArc(), GEO_Internals::addCurveLoop(), GEO_Internals::addCurveLoops(), GEO_Internals::addDiscreteSurface(), ClosureGen::addEdgeNodes(), GVertex::addElement(), GRegion::addElement(), GEdge::addElement(), GFace::addElement(), addElement2Bucket(), GEO_Internals::addEllipseArc(), addExtrudeNormals(), GEO_Internals::addLine(), addPeriodicEdge(), addPeriodicFace(), GEO_Internals::addPlaneSurface(), GEO_Internals::addSpline(), PView::addStep(), PViewDataList::addStep(), GEO_Internals::addSurfaceFilling(), GEO_Internals::addSurfaceLoop(), addToMap(), GEO_Internals::addVertex(), GEO_Internals::addVolume(), GModel::alignPeriodicBoundaries(), allEdgesLinked(), allFacesLinked(), api(), ApplicationOnShapes(), ApplyTransformationToCurve(), assemble2d(), assemble3d(), Auto(), backgroundMeshAndGuidingFieldExists(), BergotBasis::BergotBasis(), bezierCoeff::bezierCoeff(), BGM_MeshMetric(), BGM_MeshSize(), blyr_manager::blyr_manager(), bowyerWatson(), bowyerWatsonFrontal(), bowyerWatsonFrontalLayers(), bowyerWatsonParallelograms(), bowyerWatsonParallelogramsConstrained(), BuildBackgroundMeshAndGuidingField(), buildConsecutiveListOfVertices(), buildCutMesh(), buildEdgeCavity(), adaptiveElements< T >::buildMapping(), buildMeshGenerationDataStructures(), SOrientedBoundingBox::buildOBB(), splitQuadRecovery::buildPyramids(), Calloc(), carveHole(), GModel::changeEntityTag(), checkConformity(), checkDepends(), GModel::checkMeshCoherence(), gLevelsetPrimitive::choose(), classifyFaces(), SurfaceProjector::closestPoint(), GFace::closestPoint(), closestPointFinder::closestPointFinder(), BDS_Mesh::collapse_edge_parametric(), ColorOption(), colorstobpp(), PView::combine(), PViewDataList::combineSpace(), PViewData::combineSpace(), PViewDataList::combineTime(), PViewDataGModel::combineTime(), PViewData::combineTime(), BDS_Edge::commonvertex(), ComparePosition(), bezierBasisRaiser::computeCoeff(), computeCrossField(), computeCrossFieldAndH(), computeEdgeCut(), computeEdgeLoops(), GModel::computeHomology(), computeParametrization(), computeQuadLayout(), GModel::computeSizeField(), DocRecord::concave(), CondNumBasis::condNumOrder(), GModel::convertOldPartitioningToNewOne(), GEO_Internals::copy(), fullMatrix< double >::copy(), copy_elements(), copy_periodicity(), copy_vertices(), copyMesh(), PixelBuffer::copyPixels(), MElementFactory::create(), elementFactory::create(), create_gif(), create_jpeg(), create_png(), create_ppm(), create_yuv(), CreateCurve(), createEdgeLinks(), createElementMSH2(), discreteRegion::createGeometry(), discreteEdge::createGeometry(), discreteFace::createGeometry(), GModel::createGeometryOfDiscreteEntities(), createHexPri(), CreateOutputFile(), drawContext::createQuadricsAndDisplayLists(), createQuaTri(), createTopologyFromMesh1D(), cVecRead(), nodalBasis::dddf(), nodalBasis::ddf(), VertexArray::decodeHeader(), MakeSimplex::decompose(), delaunayMeshIn2D(), delaunayMeshIn3DHxt(), delaunayTrgl(), delaunayTriangulation(), FieldManager::deleteField(), pyramidalBasis::df(), polynomialBasis::df(), dimTags2String(), discretizeCurve(), dVecRead(), eigen(), EndCurve(), ExchangeOnelabParameter(), GMSH_IntegratePlugin::execute(), GMSH_GaussPointsPlugin::execute(), GMSH_MeshSubEntitiesPlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_TetrahedralizePlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_TriangulatePlugin::execute(), GMSH_CrackPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_CurvedBndDistPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_EigenvaluesPlugin::execute(), GMSH_EigenvectorsPlugin::execute(), GMSH_ExtractEdgesPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_MeshSizeFieldViewPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_NewViewPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_BubblesPlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_SummationPlugin::execute(), GMSH_DistancePlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GMSH_VoroMetalPlugin::execute(), GMSH_PostPlugin::executeRemote(), GModel::exportDiscreteGEOInternals(), ExtrudeParams::Extrude(), blyr_manager::extrude_one_external(), blyr_manager::extrude_vertices(), blyr_manager::extrude_vertices_on_edges(), ExtrudeCurve(), extrudeMesh(), ExtrudePoint(), ExtrudeShapes(), ExtrudeSurface(), pyramidalBasis::f(), polynomialBasis::f(), PixelBuffer::fill(), fillCorrespondingNodes(), PViewDataRemote::fillRemoteVertexArrays(), PView::fillVertexArray(), filterPoints(), PViewDataGModel::finalize(), VTKData::finalizeVTKFile(), gmshSurface::firstDer(), fixDelaunayCavity(), FixPeriodicMesh(), GeomMeshMatcher::forceTomatch(), bezierCoeffMemoryPool::freeMemory(), PViewData::fromVector(), FuncSpaceData::FuncSpaceData(), GEdgeSigned::GEdgeSigned(), ClosureGen::generateFaceClosurePrismFull(), drawContext::generateTextureForImage(), gaussIntegration::get(), LaplaceTerm< T1, T2 >::get(), fullMatrix< double >::get(), backgroundMesh::getAngle(), GModel::getBoundaryTags(), BoundaryLayerColumns::getColumn(), GMSH_PostPlugin::getDataList(), ElementType::getDimension(), MElement::getEdgeInfo(), getEdgeVertices(), getEdgeVerticesOnGeo(), MElement::getEigenvaluesMetric(), PViewData::getElement(), PViewData::getEntity(), getExtrudedVertices(), MPrism::getFaceInfo(), MTriangle::getFaceInfo(), MTetrahedron::getFaceInfo(), MQuadrangle::getFaceInfo(), MHexahedron::getFaceInfo(), MPyramid::getFaceInfo(), MElement::getFaceInfo(), getFaceVertices(), dofManager< double >::getFixedDofValue(), linearSystemCSR< scalar >::getFromMatrix(), getGaussJacobiQuadrature(), GetGeometryOption(), MElement::getGradShapeFunctions(), MElement::getHessShapeFunctions(), MElement::getHighOrderFace(), bezierCoeff::getIdxCornerCoeff(), MElement::getInfoMSH(), MElement::getIntegrationPoints(), SolverField< T >::getKeys(), PViewData::getListPointers(), GModel::getMEdge(), GetMeshOption(), getMeshVertices(), gmshSurface::getMetricEigenvalue(), GFace::getMetricEigenvalue(), GModel::getMFace(), PViewData::getModel(), BasisFactory::getNodalBasis(), cartesianBox< scalar >::getNodalValuesForCell(), getNodeCopies(), BDS_Face::getNodes(), PViewDataGModel::getNumValues(), GetOnelabNumber(), GetOnelabString(), Field::getOption(), GetOptions(), FuncSpaceData::getOrderForBezier(), GetOtherOption(), ElementType::getParentType(), GetPostProcessingOption(), blyr_manager::getRidge(), MElement::getShapeFunctions(), GetSolverOption(), gmshSurface::getSurface(), MElement::getThirdDerivativeShapeFunctions(), ElementType::getType(), MLineN::getTypeForMSH(), MPyramidN::getTypeForMSH(), MTriangleN::getTypeForMSH(), MTetrahedronN::getTypeForMSH(), MQuadrangleN::getTypeForMSH(), MPrismN::getTypeForMSH(), MHexahedronN::getTypeForMSH(), PViewDataGModel::getValue(), GOrientedTransfiniteFace::getVertex(), MElement::getVertexInfo(), GMSH_PostPlugin::getView(), GFace2PolyMesh(), GFaceInitialMesh(), bezierCoeffMemoryPool::giveBlock(), GmshBatch(), GmshFLTK(), gmshGenerateMonomials(), gmshGenerateMonomialsPyramidGeneral(), gmshGenerateOrderedMonomials(), gmshGeneratePoints(), gmshLineSearch(), GmshRemote(), gmshViewGetModelData(), GlobalBackgroundMesh::importGModelMeshes(), PViewDataList::importList(), PViewData::importLists(), GModel::importOCCShape(), initializeOctantBuckets(), InitializeOnelab(), insertAPoint(), inSphereTest_s(), MElement::integrateCirc(), element::integrateCirculation(), element::integrateFlux(), MElement::integrateFlux(), MFace::interpolate(), InterpolateCurve(), InterpolateExtrudedSurface(), InterpolateRuledSurface(), InterpolateSurface(), GEO_Internals::intersectCurvesWithSurface(), IntersectCurvesWithSurface(), inv2x2(), inv3x3(), STensor3::invert(), fullMatrix< double >::invert(), fullMatrix< double >::invertInPlace(), JacobianBasis::jacobianMatrixSpace(), JacobianBasis::jacobianOrder(), laplaceSmoothing(), LC_MVertex_CURV_ANISO(), GEdge::length(), linearSystemGmm< scalar >::linearSystemGmm(), linearSystemPETSc< scalar >::linearSystemPETSc(), List_Pointer(), List_Pointer_NoChange(), List_Put(), List_Read(), List_Write(), fullMatrix< double >::luFactor(), fullMatrix< double >::luSolve(), fullMatrix< double >::luSubstitute(), MakeMeshConformal(), DocRecord::MakeMeshWithPoints(), DocRecord::makePosView(), Malloc(), GeomMeshMatcher::match(), GeomMeshMatcher::matchFaces(), mathEvaluator::mathEvaluator(), mediancut(), MergeFile(), MergePostProcessingFile(), GEO_Internals::mergeVertices(), GModel::mesh(), Mesh2DWithBoundaryLayers(), Mesh3D(), MeshDelaunayVolume(), MeshExtrudedCurve(), MeshExtrudedSurface(), meshGenerator(), meshGeneratorPeriodic(), meshGFaceBamg(), meshGFaceQuadrangulateBipartiteLabelling(), meshGRegionHxt(), meshGRegionNetgen(), MeshTransfiniteSurface(), MeshTransfiniteVolume(), GEO_Internals::modifyPhysicalGroup(), MPolyhedron::MPolyhedron(), myLine::myLine(), FieldManager::newField(), GEO_Internals::newGeometryPolarSphere(), GEO_Internals::newGeometrySphere(), gmshParametricSurface::NewParametricSurface(), gmshPolarSphere::NewPolarSphere(), gmshSphere::NewSphere(), nextOne(), gmshSurface::normal(), NumberOption(), MElement::numEdge2numVertex(), simpleFunctionPython::operator()(), meshGFace::operator()(), FieldPython::operator()(), meshGRegionExtruded::operator()(), optimizeMeshGRegionNetgen::operator()(), backgroundMesh::operator()(), meshMetric::operator()(), F_Transfinite::operator()(), StructuredField::operator()(), automaticMeshSizeField::operator()(), fullMatrix< double >::operator()(), GradientField::operator()(), MathEvalField::operator()(), MathEvalFieldAniso::operator()(), ParametricField::operator()(), fullMatrix< double >::operator+=(), PValues::operator=(), BDS_Face::oppositeEdge(), BDS_Face::oppositeVertex(), opt_mesh_lc_factor(), OptimizeMesh(), GModel::optimizeMesh(), optimizeQuadMeshBoundaries(), optimizeTopologyWithCavityRemeshing(), optimizeTopologyWithDiskQuadrangulationRemeshing(), orientAndSortEdges(), BDS_Edge::otherFace(), BDS_Edge::othervertex(), output(), outputScalarField(), gmshParametricSurface::parBounds(), gmshSurface::parFromPoint(), ParseFile(), PartitionFaceMinEdgeLength(), PartitionMesh(), GModel::partitionMesh(), PartitionUsingThisSplit(), PixelBuffer::PixelBuffer(), PolyMesh2GFace(), ppm_colorhisttocolorhash(), backgroundMesh::print(), print_pgf(), DocRecord::printMedialAxis(), PrintMesh2dStatistics(), PrintOptions(), PrintOptionsDoc(), Field::putOnNewView(), PView::PView(), qmTetrahedron::qm(), quadMeshingOfSimpleFacesWithPatterns(), quadMeshRemoveHalfOfOneDMesh::quadMeshRemoveHalfOfOneDMesh(), QuadqsContextUpdater::QuadqsContextUpdater(), GModel::readACISSAT(), GModel::readACTRAN(), GModel::readBDF(), PView::readCGNS(), GModel::readCGNS(), GModel::readDIFF(), readElementBDF(), readElementsVRML(), GModel::readGEOM(), elasticitySolver::readInputFile(), PView::readMED(), PViewDataGModel::readMED(), GModel::readMED(), GModel::readMESH(), PView::readMSH(), GModel::readMSH(), readMSH4Elements(), readMSH4GhostElements(), readMSH4Nodes(), readMSHEntities(), GModel::readOFF(), GModel::readP3D(), GModel::readParasolidSTEP(), GModel::readParasolidXMT(), GModel::readPLY(), GModel::readPLY2(), PView::readPOS(), PViewDataList::readPOS(), GModel::readSAMCEF(), GModel::readSTL(), GModel::readUNV(), GModel::readVRML(), GModel::readVTK(), Realloc(), GModel::recombineMesh(), BDS_Mesh::recover_edge(), recoverEdge(), recurFindLinkedEdges(), recurFindLinkedFaces(), GModel::refineMesh(), RefineMeshWithBackgroundMeshProjection(), GVertex::removeElement(), GRegion::removeElement(), GEdge::removeElement(), GFace::removeElement(), GVertex::removeElements(), GRegion::removeElements(), GEdge::removeElements(), GFace::removeElements(), reorientQuadPoints(), reparamMeshVertexOnFace(), gmshEdge::reparamOnFace(), replaceBadQuadDominantMeshes(), ReplaceDuplicateCurves(), ReplaceDuplicateSurfaces(), gmshRegion::resetMeshAttributes(), gmshFace::resetMeshAttributes(), discreteFace::resetMeshAttributes(), gmshRegion::resetNativePtr(), gmshFace::resetNativePtr(), fullMatrix< double >::reshape(), CellComplex::restoreComplex(), QuadqsContextUpdater::restoreInitialOption(), rtree_callback(), GMSH_SimplePartitionPlugin::run(), scriptAddCommand(), scriptRemoveLastCommand(), drawContext::select(), PViewDataGModel::sendToServer(), PViewData::sendToServer(), backgroundMesh::set(), fullVector< double >::set(), fullMatrix< double >::set(), GModel::setAllVolumesPositiveTopology(), SurfaceProjector::setAnalyticalProjection(), GFace::setBoundEdges(), GRegion::setBoundFaces(), dofManager< double >::setCurrentMatrix(), SetLogFile(), GFace::setMeshMaster(), GEntity::setMeshMaster(), GEO_Internals::setMeshSize(), GEdge::setMeshSizeParametric(), PViewData::setNode(), PViewDataList::setOrder2(), GModel::setOrderN(), linearSystemBase::setParameter(), GVertex::setPosition(), bezierCoeffMemoryPool::setSizeBlocks(), SetSurfaceGeneratrices(), GEO_Internals::setTransfiniteSurface(), GEO_Internals::setTransfiniteVolume(), BoundaryLayerField::setupFor2d(), PViewData::setValue(), MElement::setVertex(), SetVolumeSurfaces(), PViewData::smooth(), smoothVertexOptimize(), GModel::snapVertices(), eigenSolver::solve(), SortCurvesConsecutive(), SortEdgeConsecutive(), SortEdgesInLoop(), SplitCurve(), StringOption(), Subdivide(), SubdivideExtrudedMesh(), subdivideOctantBucket(), surface_triangle_param(), SurfaceProjector::SurfaceProjector(), GEO_Internals::synchronize(), SystemCallExe(), linearSystemCSRGmm< scalar >::systemSolve(), fullMatrix< double >::transposeInPlace(), GModel::unpartitionMesh(), UnzipFile(), automaticMeshSizeField::update(), bezierCoeff::updateDataPtr(), meshMetric::updateMetrics(), DocRecord::voronoiCell(), Walk(), walk(), PView::write(), GModel::writeBDF(), GModel::writeCELUM(), GModel::writeCGNS(), GModel::writeDIFF(), gmshEdge::writeGEO(), GModel::writeGEO(), GModel::writeINP(), GModel::writeIR3(), GModel::writeKEY(), GModel::writeMAIL(), GModel::writeMATLAB(), PViewDataGModel::writeMED(), PViewData::writeMED(), GModel::writeMED(), GModel::writeMESH(), PViewDataList::writeMSH(), PViewDataGModel::writeMSH(), PViewData::writeMSH(), cartesianBox< scalar >::writeMSH(), GModel::writeMSH(), MElement::writeMSH2(), GModel::writeNEU(), GModel::writeOCCBREP(), GModel::writeOCCSTEP(), GModel::writeOFF(), GModel::writeP3D(), discreteEdge::writeParametrization(), GModel::writeParasolidSTEP(), GModel::writeParasolidXMT(), GModel::writePartitionedMSH(), GModel::writePartitionedTopology(), GModel::writePLY2(), PViewDataList::writePOS(), PViewData::writePOS(), GModel::writePOS(), GModel::writePY(), GModel::writeRAD(), PViewData::writeSTL(), GModel::writeSTL(), GModel::writeSU2(), GModel::writeTOCHNOG(), PViewData::writeTXT(), GModel::writeUNV(), GModel::writeVRML(), GModel::writeVTK(), VTKData::writeVTKElmData(), PView::writeX3D(), writeX3dFaces(), yyerror(), yymsg(), and bezierCoeff::~bezierCoeff().
ExchangeOnelabParameter() [1/2]
void Msg::ExchangeOnelabParameter (const std::string & key, std::string & val, std::map< std::string, std::vector< double > > & fopt, std::map< std::string, std::vector< std::string > > & copt) static
Definition at line 1458 of file GmshMessage.cpp.
ExchangeOnelabParameter() [2/2]
void Msg::ExchangeOnelabParameter (const std::string & key, std::vector< double > & val, std::map< std::string, std::vector< double > > & fopt, std::map< std::string, std::vector< std::string > > & copt) static
Definition at line 1348 of file GmshMessage.cpp.
Exit()
void Msg::Exit (int level) static
Definition at line 384 of file GmshMessage.cpp.
Referenced by Error(), GetGeometryOption(), GetMeshOption(), GetOptions(), GetOtherOption(), GetPostProcessingOption(), GetSolverOption(), GmshMainBatch(), GmshMainFLTK(), and InitializeOnelab().
Finalize()
void Msg::Finalize () static
Definition at line 195 of file GmshMessage.cpp.
Referenced by Exit(), and GmshFinalize().
FinalizeOnelab()
void Msg::FinalizeOnelab () static
Definition at line 1196 of file GmshMessage.cpp.
Referenced by Finalize().
GetAnswer()
int Msg::GetAnswer (const char * question, int defaultval, const char * zero, const char * one, const char * two = nullptr) static
Definition at line 952 of file GmshMessage.cpp.
Referenced by DoSystemUncompress(), scriptAddCommand(), and TooManyElements().
GetCallback()
GmshMessage * Msg::GetCallback () static
Definition at line 244 of file GmshMessage.cpp.
Referenced by GmshGetMessageHandler().
GetCommandLineArgs()
std::vector< std::string > & Msg::GetCommandLineArgs () static
Definition at line 277 of file GmshMessage.cpp.
Referenced by GetOptions().
GetCommandLineFull()
std::string Msg::GetCommandLineFull () static
Definition at line 282 of file GmshMessage.cpp.
Referenced by StartupMessage().
GetCommandLineNumbers()
std::map< std::string, std::vector< double > > & Msg::GetCommandLineNumbers () static
Definition at line 292 of file GmshMessage.cpp.
Referenced by GetOtherOption(), and OpenProject().
GetCommandLineStrings()
std::map< std::string, std::string > & Msg::GetCommandLineStrings () static
Definition at line 297 of file GmshMessage.cpp.
Referenced by GetOtherOption(), and OpenProject().
GetCommRank()
int Msg::GetCommRank () static
Definition at line 219 of file GmshMessage.cpp.
Referenced by dofManagerBase::_parallelFinalize(), Debug(), DeleteAllModelsAndViews(), Direct(), Error(), Info(), MsgProgressStatus::next(), PrintErrorCounter(), PrintTimers(), ProgressMeter(), StatusBar(), StatusGl(), and Warning().
GetCommSize()
int Msg::GetCommSize () static
Definition at line 224 of file GmshMessage.cpp.
Referenced by dofManagerBase::_parallelFinalize(), and StartupMessage().
GetErrorCount()
int Msg::GetErrorCount () static
Definition at line 347 of file GmshMessage.cpp.
Referenced by AdaptMesh(), FixPeriodicMesh(), Mesh1D(), Mesh2D(), Mesh3D(), OptimizeMesh(), PrintErrorCounter(), RecombineMesh(), and SetOrderN().
GetExecutableName()
std::string Msg::GetExecutableName () static
Definition at line 372 of file GmshMessage.cpp.
Referenced by OpenProjectMacFinder().
GetFirstError()
std::string Msg::GetFirstError () static
Definition at line 357 of file GmshMessage.cpp.
GetFirstWarning()
std::string Msg::GetFirstWarning () static
Definition at line 352 of file GmshMessage.cpp.
GetGmshClient()
GmshClient * Msg::GetGmshClient () static
Definition at line 1272 of file GmshMessage.cpp.
Referenced by GmshMainBatch(), and GmshMainFLTK().
GetLastError()
std::string Msg::GetLastError () static
Definition at line 362 of file GmshMessage.cpp.
Referenced by GModel::_writePartitionedMSH4(), Mesh1D(), and Mesh2D().
GetLaunchDate()
std::string Msg::GetLaunchDate () static
Definition at line 272 of file GmshMessage.cpp.
Referenced by StartupMessage().
GetMaxThreads()
int Msg::GetMaxThreads () static
Definition at line 1637 of file GmshMessage.cpp.
Referenced by GModel::_writePartitionedMSH4(), addElementsInArrays(), Mesh1D(), Mesh2D(), and StartupMessage().
GetNumOnelabClients()
int Msg::GetNumOnelabClients () static
Definition at line 1277 of file GmshMessage.cpp.
Referenced by MergeFile(), ParseFile(), and GModel::setFileName().
GetNumThreads()
int Msg::GetNumThreads () static
Definition at line 1635 of file GmshMessage.cpp.
Referenced by meshGeneratorPeriodic(), and MsgProgressStatus::next().
GetOnelabAction()
std::string Msg::GetOnelabAction () static
Definition at line 1225 of file GmshMessage.cpp.
GetOnelabNumber()
double Msg::GetOnelabNumber (const std::string & name, double defaultValue = 0., bool errorIfMissing = false) static
Definition at line 1084 of file GmshMessage.cpp.
GetOnelabString()
std::string Msg::GetOnelabString (const std::string & name, const std::string & defaultValue = "", bool errorIfMissing = false) static
Definition at line 1105 of file GmshMessage.cpp.
Referenced by MergeFile().
GetProgressMeterStep()
int Msg::GetProgressMeterStep () static
Definition at line 307 of file GmshMessage.cpp.
Referenced by opt_general_progress_meter_step().
GetString()
std::string Msg::GetString (const char * text, const std::string & defaultval) static
Definition at line 927 of file GmshMessage.cpp.
GetThreadNum()
int Msg::GetThreadNum () static
Definition at line 1638 of file GmshMessage.cpp.
Referenced by backgroundMesh::current(), backgroundMesh::set(), backgroundMesh::setCrossFieldsByDistance(), and backgroundMesh::unset().
GetValue()
double Msg::GetValue (const char * text, double defaultval) static
Definition at line 900 of file GmshMessage.cpp.
GetVerbosity()
int Msg::GetVerbosity () static
Definition at line 254 of file GmshMessage.cpp.
Referenced by buildBackgroundMesh(), Debug(), Direct(), Error(), Info(), Mesh3D(), opt_general_verbosity(), OptimizeMesh(), PrintErrorCounter(), ProgressMeter(), recombineIntoQuads(), BDS_Mesh::recover_edge(), recoverEdge(), StatusBar(), and Warning().
GetWarningCount()
int Msg::GetWarningCount () static
Definition at line 342 of file GmshMessage.cpp.
Referenced by PrintErrorCounter().
ImportPhysicalGroupsInOnelab()
void Msg::ImportPhysicalGroupsInOnelab () static
Definition at line 1523 of file GmshMessage.cpp.
Referenced by MergeFile(), and scriptAddCommand().
Info()
void Msg::Info (const char * fmt, ...) static
Definition at line 587 of file GmshMessage.cpp.
Referenced by jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), discreteFace::_createGeometryFromSTL(), _getQualityFunctionSpace(), PView::_init(), CellComplex::_insertCells(), GModel::_readMSH2(), GModel::_readMSH3(), GModel::_readMSH4(), _recombineIntoQuads(), GModel::_writePartitionedMSH2(), GModel::_writePartitionedMSH3(), GModel::_writePartitionedMSH4(), PluginManager::action(), GModel::adaptMesh(), GModel::addAutomaticExtrusionConstraints(), addPeriodicFace(), PluginManager::addPlugin(), Auto(), bowyerWatsonParallelograms(), GModel::buildCutGModel(), splitQuadRecovery::buildPyramids(), ChangePrintParameter(), checkConformity(), checkHighOrderTetrahedron(), checkHighOrderTriangles(), GModel::checkMeshCoherence(), CheckResources(), classifyFaces(), ClearProject(), CellComplex::cocombine(), CellComplex::combine(), computeEdgeCut(), computeEquivalentTriangles(), GModel::computeHomology(), computeLevelset(), GFace::computeMeanPlane(), computeNonManifoldEdges(), copyMesh(), CellComplex::coreduceComplex(), createBoundaryLayerOneLayer(), CreateCurve(), GModel::createTopologyFromMesh(), discreteFace::curvatures(), delaunayMeshIn3D(), ensureManifoldFace(), ensureSimplyConnectedEdge(), GMSH_CrackPlugin::execute(), GMSH_IntegratePlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), ExtrudeCurve(), PView::fillVertexArray(), PViewDataGModel::finalize(), FindConnectedRegions(), discreteFace::firstDer(), FixPeriodicMesh(), GenerateMesh(), GetMeshOption(), GoodbyeMessage(), InitializeOnelab(), insertVerticesInRegion(), inSphereTest_s(), LoadOnelabClient(), GModel::makeDiscreteFacesSimplyConnected(), GModel::makeDiscreteRegionsSimplyConnected(), MakeMeshConformal(), makeSimplyConnected(), GeomMeshMatcher::match(), GeomMeshMatcher::matchEdges(), GeomMeshMatcher::matchFaces(), GeomMeshMatcher::matchRegions(), GeomMeshMatcher::matchVertices(), Mesh2DWithBoundaryLayers(), Mesh3D(), MeshDelaunayVolume(), MeshExtrudedCurve(), MeshExtrudedSurface(), meshGenerator(), meshGeneratorPeriodic(), meshGRegionNetgen(), MeshTransfiniteSurface(), MeshTransfiniteVolume(), discreteFace::normal(), OpenProject(), meshGEdge::operator()(), meshGFace::operator()(), meshGRegionExtruded::operator()(), optimizeMeshGRegion::operator()(), optimizeMeshGRegionNetgen::operator()(), EmbeddedCompatibilityTest::operator()(), adaptMeshGRegion::operator()(), gLevelsetPoints::operator()(), optimizeMesh(), outputScalarField(), GEdgeSigned::print(), FuncSpaceData::print(), extrudeInfo::print(), print_pgf(), CellComplex::printComplex(), PrintMesh2dStatistics(), printStats(), ProjectPointOnSurface(), quadqsCleanup(), GModel::readACTRAN(), GModel::readBDF(), GModel::readDIFF(), readElementsVRML(), GModel::readGEOM(), GModel::readMESH(), readMSH4Elements(), readMSH4Entities(), readMSH4Nodes(), readMSH4Parametrizations(), readMSH4PeriodicNodes(), readMSHPeriodicNodes(), GModel::readOFF(), PViewDataGModel::readPCH(), GModel::readPLY(), GModel::readPLY2(), PViewDataList::readPOS(), GModel::readSAMCEF(), GModel::readSTL(), GModel::readUNV(), readVerticesVRML(), GModel::readVTK(), recombineIntoQuads(), recoverEdges(), CellComplex::reduceComplex(), relocateSlaveVertices(), RemoveDegenerateCurves(), RemoveDegenerateSurfaces(), RemoveDegenerateVolumes(), GModel::removeDuplicateMeshElements(), GModel::removeDuplicateMeshVertices(), GModel::removeInvisibleElements(), GModel::renumberMeshElements(), GModel::renumberMeshVertices(), gmshVertex::reparamOnFace(), gmshEdge::reparamOnFace(), ReplaceDuplicatePointsNew(), CellComplex::restoreComplex(), GModel::reverseInvisibleElements(), GMSH_SpanningTreePlugin::run(), PView::sendToServer(), GModel::setAllVolumesPositiveTopology(), GFace::setMeshMaster(), GEdge::setMeshMaster(), SetOrderN(), GRegion::setOutwardOrientationMeshConstraint(), GModel::snapVertices(), SortEdgesInLoop(), StartupMessage(), SubdivideExtrudedMesh(), SystemCallExe(), UnzipFile(), GModel::writeCELUM(), PViewDataGModel::writeMSH(), cartesianBox< scalar >::writeMSH(), GModel::writePartitionedTopology(), GModel::writeSU2(), GModel::writeX3D(), GFace::XYZtoUV(), and yymsg().
Initialize()
void Msg::Initialize (int argc, char ** argv) static
Definition at line 125 of file GmshMessage.cpp.
Referenced by GmshInitialize().
InitializeOnelab()
void Msg::InitializeOnelab (const std::string & name, const std::string & sockname = "") static
Definition at line 1155 of file GmshMessage.cpp.
Referenced by GetSolverOption(), and Initialize().
LoadOnelabClient()
void Msg::LoadOnelabClient (const std::string & name, const std::string & sockName) static
Definition at line 1237 of file GmshMessage.cpp.
PrintErrorCounter()
void Msg::PrintErrorCounter (const char * title) static
Definition at line 859 of file GmshMessage.cpp.
Referenced by GenerateMesh().
PrintResources()
std::string Msg::PrintResources (bool printDate, bool printWallTime, bool printCpu, bool printMem) static
Definition at line 436 of file GmshMessage.cpp.
Referenced by Info(), and StatusBar().
PrintTimers()
void Msg::PrintTimers () static
Definition at line 828 of file GmshMessage.cpp.
ProgressMeter()
void Msg::ProgressMeter (int n, bool log, const char * fmt, ...) static
Definition at line 783 of file GmshMessage.cpp.
Referenced by GModel::_readMSH2(), GModel::_readMSH3(), GModel::createGeometryOfDiscreteEntities(), GMSH_NearToFarFieldPlugin::execute(), Mesh1D(), Mesh2D(), Mesh3D(), MsgProgressStatus::next(), GModel::readDIFF(), PViewDataGModel::readMSH(), readMSH4Elements(), readMSH4Nodes(), readMSH4Parametrizations(), SetOrderN(), and MsgProgressStatus::~MsgProgressStatus().
RequestRender()
void Msg::RequestRender () static
Definition at line 629 of file GmshMessage.cpp.
ResetErrorCounter()
void Msg::ResetErrorCounter () static
Definition at line 850 of file GmshMessage.cpp.
Referenced by ClearProject(), GenerateMesh(), and OpenProject().
RunOnelabClient()
void Msg::RunOnelabClient (const std::string & name, const std::string & exe = "") static
Definition at line 1605 of file GmshMessage.cpp.
SetCallback()
void Msg::SetCallback (GmshMessage * callback) static
Definition at line 239 of file GmshMessage.cpp.
Referenced by GmshSetMessageHandler().
SetCommRank()
void Msg::SetCommRank (int val) static
Definition at line 229 of file GmshMessage.cpp.
SetCommSize()
void Msg::SetCommSize (int val) static
Definition at line 234 of file GmshMessage.cpp.
SetExecutableName()
void Msg::SetExecutableName (const std::string & name) static
Definition at line 367 of file GmshMessage.cpp.
Referenced by GetOptions().
SetInfoCpu()
void Msg::SetInfoCpu (bool val) static
Definition at line 330 of file GmshMessage.cpp.
Referenced by GetOtherOption(), and GoodbyeMessage().
SetInfoMem()
void Msg::SetInfoMem (bool val) static
Definition at line 335 of file GmshMessage.cpp.
Referenced by GetOtherOption().
SetLogFile()
void Msg::SetLogFile (const std::string & name) static
Definition at line 259 of file GmshMessage.cpp.
Referenced by GetOtherOption().
SetNumThreads()
void Msg::SetNumThreads (int num) static
Definition at line 1636 of file GmshMessage.cpp.
SetOnelabAction()
void Msg::SetOnelabAction (const std::string & action) static
Definition at line 1213 of file GmshMessage.cpp.
SetOnelabChanged()
void Msg::SetOnelabChanged (int value, const std::string & client = "Gmsh") static
Definition at line 1612 of file GmshMessage.cpp.
Referenced by MergeFile(), opt_mesh_algo2d(), opt_mesh_algo3d(), opt_mesh_algo_recombine(), opt_mesh_algo_subdivide(), opt_mesh_angle_tolerance_facet_overlap(), opt_mesh_lc_extend_from_boundary(), opt_mesh_lc_factor(), opt_mesh_lc_from_curvature(), opt_mesh_lc_from_curvature_iso(), opt_mesh_lc_from_parametric_points(), opt_mesh_lc_from_points(), opt_mesh_lc_integration_precision(), opt_mesh_lc_max(), opt_mesh_lc_min(), opt_mesh_mesh_only_empty(), opt_mesh_mesh_only_visible(), opt_mesh_min_circle_nodes(), opt_mesh_min_curve_nodes(), opt_mesh_min_line_nodes(), opt_mesh_optimize(), opt_mesh_optimize_netgen(), opt_mesh_optimize_threshold(), opt_mesh_order(), opt_mesh_rand_factor(), opt_mesh_rand_factor3d(), opt_mesh_recombine3d_all(), opt_mesh_recombine_all(), opt_mesh_refine_steps(), opt_mesh_scaling_factor(), opt_mesh_second_order_incomplete(), opt_mesh_second_order_linear(), opt_mesh_tolerance_edge_length(), opt_mesh_tolerance_initial_delaunay(), and scriptAddCommand().
SetOnelabNumber() [1/2]
void Msg::SetOnelabNumber (const std::string & name, const std::vector< double > & val, bool visible = true) static
Definition at line 1009 of file GmshMessage.cpp.
SetOnelabNumber() [2/2]
void Msg::SetOnelabNumber (const std::string & name, double val, bool visible = true, bool persistent = false, bool readOnly = false, int changedValue = 3) static
Definition at line 987 of file GmshMessage.cpp.
Referenced by GetOtherOption(), InitializeOnelab(), PViewDataGModel::sendToServer(), and PViewData::sendToServer().
SetOnelabString()
void Msg::SetOnelabString (const std::string & name, const std::string & val, bool visible = true, bool persistent = false, bool readOnly = false, int changedValue = 3, const std::string & kind = "") static
Definition at line 1021 of file GmshMessage.cpp.
Referenced by GetOtherOption(), InitializeOnelab(), MergeFile(), and GModel::setFileName().
SetProgressMeterStep()
void Msg::SetProgressMeterStep (int step) static
Definition at line 302 of file GmshMessage.cpp.
Referenced by MsgProgressStatus::MsgProgressStatus(), opt_general_progress_meter_step(), and MsgProgressStatus::~MsgProgressStatus().
SetVerbosity()
void Msg::SetVerbosity (int val) static
Definition at line 249 of file GmshMessage.cpp.
Referenced by GetOtherOption(), and opt_general_verbosity().
SetWindowTitle()
void Msg::SetWindowTitle (const std::string & title) static
Definition at line 743 of file GmshMessage.cpp.
Referenced by GModel::setFileName().
StartProgressMeter()
void Msg::StartProgressMeter (int ntotal) static
Definition at line 312 of file GmshMessage.cpp.
Referenced by GModel::_readMSH2(), GModel::_readMSH3(), GModel::createGeometryOfDiscreteEntities(), GMSH_NearToFarFieldPlugin::execute(), Mesh1D(), Mesh2D(), Mesh3D(), MsgProgressStatus::MsgProgressStatus(), GModel::readDIFF(), PViewDataGModel::readMSH(), readMSH4Elements(), readMSH4Nodes(), readMSH4Parametrizations(), and SetOrderN().
StatusBar()
void Msg::StatusBar (bool log, const char * fmt, ...) static
Definition at line 686 of file GmshMessage.cpp.
Referenced by AdaptMesh(), BarycentricRefineMesh(), adaptiveData::changeResolutionForVTK(), GModel::checkMeshCoherence(), classifyFaces(), GModel::computeHomology(), GModel::createGeometryOfDiscreteEntities(), CreateOutputFile(), VTKData::finalizeVTKFile(), GeomMeshMatcher::match(), MergeFile(), Mesh1D(), Mesh2D(), Mesh3D(), opt_general_mouse_selection(), opt_general_orthographic(), OptimizeMesh(), RecombineMesh(), RefineMesh(), GModel::removeDuplicateMeshElements(), GModel::removeDuplicateMeshVertices(), SetOrderN(), PView::write(), and PView::writeAdapt().
StatusGl()
void Msg::StatusGl (const char * fmt, ...) static
Definition at line 727 of file GmshMessage.cpp.
StopProgressMeter()
void Msg::StopProgressMeter () static
Definition at line 318 of file GmshMessage.cpp.
Referenced by GModel::_readMSH2(), GModel::_readMSH3(), GModel::_readMSH4(), GModel::createGeometryOfDiscreteEntities(), GMSH_NearToFarFieldPlugin::execute(), Mesh1D(), Mesh2D(), Mesh3D(), GModel::readDIFF(), PViewDataGModel::readMSH(), readMSH4Parametrizations(), SetOrderN(), and MsgProgressStatus::~MsgProgressStatus().
Timer()
double & Msg::Timer (const std::string & str) static
Definition at line 340 of file GmshMessage.cpp.
UndefineOnelabParameter()
void Msg::UndefineOnelabParameter (const std::string & name) static
Definition at line 1515 of file GmshMessage.cpp.
UseOnelab()
bool Msg::UseOnelab () static
Definition at line 978 of file GmshMessage.cpp.
Warning()
void Msg::Warning (const char * fmt, ...) static
Definition at line 543 of file GmshMessage.cpp.
Referenced by _addModelData(), _computeCoeffLengthVectors(), _getAdditionalNodesOnBoundary(), PViewDataList::_getRawData(), PView::_init(), GModel::_readMSH2(), GModel::_readMSH3(), _recombineIntoQuads(), Cell::_sortVertexIndices(), jacobianBasedQuality::_subdivideDomains(), GModel::_writeMSH4(), adaptiveElements< T >::adapt(), GEO_Internals::addCurveLoops(), addElementsInArrays(), GModel::addPhysicalGroup(), PluginManager::addPlugin(), assemble2d(), assemble3d(), assembleColmapStr(), Auto(), BGM_MeshSize(), buildEdgeCavity(), buildVertexCavity_recur(), checkHighOrderTetrahedron(), checkHighOrderTriangles(), GModel::checkMeshCoherence(), classifyFaces(), SurfaceProjector::closestPoint(), GFace::closestPoint(), closestVertexFinder::closestVertexFinder(), collapseVertex(), computeEdgeCut(), BoundaryLayerField::computeFor1dMesh(), copy_vertices(), copyMesh(), CopySurface(), CopyVolume(), create_gif(), CreateCurve(), createElements(), discreteEdge::createGeometry(), discreteFace::createGeometry(), createHexPri(), createPriPyrTet(), createSizeFieldFromExistingMesh(), crossField2d::crossField2d(), GModel::deleteMesh(), DoSystemUncompress(), drawGlyphs(), drawContext::drawImage(), fullMatrix< double >::eig(), ensureSimplyConnectedEdge(), MathEvalExpression::evaluate(), MathEvalExpressionAniso::evaluate(), GMSH_CrackPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_DistancePlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GModel::exportDiscreteGEOInternals(), blyr_manager::extrude_vertices_on_faces(), ExtrudeCurve(), faceSwap(), PixelBuffer::fill(), extrudeInfo::fillExtrudeParams(), PViewDataGModel::finalize(), PViewData::fromVector(), CellComplex::getACell(), getAllParameters(), getEdgeVerticesOnGeo(), CondNumBasis::getInvCondNumAndGradientsGeneral(), CondNumBasis::getInvCondNumGeneral(), FunctionSpaceBase::getKeysOnVertex(), GetMeshOption(), GFace::getMetricEigenVectors(), ElementType::getNumVertices(), GetOptions(), ElementType::getOrder(), GMSH_PostPlugin::getPossiblyAdaptiveData(), ElementType::getSerendipity(), ElementType::getType(), PViewDataGModel::getValue(), GFaceInitialMesh(), gmshGenerateOrderedMonomials(), HilbertCoordinates(), SurfaceProjector::initialize(), MVertexRTree::insert(), insertVerticesInRegion(), InterpolateUBS(), LC_MVertex_CURV(), makeSimplyConnected(), max_edge_curvature_metric(), Mesh1D(), Mesh2D(), Mesh2DWithBoundaryLayers(), Mesh3D(), meshGenerator(), meshGeneratorPeriodic(), metric_based_on_surface_curvature(), jacobianBasedQuality::minMaxJacobianDeterminant(), non_recursive_classify(), gmshFace::normal(), meshGEdge::operator()(), meshGFace::operator()(), orientMeshGFace::operator()(), EmbeddedCompatibilityTest::operator()(), meshMetric::operator()(), F_Transfinite::operator()(), BoundaryLayerField::operator()(), BDS_SwapEdgeTestQuality::operator()(), LonLatField::operator()(), GenericField::operator()(), ThresholdField::operator()(), GradientField::operator()(), CurvatureField::operator()(), MaxEigenHessianField::operator()(), LaplacianField::operator()(), MeanField::operator()(), ParametricField::operator()(), MinAnisoField::operator()(), IntersectAnisoField::operator()(), MinField::operator()(), MaxField::operator()(), RestrictField::operator()(), optimize1DMeshAtAcuteCorners(), optimizeMesh(), print_pgf(), PView::PView(), pyramidalBasis::pyramidalBasis(), quadMeshRemoveHalfOfOneDMesh::quadMeshRemoveHalfOfOneDMesh(), GModel::readDIFF(), GModel::readGEOM(), readMSH4BoundingEntities(), readMSH4GhostElements(), readMSH4Nodes(), GModel::readOFF(), GModel::readPLY(), GModel::readSTL(), GModel::readUNV(), GModel::readVTK(), RecombineTriangle::RecombineTriangle(), GEdgeLoop::recompute(), ExtendField::recomputeCurves(), ExtendField::recomputeSurfaces(), refineMeshBDS(), refineMeshMMG(), stepData< Real >::renumberData(), reparamMeshVertexOnFace(), GMSH_SpanningTreePlugin::run(), scriptRemoveLastCommand(), drawContext::select(), GRegion::setOutwardOrientationMeshConstraint(), BoundaryLayerField::setupFor1d(), BoundaryLayerField::setupFor2d(), PViewDataGModel::setValue(), smoothVertex(), SortCurvesConsecutive(), SortEdgeConsecutive(), splitElementsInBoundaryLayerIfNeeded(), bezierCoeff::subdivide(), SubdivideExtrudedMesh(), surfaceFaceUV(), GEO_Internals::synchronize(), SystemCallExe(), drawContext::unproject(), DistanceField::update(), GModel::writeCELUM(), GFace::writeGEO(), MVertex::writeMATLAB(), MElement::writeMATLAB(), GModel::writeMATLAB(), PViewDataList::writeMSH(), PViewDataGModel::writeMSH(), GModel::writeMSH(), GModel::writeNEU(), GModel::writeP3D(), GModel::writePartitionedMSH(), PViewDataList::writePOS(), PViewData::writePOS(), GFace::writePY(), GModel::writeX3D(), writeX3dEdges(), writeX3dFaces(), discreteVertex::x(), GEdge::XYZToU(), GFace::XYZtoUV(), discreteVertex::y(), yymsg(), and discreteVertex::z().
Member Data Documentation
_atLeastOneErrorInRun
int Msg::_atLeastOneErrorInRun = 0 static private
Definition at line 52 of file GmshMessage.h.
Referenced by Error(), and Exit().
_callback
GmshMessage * Msg::_callback = nullptr static private
Definition at line 55 of file GmshMessage.h.
Referenced by Debug(), Direct(), Error(), GetAnswer(), GetCallback(), GetString(), GetValue(), Info(), ProgressMeter(), RequestRender(), SetCallback(), StatusBar(), and Warning().
_client
GmshClient * Msg::_client = nullptr static private
Definition at line 63 of file GmshMessage.h.
Referenced by Debug(), Direct(), Error(), FinalizeOnelab(), GetGmshClient(), Info(), InitializeOnelab(), ProgressMeter(), StatusBar(), and Warning().
_commandLineArgs
std::vector< std::string > Msg::_commandLineArgs static private
Definition at line 57 of file GmshMessage.h.
Referenced by GetCommandLineArgs(), GetCommandLineFull(), and Initialize().
_commandLineNumbers
std::map< std::string, std::vector< double > > Msg::_commandLineNumbers static private
Definition at line 60 of file GmshMessage.h.
Referenced by GetCommandLineNumbers().
_commandLineStrings
std::map< std::string, std::string > Msg::_commandLineStrings static private
Definition at line 61 of file GmshMessage.h.
Referenced by GetCommandLineStrings().
_commRank
int Msg::_commRank = 0 static private
Definition at line 34 of file GmshMessage.h.
Referenced by GetCommRank(), Initialize(), and SetCommRank().
_commSize
int Msg::_commSize = 1 static private
Definition at line 34 of file GmshMessage.h.
Referenced by Debug(), Direct(), Error(), GetCommSize(), Info(), Initialize(), PrintTimers(), SetCommSize(), StatusBar(), and Warning().
_errorCount
int Msg::_errorCount = 0 static private
Definition at line 52 of file GmshMessage.h.
Referenced by Error(), GetErrorCount(), and ResetErrorCounter().
_execName
std::string Msg::_execName static private
Definition at line 69 of file GmshMessage.h.
Referenced by GetExecutableName(), and SetExecutableName().
_firstError
std::string Msg::_firstError static private
Definition at line 53 of file GmshMessage.h.
Referenced by Error(), GetFirstError(), and ResetErrorCounter().
_firstWarning
std::string Msg::_firstWarning static private
Definition at line 53 of file GmshMessage.h.
Referenced by GetFirstWarning(), ResetErrorCounter(), and Warning().
_infoCpu
bool Msg::_infoCpu = false static private
Definition at line 46 of file GmshMessage.h.
Referenced by Info(), SetInfoCpu(), and StatusBar().
_infoMem
bool Msg::_infoMem = false static private
Definition at line 48 of file GmshMessage.h.
Referenced by Info(), SetInfoMem(), and StatusBar().
_lastError
std::string Msg::_lastError static private
Definition at line 53 of file GmshMessage.h.
Referenced by Error(), GetLastError(), and ResetErrorCounter().
_launchDate
std::string Msg::_launchDate static private
Definition at line 58 of file GmshMessage.h.
Referenced by GetLaunchDate(), and Initialize().
_logFile
FILE * Msg::_logFile = nullptr static private
Definition at line 72 of file GmshMessage.h.
Referenced by Debug(), Direct(), Error(), Finalize(), Info(), ProgressMeter(), SetLogFile(), StatusBar(), and Warning().
_logFileName
std::string Msg::_logFileName static private
Definition at line 71 of file GmshMessage.h.
Referenced by SetLogFile().
_progressMeterCurrent
std::atomic< int > Msg::_progressMeterCurrent static private
Definition at line 40 of file GmshMessage.h.
Referenced by Info(), ProgressMeter(), StartProgressMeter(), and StopProgressMeter().
_progressMeterStep
int Msg::_progressMeterStep = 10 static private
Definition at line 39 of file GmshMessage.h.
Referenced by GetProgressMeterStep(), ProgressMeter(), and SetProgressMeterStep().
_progressMeterTotal
int Msg::_progressMeterTotal = 0 static private
Definition at line 42 of file GmshMessage.h.
Referenced by Info(), ProgressMeter(), StartProgressMeter(), and StopProgressMeter().
_startTime
double Msg::_startTime = 0. static private
Definition at line 50 of file GmshMessage.h.
Referenced by Initialize(), and PrintResources().
_timers
std::map< std::string, double > Msg::_timers static private
Definition at line 44 of file GmshMessage.h.
Referenced by PrintTimers(), and Timer().
_verbosity
int Msg::_verbosity = 5 static private
Definition at line 37 of file GmshMessage.h.
Referenced by GetVerbosity(), and SetVerbosity().
_warningCount
int Msg::_warningCount = 0 static private
Definition at line 52 of file GmshMessage.h.
Referenced by GetWarningCount(), ResetErrorCounter(), and Warning().
The documentation for this class was generated from the following files:
src/common/GmshMessage.h
src/common/GmshMessage.cpp