gmsh-TingyuanDoc: gLevelset Class Reference
gLevelset Class Reference
#include <gmshLevelset.h>
Public Member Functions
gLevelset (int tag=0)
gLevelset (const gLevelset &)
virtual ~gLevelset ()
virtual gLevelset * clone () const
virtual double operator() (double x, double y, double z) const
bool isInsideDomain (const double &x, const double &y, const double &z) const
bool isOutsideDomain (const double &x, const double &y, const double &z) const
bool isOnBorder (const double &x, const double &y, const double &z) const
virtual std::vector< gLevelset * > getChildren () const
virtual double choose (double d1, double d2) const
virtual int type () const
virtual bool isPrimitive () const
void setTag (int t)
virtual int getTag () const
void getPrimitives (std::vector< gLevelset * > &primitives)
void getPrimitivesPO (std::vector< gLevelset * > &primitives)
void getRPN (std::vector< gLevelset * > &gLsRPN)
double H (const double &x, const double &y, const double &z) const
void print () const
Public Member Functions inherited from simpleFunction< double >
simpleFunction (double val=0.0)
virtual ~simpleFunction ()
virtual bool hasDerivatives ()
virtual void setElement (MElement *e) const
virtual void gradient (double x, double y, double z, double &dfdx, double &dfdy, double &dfdz) const
virtual void hessian (double x, double y, double z, double &dfdxx, double &dfdxy, double &dfdxz, double &dfdyx, double &dfdyy, double &dfdyz, double &dfdzx, double &dfdzy, double &dfdzz) const
Static Public Member Functions
static gLevelset * find (int tag)
static void add (gLevelset *l)
Protected Attributes
int tag_
Protected Attributes inherited from simpleFunction< double >
double _val
bool _hasDerivatives
Static Protected Attributes
static const short insideDomain = -1
static int maxTag_ = 0
static std::set< gLevelset *, gLevelsetLessThan > all_
Detailed Description
Definition at line 64 of file gmshLevelset.h.
Constructor & Destructor Documentation
gLevelset() [1/2]
gLevelset::gLevelset (int tag = 0) inline
Definition at line 76 of file gmshLevelset.h.
gLevelset() [2/2]
gLevelset::gLevelset (const gLevelset & lv)
Definition at line 351 of file gmshLevelset.cpp.
~gLevelset()
virtual gLevelset::~gLevelset () inline virtual
Definition at line 84 of file gmshLevelset.h.
Member Function Documentation
add()
void gLevelset::add (gLevelset * l) static
Definition at line 44 of file gmshLevelset.cpp.
choose()
virtual double gLevelset::choose (double d1, double d2) const inline virtual
Reimplemented in gLevelsetTools, gLevelsetImproved, gLevelsetCrack, gLevelsetIntersection, gLevelsetUnion, gLevelsetCut, gLevelsetReverse, and gLevelsetPrimitive.
Definition at line 105 of file gmshLevelset.h.
Referenced by gLevelsetReverse::choose(), and gLevelsetImproved::choose().
clone()
virtual gLevelset* gLevelset::clone () const inline virtual
Reimplemented in gLevelsetConrod, gLevelsetCylinder, gLevelsetBox, gLevelsetIntersection, gLevelsetUnion, gLevelsetCut, gLevelsetGeneralQuadric, gLevelsetCone, gLevelsetEllipsoid, gLevelsetGenCylinder, gLevelsetPoints, and gLevelsetPlane.
Definition at line 87 of file gmshLevelset.h.
Referenced by gLevelsetImproved::gLevelsetImproved(), and gLevelsetTools::gLevelsetTools().
find()
gLevelset * gLevelset::find (int tag) static
Definition at line 36 of file gmshLevelset.cpp.
getChildren()
virtual std::vector<gLevelset *> gLevelset::getChildren () const inline virtual
Reimplemented in gLevelsetImproved, gLevelsetReverse, gLevelsetTools, and gLevelsetPrimitive.
Definition at line 101 of file gmshLevelset.h.
Referenced by gLevelsetReverse::getChildren(), gLevelsetImproved::getChildren(), getPrimitives(), getPrimitivesPO(), and getRPN().
getPrimitives()
void gLevelset::getPrimitives (std::vector< gLevelset * > & primitives)
Definition at line 273 of file gmshLevelset.cpp.
getPrimitivesPO()
void gLevelset::getPrimitivesPO (std::vector< gLevelset * > & primitives)
Definition at line 291 of file gmshLevelset.cpp.
Referenced by buildCutMesh().
getRPN()
void gLevelset::getRPN (std::vector< gLevelset * > & gLsRPN)
Definition at line 321 of file gmshLevelset.cpp.
Referenced by buildCutMesh().
getTag()
virtual int gLevelset::getTag () const inline virtual
Reimplemented in gLevelsetReverse, and gLevelsetTools.
Definition at line 109 of file gmshLevelset.h.
Referenced by gLevelsetReverse::getTag(), gLevelsetLessThan::operator()(), and print().
H()
double gLevelset::H (const double & x, const double & y, const double & z) const inline
Definition at line 113 of file gmshLevelset.h.
Referenced by gLevelsetCylinder::gLevelsetCylinder().
isInsideDomain()
bool gLevelset::isInsideDomain (const double & x, const double & y, const double & z) const inline
Definition at line 89 of file gmshLevelset.h.
Referenced by H(), and FuncHeaviside::operator()().
isOnBorder()
bool gLevelset::isOnBorder (const double & x, const double & y, const double & z) const inline
Definition at line 97 of file gmshLevelset.h.
Referenced by H().
isOutsideDomain()
bool gLevelset::isOutsideDomain (const double & x, const double & y, const double & z) const inline
Definition at line 93 of file gmshLevelset.h.
isPrimitive()
virtual bool gLevelset::isPrimitive () const inline virtual
Reimplemented in gLevelsetImproved, gLevelsetReverse, gLevelsetTools, and gLevelsetPrimitive.
Definition at line 107 of file gmshLevelset.h.
Referenced by gLevelsetReverse::isPrimitive(), and gLevelsetImproved::isPrimitive().
operator()()
virtual double gLevelset::operator() (double x, double y, double z) const inline virtual
Reimplemented from simpleFunction< double >.
Reimplemented in gLevelsetPrimitive, gLevelsetImproved, gLevelsetReverse, gLevelsetTools, gLevelsetYarn, gLevelsetNACA00, gLevelsetSimpleFunction, gLevelsetMathEvalAll, gLevelsetMathEval, gLevelsetShamrock, gLevelsetPopcorn, gLevelsetQuadric, gLevelsetPoints, gLevelsetPlane, and gLevelsetSphere.
Definition at line 88 of file gmshLevelset.h.
Referenced by isInsideDomain(), isOnBorder(), and isOutsideDomain().
print()
void gLevelset::print () const inline
Definition at line 118 of file gmshLevelset.h.
setTag()
void gLevelset::setTag (int t) inline
Definition at line 108 of file gmshLevelset.h.
type()
virtual int gLevelset::type () const inline virtual
Reimplemented in gLevelsetImproved, gLevelsetQuadric, gLevelsetPrimitive, gLevelsetConrod, gLevelsetCylinder, gLevelsetBox, gLevelsetReverse, gLevelsetTools, gLevelsetYarn, gLevelsetNACA00, gLevelsetSimpleFunction, gLevelsetMathEvalAll, gLevelsetMathEval, gLevelsetShamrock, gLevelsetPopcorn, gLevelsetGeneralQuadric, gLevelsetCone, gLevelsetEllipsoid, gLevelsetGenCylinder, gLevelsetPoints, gLevelsetPlane, and gLevelsetSphere.
Definition at line 106 of file gmshLevelset.h.
Referenced by print(), and gLevelsetReverse::type().
Member Data Documentation
all_
std::set< gLevelset *, gLevelsetLessThan > gLevelset::all_ static protected
Definition at line 73 of file gmshLevelset.h.
Referenced by add(), and find().
insideDomain
const short gLevelset::insideDomain = -1 static protected
Definition at line 67 of file gmshLevelset.h.
Referenced by isInsideDomain(), and isOutsideDomain().
maxTag_
int gLevelset::maxTag_ = 0 static protected
Definition at line 71 of file gmshLevelset.h.
Referenced by gLevelset().
tag_
int gLevelset::tag_ protected
Definition at line 69 of file gmshLevelset.h.
Referenced by getTag(), gLevelsetTools::getTag(), gLevelset(), and setTag().
The documentation for this class was generated from the following files:
src/geo/gmshLevelset.h
src/geo/gmshLevelset.cpp