gmsh-TingyuanDoc: MFace Class Reference
MFace Class Reference
#include <MFace.h>
Public Member Functions
MFace ()
MFace (MVertex *v0, MVertex *v1, MVertex *v2, MVertex *v3=nullptr)
MFace (const std::vector< MVertex * > &v)
std::size_t getNumVertices () const
MVertex * getVertex (std::size_t i) const
MVertex * getSortedVertex (std::size_t i) const
MEdge getEdge (std::size_t i) const
void getOrientationFlagForFace (std::vector< int > &faceOrientationFlag)
bool computeCorrespondence (const MFace &, int &, bool &) const
void getOrderedVertices (std::vector< MVertex * > &verts) const
void getOrderedVertices (const MVertex **const verts) const
double approximateArea () const
SVector3 normal () const
SVector3 tangent (int num) const
SPoint3 barycenter () const
SPoint3 interpolate (const double &u, const double &v) const
Private Attributes
std::vector< MVertex * > _v
std::vector< char > _si
Detailed Description
Definition at line 20 of file MFace.h.
Constructor & Destructor Documentation
MFace() [1/3]
MFace::MFace () inline
Definition at line 26 of file MFace.h.
MFace() [2/3]
MFace::MFace (MVertex * v0, MVertex * v1, MVertex * v2, MVertex * v3 = nullptr)
Definition at line 68 of file MFace.cpp.
MFace() [3/3]
MFace::MFace (const std::vector< MVertex * > & v)
Definition at line 78 of file MFace.cpp.
Member Function Documentation
approximateArea()
double MFace::approximateArea () const
Definition at line 195 of file MFace.cpp.
Referenced by _relocateVertexOfPyramid().
barycenter()
SPoint3 MFace::barycenter () const inline
Definition at line 65 of file MFace.h.
Referenced by _relocateVertexOfPyramid(), and Subdivide().
computeCorrespondence()
bool MFace::computeCorrespondence (const MFace & other, int & rotation, bool & swap) const
Definition at line 212 of file MFace.cpp.
Referenced by GFace::alignElementsWithMaster(), and GModel::alignPeriodicBoundaries().
getEdge()
MEdge MFace::getEdge (std::size_t i) const inline
Definition at line 35 of file MFace.h.
getNumVertices()
std::size_t MFace::getNumVertices () const inline
Definition at line 29 of file MFace.h.
Referenced by MElement::_getFaceInfo(), addToMap(), barycenter(), buildFaceSearchStructure(), checkConformity(), computeCorrespondence(), getEdge(), getFaceVertices(), getOrderedVertices(), interpolate(), operator!=(), MFaceLessThan::operator()(), operator==(), and topoFace::topoFace().
getOrderedVertices() [1/2]
void MFace::getOrderedVertices (const MVertex **const verts) const inline
Definition at line 47 of file MFace.h.
getOrderedVertices() [2/2]
void MFace::getOrderedVertices (std::vector< MVertex * > & verts) const inline
Definition at line 42 of file MFace.h.
getOrientationFlagForFace()
void MFace::getOrientationFlagForFace (std::vector< int > & faceOrientationFlag)
Definition at line 84 of file MFace.cpp.
getSortedVertex()
MVertex* MFace::getSortedVertex (std::size_t i) const inline
Definition at line 31 of file MFace.h.
Referenced by getOrderedVertices(), operator!=(), MFaceLessThan::operator()(), and operator==().
getVertex()
MVertex* MFace::getVertex (std::size_t i) const inline
Definition at line 30 of file MFace.h.
Referenced by MElement::_getFaceInfo(), addToMap(), qmHexahedron::angles(), barycenter(), checkConformity(), computeCorrespondence(), getEdge(), interpolate(), and topoFace::topoFace().
interpolate()
SPoint3 MFace::interpolate (const double & u, const double & v) const inline
Definition at line 80 of file MFace.h.
normal()
SVector3 MFace::normal () const
Definition at line 204 of file MFace.cpp.
Referenced by MElement::_getEdgeRep(), MPolygon::_initVertices(), _myGetEdgeRep(), _relocateVertexOfPyramid(), addExtrudeNormals(), drawNormals(), FixPeriodicMesh(), MPyramidN::getEdgeRep(), getGFaceOrientation(), quadsToTriangles(), MElement::signedInvCondNumRange(), tangent(), and MElement::writeSTL().
tangent()
SVector3 MFace::tangent (int num) const inline
Definition at line 55 of file MFace.h.
Member Data Documentation
_si
std::vector<char> MFace::_si private
Definition at line 23 of file MFace.h.
Referenced by getOrientationFlagForFace(), getSortedVertex(), and MFace().
_v
std::vector<MVertex *> MFace::_v private
Definition at line 22 of file MFace.h.
Referenced by approximateArea(), computeCorrespondence(), getNumVertices(), getOrientationFlagForFace(), getSortedVertex(), getVertex(), MFace(), normal(), and tangent().
The documentation for this class was generated from the following files:
src/geo/MFace.h
src/geo/MFace.cpp