gmsh-TingyuanDoc: adaptiveElements< T > Class Template Reference
adaptiveElements< T > Class Template Reference
#include <adaptiveData.h>
Public Member Functions
adaptiveElements (std::vector< fullMatrix< double > * > &interpolationMatrices)
~adaptiveElements ()
void init (int level)
bool adapt (double tol, int numComp, std::vector< PCoords > &coords, std::vector< PValues > &values, double &minVal, double &maxVal, GMSH_PostPlugin *plug=nullptr, bool onlyComputeMinMax=false)
void addInView (double tol, int step, PViewData *in, PViewDataList *out, GMSH_PostPlugin *plug=nullptr)
void adaptForVTK (double tol, int numComp, std::vector< PCoords > &coords, std::vector< PValues > &values, double &minVal, double &maxVal)
void addInViewForVTK (int step, PViewData *in, VTKData &myVTKData, bool writeVtk=true, bool buildStaticData=false)
int countElmLev0 (int step, PViewData *in)
void buildMapping (nodMap< T > &myNodMap, double tol, int &numNodInsert)
Private Attributes
fullMatrix< double > * _coeffsVal
fullMatrix< double > * _eexpsVal
fullMatrix< double > * _interpolVal
fullMatrix< double > * _coeffsGeom
fullMatrix< double > * _eexpsGeom
fullMatrix< double > * _interpolGeom
Detailed Description
template<class T>
class adaptiveElements< T >
Definition at line 596 of file adaptiveData.h.
Constructor & Destructor Documentation
adaptiveElements()
template<class T > adaptiveElements< T >::adaptiveElements (std::vector< fullMatrix< double > * > & interpolationMatrices)
Definition at line 1082 of file adaptiveData.cpp.
~adaptiveElements()
template<class T > adaptiveElements< T >::~adaptiveElements
Definition at line 1096 of file adaptiveData.cpp.
Member Function Documentation
adapt()
template<class T > bool adaptiveElements< T >::adapt (double tol, int numComp, std::vector< PCoords > & coords, std::vector< PValues > & values, double & minVal, double & maxVal, GMSH_PostPlugin * plug = nullptr, bool onlyComputeMinMax = false)
Definition at line 1206 of file adaptiveData.cpp.
adaptForVTK()
template<class T > void adaptiveElements< T >::adaptForVTK (double tol, int numComp, std::vector< PCoords > & coords, std::vector< PValues > & values, double & minVal, double & maxVal)
Definition at line 2240 of file adaptiveData.cpp.
addInView()
template<class T > void adaptiveElements< T >::addInView (double tol, int step, PViewData * in, PViewDataList * out, GMSH_PostPlugin * plug = nullptr)
Definition at line 1356 of file adaptiveData.cpp.
Referenced by adaptiveData::changeResolution().
addInViewForVTK()
template<class T > void adaptiveElements< T >::addInViewForVTK (int step, PViewData * in, VTKData & myVTKData, bool writeVtk = true, bool buildStaticData = false)
Definition at line 2452 of file adaptiveData.cpp.
Referenced by adaptiveData::changeResolutionForVTK().
buildMapping()
template<class T > void adaptiveElements< T >::buildMapping (nodMap< T > & myNodMap, double tol, int & numNodInsert)
Definition at line 2381 of file adaptiveData.cpp.
countElmLev0()
template<class T > int adaptiveElements< T >::countElmLev0 (int step, PViewData * in)
Definition at line 2620 of file adaptiveData.cpp.
Referenced by adaptiveData::countTotElmLev0().
init()
template<class T > void adaptiveElements< T >::init (int level)
Definition at line 1103 of file adaptiveData.cpp.
Referenced by adaptiveData::changeResolution(), and adaptiveData::changeResolutionForVTK().
Member Data Documentation
_coeffsGeom
template<class T > fullMatrix<double>* adaptiveElements< T >::_coeffsGeom private
Definition at line 599 of file adaptiveData.h.
Referenced by adaptiveElements< T >::adaptiveElements().
_coeffsVal
template<class T > fullMatrix<double>* adaptiveElements< T >::_coeffsVal private
Definition at line 598 of file adaptiveData.h.
Referenced by adaptiveElements< T >::adaptiveElements().
_eexpsGeom
template<class T > fullMatrix<double> * adaptiveElements< T >::_eexpsGeom private
Definition at line 599 of file adaptiveData.h.
Referenced by adaptiveElements< T >::adaptiveElements().
_eexpsVal
template<class T > fullMatrix<double> * adaptiveElements< T >::_eexpsVal private
Definition at line 598 of file adaptiveData.h.
Referenced by adaptiveElements< T >::adaptiveElements().
_interpolGeom
template<class T > fullMatrix<double> * adaptiveElements< T >::_interpolGeom private
Definition at line 599 of file adaptiveData.h.
_interpolVal
template<class T > fullMatrix<double> * adaptiveElements< T >::_interpolVal private
Definition at line 598 of file adaptiveData.h.
The documentation for this class was generated from the following files:
src/post/adaptiveData.h
src/post/adaptiveData.cpp