gmsh-TingyuanDoc: MQuadrangle Class Reference
MQuadrangle Class Reference
#include <MQuadrangle.h>
Public Member Functions
MQuadrangle (MVertex *v0, MVertex *v1, MVertex *v2, MVertex *v3, int num=0, int part=0)
MQuadrangle (const std::vector< MVertex * > &v, int num=0, int part=0)
~MQuadrangle ()
virtual double etaShapeMeasure ()
virtual double gammaShapeMeasure ()
virtual int getDim () const
virtual std::size_t getNumVertices () const
virtual MVertex * getVertex (int num)
virtual const MVertex * getVertex (int num) const
virtual void setVertex (int num, MVertex *v)
virtual MVertex * getVertexDIFF (int num)
virtual int getNumEdges () const
virtual MEdge getEdge (int num) const
virtual int numEdge2numVertex (int numEdge, int numVert) const
virtual int getNumEdgesRep (bool curved)
virtual void getEdgeRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getEdgeVertices (const int num, std::vector< MVertex * > &v) const
virtual int getNumFaces ()
virtual MFace getFace (int num) const
virtual MFaceN getHighOrderFace (int num, int sign, int rot)
virtual bool getFaceInfo (const MFace &face, int &ithFace, int &sign, int &rot) const
virtual int getNumFacesRep (bool curved)
virtual void getFaceRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getFaceVertices (const int num, std::vector< MVertex * > &v) const
virtual int getType () const
virtual int getTypeForMSH () const
virtual int getTypeForUNV () const
virtual int getTypeForVTK () const
virtual const char * getStringForPOS () const
virtual const char * getStringForBDF () const
virtual const char * getStringForDIFF () const
virtual const char * getStringForINP () const
virtual const char * getStringForKEY () const
virtual const char * getStringForRAD () const
virtual const char * getStringForTOCHNOG () const
virtual void getNode (int num, double &u, double &v, double &w) const
virtual SPoint3 barycenterUVW () const
virtual double getVolume ()
virtual void reverse ()
virtual void reorient (int rotation, bool swap)
virtual bool isInside (double u, double v, double w) const
virtual void getIntegrationPoints (int pOrder, int *npts, IntPt **pts)
virtual double angleShapeMeasure ()
virtual double getInnerRadius ()
virtual double getOuterRadius ()
virtual int numCommonNodesInDualGraph (const MElement *const other) const
virtual MEdge getEdgeSolin (int num)
virtual MFace getFaceSolin (int numFace)
Public Member Functions inherited from MElement
MElement (std::size_t num=0, int part=0)
virtual ~MElement ()
double getTolerance () const
virtual std::size_t getNum () const
void forceNum (std::size_t num)
virtual int getPolynomialOrder () const
virtual bool getIsAssimilatedSerendipity () const
virtual bool getIsOnlySerendipity () const
virtual int getPartition () const
virtual void setPartition (int num)
virtual char getVisibility () const
virtual void setVisibility (char val)
void getVertices (std::vector< MVertex * > &verts)
virtual void getVertexInfo (const MVertex *vertex, int &ithVertex) const
virtual MVertex * getVertexUNV (int num)
virtual MVertex * getVertexVTK (int num)
virtual MVertex * getVertexMATLAB (int num)
virtual MVertex * getVertexTOCHNOG (int num)
virtual MVertex * getVertexBDF (int num)
virtual MVertex * getVertexINP (int num)
virtual MVertex * getVertexKEY (int num)
virtual MVertex * getVertexRAD (int num)
virtual MVertex * getVertexNEU (int num)
virtual int getNumEdgeVertices () const
virtual int getNumFaceVertices () const
virtual int getNumVolumeVertices () const
std::size_t getNumPrimaryVertices () const
virtual MEdgeN getHighOrderEdge (int num, int sign)
MEdgeN getHighOrderEdge (const MEdge &edge)
virtual bool getEdgeInfo (const MEdge &edge, int &ithEdge, int &sign) const
MFaceN getHighOrderFace (const MFace &face)
virtual MElement * getParent () const
virtual void setParent (MElement *p, bool owner=false)
virtual void updateParent (GModel *gm)
virtual int getNumChildren () const
virtual MElement * getChild (int i) const
virtual bool ownsParent () const
virtual const MElement * getBaseElement () const
virtual MElement * getBaseElement ()
virtual MElement * getDomain (int i) const
virtual void setDomain (MElement *e, int i)
virtual double maxEdge ()
virtual double minEdge ()
double maxDistToStraight () const
double skewness ()
double minSICNShapeMeasure ()
double minSIGEShapeMeasure ()
double distoShapeMeasure ()
double minIsotropyMeasure (bool knownValid=false, bool reversedOk=false)
double minScaledJacobian (bool knownValid=false, bool reversedOk=false)
virtual void scaledJacRange (double &jmin, double &jmax, GEntity *ge=nullptr) const
virtual void idealJacRange (double &jmin, double &jmax, GEntity *ge=nullptr)
virtual void signedInvCondNumRange (double &iCNMin, double &iCNMax, GEntity *ge=nullptr)
virtual void signedInvGradErrorRange (double &minSIGE, double &maxSIGE)
virtual SPoint3 barycenter (bool primary=false) const
virtual SPoint3 fastBarycenter (bool primary=false) const
virtual SPoint3 barycenter_infty () const
virtual int getVolumeSign ()
virtual bool setVolumePositive ()
int getValidity ()
virtual std::string getInfoString (bool multline)
virtual const nodalBasis * getFunctionSpace (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getFuncSpaceData (int order=-1, bool serendip=false) const
virtual const JacobianBasis * getJacobianFuncSpace (int orderElement=-1) const
virtual const FuncSpaceData getJacobianFuncSpaceData (int orderElement=-1) const
virtual void getShapeFunctions (double u, double v, double w, double s[], int order=-1) const
virtual void getGradShapeFunctions (double u, double v, double w, double s[][3], int order=-1) const
virtual void getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order=-1) const
virtual void getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order=-1) const
virtual double getJacobian (const fullMatrix< double > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double *jac) const
virtual double getJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobian (double u, double v, double w, fullMatrix< double > &j) const
virtual double getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobianDeterminant (double u, double v, double w) const
void getSignedJacobian (fullVector< double > &jacobian, int o=-1) const
void getNodesCoord (fullMatrix< double > &nodesXYZ) const
void getNodesCoordNonSerendip (fullMatrix< double > &nodesXYZ) const
bezierCoeff * getBezierVerticesCoord () const
virtual std::size_t getNumShapeFunctions () const
virtual std::size_t getNumPrimaryShapeFunctions () const
virtual const MVertex * getShapeFunctionNode (int i) const
virtual MVertex * getShapeFunctionNode (int i)
virtual double getEigenvaluesMetric (double u, double v, double w, double values[3]) const
virtual void pnt (double u, double v, double w, SPoint3 &p) const
virtual void pnt (double u, double v, double w, double *p) const
virtual void pnt (const std::vector< double > &sf, SPoint3 &p) const
virtual void primaryPnt (double u, double v, double w, SPoint3 &p)
virtual void xyz2uvw (double xyz[3], double uvw[3]) const
virtual void movePointFromParentSpaceToElementSpace (double &u, double &v, double &w) const
virtual void movePointFromElementSpaceToParentSpace (double &u, double &v, double &w) const
double interpolate (double val[], double u, double v, double w, int stride=1, int order=-1)
void interpolateGrad (double val[], double u, double v, double w, double f[], int stride=1, double invjac[3][3]=nullptr, int order=-1)
void interpolateCurl (double val[], double u, double v, double w, double f[], int stride=3, int order=-1)
double interpolateDiv (double val[], double u, double v, double w, int stride=3, int order=-1)
double integrate (double val[], int pOrder, int stride=1, int order=-1)
double integrateCirc (double val[], int edge, int pOrder, int order=-1)
double integrateFlux (double val[], int face, int pOrder, int order=-1)
virtual void writeMSH2 (FILE *fp, double version=1.0, bool binary=false, int num=0, int elementary=1, int physical=1, int parentNum=0, int dom1Num=0, int dom2Num=0, std::vector< short > *ghosts=nullptr)
virtual void writeMSH3 (FILE *fp, bool binary=false, int elementary=1, std::vector< short > *ghosts=nullptr)
virtual void writePOS (FILE *fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor=1.0, int elementary=1)
virtual void writeSTL (FILE *fp, bool binary=false, double scalingFactor=1.0)
virtual void writeX3D (FILE *fp, double scalingFactor=1.0)
virtual void writeVRML (FILE *fp)
virtual void writePLY2 (FILE *fp)
virtual void writeUNV (FILE *fp, int num=0, int elementary=1, int physical=1)
virtual void writeVTK (FILE *fp, bool binary=false, bool bigEndian=false)
virtual void writeMATLAB (FILE *fp, int filetype, int elementary=0, int physical=0, bool binary=false)
virtual void writeTOCHNOG (FILE *fp, int num)
virtual void writeMESH (FILE *fp, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeNEU (FILE *fp, unsigned gambitType, int adjust, int phys=0)
virtual void writeIR3 (FILE *fp, int elementTagType, int num, int elementary, int physical)
virtual void writeBDF (FILE *fp, int format=0, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeDIFF (FILE *fp, int num, bool binary=false, int physical_property=1)
virtual void writeINP (FILE *fp, int num)
virtual void writeKEY (FILE *fp, int pid, int num)
virtual void writeRAD (FILE *fp, int num)
virtual void writeSU2 (FILE *fp, int num)
std::string getName ()
virtual std::size_t getNumVerticesForMSH ()
virtual void getVerticesIdForMSH (std::vector< int > &verts)
virtual MElement * copy (std::map< int, MVertex * > &vertexMap, std::map< MElement *, MElement * > &newParents, std::map< MElement *, MElement * > &newDomains)
Static Public Member Functions
static int edges_quad (const int edge, const int vert)
Static Public Member Functions inherited from MElement
static unsigned int getInfoMSH (const int typeMSH, const char **const name=nullptr)
Protected Member Functions
void _getEdgeVertices (const int num, std::vector< MVertex * > &v) const
void _getFaceVertices (std::vector< MVertex * > &v) const
void projectInMeanPlane (double *xn, double *yn)
Protected Member Functions inherited from MElement
void _getEdgeRep (MVertex *v0, MVertex *v1, double *x, double *y, double *z, SVector3 *n, int faceIndex=-1)
void _getFaceRep (MVertex *v0, MVertex *v1, MVertex *v2, double *x, double *y, double *z, SVector3 *n)
Protected Attributes
MVertex * _v [4]
Additional Inherited Members
Static Protected Member Functions inherited from MElement
static bool _getFaceInfo (const MFace &face, const MFace &other, int &sign, int &rot)
Static Protected Attributes inherited from MElement
static double _isInsideTolerance
Detailed Description
Definition at line 26 of file MQuadrangle.h.
Constructor & Destructor Documentation
MQuadrangle() [1/2]
MQuadrangle::MQuadrangle (MVertex * v0, MVertex * v1, MVertex * v2, MVertex * v3, int num = 0, int part = 0) inline
Definition at line 44 of file MQuadrangle.h.
MQuadrangle() [2/2]
MQuadrangle::MQuadrangle (const std::vector< MVertex * > & v, int num = 0, int part = 0) inline
Definition at line 53 of file MQuadrangle.h.
~MQuadrangle()
MQuadrangle::~MQuadrangle () inline
Definition at line 58 of file MQuadrangle.h.
Member Function Documentation
_getEdgeVertices()
void MQuadrangle::_getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline protected
Definition at line 29 of file MQuadrangle.h.
Referenced by getEdgeVertices(), MQuadrangle8::getEdgeVertices(), MQuadrangle9::getEdgeVertices(), and MQuadrangleN::getEdgeVertices().
_getFaceVertices()
void MQuadrangle::_getFaceVertices (std::vector< MVertex * > & v) const inline protected
Definition at line 34 of file MQuadrangle.h.
Referenced by getFaceVertices(), MQuadrangle8::getFaceVertices(), MQuadrangle9::getFaceVertices(), and MQuadrangleN::getFaceVertices().
angleShapeMeasure()
double MQuadrangle::angleShapeMeasure () virtual
Reimplemented from MElement.
Definition at line 318 of file MQuadrangle.cpp.
barycenterUVW()
virtual SPoint3 MQuadrangle::barycenterUVW () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 145 of file MQuadrangle.h.
edges_quad()
static int MQuadrangle::edges_quad (const int edge, const int vert) inline static
Definition at line 174 of file MQuadrangle.h.
Referenced by _getEdgeVertices(), Cell::findBdCellOrientation(), Cell::findBdElement(), getEdge(), getEdgeRep(), gmshGenerateMonomialsQuadrangle(), and numEdge2numVertex().
etaShapeMeasure()
double MQuadrangle::etaShapeMeasure () virtual
Reimplemented from MElement.
Definition at line 300 of file MQuadrangle.cpp.
Referenced by quadsToTriangles(), RecombineTriangle::RecombineTriangle(), and MElement::skewness().
gammaShapeMeasure()
double MQuadrangle::gammaShapeMeasure () virtual
Reimplemented from MElement.
Definition at line 309 of file MQuadrangle.cpp.
getDim()
virtual int MQuadrangle::getDim () const inline virtual
Implements MElement.
Definition at line 62 of file MQuadrangle.h.
getEdge()
virtual MEdge MQuadrangle::getEdge (int num) const inline virtual
Implements MElement.
Definition at line 73 of file MQuadrangle.h.
getEdgeRep()
void MQuadrangle::getEdgeRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Implements MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 20 of file MQuadrangle.cpp.
Referenced by MQuadrangle8::getEdgeRep(), MQuadrangle9::getEdgeRep(), and MQuadrangleN::getEdgeRep().
getEdgeSolin()
virtual MEdge MQuadrangle::getEdgeSolin (int num) inline virtual
Reimplemented from MElement.
Definition at line 180 of file MQuadrangle.h.
getEdgeVertices()
virtual void MQuadrangle::getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 84 of file MQuadrangle.h.
getFace()
virtual MFace MQuadrangle::getFace (int num) const inline virtual
Implements MElement.
Definition at line 90 of file MQuadrangle.h.
Referenced by _myGetEdgeRep().
getFaceInfo()
bool MQuadrangle::getFaceInfo (const MFace & face, int & ithFace, int & sign, int & rot) const virtual
Reimplemented from MElement.
Definition at line 148 of file MQuadrangle.cpp.
getFaceRep()
void MQuadrangle::getFaceRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Implements MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 246 of file MQuadrangle.cpp.
Referenced by MQuadrangle8::getFaceRep(), MQuadrangle9::getFaceRep(), and MQuadrangleN::getFaceRep().
getFaceSolin()
virtual MFace MQuadrangle::getFaceSolin (int numFace) inline virtual
Reimplemented from MElement.
Definition at line 185 of file MQuadrangle.h.
getFaceVertices()
virtual void MQuadrangle::getFaceVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 100 of file MQuadrangle.h.
getHighOrderFace()
MFaceN MQuadrangle::getHighOrderFace (int num, int sign, int rot) virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 569 of file MQuadrangle.cpp.
getInnerRadius()
double MQuadrangle::getInnerRadius () virtual
Reimplemented from MElement.
Definition at line 333 of file MQuadrangle.cpp.
Referenced by MHexahedron::getInnerRadius().
getIntegrationPoints()
void MQuadrangle::getIntegrationPoints (int pOrder, int * npts, IntPt ** pts) virtual
Reimplemented from MElement.
Definition at line 294 of file MQuadrangle.cpp.
getNode()
virtual void MQuadrangle::getNode (int num, double & u, double & v, double & w) const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 119 of file MQuadrangle.h.
Referenced by MQuadrangle8::getNode(), MQuadrangle9::getNode(), and MQuadrangleN::getNode().
getNumEdges()
virtual int MQuadrangle::getNumEdges () const inline virtual
Implements MElement.
Definition at line 72 of file MQuadrangle.h.
getNumEdgesRep()
virtual int MQuadrangle::getNumEdgesRep (bool curved) inline virtual
Implements MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 81 of file MQuadrangle.h.
getNumFaces()
virtual int MQuadrangle::getNumFaces () inline virtual
Implements MElement.
Definition at line 89 of file MQuadrangle.h.
getNumFacesRep()
int MQuadrangle::getNumFacesRep (bool curved) virtual
Implements MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 158 of file MQuadrangle.cpp.
Referenced by MQuadrangle8::getNumFacesRep(), MQuadrangle9::getNumFacesRep(), and MQuadrangleN::getNumFacesRep().
getNumVertices()
virtual std::size_t MQuadrangle::getNumVertices () const inline virtual
Implements MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 63 of file MQuadrangle.h.
Referenced by getHighOrderFace(), getVolume(), and Subdivide().
getOuterRadius()
double MQuadrangle::getOuterRadius () virtual
Reimplemented from MElement.
Definition at line 327 of file MQuadrangle.cpp.
getStringForBDF()
virtual const char* MQuadrangle::getStringForBDF () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangle9, and MQuadrangle8.
Definition at line 113 of file MQuadrangle.h.
getStringForDIFF()
virtual const char* MQuadrangle::getStringForDIFF () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangle9, and MQuadrangle8.
Definition at line 114 of file MQuadrangle.h.
getStringForINP()
virtual const char* MQuadrangle::getStringForINP () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangle9, and MQuadrangle8.
Definition at line 115 of file MQuadrangle.h.
getStringForKEY()
virtual const char* MQuadrangle::getStringForKEY () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangle8.
Definition at line 116 of file MQuadrangle.h.
getStringForPOS()
virtual const char* MQuadrangle::getStringForPOS () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, and MQuadrangle9.
Definition at line 112 of file MQuadrangle.h.
getStringForRAD()
virtual const char* MQuadrangle::getStringForRAD () const inline virtual
Reimplemented from MElement.
Definition at line 117 of file MQuadrangle.h.
getStringForTOCHNOG()
virtual const char* MQuadrangle::getStringForTOCHNOG () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangle9.
Definition at line 118 of file MQuadrangle.h.
getType()
virtual int MQuadrangle::getType () const inline virtual
Implements MElement.
Definition at line 105 of file MQuadrangle.h.
getTypeForMSH()
virtual int MQuadrangle::getTypeForMSH () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 106 of file MQuadrangle.h.
getTypeForUNV()
virtual int MQuadrangle::getTypeForUNV () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangle8.
Definition at line 107 of file MQuadrangle.h.
getTypeForVTK()
virtual int MQuadrangle::getTypeForVTK () const inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 111 of file MQuadrangle.h.
Referenced by MQuadrangleN::getTypeForVTK().
getVertex() [1/2]
virtual MVertex* MQuadrangle::getVertex (int num) inline virtual
Implements MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 64 of file MQuadrangle.h.
Referenced by _removeDiamonds(), qmQuadrangle::eta(), getFaceRep(), getVertexDIFF(), qmQuadrangle::NCJRange(), compareMQuadrangleLexicographic::operator()(), quadsToTriangles(), setHighOrder(), and Subdivide().
getVertex() [2/2]
virtual const MVertex* MQuadrangle::getVertex (int num) const inline virtual
Implements MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 65 of file MQuadrangle.h.
getVertexDIFF()
virtual MVertex* MQuadrangle::getVertexDIFF (int num) inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangle9, and MQuadrangle8.
Definition at line 67 of file MQuadrangle.h.
getVolume()
double MQuadrangle::getVolume () virtual
Reimplemented from MElement.
Definition at line 61 of file MQuadrangle.cpp.
isInside()
virtual bool MQuadrangle::isInside (double u, double v, double w) const inline virtual
Implements MElement.
Definition at line 158 of file MQuadrangle.h.
numCommonNodesInDualGraph()
int MQuadrangle::numCommonNodesInDualGraph (const MElement *const other) const virtual
Implements MElement.
Definition at line 75 of file MQuadrangle.cpp.
numEdge2numVertex()
virtual int MQuadrangle::numEdge2numVertex (int numEdge, int numVert) const inline virtual
Reimplemented from MElement.
Definition at line 77 of file MQuadrangle.h.
projectInMeanPlane()
void MQuadrangle::projectInMeanPlane (double * xn, double * yn) protected
reorient()
void MQuadrangle::reorient (int rotation, bool swap) virtual
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 464 of file MQuadrangle.cpp.
Referenced by GFace::alignElementsWithMaster(), GModel::alignPeriodicBoundaries(), MQuadrangle8::reorient(), and MQuadrangle9::reorient().
reverse()
virtual void MQuadrangle::reverse () inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 147 of file MQuadrangle.h.
setVertex()
virtual void MQuadrangle::setVertex (int num, MVertex * v) inline virtual
Reimplemented from MElement.
Reimplemented in MQuadrangleN, MQuadrangle9, and MQuadrangle8.
Definition at line 66 of file MQuadrangle.h.
Member Data Documentation
_v
MVertex* MQuadrangle::_v[4] protected
Definition at line 28 of file MQuadrangle.h.
Referenced by _getEdgeVertices(), _getFaceVertices(), getEdge(), getEdgeRep(), getEdgeSolin(), getFace(), getFaceInfo(), getFaceRep(), getFaceSolin(), getHighOrderFace(), MQuadrangle8::getHighOrderFace(), MQuadrangle9::getHighOrderFace(), getInnerRadius(), getVertex(), MQuadrangle8::getVertex(), MQuadrangle9::getVertex(), MQuadrangleN::getVertex(), getVolume(), MQuadrangle(), reorient(), MQuadrangleN::reorient(), reverse(), MQuadrangle8::reverse(), MQuadrangle9::reverse(), MQuadrangleN::reverse(), setVertex(), MQuadrangle8::setVertex(), MQuadrangle9::setVertex(), and MQuadrangleN::setVertex().
The documentation for this class was generated from the following files:
src/geo/MQuadrangle.h
src/geo/MQuadrangle.cpp