gmsh-TingyuanDoc: smooth_normals Class Reference
smooth_normals Class Reference
#include <SmoothData.h>
Public Member Functions
smooth_normals (double angle)
void add (double x, double y, double z, double nx, double ny, double nz)
bool get (double x, double y, double z, double &nx, double &ny, double &nz) const
Private Attributes
float tol
std::set< xyzn, lessthanxyzn > c
Detailed Description
Definition at line 100 of file SmoothData.h.
Constructor & Destructor Documentation
smooth_normals()
smooth_normals::smooth_normals (double angle) inline
Definition at line 106 of file SmoothData.h.
Member Function Documentation
add()
void smooth_normals::add (double x, double y, double z, double nx, double ny, double nz)
Definition at line 215 of file SmoothData.cpp.
Referenced by addOutlineQuadrangle(), addOutlineTriangle(), addScalarTetrahedron(), addScalarTriangle(), addSmoothNormals(), and GMSH_WarpPlugin::execute().
get()
bool smooth_normals::get (double x, double y, double z, double & nx, double & ny, double & nz) const
Definition at line 234 of file SmoothData.cpp.
Referenced by addElementsInArrays(), addOutlineQuadrangle(), addOutlineTriangle(), addScalarTetrahedron(), addScalarTriangle(), and GMSH_WarpPlugin::execute().
Member Data Documentation
c
std::set<xyzn, lessthanxyzn> smooth_normals::c private
Definition at line 103 of file SmoothData.h.
Referenced by add(), and get().
tol
float smooth_normals::tol private
Definition at line 102 of file SmoothData.h.
Referenced by add(), and get().
The documentation for this class was generated from the following files:
src/common/SmoothData.h
src/common/SmoothData.cpp