gmsh-TingyuanDoc: GMSH_CutGridPlugin Class Reference
GMSH_CutGridPlugin Class Reference
#include <CutGrid.h>
Public Member Functions
GMSH_CutGridPlugin ()
std::string getName () const
std::string getShortHelp () const
std::string getHelp () const
int getNbOptions () const
StringXNumber * getOption (int iopt)
PView * execute (PView *)
Public Member Functions inherited from GMSH_PostPlugin
GMSH_PLUGIN_TYPE getType () const
virtual int run ()
virtual PView * executeRemote (PView *)
virtual PView * getView (int index, PView *view)
virtual PViewDataList * getDataList (PView *view, bool showError=true)
virtual PViewData * getPossiblyAdaptiveData (PView *view)
virtual void assignSpecificVisibility () const
virtual bool geometricalFilter (fullMatrix< double > *) const
Public Member Functions inherited from GMSH_Plugin
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
virtual int getNbOptionsStr () const
virtual StringXString * getOptionStr (int iopt)
std::string serialize ()
Static Public Member Functions
static int getNbU ()
static int getNbV ()
static void getPoint (int iU, int iV, double *X)
static double callbackX0 (int, int, double)
static double callbackY0 (int, int, double)
static double callbackZ0 (int, int, double)
static double callbackX1 (int, int, double)
static double callbackY1 (int, int, double)
static double callbackZ1 (int, int, double)
static double callbackX2 (int, int, double)
static double callbackY2 (int, int, double)
static double callbackZ2 (int, int, double)
static double callbackU (int, int, double)
static double callbackV (int, int, double)
static double callbackConnect (int, int, double)
static void draw (void *context)
Static Public Member Functions inherited from GMSH_Plugin
static void setDrawFunction (void(*fct)(void *))
Private Member Functions
void addInView (int numsteps, int connect, int nbcomp, double ***pnts, double ***vals, std::vector< double > &P, int *nP, std::vector< double > &L, int *nL, std::vector< double > &Q, int *nQ)
PView * GenerateView (PView *v, int connectPoints)
Static Private Member Functions
static double callback (int num, int action, double value, double *opt, double step, double min, double max)
Additional Inherited Members
Public Types inherited from GMSH_Plugin
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Public Attributes inherited from GMSH_Plugin
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes inherited from GMSH_Plugin
static void(* draw)(void *) = nullptr
Detailed Description
Definition at line 15 of file CutGrid.h.
Constructor & Destructor Documentation
GMSH_CutGridPlugin()
GMSH_CutGridPlugin::GMSH_CutGridPlugin () inline
Definition at line 25 of file CutGrid.h.
Member Function Documentation
addInView()
void GMSH_CutGridPlugin::addInView (int numsteps, int connect, int nbcomp, double *** pnts, double *** vals, std::vector< double > & P, int * nP, std::vector< double > & L, int * nL, std::vector< double > & Q, int * nQ) private
Definition at line 218 of file CutGrid.cpp.
Referenced by GenerateView().
callback()
double GMSH_CutGridPlugin::callback (int num, int action, double value, double * opt, double step, double min, double max) static private
Definition at line 79 of file CutGrid.cpp.
Referenced by callbackConnect(), callbackU(), callbackV(), callbackX0(), callbackX1(), callbackX2(), callbackY0(), callbackY1(), callbackY2(), callbackZ0(), callbackZ1(), and callbackZ2().
callbackConnect()
double GMSH_CutGridPlugin::callbackConnect (int num, int action, double value) static
Definition at line 168 of file CutGrid.cpp.
callbackU()
double GMSH_CutGridPlugin::callbackU (int num, int action, double value) static
Definition at line 157 of file CutGrid.cpp.
callbackV()
double GMSH_CutGridPlugin::callbackV (int num, int action, double value) static
Definition at line 162 of file CutGrid.cpp.
callbackX0()
double GMSH_CutGridPlugin::callbackX0 (int num, int action, double value) static
Definition at line 94 of file CutGrid.cpp.
callbackX1()
double GMSH_CutGridPlugin::callbackX1 (int num, int action, double value) static
Definition at line 115 of file CutGrid.cpp.
callbackX2()
double GMSH_CutGridPlugin::callbackX2 (int num, int action, double value) static
Definition at line 136 of file CutGrid.cpp.
callbackY0()
double GMSH_CutGridPlugin::callbackY0 (int num, int action, double value) static
Definition at line 101 of file CutGrid.cpp.
callbackY1()
double GMSH_CutGridPlugin::callbackY1 (int num, int action, double value) static
Definition at line 122 of file CutGrid.cpp.
callbackY2()
double GMSH_CutGridPlugin::callbackY2 (int num, int action, double value) static
Definition at line 143 of file CutGrid.cpp.
callbackZ0()
double GMSH_CutGridPlugin::callbackZ0 (int num, int action, double value) static
Definition at line 108 of file CutGrid.cpp.
callbackZ1()
double GMSH_CutGridPlugin::callbackZ1 (int num, int action, double value) static
Definition at line 129 of file CutGrid.cpp.
callbackZ2()
double GMSH_CutGridPlugin::callbackZ2 (int num, int action, double value) static
Definition at line 150 of file CutGrid.cpp.
draw()
void GMSH_CutGridPlugin::draw (void * context) static
Definition at line 34 of file CutGrid.cpp.
execute()
PView * GMSH_CutGridPlugin::execute (PView * v) virtual
Implements GMSH_PostPlugin.
Definition at line 378 of file CutGrid.cpp.
GenerateView()
PView * GMSH_CutGridPlugin::GenerateView (PView * v, int connectPoints) private
Definition at line 307 of file CutGrid.cpp.
Referenced by execute().
getHelp()
std::string GMSH_CutGridPlugin::getHelp () const virtual
Implements GMSH_Plugin.
Definition at line 173 of file CutGrid.cpp.
getName()
std::string GMSH_CutGridPlugin::getName () const inline virtual
Implements GMSH_Plugin.
Definition at line 26 of file CutGrid.h.
getNbOptions()
int GMSH_CutGridPlugin::getNbOptions () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 189 of file CutGrid.cpp.
getNbU()
int GMSH_CutGridPlugin::getNbU () static
Definition at line 199 of file CutGrid.cpp.
Referenced by addInView(), draw(), GenerateView(), and getPoint().
getNbV()
int GMSH_CutGridPlugin::getNbV () static
Definition at line 201 of file CutGrid.cpp.
Referenced by addInView(), draw(), GenerateView(), and getPoint().
getOption()
StringXNumber * GMSH_CutGridPlugin::getOption (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 194 of file CutGrid.cpp.
getPoint()
void GMSH_CutGridPlugin::getPoint (int iU, int iV, double * X) static
Definition at line 203 of file CutGrid.cpp.
Referenced by draw(), and GenerateView().
getShortHelp()
std::string GMSH_CutGridPlugin::getShortHelp () const inline virtual
Implements GMSH_Plugin.
Definition at line 27 of file CutGrid.h.
The documentation for this class was generated from the following files:
src/plugin/CutGrid.h
src/plugin/CutGrid.cpp