gmsh-TingyuanDoc: GMSH_CutBoxPlugin Class Reference
GMSH_CutBoxPlugin Class Reference
#include <CutBox.h>
Public Member Functions
GMSH_CutBoxPlugin ()
std::string getName () const
std::string getShortHelp () const
std::string getHelp () const
int getNbOptions () const
StringXNumber * getOption (int iopt)
PView * execute (PView *)
Public Member Functions inherited from GMSH_PostPlugin
GMSH_PLUGIN_TYPE getType () const
virtual int run ()
virtual PView * executeRemote (PView *)
virtual PView * getView (int index, PView *view)
virtual PViewDataList * getDataList (PView *view, bool showError=true)
virtual PViewData * getPossiblyAdaptiveData (PView *view)
virtual void assignSpecificVisibility () const
virtual bool geometricalFilter (fullMatrix< double > *) const
Public Member Functions inherited from GMSH_Plugin
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
virtual int getNbOptionsStr () const
virtual StringXString * getOptionStr (int iopt)
std::string serialize ()
Static Public Member Functions
static int getNbU ()
static int getNbV ()
static int getNbW ()
static void getPoint (int iU, int iV, int iW, double *X)
static double callbackX0 (int, int, double)
static double callbackY0 (int, int, double)
static double callbackZ0 (int, int, double)
static double callbackX1 (int, int, double)
static double callbackY1 (int, int, double)
static double callbackZ1 (int, int, double)
static double callbackX2 (int, int, double)
static double callbackY2 (int, int, double)
static double callbackZ2 (int, int, double)
static double callbackX3 (int, int, double)
static double callbackY3 (int, int, double)
static double callbackZ3 (int, int, double)
static double callbackU (int, int, double)
static double callbackV (int, int, double)
static double callbackW (int, int, double)
static double callbackConnect (int, int, double)
static double callbackBoundary (int, int, double)
static void draw (void *context)
Static Public Member Functions inherited from GMSH_Plugin
static void setDrawFunction (void(*fct)(void *))
Private Member Functions
void addInView (int connect, int boundary, int numsteps, int nbcomp, double ****pnts, double ****vals, std::vector< double > &P, int *nP, std::vector< double > &L, int *nL, std::vector< double > &Q, int *nQ, std::vector< double > &H, int *nH)
PView * GenerateView (PView *v, int connectPoints, int boundary)
Static Private Member Functions
static double callback (int num, int action, double value, double *opt, double step, double min, double max)
Additional Inherited Members
Public Types inherited from GMSH_Plugin
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Public Attributes inherited from GMSH_Plugin
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes inherited from GMSH_Plugin
static void(* draw)(void *) = nullptr
Detailed Description
Definition at line 15 of file CutBox.h.
Constructor & Destructor Documentation
GMSH_CutBoxPlugin()
GMSH_CutBoxPlugin::GMSH_CutBoxPlugin () inline
Definition at line 26 of file CutBox.h.
Member Function Documentation
addInView()
void GMSH_CutBoxPlugin::addInView (int connect, int boundary, int numsteps, int nbcomp, double **** pnts, double **** vals, std::vector< double > & P, int * nP, std::vector< double > & L, int * nL, std::vector< double > & Q, int * nQ, std::vector< double > & H, int * nH) private
Definition at line 343 of file CutBox.cpp.
Referenced by GenerateView().
callback()
double GMSH_CutBoxPlugin::callback (int num, int action, double value, double * opt, double step, double min, double max) static private
Definition at line 164 of file CutBox.cpp.
Referenced by callbackBoundary(), callbackConnect(), callbackU(), callbackV(), callbackW(), callbackX0(), callbackX1(), callbackX2(), callbackX3(), callbackY0(), callbackY1(), callbackY2(), callbackY3(), callbackZ0(), callbackZ1(), callbackZ2(), and callbackZ3().
callbackBoundary()
double GMSH_CutBoxPlugin::callbackBoundary (int num, int action, double value) static
Definition at line 283 of file CutBox.cpp.
callbackConnect()
double GMSH_CutBoxPlugin::callbackConnect (int num, int action, double value) static
Definition at line 278 of file CutBox.cpp.
callbackU()
double GMSH_CutBoxPlugin::callbackU (int num, int action, double value) static
Definition at line 263 of file CutBox.cpp.
callbackV()
double GMSH_CutBoxPlugin::callbackV (int num, int action, double value) static
Definition at line 268 of file CutBox.cpp.
callbackW()
double GMSH_CutBoxPlugin::callbackW (int num, int action, double value) static
Definition at line 273 of file CutBox.cpp.
callbackX0()
double GMSH_CutBoxPlugin::callbackX0 (int num, int action, double value) static
Definition at line 179 of file CutBox.cpp.
callbackX1()
double GMSH_CutBoxPlugin::callbackX1 (int num, int action, double value) static
Definition at line 200 of file CutBox.cpp.
callbackX2()
double GMSH_CutBoxPlugin::callbackX2 (int num, int action, double value) static
Definition at line 221 of file CutBox.cpp.
callbackX3()
double GMSH_CutBoxPlugin::callbackX3 (int num, int action, double value) static
Definition at line 242 of file CutBox.cpp.
callbackY0()
double GMSH_CutBoxPlugin::callbackY0 (int num, int action, double value) static
Definition at line 186 of file CutBox.cpp.
callbackY1()
double GMSH_CutBoxPlugin::callbackY1 (int num, int action, double value) static
Definition at line 207 of file CutBox.cpp.
callbackY2()
double GMSH_CutBoxPlugin::callbackY2 (int num, int action, double value) static
Definition at line 228 of file CutBox.cpp.
callbackY3()
double GMSH_CutBoxPlugin::callbackY3 (int num, int action, double value) static
Definition at line 249 of file CutBox.cpp.
callbackZ0()
double GMSH_CutBoxPlugin::callbackZ0 (int num, int action, double value) static
Definition at line 193 of file CutBox.cpp.
callbackZ1()
double GMSH_CutBoxPlugin::callbackZ1 (int num, int action, double value) static
Definition at line 214 of file CutBox.cpp.
callbackZ2()
double GMSH_CutBoxPlugin::callbackZ2 (int num, int action, double value) static
Definition at line 235 of file CutBox.cpp.
callbackZ3()
double GMSH_CutBoxPlugin::callbackZ3 (int num, int action, double value) static
Definition at line 256 of file CutBox.cpp.
draw()
void GMSH_CutBoxPlugin::draw (void * context) static
Definition at line 39 of file CutBox.cpp.
execute()
PView * GMSH_CutBoxPlugin::execute (PView * v) virtual
Implements GMSH_PostPlugin.
Definition at line 1104 of file CutBox.cpp.
GenerateView()
PView * GMSH_CutBoxPlugin::GenerateView (PView * v, int connectPoints, int boundary) private
Definition at line 1016 of file CutBox.cpp.
Referenced by execute().
getHelp()
std::string GMSH_CutBoxPlugin::getHelp () const virtual
Implements GMSH_Plugin.
Definition at line 288 of file CutBox.cpp.
getName()
std::string GMSH_CutBoxPlugin::getName () const inline virtual
Implements GMSH_Plugin.
Definition at line 27 of file CutBox.h.
getNbOptions()
int GMSH_CutBoxPlugin::getNbOptions () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 307 of file CutBox.cpp.
getNbU()
int GMSH_CutBoxPlugin::getNbU () static
Definition at line 317 of file CutBox.cpp.
Referenced by addInView(), draw(), GenerateView(), and getPoint().
getNbV()
int GMSH_CutBoxPlugin::getNbV () static
Definition at line 319 of file CutBox.cpp.
Referenced by addInView(), draw(), GenerateView(), and getPoint().
getNbW()
int GMSH_CutBoxPlugin::getNbW () static
Definition at line 321 of file CutBox.cpp.
Referenced by addInView(), draw(), GenerateView(), and getPoint().
getOption()
StringXNumber * GMSH_CutBoxPlugin::getOption (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 312 of file CutBox.cpp.
getPoint()
void GMSH_CutBoxPlugin::getPoint (int iU, int iV, int iW, double * X) static
Definition at line 323 of file CutBox.cpp.
Referenced by draw(), and GenerateView().
getShortHelp()
std::string GMSH_CutBoxPlugin::getShortHelp () const inline virtual
Implements GMSH_Plugin.
Definition at line 28 of file CutBox.h.
The documentation for this class was generated from the following files:
src/plugin/CutBox.h
src/plugin/CutBox.cpp