gmsh-TingyuanDoc: Popen2 Class Reference
Popen2 Class Reference
Public Member Functions
Popen2 ()
void stop ()
bool started () const
bool start (const char *command)
bool read (void *data, size_t size)
bool write (void *data, size_t size)
~Popen2 ()
Private Attributes
int _fdIn
int _fdOut
Detailed Description
Definition at line 1338 of file Field.cpp.
Constructor & Destructor Documentation
Popen2()
Popen2::Popen2 () inline
Definition at line 1343 of file Field.cpp.
~Popen2()
Popen2::~Popen2 () inline
Definition at line 1382 of file Field.cpp.
Member Function Documentation
read()
bool Popen2::read (void * data, size_t size) inline
Definition at line 1374 of file Field.cpp.
Referenced by ExternalProcessField::operator()().
start()
bool Popen2::start (const char * command) inline
Definition at line 1353 of file Field.cpp.
Referenced by ExternalProcessField::operator()().
started()
bool Popen2::started () const inline
Definition at line 1352 of file Field.cpp.
Referenced by ExternalProcessField::closePipes().
stop()
void Popen2::stop () inline
Definition at line 1344 of file Field.cpp.
Referenced by ExternalProcessField::closePipes(), start(), and ~Popen2().
write()
bool Popen2::write (void * data, size_t size) inline
Definition at line 1378 of file Field.cpp.
Referenced by ExternalProcessField::closePipes(), and ExternalProcessField::operator()().
Member Data Documentation
_fdIn
int Popen2::_fdIn private
Definition at line 1340 of file Field.cpp.
Referenced by Popen2(), read(), start(), started(), and stop().
_fdOut
int Popen2::_fdOut private
Definition at line 1340 of file Field.cpp.
Referenced by Popen2(), start(), stop(), and write().
The documentation for this class was generated from the following file:
src/mesh/Field.cpp