gmsh-TingyuanDoc: GModel Class Reference
GModel Class Reference
#include <GModel.h>
Public Types
typedef std::set< GRegion *, GEntityPtrLessThan >::iterator riter
typedef std::set< GFace *, GEntityPtrLessThan >::iterator fiter
typedef std::set< GEdge *, GEntityPtrLessThan >::iterator eiter
typedef std::set< GVertex *, GEntityPtrLessThan >::iterator viter
typedef std::set< GRegion *, GEntityPtrLessThan >::const_iterator const_riter
typedef std::set< GFace *, GEntityPtrLessThan >::const_iterator const_fiter
typedef std::set< GEdge *, GEntityPtrLessThan >::const_iterator const_eiter
typedef std::set< GVertex *, GEntityPtrLessThan >::const_iterator const_viter
typedef std::map< std::pair< int, int >, std::string >::iterator piter
Public Member Functions
GModel (const std::string &name="")
virtual ~GModel ()
int setAsCurrent ()
void destroy (bool keepName=false)
std::size_t getMaxVertexNumber () const
std::size_t getMaxElementNumber () const
void setMaxVertexNumber (std::size_t num)
void setMaxElementNumber (std::size_t num)
std::size_t incrementAndGetMaxVertexNumber ()
std::size_t incrementAndGetMaxElementNumber ()
void decrementMaxVertexNumber ()
void checkPointMaxNumbers ()
void getCheckPointedMaxNumbers (std::size_t &maxv, std::size_t &maxe) const
std::size_t addMEdge (MEdge &edge, std::size_t num=0)
std::size_t addMFace (MFace &face, std::size_t num=0)
std::size_t getMEdge (MVertex *v0, MVertex *v1, MEdge &edge)
std::size_t getMFace (MVertex *v0, MVertex *v1, MVertex *v2, MVertex *v3, MFace &face)
hashmapMEdge::const_iterator firstMEdge ()
hashmapMEdge::const_iterator lastMEdge ()
hashmapMFace::const_iterator firstMFace ()
hashmapMFace::const_iterator lastMFace ()
void renumberMeshVertices ()
void renumberMeshElements ()
void destroyMeshCaches ()
void deleteMesh ()
void deleteMesh (const std::vector< GEntity * > &entities)
void deleteVertexArrays ()
void pruneMeshVertexAssociations ()
void createGEOInternals ()
void createOCCInternals ()
void createACISInternals ()
void createParasolidInternals ()
OCC_Internals * getOCCInternals ()
GEO_Internals * getGEOInternals ()
ACIS_Internals * getACISInternals ()
Parasolid_Internals * getParasolidInternals ()
void deleteGEOInternals ()
void deleteOCCInternals ()
void resetOCCInternals ()
void deleteACISInternals ()
void deleteParasolidInternals ()
FieldManager * getFields ()
void setName (const std::string &name)
std::string getName () const
void setFileName (const std::string &fileName)
std::string getFileName () const
bool hasFileName (const std::string &name) const
char getVisibility () const
void setVisibility (char val)
std::size_t getNumRegions () const
std::size_t getNumFaces () const
std::size_t getNumEdges () const
std::size_t getNumVertices () const
bool empty () const
riter firstRegion ()
fiter firstFace ()
eiter firstEdge ()
viter firstVertex ()
riter lastRegion ()
fiter lastFace ()
eiter lastEdge ()
viter lastVertex ()
const_riter firstRegion () const
const_fiter firstFace () const
const_eiter firstEdge () const
const_viter firstVertex () const
const_riter lastRegion () const
const_fiter lastFace () const
const_eiter lastEdge () const
const_viter lastVertex () const
std::set< GRegion *, GEntityPtrLessThan > getRegions () const
std::set< GFace *, GEntityPtrLessThan > getFaces () const
std::set< GEdge *, GEntityPtrLessThan > getEdges () const
std::set< GVertex *, GEntityPtrLessThan > getVertices () const
GRegion * getRegionByTag (int n) const
GFace * getFaceByTag (int n) const
GEdge * getEdgeByTag (int n) const
GVertex * getVertexByTag (int n) const
GEntity * getEntityByTag (int dim, int n) const
bool changeEntityTag (int dim, int tag, int newTag)
bool add (GRegion *r)
bool add (GFace *f)
bool add (GEdge *e)
bool add (GVertex *v)
bool remove (GRegion *r)
bool remove (GFace *f)
bool remove (GEdge *e)
bool remove (GVertex *v)
void remove (int dim, int tag, std::vector< GEntity * > &removed, bool recursive=false)
void remove (const std::vector< std::pair< int, int > > &dimTags, std::vector< GEntity * > &removed, bool recursive=false)
void remove ()
void snapVertices ()
void getEntities (std::vector< GEntity * > &entities, int dim=-1) const
void getEntitiesInBox (std::vector< GEntity * > &entities, const SBoundingBox3d &box, int dim=-1) const
bool getBoundaryTags (const std::vector< std::pair< int, int > > &inDimTags, std::vector< std::pair< int, int > > &outDimTags, bool combined, bool oriented=true, bool recursive=false)
int getMaxElementaryNumber (int dim)
bool noPhysicalGroups ()
void getPhysicalGroups (std::map< int, std::vector< GEntity * > > groups[4]) const
void getPhysicalGroups (int dim, std::map< int, std::vector< GEntity * > > &groups) const
const std::map< std::pair< int, int >, std::string > & getPhysicalNames () const
void setPhysicalNames (const std::map< std::pair< int, int >, std::string > &names)
void addPhysicalGroup (int dim, int tag, const std::vector< int > &tags)
void removePhysicalGroups ()
void removePhysicalGroup (int dim, int num)
int getMaxPhysicalNumber (int dim)
piter firstPhysicalName ()
piter lastPhysicalName ()
piter firstElementaryName ()
piter lastElementaryName ()
int numPhysicalNames () const
void getInnerPhysicalNamesIterators (std::vector< piter > &iterators)
int setPhysicalName (const std::string &name, int dim, int num=0)
piter setPhysicalName (piter pos, const std::string &name, int dim, int num=0)
std::string getPhysicalName (int dim, int num) const
void removePhysicalName (const std::string &name)
int getPhysicalNumber (const int &dim, const std::string &name)
std::vector< int > getTagsForPhysicalName (int dim, const std::string &name)
void setPhysicalNumToEntitiesInBox (int EntityDimension, int PhysicalNumber, std::vector< double > p1, std::vector< double > p2)
void setPhysicalNumToEntitiesInBox (int EntityDimension, int PhysicalNumber, const SBoundingBox3d &box)
std::string getElementaryName (int dim, int tag)
void setElementaryName (int dim, int tag, const std::string &name)
void removeElementaryName (const std::string &name)
int getDim () const
int getMeshDim () const
void setSelection (int val)
SBoundingBox3d bounds (bool aroundVisible=false)
int getMeshStatus (bool countDiscrete=true)
std::size_t getNumMeshElements (int dim=-1) const
std::size_t getNumMeshParentElements () const
std::size_t getNumMeshElements (unsigned c[6])
MElement * getMeshElementByCoord (SPoint3 &p, SPoint3 &param, int dim=-1, bool strict=true)
std::vector< MElement * > getMeshElementsByCoord (SPoint3 &p, int dim=-1, bool strict=true)
MElement * getMeshElementByTag (int n)
MElement * getMeshElementByTag (int n, int &entityTag)
int getMeshElementIndex (MElement *e)
void setMeshElementIndex (MElement *e, int index)
std::size_t getNumMeshVertices (int dim=-1) const
void rebuildMeshVertexCache (bool onlyIfNecessary=false)
void rebuildMeshElementCache (bool onlyIfNecessary=false)
MVertex * getMeshVertexByTag (int n)
void addMVertexToVertexCache (MVertex *v)
void getMeshVerticesForPhysicalGroup (int dim, int num, std::vector< MVertex * > &)
std::size_t indexMeshVertices (bool all, int singlePartition=0, bool renumber=true)
void scaleMesh (double factor)
void setCurrentMeshEntity (GEntity *e)
GEntity * getCurrentMeshEntity ()
void clearLastMeshEntityError ()
void addLastMeshEntityError (GEntity *e)
std::vector< GEntity * > getLastMeshEntityError ()
void clearLastMeshVertexError ()
void addLastMeshVertexError (MVertex *v)
std::vector< MVertex * > getLastMeshVertexError ()
std::size_t removeInvisibleElements ()
std::size_t reverseInvisibleElements ()
std::size_t getNumPartitions () const
void setNumPartitions (std::size_t npart)
int partitionMesh (int num, std::vector< std::pair< MElement *, int > > elementPartition=std::vector< std::pair< MElement *, int > >())
int unpartitionMesh ()
int convertOldPartitioningToNewOne ()
int writePartitionedTopology (std::string &name)
std::multimap< MElement *, short > & getGhostCells ()
void addGhostCells (MElement *elm, short partition)
void checkMeshCoherence (double tolerance)
int removeDuplicateMeshVertices (double tolerance, const std::vector< GEntity * > &entities=std::vector< GEntity * >())
int removeDuplicateMeshElements (const std::vector< GEntity * > &entities=std::vector< GEntity * >())
void createGeometryOfDiscreteEntities (const std::vector< std::pair< int, int > > &dimTags=std::vector< std::pair< int, int > >())
void makeDiscreteRegionsSimplyConnected ()
void makeDiscreteFacesSimplyConnected ()
void createTopologyFromMesh ()
void alignPeriodicBoundaries ()
int mesh (int dimension)
int adaptMesh ()
int adaptMesh (std::vector< int > technique, std::vector< simpleFunction< double > * > f, std::vector< std::vector< double > > parameters, int niter, bool meshAll=false)
bool setAllVolumesPositive ()
void setAllVolumesPositiveTopology ()
int setOrderN (int order, int linear, int incomplete, int onlyVisible)
int refineMesh (int linear, bool splitIntoQuads=false, bool splitIntoHexas=false, bool barycentric=false)
int optimizeMesh (const std::string &how, bool force=false, int niter=1)
int recombineMesh ()
bool fillVertexArrays ()
void classifySurfaces (double angleThreshold, bool includeBoundary, bool forReparametrization, double curveAngleThreshold)
GModel * buildCutGModel (gLevelset *ls, bool cutElem=true, bool saveTri=false)
void storeChain (int dim, std::map< int, std::vector< MElement * > > &entityMap, std::map< int, std::map< int, std::string > > &physicalMap)
void addHomologyRequest (const std::string &type, const std::vector< int > &domain, const std::vector< int > &subdomain, const std::vector< int > &dim)
void clearHomologyRequests ()
void computeHomology (std::vector< std::pair< int, int > > &newPhysicals)
void computeSizeField ()
std::map< MVertex *, std::pair< SVector3, SVector3 > > & getCurvatures ()
bool addAutomaticExtrusionConstraints (const std::vector< int > &numElements, const std::vector< double > &heights, const bool recombine, const std::vector< int > &regionTag)
std::map< std::string, std::vector< std::string > > & getAttributes ()
void load (const std::string &fileName)
void save (const std::string &fileName)
int writeGEO (const std::string &name, bool printLabels=true, bool onlyPhysicals=false)
int exportDiscreteGEOInternals ()
int writePY (const std::string &name, bool printLabels=true, bool onlyPhysicals=false)
int readOCCBREP (const std::string &name)
int readOCCSTEP (const std::string &name)
int readOCCIGES (const std::string &name)
int writeOCCSTEP (const std::string &name)
int writeOCCBREP (const std::string &name)
int importOCCShape (const void *shape)
GVertex * getVertexForOCCShape (const void *shape)
GEdge * getEdgeForOCCShape (const void *shape)
GFace * getFaceForOCCShape (const void *shape)
GRegion * getRegionForOCCShape (const void *shape)
int readACISSAT (const std::string &name)
int readParasolidXMT (const std::string &name)
int writeParasolidXMT (const std::string &name)
int readParasolidSTEP (const std::string &name)
int writeParasolidSTEP (const std::string &name)
int readMSH (const std::string &name)
int writeMSH (const std::string &name, double version=2.2, bool binary=false, bool saveAll=false, bool saveParametric=false, double scalingFactor=1.0, int elementStartNum=0, int saveSinglePartition=0, bool append=false)
int writePartitionedMSH (const std::string &baseName, double version=2.2, bool binary=false, bool saveAll=false, bool saveParametric=false, double scalingFactor=1.0)
int writeIR3 (const std::string &name, int elementTagType, bool saveAll, double scalingFactor)
int writePOS (const std::string &name, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, bool saveAll=false, double scalingFactor=1.0)
int readSTL (const std::string &name, double tolerance=1.e-3)
int writeSTL (const std::string &name, bool binary=false, bool saveAll=false, double scalingFactor=1.0, int oneSolidPerSurface=0)
int writeX3D (const std::string &name, bool saveAll=false, double scalingFactor=1.0, int x3dsurfaces=1, int x3dedges=0, int x3dvertices=0, int x3dvolumes=0, int x3dcolorize=0)
int readPLY (const std::string &name)
int readPLY2 (const std::string &name)
int writePLY2 (const std::string &name)
int readVRML (const std::string &name)
int writeVRML (const std::string &name, bool saveAll=false, double scalingFactor=1.0)
int readUNV (const std::string &name, bool readGroupsOfElements=true)
int writeUNV (const std::string &name, bool saveAll=false, int saveGroupsOfElements=0, int saveGroupsOfNodes=0, double scalingFactor=1.0)
int readMESH (const std::string &name)
int writeMESH (const std::string &name, int elementTagType=1, bool saveAll=false, double scalingFactor=1.0)
int readOFF (const std::string &name)
int writeOFF (const std::string &name, bool saveAll=false, double scalingFactor=1.0)
int readBDF (const std::string &name)
int writeBDF (const std::string &name, int format=0, int elementTagType=1, bool saveAll=false, double scalingFactor=1.0)
int readACTRAN (const std::string &name)
int readSAMCEF (const std::string &name)
int readP3D (const std::string &name)
int writeP3D (const std::string &name, bool saveAll=false, double scalingFactor=1.0)
int readCGNS (const std::string &name, std::vector< std::vector< MVertex * > > &vertPerZone, std::vector< std::vector< MElement * > > &eltPerZone)
int writeCGNS (const std::string &name, bool saveAll=false, double scalingFactor=1.0, bool structured=false)
int readMED (const std::string &name, int meshIndex)
int writeMED (const std::string &name, bool saveAll=false, double scalingFactor=1.0)
int readVTK (const std::string &name, bool bigEndian=false)
int writeVTK (const std::string &name, bool binary=false, bool saveAll=false, double scalingFactor=1.0, bool bigEndian=false)
int writeMATLAB (const std::string &name, bool binary=false, bool saveAll=false, double scalingFactor=1.0, int filetype=1)
int writeTOCHNOG (const std::string &name, bool saveAll=false, int saveGroupsOfNodes=0, double scalingFactor=1.0)
int readDIFF (const std::string &name)
int writeDIFF (const std::string &name, bool binary=false, bool saveAll=false, double scalingFactor=1.0)
int writeINP (const std::string &name, bool saveAll=false, int saveGroupsOfElements=0, int saveGroupsOfNodes=0, double scalingFactor=1.0)
int writeKEY (const std::string &name, int saveAll=0, int saveGroupsOfNodes=0, double scalingFactor=1.0)
int writeRAD (const std::string &name, int saveAll=0, int saveGroupsOfNodes=0, double scalingFactor=1.0)
int writeCELUM (const std::string &name, bool saveAll=false, double scalingFactor=1.0)
int readGEOM (const std::string &name)
int writeMAIL (const std::string &name, bool saveAll, double scalingFactor)
int writeSU2 (const std::string &name, bool saveAll, double scalingFactor)
int writeNEU (const std::string &name, bool saveAll, double scalingFactor)
Static Public Member Functions
static GModel * current (int index=-1)
static int setCurrent (GModel *m)
static GModel * findByName (const std::string &name, const std::string &fileName="")
static int readGEO (const std::string &name)
static int readMED (const std::string &name)
Public Attributes
smooth_normals * normals
std::function< double(int, int, double, double, double, double)> lcCallback
Static Public Attributes
static std::vector< GModel * > list
Protected Member Functions
void _storeElementsInEntities (std::map< int, std::vector< MElement * > > &map)
void _storeParentsInSubElements (std::map< int, std::vector< MElement * > > &map)
void _associateEntityWithMeshVertices ()
void _storeVerticesInEntities (std::map< int, MVertex * > &vertices)
void _storeVerticesInEntities (std::vector< MVertex * > &vertices)
void _storePhysicalTagsInEntities (int dim, std::map< int, std::map< int, std::string > > &map)
Protected Attributes
std::string _name
std::string _fileName
std::set< std::string > _fileNames
char _visible
std::vector< MVertex * > _vertexVectorCache
std::map< int, MVertex * > _vertexMapCache
std::vector< std::pair< MElement *, int > > _elementVectorCache
std::map< int, std::pair< MElement *, int > > _elementMapCache
std::map< int, int > _elementIndexCache
std::multimap< MElement *, short > _ghostCells
MElementOctree * _elementOctree
std::map< MVertex *, std::pair< SVector3, SVector3 > > _curvatures
GEO_Internals * _geo_internals
OCC_Internals * _occ_internals
ACIS_Internals * _acis_internals
Parasolid_Internals * _parasolid_internals
FieldManager * _fields
GEntity * _currentMeshEntity
std::vector< GEntity * > _lastMeshEntityError
std::vector< MVertex * > _lastMeshVertexError
std::set< GRegion *, GEntityPtrLessThan > regions
std::set< GFace *, GEntityPtrLessThan > faces
std::set< GEdge *, GEntityPtrLessThan > edges
std::set< GVertex *, GEntityPtrLessThan > vertices
std::map< std::pair< int, int >, std::string > _physicalNames
std::map< std::pair< int, int >, std::string > _elementaryNames
std::size_t _numPartitions
std::map< std::string, std::vector< std::string > > _attributes
Static Protected Attributes
static int _current = -1
Private Member Functions
int _readMSH2 (const std::string &name)
int _writeMSH2 (const std::string &name, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor, int elementStartNum, int saveSinglePartition, bool append, bool renumberVertices)
int _writePartitionedMSH2 (const std::string &baseName, bool binary, bool saveAll, bool saveParametric, double scalingFactor)
int _readMSH3 (const std::string &name)
int _writeMSH3 (const std::string &name, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor, int elementStartNum, int saveSinglePartition, bool append)
int _writePartitionedMSH3 (const std::string &baseName, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor)
int _readMSH4 (const std::string &name)
int _writeMSH4 (const std::string &name, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor, bool append, int partitionToSave=0, std::map< GEntity *, SBoundingBox3d > *entityBounds=nullptr)
int _writePartitionedMSH4 (const std::string &baseName, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor)
int _writeX3dFile (FILE *fp, bool saveAll, double scalingFactor, int x3dsurfaces, int x3dedges, int x3dvertices, int x3dcolorize, std::vector< GFace * > &customFaces)
Private Attributes
std::multimap< std::pair< const std::vector< int >, const std::vector< int > >, std::pair< const std::string, const std::vector< int > > > _homologyRequests
std::set< GRegion *, GEntityPtrLessThan > _chainRegions
std::set< GFace *, GEntityPtrLessThan > _chainFaces
std::set< GEdge *, GEntityPtrLessThan > _chainEdges
std::set< GVertex *, GEntityPtrLessThan > _chainVertices
hashmapMEdge _mapEdgeNum
hashmapMFace _mapFaceNum
std::size_t _maxVertexNum
std::size_t _maxElementNum
std::size_t _checkPointedMaxVertexNum
std::size_t _checkPointedMaxElementNum
Detailed Description
Definition at line 44 of file GModel.h.
Member Typedef Documentation
const_eiter
typedef std::set<GEdge *, GEntityPtrLessThan>::const_iterator GModel::const_eiter
Definition at line 190 of file GModel.h.
const_fiter
typedef std::set<GFace *, GEntityPtrLessThan>::const_iterator GModel::const_fiter
Definition at line 189 of file GModel.h.
const_riter
typedef std::set<GRegion *, GEntityPtrLessThan>::const_iterator GModel::const_riter
Definition at line 188 of file GModel.h.
const_viter
typedef std::set<GVertex *, GEntityPtrLessThan>::const_iterator GModel::const_viter
Definition at line 191 of file GModel.h.
eiter
typedef std::set<GEdge *, GEntityPtrLessThan>::iterator GModel::eiter
Definition at line 185 of file GModel.h.
fiter
typedef std::set<GFace *, GEntityPtrLessThan>::iterator GModel::fiter
Definition at line 184 of file GModel.h.
piter
typedef std::map<std::pair<int, int>, std::string>::iterator GModel::piter
Definition at line 194 of file GModel.h.
riter
typedef std::set<GRegion *, GEntityPtrLessThan>::iterator GModel::riter
Definition at line 183 of file GModel.h.
viter
typedef std::set<GVertex *, GEntityPtrLessThan>::iterator GModel::viter
Definition at line 186 of file GModel.h.
Constructor & Destructor Documentation
GModel()
GModel::GModel (const std::string & name = "")
Definition at line 72 of file GModel.cpp.
Referenced by current().
~GModel()
GModel::~GModel () virtual
Definition at line 99 of file GModel.cpp.
Member Function Documentation
_associateEntityWithMeshVertices()
void GModel::_associateEntityWithMeshVertices () protected
Definition at line 2470 of file GModel.cpp.
Referenced by _readMSH2(), _readMSH3(), buildCutGModel(), pruneMeshVertexAssociations(), readACTRAN(), readBDF(), readDIFF(), readGEOM(), readMESH(), readOFF(), readPLY(), readPLY2(), readSAMCEF(), readSTL(), readUNV(), readVRML(), readVTK(), and removeDuplicateMeshVertices().
_readMSH2()
int GModel::_readMSH2 (const std::string & name) private
Definition at line 100 of file GModelIO_MSH2.cpp.
Referenced by readMSH().
_readMSH3()
int GModel::_readMSH3 (const std::string & name) private
Definition at line 190 of file GModelIO_MSH3.cpp.
Referenced by readMSH().
_readMSH4()
int GModel::_readMSH4 (const std::string & name) private
Definition at line 1255 of file GModelIO_MSH4.cpp.
Referenced by readMSH().
_storeElementsInEntities()
void GModel::_storeElementsInEntities (std::map< int, std::vector< MElement * > > & map) protected
Definition at line 2273 of file GModel.cpp.
Referenced by _readMSH2(), _readMSH3(), buildCutGModel(), readACTRAN(), readBDF(), readDIFF(), readGEOM(), readMESH(), readPLY(), readPLY2(), readSAMCEF(), readUNV(), readVRML(), readVTK(), and storeChain().
_storeParentsInSubElements()
void GModel::_storeParentsInSubElements (std::map< int, std::vector< MElement * > > & map) protected
Definition at line 2347 of file GModel.cpp.
Referenced by _readMSH3().
_storePhysicalTagsInEntities()
void GModel::_storePhysicalTagsInEntities (int dim, std::map< int, std::map< int, std::string > > & map) protected
Definition at line 2568 of file GModel.cpp.
Referenced by _readMSH2(), buildCutGModel(), readDIFF(), readUNV(), readVTK(), and storeChain().
_storeVerticesInEntities() [1/2]
void GModel::_storeVerticesInEntities (std::map< int, MVertex * > & vertices) protected
Definition at line 2496 of file GModel.cpp.
Referenced by _readMSH2(), _readMSH3(), buildCutGModel(), pruneMeshVertexAssociations(), readACTRAN(), readBDF(), readDIFF(), readGEOM(), readMESH(), readOFF(), readPLY(), readPLY2(), readSAMCEF(), readSTL(), readUNV(), readVRML(), readVTK(), and removeDuplicateMeshVertices().
_storeVerticesInEntities() [2/2]
void GModel::_storeVerticesInEntities (std::vector< MVertex * > & vertices) protected
Definition at line 2511 of file GModel.cpp.
_writeMSH2()
int GModel::_writeMSH2 (const std::string & name, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor, int elementStartNum, int saveSinglePartition, bool append, bool renumberVertices) private
Definition at line 883 of file GModelIO_MSH2.cpp.
Referenced by _writePartitionedMSH2(), and writeMSH().
_writeMSH3()
int GModel::_writeMSH3 (const std::string & name, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor, int elementStartNum, int saveSinglePartition, bool append) private
Definition at line 725 of file GModelIO_MSH3.cpp.
Referenced by _writePartitionedMSH3(), and writeMSH().
_writeMSH4()
int GModel::_writeMSH4 (const std::string & name, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor, bool append, int partitionToSave = 0, std::map< GEntity *, SBoundingBox3d > * entityBounds = nullptr) private
Definition at line 2796 of file GModelIO_MSH4.cpp.
Referenced by _writePartitionedMSH4(), and writeMSH().
_writePartitionedMSH2()
int GModel::_writePartitionedMSH2 (const std::string & baseName, bool binary, bool saveAll, bool saveParametric, double scalingFactor) private
Definition at line 1126 of file GModelIO_MSH2.cpp.
Referenced by writePartitionedMSH().
_writePartitionedMSH3()
int GModel::_writePartitionedMSH3 (const std::string & baseName, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor) private
Definition at line 841 of file GModelIO_MSH3.cpp.
Referenced by writePartitionedMSH().
_writePartitionedMSH4()
int GModel::_writePartitionedMSH4 (const std::string & baseName, double version, bool binary, bool saveAll, bool saveParametric, double scalingFactor) private
Definition at line 2906 of file GModelIO_MSH4.cpp.
Referenced by writePartitionedMSH().
_writeX3dFile()
int GModel::_writeX3dFile (FILE * fp, bool saveAll, double scalingFactor, int x3dsurfaces, int x3dedges, int x3dvertices, int x3dcolorize, std::vector< GFace * > & customFaces) private
Definition at line 315 of file GModelIO_X3D.cpp.
Referenced by writeX3D().
adaptMesh() [1/2]
int GModel::adaptMesh ()
Definition at line 1215 of file GModel.cpp.
Referenced by GmshBatch().
adaptMesh() [2/2]
int GModel::adaptMesh (std::vector< int > technique, std::vector< simpleFunction< double > * > f, std::vector< std::vector< double > > parameters, int niter, bool meshAll = false)
Definition at line 1231 of file GModel.cpp.
add() [1/4]
bool GModel::add (GEdge * e) inline
Definition at line 396 of file GModel.h.
add() [2/4]
bool GModel::add (GFace * f) inline
Definition at line 395 of file GModel.h.
add() [3/4]
bool GModel::add (GRegion * r) inline
Definition at line 394 of file GModel.h.
Referenced by _storeElementsInEntities(), classifyFaces(), createTopologyFromMesh1D(), createTopologyFromMesh2D(), createTopologyFromMesh3D(), ensureManifoldFace(), ensureSimplyConnectedEdge(), GMSH_CrackPlugin::execute(), GMSH_MeshSubEntitiesPlugin::execute(), getBoundaryFromMesh(), makeDiscreteFacesSimplyConnected(), makeDiscreteRegionsSimplyConnected(), readMSH4Entities(), readMSH4Nodes(), readMSHEntities(), readOFF(), readP3D(), readSTL(), and GEO_Internals::synchronize().
add() [4/4]
bool GModel::add (GVertex * v) inline
Definition at line 397 of file GModel.h.
addAutomaticExtrusionConstraints()
bool GModel::addAutomaticExtrusionConstraints (const std::vector< int > & numElements, const std::vector< double > & heights, const bool recombine, const std::vector< int > & regionTag)
Definition at line 322 of file GModelAutoExtrude.cpp.
Referenced by OpenProject().
addGhostCells()
void GModel::addGhostCells (MElement * elm, short partition) inline
Definition at line 619 of file GModel.h.
Referenced by ghostEdge::addElement(), ghostFace::addElement(), ghostRegion::addElement(), ghostRegion::addHexahedron(), ghostEdge::addLine(), ghostFace::addPolygon(), ghostRegion::addPolyhedron(), ghostRegion::addPrism(), ghostRegion::addPyramid(), ghostFace::addQuadrangle(), ghostRegion::addTetrahedron(), ghostFace::addTriangle(), and ghostRegion::addTrihedron().
addHomologyRequest()
void GModel::addHomologyRequest (const std::string & type, const std::vector< int > & domain, const std::vector< int > & subdomain, const std::vector< int > & dim)
Definition at line 3480 of file GModel.cpp.
addLastMeshEntityError()
void GModel::addLastMeshEntityError (GEntity * e) inline
Definition at line 585 of file GModel.h.
addLastMeshVertexError()
void GModel::addLastMeshVertexError (MVertex * v) inline
Definition at line 591 of file GModel.h.
addMEdge()
std::size_t GModel::addMEdge (MEdge & edge, std::size_t num = 0)
Definition at line 1561 of file GModel.cpp.
addMFace()
std::size_t GModel::addMFace (MFace & face, std::size_t num = 0)
Definition at line 1583 of file GModel.cpp.
addMVertexToVertexCache()
void GModel::addMVertexToVertexCache (MVertex * v)
Definition at line 1970 of file GModel.cpp.
addPhysicalGroup()
void GModel::addPhysicalGroup (int dim, int tag, const std::vector< int > & tags)
Definition at line 881 of file GModel.cpp.
alignPeriodicBoundaries()
void GModel::alignPeriodicBoundaries ()
Definition at line 2828 of file GModel.cpp.
Referenced by _readMSH2().
bounds()
SBoundingBox3d GModel::bounds (bool aroundVisible = false)
Definition at line 1043 of file GModel.cpp.
Referenced by _writePartitionedMSH4(), checkMeshCoherence(), stepData< Real >::computeBoundingBox(), GMSH_MeshVolumePlugin::execute(), GMSH_BubblesPlugin::execute(), MElementOctree::MElementOctree(), MergePostProcessingFile(), opt_general_xmax(), opt_general_xmin(), opt_general_ymax(), opt_general_ymin(), opt_general_zmax(), opt_general_zmin(), removeDuplicateMeshVertices(), GMSH_SimplePartitionPlugin::run(), SetBoundingBox(), and OctreeField::update().
buildCutGModel()
GModel * GModel::buildCutGModel (gLevelset * ls, bool cutElem = true, bool saveTri = false)
Definition at line 3376 of file GModel.cpp.
Referenced by thermicSolver::cutMesh(), elasticitySolver::cutMesh(), elasticitySolver::readInputFile(), and GMSH_CutMeshPlugin::run().
changeEntityTag()
bool GModel::changeEntityTag (int dim, int tag, int newTag)
Definition at line 367 of file GModel.cpp.
checkMeshCoherence()
void GModel::checkMeshCoherence (double tolerance)
Definition at line 2595 of file GModel.cpp.
Referenced by GmshBatch().
checkPointMaxNumbers()
void GModel::checkPointMaxNumbers () inline
Definition at line 264 of file GModel.h.
classifySurfaces()
void GModel::classifySurfaces (double angleThreshold, bool includeBoundary, bool forReparametrization, double curveAngleThreshold)
Definition at line 3472 of file GModel.cpp.
Referenced by GmshBatch().
clearHomologyRequests()
void GModel::clearHomologyRequests ()
Definition at line 3491 of file GModel.cpp.
clearLastMeshEntityError()
void GModel::clearLastMeshEntityError () inline
Definition at line 584 of file GModel.h.
Referenced by GenerateMesh().
clearLastMeshVertexError()
void GModel::clearLastMeshVertexError () inline
Definition at line 590 of file GModel.h.
Referenced by GenerateMesh().
computeHomology()
void GModel::computeHomology (std::vector< std::pair< int, int > > & newPhysicals)
Definition at line 3496 of file GModel.cpp.
Referenced by mesh().
computeSizeField()
void GModel::computeSizeField ()
Definition at line 3590 of file GModel.cpp.
Referenced by GmshBatch().
convertOldPartitioningToNewOne()
int GModel::convertOldPartitioningToNewOne ()
Definition at line 2236 of file GModel.cpp.
Referenced by _readMSH2(), and _readMSH3().
createACISInternals()
void GModel::createACISInternals ()
Definition at line 3604 of file GModel.cpp.
createGEOInternals()
void GModel::createGEOInternals ()
Definition at line 1670 of file GModelIO_GEO.cpp.
Referenced by GModel().
createGeometryOfDiscreteEntities()
void GModel::createGeometryOfDiscreteEntities (const std::vector< std::pair< int, int > > & dimTags = std::vector<std::pair<int, int> >())
Definition at line 2370 of file GModel.cpp.
Referenced by GmshBatch().
createOCCInternals()
void GModel::createOCCInternals ()
Definition at line 5874 of file GModelIO_OCC.cpp.
Referenced by _createOcc().
createParasolidInternals()
void GModel::createParasolidInternals ()
Definition at line 3619 of file GModel.cpp.
createTopologyFromMesh()
void GModel::createTopologyFromMesh ()
Definition at line 663 of file GModelCreateTopologyFromMesh.cpp.
Referenced by _readMSH2().
current()
GModel * GModel::current (int index = -1) static
Definition at line 136 of file GModel.cpp.
Referenced by _addElements(), _addModelData(), _checkInit(), _create_splitted_curve(), _createOcc(), _getEntities(), _getEntitiesForElementTypes(), addEmbedded(), addPeriodicEdge(), addPeriodicFace(), groupOfElements::addPhysical(), allEdgesLinked(), allFacesLinked(), ApplicationOnShapes(), BGM_MeshSizeWithoutScaling(), ClearProject(), BoundaryLayerField::computeFor1dMesh(), CreateCurve(), createEdgeLinks(), CreateEdgeLoop(), createFaceLinks(), CreateOutputFile(), CreatePhysicalGroup(), CreateReversedCurve(), CreateSurface(), CreateSurfaceLoop(), CreateVertex(), CreateVolume(), DeleteCurve(), MVertex::deleteLast(), DeletePhysicalLine(), DeletePhysicalPoint(), DeletePhysicalSurface(), DeletePhysicalVolume(), DeletePoint(), DeleteSurface(), DeleteVolume(), DoSystemUncompress(), drawContext::draw3d(), drawArrays(), drawContext::drawBackgroundImage(), drawContext::drawImage(), DuplicateCurve(), DuplicateSurface(), DuplicateVertex(), DuplicateVolume(), GMSH_NewViewPlugin::elementData(), MathEvalExpression::evaluate(), MathEvalExpressionAniso::evaluate(), GMSH_CrackPlugin::execute(), GMSH_GaussPointsPlugin::execute(), GMSH_MeshSubEntitiesPlugin::execute(), GMSH_SkinPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_CurvedBndDistPlugin::execute(), GMSH_MeshSizeFieldViewPlugin::execute(), GMSH_InvisiblePlugin::execute(), GMSH_DiscretizationErrorPlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_BubblesPlugin::execute(), GMSH_NewViewPlugin::execute(), GMSH_DistancePlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_ShowNeighborElementsPlugin::execute(), ExtrudeCurve(), ExtrudePoint(), ExtrudeSurface(), FindCurve(), FindEdgeLoop(), FindPhysicalGroup(), FindPoint(), FindSurface(), FindSurfaceLoop(), FindVolume(), MElement::forceNum(), MVertex::forceNum(), getAllElementaryTags(), getAllPhysicalTags(), getBoundingBox(), GetDefaultFileName(), getElementaryTagsForPhysicalGroups(), getElementaryTagsInBoundingBox(), GetMeshOption(), GetOptions(), getParentTags(), GetStatistics(), GFaceDelaunayRefinement(), GFaceDelaunayRefinementOldMesher(), GFaceInitialMesh(), gLevelsetYarn::gLevelsetYarn(), GmshBatch(), GmshFLTK(), PViewDataGModel::importLists(), Msg::ImportPhysicalGroupsInOnelab(), IntersectCurvesWithSurface(), load(), MaxNumCurve(), MaxNumPoint(), MaxNumSurface(), MElement::MElement(), MergeFile(), MergePostProcessingFile(), MVertex::MVertex(), needPolygonOffset(), NEWCURVE(), NEWCURVELOOP(), NEWFIELD(), NEWPHYSICAL(), NEWPOINT(), NEWREG(), NEWSURFACE(), NEWSURFACELOOP(), NEWVOLUME(), GMSH_NewViewPlugin::nodeData(), OpenProject(), drawGVertex::operator()(), drawGEdge::operator()(), BoundaryLayerField::operator()(), drawGFace::operator()(), LonLatField::operator()(), drawMeshGVertex::operator()(), drawGRegion::operator()(), drawMeshGEdge::operator()(), drawMeshGFace::operator()(), drawMeshGRegion::operator()(), ThresholdField::operator()(), GradientField::operator()(), CurvatureField::operator()(), MaxEigenHessianField::operator()(), LaplacianField::operator()(), MeanField::operator()(), ParametricField::operator()(), MinAnisoField::operator()(), IntersectAnisoField::operator()(), MinField::operator()(), MaxField::operator()(), RestrictField::operator()(), opt_general_filename(), opt_general_xmax(), opt_general_xmin(), opt_general_ymax(), opt_general_ymin(), opt_general_zmax(), opt_general_zmin(), orientAndSortEdges(), ParseString(), PolyMesh2GFace(), PrintOptionsDoc(), Field::putOnNewView(), QuadqsContextUpdater::QuadqsContextUpdater(), readGEO(), PView::readMSH(), PViewDataGModel::readMSH(), readMSH4Nodes(), PViewDataGModel::readPCH(), RecognizeLineLoop(), RecognizeSurfaceLoop(), ExtendField::recomputeCurves(), ExtendField::recomputeSurfaces(), recurFindLinkedEdges(), recurFindLinkedFaces(), RemoveDegenerateCurves(), RemoveDegenerateSurfaces(), RemoveDegenerateVolumes(), removeEmbedded(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicatePointsNew(), ReplaceDuplicateSurfaces(), GMSH_CutMeshPlugin::run(), GMSH_SimplePartitionPlugin::run(), GMSH_SpanningTreePlugin::run(), save(), scriptAddBox(), scriptAddCircle(), scriptAddCircleArc(), scriptAddCommand(), scriptAddCone(), scriptAddCurve(), scriptAddCurveLoop(), scriptAddCylinder(), scriptAddDisk(), scriptAddEllipse(), scriptAddEllipseArc(), scriptAddPipe(), scriptAddPoint(), scriptAddRectangle(), scriptAddRemovePhysicalGroup(), scriptAddSphere(), scriptAddSurface(), scriptAddSurfaceLoop(), scriptAddTorus(), scriptAddVolume(), scriptAddWedge(), drawContext::select(), SetBoundingBox(), setColor(), SetSurfaceGeneratrices(), BoundaryLayerField::setupFor1d(), BoundaryLayerField::setupFor2d(), setVisibility(), SetVolumeSurfaces(), SplitCurve(), jacobianBasedQuality::testAllMeasuresAllElements(), OctreeField::update(), DistanceField::update(), and writeNEU().
decrementMaxVertexNumber()
void GModel::decrementMaxVertexNumber () inline
Definition at line 258 of file GModel.h.
Referenced by MVertex::deleteLast().
deleteACISInternals()
void GModel::deleteACISInternals ()
Definition at line 3606 of file GModel.cpp.
Referenced by ~GModel().
deleteGEOInternals()
void GModel::deleteGEOInternals ()
Definition at line 1672 of file GModelIO_GEO.cpp.
Referenced by ~GModel().
deleteMesh() [1/2]
void GModel::deleteMesh ()
Definition at line 236 of file GModel.cpp.
Referenced by deleteMesh(), and GenerateMesh().
deleteMesh() [2/2]
void GModel::deleteMesh (const std::vector< GEntity * > & entities)
Definition at line 248 of file GModel.cpp.
deleteOCCInternals()
void GModel::deleteOCCInternals ()
Definition at line 5880 of file GModelIO_OCC.cpp.
Referenced by ~GModel().
deleteParasolidInternals()
void GModel::deleteParasolidInternals ()
Definition at line 3621 of file GModel.cpp.
Referenced by ~GModel().
deleteVertexArrays()
void GModel::deleteVertexArrays ()
Definition at line 299 of file GModel.cpp.
Referenced by classifyFaces().
destroy()
void GModel::destroy (bool keepName = false)
Definition at line 168 of file GModel.cpp.
Referenced by OpenProject(), and ~GModel().
destroyMeshCaches()
void GModel::destroyMeshCaches ()
Definition at line 214 of file GModel.cpp.
Referenced by BarycentricRefineMesh(), classifyFaces(), GVertex::deleteMesh(), GRegion::deleteMesh(), GEdge::deleteMesh(), GFace::deleteMesh(), deleteMesh(), destroy(), removeDuplicateMeshVertices(), removeInvisibleElements(), renumberMeshElements(), renumberMeshVertices(), reverseInvisibleElements(), SetOrder1(), and SetOrderN().
empty()
bool GModel::empty () const
Definition at line 311 of file GModel.cpp.
Referenced by MergeFile(), PrintMesh2dStatistics(), PView::readMSH(), readSTL(), and writeMATLAB().
exportDiscreteGEOInternals()
int GModel::exportDiscreteGEOInternals ()
Definition at line 1910 of file GModelIO_GEO.cpp.
Referenced by classifyFaces().
fillVertexArrays()
bool GModel::fillVertexArrays ()
Definition at line 452 of file GModelVertexArrays.cpp.
Referenced by drawContext::drawMesh().
findByName()
GModel * GModel::findByName (const std::string & name, const std::string & fileName = "") static
Definition at line 158 of file GModel.cpp.
Referenced by _addModelData().
firstEdge() [1/2]
eiter GModel::firstEdge () inline
Definition at line 356 of file GModel.h.
Referenced by _associateEntityWithMeshVertices(), _getOneElementOfGivenType(), _writeMSH2(), _writeMSH3(), _writeX3dFile(), adaptMesh(), alignPeriodicBoundaries(), buildEdgeSearchStructure(), classifyFaces(), createEdgeLinks(), createGeometryOfDiscreteEntities(), createTopologyFromMesh1D(), createTopologyFromMesh2D(), deleteMesh(), deleteVertexArrays(), destroy(), drawContext::drawGeom(), drawContext::drawMesh(), GMSH_BubblesPlugin::execute(), exportDiscreteGEOInternals(), fillVertexArrays(), FixPeriodicMesh(), GeomMeshMatcher::forceTomatch(), GenerateMesh(), getEntitiesToSave(), getGEdge(), getGVertex(), getMeshStatus(), getNodeCopies(), getNumElementsMSH(), PViewDataGModel::getNumLines(), getNumMeshElements(), GetStatistics(), GFaceInitialMesh(), GeomMeshMatcher::matchEdges(), Mesh1D(), Mesh2DWithBoundaryLayers(), RefineMesh(), remove(), removeInvisibleElements(), reverseInvisibleElements(), SetOrder1(), SetOrderN(), GEO_Internals::synchronize(), jacobianBasedQuality::testAllMeasuresAllElements(), topoExists(), writeGEO(), writeINP(), writeKEY(), writeMESH(), writeMSH4Entities(), writeMSH4Parametrizations(), writeMSHEntities(), writePY(), writeRAD(), writeTOCHNOG(), and writeVRML().
firstEdge() [2/2]
const_eiter GModel::firstEdge () const inline
Definition at line 364 of file GModel.h.
firstElementaryName()
piter GModel::firstElementaryName () inline
Definition at line 460 of file GModel.h.
firstFace() [1/2]
fiter GModel::firstFace () inline
Definition at line 355 of file GModel.h.
Referenced by _associateEntityWithMeshVertices(), _getOneElementOfGivenType(), _isModelOkForTopologicalOpti(), _writeMSH2(), _writeMSH3(), _writeX3dFile(), adaptMesh(), alignPeriodicBoundaries(), BarycentricRefineMesh(), checkHighOrderTriangles(), classifyFaces(), completeTheSetOfFaces(), computeDiscreteCurvatures(), computeEdgeCut(), computeLevelset(), computeNonManifoldEdges(), createFaceLinks(), createGeometryOfDiscreteEntities(), createSizeFieldFromExistingMesh(), createTopologyFromMesh2D(), createTopologyFromMesh3D(), deleteMesh(), deleteVertexArrays(), destroy(), drawContext::drawGeom(), drawContext::drawMesh(), ensureManifoldFaces(), GMSH_CurvedBndDistPlugin::execute(), GMSH_BubblesPlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_ShowNeighborElementsPlugin::execute(), exportDiscreteGEOInternals(), fillVertexArrays(), FixErasedExtrScaleFlags(), FixPeriodicMesh(), GeomMeshMatcher::forceTomatch(), GenerateMesh(), getEntitiesToSave(), getFacesOfTheModel(), getGFace(), getMeshStatus(), getNumElementsMSH(), getNumMeshElements(), PViewDataGModel::getNumPolygons(), PViewDataGModel::getNumQuadrangles(), PViewDataGModel::getNumTriangles(), GetStatistics(), insertVerticesInRegion(), makeDiscreteFacesSimplyConnected(), GeomMeshMatcher::matchFaces(), Mesh2D(), Mesh2DWithBoundaryLayers(), meshMetric::meshMetric(), OptimizeMesh(), PrintMesh2dStatistics(), RecombineMesh(), RefineMesh(), remove(), removeInvisibleElements(), reverseInvisibleElements(), SetOrder1(), SetOrderN(), GEO_Internals::synchronize(), jacobianBasedQuality::testAllMeasuresAllElements(), topoExists(), writeCELUM(), writeGEO(), writeINP(), writeIR3(), writeKEY(), writeMAIL(), writeMESH(), writeMSH4Entities(), writeMSH4Parametrizations(), writeMSHEntities(), writeNEU(), writeP3D(), writePLY2(), writePY(), writeRAD(), writeSTL(), writeSU2(), writeTOCHNOG(), and writeVRML().
firstFace() [2/2]
const_fiter GModel::firstFace () const inline
Definition at line 363 of file GModel.h.
firstMEdge()
hashmapMEdge::const_iterator GModel::firstMEdge () inline
Definition at line 285 of file GModel.h.
firstMFace()
hashmapMFace::const_iterator GModel::firstMFace () inline
Definition at line 287 of file GModel.h.
firstPhysicalName()
piter GModel::firstPhysicalName () inline
Definition at line 458 of file GModel.h.
Referenced by _writeMSH2(), _writeMSH3(), _writeMSH4(), getInnerPhysicalNamesIterators(), and getPhysicalNumber().
firstRegion() [1/2]
riter GModel::firstRegion () inline
Definition at line 354 of file GModel.h.
Referenced by _associateEntityWithMeshVertices(), _getOneElementOfGivenType(), _writeMSH2(), _writeMSH3(), AdaptMesh(), adaptMesh(), BarycentricRefineMesh(), buildFaceSearchStructure(), splitQuadRecovery::buildPyramids(), checkHighOrderTetrahedron(), classifyFaces(), createGeometryOfDiscreteEntities(), createTopologyFromMesh3D(), deleteMesh(), deleteVertexArrays(), destroy(), drawContext::drawGeom(), drawContext::drawMesh(), GMSH_ShowNeighborElementsPlugin::execute(), exportDiscreteGEOInternals(), fillVertexArrays(), FixErasedExtrScaleFlags(), GenerateMesh(), getEntitiesToSave(), getMeshStatus(), getNumElementsMSH(), PViewDataGModel::getNumHexahedra(), getNumMeshElements(), PViewDataGModel::getNumPolyhedra(), PViewDataGModel::getNumPrisms(), PViewDataGModel::getNumPyramids(), PViewDataGModel::getNumTetrahedra(), PViewDataGModel::getNumTrihedra(), getRegionFromBoundingFaces(), GetStatistics(), insertVerticesInRegion(), makeDiscreteRegionsSimplyConnected(), MakeMeshConformal(), Mesh3D(), meshMetric::meshMetric(), OptimizeMesh(), RefineMesh(), remove(), removeInvisibleElements(), reverseInvisibleElements(), SetOrder1(), SetOrderN(), SubdivideExtrudedMesh(), GEO_Internals::synchronize(), jacobianBasedQuality::testAllMeasuresAllElements(), topoExists(), writeGEO(), writeINP(), writeIR3(), writeKEY(), writeMESH(), writeMSH4Entities(), writeMSHEntities(), writeNEU(), writeP3D(), writePY(), writeRAD(), writeSU2(), and writeTOCHNOG().
firstRegion() [2/2]
const_riter GModel::firstRegion () const inline
Definition at line 362 of file GModel.h.
firstVertex() [1/2]
viter GModel::firstVertex () inline
Definition at line 357 of file GModel.h.
Referenced by _associateEntityWithMeshVertices(), _getOneElementOfGivenType(), _writeMSH2(), _writeMSH3(), _writeX3dFile(), classifyFaces(), createTopologyFromMesh1D(), deleteMesh(), deleteVertexArrays(), destroy(), drawContext::drawGeom(), drawContext::drawMesh(), GMSH_BubblesPlugin::execute(), exportDiscreteGEOInternals(), getEntitiesToSave(), getMeshStatus(), getNumElementsMSH(), PViewDataGModel::getNumPoints(), GetStatistics(), GeomMeshMatcher::matchVertices(), Mesh0D(), remove(), snapVertices(), GEO_Internals::synchronize(), TooManyElements(), writeGEO(), writeINP(), writeKEY(), writeMSH4Entities(), writeMSHEntities(), writePY(), writeRAD(), writeTOCHNOG(), and writeVRML().
firstVertex() [2/2]
const_viter GModel::firstVertex () const inline
Definition at line 365 of file GModel.h.
getACISInternals()
ACIS_Internals* GModel::getACISInternals () inline
Definition at line 316 of file GModel.h.
getAttributes()
std::map<std::string, std::vector<std::string> >& GModel::getAttributes () inline
Definition at line 731 of file GModel.h.
getBoundaryTags()
bool GModel::getBoundaryTags (const std::vector< std::pair< int, int > > & inDimTags, std::vector< std::pair< int, int > > & outDimTags, bool combined, bool oriented = true, bool recursive = false)
Definition at line 697 of file GModel.cpp.
getCheckPointedMaxNumbers()
void GModel::getCheckPointedMaxNumbers (std::size_t & maxv, std::size_t & maxe) const inline
Definition at line 269 of file GModel.h.
getCurrentMeshEntity()
GEntity* GModel::getCurrentMeshEntity () inline
Definition at line 581 of file GModel.h.
getCurvatures()
std::map<MVertex *, std::pair<SVector3, SVector3> >& GModel::getCurvatures () inline
Definition at line 719 of file GModel.h.
Referenced by computeDiscreteCurvatures(), and discreteFace::createGeometry().
getDim()
int GModel::getDim () const
Definition at line 989 of file GModel.cpp.
Referenced by adaptMesh(), computeHomology(), createTopologyFromMesh(), getBoundaryFromMesh(), meshMetric::meshMetric(), OptimizeMesh(), readMSH4Entities(), writeNEU(), writeSU2(), and writeTOCHNOG().
getEdgeByTag()
GEdge * GModel::getEdgeByTag (int n) const
Definition at line 336 of file GModel.cpp.
Referenced by _readMSH2(), _readMSH3(), _storeElementsInEntities(), _storePhysicalTagsInEntities(), frameSolver2d::addBeamsOrBars(), addEmbedded(), addPeriodicEdge(), allEdgesLinked(), changeEntityTag(), createGeometryOfDiscreteEntities(), ExtrudeCurve(), FixErasedExtrScaleFlags(), getBoundaryTags(), getEntityByTag(), Mesh2DWithBoundaryLayers(), MeshExtrudedCurve(), MeshExtrudedSurface(), BoundaryLayerField::operator()(), orientAndSortEdges(), readMSH4Entities(), readMSH4Parametrizations(), readMSH4PeriodicNodes(), readMSHEntities(), readMSHPeriodicNodes(), ExtendField::recomputeCurves(), recurFindLinkedEdges(), remove(), gmshFace::resetNativePtr(), drawContext::select(), GFace::setBoundEdges(), GFace::setMeshMaster(), SetSurfaceGeneratrices(), BoundaryLayerField::setupFor1d(), storeChain(), GEO_Internals::synchronize(), and DistanceField::update().
getEdgeForOCCShape()
GEdge * GModel::getEdgeForOCCShape (const void * shape)
Definition at line 5966 of file GModelIO_OCC.cpp.
getEdges()
std::set<GEdge *, GEntityPtrLessThan> GModel::getEdges () const inline
Definition at line 377 of file GModel.h.
Referenced by GlobalBackgroundMesh::importGModelMeshes().
getElementaryName()
std::string GModel::getElementaryName (int dim, int tag)
Definition at line 1007 of file GModel.cpp.
Referenced by _writeX3dFile(), drawEntityLabel(), GEntity::getInfoString(), writeSTL(), and writeX3D().
getEntities()
void GModel::getEntities (std::vector< GEntity * > & entities, int dim = -1) const
Definition at line 651 of file GModel.cpp.
Referenced by _getEntities(), _getEntitiesForElementTypes(), _readMSH4(), _writeMSH2(), _writeMSH3(), _writeMSH4(), _writePartitionedMSH4(), bounds(), buildCutMesh(), checkMeshCoherence(), GMSH_NewViewPlugin::elementData(), GMSH_GaussPointsPlugin::execute(), GMSH_CrackPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_InvisiblePlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_DistancePlugin::execute(), stepData< Real >::fillEntities(), MElementOctree::find(), MElementOctree::findAll(), GeomMeshMatcher::forceTomatch(), getAllElementaryTags(), getBoundaryFromMesh(), getEntitiesInBox(), getMaxElementaryNumber(), getMaxPhysicalNumber(), getNumMeshElements(), getNumMeshParentElements(), getNumMeshVertices(), getPhysicalGroups(), indexMeshVertices(), GeomMeshMatcher::matchRegions(), MElementOctree::MElementOctree(), GMSH_NewViewPlugin::nodeData(), noPhysicalGroups(), pruneMeshVertexAssociations(), Field::putOnNewView(), readMSH4GhostElements(), readPLY(), rebuildMeshElementCache(), rebuildMeshVertexCache(), removeDuplicateMeshElements(), removeDuplicateMeshVertices(), removePhysicalGroup(), removePhysicalGroups(), renumberMeshElements(), renumberMeshVertices(), GMSH_SimplePartitionPlugin::run(), scaleMesh(), setSelection(), setVisibility(), writeBDF(), writeDIFF(), writeINP(), writeIR3(), writeKEY(), writeMAIL(), writeMATLAB(), writeMESH(), writeMSH4GhostCells(), writeMSH4PeriodicNodes(), writeNEU(), writeOFF(), writePartitionedTopology(), writePLY2(), writePOS(), writeRAD(), writeSU2(), writeTOCHNOG(), writeUNV(), writeVTK(), and writeX3D().
getEntitiesInBox()
void GModel::getEntitiesInBox (std::vector< GEntity * > & entities, const SBoundingBox3d & box, int dim = -1) const
Definition at line 672 of file GModel.cpp.
Referenced by getElementaryTagsInBoundingBox(), and setPhysicalNumToEntitiesInBox().
getEntityByTag()
GEntity * GModel::getEntityByTag (int dim, int n) const
Definition at line 356 of file GModel.cpp.
Referenced by _getEntities(), _getEntitiesForElementTypes(), addPhysicalGroup(), getBoundingBox(), getParentTags(), readMSH4BoundingEntities(), readMSH4Elements(), readMSH4Entities(), readMSH4Nodes(), setColor(), and setVisibility().
getFaceByTag()
GFace * GModel::getFaceByTag (int n) const
Definition at line 326 of file GModel.cpp.
Referenced by _readMSH2(), _readMSH3(), _storeElementsInEntities(), _storePhysicalTagsInEntities(), addEmbedded(), addPeriodicFace(), allFacesLinked(), changeEntityTag(), checkDepends(), createGeometryOfDiscreteEntities(), ExtrudeSurface(), FixErasedExtrScaleFlags(), getBoundaryTags(), getEntityByTag(), GFaceDelaunayRefinement(), GFaceDelaunayRefinementOldMesher(), GFaceInitialMesh(), Mesh2DWithBoundaryLayers(), MeshExtrudedSurface(), meshGRegionExtruded::operator()(), BoundaryLayerField::operator()(), phase1(), phase2(), phase3(), PolyMesh2GFace(), readMSH4Entities(), readMSH4Parametrizations(), readMSH4PeriodicNodes(), readMSHEntities(), readMSHPeriodicNodes(), ExtendField::recomputeSurfaces(), recurFindLinkedFaces(), remove(), removeEmbedded(), gmshRegion::resetNativePtr(), drawContext::select(), GRegion::setBoundFaces(), BoundaryLayerField::setupFor2d(), SetVolumeSurfaces(), storeChain(), GEO_Internals::synchronize(), and DistanceField::update().
getFaceForOCCShape()
GFace * GModel::getFaceForOCCShape (const void * shape)
Definition at line 5976 of file GModelIO_OCC.cpp.
getFaces()
std::set<GFace *, GEntityPtrLessThan> GModel::getFaces () const inline
Definition at line 376 of file GModel.h.
Referenced by classifyFaces(), GenerateMesh(), GlobalBackgroundMesh::importGModelMeshes(), optimize1DMeshAtAcuteCorners(), OptimizeMesh(), and transferSeamGEdgesVerticesToGFace().
getFields()
FieldManager* GModel::getFields () inline
Definition at line 325 of file GModel.h.
Referenced by _recombineIntoQuads(), adaptMesh(), addBoundaryLayerPoints(), addExtrudeNormals(), BGM_MeshMetric(), BGM_MeshSizeWithoutScaling(), computeSizeField(), MathEvalExpression::evaluate(), MathEvalExpressionAniso::evaluate(), GMSH_MeshSizeFieldViewPlugin::execute(), GmshBatch(), GmshFLTK(), Mesh0D(), Mesh1D(), Mesh2D(), Mesh3D(), F_Lc_aniso::operator()(), LonLatField::operator()(), ThresholdField::operator()(), GradientField::operator()(), CurvatureField::operator()(), MaxEigenHessianField::operator()(), LaplacianField::operator()(), MeanField::operator()(), ParametricField::operator()(), MinAnisoField::operator()(), IntersectAnisoField::operator()(), MinField::operator()(), MaxField::operator()(), RestrictField::operator()(), PrintOptionsDoc(), quadqsCleanup(), splitElementsInBoundaryLayerIfNeeded(), OctreeField::update(), and writeGEO().
getFileName()
std::string GModel::getFileName () const inline
Definition at line 333 of file GModel.h.
Referenced by opt_general_filename().
getGEOInternals()
GEO_Internals* GModel::getGEOInternals () inline
Definition at line 315 of file GModel.h.
Referenced by addEmbedded(), addPeriodicEdge(), addPeriodicFace(), CreateCurve(), CreateEdgeLoop(), CreatePhysicalGroup(), CreateSurface(), CreateSurfaceLoop(), CreateVertex(), CreateVolume(), DeleteCurve(), DeletePoint(), DeleteSurface(), DeleteVolume(), discreteEdge::discreteEdge(), discreteFace::discreteFace(), discreteRegion::discreteRegion(), discreteVertex::discreteVertex(), ExtrudeSurface(), getAllElementaryTags(), getAllPhysicalTags(), getBoundingBox(), getElementaryTagsForPhysicalGroups(), getElementaryTagsInBoundingBox(), getParentTags(), MaxNumCurve(), MaxNumPoint(), MaxNumSurface(), MergeFile(), NEWCURVE(), NEWCURVELOOP(), NEWPHYSICAL(), NEWPOINT(), NEWSURFACE(), NEWSURFACELOOP(), NEWVOLUME(), OpenProject(), readGEO(), removeEmbedded(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicateSurfaces(), scriptAddCommand(), scriptAddCurveLoop(), scriptAddPipe(), scriptAddRemovePhysicalGroup(), scriptAddSurfaceLoop(), setColor(), setVisibility(), and SplitCurve().
getGhostCells()
std::multimap<MElement *, short>& GModel::getGhostCells () inline
Definition at line 618 of file GModel.h.
Referenced by writeElementMSH().
getInnerPhysicalNamesIterators()
void GModel::getInnerPhysicalNamesIterators (std::vector< piter > & iterators)
Definition at line 929 of file GModel.cpp.
Referenced by _readMSH4().
getLastMeshEntityError()
std::vector<GEntity *> GModel::getLastMeshEntityError () inline
Definition at line 586 of file GModel.h.
getLastMeshVertexError()
std::vector<MVertex *> GModel::getLastMeshVertexError () inline
Definition at line 592 of file GModel.h.
getMaxElementaryNumber()
int GModel::getMaxElementaryNumber (int dim)
Definition at line 817 of file GModel.cpp.
Referenced by GMSH_SpanningTreePlugin::addToModel(), buildCutMesh(), classifyFaces(), createTopologyFromMesh1D(), createTopologyFromMesh2D(), createTopologyFromMesh3D(), ensureManifoldFace(), ensureSimplyConnectedEdge(), GMSH_CrackPlugin::execute(), GMSH_MeshSubEntitiesPlugin::execute(), GMSH_BubblesPlugin::execute(), getBoundaryFromMesh(), makeDiscreteFacesSimplyConnected(), makeDiscreteRegionsSimplyConnected(), readOFF(), readP3D(), readPLY(), readPLY2(), readSTL(), readUNV(), readVRML(), readVTK(), scriptAddBox(), scriptAddCircle(), scriptAddCircleArc(), scriptAddCone(), scriptAddCurve(), scriptAddCylinder(), scriptAddDisk(), scriptAddEllipse(), scriptAddEllipseArc(), scriptAddPoint(), scriptAddRectangle(), scriptAddSphere(), scriptAddSurface(), scriptAddTorus(), scriptAddVolume(), and scriptAddWedge().
getMaxElementNumber()
std::size_t GModel::getMaxElementNumber () const inline
Definition at line 223 of file GModel.h.
getMaxPhysicalNumber()
int GModel::getMaxPhysicalNumber (int dim)
Definition at line 917 of file GModel.cpp.
Referenced by GMSH_SpanningTreePlugin::addToModel(), buildCutMesh(), setPhysicalName(), writeElementsMSH(), and writeNEU().
getMaxVertexNumber()
std::size_t GModel::getMaxVertexNumber () const inline
Definition at line 222 of file GModel.h.
Referenced by MVertex::deleteLast().
getMEdge()
std::size_t GModel::getMEdge (MVertex * v0, MVertex * v1, MEdge & edge)
Definition at line 1569 of file GModel.cpp.
getMeshDim()
int GModel::getMeshDim () const
Definition at line 998 of file GModel.cpp.
Referenced by checkMeshCoherence(), GMSH_DistancePlugin::execute(), and OptimizeMesh().
getMeshElementByCoord()
MElement * GModel::getMeshElementByCoord (SPoint3 & p, SPoint3 & param, int dim = -1, bool strict = true)
Definition at line 1842 of file GModel.cpp.
Referenced by getElement().
getMeshElementByTag() [1/2]
MElement* GModel::getMeshElementByTag (int n) inline
Definition at line 538 of file GModel.h.
Referenced by readMSH4GhostElements(), MSubTetrahedron::updateParent(), MSubTriangle::updateParent(), MSubLine::updateParent(), MSubPoint::updateParent(), and writeNEU().
getMeshElementByTag() [2/2]
MElement * GModel::getMeshElementByTag (int n, int & entityTag)
Definition at line 2007 of file GModel.cpp.
getMeshElementIndex()
int GModel::getMeshElementIndex (MElement * e)
Definition at line 2027 of file GModel.cpp.
Referenced by _writeMSH2(), and writeElementsMSH().
getMeshElementsByCoord()
std::vector< MElement * > GModel::getMeshElementsByCoord (SPoint3 & p, int dim = -1, bool strict = true)
Definition at line 1865 of file GModel.cpp.
Referenced by getElement().
getMeshStatus()
int GModel::getMeshStatus (bool countDiscrete = true)
Definition at line 1474 of file GModel.cpp.
Referenced by drawContext::drawMesh(), GMSH_NewViewPlugin::execute(), fillVertexArrays(), GenerateMesh(), and needPolygonOffset().
getMeshVertexByTag()
MVertex * GModel::getMeshVertexByTag (int n)
Definition at line 1953 of file GModel.cpp.
Referenced by _addElements(), GMSH_SpanningTreePlugin::addToModel(), MElementFactory::create(), GeomMeshMatcher::forceTomatch(), getMeshVertices(), GFaceDelaunayRefinementOldMesher(), PolyMesh2GFace(), readMSH4Elements(), readMSH4PeriodicNodes(), readMSHPeriodicNodes(), and readUNV().
getMeshVerticesForPhysicalGroup()
void GModel::getMeshVerticesForPhysicalGroup (int dim, int num, std::vector< MVertex * > & v)
Definition at line 1987 of file GModel.cpp.
Referenced by femTerm< scalar >::dirichletNodalBC().
getMFace()
std::size_t GModel::getMFace (MVertex * v0, MVertex * v1, MVertex * v2, MVertex * v3, MFace & face)
Definition at line 1591 of file GModel.cpp.
getName()
std::string GModel::getName () const inline
Definition at line 329 of file GModel.h.
Referenced by buildCutMesh(), destroy(), GMSH_FieldFromAmplitudePhasePlugin::execute(), findByName(), PrintMesh2dStatistics(), writeMATLAB(), and writeVTK().
getNumEdges()
std::size_t GModel::getNumEdges () const inline
Definition at line 346 of file GModel.h.
Referenced by buildCutMesh(), getDim(), GetStatistics(), GeomMeshMatcher::match(), GeomMeshMatcher::matchEdges(), Mesh1D(), drawContext::select(), SetOrderN(), GEO_Internals::synchronize(), and writeMSHEntities().
getNumFaces()
std::size_t GModel::getNumFaces () const inline
Definition at line 345 of file GModel.h.
Referenced by buildCutMesh(), getDim(), GetStatistics(), GeomMeshMatcher::match(), GeomMeshMatcher::matchFaces(), Mesh2D(), drawContext::select(), SetOrderN(), GEO_Internals::synchronize(), and writeMSHEntities().
getNumMeshElements() [1/2]
std::size_t GModel::getNumMeshElements (int dim = -1) const
Definition at line 1540 of file GModel.cpp.
Referenced by adaptMesh(), PViewDataGModel::addData(), buildCutMesh(), checkMeshCoherence(), GenerateMesh(), getMeshDim(), rebuildMeshElementCache(), GMSH_SimplePartitionPlugin::run(), drawContext::select(), GEO_Internals::synchronize(), writeSU2(), and writeUNV().
getNumMeshElements() [2/2]
std::size_t GModel::getNumMeshElements (unsigned c[6])
Definition at line 1822 of file GModel.cpp.
getNumMeshParentElements()
std::size_t GModel::getNumMeshParentElements () const
Definition at line 1551 of file GModel.cpp.
Referenced by buildCutMesh().
getNumMeshVertices()
std::size_t GModel::getNumMeshVertices (int dim = -1) const
Definition at line 1529 of file GModel.cpp.
Referenced by PViewDataGModel::addData(), checkMeshCoherence(), GMSH_MeshVolumePlugin::execute(), GMSH_DistancePlugin::execute(), GenerateMesh(), rebuildMeshVertexCache(), GMSH_SpanningTreePlugin::run(), and writeMSH4Nodes().
getNumPartitions()
std::size_t GModel::getNumPartitions () const inline
Definition at line 602 of file GModel.h.
Referenced by _readMSH2(), _readMSH3(), _writeMSH4(), _writePartitionedMSH2(), _writePartitionedMSH3(), _writePartitionedMSH4(), buildCutMesh(), MElementFactory::create(), createElementMSH2(), readDIFF(), readMSH4Entities(), readMSH4GhostElements(), writeMSH(), writeMSH4Entities(), writePartitionedMSH(), and writePartitionedTopology().
getNumRegions()
std::size_t GModel::getNumRegions () const inline
Definition at line 344 of file GModel.h.
Referenced by BarycentricRefineMesh(), elasticitySolver::elasticitySolver(), getDim(), GetStatistics(), Mesh3D(), drawContext::select(), thermicSolver::setMesh(), elasticitySolver::setMesh(), SetOrderN(), GEO_Internals::synchronize(), and writeMSHEntities().
getNumVertices()
std::size_t GModel::getNumVertices () const inline
Definition at line 347 of file GModel.h.
Referenced by buildCutMesh(), drawContext::draw3d(), getDim(), GetStatistics(), GeomMeshMatcher::match(), GeomMeshMatcher::matchVertices(), drawContext::select(), GEO_Internals::synchronize(), TooManyElements(), and writeMSHEntities().
getOCCInternals()
OCC_Internals* GModel::getOCCInternals () inline
Definition at line 314 of file GModel.h.
Referenced by addEmbedded(), addPeriodicEdge(), addPeriodicFace(), getAllElementaryTags(), getAllPhysicalTags(), getBoundingBox(), getElementaryTagsForPhysicalGroups(), getElementaryTagsInBoundingBox(), getParentTags(), readGEO(), removeEmbedded(), scriptAddCommand(), setColor(), and setVisibility().
getParasolidInternals()
Parasolid_Internals* GModel::getParasolidInternals () inline
Definition at line 317 of file GModel.h.
getPhysicalGroups() [1/2]
void GModel::getPhysicalGroups (int dim, std::map< int, std::vector< GEntity * > > & groups) const
Definition at line 861 of file GModel.cpp.
getPhysicalGroups() [2/2]
void GModel::getPhysicalGroups (std::map< int, std::vector< GEntity * > > groups[4]) const
Definition at line 837 of file GModel.cpp.
Referenced by _writeX3dFile(), groupOfElements::addPhysical(), GMSH_NewViewPlugin::elementData(), GMSH_GaussPointsPlugin::execute(), GMSH_MeshSubEntitiesPlugin::execute(), GMSH_CrackPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_SpanningTreePlugin::getAllMElement(), getAllPhysicalTags(), getElementaryTagsForPhysicalGroups(), getMeshVerticesForPhysicalGroup(), GetStatistics(), getTagsForPhysicalName(), gLevelsetYarn::gLevelsetYarn(), Msg::ImportPhysicalGroupsInOnelab(), femTerm< scalar >::neumannNodalBC(), femTerm< scalar >::neumannNormalNodalBC(), writeGEO(), writeINP(), writeKEY(), writeRAD(), writeSTL(), writeSU2(), writeTOCHNOG(), and writeUNV().
getPhysicalName()
std::string GModel::getPhysicalName (int dim, int num) const
Definition at line 961 of file GModel.cpp.
Referenced by _writeX3dFile(), drawEntityLabel(), GEntity::getInfoString(), Msg::ImportPhysicalGroupsInOnelab(), physicalName(), writeNEU(), writePartitionedTopology(), and writeSTL().
getPhysicalNames()
const std::map<std::pair<int, int>, std::string>& GModel::getPhysicalNames () const inline
Definition at line 437 of file GModel.h.
Referenced by GeomMeshMatcher::match().
getPhysicalNumber()
int GModel::getPhysicalNumber (const int & dim, const std::string & name)
Definition at line 980 of file GModel.cpp.
Referenced by elasticitySolver::addDirichletBC(), elasticitySolver::addElasticDomain(), elasticitySolver::addNeumannBC(), getTagsForPhysicalName(), and setPhysicalName().
getRegionByTag()
GRegion * GModel::getRegionByTag (int n) const
Definition at line 316 of file GModel.cpp.
Referenced by _readMSH2(), _readMSH3(), _storeElementsInEntities(), _storePhysicalTagsInEntities(), addAutomaticExtrusionConstraints(), addEmbedded(), changeEntityTag(), createGeometryOfDiscreteEntities(), getBoundaryTags(), getEntityByTag(), readMSH4Entities(), readMSHEntities(), remove(), removeEmbedded(), drawContext::select(), storeChain(), and GEO_Internals::synchronize().
getRegionForOCCShape()
GRegion * GModel::getRegionForOCCShape (const void * shape)
Definition at line 5986 of file GModelIO_OCC.cpp.
getRegions()
std::set<GRegion *, GEntityPtrLessThan> GModel::getRegions () const inline
Definition at line 372 of file GModel.h.
Referenced by OptimizeMesh().
getTagsForPhysicalName()
std::vector< int > GModel::getTagsForPhysicalName (int dim, const std::string & name)
Definition at line 420 of file GModel.cpp.
getVertexByTag()
GVertex * GModel::getVertexByTag (int n) const
Definition at line 346 of file GModel.cpp.
Referenced by _readMSH2(), _readMSH3(), _storeElementsInEntities(), _storePhysicalTagsInEntities(), addEmbedded(), frameSolver2d::addFixations(), frameSolver2d::addNodalForces(), changeEntityTag(), BoundaryLayerField::computeFor1dMesh(), ExtrudePoint(), getBoundaryTags(), getEntityByTag(), MeshExtrudedCurve(), BoundaryLayerField::operator()(), readMSH4Entities(), readMSH4PeriodicNodes(), readMSHEntities(), readMSHPeriodicNodes(), remove(), gmshRegion::resetMeshAttributes(), gmshFace::resetMeshAttributes(), discreteFace::resetMeshAttributes(), drawContext::select(), storeChain(), GEO_Internals::synchronize(), and DistanceField::update().
getVertexForOCCShape()
GVertex * GModel::getVertexForOCCShape (const void * shape)
Definition at line 5956 of file GModelIO_OCC.cpp.
getVertices()
std::set<GVertex *, GEntityPtrLessThan> GModel::getVertices () const inline
Definition at line 378 of file GModel.h.
Referenced by GlobalBackgroundMesh::importGModelMeshes().
getVisibility()
char GModel::getVisibility () const inline
Definition at line 340 of file GModel.h.
Referenced by bounds(), drawContext::drawGeom(), drawContext::drawMesh(), fillVertexArrays(), setSelection(), and ~GModel().
hasFileName()
bool GModel::hasFileName (const std::string & name) const inline
Definition at line 334 of file GModel.h.
importOCCShape()
int GModel::importOCCShape (const void * shape)
Definition at line 5942 of file GModelIO_OCC.cpp.
incrementAndGetMaxElementNumber()
std::size_t GModel::incrementAndGetMaxElementNumber () inline
Definition at line 246 of file GModel.h.
Referenced by MElement::MElement().
incrementAndGetMaxVertexNumber()
std::size_t GModel::incrementAndGetMaxVertexNumber () inline
Definition at line 236 of file GModel.h.
Referenced by MVertex::MVertex().
indexMeshVertices()
std::size_t GModel::indexMeshVertices (bool all, int singlePartition = 0, bool renumber = true)
Definition at line 2135 of file GModel.cpp.
Referenced by _writeMSH2(), _writeMSH3(), buildCutMesh(), writeBDF(), writeDIFF(), writeINP(), writeIR3(), writeKEY(), writeMAIL(), writeMATLAB(), writeMESH(), writeNEU(), writeOFF(), writePLY2(), writeRAD(), writeSU2(), writeTOCHNOG(), writeUNV(), writeVRML(), and writeVTK().
lastEdge() [1/2]
eiter GModel::lastEdge () inline
Definition at line 360 of file GModel.h.
Referenced by _associateEntityWithMeshVertices(), _getOneElementOfGivenType(), _writeMSH2(), _writeMSH3(), _writeX3dFile(), adaptMesh(), alignPeriodicBoundaries(), buildEdgeSearchStructure(), classifyFaces(), createEdgeLinks(), createGeometryOfDiscreteEntities(), createTopologyFromMesh1D(), createTopologyFromMesh2D(), deleteMesh(), deleteVertexArrays(), destroy(), drawContext::drawGeom(), drawContext::drawMesh(), GMSH_BubblesPlugin::execute(), exportDiscreteGEOInternals(), fillVertexArrays(), FixPeriodicMesh(), GeomMeshMatcher::forceTomatch(), GenerateMesh(), getEntitiesToSave(), getGEdge(), getGVertex(), getMeshStatus(), getNodeCopies(), getNumElementsMSH(), PViewDataGModel::getNumLines(), getNumMeshElements(), GetStatistics(), GFaceInitialMesh(), GeomMeshMatcher::matchEdges(), Mesh1D(), Mesh2DWithBoundaryLayers(), RefineMesh(), remove(), removeInvisibleElements(), reverseInvisibleElements(), SetOrder1(), SetOrderN(), GEO_Internals::synchronize(), jacobianBasedQuality::testAllMeasuresAllElements(), topoExists(), writeGEO(), writeINP(), writeKEY(), writeMESH(), writeMSH4Entities(), writeMSH4Parametrizations(), writeMSHEntities(), writePY(), writeRAD(), writeTOCHNOG(), and writeVRML().
lastEdge() [2/2]
const_eiter GModel::lastEdge () const inline
Definition at line 368 of file GModel.h.
lastElementaryName()
piter GModel::lastElementaryName () inline
Definition at line 461 of file GModel.h.
lastFace() [1/2]
fiter GModel::lastFace () inline
Definition at line 359 of file GModel.h.
Referenced by _associateEntityWithMeshVertices(), _getOneElementOfGivenType(), _isModelOkForTopologicalOpti(), _writeMSH2(), _writeMSH3(), _writeX3dFile(), adaptMesh(), alignPeriodicBoundaries(), BarycentricRefineMesh(), checkHighOrderTriangles(), classifyFaces(), completeTheSetOfFaces(), computeDiscreteCurvatures(), computeEdgeCut(), computeLevelset(), computeNonManifoldEdges(), createFaceLinks(), createGeometryOfDiscreteEntities(), createSizeFieldFromExistingMesh(), createTopologyFromMesh2D(), createTopologyFromMesh3D(), deleteMesh(), deleteVertexArrays(), destroy(), drawContext::drawGeom(), drawContext::drawMesh(), ensureManifoldFaces(), GMSH_CurvedBndDistPlugin::execute(), GMSH_DiscretizationErrorPlugin::execute(), GMSH_BubblesPlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), GMSH_ShowNeighborElementsPlugin::execute(), exportDiscreteGEOInternals(), fillVertexArrays(), FixErasedExtrScaleFlags(), FixPeriodicMesh(), GeomMeshMatcher::forceTomatch(), GenerateMesh(), getEntitiesToSave(), getFacesOfTheModel(), getGFace(), getMeshStatus(), getNumElementsMSH(), getNumMeshElements(), PViewDataGModel::getNumPolygons(), PViewDataGModel::getNumQuadrangles(), PViewDataGModel::getNumTriangles(), GetStatistics(), insertVerticesInRegion(), makeDiscreteFacesSimplyConnected(), GeomMeshMatcher::matchFaces(), Mesh2D(), Mesh2DWithBoundaryLayers(), meshMetric::meshMetric(), OptimizeMesh(), PrintMesh2dStatistics(), RecombineMesh(), RefineMesh(), remove(), removeInvisibleElements(), reverseInvisibleElements(), SetOrder1(), SetOrderN(), GEO_Internals::synchronize(), jacobianBasedQuality::testAllMeasuresAllElements(), topoExists(), writeCELUM(), writeGEO(), writeINP(), writeIR3(), writeKEY(), writeMAIL(), writeMESH(), writeMSH4Entities(), writeMSH4Parametrizations(), writeMSHEntities(), writeNEU(), writeP3D(), writePLY2(), writePY(), writeRAD(), writeSTL(), writeSU2(), writeTOCHNOG(), and writeVRML().
lastFace() [2/2]
const_fiter GModel::lastFace () const inline
Definition at line 367 of file GModel.h.
lastMEdge()
hashmapMEdge::const_iterator GModel::lastMEdge () inline
Definition at line 286 of file GModel.h.
lastMFace()
hashmapMFace::const_iterator GModel::lastMFace () inline
Definition at line 288 of file GModel.h.
lastPhysicalName()
piter GModel::lastPhysicalName () inline
Definition at line 459 of file GModel.h.
Referenced by _writeMSH2(), _writeMSH3(), _writeMSH4(), getInnerPhysicalNamesIterators(), getPhysicalNumber(), and setPhysicalName().
lastRegion() [1/2]
riter GModel::lastRegion () inline
Definition at line 358 of file GModel.h.
Referenced by _associateEntityWithMeshVertices(), _getOneElementOfGivenType(), _writeMSH2(), _writeMSH3(), AdaptMesh(), adaptMesh(), BarycentricRefineMesh(), buildFaceSearchStructure(), splitQuadRecovery::buildPyramids(), checkHighOrderTetrahedron(), classifyFaces(), createGeometryOfDiscreteEntities(), createTopologyFromMesh3D(), deleteMesh(), deleteVertexArrays(), destroy(), drawContext::drawGeom(), drawContext::drawMesh(), GMSH_ShowNeighborElementsPlugin::execute(), exportDiscreteGEOInternals(), fillVertexArrays(), FixErasedExtrScaleFlags(), GenerateMesh(), getEntitiesToSave(), getMeshStatus(), getNumElementsMSH(), PViewDataGModel::getNumHexahedra(), getNumMeshElements(), PViewDataGModel::getNumPolyhedra(), PViewDataGModel::getNumPrisms(), PViewDataGModel::getNumPyramids(), PViewDataGModel::getNumTetrahedra(), PViewDataGModel::getNumTrihedra(), getRegionFromBoundingFaces(), GetStatistics(), insertVerticesInRegion(), makeDiscreteRegionsSimplyConnected(), MakeMeshConformal(), Mesh3D(), meshMetric::meshMetric(), OptimizeMesh(), RefineMesh(), remove(), removeInvisibleElements(), reverseInvisibleElements(), SetOrder1(), SetOrderN(), SubdivideExtrudedMesh(), GEO_Internals::synchronize(), jacobianBasedQuality::testAllMeasuresAllElements(), topoExists(), writeGEO(), writeINP(), writeIR3(), writeKEY(), writeMESH(), writeMSH4Entities(), writeMSHEntities(), writeNEU(), writeP3D(), writePY(), writeRAD(), writeSU2(), and writeTOCHNOG().
lastRegion() [2/2]
const_riter GModel::lastRegion () const inline
Definition at line 366 of file GModel.h.
lastVertex() [1/2]
viter GModel::lastVertex () inline
Definition at line 361 of file GModel.h.
Referenced by _associateEntityWithMeshVertices(), _getOneElementOfGivenType(), _writeMSH2(), _writeMSH3(), _writeX3dFile(), classifyFaces(), createTopologyFromMesh1D(), deleteMesh(), deleteVertexArrays(), destroy(), drawContext::drawGeom(), drawContext::drawMesh(), GMSH_BubblesPlugin::execute(), exportDiscreteGEOInternals(), getEntitiesToSave(), getMeshStatus(), getNumElementsMSH(), PViewDataGModel::getNumPoints(), GetStatistics(), GeomMeshMatcher::matchVertices(), Mesh0D(), remove(), snapVertices(), GEO_Internals::synchronize(), TooManyElements(), writeGEO(), writeINP(), writeKEY(), writeMSH4Entities(), writeMSHEntities(), writePY(), writeRAD(), writeTOCHNOG(), and writeVRML().
lastVertex() [2/2]
const_viter GModel::lastVertex () const inline
Definition at line 369 of file GModel.h.
load()
void GModel::load (const std::string & fileName)
Definition at line 3424 of file GModel.cpp.
Referenced by readUNV().
makeDiscreteFacesSimplyConnected()
void GModel::makeDiscreteFacesSimplyConnected ()
Definition at line 3160 of file GModel.cpp.
makeDiscreteRegionsSimplyConnected()
void GModel::makeDiscreteRegionsSimplyConnected ()
Definition at line 3101 of file GModel.cpp.
mesh()
int GModel::mesh (int dimension)
Definition at line 1066 of file GModel.cpp.
Referenced by _readMSH2(), _readMSH3(), _writeMSH2(), adaptMesh(), fillVertexArrays(), GmshBatch(), optimizeMesh(), readSTL(), readUNV(), recombineMesh(), refineMesh(), removeDuplicateMeshElements(), removeDuplicateMeshVertices(), renumberMeshElements(), renumberMeshVertices(), setOrderN(), and writeUNV().
noPhysicalGroups()
bool GModel::noPhysicalGroups ()
Definition at line 828 of file GModel.cpp.
Referenced by _writeMSH2(), _writeMSH3(), _writeMSH4(), _writeX3dFile(), writeBDF(), writeCELUM(), writeDIFF(), writeINP(), writeIR3(), writeKEY(), writeMAIL(), writeMATLAB(), writeMESH(), writeOFF(), writeP3D(), writePOS(), writeRAD(), writeSTL(), writeSU2(), writeTOCHNOG(), writeUNV(), writeVRML(), and writeVTK().
numPhysicalNames()
int GModel::numPhysicalNames () const inline
Definition at line 464 of file GModel.h.
Referenced by _readMSH4(), _writeMSH2(), _writeMSH3(), and _writeMSH4().
optimizeMesh()
int GModel::optimizeMesh (const std::string & how, bool force = false, int niter = 1)
Definition at line 1437 of file GModel.cpp.
partitionMesh()
int GModel::partitionMesh (int num, std::vector< std::pair< MElement *, int > > elementPartition = std::vector<std::pair<MElement *, int> >())
Definition at line 2208 of file GModel.cpp.
Referenced by GmshBatch().
pruneMeshVertexAssociations()
void GModel::pruneMeshVertexAssociations ()
Definition at line 2527 of file GModel.cpp.
Referenced by classifyFaces(), computeHomology(), createTopologyFromMesh(), GMSH_MeshSubEntitiesPlugin::execute(), and SetOrderN().
readACISSAT()
int GModel::readACISSAT (const std::string & name)
Definition at line 3608 of file GModel.cpp.
Referenced by MergeFile().
readACTRAN()
int GModel::readACTRAN (const std::string & name)
Definition at line 32 of file GModelIO_ACTRAN.cpp.
Referenced by MergeFile().
readBDF()
int GModel::readBDF (const std::string & name)
Definition at line 218 of file GModelIO_BDF.cpp.
Referenced by MergeFile().
readCGNS()
int GModel::readCGNS (const std::string & name, std::vector< std::vector< MVertex * > > & vertPerZone, std::vector< std::vector< MElement * > > & eltPerZone)
Definition at line 244 of file GModelIO_CGNS.cpp.
Referenced by MergeFile().
readDIFF()
int GModel::readDIFF (const std::string & name)
Definition at line 42 of file GModelIO_DIFF.cpp.
Referenced by MergeFile().
readGEO()
int GModel::readGEO (const std::string & name) static
Definition at line 3440 of file GModel.cpp.
Referenced by MergeFile(), and ParseString().
readGEOM()
int GModel::readGEOM (const std::string & name)
Definition at line 24 of file GModelIO_GEOM.cpp.
Referenced by MergeFile().
readMED() [1/2]
int GModel::readMED (const std::string & name) static
Definition at line 879 of file GModelIO_MED.cpp.
Referenced by MergeFile().
readMED() [2/2]
int GModel::readMED (const std::string & name, int meshIndex)
Definition at line 886 of file GModelIO_MED.cpp.
readMESH()
int GModel::readMESH (const std::string & name)
Definition at line 31 of file GModelIO_MESH.cpp.
Referenced by MergeFile().
readMSH()
int GModel::readMSH (const std::string & name)
Definition at line 12 of file GModelIO_MSH.cpp.
Referenced by GMSH_FieldFromAmplitudePhasePlugin::execute(), MergeFile(), thermicSolver::setMesh(), and elasticitySolver::setMesh().
readOCCBREP()
int GModel::readOCCBREP (const std::string & name)
Definition at line 5892 of file GModelIO_OCC.cpp.
Referenced by MergeFile().
readOCCIGES()
int GModel::readOCCIGES (const std::string & name)
Definition at line 5911 of file GModelIO_OCC.cpp.
Referenced by MergeFile().
readOCCSTEP()
int GModel::readOCCSTEP (const std::string & name)
Definition at line 5902 of file GModelIO_OCC.cpp.
Referenced by MergeFile().
readOFF()
int GModel::readOFF (const std::string & name)
Definition at line 14 of file GModelIO_OFF.cpp.
Referenced by MergeFile().
readP3D()
int GModel::readP3D (const std::string & name)
Definition at line 13 of file GModelIO_P3D.cpp.
Referenced by MergeFile().
readParasolidSTEP()
int GModel::readParasolidSTEP (const std::string & name)
Definition at line 3637 of file GModel.cpp.
readParasolidXMT()
int GModel::readParasolidXMT (const std::string & name)
Definition at line 3623 of file GModel.cpp.
Referenced by MergeFile().
readPLY()
int GModel::readPLY (const std::string & name)
Definition at line 49 of file GModelIO_PLY.cpp.
Referenced by MergeFile().
readPLY2()
int GModel::readPLY2 (const std::string & name)
Definition at line 216 of file GModelIO_PLY.cpp.
Referenced by MergeFile().
readSAMCEF()
int GModel::readSAMCEF (const std::string & name)
Definition at line 33 of file GModelIO_SAMCEF.cpp.
Referenced by MergeFile().
readSTL()
int GModel::readSTL (const std::string & name, double tolerance = 1.e-3)
Definition at line 22 of file GModelIO_STL.cpp.
Referenced by MergeFile().
readUNV()
int GModel::readUNV (const std::string & name, bool readGroupsOfElements = true)
Definition at line 36 of file GModelIO_UNV.cpp.
Referenced by MergeFile().
readVRML()
int GModel::readVRML (const std::string & name)
Definition at line 118 of file GModelIO_VRML.cpp.
Referenced by MergeFile().
readVTK()
int GModel::readVTK (const std::string & name, bool bigEndian = false)
Definition at line 131 of file GModelIO_VTK.cpp.
Referenced by MergeFile().
rebuildMeshElementCache()
void GModel::rebuildMeshElementCache (bool onlyIfNecessary = false)
Definition at line 1914 of file GModel.cpp.
Referenced by getMeshElementByTag().
rebuildMeshVertexCache()
void GModel::rebuildMeshVertexCache (bool onlyIfNecessary = false)
Definition at line 1879 of file GModel.cpp.
Referenced by addMVertexToVertexCache(), and getMeshVertexByTag().
recombineMesh()
int GModel::recombineMesh ()
Definition at line 1421 of file GModel.cpp.
refineMesh()
int GModel::refineMesh (int linear, bool splitIntoQuads = false, bool splitIntoHexas = false, bool barycentric = false)
Definition at line 1401 of file GModel.cpp.
Referenced by GmshBatch().
remove() [1/7]
void GModel::remove ()
Definition at line 608 of file GModel.cpp.
Referenced by makeDiscreteFacesSimplyConnected(), makeDiscreteRegionsSimplyConnected(), and remove().
remove() [2/7]
void GModel::remove (const std::vector< std::pair< int, int > > & dimTags, std::vector< GEntity * > & removed, bool recursive = false)
Definition at line 601 of file GModel.cpp.
remove() [3/7]
bool GModel::remove (GEdge * e)
Definition at line 463 of file GModel.cpp.
remove() [4/7]
bool GModel::remove (GFace * f)
Definition at line 449 of file GModel.cpp.
remove() [5/7]
bool GModel::remove (GRegion * r)
Definition at line 435 of file GModel.cpp.
Referenced by classifyFaces(), and GEO_Internals::synchronize().
remove() [6/7]
bool GModel::remove (GVertex * v)
Definition at line 477 of file GModel.cpp.
remove() [7/7]
void GModel::remove (int dim, int tag, std::vector< GEntity * > & removed, bool recursive = false)
Definition at line 489 of file GModel.cpp.
removeDuplicateMeshElements()
int GModel::removeDuplicateMeshElements (const std::vector< GEntity * > & entities = std::vector<GEntity*>())
Definition at line 2792 of file GModel.cpp.
removeDuplicateMeshVertices()
int GModel::removeDuplicateMeshVertices (double tolerance, const std::vector< GEntity * > & entities = std::vector<GEntity*>())
Definition at line 2684 of file GModel.cpp.
removeElementaryName()
void GModel::removeElementaryName (const std::string & name)
Definition at line 1014 of file GModel.cpp.
removeInvisibleElements()
std::size_t GModel::removeInvisibleElements ()
Definition at line 2057 of file GModel.cpp.
Referenced by GMSH_InvisiblePlugin::execute().
removePhysicalGroup()
void GModel::removePhysicalGroup (int dim, int num)
Definition at line 901 of file GModel.cpp.
Referenced by DeletePhysicalLine(), DeletePhysicalPoint(), DeletePhysicalSurface(), and DeletePhysicalVolume().
removePhysicalGroups()
void GModel::removePhysicalGroups ()
Definition at line 893 of file GModel.cpp.
Referenced by GEO_Internals::synchronize().
removePhysicalName()
void GModel::removePhysicalName (const std::string & name)
Definition at line 968 of file GModel.cpp.
renumberMeshElements()
void GModel::renumberMeshElements ()
Definition at line 1732 of file GModel.cpp.
Referenced by adaptMesh(), mesh(), optimizeMesh(), recombineMesh(), refineMesh(), removeDuplicateMeshElements(), and setOrderN().
renumberMeshVertices()
void GModel::renumberMeshVertices ()
Definition at line 1623 of file GModel.cpp.
Referenced by adaptMesh(), mesh(), optimizeMesh(), recombineMesh(), refineMesh(), removeDuplicateMeshVertices(), and setOrderN().
resetOCCInternals()
void GModel::resetOCCInternals ()
Definition at line 5886 of file GModelIO_OCC.cpp.
Referenced by destroy().
reverseInvisibleElements()
std::size_t GModel::reverseInvisibleElements ()
Definition at line 2102 of file GModel.cpp.
Referenced by GMSH_InvisiblePlugin::execute().
save()
void GModel::save (const std::string & fileName)
Definition at line 3432 of file GModel.cpp.
scaleMesh()
void GModel::scaleMesh (double factor)
Definition at line 2189 of file GModel.cpp.
Referenced by MergeFile().
setAllVolumesPositive()
bool GModel::setAllVolumesPositive ()
Definition at line 1085 of file GModel.cpp.
Referenced by Mesh3D(), MeshDelaunayVolume(), OptimizeMesh(), and RefineMesh().
setAllVolumesPositiveTopology()
void GModel::setAllVolumesPositiveTopology ()
Definition at line 1161 of file GModel.cpp.
setAsCurrent()
int GModel::setAsCurrent () inline
Definition at line 211 of file GModel.h.
setCurrent()
int GModel::setCurrent (GModel * m) static
Definition at line 147 of file GModel.cpp.
Referenced by load(), GeomMeshMatcher::match(), MergeFile(), MergePostProcessingFile(), save(), and setAsCurrent().
setCurrentMeshEntity()
void GModel::setCurrentMeshEntity (GEntity * e)
Definition at line 2202 of file GModel.cpp.
Referenced by meshGEdge::operator()(), meshGFace::operator()(), meshGRegion::operator()(), meshGRegionExtruded::operator()(), optimizeMeshGRegion::operator()(), orientMeshGFace::operator()(), and optimizeMeshGRegionNetgen::operator()().
setElementaryName()
void GModel::setElementaryName (int dim, int tag, const std::string & name) inline
Definition at line 500 of file GModel.h.
Referenced by readSTL().
setFileName()
void GModel::setFileName (const std::string & fileName)
Definition at line 123 of file GModel.cpp.
Referenced by buildCutMesh(), ClearProject(), DoSystemUncompress(), GetOptions(), MergeFile(), and scriptAddCommand().
setMaxElementNumber()
void GModel::setMaxElementNumber (std::size_t num) inline
Definition at line 229 of file GModel.h.
Referenced by MElement::forceNum(), MElement::MElement(), and renumberMeshElements().
setMaxVertexNumber()
void GModel::setMaxVertexNumber (std::size_t num) inline
Definition at line 224 of file GModel.h.
Referenced by MVertex::forceNum(), MVertex::MVertex(), and renumberMeshVertices().
setMeshElementIndex()
void GModel::setMeshElementIndex (MElement * e, int index)
Definition at line 2036 of file GModel.cpp.
Referenced by writeElementMSH().
setName()
void GModel::setName (const std::string & name) inline
Definition at line 328 of file GModel.h.
Referenced by ClearProject(), GMSH_FieldFromAmplitudePhasePlugin::execute(), MergeFile(), and scriptAddCommand().
setNumPartitions()
void GModel::setNumPartitions (std::size_t npart) inline
Definition at line 603 of file GModel.h.
Referenced by buildCutMesh(), MElementFactory::create(), createElementMSH2(), readDIFF(), and readMSH4Entities().
setOrderN()
int GModel::setOrderN (int order, int linear, int incomplete, int onlyVisible)
Definition at line 1454 of file GModel.cpp.
Referenced by classifyFaces(), and PolyMesh2GFace().
setPhysicalName() [1/2]
int GModel::setPhysicalName (const std::string & name, int dim, int num = 0)
Definition at line 937 of file GModel.cpp.
Referenced by _readMSH2(), _readMSH3(), _readMSH4(), GMSH_SpanningTreePlugin::addToModel(), and buildCutGModel().
setPhysicalName() [2/2]
GModel::piter GModel::setPhysicalName (piter pos, const std::string & name, int dim, int num = 0)
Definition at line 949 of file GModel.cpp.
setPhysicalNames()
void GModel::setPhysicalNames (const std::map< std::pair< int, int >, std::string > & names) inline
Definition at line 441 of file GModel.h.
Referenced by GeomMeshMatcher::match().
setPhysicalNumToEntitiesInBox() [1/2]
void GModel::setPhysicalNumToEntitiesInBox (int EntityDimension, int PhysicalNumber, const SBoundingBox3d & box)
Definition at line 3452 of file GModel.cpp.
setPhysicalNumToEntitiesInBox() [2/2]
void GModel::setPhysicalNumToEntitiesInBox (int EntityDimension, int PhysicalNumber, std::vector< double > p1, std::vector< double > p2)
Definition at line 3462 of file GModel.cpp.
setSelection()
void GModel::setSelection (int val)
Definition at line 1026 of file GModel.cpp.
Referenced by ClearProject(), and OpenProject().
setVisibility()
void GModel::setVisibility (char val) inline
Definition at line 341 of file GModel.h.
Referenced by GMSH_FieldFromAmplitudePhasePlugin::execute(), GModel(), GmshFLTK(), MergeFile(), MergePostProcessingFile(), and GMSH_CutMeshPlugin::run().
snapVertices()
void GModel::snapVertices ()
Definition at line 616 of file GModel.cpp.
Referenced by importOCCShape(), and readOCCBREP().
storeChain()
void GModel::storeChain (int dim, std::map< int, std::vector< MElement * > > & entityMap, std::map< int, std::map< int, std::string > > & physicalMap)
Definition at line 2247 of file GModel.cpp.
Referenced by GMSH_SpanningTreePlugin::addToModel().
unpartitionMesh()
int GModel::unpartitionMesh ()
Definition at line 2226 of file GModel.cpp.
Referenced by GMSH_SimplePartitionPlugin::run().
writeBDF()
int GModel::writeBDF (const std::string & name, int format = 0, int elementTagType = 1, bool saveAll = false, double scalingFactor = 1.0)
Definition at line 347 of file GModelIO_BDF.cpp.
Referenced by CreateOutputFile().
writeCELUM()
int GModel::writeCELUM (const std::string & name, bool saveAll = false, double scalingFactor = 1.0)
Definition at line 17 of file GModelIO_CELUM.cpp.
Referenced by CreateOutputFile().
writeCGNS()
int GModel::writeCGNS (const std::string & name, bool saveAll = false, double scalingFactor = 1.0, bool structured = false)
Definition at line 252 of file GModelIO_CGNS.cpp.
Referenced by CreateOutputFile().
writeDIFF()
int GModel::writeDIFF (const std::string & name, bool binary = false, bool saveAll = false, double scalingFactor = 1.0)
Definition at line 407 of file GModelIO_DIFF.cpp.
Referenced by CreateOutputFile().
writeGEO()
int GModel::writeGEO (const std::string & name, bool printLabels = true, bool onlyPhysicals = false)
Definition at line 1802 of file GModelIO_GEO.cpp.
Referenced by CreateOutputFile().
writeINP()
int GModel::writeINP (const std::string & name, bool saveAll = false, int saveGroupsOfElements = 0, int saveGroupsOfNodes = 0, double scalingFactor = 1.0)
Definition at line 53 of file GModelIO_INP.cpp.
Referenced by CreateOutputFile().
writeIR3()
int GModel::writeIR3 (const std::string & name, int elementTagType, bool saveAll, double scalingFactor)
Definition at line 10 of file GModelIO_IR3.cpp.
Referenced by CreateOutputFile().
writeKEY()
int GModel::writeKEY (const std::string & name, int saveAll = 0, int saveGroupsOfNodes = 0, double scalingFactor = 1.0)
Definition at line 53 of file GModelIO_KEY.cpp.
Referenced by CreateOutputFile().
writeMAIL()
int GModel::writeMAIL (const std::string & name, bool saveAll, double scalingFactor)
Definition at line 10 of file GModelIO_MAIL.cpp.
Referenced by CreateOutputFile().
writeMATLAB()
int GModel::writeMATLAB (const std::string & name, bool binary = false, bool saveAll = false, double scalingFactor = 1.0, int filetype = 1)
Definition at line 47 of file GModelIO_MATLAB.cpp.
Referenced by CreateOutputFile().
writeMED()
int GModel::writeMED (const std::string & name, bool saveAll = false, double scalingFactor = 1.0)
Definition at line 893 of file GModelIO_MED.cpp.
Referenced by CreateOutputFile().
writeMESH()
int GModel::writeMESH (const std::string & name, int elementTagType = 1, bool saveAll = false, double scalingFactor = 1.0)
Definition at line 249 of file GModelIO_MESH.cpp.
Referenced by CreateOutputFile().
writeMSH()
int GModel::writeMSH (const std::string & name, double version = 2.2, bool binary = false, bool saveAll = false, bool saveParametric = false, double scalingFactor = 1.0, int elementStartNum = 0, int saveSinglePartition = 0, bool append = false)
Definition at line 76 of file GModelIO_MSH.cpp.
Referenced by _writeMSH3(), adaptMesh(), CreateOutputFile(), thermicSolver::cutMesh(), elasticitySolver::cutMesh(), GeomMeshMatcher::forceTomatch(), meshGenerator(), elasticitySolver::readInputFile(), and recombineIntoQuads().
writeNEU()
int GModel::writeNEU (const std::string & name, bool saveAll, double scalingFactor)
Definition at line 121 of file GModelIO_NEU.cpp.
Referenced by CreateOutputFile().
writeOCCBREP()
int GModel::writeOCCBREP (const std::string & name)
Definition at line 5920 of file GModelIO_OCC.cpp.
Referenced by CreateOutputFile().
writeOCCSTEP()
int GModel::writeOCCSTEP (const std::string & name)
Definition at line 5931 of file GModelIO_OCC.cpp.
Referenced by CreateOutputFile().
writeOFF()
int GModel::writeOFF (const std::string & name, bool saveAll = false, double scalingFactor = 1.0)
Definition at line 83 of file GModelIO_OFF.cpp.
Referenced by CreateOutputFile().
writeP3D()
int GModel::writeP3D (const std::string & name, bool saveAll = false, double scalingFactor = 1.0)
Definition at line 123 of file GModelIO_P3D.cpp.
Referenced by CreateOutputFile().
writeParasolidSTEP()
int GModel::writeParasolidSTEP (const std::string & name)
Definition at line 3644 of file GModel.cpp.
Referenced by CreateOutputFile().
writeParasolidXMT()
int GModel::writeParasolidXMT (const std::string & name)
Definition at line 3630 of file GModel.cpp.
Referenced by CreateOutputFile().
writePartitionedMSH()
int GModel::writePartitionedMSH (const std::string & baseName, double version = 2.2, bool binary = false, bool saveAll = false, bool saveParametric = false, double scalingFactor = 1.0)
Definition at line 104 of file GModelIO_MSH.cpp.
Referenced by CreateOutputFile().
writePartitionedTopology()
int GModel::writePartitionedTopology (std::string & name)
Definition at line 2991 of file GModelIO_MSH4.cpp.
Referenced by CreateOutputFile().
writePLY2()
int GModel::writePLY2 (const std::string & name)
Definition at line 282 of file GModelIO_PLY.cpp.
Referenced by CreateOutputFile().
writePOS()
int GModel::writePOS (const std::string & name, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, bool saveAll = false, double scalingFactor = 1.0)
Definition at line 11 of file GModelIO_POS.cpp.
Referenced by CreateOutputFile().
writePY()
int GModel::writePY (const std::string & name, bool printLabels = true, bool onlyPhysicals = false)
Definition at line 1863 of file GModelIO_GEO.cpp.
Referenced by CreateOutputFile().
writeRAD()
int GModel::writeRAD (const std::string & name, int saveAll = 0, int saveGroupsOfNodes = 0, double scalingFactor = 1.0)
Definition at line 54 of file GModelIO_RAD.cpp.
Referenced by CreateOutputFile().
writeSTL()
int GModel::writeSTL (const std::string & name, bool binary = false, bool saveAll = false, double scalingFactor = 1.0, int oneSolidPerSurface = 0)
Definition at line 308 of file GModelIO_STL.cpp.
Referenced by CreateOutputFile().
writeSU2()
int GModel::writeSU2 (const std::string & name, bool saveAll, double scalingFactor)
Definition at line 29 of file GModelIO_SU2.cpp.
Referenced by CreateOutputFile().
writeTOCHNOG()
int GModel::writeTOCHNOG (const std::string & name, bool saveAll = false, int saveGroupsOfNodes = 0, double scalingFactor = 1.0)
Definition at line 54 of file GModelIO_TOCHNOG.cpp.
Referenced by CreateOutputFile().
writeUNV()
int GModel::writeUNV (const std::string & name, bool saveAll = false, int saveGroupsOfElements = 0, int saveGroupsOfNodes = 0, double scalingFactor = 1.0)
Definition at line 398 of file GModelIO_UNV.cpp.
Referenced by CreateOutputFile().
writeVRML()
int GModel::writeVRML (const std::string & name, bool saveAll = false, double scalingFactor = 1.0)
Definition at line 191 of file GModelIO_VRML.cpp.
Referenced by CreateOutputFile().
writeVTK()
int GModel::writeVTK (const std::string & name, bool binary = false, bool saveAll = false, double scalingFactor = 1.0, bool bigEndian = false)
Definition at line 19 of file GModelIO_VTK.cpp.
Referenced by CreateOutputFile().
writeX3D()
int GModel::writeX3D (const std::string & name, bool saveAll = false, double scalingFactor = 1.0, int x3dsurfaces = 1, int x3dedges = 0, int x3dvertices = 0, int x3dvolumes = 0, int x3dcolorize = 0)
Definition at line 472 of file GModelIO_X3D.cpp.
Referenced by CreateOutputFile().
Member Data Documentation
_acis_internals
ACIS_Internals* GModel::_acis_internals protected
Definition at line 123 of file GModel.h.
Referenced by getACISInternals().
_attributes
std::map<std::string, std::vector<std::string> > GModel::_attributes protected
Definition at line 156 of file GModel.h.
Referenced by _readMSH4(), _writeMSH4(), and getAttributes().
_chainEdges
std::set<GEdge *, GEntityPtrLessThan> GModel::_chainEdges private
Definition at line 51 of file GModel.h.
Referenced by pruneMeshVertexAssociations(), and storeChain().
_chainFaces
std::set<GFace *, GEntityPtrLessThan> GModel::_chainFaces private
Definition at line 50 of file GModel.h.
Referenced by pruneMeshVertexAssociations(), and storeChain().
_chainRegions
std::set<GRegion *, GEntityPtrLessThan> GModel::_chainRegions private
Definition at line 49 of file GModel.h.
Referenced by pruneMeshVertexAssociations(), and storeChain().
_chainVertices
std::set<GVertex *, GEntityPtrLessThan> GModel::_chainVertices private
Definition at line 52 of file GModel.h.
Referenced by pruneMeshVertexAssociations(), and storeChain().
_checkPointedMaxElementNum
std::size_t GModel::_checkPointedMaxElementNum private
Definition at line 57 of file GModel.h.
Referenced by destroy(), getCheckPointedMaxNumbers(), and GModel().
_checkPointedMaxVertexNum
std::size_t GModel::_checkPointedMaxVertexNum private
Definition at line 57 of file GModel.h.
Referenced by checkPointMaxNumbers(), destroy(), getCheckPointedMaxNumbers(), and GModel().
_current
int GModel::_current = -1 static protected
Definition at line 139 of file GModel.h.
Referenced by current(), and setCurrent().
_currentMeshEntity
GEntity* GModel::_currentMeshEntity protected
Definition at line 131 of file GModel.h.
Referenced by deleteMesh(), destroy(), getCurrentMeshEntity(), and setCurrentMeshEntity().
_curvatures
std::map<MVertex *, std::pair<SVector3, SVector3> > GModel::_curvatures protected
Definition at line 116 of file GModel.h.
Referenced by getCurvatures().
_elementaryNames
std::map<std::pair<int, int>, std::string> GModel::_elementaryNames protected
Definition at line 150 of file GModel.h.
Referenced by firstElementaryName(), getElementaryName(), lastElementaryName(), removeElementaryName(), and setElementaryName().
_elementIndexCache
std::map<int, int> GModel::_elementIndexCache protected
Definition at line 105 of file GModel.h.
Referenced by _writeMSH2(), _writeMSH3(), destroyMeshCaches(), getMeshElementIndex(), and setMeshElementIndex().
_elementMapCache
std::map<int, std::pair<MElement *, int> > GModel::_elementMapCache protected
Definition at line 104 of file GModel.h.
Referenced by _readMSH4(), destroyMeshCaches(), getMeshElementByTag(), and rebuildMeshElementCache().
_elementOctree
MElementOctree* GModel::_elementOctree protected
Definition at line 113 of file GModel.h.
Referenced by adaptMesh(), destroyMeshCaches(), getMeshElementByCoord(), and getMeshElementsByCoord().
_elementVectorCache
std::vector<std::pair<MElement *, int> > GModel::_elementVectorCache protected
Definition at line 103 of file GModel.h.
Referenced by _readMSH4(), destroyMeshCaches(), getMeshElementByTag(), and rebuildMeshElementCache().
_fields
FieldManager* GModel::_fields protected
Definition at line 128 of file GModel.h.
Referenced by destroy(), getFields(), GModel(), and ~GModel().
_fileName
std::string GModel::_fileName protected
Definition at line 93 of file GModel.h.
Referenced by getFileName(), and setFileName().
_fileNames
std::set<std::string> GModel::_fileNames protected
Definition at line 94 of file GModel.h.
Referenced by destroy(), hasFileName(), and setFileName().
_geo_internals
GEO_Internals* GModel::_geo_internals protected
Definition at line 119 of file GModel.h.
Referenced by createGEOInternals(), deleteGEOInternals(), exportDiscreteGEOInternals(), and getGEOInternals().
_ghostCells
std::multimap<MElement *, short> GModel::_ghostCells protected
Definition at line 110 of file GModel.h.
Referenced by _readMSH2(), _writePartitionedMSH2(), addGhostCells(), and getGhostCells().
_homologyRequests
std::multimap<std::pair<const std::vector<int>, const std::vector<int> >, std::pair<const std::string, const std::vector<int> > > GModel::_homologyRequests private
Definition at line 48 of file GModel.h.
Referenced by addHomologyRequest(), clearHomologyRequests(), and computeHomology().
_lastMeshEntityError
std::vector<GEntity *> GModel::_lastMeshEntityError protected
Definition at line 134 of file GModel.h.
Referenced by addLastMeshEntityError(), clearLastMeshEntityError(), deleteMesh(), destroy(), and getLastMeshEntityError().
_lastMeshVertexError
std::vector<MVertex *> GModel::_lastMeshVertexError protected
Definition at line 135 of file GModel.h.
Referenced by addLastMeshVertexError(), clearLastMeshVertexError(), deleteMesh(), destroy(), and getLastMeshVertexError().
_mapEdgeNum
hashmapMEdge GModel::_mapEdgeNum private
Definition at line 53 of file GModel.h.
Referenced by addMEdge(), firstMEdge(), getMEdge(), and lastMEdge().
_mapFaceNum
hashmapMFace GModel::_mapFaceNum private
Definition at line 54 of file GModel.h.
Referenced by addMFace(), firstMFace(), getMFace(), and lastMFace().
_maxElementNum
std::size_t GModel::_maxElementNum private
Definition at line 56 of file GModel.h.
Referenced by destroy(), getMaxElementNumber(), GModel(), incrementAndGetMaxElementNumber(), rebuildMeshElementCache(), and setMaxElementNumber().
_maxVertexNum
std::size_t GModel::_maxVertexNum private
Definition at line 56 of file GModel.h.
Referenced by checkPointMaxNumbers(), decrementMaxVertexNumber(), destroy(), getMaxVertexNumber(), GModel(), incrementAndGetMaxVertexNumber(), rebuildMeshVertexCache(), and setMaxVertexNumber().
_name
std::string GModel::_name protected
Definition at line 90 of file GModel.h.
Referenced by destroy(), getName(), and setName().
_numPartitions
std::size_t GModel::_numPartitions protected
Definition at line 153 of file GModel.h.
Referenced by getNumPartitions(), partitionMesh(), and setNumPartitions().
_occ_internals
OCC_Internals* GModel::_occ_internals protected
Definition at line 121 of file GModel.h.
Referenced by createOCCInternals(), deleteOCCInternals(), getEdgeForOCCShape(), getFaceForOCCShape(), getOCCInternals(), getRegionForOCCShape(), getVertexForOCCShape(), importOCCShape(), readOCCBREP(), readOCCIGES(), readOCCSTEP(), resetOCCInternals(), writeOCCBREP(), and writeOCCSTEP().
_parasolid_internals
Parasolid_Internals* GModel::_parasolid_internals protected
Definition at line 125 of file GModel.h.
Referenced by getParasolidInternals().
_physicalNames
std::map<std::pair<int, int>, std::string> GModel::_physicalNames protected
Definition at line 150 of file GModel.h.
Referenced by _storePhysicalTagsInEntities(), firstPhysicalName(), getPhysicalName(), getPhysicalNames(), lastPhysicalName(), numPhysicalNames(), removePhysicalGroup(), removePhysicalName(), setPhysicalName(), setPhysicalNames(), and writeGEO().
_vertexMapCache
std::map<int, MVertex *> GModel::_vertexMapCache protected
Definition at line 102 of file GModel.h.
Referenced by _readMSH2(), _readMSH3(), _readMSH4(), addMVertexToVertexCache(), destroyMeshCaches(), getMeshVertexByTag(), readACTRAN(), readSAMCEF(), readUNV(), and rebuildMeshVertexCache().
_vertexVectorCache
std::vector<MVertex *> GModel::_vertexVectorCache protected
Definition at line 101 of file GModel.h.
Referenced by _readMSH2(), _readMSH3(), _readMSH4(), addMVertexToVertexCache(), destroyMeshCaches(), getMeshVertexByTag(), and rebuildMeshVertexCache().
_visible
char GModel::_visible protected
Definition at line 97 of file GModel.h.
Referenced by getVisibility(), and setVisibility().
edges
std::set<GEdge *, GEntityPtrLessThan> GModel::edges protected
Definition at line 145 of file GModel.h.
Referenced by _writeX3dFile(), add(), changeEntityTag(), destroy(), empty(), exportDiscreteGEOInternals(), firstEdge(), getBoundaryTags(), getEdgeByTag(), getEdges(), getEntities(), getNumEdges(), lastEdge(), remove(), and snapVertices().
faces
std::set<GFace *, GEntityPtrLessThan> GModel::faces protected
Definition at line 144 of file GModel.h.
Referenced by _writeX3dFile(), add(), changeEntityTag(), destroy(), empty(), exportDiscreteGEOInternals(), firstFace(), getBoundaryTags(), getEntities(), getFaceByTag(), getFaces(), getNumFaces(), lastFace(), readSTL(), remove(), writeOFF(), writeP3D(), writeSTL(), and writeX3D().
lcCallback
std::function<double(int, int, double, double, double, double)> GModel::lcCallback
Definition at line 713 of file GModel.h.
Referenced by BGM_MeshSizeWithoutScaling().
list
std::vector< GModel * > GModel::list static
Definition at line 202 of file GModel.h.
Referenced by current(), DeleteAllModelsAndViews(), drawContext::drawAxes(), drawContext::drawGeom(), drawContext::drawMesh(), findByName(), GModel(), GmshInitialize(), OpenProject(), setCurrent(), and ~GModel().
normals
smooth_normals* GModel::normals
Definition at line 653 of file GModel.h.
Referenced by addElementsInArrays(), addSmoothNormals(), destroy(), and fillVertexArrays().
regions
std::set<GRegion *, GEntityPtrLessThan> GModel::regions protected
Definition at line 143 of file GModel.h.
Referenced by add(), addAutomaticExtrusionConstraints(), changeEntityTag(), destroy(), empty(), firstRegion(), getEntities(), getNumRegions(), getRegionByTag(), getRegions(), lastRegion(), RelocateVertices(), RelocateVerticesOfPyramids(), remove(), setAllVolumesPositive(), setAllVolumesPositiveTopology(), and writeP3D().
vertices
std::set<GVertex *, GEntityPtrLessThan> GModel::vertices protected
Definition at line 146 of file GModel.h.
Referenced by _readMSH2(), _storeVerticesInEntities(), add(), changeEntityTag(), checkMeshCoherence(), destroy(), empty(), firstVertex(), getEntities(), getFaceVerticesOnExtrudedGeo(), getFaceVerticesOnGeo(), getNumVertices(), getVertexByTag(), getVertices(), interpVerticesInExistingFace(), lastVertex(), pruneMeshVertexAssociations(), readACTRAN(), readBDF(), readDIFF(), readElementBDF(), readGEOM(), readMESH(), readOFF(), readPLY(), readPLY2(), readSAMCEF(), readSTL(), readUNV(), readVTK(), remove(), and removeDuplicateMeshVertices().
The documentation for this class was generated from the following files:
src/geo/GModel.h
src/geo/GModel.cpp
src/geo/GModelAutoExtrude.cpp
src/geo/GModelCreateTopologyFromMesh.cpp
src/geo/GModelIO_ACTRAN.cpp
src/geo/GModelIO_BDF.cpp
src/geo/GModelIO_CELUM.cpp
src/geo/GModelIO_CGNS.cpp
src/geo/GModelIO_DIFF.cpp
src/geo/GModelIO_GEO.cpp
src/geo/GModelIO_GEOM.cpp
src/geo/GModelIO_INP.cpp
src/geo/GModelIO_IR3.cpp
src/geo/GModelIO_KEY.cpp
src/geo/GModelIO_MAIL.cpp
src/geo/GModelIO_MATLAB.cpp
src/geo/GModelIO_MED.cpp
src/geo/GModelIO_MESH.cpp
src/geo/GModelIO_MSH.cpp
src/geo/GModelIO_MSH2.cpp
src/geo/GModelIO_MSH3.cpp
src/geo/GModelIO_MSH4.cpp
src/geo/GModelIO_NEU.cpp
src/geo/GModelIO_OCC.cpp
src/geo/GModelIO_OFF.cpp
src/geo/GModelIO_P3D.cpp
src/geo/GModelIO_PLY.cpp
src/geo/GModelIO_POS.cpp
src/geo/GModelIO_RAD.cpp
src/geo/GModelIO_SAMCEF.cpp
src/geo/GModelIO_STL.cpp
src/geo/GModelIO_SU2.cpp
src/geo/GModelIO_TOCHNOG.cpp
src/geo/GModelIO_UNV.cpp
src/geo/GModelIO_VRML.cpp
src/geo/GModelIO_VTK.cpp
src/geo/GModelIO_X3D.cpp
src/geo/GModelVertexArrays.cpp