gmsh-TingyuanDoc: nodMap< T > Class Template Reference
nodMap< T > Class Template Reference
#include <adaptiveData.h>
Public Member Functions
void cleanMapping ()
~nodMap ()
int getSize ()
Public Attributes
std::vector< int > mapping
Detailed Description
template<class T>
class nodMap< T >
Definition at line 68 of file adaptiveData.h.
Constructor & Destructor Documentation
~nodMap()
template<class T > nodMap< T >::~nodMap () inline
Definition at line 74 of file adaptiveData.h.
Member Function Documentation
cleanMapping()
template<class T > void nodMap< T >::cleanMapping () inline
Definition at line 73 of file adaptiveData.h.
Referenced by adaptiveElements< T >::buildMapping(), and nodMap< T >::~nodMap().
getSize()
template<class T > int nodMap< T >::getSize () inline
Definition at line 75 of file adaptiveData.h.
Referenced by adaptiveElements< T >::buildMapping().
Member Data Documentation
mapping
template<class T > std::vector<int> nodMap< T >::mapping
Definition at line 70 of file adaptiveData.h.
Referenced by adaptiveElements< T >::addInViewForVTK(), adaptiveElements< T >::buildMapping(), nodMap< T >::cleanMapping(), and nodMap< T >::getSize().
The documentation for this class was generated from the following file:
src/post/adaptiveData.h