gmsh-TingyuanDoc: OCC_Internals Class Reference
OCC_Internals Class Reference
#include <GModelIO_OCC.h>
Public Types
enum BooleanOperator {
Union, Intersection, Difference, Section,
Fragments
}
Public Member Functions
OCC_Internals ()
bool getChanged () const
void reset ()
void setMaxTag (int dim, int val)
int getMaxTag (int dim) const
bool addVertex (int &tag, double x, double y, double z, double meshSize=MAX_LC)
bool addLine (int &tag, int startTag, int endTag)
bool addLine (int &tag, const std::vector< int > &pointTags)
bool addCircleArc (int &tag, int startTag, int centerTag, int endTag)
bool addCircle (int &tag, double x, double y, double z, double r, double angle1, double angle2, const std::vector< double > &N=std::vector< double >(), const std::vector< double > &V=std::vector< double >())
bool addEllipseArc (int &tag, int startTag, int centerTag, int majorTag, int endTag)
bool addEllipse (int &tag, double x, double y, double z, double r1, double r2, double angle1, double angle2, const std::vector< double > &N=std::vector< double >(), const std::vector< double > &V=std::vector< double >())
bool addSpline (int &tag, const std::vector< int > &pointTags, const std::vector< SVector3 > &tangents=std::vector< SVector3 >())
bool addBezier (int &tag, const std::vector< int > &pointTags)
bool addBSpline (int &tag, const std::vector< int > &pointTags, const int degree=-1, const std::vector< double > &weights=std::vector< double >(), const std::vector< double > &knots=std::vector< double >(), const std::vector< int > &multiplicities=std::vector< int >())
bool addWire (int &tag, const std::vector< int > &curveTags, bool closed)
bool addCurveLoop (int &tag, const std::vector< int > &curveTags)
bool addRectangle (int &tag, double x, double y, double z, double dx, double dy, double roundedRadius=0.)
bool addDisk (int &tag, double xc, double yc, double zc, double rx, double ry, const std::vector< double > &N=std::vector< double >(), const std::vector< double > &V=std::vector< double >())
bool addPlaneSurface (int &tag, const std::vector< int > &wireTags)
bool addSurfaceFilling (int &tag, int wireTag, const std::vector< int > &pointTags=std::vector< int >(), const std::vector< int > &surfaceTags=std::vector< int >(), const std::vector< int > &surfaceContinuity=std::vector< int >(), const int degree=2, const int numPointsOnCurves=15, const int numIter=2, const bool anisotropic=false, const double tol2d=0.00001, const double tol3d=0.0001, const double tolAng=0.01, const double tolCurv=0.1, const int maxDegree=8, const int maxSegments=9)
bool addBSplineFilling (int &tag, int wireTag, const std::string &type="")
bool addBezierFilling (int &tag, int wireTag, const std::string &type="")
bool addBSplineSurface (int &tag, const std::vector< int > &pointTags, const int numPointsU, const int degreeU, const int degreeV, const std::vector< double > &weights, const std::vector< double > &knotsU, const std::vector< double > &knotsV, const std::vector< int > &multiplicitiesU, const std::vector< int > &multiplicitiesV, const std::vector< int > &wireTags=std::vector< int >(), bool wire3D=true)
bool addBezierSurface (int &tag, const std::vector< int > &pointTags, const int numPointsU, const std::vector< int > &wireTags=std::vector< int >(), bool wire3D=true)
bool addTrimmedSurface (int &tag, int surfaceTag, const std::vector< int > &wireTags, bool wire3D)
bool addSurfaceLoop (int &tag, const std::vector< int > &surfaceTags, bool sewing)
bool addVolume (int &tag, const std::vector< int > &shellTags)
bool addSphere (int &tag, double xc, double yc, double zc, double radius, double angle1, double angle2, double angle3)
bool addBox (int &tag, double x, double y, double z, double dx, double dy, double dz)
bool addCylinder (int &tag, double x, double y, double z, double dx, double dy, double dz, double r, double angle)
bool addCone (int &tag, double x, double y, double z, double dx, double dy, double dz, double r1, double r2, double angle)
bool addWedge (int &tag, double x, double y, double z, double dx, double dy, double dz, double ltx, const std::vector< double > &N=std::vector< double >())
bool addTorus (int &tag, double x, double y, double z, double r1, double r2, double angle, const std::vector< double > &N=std::vector< double >())
bool addThruSections (int tag, const std::vector< int > &wireTags, bool makeSolid, bool makeRuled, std::vector< std::pair< int, int > > &outDimTags, int maxDegree=-1, const std::string &continuity="", const std::string &parametrization="", bool smoothing=false)
bool addThickSolid (int tag, int solidTag, const std::vector< int > &excludeFaceTags, double offset, std::vector< std::pair< int, int > > &outDimTags)
bool extrude (const std::vector< std::pair< int, int > > &inDimTags, double dx, double dy, double dz, std::vector< std::pair< int, int > > &outDimTags, ExtrudeParams *e=0)
bool revolve (const std::vector< std::pair< int, int > > &inDimTags, double x, double y, double z, double ax, double ay, double az, double angle, std::vector< std::pair< int, int > > &outDimTags, ExtrudeParams *e=0)
bool addPipe (const std::vector< std::pair< int, int > > &inDimTags, int wireTag, std::vector< std::pair< int, int > > &outDimTags, const std::string &trihedron="")
bool fillet (const std::vector< int > &volumeTags, const std::vector< int > &curveTags, const std::vector< double > &radii, std::vector< std::pair< int, int > > &outDimTags, bool removeVolume)
bool chamfer (const std::vector< int > &volumeTags, const std::vector< int > &curveTags, const std::vector< int > &surfaceTags, const std::vector< double > &distances, std::vector< std::pair< int, int > > &outDimTags, bool removeVolume)
bool booleanOperator (int tag, BooleanOperator op, const std::vector< std::pair< int, int > > &objectDimTags, const std::vector< std::pair< int, int > > &toolDimTags, std::vector< std::pair< int, int > > &outDimTags, std::vector< std::vector< std::pair< int, int > > > &outDimTagsMap, bool removeObject, bool removeTool)
bool booleanUnion (int tag, const std::vector< std::pair< int, int > > &objectDimTags, const std::vector< std::pair< int, int > > &toolDimTags, std::vector< std::pair< int, int > > &outDimTags, std::vector< std::vector< std::pair< int, int > > > &outDimTagsMap, bool removeObject, bool removeTool)
bool booleanIntersection (int tag, const std::vector< std::pair< int, int > > &objectDimTags, const std::vector< std::pair< int, int > > &toolDimTags, std::vector< std::pair< int, int > > &outDimTags, std::vector< std::vector< std::pair< int, int > > > &outDimTagsMap, bool removeObject, bool removeTool)
bool booleanDifference (int tag, const std::vector< std::pair< int, int > > &objectDimTags, const std::vector< std::pair< int, int > > &toolDimTags, std::vector< std::pair< int, int > > &outDimTags, std::vector< std::vector< std::pair< int, int > > > &outDimTagsMap, bool removeObject, bool removeTool)
bool booleanFragments (int tag, const std::vector< std::pair< int, int > > &objectDimTags, const std::vector< std::pair< int, int > > &toolDimTags, std::vector< std::pair< int, int > > &outDimTags, std::vector< std::vector< std::pair< int, int > > > &outDimTagsMap, bool removeObject, bool removeTool)
void removeAllDuplicates ()
bool mergeVertices (const std::vector< int > &tags)
bool translate (const std::vector< std::pair< int, int > > &inDimTags, double dx, double dy, double dz)
bool rotate (const std::vector< std::pair< int, int > > &inDimTags, double x, double y, double z, double ax, double ay, double az, double angle)
bool dilate (const std::vector< std::pair< int, int > > &inDimTags, double x, double y, double z, double a, double b, double c)
bool symmetry (const std::vector< std::pair< int, int > > &inDimTags, double a, double b, double c, double d)
bool affine (const std::vector< std::pair< int, int > > &inDimTags, const std::vector< double > &mat)
bool copy (const std::vector< std::pair< int, int > > &inDimTags, std::vector< std::pair< int, int > > &outDimTags)
bool remove (int dim, int tag, bool recursive=false)
bool remove (const std::vector< std::pair< int, int > > &dimTags, bool recursive=false)
bool importShapes (const std::string &fileName, bool highestDimOnly, std::vector< std::pair< int, int > > &outDimTags, const std::string &format="")
bool healShapes (const std::vector< std::pair< int, int > > &inDimTags, std::vector< std::pair< int, int > > &outDimTags, double tolerance, bool fixDegenerated, bool fixSmallEdges, bool fixSmallFaces, bool sewFaces, bool makeSolids)
bool convertToNURBS (const std::vector< std::pair< int, int > > &dimTags)
void setMeshSize (int dim, int tag, double size)
void synchronize (GModel *model)
bool exportShapes (GModel *model, const std::string &fileName, const std::string &format="", bool onlyVisible=false)
bool getEntities (std::vector< std::pair< int, int > > &dimTags, int dim)
bool getVertex (int tag, double &x, double &y, double &z)
bool getBoundingBox (int dim, int tag, double &xmin, double &ymin, double &zmin, double &xmax, double &ymax, double &zmax)
bool getEntitiesInBoundingBox (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, std::vector< std::pair< int, int > > &dimTags, int dim)
bool getCurveLoops (int surfaceTag, std::vector< int > &curveLoopTags, std::vector< std::vector< int > > &curveTags)
bool getSurfaceLoops (int volumeTag, std::vector< int > &surfaceLoopTags, std::vector< std::vector< int > > &surfaceTags)
bool getMass (int dim, int tag, double &mass)
bool getCenterOfMass (int dim, int tag, double &x, double &y, double &z)
bool getMatrixOfInertia (int dim, int tag, std::vector< double > &mat)
double getDistance (int dim1, int tag1, int dim2, int tag2, double &x1, double &y1, double &z1, double &x2, double &y2, double &z2)
bool makeRectangleSTL (double x, double y, double z, double dx, double dy, double roundedRadius, std::vector< SPoint3 > &vertices, std::vector< SVector3 > &normals, std::vector< int > &triangles)
bool makeDiskSTL (double xc, double yc, double zc, double rx, double ry, std::vector< SPoint3 > &vertices, std::vector< SVector3 > &normals, std::vector< int > &triangles)
bool makeSphereSTL (double xc, double yc, double zc, double radius, double angle1, double angle2, double angle3, std::vector< SPoint3 > &vertices, std::vector< SVector3 > &normals, std::vector< int > &triangles)
bool makeBoxSTL (double x, double y, double z, double dx, double dy, double dz, std::vector< SPoint3 > &vertices, std::vector< SVector3 > &normals, std::vector< int > &triangles)
bool makeCylinderSTL (double x, double y, double z, double dx, double dy, double dz, double r, double angle, std::vector< SPoint3 > &vertices, std::vector< SVector3 > &normals, std::vector< int > &triangles)
bool makeConeSTL (double x, double y, double z, double dx, double dy, double dz, double r1, double r2, double angle, std::vector< SPoint3 > &vertices, std::vector< SVector3 > &normals, std::vector< int > &triangles)
bool makeWedgeSTL (double x, double y, double z, double dx, double dy, double dz, double ltx, std::vector< SPoint3 > &vertices, std::vector< SVector3 > &normals, std::vector< int > &triangles)
bool makeTorusSTL (double x, double y, double z, double r1, double r2, double angle, std::vector< SPoint3 > &vertices, std::vector< SVector3 > &normals, std::vector< int > &triangles)
Private Member Functions
bool _error (std::string what)
Detailed Description
Definition at line 471 of file GModelIO_OCC.h.
Member Enumeration Documentation
BooleanOperator
enum OCC_Internals::BooleanOperator
Enumerator
Union
Intersection
Difference
Section
Fragments
Definition at line 480 of file GModelIO_OCC.h.
Constructor & Destructor Documentation
OCC_Internals()
OCC_Internals::OCC_Internals () inline
Definition at line 481 of file GModelIO_OCC.h.
Member Function Documentation
_error()
bool OCC_Internals::_error (std::string what) inline private
Definition at line 473 of file GModelIO_OCC.h.
Referenced by addBezier(), addBezierFilling(), addBezierSurface(), addBox(), addBSpline(), addBSplineFilling(), addBSplineSurface(), addCircle(), addCircleArc(), addCone(), addCurveLoop(), addCylinder(), addDisk(), addEllipse(), addEllipseArc(), addLine(), addPipe(), addPlaneSurface(), addRectangle(), addSphere(), addSpline(), addSurfaceFilling(), addSurfaceLoop(), addThickSolid(), addThruSections(), addTorus(), addTrimmedSurface(), addVertex(), addVolume(), addWedge(), addWire(), affine(), booleanDifference(), booleanFragments(), booleanIntersection(), booleanOperator(), booleanUnion(), chamfer(), convertToNURBS(), copy(), dilate(), exportShapes(), extrude(), fillet(), healShapes(), importShapes(), mergeVertices(), removeAllDuplicates(), revolve(), rotate(), symmetry(), and translate().
addBezier()
bool OCC_Internals::addBezier (int & tag, const std::vector< int > & pointTags) inline
Definition at line 527 of file GModelIO_OCC.h.
addBezierFilling()
bool OCC_Internals::addBezierFilling (int & tag, int wireTag, const std::string & type = "") inline
Definition at line 579 of file GModelIO_OCC.h.
addBezierSurface()
bool OCC_Internals::addBezierSurface (int & tag, const std::vector< int > & pointTags, const int numPointsU, const std::vector< int > & wireTags = std::vector<int>(), bool wire3D = true) inline
Definition at line 595 of file GModelIO_OCC.h.
addBox()
bool OCC_Internals::addBox (int & tag, double x, double y, double z, double dx, double dy, double dz) inline
Definition at line 621 of file GModelIO_OCC.h.
addBSpline()
bool OCC_Internals::addBSpline (int & tag, const std::vector< int > & pointTags, const int degree = -1, const std::vector< double > & weights = std::vector<double>(), const std::vector< double > & knots = std::vector<double>(), const std::vector< int > & multiplicities = std::vector<int>()) inline
Definition at line 531 of file GModelIO_OCC.h.
addBSplineFilling()
bool OCC_Internals::addBSplineFilling (int & tag, int wireTag, const std::string & type = "") inline
Definition at line 575 of file GModelIO_OCC.h.
addBSplineSurface()
bool OCC_Internals::addBSplineSurface (int & tag, const std::vector< int > & pointTags, const int numPointsU, const int degreeU, const int degreeV, const std::vector< double > & weights, const std::vector< double > & knotsU, const std::vector< double > & knotsV, const std::vector< int > & multiplicitiesU, const std::vector< int > & multiplicitiesV, const std::vector< int > & wireTags = std::vector<int>(), bool wire3D = true) inline
Definition at line 583 of file GModelIO_OCC.h.
addCircle()
bool OCC_Internals::addCircle (int & tag, double x, double y, double z, double r, double angle1, double angle2, const std::vector< double > & N = std::vector<double>(), const std::vector< double > & V = std::vector<double>()) inline
Definition at line 503 of file GModelIO_OCC.h.
addCircleArc()
bool OCC_Internals::addCircleArc (int & tag, int startTag, int centerTag, int endTag) inline
Definition at line 499 of file GModelIO_OCC.h.
addCone()
bool OCC_Internals::addCone (int & tag, double x, double y, double z, double dx, double dy, double dz, double r1, double r2, double angle) inline
Definition at line 631 of file GModelIO_OCC.h.
addCurveLoop()
bool OCC_Internals::addCurveLoop (int & tag, const std::vector< int > & curveTags) inline
Definition at line 543 of file GModelIO_OCC.h.
addCylinder()
bool OCC_Internals::addCylinder (int & tag, double x, double y, double z, double dx, double dy, double dz, double r, double angle) inline
Definition at line 626 of file GModelIO_OCC.h.
addDisk()
bool OCC_Internals::addDisk (int & tag, double xc, double yc, double zc, double rx, double ry, const std::vector< double > & N = std::vector<double>(), const std::vector< double > & V = std::vector<double>()) inline
Definition at line 552 of file GModelIO_OCC.h.
addEllipse()
bool OCC_Internals::addEllipse (int & tag, double x, double y, double z, double r1, double r2, double angle1, double angle2, const std::vector< double > & N = std::vector<double>(), const std::vector< double > & V = std::vector<double>()) inline
Definition at line 515 of file GModelIO_OCC.h.
addEllipseArc()
bool OCC_Internals::addEllipseArc (int & tag, int startTag, int centerTag, int majorTag, int endTag) inline
Definition at line 510 of file GModelIO_OCC.h.
addLine() [1/2]
bool OCC_Internals::addLine (int & tag, const std::vector< int > & pointTags) inline
Definition at line 495 of file GModelIO_OCC.h.
addLine() [2/2]
bool OCC_Internals::addLine (int & tag, int startTag, int endTag) inline
Definition at line 491 of file GModelIO_OCC.h.
addPipe()
bool OCC_Internals::addPipe (const std::vector< std::pair< int, int > > & inDimTags, int wireTag, std::vector< std::pair< int, int > > & outDimTags, const std::string & trihedron = "") inline
Definition at line 677 of file GModelIO_OCC.h.
addPlaneSurface()
bool OCC_Internals::addPlaneSurface (int & tag, const std::vector< int > & wireTags) inline
Definition at line 558 of file GModelIO_OCC.h.
addRectangle()
bool OCC_Internals::addRectangle (int & tag, double x, double y, double z, double dx, double dy, double roundedRadius = 0.) inline
Definition at line 547 of file GModelIO_OCC.h.
addSphere()
bool OCC_Internals::addSphere (int & tag, double xc, double yc, double zc, double radius, double angle1, double angle2, double angle3) inline
Definition at line 616 of file GModelIO_OCC.h.
addSpline()
bool OCC_Internals::addSpline (int & tag, const std::vector< int > & pointTags, const std::vector< SVector3 > & tangents = std::vector<SVector3>()) inline
Definition at line 522 of file GModelIO_OCC.h.
addSurfaceFilling()
bool OCC_Internals::addSurfaceFilling (int & tag, int wireTag, const std::vector< int > & pointTags = std::vector<int>(), const std::vector< int > & surfaceTags = std::vector<int>(), const std::vector< int > & surfaceContinuity = std::vector<int>(), const int degree = 2, const int numPointsOnCurves = 15, const int numIter = 2, const bool anisotropic = false, const double tol2d = 0.00001, const double tol3d = 0.0001, const double tolAng = 0.01, const double tolCurv = 0.1, const int maxDegree = 8, const int maxSegments = 9) inline
Definition at line 562 of file GModelIO_OCC.h.
addSurfaceLoop()
bool OCC_Internals::addSurfaceLoop (int & tag, const std::vector< int > & surfaceTags, bool sewing) inline
Definition at line 607 of file GModelIO_OCC.h.
addThickSolid()
bool OCC_Internals::addThickSolid (int tag, int solidTag, const std::vector< int > & excludeFaceTags, double offset, std::vector< std::pair< int, int > > & outDimTags) inline
Definition at line 657 of file GModelIO_OCC.h.
addThruSections()
bool OCC_Internals::addThruSections (int tag, const std::vector< int > & wireTags, bool makeSolid, bool makeRuled, std::vector< std::pair< int, int > > & outDimTags, int maxDegree = -1, const std::string & continuity = "", const std::string & parametrization = "", bool smoothing = false) inline
Definition at line 648 of file GModelIO_OCC.h.
addTorus()
bool OCC_Internals::addTorus (int & tag, double x, double y, double z, double r1, double r2, double angle, const std::vector< double > & N = std::vector<double>()) inline
Definition at line 642 of file GModelIO_OCC.h.
addTrimmedSurface()
bool OCC_Internals::addTrimmedSurface (int & tag, int surfaceTag, const std::vector< int > & wireTags, bool wire3D) inline
Definition at line 602 of file GModelIO_OCC.h.
addVertex()
bool OCC_Internals::addVertex (int & tag, double x, double y, double z, double meshSize = MAX_LC) inline
Definition at line 486 of file GModelIO_OCC.h.
addVolume()
bool OCC_Internals::addVolume (int & tag, const std::vector< int > & shellTags) inline
Definition at line 612 of file GModelIO_OCC.h.
addWedge()
bool OCC_Internals::addWedge (int & tag, double x, double y, double z, double dx, double dy, double dz, double ltx, const std::vector< double > & N = std::vector<double>()) inline
Definition at line 636 of file GModelIO_OCC.h.
addWire()
bool OCC_Internals::addWire (int & tag, const std::vector< int > & curveTags, bool closed) inline
Definition at line 539 of file GModelIO_OCC.h.
affine()
bool OCC_Internals::affine (const std::vector< std::pair< int, int > > & inDimTags, const std::vector< double > & mat) inline
Definition at line 769 of file GModelIO_OCC.h.
booleanDifference()
bool OCC_Internals::booleanDifference (int tag, const std::vector< std::pair< int, int > > & objectDimTags, const std::vector< std::pair< int, int > > & toolDimTags, std::vector< std::pair< int, int > > & outDimTags, std::vector< std::vector< std::pair< int, int > > > & outDimTagsMap, bool removeObject, bool removeTool) inline
Definition at line 726 of file GModelIO_OCC.h.
booleanFragments()
bool OCC_Internals::booleanFragments (int tag, const std::vector< std::pair< int, int > > & objectDimTags, const std::vector< std::pair< int, int > > & toolDimTags, std::vector< std::pair< int, int > > & outDimTags, std::vector< std::vector< std::pair< int, int > > > & outDimTagsMap, bool removeObject, bool removeTool) inline
Definition at line 735 of file GModelIO_OCC.h.
booleanIntersection()
bool OCC_Internals::booleanIntersection (int tag, const std::vector< std::pair< int, int > > & objectDimTags, const std::vector< std::pair< int, int > > & toolDimTags, std::vector< std::pair< int, int > > & outDimTags, std::vector< std::vector< std::pair< int, int > > > & outDimTagsMap, bool removeObject, bool removeTool) inline
Definition at line 717 of file GModelIO_OCC.h.
booleanOperator()
bool OCC_Internals::booleanOperator (int tag, BooleanOperator op, const std::vector< std::pair< int, int > > & objectDimTags, const std::vector< std::pair< int, int > > & toolDimTags, std::vector< std::pair< int, int > > & outDimTags, std::vector< std::vector< std::pair< int, int > > > & outDimTagsMap, bool removeObject, bool removeTool) inline
Definition at line 698 of file GModelIO_OCC.h.
booleanUnion()
bool OCC_Internals::booleanUnion (int tag, const std::vector< std::pair< int, int > > & objectDimTags, const std::vector< std::pair< int, int > > & toolDimTags, std::vector< std::pair< int, int > > & outDimTags, std::vector< std::vector< std::pair< int, int > > > & outDimTagsMap, bool removeObject, bool removeTool) inline
Definition at line 709 of file GModelIO_OCC.h.
chamfer()
bool OCC_Internals::chamfer (const std::vector< int > & volumeTags, const std::vector< int > & curveTags, const std::vector< int > & surfaceTags, const std::vector< double > & distances, std::vector< std::pair< int, int > > & outDimTags, bool removeVolume) inline
Definition at line 690 of file GModelIO_OCC.h.
convertToNURBS()
bool OCC_Internals::convertToNURBS (const std::vector< std::pair< int, int > > & dimTags) inline
Definition at line 798 of file GModelIO_OCC.h.
copy()
bool OCC_Internals::copy (const std::vector< std::pair< int, int > > & inDimTags, std::vector< std::pair< int, int > > & outDimTags) inline
Definition at line 774 of file GModelIO_OCC.h.
dilate()
bool OCC_Internals::dilate (const std::vector< std::pair< int, int > > & inDimTags, double x, double y, double z, double a, double b, double c) inline
Definition at line 759 of file GModelIO_OCC.h.
exportShapes()
bool OCC_Internals::exportShapes (GModel * model, const std::string & fileName, const std::string & format = "", bool onlyVisible = false) inline
Definition at line 804 of file GModelIO_OCC.h.
Referenced by GModel::writeOCCBREP(), and GModel::writeOCCSTEP().
extrude()
bool OCC_Internals::extrude (const std::vector< std::pair< int, int > > & inDimTags, double dx, double dy, double dz, std::vector< std::pair< int, int > > & outDimTags, ExtrudeParams * e = 0) inline
Definition at line 663 of file GModelIO_OCC.h.
fillet()
bool OCC_Internals::fillet (const std::vector< int > & volumeTags, const std::vector< int > & curveTags, const std::vector< double > & radii, std::vector< std::pair< int, int > > & outDimTags, bool removeVolume) inline
Definition at line 683 of file GModelIO_OCC.h.
getBoundingBox()
bool OCC_Internals::getBoundingBox (int dim, int tag, double & xmin, double & ymin, double & zmin, double & xmax, double & ymax, double & zmax) inline
Definition at line 814 of file GModelIO_OCC.h.
getCenterOfMass()
bool OCC_Internals::getCenterOfMass (int dim, int tag, double & x, double & y, double & z) inline
Definition at line 837 of file GModelIO_OCC.h.
getChanged()
bool OCC_Internals::getChanged () const inline
Definition at line 482 of file GModelIO_OCC.h.
getCurveLoops()
bool OCC_Internals::getCurveLoops (int surfaceTag, std::vector< int > & curveLoopTags, std::vector< std::vector< int > > & curveTags) inline
Definition at line 826 of file GModelIO_OCC.h.
getDistance()
double OCC_Internals::getDistance (int dim1, int tag1, int dim2, int tag2, double & x1, double & y1, double & z1, double & x2, double & y2, double & z2) inline
Definition at line 845 of file GModelIO_OCC.h.
getEntities()
bool OCC_Internals::getEntities (std::vector< std::pair< int, int > > & dimTags, int dim) inline
Definition at line 809 of file GModelIO_OCC.h.
getEntitiesInBoundingBox()
bool OCC_Internals::getEntitiesInBoundingBox (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, std::vector< std::pair< int, int > > & dimTags, int dim) inline
Definition at line 819 of file GModelIO_OCC.h.
getMass()
bool OCC_Internals::getMass (int dim, int tag, double & mass) inline
Definition at line 836 of file GModelIO_OCC.h.
getMatrixOfInertia()
bool OCC_Internals::getMatrixOfInertia (int dim, int tag, std::vector< double > & mat) inline
Definition at line 841 of file GModelIO_OCC.h.
getMaxTag()
int OCC_Internals::getMaxTag (int dim) const inline
Definition at line 485 of file GModelIO_OCC.h.
getSurfaceLoops()
bool OCC_Internals::getSurfaceLoops (int volumeTag, std::vector< int > & surfaceLoopTags, std::vector< std::vector< int > > & surfaceTags) inline
Definition at line 831 of file GModelIO_OCC.h.
getVertex()
bool OCC_Internals::getVertex (int tag, double & x, double & y, double & z) inline
Definition at line 813 of file GModelIO_OCC.h.
healShapes()
bool OCC_Internals::healShapes (const std::vector< std::pair< int, int > > & inDimTags, std::vector< std::pair< int, int > > & outDimTags, double tolerance, bool fixDegenerated, bool fixSmallEdges, bool fixSmallFaces, bool sewFaces, bool makeSolids) inline
Definition at line 791 of file GModelIO_OCC.h.
importShapes()
bool OCC_Internals::importShapes (const std::string & fileName, bool highestDimOnly, std::vector< std::pair< int, int > > & outDimTags, const std::string & format = "") inline
Definition at line 785 of file GModelIO_OCC.h.
Referenced by GModel::importOCCShape(), GModel::readOCCBREP(), GModel::readOCCIGES(), and GModel::readOCCSTEP().
makeBoxSTL()
bool OCC_Internals::makeBoxSTL (double x, double y, double z, double dx, double dy, double dz, std::vector< SPoint3 > & vertices, std::vector< SVector3 > & normals, std::vector< int > & triangles) inline
Definition at line 873 of file GModelIO_OCC.h.
makeConeSTL()
bool OCC_Internals::makeConeSTL (double x, double y, double z, double dx, double dy, double dz, double r1, double r2, double angle, std::vector< SPoint3 > & vertices, std::vector< SVector3 > & normals, std::vector< int > & triangles) inline
Definition at line 887 of file GModelIO_OCC.h.
makeCylinderSTL()
bool OCC_Internals::makeCylinderSTL (double x, double y, double z, double dx, double dy, double dz, double r, double angle, std::vector< SPoint3 > & vertices, std::vector< SVector3 > & normals, std::vector< int > & triangles) inline
Definition at line 879 of file GModelIO_OCC.h.
makeDiskSTL()
bool OCC_Internals::makeDiskSTL (double xc, double yc, double zc, double rx, double ry, std::vector< SPoint3 > & vertices, std::vector< SVector3 > & normals, std::vector< int > & triangles) inline
Definition at line 859 of file GModelIO_OCC.h.
makeRectangleSTL()
bool OCC_Internals::makeRectangleSTL (double x, double y, double z, double dx, double dy, double roundedRadius, std::vector< SPoint3 > & vertices, std::vector< SVector3 > & normals, std::vector< int > & triangles) inline
Definition at line 852 of file GModelIO_OCC.h.
makeSphereSTL()
bool OCC_Internals::makeSphereSTL (double xc, double yc, double zc, double radius, double angle1, double angle2, double angle3, std::vector< SPoint3 > & vertices, std::vector< SVector3 > & normals, std::vector< int > & triangles) inline
Definition at line 865 of file GModelIO_OCC.h.
makeTorusSTL()
bool OCC_Internals::makeTorusSTL (double x, double y, double z, double r1, double r2, double angle, std::vector< SPoint3 > & vertices, std::vector< SVector3 > & normals, std::vector< int > & triangles) inline
Definition at line 900 of file GModelIO_OCC.h.
makeWedgeSTL()
bool OCC_Internals::makeWedgeSTL (double x, double y, double z, double dx, double dy, double dz, double ltx, std::vector< SPoint3 > & vertices, std::vector< SVector3 > & normals, std::vector< int > & triangles) inline
Definition at line 894 of file GModelIO_OCC.h.
mergeVertices()
bool OCC_Internals::mergeVertices (const std::vector< int > & tags) inline
Definition at line 745 of file GModelIO_OCC.h.
remove() [1/2]
bool OCC_Internals::remove (const std::vector< std::pair< int, int > > & dimTags, bool recursive = false) inline
Definition at line 780 of file GModelIO_OCC.h.
remove() [2/2]
bool OCC_Internals::remove (int dim, int tag, bool recursive = false) inline
Definition at line 779 of file GModelIO_OCC.h.
removeAllDuplicates()
void OCC_Internals::removeAllDuplicates () inline
Definition at line 744 of file GModelIO_OCC.h.
reset()
void OCC_Internals::reset () inline
Definition at line 483 of file GModelIO_OCC.h.
Referenced by GModel::resetOCCInternals().
revolve()
bool OCC_Internals::revolve (const std::vector< std::pair< int, int > > & inDimTags, double x, double y, double z, double ax, double ay, double az, double angle, std::vector< std::pair< int, int > > & outDimTags, ExtrudeParams * e = 0) inline
Definition at line 670 of file GModelIO_OCC.h.
rotate()
bool OCC_Internals::rotate (const std::vector< std::pair< int, int > > & inDimTags, double x, double y, double z, double ax, double ay, double az, double angle) inline
Definition at line 754 of file GModelIO_OCC.h.
setMaxTag()
void OCC_Internals::setMaxTag (int dim, int val) inline
Definition at line 484 of file GModelIO_OCC.h.
setMeshSize()
void OCC_Internals::setMeshSize (int dim, int tag, double size) inline
Definition at line 802 of file GModelIO_OCC.h.
symmetry()
bool OCC_Internals::symmetry (const std::vector< std::pair< int, int > > & inDimTags, double a, double b, double c, double d) inline
Definition at line 764 of file GModelIO_OCC.h.
synchronize()
void OCC_Internals::synchronize (GModel * model) inline
Definition at line 803 of file GModelIO_OCC.h.
Referenced by addEmbedded(), addPeriodicEdge(), addPeriodicFace(), getAllElementaryTags(), getAllPhysicalTags(), getBoundingBox(), getElementaryTagsForPhysicalGroups(), getElementaryTagsInBoundingBox(), getParentTags(), GModel::importOCCShape(), GModel::readGEO(), GModel::readOCCBREP(), GModel::readOCCIGES(), GModel::readOCCSTEP(), removeEmbedded(), scriptAddCommand(), setColor(), and setVisibility().
translate()
bool OCC_Internals::translate (const std::vector< std::pair< int, int > > & inDimTags, double dx, double dy, double dz) inline
Definition at line 749 of file GModelIO_OCC.h.
The documentation for this class was generated from the following file:
src/geo/GModelIO_OCC.h