gmsh-TingyuanDoc: initPView Class Reference
initPView Class Reference
Public Member Functions
bool operator() (PView *p)
Private Member Functions
int _estimateIfClipped (PView *p, int num)
int _estimateNumPoints (PView *p)
int _estimateNumLines (PView *p)
int _estimateNumTriangles (PView *p)
int _estimateNumVectors (PView *p)
int _estimateNumEllipses (PView *p)
Detailed Description
Definition at line 1422 of file PViewVertexArrays.cpp.
Member Function Documentation
_estimateIfClipped()
int initPView::_estimateIfClipped (PView * p, int num) inline private
Definition at line 1427 of file PViewVertexArrays.cpp.
Referenced by _estimateNumEllipses(), _estimateNumTriangles(), and _estimateNumVectors().
_estimateNumEllipses()
int initPView::_estimateNumEllipses (PView * p) inline private
Definition at line 1486 of file PViewVertexArrays.cpp.
Referenced by operator()().
_estimateNumLines()
int initPView::_estimateNumLines (PView * p) inline private
Definition at line 1445 of file PViewVertexArrays.cpp.
Referenced by operator()().
_estimateNumPoints()
int initPView::_estimateNumPoints (PView * p) inline private
Definition at line 1438 of file PViewVertexArrays.cpp.
Referenced by operator()().
_estimateNumTriangles()
int initPView::_estimateNumTriangles (PView * p) inline private
Definition at line 1452 of file PViewVertexArrays.cpp.
Referenced by operator()().
_estimateNumVectors()
int initPView::_estimateNumVectors (PView * p) inline private
Definition at line 1478 of file PViewVertexArrays.cpp.
Referenced by operator()().
operator()()
bool initPView::operator() (PView * p) inline
Definition at line 1496 of file PViewVertexArrays.cpp.
The documentation for this class was generated from the following file:
src/post/PViewVertexArrays.cpp