gmsh-TingyuanDoc: onelab::server Class Reference
onelab::server Class Reference
#include <onelab.h>
Public Types
typedef std::set< client * >::iterator citer
Public Member Functions
server (const std::string &address="")
~server ()
void clear (const std::string &name="", const std::string &client="")
template<class T >
bool set (const T &p, const std::string &client="")
template<class T >
bool get (std::vector< T > &ps, const std::string &name="", const std::string &client="")
citer firstClient ()
citer lastClient ()
int getNumClients ()
citer findClient (const std::string &name)
void registerClient (client *c)
void unregisterClient (client *c)
void setChanged (int changed, const std::string &client="")
int getChanged (const std::string &client="")
void thresholdChanged (int value, const std::string &client="")
int getNumParameters ()
void getParameterNames (std::vector< std::string > &names, const std::string &search="") const
std::vector< std::string > toChar (const std::string &client="")
bool fromChar (const std::vector< std::string > &msg, const std::string &client="")
bool toFile (FILE *fp, const std::string &client="")
bool fromFile (FILE *fp, const std::string &client="")
bool toJSON (std::string &json, const std::string &client="")
bool fromJSON (const std::string &json, const std::string &client="")
Static Public Member Functions
static server * instance (const std::string &address="")
static void setInstance (server *s)
Private Attributes
std::string _address
std::set< client * > _clients
parameterSpace _parameterSpace
Static Private Attributes
static server * _server
Detailed Description
Definition at line 1295 of file onelab.h.
Member Typedef Documentation
citer
typedef std::set<client *>::iterator onelab::server::citer
Definition at line 1329 of file onelab.h.
Constructor & Destructor Documentation
server()
onelab::server::server (const std::string & address = "") inline
Definition at line 1307 of file onelab.h.
Referenced by instance().
~server()
onelab::server::~server () inline
Definition at line 1308 of file onelab.h.
Member Function Documentation
clear()
void onelab::server::clear (const std::string & name = "", const std::string & client = "") inline
Definition at line 1315 of file onelab.h.
Referenced by onelab::localClient::clear().
findClient()
citer onelab::server::findClient (const std::string & name) inline
Definition at line 1333 of file onelab.h.
firstClient()
citer onelab::server::firstClient () inline
Definition at line 1330 of file onelab.h.
fromChar()
bool onelab::server::fromChar (const std::vector< std::string > & msg, const std::string & client = "") inline
Definition at line 1367 of file onelab.h.
Referenced by fromFile().
fromFile()
bool onelab::server::fromFile (FILE * fp, const std::string & client = "") inline
Definition at line 1376 of file onelab.h.
fromJSON()
bool onelab::server::fromJSON (const std::string & json, const std::string & client = "") inline
Definition at line 1386 of file onelab.h.
get()
template<class T > bool onelab::server::get (std::vector< T > & ps, const std::string & name = "", const std::string & client = "") inline
Definition at line 1324 of file onelab.h.
Referenced by onelab::localClient::_get().
getChanged()
int onelab::server::getChanged (const std::string & client = "") inline
Definition at line 1349 of file onelab.h.
getNumClients()
int onelab::server::getNumClients () inline
Definition at line 1332 of file onelab.h.
Referenced by Msg::GetNumOnelabClients().
getNumParameters()
int onelab::server::getNumParameters () inline
Definition at line 1357 of file onelab.h.
getParameterNames()
void onelab::server::getParameterNames (std::vector< std::string > & names, const std::string & search = "") const inline
Definition at line 1358 of file onelab.h.
instance()
static server* onelab::server::instance (const std::string & address = "") inline static
Definition at line 1309 of file onelab.h.
Referenced by onelab::localClient::_get(), onelab::localClient::_set(), onelab::localClient::clear(), Msg::FinalizeOnelab(), Msg::GetNumOnelabClients(), onelab::localClient::localClient(), Msg::SetOnelabChanged(), and onelab::localClient::~localClient().
lastClient()
citer onelab::server::lastClient () inline
Definition at line 1331 of file onelab.h.
Referenced by Msg::FinalizeOnelab().
registerClient()
void onelab::server::registerClient (client * c) inline
Definition at line 1339 of file onelab.h.
Referenced by onelab::localClient::localClient().
set()
template<class T > bool onelab::server::set (const T & p, const std::string & client = "") inline
Definition at line 1319 of file onelab.h.
Referenced by onelab::localClient::_set().
setChanged()
void onelab::server::setChanged (int changed, const std::string & client = "") inline
Definition at line 1345 of file onelab.h.
Referenced by Msg::SetOnelabChanged().
setInstance()
static void onelab::server::setInstance (server * s) inline static
Definition at line 1314 of file onelab.h.
thresholdChanged()
void onelab::server::thresholdChanged (int value, const std::string & client = "") inline
Definition at line 1353 of file onelab.h.
toChar()
std::vector<std::string> onelab::server::toChar (const std::string & client = "") inline
Definition at line 1363 of file onelab.h.
Referenced by toFile().
toFile()
bool onelab::server::toFile (FILE * fp, const std::string & client = "") inline
Definition at line 1372 of file onelab.h.
toJSON()
bool onelab::server::toJSON (std::string & json, const std::string & client = "") inline
Definition at line 1382 of file onelab.h.
unregisterClient()
void onelab::server::unregisterClient (client * c) inline
Definition at line 1344 of file onelab.h.
Referenced by onelab::localClient::~localClient().
Member Data Documentation
_address
std::string onelab::server::_address private
Definition at line 1300 of file onelab.h.
_clients
std::set<client *> onelab::server::_clients private
Definition at line 1302 of file onelab.h.
Referenced by findClient(), firstClient(), getNumClients(), lastClient(), registerClient(), and unregisterClient().
_parameterSpace
parameterSpace onelab::server::_parameterSpace private
Definition at line 1304 of file onelab.h.
Referenced by clear(), fromChar(), fromJSON(), get(), getChanged(), getNumParameters(), getParameterNames(), set(), setChanged(), thresholdChanged(), toChar(), and toJSON().
_server
server* onelab::server::_server static private
Definition at line 1298 of file onelab.h.
Referenced by instance(), and setInstance().
The documentation for this class was generated from the following file:
src/common/onelab.h