gmsh-TingyuanDoc: GMSH_CutPlanePlugin Class Reference
GMSH_CutPlanePlugin Class Reference
#include <CutPlane.h>
Public Member Functions
GMSH_CutPlanePlugin ()
std::string getName () const
std::string getShortHelp () const
std::string getHelp () const
int getNbOptions () const
StringXNumber * getOption (int iopt)
PView * execute (PView *)
virtual bool geometricalFilter (fullMatrix< double > *) const
Public Member Functions inherited from GMSH_LevelsetPlugin
GMSH_LevelsetPlugin ()
void assignSpecificVisibility () const
Public Member Functions inherited from GMSH_PostPlugin
GMSH_PLUGIN_TYPE getType () const
virtual int run ()
virtual PView * executeRemote (PView *)
virtual PView * getView (int index, PView *view)
virtual PViewDataList * getDataList (PView *view, bool showError=true)
virtual PViewData * getPossiblyAdaptiveData (PView *view)
Public Member Functions inherited from GMSH_Plugin
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
virtual int getNbOptionsStr () const
virtual StringXString * getOptionStr (int iopt)
std::string serialize ()
Static Public Member Functions
static double callbackA (int, int, double)
static double callbackB (int, int, double)
static double callbackC (int, int, double)
static double callbackD (int, int, double)
static double callbackVol (int, int, double)
static double callbackRecur (int, int, double)
static double callbackTarget (int, int, double)
static void draw (void *context)
Static Public Member Functions inherited from GMSH_Plugin
static void setDrawFunction (void(*fct)(void *))
Private Member Functions
double levelset (double x, double y, double z, double val) const
Static Private Member Functions
static double callback (int num, int action, double value, double *opt, double step, double min, double max)
Static Private Attributes
static int iview = 0
Additional Inherited Members
Public Types inherited from GMSH_Plugin
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Public Attributes inherited from GMSH_Plugin
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes inherited from GMSH_Plugin
static void(* draw)(void *) = nullptr
Protected Types inherited from GMSH_LevelsetPlugin
enum ORIENTATION { NONE, PLANE, SPHERE, MAP }
Protected Attributes inherited from GMSH_LevelsetPlugin
double _ref [3]
double _targetError
int _valueTimeStep
int _valueView
int _valueIndependent
int _recurLevel
int _extractVolume
ORIENTATION _orientation
Detailed Description
Definition at line 15 of file CutPlane.h.
Constructor & Destructor Documentation
GMSH_CutPlanePlugin()
GMSH_CutPlanePlugin::GMSH_CutPlanePlugin () inline
Definition at line 22 of file CutPlane.h.
Member Function Documentation
callback()
double GMSH_CutPlanePlugin::callback (int num, int action, double value, double * opt, double step, double min, double max) static private
Definition at line 50 of file CutPlane.cpp.
Referenced by callbackA(), callbackB(), callbackC(), callbackD(), callbackRecur(), callbackTarget(), and callbackVol().
callbackA()
double GMSH_CutPlanePlugin::callbackA (int num, int action, double value) static
Definition at line 66 of file CutPlane.cpp.
callbackB()
double GMSH_CutPlanePlugin::callbackB (int num, int action, double value) static
Definition at line 72 of file CutPlane.cpp.
callbackC()
double GMSH_CutPlanePlugin::callbackC (int num, int action, double value) static
Definition at line 78 of file CutPlane.cpp.
callbackD()
double GMSH_CutPlanePlugin::callbackD (int num, int action, double value) static
Definition at line 84 of file CutPlane.cpp.
callbackRecur()
double GMSH_CutPlanePlugin::callbackRecur (int num, int action, double value) static
Definition at line 97 of file CutPlane.cpp.
callbackTarget()
double GMSH_CutPlanePlugin::callbackTarget (int num, int action, double value) static
Definition at line 102 of file CutPlane.cpp.
callbackVol()
double GMSH_CutPlanePlugin::callbackVol (int num, int action, double value) static
Definition at line 91 of file CutPlane.cpp.
draw()
void GMSH_CutPlanePlugin::draw (void * context) static
Definition at line 31 of file CutPlane.cpp.
execute()
PView * GMSH_CutPlanePlugin::execute (PView * v) virtual
Reimplemented from GMSH_LevelsetPlugin.
Definition at line 150 of file CutPlane.cpp.
geometricalFilter()
bool GMSH_CutPlanePlugin::geometricalFilter (fullMatrix< double > * node_positions) const virtual
Reimplemented from GMSH_PostPlugin.
Definition at line 136 of file CutPlane.cpp.
getHelp()
std::string GMSH_CutPlanePlugin::getHelp () const virtual
Implements GMSH_Plugin.
Definition at line 108 of file CutPlane.cpp.
getName()
std::string GMSH_CutPlanePlugin::getName () const inline virtual
Implements GMSH_Plugin.
Definition at line 23 of file CutPlane.h.
getNbOptions()
int GMSH_CutPlanePlugin::getNbOptions () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 119 of file CutPlane.cpp.
getOption()
StringXNumber * GMSH_CutPlanePlugin::getOption (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 124 of file CutPlane.cpp.
getShortHelp()
std::string GMSH_CutPlanePlugin::getShortHelp () const inline virtual
Implements GMSH_Plugin.
Definition at line 24 of file CutPlane.h.
levelset()
double GMSH_CutPlanePlugin::levelset (double x, double y, double z, double val) const private virtual
Implements GMSH_LevelsetPlugin.
Definition at line 129 of file CutPlane.cpp.
Referenced by geometricalFilter().
Member Data Documentation
iview
int GMSH_CutPlanePlugin::iview = 0 static private
Definition at line 19 of file CutPlane.h.
Referenced by callback(), and draw().
The documentation for this class was generated from the following files:
src/plugin/CutPlane.h
src/plugin/CutPlane.cpp