gmsh-TingyuanDoc: MPyramid Class Reference
MPyramid Class Reference
#include <MPyramid.h>
Public Member Functions
MPyramid (MVertex *v0, MVertex *v1, MVertex *v2, MVertex *v3, MVertex *v4, int num=0, int part=0)
MPyramid (const std::vector< MVertex * > &v, int num=0, int part=0)
~MPyramid ()
virtual int getDim () const
virtual std::size_t getNumVertices () const
virtual MVertex * getVertex (int num)
virtual const MVertex * getVertex (int num) const
virtual void setVertex (int num, MVertex *v)
virtual int getNumEdges () const
virtual MEdge getEdge (int num) const
virtual int numEdge2numVertex (int numEdge, int numVert) const
virtual int getNumEdgesRep (bool curved)
virtual void getEdgeRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getEdgeVertices (const int num, std::vector< MVertex * > &v) const
virtual int getNumFaces ()
virtual MFace getFace (int num) const
virtual int getNumFacesRep (bool curved)
virtual void getFaceRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getFaceVertices (const int num, std::vector< MVertex * > &v) const
virtual bool getFaceInfo (const MFace &face, int &ithFace, int &sign, int &rot) const
virtual int getType () const
virtual int getTypeForMSH () const
virtual int getTypeForVTK () const
virtual const char * getStringForPOS () const
virtual const char * getStringForBDF () const
virtual void reverse ()
virtual int getVolumeSign ()
virtual void getNode (int num, double &u, double &v, double &w) const
virtual SPoint3 barycenterUVW () const
virtual bool isInside (double u, double v, double w) const
void getIntegrationPoints (int pOrder, int *npts, IntPt **pts)
virtual int numCommonNodesInDualGraph (const MElement *const other) const
virtual MVertex * getVertexNEU (int num)
Public Member Functions inherited from MElement
MElement (std::size_t num=0, int part=0)
virtual ~MElement ()
double getTolerance () const
virtual std::size_t getNum () const
void forceNum (std::size_t num)
virtual int getPolynomialOrder () const
virtual bool getIsAssimilatedSerendipity () const
virtual bool getIsOnlySerendipity () const
virtual int getPartition () const
virtual void setPartition (int num)
virtual char getVisibility () const
virtual void setVisibility (char val)
void getVertices (std::vector< MVertex * > &verts)
virtual void getVertexInfo (const MVertex *vertex, int &ithVertex) const
virtual MVertex * getVertexUNV (int num)
virtual MVertex * getVertexVTK (int num)
virtual MVertex * getVertexMATLAB (int num)
virtual MVertex * getVertexTOCHNOG (int num)
virtual MVertex * getVertexBDF (int num)
virtual MVertex * getVertexDIFF (int num)
virtual MVertex * getVertexINP (int num)
virtual MVertex * getVertexKEY (int num)
virtual MVertex * getVertexRAD (int num)
virtual int getNumEdgeVertices () const
virtual int getNumFaceVertices () const
virtual int getNumVolumeVertices () const
std::size_t getNumPrimaryVertices () const
virtual MEdgeN getHighOrderEdge (int num, int sign)
MEdgeN getHighOrderEdge (const MEdge &edge)
virtual bool getEdgeInfo (const MEdge &edge, int &ithEdge, int &sign) const
virtual MEdge getEdgeSolin (int numEdge)
virtual MFaceN getHighOrderFace (int num, int sign, int rot)
MFaceN getHighOrderFace (const MFace &face)
virtual MFace getFaceSolin (int numFace)
virtual MElement * getParent () const
virtual void setParent (MElement *p, bool owner=false)
virtual void updateParent (GModel *gm)
virtual int getNumChildren () const
virtual MElement * getChild (int i) const
virtual bool ownsParent () const
virtual const MElement * getBaseElement () const
virtual MElement * getBaseElement ()
virtual MElement * getDomain (int i) const
virtual void setDomain (MElement *e, int i)
virtual double maxEdge ()
virtual double minEdge ()
double maxDistToStraight () const
double skewness ()
virtual double gammaShapeMeasure ()
virtual double etaShapeMeasure ()
double minSICNShapeMeasure ()
double minSIGEShapeMeasure ()
double distoShapeMeasure ()
double minIsotropyMeasure (bool knownValid=false, bool reversedOk=false)
double minScaledJacobian (bool knownValid=false, bool reversedOk=false)
virtual double angleShapeMeasure ()
virtual void scaledJacRange (double &jmin, double &jmax, GEntity *ge=nullptr) const
virtual void idealJacRange (double &jmin, double &jmax, GEntity *ge=nullptr)
virtual void signedInvCondNumRange (double &iCNMin, double &iCNMax, GEntity *ge=nullptr)
virtual void signedInvGradErrorRange (double &minSIGE, double &maxSIGE)
virtual double getInnerRadius ()
virtual double getOuterRadius ()
virtual SPoint3 barycenter (bool primary=false) const
virtual SPoint3 fastBarycenter (bool primary=false) const
virtual SPoint3 barycenter_infty () const
virtual double getVolume ()
virtual bool setVolumePositive ()
int getValidity ()
virtual std::string getInfoString (bool multline)
virtual const nodalBasis * getFunctionSpace (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getFuncSpaceData (int order=-1, bool serendip=false) const
virtual const JacobianBasis * getJacobianFuncSpace (int orderElement=-1) const
virtual const FuncSpaceData getJacobianFuncSpaceData (int orderElement=-1) const
virtual void getShapeFunctions (double u, double v, double w, double s[], int order=-1) const
virtual void getGradShapeFunctions (double u, double v, double w, double s[][3], int order=-1) const
virtual void getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order=-1) const
virtual void getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order=-1) const
virtual double getJacobian (const fullMatrix< double > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double *jac) const
virtual double getJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobian (double u, double v, double w, fullMatrix< double > &j) const
virtual double getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobianDeterminant (double u, double v, double w) const
void getSignedJacobian (fullVector< double > &jacobian, int o=-1) const
void getNodesCoord (fullMatrix< double > &nodesXYZ) const
void getNodesCoordNonSerendip (fullMatrix< double > &nodesXYZ) const
bezierCoeff * getBezierVerticesCoord () const
virtual std::size_t getNumShapeFunctions () const
virtual std::size_t getNumPrimaryShapeFunctions () const
virtual const MVertex * getShapeFunctionNode (int i) const
virtual MVertex * getShapeFunctionNode (int i)
virtual double getEigenvaluesMetric (double u, double v, double w, double values[3]) const
virtual void pnt (double u, double v, double w, SPoint3 &p) const
virtual void pnt (double u, double v, double w, double *p) const
virtual void pnt (const std::vector< double > &sf, SPoint3 &p) const
virtual void primaryPnt (double u, double v, double w, SPoint3 &p)
virtual void xyz2uvw (double xyz[3], double uvw[3]) const
virtual void movePointFromParentSpaceToElementSpace (double &u, double &v, double &w) const
virtual void movePointFromElementSpaceToParentSpace (double &u, double &v, double &w) const
double interpolate (double val[], double u, double v, double w, int stride=1, int order=-1)
void interpolateGrad (double val[], double u, double v, double w, double f[], int stride=1, double invjac[3][3]=nullptr, int order=-1)
void interpolateCurl (double val[], double u, double v, double w, double f[], int stride=3, int order=-1)
double interpolateDiv (double val[], double u, double v, double w, int stride=3, int order=-1)
double integrate (double val[], int pOrder, int stride=1, int order=-1)
double integrateCirc (double val[], int edge, int pOrder, int order=-1)
double integrateFlux (double val[], int face, int pOrder, int order=-1)
virtual void writeMSH2 (FILE *fp, double version=1.0, bool binary=false, int num=0, int elementary=1, int physical=1, int parentNum=0, int dom1Num=0, int dom2Num=0, std::vector< short > *ghosts=nullptr)
virtual void writeMSH3 (FILE *fp, bool binary=false, int elementary=1, std::vector< short > *ghosts=nullptr)
virtual void writePOS (FILE *fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor=1.0, int elementary=1)
virtual void writeSTL (FILE *fp, bool binary=false, double scalingFactor=1.0)
virtual void writeX3D (FILE *fp, double scalingFactor=1.0)
virtual void writeVRML (FILE *fp)
virtual void writePLY2 (FILE *fp)
virtual void writeUNV (FILE *fp, int num=0, int elementary=1, int physical=1)
virtual void writeVTK (FILE *fp, bool binary=false, bool bigEndian=false)
virtual void writeMATLAB (FILE *fp, int filetype, int elementary=0, int physical=0, bool binary=false)
virtual void writeTOCHNOG (FILE *fp, int num)
virtual void writeMESH (FILE *fp, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeNEU (FILE *fp, unsigned gambitType, int adjust, int phys=0)
virtual void writeIR3 (FILE *fp, int elementTagType, int num, int elementary, int physical)
virtual void writeBDF (FILE *fp, int format=0, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeDIFF (FILE *fp, int num, bool binary=false, int physical_property=1)
virtual void writeINP (FILE *fp, int num)
virtual void writeKEY (FILE *fp, int pid, int num)
virtual void writeRAD (FILE *fp, int num)
virtual void writeSU2 (FILE *fp, int num)
virtual int getTypeForUNV () const
virtual const char * getStringForTOCHNOG () const
virtual const char * getStringForDIFF () const
virtual const char * getStringForINP () const
virtual const char * getStringForKEY () const
virtual const char * getStringForRAD () const
std::string getName ()
virtual std::size_t getNumVerticesForMSH ()
virtual void getVerticesIdForMSH (std::vector< int > &verts)
virtual MElement * copy (std::map< int, MVertex * > &vertexMap, std::map< MElement *, MElement * > &newParents, std::map< MElement *, MElement * > &newDomains)
Static Public Member Functions
static int edges_pyramid (const int edge, const int vert)
static int faces_pyramid (const int face, const int vert)
static int faces2edge_pyramid (const int face, const int edge)
Static Public Member Functions inherited from MElement
static unsigned int getInfoMSH (const int typeMSH, const char **const name=nullptr)
Protected Member Functions
void _getEdgeVertices (const int num, std::vector< MVertex * > &v) const
void _getFaceVertices (const int num, std::vector< MVertex * > &v) const
Protected Member Functions inherited from MElement
void _getEdgeRep (MVertex *v0, MVertex *v1, double *x, double *y, double *z, SVector3 *n, int faceIndex=-1)
void _getFaceRep (MVertex *v0, MVertex *v1, MVertex *v2, double *x, double *y, double *z, SVector3 *n)
Protected Attributes
MVertex * _v [5]
Additional Inherited Members
Static Protected Member Functions inherited from MElement
static bool _getFaceInfo (const MFace &face, const MFace &other, int &sign, int &rot)
Static Protected Attributes inherited from MElement
static double _isInsideTolerance
Detailed Description
Definition at line 32 of file MPyramid.h.
Constructor & Destructor Documentation
MPyramid() [1/2]
MPyramid::MPyramid (MVertex * v0, MVertex * v1, MVertex * v2, MVertex * v3, MVertex * v4, int num = 0, int part = 0) inline
Definition at line 56 of file MPyramid.h.
MPyramid() [2/2]
MPyramid::MPyramid (const std::vector< MVertex * > & v, int num = 0, int part = 0) inline
Definition at line 66 of file MPyramid.h.
~MPyramid()
MPyramid::~MPyramid () inline
Definition at line 71 of file MPyramid.h.
Member Function Documentation
_getEdgeVertices()
void MPyramid::_getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline protected
Definition at line 35 of file MPyramid.h.
Referenced by getEdgeVertices(), and MPyramidN::getEdgeVertices().
_getFaceVertices()
void MPyramid::_getFaceVertices (const int num, std::vector< MVertex * > & v) const inline protected
Definition at line 40 of file MPyramid.h.
Referenced by getFaceVertices().
barycenterUVW()
virtual SPoint3 MPyramid::barycenterUVW () const inline virtual
Reimplemented from MElement.
Definition at line 165 of file MPyramid.h.
edges_pyramid()
static int MPyramid::edges_pyramid (const int edge, const int vert) inline static
Definition at line 175 of file MPyramid.h.
Referenced by _getEdgeVertices(), getEdge(), gmshGenerateMonomialsPyramid(), and numEdge2numVertex().
faces2edge_pyramid()
static int MPyramid::faces2edge_pyramid (const int face, const int edge) inline static
Definition at line 187 of file MPyramid.h.
Referenced by retrieveFaceBoundaryVertices().
faces_pyramid()
static int MPyramid::faces_pyramid (const int face, const int vert) inline static
Definition at line 181 of file MPyramid.h.
Referenced by _getFaceVertices(), _myGetFaceRep(), Cell::findBdCellOrientation(), Cell::findBdElement(), getFace(), MPyramidN::getFaceVertices(), gmshGenerateMonomialsPyramid(), and retrieveFaceBoundaryVertices().
getDim()
virtual int MPyramid::getDim () const inline virtual
Implements MElement.
Definition at line 72 of file MPyramid.h.
getEdge()
virtual MEdge MPyramid::getEdge (int num) const inline virtual
Implements MElement.
Definition at line 78 of file MPyramid.h.
Referenced by getEdgeRep().
getEdgeRep()
virtual void MPyramid::getEdgeRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) inline virtual
Implements MElement.
Reimplemented in MPyramidN.
Definition at line 87 of file MPyramid.h.
Referenced by MPyramidN::getEdgeRep().
getEdgeVertices()
virtual void MPyramid::getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MElement.
Reimplemented in MPyramidN.
Definition at line 94 of file MPyramid.h.
getFace()
virtual MFace MPyramid::getFace (int num) const inline virtual
Implements MElement.
Definition at line 100 of file MPyramid.h.
Referenced by MPyramidN::getEdgeRep(), and getFaceInfo().
getFaceInfo()
bool MPyramid::getFaceInfo (const MFace & face, int & ithFace, int & sign, int & rot) const virtual
Reimplemented from MElement.
Definition at line 42 of file MPyramid.cpp.
getFaceRep()
void MPyramid::getFaceRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Implements MElement.
Reimplemented in MPyramidN.
Definition at line 349 of file MPyramid.cpp.
Referenced by MPyramidN::getFaceRep().
getFaceVertices()
virtual void MPyramid::getFaceVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MElement.
Reimplemented in MPyramidN.
Definition at line 111 of file MPyramid.h.
getIntegrationPoints()
void MPyramid::getIntegrationPoints (int pOrder, int * npts, IntPt ** pts) virtual
Reimplemented from MElement.
Definition at line 36 of file MPyramid.cpp.
getNode()
virtual void MPyramid::getNode (int num, double & u, double & v, double & w) const inline virtual
Reimplemented from MElement.
Reimplemented in MPyramidN.
Definition at line 130 of file MPyramid.h.
Referenced by MPyramidN::getNode().
getNumEdges()
virtual int MPyramid::getNumEdges () const inline virtual
Implements MElement.
Definition at line 77 of file MPyramid.h.
getNumEdgesRep()
virtual int MPyramid::getNumEdgesRep (bool curved) inline virtual
Implements MElement.
Reimplemented in MPyramidN.
Definition at line 86 of file MPyramid.h.
getNumFaces()
virtual int MPyramid::getNumFaces () inline virtual
Implements MElement.
Definition at line 99 of file MPyramid.h.
getNumFacesRep()
int MPyramid::getNumFacesRep (bool curved) virtual
Implements MElement.
Reimplemented in MPyramidN.
Definition at line 105 of file MPyramid.cpp.
Referenced by MPyramidN::getNumFacesRep().
getNumVertices()
virtual std::size_t MPyramid::getNumVertices () const inline virtual
Implements MElement.
Reimplemented in MPyramidN.
Definition at line 73 of file MPyramid.h.
Referenced by Subdivide().
getStringForBDF()
virtual const char* MPyramid::getStringForBDF () const inline virtual
Reimplemented from MElement.
Definition at line 122 of file MPyramid.h.
getStringForPOS()
virtual const char* MPyramid::getStringForPOS () const inline virtual
Reimplemented from MElement.
Definition at line 121 of file MPyramid.h.
getType()
virtual int MPyramid::getType () const inline virtual
Implements MElement.
Definition at line 118 of file MPyramid.h.
getTypeForMSH()
virtual int MPyramid::getTypeForMSH () const inline virtual
Reimplemented from MElement.
Reimplemented in MPyramidN.
Definition at line 119 of file MPyramid.h.
getTypeForVTK()
virtual int MPyramid::getTypeForVTK () const inline virtual
Reimplemented from MElement.
Definition at line 120 of file MPyramid.h.
getVertex() [1/2]
virtual MVertex* MPyramid::getVertex (int num) inline virtual
Implements MElement.
Reimplemented in MPyramidN.
Definition at line 74 of file MPyramid.h.
Referenced by getFaceRep(), getVertexNEU(), setHighOrder(), and Subdivide().
getVertex() [2/2]
virtual const MVertex* MPyramid::getVertex (int num) const inline virtual
Implements MElement.
Reimplemented in MPyramidN.
Definition at line 75 of file MPyramid.h.
getVertexNEU()
virtual MVertex* MPyramid::getVertexNEU (int num) inline virtual
Reimplemented from MElement.
Definition at line 199 of file MPyramid.h.
getVolumeSign()
int MPyramid::getVolumeSign () virtual
Reimplemented from MElement.
Definition at line 15 of file MPyramid.cpp.
isInside()
virtual bool MPyramid::isInside (double u, double v, double w) const inline virtual
Implements MElement.
Definition at line 166 of file MPyramid.h.
numCommonNodesInDualGraph()
int MPyramid::numCommonNodesInDualGraph (const MElement *const other) const virtual
Implements MElement.
Definition at line 375 of file MPyramid.cpp.
numEdge2numVertex()
virtual int MPyramid::numEdge2numVertex (int numEdge, int numVert) const inline virtual
Reimplemented from MElement.
Definition at line 82 of file MPyramid.h.
reverse()
virtual void MPyramid::reverse () inline virtual
Reimplemented from MElement.
Reimplemented in MPyramidN.
Definition at line 123 of file MPyramid.h.
setVertex()
virtual void MPyramid::setVertex (int num, MVertex * v) inline virtual
Reimplemented from MElement.
Reimplemented in MPyramidN.
Definition at line 76 of file MPyramid.h.
Member Data Documentation
_v
MVertex* MPyramid::_v[5] protected
Definition at line 34 of file MPyramid.h.
Referenced by _getEdgeVertices(), _getFaceVertices(), getEdge(), getFace(), MPyramidN::getFaceVertices(), getVertex(), MPyramidN::getVertex(), getVolumeSign(), MPyramid(), reverse(), MPyramidN::reverse(), setVertex(), and MPyramidN::setVertex().
The documentation for this class was generated from the following files:
src/geo/MPyramid.h
src/geo/MPyramid.cpp