gmsh-TingyuanDoc: onelab::client Class Reference
onelab::client Class Reference abstract
#include <onelab.h>
Public Member Functions
client (const std::string &name)
virtual ~client ()
std::string getName ()
void setId (int id)
int getId ()
void setIndex (int index)
int getIndex ()
virtual bool run ()
virtual bool isNetworkClient ()
virtual bool kill ()
virtual void sendInfo (const std::string &msg)
virtual void sendWarning (const std::string &msg)
virtual void sendError (const std::string &msg)
virtual void sendProgress (const std::string &msg)
virtual void sendMergeFileRequest (const std::string &msg)
virtual void sendOpenProjectRequest (const std::string &msg)
virtual void sendParseStringRequest (const std::string &msg)
virtual void sendVertexArray (const std::string &msg)
virtual bool clear (const std::string &name)=0
virtual bool set (const number &p)=0
virtual bool set (const string &p)=0
virtual bool get (std::vector< number > &ps, const std::string &name="")=0
virtual bool get (std::vector< string > &ps, const std::string &name="")=0
virtual bool setAndAppendChoices (const number &p)=0
virtual bool setAndAppendChoices (const string &p)=0
virtual bool getWithoutChoices (std::vector< number > &ps, const std::string &name="")=0
virtual bool getWithoutChoices (std::vector< string > &ps, const std::string &name="")=0
std::vector< std::string > toChar ()
bool fromChar (const std::vector< std::string > &msg)
bool toFile (FILE *fp)
bool fromFile (FILE *fp)
Protected Attributes
std::string _name
int _id
int _index
Detailed Description
Definition at line 1201 of file onelab.h.
Constructor & Destructor Documentation
client()
onelab::client::client (const std::string & name) inline
Definition at line 1211 of file onelab.h.
~client()
virtual onelab::client::~client () inline virtual
Definition at line 1212 of file onelab.h.
Member Function Documentation
clear()
virtual bool onelab::client::clear (const std::string & name) pure virtual
Implemented in onelab::remoteNetworkClient, and onelab::localClient.
fromChar()
bool onelab::client::fromChar (const std::vector< std::string > & msg) inline
Definition at line 1263 of file onelab.h.
Referenced by fromFile().
fromFile()
bool onelab::client::fromFile (FILE * fp) inline
Definition at line 1285 of file onelab.h.
get() [1/2]
virtual bool onelab::client::get (std::vector< number > & ps, const std::string & name = "") pure virtual
Implemented in onelab::remoteNetworkClient, and onelab::localClient.
Referenced by onelab::parameter::fromJSON(), and toChar().
get() [2/2]
virtual bool onelab::client::get (std::vector< string > & ps, const std::string & name = "") pure virtual
Implemented in onelab::remoteNetworkClient, and onelab::localClient.
getId()
int onelab::client::getId () inline
Definition at line 1215 of file onelab.h.
getIndex()
int onelab::client::getIndex () inline
Definition at line 1217 of file onelab.h.
getName()
std::string onelab::client::getName () inline
Definition at line 1213 of file onelab.h.
Referenced by toFile().
getWithoutChoices() [1/2]
virtual bool onelab::client::getWithoutChoices (std::vector< number > & ps, const std::string & name = "") pure virtual
Implemented in onelab::remoteNetworkClient, and onelab::localClient.
getWithoutChoices() [2/2]
virtual bool onelab::client::getWithoutChoices (std::vector< string > & ps, const std::string & name = "") pure virtual
Implemented in onelab::remoteNetworkClient, and onelab::localClient.
isNetworkClient()
virtual bool onelab::client::isNetworkClient () inline virtual
Reimplemented in onelab::remoteNetworkClient, and onelab::localNetworkClient.
Definition at line 1219 of file onelab.h.
kill()
virtual bool onelab::client::kill () inline virtual
Reimplemented in onelab::localNetworkClient.
Definition at line 1220 of file onelab.h.
run()
virtual bool onelab::client::run () inline virtual
Reimplemented in onelab::localNetworkClient.
Definition at line 1218 of file onelab.h.
sendError()
virtual void onelab::client::sendError (const std::string & msg) inline virtual
Reimplemented in onelab::remoteNetworkClient.
Definition at line 1229 of file onelab.h.
sendInfo()
virtual void onelab::client::sendInfo (const std::string & msg) inline virtual
Reimplemented in onelab::remoteNetworkClient.
Definition at line 1221 of file onelab.h.
sendMergeFileRequest()
virtual void onelab::client::sendMergeFileRequest (const std::string & msg) inline virtual
Reimplemented in onelab::remoteNetworkClient.
Definition at line 1237 of file onelab.h.
sendOpenProjectRequest()
virtual void onelab::client::sendOpenProjectRequest (const std::string & msg) inline virtual
Reimplemented in onelab::remoteNetworkClient.
Definition at line 1238 of file onelab.h.
sendParseStringRequest()
virtual void onelab::client::sendParseStringRequest (const std::string & msg) inline virtual
Reimplemented in onelab::remoteNetworkClient.
Definition at line 1239 of file onelab.h.
sendProgress()
virtual void onelab::client::sendProgress (const std::string & msg) inline virtual
Reimplemented in onelab::remoteNetworkClient.
Definition at line 1233 of file onelab.h.
sendVertexArray()
virtual void onelab::client::sendVertexArray (const std::string & msg) inline virtual
Definition at line 1240 of file onelab.h.
sendWarning()
virtual void onelab::client::sendWarning (const std::string & msg) inline virtual
Reimplemented in onelab::remoteNetworkClient.
Definition at line 1225 of file onelab.h.
set() [1/2]
virtual bool onelab::client::set (const number & p) pure virtual
Implemented in onelab::remoteNetworkClient, and onelab::localClient.
Referenced by fromChar().
set() [2/2]
virtual bool onelab::client::set (const string & p) pure virtual
Implemented in onelab::remoteNetworkClient, and onelab::localClient.
setAndAppendChoices() [1/2]
virtual bool onelab::client::setAndAppendChoices (const number & p) pure virtual
Implemented in onelab::remoteNetworkClient, and onelab::localClient.
setAndAppendChoices() [2/2]
virtual bool onelab::client::setAndAppendChoices (const string & p) pure virtual
Implemented in onelab::remoteNetworkClient, and onelab::localClient.
setId()
void onelab::client::setId (int id) inline
Definition at line 1214 of file onelab.h.
setIndex()
void onelab::client::setIndex (int index) inline
Definition at line 1216 of file onelab.h.
toChar()
std::vector<std::string> onelab::client::toChar () inline
Definition at line 1252 of file onelab.h.
Referenced by toFile().
toFile()
bool onelab::client::toFile (FILE * fp) inline
Definition at line 1284 of file onelab.h.
Member Data Documentation
_id
int onelab::client::_id protected
Definition at line 1206 of file onelab.h.
Referenced by getId(), and setId().
_index
int onelab::client::_index protected
Definition at line 1208 of file onelab.h.
Referenced by getIndex(), and setIndex().
_name
std::string onelab::client::_name protected
Definition at line 1204 of file onelab.h.
Referenced by onelab::localClient::_get(), onelab::localClient::_set(), getName(), and onelab::localClient::setAndAppendChoices().
The documentation for this class was generated from the following file:
src/common/onelab.h