gmsh-TingyuanDoc: mathEvaluator Class Reference
mathEvaluator Class Reference
#include <mathEvaluator.h>
Public Member Functions
mathEvaluator (std::vector< std::string > &expressions, const std::vector< std::string > &variables)
~mathEvaluator ()
bool eval (const std::vector< double > &values, std::vector< double > &res)
Detailed Description
Definition at line 37 of file mathEvaluator.h.
Constructor & Destructor Documentation
mathEvaluator()
mathEvaluator::mathEvaluator (std::vector< std::string > & expressions, const std::vector< std::string > & variables) inline
Definition at line 39 of file mathEvaluator.h.
~mathEvaluator()
mathEvaluator::~mathEvaluator () inline
Definition at line 46 of file mathEvaluator.h.
Member Function Documentation
eval()
bool mathEvaluator::eval (const std::vector< double > & values, std::vector< double > & res) inline
Definition at line 47 of file mathEvaluator.h.
Referenced by applyGeneralRaise(), MathEvalExpression::evaluate(), gLevelsetMathEvalAll::gradient(), gLevelsetMathEvalAll::hessian(), gLevelsetMathEval::operator()(), gLevelsetMathEvalAll::operator()(), and gmshParametricSurface::point().
The documentation for this class was generated from the following file:
src/numeric/mathEvaluator.h