gmsh-TingyuanDoc: HierarchicalBasisHcurlLine Class Reference
HierarchicalBasisHcurlLine Class Reference
#include <HierarchicalBasisHcurlLine.h>
Public Member Functions
HierarchicalBasisHcurlLine (int order)
virtual ~HierarchicalBasisHcurlLine ()
virtual unsigned int getNumberOfOrientations () const
virtual void generateBasis (double const &u, double const &v, double const &w, std::vector< std::vector< double > > &vertexBasis, std::vector< std::vector< double > > &edgeBasis, std::vector< std::vector< double > > &faceBasis, std::vector< std::vector< double > > &bubbleBasis, std::string typeFunction)
virtual void orientEdge (int const &flagOrientation, int const &edgeNumber, std::vector< std::vector< double > > &edgeBasis, const std::vector< std::vector< double > > &eTablePositiveFlag, const std::vector< std::vector< double > > &eTableNegativeFlag)
virtual void orientEdgeFunctionsForNegativeFlag (std::vector< std::vector< double > > &edgeFunctions)
virtual void orientFace (int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, const std::vector< std::vector< double > > &quadFaceFunctionsAllOrientation, const std::vector< std::vector< double > > &triFaceFunctionsAllOrientation, std::vector< std::vector< double > > &fTableCopy)
virtual void getKeysInfo (std::vector< int > &functionTypeInfo, std::vector< int > &orderInfo)
Public Member Functions inherited from HierarchicalBasisHcurl
virtual ~HierarchicalBasisHcurl ()=0
virtual void generateBasis (double const &u, double const &v, double const &w, std::vector< double > &vertexBasis, std::vector< double > &edgeBasis, std::vector< double > &faceBasis, std::vector< double > &bubbleBasis)
virtual void orientFace (int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, const std::vector< double > &quadFaceFunctionsAllOrientations, const std::vector< double > &triFaceFunctionsAllOrientations, std::vector< double > &fTableCopy)
virtual void orientEdge (int const &flagOrientation, int const &edgeNumber, std::vector< double > &edgeFunctions, const std::vector< double > &eTablePositiveFlag, const std::vector< double > &eTableNegativeFlag)
virtual void orientEdgeFunctionsForNegativeFlag (std::vector< double > &edgeFunctions)
virtual void addAllOrientedFaceFunctions (double const &u, double const &v, double const &w, const std::vector< double > &faceFunctions, std::vector< double > &quadFaceFunctionsAllOrientations, std::vector< double > &triFaceFunctionsAllOrientations)
virtual void addAllOrientedFaceFunctions (double const &u, double const &v, double const &w, const std::vector< std::vector< double > > &faceFunctions, std::vector< std::vector< double > > &quadFaceFunctionsAllOrientations, std::vector< std::vector< double > > &triFaceFunctionsAllOrientations, std::string typeFunction)
Public Member Functions inherited from HierarchicalBasis
virtual ~HierarchicalBasis ()=0
int getnVertexFunction () const
int getnEdgeFunction () const
int getnTriFaceFunction () const
int getnQuadFaceFunction () const
int getnBubbleFunction () const
int getNumTriFace () const
int getNumQuadFace () const
int getNumEdge () const
int numberOrientationQuadFace (int const &flag1, int const &flag2, int const &flag3)
int numberOrientationTriFace (int const &flag1, int const &flag2)
Private Member Functions
virtual void generateHcurlBasis (double const &u, double const &v, double const &w, std::vector< std::vector< double > > &edgeBasis, std::vector< std::vector< double > > &faceBasis, std::vector< std::vector< double > > &bubbleBasis)
virtual void generateCurlBasis (double const &u, double const &v, double const &w, std::vector< std::vector< double > > &edgeBasis, std::vector< std::vector< double > > &faceBasis, std::vector< std::vector< double > > &bubbleBasis)
virtual void orientOneFace (double const &u, double const &v, double const &w, int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, std::vector< std::vector< double > > &faceFunctions, std::string typeFunction)
Static Private Member Functions
static double _affineCoordinate (int j, double u)
static double dotProduct (const std::vector< double > &u, const std::vector< double > &v)
Private Attributes
int _pe
Additional Inherited Members
Protected Member Functions inherited from HierarchicalBasisHcurl
virtual void orientOneFace (double const &u, double const &v, double const &w, int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, std::vector< double > &faceFunctions)
Protected Attributes inherited from HierarchicalBasis
int _nvertex
int _nedge
int _nfaceQuad
int _nfaceTri
int _nVertexFunction
int _nEdgeFunction
int _nQuadFaceFunction
int _nTriFaceFunction
int _nBubbleFunction
Detailed Description
Definition at line 31 of file HierarchicalBasisHcurlLine.h.
Constructor & Destructor Documentation
HierarchicalBasisHcurlLine()
HierarchicalBasisHcurlLine::HierarchicalBasisHcurlLine (int order)
Definition at line 14 of file HierarchicalBasisHcurlLine.cpp.
~HierarchicalBasisHcurlLine()
HierarchicalBasisHcurlLine::~HierarchicalBasisHcurlLine () virtual
Definition at line 28 of file HierarchicalBasisHcurlLine.cpp.
Member Function Documentation
_affineCoordinate()
double HierarchicalBasisHcurlLine::_affineCoordinate (int j, double u) static private
Definition at line 35 of file HierarchicalBasisHcurlLine.cpp.
Referenced by generateHcurlBasis().
dotProduct()
double HierarchicalBasisHcurlLine::dotProduct (const std::vector< double > & u, const std::vector< double > & v) static private
Definition at line 44 of file HierarchicalBasisHcurlLine.cpp.
Referenced by generateHcurlBasis().
generateBasis()
virtual void HierarchicalBasisHcurlLine::generateBasis (double const & u, double const & v, double const & w, std::vector< std::vector< double > > & vertexBasis, std::vector< std::vector< double > > & edgeBasis, std::vector< std::vector< double > > & faceBasis, std::vector< std::vector< double > > & bubbleBasis, std::string typeFunction) inline virtual
Implements HierarchicalBasisHcurl.
Definition at line 37 of file HierarchicalBasisHcurlLine.h.
generateCurlBasis()
void HierarchicalBasisHcurlLine::generateCurlBasis (double const & u, double const & v, double const & w, std::vector< std::vector< double > > & edgeBasis, std::vector< std::vector< double > > & faceBasis, std::vector< std::vector< double > > & bubbleBasis) private virtual
Definition at line 128 of file HierarchicalBasisHcurlLine.cpp.
Referenced by generateBasis().
generateHcurlBasis()
void HierarchicalBasisHcurlLine::generateHcurlBasis (double const & u, double const & v, double const & w, std::vector< std::vector< double > > & edgeBasis, std::vector< std::vector< double > > & faceBasis, std::vector< std::vector< double > > & bubbleBasis) private virtual
Definition at line 49 of file HierarchicalBasisHcurlLine.cpp.
Referenced by generateBasis().
getKeysInfo()
void HierarchicalBasisHcurlLine::getKeysInfo (std::vector< int > & functionTypeInfo, std::vector< int > & orderInfo) virtual
Implements HierarchicalBasisHcurl.
Definition at line 137 of file HierarchicalBasisHcurlLine.cpp.
getNumberOfOrientations()
unsigned int HierarchicalBasisHcurlLine::getNumberOfOrientations () const virtual
Implements HierarchicalBasis.
Definition at line 30 of file HierarchicalBasisHcurlLine.cpp.
orientEdge()
void HierarchicalBasisHcurlLine::orientEdge (int const & flagOrientation, int const & edgeNumber, std::vector< std::vector< double > > & edgeBasis, const std::vector< std::vector< double > > & eTablePositiveFlag, const std::vector< std::vector< double > > & eTableNegativeFlag) virtual
Implements HierarchicalBasisHcurl.
Definition at line 95 of file HierarchicalBasisHcurlLine.cpp.
orientEdgeFunctionsForNegativeFlag()
void HierarchicalBasisHcurlLine::orientEdgeFunctionsForNegativeFlag (std::vector< std::vector< double > > & edgeFunctions) virtual
Implements HierarchicalBasisHcurl.
Definition at line 117 of file HierarchicalBasisHcurlLine.cpp.
orientFace()
virtual void HierarchicalBasisHcurlLine::orientFace (int const & flag1, int const & flag2, int const & flag3, int const & faceNumber, const std::vector< std::vector< double > > & quadFaceFunctionsAllOrientation, const std::vector< std::vector< double > > & triFaceFunctionsAllOrientation, std::vector< std::vector< double > > & fTableCopy) inline virtual
Implements HierarchicalBasisHcurl.
Definition at line 61 of file HierarchicalBasisHcurlLine.h.
orientOneFace()
virtual void HierarchicalBasisHcurlLine::orientOneFace (double const & u, double const & v, double const & w, int const & flag1, int const & flag2, int const & flag3, int const & faceNumber, std::vector< std::vector< double > > & faceFunctions, std::string typeFunction) inline private virtual
Implements HierarchicalBasisHcurl.
Definition at line 87 of file HierarchicalBasisHcurlLine.h.
Member Data Documentation
_pe
int HierarchicalBasisHcurlLine::_pe private
Definition at line 70 of file HierarchicalBasisHcurlLine.h.
Referenced by generateHcurlBasis(), getKeysInfo(), HierarchicalBasisHcurlLine(), orientEdge(), and orientEdgeFunctionsForNegativeFlag().
The documentation for this class was generated from the following files:
src/numeric/HierarchicalBasisHcurlLine.h
src/numeric/HierarchicalBasisHcurlLine.cpp