gmsh-TingyuanDoc: GEdge Class Reference
GEdge Class Reference abstract
#include <GEdge.h>
Public Member Functions
GEdge (GModel *model, int tag, GVertex *v0, GVertex *v1)
GEdge (GModel *model, int tag)
virtual ~GEdge ()
virtual void deleteMesh ()
void setBeginVertex (GVertex *gv)
void setEndVertex (GVertex *gv)
virtual GVertex * getBeginVertex () const
virtual GVertex * getEndVertex () const
void setVertex (GVertex *const f, const int orientation)
void setMeshMaster (GEdge *master, const std::vector< double > &)
void setMeshMaster (GEdge *master, int sign)
void reverse ()
void addFace (GFace *f)
virtual void delFace (GFace *f)
virtual int dim () const
virtual GEntity * getParentEntity ()
virtual std::vector< GVertex * > vertices () const
virtual void setVisibility (char val, bool recursive=false)
virtual void setColor (unsigned int val, bool recursive=false)
virtual bool isSeam (const GFace *face) const
virtual SBoundingBox3d bounds (bool fast=false)
virtual SOrientedBoundingBox getOBB ()
virtual std::list< GRegion * > regions () const
virtual std::vector< GFace * > faces () const
virtual std::size_t numFaces () const
virtual bool isOrphan ()
virtual GPoint point (double p) const =0
virtual bool containsParam (double pt) const
virtual SVector3 position (double p) const
virtual SVector3 firstDer (double par) const =0
virtual SVector3 secondDer (double par) const
virtual double curvature (double par) const
virtual SPoint2 reparamOnFace (const GFace *face, double epar, int dir) const
virtual int minimumMeshSegments () const
virtual int minimumDrawSegments () const
virtual std::string getAdditionalInfoString (bool multline=false)
virtual void writeGEO (FILE *fp)
virtual void writePY (FILE *fp)
bool storeSTLAsMesh ()
virtual bool is3D () const
double length () const
void setLength (const double l)
double length (const double &u0, const double &u1, const int nbQuadPoints=4)
double prescribedMeshSizeAtVertex () const
double prescribedMeshSizeAtParam (double u)
void setMeshSizeParametric (const std::vector< double > u, const std::vector< double > lc)
void setTooSmall (bool const b)
virtual bool isMeshDegenerated () const
virtual void getElementTypes (std::vector< int > &types) const
std::size_t getNumMeshElements () const
std::size_t getNumMeshElementsByType (const int familyType) const
std::size_t getNumMeshParentElements ()
void getNumMeshElements (unsigned *const c) const
MElement *const * getStartElementType (int type) const
MElement * getMeshElement (std::size_t index) const
MElement * getMeshElementByType (const int familyType, const std::size_t index) const
virtual void resetMeshAttributes ()
virtual bool periodic (int dim) const
virtual Range< double > parBounds (int i) const =0
virtual Range< double > parBoundsOnFace (GFace *face=nullptr) const
double getLowerBound () const
double getUpperBound () const
virtual bool containsPoint (const SPoint3 &pt) const
virtual GPoint closestPoint (const SPoint3 &queryPoint, double &param) const
virtual double parFromPoint (const SPoint3 &P) const
virtual bool refineProjection (const SVector3 &Q, double &u, int MaxIter, double relax, double tol, double &err) const
virtual bool XYZToU (const double X, const double Y, const double Z, double &U, const double relax=1, bool first=true) const
void relocateMeshVertices ()
void addLine (MLine *line)
void addElement (int type, MElement *e)
void removeElement (int type, MElement *e)
void removeElements (int type)
virtual void discretize (double tol, std::vector< SPoint3 > &dpts, std::vector< double > &ts)
SPoint3 closestPointWithTol (SPoint3 &p, double tolerance)
virtual void mesh (bool verbose)
virtual bool reorder (const int elementType, const std::vector< std::size_t > &ordering)
Public Member Functions inherited from GEntity
void addVerticesInSet (std::set< MVertex * > &, bool closure) const
virtual std::string getTypeString ()
GEntity (GModel *m, int t)
virtual ~GEntity ()
void deleteVertexArrays ()
virtual std::vector< GEdge * > const & edges () const
std::vector< GRegion * > bindingsGetRegions ()
std::vector< GFace * > bindingsGetFaces ()
std::vector< GEdge * > bindingsGetEdges () const
std::vector< GVertex * > bindingsGetVertices ()
virtual GeomType geomType () const
virtual bool continuous (int dim) const
virtual double period (int dim) const
virtual bool degenerate (int dim) const
virtual bool haveParametrization ()
virtual bool isFullyDiscrete ()
virtual double tolerance () const
virtual ModelType getNativeType () const
virtual void * getNativePtr () const
virtual int getNativeInt () const
GModel * model () const
int tag () const
void setTag (int tag)
virtual void addPhysicalEntity (int physicalTag)
virtual std::vector< int > getPhysicalEntities ()
GEntity * getMeshMaster () const
void setMeshMaster (GEntity *)
void setMeshMaster (GEntity *, const std::vector< double > &, bool updateCorrespondingVertices=true)
void updateCorrespondingVertices ()
void copyMasterCoordinates ()
virtual void alignElementsWithMaster ()
virtual char getVisibility ()
virtual char getSelection ()
virtual void setSelection (char val)
virtual unsigned int getColor ()
virtual void setColor (unsigned color, bool recursive=false)
virtual bool useColor ()
virtual std::string getInfoString (bool additional=true, bool multiline=false)
virtual double getMeshSize () const
virtual double getMeshSizeFactor () const
bool getAllElementsVisible ()
void setAllElementsVisible (bool val)
std::size_t getNumMeshVertices ()
MVertex * getMeshVertex (std::size_t index)
void addMeshVertex (MVertex *v)
void removeMeshVertex (MVertex *v)
GVertex * cast2Vertex ()
GEdge * cast2Edge ()
GFace * cast2Face ()
GRegion * cast2Region ()
Public Attributes
int masterOrientation
std::vector< MLine * > lines
GEdge * compoundCurve
std::vector< SPoint3 > stl_vertices_xyz
struct {
char method
double coeffTransfinite
double meshSize
double meshSizeFactor
int nbPointsTransfinite
int typeTransfinite
int minimumMeshSegments
ExtrudeParams * extrude
bool reverseMesh
} meshAttributes
struct {
GEntity::MeshGenerationStatus status
} meshStatistics
Public Attributes inherited from GEntity
std::vector< MVertex * > mesh_vertices
std::vector< GEntity * > compound
std::map< GVertex *, GVertex * > vertexCounterparts
std::vector< int > physicals
VertexArray * va_lines
VertexArray * va_triangles
std::set< MElement * > curvedBLElements
std::vector< double > affineTransform
std::map< MVertex *, MVertex * > correspondingVertices
std::map< MVertex *, MVertex * > correspondingHighOrderVertices
Protected Attributes
GVertex * _v0
GVertex * _v1
std::vector< GFace * > _faces
Protected Attributes inherited from GEntity
SOrientedBoundingBox * _obb
Private Attributes
double _length
bool _tooSmall
closestPointFinder * _cp
std::vector< double > _u_lc
std::vector< double > _lc
Additional Inherited Members
Public Types inherited from GEntity
enum ModelType {
UnknownModel, GmshModel, OpenCascadeModel, AcisModel,
ParasolidModel
}
enum GeomType {
Unknown, Point, BoundaryLayerPoint, Line,
Circle, Ellipse, Conic, Parabola,
Hyperbola, TrimmedCurve, OffsetCurve, BSpline,
Bezier, ParametricCurve, BoundaryLayerCurve, DiscreteCurve,
Plane, Nurb, Cylinder, Sphere,
Cone, Torus, RuledSurface, ParametricSurface,
BSplineSurface, BezierSurface, SurfaceOfRevolution, BoundaryLayerSurface,
DiscreteSurface, DiscreteDiskSurface, Volume, DiscreteVolume,
PartitionPoint, PartitionCurve, PartitionSurface, PartitionVolume,
GhostCurve, GhostSurface, GhostVolume
}
enum MeshGenerationStatus { PENDING, DONE, FAILED }
Detailed Description
Definition at line 26 of file GEdge.h.
Constructor & Destructor Documentation
GEdge() [1/2]
GEdge::GEdge (GModel * model, int tag, GVertex * v0, GVertex * v1)
Definition at line 26 of file GEdge.cpp.
GEdge() [2/2]
GEdge::GEdge (GModel * model, int tag)
Definition at line 36 of file GEdge.cpp.
~GEdge()
GEdge::~GEdge () virtual
Definition at line 44 of file GEdge.cpp.
Member Function Documentation
addElement()
void GEdge::addElement (int type, MElement * e) virtual
Reimplemented from GEntity.
Definition at line 775 of file GEdge.cpp.
Referenced by ghostEdge::addElement().
addFace()
void GEdge::addFace (GFace * f)
Definition at line 200 of file GEdge.cpp.
Referenced by gmshFace::resetNativePtr(), and GFace::setBoundEdges().
addLine()
void GEdge::addLine (MLine * line) inline
Definition at line 266 of file GEdge.h.
Referenced by addElement(), and ghostEdge::addLine().
bounds()
SBoundingBox3d GEdge::bounds (bool fast = false) virtual
Reimplemented from GEntity.
Definition at line 212 of file GEdge.cpp.
Referenced by GFace::setMeshMaster(), and writeGEO().
closestPoint()
GPoint GEdge::closestPoint (const SPoint3 & queryPoint, double & param) const virtual
Definition at line 552 of file GEdge.cpp.
Referenced by copy_vertices(), getGEdge(), optimize1DMeshAtAcuteCorners(), and relocateSlaveVertices().
closestPointWithTol()
SPoint3 GEdge::closestPointWithTol (SPoint3 & p, double tolerance)
Definition at line 728 of file GEdge.cpp.
containsParam()
bool GEdge::containsParam (double pt) const virtual
Definition at line 453 of file GEdge.cpp.
Referenced by containsPoint().
containsPoint()
bool GEdge::containsPoint (const SPoint3 & pt) const virtual
Reimplemented from GEntity.
Definition at line 445 of file GEdge.cpp.
curvature()
double GEdge::curvature (double par) const virtual
Reimplemented in discreteEdge.
Definition at line 492 of file GEdge.cpp.
Referenced by LC_MVertex_CURV(), max_edge_curvature(), max_edge_curvature_metric(), and BoundaryLayerField::operator()().
deleteMesh()
void GEdge::deleteMesh () virtual
Reimplemented from GEntity.
Definition at line 53 of file GEdge.cpp.
Referenced by copy_vertices(), deMeshGEdge::operator()(), and ~GEdge().
delFace()
void GEdge::delFace (GFace * f) virtual
Definition at line 206 of file GEdge.cpp.
dim()
virtual int GEdge::dim () const inline virtual
Reimplemented from GEntity.
Definition at line 86 of file GEdge.h.
Referenced by addExtrudeNormals().
discretize()
void GEdge::discretize (double tol, std::vector< SPoint3 > & dpts, std::vector< double > & ts) virtual
Reimplemented in gmshEdge.
Definition at line 806 of file GEdge.cpp.
Referenced by closestPointFinder::closestPointFinder(), and gmshEdge::discretize().
faces()
virtual std::vector<GFace *> GEdge::faces () const inline virtual
Reimplemented from GEntity.
Definition at line 113 of file GEdge.h.
Referenced by isOrphan(), GeomMeshMatcher::matchFaces(), max_surf_curvature(), meshGEdgeProcessing(), metric_based_on_surface_curvature(), meshGEdge::operator()(), regions(), skipEdge(), and transferSeamGEdgesVerticesToGFace().
firstDer()
virtual SVector3 GEdge::firstDer (double par) const pure virtual
Implemented in discreteEdge, gmshEdge, and xyEdge.
Referenced by crossField2d::crossField2d(), curvature(), blyr_manager::extrude_vertices_on_edges(), length(), max_edge_curvature_metric(), meshGEdgeProcessing(), meshGEdge::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), F_Transfinite::operator()(), BoundaryLayerField::operator()(), F_One::operator()(), refineProjection(), and secondDer().
getAdditionalInfoString()
std::string GEdge::getAdditionalInfoString (bool multline = false) virtual
Reimplemented from GEntity.
Reimplemented in gmshEdge.
Definition at line 295 of file GEdge.cpp.
Referenced by gmshEdge::getAdditionalInfoString().
getBeginVertex()
virtual GVertex* GEdge::getBeginVertex () const inline virtual
Definition at line 63 of file GEdge.h.
Referenced by _eulerCharacteristic(), addBoundaryLayerPoints(), allEdgesLinked(), buildConsecutiveListOfVertices(), copyMesh(), createEdgeLinks(), createElements(), discreteEdge::createGeometry(), createPoints(), discretize(), DuplicateCurve(), blyr_manager::extrude_vertices_on_edges(), ExtrudeCurve(), fillCorrespondingNodes(), filterPoints(), GEdgeSigned::getBeginVertex(), GModel::getBoundaryTags(), getDegeneratedVertices(), GEdgeSigned::getEndVertex(), getOBB(), LC_MVertex_PNTS(), GeomMeshMatcher::matchEdges(), max_edge_curvature(), max_edge_curvature_metric(), Mesh2DWithBoundaryLayers(), MeshExtrudedCurve(), meshGEdgeProcessing(), nextOne(), meshGEdge::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), orientAndSortEdges(), quad_face_opposite_edge(), recoverEdge(), recurFindLinkedEdges(), GModel::remove(), reparamMeshVertexOnEdge(), gmshFace::resetNativePtr(), GFace::setMeshMaster(), setMeshMaster(), BoundaryLayerField::setupFor1d(), topoExists(), vertices(), writeGEO(), and writePY().
getElementTypes()
virtual void GEdge::getElementTypes (std::vector< int > & types) const inline virtual
Reimplemented from GEntity.
Definition at line 194 of file GEdge.h.
getEndVertex()
virtual GVertex* GEdge::getEndVertex () const inline virtual
Definition at line 64 of file GEdge.h.
Referenced by _eulerCharacteristic(), addBoundaryLayerPoints(), allEdgesLinked(), buildConsecutiveListOfVertices(), copyMesh(), createEdgeLinks(), createElements(), discreteEdge::createGeometry(), createPoints(), discretize(), DuplicateCurve(), blyr_manager::extrude_vertices_on_edges(), ExtrudeCurve(), fillCorrespondingNodes(), filterPoints(), GEdgeSigned::getBeginVertex(), GModel::getBoundaryTags(), getDegeneratedVertices(), getEdgeVerticesOnGeo(), GEdgeSigned::getEndVertex(), getOBB(), LC_MVertex_PNTS(), GeomMeshMatcher::matchEdges(), Mesh2DWithBoundaryLayers(), MeshExtrudedCurve(), meshGEdgeProcessing(), nextOne(), meshGEdge::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), orientAndSortEdges(), quad_face_opposite_edge(), recoverEdge(), recurFindLinkedEdges(), GModel::remove(), reparamMeshVertexOnEdge(), gmshFace::resetNativePtr(), GFace::setMeshMaster(), setMeshMaster(), BoundaryLayerField::setupFor1d(), topoExists(), vertices(), writeGEO(), and writePY().
getLowerBound()
double GEdge::getLowerBound () const inline
Definition at line 227 of file GEdge.h.
getMeshElement()
MElement * GEdge::getMeshElement (std::size_t index) const virtual
Reimplemented from GEntity.
Definition at line 173 of file GEdge.cpp.
Referenced by GModel::_readMSH4(), GModel::alignPeriodicBoundaries(), bounds(), DocRecord::concave(), DocRecord::delaunay_conformity(), FixPeriodicMesh(), orientMeshGEdge::operator()(), and setHighOrderFromExistingMesh().
getMeshElementByType()
MElement * GEdge::getMeshElementByType (const int familyType, const std::size_t index) const virtual
Reimplemented from GEntity.
Definition at line 179 of file GEdge.cpp.
getNumMeshElements() [1/2]
std::size_t GEdge::getNumMeshElements () const inline virtual
Reimplemented from GEntity.
Definition at line 201 of file GEdge.h.
Referenced by GModel::_readMSH4(), GModel::alignPeriodicBoundaries(), bounds(), DocRecord::concave(), DocRecord::delaunay_conformity(), FixPeriodicMesh(), GModel::getMeshStatus(), meshGEdgeProcessing(), meshGEdge::operator()(), orientMeshGEdge::operator()(), and setHighOrderFromExistingMesh().
getNumMeshElements() [2/2]
void GEdge::getNumMeshElements (unsigned *const c) const virtual
Reimplemented from GEntity.
Definition at line 162 of file GEdge.cpp.
getNumMeshElementsByType()
std::size_t GEdge::getNumMeshElementsByType (const int familyType) const virtual
Reimplemented from GEntity.
Definition at line 148 of file GEdge.cpp.
getNumMeshParentElements()
std::size_t GEdge::getNumMeshParentElements () virtual
Reimplemented from GEntity.
Definition at line 155 of file GEdge.cpp.
getOBB()
SOrientedBoundingBox GEdge::getOBB () virtual
Reimplemented from GEntity.
Definition at line 234 of file GEdge.cpp.
Referenced by GeomMeshMatcher::matchEdges().
getParentEntity()
virtual GEntity* GEdge::getParentEntity () inline virtual
Reimplemented from GEntity.
Reimplemented in partitionEdge.
Definition at line 89 of file GEdge.h.
getStartElementType()
MElement *const * GEdge::getStartElementType (int type) const virtual
Reimplemented from GEntity.
Definition at line 167 of file GEdge.cpp.
getUpperBound()
double GEdge::getUpperBound () const inline
Definition at line 228 of file GEdge.h.
is3D()
virtual bool GEdge::is3D () const inline virtual
Definition at line 167 of file GEdge.h.
isMeshDegenerated()
virtual bool GEdge::isMeshDegenerated () const inline virtual
Reimplemented in xyEdge.
Definition at line 184 of file GEdge.h.
isOrphan()
bool GEdge::isOrphan () virtual
Reimplemented from GEntity.
Definition at line 705 of file GEdge.cpp.
Referenced by drawGEdge::operator()().
isSeam()
virtual bool GEdge::isSeam (const GFace * face) const inline virtual
Definition at line 101 of file GEdge.h.
Referenced by _relocateVertex(), buildConsecutiveListOfVertices(), getAllParameters(), GVertex::isOnSeam(), reparamMeshVertexOnFace(), transferSeamGEdgesVerticesToGFace(), and trueBoundary().
length() [1/2]
double GEdge::length () const inline
Definition at line 170 of file GEdge.h.
Referenced by fillPointCloud(), mylength(), F_Transfinite::operator()(), ExtendField::recomputeCurves(), and ExtendField::recomputeSurfaces().
length() [2/2]
double GEdge::length (const double & u0, const double & u1, const int nbQuadPoints = 4)
Definition at line 500 of file GEdge.cpp.
mesh()
void GEdge::mesh (bool verbose) virtual
Reimplemented from GEntity.
Reimplemented in discreteEdge.
Definition at line 918 of file GEdge.cpp.
Referenced by Mesh1D().
minimumDrawSegments()
virtual int GEdge::minimumDrawSegments () const inline virtual
Reimplemented in discreteEdge, and gmshEdge.
Definition at line 151 of file GEdge.h.
Referenced by gmshEdge::minimumDrawSegments(), drawGEdge::operator()(), and writeGEO().
minimumMeshSegments()
virtual int GEdge::minimumMeshSegments () const inline virtual
Reimplemented in discreteEdge, and gmshEdge.
Definition at line 148 of file GEdge.h.
numFaces()
virtual std::size_t GEdge::numFaces () const inline virtual
Definition at line 116 of file GEdge.h.
Referenced by drawGEdge::operator()().
parBounds()
virtual Range<double> GEdge::parBounds (int i) const pure virtual
Reimplemented from GEntity.
Implemented in discreteEdge, gmshEdge, and xyEdge.
Referenced by bounds(), GFace::buildRepresentationCross(), closestPoint(), containsParam(), copyMesh(), blyr_manager::extrude_vertices_on_edges(), extrudeMesh(), fillPointCloud(), getEdgeVerticesOnGeo(), getLowerBound(), getOBB(), getUpperBound(), LC_MVertex_PNTS(), max_edge_curvature(), max_edge_curvature_metric(), meshGEdgeTargetNumberOfPoints(), meshGEdge::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), F_Transfinite::operator()(), parBoundsOnFace(), refineProjection(), reparamMeshVertexOnEdge(), secondDer(), GFace::setMeshMaster(), DistanceField::update(), writeGEO(), and XYZToU().
parBoundsOnFace()
virtual Range<double> GEdge::parBoundsOnFace (GFace * face = nullptr) const inline virtual
Definition at line 223 of file GEdge.h.
Referenced by buildConsecutiveListOfVertices(), meshGeneratorPeriodic(), and trueBoundary().
parFromPoint()
double GEdge::parFromPoint (const SPoint3 & P) const virtual
Definition at line 595 of file GEdge.cpp.
Referenced by copyMesh(), createPoints(), filterPoints(), getAllParameters(), relocateSlaveVertices(), and reparamMeshVertexOnEdge().
periodic()
virtual bool GEdge::periodic (int dim) const inline virtual
Reimplemented from GEntity.
Definition at line 219 of file GEdge.h.
Referenced by discreteEdge::curvature(), gmshEdge::discretize(), getEdgeVerticesOnGeo(), discreteEdge::minimumMeshSegments(), and gmshEdge::reparamOnFace().
point()
virtual GPoint GEdge::point (double p) const pure virtual
Implemented in discreteEdge, gmshEdge, and xyEdge.
Referenced by quadMeshRemoveHalfOfOneDMesh::_subdivide(), bounds(), GFace::buildRepresentationCross(), closestPoint(), copyMesh(), blyr_manager::extrude_vertices_on_edges(), fillPointCloud(), getEdgeVerticesOnGeo(), getOBB(), meshGeneratorPeriodic(), meshGEdge::operator()(), curveFunctorGEdge::operator()(), F_LcB::operator()(), F_Lc::operator()(), F_Lc_aniso::operator()(), drawGEdge::operator()(), BoundaryLayerField::operator()(), position(), relocateMeshVertices(), relocateSlaveVertices(), reparamOnFace(), GFace::setMeshMaster(), DistanceField::update(), and writeGEO().
position()
virtual SVector3 GEdge::position (double p) const inline virtual
Definition at line 128 of file GEdge.h.
Referenced by _discretize(), closestPoint(), goldenSectionSearch(), meshGEdgeProcessing(), refineProjection(), and XYZToU().
prescribedMeshSizeAtParam()
double GEdge::prescribedMeshSizeAtParam (double u)
Definition at line 979 of file GEdge.cpp.
prescribedMeshSizeAtVertex()
double GEdge::prescribedMeshSizeAtVertex () const inline
Definition at line 175 of file GEdge.h.
refineProjection()
bool GEdge::refineProjection (const SVector3 & Q, double & u, int MaxIter, double relax, double tol, double & err) const virtual
Definition at line 604 of file GEdge.cpp.
Referenced by XYZToU().
regions()
std::list< GRegion * > GEdge::regions () const virtual
Reimplemented from GEntity.
Definition at line 692 of file GEdge.cpp.
Referenced by isOrphan().
relocateMeshVertices()
void GEdge::relocateMeshVertices () virtual
Reimplemented from GEntity.
Definition at line 714 of file GEdge.cpp.
removeElement()
void GEdge::removeElement (int type, MElement * e) virtual
Reimplemented from GEntity.
Definition at line 784 of file GEdge.cpp.
removeElements()
void GEdge::removeElements (int type) virtual
Reimplemented from GEntity.
Definition at line 797 of file GEdge.cpp.
reorder()
bool GEdge::reorder (const int elementType, const std::vector< std::size_t > & ordering) virtual
Reimplemented from GEntity.
Definition at line 947 of file GEdge.cpp.
reparamOnFace()
SPoint2 GEdge::reparamOnFace (const GFace * face, double epar, int dir) const virtual
Reimplemented in discreteEdge, gmshEdge, and xyEdge.
Definition at line 482 of file GEdge.cpp.
Referenced by buildConsecutiveListOfVertices(), getAllParameters(), max_surf_curvature(), meshGeneratorPeriodic(), metric_based_on_surface_curvature(), reparamMeshVertexOnFace(), gmshEdge::reparamOnFace(), transferSeamGEdgesVerticesToGFace(), and trueBoundary().
resetMeshAttributes()
void GEdge::resetMeshAttributes () virtual
Reimplemented from GEntity.
Reimplemented in gmshEdge.
Definition at line 187 of file GEdge.cpp.
Referenced by GEdge(), and GEO_Internals::synchronize().
reverse()
void GEdge::reverse ()
Definition at line 140 of file GEdge.cpp.
secondDer()
SVector3 GEdge::secondDer (double par) const virtual
Reimplemented in gmshEdge, and xyEdge.
Definition at line 460 of file GEdge.cpp.
Referenced by curvature().
setBeginVertex()
void GEdge::setBeginVertex (GVertex * gv) inline
Definition at line 61 of file GEdge.h.
Referenced by discreteEdge::createGeometry(), and createTopologyFromMesh1D().
setColor()
void GEdge::setColor (unsigned int val, bool recursive = false) virtual
Definition at line 286 of file GEdge.cpp.
setEndVertex()
void GEdge::setEndVertex (GVertex * gv) inline
Definition at line 62 of file GEdge.h.
Referenced by discreteEdge::createGeometry(), and createTopologyFromMesh1D().
setLength()
void GEdge::setLength (const double l) inline
Definition at line 171 of file GEdge.h.
Referenced by meshGEdgeProcessing().
setMeshMaster() [1/2]
void GEdge::setMeshMaster (GEdge * master, const std::vector< double > & tfo)
Definition at line 89 of file GEdge.cpp.
Referenced by addPeriodicEdge(), MeshExtrudedCurve(), and GFace::setMeshMaster().
setMeshMaster() [2/2]
void GEdge::setMeshMaster (GEdge * master, int sign)
Definition at line 65 of file GEdge.cpp.
setMeshSizeParametric()
void GEdge::setMeshSizeParametric (const std::vector< double > u, const std::vector< double > lc)
Definition at line 998 of file GEdge.cpp.
Referenced by setMeshSizeFromCurvePoints().
setTooSmall()
void GEdge::setTooSmall (bool const b) inline
Definition at line 183 of file GEdge.h.
Referenced by meshGEdgeProcessing(), and GEO_Internals::synchronize().
setVertex()
void GEdge::setVertex (GVertex *const f, const int orientation) inline
Definition at line 65 of file GEdge.h.
setVisibility()
void GEdge::setVisibility (char val, bool recursive = false) virtual
Reimplemented from GEntity.
Definition at line 277 of file GEdge.cpp.
storeSTLAsMesh()
bool GEdge::storeSTLAsMesh ()
Definition at line 425 of file GEdge.cpp.
vertices()
std::vector< GVertex * > GEdge::vertices () const virtual
Reimplemented from GEntity.
Definition at line 971 of file GEdge.cpp.
Referenced by discreteEdge::createGeometry(), getOBB(), and transferSeamGEdgesVerticesToGFace().
writeGEO()
void GEdge::writeGEO (FILE * fp) virtual
Reimplemented in gmshEdge.
Definition at line 354 of file GEdge.cpp.
writePY()
void GEdge::writePY (FILE * fp) virtual
Definition at line 405 of file GEdge.cpp.
XYZToU()
bool GEdge::XYZToU (const double X, const double Y, const double Z, double & U, const double relax = 1, bool first = true) const virtual
Definition at line 640 of file GEdge.cpp.
Referenced by containsPoint(), and parFromPoint().
Member Data Documentation
_cp
closestPointFinder* GEdge::_cp private
Definition at line 30 of file GEdge.h.
Referenced by closestPointWithTol(), and ~GEdge().
_faces
std::vector<GFace *> GEdge::_faces protected
Definition at line 36 of file GEdge.h.
Referenced by addFace(), delFace(), faces(), getAdditionalInfoString(), numFaces(), and regions().
_lc
std::vector<double> GEdge::_lc private
Definition at line 32 of file GEdge.h.
Referenced by prescribedMeshSizeAtParam(), and setMeshSizeParametric().
_length
double GEdge::_length private
Definition at line 28 of file GEdge.h.
Referenced by length(), and setLength().
_tooSmall
bool GEdge::_tooSmall private
Definition at line 29 of file GEdge.h.
Referenced by isMeshDegenerated(), and setTooSmall().
_u_lc
std::vector<double> GEdge::_u_lc private
Definition at line 32 of file GEdge.h.
Referenced by prescribedMeshSizeAtParam(), and setMeshSizeParametric().
_v0
GVertex* GEdge::_v0 protected
Definition at line 35 of file GEdge.h.
Referenced by GEdge(), getAdditionalInfoString(), getBeginVertex(), isMeshDegenerated(), periodic(), gmshEdge::resetNativePtr(), reverse(), setBeginVertex(), setColor(), setVertex(), setVisibility(), and ~GEdge().
_v1
GVertex * GEdge::_v1 protected
Definition at line 35 of file GEdge.h.
Referenced by GEdge(), getAdditionalInfoString(), getEndVertex(), isMeshDegenerated(), periodic(), gmshEdge::resetNativePtr(), reverse(), setColor(), setEndVertex(), setVertex(), setVisibility(), and ~GEdge().
coeffTransfinite
double GEdge::coeffTransfinite
Definition at line 251 of file GEdge.h.
Referenced by F_Transfinite::operator()(), and QuadqsContextUpdater::QuadqsContextUpdater().
compoundCurve
GEdge* GEdge::compoundCurve
Definition at line 47 of file GEdge.h.
extrude
ExtrudeParams* GEdge::extrude
Definition at line 257 of file GEdge.h.
Referenced by copyMesh(), extrudeMesh(), Mesh2DWithBoundaryLayers(), and MeshExtrudedCurve().
lines
std::vector<MLine *> GEdge::lines
Definition at line 42 of file GEdge.h.
Referenced by initMeshGEdge::_estimateNumLines(), _getEntitiesForElementTypes(), GModel::_storeElementsInEntities(), frameSolver2d::addBeamsOrBars(), addLine(), blyr_manager::classify_ridges(), classifyFaces(), copy_elements(), copyMesh(), createElements(), discreteEdge::createGeometry(), createTopologyFromMesh2D(), deleteMesh(), ensureSimplyConnectedEdge(), GMSH_CrackPlugin::execute(), GMSH_MeshSubEntitiesPlugin::execute(), blyr_manager::extrude_ridges(), blyr_manager::extrude_ridges_on_faces(), blyr_manager::extrude_vertices_on_edges(), extrudeMesh(), GeomMeshMatcher::forceTomatch(), getAcuteCorners(), getBoundaryFromMesh(), getGEdge(), getMeshElement(), getMeshElementByType(), getNumMeshElements(), getNumMeshElementsByType(), getNumMeshParentElements(), getStartElementType(), meshPolygon(), modifyInitialMeshForBoundaryLayers(), meshGEdge::operator()(), initMeshGEdge::operator()(), drawMeshGEdge::operator()(), optimize1DMeshAtAcuteCorners(), DocRecord::printMedialAxis(), ExtendField::recomputeCurves(), recoverEdge(), removeElement(), removeElements(), reorder(), reverse(), setHighOrder(), storeSTLAsMesh(), Subdivide(), transferSeamGEdgesVerticesToGFace(), and ghostEdge::~ghostEdge().
masterOrientation
int GEdge::masterOrientation
Definition at line 40 of file GEdge.h.
Referenced by meshGEdge::operator()(), and setMeshMaster().
meshAttributes
struct { ... } GEdge::meshAttributes
Referenced by copyMesh(), extrudeMesh(), filterPoints(), getAdditionalInfoString(), GModel::getMeshStatus(), mesh(), Mesh2DWithBoundaryLayers(), MeshExtrudedCurve(), meshGEdgeProcessing(), gmshEdge::minimumMeshSegments(), meshGEdge::operator()(), orientMeshGEdge::operator()(), F_Transfinite::operator()(), prescribedMeshSizeAtVertex(), QuadqsContextUpdater::QuadqsContextUpdater(), gmshEdge::resetMeshAttributes(), resetMeshAttributes(), gmshFace::resetNativePtr(), gmshEdge::writeGEO(), and writeGEO().
meshSize
double GEdge::meshSize
Definition at line 252 of file GEdge.h.
Referenced by QuadqsContextUpdater::QuadqsContextUpdater().
meshSizeFactor
double GEdge::meshSizeFactor
Definition at line 252 of file GEdge.h.
Referenced by QuadqsContextUpdater::QuadqsContextUpdater().
meshStatistics
struct { ... } GEdge::meshStatistics
Referenced by GEdge(), GModel::getMeshStatus(), mesh(), Mesh1D(), MeshExtrudedCurve(), meshGEdge::operator()(), and deMeshGEdge::operator()().
method
char GEdge::method
Definition at line 250 of file GEdge.h.
Referenced by filterPoints(), GModel::getMeshStatus(), meshGEdgeProcessing(), meshGEdge::operator()(), and QuadqsContextUpdater::QuadqsContextUpdater().
minimumMeshSegments
int GEdge::minimumMeshSegments
Definition at line 255 of file GEdge.h.
Referenced by meshGEdgeProcessing(), QuadqsContextUpdater::QuadqsContextUpdater(), and gmshFace::resetNativePtr().
nbPointsTransfinite
int GEdge::nbPointsTransfinite
Definition at line 253 of file GEdge.h.
Referenced by meshGEdgeProcessing(), F_Transfinite::operator()(), and QuadqsContextUpdater::QuadqsContextUpdater().
reverseMesh
bool GEdge::reverseMesh
Definition at line 259 of file GEdge.h.
Referenced by orientMeshGEdge::operator()(), and QuadqsContextUpdater::QuadqsContextUpdater().
status
GEntity::MeshGenerationStatus GEdge::status mutable
Definition at line 263 of file GEdge.h.
Referenced by GModel::getMeshStatus(), mesh(), Mesh1D(), MeshExtrudedCurve(), meshGEdge::operator()(), and deMeshGEdge::operator()().
stl_vertices_xyz
std::vector<SPoint3> GEdge::stl_vertices_xyz
Definition at line 50 of file GEdge.h.
Referenced by storeSTLAsMesh().
typeTransfinite
int GEdge::typeTransfinite
Definition at line 254 of file GEdge.h.
Referenced by meshGEdgeProcessing(), F_Transfinite::operator()(), and QuadqsContextUpdater::QuadqsContextUpdater().
The documentation for this class was generated from the following files:
src/geo/GEdge.h
src/geo/GEdge.cpp