gmsh-TingyuanDoc: groupOfElements Class Reference
groupOfElements Class Reference
#include <groupOfElements.h>
Public Types
typedef std::set< MElement * > elementContainer
typedef std::set< MVertex * > vertexContainer
Public Member Functions
groupOfElements ()
groupOfElements (int dim, int physical)
groupOfElements (GFace *)
groupOfElements (GRegion *)
groupOfElements (std::vector< MElement * > &elems)
virtual ~groupOfElements ()
virtual void addPhysical (int dim, int physical)
virtual void addElementary (GEntity *ge, const elementFilter &f)
virtual void addPhysical (int dim, int physical, const elementFilter &)
vertexContainer::const_iterator vbegin () const
vertexContainer::const_iterator vend () const
elementContainer::const_iterator begin () const
elementContainer::const_iterator end () const
size_t size () const
size_t vsize () const
bool find (MElement *e) const
bool find (MVertex *v) const
void insert (MElement *e)
void clearAll ()
Protected Attributes
vertexContainer _vertices
elementContainer _elements
elementContainer _parents
Detailed Description
Definition at line 24 of file groupOfElements.h.
Member Typedef Documentation
elementContainer
typedef std::set<MElement *> groupOfElements::elementContainer
Definition at line 26 of file groupOfElements.h.
vertexContainer
typedef std::set<MVertex *> groupOfElements::vertexContainer
Definition at line 27 of file groupOfElements.h.
Constructor & Destructor Documentation
groupOfElements() [1/5]
groupOfElements::groupOfElements () inline
Definition at line 35 of file groupOfElements.h.
groupOfElements() [2/5]
groupOfElements::groupOfElements (int dim, int physical) inline
Definition at line 36 of file groupOfElements.h.
groupOfElements() [3/5]
groupOfElements::groupOfElements (GFace * gf)
Definition at line 10 of file groupOfElements.cpp.
groupOfElements() [4/5]
groupOfElements::groupOfElements (GRegion * gr)
Definition at line 16 of file groupOfElements.cpp.
groupOfElements() [5/5]
groupOfElements::groupOfElements (std::vector< MElement * > & elems)
Definition at line 22 of file groupOfElements.cpp.
~groupOfElements()
virtual groupOfElements::~groupOfElements () inline virtual
Definition at line 41 of file groupOfElements.h.
Member Function Documentation
addElementary()
void groupOfElements::addElementary (GEntity * ge, const elementFilter & f) virtual
Definition at line 34 of file groupOfElements.cpp.
Referenced by addPhysical(), and groupOfElements().
addPhysical() [1/2]
virtual void groupOfElements::addPhysical (int dim, int physical) inline virtual
Definition at line 43 of file groupOfElements.h.
Referenced by groupOfElements().
addPhysical() [2/2]
void groupOfElements::addPhysical (int dim, int physical, const elementFilter & filter) virtual
Definition at line 44 of file groupOfElements.cpp.
begin()
elementContainer::const_iterator groupOfElements::begin () const inline
Definition at line 55 of file groupOfElements.h.
Referenced by femTerm< scalar >::addToMatrix(), femTerm< scalar >::addToRightHandSide(), groupOfLagMultElements::fillElementContainer(), and FilterElementsCutByLevelSet::FilterElementsCutByLevelSet().
clearAll()
void groupOfElements::clearAll () inline
Definition at line 89 of file groupOfElements.h.
end()
elementContainer::const_iterator groupOfElements::end () const inline
Definition at line 56 of file groupOfElements.h.
Referenced by femTerm< scalar >::addToMatrix(), femTerm< scalar >::addToRightHandSide(), groupOfLagMultElements::fillElementContainer(), and FilterElementsCutByLevelSet::FilterElementsCutByLevelSet().
find() [1/2]
bool groupOfElements::find (MElement * e) const inline
Definition at line 62 of file groupOfElements.h.
Referenced by femTerm< scalar >::addToMatrix(), and groupOfLagMultElements::fillElementContainer().
find() [2/2]
bool groupOfElements::find (MVertex * v) const inline
Definition at line 70 of file groupOfElements.h.
insert()
void groupOfElements::insert (MElement * e) inline
Definition at line 72 of file groupOfElements.h.
Referenced by addElementary(), groupOfLagMultElements::fillElementContainer(), and groupOfElements().
size()
size_t groupOfElements::size () const inline
Definition at line 58 of file groupOfElements.h.
vbegin()
vertexContainer::const_iterator groupOfElements::vbegin () const inline
Definition at line 53 of file groupOfElements.h.
vend()
vertexContainer::const_iterator groupOfElements::vend () const inline
Definition at line 54 of file groupOfElements.h.
vsize()
size_t groupOfElements::vsize () const inline
Definition at line 59 of file groupOfElements.h.
Member Data Documentation
_elements
elementContainer groupOfElements::_elements protected
Definition at line 31 of file groupOfElements.h.
Referenced by begin(), clearAll(), end(), find(), insert(), and size().
_parents
elementContainer groupOfElements::_parents protected
Definition at line 32 of file groupOfElements.h.
Referenced by clearAll(), find(), and insert().
_vertices
vertexContainer groupOfElements::_vertices protected
Definition at line 30 of file groupOfElements.h.
Referenced by clearAll(), find(), insert(), vbegin(), vend(), and vsize().
The documentation for this class was generated from the following files:
src/solver/groupOfElements.h
src/solver/groupOfElements.cpp