gmsh-TingyuanDoc: xFemFunctionSpace< T > Class Template Reference
xFemFunctionSpace< T > Class Template Reference
#include <functionSpace.h>
Public Types
typedef TensorialTraits< T >::ValType ValType
typedef TensorialTraits< T >::GradType GradType
typedef TensorialTraits< T >::HessType HessType
Public Types inherited from FunctionSpace< T >
typedef TensorialTraits< T >::ValType ValType
typedef TensorialTraits< T >::GradType GradType
typedef TensorialTraits< T >::HessType HessType
typedef TensorialTraits< T >::ThirdDevType ThirdDevType
Public Member Functions
virtual void hessfuvw (MElement *ele, double u, double v, double w, std::vector< HessType > &hess) const
xFemFunctionSpace (FunctionSpace< T > *spacebase, simpleFunctionOnElement< double > *funcEnrichment)
virtual void f (MElement *ele, double u, double v, double w, std::vector< ValType > &vals) const
virtual void gradf (MElement *ele, double u, double v, double w, std::vector< GradType > &grads) const
virtual int getNumKeys (MElement *ele) const
virtual void getKeys (MElement *ele, std::vector< Dof > &keys) const
Public Member Functions inherited from FunctionSpace< T >
virtual int getId (void) const
virtual void fuvw (MElement *ele, double u, double v, double w, std::vector< ValType > &vals) const
virtual void gradfuvw (MElement *ele, double u, double v, double w, std::vector< GradType > &grads) const
virtual void hessf (MElement *ele, double u, double v, double w, std::vector< HessType > &hess) const
virtual void thirdDevfuvw (MElement *ele, double u, double v, double w, std::vector< ThirdDevType > &third) const
virtual void thirdDevf (MElement *ele, double u, double v, double w, std::vector< ThirdDevType > &third) const
Public Member Functions inherited from FunctionSpaceBase
virtual ~FunctionSpaceBase ()
virtual void getKeysOnVertex (MElement *ele, MVertex *v, const std::vector< int > &comp, std::vector< Dof > &keys) const
virtual FunctionSpaceBase * clone (const int id) const
Protected Attributes
FunctionSpace< T > * _spacebase
simpleFunctionOnElement< double > * _funcEnrichment
Protected Attributes inherited from FunctionSpace< T >
int _iField
Detailed Description
template<class T>
class xFemFunctionSpace< T >
Definition at line 620 of file functionSpace.h.
Member Typedef Documentation
GradType
template<class T > typedef TensorialTraits<T>::GradType xFemFunctionSpace< T >::GradType
Definition at line 623 of file functionSpace.h.
HessType
template<class T > typedef TensorialTraits<T>::HessType xFemFunctionSpace< T >::HessType
Definition at line 624 of file functionSpace.h.
ValType
template<class T > typedef TensorialTraits<T>::ValType xFemFunctionSpace< T >::ValType
Definition at line 622 of file functionSpace.h.
Constructor & Destructor Documentation
xFemFunctionSpace()
template<class T > xFemFunctionSpace< T >::xFemFunctionSpace (FunctionSpace< T > * spacebase, simpleFunctionOnElement< double > * funcEnrichment) inline
Definition at line 635 of file functionSpace.h.
Member Function Documentation
f()
template<class T > void xFemFunctionSpace< T >::f (MElement * ele, double u, double v, double w, std::vector< ValType > & vals) const virtual
Implements FunctionSpace< T >.
Definition at line 677 of file functionSpace.h.
Referenced by xFemFunctionSpace< T >::f(), and xFemFunctionSpace< T >::gradf().
getKeys()
template<class T > void xFemFunctionSpace< T >::getKeys (MElement * ele, std::vector< Dof > & keys) const virtual
Implements FunctionSpace< T >.
Definition at line 767 of file functionSpace.h.
Referenced by xFemFunctionSpace< T >::getKeys().
getNumKeys()
template<class T > int xFemFunctionSpace< T >::getNumKeys (MElement * ele) const virtual
Implements FunctionSpace< T >.
Definition at line 755 of file functionSpace.h.
Referenced by xFemFunctionSpace< T >::getKeys(), and xFemFunctionSpace< T >::getNumKeys().
gradf()
template<class T > void xFemFunctionSpace< T >::gradf (MElement * ele, double u, double v, double w, std::vector< GradType > & grads) const virtual
Implements FunctionSpace< T >.
Definition at line 710 of file functionSpace.h.
Referenced by xFemFunctionSpace< T >::gradf().
hessfuvw()
template<class T > virtual void xFemFunctionSpace< T >::hessfuvw (MElement * ele, double u, double v, double w, std::vector< HessType > & hess) const inline virtual
Implements FunctionSpace< T >.
Definition at line 631 of file functionSpace.h.
Member Data Documentation
_funcEnrichment
template<class T > simpleFunctionOnElement<double>* xFemFunctionSpace< T >::_funcEnrichment protected
Definition at line 628 of file functionSpace.h.
_spacebase
template<class T > FunctionSpace<T>* xFemFunctionSpace< T >::_spacebase protected
Definition at line 627 of file functionSpace.h.
The documentation for this class was generated from the following file:
src/solver/functionSpace.h