gmsh-TingyuanDoc: gmshSurface Class Reference
gmshSurface Class Reference abstract
#include <gmshSurface.h>
Public Types
enum gmshSurfaceType {
Plane, Nurbs, Cylinder, Sphere,
Cone, Torus, ParametricSurface, PolarSphere
}
Public Member Functions
virtual ~gmshSurface ()
virtual Range< double > parBounds (int i) const =0
virtual gmshSurface::gmshSurfaceType geomType () const =0
virtual SPoint3 point (double par1, double par2) const =0
virtual SPoint3 point (const SPoint2 &p) const
virtual SPoint2 parFromPoint (double x, double y, double z)
virtual SVector3 normal (const SPoint2 &param) const
virtual Pair< SVector3, SVector3 > firstDer (const SPoint2 &param)
virtual double getMetricEigenvalue (const SPoint2 &)
Static Public Member Functions
static void reset ()
static int maxTag ()
static gmshSurface * getSurface (int tag)
Public Attributes
bool vertex_defined_on_surface
Static Protected Attributes
static std::map< int, gmshSurface * > allGmshSurfaces
Detailed Description
Definition at line 22 of file gmshSurface.h.
Member Enumeration Documentation
gmshSurfaceType
enum gmshSurface::gmshSurfaceType
Enumerator
Plane
Nurbs
Cylinder
Sphere
Cone
Torus
ParametricSurface
PolarSphere
Definition at line 47 of file gmshSurface.h.
Constructor & Destructor Documentation
~gmshSurface()
virtual gmshSurface::~gmshSurface () inline virtual
Definition at line 29 of file gmshSurface.h.
Member Function Documentation
firstDer()
Pair< SVector3, SVector3 > gmshSurface::firstDer (const SPoint2 & param) virtual
Definition at line 26 of file gmshSurface.cpp.
geomType()
virtual gmshSurface::gmshSurfaceType gmshSurface::geomType () const pure virtual
Implemented in gmshParametricSurface, gmshPolarSphere, and gmshSphere.
getMetricEigenvalue()
double gmshSurface::getMetricEigenvalue (const SPoint2 &) virtual
Reimplemented in gmshPolarSphere.
Definition at line 32 of file gmshSurface.cpp.
Referenced by gmshFace::getMetricEigenvalue().
getSurface()
gmshSurface * gmshSurface::getSurface (int tag) static
Definition at line 51 of file gmshSurface.cpp.
maxTag()
static int gmshSurface::maxTag () inline static
Definition at line 38 of file gmshSurface.h.
normal()
SVector3 gmshSurface::normal (const SPoint2 & param) const virtual
Reimplemented in gmshPolarSphere, and gmshSphere.
Definition at line 20 of file gmshSurface.cpp.
parBounds()
virtual Range<double> gmshSurface::parBounds (int i) const pure virtual
Implemented in gmshParametricSurface, gmshPolarSphere, and gmshSphere.
parFromPoint()
SPoint2 gmshSurface::parFromPoint (double x, double y, double z) virtual
Definition at line 13 of file gmshSurface.cpp.
point() [1/2]
virtual SPoint3 gmshSurface::point (const SPoint2 & p) const inline virtual
Definition at line 59 of file gmshSurface.h.
Referenced by point().
point() [2/2]
virtual SPoint3 gmshSurface::point (double par1, double par2) const pure virtual
Implemented in gmshParametricSurface, gmshPolarSphere, and gmshSphere.
Referenced by CreateVertex(), InterpolateBezier(), InterpolateSurface(), InterpolateUBS(), gmshSphere::normal(), and gmshPolarSphere::normal().
reset()
static void gmshSurface::reset () inline static
Definition at line 30 of file gmshSurface.h.
Referenced by GModel::destroy().
Member Data Documentation
allGmshSurfaces
std::map< int, gmshSurface * > gmshSurface::allGmshSurfaces static protected
Definition at line 24 of file gmshSurface.h.
Referenced by getSurface(), maxTag(), gmshParametricSurface::NewParametricSurface(), gmshPolarSphere::NewPolarSphere(), gmshSphere::NewSphere(), and reset().
vertex_defined_on_surface
bool gmshSurface::vertex_defined_on_surface
Definition at line 28 of file gmshSurface.h.
Referenced by CreateVertex().
The documentation for this class was generated from the following files:
src/geo/gmshSurface.h
src/geo/gmshSurface.cpp