gmsh-TingyuanDoc: linearSystemFull< scalar > Class Template Reference
linearSystemFull< scalar > Class Template Reference
#include <linearSystemFull.h>
Public Member Functions
linearSystemFull ()
virtual bool isAllocated () const
virtual void allocate (int nbRows)
virtual ~linearSystemFull ()
virtual void clear ()
virtual void addToMatrix (int row, int col, const scalar &val)
virtual void getFromMatrix (int row, int col, scalar &val) const
virtual void addToRightHandSide (int row, const scalar &val, int ith=0)
virtual void addToSolution (int row, const scalar &val)
virtual void getFromRightHandSide (int row, scalar &val) const
virtual void getFromSolution (int row, scalar &val) const
virtual void zeroMatrix ()
virtual void zeroRightHandSide ()
virtual void zeroSolution ()
virtual double normInfRightHandSide () const
virtual int systemSolve ()
Public Member Functions inherited from linearSystem< scalar >
linearSystem ()
virtual ~linearSystem ()
Public Member Functions inherited from linearSystemBase
virtual ~linearSystemBase ()
virtual void preAllocateEntries ()
virtual int matMult ()
void setParameter (const std::string &key, std::string value)
std::string getParameter (const std::string &key) const
virtual void insertInSparsityPattern (int _row, int _col)
virtual double normInfSolution () const
Private Attributes
fullMatrix< scalar > * _a
fullVector< scalar > * _b
fullVector< scalar > * _x
Additional Inherited Members
Protected Attributes inherited from linearSystemBase
std::map< std::string, std::string > _parameters
Detailed Description
template<class scalar>
class linearSystemFull< scalar >
Definition at line 17 of file linearSystemFull.h.
Constructor & Destructor Documentation
linearSystemFull()
template<class scalar > linearSystemFull< scalar >::linearSystemFull () inline
Definition at line 23 of file linearSystemFull.h.
~linearSystemFull()
template<class scalar > virtual linearSystemFull< scalar >::~linearSystemFull () inline virtual
Definition at line 32 of file linearSystemFull.h.
Member Function Documentation
addToMatrix()
template<class scalar > virtual void linearSystemFull< scalar >::addToMatrix (int row, int col, const scalar & val) inline virtual
Implements linearSystem< scalar >.
Definition at line 42 of file linearSystemFull.h.
Referenced by computeParametrization().
addToRightHandSide()
template<class scalar > virtual void linearSystemFull< scalar >::addToRightHandSide (int row, const scalar & val, int ith = 0) inline virtual
Implements linearSystem< scalar >.
Definition at line 50 of file linearSystemFull.h.
Referenced by computeParametrization().
addToSolution()
template<class scalar > virtual void linearSystemFull< scalar >::addToSolution (int row, const scalar & val) inline virtual
Implements linearSystem< scalar >.
Definition at line 54 of file linearSystemFull.h.
allocate()
template<class scalar > virtual void linearSystemFull< scalar >::allocate (int nbRows) inline virtual
Implements linearSystemBase.
Definition at line 25 of file linearSystemFull.h.
Referenced by computeParametrization().
clear()
template<class scalar > virtual void linearSystemFull< scalar >::clear () inline virtual
Implements linearSystemBase.
Definition at line 33 of file linearSystemFull.h.
Referenced by linearSystemFull< scalar >::allocate(), and linearSystemFull< scalar >::~linearSystemFull().
getFromMatrix()
template<class scalar > virtual void linearSystemFull< scalar >::getFromMatrix (int row, int col, scalar & val) const inline virtual
Implements linearSystem< scalar >.
Definition at line 46 of file linearSystemFull.h.
getFromRightHandSide()
template<class scalar > virtual void linearSystemFull< scalar >::getFromRightHandSide (int row, scalar & val) const inline virtual
Implements linearSystem< scalar >.
Definition at line 58 of file linearSystemFull.h.
getFromSolution()
template<class scalar > virtual void linearSystemFull< scalar >::getFromSolution (int row, scalar & val) const inline virtual
Implements linearSystem< scalar >.
Definition at line 62 of file linearSystemFull.h.
Referenced by computeParametrization().
isAllocated()
template<class scalar > virtual bool linearSystemFull< scalar >::isAllocated () const inline virtual
Implements linearSystemBase.
Definition at line 24 of file linearSystemFull.h.
normInfRightHandSide()
template<class scalar > virtual double linearSystemFull< scalar >::normInfRightHandSide () const inline virtual
Implements linearSystemBase.
Definition at line 66 of file linearSystemFull.h.
systemSolve()
template<class scalar > virtual int linearSystemFull< scalar >::systemSolve () inline virtual
Implements linearSystemBase.
Definition at line 77 of file linearSystemFull.h.
Referenced by computeParametrization(), GMSH_DistancePlugin::execute(), propagateValuesOnFace(), frameSolver2d::solve(), thermicSolver::solve(), and elasticitySolver::solve().
zeroMatrix()
template<class scalar > virtual void linearSystemFull< scalar >::zeroMatrix () inline virtual
Implements linearSystemBase.
Definition at line 63 of file linearSystemFull.h.
zeroRightHandSide()
template<class scalar > virtual void linearSystemFull< scalar >::zeroRightHandSide () inline virtual
Implements linearSystemBase.
Definition at line 64 of file linearSystemFull.h.
Referenced by computeParametrization().
zeroSolution()
template<class scalar > virtual void linearSystemFull< scalar >::zeroSolution () inline virtual
Implements linearSystemBase.
Definition at line 65 of file linearSystemFull.h.
Member Data Documentation
_a
template<class scalar > fullMatrix<scalar>* linearSystemFull< scalar >::_a private
Definition at line 19 of file linearSystemFull.h.
Referenced by linearSystemFull< scalar >::allocate(), linearSystemFull< scalar >::clear(), linearSystemFull< scalar >::isAllocated(), linearSystemFull< scalar >::systemSolve(), and linearSystemFull< scalar >::zeroMatrix().
_b
template<class scalar > fullVector<scalar>* linearSystemFull< scalar >::_b private
Definition at line 20 of file linearSystemFull.h.
Referenced by linearSystemFull< scalar >::allocate(), linearSystemFull< scalar >::clear(), linearSystemFull< scalar >::normInfRightHandSide(), linearSystemFull< scalar >::systemSolve(), and linearSystemFull< scalar >::zeroRightHandSide().
_x
template<class scalar > fullVector<scalar> * linearSystemFull< scalar >::_x private
Definition at line 20 of file linearSystemFull.h.
Referenced by linearSystemFull< scalar >::allocate(), linearSystemFull< scalar >::clear(), linearSystemFull< scalar >::systemSolve(), and linearSystemFull< scalar >::zeroSolution().
The documentation for this class was generated from the following file:
src/solver/linearSystemFull.h