gmsh-TingyuanDoc: gLevelsetNACA00 Class Reference
gLevelsetNACA00 Class Reference
#include <gmshLevelset.h>
Public Member Functions
gLevelsetNACA00 (double x0, double y0, double c, double t)
~gLevelsetNACA00 ()
double operator() (double x, double y, double z) const
void gradient (double x, double y, double z, double &dfdx, double &dfdy, double &dfdz) const
void hessian (double x, double y, double z, double &dfdxx, double &dfdxy, double &dfdxz, double &dfdyx, double &dfdyy, double &dfdyz, double &dfdzx, double &dfdzy, double &dfdzz) const
int type () const
Public Member Functions inherited from gLevelsetPrimitive
gLevelsetPrimitive ()
gLevelsetPrimitive (const gLevelsetPrimitive &lv)
gLevelsetPrimitive (int tag)
std::vector< gLevelset * > getChildren () const
double choose (double d1, double d2) const
virtual bool isPrimitive () const
Public Member Functions inherited from gLevelset
gLevelset (int tag=0)
gLevelset (const gLevelset &)
virtual ~gLevelset ()
virtual gLevelset * clone () const
bool isInsideDomain (const double &x, const double &y, const double &z) const
bool isOutsideDomain (const double &x, const double &y, const double &z) const
bool isOnBorder (const double &x, const double &y, const double &z) const
void setTag (int t)
virtual int getTag () const
void getPrimitives (std::vector< gLevelset * > &primitives)
void getPrimitivesPO (std::vector< gLevelset * > &primitives)
void getRPN (std::vector< gLevelset * > &gLsRPN)
double H (const double &x, const double &y, const double &z) const
void print () const
Public Member Functions inherited from simpleFunction< double >
simpleFunction (double val=0.0)
virtual ~simpleFunction ()
virtual bool hasDerivatives ()
virtual void setElement (MElement *e) const
Private Member Functions
void getClosestBndPoint (const double x, const double y, const double z, double &xb, double &yb, double &curvRad, bool &in) const
Private Attributes
double _x0
double _y0
double _c
double _t
Additional Inherited Members
Static Public Member Functions inherited from gLevelset
static gLevelset * find (int tag)
static void add (gLevelset *l)
Protected Attributes inherited from gLevelset
int tag_
Protected Attributes inherited from simpleFunction< double >
double _val
bool _hasDerivatives
Static Protected Attributes inherited from gLevelset
static const short insideDomain = -1
static int maxTag_ = 0
static std::set< gLevelset *, gLevelsetLessThan > all_
Detailed Description
Definition at line 412 of file gmshLevelset.h.
Constructor & Destructor Documentation
gLevelsetNACA00()
gLevelsetNACA00::gLevelsetNACA00 (double x0, double y0, double c, double t)
Definition at line 1426 of file gmshLevelset.cpp.
~gLevelsetNACA00()
gLevelsetNACA00::~gLevelsetNACA00 () inline
Definition at line 417 of file gmshLevelset.h.
Member Function Documentation
getClosestBndPoint()
void gLevelsetNACA00::getClosestBndPoint (const double x, const double y, const double z, double & xb, double & yb, double & curvRad, bool & in) const private
Definition at line 1432 of file gmshLevelset.cpp.
Referenced by gradient(), hessian(), and operator()().
gradient()
void gLevelsetNACA00::gradient (double x, double y, double z, double & dfdx, double & dfdy, double & dfdz) const virtual
Reimplemented from simpleFunction< double >.
Definition at line 1498 of file gmshLevelset.cpp.
hessian()
void gLevelsetNACA00::hessian (double x, double y, double z, double & dfdxx, double & dfdxy, double & dfdxz, double & dfdyx, double & dfdyy, double & dfdyz, double & dfdzx, double & dfdzy, double & dfdzz) const virtual
Reimplemented from simpleFunction< double >.
Definition at line 1513 of file gmshLevelset.cpp.
operator()()
double gLevelsetNACA00::operator() (double x, double y, double z) const virtual
Implements gLevelsetPrimitive.
Definition at line 1487 of file gmshLevelset.cpp.
type()
int gLevelsetNACA00::type () const inline virtual
Implements gLevelsetPrimitive.
Definition at line 424 of file gmshLevelset.h.
Member Data Documentation
_c
double gLevelsetNACA00::_c private
Definition at line 413 of file gmshLevelset.h.
Referenced by getClosestBndPoint().
_t
double gLevelsetNACA00::_t private
Definition at line 413 of file gmshLevelset.h.
Referenced by getClosestBndPoint().
_x0
double gLevelsetNACA00::_x0 private
Definition at line 413 of file gmshLevelset.h.
Referenced by getClosestBndPoint().
_y0
double gLevelsetNACA00::_y0 private
Definition at line 413 of file gmshLevelset.h.
Referenced by getClosestBndPoint().
The documentation for this class was generated from the following files:
src/geo/gmshLevelset.h
src/geo/gmshLevelset.cpp