gmsh-TingyuanDoc: GMSH_StreamLinesPlugin Class Reference
GMSH_StreamLinesPlugin Class Reference
#include <StreamLines.h>
Public Member Functions
GMSH_StreamLinesPlugin ()
std::string getName () const
std::string getShortHelp () const
std::string getHelp () const
int getNbOptions () const
StringXNumber * getOption (int iopt)
PView * execute (PView *)
Public Member Functions inherited from GMSH_PostPlugin
GMSH_PLUGIN_TYPE getType () const
virtual int run ()
virtual PView * executeRemote (PView *)
virtual PView * getView (int index, PView *view)
virtual PViewDataList * getDataList (PView *view, bool showError=true)
virtual PViewData * getPossiblyAdaptiveData (PView *view)
virtual void assignSpecificVisibility () const
virtual bool geometricalFilter (fullMatrix< double > *) const
Public Member Functions inherited from GMSH_Plugin
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
virtual int getNbOptionsStr () const
virtual StringXString * getOptionStr (int iopt)
std::string serialize ()
Static Public Member Functions
static int getNbU ()
static int getNbV ()
static void getPoint (int iU, int iV, double *X)
static double callbackX0 (int, int, double)
static double callbackY0 (int, int, double)
static double callbackZ0 (int, int, double)
static double callbackX1 (int, int, double)
static double callbackY1 (int, int, double)
static double callbackZ1 (int, int, double)
static double callbackX2 (int, int, double)
static double callbackY2 (int, int, double)
static double callbackZ2 (int, int, double)
static double callbackU (int, int, double)
static double callbackV (int, int, double)
static void draw (void *context)
Static Public Member Functions inherited from GMSH_Plugin
static void setDrawFunction (void(*fct)(void *))
Static Private Member Functions
static double callback (int num, int action, double value, double *opt, double step, double min, double max)
Additional Inherited Members
Public Types inherited from GMSH_Plugin
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Public Attributes inherited from GMSH_Plugin
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes inherited from GMSH_Plugin
static void(* draw)(void *) = nullptr
Detailed Description
Definition at line 15 of file StreamLines.h.
Constructor & Destructor Documentation
GMSH_StreamLinesPlugin()
GMSH_StreamLinesPlugin::GMSH_StreamLinesPlugin () inline
Definition at line 20 of file StreamLines.h.
Member Function Documentation
callback()
double GMSH_StreamLinesPlugin::callback (int num, int action, double value, double * opt, double step, double min, double max) static private
Definition at line 57 of file StreamLines.cpp.
Referenced by callbackU(), callbackV(), callbackX0(), callbackX1(), callbackX2(), callbackY0(), callbackY1(), callbackY2(), callbackZ0(), callbackZ1(), and callbackZ2().
callbackU()
double GMSH_StreamLinesPlugin::callbackU (int num, int action, double value) static
Definition at line 135 of file StreamLines.cpp.
callbackV()
double GMSH_StreamLinesPlugin::callbackV (int num, int action, double value) static
Definition at line 141 of file StreamLines.cpp.
callbackX0()
double GMSH_StreamLinesPlugin::callbackX0 (int num, int action, double value) static
Definition at line 72 of file StreamLines.cpp.
callbackX1()
double GMSH_StreamLinesPlugin::callbackX1 (int num, int action, double value) static
Definition at line 93 of file StreamLines.cpp.
callbackX2()
double GMSH_StreamLinesPlugin::callbackX2 (int num, int action, double value) static
Definition at line 114 of file StreamLines.cpp.
callbackY0()
double GMSH_StreamLinesPlugin::callbackY0 (int num, int action, double value) static
Definition at line 79 of file StreamLines.cpp.
callbackY1()
double GMSH_StreamLinesPlugin::callbackY1 (int num, int action, double value) static
Definition at line 100 of file StreamLines.cpp.
callbackY2()
double GMSH_StreamLinesPlugin::callbackY2 (int num, int action, double value) static
Definition at line 121 of file StreamLines.cpp.
callbackZ0()
double GMSH_StreamLinesPlugin::callbackZ0 (int num, int action, double value) static
Definition at line 86 of file StreamLines.cpp.
callbackZ1()
double GMSH_StreamLinesPlugin::callbackZ1 (int num, int action, double value) static
Definition at line 107 of file StreamLines.cpp.
callbackZ2()
double GMSH_StreamLinesPlugin::callbackZ2 (int num, int action, double value) static
Definition at line 128 of file StreamLines.cpp.
draw()
void GMSH_StreamLinesPlugin::draw (void * context) static
Definition at line 42 of file StreamLines.cpp.
execute()
PView * GMSH_StreamLinesPlugin::execute (PView * v) virtual
Implements GMSH_PostPlugin.
Definition at line 212 of file StreamLines.cpp.
getHelp()
std::string GMSH_StreamLinesPlugin::getHelp () const virtual
Implements GMSH_Plugin.
Definition at line 147 of file StreamLines.cpp.
getName()
std::string GMSH_StreamLinesPlugin::getName () const inline virtual
Implements GMSH_Plugin.
Definition at line 21 of file StreamLines.h.
getNbOptions()
int GMSH_StreamLinesPlugin::getNbOptions () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 174 of file StreamLines.cpp.
getNbU()
int GMSH_StreamLinesPlugin::getNbU () static
Definition at line 184 of file StreamLines.cpp.
Referenced by draw(), execute(), and getPoint().
getNbV()
int GMSH_StreamLinesPlugin::getNbV () static
Definition at line 189 of file StreamLines.cpp.
Referenced by draw(), execute(), and getPoint().
getOption()
StringXNumber * GMSH_StreamLinesPlugin::getOption (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 179 of file StreamLines.cpp.
getPoint()
void GMSH_StreamLinesPlugin::getPoint (int iU, int iV, double * X) static
Definition at line 194 of file StreamLines.cpp.
Referenced by draw(), and execute().
getShortHelp()
std::string GMSH_StreamLinesPlugin::getShortHelp () const inline virtual
Implements GMSH_Plugin.
Definition at line 22 of file StreamLines.h.
The documentation for this class was generated from the following files:
src/plugin/StreamLines.h
src/plugin/StreamLines.cpp