gmsh-TingyuanDoc: HierarchicalBasisHcurlTria Class Reference
HierarchicalBasisHcurlTria Class Reference
#include <HierarchicalBasisHcurlTria.h>
Public Member Functions
HierarchicalBasisHcurlTria (int order)
virtual ~HierarchicalBasisHcurlTria ()
virtual unsigned int getNumberOfOrientations () const
virtual void generateBasis (double const &u, double const &v, double const &w, std::vector< std::vector< double > > &vertexBasis, std::vector< std::vector< double > > &edgeBasis, std::vector< std::vector< double > > &faceBasis, std::vector< std::vector< double > > &bubbleBasis, std::string typeFunction)
virtual void orientEdge (int const &flagOrientation, int const &edgeNumber, std::vector< std::vector< double > > &edgeBasis, const std::vector< std::vector< double > > &eTablePositiveFlag, const std::vector< std::vector< double > > &eTableNegativeFlag)
virtual void orientEdgeFunctionsForNegativeFlag (std::vector< std::vector< double > > &edgeFunctions)
virtual void orientFace (int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, const std::vector< std::vector< double > > &quadFaceFunctionsAllOrientation, const std::vector< std::vector< double > > &triFaceFunctionsAllOrientation, std::vector< std::vector< double > > &fTableCopy)
virtual void getKeysInfo (std::vector< int > &functionTypeInfo, std::vector< int > &orderInfo)
Public Member Functions inherited from HierarchicalBasisHcurl
virtual ~HierarchicalBasisHcurl ()=0
virtual void generateBasis (double const &u, double const &v, double const &w, std::vector< double > &vertexBasis, std::vector< double > &edgeBasis, std::vector< double > &faceBasis, std::vector< double > &bubbleBasis)
virtual void orientFace (int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, const std::vector< double > &quadFaceFunctionsAllOrientations, const std::vector< double > &triFaceFunctionsAllOrientations, std::vector< double > &fTableCopy)
virtual void orientEdge (int const &flagOrientation, int const &edgeNumber, std::vector< double > &edgeFunctions, const std::vector< double > &eTablePositiveFlag, const std::vector< double > &eTableNegativeFlag)
virtual void orientEdgeFunctionsForNegativeFlag (std::vector< double > &edgeFunctions)
virtual void addAllOrientedFaceFunctions (double const &u, double const &v, double const &w, const std::vector< double > &faceFunctions, std::vector< double > &quadFaceFunctionsAllOrientations, std::vector< double > &triFaceFunctionsAllOrientations)
virtual void addAllOrientedFaceFunctions (double const &u, double const &v, double const &w, const std::vector< std::vector< double > > &faceFunctions, std::vector< std::vector< double > > &quadFaceFunctionsAllOrientations, std::vector< std::vector< double > > &triFaceFunctionsAllOrientations, std::string typeFunction)
Public Member Functions inherited from HierarchicalBasis
virtual ~HierarchicalBasis ()=0
int getnVertexFunction () const
int getnEdgeFunction () const
int getnTriFaceFunction () const
int getnQuadFaceFunction () const
int getnBubbleFunction () const
int getNumTriFace () const
int getNumQuadFace () const
int getNumEdge () const
int numberOrientationQuadFace (int const &flag1, int const &flag2, int const &flag3)
int numberOrientationTriFace (int const &flag1, int const &flag2)
Private Member Functions
virtual void generateHcurlBasis (double const &u, double const &v, double const &w, std::vector< std::vector< double > > &edgeBasis, std::vector< std::vector< double > > &faceBasis, std::vector< std::vector< double > > &bubbleBasis)
virtual void generateCurlBasis (double const &u, double const &v, double const &w, std::vector< std::vector< double > > &edgeBasis, std::vector< std::vector< double > > &faceBasis, std::vector< std::vector< double > > &bubbleBasis)
virtual void orientOneFace (double const &u, double const &v, double const &w, int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, std::vector< std::vector< double > > &faceFunctions, std::string typeFunction)
Static Private Member Functions
static double _affineCoordinate (int const &j, double const &u, double const &v)
static double dotProduct (const std::vector< double > &u, const std::vector< double > &v)
Private Attributes
int _pf
int _pOrderEdge [3]
Additional Inherited Members
Protected Member Functions inherited from HierarchicalBasisHcurl
virtual void orientOneFace (double const &u, double const &v, double const &w, int const &flag1, int const &flag2, int const &flag3, int const &faceNumber, std::vector< double > &faceFunctions)
Protected Attributes inherited from HierarchicalBasis
int _nvertex
int _nedge
int _nfaceQuad
int _nfaceTri
int _nVertexFunction
int _nEdgeFunction
int _nQuadFaceFunction
int _nTriFaceFunction
int _nBubbleFunction
Detailed Description
Definition at line 38 of file HierarchicalBasisHcurlTria.h.
Constructor & Destructor Documentation
HierarchicalBasisHcurlTria()
HierarchicalBasisHcurlTria::HierarchicalBasisHcurlTria (int order)
Definition at line 12 of file HierarchicalBasisHcurlTria.cpp.
~HierarchicalBasisHcurlTria()
HierarchicalBasisHcurlTria::~HierarchicalBasisHcurlTria () virtual
Definition at line 38 of file HierarchicalBasisHcurlTria.cpp.
Member Function Documentation
_affineCoordinate()
double HierarchicalBasisHcurlTria::_affineCoordinate (int const & j, double const & u, double const & v) static private
Definition at line 45 of file HierarchicalBasisHcurlTria.cpp.
Referenced by generateCurlBasis(), generateHcurlBasis(), and orientOneFace().
dotProduct()
double HierarchicalBasisHcurlTria::dotProduct (const std::vector< double > & u, const std::vector< double > & v) static private
Definition at line 32 of file HierarchicalBasisHcurlTria.cpp.
Referenced by generateCurlBasis(), and generateHcurlBasis().
generateBasis()
virtual void HierarchicalBasisHcurlTria::generateBasis (double const & u, double const & v, double const & w, std::vector< std::vector< double > > & vertexBasis, std::vector< std::vector< double > > & edgeBasis, std::vector< std::vector< double > > & faceBasis, std::vector< std::vector< double > > & bubbleBasis, std::string typeFunction) inline virtual
Implements HierarchicalBasisHcurl.
Definition at line 43 of file HierarchicalBasisHcurlTria.h.
generateCurlBasis()
void HierarchicalBasisHcurlTria::generateCurlBasis (double const & u, double const & v, double const & w, std::vector< std::vector< double > > & edgeBasis, std::vector< std::vector< double > > & faceBasis, std::vector< std::vector< double > > & bubbleBasis) private virtual
Definition at line 244 of file HierarchicalBasisHcurlTria.cpp.
Referenced by generateBasis().
generateHcurlBasis()
void HierarchicalBasisHcurlTria::generateHcurlBasis (double const & u, double const & v, double const & w, std::vector< std::vector< double > > & edgeBasis, std::vector< std::vector< double > > & faceBasis, std::vector< std::vector< double > > & bubbleBasis) private virtual
Definition at line 57 of file HierarchicalBasisHcurlTria.cpp.
Referenced by generateBasis().
getKeysInfo()
void HierarchicalBasisHcurlTria::getKeysInfo (std::vector< int > & functionTypeInfo, std::vector< int > & orderInfo) virtual
Implements HierarchicalBasisHcurl.
Definition at line 766 of file HierarchicalBasisHcurlTria.cpp.
getNumberOfOrientations()
unsigned int HierarchicalBasisHcurlTria::getNumberOfOrientations () const virtual
Implements HierarchicalBasis.
Definition at line 40 of file HierarchicalBasisHcurlTria.cpp.
orientEdge()
void HierarchicalBasisHcurlTria::orientEdge (int const & flagOrientation, int const & edgeNumber, std::vector< std::vector< double > > & edgeBasis, const std::vector< std::vector< double > > & eTablePositiveFlag, const std::vector< std::vector< double > > & eTableNegativeFlag) virtual
Implements HierarchicalBasisHcurl.
Definition at line 192 of file HierarchicalBasisHcurlTria.cpp.
orientEdgeFunctionsForNegativeFlag()
void HierarchicalBasisHcurlTria::orientEdgeFunctionsForNegativeFlag (std::vector< std::vector< double > > & edgeFunctions) virtual
Implements HierarchicalBasisHcurl.
Definition at line 223 of file HierarchicalBasisHcurlTria.cpp.
orientFace()
void HierarchicalBasisHcurlTria::orientFace (int const & flag1, int const & flag2, int const & flag3, int const & faceNumber, const std::vector< std::vector< double > > & quadFaceFunctionsAllOrientation, const std::vector< std::vector< double > > & triFaceFunctionsAllOrientation, std::vector< std::vector< double > > & fTableCopy) virtual
Implements HierarchicalBasisHcurl.
Definition at line 751 of file HierarchicalBasisHcurlTria.cpp.
orientOneFace()
void HierarchicalBasisHcurlTria::orientOneFace (double const & u, double const & v, double const & w, int const & flag1, int const & flag2, int const & flag3, int const & faceNumber, std::vector< std::vector< double > > & faceFunctions, std::string typeFunction) private virtual
Implements HierarchicalBasisHcurl.
Definition at line 427 of file HierarchicalBasisHcurlTria.cpp.
Member Data Documentation
_pf
int HierarchicalBasisHcurlTria::_pf private
Definition at line 77 of file HierarchicalBasisHcurlTria.h.
Referenced by generateCurlBasis(), generateHcurlBasis(), getKeysInfo(), HierarchicalBasisHcurlTria(), and orientOneFace().
_pOrderEdge
int HierarchicalBasisHcurlTria::_pOrderEdge[3] private
Definition at line 78 of file HierarchicalBasisHcurlTria.h.
Referenced by generateCurlBasis(), generateHcurlBasis(), getKeysInfo(), HierarchicalBasisHcurlTria(), orientEdge(), and orientEdgeFunctionsForNegativeFlag().
The documentation for this class was generated from the following files:
src/numeric/HierarchicalBasisHcurlTria.h
src/numeric/HierarchicalBasisHcurlTria.cpp