gmsh-TingyuanDoc: MTet4Factory Class Reference
MTet4Factory Class Reference
#include <meshGRegionDelaunayInsertion.h>
Public Types
typedef std::set< MTet4 *, compareTet4Ptr > container
typedef container::iterator iterator
Public Member Functions
MTet4Factory (int _size=1000000)
~MTet4Factory ()
MTet4 * Create (MTetrahedron *t, std::vector< double > &sizes, std::vector< double > &sizesBGM)
MTet4 * Create (MTetrahedron *t, std::vector< double > &sizes, std::vector< double > &sizesBGM, double lc1, double lc2)
void Free (MTet4 *t)
void changeTetRadius (iterator it, double r)
container & getAllTets ()
Private Attributes
container allTets
Detailed Description
Definition at line 230 of file meshGRegionDelaunayInsertion.h.
Member Typedef Documentation
container
typedef std::set<MTet4 *, compareTet4Ptr> MTet4Factory::container
Definition at line 232 of file meshGRegionDelaunayInsertion.h.
iterator
typedef container::iterator MTet4Factory::iterator
Definition at line 233 of file meshGRegionDelaunayInsertion.h.
Constructor & Destructor Documentation
MTet4Factory()
MTet4Factory::MTet4Factory (int _size = 1000000) inline
Definition at line 259 of file meshGRegionDelaunayInsertion.h.
~MTet4Factory()
MTet4Factory::~MTet4Factory () inline
Definition at line 267 of file meshGRegionDelaunayInsertion.h.
Member Function Documentation
changeTetRadius()
void MTet4Factory::changeTetRadius (iterator it, double r) inline
Definition at line 307 of file meshGRegionDelaunayInsertion.h.
Referenced by insertVerticesInRegion().
Create() [1/2]
MTet4* MTet4Factory::Create (MTetrahedron * t, std::vector< double > & sizes, std::vector< double > & sizesBGM) inline
Definition at line 273 of file meshGRegionDelaunayInsertion.h.
Referenced by insertVertexB(), and insertVerticesInRegion().
Create() [2/2]
MTet4* MTet4Factory::Create (MTetrahedron * t, std::vector< double > & sizes, std::vector< double > & sizesBGM, double lc1, double lc2) inline
Definition at line 284 of file meshGRegionDelaunayInsertion.h.
Free()
void MTet4Factory::Free (MTet4 * t) inline
Definition at line 296 of file meshGRegionDelaunayInsertion.h.
Referenced by insertVertexB(), insertVerticesInRegion(), and memoryCleanup().
getAllTets()
container& MTet4Factory::getAllTets () inline
Definition at line 314 of file meshGRegionDelaunayInsertion.h.
Referenced by insertVerticesInRegion().
Member Data Documentation
allTets
container MTet4Factory::allTets private
Definition at line 236 of file meshGRegionDelaunayInsertion.h.
Referenced by changeTetRadius(), and getAllTets().
The documentation for this class was generated from the following file:
src/mesh/meshGRegionDelaunayInsertion.h