gmsh-TingyuanDoc: drawContextGlobal Class Reference
drawContextGlobal Class Reference
#include <drawContext.h>
Public Member Functions
drawContextGlobal ()
virtual ~drawContextGlobal ()
virtual void draw (bool rateLimited=true)
virtual void drawCurrentOpenglWindow (bool make_current)
virtual int getFontIndex (const char *fontname)
virtual int getFontEnum (int index)
virtual const char * getFontName (int index)
virtual int getFontAlign (const char *alignstr)
virtual int getFontSize ()
virtual void setFont (int fontid, int fontsize)
virtual double getStringWidth (const char *str)
virtual int getStringHeight ()
virtual int getStringDescent ()
virtual void drawString (const char *str)
virtual void resetFontTextures ()
virtual void flushString ()
virtual std::string getName ()
Detailed Description
Definition at line 93 of file drawContext.h.
Constructor & Destructor Documentation
drawContextGlobal()
drawContextGlobal::drawContextGlobal () inline
Definition at line 95 of file drawContext.h.
~drawContextGlobal()
virtual drawContextGlobal::~drawContextGlobal () inline virtual
Definition at line 96 of file drawContext.h.
Member Function Documentation
draw()
virtual void drawContextGlobal::draw (bool rateLimited = true) inline virtual
Definition at line 97 of file drawContext.h.
Referenced by CreateOutputFile(), GMSH_ShowNeighborElementsPlugin::execute(), OpenProjectMacFinder(), and GMSH_Plugin::setDrawFunction().
drawCurrentOpenglWindow()
virtual void drawContextGlobal::drawCurrentOpenglWindow (bool make_current) inline virtual
Definition at line 98 of file drawContext.h.
Referenced by CreateOutputFile(), and PixelBuffer::fill().
drawString()
virtual void drawContextGlobal::drawString (const char * str) inline virtual
Definition at line 108 of file drawContext.h.
Referenced by drawContext::drawString().
flushString()
virtual void drawContextGlobal::flushString () inline virtual
Definition at line 110 of file drawContext.h.
getFontAlign()
virtual int drawContextGlobal::getFontAlign (const char * alignstr) inline virtual
Definition at line 102 of file drawContext.h.
Referenced by getStyle().
getFontEnum()
virtual int drawContextGlobal::getFontEnum (int index) inline virtual
Definition at line 100 of file drawContext.h.
Referenced by drawContext::drawString().
getFontIndex()
virtual int drawContextGlobal::getFontIndex (const char * fontname) inline virtual
Definition at line 99 of file drawContext.h.
Referenced by getStyle().
getFontName()
virtual const char* drawContextGlobal::getFontName (int index) inline virtual
Definition at line 101 of file drawContext.h.
Referenced by drawContext::drawString().
getFontSize()
virtual int drawContextGlobal::getFontSize () inline virtual
Definition at line 103 of file drawContext.h.
getName()
virtual std::string drawContextGlobal::getName () inline virtual
Definition at line 111 of file drawContext.h.
Referenced by opt_general_graphics_font_engine().
getStringDescent()
virtual int drawContextGlobal::getStringDescent () inline virtual
Definition at line 107 of file drawContext.h.
Referenced by drawGraphAxes(), and drawScaleValues().
getStringHeight()
virtual int drawContextGlobal::getStringHeight () inline virtual
Definition at line 106 of file drawContext.h.
Referenced by drawContext::drawGraph2d(), drawGraphAxes(), drawScaleLabel(), drawContext::drawScales(), drawScaleValues(), drawContext::drawString(), and drawTics().
getStringWidth()
virtual double drawContextGlobal::getStringWidth (const char * str) inline virtual
Definition at line 105 of file drawContext.h.
Referenced by drawGraphAxes(), drawContext::drawScales(), drawScaleValues(), drawContext::drawString(), and drawTics().
resetFontTextures()
virtual void drawContextGlobal::resetFontTextures () inline virtual
Definition at line 109 of file drawContext.h.
Referenced by opt_general_color_axes(), opt_general_color_small_axes(), opt_general_color_text(), opt_mesh_color_carousel(), opt_view_color_axes(), opt_view_color_background2d(), opt_view_color_text2d(), and opt_view_color_text3d().
setFont()
virtual void drawContextGlobal::setFont (int fontid, int fontsize) inline virtual
Definition at line 104 of file drawContext.h.
Referenced by drawContext::drawGraph2d(), drawScaleLabel(), drawContext::drawScales(), drawScaleValues(), drawContext::drawString(), and drawTics().
The documentation for this class was generated from the following file:
src/graphics/drawContext.h