gmsh-TingyuanDoc: nodalBasis Class Reference
nodalBasis Class Reference abstract
#include <nodalBasis.h>
Classes
class closure
Public Types
typedef std::vector< closure > clCont
Public Member Functions
nodalBasis ()
nodalBasis (int tag)
virtual ~nodalBasis ()
virtual int getNumShapeFunctions () const =0
int getNumBubbleShapeFunctions () const
void getReferenceNodes (fullMatrix< double > &nodes) const
const fullMatrix< double > & getReferenceNodes () const
bool forwardTransformation (const fullMatrix< double > &otherPoints, fullMatrix< double > &projection, int elementType=-1) const
bool forwardRenumbering (const fullMatrix< double > &otherPoints, int *renum, int elemenType=-1) const
virtual void f (double u, double v, double w, double *sf) const =0
virtual void f (const fullMatrix< double > &coord, fullMatrix< double > &sf) const =0
virtual void f (double u, double v, double w, int i, double *sf) const =0
virtual void df (double u, double v, double w, double grads[][3]) const =0
virtual void df (const fullMatrix< double > &coord, fullMatrix< double > &dfm) const =0
virtual void df (double u, double v, double w, int i, double grad[3]) const =0
virtual void ddf (double u, double v, double w, double grads[][3][3]) const
virtual void dddf (double u, double v, double w, double grads[][3][3][3]) const
virtual int getClosureType (int id) const
virtual const std::vector< int > & getClosure (int id) const
virtual const std::vector< int > & getFullClosure (int id) const
int getClosureId (int iFace, int iSign=1, int iRot=0) const
void breakClosureId (int i, int &iFace, int &iSign, int &iRot) const
Public Attributes
int type
int parentType
int order
int dimension
int numFaces
bool serendip
fullMatrix< double > points
clCont closures
clCont fullClosures
std::vector< int > closureRef
Detailed Description
Definition at line 12 of file nodalBasis.h.
Member Typedef Documentation
clCont
typedef std::vector<closure> nodalBasis::clCont
Definition at line 67 of file nodalBasis.h.
Constructor & Destructor Documentation
nodalBasis() [1/2]
nodalBasis::nodalBasis () inline
Definition at line 18 of file nodalBasis.h.
nodalBasis() [2/2]
nodalBasis::nodalBasis (int tag)
Definition at line 776 of file nodalBasis.cpp.
~nodalBasis()
virtual nodalBasis::~nodalBasis () inline virtual
Definition at line 20 of file nodalBasis.h.
Member Function Documentation
breakClosureId()
void nodalBasis::breakClosureId (int i, int & iFace, int & iSign, int & iRot) const inline
Definition at line 91 of file nodalBasis.h.
dddf()
virtual void nodalBasis::dddf (double u, double v, double w, double grads[][3][3][3]) const inline virtual
Reimplemented in polynomialBasis, and incompleteBasis.
Definition at line 51 of file nodalBasis.h.
Referenced by incompleteBasis::dddf(), and MElement::getThirdDerivativeShapeFunctions().
ddf()
virtual void nodalBasis::ddf (double u, double v, double w, double grads[][3][3]) const inline virtual
Reimplemented in polynomialBasis, and incompleteBasis.
Definition at line 47 of file nodalBasis.h.
Referenced by incompleteBasis::ddf(), and MElement::getHessShapeFunctions().
df() [1/3]
virtual void nodalBasis::df (const fullMatrix< double > & coord, fullMatrix< double > & dfm) const pure virtual
Implemented in polynomialBasis, pyramidalBasis, and incompleteBasis.
df() [2/3]
virtual void nodalBasis::df (double u, double v, double w, double grads[][3]) const pure virtual
Implemented in polynomialBasis, incompleteBasis, and pyramidalBasis.
Referenced by CondNumBasis::CondNumBasis(), incompleteBasis::df(), MFaceN::frame(), MElement::getGradShapeFunctions(), GradientBasis::GradientBasis(), JacobianBasis::JacobianBasis(), MFaceN::normal(), MEdgeN::tangent(), and MFaceN::tangent().
df() [3/3]
virtual void nodalBasis::df (double u, double v, double w, int i, double grad[3]) const pure virtual
Implemented in polynomialBasis, and pyramidalBasis.
f() [1/3]
virtual void nodalBasis::f (const fullMatrix< double > & coord, fullMatrix< double > & sf) const pure virtual
Implemented in polynomialBasis, pyramidalBasis, and incompleteBasis.
f() [2/3]
virtual void nodalBasis::f (double u, double v, double w, double * sf) const pure virtual
Implemented in pyramidalBasis, polynomialBasis, and incompleteBasis.
Referenced by incompleteBasis::f(), forwardTransformation(), MFaceN::frame(), MElement::getShapeFunctions(), MEdgeN::interpolate(), JacobianBasis::JacobianBasis(), MElement::maxDistToStraight(), MEdgeN::pnt(), and MFaceN::pnt().
f() [3/3]
virtual void nodalBasis::f (double u, double v, double w, int i, double * sf) const pure virtual
Implemented in pyramidalBasis, and polynomialBasis.
forwardRenumbering()
bool nodalBasis::forwardRenumbering (const fullMatrix< double > & otherPoints, int * renum, int elemenType = -1) const
Definition at line 928 of file nodalBasis.cpp.
forwardTransformation()
bool nodalBasis::forwardTransformation (const fullMatrix< double > & otherPoints, fullMatrix< double > & projection, int elementType = -1) const
Definition at line 910 of file nodalBasis.cpp.
Referenced by forwardRenumbering().
getClosure()
virtual const std::vector<int>& nodalBasis::getClosure (int id) const inline virtual
Definition at line 74 of file nodalBasis.h.
Referenced by MElement::getHighOrderFace().
getClosureId()
int nodalBasis::getClosureId (int iFace, int iSign = 1, int iRot = 0) const inline
Definition at line 86 of file nodalBasis.h.
Referenced by GMSH_CurvedBndDistPlugin::execute(), and MElement::getHighOrderFace().
getClosureType()
virtual int nodalBasis::getClosureType (int id) const inline virtual
Definition at line 73 of file nodalBasis.h.
Referenced by GMSH_CurvedBndDistPlugin::execute().
getFullClosure()
virtual const std::vector<int>& nodalBasis::getFullClosure (int id) const inline virtual
Definition at line 78 of file nodalBasis.h.
getNumBubbleShapeFunctions()
int nodalBasis::getNumBubbleShapeFunctions () const
Definition at line 863 of file nodalBasis.cpp.
getNumShapeFunctions()
virtual int nodalBasis::getNumShapeFunctions () const pure virtual
Implemented in pyramidalBasis, polynomialBasis, and incompleteBasis.
Referenced by incompleteBasis::_computeCoefficientsTriangle(), CondNumBasis::CondNumBasis(), MFaceN::frame(), MEdgeN::interpolate(), JacobianBasis::JacobianBasis(), MFaceN::normal(), MEdgeN::pnt(), MFaceN::pnt(), MEdgeN::tangent(), and MFaceN::tangent().
getReferenceNodes() [1/2]
const fullMatrix<double>& nodalBasis::getReferenceNodes () const inline
Definition at line 24 of file nodalBasis.h.
getReferenceNodes() [2/2]
void nodalBasis::getReferenceNodes (fullMatrix< double > & nodes) const inline
Definition at line 23 of file nodalBasis.h.
Referenced by incompleteBasis::_computeCoefficientsTriangle(), MElement::getNode(), MElement::getNodesCoordNonSerendip(), and MElement::xyz2uvw().
Member Data Documentation
closureRef
std::vector<int> nodalBasis::closureRef
Definition at line 69 of file nodalBasis.h.
Referenced by miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), and nodalBasis().
closures
clCont nodalBasis::closures
Definition at line 68 of file nodalBasis.h.
Referenced by GMSH_CurvedBndDistPlugin::execute(), getClosure(), getClosureType(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), and nodalBasis().
dimension
int nodalBasis::dimension
Definition at line 14 of file nodalBasis.h.
Referenced by polynomialBasis::evaluateMonomials(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), and nodalBasis().
fullClosures
clCont nodalBasis::fullClosures
Definition at line 68 of file nodalBasis.h.
Referenced by getFullClosure(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), and nodalBasis().
numFaces
int nodalBasis::numFaces
Definition at line 14 of file nodalBasis.h.
Referenced by breakClosureId(), getClosureId(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), and nodalBasis().
order
int nodalBasis::order
Definition at line 14 of file nodalBasis.h.
Referenced by incompleteBasis::_computeCoefficientsTriangle(), getNumBubbleShapeFunctions(), incompleteBasis::incompleteBasis(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), nodalBasis(), polynomialBasis::polynomialBasis(), and pyramidalBasis::pyramidalBasis().
parentType
int nodalBasis::parentType
Definition at line 14 of file nodalBasis.h.
Referenced by getNumBubbleShapeFunctions(), incompleteBasis::incompleteBasis(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), nodalBasis(), and polynomialBasis::polynomialBasis().
points
fullMatrix<double> nodalBasis::points
Definition at line 16 of file nodalBasis.h.
Referenced by incompleteBasis::_computeCoefficientsTriangle(), CondNumBasis::CondNumBasis(), pyramidalBasis::df(), pyramidalBasis::f(), forwardRenumbering(), forwardTransformation(), ClosureGen::generateFaceClosureHex(), ClosureGen::generateFaceClosurePyr(), MPrismN::getNode(), incompleteBasis::getNumShapeFunctions(), pyramidalBasis::getNumShapeFunctions(), getReferenceNodes(), interpVerticesInExistingEdge(), JacobianBasis::JacobianBasis(), MElement::maxDistToStraight(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), nodalBasis(), polynomialBasis::polynomialBasis(), and pyramidalBasis::pyramidalBasis().
serendip
bool nodalBasis::serendip
Definition at line 15 of file nodalBasis.h.
Referenced by getNumBubbleShapeFunctions(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), nodalBasis(), polynomialBasis::polynomialBasis(), and pyramidalBasis::pyramidalBasis().
type
int nodalBasis::type
Definition at line 14 of file nodalBasis.h.
Referenced by forwardTransformation(), ClosureGen::generateFaceClosureHex(), ClosureGen::generateFaceClosurePyr(), getNumBubbleShapeFunctions(), incompleteBasis::incompleteBasis(), miniBasisTet::miniBasisTet(), miniBasisTri::miniBasisTri(), and nodalBasis().
The documentation for this class was generated from the following files:
src/numeric/nodalBasis.h
src/numeric/nodalBasis.cpp