gmsh-TingyuanDoc: OctreeField::Cell Class Reference
OctreeField::Cell Class Reference
Public Member Functions
double evaluate (double x, double y, double z) const
Cell ()
void init (double x0, double y0, double z0, double l, Field &field, int level)
~Cell ()
void print (double x0, double y0, double z0, double l, FILE *f)
Private Attributes
void * _data
bool _isleaf
Detailed Description
Definition at line 2260 of file Field.cpp.
Constructor & Destructor Documentation
Cell()
OctreeField::Cell::Cell () inline
Definition at line 2275 of file Field.cpp.
~Cell()
OctreeField::Cell::~Cell () inline
Definition at line 2332 of file Field.cpp.
Member Function Documentation
evaluate()
double OctreeField::Cell::evaluate (double x, double y, double z) const inline
Definition at line 2266 of file Field.cpp.
Referenced by evaluate(), and OctreeField::operator()().
init()
void OctreeField::Cell::init (double x0, double y0, double z0, double l, Field & field, int level) inline
Definition at line 2276 of file Field.cpp.
Referenced by init(), and OctreeField::update().
print()
void OctreeField::Cell::print (double x0, double y0, double z0, double l, FILE * f) inline
Definition at line 2340 of file Field.cpp.
Referenced by print().
Member Data Documentation
_data
void* OctreeField::Cell::_data private
Definition at line 2262 of file Field.cpp.
Referenced by evaluate(), init(), print(), and ~Cell().
_isleaf
bool OctreeField::Cell::_isleaf private
Definition at line 2263 of file Field.cpp.
Referenced by evaluate(), init(), print(), and ~Cell().
The documentation for this class was generated from the following file:
src/mesh/Field.cpp