gmsh-TingyuanDoc: PView Class Reference
PView Class Reference
#include <PView.h>
Public Member Functions
PView (int tag=-1)
PView (PViewData *data, int tag=-1)
PView (PView *ref, bool copyOptions=true, int tag=-1)
PView (const std::string &xname, const std::string &yname, std::vector< double > &x, std::vector< double > &y)
PView (const std::string &name, std::vector< double > &x, std::vector< double > &y, std::vector< double > &z, std::vector< double > &v)
PView (const std::string &name, const std::string &type, GModel *model, std::map< int, std::vector< double > > &data, double time=0., int numComp=-1, int tag=-1)
void addStep (GModel *model, const std::map< int, std::vector< double > > &data, double time=0., int numComp=-1)
void addStep (std::vector< double > &y)
~PView ()
void deleteVertexArrays ()
PViewOptions * getOptions ()
void setOptions (PViewOptions *val=nullptr)
PViewData * getData (bool useAdaptiveIfAvailable=false)
void setData (PViewData *val)
int getTag ()
int getIndex ()
void setIndex (int val)
bool & getChanged ()
void setChanged (bool val)
int getAliasOf ()
SPoint3 & getEye ()
void setEye (SPoint3 &p)
double getMemoryInMb ()
bool write (const std::string &fileName, int format, bool append=false)
void sendToServer (const std::string &name)
bool writeAdapt (const std::string &fileName, int useDefaultName, bool isBinary, int adaptLev, double adaptErr, int npart, bool append=false)
bool fillVertexArrays ()
Static Public Member Functions
static int getGlobalTag ()
static void setGlobalTag (int tag)
static void combine (bool time, int how, bool remove, bool copyOptions)
static PView * getViewByName (const std::string &name, int timeStep=-1, int partition=-1, const std::string &fileName="")
static PView * getViewByFileName (const std::string &fileName, int timeStep=-1, int partition=-1)
static PView * getViewByTag (int tag, int timeStep=-1, int partition=-1)
static void sortByName ()
static bool readPOS (const std::string &fileName, int fileIndex=-1)
static bool readMSH (const std::string &fileName, int fileIndex=-1, int partitionToRead=-1)
static bool readCGNS (const std::vector< std::vector< MVertex * > > &vertPerZone, const std::vector< std::vector< MElement * > > &eltPerZone, const std::string &fileName)
static bool readMED (const std::string &fileName, int fileIndex=-1)
static bool readPCH (const std::string &fileName, int fileIndex=-1)
static bool writeX3D (const std::string &fileName)
static void fillVertexArray (onelab::localNetworkClient *remote, int length, const char *data, int swap)
Public Attributes
VertexArray * va_points
VertexArray * va_lines
VertexArray * va_triangles
VertexArray * va_vectors
VertexArray * va_ellipses
smooth_normals * normals
Static Public Attributes
static std::vector< PView * > list
Private Member Functions
void _init (int tag=-1)
Private Attributes
int _tag
int _index
bool _changed
int _aliasOf
SPoint3 _eye
PViewOptions * _options
PViewData * _data
Static Private Attributes
static int _globalTag = 1
Detailed Description
Definition at line 27 of file PView.h.
Constructor & Destructor Documentation
PView() [1/6]
PView::PView (int tag = -1)
Definition at line 53 of file PView.cpp.
Referenced by combine(), fillVertexArray(), readMSH(), readPCH(), and readPOS().
PView() [2/6]
PView::PView (PViewData * data, int tag = -1)
Definition at line 63 of file PView.cpp.
PView() [3/6]
PView::PView (PView * ref, bool copyOptions = true, int tag = -1)
Definition at line 73 of file PView.cpp.
PView() [4/6]
PView::PView (const std::string & xname, const std::string & yname, std::vector< double > & x, std::vector< double > & y)
Definition at line 99 of file PView.cpp.
PView() [5/6]
PView::PView (const std::string & name, std::vector< double > & x, std::vector< double > & y, std::vector< double > & z, std::vector< double > & v)
Definition at line 124 of file PView.cpp.
PView() [6/6]
PView::PView (const std::string & name, const std::string & type, GModel * model, std::map< int, std::vector< double > > & data, double time = 0., int numComp = -1, int tag = -1)
Definition at line 139 of file PView.cpp.
~PView()
PView::~PView ()
Definition at line 179 of file PView.cpp.
Member Function Documentation
_init()
void PView::_init (int tag = -1) private
Definition at line 20 of file PView.cpp.
Referenced by PView().
addStep() [1/2]
void PView::addStep (GModel * model, const std::map< int, std::vector< double > > & data, double time = 0., int numComp = -1)
Definition at line 168 of file PView.cpp.
Referenced by GMSH_FieldFromAmplitudePhasePlugin::execute().
addStep() [2/2]
void PView::addStep (std::vector< double > & y)
Definition at line 115 of file PView.cpp.
combine()
void PView::combine (bool time, int how, bool remove, bool copyOptions) static
Definition at line 249 of file PView.cpp.
Referenced by GmshFLTK().
deleteVertexArrays()
void PView::deleteVertexArrays ()
Definition at line 210 of file PView.cpp.
Referenced by initPView::operator()(), and ~PView().
fillVertexArray()
void PView::fillVertexArray (onelab::localNetworkClient * remote, int length, const char * data, int swap) static
Definition at line 1574 of file PViewVertexArrays.cpp.
fillVertexArrays()
bool PView::fillVertexArrays ()
Definition at line 1568 of file PViewVertexArrays.cpp.
getAliasOf()
int PView::getAliasOf () inline
Definition at line 100 of file PView.h.
Referenced by PView(), and ~PView().
getChanged()
bool& PView::getChanged () inline
Definition at line 96 of file PView.h.
Referenced by initPView::operator()().
getData()
PViewData * PView::getData (bool useAdaptiveIfAvailable = false)
Definition at line 233 of file PView.cpp.
Referenced by _addModelData(), initPView::_estimateNumEllipses(), initPView::_estimateNumLines(), initPView::_estimateNumPoints(), initPView::_estimateNumTriangles(), initPView::_estimateNumVectors(), addElementsInArrays(), addVectorElement(), combine(), drawGlyphs(), drawGraph(), drawGraphAxes(), drawScale(), drawScaleLabel(), drawContext::drawScales(), GMSH_LongituteLatitudePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_SmoothPlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_HarmonicToTimePlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_ProbePlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_FieldFromAmplitudePhasePlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_AnnotatePlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GMSH_PostPlugin::executeRemote(), frameSolver2d::exportFrameData(), fillVertexArray(), GMSH_PostPlugin::getDataList(), getExternalValues(), getGraphData(), getLineNormal(), getMemoryInMb(), GMSH_PostPlugin::getPossiblyAdaptiveData(), getViewByFileName(), getViewByName(), getViewByTag(), gmshViewGetModelData(), OctreePost::OctreePost(), PViewEvaluator::operator()(), PViewLessThanName::operator()(), drawPView::operator()(), drawPViewBoundingBox::operator()(), initPView::operator()(), PView(), readMSH(), GModel::readPLY(), writeX3D(), writeX3DScale(), and writeX3DScaleLabel().
getEye()
SPoint3& PView::getEye () inline
Definition at line 103 of file PView.h.
Referenced by eyeChanged(), and drawPView::operator()().
getGlobalTag()
int PView::getGlobalTag () static
Definition at line 206 of file PView.cpp.
getIndex()
int PView::getIndex () inline
Definition at line 92 of file PView.h.
Referenced by GMSH_SkinPlugin::execute(), GMSH_ExtractElementsPlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_PostPlugin::getView(), and drawPView::operator()().
getMemoryInMb()
double PView::getMemoryInMb ()
Definition at line 388 of file PView.cpp.
getOptions()
PViewOptions* PView::getOptions () inline
Definition at line 81 of file PView.h.
Referenced by _addModelData(), initPView::_estimateIfClipped(), initPView::_estimateNumEllipses(), initPView::_estimateNumLines(), initPView::_estimateNumPoints(), initPView::_estimateNumTriangles(), initPView::_estimateNumVectors(), addElementsInArrays(), addGraphPoint(), addOutlineElement(), addOutlineQuadrangle(), addOutlineTriangle(), addScalarHexahedron(), addScalarLine(), addScalarPoint(), addScalarPolygon(), addScalarPolyhedron(), addScalarPrism(), addScalarPyramid(), addScalarQuadrangle(), addScalarTetrahedron(), addScalarTriangle(), addTensorElement(), addVectorElement(), applyGeneralRaise(), changeCoordinates(), combine(), drawArrays(), drawEllipseArray(), drawGlyphs(), drawGraph(), drawGraphAxes(), drawGraphCurves(), drawNormalVectorGlyphs(), drawNumberGlyphs(), drawScale(), drawScaleBar(), drawScaleLabel(), drawContext::drawScales(), drawScaleValues(), drawTangentVectorGlyphs(), drawVectorArray(), GMSH_IntegratePlugin::execute(), GMSH_MinMaxPlugin::execute(), GMSH_MeshVolumePlugin::execute(), GMSH_ParticlesPlugin::execute(), GMSH_StreamLinesPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_BoundaryAnglesPlugin::execute(), fillVertexArray(), getExternalValues(), getGraphData(), getLineNormal(), getPointNormal(), GMSH_PostPlugin::getPossiblyAdaptiveData(), drawPView::operator()(), drawPViewBoundingBox::operator()(), initPView::operator()(), PView(), writeX3D(), writeX3DScale(), writeX3DScaleBar(), writeX3DScaleLabel(), and writeX3DScaleValues().
getTag()
int PView::getTag () inline
Definition at line 89 of file PView.h.
Referenced by _init(), GMSH_PostPlugin::executeRemote(), getViewByTag(), PView(), GMSH_PostPlugin::run(), and ~PView().
getViewByFileName()
PView * PView::getViewByFileName (const std::string & fileName, int timeStep = -1, int partition = -1) static
Definition at line 362 of file PView.cpp.
getViewByName()
PView * PView::getViewByName (const std::string & name, int timeStep = -1, int partition = -1, const std::string & fileName = "") static
Definition at line 347 of file PView.cpp.
Referenced by quadqsCleanup(), and readMSH().
getViewByTag()
PView * PView::getViewByTag (int tag, int timeStep = -1, int partition = -1) static
Definition at line 376 of file PView.cpp.
Referenced by _addModelData(), fillVertexArray(), gmshViewGetModelData(), and PView().
readCGNS()
bool PView::readCGNS (const std::vector< std::vector< MVertex * > > & vertPerZone, const std::vector< std::vector< MElement * > > & eltPerZone, const std::string & fileName) static
Definition at line 179 of file PViewIO_CGNS.cpp.
Referenced by MergeFile().
readMED()
bool PView::readMED (const std::string & fileName, int fileIndex = -1) static
Definition at line 357 of file PViewIO.cpp.
Referenced by MergeFile().
readMSH()
bool PView::readMSH (const std::string & fileName, int fileIndex = -1, int partitionToRead = -1) static
Definition at line 84 of file PViewIO.cpp.
Referenced by MergeFile().
readPCH()
bool PView::readPCH (const std::string & fileName, int fileIndex = -1) static
Definition at line 366 of file PViewIO.cpp.
Referenced by MergeFile().
readPOS()
bool PView::readPOS (const std::string & fileName, int fileIndex = -1) static
Definition at line 19 of file PViewIO.cpp.
Referenced by MergeFile().
sendToServer()
void PView::sendToServer (const std::string & name)
Definition at line 443 of file PViewIO.cpp.
setChanged()
void PView::setChanged (bool val)
Definition at line 241 of file PView.cpp.
Referenced by _addModelData(), GMSH_LongituteLatitudePlugin::execute(), GMSH_SmoothPlugin::execute(), GMSH_SphericalRaisePlugin::execute(), GMSH_WarpPlugin::execute(), GMSH_NearestNeighborPlugin::execute(), GMSH_RemovePlugin::execute(), GMSH_MakeSimplexPlugin::execute(), GMSH_ModulusPhasePlugin::execute(), GMSH_TransformPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_LevelsetPlugin::execute(), fillVertexArray(), initPView::operator()(), and Field::putOnNewView().
setData()
void PView::setData (PViewData * val) inline
Definition at line 86 of file PView.h.
Referenced by _addModelData().
setEye()
void PView::setEye (SPoint3 & p) inline
Definition at line 104 of file PView.h.
Referenced by eyeChanged().
setGlobalTag()
void PView::setGlobalTag (int tag) static
Definition at line 208 of file PView.cpp.
Referenced by DeleteAllModelsAndViews().
setIndex()
void PView::setIndex (int val) inline
Definition at line 93 of file PView.h.
Referenced by _init(), sortByName(), and ~PView().
setOptions()
void PView::setOptions (PViewOptions * val = nullptr)
Definition at line 224 of file PView.cpp.
Referenced by combine().
sortByName()
void PView::sortByName () static
Definition at line 341 of file PView.cpp.
write()
bool PView::write (const std::string & fileName, int format, bool append = false)
Definition at line 378 of file PViewIO.cpp.
Referenced by GMSH_BoundaryAnglesPlugin::execute().
writeAdapt()
bool PView::writeAdapt (const std::string & fileName, int useDefaultName, bool isBinary, int adaptLev, double adaptErr, int npart, bool append = false)
Definition at line 433 of file PViewIO.cpp.
writeX3D()
bool PView::writeX3D (const std::string & fileName) static
Definition at line 72 of file PViewX3D.cpp.
Referenced by write().
Member Data Documentation
_aliasOf
int PView::_aliasOf private
Definition at line 37 of file PView.h.
Referenced by _init(), getAliasOf(), PView(), and ~PView().
_changed
bool PView::_changed private
Definition at line 35 of file PView.h.
Referenced by _init(), getChanged(), and setChanged().
_data
PViewData* PView::_data private
Definition at line 43 of file PView.h.
Referenced by addStep(), getData(), PView(), sendToServer(), setData(), write(), writeAdapt(), and ~PView().
_eye
SPoint3 PView::_eye private
Definition at line 39 of file PView.h.
Referenced by _init(), getEye(), setChanged(), and setEye().
_globalTag
int PView::_globalTag = 1 static private
Definition at line 29 of file PView.h.
Referenced by _init(), getGlobalTag(), and setGlobalTag().
_index
int PView::_index private
Definition at line 33 of file PView.h.
Referenced by getIndex(), sendToServer(), setIndex(), and ~PView().
_options
PViewOptions* PView::_options private
Definition at line 41 of file PView.h.
Referenced by getOptions(), PView(), setOptions(), writeAdapt(), and ~PView().
_tag
int PView::_tag private
Definition at line 31 of file PView.h.
Referenced by _init(), getTag(), and ~PView().
list
std::vector< PView * > PView::list static
Definition at line 112 of file PView.h.
Referenced by _init(), addExtrudeNormals(), assemblePostAxis(), GMSH_IsosurfacePlugin::callbackValue(), combine(), DeleteAllModelsAndViews(), GMSH_ProbePlugin::draw(), GMSH_CutPlanePlugin::draw(), drawContext::drawGraph2d(), drawContext::drawMesh(), drawContext::drawPost(), drawScaleLabel(), drawContext::drawScales(), drawContext::drawText2d(), GMSH_ModifyComponentsPlugin::execute(), GMSH_LevelsetPlugin::execute(), GMSH_PostPlugin::executeRemote(), GetColorTable(), getExternalValues(), GetMeshOption(), GetStatistics(), GMSH_PostPlugin::getView(), getViewByFileName(), getViewByName(), getViewByTag(), GmshBatch(), GmshFLTK(), MergeFile(), MergePostProcessingFile(), needPolygonOffset(), opt_general_color_scheme(), opt_post_nb_views(), opt_view_name(), PrintColorTable(), PrintOptions(), ReInitOptions(), GMSH_CutMeshPlugin::run(), drawContext::select(), SetBoundingBox(), sortByName(), writeX3D(), writeX3DScaleLabel(), and ~PView().
normals
smooth_normals* PView::normals
Definition at line 166 of file PView.h.
Referenced by _init(), addOutlineQuadrangle(), addOutlineTriangle(), addScalarTetrahedron(), addScalarTriangle(), initPView::operator()(), and ~PView().
va_ellipses
VertexArray * PView::va_ellipses
Definition at line 156 of file PView.h.
Referenced by _init(), addTensorElement(), deleteVertexArrays(), fillVertexArray(), getMemoryInMb(), drawPView::operator()(), and initPView::operator()().
va_lines
VertexArray * PView::va_lines
Definition at line 156 of file PView.h.
Referenced by _init(), addOutlineLine(), addOutlineQuadrangle(), addOutlineTriangle(), addScalarLine(), addScalarTriangle(), addVectorElement(), deleteVertexArrays(), fillVertexArray(), getMemoryInMb(), drawPView::operator()(), and initPView::operator()().
va_points
VertexArray* PView::va_points
Definition at line 156 of file PView.h.
Referenced by _init(), addOutlinePoint(), addScalarLine(), addScalarPoint(), deleteVertexArrays(), fillVertexArray(), getMemoryInMb(), drawPView::operator()(), and initPView::operator()().
va_triangles
VertexArray * PView::va_triangles
Definition at line 156 of file PView.h.
Referenced by _init(), addScalarTetrahedron(), addScalarTriangle(), addTriangle(), deleteVertexArrays(), fillVertexArray(), getMemoryInMb(), drawPView::operator()(), and initPView::operator()().
va_vectors
VertexArray * PView::va_vectors
Definition at line 156 of file PView.h.
Referenced by _init(), addVectorElement(), deleteVertexArrays(), fillVertexArray(), getMemoryInMb(), drawPView::operator()(), and initPView::operator()().
The documentation for this class was generated from the following files:
src/post/PView.h
src/post/PView.cpp
src/post/PViewIO.cpp
src/post/PViewIO_CGNS.cpp
src/post/PViewVertexArrays.cpp
src/post/PViewX3D.cpp