gmsh-TingyuanDoc: MPoint Class Reference
MPoint Class Reference
#include <MPoint.h>
Public Member Functions
MPoint (MVertex *v0, int num=0, int part=0)
MPoint (const std::vector< MVertex * > &v, int num=0, int part=0)
~MPoint ()
virtual int getDim () const
virtual std::size_t getNumVertices () const
virtual MVertex * getVertex (int num)
virtual const MVertex * getVertex (int num) const
virtual void setVertex (int num, MVertex *v)
virtual int getNumEdges () const
virtual MEdge getEdge (int num) const
virtual int getNumEdgesRep (bool curved)
virtual void getEdgeRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual int getNumFaces ()
virtual MFace getFace (int num) const
virtual int getNumFacesRep (bool curved)
virtual void getFaceRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual int getType () const
virtual int getTypeForMSH () const
virtual int getTypeForVTK () const
virtual const char * getStringForPOS () const
virtual void getNode (int num, double &u, double &v, double &w) const
virtual SPoint3 barycenterUVW () const
virtual void getShapeFunctions (double u, double v, double w, double s[], int o) const
virtual void getGradShapeFunctions (double u, double v, double w, double s[][3], int o) const
virtual const JacobianBasis * getJacobianFuncSpace (int o) const
virtual bool isInside (double u, double v, double w) const
virtual void getIntegrationPoints (int pOrder, int *npts, IntPt **pts)
virtual int numCommonNodesInDualGraph (const MElement *const other) const
Public Member Functions inherited from MElement
MElement (std::size_t num=0, int part=0)
virtual ~MElement ()
double getTolerance () const
virtual std::size_t getNum () const
void forceNum (std::size_t num)
virtual int getPolynomialOrder () const
virtual bool getIsAssimilatedSerendipity () const
virtual bool getIsOnlySerendipity () const
virtual int getPartition () const
virtual void setPartition (int num)
virtual char getVisibility () const
virtual void setVisibility (char val)
void getVertices (std::vector< MVertex * > &verts)
virtual void getVertexInfo (const MVertex *vertex, int &ithVertex) const
virtual MVertex * getVertexUNV (int num)
virtual MVertex * getVertexVTK (int num)
virtual MVertex * getVertexMATLAB (int num)
virtual MVertex * getVertexTOCHNOG (int num)
virtual MVertex * getVertexBDF (int num)
virtual MVertex * getVertexDIFF (int num)
virtual MVertex * getVertexINP (int num)
virtual MVertex * getVertexKEY (int num)
virtual MVertex * getVertexRAD (int num)
virtual MVertex * getVertexNEU (int num)
virtual int getNumEdgeVertices () const
virtual int getNumFaceVertices () const
virtual int getNumVolumeVertices () const
std::size_t getNumPrimaryVertices () const
virtual MEdgeN getHighOrderEdge (int num, int sign)
MEdgeN getHighOrderEdge (const MEdge &edge)
virtual bool getEdgeInfo (const MEdge &edge, int &ithEdge, int &sign) const
virtual int numEdge2numVertex (int numEdge, int numVert) const
virtual MEdge getEdgeSolin (int numEdge)
virtual MFaceN getHighOrderFace (int num, int sign, int rot)
MFaceN getHighOrderFace (const MFace &face)
virtual bool getFaceInfo (const MFace &face, int &ithFace, int &sign, int &rot) const
virtual MFace getFaceSolin (int numFace)
virtual void getEdgeVertices (const int num, std::vector< MVertex * > &v) const
virtual void getFaceVertices (const int num, std::vector< MVertex * > &v) const
virtual MElement * getParent () const
virtual void setParent (MElement *p, bool owner=false)
virtual void updateParent (GModel *gm)
virtual int getNumChildren () const
virtual MElement * getChild (int i) const
virtual bool ownsParent () const
virtual const MElement * getBaseElement () const
virtual MElement * getBaseElement ()
virtual MElement * getDomain (int i) const
virtual void setDomain (MElement *e, int i)
virtual double maxEdge ()
virtual double minEdge ()
double maxDistToStraight () const
double skewness ()
virtual double gammaShapeMeasure ()
virtual double etaShapeMeasure ()
double minSICNShapeMeasure ()
double minSIGEShapeMeasure ()
double distoShapeMeasure ()
double minIsotropyMeasure (bool knownValid=false, bool reversedOk=false)
double minScaledJacobian (bool knownValid=false, bool reversedOk=false)
virtual double angleShapeMeasure ()
virtual void scaledJacRange (double &jmin, double &jmax, GEntity *ge=nullptr) const
virtual void idealJacRange (double &jmin, double &jmax, GEntity *ge=nullptr)
virtual void signedInvCondNumRange (double &iCNMin, double &iCNMax, GEntity *ge=nullptr)
virtual void signedInvGradErrorRange (double &minSIGE, double &maxSIGE)
virtual double getInnerRadius ()
virtual double getOuterRadius ()
virtual SPoint3 barycenter (bool primary=false) const
virtual SPoint3 fastBarycenter (bool primary=false) const
virtual SPoint3 barycenter_infty () const
virtual void reverse ()
virtual double getVolume ()
virtual int getVolumeSign ()
virtual bool setVolumePositive ()
int getValidity ()
virtual std::string getInfoString (bool multline)
virtual const nodalBasis * getFunctionSpace (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getFuncSpaceData (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getJacobianFuncSpaceData (int orderElement=-1) const
virtual void getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order=-1) const
virtual void getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order=-1) const
virtual double getJacobian (const fullMatrix< double > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double *jac) const
virtual double getJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobian (double u, double v, double w, fullMatrix< double > &j) const
virtual double getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobianDeterminant (double u, double v, double w) const
void getSignedJacobian (fullVector< double > &jacobian, int o=-1) const
void getNodesCoord (fullMatrix< double > &nodesXYZ) const
void getNodesCoordNonSerendip (fullMatrix< double > &nodesXYZ) const
bezierCoeff * getBezierVerticesCoord () const
virtual std::size_t getNumShapeFunctions () const
virtual std::size_t getNumPrimaryShapeFunctions () const
virtual const MVertex * getShapeFunctionNode (int i) const
virtual MVertex * getShapeFunctionNode (int i)
virtual double getEigenvaluesMetric (double u, double v, double w, double values[3]) const
virtual void pnt (double u, double v, double w, SPoint3 &p) const
virtual void pnt (double u, double v, double w, double *p) const
virtual void pnt (const std::vector< double > &sf, SPoint3 &p) const
virtual void primaryPnt (double u, double v, double w, SPoint3 &p)
virtual void xyz2uvw (double xyz[3], double uvw[3]) const
virtual void movePointFromParentSpaceToElementSpace (double &u, double &v, double &w) const
virtual void movePointFromElementSpaceToParentSpace (double &u, double &v, double &w) const
double interpolate (double val[], double u, double v, double w, int stride=1, int order=-1)
void interpolateGrad (double val[], double u, double v, double w, double f[], int stride=1, double invjac[3][3]=nullptr, int order=-1)
void interpolateCurl (double val[], double u, double v, double w, double f[], int stride=3, int order=-1)
double interpolateDiv (double val[], double u, double v, double w, int stride=3, int order=-1)
double integrate (double val[], int pOrder, int stride=1, int order=-1)
double integrateCirc (double val[], int edge, int pOrder, int order=-1)
double integrateFlux (double val[], int face, int pOrder, int order=-1)
virtual void writeMSH2 (FILE *fp, double version=1.0, bool binary=false, int num=0, int elementary=1, int physical=1, int parentNum=0, int dom1Num=0, int dom2Num=0, std::vector< short > *ghosts=nullptr)
virtual void writeMSH3 (FILE *fp, bool binary=false, int elementary=1, std::vector< short > *ghosts=nullptr)
virtual void writePOS (FILE *fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor=1.0, int elementary=1)
virtual void writeSTL (FILE *fp, bool binary=false, double scalingFactor=1.0)
virtual void writeX3D (FILE *fp, double scalingFactor=1.0)
virtual void writeVRML (FILE *fp)
virtual void writePLY2 (FILE *fp)
virtual void writeUNV (FILE *fp, int num=0, int elementary=1, int physical=1)
virtual void writeVTK (FILE *fp, bool binary=false, bool bigEndian=false)
virtual void writeMATLAB (FILE *fp, int filetype, int elementary=0, int physical=0, bool binary=false)
virtual void writeTOCHNOG (FILE *fp, int num)
virtual void writeMESH (FILE *fp, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeNEU (FILE *fp, unsigned gambitType, int adjust, int phys=0)
virtual void writeIR3 (FILE *fp, int elementTagType, int num, int elementary, int physical)
virtual void writeBDF (FILE *fp, int format=0, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeDIFF (FILE *fp, int num, bool binary=false, int physical_property=1)
virtual void writeINP (FILE *fp, int num)
virtual void writeKEY (FILE *fp, int pid, int num)
virtual void writeRAD (FILE *fp, int num)
virtual void writeSU2 (FILE *fp, int num)
virtual int getTypeForUNV () const
virtual const char * getStringForTOCHNOG () const
virtual const char * getStringForBDF () const
virtual const char * getStringForDIFF () const
virtual const char * getStringForINP () const
virtual const char * getStringForKEY () const
virtual const char * getStringForRAD () const
std::string getName ()
virtual std::size_t getNumVerticesForMSH ()
virtual void getVerticesIdForMSH (std::vector< int > &verts)
virtual MElement * copy (std::map< int, MVertex * > &vertexMap, std::map< MElement *, MElement * > &newParents, std::map< MElement *, MElement * > &newDomains)
Protected Attributes
MVertex * _v [1]
Additional Inherited Members
Static Public Member Functions inherited from MElement
static unsigned int getInfoMSH (const int typeMSH, const char **const name=nullptr)
Protected Member Functions inherited from MElement
void _getEdgeRep (MVertex *v0, MVertex *v1, double *x, double *y, double *z, SVector3 *n, int faceIndex=-1)
void _getFaceRep (MVertex *v0, MVertex *v1, MVertex *v2, double *x, double *y, double *z, SVector3 *n)
Static Protected Member Functions inherited from MElement
static bool _getFaceInfo (const MFace &face, const MFace &other, int &sign, int &rot)
Static Protected Attributes inherited from MElement
static double _isInsideTolerance
Detailed Description
Definition at line 16 of file MPoint.h.
Constructor & Destructor Documentation
MPoint() [1/2]
MPoint::MPoint (MVertex * v0, int num = 0, int part = 0) inline
Definition at line 21 of file MPoint.h.
Referenced by MSubPoint::getBaseElement().
MPoint() [2/2]
MPoint::MPoint (const std::vector< MVertex * > & v, int num = 0, int part = 0) inline
Definition at line 25 of file MPoint.h.
~MPoint()
MPoint::~MPoint () inline
Definition at line 30 of file MPoint.h.
Member Function Documentation
barycenterUVW()
virtual SPoint3 MPoint::barycenterUVW () const inline virtual
Reimplemented from MElement.
Definition at line 58 of file MPoint.h.
getDim()
virtual int MPoint::getDim () const inline virtual
Implements MElement.
Definition at line 31 of file MPoint.h.
Referenced by MSubPoint::isInside().
getEdge()
virtual MEdge MPoint::getEdge (int num) const inline virtual
Implements MElement.
Definition at line 37 of file MPoint.h.
getEdgeRep()
virtual void MPoint::getEdgeRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) inline virtual
Implements MElement.
Definition at line 39 of file MPoint.h.
getFace()
virtual MFace MPoint::getFace (int num) const inline virtual
Implements MElement.
Definition at line 44 of file MPoint.h.
getFaceRep()
virtual void MPoint::getFaceRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) inline virtual
Implements MElement.
Definition at line 46 of file MPoint.h.
getGradShapeFunctions()
virtual void MPoint::getGradShapeFunctions (double u, double v, double w, double s[][3], int o) const inline virtual
Reimplemented from MElement.
Reimplemented in MSubPoint.
Definition at line 64 of file MPoint.h.
getIntegrationPoints()
virtual void MPoint::getIntegrationPoints (int pOrder, int * npts, IntPt ** pts) inline virtual
Reimplemented from MElement.
Reimplemented in MSubPoint.
Definition at line 79 of file MPoint.h.
getJacobianFuncSpace()
virtual const JacobianBasis* MPoint::getJacobianFuncSpace (int o) const inline virtual
Reimplemented from MElement.
Reimplemented in MSubPoint.
Definition at line 69 of file MPoint.h.
getNode()
virtual void MPoint::getNode (int num, double & u, double & v, double & w) const inline virtual
Reimplemented from MElement.
Definition at line 54 of file MPoint.h.
getNumEdges()
virtual int MPoint::getNumEdges () const inline virtual
Implements MElement.
Definition at line 36 of file MPoint.h.
getNumEdgesRep()
virtual int MPoint::getNumEdgesRep (bool curved) inline virtual
Implements MElement.
Definition at line 38 of file MPoint.h.
getNumFaces()
virtual int MPoint::getNumFaces () inline virtual
Implements MElement.
Definition at line 43 of file MPoint.h.
getNumFacesRep()
virtual int MPoint::getNumFacesRep (bool curved) inline virtual
Implements MElement.
Definition at line 45 of file MPoint.h.
getNumVertices()
virtual std::size_t MPoint::getNumVertices () const inline virtual
Implements MElement.
Definition at line 32 of file MPoint.h.
getShapeFunctions()
virtual void MPoint::getShapeFunctions (double u, double v, double w, double s[], int o) const inline virtual
Reimplemented from MElement.
Reimplemented in MSubPoint.
Definition at line 59 of file MPoint.h.
getStringForPOS()
virtual const char* MPoint::getStringForPOS () const inline virtual
Reimplemented from MElement.
Definition at line 53 of file MPoint.h.
getType()
virtual int MPoint::getType () const inline virtual
Implements MElement.
Definition at line 50 of file MPoint.h.
getTypeForMSH()
virtual int MPoint::getTypeForMSH () const inline virtual
Reimplemented from MElement.
Reimplemented in MSubPoint.
Definition at line 51 of file MPoint.h.
getTypeForVTK()
virtual int MPoint::getTypeForVTK () const inline virtual
Reimplemented from MElement.
Definition at line 52 of file MPoint.h.
getVertex() [1/2]
virtual MVertex* MPoint::getVertex (int num) inline virtual
Implements MElement.
Definition at line 33 of file MPoint.h.
Referenced by MSubPoint::getIntegrationPoints().
getVertex() [2/2]
virtual const MVertex* MPoint::getVertex (int num) const inline virtual
Implements MElement.
Definition at line 34 of file MPoint.h.
isInside()
virtual bool MPoint::isInside (double u, double v, double w) const inline virtual
Implements MElement.
Reimplemented in MSubPoint.
Definition at line 73 of file MPoint.h.
numCommonNodesInDualGraph()
virtual int MPoint::numCommonNodesInDualGraph (const MElement *const other) const inline virtual
Implements MElement.
Definition at line 89 of file MPoint.h.
setVertex()
virtual void MPoint::setVertex (int num, MVertex * v) inline virtual
Reimplemented from MElement.
Definition at line 35 of file MPoint.h.
Member Data Documentation
_v
MVertex* MPoint::_v[1] protected
Definition at line 18 of file MPoint.h.
Referenced by getVertex(), MPoint(), and setVertex().
The documentation for this class was generated from the following file:
src/geo/MPoint.h