gmsh-TingyuanDoc: MPrism15 Class Reference
MPrism15 Class Reference
#include <MPrism.h>
Public Member Functions
MPrism15 (MVertex *v0, MVertex *v1, MVertex *v2, MVertex *v3, MVertex *v4, MVertex *v5, MVertex *v6, MVertex *v7, MVertex *v8, MVertex *v9, MVertex *v10, MVertex *v11, MVertex *v12, MVertex *v13, MVertex *v14, int num=0, int part=0)
MPrism15 (const std::vector< MVertex * > &v, int num=0, int part=0)
~MPrism15 ()
virtual int getPolynomialOrder () const
virtual std::size_t getNumVertices () const
virtual MVertex * getVertex (int num)
virtual const MVertex * getVertex (int num) const
virtual void setVertex (int num, MVertex *v)
virtual MVertex * getVertexUNV (int num)
virtual MVertex * getVertexBDF (int num)
virtual MVertex * getVertexINP (int num)
virtual MVertex * getVertexVTK (int num)
virtual MVertex * getVertexKEY (int num)
virtual int getNumEdgeVertices () const
virtual int getNumEdgesRep (bool curved)
virtual void getEdgeRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getEdgeVertices (const int num, std::vector< MVertex * > &v) const
virtual int getNumFacesRep (bool curved)
virtual void getFaceRep (bool curved, int num, double *x, double *y, double *z, SVector3 *n)
virtual void getFaceVertices (const int num, std::vector< MVertex * > &v) const
virtual int getTypeForMSH () const
virtual int getTypeForUNV () const
virtual int getTypeForVTK () const
virtual const char * getStringForBDF () const
virtual const char * getStringForINP () const
virtual const char * getStringForKEY () const
virtual void reverse ()
virtual void getNode (int num, double &u, double &v, double &w) const
Public Member Functions inherited from MPrism
MPrism (MVertex *v0, MVertex *v1, MVertex *v2, MVertex *v3, MVertex *v4, MVertex *v5, int num=0, int part=0)
MPrism (const std::vector< MVertex * > &v, int num=0, int part=0)
~MPrism ()
virtual int getDim () const
virtual double getInnerRadius ()
virtual int getNumEdges () const
virtual MEdge getEdge (int num) const
virtual int numEdge2numVertex (int numEdge, int numVert) const
virtual int getNumFaces ()
virtual bool getFaceInfo (const MFace &face, int &ithFace, int &sign, int &rot) const
virtual MFace getFace (int num) const
virtual int getType () const
virtual const char * getStringForPOS () const
virtual const char * getStringForRAD () const
virtual double gammaShapeMeasure ()
virtual int getVolumeSign ()
virtual SPoint3 barycenterUVW () const
virtual bool isInside (double u, double v, double w) const
virtual void getIntegrationPoints (int pOrder, int *npts, IntPt **pts)
virtual int numCommonNodesInDualGraph (const MElement *const other) const
virtual MEdge getEdgeSolin (int num)
virtual MFace getFaceSolin (int num)
Public Member Functions inherited from MElement
MElement (std::size_t num=0, int part=0)
virtual ~MElement ()
double getTolerance () const
virtual std::size_t getNum () const
void forceNum (std::size_t num)
virtual bool getIsAssimilatedSerendipity () const
virtual bool getIsOnlySerendipity () const
virtual int getPartition () const
virtual void setPartition (int num)
virtual char getVisibility () const
virtual void setVisibility (char val)
void getVertices (std::vector< MVertex * > &verts)
virtual void getVertexInfo (const MVertex *vertex, int &ithVertex) const
virtual MVertex * getVertexMATLAB (int num)
virtual MVertex * getVertexTOCHNOG (int num)
virtual MVertex * getVertexDIFF (int num)
virtual MVertex * getVertexRAD (int num)
virtual MVertex * getVertexNEU (int num)
virtual int getNumFaceVertices () const
virtual int getNumVolumeVertices () const
std::size_t getNumPrimaryVertices () const
virtual MEdgeN getHighOrderEdge (int num, int sign)
MEdgeN getHighOrderEdge (const MEdge &edge)
virtual bool getEdgeInfo (const MEdge &edge, int &ithEdge, int &sign) const
virtual MFaceN getHighOrderFace (int num, int sign, int rot)
MFaceN getHighOrderFace (const MFace &face)
virtual MElement * getParent () const
virtual void setParent (MElement *p, bool owner=false)
virtual void updateParent (GModel *gm)
virtual int getNumChildren () const
virtual MElement * getChild (int i) const
virtual bool ownsParent () const
virtual const MElement * getBaseElement () const
virtual MElement * getBaseElement ()
virtual MElement * getDomain (int i) const
virtual void setDomain (MElement *e, int i)
virtual double maxEdge ()
virtual double minEdge ()
double maxDistToStraight () const
double skewness ()
virtual double etaShapeMeasure ()
double minSICNShapeMeasure ()
double minSIGEShapeMeasure ()
double distoShapeMeasure ()
double minIsotropyMeasure (bool knownValid=false, bool reversedOk=false)
double minScaledJacobian (bool knownValid=false, bool reversedOk=false)
virtual double angleShapeMeasure ()
virtual void scaledJacRange (double &jmin, double &jmax, GEntity *ge=nullptr) const
virtual void idealJacRange (double &jmin, double &jmax, GEntity *ge=nullptr)
virtual void signedInvCondNumRange (double &iCNMin, double &iCNMax, GEntity *ge=nullptr)
virtual void signedInvGradErrorRange (double &minSIGE, double &maxSIGE)
virtual double getOuterRadius ()
virtual SPoint3 barycenter (bool primary=false) const
virtual SPoint3 fastBarycenter (bool primary=false) const
virtual SPoint3 barycenter_infty () const
virtual double getVolume ()
virtual bool setVolumePositive ()
int getValidity ()
virtual std::string getInfoString (bool multline)
virtual const nodalBasis * getFunctionSpace (int order=-1, bool serendip=false) const
virtual const FuncSpaceData getFuncSpaceData (int order=-1, bool serendip=false) const
virtual const JacobianBasis * getJacobianFuncSpace (int orderElement=-1) const
virtual const FuncSpaceData getJacobianFuncSpaceData (int orderElement=-1) const
virtual void getShapeFunctions (double u, double v, double w, double s[], int order=-1) const
virtual void getGradShapeFunctions (double u, double v, double w, double s[][3], int order=-1) const
virtual void getHessShapeFunctions (double u, double v, double w, double s[][3][3], int order=-1) const
virtual void getThirdDerivativeShapeFunctions (double u, double v, double w, double s[][3][3][3], int order=-1) const
virtual double getJacobian (const fullMatrix< double > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double jac[3][3]) const
virtual double getJacobian (const std::vector< SVector3 > &gsf, double *jac) const
virtual double getJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobian (double u, double v, double w, fullMatrix< double > &j) const
virtual double getPrimaryJacobian (double u, double v, double w, double jac[3][3]) const
double getJacobianDeterminant (double u, double v, double w) const
void getSignedJacobian (fullVector< double > &jacobian, int o=-1) const
void getNodesCoord (fullMatrix< double > &nodesXYZ) const
void getNodesCoordNonSerendip (fullMatrix< double > &nodesXYZ) const
bezierCoeff * getBezierVerticesCoord () const
virtual std::size_t getNumShapeFunctions () const
virtual std::size_t getNumPrimaryShapeFunctions () const
virtual const MVertex * getShapeFunctionNode (int i) const
virtual MVertex * getShapeFunctionNode (int i)
virtual double getEigenvaluesMetric (double u, double v, double w, double values[3]) const
virtual void pnt (double u, double v, double w, SPoint3 &p) const
virtual void pnt (double u, double v, double w, double *p) const
virtual void pnt (const std::vector< double > &sf, SPoint3 &p) const
virtual void primaryPnt (double u, double v, double w, SPoint3 &p)
virtual void xyz2uvw (double xyz[3], double uvw[3]) const
virtual void movePointFromParentSpaceToElementSpace (double &u, double &v, double &w) const
virtual void movePointFromElementSpaceToParentSpace (double &u, double &v, double &w) const
double interpolate (double val[], double u, double v, double w, int stride=1, int order=-1)
void interpolateGrad (double val[], double u, double v, double w, double f[], int stride=1, double invjac[3][3]=nullptr, int order=-1)
void interpolateCurl (double val[], double u, double v, double w, double f[], int stride=3, int order=-1)
double interpolateDiv (double val[], double u, double v, double w, int stride=3, int order=-1)
double integrate (double val[], int pOrder, int stride=1, int order=-1)
double integrateCirc (double val[], int edge, int pOrder, int order=-1)
double integrateFlux (double val[], int face, int pOrder, int order=-1)
virtual void writeMSH2 (FILE *fp, double version=1.0, bool binary=false, int num=0, int elementary=1, int physical=1, int parentNum=0, int dom1Num=0, int dom2Num=0, std::vector< short > *ghosts=nullptr)
virtual void writeMSH3 (FILE *fp, bool binary=false, int elementary=1, std::vector< short > *ghosts=nullptr)
virtual void writePOS (FILE *fp, bool printElementary, bool printElementNumber, bool printSICN, bool printSIGE, bool printGamma, bool printDisto, double scalingFactor=1.0, int elementary=1)
virtual void writeSTL (FILE *fp, bool binary=false, double scalingFactor=1.0)
virtual void writeX3D (FILE *fp, double scalingFactor=1.0)
virtual void writeVRML (FILE *fp)
virtual void writePLY2 (FILE *fp)
virtual void writeUNV (FILE *fp, int num=0, int elementary=1, int physical=1)
virtual void writeVTK (FILE *fp, bool binary=false, bool bigEndian=false)
virtual void writeMATLAB (FILE *fp, int filetype, int elementary=0, int physical=0, bool binary=false)
virtual void writeTOCHNOG (FILE *fp, int num)
virtual void writeMESH (FILE *fp, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeNEU (FILE *fp, unsigned gambitType, int adjust, int phys=0)
virtual void writeIR3 (FILE *fp, int elementTagType, int num, int elementary, int physical)
virtual void writeBDF (FILE *fp, int format=0, int elementTagType=1, int elementary=1, int physical=0)
virtual void writeDIFF (FILE *fp, int num, bool binary=false, int physical_property=1)
virtual void writeINP (FILE *fp, int num)
virtual void writeKEY (FILE *fp, int pid, int num)
virtual void writeRAD (FILE *fp, int num)
virtual void writeSU2 (FILE *fp, int num)
virtual const char * getStringForTOCHNOG () const
virtual const char * getStringForDIFF () const
std::string getName ()
virtual std::size_t getNumVerticesForMSH ()
virtual void getVerticesIdForMSH (std::vector< int > &verts)
virtual MElement * copy (std::map< int, MVertex * > &vertexMap, std::map< MElement *, MElement * > &newParents, std::map< MElement *, MElement * > &newDomains)
Protected Attributes
MVertex * _vs [9]
Protected Attributes inherited from MPrism
MVertex * _v [6]
Additional Inherited Members
Static Public Member Functions inherited from MPrism
static int edges_prism (const int edge, const int vert)
static int faces_prism (const int face, const int vert)
static int faces2edge_prism (const int face, const int edge)
static int faceClosureEdge2edge (const int face, const int edge)
Static Public Member Functions inherited from MElement
static unsigned int getInfoMSH (const int typeMSH, const char **const name=nullptr)
Protected Member Functions inherited from MPrism
void _getEdgeVertices (const int num, std::vector< MVertex * > &v) const
void _getFaceVertices (const int num, std::vector< MVertex * > &v) const
Protected Member Functions inherited from MElement
void _getEdgeRep (MVertex *v0, MVertex *v1, double *x, double *y, double *z, SVector3 *n, int faceIndex=-1)
void _getFaceRep (MVertex *v0, MVertex *v1, MVertex *v2, double *x, double *y, double *z, SVector3 *n)
Static Protected Member Functions inherited from MElement
static bool _getFaceInfo (const MFace &face, const MFace &other, int &sign, int &rot)
Static Protected Attributes inherited from MElement
static double _isInsideTolerance
Detailed Description
Definition at line 263 of file MPrism.h.
Constructor & Destructor Documentation
MPrism15() [1/2]
MPrism15::MPrism15 (MVertex * v0, MVertex * v1, MVertex * v2, MVertex * v3, MVertex * v4, MVertex * v5, MVertex * v6, MVertex * v7, MVertex * v8, MVertex * v9, MVertex * v10, MVertex * v11, MVertex * v12, MVertex * v13, MVertex * v14, int num = 0, int part = 0) inline
Definition at line 268 of file MPrism.h.
MPrism15() [2/2]
MPrism15::MPrism15 (const std::vector< MVertex * > & v, int num = 0, int part = 0) inline
Definition at line 285 of file MPrism.h.
~MPrism15()
MPrism15::~MPrism15 () inline
Definition at line 291 of file MPrism.h.
Member Function Documentation
getEdgeRep()
void MPrism15::getEdgeRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Reimplemented from MPrism.
Definition at line 138 of file MPrism.cpp.
getEdgeVertices()
virtual void MPrism15::getEdgeVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MPrism.
Definition at line 338 of file MPrism.h.
getFaceRep()
void MPrism15::getFaceRep (bool curved, int num, double * x, double * y, double * z, SVector3 * n) virtual
Reimplemented from MPrism.
Definition at line 425 of file MPrism.cpp.
getFaceVertices()
virtual void MPrism15::getFaceVertices (const int num, std::vector< MVertex * > & v) const inline virtual
Reimplemented from MPrism.
Definition at line 347 of file MPrism.h.
getNode()
virtual void MPrism15::getNode (int num, double & u, double & v, double & w) const inline virtual
Reimplemented from MPrism.
Definition at line 387 of file MPrism.h.
getNumEdgesRep()
int MPrism15::getNumEdgesRep (bool curved) virtual
Reimplemented from MPrism.
Definition at line 165 of file MPrism.cpp.
getNumEdgeVertices()
virtual int MPrism15::getNumEdgeVertices () const inline virtual
Reimplemented from MElement.
Definition at line 334 of file MPrism.h.
getNumFacesRep()
int MPrism15::getNumFacesRep (bool curved) virtual
Reimplemented from MPrism.
Definition at line 464 of file MPrism.cpp.
getNumVertices()
virtual std::size_t MPrism15::getNumVertices () const inline virtual
Reimplemented from MPrism.
Definition at line 293 of file MPrism.h.
getPolynomialOrder()
virtual int MPrism15::getPolynomialOrder () const inline virtual
Reimplemented from MElement.
Definition at line 292 of file MPrism.h.
getStringForBDF()
virtual const char* MPrism15::getStringForBDF () const inline virtual
Reimplemented from MPrism.
Definition at line 362 of file MPrism.h.
getStringForINP()
virtual const char* MPrism15::getStringForINP () const inline virtual
Reimplemented from MPrism.
Definition at line 363 of file MPrism.h.
getStringForKEY()
virtual const char* MPrism15::getStringForKEY () const inline virtual
Reimplemented from MPrism.
Definition at line 364 of file MPrism.h.
getTypeForMSH()
virtual int MPrism15::getTypeForMSH () const inline virtual
Reimplemented from MPrism.
Definition at line 359 of file MPrism.h.
getTypeForUNV()
virtual int MPrism15::getTypeForUNV () const inline virtual
Reimplemented from MPrism.
Definition at line 360 of file MPrism.h.
getTypeForVTK()
virtual int MPrism15::getTypeForVTK () const inline virtual
Reimplemented from MPrism.
Definition at line 361 of file MPrism.h.
getVertex() [1/2]
virtual MVertex* MPrism15::getVertex (int num) inline virtual
Reimplemented from MPrism.
Definition at line 294 of file MPrism.h.
Referenced by getVertexBDF(), getVertexINP(), getVertexUNV(), and getVertexVTK().
getVertex() [2/2]
virtual const MVertex* MPrism15::getVertex (int num) const inline virtual
Reimplemented from MPrism.
Definition at line 298 of file MPrism.h.
getVertexBDF()
virtual MVertex* MPrism15::getVertexBDF (int num) inline virtual
Reimplemented from MElement.
Definition at line 315 of file MPrism.h.
Referenced by getVertexKEY().
getVertexINP()
virtual MVertex* MPrism15::getVertexINP (int num) inline virtual
Reimplemented from MElement.
Definition at line 321 of file MPrism.h.
getVertexKEY()
virtual MVertex* MPrism15::getVertexKEY (int num) inline virtual
Reimplemented from MElement.
Definition at line 333 of file MPrism.h.
getVertexUNV()
virtual MVertex* MPrism15::getVertexUNV (int num) inline virtual
Reimplemented from MElement.
Definition at line 309 of file MPrism.h.
getVertexVTK()
virtual MVertex* MPrism15::getVertexVTK (int num) inline virtual
Reimplemented from MPrism.
Definition at line 327 of file MPrism.h.
reverse()
virtual void MPrism15::reverse () inline virtual
Reimplemented from MPrism.
Definition at line 368 of file MPrism.h.
setVertex()
virtual void MPrism15::setVertex (int num, MVertex * v) inline virtual
Reimplemented from MPrism.
Definition at line 302 of file MPrism.h.
Member Data Documentation
_vs
MVertex* MPrism15::_vs[9] protected
Definition at line 265 of file MPrism.h.
Referenced by getEdgeVertices(), getFaceVertices(), getVertex(), MPrism15(), reverse(), and setVertex().
The documentation for this class was generated from the following files:
src/geo/MPrism.h
src/geo/MPrism.cpp