gmsh-TingyuanDoc: BilinearTermBase Class Reference
BilinearTermBase Class Reference abstract
#include <terms.h>
Public Member Functions
virtual ~BilinearTermBase ()
virtual void get (MElement *ele, int npts, IntPt *GP, fullMatrix< double > &m) const
virtual void get (MElement *ele, int npts, IntPt *GP, std::vector< fullMatrix< double > > &mv) const =0
virtual BilinearTermBase * clone () const =0
Detailed Description
Definition at line 93 of file terms.h.
Constructor & Destructor Documentation
~BilinearTermBase()
virtual BilinearTermBase::~BilinearTermBase () inline virtual
Definition at line 95 of file terms.h.
Member Function Documentation
clone()
virtual BilinearTermBase* BilinearTermBase::clone () const pure virtual
Implemented in LagMultTerm, LagrangeMultiplierTerm< T1 >, IsotropicElasticTerm, LaplaceTerm< T1, T1 >, LaplaceTerm< T1, T2 >, BilinearTermContractWithLaw< T2 >, and BilinearTermContract< T2 >.
get() [1/2]
void BilinearTermBase::get (MElement * ele, int npts, IntPt * GP, fullMatrix< double > & m) const virtual
Reimplemented in LagMultTerm, LagrangeMultiplierTerm< T1 >, IsotropicElasticTerm, LaplaceTerm< T1, T1 >, LaplaceTerm< T1, T2 >, BilinearTermContractWithLaw< T2 >, and BilinearTermContract< T2 >.
Definition at line 20 of file terms.cpp.
Referenced by Assemble(), BilinearTermToScalarTerm::get(), and BilinearTermContractWithLaw< T2 >::get().
get() [2/2]
virtual void BilinearTermBase::get (MElement * ele, int npts, IntPt * GP, std::vector< fullMatrix< double > > & mv) const pure virtual
Implemented in LagMultTerm, LagrangeMultiplierTerm< T1 >, IsotropicElasticTerm, LaplaceTerm< T1, T1 >, LaplaceTerm< T1, T2 >, BilinearTermContractWithLaw< T2 >, and BilinearTermContract< T2 >.
The documentation for this class was generated from the following files:
src/solver/terms.h
src/solver/terms.cpp