gmsh-TingyuanDoc: bezierBasisRaiser Class Reference
bezierBasisRaiser Class Reference
#include <bezierBasis.h>
Classes
class _data
Public Member Functions
bezierBasisRaiser (const bezierBasis *bezier)
void computeCoeff (const fullVector< double > &coeffA, const fullVector< double > &coeffB, fullVector< double > &coeffSquare) const
void computeCoeff (const fullVector< double > &coeffA, const fullVector< double > &coeffB, const fullVector< double > &coeffC, fullVector< double > &coeffCubic) const
Private Member Functions
void _fillRaiserData ()
void _fillRaiserDataPyr ()
Private Attributes
std::vector< std::vector< _data > > _raiser2
std::vector< std::vector< _data > > _raiser3
const bezierBasis * _bfs
Detailed Description
Definition at line 60 of file bezierBasis.h.
Constructor & Destructor Documentation
bezierBasisRaiser()
bezierBasisRaiser::bezierBasisRaiser (const bezierBasis * bezier) inline
Definition at line 81 of file bezierBasis.h.
Member Function Documentation
_fillRaiserData()
void bezierBasisRaiser::_fillRaiserData () private
Definition at line 291 of file bezierBasis.cpp.
Referenced by _fillRaiserDataPyr(), and bezierBasisRaiser().
_fillRaiserDataPyr()
void bezierBasisRaiser::_fillRaiserDataPyr () private
Definition at line 434 of file bezierBasis.cpp.
Referenced by _fillRaiserData().
computeCoeff() [1/2]
void bezierBasisRaiser::computeCoeff (const fullVector< double > & coeffA, const fullVector< double > & coeffB, const fullVector< double > & coeffC, fullVector< double > & coeffCubic) const
Definition at line 577 of file bezierBasis.cpp.
computeCoeff() [2/2]
void bezierBasisRaiser::computeCoeff (const fullVector< double > & coeffA, const fullVector< double > & coeffB, fullVector< double > & coeffSquare) const
Definition at line 552 of file bezierBasis.cpp.
Referenced by jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), and jacobianBasedQuality::_coeffDataICN::_computeLowerBound().
Member Data Documentation
_bfs
const bezierBasis* bezierBasisRaiser::_bfs private
Definition at line 78 of file bezierBasis.h.
Referenced by _fillRaiserData(), and _fillRaiserDataPyr().
_raiser2
std::vector<std::vector<_data> > bezierBasisRaiser::_raiser2 private
Definition at line 77 of file bezierBasis.h.
Referenced by _fillRaiserData(), _fillRaiserDataPyr(), and computeCoeff().
_raiser3
std::vector<std::vector<_data> > bezierBasisRaiser::_raiser3 private
Definition at line 77 of file bezierBasis.h.
Referenced by _fillRaiserData(), _fillRaiserDataPyr(), and computeCoeff().
The documentation for this class was generated from the following files:
src/numeric/bezierBasis.h
src/numeric/bezierBasis.cpp