gmsh-TingyuanDoc: linearSystem< scalar > Class Template Reference
linearSystem< scalar > Class Template Reference abstract
#include <linearSystem.h>
Public Member Functions
linearSystem ()
virtual ~linearSystem ()
virtual void addToMatrix (int _row, int _col, const scalar &val)=0
virtual void getFromMatrix (int _row, int _col, scalar &val) const =0
virtual void addToRightHandSide (int _row, const scalar &val, int ith=0)=0
virtual void getFromRightHandSide (int _row, scalar &val) const =0
virtual void getFromSolution (int _row, scalar &val) const =0
virtual void addToSolution (int _row, const scalar &val)=0
Public Member Functions inherited from linearSystemBase
virtual ~linearSystemBase ()
virtual bool isAllocated () const =0
virtual void allocate (int nbRows)=0
virtual void preAllocateEntries ()
virtual void clear ()=0
virtual void zeroMatrix ()=0
virtual void zeroRightHandSide ()=0
virtual void zeroSolution ()=0
virtual int systemSolve ()=0
virtual int matMult ()
void setParameter (const std::string &key, std::string value)
std::string getParameter (const std::string &key) const
virtual void insertInSparsityPattern (int _row, int _col)
virtual double normInfRightHandSide () const =0
virtual double normInfSolution () const
Additional Inherited Members
Protected Attributes inherited from linearSystemBase
std::map< std::string, std::string > _parameters
Detailed Description
template<class scalar>
class linearSystem< scalar >
Definition at line 38 of file linearSystem.h.
Constructor & Destructor Documentation
linearSystem()
template<class scalar > linearSystem< scalar >::linearSystem () inline
Definition at line 40 of file linearSystem.h.
~linearSystem()
template<class scalar > virtual linearSystem< scalar >::~linearSystem () inline virtual
Definition at line 41 of file linearSystem.h.
Member Function Documentation
addToMatrix()
template<class scalar > virtual void linearSystem< scalar >::addToMatrix (int _row, int _col, const scalar & val) pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemGmm< scalar >, linearSystemFull< scalar >, and linearSystemCSR< scalar >.
Referenced by dofManager< double >::assemble().
addToRightHandSide()
template<class scalar > virtual void linearSystem< scalar >::addToRightHandSide (int _row, const scalar & val, int ith = 0) pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemGmm< scalar >, linearSystemCSR< scalar >, and linearSystemFull< scalar >.
Referenced by dofManager< double >::assemble(), and dofManager< double >::assembleLinConst().
addToSolution()
template<class scalar > virtual void linearSystem< scalar >::addToSolution (int _row, const scalar & val) pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemGmm< scalar >, linearSystemCSR< scalar >, and linearSystemFull< scalar >.
getFromMatrix()
template<class scalar > virtual void linearSystem< scalar >::getFromMatrix (int _row, int _col, scalar & val) const pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemGmm< scalar >, linearSystemCSR< scalar >, and linearSystemFull< scalar >.
Referenced by elasticitySolver::exportKb().
getFromRightHandSide()
template<class scalar > virtual void linearSystem< scalar >::getFromRightHandSide (int _row, scalar & val) const pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemGmm< scalar >, linearSystemCSR< scalar >, and linearSystemFull< scalar >.
Referenced by elasticitySolver::exportKb().
getFromSolution()
template<class scalar > virtual void linearSystem< scalar >::getFromSolution (int _row, scalar & val) const pure virtual
Implemented in linearSystemPETSc< scalar >, linearSystemCSR< scalar >, linearSystemGmm< scalar >, and linearSystemFull< scalar >.
Referenced by dofManager< double >::getAnUnknown(), and dofManager< double >::getDofValue().
The documentation for this class was generated from the following file:
src/solver/linearSystem.h