gmsh-TingyuanDoc: robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs > Class Template Reference
robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs > Class Template Reference
#include <robin_hood.h>
Public Member Functions
BulkPoolAllocator () noexcept=default
BulkPoolAllocator (const BulkPoolAllocator &ROBIN_HOOD_UNUSED(o)) noexcept
BulkPoolAllocator (BulkPoolAllocator &&o) noexcept
BulkPoolAllocator & operator= (BulkPoolAllocator &&o) noexcept
BulkPoolAllocator & operator= (const BulkPoolAllocator &ROBIN_HOOD_UNUSED(o)) noexcept
~BulkPoolAllocator () noexcept
void reset () noexcept
T * allocate ()
void deallocate (T *obj) noexcept
void addOrFree (void *ptr, const size_t numBytes) noexcept
void swap (BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs > &other) noexcept
Private Member Functions
ROBIN_HOOD (NODISCARD) size_t calcNumElementsToAlloc() const noexcept
void add (void *ptr, const size_t numBytes) noexcept
ROBIN_HOOD (NOINLINE) T *performAllocation()
Private Attributes
T * mHead {nullptr}
T ** mListForFree {nullptr}
Static Private Attributes
static const size_t ALIGNMENT
static constexpr size_t ALIGNED_SIZE = ((sizeof(T) - 1) / ALIGNMENT + 1) * ALIGNMENT
Detailed Description
template<typename T, size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256>
class robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >
Definition at line 367 of file robin_hood.h.
Constructor & Destructor Documentation
BulkPoolAllocator() [1/3]
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::BulkPoolAllocator () default noexcept
BulkPoolAllocator() [2/3]
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::BulkPoolAllocator (const BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs > & ROBIN_HOOD_UNUSEDo) inline noexcept
Definition at line 372 of file robin_hood.h.
BulkPoolAllocator() [3/3]
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::BulkPoolAllocator (BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs > && o) inline noexcept
Definition at line 376 of file robin_hood.h.
~BulkPoolAllocator()
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::~BulkPoolAllocator () inline noexcept
Definition at line 399 of file robin_hood.h.
Member Function Documentation
add()
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> void robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::add (void * ptr, const size_t numBytes) inline private noexcept
Definition at line 476 of file robin_hood.h.
Referenced by robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::addOrFree(), and robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::ROBIN_HOOD().
addOrFree()
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> void robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::addOrFree (void * ptr, const size_t numBytes) inline noexcept
Definition at line 439 of file robin_hood.h.
allocate()
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> T* robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::allocate () inline
Definition at line 417 of file robin_hood.h.
deallocate()
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> void robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::deallocate (T * obj) inline noexcept
Definition at line 431 of file robin_hood.h.
operator=() [1/2]
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> BulkPoolAllocator& robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::operator= (BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs > && o) inline noexcept
Definition at line 383 of file robin_hood.h.
operator=() [2/2]
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> BulkPoolAllocator& robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::operator= (const BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs > & ROBIN_HOOD_UNUSEDo) inline noexcept
Definition at line 394 of file robin_hood.h.
reset()
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> void robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::reset () inline noexcept
Definition at line 404 of file robin_hood.h.
Referenced by robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::operator=(), and robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::~BulkPoolAllocator().
ROBIN_HOOD() [1/2]
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::ROBIN_HOOD (NODISCARD) const inline private noexcept
Definition at line 462 of file robin_hood.h.
ROBIN_HOOD() [2/2]
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::ROBIN_HOOD (NOINLINE) inline private
Definition at line 506 of file robin_hood.h.
swap()
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> void robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::swap (BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs > & other) inline noexcept
Definition at line 451 of file robin_hood.h.
Referenced by robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::swap().
Member Data Documentation
ALIGNED_SIZE
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> constexpr size_t robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::ALIGNED_SIZE = ((sizeof(T) - 1) / ALIGNMENT + 1) * ALIGNMENT static constexpr private
Definition at line 528 of file robin_hood.h.
Referenced by robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::add(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::addOrFree(), and robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::ROBIN_HOOD().
ALIGNMENT
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> const size_t robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::ALIGNMENT static private
Initial value:
=
        (ROBIN_HOOD_STD::alignment_of<T>::value > ROBIN_HOOD_STD::alignment_of<T*>::value)
            ? ROBIN_HOOD_STD::alignment_of<T>::value
            : +ROBIN_HOOD_STD::alignment_of<T*>::value
Definition at line 522 of file robin_hood.h.
Referenced by robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::add(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::addOrFree(), and robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::ROBIN_HOOD().
mHead
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> T* robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::mHead {nullptr} private
Definition at line 536 of file robin_hood.h.
Referenced by robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::add(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::allocate(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::deallocate(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::operator=(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::reset(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::ROBIN_HOOD(), and robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::swap().
mListForFree
template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> T** robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >::mListForFree {nullptr} private
Definition at line 537 of file robin_hood.h.
Referenced by robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::add(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::operator=(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::reset(), robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::ROBIN_HOOD(), and robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >::swap().
The documentation for this class was generated from the following file:
src/common/robin_hood.h