gmsh-TingyuanDoc: GMSH_ParticlesPlugin Class Reference
GMSH_ParticlesPlugin Class Reference
#include <Particles.h>
Public Member Functions
GMSH_ParticlesPlugin ()
std::string getName () const
std::string getShortHelp () const
std::string getHelp () const
int getNbOptions () const
StringXNumber * getOption (int iopt)
PView * execute (PView *)
Public Member Functions inherited from GMSH_PostPlugin
GMSH_PLUGIN_TYPE getType () const
virtual int run ()
virtual PView * executeRemote (PView *)
virtual PView * getView (int index, PView *view)
virtual PViewDataList * getDataList (PView *view, bool showError=true)
virtual PViewData * getPossiblyAdaptiveData (PView *view)
virtual void assignSpecificVisibility () const
virtual bool geometricalFilter (fullMatrix< double > *) const
Public Member Functions inherited from GMSH_Plugin
GMSH_Plugin ()
virtual ~GMSH_Plugin ()
virtual std::string getAuthor () const
virtual std::string getCopyright () const
virtual void catchErrorMessage (char *errorMessage) const
virtual int getNbOptionsStr () const
virtual StringXString * getOptionStr (int iopt)
std::string serialize ()
Static Public Member Functions
static int getNbU ()
static int getNbV ()
static void getPoint (int iU, int iV, double *X)
static double callbackX0 (int, int, double)
static double callbackY0 (int, int, double)
static double callbackZ0 (int, int, double)
static double callbackX1 (int, int, double)
static double callbackY1 (int, int, double)
static double callbackZ1 (int, int, double)
static double callbackX2 (int, int, double)
static double callbackY2 (int, int, double)
static double callbackZ2 (int, int, double)
static double callbackU (int, int, double)
static double callbackV (int, int, double)
static void draw (void *context)
Static Public Member Functions inherited from GMSH_Plugin
static void setDrawFunction (void(*fct)(void *))
Static Private Member Functions
static double callback (int num, int action, double value, double *opt, double step, double min, double max)
Additional Inherited Members
Public Types inherited from GMSH_Plugin
enum GMSH_PLUGIN_TYPE { GMSH_CAD_PLUGIN, GMSH_MESH_PLUGIN, GMSH_POST_PLUGIN, GMSH_SOLVER_PLUGIN }
Public Attributes inherited from GMSH_Plugin
PluginDialogBox * dialogBox
void * hlib
Static Public Attributes inherited from GMSH_Plugin
static void(* draw)(void *) = nullptr
Detailed Description
Definition at line 15 of file Particles.h.
Constructor & Destructor Documentation
GMSH_ParticlesPlugin()
GMSH_ParticlesPlugin::GMSH_ParticlesPlugin () inline
Definition at line 20 of file Particles.h.
Member Function Documentation
callback()
double GMSH_ParticlesPlugin::callback (int num, int action, double value, double * opt, double step, double min, double max) static private
Definition at line 59 of file Particles.cpp.
Referenced by callbackU(), callbackV(), callbackX0(), callbackX1(), callbackX2(), callbackY0(), callbackY1(), callbackY2(), callbackZ0(), callbackZ1(), and callbackZ2().
callbackU()
double GMSH_ParticlesPlugin::callbackU (int num, int action, double value) static
Definition at line 137 of file Particles.cpp.
callbackV()
double GMSH_ParticlesPlugin::callbackV (int num, int action, double value) static
Definition at line 143 of file Particles.cpp.
callbackX0()
double GMSH_ParticlesPlugin::callbackX0 (int num, int action, double value) static
Definition at line 74 of file Particles.cpp.
callbackX1()
double GMSH_ParticlesPlugin::callbackX1 (int num, int action, double value) static
Definition at line 95 of file Particles.cpp.
callbackX2()
double GMSH_ParticlesPlugin::callbackX2 (int num, int action, double value) static
Definition at line 116 of file Particles.cpp.
callbackY0()
double GMSH_ParticlesPlugin::callbackY0 (int num, int action, double value) static
Definition at line 81 of file Particles.cpp.
callbackY1()
double GMSH_ParticlesPlugin::callbackY1 (int num, int action, double value) static
Definition at line 102 of file Particles.cpp.
callbackY2()
double GMSH_ParticlesPlugin::callbackY2 (int num, int action, double value) static
Definition at line 123 of file Particles.cpp.
callbackZ0()
double GMSH_ParticlesPlugin::callbackZ0 (int num, int action, double value) static
Definition at line 88 of file Particles.cpp.
callbackZ1()
double GMSH_ParticlesPlugin::callbackZ1 (int num, int action, double value) static
Definition at line 109 of file Particles.cpp.
callbackZ2()
double GMSH_ParticlesPlugin::callbackZ2 (int num, int action, double value) static
Definition at line 130 of file Particles.cpp.
draw()
void GMSH_ParticlesPlugin::draw (void * context) static
Definition at line 44 of file Particles.cpp.
execute()
PView * GMSH_ParticlesPlugin::execute (PView * v) virtual
Implements GMSH_PostPlugin.
Definition at line 208 of file Particles.cpp.
getHelp()
std::string GMSH_ParticlesPlugin::getHelp () const virtual
Implements GMSH_Plugin.
Definition at line 149 of file Particles.cpp.
getName()
std::string GMSH_ParticlesPlugin::getName () const inline virtual
Implements GMSH_Plugin.
Definition at line 21 of file Particles.h.
getNbOptions()
int GMSH_ParticlesPlugin::getNbOptions () const virtual
Reimplemented from GMSH_Plugin.
Definition at line 173 of file Particles.cpp.
getNbU()
int GMSH_ParticlesPlugin::getNbU () static
Definition at line 183 of file Particles.cpp.
Referenced by draw(), execute(), and getPoint().
getNbV()
int GMSH_ParticlesPlugin::getNbV () static
Definition at line 188 of file Particles.cpp.
Referenced by draw(), execute(), and getPoint().
getOption()
StringXNumber * GMSH_ParticlesPlugin::getOption (int iopt) virtual
Reimplemented from GMSH_Plugin.
Definition at line 178 of file Particles.cpp.
getPoint()
void GMSH_ParticlesPlugin::getPoint (int iU, int iV, double * X) static
Definition at line 193 of file Particles.cpp.
Referenced by draw(), and execute().
getShortHelp()
std::string GMSH_ParticlesPlugin::getShortHelp () const inline virtual
Implements GMSH_Plugin.
Definition at line 22 of file Particles.h.
The documentation for this class was generated from the following files:
src/plugin/Particles.h
src/plugin/Particles.cpp