gmsh-TingyuanDoc: elementFactory Class Reference
elementFactory Class Reference
#include <shapeFunctions.h>
Public Member Functions
element * create (int numNodes, int dimension, double *x, double *y, double *z, bool copy=false)
Detailed Description
Definition at line 1402 of file shapeFunctions.h.
Member Function Documentation
create()
element* elementFactory::create (int numNodes, int dimension, double * x, double * y, double * z, bool copy = false) inline
Definition at line 1404 of file shapeFunctions.h.
Referenced by OctreePost::_getValue(), GMSH_IntegratePlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_Scal2VecPlugin::execute(), GMSH_Scal2TensPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), and readMSH4Elements().
The documentation for this class was generated from the following file:
src/post/shapeFunctions.h