gmsh-TingyuanDoc: Pair< L, R > Class Template Reference
Pair< L, R > Class Template Reference
#include <Pair.h>
Public Member Functions
Pair ()
Pair (const L &left, const R &right)
L left () const
void left (const L &left)
R right () const
void right (const R &right)
L first () const
R second () const
Private Attributes
L Left
R Right
Detailed Description
template<class L, class R>
class Pair< L, R >
Definition at line 10 of file Pair.h.
Constructor & Destructor Documentation
Pair() [1/2]
template<class L , class R > Pair< L, R >::Pair () inline
Definition at line 16 of file Pair.h.
Pair() [2/2]
template<class L , class R > Pair< L, R >::Pair (const L & left, const R & right) inline
Definition at line 17 of file Pair.h.
Member Function Documentation
first()
template<class L , class R > L Pair< L, R >::first () const inline
Definition at line 22 of file Pair.h.
Referenced by buildMetric(), GFace::curvatureDiv(), GFace::curvatures(), GFace::getMetricEigenVectors(), improved_translate(), GFace::normal(), backgroundMesh::propagateCrossField(), and backgroundMesh::propagateCrossFieldByDistance().
left() [1/2]
template<class L , class R > L Pair< L, R >::left () const inline
Definition at line 18 of file Pair.h.
Referenced by GFace::XYZtoUV().
left() [2/2]
template<class L , class R > void Pair< L, R >::left (const L & left) inline
Definition at line 19 of file Pair.h.
Referenced by Pair< L, R >::left().
right() [1/2]
template<class L , class R > R Pair< L, R >::right () const inline
Definition at line 20 of file Pair.h.
Referenced by GFace::XYZtoUV().
right() [2/2]
template<class L , class R > void Pair< L, R >::right (const R & right) inline
Definition at line 21 of file Pair.h.
Referenced by Pair< L, R >::right().
second()
template<class L , class R > R Pair< L, R >::second () const inline
Definition at line 23 of file Pair.h.
Referenced by buildMetric(), GFace::curvatureDiv(), GFace::curvatures(), GFace::getMetricEigenVectors(), improved_translate(), GFace::normal(), and backgroundMesh::propagateCrossField().
Member Data Documentation
Left
template<class L , class R > L Pair< L, R >::Left private
Definition at line 12 of file Pair.h.
Referenced by Pair< L, R >::first(), and Pair< L, R >::left().
Right
template<class L , class R > R Pair< L, R >::Right private
Definition at line 13 of file Pair.h.
Referenced by Pair< L, R >::right(), and Pair< L, R >::second().
The documentation for this class was generated from the following file:
src/geo/Pair.h