gmsh-TingyuanDoc: MElementFactory Class Reference
MElementFactory Class Reference
#include <MElement.h>
Public Member Functions
MElement * create (int type, std::vector< MVertex * > &v, std::size_t num=0, int part=0, bool owner=false, int parent=0, MElement *parent_ptr=nullptr, MElement *d1=nullptr, MElement *d2=nullptr)
MElement * create (int num, int type, const std::vector< int > &data, GModel *model)
Detailed Description
Definition at line 517 of file MElement.h.
Member Function Documentation
create() [1/2]
MElement * MElementFactory::create (int num, int type, const std::vector< int > & data, GModel * model)
Definition at line 2690 of file MElement.cpp.
create() [2/2]
MElement * MElementFactory::create (int type, std::vector< MVertex * > & v, std::size_t num = 0, int part = 0, bool owner = false, int parent = 0, MElement * parent_ptr = nullptr, MElement * d1 = nullptr, MElement * d2 = nullptr)
Definition at line 2556 of file MElement.cpp.
Referenced by copy_elements(), create(), createElementMSH2(), createElements(), createTopologyFromMesh2D(), createTopologyFromMesh3D(), GModel::makeDiscreteFacesSimplyConnected(), and GModel::makeDiscreteRegionsSimplyConnected().
The documentation for this class was generated from the following files:
src/geo/MElement.h
src/geo/MElement.cpp