gmsh-TingyuanDoc: GEdgeSigned Class Reference
GEdgeSigned Class Reference
#include <GEdgeLoop.h>
Public Member Functions
GEdgeSigned (int sign, GEdge *ge)
GVertex * getBeginVertex () const
GVertex * getEndVertex () const
void print () const
int getSign () const
GEdge * getEdge () const
void changeSign ()
Private Attributes
int _sign
GEdge * _ge
Detailed Description
Definition at line 12 of file GEdgeLoop.h.
Constructor & Destructor Documentation
GEdgeSigned()
GEdgeSigned::GEdgeSigned (int sign, GEdge * ge) inline
Definition at line 17 of file GEdgeLoop.h.
Member Function Documentation
changeSign()
void GEdgeSigned::changeSign () inline
Definition at line 33 of file GEdgeLoop.h.
getBeginVertex()
GVertex* GEdgeSigned::getBeginVertex () const inline
Definition at line 22 of file GEdgeLoop.h.
Referenced by loopTheLoop(), and print().
getEdge()
GEdge* GEdgeSigned::getEdge () const inline
Definition at line 32 of file GEdgeLoop.h.
Referenced by loopTheLoop(), and nextOne().
getEndVertex()
GVertex* GEdgeSigned::getEndVertex () const inline
Definition at line 26 of file GEdgeLoop.h.
Referenced by loopTheLoop(), nextOne(), and print().
getSign()
int GEdgeSigned::getSign () const inline
Definition at line 31 of file GEdgeLoop.h.
print()
void GEdgeSigned::print () const
Definition at line 11 of file GEdgeLoop.cpp.
Referenced by nextOne().
Member Data Documentation
_ge
GEdge* GEdgeSigned::_ge private
Definition at line 15 of file GEdgeLoop.h.
Referenced by getBeginVertex(), getEdge(), getEndVertex(), and print().
_sign
int GEdgeSigned::_sign private
Definition at line 14 of file GEdgeLoop.h.
Referenced by changeSign(), GEdgeSigned(), getBeginVertex(), getEndVertex(), getSign(), and print().
The documentation for this class was generated from the following files:
src/geo/GEdgeLoop.h
src/geo/GEdgeLoop.cpp