gmsh-TingyuanDoc: tetgenmesh Class Reference
tetgenmesh Class Reference
#include <tetgenBR.h>
Classes
class arraypool
class badface
class face
class flipconstraints
class insertvertexflags
class memorypool
class optparameters
class triface
Public Types
enum verttype {
UNUSEDVERTEX, DUPLICATEDVERTEX, RIDGEVERTEX, ACUTEVERTEX,
FACETVERTEX, VOLVERTEX, FREESEGVERTEX, FREEFACETVERTEX,
FREEVOLVERTEX, NREGULARVERTEX, DEADVERTEX
}
enum interresult {
DISJOINT, INTERSECT, SHAREVERT, SHAREEDGE,
SHAREFACE, TOUCHEDGE, TOUCHFACE, ACROSSVERT,
ACROSSEDGE, ACROSSFACE
}
enum locateresult {
UNKNOWN, OUTSIDE, INTETRAHEDRON, ONFACE,
ONEDGE, ONVERTEX, ENCVERTEX, ENCSEGMENT,
ENCSUBFACE, NEARVERTEX, NONREGULAR, INSTAR,
BADELEMENT
}
typedef REAL ** tetrahedron
typedef REAL ** shellface
typedef REAL * point
Public Member Functions
void inittables ()
tetrahedron encode (triface &t)
tetrahedron encode2 (tetrahedron *ptr, int ver)
void decode (tetrahedron ptr, triface &t)
void bond (triface &t1, triface &t2)
void dissolve (triface &t)
void esym (triface &t1, triface &t2)
void esymself (triface &t)
void enext (triface &t1, triface &t2)
void enextself (triface &t)
void eprev (triface &t1, triface &t2)
void eprevself (triface &t)
void enextesym (triface &t1, triface &t2)
void enextesymself (triface &t)
void eprevesym (triface &t1, triface &t2)
void eprevesymself (triface &t)
void eorgoppo (triface &t1, triface &t2)
void eorgoppoself (triface &t)
void edestoppo (triface &t1, triface &t2)
void edestoppoself (triface &t)
void fsym (triface &t1, triface &t2)
void fsymself (triface &t)
void fnext (triface &t1, triface &t2)
void fnextself (triface &t)
point org (triface &t)
point dest (triface &t)
point apex (triface &t)
point oppo (triface &t)
void setorg (triface &t, point p)
void setdest (triface &t, point p)
void setapex (triface &t, point p)
void setoppo (triface &t, point p)
REAL elemattribute (tetrahedron *ptr, int attnum)
void setelemattribute (tetrahedron *ptr, int attnum, REAL value)
REAL volumebound (tetrahedron *ptr)
void setvolumebound (tetrahedron *ptr, REAL value)
int elemindex (tetrahedron *ptr)
void setelemindex (tetrahedron *ptr, int value)
int elemmarker (tetrahedron *ptr)
void setelemmarker (tetrahedron *ptr, int value)
void infect (triface &t)
void uninfect (triface &t)
bool infected (triface &t)
void marktest (triface &t)
void unmarktest (triface &t)
bool marktested (triface &t)
void markface (triface &t)
void unmarkface (triface &t)
bool facemarked (triface &t)
void markedge (triface &t)
void unmarkedge (triface &t)
bool edgemarked (triface &t)
void marktest2 (triface &t)
void unmarktest2 (triface &t)
bool marktest2ed (triface &t)
int elemcounter (triface &t)
void setelemcounter (triface &t, int value)
void increaseelemcounter (triface &t)
void decreaseelemcounter (triface &t)
bool ishulltet (triface &t)
bool isdeadtet (triface &t)
void sdecode (shellface sptr, face &s)
shellface sencode (face &s)
shellface sencode2 (shellface *sh, int shver)
void spivot (face &s1, face &s2)
void spivotself (face &s)
void sbond (face &s1, face &s2)
void sbond1 (face &s1, face &s2)
void sdissolve (face &s)
point sorg (face &s)
point sdest (face &s)
point sapex (face &s)
void setsorg (face &s, point pointptr)
void setsdest (face &s, point pointptr)
void setsapex (face &s, point pointptr)
void sesym (face &s1, face &s2)
void sesymself (face &s)
void senext (face &s1, face &s2)
void senextself (face &s)
void senext2 (face &s1, face &s2)
void senext2self (face &s)
REAL areabound (face &s)
void setareabound (face &s, REAL value)
int shellmark (face &s)
void setshellmark (face &s, int value)
void sinfect (face &s)
void suninfect (face &s)
bool sinfected (face &s)
void smarktest (face &s)
void sunmarktest (face &s)
bool smarktested (face &s)
void smarktest2 (face &s)
void sunmarktest2 (face &s)
bool smarktest2ed (face &s)
void smarktest3 (face &s)
void sunmarktest3 (face &s)
bool smarktest3ed (face &s)
void setfacetindex (face &f, int value)
int getfacetindex (face &f)
void tsbond (triface &t, face &s)
void tsdissolve (triface &t)
void stdissolve (face &s)
void tspivot (triface &t, face &s)
void stpivot (face &s, triface &t)
void tssbond1 (triface &t, face &seg)
void sstbond1 (face &s, triface &t)
void tssdissolve1 (triface &t)
void sstdissolve1 (face &s)
void tsspivot1 (triface &t, face &s)
void sstpivot1 (face &s, triface &t)
void ssbond (face &s, face &edge)
void ssbond1 (face &s, face &edge)
void ssdissolve (face &s)
void sspivot (face &s, face &edge)
int pointmark (point pt)
void setpointmark (point pt, int value)
enum verttype pointtype (point pt)
void setpointtype (point pt, enum verttype value)
int pointgeomtag (point pt)
void setpointgeomtag (point pt, int value)
REAL pointgeomuv (point pt, int i)
void setpointgeomuv (point pt, int i, REAL value)
void pinfect (point pt)
void puninfect (point pt)
bool pinfected (point pt)
void pmarktest (point pt)
void punmarktest (point pt)
bool pmarktested (point pt)
void pmarktest2 (point pt)
void punmarktest2 (point pt)
bool pmarktest2ed (point pt)
void pmarktest3 (point pt)
void punmarktest3 (point pt)
bool pmarktest3ed (point pt)
tetrahedron point2tet (point pt)
void setpoint2tet (point pt, tetrahedron value)
shellface point2sh (point pt)
void setpoint2sh (point pt, shellface value)
point point2ppt (point pt)
void setpoint2ppt (point pt, point value)
tetrahedron point2bgmtet (point pt)
void setpoint2bgmtet (point pt, tetrahedron value)
void setpointinsradius (point pt, REAL value)
REAL getpointinsradius (point pt)
bool issteinerpoint (point pt)
void point2tetorg (point pt, triface &t)
void point2shorg (point pa, face &s)
point farsorg (face &seg)
point farsdest (face &seg)
void tetrahedrondealloc (tetrahedron *)
tetrahedron * tetrahedrontraverse ()
tetrahedron * alltetrahedrontraverse ()
void shellfacedealloc (memorypool *, shellface *)
shellface * shellfacetraverse (memorypool *)
void pointdealloc (point)
point pointtraverse ()
void makeindex2pointmap (point *&)
void makepoint2submap (memorypool *, int *&, face *&)
void maketetrahedron (triface *)
void makeshellface (memorypool *, face *)
void makepoint (point *, enum verttype)
void initializepools ()
REAL insphere_s (REAL *, REAL *, REAL *, REAL *, REAL *)
REAL orient4d_s (REAL *, REAL *, REAL *, REAL *, REAL *, REAL, REAL, REAL, REAL, REAL)
int tri_edge_2d (point, point, point, point, point, point, int, int *, int *)
int tri_edge_tail (point, point, point, point, point, point, REAL, REAL, int, int *, int *)
int tri_edge_test (point, point, point, point, point, point, int, int *, int *)
int tri_edge_inter_tail (point, point, point, point, point, REAL, REAL)
int tri_tri_inter (point, point, point, point, point, point)
REAL dot (REAL *v1, REAL *v2)
void cross (REAL *v1, REAL *v2, REAL *n)
bool lu_decmp (REAL lu[4][4], int n, int *ps, REAL *d, int N)
void lu_solve (REAL lu[4][4], int n, int *ps, REAL *b, int N)
REAL incircle3d (point pa, point pb, point pc, point pd)
REAL orient3dfast (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL norm2 (REAL x, REAL y, REAL z)
REAL distance (REAL *p1, REAL *p2)
void facenormal (point pa, point pb, point pc, REAL *n, int pivot, REAL *lav)
REAL shortdistance (REAL *p, REAL *e1, REAL *e2)
REAL triarea (REAL *pa, REAL *pb, REAL *pc)
REAL interiorangle (REAL *o, REAL *p1, REAL *p2, REAL *n)
void projpt2edge (REAL *p, REAL *e1, REAL *e2, REAL *prj)
void projpt2face (REAL *p, REAL *f1, REAL *f2, REAL *f3, REAL *prj)
bool tetalldihedral (point, point, point, point, REAL *, REAL *, REAL *)
void tetallnormal (point, point, point, point, REAL N[4][3], REAL *volume)
REAL tetaspectratio (point, point, point, point)
bool circumsphere (REAL *, REAL *, REAL *, REAL *, REAL *cent, REAL *radius)
bool orthosphere (REAL *, REAL *, REAL *, REAL *, REAL, REAL, REAL, REAL, REAL *, REAL *)
void planelineint (REAL *, REAL *, REAL *, REAL *, REAL *, REAL *, REAL *)
int linelineint (REAL *, REAL *, REAL *, REAL *, REAL *, REAL *, REAL *, REAL *)
REAL tetprismvol (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
bool calculateabovepoint (arraypool *, point *, point *, point *)
void calculateabovepoint4 (point, point, point, point)
void report_overlapping_facets (face *, face *, REAL dihedang=0.0)
int report_selfint_edge (point, point, face *sedge, triface *searchtet, enum interresult)
int report_selfint_face (point, point, point, face *sface, triface *iedge, int intflag, int *types, int *poss)
void flip23 (triface *, int, flipconstraints *fc)
void flip32 (triface *, int, flipconstraints *fc)
void flip41 (triface *, int, flipconstraints *fc)
int flipnm (triface *, int n, int level, int, flipconstraints *fc)
int flipnm_post (triface *, int n, int nn, int, flipconstraints *fc)
int insertpoint (point, triface *, face *, face *, insertvertexflags *)
void insertpoint_abort (face *, insertvertexflags *)
void transfernodes ()
void hilbert_init (int n)
int hilbert_split (point *vertexarray, int arraysize, int gc0, int gc1, REAL, REAL, REAL, REAL, REAL, REAL)
void hilbert_sort3 (point *vertexarray, int arraysize, int e, int d, REAL, REAL, REAL, REAL, REAL, REAL, int depth)
void brio_multiscale_sort (point *, int, int threshold, REAL ratio, int *depth)
unsigned long randomnation (unsigned int choices)
void randomsample (point searchpt, triface *searchtet)
enum locateresult locate (point searchpt, triface *searchtet, int chkencflag=0)
void flippush (badface *&, triface *)
int incrementalflip (point newpt, int, flipconstraints *fc)
void initialdelaunay (point pa, point pb, point pc, point pd)
void incrementaldelaunay (clock_t &)
void flipshpush (face *)
void flip22 (face *, int, int)
void flip31 (face *, int)
long lawsonflip ()
int sinsertvertex (point newpt, face *, face *, int iloc, int bowywat, int)
int sremovevertex (point delpt, face *, face *, int lawson)
enum locateresult slocate (point, face *, int, int, int)
enum interresult sscoutsegment (face *, point, int, int, int)
void scarveholes (int, REAL *)
void unifysegments ()
void identifyinputedges (point *)
void mergefacets ()
enum interresult finddirection (triface *searchtet, point endpt)
int checkflipeligibility (int fliptype, point, point, point, point, point, int level, int edgepivot, flipconstraints *fc)
int removeedgebyflips (triface *, flipconstraints *)
int removefacebyflips (triface *, flipconstraints *)
int recoveredgebyflips (point, point, face *, triface *, int fullsearch)
int add_steinerpt_in_schoenhardtpoly (triface *, int, int chkencflag)
int add_steinerpt_in_segment (face *, int searchlevel)
int addsteiner4recoversegment (face *, int)
int recoversegments (arraypool *, int fullsearch, int steinerflag)
int recoverfacebyflips (point, point, point, face *, triface *)
int recoversubfaces (arraypool *, int steinerflag)
int getvertexstar (int, point searchpt, arraypool *, arraypool *, arraypool *)
int getedge (point, point, triface *)
int reduceedgesatvertex (point startpt, arraypool *endptlist)
int removevertexbyflips (point steinerpt)
int suppressbdrysteinerpoint (point steinerpt)
int suppresssteinerpoints ()
void recoverboundary (clock_t &)
void carveholes ()
bool reconstructmesh (void *)
void outsurfacemesh (const char *mfilename)
void outmesh2medit (const char *mfilename)
void enqueuesubface (memorypool *, face *)
void enqueuetetrahedron (triface *)
long lawsonflip3d (flipconstraints *fc)
void recoverdelaunay ()
int gettetrahedron (point, point, point, point, triface *)
long improvequalitybyflips ()
int smoothpoint (point smtpt, arraypool *, int ccw, optparameters *opm)
long improvequalitybysmoothing (optparameters *opm)
int splitsliver (triface *, REAL, int)
long removeslivers (int)
void optimizemesh ()
void jettisonnodes ()
void initializetetgenmesh ()
void freememory ()
tetgenmesh ()
~tetgenmesh ()
Public Attributes
tetgenio * in
tetgenio * addin
tetgenbehavior * b
tetgenmesh * bgm
memorypool * tetrahedrons
memorypool * subfaces
memorypool * subsegs
memorypool * points
memorypool * tet2subpool
memorypool * tet2segpool
memorypool * badtetrahedrons
memorypool * badsubfacs
memorypool * badsubsegs
memorypool * flippool
arraypool * unflipqueue
badface * flipstack
arraypool * cavetetlist
arraypool * cavebdrylist
arraypool * caveoldtetlist
arraypool * cavetetshlist
arraypool * cavetetseglist
arraypool * cavetetvertlist
arraypool * caveencshlist
arraypool * caveencseglist
arraypool * caveshlist
arraypool * caveshbdlist
arraypool * cavesegshlist
arraypool * subsegstack
arraypool * subfacstack
arraypool * subvertstack
arraypool * encseglist
arraypool * encshlist
int * idx2facetlist
point * facetverticeslist
point * segmentendpointslist
point dummypoint
triface recenttet
face recentsh
point * highordertable
int numpointattrib
int numelemattrib
int sizeoftensor
int pointmtrindex
int pointparamindex
int point2simindex
int pointmarkindex
int pointinsradiusindex
int elemattribindex
int volumeboundindex
int elemmarkerindex
int shmarkindex
int areaboundindex
int checksubsegflag
int checksubfaceflag
int checkconstraints
int nonconvex
int autofliplinklevel
int useinsertradius
long samples
unsigned long randomseed
REAL cosmaxdihed
REAL cosmindihed
REAL cossmtdihed
REAL cosslidihed
REAL minfaceang
REAL minfacetdihed
REAL tetprism_vol_sum
REAL longest
REAL minedgelength
REAL xmax
REAL xmin
REAL ymax
REAL ymin
REAL zmax
REAL zmin
long insegments
long hullsize
long meshedges
long meshhulledges
long steinerleft
long dupverts
long unuverts
long nonregularcount
long st_segref_count
long st_facref_count
long st_volref_count
long fillregioncount
long cavitycount
long cavityexpcount
long flip14count
long flip26count
long flipn2ncount
long flip23count
long flip32count
long flip44count
long flip41count
long flip31count
long flip22count
unsigned long totalworkmemory
int transgc [8][3][8]
int tsb1mod3 [8]
Static Public Attributes
static REAL PI = 3.14159265358979323846264338327950288419716939937510582
static int bondtbl [12][12] = {{0,},}
static int fsymtbl [12][12] = {{0,},}
static int esymtbl [12] = {9, 6, 11, 4, 3, 7, 1, 5, 10, 0, 8, 2}
static int enexttbl [12] = {0,}
static int eprevtbl [12] = {0,}
static int enextesymtbl [12] = {0,}
static int eprevesymtbl [12] = {0,}
static int eorgoppotbl [12] = {0,}
static int edestoppotbl [12] = {0,}
static int facepivot1 [12] = {0,}
static int facepivot2 [12][12] = {{0,},}
static int orgpivot [12] = {7, 7, 5, 5, 6, 4, 4, 6, 5, 6, 7, 4}
static int destpivot [12] = {6, 4, 4, 6, 5, 6, 7, 4, 7, 7, 5, 5}
static int apexpivot [12] = {5, 6, 7, 4, 7, 7, 5, 5, 6, 4, 4, 6}
static int oppopivot [12] = {4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7}
static int tsbondtbl [12][6] = {{0,},}
static int stbondtbl [12][6] = {{0,},}
static int tspivottbl [12][6] = {{0,},}
static int stpivottbl [12][6] = {{0,},}
static int ver2edge [12] = {0, 1, 2, 3, 3, 5, 1, 5, 4, 0, 4, 2}
static int edge2ver [6] = {0, 1, 2, 3, 8, 5}
static int epivot [12] = {4, 5, 2, 11, 4, 5, 2, 11, 4, 5, 2, 11}
static int sorgpivot [6] = {3, 4, 4, 5, 5, 3}
static int sdestpivot [6] = {4, 3, 5, 4, 3, 5}
static int sapexpivot [6] = {5, 5, 3, 3, 4, 4}
static int snextpivot [6] = {2, 5, 4, 1, 0, 3}
Detailed Description
Definition at line 254 of file tetgenBR.h.
Member Typedef Documentation
point
typedef REAL* tetgenmesh::point
Definition at line 330 of file tetgenBR.h.
shellface
typedef REAL** tetgenmesh::shellface
Definition at line 313 of file tetgenBR.h.
tetrahedron
typedef REAL** tetgenmesh::tetrahedron
Definition at line 302 of file tetgenBR.h.
Member Enumeration Documentation
interresult
enum tetgenmesh::interresult
Enumerator
DISJOINT
INTERSECT
SHAREVERT
SHAREEDGE
SHAREFACE
TOUCHEDGE
TOUCHFACE
ACROSSVERT
ACROSSEDGE
ACROSSFACE
Definition at line 697 of file tetgenBR.h.
locateresult
enum tetgenmesh::locateresult
Enumerator
UNKNOWN
OUTSIDE
INTETRAHEDRON
ONFACE
ONEDGE
ONVERTEX
ENCVERTEX
ENCSEGMENT
ENCSUBFACE
NEARVERTEX
NONREGULAR
INSTAR
BADELEMENT
Definition at line 711 of file tetgenBR.h.
verttype
enum tetgenmesh::verttype
Enumerator
UNUSEDVERTEX
DUPLICATEDVERTEX
RIDGEVERTEX
ACUTEVERTEX
FACETVERTEX
VOLVERTEX
FREESEGVERTEX
FREEFACETVERTEX
FREEVOLVERTEX
NREGULARVERTEX
DEADVERTEX
Definition at line 682 of file tetgenBR.h.
Constructor & Destructor Documentation
tetgenmesh()
tetgenmesh::tetgenmesh () inline
Definition at line 1493 of file tetgenBR.h.
~tetgenmesh()
tetgenmesh::~tetgenmesh () inline
Definition at line 1495 of file tetgenBR.h.
Member Function Documentation
add_steinerpt_in_schoenhardtpoly()
int tetgenmesh::add_steinerpt_in_schoenhardtpoly (triface * abtets, int n, int chkencflag)
Definition at line 12343 of file tetgenBR.cxx.
Referenced by addsteiner4recoversegment().
add_steinerpt_in_segment()
int tetgenmesh::add_steinerpt_in_segment (face * misseg, int searchlevel)
Definition at line 12498 of file tetgenBR.cxx.
Referenced by addsteiner4recoversegment().
addsteiner4recoversegment()
int tetgenmesh::addsteiner4recoversegment (face * misseg, int splitsegflag)
Definition at line 12669 of file tetgenBR.cxx.
Referenced by recoversegments().
alltetrahedrontraverse()
tetgenmesh::tetrahedron * tetgenmesh::alltetrahedrontraverse ()
Definition at line 1384 of file tetgenBR.cxx.
Referenced by carveholes().
apex()
tetgenmesh::point tetgenmesh::apex (triface & t) inline
Definition at line 1740 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), addsteiner4recoversegment(), carveholes(), flip23(), flip32(), flip41(), flipnm(), getedge(), gettetrahedron(), getvertexstar(), incrementalflip(), insertpoint(), lawsonflip3d(), recoveredgebyflips(), recoverfacebyflips(), removefacebyflips(), removevertexbyflips(), smoothpoint(), and suppressbdrysteinerpoint().
areabound()
REAL tetgenmesh::areabound (face & s) inline
Definition at line 2108 of file tetgenBR.h.
Referenced by flip31(), sinsertvertex(), and sscoutsegment().
bond()
void tetgenmesh::bond (triface & t1, triface & t2) inline
Definition at line 1606 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), initialdelaunay(), insertpoint(), and suppressbdrysteinerpoint().
brio_multiscale_sort()
void tetgenmesh::brio_multiscale_sort (point * vertexarray, int arraysize, int threshold, REAL ratio, int * depth)
Definition at line 8315 of file tetgenBR.cxx.
Referenced by incrementaldelaunay().
calculateabovepoint()
bool tetgenmesh::calculateabovepoint (arraypool * facpoints, point * ppa, point * ppb, point * ppc)
Definition at line 3916 of file tetgenBR.cxx.
calculateabovepoint4()
void tetgenmesh::calculateabovepoint4 (point pa, point pb, point pc, point pd)
Definition at line 4006 of file tetgenBR.cxx.
Referenced by sscoutsegment().
carveholes()
void tetgenmesh::carveholes ()
Definition at line 15267 of file tetgenBR.cxx.
checkflipeligibility()
int tetgenmesh::checkflipeligibility (int fliptype, point pa, point pb, point pc, point pd, point pe, int level, int edgepivot, flipconstraints * fc)
Definition at line 11663 of file tetgenBR.cxx.
Referenced by flipnm().
circumsphere()
bool tetgenmesh::circumsphere (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * cent, REAL * radius)
Definition at line 3665 of file tetgenBR.cxx.
Referenced by incircle3d().
cross()
void tetgenmesh::cross (REAL * v1, REAL * v2, REAL * n) inline
Definition at line 2646 of file tetgenBR.h.
Referenced by calculateabovepoint(), circumsphere(), facenormal(), incrementaldelaunay(), and triarea().
decode()
void tetgenmesh::decode (tetrahedron ptr, triface & t) inline
Definition at line 1597 of file tetgenBR.h.
Referenced by carveholes(), fnext(), fsym(), insertpoint(), point2tetorg(), recoverdelaunay(), sstpivot1(), and stpivot().
decreaseelemcounter()
void tetgenmesh::decreaseelemcounter (triface & t) inline
Definition at line 1948 of file tetgenBR.h.
Referenced by flipnm().
dest()
tetgenmesh::point tetgenmesh::dest (triface & t) inline
Definition at line 1735 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), addsteiner4recoversegment(), carveholes(), flip23(), flip32(), flip41(), flipnm(), getedge(), incrementalflip(), insertpoint(), lawsonflip3d(), recoveredgebyflips(), recoversubfaces(), reduceedgesatvertex(), removefacebyflips(), report_selfint_edge(), report_selfint_face(), smoothpoint(), splitsliver(), and suppressbdrysteinerpoint().
dissolve()
void tetgenmesh::dissolve (triface & t) inline
Definition at line 1614 of file tetgenBR.h.
Referenced by suppressbdrysteinerpoint().
distance()
REAL tetgenmesh::distance (REAL * p1, REAL * p2) inline
Definition at line 2654 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), calculateabovepoint4(), incircle3d(), incrementaldelaunay(), insertpoint(), lawsonflip3d(), suppressbdrysteinerpoint(), and tri_edge_2d().
dot()
REAL tetgenmesh::dot (REAL * v1, REAL * v2) inline
Definition at line 2640 of file tetgenBR.h.
Referenced by calculateabovepoint(), calculateabovepoint4(), circumsphere(), facenormal(), incircle3d(), interiorangle(), linelineint(), lu_solve(), mergefacets(), projpt2edge(), projpt2face(), shortdistance(), suppressbdrysteinerpoint(), tetalldihedral(), tetaspectratio(), tetprismvol(), tri_edge_2d(), triarea(), and unifysegments().
edestoppo()
void tetgenmesh::edestoppo (triface & t1, triface & t2) inline
Definition at line 1688 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), flip23(), flip32(), insertpoint(), lawsonflip3d(), recoverfacebyflips(), and splitsliver().
edestoppoself()
void tetgenmesh::edestoppoself (triface & t) inline
Definition at line 1694 of file tetgenBR.h.
Referenced by flipnm().
edgemarked()
bool tetgenmesh::edgemarked (triface & t) inline
Definition at line 1900 of file tetgenBR.h.
elemattribute()
REAL tetgenmesh::elemattribute (tetrahedron * ptr, int attnum) inline
Definition at line 1778 of file tetgenBR.h.
Referenced by flip23(), flip32(), insertpoint(), and optimizemesh().
elemcounter()
int tetgenmesh::elemcounter (triface & t) inline
Definition at line 1928 of file tetgenBR.h.
Referenced by decreaseelemcounter(), flipnm(), and increaseelemcounter().
elemindex()
int tetgenmesh::elemindex (tetrahedron * ptr) inline
Definition at line 1804 of file tetgenBR.h.
elemmarker()
int tetgenmesh::elemmarker (tetrahedron * ptr) inline
Definition at line 1819 of file tetgenBR.h.
encode()
tetgenmesh::tetrahedron tetgenmesh::encode (triface & t) inline
Definition at line 1584 of file tetgenBR.h.
Referenced by initialdelaunay(), sstbond1(), and suppressbdrysteinerpoint().
encode2()
tetgenmesh::tetrahedron tetgenmesh::encode2 (tetrahedron * ptr, int ver) inline
Definition at line 1589 of file tetgenBR.h.
Referenced by bond(), and tsbond().
enext()
void tetgenmesh::enext (triface & t1, triface & t2) inline
Definition at line 1618 of file tetgenBR.h.
Referenced by flip23(), flip32(), flip41(), flipnm(), incrementalflip(), removefacebyflips(), and splitsliver().
enextesym()
void tetgenmesh::enextesym (triface & t1, triface & t2) inline
Definition at line 1650 of file tetgenBR.h.
Referenced by flip23(), flip32(), initialdelaunay(), and recoveredgebyflips().
enextesymself()
void tetgenmesh::enextesymself (triface & t) inline
Definition at line 1656 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), getedge(), getvertexstar(), and recoveredgebyflips().
enextself()
void tetgenmesh::enextself (triface & t) inline
Definition at line 1624 of file tetgenBR.h.
Referenced by addsteiner4recoversegment(), carveholes(), flip23(), flip32(), flip41(), flipnm(), flipnm_post(), getedge(), getvertexstar(), incrementalflip(), insertpoint(), lawsonflip3d(), recoveredgebyflips(), removevertexbyflips(), and suppressbdrysteinerpoint().
enqueuesubface()
void tetgenmesh::enqueuesubface (memorypool * pool, face * chkface)
Definition at line 15897 of file tetgenBR.cxx.
Referenced by flip22(), flip23(), flip32(), flip41(), and insertpoint().
enqueuetetrahedron()
void tetgenmesh::enqueuetetrahedron (triface * chktet)
Definition at line 15912 of file tetgenBR.cxx.
Referenced by flip23(), flip32(), flip41(), and insertpoint().
eorgoppo()
void tetgenmesh::eorgoppo (triface & t1, triface & t2) inline
Definition at line 1677 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), flip23(), flip32(), flipnm(), getedge(), insertpoint(), and lawsonflip3d().
eorgoppoself()
void tetgenmesh::eorgoppoself (triface & t) inline
Definition at line 1683 of file tetgenBR.h.
Referenced by flipnm().
eprev()
void tetgenmesh::eprev (triface & t1, triface & t2) inline
Definition at line 1628 of file tetgenBR.h.
Referenced by flip23(), flip32(), flip41(), flipnm(), incrementalflip(), removefacebyflips(), removevertexbyflips(), and splitsliver().
eprevesym()
void tetgenmesh::eprevesym (triface & t1, triface & t2) inline
Definition at line 1663 of file tetgenBR.h.
Referenced by flip23(), flip32(), initialdelaunay(), and recoveredgebyflips().
eprevesymself()
void tetgenmesh::eprevesymself (triface & t) inline
Definition at line 1669 of file tetgenBR.h.
Referenced by flip23().
eprevself()
void tetgenmesh::eprevself (triface & t) inline
Definition at line 1634 of file tetgenBR.h.
Referenced by addsteiner4recoversegment(), carveholes(), flip23(), flip32(), flip41(), flipnm(), flipnm_post(), lawsonflip3d(), recoverfacebyflips(), and removevertexbyflips().
esym()
void tetgenmesh::esym (triface & t1, triface & t2) inline
Definition at line 1639 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), flipnm(), flipnm_post(), getvertexstar(), incrementalflip(), initialdelaunay(), insertpoint(), lawsonflip3d(), removevertexbyflips(), and suppressbdrysteinerpoint().
esymself()
void tetgenmesh::esymself (triface & t) inline
Definition at line 1645 of file tetgenBR.h.
Referenced by addsteiner4recoversegment(), carveholes(), flip23(), flip32(), flip41(), flipnm(), flipnm_post(), getedge(), getvertexstar(), incrementalflip(), insertpoint(), lawsonflip3d(), removevertexbyflips(), splitsliver(), and suppressbdrysteinerpoint().
facemarked()
bool tetgenmesh::facemarked (triface & t) inline
Definition at line 1880 of file tetgenBR.h.
Referenced by flippush(), incrementalflip(), lawsonflip3d(), and recoverdelaunay().
facenormal()
void tetgenmesh::facenormal (point pa, point pb, point pc, REAL * n, int pivot, REAL * lav)
Definition at line 3189 of file tetgenBR.cxx.
Referenced by calculateabovepoint(), calculateabovepoint4(), incircle3d(), mergefacets(), planelineint(), projpt2face(), suppressbdrysteinerpoint(), tetalldihedral(), tri_edge_2d(), and unifysegments().
farsdest()
tetgenmesh::point tetgenmesh::farsdest (face & seg) inline
Definition at line 2618 of file tetgenBR.h.
Referenced by report_selfint_edge(), and report_selfint_face().
farsorg()
tetgenmesh::point tetgenmesh::farsorg (face & seg) inline
Definition at line 2603 of file tetgenBR.h.
Referenced by report_selfint_edge(), and report_selfint_face().
finddirection()
enum tetgenmesh::interresult tetgenmesh::finddirection (triface * searchtet, point endpt)
Definition at line 11292 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), getedge(), insertpoint(), recoveredgebyflips(), recoverfacebyflips(), recoversubfaces(), reduceedgesatvertex(), and removevertexbyflips().
flip22()
void tetgenmesh::flip22 (face * flipfaces, int flipflag, int chkencflag)
Definition at line 9281 of file tetgenBR.cxx.
Referenced by flip32(), lawsonflip(), and sscoutsegment().
flip23()
void tetgenmesh::flip23 (triface * fliptets, int hullflag, flipconstraints * fc)
Definition at line 4744 of file tetgenBR.cxx.
Referenced by flipnm(), flipnm_post(), incrementalflip(), lawsonflip3d(), removefacebyflips(), and removevertexbyflips().
flip31()
void tetgenmesh::flip31 (face * flipfaces, int flipflag)
Definition at line 9403 of file tetgenBR.cxx.
Referenced by flip41(), and sscoutsegment().
flip32()
void tetgenmesh::flip32 (triface * fliptets, int hullflag, flipconstraints * fc)
Definition at line 5083 of file tetgenBR.cxx.
Referenced by flipnm(), flipnm_post(), incrementalflip(), lawsonflip3d(), and removevertexbyflips().
flip41()
void tetgenmesh::flip41 (triface * fliptets, int hullflag, flipconstraints * fc)
Definition at line 5485 of file tetgenBR.cxx.
Referenced by removevertexbyflips().
flipnm()
int tetgenmesh::flipnm (triface * abtets, int n, int level, int abedgepivot, flipconstraints * fc)
Definition at line 5804 of file tetgenBR.cxx.
Referenced by removeedgebyflips().
flipnm_post()
int tetgenmesh::flipnm_post (triface * abtets, int n, int nn, int abedgepivot, flipconstraints * fc)
Definition at line 6478 of file tetgenBR.cxx.
Referenced by flipnm(), and removeedgebyflips().
flippush()
void tetgenmesh::flippush (badface *& fstack, triface * flipface)
Definition at line 8680 of file tetgenBR.cxx.
Referenced by carveholes(), flip23(), flip32(), flip41(), insertpoint(), lawsonflip3d(), and recoverdelaunay().
flipshpush()
void tetgenmesh::flipshpush (face * flipedge)
Definition at line 9259 of file tetgenBR.cxx.
Referenced by flip22(), flip31(), and mergefacets().
fnext()
void tetgenmesh::fnext (triface & t1, triface & t2) inline
Definition at line 1716 of file tetgenBR.h.
Referenced by flip23(), flip41(), flipnm(), flipnm_post(), getedge(), incrementalflip(), lawsonflip3d(), and removevertexbyflips().
fnextself()
void tetgenmesh::fnextself (triface & t) inline
Referenced by addsteiner4recoversegment(), carveholes(), flip41(), flipnm(), gettetrahedron(), incrementalflip(), insertpoint(), recoveredgebyflips(), recoverfacebyflips(), recoversegments(), recoversubfaces(), removeedgebyflips(), removevertexbyflips(), splitsliver(), and suppressbdrysteinerpoint().
freememory()
void tetgenmesh::freememory () inline
Definition at line 1429 of file tetgenBR.h.
Referenced by ~tetgenmesh().
fsym()
void tetgenmesh::fsym (triface & t1, triface & t2) inline
Definition at line 1701 of file tetgenBR.h.
Referenced by addsteiner4recoversegment(), carveholes(), flip32(), flip41(), flipnm(), flipnm_post(), incrementalflip(), insertpoint(), lawsonflip3d(), removefacebyflips(), removevertexbyflips(), and suppressbdrysteinerpoint().
fsymself()
void tetgenmesh::fsymself (triface & t) inline
Referenced by carveholes(), flip32(), gettetrahedron(), getvertexstar(), insertpoint(), lawsonflip3d(), recoveredgebyflips(), recoverfacebyflips(), recoversubfaces(), and removevertexbyflips().
getedge()
int tetgenmesh::getedge (point e1, point e2, triface * tedge)
Definition at line 13540 of file tetgenBR.cxx.
Referenced by flipnm(), gettetrahedron(), recoverdelaunay(), reduceedgesatvertex(), and removevertexbyflips().
getfacetindex()
int tetgenmesh::getfacetindex (face & f) inline
Definition at line 2220 of file tetgenBR.h.
Referenced by flip31(), sinsertvertex(), and sscoutsegment().
getpointinsradius()
REAL tetgenmesh::getpointinsradius (point pt) inline
Definition at line 2558 of file tetgenBR.h.
gettetrahedron()
int tetgenmesh::gettetrahedron (point pa, point pb, point pc, point pd, triface * searchtet)
Definition at line 16388 of file tetgenBR.cxx.
Referenced by improvequalitybyflips(), improvequalitybysmoothing(), and removeslivers().
getvertexstar()
int tetgenmesh::getvertexstar (int fullstar, point searchpt, arraypool * tetlist, arraypool * vertlist, arraypool * shlist)
Definition at line 13398 of file tetgenBR.cxx.
Referenced by improvequalitybysmoothing(), removevertexbyflips(), suppressbdrysteinerpoint(), and suppresssteinerpoints().
hilbert_init()
void tetgenmesh::hilbert_init (int n)
Definition at line 8095 of file tetgenBR.cxx.
Referenced by incrementaldelaunay().
hilbert_sort3()
void tetgenmesh::hilbert_sort3 (point * vertexarray, int arraysize, int e, int d, REAL bxmin, REAL bxmax, REAL bymin, REAL bymax, REAL bzmin, REAL bzmax, int depth)
Definition at line 8215 of file tetgenBR.cxx.
Referenced by brio_multiscale_sort().
hilbert_split()
int tetgenmesh::hilbert_split (point * vertexarray, int arraysize, int gc0, int gc1, REAL bxmin, REAL bxmax, REAL bymin, REAL bymax, REAL bzmin, REAL bzmax)
Definition at line 8144 of file tetgenBR.cxx.
Referenced by hilbert_sort3().
identifyinputedges()
void tetgenmesh::identifyinputedges (point * idx2verlist)
Definition at line 11163 of file tetgenBR.cxx.
improvequalitybyflips()
long tetgenmesh::improvequalitybyflips ()
Definition at line 16425 of file tetgenBR.cxx.
Referenced by optimizemesh().
improvequalitybysmoothing()
long tetgenmesh::improvequalitybysmoothing (optparameters * opm)
Definition at line 16774 of file tetgenBR.cxx.
Referenced by optimizemesh().
incircle3d()
REAL tetgenmesh::incircle3d (point pa, point pb, point pc, point pd)
Definition at line 3138 of file tetgenBR.cxx.
Referenced by insertpoint(), lawsonflip(), and sinsertvertex().
increaseelemcounter()
void tetgenmesh::increaseelemcounter (triface & t) inline
Definition at line 1942 of file tetgenBR.h.
Referenced by flipnm().
incrementaldelaunay()
void tetgenmesh::incrementaldelaunay (clock_t & tv)
Definition at line 9033 of file tetgenBR.cxx.
incrementalflip()
int tetgenmesh::incrementalflip (point newpt, int hullflag, flipconstraints * fc)
Definition at line 8711 of file tetgenBR.cxx.
Referenced by incrementaldelaunay().
infect()
void tetgenmesh::infect (triface & t) inline
Definition at line 1833 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), carveholes(), getedge(), getvertexstar(), insertpoint(), and splitsliver().
infected()
bool tetgenmesh::infected (triface & t) inline
Definition at line 1843 of file tetgenBR.h.
Referenced by carveholes(), getedge(), getvertexstar(), and insertpoint().
initialdelaunay()
void tetgenmesh::initialdelaunay (point pa, point pb, point pc, point pd)
Definition at line 8949 of file tetgenBR.cxx.
Referenced by incrementaldelaunay().
initializepools()
void tetgenmesh::initializepools ()
Definition at line 1591 of file tetgenBR.cxx.
initializetetgenmesh()
void tetgenmesh::initializetetgenmesh () inline
Definition at line 1361 of file tetgenBR.h.
Referenced by freememory(), and tetgenmesh().
inittables()
void tetgenmesh::inittables ()
Definition at line 675 of file tetgenBR.cxx.
Referenced by initializepools().
insertpoint()
int tetgenmesh::insertpoint (point insertpt, triface * searchtet, face * splitsh, face * splitseg, insertvertexflags * ivf)
Definition at line 6641 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), addsteiner4recoversegment(), incrementaldelaunay(), recoversubfaces(), and splitsliver().
insertpoint_abort()
void tetgenmesh::insertpoint_abort (face * splitseg, insertvertexflags * ivf)
Definition at line 8037 of file tetgenBR.cxx.
Referenced by insertpoint().
insphere_s()
REAL tetgenmesh::insphere_s (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe)
Definition at line 1890 of file tetgenBR.cxx.
Referenced by incrementalflip(), insertpoint(), and lawsonflip3d().
interiorangle()
REAL tetgenmesh::interiorangle (REAL * o, REAL * p1, REAL * p2, REAL * n)
Definition at line 3334 of file tetgenBR.cxx.
isdeadtet()
bool tetgenmesh::isdeadtet (triface & t) inline
Definition at line 1963 of file tetgenBR.h.
Referenced by getedge(), improvequalitybyflips(), incrementalflip(), lawsonflip3d(), and recoverdelaunay().
ishulltet()
bool tetgenmesh::ishulltet (triface & t) inline
Definition at line 1956 of file tetgenBR.h.
Referenced by carveholes(), insertpoint(), lawsonflip3d(), splitsliver(), and suppressbdrysteinerpoint().
issteinerpoint()
bool tetgenmesh::issteinerpoint (point pt) inline
Definition at line 2563 of file tetgenBR.h.
Referenced by insertpoint(), and report_selfint_face().
jettisonnodes()
void tetgenmesh::jettisonnodes ()
Definition at line 17331 of file tetgenBR.cxx.
lawsonflip()
long tetgenmesh::lawsonflip ()
Definition at line 9496 of file tetgenBR.cxx.
Referenced by mergefacets(), and sscoutsegment().
lawsonflip3d()
long tetgenmesh::lawsonflip3d (flipconstraints * fc)
Definition at line 15931 of file tetgenBR.cxx.
Referenced by carveholes(), and recoverdelaunay().
linelineint()
int tetgenmesh::linelineint (REAL * A, REAL * B, REAL * C, REAL * D, REAL * P, REAL * Q, REAL * tp, REAL * tq)
Definition at line 3825 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_segment(), and report_selfint_edge().
locate()
enum tetgenmesh::locateresult tetgenmesh::locate (point searchpt, triface * searchtet, int chkencflag = 0)
Definition at line 8367 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_schoenhardtpoly(), carveholes(), insertpoint(), and splitsliver().
lu_decmp()
bool tetgenmesh::lu_decmp (REAL lu[4][4], int n, int * ps, REAL * d, int N)
Definition at line 3027 of file tetgenBR.cxx.
Referenced by circumsphere(), orthosphere(), tetallnormal(), and tetaspectratio().
lu_solve()
void tetgenmesh::lu_solve (REAL lu[4][4], int n, int * ps, REAL * b, int N)
Definition at line 3100 of file tetgenBR.cxx.
Referenced by circumsphere(), orthosphere(), tetallnormal(), and tetaspectratio().
makeindex2pointmap()
void tetgenmesh::makeindex2pointmap (point *& idx2verlist)
Definition at line 1230 of file tetgenBR.cxx.
makepoint()
void tetgenmesh::makepoint (point * pnewpoint, enum verttype vtype)
Definition at line 1549 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), addsteiner4recoversegment(), recoversubfaces(), splitsliver(), and suppressbdrysteinerpoint().
makepoint2submap()
void tetgenmesh::makepoint2submap (memorypool * pool, int *& idx2faclist, face *& facperverlist)
Definition at line 1264 of file tetgenBR.cxx.
Referenced by identifyinputedges(), and unifysegments().
makeshellface()
void tetgenmesh::makeshellface (memorypool * pool, face * newface)
Definition at line 1509 of file tetgenBR.cxx.
Referenced by flip31(), identifyinputedges(), recoversubfaces(), sinsertvertex(), and sscoutsegment().
maketetrahedron()
void tetgenmesh::maketetrahedron (triface * newtet)
Definition at line 1472 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_schoenhardtpoly(), carveholes(), flip23(), initialdelaunay(), insertpoint(), and suppressbdrysteinerpoint().
markedge()
void tetgenmesh::markedge (triface & t) inline
Definition at line 1890 of file tetgenBR.h.
markface()
void tetgenmesh::markface (triface & t) inline
Definition at line 1870 of file tetgenBR.h.
Referenced by flippush().
marktest()
void tetgenmesh::marktest (triface & t) inline
Definition at line 1851 of file tetgenBR.h.
Referenced by improvequalitybysmoothing(), incrementalflip(), and insertpoint().
marktest2()
void tetgenmesh::marktest2 (triface & t) inline
Definition at line 1909 of file tetgenBR.h.
Referenced by enqueuetetrahedron().
marktest2ed()
bool tetgenmesh::marktest2ed (triface & t) inline
Definition at line 1919 of file tetgenBR.h.
Referenced by enqueuetetrahedron().
marktested()
bool tetgenmesh::marktested (triface & t) inline
Definition at line 1861 of file tetgenBR.h.
Referenced by improvequalitybysmoothing(), incrementalflip(), and insertpoint().
mergefacets()
void tetgenmesh::mergefacets ()
Definition at line 11292 of file tetgenBR.cxx.
norm2()
REAL tetgenmesh::norm2 (REAL x, REAL y, REAL z) inline
Definition at line 2661 of file tetgenBR.h.
Referenced by incrementaldelaunay().
oppo()
tetgenmesh::point tetgenmesh::oppo (triface & t) inline
Definition at line 1745 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), addsteiner4recoversegment(), flip23(), flipnm(), gettetrahedron(), incrementalflip(), insertpoint(), lawsonflip3d(), recoveredgebyflips(), recoverfacebyflips(), removefacebyflips(), and removevertexbyflips().
optimizemesh()
void tetgenmesh::optimizemesh ()
Definition at line 17176 of file tetgenBR.cxx.
org()
tetgenmesh::point tetgenmesh::org (triface & t) inline
Definition at line 1730 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), addsteiner4recoversegment(), carveholes(), flip23(), flip32(), flip41(), flipnm(), getedge(), incrementaldelaunay(), incrementalflip(), insertpoint(), lawsonflip3d(), randomsample(), recoveredgebyflips(), removefacebyflips(), removevertexbyflips(), report_selfint_face(), smoothpoint(), splitsliver(), and suppressbdrysteinerpoint().
orient3dfast()
REAL tetgenmesh::orient3dfast (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 3300 of file tetgenBR.cxx.
Referenced by incrementaldelaunay(), insertpoint(), lawsonflip3d(), smoothpoint(), and suppresssteinerpoints().
orient4d_s()
REAL tetgenmesh::orient4d_s (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL eheight)
Definition at line 1961 of file tetgenBR.cxx.
Referenced by incrementalflip(), and insertpoint().
orthosphere()
bool tetgenmesh::orthosphere (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL * orthocent, REAL * radius)
Definition at line 3723 of file tetgenBR.cxx.
outmesh2medit()
void tetgenmesh::outmesh2medit (const char * mfilename)
outsurfacemesh()
void tetgenmesh::outsurfacemesh (const char * mfilename)
pinfect()
void tetgenmesh::pinfect (point pt) inline
Definition at line 2446 of file tetgenBR.h.
Referenced by getvertexstar(), incrementalflip(), and insertpoint().
pinfected()
bool tetgenmesh::pinfected (point pt) inline
Definition at line 2456 of file tetgenBR.h.
Referenced by getvertexstar(), incrementalflip(), and insertpoint().
planelineint()
void tetgenmesh::planelineint (REAL * pa, REAL * pb, REAL * pc, REAL * e1, REAL * e2, REAL * ip, REAL * u)
Definition at line 3790 of file tetgenBR.cxx.
Referenced by report_selfint_edge(), report_selfint_face(), and suppressbdrysteinerpoint().
pmarktest()
void tetgenmesh::pmarktest (point pt) inline
Definition at line 2464 of file tetgenBR.h.
pmarktest2()
void tetgenmesh::pmarktest2 (point pt) inline
Definition at line 2479 of file tetgenBR.h.
pmarktest2ed()
bool tetgenmesh::pmarktest2ed (point pt) inline
Definition at line 2489 of file tetgenBR.h.
pmarktest3()
void tetgenmesh::pmarktest3 (point pt) inline
Definition at line 2494 of file tetgenBR.h.
pmarktest3ed()
bool tetgenmesh::pmarktest3ed (point pt) inline
Definition at line 2504 of file tetgenBR.h.
pmarktested()
bool tetgenmesh::pmarktested (point pt) inline
Definition at line 2474 of file tetgenBR.h.
point2bgmtet()
tetgenmesh::tetrahedron tetgenmesh::point2bgmtet (point pt) inline
Definition at line 2542 of file tetgenBR.h.
point2ppt()
tetgenmesh::point tetgenmesh::point2ppt (point pt) inline
Definition at line 2522 of file tetgenBR.h.
point2sh()
tetgenmesh::shellface tetgenmesh::point2sh (point pt) inline
Definition at line 2532 of file tetgenBR.h.
Referenced by point2shorg(), removevertexbyflips(), report_selfint_edge(), and suppressbdrysteinerpoint().
point2shorg()
void tetgenmesh::point2shorg (point pa, face & s) inline
Definition at line 2588 of file tetgenBR.h.
point2tet()
tetgenmesh::tetrahedron tetgenmesh::point2tet (point pt) inline
Definition at line 2512 of file tetgenBR.h.
Referenced by carveholes(), insertpoint(), and point2tetorg().
point2tetorg()
void tetgenmesh::point2tetorg (point pt, triface & t) inline
Definition at line 2571 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), getedge(), getvertexstar(), insertpoint(), recoveredgebyflips(), recoverfacebyflips(), recoversubfaces(), reduceedgesatvertex(), and removevertexbyflips().
pointdealloc()
void tetgenmesh::pointdealloc (point dyingpoint)
Definition at line 1439 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), jettisonnodes(), splitsliver(), and suppressbdrysteinerpoint().
pointgeomtag()
int tetgenmesh::pointgeomtag (point pt) inline
Definition at line 2421 of file tetgenBR.h.
pointgeomuv()
REAL tetgenmesh::pointgeomuv (point pt, int i) inline
Definition at line 2433 of file tetgenBR.h.
pointmark()
int tetgenmesh::pointmark (point pt) inline
Definition at line 2396 of file tetgenBR.h.
Referenced by addsteiner4recoversegment(), calculateabovepoint(), carveholes(), getedge(), identifyinputedges(), incrementaldelaunay(), initialdelaunay(), insertpoint(), insphere_s(), makepoint2submap(), orient4d_s(), randomsample(), recoversegments(), recoversubfaces(), removevertexbyflips(), report_overlapping_facets(), report_selfint_edge(), report_selfint_face(), sinsertvertex(), sscoutsegment(), suppressbdrysteinerpoint(), and unifysegments().
pointtraverse()
tetgenmesh::point tetgenmesh::pointtraverse ()
Definition at line 1453 of file tetgenBR.cxx.
Referenced by carveholes(), jettisonnodes(), and makeindex2pointmap().
pointtype()
enum tetgenmesh::verttype tetgenmesh::pointtype (point pt) inline
Definition at line 2401 of file tetgenBR.h.
Referenced by addsteiner4recoversegment(), carveholes(), flip22(), flip31(), improvequalitybysmoothing(), incrementaldelaunay(), initialdelaunay(), issteinerpoint(), jettisonnodes(), lawsonflip3d(), pointtraverse(), recoverfacebyflips(), removevertexbyflips(), report_selfint_edge(), sinsertvertex(), suppressbdrysteinerpoint(), and suppresssteinerpoints().
projpt2edge()
void tetgenmesh::projpt2edge (REAL * p, REAL * e1, REAL * e2, REAL * prj)
Definition at line 3379 of file tetgenBR.cxx.
projpt2face()
void tetgenmesh::projpt2face (REAL * p, REAL * f1, REAL * f2, REAL * f3, REAL * prj)
Definition at line 3408 of file tetgenBR.cxx.
puninfect()
void tetgenmesh::puninfect (point pt) inline
Definition at line 2451 of file tetgenBR.h.
Referenced by getvertexstar(), incrementalflip(), and insertpoint().
punmarktest()
void tetgenmesh::punmarktest (point pt) inline
Definition at line 2469 of file tetgenBR.h.
punmarktest2()
void tetgenmesh::punmarktest2 (point pt) inline
Definition at line 2484 of file tetgenBR.h.
punmarktest3()
void tetgenmesh::punmarktest3 (point pt) inline
Definition at line 2499 of file tetgenBR.h.
randomnation()
unsigned long tetgenmesh::randomnation (unsigned int choices)
Definition at line 8337 of file tetgenBR.cxx.
Referenced by insertpoint(), randomsample(), recoverboundary(), and smoothpoint().
randomsample()
void tetgenmesh::randomsample (point searchpt, triface * searchtet)
Definition at line 8367 of file tetgenBR.cxx.
Referenced by carveholes(), and insertpoint().
reconstructmesh()
bool tetgenmesh::reconstructmesh (void *)
recoverboundary()
void tetgenmesh::recoverboundary (clock_t & tv)
Definition at line 14934 of file tetgenBR.cxx.
recoverdelaunay()
void tetgenmesh::recoverdelaunay ()
Definition at line 16219 of file tetgenBR.cxx.
recoveredgebyflips()
int tetgenmesh::recoveredgebyflips (point startpt, point endpt, face * sedge, triface * searchtet, int fullsearch)
Definition at line 12059 of file tetgenBR.cxx.
Referenced by recoversegments(), and recoversubfaces().
recoverfacebyflips()
int tetgenmesh::recoverfacebyflips (point pa, point pb, point pc, face * searchsh, triface * searchtet)
Definition at line 12982 of file tetgenBR.cxx.
Referenced by recoversubfaces().
recoversegments()
int tetgenmesh::recoversegments (arraypool * misseglist, int fullsearch, int steinerflag)
Definition at line 12858 of file tetgenBR.cxx.
Referenced by recoverboundary().
recoversubfaces()
int tetgenmesh::recoversubfaces (arraypool * misshlist, int steinerflag)
Definition at line 13146 of file tetgenBR.cxx.
Referenced by recoverboundary().
reduceedgesatvertex()
int tetgenmesh::reduceedgesatvertex (point startpt, arraypool * endptlist)
Definition at line 13658 of file tetgenBR.cxx.
Referenced by removevertexbyflips().
removeedgebyflips()
int tetgenmesh::removeedgebyflips (triface * flipedge, flipconstraints * fc)
Definition at line 11898 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_segment(), improvequalitybyflips(), recoverdelaunay(), recoveredgebyflips(), recoverfacebyflips(), reduceedgesatvertex(), and removefacebyflips().
removefacebyflips()
int tetgenmesh::removefacebyflips (triface * flipface, flipconstraints * fc)
Definition at line 11991 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_segment(), and recoveredgebyflips().
removeslivers()
long tetgenmesh::removeslivers (int chkencflag)
Definition at line 17052 of file tetgenBR.cxx.
Referenced by optimizemesh().
removevertexbyflips()
int tetgenmesh::removevertexbyflips (point steinerpt)
Definition at line 13745 of file tetgenBR.cxx.
Referenced by lawsonflip3d(), recoverboundary(), suppressbdrysteinerpoint(), and suppresssteinerpoints().
report_overlapping_facets()
void tetgenmesh::report_overlapping_facets (face * f1, face * f2, REAL dihedang = 0.0)
Definition at line 4042 of file tetgenBR.cxx.
Referenced by unifysegments().
report_selfint_edge()
int tetgenmesh::report_selfint_edge (point e1, point e2, face * sedge, triface * searchtet, enum interresult dir)
Definition at line 4109 of file tetgenBR.cxx.
Referenced by recoveredgebyflips().
report_selfint_face()
int tetgenmesh::report_selfint_face (point p1, point p2, point p3, face * sface, triface * iedge, int intflag, int * types, int * poss)
Definition at line 4506 of file tetgenBR.cxx.
Referenced by recoverfacebyflips().
sapex()
tetgenmesh::point tetgenmesh::sapex (face & s) inline
Definition at line 2049 of file tetgenBR.h.
Referenced by carveholes(), flip22(), identifyinputedges(), insertpoint(), lawsonflip(), mergefacets(), recoversubfaces(), removevertexbyflips(), report_overlapping_facets(), report_selfint_edge(), report_selfint_face(), sinsertvertex(), sscoutsegment(), suppressbdrysteinerpoint(), and unifysegments().
sbond()
void tetgenmesh::sbond (face & s1, face & s2) inline
Definition at line 2001 of file tetgenBR.h.
Referenced by sinsertvertex(), and sscoutsegment().
sbond1()
void tetgenmesh::sbond1 (face & s1, face & s2) inline
Definition at line 2011 of file tetgenBR.h.
Referenced by carveholes(), flip22(), flip31(), sinsertvertex(), sscoutsegment(), and unifysegments().
scarveholes()
void tetgenmesh::scarveholes (int holes, REAL * holelist)
Definition at line 10810 of file tetgenBR.cxx.
sdecode()
void tetgenmesh::sdecode (shellface sptr, face & s) inline
Definition at line 1982 of file tetgenBR.h.
Referenced by insertpoint(), point2shorg(), removevertexbyflips(), report_selfint_edge(), spivot(), spivotself(), sspivot(), suppressbdrysteinerpoint(), tspivot(), and tsspivot1().
sdest()
tetgenmesh::point tetgenmesh::sdest (face & s) inline
Definition at line 2044 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), farsdest(), flip22(), flip31(), flipshpush(), identifyinputedges(), insertpoint(), lawsonflip(), lawsonflip3d(), mergefacets(), recoversegments(), recoversubfaces(), removevertexbyflips(), report_overlapping_facets(), report_selfint_edge(), report_selfint_face(), sinsertvertex(), sscoutsegment(), suppressbdrysteinerpoint(), and unifysegments().
sdissolve()
void tetgenmesh::sdissolve (face & s) inline
Definition at line 2019 of file tetgenBR.h.
Referenced by carveholes(), flip22(), scarveholes(), sinsertvertex(), and sscoutsegment().
sencode()
tetgenmesh::shellface tetgenmesh::sencode (face & s) inline
Definition at line 1988 of file tetgenBR.h.
Referenced by flip22(), flip31(), sbond(), sbond1(), sinsertvertex(), ssbond(), ssbond1(), sscoutsegment(), and tssbond1().
sencode2()
tetgenmesh::shellface tetgenmesh::sencode2 (shellface * sh, int shver) inline
Definition at line 1993 of file tetgenBR.h.
Referenced by tsbond().
senext()
void tetgenmesh::senext (face & s1, face & s2) inline
Definition at line 2087 of file tetgenBR.h.
Referenced by farsdest(), flip22(), flip31(), mergefacets(), removevertexbyflips(), sinsertvertex(), sscoutsegment(), and suppressbdrysteinerpoint().
senext2()
void tetgenmesh::senext2 (face & s1, face & s2) inline
Definition at line 2095 of file tetgenBR.h.
Referenced by farsorg(), flip22(), flip31(), identifyinputedges(), removevertexbyflips(), sinsertvertex(), sscoutsegment(), and suppressbdrysteinerpoint().
senext2self()
void tetgenmesh::senext2self (face & s) inline
Definition at line 2101 of file tetgenBR.h.
Referenced by flip41(), sinsertvertex(), sscoutsegment(), suppressbdrysteinerpoint(), and unifysegments().
senextself()
void tetgenmesh::senextself (face & s) inline
Definition at line 2093 of file tetgenBR.h.
Referenced by carveholes(), insertpoint(), lawsonflip3d(), mergefacets(), recoversubfaces(), scarveholes(), sinsertvertex(), sscoutsegment(), and suppressbdrysteinerpoint().
sesym()
void tetgenmesh::sesym (face & s1, face & s2) inline
Definition at line 2076 of file tetgenBR.h.
Referenced by flip41().
sesymself()
void tetgenmesh::sesymself (face & s) inline
Definition at line 2082 of file tetgenBR.h.
Referenced by addsteiner4recoversegment(), carveholes(), farsdest(), farsorg(), flip22(), flip23(), flip31(), flip32(), flip41(), identifyinputedges(), insertpoint(), lawsonflip3d(), recoversubfaces(), removevertexbyflips(), sinsertvertex(), sscoutsegment(), suppressbdrysteinerpoint(), and unifysegments().
setapex()
void tetgenmesh::setapex (triface & t, point p) inline
Definition at line 1760 of file tetgenBR.h.
Referenced by insertpoint(), and suppressbdrysteinerpoint().
setareabound()
void tetgenmesh::setareabound (face & s, REAL value) inline
Definition at line 2113 of file tetgenBR.h.
Referenced by flip31(), identifyinputedges(), makeshellface(), sinsertvertex(), sscoutsegment(), and unifysegments().
setdest()
void tetgenmesh::setdest (triface & t, point p) inline
Definition at line 1755 of file tetgenBR.h.
Referenced by insertpoint().
setelemattribute()
void tetgenmesh::setelemattribute (tetrahedron * ptr, int attnum, REAL value) inline
Definition at line 1783 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), insertpoint(), and maketetrahedron().
setelemcounter()
void tetgenmesh::setelemcounter (triface & t, int value) inline
Definition at line 1933 of file tetgenBR.h.
Referenced by decreaseelemcounter(), increaseelemcounter(), and removeedgebyflips().
setelemindex()
void tetgenmesh::setelemindex (tetrahedron * ptr, int value) inline
Definition at line 1810 of file tetgenBR.h.
setelemmarker()
void tetgenmesh::setelemmarker (tetrahedron * ptr, int value) inline
Definition at line 1824 of file tetgenBR.h.
Referenced by flip23(), flip32(), flip41(), and maketetrahedron().
setfacetindex()
void tetgenmesh::setfacetindex (face & f, int value) inline
Definition at line 2215 of file tetgenBR.h.
Referenced by flip31(), makeshellface(), sinsertvertex(), and sscoutsegment().
setoppo()
void tetgenmesh::setoppo (triface & t, point p) inline
Definition at line 1765 of file tetgenBR.h.
Referenced by insertpoint(), and suppressbdrysteinerpoint().
setorg()
void tetgenmesh::setorg (triface & t, point p) inline
Definition at line 1750 of file tetgenBR.h.
Referenced by insertpoint().
setpoint2bgmtet()
void tetgenmesh::setpoint2bgmtet (point pt, tetrahedron value) inline
Definition at line 2547 of file tetgenBR.h.
Referenced by initializepools(), and makepoint().
setpoint2ppt()
void tetgenmesh::setpoint2ppt (point pt, point value) inline
Definition at line 2527 of file tetgenBR.h.
Referenced by incrementaldelaunay(), initializepools(), and makepoint().
setpoint2sh()
void tetgenmesh::setpoint2sh (point pt, shellface value) inline
Definition at line 2537 of file tetgenBR.h.
Referenced by flip22(), flip31(), initializepools(), makepoint(), sinsertvertex(), and sscoutsegment().
setpoint2tet()
void tetgenmesh::setpoint2tet (point pt, tetrahedron value) inline
Definition at line 2517 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), initialdelaunay(), initializepools(), insertpoint(), makepoint(), and suppressbdrysteinerpoint().
setpointgeomtag()
void tetgenmesh::setpointgeomtag (point pt, int value) inline
Definition at line 2426 of file tetgenBR.h.
setpointgeomuv()
void tetgenmesh::setpointgeomuv (point pt, int i, REAL value) inline
Definition at line 2438 of file tetgenBR.h.
setpointinsradius()
void tetgenmesh::setpointinsradius (point pt, REAL value) inline
Definition at line 2553 of file tetgenBR.h.
setpointmark()
void tetgenmesh::setpointmark (point pt, int value) inline
Definition at line 2401 of file tetgenBR.h.
Referenced by initializepools(), jettisonnodes(), and makepoint().
setpointtype()
void tetgenmesh::setpointtype (point pt, enum verttype value) inline
Definition at line 2413 of file tetgenBR.h.
Referenced by carveholes(), flip41(), incrementaldelaunay(), initialdelaunay(), initializepools(), insertpoint(), makepoint(), pointdealloc(), recoverfacebyflips(), removevertexbyflips(), and suppressbdrysteinerpoint().
setsapex()
void tetgenmesh::setsapex (face & s, point pointptr) inline
Definition at line 2064 of file tetgenBR.h.
setsdest()
void tetgenmesh::setsdest (face & s, point pointptr) inline
Definition at line 2059 of file tetgenBR.h.
setshellmark()
void tetgenmesh::setshellmark (face & s, int value) inline
Definition at line 2126 of file tetgenBR.h.
Referenced by flip31(), identifyinputedges(), makeshellface(), sinsertvertex(), and sscoutsegment().
setsorg()
void tetgenmesh::setsorg (face & s, point pointptr) inline
Definition at line 2054 of file tetgenBR.h.
setvolumebound()
void tetgenmesh::setvolumebound (tetrahedron * ptr, REAL value) inline
Definition at line 1796 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), insertpoint(), and maketetrahedron().
shellfacedealloc()
void tetgenmesh::shellfacedealloc (memorypool * pool, shellface * dyingsh)
Definition at line 1404 of file tetgenBR.cxx.
Referenced by carveholes(), flip41(), insertpoint(), mergefacets(), recoverfacebyflips(), recoversubfaces(), scarveholes(), sinsertvertex(), sscoutsegment(), and unifysegments().
shellfacetraverse()
tetgenmesh::shellface * tetgenmesh::shellfacetraverse (memorypool * pool)
Definition at line 1419 of file tetgenBR.cxx.
Referenced by carveholes(), identifyinputedges(), makepoint2submap(), mergefacets(), recoverboundary(), and unifysegments().
shellmark()
int tetgenmesh::shellmark (face & s) inline
Definition at line 2121 of file tetgenBR.h.
Referenced by carveholes(), flip31(), mergefacets(), report_overlapping_facets(), report_selfint_edge(), report_selfint_face(), sinsertvertex(), and sscoutsegment().
shortdistance()
REAL tetgenmesh::shortdistance (REAL * p, REAL * e1, REAL * e2)
Definition at line 3255 of file tetgenBR.cxx.
sinfect()
void tetgenmesh::sinfect (face & s) inline
Definition at line 2134 of file tetgenBR.h.
Referenced by carveholes(), flipnm(), insertpoint(), removeedgebyflips(), scarveholes(), and suppressbdrysteinerpoint().
sinfected()
bool tetgenmesh::sinfected (face & s) inline
Definition at line 2148 of file tetgenBR.h.
Referenced by carveholes(), flipnm(), getvertexstar(), insertpoint(), removeedgebyflips(), scarveholes(), and suppressbdrysteinerpoint().
sinsertvertex()
int tetgenmesh::sinsertvertex (point newpt, face * searchsh, face * splitseg, int iloc, int bowywat, int rflag)
Definition at line 9578 of file tetgenBR.cxx.
Referenced by insertpoint(), and recoverfacebyflips().
slocate()
enum tetgenmesh::locateresult tetgenmesh::slocate (point searchpt, face * searchsh, int aflag, int cflag, int rflag)
Definition at line 10079 of file tetgenBR.cxx.
Referenced by scarveholes(), and sinsertvertex().
smarktest()
void tetgenmesh::smarktest (face & s) inline
Definition at line 2156 of file tetgenBR.h.
Referenced by insertpoint(), scarveholes(), sinsertvertex(), and sscoutsegment().
smarktest2()
void tetgenmesh::smarktest2 (face & s) inline
Definition at line 2176 of file tetgenBR.h.
Referenced by enqueuesubface(), and recoversubfaces().
smarktest2ed()
bool tetgenmesh::smarktest2ed (face & s) inline
Definition at line 2188 of file tetgenBR.h.
Referenced by enqueuesubface(), and recoversubfaces().
smarktest3()
void tetgenmesh::smarktest3 (face & s) inline
Definition at line 2195 of file tetgenBR.h.
smarktest3ed()
bool tetgenmesh::smarktest3ed (face & s) inline
Definition at line 2207 of file tetgenBR.h.
smarktested()
bool tetgenmesh::smarktested (face & s) inline
Definition at line 2168 of file tetgenBR.h.
Referenced by insertpoint(), scarveholes(), sinsertvertex(), and sscoutsegment().
smoothpoint()
int tetgenmesh::smoothpoint (point smtpt, arraypool * linkfacelist, int ccw, optparameters * opm)
Definition at line 16615 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_schoenhardtpoly(), improvequalitybysmoothing(), splitsliver(), and suppresssteinerpoints().
sorg()
tetgenmesh::point tetgenmesh::sorg (face & s) inline
Definition at line 2039 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), farsorg(), flip22(), flip31(), flipshpush(), identifyinputedges(), insertpoint(), lawsonflip(), lawsonflip3d(), mergefacets(), recoversegments(), recoversubfaces(), removevertexbyflips(), report_overlapping_facets(), report_selfint_edge(), report_selfint_face(), sinsertvertex(), sscoutsegment(), suppressbdrysteinerpoint(), and unifysegments().
spivot()
void tetgenmesh::spivot (face & s1, face & s2) inline
Definition at line 2024 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), flip22(), flip31(), flip32(), flip41(), identifyinputedges(), insertpoint(), lawsonflip(), lawsonflip3d(), mergefacets(), recoverfacebyflips(), recoversubfaces(), removevertexbyflips(), report_selfint_edge(), report_selfint_face(), scarveholes(), sinsertvertex(), sscoutsegment(), and suppressbdrysteinerpoint().
spivotself()
void tetgenmesh::spivotself (face & s) inline
Definition at line 2030 of file tetgenBR.h.
Referenced by farsdest(), farsorg(), insertpoint(), removevertexbyflips(), sinsertvertex(), sscoutsegment(), and suppressbdrysteinerpoint().
splitsliver()
int tetgenmesh::splitsliver (triface * slitet, REAL cosd, int chkencflag)
Definition at line 16920 of file tetgenBR.cxx.
Referenced by removeslivers().
sremovevertex()
int tetgenmesh::sremovevertex (point delpt, face * parentsh, face * parentseg, int lawson)
Definition at line 10079 of file tetgenBR.cxx.
Referenced by removevertexbyflips(), and suppressbdrysteinerpoint().
ssbond()
void tetgenmesh::ssbond (face & s, face & edge) inline
Definition at line 2310 of file tetgenBR.h.
Referenced by carveholes(), flip22(), flip31(), identifyinputedges(), recoversubfaces(), sinsertvertex(), sscoutsegment(), and unifysegments().
ssbond1()
void tetgenmesh::ssbond1 (face & s, face & edge) inline
Definition at line 2316 of file tetgenBR.h.
sscoutsegment()
enum tetgenmesh::interresult tetgenmesh::sscoutsegment (face * searchsh, point endpt, int insertsegflag, int reporterrorflag, int chkencflag)
Definition at line 10079 of file tetgenBR.cxx.
ssdissolve()
void tetgenmesh::ssdissolve (face & s) inline
Definition at line 2324 of file tetgenBR.h.
Referenced by flip22(), mergefacets(), recoversubfaces(), and sscoutsegment().
sspivot()
void tetgenmesh::sspivot (face & s, face & edge) inline
Definition at line 2328 of file tetgenBR.h.
Referenced by carveholes(), flip22(), flip31(), identifyinputedges(), mergefacets(), recoversubfaces(), sinsertvertex(), sscoutsegment(), suppressbdrysteinerpoint(), and unifysegments().
sstbond1()
void tetgenmesh::sstbond1 (face & s, triface & t) inline
Definition at line 2354 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), insertpoint(), recoversegments(), recoversubfaces(), removevertexbyflips(), and suppressbdrysteinerpoint().
sstdissolve1()
void tetgenmesh::sstdissolve1 (face & s) inline
Definition at line 2366 of file tetgenBR.h.
Referenced by insertpoint(), and removevertexbyflips().
sstpivot1()
void tetgenmesh::sstpivot1 (face & s, triface & t) inline
Definition at line 2385 of file tetgenBR.h.
Referenced by carveholes(), insertpoint(), recoversegments(), recoversubfaces(), removevertexbyflips(), and suppressbdrysteinerpoint().
stdissolve()
void tetgenmesh::stdissolve (face & s) inline
Definition at line 2296 of file tetgenBR.h.
Referenced by flip32(), insertpoint(), and removevertexbyflips().
stpivot()
void tetgenmesh::stpivot (face & s, triface & t) inline
Definition at line 2276 of file tetgenBR.h.
Referenced by insertpoint(), lawsonflip3d(), recoversubfaces(), removevertexbyflips(), and suppressbdrysteinerpoint().
suninfect()
void tetgenmesh::suninfect (face & s) inline
Definition at line 2140 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), carveholes(), getvertexstar(), insertpoint(), and suppressbdrysteinerpoint().
sunmarktest()
void tetgenmesh::sunmarktest (face & s) inline
Definition at line 2162 of file tetgenBR.h.
Referenced by insertpoint(), insertpoint_abort(), and scarveholes().
sunmarktest2()
void tetgenmesh::sunmarktest2 (face & s) inline
Definition at line 2182 of file tetgenBR.h.
sunmarktest3()
void tetgenmesh::sunmarktest3 (face & s) inline
Definition at line 2201 of file tetgenBR.h.
suppressbdrysteinerpoint()
int tetgenmesh::suppressbdrysteinerpoint (point steinerpt)
Definition at line 14268 of file tetgenBR.cxx.
Referenced by suppresssteinerpoints().
suppresssteinerpoints()
int tetgenmesh::suppresssteinerpoints ()
Definition at line 14778 of file tetgenBR.cxx.
tetalldihedral()
bool tetgenmesh::tetalldihedral (point pa, point pb, point pc, point pd, REAL * cosdd, REAL * cosmaxd, REAL * cosmind)
Definition at line 3444 of file tetgenBR.cxx.
Referenced by checkflipeligibility(), improvequalitybyflips(), improvequalitybysmoothing(), optimizemesh(), removeslivers(), and smoothpoint().
tetallnormal()
void tetgenmesh::tetallnormal (point pa, point pb, point pc, point pd, REAL N[4][3], REAL * volume)
Definition at line 3542 of file tetgenBR.cxx.
Referenced by tetalldihedral().
tetaspectratio()
REAL tetgenmesh::tetaspectratio (point pa, point pb, point pc, point pd)
Definition at line 3585 of file tetgenBR.cxx.
Referenced by smoothpoint().
tetprismvol()
REAL tetgenmesh::tetprismvol (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 3884 of file tetgenBR.cxx.
Referenced by flip23(), flip32(), flip41(), and recoverdelaunay().
tetrahedrondealloc()
void tetgenmesh::tetrahedrondealloc (tetrahedron * dyingtetrahedron)
Definition at line 1347 of file tetgenBR.cxx.
Referenced by add_steinerpt_in_schoenhardtpoly(), carveholes(), flip32(), flip41(), insertpoint(), and suppressbdrysteinerpoint().
tetrahedrontraverse()
tetgenmesh::tetrahedron * tetgenmesh::tetrahedrontraverse ()
Definition at line 1370 of file tetgenBR.cxx.
Referenced by carveholes(), optimizemesh(), and recoverdelaunay().
transfernodes()
void tetgenmesh::transfernodes ()
tri_edge_2d()
int tetgenmesh::tri_edge_2d (point A, point B, point C, point P, point Q, point R, int level, int * types, int * pos)
Definition at line 2044 of file tetgenBR.cxx.
Referenced by tri_edge_tail().
tri_edge_inter_tail()
int tetgenmesh::tri_edge_inter_tail (point , point , point , point , point , REAL , REAL)
Definition at line 2875 of file tetgenBR.cxx.
Referenced by tri_tri_inter().
tri_edge_tail()
int tetgenmesh::tri_edge_tail (point A, point B, point C, point P, point Q, point R, REAL sP, REAL sQ, int level, int * types, int * pos)
Definition at line 2655 of file tetgenBR.cxx.
Referenced by tri_edge_inter_tail(), and tri_edge_test().
tri_edge_test()
int tetgenmesh::tri_edge_test (point A, point B, point C, point P, point Q, point R, int level, int * types, int * pos)
Definition at line 2853 of file tetgenBR.cxx.
Referenced by addsteiner4recoversegment(), checkflipeligibility(), recoveredgebyflips(), and recoverfacebyflips().
tri_tri_inter()
int tetgenmesh::tri_tri_inter (point , point , point , point , point , point)
Definition at line 2912 of file tetgenBR.cxx.
triarea()
REAL tetgenmesh::triarea (REAL * pa, REAL * pb, REAL * pc)
Definition at line 3283 of file tetgenBR.cxx.
tsbond()
void tetgenmesh::tsbond (triface & t, face & s) inline
Definition at line 2237 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), insertpoint(), recoversubfaces(), removevertexbyflips(), and suppressbdrysteinerpoint().
tsdissolve()
void tetgenmesh::tsdissolve (triface & t) inline
Definition at line 2289 of file tetgenBR.h.
Referenced by insertpoint(), removevertexbyflips(), and suppressbdrysteinerpoint().
tspivot()
void tetgenmesh::tspivot (triface & t, face & s) inline
Definition at line 2258 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), getvertexstar(), lawsonflip3d(), report_selfint_edge(), and report_selfint_face().
tssbond1()
void tetgenmesh::tssbond1 (triface & t, face & seg) inline
Definition at line 2343 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), insertpoint(), recoversegments(), recoversubfaces(), removevertexbyflips(), and suppressbdrysteinerpoint().
tssdissolve1()
void tetgenmesh::tssdissolve1 (triface & t) inline
Definition at line 2359 of file tetgenBR.h.
Referenced by recoversubfaces(), removevertexbyflips(), and suppressbdrysteinerpoint().
tsspivot1()
void tetgenmesh::tsspivot1 (triface & t, face & s) inline
Definition at line 2371 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), flipnm(), removeedgebyflips(), report_selfint_edge(), and report_selfint_face().
unifysegments()
void tetgenmesh::unifysegments ()
Definition at line 10905 of file tetgenBR.cxx.
uninfect()
void tetgenmesh::uninfect (triface & t) inline
Definition at line 1838 of file tetgenBR.h.
Referenced by carveholes(), getedge(), getvertexstar(), insertpoint(), and insertpoint_abort().
unmarkedge()
void tetgenmesh::unmarkedge (triface & t) inline
Definition at line 1895 of file tetgenBR.h.
unmarkface()
void tetgenmesh::unmarkface (triface & t) inline
Definition at line 1875 of file tetgenBR.h.
Referenced by incrementalflip(), and lawsonflip3d().
unmarktest()
void tetgenmesh::unmarktest (triface & t) inline
Definition at line 1856 of file tetgenBR.h.
Referenced by improvequalitybysmoothing(), incrementalflip(), insertpoint(), and insertpoint_abort().
unmarktest2()
void tetgenmesh::unmarktest2 (triface & t) inline
Definition at line 1914 of file tetgenBR.h.
Referenced by removeslivers().
volumebound()
REAL tetgenmesh::volumebound (tetrahedron * ptr) inline
Definition at line 1791 of file tetgenBR.h.
Referenced by flip23(), flip32(), and insertpoint().
Member Data Documentation
addin
tetgenio * tetgenmesh::addin
Definition at line 734 of file tetgenBR.h.
Referenced by initializepools(), and initializetetgenmesh().
apexpivot
int tetgenmesh::apexpivot = {5, 6, 7, 4, 7, 7, 5, 5, 6, 4, 4, 6} static
Definition at line 846 of file tetgenBR.h.
Referenced by apex(), and setapex().
areaboundindex
int tetgenmesh::areaboundindex
Definition at line 800 of file tetgenBR.h.
Referenced by areabound(), initializepools(), initializetetgenmesh(), and setareabound().
autofliplinklevel
int tetgenmesh::autofliplinklevel
Definition at line 805 of file tetgenBR.h.
Referenced by flipnm(), improvequalitybyflips(), initializetetgenmesh(), recoverboundary(), recoverdelaunay(), recoversegments(), and recoversubfaces().
b
tetgenbehavior* tetgenmesh::b
Definition at line 737 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), addsteiner4recoversegment(), calculateabovepoint(), carveholes(), checkflipeligibility(), flip23(), flip32(), flipnm(), flipnm_post(), getedge(), hilbert_sort3(), identifyinputedges(), improvequalitybyflips(), improvequalitybysmoothing(), incrementaldelaunay(), incrementalflip(), initialdelaunay(), initializepools(), initializetetgenmesh(), insertpoint(), jettisonnodes(), lawsonflip(), lawsonflip3d(), lu_solve(), makeindex2pointmap(), makepoint(), makepoint2submap(), maketetrahedron(), mergefacets(), optimizemesh(), randomsample(), recoverboundary(), recoverdelaunay(), recoversegments(), recoversubfaces(), removeedgebyflips(), removeslivers(), removevertexbyflips(), report_overlapping_facets(), sinsertvertex(), splitsliver(), sscoutsegment(), suppressbdrysteinerpoint(), suppresssteinerpoints(), terminatetetgen(), and unifysegments().
badsubfacs
memorypool * tetgenmesh::badsubfacs
Definition at line 748 of file tetgenBR.h.
Referenced by flip22(), flip23(), flip32(), flip41(), freememory(), initializetetgenmesh(), and insertpoint().
badsubsegs
memorypool * tetgenmesh::badsubsegs
Definition at line 748 of file tetgenBR.h.
Referenced by flip22(), flip23(), flip32(), flip41(), freememory(), initializetetgenmesh(), and insertpoint().
badtetrahedrons
memorypool* tetgenmesh::badtetrahedrons
Definition at line 748 of file tetgenBR.h.
Referenced by enqueuetetrahedron(), freememory(), initializetetgenmesh(), optimizemesh(), and removeslivers().
bgm
tetgenmesh* tetgenmesh::bgm
Definition at line 740 of file tetgenBR.h.
Referenced by freememory(), initializepools(), initializetetgenmesh(), and makepoint().
bondtbl
int tetgenmesh::bondtbl = {{0,},} static
Definition at line 841 of file tetgenBR.h.
Referenced by bond(), and inittables().
cavebdrylist
arraypool * tetgenmesh::cavebdrylist
Definition at line 756 of file tetgenBR.h.
Referenced by freememory(), getedge(), incrementalflip(), initializepools(), initializetetgenmesh(), insertpoint(), and insertpoint_abort().
caveencseglist
arraypool * tetgenmesh::caveencseglist
Definition at line 758 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), flipnm(), freememory(), initializepools(), initializetetgenmesh(), insertpoint(), and removeedgebyflips().
caveencshlist
arraypool* tetgenmesh::caveencshlist
Definition at line 758 of file tetgenBR.h.
Referenced by freememory(), initializepools(), initializetetgenmesh(), and insertpoint().
caveoldtetlist
arraypool * tetgenmesh::caveoldtetlist
Definition at line 756 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), freememory(), initializepools(), initializetetgenmesh(), insertpoint(), insertpoint_abort(), splitsliver(), and suppressbdrysteinerpoint().
cavesegshlist
arraypool * tetgenmesh::cavesegshlist
Definition at line 759 of file tetgenBR.h.
Referenced by freememory(), initializepools(), initializetetgenmesh(), insertpoint(), insertpoint_abort(), recoverfacebyflips(), sinsertvertex(), sscoutsegment(), and suppressbdrysteinerpoint().
caveshbdlist
arraypool * tetgenmesh::caveshbdlist
Definition at line 759 of file tetgenBR.h.
Referenced by freememory(), initializepools(), initializetetgenmesh(), insertpoint(), recoverfacebyflips(), removevertexbyflips(), scarveholes(), sinsertvertex(), sscoutsegment(), and suppressbdrysteinerpoint().
caveshlist
arraypool* tetgenmesh::caveshlist
Definition at line 759 of file tetgenBR.h.
Referenced by freememory(), initializepools(), initializetetgenmesh(), insertpoint(), insertpoint_abort(), recoverfacebyflips(), scarveholes(), sinsertvertex(), sscoutsegment(), and suppressbdrysteinerpoint().
cavetetlist
arraypool* tetgenmesh::cavetetlist
Definition at line 756 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), flipnm(), flipnm_post(), freememory(), improvequalitybyflips(), improvequalitybysmoothing(), initializepools(), initializetetgenmesh(), insertpoint(), insertpoint_abort(), recoverdelaunay(), removevertexbyflips(), splitsliver(), suppressbdrysteinerpoint(), and suppresssteinerpoints().
cavetetseglist
arraypool * tetgenmesh::cavetetseglist
Definition at line 757 of file tetgenBR.h.
Referenced by freememory(), initializepools(), initializetetgenmesh(), insertpoint(), and insertpoint_abort().
cavetetshlist
arraypool* tetgenmesh::cavetetshlist
Definition at line 757 of file tetgenBR.h.
Referenced by freememory(), initializepools(), initializetetgenmesh(), insertpoint(), and insertpoint_abort().
cavetetvertlist
arraypool * tetgenmesh::cavetetvertlist
Definition at line 757 of file tetgenBR.h.
Referenced by carveholes(), freememory(), incrementalflip(), initializepools(), initializetetgenmesh(), insertpoint(), and removevertexbyflips().
cavitycount
long tetgenmesh::cavitycount
Definition at line 828 of file tetgenBR.h.
Referenced by initializetetgenmesh().
cavityexpcount
long tetgenmesh::cavityexpcount
Definition at line 828 of file tetgenBR.h.
Referenced by initializetetgenmesh().
checkconstraints
int tetgenmesh::checkconstraints
Definition at line 803 of file tetgenBR.h.
Referenced by flip31(), initializepools(), initializetetgenmesh(), makeshellface(), sinsertvertex(), and sscoutsegment().
checksubfaceflag
int tetgenmesh::checksubfaceflag
Definition at line 802 of file tetgenBR.h.
Referenced by flip23(), flip32(), flip41(), flipnm(), initializetetgenmesh(), insertpoint(), lawsonflip3d(), recoverboundary(), recoveredgebyflips(), and removevertexbyflips().
checksubsegflag
int tetgenmesh::checksubsegflag
Definition at line 801 of file tetgenBR.h.
Referenced by flip23(), flip32(), flip41(), flipnm(), initializetetgenmesh(), insertpoint(), lawsonflip3d(), recoverboundary(), recoveredgebyflips(), and removeedgebyflips().
cosmaxdihed
REAL tetgenmesh::cosmaxdihed
Definition at line 809 of file tetgenBR.h.
Referenced by improvequalitybyflips(), and optimizemesh().
cosmindihed
REAL tetgenmesh::cosmindihed
Definition at line 809 of file tetgenBR.h.
cosslidihed
REAL tetgenmesh::cosslidihed
Definition at line 811 of file tetgenBR.h.
Referenced by optimizemesh(), and removeslivers().
cossmtdihed
REAL tetgenmesh::cossmtdihed
Definition at line 810 of file tetgenBR.h.
Referenced by improvequalitybysmoothing(), and optimizemesh().
destpivot
int tetgenmesh::destpivot = {6, 4, 4, 6, 5, 6, 7, 4, 7, 7, 5, 5} static
Definition at line 846 of file tetgenBR.h.
Referenced by dest(), and setdest().
dummypoint
point tetgenmesh::dummypoint
Definition at line 775 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), calculateabovepoint(), calculateabovepoint4(), carveholes(), checkflipeligibility(), flip23(), flip32(), flip41(), flipnm(), freememory(), improvequalitybyflips(), incrementalflip(), initialdelaunay(), initializepools(), initializetetgenmesh(), insertpoint(), ishulltet(), lawsonflip3d(), recoverfacebyflips(), reduceedgesatvertex(), sinsertvertex(), sscoutsegment(), suppressbdrysteinerpoint(), and tetrahedrontraverse().
dupverts
long tetgenmesh::dupverts
Definition at line 824 of file tetgenBR.h.
Referenced by incrementaldelaunay(), initializetetgenmesh(), and jettisonnodes().
edestoppotbl
int tetgenmesh::edestoppotbl = {0,} static
Definition at line 844 of file tetgenBR.h.
Referenced by edestoppo(), edestoppoself(), and inittables().
edge2ver
int tetgenmesh::edge2ver = {0, 1, 2, 3, 8, 5} static
Definition at line 849 of file tetgenBR.h.
Referenced by improvequalitybyflips(), and removeslivers().
elemattribindex
int tetgenmesh::elemattribindex
Definition at line 796 of file tetgenBR.h.
Referenced by elemattribute(), initializepools(), initializetetgenmesh(), and setelemattribute().
elemmarkerindex
int tetgenmesh::elemmarkerindex
Definition at line 798 of file tetgenBR.h.
Referenced by edgemarked(), elemcounter(), elemmarker(), facemarked(), infect(), infected(), initializepools(), markedge(), markface(), marktest(), marktest2(), marktest2ed(), marktested(), setelemcounter(), setelemmarker(), uninfect(), unmarkedge(), unmarkface(), unmarktest(), and unmarktest2().
encseglist
arraypool* tetgenmesh::encseglist
Definition at line 765 of file tetgenBR.h.
Referenced by freememory(), and initializetetgenmesh().
encshlist
arraypool * tetgenmesh::encshlist
Definition at line 765 of file tetgenBR.h.
Referenced by freememory(), and initializetetgenmesh().
enextesymtbl
int tetgenmesh::enextesymtbl = {0,} static
Definition at line 843 of file tetgenBR.h.
Referenced by enextesym(), enextesymself(), and inittables().
enexttbl
int tetgenmesh::enexttbl = {0,} static
Definition at line 842 of file tetgenBR.h.
Referenced by enext(), enextself(), and inittables().
eorgoppotbl
int tetgenmesh::eorgoppotbl = {0,} static
Definition at line 844 of file tetgenBR.h.
Referenced by eorgoppo(), eorgoppoself(), and inittables().
epivot
int tetgenmesh::epivot = {4, 5, 2, 11, 4, 5, 2, 11, 4, 5, 2, 11} static
Definition at line 849 of file tetgenBR.h.
Referenced by incrementalflip(), and insertpoint().
eprevesymtbl
int tetgenmesh::eprevesymtbl = {0,} static
Definition at line 843 of file tetgenBR.h.
Referenced by eprevesym(), eprevesymself(), and inittables().
eprevtbl
int tetgenmesh::eprevtbl = {0,} static
Definition at line 842 of file tetgenBR.h.
Referenced by eprev(), eprevself(), and inittables().
esymtbl
int tetgenmesh::esymtbl = {9, 6, 11, 4, 3, 7, 1, 5, 10, 0, 8, 2} static
Definition at line 842 of file tetgenBR.h.
Referenced by esym(), esymself(), and inittables().
facepivot1
int tetgenmesh::facepivot1 = {0,} static
Definition at line 845 of file tetgenBR.h.
Referenced by fnext(), and inittables().
facepivot2
int tetgenmesh::facepivot2 = {{0,},} static
Definition at line 845 of file tetgenBR.h.
Referenced by fnext(), and inittables().
facetverticeslist
point* tetgenmesh::facetverticeslist
Definition at line 769 of file tetgenBR.h.
Referenced by freememory(), and initializetetgenmesh().
fillregioncount
long tetgenmesh::fillregioncount
Definition at line 828 of file tetgenBR.h.
Referenced by initializetetgenmesh().
flip14count
long tetgenmesh::flip14count
Definition at line 829 of file tetgenBR.h.
Referenced by initializetetgenmesh(), and insertpoint().
flip22count
long tetgenmesh::flip22count
Definition at line 831 of file tetgenBR.h.
Referenced by flip22(), initializetetgenmesh(), and lawsonflip3d().
flip23count
long tetgenmesh::flip23count
Definition at line 830 of file tetgenBR.h.
Referenced by flip23(), initializetetgenmesh(), and lawsonflip3d().
flip26count
long tetgenmesh::flip26count
Definition at line 829 of file tetgenBR.h.
Referenced by initializetetgenmesh(), and insertpoint().
flip31count
long tetgenmesh::flip31count
Definition at line 831 of file tetgenBR.h.
Referenced by flip31(), and initializetetgenmesh().
flip32count
long tetgenmesh::flip32count
Definition at line 830 of file tetgenBR.h.
Referenced by flip32(), initializetetgenmesh(), and lawsonflip3d().
flip41count
long tetgenmesh::flip41count
Definition at line 830 of file tetgenBR.h.
Referenced by flip41(), and initializetetgenmesh().
flip44count
long tetgenmesh::flip44count
Definition at line 830 of file tetgenBR.h.
Referenced by initializetetgenmesh(), and lawsonflip3d().
flipn2ncount
long tetgenmesh::flipn2ncount
Definition at line 829 of file tetgenBR.h.
Referenced by initializetetgenmesh(), and insertpoint().
flippool
memorypool* tetgenmesh::flippool
Definition at line 751 of file tetgenBR.h.
Referenced by flippush(), flipshpush(), freememory(), incrementalflip(), initializepools(), initializetetgenmesh(), lawsonflip(), lawsonflip3d(), recoverdelaunay(), and unifysegments().
flipstack
badface* tetgenmesh::flipstack
Definition at line 753 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), flipshpush(), incrementaldelaunay(), incrementalflip(), initializetetgenmesh(), insertpoint(), lawsonflip(), lawsonflip3d(), mergefacets(), and recoverdelaunay().
fsymtbl
int tetgenmesh::fsymtbl = {{0,},} static
Definition at line 841 of file tetgenBR.h.
Referenced by fsym(), and inittables().
highordertable
point* tetgenmesh::highordertable
Definition at line 785 of file tetgenBR.h.
Referenced by freememory(), and initializetetgenmesh().
hullsize
long tetgenmesh::hullsize
Definition at line 820 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), flip41(), initialdelaunay(), initializetetgenmesh(), insertpoint(), and suppressbdrysteinerpoint().
idx2facetlist
int* tetgenmesh::idx2facetlist
Definition at line 768 of file tetgenBR.h.
Referenced by freememory(), and initializetetgenmesh().
in
tetgenio* tetgenmesh::in
Definition at line 734 of file tetgenBR.h.
Referenced by carveholes(), identifyinputedges(), incrementaldelaunay(), initializepools(), initializetetgenmesh(), jettisonnodes(), makeindex2pointmap(), makepoint(), makepoint2submap(), and unifysegments().
insegments
long tetgenmesh::insegments
Definition at line 819 of file tetgenBR.h.
Referenced by initializetetgenmesh().
longest
REAL tetgenmesh::longest
Definition at line 814 of file tetgenBR.h.
Referenced by initializetetgenmesh(), and randomsample().
meshedges
long tetgenmesh::meshedges
Definition at line 821 of file tetgenBR.h.
Referenced by initializetetgenmesh().
meshhulledges
long tetgenmesh::meshhulledges
Definition at line 822 of file tetgenBR.h.
Referenced by initializetetgenmesh().
minedgelength
REAL tetgenmesh::minedgelength
Definition at line 815 of file tetgenBR.h.
Referenced by incrementaldelaunay(), initializetetgenmesh(), and insertpoint().
minfaceang
REAL tetgenmesh::minfaceang
Definition at line 812 of file tetgenBR.h.
Referenced by initializetetgenmesh().
minfacetdihed
REAL tetgenmesh::minfacetdihed
Definition at line 812 of file tetgenBR.h.
Referenced by initializetetgenmesh(), and unifysegments().
nonconvex
int tetgenmesh::nonconvex
Definition at line 804 of file tetgenBR.h.
Referenced by carveholes(), flipnm(), initializetetgenmesh(), insertpoint(), lawsonflip3d(), randomsample(), and reduceedgesatvertex().
nonregularcount
long tetgenmesh::nonregularcount
Definition at line 826 of file tetgenBR.h.
Referenced by incrementaldelaunay(), initializetetgenmesh(), and insertpoint().
numelemattrib
int tetgenmesh::numelemattrib
Definition at line 789 of file tetgenBR.h.
Referenced by carveholes(), flip23(), flip32(), initializepools(), initializetetgenmesh(), insertpoint(), maketetrahedron(), and optimizemesh().
numpointattrib
int tetgenmesh::numpointattrib
Definition at line 788 of file tetgenBR.h.
Referenced by initializepools(), initializetetgenmesh(), and makepoint().
oppopivot
int tetgenmesh::oppopivot = {4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7} static
Definition at line 846 of file tetgenBR.h.
Referenced by oppo(), and setoppo().
orgpivot
int tetgenmesh::orgpivot = {7, 7, 5, 5, 6, 4, 4, 6, 5, 6, 7, 4} static
Definition at line 846 of file tetgenBR.h.
Referenced by org(), and setorg().
PI
REAL tetgenmesh::PI = 3.14159265358979323846264338327950288419716939937510582 static
Definition at line 781 of file tetgenBR.h.
Referenced by initializetetgenmesh(), interiorangle(), mergefacets(), optimizemesh(), report_overlapping_facets(), and unifysegments().
point2simindex
int tetgenmesh::point2simindex
Definition at line 793 of file tetgenBR.h.
Referenced by initializepools(), initializetetgenmesh(), point2bgmtet(), point2ppt(), point2sh(), point2tet(), setpoint2bgmtet(), setpoint2ppt(), setpoint2sh(), and setpoint2tet().
pointinsradiusindex
int tetgenmesh::pointinsradiusindex
Definition at line 795 of file tetgenBR.h.
Referenced by getpointinsradius(), initializepools(), initializetetgenmesh(), and setpointinsradius().
pointmarkindex
int tetgenmesh::pointmarkindex
Definition at line 794 of file tetgenBR.h.
Referenced by initializepools(), initializetetgenmesh(), makepoint(), pinfect(), pinfected(), pmarktest(), pmarktest2(), pmarktest2ed(), pmarktest3(), pmarktest3ed(), pmarktested(), pointgeomtag(), pointmark(), puninfect(), punmarktest(), punmarktest2(), punmarktest3(), setpointgeomtag(), setpointmark(), and setpointtype().
pointmtrindex
int tetgenmesh::pointmtrindex
Definition at line 791 of file tetgenBR.h.
Referenced by initializepools(), initializetetgenmesh(), insertpoint(), and makepoint().
pointparamindex
int tetgenmesh::pointparamindex
Definition at line 792 of file tetgenBR.h.
Referenced by initializepools(), initializetetgenmesh(), pointgeomuv(), and setpointgeomuv().
points
memorypool * tetgenmesh::points
Definition at line 744 of file tetgenBR.h.
Referenced by carveholes(), freememory(), incrementaldelaunay(), initializepools(), initializetetgenmesh(), jettisonnodes(), makeindex2pointmap(), makepoint(), makepoint2submap(), pointdealloc(), and pointtraverse().
randomseed
unsigned long tetgenmesh::randomseed
Definition at line 808 of file tetgenBR.h.
Referenced by initializetetgenmesh(), and randomnation().
recentsh
face tetgenmesh::recentsh
Definition at line 778 of file tetgenBR.h.
Referenced by flip22(), flip31(), scarveholes(), and sinsertvertex().
recenttet
triface tetgenmesh::recenttet
Definition at line 777 of file tetgenBR.h.
Referenced by flip23(), flip32(), flip41(), incrementaldelaunay(), initialdelaunay(), insertpoint(), and randomsample().
samples
long tetgenmesh::samples
Definition at line 807 of file tetgenBR.h.
Referenced by initializetetgenmesh(), and randomsample().
sapexpivot
int tetgenmesh::sapexpivot = {5, 5, 3, 3, 4, 4} static
Definition at line 850 of file tetgenBR.h.
Referenced by sapex(), and setsapex().
sdestpivot
int tetgenmesh::sdestpivot = {4, 3, 5, 4, 3, 5} static
Definition at line 850 of file tetgenBR.h.
Referenced by sdest(), and setsdest().
segmentendpointslist
point* tetgenmesh::segmentendpointslist
Definition at line 772 of file tetgenBR.h.
Referenced by freememory(), and initializetetgenmesh().
shmarkindex
int tetgenmesh::shmarkindex
Definition at line 799 of file tetgenBR.h.
Referenced by getfacetindex(), initializepools(), initializetetgenmesh(), makeshellface(), setfacetindex(), setshellmark(), shellmark(), sinfect(), sinfected(), smarktest(), smarktest2(), smarktest2ed(), smarktest3(), smarktest3ed(), smarktested(), suninfect(), sunmarktest(), sunmarktest2(), and sunmarktest3().
sizeoftensor
int tetgenmesh::sizeoftensor
Definition at line 790 of file tetgenBR.h.
Referenced by initializepools(), initializetetgenmesh(), and makepoint().
snextpivot
int tetgenmesh::snextpivot = {2, 5, 4, 1, 0, 3} static
Definition at line 851 of file tetgenBR.h.
Referenced by senext(), senext2(), senext2self(), and senextself().
sorgpivot
int tetgenmesh::sorgpivot = {3, 4, 4, 5, 5, 3} static
Definition at line 850 of file tetgenBR.h.
Referenced by setsorg(), and sorg().
st_facref_count
long tetgenmesh::st_facref_count
Definition at line 827 of file tetgenBR.h.
Referenced by carveholes(), initializetetgenmesh(), recoverboundary(), recoverfacebyflips(), recoversubfaces(), removevertexbyflips(), and suppressbdrysteinerpoint().
st_segref_count
long tetgenmesh::st_segref_count
Definition at line 827 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), initializetetgenmesh(), recoverboundary(), recoversegments(), removevertexbyflips(), and suppressbdrysteinerpoint().
st_volref_count
long tetgenmesh::st_volref_count
Definition at line 827 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), carveholes(), initializetetgenmesh(), recoverboundary(), recoverfacebyflips(), recoversegments(), removevertexbyflips(), splitsliver(), and suppressbdrysteinerpoint().
stbondtbl
int tetgenmesh::stbondtbl = {{0,},} static
Definition at line 847 of file tetgenBR.h.
Referenced by inittables(), and tsbond().
steinerleft
long tetgenmesh::steinerleft
Definition at line 823 of file tetgenBR.h.
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), initializetetgenmesh(), recoversubfaces(), removeslivers(), removevertexbyflips(), splitsliver(), and suppressbdrysteinerpoint().
stpivottbl
int tetgenmesh::stpivottbl = {{0,},} static
Definition at line 848 of file tetgenBR.h.
Referenced by inittables(), and stpivot().
subfaces
memorypool * tetgenmesh::subfaces
Definition at line 744 of file tetgenBR.h.
Referenced by carveholes(), flip31(), flip41(), freememory(), identifyinputedges(), initializepools(), initializetetgenmesh(), insertpoint(), mergefacets(), recoverboundary(), recoverfacebyflips(), scarveholes(), sinsertvertex(), sscoutsegment(), and unifysegments().
subfacstack
arraypool * tetgenmesh::subfacstack
Definition at line 762 of file tetgenBR.h.
Referenced by carveholes(), freememory(), initializepools(), initializetetgenmesh(), insertpoint(), recoverboundary(), recoverfacebyflips(), and recoversubfaces().
subsegs
memorypool * tetgenmesh::subsegs
Definition at line 744 of file tetgenBR.h.
Referenced by carveholes(), freememory(), identifyinputedges(), initializepools(), initializetetgenmesh(), insertpoint(), mergefacets(), recoverboundary(), recoversubfaces(), sinsertvertex(), sscoutsegment(), and unifysegments().
subsegstack
arraypool* tetgenmesh::subsegstack
Definition at line 762 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), freememory(), initializepools(), initializetetgenmesh(), insertpoint(), recoverboundary(), and recoversegments().
subvertstack
arraypool * tetgenmesh::subvertstack
Definition at line 762 of file tetgenBR.h.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), freememory(), initializepools(), initializetetgenmesh(), recoverboundary(), recoverfacebyflips(), recoversubfaces(), suppressbdrysteinerpoint(), and suppresssteinerpoints().
tet2segpool
memorypool * tetgenmesh::tet2segpool
Definition at line 745 of file tetgenBR.h.
Referenced by flip23(), flip32(), flip41(), freememory(), initializepools(), initializetetgenmesh(), tetrahedrondealloc(), and tssbond1().
tet2subpool
memorypool* tetgenmesh::tet2subpool
Definition at line 745 of file tetgenBR.h.
Referenced by flip23(), flip32(), flip41(), freememory(), initializepools(), initializetetgenmesh(), tetrahedrondealloc(), and tsbond().
tetprism_vol_sum
REAL tetgenmesh::tetprism_vol_sum
Definition at line 813 of file tetgenBR.h.
Referenced by initializetetgenmesh(), lawsonflip3d(), and recoverdelaunay().
tetrahedrons
memorypool* tetgenmesh::tetrahedrons
Definition at line 744 of file tetgenBR.h.
Referenced by alltetrahedrontraverse(), carveholes(), freememory(), initializepools(), initializetetgenmesh(), maketetrahedron(), optimizemesh(), randomsample(), recoverdelaunay(), tetrahedrondealloc(), and tetrahedrontraverse().
totalworkmemory
unsigned long tetgenmesh::totalworkmemory
Definition at line 832 of file tetgenBR.h.
Referenced by initializetetgenmesh(), and recoverboundary().
transgc
int tetgenmesh::transgc[8][3][8]
Definition at line 1239 of file tetgenBR.h.
Referenced by hilbert_init(), and hilbert_sort3().
tsb1mod3
int tetgenmesh::tsb1mod3[8]
Definition at line 1239 of file tetgenBR.h.
Referenced by hilbert_init(), and hilbert_sort3().
tsbondtbl
int tetgenmesh::tsbondtbl = {{0,},} static
Definition at line 847 of file tetgenBR.h.
Referenced by inittables(), and tsbond().
tspivottbl
int tetgenmesh::tspivottbl = {{0,},} static
Definition at line 848 of file tetgenBR.h.
Referenced by inittables(), and tspivot().
unflipqueue
arraypool* tetgenmesh::unflipqueue
Definition at line 752 of file tetgenBR.h.
Referenced by carveholes(), freememory(), improvequalitybyflips(), improvequalitybysmoothing(), initializepools(), initializetetgenmesh(), lawsonflip3d(), optimizemesh(), recoverdelaunay(), and removeslivers().
unuverts
long tetgenmesh::unuverts
Definition at line 825 of file tetgenBR.h.
Referenced by carveholes(), flip41(), initializetetgenmesh(), jettisonnodes(), removevertexbyflips(), and suppressbdrysteinerpoint().
useinsertradius
int tetgenmesh::useinsertradius
Definition at line 806 of file tetgenBR.h.
Referenced by flip31(), initializepools(), initializetetgenmesh(), makeshellface(), sinsertvertex(), and sscoutsegment().
ver2edge
int tetgenmesh::ver2edge = {0, 1, 2, 3, 3, 5, 1, 5, 4, 0, 4, 2} static
Definition at line 849 of file tetgenBR.h.
Referenced by edgemarked(), markedge(), tssbond1(), tssdissolve1(), tsspivot1(), and unmarkedge().
volumeboundindex
int tetgenmesh::volumeboundindex
Definition at line 797 of file tetgenBR.h.
Referenced by initializepools(), initializetetgenmesh(), setvolumebound(), and volumebound().
xmax
REAL tetgenmesh::xmax
Definition at line 816 of file tetgenBR.h.
Referenced by brio_multiscale_sort(), incrementaldelaunay(), and initializetetgenmesh().
xmin
REAL tetgenmesh::xmin
Definition at line 816 of file tetgenBR.h.
Referenced by brio_multiscale_sort(), incrementaldelaunay(), and initializetetgenmesh().
ymax
REAL tetgenmesh::ymax
Definition at line 816 of file tetgenBR.h.
Referenced by brio_multiscale_sort(), incrementaldelaunay(), and initializetetgenmesh().
ymin
REAL tetgenmesh::ymin
Definition at line 816 of file tetgenBR.h.
Referenced by brio_multiscale_sort(), incrementaldelaunay(), and initializetetgenmesh().
zmax
REAL tetgenmesh::zmax
Definition at line 816 of file tetgenBR.h.
Referenced by brio_multiscale_sort(), incrementaldelaunay(), and initializetetgenmesh().
zmin
REAL tetgenmesh::zmin
Definition at line 816 of file tetgenBR.h.
Referenced by brio_multiscale_sort(), incrementaldelaunay(), and initializetetgenmesh().
The documentation for this class was generated from the following files:
src/mesh/tetgenBR.h
src/mesh/tetgenBR.cxx