gmsh-TingyuanDoc: FieldOption Class Reference
FieldOption Class Reference abstract
#include <Field.h>
Public Member Functions
FieldOption (const std::string &help, bool *_status, bool deprecated)
virtual ~FieldOption ()
virtual FieldOptionType getType ()=0
virtual void getTextRepresentation (std::string &v_str)=0
virtual std::string getDescription ()
std::string getTypeName ()
virtual void numericalValue (double val)
virtual double numericalValue () const
virtual const std::list< int > & list () const
virtual const std::list< double > & listdouble () const
virtual void list (std::list< int > value)
virtual void listdouble (std::list< double > value)
virtual std::string string () const
virtual void string (const std::string value)
bool isDeprecated ()
Protected Member Functions
void modified ()
Protected Attributes
bool * status
Private Attributes
std::string _help
bool _deprecated
Detailed Description
Definition at line 50 of file Field.h.
Constructor & Destructor Documentation
FieldOption()
FieldOption::FieldOption (const std::string & help, bool * _status, bool deprecated) inline
Definition at line 63 of file Field.h.
~FieldOption()
virtual FieldOption::~FieldOption () inline virtual
Definition at line 67 of file Field.h.
Member Function Documentation
getDescription()
virtual std::string FieldOption::getDescription () inline virtual
Definition at line 70 of file Field.h.
getTextRepresentation()
virtual void FieldOption::getTextRepresentation (std::string & v_str) pure virtual
Implemented in FieldOptionBool, FieldOptionListDouble, FieldOptionList, FieldOptionInt, FieldOptionDouble, and FieldOptionString.
getType()
virtual FieldOptionType FieldOption::getType () pure virtual
Implemented in FieldOptionBool, FieldOptionPath, FieldOptionListDouble, FieldOptionList, FieldOptionInt, FieldOptionDouble, and FieldOptionString.
Referenced by getTypeName().
getTypeName()
std::string FieldOption::getTypeName () inline
Definition at line 71 of file Field.h.
isDeprecated()
bool FieldOption::isDeprecated () inline
Definition at line 100 of file Field.h.
list() [1/2]
virtual const std::list<int>& FieldOption::list () const inline virtual
Reimplemented in FieldOptionList.
Definition at line 86 of file Field.h.
list() [2/2]
virtual void FieldOption::list (std::list< int > value) inline virtual
Reimplemented in FieldOptionList.
Definition at line 96 of file Field.h.
listdouble() [1/2]
virtual const std::list<double>& FieldOption::listdouble () const inline virtual
Reimplemented in FieldOptionListDouble.
Definition at line 91 of file Field.h.
listdouble() [2/2]
virtual void FieldOption::listdouble (std::list< double > value) inline virtual
Reimplemented in FieldOptionListDouble.
Definition at line 97 of file Field.h.
modified()
void FieldOption::modified () inline protected
Definition at line 57 of file Field.h.
Referenced by FieldOptionList::list(), FieldOptionListDouble::listdouble(), FieldOptionDouble::numericalValue(), FieldOptionInt::numericalValue(), FieldOptionBool::numericalValue(), and FieldOptionString::string().
numericalValue() [1/2]
virtual double FieldOption::numericalValue () const inline virtual
Reimplemented in FieldOptionBool, FieldOptionInt, and FieldOptionDouble.
Definition at line 85 of file Field.h.
numericalValue() [2/2]
virtual void FieldOption::numericalValue (double val) inline virtual
Reimplemented in FieldOptionBool, FieldOptionInt, and FieldOptionDouble.
Definition at line 84 of file Field.h.
string() [1/2]
virtual std::string FieldOption::string () const inline virtual
Reimplemented in FieldOptionString.
Definition at line 98 of file Field.h.
string() [2/2]
virtual void FieldOption::string (const std::string value) inline virtual
Reimplemented in FieldOptionString.
Definition at line 99 of file Field.h.
Member Data Documentation
_deprecated
bool FieldOption::_deprecated private
Definition at line 53 of file Field.h.
Referenced by isDeprecated().
_help
std::string FieldOption::_help private
Definition at line 52 of file Field.h.
Referenced by getDescription().
status
bool* FieldOption::status protected
Definition at line 56 of file Field.h.
Referenced by modified().
The documentation for this class was generated from the following file:
src/mesh/Field.h