gmsh-TingyuanDoc: initMeshGRegion Class Reference
initMeshGRegion Class Reference
Public Member Functions
void operator() (GRegion *r)
Private Member Functions
int _estimateIfClipped (int num)
int _estimateNumLines (GRegion *r)
int _estimateNumTriangles (GRegion *r)
Private Attributes
bool _curved
Detailed Description
Definition at line 354 of file GModelVertexArrays.cpp.
Member Function Documentation
_estimateIfClipped()
int initMeshGRegion::_estimateIfClipped (int num) inline private
Definition at line 357 of file GModelVertexArrays.cpp.
Referenced by _estimateNumLines(), and _estimateNumTriangles().
_estimateNumLines()
int initMeshGRegion::_estimateNumLines (GRegion * r) inline private
Definition at line 375 of file GModelVertexArrays.cpp.
Referenced by operator()().
_estimateNumTriangles()
int initMeshGRegion::_estimateNumTriangles (GRegion * r) inline private
Definition at line 393 of file GModelVertexArrays.cpp.
Referenced by operator()().
operator()()
void initMeshGRegion::operator() (GRegion * r) inline
Definition at line 412 of file GModelVertexArrays.cpp.
Member Data Documentation
_curved
bool initMeshGRegion::_curved private
Definition at line 356 of file GModelVertexArrays.cpp.
Referenced by _estimateNumLines(), _estimateNumTriangles(), and operator()().
The documentation for this class was generated from the following file:
src/geo/GModelVertexArrays.cpp