gmsh-TingyuanDoc: src/numeric/decasteljau.cpp File Reference
decasteljau.cpp File Reference
#include <algorithm>
#include "decasteljau.h"
#include "SPoint3.h"
#include "SVector3.h"
Classes
struct sortedPoint
Functions
static int sortedPointInsert (const SPoint3 &p, const double t, std::vector< sortedPoint > &pts, int pos)
static void sortedPointToVector (const std::vector< sortedPoint > &spts, std::vector< SPoint3 > &pts, std::vector< double > &ts)
double sqDistPointSegment (const SPoint3 &p, const SPoint3 &s0, const SPoint3 &s1)
static void decasteljau (double tol, std::vector< sortedPoint > &discrete, int pos, const SPoint3 &p0, const SPoint3 &p1, const SPoint3 &p2, double t0, double t2)
void decasteljau (double tol, const SPoint3 &p0, const SPoint3 &p1, const SPoint3 &p2, std::vector< SPoint3 > &pts, std::vector< double > &ts)
static void decasteljau (double tol, std::vector< sortedPoint > &discrete, int pos, const SPoint3 &p0, const SPoint3 &p1, const SPoint3 &p2, const SPoint3 &p3, double t0, double t3)
void decasteljau (double tol, const SPoint3 &p0, const SPoint3 &p1, const SPoint3 &p2, const SPoint3 &p3, std::vector< SPoint3 > &pts, std::vector< double > &ts)
static void decasteljau (double tol, std::vector< sortedPoint > &discrete, int pos, const std::vector< SPoint3 > &pts, double t0, double te)
void decasteljau (double tol, const std::vector< SPoint3 > &controlPoints, std::vector< SPoint3 > &pts, std::vector< double > &ts)
Function Documentation
decasteljau() [1/6]
void decasteljau (double tol, const SPoint3 & p0, const SPoint3 & p1, const SPoint3 & p2, const SPoint3 & p3, std::vector< SPoint3 > & pts, std::vector< double > & ts)
Definition at line 101 of file decasteljau.cpp.
decasteljau() [2/6]
void decasteljau (double tol, const SPoint3 & p0, const SPoint3 & p1, const SPoint3 & p2, std::vector< SPoint3 > & pts, std::vector< double > & ts)
Definition at line 69 of file decasteljau.cpp.
decasteljau() [3/6]
void decasteljau (double tol, const std::vector< SPoint3 > & controlPoints, std::vector< SPoint3 > & pts, std::vector< double > & ts)
Definition at line 134 of file decasteljau.cpp.
decasteljau() [4/6]
static void decasteljau (double tol, std::vector< sortedPoint > & discrete, int pos, const SPoint3 & p0, const SPoint3 & p1, const SPoint3 & p2, const SPoint3 & p3, double t0, double t3) static
Definition at line 82 of file decasteljau.cpp.
decasteljau() [5/6]
static void decasteljau (double tol, std::vector< sortedPoint > & discrete, int pos, const SPoint3 & p0, const SPoint3 & p1, const SPoint3 & p2, double t0, double t2) static
Definition at line 55 of file decasteljau.cpp.
Referenced by decasteljau().
decasteljau() [6/6]
static void decasteljau (double tol, std::vector< sortedPoint > & discrete, int pos, const std::vector< SPoint3 > & pts, double t0, double te) static
Definition at line 114 of file decasteljau.cpp.
sortedPointInsert()
static int sortedPointInsert (const SPoint3 & p, const double t, std::vector< sortedPoint > & pts, int pos) static
Definition at line 19 of file decasteljau.cpp.
Referenced by decasteljau().
sortedPointToVector()
static void sortedPointToVector (const std::vector< sortedPoint > & spts, std::vector< SPoint3 > & pts, std::vector< double > & ts) static
Definition at line 29 of file decasteljau.cpp.
Referenced by decasteljau().
sqDistPointSegment()
double sqDistPointSegment (const SPoint3 & p, const SPoint3 & s0, const SPoint3 & s1)
Definition at line 43 of file decasteljau.cpp.
Referenced by decasteljau().