gmsh-TingyuanDoc: src/numeric/discreteFrechetDistance.cpp File Reference
discreteFrechetDistance.cpp File Reference
#include <algorithm>
#include "discreteFrechetDistance.h"
#include "fullMatrix.h"
Functions
static double distance (const SPoint3 &p1, const SPoint3 &p2)
static double c (int i, int j, fullMatrix< double > &CA, const std::vector< SPoint3 > &P, const std::vector< SPoint3 > &Q)
double discreteFrechetDistance (const std::vector< SPoint3 > &P, const std::vector< SPoint3 > &Q)
Function Documentation
c()
static double c (int i, int j, fullMatrix< double > & CA, const std::vector< SPoint3 > & P, const std::vector< SPoint3 > & Q) static
Definition at line 15 of file discreteFrechetDistance.cpp.
Referenced by GEO_Internals::_addCompoundSpline(), bezierCoeff::_computeCoefficients(), _computeDeterminantAndRegularize(), discreteFace::_computeSTLNormals(), _create_splitted_curve(), discreteFace::_createGeometryFromSTL(), GMSH_LevelsetPlugin::_cutAndAddElements(), PViewDataList::_getString(), _h2d(), _kaboom(), _relocateVertexOfPyramid(), _sort2_xkws(), PViewDataList::_stat(), GmshSocket::_swapBytes(), GEO_Internals::_transform(), GModel::addAutomaticExtrusionConstraints(), GEO_Internals::addBezier(), GEO_Internals::addBSpline(), GEO_Internals::addCircleArc(), GEO_Internals::addCurveLoops(), addElementsInArrays(), GEO_Internals::addEllipseArc(), GEO_Internals::addLine(), GEO_Internals::addSpline(), femTerm< scalar >::addToMatrix(), addTriangle(), analyze2dMetric(), xyzn::angle(), angle3Vertices(), angle_plan(), qmTriangle::angles(), qmQuadrangle::angles(), ApplicationOnShapes(), ApplyTransformationToCurve(), ApplyTransformationToSurface(), bowyerWatsonFrontal(), buildDelaunayBall(), buildMetricTangentToCurve(), centroid(), char2float(), char_out(), closestPoint(), CombinedCell::CombinedCell(), PViewDataList::combineSpace(), PViewDataList::combineTime(), compress(), computeAdjacencies(), HilbertSort::ComputeGrayCode(), HilbertSortB::ComputeGrayCode(), GFace::computeMeanPlane(), computeParametrization(), gmshFace::containsPoint(), GEO_Internals::copy(), CopyCurve(), CreateReversedCurve(), cubic(), discreteEdge::curvature(), discreteFace::curvatureMax(), CurvatureRusinkiewicz(), curveGetPoint(), cVecRead(), tetgenmesh::decreaseelemcounter(), Surface::degenerate(), DeleteCurve(), DeletePoint(), DeleteSurface(), DeleteVolume(), GEO_Internals::dilate(), discreteEdge::discreteEdge(), discreteFrechetDistance(), discretizeCurve(), drawContext::drawBackgroundImage(), drawContext::drawPlaneInBoundingBox(), drawContext::drawScales(), DuplicateCurve(), DuplicateSurface(), eigenvalue(), eigenvalue2x2(), EndCurve(), EndSurface(), qmQuadrangle::eta(), GModel::exportDiscreteGEOInternals(), ExtractDoubleQuotedString(), ExtrudePoint(), ExtrudeShapes(), ExtrudeSurface(), GFace::fillVertexArray(), filterColumns(), FindCubicRoots(), fixDelaunayCavity(), float2char(), fourthPoint(), fullMatrix< double >::fullMatrix(), qmTriangle::gamma(), BilinearTermContractWithLaw< T2 >::get(), fullMatrix< double >::get(), GModel::getBoundaryTags(), MQuadrangle::getInnerRadius(), element::getJacobian(), getNodeCopies(), GVertex::getNumMeshElements(), GRegion::getNumMeshElements(), GEdge::getNumMeshElements(), GFace::getNumMeshElements(), GModel::getNumMeshElements(), MFace::getOrientationFlagForFace(), GetVolTet(), MQuadrangle::getVolume(), GFaceInitialMesh(), gl2psAddBoundaryInList(), gl2psCutEdge(), gl2psGetNormal(), gl2psPrintSVGPixmap(), gl2psPvec(), gLevelsetBox::gLevelsetBox(), gLevelsetEllipsoid::gLevelsetEllipsoid(), gLevelsetGeneralQuadric::gLevelsetGeneralQuadric(), gmshEdge::gmshEdge(), GmshFLTK(), GOrientedTransfiniteFace::GOrientedTransfiniteFace(), tetgenmesh::hilbert_init(), hypotenuse(), tetgenmesh::incircle3d(), robustPredicates::incircleadapt(), robustPredicates::incircleexact(), robustPredicates::incircleslow(), inCircumCircleAniso(), tetgenmesh::increaseelemcounter(), Msg::InitializeOnelab(), robustPredicates::insphereadapt(), robustPredicates::insphereexact(), robustPredicates::insphereslow(), InterpolateBezier(), InterpolateCurve(), InterpolateExtrudedSurface(), intersectCurveSurface(), IntersectCurvesWithSurface(), intersection_segments(), discreteFace::intersectionWithCircle(), invalidChar(), GMSH_CutSpherePlugin::levelset(), maxDir(), MaxNumCurve(), meshGenerator(), meshGeneratorPeriodic(), qmPrism::minNCJ(), fullMatrix< double >::mult(), fullMatrix< double >::multOnBlock(), myangle(), gmshFace::normal(), normal_triangle(), oneSidedHausdorffDistance(), compareAngle::operator()(), picojson::serialize_str_char< Iter >::operator()(), RestrictField::operator()(), ConstantField::operator()(), conn::operator<(), conn::operator==(), robustPredicates::orient2dadapt(), robustPredicates::orient2dexact(), robustPredicates::orient2dslow(), robustPredicates::orient3dadapt(), robustPredicates::orient3dexact(), robustPredicates::orient3dslow(), robustPredicates::orient4dadapt(), robustPredicates::orient4dexact(), orientationTest(), prismNCJ(), prodve(), SurfaceProjectorUtils::project_point_triangle_l2(), projectPointToPlane(), projectPS(), backgroundMesh::propagateCrossFieldByDistance(), elasticitySolver::readInputFile(), DocRecord::recur_tag_triangles(), onelab::server::registerClient(), robin_hood::detail::Table< IsFlat, MaxLoadFactor100, Key, T, Hash, KeyEqual >::rehash(), RemoveDegenerateCurves(), RemoveDegenerateSurfaces(), ReplaceDuplicateCurves(), ReplaceDuplicatePoints(), ReplaceDuplicatePointsNew(), robin_hood::detail::Table< IsFlat, MaxLoadFactor100, Key, T, Hash, KeyEqual >::reserve(), gmshEdge::resetNativePtr(), gmshFace::resetNativePtr(), fullMatrix< double >::resize(), robustPredicates::scale_expansion(), robustPredicates::scale_expansion_zeroelim(), xyFace::secondDer(), fullMatrix< double >::set(), fullVector< double >::setAsProxy(), fullMatrix< double >::setAsProxy(), GEO_Internals::setDegenerated(), tetgenmesh::setelemcounter(), GEO_Internals::setReverseMesh(), SetSurfaceGeneratrices(), GEO_Internals::setTransfiniteLine(), VertexArray::sort(), SortCurvesConsecutive(), SortEdgeConsecutive(), SortEdgesInLoop(), GEO_Internals::splitCurve(), SplitCurve(), surface_triangle_param(), SwapBytes(), GEO_Internals::symmetry(), GEO_Internals::synchronize(), DocRecord::tagInterior(), tensprod(), tetcircumcenter(), triangle_area(), triangle_area2d(), TRIANGLE_VALIDITY(), onelab::server::unregisterClient(), vector_triangle(), faceXtet::visible(), and PView::writeX3D().
discreteFrechetDistance()
double discreteFrechetDistance (const std::vector< SPoint3 > & P, const std::vector< SPoint3 > & Q)
Definition at line 46 of file discreteFrechetDistance.cpp.
distance()
static double distance (const SPoint3 & p1, const SPoint3 & p2) static
Definition at line 10 of file discreteFrechetDistance.cpp.
Referenced by c().