gmsh-TingyuanDoc: src/graphics/drawMesh.cpp File Reference
drawMesh.cpp File Reference
#include <cmath>
#include "drawContext.h"
#include "GmshMessage.h"
#include "GmshDefines.h"
#include "GModel.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
#include "MTrihedron.h"
#include "MElementCut.h"
#include "Context.h"
#include "OS.h"
#include "gl2ps.h"
#include "VertexArray.h"
#include "SmoothData.h"
#include "PView.h"
#include "PViewData.h"
Classes
class drawMeshGVertex
class drawMeshGEdge
class drawMeshGFace
class drawMeshGRegion
Functions
unsigned int getColorByEntity (GEntity *e)
bool isElementVisible (MElement *ele)
template<class T >
static void drawElementLabels (drawContext *ctx, GEntity *e, std::vector< T * > &elements, int forceColor=0, unsigned int color=0)
template<class T >
static void drawNormals (drawContext *ctx, std::vector< T * > &elements)
template<class T >
static void drawTangents (drawContext *ctx, std::vector< T * > &elements)
static void drawVertexLabel (drawContext *ctx, GEntity *e, MVertex *v, int partition=-1)
static void drawVerticesPerEntity (drawContext *ctx, GEntity *e)
template<class T >
static void drawVerticesPerElement (drawContext *ctx, GEntity *e, std::vector< T * > &elements)
template<class T >
static void drawBarycentricDual (std::vector< T * > &elements)
template<class T >
static void drawVoronoiDual (std::vector< T * > &elements)
static void drawArrays (drawContext *ctx, GEntity *e, VertexArray *va, GLint type, bool useNormalArray, int forceColor=0, unsigned int color=0)
static void beginFakeTransparency ()
static void endFakeTransparency ()
Function Documentation
beginFakeTransparency()
static void beginFakeTransparency () static
Definition at line 660 of file drawMesh.cpp.
Referenced by drawContext::drawMesh().
drawArrays()
static void drawArrays (drawContext * ctx, GEntity * e, VertexArray * va, GLint type, bool useNormalArray, int forceColor = 0, unsigned int color = 0) static
Definition at line 333 of file drawMesh.cpp.
Referenced by drawMeshGEdge::operator()(), drawMeshGFace::operator()(), and drawMeshGRegion::operator()().
drawBarycentricDual()
template<class T > static void drawBarycentricDual (std::vector< T * > & elements) static
Definition at line 239 of file drawMesh.cpp.
Referenced by drawMeshGFace::operator()(), and drawMeshGRegion::operator()().
drawElementLabels()
template<class T > static void drawElementLabels (drawContext * ctx, GEntity * e, std::vector< T * > & elements, int forceColor = 0, unsigned int color = 0) static
Definition at line 38 of file drawMesh.cpp.
Referenced by drawMeshGEdge::operator()(), drawMeshGFace::operator()(), and drawMeshGRegion::operator()().
drawNormals()
template<class T > static void drawNormals (drawContext * ctx, std::vector< T * > & elements) static
Definition at line 73 of file drawMesh.cpp.
Referenced by drawMeshGFace::operator()().
drawTangents()
template<class T > static void drawTangents (drawContext * ctx, std::vector< T * > & elements) static
Definition at line 89 of file drawMesh.cpp.
Referenced by drawMeshGEdge::operator()().
drawVertexLabel()
static void drawVertexLabel (drawContext * ctx, GEntity * e, MVertex * v, int partition = -1) static
Definition at line 104 of file drawMesh.cpp.
Referenced by drawVerticesPerElement(), and drawVerticesPerEntity().
drawVerticesPerElement()
template<class T > static void drawVerticesPerElement (drawContext * ctx, GEntity * e, std::vector< T * > & elements) static
Definition at line 200 of file drawMesh.cpp.
Referenced by drawMeshGEdge::operator()(), drawMeshGFace::operator()(), and drawMeshGRegion::operator()().
drawVerticesPerEntity()
static void drawVerticesPerEntity (drawContext * ctx, GEntity * e) static
Definition at line 146 of file drawMesh.cpp.
Referenced by drawMeshGVertex::operator()(), drawMeshGEdge::operator()(), drawMeshGFace::operator()(), and drawMeshGRegion::operator()().
drawVoronoiDual()
template<class T > static void drawVoronoiDual (std::vector< T * > & elements) static
Definition at line 280 of file drawMesh.cpp.
Referenced by drawMeshGFace::operator()(), and drawMeshGRegion::operator()().
endFakeTransparency()
static void endFakeTransparency () static
Definition at line 671 of file drawMesh.cpp.
Referenced by drawContext::drawMesh().
getColorByEntity()
unsigned int getColorByEntity (GEntity * e)
Definition at line 25 of file GModelVertexArrays.cpp.
Referenced by drawArrays(), drawElementLabels(), drawVertexLabel(), drawVerticesPerElement(), drawVerticesPerEntity(), and getColorByElement().
isElementVisible()
bool isElementVisible (MElement * ele)
Definition at line 101 of file GModelVertexArrays.cpp.
Referenced by addElementsInArrays(), areAllElementsVisible(), drawBarycentricDual(), drawElementLabels(), drawGlyphs(), drawNormals(), drawTangents(), drawVerticesPerElement(), and drawVoronoiDual().