gmsh-TingyuanDoc: src/graphics/drawContext.cpp File Reference
drawContext.cpp File Reference
#include <string>
#include <stdio.h>
#include "GmshGlobal.h"
#include "GmshConfig.h"
#include "GmshMessage.h"
#include "drawContext.h"
#include "Trackball.h"
#include "Context.h"
#include "Numeric.h"
#include "GModel.h"
#include "MElement.h"
#include "PView.h"
#include "PViewOptions.h"
#include "VertexArray.h"
#include "StringUtils.h"
#include "OS.h"
#include "gl2ps.h"
Classes
class hit
class hitDepthLessThan
Functions
SPoint2 getGraph2dDataPointForTag (unsigned int)
static int needPolygonOffset ()
static MElement * getElement (GEntity *e, int va_type, int index)
Function Documentation
getElement()
static MElement* getElement (GEntity * e, int va_type, int index) static
Definition at line 902 of file drawContext.cpp.
Referenced by drawContext::select().
getGraph2dDataPointForTag()
SPoint2 getGraph2dDataPointForTag (unsigned int)
Definition at line 413 of file drawGraph2d.cpp.
Referenced by drawContext::select().
needPolygonOffset()
static int needPolygonOffset () static
Definition at line 260 of file drawContext.cpp.
Referenced by drawContext::draw3d().