gmsh-TingyuanDoc: src/graphics/drawPost.cpp File Reference
drawPost.cpp File Reference
#include <cmath>
#include <algorithm>
#include "GmshConfig.h"
#include "GmshDefines.h"
#include "GmshMessage.h"
#include "drawContext.h"
#include "PView.h"
#include "PViewOptions.h"
#include "PViewData.h"
#include "Plugin.h"
#include "Numeric.h"
#include "VertexArray.h"
#include "Context.h"
#include "gl2ps.h"
Classes
class drawPView
class drawPViewBoundingBox
Functions
static void drawArrays (drawContext *ctx, PView *p, VertexArray *va, GLint type, bool useNormalArray)
static void drawEllipseArray (drawContext *ctx, PView *p, VertexArray *va)
static void drawVectorArray (drawContext *ctx, PView *p, VertexArray *va)
static std::string stringValue (int numComp, double d[9], double norm, const char *format)
static void drawNumberGlyphs (drawContext *ctx, PView *p, int numNodes, int numComp, double **xyz, double **val)
static void drawNormalVectorGlyphs (drawContext *ctx, PView *p, int numNodes, double **xyz, double **val)
static void drawTangentVectorGlyphs (drawContext *ctx, PView *p, int numNodes, double **xyz, double **val)
static void drawGlyphs (drawContext *ctx, PView *p)
static bool eyeChanged (drawContext *ctx, PView *p)
Function Documentation
drawArrays()
static void drawArrays (drawContext * ctx, PView * p, VertexArray * va, GLint type, bool useNormalArray) static
Definition at line 26 of file drawPost.cpp.
Referenced by drawPView::operator()().
drawEllipseArray()
static void drawEllipseArray (drawContext * ctx, PView * p, VertexArray * va) static
Definition at line 141 of file drawPost.cpp.
Referenced by drawPView::operator()().
drawGlyphs()
static void drawGlyphs (drawContext * ctx, PView * p) static
Definition at line 330 of file drawPost.cpp.
Referenced by drawPView::operator()().
drawNormalVectorGlyphs()
static void drawNormalVectorGlyphs (drawContext * ctx, PView * p, int numNodes, double ** xyz, double ** val) static
Definition at line 289 of file drawPost.cpp.
Referenced by drawGlyphs().
drawNumberGlyphs()
static void drawNumberGlyphs (drawContext * ctx, PView * p, int numNodes, int numComp, double ** xyz, double ** val) static
Definition at line 236 of file drawPost.cpp.
Referenced by drawGlyphs().
drawTangentVectorGlyphs()
static void drawTangentVectorGlyphs (drawContext * ctx, PView * p, int numNodes, double ** xyz, double ** val) static
Definition at line 313 of file drawPost.cpp.
Referenced by drawGlyphs().
drawVectorArray()
static void drawVectorArray (drawContext * ctx, PView * p, VertexArray * va) static
Definition at line 168 of file drawPost.cpp.
Referenced by drawPView::operator()().
eyeChanged()
static bool eyeChanged (drawContext * ctx, PView * p) static
Definition at line 436 of file drawPost.cpp.
Referenced by drawPView::operator()().
stringValue()
static std::string stringValue (int numComp, double d[9], double norm, const char * format) static
Definition at line 218 of file drawPost.cpp.
Referenced by drawNumberGlyphs().