gmsh-TingyuanDoc: src/graphics/drawGeom.cpp File Reference
drawGeom.cpp File Reference
#include <string.h>
#include "drawContext.h"
#include "Context.h"
#include "gl2ps.h"
#include "VertexArray.h"
#include "GModel.h"
#include "SBoundingBox3d.h"
#include "GmshMessage.h"
#include "StringUtils.h"
Classes
class drawGVertex
class drawGEdge
class drawGFace
class drawGRegion
Functions
static void drawEntityLabel (drawContext *ctx, GEntity *e, double x, double y, double z, double offset)
Function Documentation
drawEntityLabel()
static void drawEntityLabel (drawContext * ctx, GEntity * e, double x, double y, double z, double offset) static
Definition at line 16 of file drawGeom.cpp.
Referenced by drawGVertex::operator()(), drawGEdge::operator()(), drawGFace::operator()(), and drawGRegion::operator()().