gmsh-TingyuanDoc: src/graphics/drawScales.cpp File Reference
drawScales.cpp File Reference
#include <algorithm>
#include "drawContext.h"
#include "PView.h"
#include "PViewOptions.h"
#include "PViewData.h"
#include "Context.h"
#include "gl2ps.h"
Functions
static void drawScaleBar (PView *p, double xmin, double ymin, double width, double height, double tic, int horizontal)
static void drawScaleValues (drawContext *ctx, PView *p, double xmin, double ymin, double width, double height, double tic, int horizontal)
static void drawScaleLabel (drawContext *ctx, PView *p, double xmin, double ymin, double width, double height, double tic, int horizontal)
static void drawScale (drawContext *ctx, PView *p, double xmin, double ymin, double width, double height, double tic, int horizontal)
Function Documentation
drawScale()
static void drawScale (drawContext * ctx, PView * p, double xmin, double ymin, double width, double height, double tic, int horizontal) static
Definition at line 243 of file drawScales.cpp.
Referenced by drawContext::drawScales().
drawScaleBar()
static void drawScaleBar (PView * p, double xmin, double ymin, double width, double height, double tic, int horizontal) static
Definition at line 14 of file drawScales.cpp.
Referenced by drawScale().
drawScaleLabel()
static void drawScaleLabel (drawContext * ctx, PView * p, double xmin, double ymin, double width, double height, double tic, int horizontal) static
Definition at line 164 of file drawScales.cpp.
Referenced by drawScale().
drawScaleValues()
static void drawScaleValues (drawContext * ctx, PView * p, double xmin, double ymin, double width, double height, double tic, int horizontal) static
Definition at line 85 of file drawScales.cpp.
Referenced by drawScale().