gmsh-TingyuanDoc: src/geo/findLinks.cpp File Reference
findLinks.cpp File Reference
#include <stdlib.h>
#include "GmshMessage.h"
#include "MallocUtils.h"
#include "GModel.h"
#include "TreeUtils.h"
#include "ListUtils.h"
Classes
struct nxa
struct lnk
Functions
static void freeLink (void *link)
static int complink (const void *a, const void *b)
static void recurFindLinkedEdges (int ed, List_T *edges, Tree_T *points, Tree_T *links)
static int createEdgeLinks (Tree_T *links)
static void orientAndSortEdges (List_T *edges, Tree_T *links)
int allEdgesLinked (int ed, List_T *edges)
static void recurFindLinkedFaces (int fac, List_T *faces, Tree_T *edges, Tree_T *links)
static void createFaceLinks (Tree_T *links)
int allFacesLinked (int fac, List_T *faces)
Function Documentation
allEdgesLinked()
int allEdgesLinked (int ed, List_T * edges)
Definition at line 163 of file findLinks.cpp.
allFacesLinked()
int allFacesLinked (int fac, List_T * faces)
Definition at line 285 of file findLinks.cpp.
complink()
static int complink (const void * a, const void * b) static
Definition at line 28 of file findLinks.cpp.
Referenced by allEdgesLinked(), and allFacesLinked().
createEdgeLinks()
static int createEdgeLinks (Tree_T * links) static
Definition at line 76 of file findLinks.cpp.
Referenced by allEdgesLinked().
createFaceLinks()
static void createFaceLinks (Tree_T * links) static
Definition at line 260 of file findLinks.cpp.
Referenced by allFacesLinked().
freeLink()
static void freeLink (void * link) static
Definition at line 22 of file findLinks.cpp.
Referenced by allEdgesLinked(), and allFacesLinked().
orientAndSortEdges()
static void orientAndSortEdges (List_T * edges, Tree_T * links) static
Definition at line 106 of file findLinks.cpp.
Referenced by allEdgesLinked().
recurFindLinkedEdges()
static void recurFindLinkedEdges (int ed, List_T * edges, Tree_T * points, Tree_T * links) static
Definition at line 39 of file findLinks.cpp.
Referenced by allEdgesLinked().
recurFindLinkedFaces()
static void recurFindLinkedFaces (int fac, List_T * faces, Tree_T * edges, Tree_T * links) static
Definition at line 225 of file findLinks.cpp.
Referenced by allFacesLinked().