gmsh-TingyuanDoc: src/graphics/gl2pgf.cpp File Reference
gl2pgf.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include "GmshConfig.h"
#include "PixelBuffer.h"
#include "OS.h"
#include "Context.h"
#include "PView.h"
#include "PViewData.h"
#include "Numeric.h"
#include "Options.h"
#include "StringUtils.h"
#include "gl2png.h"
Functions
static int assembleColmapStr (const int num, const int intType, int &samples, std::string &ret)
static int assembleColbarStr (const int num, const int intType, const int samples, std::string &ret)
static int assemblePostAxis (const int num, const int intType, std::string &ret)
static int getMinMaxOfAxis (const int num, double result[8][3])
static int assemble2d (const int num, const int exportAxis, std::string &axisstr, std::string &plotstr, double *eulerAngles)
static int assemble3d (const int num, const int exportAxis, std::string &axisstr, std::string &plotstr, double *eulerAngles, int *viewport, double *proj, double *model, int ypix, int xpix)
int print_pgf (const std::string &name, const int num, const int cnt, PixelBuffer *buffer, double *eulerAngles, int *viewport, double *proj, double *model)
Function Documentation
assemble2d()
static int assemble2d (const int num, const int exportAxis, std::string & axisstr, std::string & plotstr, double * eulerAngles) static
Definition at line 224 of file gl2pgf.cpp.
Referenced by assemble3d(), and print_pgf().
assemble3d()
static int assemble3d (const int num, const int exportAxis, std::string & axisstr, std::string & plotstr, double * eulerAngles, int * viewport, double * proj, double * model, int ypix, int xpix) static
Definition at line 398 of file gl2pgf.cpp.
Referenced by print_pgf().
assembleColbarStr()
static int assembleColbarStr (const int num, const int intType, const int samples, std::string & ret) static
Definition at line 79 of file gl2pgf.cpp.
Referenced by print_pgf().
assembleColmapStr()
static int assembleColmapStr (const int num, const int intType, int & samples, std::string & ret) static
Definition at line 21 of file gl2pgf.cpp.
Referenced by print_pgf().
assemblePostAxis()
static int assemblePostAxis (const int num, const int intType, std::string & ret) static
Definition at line 137 of file gl2pgf.cpp.
Referenced by print_pgf().
getMinMaxOfAxis()
static int getMinMaxOfAxis (const int num, double result[8][3]) static
Definition at line 164 of file gl2pgf.cpp.
Referenced by assemble2d(), and assemble3d().
print_pgf()
int print_pgf (const std::string & name, const int num, const int cnt, PixelBuffer * buffer, double * eulerAngles, int * viewport, double * proj, double * model)
Definition at line 567 of file gl2pgf.cpp.
Referenced by CreateOutputFile().