gmsh-TingyuanDoc: src/graphics/gl2ps.cpp File Reference
gl2ps.cpp File Reference
#include "gl2ps.h"
#include <math.h>
#include <string.h>
#include <sys/types.h>
#include <stdarg.h>
#include <time.h>
#include <float.h>
Classes
struct GL2PSbsptree2d_
struct GL2PSlist
struct GL2PSbsptree_
struct GL2PStriangle
struct GL2PSstring
struct GL2PSimage
struct GL2PSimagemap_
struct GL2PSprimitive
struct GL2PScompress
struct GL2PSpdfgroup
struct GL2PScontext
struct GL2PSbackend
Macros
#define GL2PS_EPSILON 5.0e-3F
#define GL2PS_ZSCALE 1000.0F
#define GL2PS_ZOFFSET 5.0e-2F
#define GL2PS_ZOFFSET_LARGE 20.0F
#define GL2PS_ZERO(arg) (fabs(arg) < 1.e-20)
#define GL2PS_COINCIDENT 1
#define GL2PS_IN_FRONT_OF 2
#define GL2PS_IN_BACK_OF 3
#define GL2PS_SPANNING 4
#define GL2PS_POINT_COINCIDENT 0
#define GL2PS_POINT_INFRONT 1
#define GL2PS_POINT_BACK 2
#define GL2PS_BEGIN_OFFSET_TOKEN 1
#define GL2PS_END_OFFSET_TOKEN 2
#define GL2PS_BEGIN_BOUNDARY_TOKEN 3
#define GL2PS_END_BOUNDARY_TOKEN 4
#define GL2PS_BEGIN_STIPPLE_TOKEN 5
#define GL2PS_END_STIPPLE_TOKEN 6
#define GL2PS_POINT_SIZE_TOKEN 7
#define GL2PS_LINE_CAP_TOKEN 8
#define GL2PS_LINE_JOIN_TOKEN 9
#define GL2PS_LINE_WIDTH_TOKEN 10
#define GL2PS_BEGIN_BLEND_TOKEN 11
#define GL2PS_END_BLEND_TOKEN 12
#define GL2PS_SRC_BLEND_TOKEN 13
#define GL2PS_DST_BLEND_TOKEN 14
#define GL2PS_IMAGEMAP_TOKEN 15
#define GL2PS_DRAW_PIXELS_TOKEN 16
#define GL2PS_TEXT_TOKEN 17
Typedefs
typedef GLfloat GL2PSplane[4]
typedef struct GL2PSbsptree2d_ GL2PSbsptree2d
typedef struct GL2PSbsptree_ GL2PSbsptree
typedef struct GL2PSimagemap_ GL2PSimagemap
Enumerations
enum GL2PS_TRIANGLE_PROPERTY {
T_UNDEFINED = -1, T_CONST_COLOR = 1, T_VAR_COLOR = 1<<1, T_ALPHA_1 = 1<<2,
T_ALPHA_LESS_1 = 1<<3, T_VAR_ALPHA = 1<<4
}
Functions
static GLint gl2psPrintPrimitives (void)
static void gl2psMsg (GLint level, const char *fmt,...)
static void * gl2psMalloc (size_t size)
static void * gl2psRealloc (void *ptr, size_t size)
static void gl2psFree (void *ptr)
static int gl2psWriteBigEndian (unsigned long data, int bytes)
static int gl2psPrintf (const char *fmt,...)
static void gl2psPrintGzipHeader (void)
static void gl2psPrintGzipFooter (void)
static void gl2psListRealloc (GL2PSlist *list, GLint n)
static GL2PSlist * gl2psListCreate (GLint n, GLint incr, GLint size)
static void gl2psListReset (GL2PSlist *list)
static void gl2psListDelete (GL2PSlist *list)
static void gl2psListAdd (GL2PSlist *list, void *data)
static int gl2psListNbr (GL2PSlist *list)
static void * gl2psListPointer (GL2PSlist *list, GLint idx)
static void gl2psListSort (GL2PSlist *list, int(*fcmp)(const void *a, const void *b))
static void gl2psListAssignSortIds (GL2PSlist *list)
static void gl2psListAction (GL2PSlist *list, void(*action)(void *data))
static void gl2psListActionInverse (GL2PSlist *list, void(*action)(void *data))
static GLboolean gl2psSameColor (GL2PSrgba rgba1, GL2PSrgba rgba2)
static GLboolean gl2psVertsSameColor (const GL2PSprimitive *prim)
static GLboolean gl2psSameColorThreshold (int n, GL2PSrgba rgba[], GL2PSrgba threshold)
static void gl2psSetLastColor (GL2PSrgba rgba)
static GLfloat gl2psGetRGB (GL2PSimage *im, GLuint x, GLuint y, GLfloat *red, GLfloat *green, GLfloat *blue)
static GL2PSimage * gl2psCopyPixmap (GL2PSimage *im)
static void gl2psFreePixmap (GL2PSimage *im)
static GLint gl2psAddText (GLint type, const char *str, const char *fontname, GLshort fontsize, GLint alignment, GLfloat angle, GL2PSrgba color, GLboolean setblpos, GLfloat blx, GLfloat bly)
static GL2PSstring * gl2psCopyText (GL2PSstring *t)
static void gl2psFreeText (GL2PSstring *text)
static GLboolean gl2psSupportedBlendMode (GLenum sfactor, GLenum dfactor)
static void gl2psAdaptVertexForBlending (GL2PSvertex *v)
static void gl2psAssignTriangleProperties (GL2PStriangle *t)
static void gl2psFillTriangleFromPrimitive (GL2PStriangle *t, GL2PSprimitive *p, GLboolean assignprops)
static void gl2psInitTriangle (GL2PStriangle *t)
static void gl2psResetLineProperties (void)
static GL2PSprimitive * gl2psCopyPrimitive (GL2PSprimitive *p)
static GLboolean gl2psSamePosition (GL2PSxyz p1, GL2PSxyz p2)
static GLfloat gl2psComparePointPlane (GL2PSxyz point, GL2PSplane plane)
static GLfloat gl2psPsca (GLfloat *a, GLfloat *b)
static void gl2psPvec (GLfloat *a, GLfloat *b, GLfloat *c)
static GLfloat gl2psNorm (GLfloat *a)
static void gl2psGetNormal (GLfloat *a, GLfloat *b, GLfloat *c)
static void gl2psGetPlane (GL2PSprimitive *prim, GL2PSplane plane)
static void gl2psCutEdge (GL2PSvertex *a, GL2PSvertex *b, GL2PSplane plane, GL2PSvertex *c)
static void gl2psCreateSplitPrimitive (GL2PSprimitive *parent, GL2PSplane plane, GL2PSprimitive *child, GLshort numverts, GLshort *index0, GLshort *index1)
static void gl2psAddIndex (GLshort *index0, GLshort *index1, GLshort *nb, GLshort i, GLshort j)
static GLshort gl2psGetIndex (GLshort i, GLshort num)
static GLint gl2psTestSplitPrimitive (GL2PSprimitive *prim, GL2PSplane plane)
static GLint gl2psSplitPrimitive (GL2PSprimitive *prim, GL2PSplane plane, GL2PSprimitive **front, GL2PSprimitive **back)
static void gl2psDivideQuad (GL2PSprimitive *quad, GL2PSprimitive **t1, GL2PSprimitive **t2)
static int gl2psCompareDepth (const void *a, const void *b)
static int gl2psTrianglesFirst (const void *a, const void *b)
static GLint gl2psFindRoot (GL2PSlist *primitives, GL2PSprimitive **root)
static void gl2psFreeImagemap (GL2PSimagemap *list)
static void gl2psFreePrimitive (void *data)
static void gl2psAddPrimitiveInList (GL2PSprimitive *prim, GL2PSlist *list)
static void gl2psFreeBspTree (GL2PSbsptree **tree)
static GLboolean gl2psGreater (GLfloat f1, GLfloat f2)
static GLboolean gl2psLess (GLfloat f1, GLfloat f2)
static void gl2psBuildBspTree (GL2PSbsptree *tree, GL2PSlist *primitives)
static void gl2psTraverseBspTree (GL2PSbsptree *tree, GL2PSxyz eye, GLfloat epsilon, GLboolean(*compare)(GLfloat f1, GLfloat f2), void(*action)(void *data), int inverse)
static void gl2psRescaleAndOffset (void)
static GLint gl2psGetPlaneFromPoints (GL2PSxyz a, GL2PSxyz b, GL2PSplane plane)
static void gl2psFreeBspImageTree (GL2PSbsptree2d **tree)
static GLint gl2psCheckPoint (GL2PSxyz point, GL2PSplane plane)
static void gl2psAddPlanesInBspTreeImage (GL2PSprimitive *prim, GL2PSbsptree2d **tree)
static GLint gl2psCheckPrimitive (GL2PSprimitive *prim, GL2PSplane plane)
static GL2PSprimitive * gl2psCreateSplitPrimitive2D (GL2PSprimitive *parent, GLshort numverts, GL2PSvertex *vertx)
static void gl2psSplitPrimitive2D (GL2PSprimitive *prim, GL2PSplane plane, GL2PSprimitive **front, GL2PSprimitive **back)
static GLint gl2psAddInBspImageTree (GL2PSprimitive *prim, GL2PSbsptree2d **tree)
static void gl2psAddInImageTree (void *data)
static void gl2psAddBoundaryInList (GL2PSprimitive *prim, GL2PSlist *list)
static void gl2psBuildPolygonBoundary (GL2PSbsptree *tree)
GL2PSDLL_API void gl2psAddPolyPrimitive (GLshort type, GLshort numverts, GL2PSvertex *verts, GLint offset, GLfloat ofactor, GLfloat ounits, GLushort pattern, GLint factor, GLfloat width, GLint linecap, GLint linejoin, char boundary)
static GLint gl2psGetVertex (GL2PSvertex *v, GLfloat *p)
static void gl2psParseFeedbackBuffer (GLint used)
static void gl2psWriteByte (unsigned char byte)
static void gl2psPrintPostScriptPixmap (GLfloat x, GLfloat y, GL2PSimage *im)
static void gl2psPrintPostScriptImagemap (GLfloat x, GLfloat y, GLsizei width, GLsizei height, const unsigned char *imagemap)
static void gl2psPrintPostScriptHeader (void)
static void gl2psPrintPostScriptColor (GL2PSrgba rgba)
static void gl2psResetPostScriptColor (void)
static void gl2psEndPostScriptLine (void)
static void gl2psParseStipplePattern (GLushort pattern, GLint factor, int *nb, int array[10])
static int gl2psPrintPostScriptDash (GLushort pattern, GLint factor, const char *str)
static void gl2psPrintPostScriptPrimitive (void *data)
static void gl2psPrintPostScriptFooter (void)
static void gl2psPrintPostScriptBeginViewport (GLint viewport[4])
static GLint gl2psPrintPostScriptEndViewport (void)
static void gl2psPrintPostScriptFinalPrimitive (void)
static void gl2psPrintTeXHeader (void)
static void gl2psPrintTeXPrimitive (void *data)
static void gl2psPrintTeXFooter (void)
static void gl2psPrintTeXBeginViewport (GLint viewport[4])
static GLint gl2psPrintTeXEndViewport (void)
static void gl2psPrintTeXFinalPrimitive (void)
static int gl2psPrintPDFCompressorType (void)
static int gl2psPrintPDFStrokeColor (GL2PSrgba rgba)
static int gl2psPrintPDFFillColor (GL2PSrgba rgba)
static int gl2psPrintPDFLineWidth (GLfloat lw)
static int gl2psPrintPDFLineCap (GLint lc)
static int gl2psPrintPDFLineJoin (GLint lj)
static void gl2psPutPDFText (GL2PSstring *text, int cnt, GLfloat x, GLfloat y)
static void gl2psPutPDFTextBL (GL2PSstring *text, int cnt, GLfloat x, GLfloat y, GLfloat xbl, GLfloat ybl)
static void gl2psPutPDFSpecial (int prim, int sec, GL2PSstring *text)
static void gl2psPutPDFImage (GL2PSimage *image, int cnt, GLfloat x, GLfloat y)
static void gl2psPDFstacksInit (void)
static void gl2psPDFgroupObjectInit (GL2PSpdfgroup *gro)
static void gl2psPDFgroupListInit (void)
static void gl2psSortOutTrianglePDFgroup (GL2PSpdfgroup *gro)
static void gl2psPDFgroupListWriteMainStream (void)
static int gl2psPDFgroupListWriteGStateResources (void)
static int gl2psPDFgroupListWriteShaderResources (void)
static int gl2psPDFgroupListWriteXObjectResources (void)
static int gl2psPDFgroupListWriteFontResources (void)
static void gl2psPDFgroupListDelete (void)
static int gl2psPrintPDFInfo (void)
static int gl2psPrintPDFCatalog (void)
static int gl2psPrintPDFPages (void)
static int gl2psOpenPDFDataStream (void)
static int gl2psOpenPDFDataStreamWritePreface (void)
static void gl2psPrintPDFHeader (void)
static void gl2psPrintPDFPrimitive (void *data)
static int gl2psClosePDFDataStream (void)
static int gl2psPrintPDFDataStreamLength (int val)
static int gl2psPrintPDFOpenPage (void)
static int gl2psPDFgroupListWriteVariableResources (void)
static int gl2psPrintPDFGSObject (void)
static int gl2psPrintPDFShaderStreamDataCoord (GL2PSvertex *vertex, int(*action)(unsigned long data, int size), GLfloat dx, GLfloat dy, GLfloat xmin, GLfloat ymin)
static int gl2psPrintPDFShaderStreamDataRGB (GL2PSvertex *vertex, int(*action)(unsigned long data, int size))
static int gl2psPrintPDFShaderStreamDataAlpha (GL2PSvertex *vertex, int(*action)(unsigned long data, int size), int sigbyte)
static int gl2psPrintPDFShaderStreamData (GL2PStriangle *triangle, GLfloat dx, GLfloat dy, GLfloat xmin, GLfloat ymin, int(*action)(unsigned long data, int size), int gray)
static void gl2psPDFRectHull (GLfloat *xmin, GLfloat *xmax, GLfloat *ymin, GLfloat *ymax, GL2PStriangle *triangles, int cnt)
static int gl2psPrintPDFShader (int obj, GL2PStriangle *triangles, int size, int gray)
static int gl2psPrintPDFShaderMask (int obj, int childobj)
static int gl2psPrintPDFShaderExtGS (int obj, int childobj)
static int gl2psPrintPDFShaderSimpleExtGS (int obj, GLfloat alpha)
static int gl2psPrintPDFPixmapStreamData (GL2PSimage *im, int(*action)(unsigned long data, int size), int gray)
static int gl2psPrintPDFPixmap (int obj, int childobj, GL2PSimage *im, int gray)
static int gl2psPrintPDFText (int obj, GL2PSstring *s, int fontnumber)
static int gl2psPDFgroupListWriteObjects (int entryoffs)
static void gl2psPrintPDFFooter (void)
static void gl2psPrintPDFBeginViewport (GLint viewport[4])
static GLint gl2psPrintPDFEndViewport (void)
static void gl2psPrintPDFFinalPrimitive (void)
static void gl2psSVGGetCoordsAndColors (int n, GL2PSvertex *verts, GL2PSxyz *xyz, GL2PSrgba *rgba)
static void gl2psSVGGetColorString (GL2PSrgba rgba, char str[32])
static void gl2psPrintSVGHeader (void)
static void gl2psPrintSVGSmoothTriangle (GL2PSxyz xyz[3], GL2PSrgba rgba[3])
static void gl2psPrintSVGDash (GLushort pattern, GLint factor)
static void gl2psEndSVGLine (void)
static void gl2psPrintSVGPixmap (GLfloat x, GLfloat y, GL2PSimage *pixmap)
static void gl2psPrintSVGPrimitive (void *data)
static void gl2psPrintSVGFooter (void)
static void gl2psPrintSVGBeginViewport (GLint viewport[4])
static GLint gl2psPrintSVGEndViewport (void)
static void gl2psPrintSVGFinalPrimitive (void)
static void gl2psPrintPGFColor (GL2PSrgba rgba)
static void gl2psPrintPGFHeader (void)
static void gl2psPrintPGFDash (GLushort pattern, GLint factor)
static const char * gl2psPGFTextAlignment (int align)
static void gl2psPrintPGFPrimitive (void *data)
static void gl2psPrintPGFFooter (void)
static void gl2psPrintPGFBeginViewport (GLint viewport[4])
static GLint gl2psPrintPGFEndViewport (void)
static void gl2psPrintPGFFinalPrimitive (void)
static void gl2psComputeTightBoundingBox (void *data)
static GLboolean gl2psCheckOptions (GLint options, GLint colormode)
GL2PSDLL_API GLint gl2psBeginPage (const char *title, const char *producer, GLint viewport[4], GLint format, GLint sort, GLint options, GLint colormode, GLint colorsize, GL2PSrgba *colormap, GLint nr, GLint ng, GLint nb, GLint buffersize, FILE *stream, const char *filename)
GL2PSDLL_API GLint gl2psEndPage (void)
GL2PSDLL_API GLint gl2psBeginViewport (GLint viewport[4])
GL2PSDLL_API GLint gl2psEndViewport (void)
GL2PSDLL_API GLint gl2psSorting (GLint mode)
GL2PSDLL_API GLint gl2psTextOptColor (const char *str, const char *fontname, GLshort fontsize, GLint alignment, GLfloat angle, GL2PSrgba color)
GL2PSDLL_API GLint gl2psTextOptColorBL (const char *str, const char *fontname, GLshort fontsize, GLint alignment, GLfloat angle, GL2PSrgba color, GLfloat blx, GLfloat bly)
GL2PSDLL_API GLint gl2psTextOpt (const char *str, const char *fontname, GLshort fontsize, GLint alignment, GLfloat angle)
GL2PSDLL_API GLint gl2psText (const char *str, const char *fontname, GLshort fontsize)
GL2PSDLL_API GLint gl2psSpecial (GLint format, const char *str)
GL2PSDLL_API GLint gl2psSpecialColor (GLint format, const char *str, GL2PSrgba rgba)
GL2PSDLL_API GLint gl2psDrawPixels (GLsizei width, GLsizei height, GLint xorig, GLint yorig, GLenum format, GLenum type, const void *pixels)
GL2PSDLL_API GLint gl2psDrawImageMap (GLsizei width, GLsizei height, const GLfloat position[3], const unsigned char *imagemap)
GL2PSDLL_API GLint gl2psEnable (GLint mode)
GL2PSDLL_API GLint gl2psDisable (GLint mode)
GL2PSDLL_API GLint gl2psPointSize (GLfloat value)
GL2PSDLL_API GLint gl2psLineCap (GLint value)
GL2PSDLL_API GLint gl2psLineJoin (GLint value)
GL2PSDLL_API GLint gl2psLineWidth (GLfloat value)
GL2PSDLL_API GLint gl2psBlendFunc (GLenum sfactor, GLenum dfactor)
GL2PSDLL_API GLint gl2psSetOptions (GLint options)
GL2PSDLL_API GLint gl2psGetOptions (GLint *options)
GL2PSDLL_API const char * gl2psGetFileExtension (GLint format)
GL2PSDLL_API const char * gl2psGetFormatDescription (GLint format)
GL2PSDLL_API GLint gl2psGetFileFormat ()
GL2PSDLL_API GLint gl2psForceRasterPos (GL2PSvertex *vert)
GL2PSDLL_API GLint gl2psSetTexScaling (GLfloat scaling)
Variables
static GL2PScontext * gl2ps = NULL
static GL2PSbackend gl2psPS
static GL2PSbackend gl2psEPS
static GL2PSbackend gl2psTEX
static GL2PSbackend gl2psPDF
static GL2PSbackend gl2psSVG
static GL2PSbackend gl2psPGF
static GL2PSbackend * gl2psbackends []
Macro Definition Documentation
GL2PS_BEGIN_BLEND_TOKEN
#define GL2PS_BEGIN_BLEND_TOKEN 11
Definition at line 92 of file gl2ps.cpp.
GL2PS_BEGIN_BOUNDARY_TOKEN
#define GL2PS_BEGIN_BOUNDARY_TOKEN 3
Definition at line 84 of file gl2ps.cpp.
GL2PS_BEGIN_OFFSET_TOKEN
#define GL2PS_BEGIN_OFFSET_TOKEN 1
Definition at line 82 of file gl2ps.cpp.
GL2PS_BEGIN_STIPPLE_TOKEN
#define GL2PS_BEGIN_STIPPLE_TOKEN 5
Definition at line 86 of file gl2ps.cpp.
GL2PS_COINCIDENT
#define GL2PS_COINCIDENT 1
Definition at line 69 of file gl2ps.cpp.
GL2PS_DRAW_PIXELS_TOKEN
#define GL2PS_DRAW_PIXELS_TOKEN 16
Definition at line 97 of file gl2ps.cpp.
GL2PS_DST_BLEND_TOKEN
#define GL2PS_DST_BLEND_TOKEN 14
Definition at line 95 of file gl2ps.cpp.
GL2PS_END_BLEND_TOKEN
#define GL2PS_END_BLEND_TOKEN 12
Definition at line 93 of file gl2ps.cpp.
GL2PS_END_BOUNDARY_TOKEN
#define GL2PS_END_BOUNDARY_TOKEN 4
Definition at line 85 of file gl2ps.cpp.
GL2PS_END_OFFSET_TOKEN
#define GL2PS_END_OFFSET_TOKEN 2
Definition at line 83 of file gl2ps.cpp.
GL2PS_END_STIPPLE_TOKEN
#define GL2PS_END_STIPPLE_TOKEN 6
Definition at line 87 of file gl2ps.cpp.
GL2PS_EPSILON
#define GL2PS_EPSILON 5.0e-3F
Definition at line 61 of file gl2ps.cpp.
GL2PS_IMAGEMAP_TOKEN
#define GL2PS_IMAGEMAP_TOKEN 15
Definition at line 96 of file gl2ps.cpp.
GL2PS_IN_BACK_OF
#define GL2PS_IN_BACK_OF 3
Definition at line 71 of file gl2ps.cpp.
GL2PS_IN_FRONT_OF
#define GL2PS_IN_FRONT_OF 2
Definition at line 70 of file gl2ps.cpp.
GL2PS_LINE_CAP_TOKEN
#define GL2PS_LINE_CAP_TOKEN 8
Definition at line 89 of file gl2ps.cpp.
GL2PS_LINE_JOIN_TOKEN
#define GL2PS_LINE_JOIN_TOKEN 9
Definition at line 90 of file gl2ps.cpp.
GL2PS_LINE_WIDTH_TOKEN
#define GL2PS_LINE_WIDTH_TOKEN 10
Definition at line 91 of file gl2ps.cpp.
GL2PS_POINT_BACK
#define GL2PS_POINT_BACK 2
Definition at line 78 of file gl2ps.cpp.
GL2PS_POINT_COINCIDENT
#define GL2PS_POINT_COINCIDENT 0
Definition at line 76 of file gl2ps.cpp.
GL2PS_POINT_INFRONT
#define GL2PS_POINT_INFRONT 1
Definition at line 77 of file gl2ps.cpp.
GL2PS_POINT_SIZE_TOKEN
#define GL2PS_POINT_SIZE_TOKEN 7
Definition at line 88 of file gl2ps.cpp.
GL2PS_SPANNING
#define GL2PS_SPANNING 4
Definition at line 72 of file gl2ps.cpp.
GL2PS_SRC_BLEND_TOKEN
#define GL2PS_SRC_BLEND_TOKEN 13
Definition at line 94 of file gl2ps.cpp.
GL2PS_TEXT_TOKEN
#define GL2PS_TEXT_TOKEN 17
Definition at line 98 of file gl2ps.cpp.
GL2PS_ZERO
#define GL2PS_ZERO (arg) (fabs(arg) < 1.e-20)
Definition at line 65 of file gl2ps.cpp.
GL2PS_ZOFFSET
#define GL2PS_ZOFFSET 5.0e-2F
Definition at line 63 of file gl2ps.cpp.
GL2PS_ZOFFSET_LARGE
#define GL2PS_ZOFFSET_LARGE 20.0F
Definition at line 64 of file gl2ps.cpp.
GL2PS_ZSCALE
#define GL2PS_ZSCALE 1000.0F
Definition at line 62 of file gl2ps.cpp.
Typedef Documentation
GL2PSbsptree
typedef struct GL2PSbsptree_ GL2PSbsptree
Definition at line 108 of file gl2ps.cpp.
GL2PSbsptree2d
typedef struct GL2PSbsptree2d_ GL2PSbsptree2d
Definition at line 108 of file gl2ps.cpp.
GL2PSimagemap
typedef struct GL2PSimagemap_ GL2PSimagemap
Definition at line 108 of file gl2ps.cpp.
GL2PSplane
typedef GLfloat GL2PSplane[4]
Definition at line 108 of file gl2ps.cpp.
Enumeration Type Documentation
GL2PS_TRIANGLE_PROPERTY
enum GL2PS_TRIANGLE_PROPERTY
Enumerator
T_UNDEFINED
T_CONST_COLOR
T_VAR_COLOR
T_ALPHA_1
T_ALPHA_LESS_1
T_VAR_ALPHA
Definition at line 99 of file gl2ps.cpp.
Function Documentation
gl2psAdaptVertexForBlending()
static void gl2psAdaptVertexForBlending (GL2PSvertex * v) static
Definition at line 985 of file gl2ps.cpp.
Referenced by gl2psParseFeedbackBuffer().
gl2psAddBoundaryInList()
static void gl2psAddBoundaryInList (GL2PSprimitive * prim, GL2PSlist * list) static
Definition at line 2142 of file gl2ps.cpp.
Referenced by gl2psBuildPolygonBoundary().
gl2psAddInBspImageTree()
static GLint gl2psAddInBspImageTree (GL2PSprimitive * prim, GL2PSbsptree2d ** tree) static
Definition at line 2066 of file gl2ps.cpp.
Referenced by gl2psAddInImageTree().
gl2psAddIndex()
static void gl2psAddIndex (GLshort * index0, GLshort * index1, GLshort * nb, GLshort i, GLshort j) static
Definition at line 1306 of file gl2ps.cpp.
Referenced by gl2psSplitPrimitive().
gl2psAddInImageTree()
static void gl2psAddInImageTree (void * data) static
Definition at line 2125 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psAddPlanesInBspTreeImage()
static void gl2psAddPlanesInBspTreeImage (GL2PSprimitive * prim, GL2PSbsptree2d ** tree) static
Definition at line 1827 of file gl2ps.cpp.
Referenced by gl2psAddInBspImageTree().
gl2psAddPolyPrimitive()
GL2PSDLL_API void gl2psAddPolyPrimitive (GLshort type, GLshort numverts, GL2PSvertex * verts, GLint offset, GLfloat ofactor, GLfloat ounits, GLushort pattern, GLint factor, GLfloat width, GLint linecap, GLint linejoin, char boundary)
Definition at line 2234 of file gl2ps.cpp.
Referenced by gl2psParseFeedbackBuffer().
gl2psAddPrimitiveInList()
static void gl2psAddPrimitiveInList (GL2PSprimitive * prim, GL2PSlist * list) static
Definition at line 1557 of file gl2ps.cpp.
Referenced by gl2psBuildBspTree().
gl2psAddText()
static GLint gl2psAddText (GLint type, const char * str, const char * fontname, GLshort fontsize, GLint alignment, GLfloat angle, GL2PSrgba color, GLboolean setblpos, GLfloat blx, GLfloat bly) static
Definition at line 864 of file gl2ps.cpp.
Referenced by gl2psSpecial(), gl2psSpecialColor(), gl2psText(), gl2psTextOpt(), gl2psTextOptColor(), and gl2psTextOptColorBL().
gl2psAssignTriangleProperties()
static void gl2psAssignTriangleProperties (GL2PStriangle * t) static
Definition at line 1009 of file gl2ps.cpp.
Referenced by gl2psFillTriangleFromPrimitive().
gl2psBeginPage()
GL2PSDLL_API GLint gl2psBeginPage (const char * title, const char * producer, GLint viewport[4], GLint format, GLint sort, GLint options, GLint colormode, GLint colorsize, GL2PSrgba * colormap, GLint nr, GLint ng, GLint nb, GLint buffersize, FILE * stream, const char * filename)
Definition at line 6027 of file gl2ps.cpp.
Referenced by CreateOutputFile().
gl2psBeginViewport()
GL2PSDLL_API GLint gl2psBeginViewport (GLint viewport[4])
Definition at line 6248 of file gl2ps.cpp.
gl2psBlendFunc()
GL2PSDLL_API GLint gl2psBlendFunc (GLenum sfactor, GLenum dfactor)
Definition at line 6577 of file gl2ps.cpp.
gl2psBuildBspTree()
static void gl2psBuildBspTree (GL2PSbsptree * tree, GL2PSlist * primitives) static
Definition at line 1599 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psBuildPolygonBoundary()
static void gl2psBuildPolygonBoundary (GL2PSbsptree * tree) static
Definition at line 2214 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psCheckOptions()
static GLboolean gl2psCheckOptions (GLint options, GLint colormode) static
Definition at line 5993 of file gl2ps.cpp.
Referenced by gl2psBeginPage(), and gl2psSetOptions().
gl2psCheckPoint()
static GLint gl2psCheckPoint (GL2PSxyz point, GL2PSplane plane) static
Definition at line 1817 of file gl2ps.cpp.
Referenced by gl2psAddPlanesInBspTreeImage(), gl2psCheckPrimitive(), and gl2psSplitPrimitive2D().
gl2psCheckPrimitive()
static GLint gl2psCheckPrimitive (GL2PSprimitive * prim, GL2PSplane plane) static
Definition at line 1931 of file gl2ps.cpp.
Referenced by gl2psAddInBspImageTree().
gl2psClosePDFDataStream()
static int gl2psClosePDFDataStream (void) static
Definition at line 4317 of file gl2ps.cpp.
Referenced by gl2psPrintPDFFooter().
gl2psCompareDepth()
static int gl2psCompareDepth (const void * a, const void * b) static
Definition at line 1444 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psComparePointPlane()
static GLfloat gl2psComparePointPlane (GL2PSxyz point, GL2PSplane plane) static
Definition at line 1125 of file gl2ps.cpp.
Referenced by gl2psCheckPoint(), gl2psCutEdge(), gl2psSplitPrimitive(), gl2psTestSplitPrimitive(), and gl2psTraverseBspTree().
gl2psComputeTightBoundingBox()
static void gl2psComputeTightBoundingBox (void * data) static
Definition at line 5897 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psCopyPixmap()
static GL2PSimage* gl2psCopyPixmap (GL2PSimage * im) static
Definition at line 761 of file gl2ps.cpp.
Referenced by gl2psCopyPrimitive().
gl2psCopyPrimitive()
static GL2PSprimitive* gl2psCopyPrimitive (GL2PSprimitive * p) static
Definition at line 1069 of file gl2ps.cpp.
Referenced by gl2psPrintPDFPrimitive().
gl2psCopyText()
static GL2PSstring* gl2psCopyText (GL2PSstring * t) static
Definition at line 949 of file gl2ps.cpp.
Referenced by gl2psCopyPrimitive().
gl2psCreateSplitPrimitive()
static void gl2psCreateSplitPrimitive (GL2PSprimitive * parent, GL2PSplane plane, GL2PSprimitive * child, GLshort numverts, GLshort * index0, GLshort * index1) static
Definition at line 1258 of file gl2ps.cpp.
Referenced by gl2psSplitPrimitive().
gl2psCreateSplitPrimitive2D()
static GL2PSprimitive* gl2psCreateSplitPrimitive2D (GL2PSprimitive * parent, GLshort numverts, GL2PSvertex * vertx) static
Definition at line 1946 of file gl2ps.cpp.
Referenced by gl2psSplitPrimitive2D().
gl2psCutEdge()
static void gl2psCutEdge (GL2PSvertex * a, GL2PSvertex * b, GL2PSplane plane, GL2PSvertex * c) static
Definition at line 1233 of file gl2ps.cpp.
Referenced by gl2psCreateSplitPrimitive(), and gl2psSplitPrimitive2D().
gl2psDisable()
GL2PSDLL_API GLint gl2psDisable (GLint mode)
Definition at line 6512 of file gl2ps.cpp.
Referenced by drawArrays(), drawBarycentricDual(), drawGraphAxes(), drawGraphCurves(), drawGridStipple(), drawVoronoiDual(), and drawGFace::operator()().
gl2psDivideQuad()
static void gl2psDivideQuad (GL2PSprimitive * quad, GL2PSprimitive ** t1, GL2PSprimitive ** t2) static
Definition at line 1416 of file gl2ps.cpp.
Referenced by gl2psAddPrimitiveInList().
gl2psDrawImageMap()
GL2PSDLL_API GLint gl2psDrawImageMap (GLsizei width, GLsizei height, const GLfloat position[3], const unsigned char * imagemap)
Definition at line 6451 of file gl2ps.cpp.
gl2psDrawPixels()
GL2PSDLL_API GLint gl2psDrawPixels (GLsizei width, GLsizei height, GLint xorig, GLint yorig, GLenum format, GLenum type, const void * pixels)
Definition at line 6337 of file gl2ps.cpp.
Referenced by CreateOutputFile().
gl2psEnable()
GL2PSDLL_API GLint gl2psEnable (GLint mode)
Definition at line 6476 of file gl2ps.cpp.
Referenced by drawArrays(), drawBarycentricDual(), drawGraphAxes(), drawGraphCurves(), drawGridStipple(), drawVoronoiDual(), and drawGFace::operator()().
gl2psEndPage()
GL2PSDLL_API GLint gl2psEndPage (void)
Definition at line 6221 of file gl2ps.cpp.
Referenced by CreateOutputFile().
gl2psEndPostScriptLine()
static void gl2psEndPostScriptLine (void) static
Definition at line 3010 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptFinalPrimitive(), and gl2psPrintPostScriptPrimitive().
gl2psEndSVGLine()
static void gl2psEndSVGLine (void) static
Definition at line 5269 of file gl2ps.cpp.
Referenced by gl2psPrintSVGFinalPrimitive(), and gl2psPrintSVGPrimitive().
gl2psEndViewport()
GL2PSDLL_API GLint gl2psEndViewport (void)
Definition at line 6257 of file gl2ps.cpp.
gl2psFillTriangleFromPrimitive()
static void gl2psFillTriangleFromPrimitive (GL2PStriangle * t, GL2PSprimitive * p, GLboolean assignprops) static
Definition at line 1042 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), and gl2psSortOutTrianglePDFgroup().
gl2psFindRoot()
static GLint gl2psFindRoot (GL2PSlist * primitives, GL2PSprimitive ** root) static
Definition at line 1485 of file gl2ps.cpp.
Referenced by gl2psBuildBspTree().
gl2psForceRasterPos()
GL2PSDLL_API GLint gl2psForceRasterPos (GL2PSvertex * vert)
Definition at line 6642 of file gl2ps.cpp.
gl2psFree()
static void gl2psFree (void * ptr) static
Definition at line 305 of file gl2ps.cpp.
Referenced by gl2psAddInBspImageTree(), gl2psAddPlanesInBspTreeImage(), gl2psBeginPage(), gl2psEndPage(), gl2psFreeBspImageTree(), gl2psFreeBspTree(), gl2psFreeImagemap(), gl2psFreePixmap(), gl2psFreePrimitive(), gl2psFreeText(), gl2psListDelete(), gl2psPDFgroupListWriteObjects(), gl2psPrintf(), gl2psPrintGzipFooter(), gl2psPrintPDFFooter(), gl2psSorting(), and gl2psSplitPrimitive2D().
gl2psFreeBspImageTree()
static void gl2psFreeBspImageTree (GL2PSbsptree2d ** tree) static
Definition at line 1807 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psFreeBspTree()
static void gl2psFreeBspTree (GL2PSbsptree ** tree) static
Definition at line 1573 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psFreeImagemap()
static void gl2psFreeImagemap (GL2PSimagemap * list) static
Definition at line 1530 of file gl2ps.cpp.
Referenced by gl2psEndPage().
gl2psFreePixmap()
static void gl2psFreePixmap (GL2PSimage * im) static
Definition at line 789 of file gl2ps.cpp.
Referenced by gl2psFreePrimitive().
gl2psFreePrimitive()
static void gl2psFreePrimitive (void * data) static
Definition at line 1542 of file gl2ps.cpp.
Referenced by gl2psAddPrimitiveInList(), gl2psBuildBspTree(), gl2psFreeBspTree(), gl2psPrintPDFFooter(), and gl2psPrintPrimitives().
gl2psFreeText()
static void gl2psFreeText (GL2PSstring * text) static
Definition at line 963 of file gl2ps.cpp.
Referenced by gl2psFreePrimitive().
gl2psGetFileExtension()
GL2PSDLL_API const char* gl2psGetFileExtension (GLint format)
Definition at line 6617 of file gl2ps.cpp.
gl2psGetFileFormat()
GL2PSDLL_API GLint gl2psGetFileFormat ()
Definition at line 6633 of file gl2ps.cpp.
gl2psGetFormatDescription()
GL2PSDLL_API const char* gl2psGetFormatDescription (GLint format)
Definition at line 6625 of file gl2ps.cpp.
gl2psGetIndex()
static GLshort gl2psGetIndex (GLshort i, GLshort num) static
Definition at line 1320 of file gl2ps.cpp.
Referenced by gl2psAddBoundaryInList(), gl2psSplitPrimitive(), and gl2psTestSplitPrimitive().
gl2psGetNormal()
static void gl2psGetNormal (GLfloat * a, GLfloat * b, GLfloat * c) static
Definition at line 1150 of file gl2ps.cpp.
Referenced by gl2psGetPlane().
gl2psGetOptions()
GL2PSDLL_API GLint gl2psGetOptions (GLint * options)
Definition at line 6605 of file gl2ps.cpp.
gl2psGetPlane()
static void gl2psGetPlane (GL2PSprimitive * prim, GL2PSplane plane) static
Definition at line 1169 of file gl2ps.cpp.
Referenced by gl2psBuildBspTree(), and gl2psFindRoot().
gl2psGetPlaneFromPoints()
static GLint gl2psGetPlaneFromPoints (GL2PSxyz a, GL2PSxyz b, GL2PSplane plane) static
Definition at line 1785 of file gl2ps.cpp.
Referenced by gl2psAddPlanesInBspTreeImage().
gl2psGetRGB()
static GLfloat gl2psGetRGB (GL2PSimage * im, GLuint x, GLuint y, GLfloat * red, GLfloat * green, GLfloat * blue) static
Definition at line 733 of file gl2ps.cpp.
Referenced by gl2psPrintPDFPixmapStreamData(), and gl2psPrintPostScriptPixmap().
gl2psGetVertex()
static GLint gl2psGetVertex (GL2PSvertex * v, GLfloat * p) static
Definition at line 2265 of file gl2ps.cpp.
Referenced by gl2psParseFeedbackBuffer().
gl2psGreater()
static GLboolean gl2psGreater (GLfloat f1, GLfloat f2) static
Definition at line 1587 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psInitTriangle()
static void gl2psInitTriangle (GL2PStriangle * t) static
Definition at line 1052 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListInit().
gl2psLess()
static GLboolean gl2psLess (GLfloat f1, GLfloat f2) static
Definition at line 1593 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psLineCap()
GL2PSDLL_API GLint gl2psLineCap (GLint value)
Definition at line 6547 of file gl2ps.cpp.
gl2psLineJoin()
GL2PSDLL_API GLint gl2psLineJoin (GLint value)
Definition at line 6557 of file gl2ps.cpp.
gl2psLineWidth()
GL2PSDLL_API GLint gl2psLineWidth (GLfloat value)
Definition at line 6567 of file gl2ps.cpp.
Referenced by drawContext::drawAxes(), drawGraphAxes(), drawGraphCurves(), drawContext::drawMesh(), drawContext::drawSmallAxes(), drawGEdge::operator()(), drawGFace::operator()(), drawPView::operator()(), and drawPViewBoundingBox::operator()().
gl2psListAction()
static void gl2psListAction (GL2PSlist * list, void(*)(void *data) action) static
Definition at line 613 of file gl2ps.cpp.
Referenced by gl2psFreeBspTree(), gl2psPrintPDFFooter(), gl2psPrintPrimitives(), and gl2psTraverseBspTree().
gl2psListActionInverse()
static void gl2psListActionInverse (GL2PSlist * list, void(*)(void *data) action) static
Definition at line 622 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives(), and gl2psTraverseBspTree().
gl2psListAdd()
static void gl2psListAdd (GL2PSlist * list, void * data) static
Definition at line 565 of file gl2ps.cpp.
Referenced by gl2psAddBoundaryInList(), gl2psAddPolyPrimitive(), gl2psAddPrimitiveInList(), gl2psAddText(), gl2psDrawPixels(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListInit(), and gl2psPrintPDFPrimitive().
gl2psListAssignSortIds()
static void gl2psListAssignSortIds (GL2PSlist * list) static
Definition at line 605 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psListCreate()
static GL2PSlist* gl2psListCreate (GLint n, GLint incr, GLint size) static
Definition at line 536 of file gl2ps.cpp.
Referenced by gl2psBeginPage(), gl2psBuildBspTree(), gl2psPDFgroupListInit(), gl2psPrintPDFHeader(), gl2psPrintPrimitives(), and gl2psPrintSVGPixmap().
gl2psListDelete()
static void gl2psListDelete (GL2PSlist * list) static
Definition at line 558 of file gl2ps.cpp.
Referenced by gl2psBuildBspTree(), gl2psEndPage(), gl2psFreeBspTree(), gl2psPDFgroupListDelete(), gl2psPrintPDFFooter(), and gl2psPrintSVGPixmap().
gl2psListNbr()
static int gl2psListNbr (GL2PSlist * list) static
Definition at line 576 of file gl2ps.cpp.
Referenced by gl2psBuildBspTree(), gl2psBuildPolygonBoundary(), gl2psFindRoot(), gl2psListAction(), gl2psListActionInverse(), gl2psListAssignSortIds(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListDelete(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupListWriteXObjectResources(), gl2psPrintPrimitives(), gl2psPrintSVGPixmap(), gl2psRescaleAndOffset(), and gl2psSortOutTrianglePDFgroup().
gl2psListPointer()
static void* gl2psListPointer (GL2PSlist * list, GLint idx) static
Definition at line 583 of file gl2ps.cpp.
Referenced by gl2psBuildBspTree(), gl2psBuildPolygonBoundary(), gl2psFindRoot(), gl2psListAction(), gl2psListActionInverse(), gl2psListAssignSortIds(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListDelete(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupListWriteXObjectResources(), gl2psRescaleAndOffset(), and gl2psSortOutTrianglePDFgroup().
gl2psListRealloc()
static void gl2psListRealloc (GL2PSlist * list, GLint n) static
Definition at line 516 of file gl2ps.cpp.
Referenced by gl2psListAdd(), and gl2psListCreate().
gl2psListReset()
static void gl2psListReset (GL2PSlist * list) static
Definition at line 552 of file gl2ps.cpp.
Referenced by gl2psParseFeedbackBuffer(), and gl2psPrintPrimitives().
gl2psListSort()
static void gl2psListSort (GL2PSlist * list, int(*)(const void *a, const void *b) fcmp) static
Definition at line 596 of file gl2ps.cpp.
Referenced by gl2psBuildBspTree(), and gl2psPrintPrimitives().
gl2psMalloc()
static void* gl2psMalloc (size_t size) static
Definition at line 279 of file gl2ps.cpp.
Referenced by gl2psAddBoundaryInList(), gl2psAddPlanesInBspTreeImage(), gl2psAddPolyPrimitive(), gl2psAddText(), gl2psBeginPage(), gl2psBuildBspTree(), gl2psCopyPixmap(), gl2psCopyPrimitive(), gl2psCopyText(), gl2psCreateSplitPrimitive(), gl2psCreateSplitPrimitive2D(), gl2psDivideQuad(), gl2psDrawPixels(), gl2psListCreate(), gl2psListRealloc(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListWriteObjects(), gl2psPrintf(), gl2psPrintPDFHeader(), gl2psPrintPrimitives(), and gl2psSplitPrimitive().
gl2psMsg()
static void gl2psMsg (GLint level, const char * fmt, ...) static
Definition at line 261 of file gl2ps.cpp.
Referenced by gl2psBeginPage(), gl2psCheckOptions(), gl2psClosePDFDataStream(), gl2psCopyPrimitive(), gl2psCreateSplitPrimitive(), gl2psDisable(), gl2psDrawPixels(), gl2psEnable(), gl2psFindRoot(), gl2psGetPlane(), gl2psListAdd(), gl2psListPointer(), gl2psListRealloc(), gl2psMalloc(), gl2psParseFeedbackBuffer(), gl2psPrintGzipFooter(), gl2psPrintPostScriptPrimitive(), gl2psPrintPrimitives(), gl2psPrintSVGPixmap(), gl2psPrintSVGPrimitive(), gl2psRealloc(), and gl2psSorting().
gl2psNorm()
static GLfloat gl2psNorm (GLfloat * a) static
Definition at line 1145 of file gl2ps.cpp.
Referenced by gl2psAddBoundaryInList(), and gl2psGetNormal().
gl2psOpenPDFDataStream()
static int gl2psOpenPDFDataStream (void) static
Definition at line 4236 of file gl2ps.cpp.
Referenced by gl2psPrintPDFHeader().
gl2psOpenPDFDataStreamWritePreface()
static int gl2psOpenPDFDataStreamWritePreface (void) static
Definition at line 4253 of file gl2ps.cpp.
Referenced by gl2psPrintPDFHeader().
gl2psParseFeedbackBuffer()
static void gl2psParseFeedbackBuffer (GLint used) static
Definition at line 2290 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psParseStipplePattern()
static void gl2psParseStipplePattern (GLushort pattern, GLint factor, int * nb, int array[10]) static
Definition at line 3022 of file gl2ps.cpp.
Referenced by gl2psPrintPGFDash(), gl2psPrintPostScriptDash(), and gl2psPrintSVGDash().
gl2psPDFgroupListDelete()
static void gl2psPDFgroupListDelete (void) static
Definition at line 4151 of file gl2ps.cpp.
Referenced by gl2psPrintPDFFooter().
gl2psPDFgroupListInit()
static void gl2psPDFgroupListInit (void) static
Definition at line 3678 of file gl2ps.cpp.
Referenced by gl2psPrintPDFFooter().
gl2psPDFgroupListWriteFontResources()
static int gl2psPDFgroupListWriteFontResources (void) static
Definition at line 4131 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteVariableResources().
gl2psPDFgroupListWriteGStateResources()
static int gl2psPDFgroupListWriteGStateResources (void) static
Definition at line 4053 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteVariableResources().
gl2psPDFgroupListWriteMainStream()
static void gl2psPDFgroupListWriteMainStream (void) static
Definition at line 3839 of file gl2ps.cpp.
Referenced by gl2psPrintPDFFooter().
gl2psPDFgroupListWriteObjects()
static int gl2psPDFgroupListWriteObjects (int entryoffs) static
Definition at line 4890 of file gl2ps.cpp.
Referenced by gl2psPrintPDFFooter().
gl2psPDFgroupListWriteShaderResources()
static int gl2psPDFgroupListWriteShaderResources (void) static
Definition at line 4074 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteVariableResources().
gl2psPDFgroupListWriteVariableResources()
static int gl2psPDFgroupListWriteVariableResources (void) static
Definition at line 4381 of file gl2ps.cpp.
Referenced by gl2psPrintPDFFooter().
gl2psPDFgroupListWriteXObjectResources()
static int gl2psPDFgroupListWriteXObjectResources (void) static
Definition at line 4095 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteVariableResources().
gl2psPDFgroupObjectInit()
static void gl2psPDFgroupObjectInit (GL2PSpdfgroup * gro) static
Definition at line 3665 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListInit().
gl2psPDFRectHull()
static void gl2psPDFRectHull (GLfloat * xmin, GLfloat * xmax, GLfloat * ymin, GLfloat * ymax, GL2PStriangle * triangles, int cnt) static
Definition at line 4571 of file gl2ps.cpp.
Referenced by gl2psPrintPDFShader().
gl2psPDFstacksInit()
static void gl2psPDFstacksInit (void) static
Definition at line 3654 of file gl2ps.cpp.
Referenced by gl2psPrintPDFHeader().
gl2psPGFTextAlignment()
static const char* gl2psPGFTextAlignment (int align) static
Definition at line 5651 of file gl2ps.cpp.
Referenced by gl2psPrintPGFPrimitive().
gl2psPointSize()
GL2PSDLL_API GLint gl2psPointSize (GLfloat value)
Definition at line 6537 of file gl2ps.cpp.
Referenced by drawArrays(), drawGraphAxes(), drawGraphCurves(), drawContext::drawMesh(), drawGVertex::operator()(), and drawPView::operator()().
gl2psPrintf()
static int gl2psPrintf (const char * fmt, ...) static
Definition at line 404 of file gl2ps.cpp.
Referenced by gl2psEndPostScriptLine(), gl2psEndSVGLine(), gl2psOpenPDFDataStreamWritePreface(), gl2psPDFgroupListWriteMainStream(), gl2psPrintPDFBeginViewport(), gl2psPrintPDFEndViewport(), gl2psPrintPDFFillColor(), gl2psPrintPDFLineCap(), gl2psPrintPDFLineJoin(), gl2psPrintPDFLineWidth(), gl2psPrintPDFStrokeColor(), gl2psPrintPostScriptBeginViewport(), gl2psPrintPostScriptColor(), gl2psPrintPostScriptDash(), gl2psPrintPostScriptEndViewport(), gl2psPrintPostScriptFooter(), gl2psPrintPostScriptHeader(), gl2psPrintPostScriptImagemap(), gl2psPrintPostScriptPixmap(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGBeginViewport(), gl2psPrintSVGDash(), gl2psPrintSVGEndViewport(), gl2psPrintSVGFooter(), gl2psPrintSVGHeader(), gl2psPrintSVGPixmap(), gl2psPrintSVGPrimitive(), gl2psPrintSVGSmoothTriangle(), gl2psPutPDFImage(), gl2psPutPDFSpecial(), gl2psPutPDFText(), gl2psPutPDFTextBL(), and gl2psWriteByte().
gl2psPrintGzipFooter()
static void gl2psPrintGzipFooter (void) static
Definition at line 474 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptFooter(), and gl2psPrintSVGFooter().
gl2psPrintGzipHeader()
static void gl2psPrintGzipHeader (void) static
Definition at line 456 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptHeader(), and gl2psPrintSVGHeader().
gl2psPrintPDFBeginViewport()
static void gl2psPrintPDFBeginViewport (GLint viewport[4]) static
Definition at line 5031 of file gl2ps.cpp.
gl2psPrintPDFCatalog()
static int gl2psPrintPDFCatalog (void) static
Definition at line 4211 of file gl2ps.cpp.
Referenced by gl2psPrintPDFHeader().
gl2psPrintPDFCompressorType()
static int gl2psPrintPDFCompressorType (void) static
Definition at line 3504 of file gl2ps.cpp.
Referenced by gl2psOpenPDFDataStream(), gl2psPrintPDFPixmap(), and gl2psPrintPDFShader().
gl2psPrintPDFDataStreamLength()
static int gl2psPrintPDFDataStreamLength (int val) static
Definition at line 4342 of file gl2ps.cpp.
Referenced by gl2psPrintPDFFooter().
gl2psPrintPDFEndViewport()
static GLint gl2psPrintPDFEndViewport (void) static
Definition at line 5076 of file gl2ps.cpp.
gl2psPrintPDFFillColor()
static int gl2psPrintPDFFillColor (GL2PSrgba rgba) static
Definition at line 3531 of file gl2ps.cpp.
Referenced by gl2psOpenPDFDataStreamWritePreface(), gl2psPDFgroupListWriteMainStream(), and gl2psPrintPDFBeginViewport().
gl2psPrintPDFFinalPrimitive()
static void gl2psPrintPDFFinalPrimitive (void) static
Definition at line 5085 of file gl2ps.cpp.
gl2psPrintPDFFooter()
static void gl2psPrintPDFFooter (void) static
Definition at line 4966 of file gl2ps.cpp.
gl2psPrintPDFGSObject()
static int gl2psPrintPDFGSObject (void) static
Definition at line 4407 of file gl2ps.cpp.
Referenced by gl2psPrintPDFFooter().
gl2psPrintPDFHeader()
static void gl2psPrintPDFHeader (void) static
Definition at line 4271 of file gl2ps.cpp.
Referenced by gl2psPrintPDFBeginViewport().
gl2psPrintPDFInfo()
static int gl2psPrintPDFInfo (void) static
Definition at line 4170 of file gl2ps.cpp.
Referenced by gl2psPrintPDFHeader().
gl2psPrintPDFLineCap()
static int gl2psPrintPDFLineCap (GLint lc) static
Definition at line 3557 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream().
gl2psPrintPDFLineJoin()
static int gl2psPrintPDFLineJoin (GLint lj) static
Definition at line 3565 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream().
gl2psPrintPDFLineWidth()
static int gl2psPrintPDFLineWidth (GLfloat lw) static
Definition at line 3547 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream().
gl2psPrintPDFOpenPage()
static int gl2psPrintPDFOpenPage (void) static
Definition at line 4352 of file gl2ps.cpp.
Referenced by gl2psPrintPDFFooter().
gl2psPrintPDFPages()
static int gl2psPrintPDFPages (void) static
Definition at line 4222 of file gl2ps.cpp.
Referenced by gl2psPrintPDFHeader().
gl2psPrintPDFPixmap()
static int gl2psPrintPDFPixmap (int obj, int childobj, GL2PSimage * im, int gray) static
Definition at line 4803 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteObjects().
gl2psPrintPDFPixmapStreamData()
static int gl2psPrintPDFPixmapStreamData (GL2PSimage * im, int(*)(unsigned long data, int size) action, int gray) static
Definition at line 4764 of file gl2ps.cpp.
Referenced by gl2psPrintPDFPixmap().
gl2psPrintPDFPrimitive()
static void gl2psPrintPDFPrimitive (void * data) static
Definition at line 4304 of file gl2ps.cpp.
gl2psPrintPDFShader()
static int gl2psPrintPDFShader (int obj, GL2PStriangle * triangles, int size, int gray) static
Definition at line 4601 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteObjects().
gl2psPrintPDFShaderExtGS()
static int gl2psPrintPDFShaderExtGS (int obj, int childobj) static
Definition at line 4727 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteObjects().
gl2psPrintPDFShaderMask()
static int gl2psPrintPDFShaderMask (int obj, int childobj) static
Definition at line 4688 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteObjects().
gl2psPrintPDFShaderSimpleExtGS()
static int gl2psPrintPDFShaderSimpleExtGS (int obj, GLfloat alpha) static
Definition at line 4748 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteObjects().
gl2psPrintPDFShaderStreamData()
static int gl2psPrintPDFShaderStreamData (GL2PStriangle * triangle, GLfloat dx, GLfloat dy, GLfloat xmin, GLfloat ymin, int(*)(unsigned long data, int size) action, int gray) static
Definition at line 4544 of file gl2ps.cpp.
Referenced by gl2psPrintPDFShader().
gl2psPrintPDFShaderStreamDataAlpha()
static int gl2psPrintPDFShaderStreamDataAlpha (GL2PSvertex * vertex, int(*)(unsigned long data, int size) action, int sigbyte) static
Definition at line 4513 of file gl2ps.cpp.
Referenced by gl2psPrintPDFShaderStreamData().
gl2psPrintPDFShaderStreamDataCoord()
static int gl2psPrintPDFShaderStreamDataCoord (GL2PSvertex * vertex, int(*)(unsigned long data, int size) action, GLfloat dx, GLfloat dy, GLfloat xmin, GLfloat ymin) static
Definition at line 4427 of file gl2ps.cpp.
Referenced by gl2psPrintPDFShaderStreamData().
gl2psPrintPDFShaderStreamDataRGB()
static int gl2psPrintPDFShaderStreamDataRGB (GL2PSvertex * vertex, int(*)(unsigned long data, int size) action) static
Definition at line 4473 of file gl2ps.cpp.
Referenced by gl2psPrintPDFShaderStreamData().
gl2psPrintPDFStrokeColor()
static int gl2psPrintPDFStrokeColor (GL2PSrgba rgba) static
Definition at line 3514 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream().
gl2psPrintPDFText()
static int gl2psPrintPDFText (int obj, GL2PSstring * s, int fontnumber) static
Definition at line 4870 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteObjects().
gl2psPrintPGFBeginViewport()
static void gl2psPrintPGFBeginViewport (GLint viewport[4]) static
Definition at line 5812 of file gl2ps.cpp.
gl2psPrintPGFColor()
static void gl2psPrintPGFColor (GL2PSrgba rgba) static
Definition at line 5594 of file gl2ps.cpp.
Referenced by gl2psPrintPGFBeginViewport(), gl2psPrintPGFHeader(), and gl2psPrintPGFPrimitive().
gl2psPrintPGFDash()
static void gl2psPrintPGFDash (GLushort pattern, GLint factor) static
Definition at line 5629 of file gl2ps.cpp.
Referenced by gl2psPrintPGFPrimitive().
gl2psPrintPGFEndViewport()
static GLint gl2psPrintPGFEndViewport (void) static
Definition at line 5854 of file gl2ps.cpp.
gl2psPrintPGFFinalPrimitive()
static void gl2psPrintPGFFinalPrimitive (void) static
Definition at line 5862 of file gl2ps.cpp.
gl2psPrintPGFFooter()
static void gl2psPrintPGFFooter (void) static
Definition at line 5807 of file gl2ps.cpp.
gl2psPrintPGFHeader()
static void gl2psPrintPGFHeader (void) static
Definition at line 5602 of file gl2ps.cpp.
Referenced by gl2psPrintPGFBeginViewport().
gl2psPrintPGFPrimitive()
static void gl2psPrintPGFPrimitive (void * data) static
Definition at line 5667 of file gl2ps.cpp.
gl2psPrintPostScriptBeginViewport()
static void gl2psPrintPostScriptBeginViewport (GLint viewport[4]) static
Definition at line 3259 of file gl2ps.cpp.
gl2psPrintPostScriptColor()
static void gl2psPrintPostScriptColor (GL2PSrgba rgba) static
Definition at line 2997 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptPrimitive().
gl2psPrintPostScriptDash()
static int gl2psPrintPostScriptDash (GLushort pattern, GLint factor, const char * str) static
Definition at line 3056 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream(), and gl2psPrintPostScriptPrimitive().
gl2psPrintPostScriptEndViewport()
static GLint gl2psPrintPostScriptEndViewport (void) static
Definition at line 3302 of file gl2ps.cpp.
gl2psPrintPostScriptFinalPrimitive()
static void gl2psPrintPostScriptFinalPrimitive (void) static
Definition at line 3311 of file gl2ps.cpp.
gl2psPrintPostScriptFooter()
static void gl2psPrintPostScriptFooter (void) static
Definition at line 3246 of file gl2ps.cpp.
gl2psPrintPostScriptHeader()
static void gl2psPrintPostScriptHeader (void) static
Definition at line 2756 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptBeginViewport().
gl2psPrintPostScriptImagemap()
static void gl2psPrintPostScriptImagemap (GLfloat x, GLfloat y, GLsizei width, GLsizei height, const unsigned char * imagemap) static
Definition at line 2736 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptPrimitive().
gl2psPrintPostScriptPixmap()
static void gl2psPrintPostScriptPixmap (GLfloat x, GLfloat y, GL2PSimage * im) static
Definition at line 2535 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptPrimitive().
gl2psPrintPostScriptPrimitive()
static void gl2psPrintPostScriptPrimitive (void * data) static
Definition at line 3083 of file gl2ps.cpp.
gl2psPrintPrimitives()
static GLint gl2psPrintPrimitives (void) static
Definition at line 5916 of file gl2ps.cpp.
Referenced by gl2psEndPage(), gl2psPrintPDFEndViewport(), gl2psPrintPGFEndViewport(), gl2psPrintPostScriptEndViewport(), gl2psPrintSVGEndViewport(), and gl2psPrintTeXEndViewport().
gl2psPrintSVGBeginViewport()
static void gl2psPrintSVGBeginViewport (GLint viewport[4]) static
Definition at line 5514 of file gl2ps.cpp.
gl2psPrintSVGDash()
static void gl2psPrintSVGDash (GLushort pattern, GLint factor) static
Definition at line 5254 of file gl2ps.cpp.
Referenced by gl2psPrintSVGPrimitive().
gl2psPrintSVGEndViewport()
static GLint gl2psPrintSVGEndViewport (void) static
Definition at line 5560 of file gl2ps.cpp.
gl2psPrintSVGFinalPrimitive()
static void gl2psPrintSVGFinalPrimitive (void) static
Definition at line 5569 of file gl2ps.cpp.
gl2psPrintSVGFooter()
static void gl2psPrintSVGFooter (void) static
Definition at line 5506 of file gl2ps.cpp.
gl2psPrintSVGHeader()
static void gl2psPrintSVGHeader (void) static
Definition at line 5133 of file gl2ps.cpp.
Referenced by gl2psPrintSVGBeginViewport().
gl2psPrintSVGPixmap()
static void gl2psPrintSVGPixmap (GLfloat x, GLfloat y, GL2PSimage * pixmap) static
Definition at line 5282 of file gl2ps.cpp.
Referenced by gl2psPrintSVGPrimitive().
gl2psPrintSVGPrimitive()
static void gl2psPrintSVGPrimitive (void * data) static
Definition at line 5321 of file gl2ps.cpp.
gl2psPrintSVGSmoothTriangle()
static void gl2psPrintSVGSmoothTriangle (GL2PSxyz xyz[3], GL2PSrgba rgba[3]) static
Definition at line 5186 of file gl2ps.cpp.
Referenced by gl2psPrintSVGPrimitive().
gl2psPrintTeXBeginViewport()
static void gl2psPrintTeXBeginViewport (GLint viewport[4]) static
Definition at line 3463 of file gl2ps.cpp.
gl2psPrintTeXEndViewport()
static GLint gl2psPrintTeXEndViewport (void) static
Definition at line 3476 of file gl2ps.cpp.
gl2psPrintTeXFinalPrimitive()
static void gl2psPrintTeXFinalPrimitive (void) static
Definition at line 3481 of file gl2ps.cpp.
gl2psPrintTeXFooter()
static void gl2psPrintTeXFooter (void) static
Definition at line 3457 of file gl2ps.cpp.
gl2psPrintTeXHeader()
static void gl2psPrintTeXHeader (void) static
Definition at line 3347 of file gl2ps.cpp.
Referenced by gl2psPrintTeXBeginViewport().
gl2psPrintTeXPrimitive()
static void gl2psPrintTeXPrimitive (void * data) static
Definition at line 3392 of file gl2ps.cpp.
gl2psPsca()
static GLfloat gl2psPsca (GLfloat * a, GLfloat * b) static
Definition at line 1133 of file gl2ps.cpp.
Referenced by gl2psCutEdge().
gl2psPutPDFImage()
static void gl2psPutPDFImage (GL2PSimage * image, int cnt, GLfloat x, GLfloat y) static
Definition at line 3643 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream().
gl2psPutPDFSpecial()
static void gl2psPutPDFSpecial (int prim, int sec, GL2PSstring * text) static
Definition at line 3637 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream().
gl2psPutPDFText()
static void gl2psPutPDFText (GL2PSstring * text, int cnt, GLfloat x, GLfloat y) static
Definition at line 3573 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream().
gl2psPutPDFTextBL()
static void gl2psPutPDFTextBL (GL2PSstring * text, int cnt, GLfloat x, GLfloat y, GLfloat xbl, GLfloat ybl) static
Definition at line 3604 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream().
gl2psPvec()
static void gl2psPvec (GLfloat * a, GLfloat * b, GLfloat * c) static
Definition at line 1138 of file gl2ps.cpp.
Referenced by gl2psGetNormal().
gl2psRealloc()
static void* gl2psRealloc (void * ptr, size_t size) static
Definition at line 292 of file gl2ps.cpp.
Referenced by gl2psListRealloc(), gl2psPrintPDFFooter(), and gl2psSplitPrimitive2D().
gl2psRescaleAndOffset()
static void gl2psRescaleAndOffset (void) static
Definition at line 1698 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psResetLineProperties()
static void gl2psResetLineProperties (void) static
Definition at line 1063 of file gl2ps.cpp.
Referenced by gl2psEndViewport(), gl2psPrintPDFBeginViewport(), gl2psPrintPGFBeginViewport(), gl2psPrintPostScriptBeginViewport(), gl2psPrintSVGBeginViewport(), and gl2psPrintTeXBeginViewport().
gl2psResetPostScriptColor()
static void gl2psResetPostScriptColor (void) static
Definition at line 3005 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptBeginViewport(), and gl2psPrintPostScriptPrimitive().
gl2psSameColor()
static GLboolean gl2psSameColor (GL2PSrgba rgba1, GL2PSrgba rgba2) static
Definition at line 687 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListInit(), gl2psPrintPGFColor(), gl2psPrintPostScriptColor(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), and gl2psVertsSameColor().
gl2psSameColorThreshold()
static GLboolean gl2psSameColorThreshold (int n, GL2PSrgba rgba[], GL2PSrgba threshold) static
Definition at line 708 of file gl2ps.cpp.
Referenced by gl2psPrintSVGSmoothTriangle().
gl2psSamePosition()
static GLboolean gl2psSamePosition (GL2PSxyz p1, GL2PSxyz p2) static
Definition at line 1110 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream(), gl2psPrintPostScriptPrimitive(), and gl2psPrintSVGPrimitive().
gl2psSetLastColor()
static void gl2psSetLastColor (GL2PSrgba rgba) static
Definition at line 725 of file gl2ps.cpp.
Referenced by gl2psPrintPDFStrokeColor(), gl2psPrintPGFColor(), gl2psPrintPostScriptColor(), and gl2psPrintSVGPrimitive().
gl2psSetOptions()
GL2PSDLL_API GLint gl2psSetOptions (GLint options)
Definition at line 6592 of file gl2ps.cpp.
gl2psSetTexScaling()
GL2PSDLL_API GLint gl2psSetTexScaling (GLfloat scaling)
Definition at line 6661 of file gl2ps.cpp.
Referenced by CreateOutputFile().
gl2psSorting()
GL2PSDLL_API GLint gl2psSorting (GLint mode)
Definition at line 6271 of file gl2ps.cpp.
gl2psSortOutTrianglePDFgroup()
static void gl2psSortOutTrianglePDFgroup (GL2PSpdfgroup * gro) static
Definition at line 3785 of file gl2ps.cpp.
Referenced by gl2psPDFgroupListWriteMainStream().
gl2psSpecial()
GL2PSDLL_API GLint gl2psSpecial (GLint format, const char * str)
Definition at line 6327 of file gl2ps.cpp.
gl2psSpecialColor()
GL2PSDLL_API GLint gl2psSpecialColor (GLint format, const char * str, GL2PSrgba rgba)
Definition at line 6332 of file gl2ps.cpp.
gl2psSplitPrimitive()
static GLint gl2psSplitPrimitive (GL2PSprimitive * prim, GL2PSplane plane, GL2PSprimitive ** front, GL2PSprimitive ** back) static
Definition at line 1356 of file gl2ps.cpp.
Referenced by gl2psBuildBspTree().
gl2psSplitPrimitive2D()
static void gl2psSplitPrimitive2D (GL2PSprimitive * prim, GL2PSplane plane, GL2PSprimitive ** front, GL2PSprimitive ** back) static
Definition at line 1984 of file gl2ps.cpp.
Referenced by gl2psAddInBspImageTree().
gl2psSupportedBlendMode()
static GLboolean gl2psSupportedBlendMode (GLenum sfactor, GLenum dfactor) static
Definition at line 974 of file gl2ps.cpp.
Referenced by gl2psBlendFunc().
gl2psSVGGetColorString()
static void gl2psSVGGetColorString (GL2PSrgba rgba, char str[32]) static
Definition at line 5122 of file gl2ps.cpp.
Referenced by gl2psPrintSVGBeginViewport(), gl2psPrintSVGHeader(), gl2psPrintSVGPrimitive(), and gl2psPrintSVGSmoothTriangle().
gl2psSVGGetCoordsAndColors()
static void gl2psSVGGetCoordsAndColors (int n, GL2PSvertex * verts, GL2PSxyz * xyz, GL2PSrgba * rgba) static
Definition at line 5108 of file gl2ps.cpp.
Referenced by gl2psPrintSVGPrimitive().
gl2psTestSplitPrimitive()
static GLint gl2psTestSplitPrimitive (GL2PSprimitive * prim, GL2PSplane plane) static
Definition at line 1325 of file gl2ps.cpp.
Referenced by gl2psFindRoot().
gl2psText()
GL2PSDLL_API GLint gl2psText (const char * str, const char * fontname, GLshort fontsize)
Definition at line 6321 of file gl2ps.cpp.
Referenced by drawContext::drawString().
gl2psTextOpt()
GL2PSDLL_API GLint gl2psTextOpt (const char * str, const char * fontname, GLshort fontsize, GLint alignment, GLfloat angle)
Definition at line 6315 of file gl2ps.cpp.
Referenced by drawContext::drawString().
gl2psTextOptColor()
GL2PSDLL_API GLint gl2psTextOptColor (const char * str, const char * fontname, GLshort fontsize, GLint alignment, GLfloat angle, GL2PSrgba color)
Definition at line 6294 of file gl2ps.cpp.
gl2psTextOptColorBL()
GL2PSDLL_API GLint gl2psTextOptColorBL (const char * str, const char * fontname, GLshort fontsize, GLint alignment, GLfloat angle, GL2PSrgba color, GLfloat blx, GLfloat bly)
This version of gl2psTextOptColor is used to go around the fact that PDF does not support text alignment. The extra parameters (blx, bly) represent the bottom left corner of the text bounding box.
Definition at line 6307 of file gl2ps.cpp.
gl2psTraverseBspTree()
static void gl2psTraverseBspTree (GL2PSbsptree * tree, GL2PSxyz eye, GLfloat epsilon, GLboolean(*)(GLfloat f1, GLfloat f2) compare, void(*)(void *data) action, int inverse) static
Definition at line 1662 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
gl2psTrianglesFirst()
static int gl2psTrianglesFirst (const void * a, const void * b) static
Definition at line 1476 of file gl2ps.cpp.
Referenced by gl2psBuildBspTree().
gl2psVertsSameColor()
static GLboolean gl2psVertsSameColor (const GL2PSprimitive * prim) static
Definition at line 696 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptPrimitive().
gl2psWriteBigEndian()
static int gl2psWriteBigEndian (unsigned long data, int bytes) static
Definition at line 311 of file gl2ps.cpp.
Referenced by gl2psPrintPDFPixmap(), and gl2psPrintPDFShader().
gl2psWriteByte()
static void gl2psWriteByte (unsigned char byte) static
Definition at line 2528 of file gl2ps.cpp.
Referenced by gl2psPrintPostScriptImagemap(), and gl2psPrintPostScriptPixmap().
Variable Documentation
gl2ps
GL2PScontext* gl2ps = NULL static
Definition at line 249 of file gl2ps.cpp.
Referenced by gl2psAdaptVertexForBlending(), gl2psAddInBspImageTree(), gl2psAddInImageTree(), gl2psAddPolyPrimitive(), gl2psAddText(), gl2psBeginPage(), gl2psBeginViewport(), gl2psBlendFunc(), gl2psClosePDFDataStream(), gl2psComputeTightBoundingBox(), gl2psDisable(), gl2psDrawImageMap(), gl2psDrawPixels(), gl2psEnable(), gl2psEndPage(), gl2psEndPostScriptLine(), gl2psEndSVGLine(), gl2psEndViewport(), gl2psFindRoot(), gl2psForceRasterPos(), gl2psGetFileFormat(), gl2psGetOptions(), gl2psGetVertex(), gl2psLineCap(), gl2psLineJoin(), gl2psLineWidth(), gl2psMsg(), gl2psOpenPDFDataStream(), gl2psOpenPDFDataStreamWritePreface(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListDelete(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupListWriteVariableResources(), gl2psPDFgroupListWriteXObjectResources(), gl2psPDFstacksInit(), gl2psPointSize(), gl2psPrintf(), gl2psPrintGzipFooter(), gl2psPrintGzipHeader(), gl2psPrintPDFBeginViewport(), gl2psPrintPDFCatalog(), gl2psPrintPDFCompressorType(), gl2psPrintPDFDataStreamLength(), gl2psPrintPDFEndViewport(), gl2psPrintPDFFooter(), gl2psPrintPDFGSObject(), gl2psPrintPDFHeader(), gl2psPrintPDFInfo(), gl2psPrintPDFLineCap(), gl2psPrintPDFLineJoin(), gl2psPrintPDFOpenPage(), gl2psPrintPDFPages(), gl2psPrintPDFPixmap(), gl2psPrintPDFPrimitive(), gl2psPrintPDFShader(), gl2psPrintPDFShaderExtGS(), gl2psPrintPDFShaderMask(), gl2psPrintPDFShaderSimpleExtGS(), gl2psPrintPDFText(), gl2psPrintPGFBeginViewport(), gl2psPrintPGFColor(), gl2psPrintPGFDash(), gl2psPrintPGFEndViewport(), gl2psPrintPGFFooter(), gl2psPrintPGFHeader(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptBeginViewport(), gl2psPrintPostScriptColor(), gl2psPrintPostScriptDash(), gl2psPrintPostScriptHeader(), gl2psPrintPostScriptPrimitive(), gl2psPrintPrimitives(), gl2psPrintSVGBeginViewport(), gl2psPrintSVGHeader(), gl2psPrintSVGPrimitive(), gl2psPrintSVGSmoothTriangle(), gl2psPrintTeXBeginViewport(), gl2psPrintTeXFooter(), gl2psPrintTeXHeader(), gl2psPrintTeXPrimitive(), gl2psPutPDFImage(), gl2psPutPDFSpecial(), gl2psPutPDFText(), gl2psPutPDFTextBL(), gl2psRescaleAndOffset(), gl2psResetLineProperties(), gl2psResetPostScriptColor(), gl2psSetLastColor(), gl2psSetOptions(), gl2psSetTexScaling(), gl2psSorting(), gl2psSortOutTrianglePDFgroup(), gl2psSVGGetCoordsAndColors(), and gl2psWriteBigEndian().
gl2psbackends
GL2PSbackend* gl2psbackends[] static
Initial value:
= {
  &gl2psPS,
  &gl2psEPS,
  &gl2psTEX,
  &gl2psPDF,
  &gl2psSVG,
  &gl2psPGF
}
Definition at line 5888 of file gl2ps.cpp.
Referenced by gl2psBeginPage(), gl2psBeginViewport(), gl2psEndPage(), gl2psEndViewport(), gl2psGetFileExtension(), gl2psGetFormatDescription(), and gl2psPrintPrimitives().
gl2psEPS
GL2PSbackend gl2psEPS static
Initial value:
= {
  gl2psPrintPostScriptHeader,
  gl2psPrintPostScriptFooter,
  gl2psPrintPostScriptBeginViewport,
  gl2psPrintPostScriptEndViewport,
  gl2psPrintPostScriptPrimitive,
  gl2psPrintPostScriptFinalPrimitive,
  "eps",
  "Encapsulated Postscript"
}
Definition at line 3330 of file gl2ps.cpp.
gl2psPDF
GL2PSbackend gl2psPDF static
Initial value:
= {
  gl2psPrintPDFHeader,
  gl2psPrintPDFFooter,
  gl2psPrintPDFBeginViewport,
  gl2psPrintPDFEndViewport,
  gl2psPrintPDFPrimitive,
  gl2psPrintPDFFinalPrimitive,
  "pdf",
  "Portable Document Format"
}
Definition at line 5091 of file gl2ps.cpp.
gl2psPGF
GL2PSbackend gl2psPGF static
Initial value:
= {
  gl2psPrintPGFHeader,
  gl2psPrintPGFFooter,
  gl2psPrintPGFBeginViewport,
  gl2psPrintPGFEndViewport,
  gl2psPrintPGFPrimitive,
  gl2psPrintPGFFinalPrimitive,
  "tex",
  "PGF Latex Graphics"
}
Definition at line 5868 of file gl2ps.cpp.
gl2psPS
GL2PSbackend gl2psPS static
Initial value:
= {
  gl2psPrintPostScriptHeader,
  gl2psPrintPostScriptFooter,
  gl2psPrintPostScriptBeginViewport,
  gl2psPrintPostScriptEndViewport,
  gl2psPrintPostScriptPrimitive,
  gl2psPrintPostScriptFinalPrimitive,
  "ps",
  "Postscript"
}
Definition at line 3319 of file gl2ps.cpp.
gl2psSVG
GL2PSbackend gl2psSVG static
Initial value:
= {
  gl2psPrintSVGHeader,
  gl2psPrintSVGFooter,
  gl2psPrintSVGBeginViewport,
  gl2psPrintSVGEndViewport,
  gl2psPrintSVGPrimitive,
  gl2psPrintSVGFinalPrimitive,
  "svg",
  "Scalable Vector Graphics"
}
Definition at line 5577 of file gl2ps.cpp.
gl2psTEX
GL2PSbackend gl2psTEX static
Initial value:
= {
  gl2psPrintTeXHeader,
  gl2psPrintTeXFooter,
  gl2psPrintTeXBeginViewport,
  gl2psPrintTeXEndViewport,
  gl2psPrintTeXPrimitive,
  gl2psPrintTeXFinalPrimitive,
  "tex",
  "LaTeX text"
}
Definition at line 3487 of file gl2ps.cpp.