gmsh-TingyuanDoc: src/graphics/gl2ps.h File Reference
gl2ps.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include "GmshConfig.h"
#include <GL/gl.h>
Classes
struct GL2PSvertex
Macros
#define GL2PSDLL_API
#define GL2PS_MAJOR_VERSION 1
#define GL2PS_MINOR_VERSION 4
#define GL2PS_PATCH_VERSION 3
#define GL2PS_EXTRA_VERSION ""
#define GL2PS_VERSION
#define GL2PS_COPYRIGHT "(C) 1999-2020 C. Geuzaine"
#define GL2PS_PS 0
#define GL2PS_EPS 1
#define GL2PS_TEX 2
#define GL2PS_PDF 3
#define GL2PS_SVG 4
#define GL2PS_PGF 5
#define GL2PS_NO_SORT 1
#define GL2PS_SIMPLE_SORT 2
#define GL2PS_BSP_SORT 3
#define GL2PS_SUCCESS 0
#define GL2PS_INFO 1
#define GL2PS_WARNING 2
#define GL2PS_ERROR 3
#define GL2PS_NO_FEEDBACK 4
#define GL2PS_OVERFLOW 5
#define GL2PS_UNINITIALIZED 6
#define GL2PS_NONE 0
#define GL2PS_DRAW_BACKGROUND (1<<0)
#define GL2PS_SIMPLE_LINE_OFFSET (1<<1)
#define GL2PS_SILENT (1<<2)
#define GL2PS_BEST_ROOT (1<<3)
#define GL2PS_OCCLUSION_CULL (1<<4)
#define GL2PS_NO_TEXT (1<<5)
#define GL2PS_LANDSCAPE (1<<6)
#define GL2PS_NO_PS3_SHADING (1<<7)
#define GL2PS_NO_PIXMAP (1<<8)
#define GL2PS_USE_CURRENT_VIEWPORT (1<<9)
#define GL2PS_COMPRESS (1<<10)
#define GL2PS_NO_BLENDING (1<<11)
#define GL2PS_TIGHT_BOUNDING_BOX (1<<12)
#define GL2PS_NO_OPENGL_CONTEXT (1<<13)
#define GL2PS_NO_TEX_FONTSIZE (1<<14)
#define GL2PS_SQUARE_POINTS (1<<15)
#define GL2PS_POLYGON_OFFSET_FILL 1
#define GL2PS_POLYGON_BOUNDARY 2
#define GL2PS_LINE_STIPPLE 3
#define GL2PS_BLEND 4
#define GL2PS_LINE_CAP_BUTT 0
#define GL2PS_LINE_CAP_ROUND 1
#define GL2PS_LINE_CAP_SQUARE 2
#define GL2PS_LINE_JOIN_MITER 0
#define GL2PS_LINE_JOIN_ROUND 1
#define GL2PS_LINE_JOIN_BEVEL 2
#define GL2PS_TEXT_C 1
#define GL2PS_TEXT_CL 2
#define GL2PS_TEXT_CR 3
#define GL2PS_TEXT_B 4
#define GL2PS_TEXT_BL 5
#define GL2PS_TEXT_BR 6
#define GL2PS_TEXT_T 7
#define GL2PS_TEXT_TL 8
#define GL2PS_TEXT_TR 9
#define GL2PS_NO_TYPE -1
#define GL2PS_TEXT 1
#define GL2PS_POINT 2
#define GL2PS_LINE 3
#define GL2PS_QUADRANGLE 4
#define GL2PS_TRIANGLE 5
#define GL2PS_PIXMAP 6
#define GL2PS_IMAGEMAP 7
#define GL2PS_IMAGEMAP_WRITTEN 8
#define GL2PS_IMAGEMAP_VISIBLE 9
#define GL2PS_SPECIAL 10
Typedefs
typedef GLfloat GL2PSrgba[4]
typedef GLfloat GL2PSxyz[3]
Functions
GL2PSDLL_API GLint gl2psBeginPage (const char *title, const char *producer, GLint viewport[4], GLint format, GLint sort, GLint options, GLint colormode, GLint colorsize, GL2PSrgba *colormap, GLint nr, GLint ng, GLint nb, GLint buffersize, FILE *stream, const char *filename)
GL2PSDLL_API GLint gl2psEndPage (void)
GL2PSDLL_API GLint gl2psSetOptions (GLint options)
GL2PSDLL_API GLint gl2psGetOptions (GLint *options)
GL2PSDLL_API GLint gl2psBeginViewport (GLint viewport[4])
GL2PSDLL_API GLint gl2psEndViewport (void)
GL2PSDLL_API GLint gl2psText (const char *str, const char *fontname, GLshort fontsize)
GL2PSDLL_API GLint gl2psTextOpt (const char *str, const char *fontname, GLshort fontsize, GLint align, GLfloat angle)
GL2PSDLL_API GLint gl2psTextOptColor (const char *str, const char *fontname, GLshort fontsize, GLint align, GLfloat angle, GL2PSrgba color)
GL2PSDLL_API GLint gl2psTextOptColorBL (const char *str, const char *fontname, GLshort fontsize, GLint align, GLfloat angle, GL2PSrgba color, GLfloat blx, GLfloat bly)
GL2PSDLL_API GLint gl2psSpecial (GLint format, const char *str)
GL2PSDLL_API GLint gl2psSpecialColor (GLint format, const char *str, GL2PSrgba rgba)
GL2PSDLL_API GLint gl2psDrawPixels (GLsizei width, GLsizei height, GLint xorig, GLint yorig, GLenum format, GLenum type, const void *pixels)
GL2PSDLL_API GLint gl2psEnable (GLint mode)
GL2PSDLL_API GLint gl2psDisable (GLint mode)
GL2PSDLL_API GLint gl2psPointSize (GLfloat value)
GL2PSDLL_API GLint gl2psLineCap (GLint value)
GL2PSDLL_API GLint gl2psLineJoin (GLint value)
GL2PSDLL_API GLint gl2psLineWidth (GLfloat value)
GL2PSDLL_API GLint gl2psBlendFunc (GLenum sfactor, GLenum dfactor)
GL2PSDLL_API GLint gl2psSorting (GLint mode)
GL2PSDLL_API GLint gl2psForceRasterPos (GL2PSvertex *vert)
GL2PSDLL_API void gl2psAddPolyPrimitive (GLshort type, GLshort numverts, GL2PSvertex *verts, GLint offset, GLfloat ofactor, GLfloat ounits, GLushort pattern, GLint factor, GLfloat width, GLint linecap, GLint linejoin, char boundary)
GL2PSDLL_API GLint gl2psDrawImageMap (GLsizei width, GLsizei height, const GLfloat position[3], const unsigned char *imagemap)
GL2PSDLL_API const char * gl2psGetFileExtension (GLint format)
GL2PSDLL_API const char * gl2psGetFormatDescription (GLint format)
GL2PSDLL_API GLint gl2psGetFileFormat ()
GL2PSDLL_API GLint gl2psSetTexScaling (GLfloat scaling)
Macro Definition Documentation
GL2PS_BEST_ROOT
#define GL2PS_BEST_ROOT (1<<3)
Definition at line 132 of file gl2ps.h.
GL2PS_BLEND
#define GL2PS_BLEND 4
Definition at line 151 of file gl2ps.h.
GL2PS_BSP_SORT
#define GL2PS_BSP_SORT 3
Definition at line 114 of file gl2ps.h.
GL2PS_COMPRESS
#define GL2PS_COMPRESS (1<<10)
Definition at line 139 of file gl2ps.h.
GL2PS_COPYRIGHT
#define GL2PS_COPYRIGHT "(C) 1999-2020 C. Geuzaine"
Definition at line 99 of file gl2ps.h.
GL2PS_DRAW_BACKGROUND
#define GL2PS_DRAW_BACKGROUND (1<<0)
Definition at line 129 of file gl2ps.h.
GL2PS_EPS
#define GL2PS_EPS 1
Definition at line 104 of file gl2ps.h.
GL2PS_ERROR
#define GL2PS_ERROR 3
Definition at line 121 of file gl2ps.h.
GL2PS_EXTRA_VERSION
#define GL2PS_EXTRA_VERSION ""
Definition at line 93 of file gl2ps.h.
GL2PS_IMAGEMAP
#define GL2PS_IMAGEMAP 7
Definition at line 195 of file gl2ps.h.
GL2PS_IMAGEMAP_VISIBLE
#define GL2PS_IMAGEMAP_VISIBLE 9
Definition at line 197 of file gl2ps.h.
GL2PS_IMAGEMAP_WRITTEN
#define GL2PS_IMAGEMAP_WRITTEN 8
Definition at line 196 of file gl2ps.h.
GL2PS_INFO
#define GL2PS_INFO 1
Definition at line 119 of file gl2ps.h.
GL2PS_LANDSCAPE
#define GL2PS_LANDSCAPE (1<<6)
Definition at line 135 of file gl2ps.h.
GL2PS_LINE
#define GL2PS_LINE 3
Definition at line 191 of file gl2ps.h.
GL2PS_LINE_CAP_BUTT
#define GL2PS_LINE_CAP_BUTT 0
Definition at line 155 of file gl2ps.h.
GL2PS_LINE_CAP_ROUND
#define GL2PS_LINE_CAP_ROUND 1
Definition at line 156 of file gl2ps.h.
GL2PS_LINE_CAP_SQUARE
#define GL2PS_LINE_CAP_SQUARE 2
Definition at line 157 of file gl2ps.h.
GL2PS_LINE_JOIN_BEVEL
#define GL2PS_LINE_JOIN_BEVEL 2
Definition at line 161 of file gl2ps.h.
GL2PS_LINE_JOIN_MITER
#define GL2PS_LINE_JOIN_MITER 0
Definition at line 159 of file gl2ps.h.
GL2PS_LINE_JOIN_ROUND
#define GL2PS_LINE_JOIN_ROUND 1
Definition at line 160 of file gl2ps.h.
GL2PS_LINE_STIPPLE
#define GL2PS_LINE_STIPPLE 3
Definition at line 150 of file gl2ps.h.
GL2PS_MAJOR_VERSION
#define GL2PS_MAJOR_VERSION 1
Definition at line 90 of file gl2ps.h.
GL2PS_MINOR_VERSION
#define GL2PS_MINOR_VERSION 4
Definition at line 91 of file gl2ps.h.
GL2PS_NO_BLENDING
#define GL2PS_NO_BLENDING (1<<11)
Definition at line 140 of file gl2ps.h.
GL2PS_NO_FEEDBACK
#define GL2PS_NO_FEEDBACK 4
Definition at line 122 of file gl2ps.h.
GL2PS_NO_OPENGL_CONTEXT
#define GL2PS_NO_OPENGL_CONTEXT (1<<13)
Definition at line 142 of file gl2ps.h.
GL2PS_NO_PIXMAP
#define GL2PS_NO_PIXMAP (1<<8)
Definition at line 137 of file gl2ps.h.
GL2PS_NO_PS3_SHADING
#define GL2PS_NO_PS3_SHADING (1<<7)
Definition at line 136 of file gl2ps.h.
GL2PS_NO_SORT
#define GL2PS_NO_SORT 1
Definition at line 112 of file gl2ps.h.
GL2PS_NO_TEX_FONTSIZE
#define GL2PS_NO_TEX_FONTSIZE (1<<14)
Definition at line 143 of file gl2ps.h.
GL2PS_NO_TEXT
#define GL2PS_NO_TEXT (1<<5)
Definition at line 134 of file gl2ps.h.
GL2PS_NO_TYPE
#define GL2PS_NO_TYPE -1
Definition at line 188 of file gl2ps.h.
GL2PS_NONE
#define GL2PS_NONE 0
Definition at line 128 of file gl2ps.h.
GL2PS_OCCLUSION_CULL
#define GL2PS_OCCLUSION_CULL (1<<4)
Definition at line 133 of file gl2ps.h.
GL2PS_OVERFLOW
#define GL2PS_OVERFLOW 5
Definition at line 123 of file gl2ps.h.
GL2PS_PATCH_VERSION
#define GL2PS_PATCH_VERSION 3
Definition at line 92 of file gl2ps.h.
GL2PS_PDF
#define GL2PS_PDF 3
Definition at line 106 of file gl2ps.h.
GL2PS_PGF
#define GL2PS_PGF 5
Definition at line 108 of file gl2ps.h.
GL2PS_PIXMAP
#define GL2PS_PIXMAP 6
Definition at line 194 of file gl2ps.h.
GL2PS_POINT
#define GL2PS_POINT 2
Definition at line 190 of file gl2ps.h.
GL2PS_POLYGON_BOUNDARY
#define GL2PS_POLYGON_BOUNDARY 2
Definition at line 149 of file gl2ps.h.
GL2PS_POLYGON_OFFSET_FILL
#define GL2PS_POLYGON_OFFSET_FILL 1
Definition at line 148 of file gl2ps.h.
GL2PS_PS
#define GL2PS_PS 0
Definition at line 103 of file gl2ps.h.
GL2PS_QUADRANGLE
#define GL2PS_QUADRANGLE 4
Definition at line 192 of file gl2ps.h.
GL2PS_SILENT
#define GL2PS_SILENT (1<<2)
Definition at line 131 of file gl2ps.h.
GL2PS_SIMPLE_LINE_OFFSET
#define GL2PS_SIMPLE_LINE_OFFSET (1<<1)
Definition at line 130 of file gl2ps.h.
GL2PS_SIMPLE_SORT
#define GL2PS_SIMPLE_SORT 2
Definition at line 113 of file gl2ps.h.
GL2PS_SPECIAL
#define GL2PS_SPECIAL 10
Definition at line 198 of file gl2ps.h.
GL2PS_SQUARE_POINTS
#define GL2PS_SQUARE_POINTS (1<<15)
Definition at line 144 of file gl2ps.h.
GL2PS_SUCCESS
#define GL2PS_SUCCESS 0
Definition at line 118 of file gl2ps.h.
GL2PS_SVG
#define GL2PS_SVG 4
Definition at line 107 of file gl2ps.h.
GL2PS_TEX
#define GL2PS_TEX 2
Definition at line 105 of file gl2ps.h.
GL2PS_TEXT
#define GL2PS_TEXT 1
Definition at line 189 of file gl2ps.h.
GL2PS_TEXT_B
#define GL2PS_TEXT_B 4
Definition at line 172 of file gl2ps.h.
GL2PS_TEXT_BL
#define GL2PS_TEXT_BL 5
Definition at line 173 of file gl2ps.h.
GL2PS_TEXT_BR
#define GL2PS_TEXT_BR 6
Definition at line 174 of file gl2ps.h.
GL2PS_TEXT_C
#define GL2PS_TEXT_C 1
Definition at line 169 of file gl2ps.h.
GL2PS_TEXT_CL
#define GL2PS_TEXT_CL 2
Definition at line 170 of file gl2ps.h.
GL2PS_TEXT_CR
#define GL2PS_TEXT_CR 3
Definition at line 171 of file gl2ps.h.
GL2PS_TEXT_T
#define GL2PS_TEXT_T 7
Definition at line 175 of file gl2ps.h.
GL2PS_TEXT_TL
#define GL2PS_TEXT_TL 8
Definition at line 176 of file gl2ps.h.
GL2PS_TEXT_TR
#define GL2PS_TEXT_TR 9
Definition at line 177 of file gl2ps.h.
GL2PS_TIGHT_BOUNDING_BOX
#define GL2PS_TIGHT_BOUNDING_BOX (1<<12)
Definition at line 141 of file gl2ps.h.
GL2PS_TRIANGLE
#define GL2PS_TRIANGLE 5
Definition at line 193 of file gl2ps.h.
GL2PS_UNINITIALIZED
#define GL2PS_UNINITIALIZED 6
Definition at line 124 of file gl2ps.h.
GL2PS_USE_CURRENT_VIEWPORT
#define GL2PS_USE_CURRENT_VIEWPORT (1<<9)
Definition at line 138 of file gl2ps.h.
GL2PS_VERSION
#define GL2PS_VERSION
Value:
                       (GL2PS_MAJOR_VERSION + \
                       0.01 * GL2PS_MINOR_VERSION + \
                       0.0001 * GL2PS_PATCH_VERSION)
Definition at line 95 of file gl2ps.h.
GL2PS_WARNING
#define GL2PS_WARNING 2
Definition at line 120 of file gl2ps.h.
GL2PSDLL_API
#define GL2PSDLL_API
Definition at line 65 of file gl2ps.h.
Typedef Documentation
GL2PSrgba
typedef GLfloat GL2PSrgba[4]
Definition at line 178 of file gl2ps.h.
GL2PSxyz
typedef GLfloat GL2PSxyz[3]
Definition at line 179 of file gl2ps.h.
Function Documentation
gl2psAddPolyPrimitive()
GL2PSDLL_API void gl2psAddPolyPrimitive (GLshort type, GLshort numverts, GL2PSvertex * verts, GLint offset, GLfloat ofactor, GLfloat ounits, GLushort pattern, GLint factor, GLfloat width, GLint linecap, GLint linejoin, char boundary)
Definition at line 2234 of file gl2ps.cpp.
Referenced by gl2psParseFeedbackBuffer().
gl2psBeginPage()
GL2PSDLL_API GLint gl2psBeginPage (const char * title, const char * producer, GLint viewport[4], GLint format, GLint sort, GLint options, GLint colormode, GLint colorsize, GL2PSrgba * colormap, GLint nr, GLint ng, GLint nb, GLint buffersize, FILE * stream, const char * filename)
Definition at line 6027 of file gl2ps.cpp.
Referenced by CreateOutputFile().
gl2psBeginViewport()
GL2PSDLL_API GLint gl2psBeginViewport (GLint viewport[4])
Definition at line 6248 of file gl2ps.cpp.
gl2psBlendFunc()
GL2PSDLL_API GLint gl2psBlendFunc (GLenum sfactor, GLenum dfactor)
Definition at line 6577 of file gl2ps.cpp.
gl2psDisable()
GL2PSDLL_API GLint gl2psDisable (GLint mode)
Definition at line 6512 of file gl2ps.cpp.
Referenced by drawArrays(), drawBarycentricDual(), drawGraphAxes(), drawGraphCurves(), drawGridStipple(), drawVoronoiDual(), and drawGFace::operator()().
gl2psDrawImageMap()
GL2PSDLL_API GLint gl2psDrawImageMap (GLsizei width, GLsizei height, const GLfloat position[3], const unsigned char * imagemap)
Definition at line 6451 of file gl2ps.cpp.
gl2psDrawPixels()
GL2PSDLL_API GLint gl2psDrawPixels (GLsizei width, GLsizei height, GLint xorig, GLint yorig, GLenum format, GLenum type, const void * pixels)
Definition at line 6337 of file gl2ps.cpp.
Referenced by CreateOutputFile().
gl2psEnable()
GL2PSDLL_API GLint gl2psEnable (GLint mode)
Definition at line 6476 of file gl2ps.cpp.
Referenced by drawArrays(), drawBarycentricDual(), drawGraphAxes(), drawGraphCurves(), drawGridStipple(), drawVoronoiDual(), and drawGFace::operator()().
gl2psEndPage()
GL2PSDLL_API GLint gl2psEndPage (void)
Definition at line 6221 of file gl2ps.cpp.
Referenced by CreateOutputFile().
gl2psEndViewport()
GL2PSDLL_API GLint gl2psEndViewport (void)
Definition at line 6257 of file gl2ps.cpp.
gl2psForceRasterPos()
GL2PSDLL_API GLint gl2psForceRasterPos (GL2PSvertex * vert)
Definition at line 6642 of file gl2ps.cpp.
gl2psGetFileExtension()
GL2PSDLL_API const char* gl2psGetFileExtension (GLint format)
Definition at line 6617 of file gl2ps.cpp.
gl2psGetFileFormat()
GL2PSDLL_API GLint gl2psGetFileFormat ()
Definition at line 6633 of file gl2ps.cpp.
gl2psGetFormatDescription()
GL2PSDLL_API const char* gl2psGetFormatDescription (GLint format)
Definition at line 6625 of file gl2ps.cpp.
gl2psGetOptions()
GL2PSDLL_API GLint gl2psGetOptions (GLint * options)
Definition at line 6605 of file gl2ps.cpp.
gl2psLineCap()
GL2PSDLL_API GLint gl2psLineCap (GLint value)
Definition at line 6547 of file gl2ps.cpp.
gl2psLineJoin()
GL2PSDLL_API GLint gl2psLineJoin (GLint value)
Definition at line 6557 of file gl2ps.cpp.
gl2psLineWidth()
GL2PSDLL_API GLint gl2psLineWidth (GLfloat value)
Definition at line 6567 of file gl2ps.cpp.
Referenced by drawContext::drawAxes(), drawGraphAxes(), drawGraphCurves(), drawContext::drawMesh(), drawContext::drawSmallAxes(), drawGEdge::operator()(), drawGFace::operator()(), drawPView::operator()(), and drawPViewBoundingBox::operator()().
gl2psPointSize()
GL2PSDLL_API GLint gl2psPointSize (GLfloat value)
Definition at line 6537 of file gl2ps.cpp.
Referenced by drawArrays(), drawGraphAxes(), drawGraphCurves(), drawContext::drawMesh(), drawGVertex::operator()(), and drawPView::operator()().
gl2psSetOptions()
GL2PSDLL_API GLint gl2psSetOptions (GLint options)
Definition at line 6592 of file gl2ps.cpp.
gl2psSetTexScaling()
GL2PSDLL_API GLint gl2psSetTexScaling (GLfloat scaling)
Definition at line 6661 of file gl2ps.cpp.
Referenced by CreateOutputFile().
gl2psSorting()
GL2PSDLL_API GLint gl2psSorting (GLint mode)
Definition at line 6271 of file gl2ps.cpp.
gl2psSpecial()
GL2PSDLL_API GLint gl2psSpecial (GLint format, const char * str)
Definition at line 6327 of file gl2ps.cpp.
gl2psSpecialColor()
GL2PSDLL_API GLint gl2psSpecialColor (GLint format, const char * str, GL2PSrgba rgba)
Definition at line 6332 of file gl2ps.cpp.
gl2psText()
GL2PSDLL_API GLint gl2psText (const char * str, const char * fontname, GLshort fontsize)
Definition at line 6321 of file gl2ps.cpp.
Referenced by drawContext::drawString().
gl2psTextOpt()
GL2PSDLL_API GLint gl2psTextOpt (const char * str, const char * fontname, GLshort fontsize, GLint align, GLfloat angle)
Definition at line 6315 of file gl2ps.cpp.
Referenced by drawContext::drawString().
gl2psTextOptColor()
GL2PSDLL_API GLint gl2psTextOptColor (const char * str, const char * fontname, GLshort fontsize, GLint align, GLfloat angle, GL2PSrgba color)
Definition at line 6294 of file gl2ps.cpp.
gl2psTextOptColorBL()
GL2PSDLL_API GLint gl2psTextOptColorBL (const char * str, const char * fontname, GLshort fontsize, GLint alignment, GLfloat angle, GL2PSrgba color, GLfloat blx, GLfloat bly)
This version of gl2psTextOptColor is used to go around the fact that PDF does not support text alignment. The extra parameters (blx, bly) represent the bottom left corner of the text bounding box.
Definition at line 6307 of file gl2ps.cpp.