gmsh-TingyuanDoc: src/geo/gmshEdge.cpp File Reference
gmshEdge.cpp File Reference
#include "gmshEdge.h"
#include "Context.h"
#include "GFace.h"
#include "GModel.h"
#include "Geo.h"
#include "GeoInterpolation.h"
#include "GmshMessage.h"
#include "decasteljau.h"
#include <sstream>
Functions
static void setMeshSizeFromCurvePoints (GEdge &edge, const Curve &curve)
static SPoint3 curveGetPoint (Curve *c, int i)
Function Documentation
curveGetPoint()
static SPoint3 curveGetPoint (Curve * c, int i) inline static
Definition at line 532 of file gmshEdge.cpp.
Referenced by gmshEdge::discretize().
setMeshSizeFromCurvePoints()
static void setMeshSizeFromCurvePoints (GEdge & edge, const Curve & curve) static
Definition at line 16 of file gmshEdge.cpp.
Referenced by gmshEdge::gmshEdge(), and gmshEdge::resetNativePtr().