gmsh-TingyuanDoc: src/geo/gmshEdgeDiscretize.cpp File Reference
gmshEdgeDiscretize.cpp File Reference
#include <cstdio>
#include <cmath>
#include <vector>
#include "SPoint3.h"
#include "SVector3.h"
#include "GEdge.h"
#include "gmshEdge.h"
#include "Geo.h"
Classes
class discreteList
Functions
static void decasteljau (double tol, discreteList &discrete, int pos, const SPoint3 &p0, const SPoint3 &p1, const SPoint3 &p2, const SPoint3 &p3, double t0, double t3)
static int discretizeBezier (double tol, discreteList &discrete, int pos, const SPoint3 pt[4], double t0, double t3, bool insertFirstPoint)
static int discretizeBSpline (double tol, discreteList &discrete, int pos, const SPoint3 pt[4], double t0, double t3, bool insertFirstPoint)
static int discretizeCatmullRom (double tol, discreteList &discrete, int pos, const SPoint3 pt[4], double t0, double t3, bool insertFirstPoint)
static SPoint3 curveGetPoint (Curve *c, int i)
static void discretizeCurve (Curve *c, double tol, std::vector< SPoint3 > &pts, std::vector< double > &ts)
Function Documentation
curveGetPoint()
static SPoint3 curveGetPoint (Curve * c, int i) inline static
Definition at line 98 of file gmshEdgeDiscretize.cpp.
Referenced by discretizeCurve().
decasteljau()
static void decasteljau (double tol, discreteList & discrete, int pos, const SPoint3 & p0, const SPoint3 & p1, const SPoint3 & p2, const SPoint3 & p3, double t0, double t3) static
Definition at line 41 of file gmshEdgeDiscretize.cpp.
Referenced by gmshEdge::discretize(), MLine3::discretize(), MLineN::discretize(), and discretizeBezier().
discretizeBezier()
static int discretizeBezier (double tol, discreteList & discrete, int pos, const SPoint3 pt[4], double t0, double t3, bool insertFirstPoint) static
Definition at line 68 of file gmshEdgeDiscretize.cpp.
Referenced by discretizeBSpline(), discretizeCatmullRom(), and discretizeCurve().
discretizeBSpline()
static int discretizeBSpline (double tol, discreteList & discrete, int pos, const SPoint3 pt[4], double t0, double t3, bool insertFirstPoint) static
Definition at line 78 of file gmshEdgeDiscretize.cpp.
Referenced by discretizeCurve().
discretizeCatmullRom()
static int discretizeCatmullRom (double tol, discreteList & discrete, int pos, const SPoint3 pt[4], double t0, double t3, bool insertFirstPoint) static
Definition at line 89 of file gmshEdgeDiscretize.cpp.
Referenced by discretizeCurve().
discretizeCurve()
static void discretizeCurve (Curve * c, double tol, std::vector< SPoint3 > & pts, std::vector< double > & ts) static
Definition at line 105 of file gmshEdgeDiscretize.cpp.