gmsh-TingyuanDoc: src/geo/gmshLevelset.cpp File Reference
gmshLevelset.cpp File Reference
#include <queue>
#include <stack>
#include <cmath>
#include "gmshLevelset.h"
#include "fullMatrix.h"
#include "GModel.h"
#include "OS.h"
#include "MElement.h"
#include "Numeric.h"
#include "cartesian.h"
#include "GmshConfig.h"
#include "mathEvaluator.h"
Functions
void insertActiveCells (double x, double y, double z, double rmax, cartesianBox< double > &box)
void fillPointCloud (GEdge *ge, double sampling, std::vector< SPoint3 > &points)
int removeBadChildCells (cartesianBox< double > *parent)
void removeParentCellsWithChildren (cartesianBox< double > *box)
void computeLevelset (GModel *gm, cartesianBox< double > &box)
double det3 (double d11, double d12, double d13, double d21, double d22, double d23, double d31, double d32, double d33)
void norm (const double *vec, double *norm)
void cross (const double *pt0, const double *pt1, const double *pt2, double *cross)
bool isPlanar (const double *pt1, const double *pt2, const double *pt3, const double *pt4)
double evalRadialFnDer (int p, int index, double dx, double dy, double dz, double ep)
void printNodes (fullMatrix< double > &myNodes, fullMatrix< double > &surf)
Function Documentation
computeLevelset()
void computeLevelset (GModel * gm, cartesianBox< double > & box)
Definition at line 144 of file gmshLevelset.cpp.
cross()
void cross (const double * pt0, const double * pt1, const double * pt2, double * cross) inline
Definition at line 210 of file gmshLevelset.cpp.
Referenced by eigen(), gLevelsetConrod::gLevelsetConrod(), isPlanar(), and vcross().
det3()
double det3 (double d11, double d12, double d13, double d21, double d22, double d23, double d31, double d32, double d33) inline
Definition at line 195 of file gmshLevelset.cpp.
Referenced by gLevelsetPlane::gLevelsetPlane().
evalRadialFnDer()
double evalRadialFnDer (int p, int index, double dx, double dy, double dz, double ep) inline
Definition at line 234 of file gmshLevelset.cpp.
Referenced by gLevelsetPoints::generateRbfMat().
fillPointCloud()
void fillPointCloud (GEdge * ge, double sampling, std::vector< SPoint3 > & points)
Definition at line 61 of file gmshLevelset.cpp.
insertActiveCells()
void insertActiveCells (double x, double y, double z, double rmax, cartesianBox< double > & box)
Definition at line 46 of file gmshLevelset.cpp.
isPlanar()
bool isPlanar (const double * pt1, const double * pt2, const double * pt3, const double * pt4) inline
Definition at line 220 of file gmshLevelset.cpp.
Referenced by gLevelsetBox::gLevelsetBox().
norm()
void norm (const double * vec, double * norm) inline
Definition at line 202 of file gmshLevelset.cpp.
Referenced by addVectorElement(), qmHexahedron::angles(), tetgenmesh::calculateabovepoint4(), changeReferential(), GModel::checkMeshCoherence(), SOrientedBoundingBox::compare(), GFace::computeMeanPlane(), meshMetric::computeMetricFrey(), meshMetric::computeMetricIsoLinInterp(), meshMetric::computeMetricLevelSet(), gLevelsetQuadric::computeRotationMatrix(), GEdge::curvature(), GFace::curvatureDiv(), GMSH_BubblesPlugin::execute(), GMSH_DistancePlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), gLevelsetNACA00::getClosestBndPoint(), GMSH_NearToFarFieldPlugin::getFarFieldMonk(), MQuadrangle::getInnerRadius(), MTriangle::getVolume(), gl2psAddBoundaryInList(), gl2psGetNormal(), gLevelsetBox::gLevelsetBox(), gLevelsetConrod::gLevelsetConrod(), gLevelsetCylinder::gLevelsetCylinder(), gLevelsetPlane::gLevelsetPlane(), gmshLineSearch(), intersection_segments(), isPlanar(), GEdge::length(), meshGenerator(), meshGEdge::operator()(), F_Lc::operator()(), F_Transfinite::operator()(), F_One::operator()(), optimalPointFrontal(), GModel::readSTL(), GModel::removeDuplicateMeshVertices(), GRegion::setOutwardOrientationMeshConstraint(), stringValue(), sys2x2(), sys3x3_with_tol(), and PViewDataList::writeMSH().
printNodes()
void printNodes (fullMatrix< double > & myNodes, fullMatrix< double > & surf) inline
Definition at line 257 of file gmshLevelset.cpp.
Referenced by gLevelsetPoints::gLevelsetPoints().
removeBadChildCells()
int removeBadChildCells (cartesianBox< double > * parent)
Definition at line 75 of file gmshLevelset.cpp.
removeParentCellsWithChildren()
void removeParentCellsWithChildren (cartesianBox< double > * box)
Definition at line 120 of file gmshLevelset.cpp.