gmsh-TingyuanDoc: src/common/gmsh.cpp File Reference
gmsh.cpp File Reference
#include <sstream>
#include <regex>
#include "GmshConfig.h"
#include "GmshDefines.h"
#include "GmshGlobal.h"
#include "MallocUtils.h"
#include "GModel.h"
#include "GModelIO_GEO.h"
#include "GModelIO_OCC.h"
#include "GVertex.h"
#include "GEdge.h"
#include "GFace.h"
#include "GRegion.h"
#include "discreteVertex.h"
#include "discreteEdge.h"
#include "discreteFace.h"
#include "discreteRegion.h"
#include "partitionVertex.h"
#include "partitionEdge.h"
#include "partitionFace.h"
#include "partitionRegion.h"
#include "ghostEdge.h"
#include "ghostFace.h"
#include "ghostRegion.h"
#include "gmshSurface.h"
#include "MVertex.h"
#include "MPoint.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
#include "MVertexRTree.h"
#include "ExtrudeParams.h"
#include "StringUtils.h"
#include "Context.h"
#include "polynomialBasis.h"
#include "pyramidalBasis.h"
#include "Numeric.h"
#include "OS.h"
#include "OpenFile.h"
#include "HierarchicalBasisH1Quad.h"
#include "HierarchicalBasisH1Tria.h"
#include "HierarchicalBasisH1Line.h"
#include "HierarchicalBasisH1Brick.h"
#include "HierarchicalBasisH1Tetra.h"
#include "HierarchicalBasisH1Pri.h"
#include "HierarchicalBasisH1Point.h"
#include "HierarchicalBasisHcurlLine.h"
#include "HierarchicalBasisHcurlQuad.h"
#include "HierarchicalBasisHcurlBrick.h"
#include "HierarchicalBasisHcurlTria.h"
#include "HierarchicalBasisHcurlTetra.h"
#include "HierarchicalBasisHcurlPri.h"
#include "gmsh.h"
#include "gmshc.h"
Classes
class apiMsg
Functions
static bool _checkInit ()
static std::string _getEntityName (int dim, int tag)
static void _getEntities (const gmsh::vectorpair &dimTags, std::vector< GEntity * > &entities)
static void _getAdditionalNodesOnBoundary (GEntity *entity, std::vector< std::size_t > &nodeTags, std::vector< double > &coord, std::vector< double > &parametricCoord, bool parametric)
static void _getEntitiesForElementTypes (int dim, int tag, std::map< int, std::vector< GEntity * > > &typeEnt)
template<class T >
static void _addElements (int dim, int tag, const std::vector< MElement * > &src, std::vector< T * > &dst)
static void _addElements (int dim, int tag, GEntity *ge, int type, const std::vector< std::size_t > &elementTags, const std::vector< std::size_t > &nodeTags)
static bool _getFunctionSpaceInfo (const std::string &fsType, std::string &fsName, int &fsOrder, int &fsComp)
static bool _getIntegrationInfo (const std::string &intType, std::string &intName, int &intOrder)
int _eulerCharacteristic (GRegion *gr)
static ExtrudeParams * _getExtrudeParams (const std::vector< int > &numElements, const std::vector< double > &heights, const bool recombine)
static void _createOcc ()
template<class T >
static void _addModelData (const int tag, const int step, const std::string &modelName, const std::string &dataType, const std::vector< std::size_t > &tags, const T &data, const double time, const int numComponents, const int partition)
GMSH_API void gmshViewGetModelData (const int tag, const int step, char **dataType, size_t **tags, size_t *tags_n, double ***data, size_t **data_n, size_t *data_nn, double *time, int *numComponents, int *ierr)
Variables
static int _initialized = 0
static int _argc = 0
static char ** _argv = nullptr
Function Documentation
_addElements() [1/2]
template<class T > static void _addElements (int dim, int tag, const std::vector< MElement * > & src, std::vector< T * > & dst) static
Definition at line 1987 of file gmsh.cpp.
Referenced by _addElements().
_addElements() [2/2]
static void _addElements (int dim, int tag, GEntity * ge, int type, const std::vector< std::size_t > & elementTags, const std::vector< std::size_t > & nodeTags) static
Definition at line 1994 of file gmsh.cpp.
_addModelData()
template<class T > static void _addModelData (const int tag, const int step, const std::string & modelName, const std::string & dataType, const std::vector< std::size_t > & tags, const T & data, const double time, const int numComponents, const int partition) static
Definition at line 7129 of file gmsh.cpp.
_checkInit()
static bool _checkInit () static
Definition at line 113 of file gmsh.cpp.
Referenced by gmshViewGetModelData().
_createOcc()
static void _createOcc () static
Definition at line 6300 of file gmsh.cpp.
_eulerCharacteristic()
int _eulerCharacteristic (GRegion * gr)
Definition at line 4788 of file gmsh.cpp.
_getAdditionalNodesOnBoundary()
static void _getAdditionalNodesOnBoundary (GEntity * entity, std::vector< std::size_t > & nodeTags, std::vector< double > & coord, std::vector< double > & parametricCoord, bool parametric) static
Definition at line 1477 of file gmsh.cpp.
_getEntities()
static void _getEntities (const gmsh::vectorpair & dimTags, std::vector< GEntity * > & entities) static
Definition at line 1426 of file gmsh.cpp.
_getEntitiesForElementTypes()
static void _getEntitiesForElementTypes (int dim, int tag, std::map< int, std::vector< GEntity * > > & typeEnt) static
Definition at line 1808 of file gmsh.cpp.
_getEntityName()
static std::string _getEntityName (int dim, int tag) static
Definition at line 398 of file gmsh.cpp.
Referenced by _addElements(), _getEntities(), and _getEntitiesForElementTypes().
_getExtrudeParams()
static ExtrudeParams* _getExtrudeParams (const std::vector< int > & numElements, const std::vector< double > & heights, const bool recombine) static
Definition at line 6000 of file gmsh.cpp.
_getFunctionSpaceInfo()
static bool _getFunctionSpaceInfo (const std::string & fsType, std::string & fsName, int & fsOrder, int & fsComp) static
Definition at line 2318 of file gmsh.cpp.
_getIntegrationInfo()
static bool _getIntegrationInfo (const std::string & intType, std::string & intName, int & intOrder) static
Definition at line 4420 of file gmsh.cpp.
gmshViewGetModelData()
GMSH_API void gmshViewGetModelData (const int tag, const int step, char ** dataType, size_t ** tags, size_t * tags_n, double *** data, size_t ** data_n, size_t * data_nn, double * time, int * numComponents, int * ierr)
Definition at line 7332 of file gmsh.cpp.
Variable Documentation
_argc
int _argc = 0 static
Definition at line 110 of file gmsh.cpp.
_argv
char** _argv = nullptr static
Definition at line 111 of file gmsh.cpp.
_initialized
int _initialized = 0 static
Definition at line 109 of file gmsh.cpp.
Referenced by _checkInit().