gmsh-TingyuanDoc: src/mesh/gmshCrossFields.cpp File Reference
gmshCrossFields.cpp File Reference
#include <vector>
#include <stack>
#include <queue>
#include "OS.h"
#include "GmshConfig.h"
#include "gmshCrossFields.h"
#include "GModel.h"
#include "GFace.h"
#include "MEdge.h"
#include "MLine.h"
#include "MTriangle.h"
#include "GmshMessage.h"
#include "Context.h"
#include "meshGFaceOptimize.h"
#include "discreteEdge.h"
#include "Numeric.h"
#include "GModelParametrize.h"
Functions
static void getFacesOfTheModel (GModel *gm, std::vector< GFace * > &f)
int computeCrossFieldAndH (GModel *gm, std::vector< int > &tags)
int computeQuadLayout (GModel *gm, std::vector< int > &tags)
int computeCrossField (GModel *gm, std::vector< int > &tags)
Function Documentation
computeCrossField()
int computeCrossField (GModel * gm, std::vector< int > & tags)
Definition at line 3895 of file gmshCrossFields.cpp.
Referenced by GmshBatch().
computeCrossFieldAndH()
int computeCrossFieldAndH (GModel * gm, std::vector< int > & tags)
Definition at line 3870 of file gmshCrossFields.cpp.
Referenced by computeCrossField(), and computeQuadLayout().
computeQuadLayout()
int computeQuadLayout (GModel * gm, std::vector< int > & tags)
Definition at line 3882 of file gmshCrossFields.cpp.
getFacesOfTheModel()
static void getFacesOfTheModel (GModel * gm, std::vector< GFace * > & f) static
Definition at line 3862 of file gmshCrossFields.cpp.
Referenced by computeCrossField(), computeCrossFieldAndH(), and computeQuadLayout().