gmsh-TingyuanDoc: src/numeric/hausdorffDistance.cpp File Reference
hausdorffDistance.cpp File Reference
#include "SVector3.h"
#include "hausdorffDistance.h"
Functions
static double intersect (SPoint3 &q, SVector3 &n, SPoint3 &p1, SPoint3 &p2, SPoint3 &result)
static double projection (SPoint3 &p1, SPoint3 &p2, SPoint3 &q, SPoint3 &result)
static SPoint3 closestPoint (SPoint3 &p1, SPoint3 &p2, SPoint3 &q)
double closestPoint (const std::vector< SPoint3 > &P, const SPoint3 &p, SPoint3 &result)
double oneSidedHausdorffDistance (const std::vector< SPoint3 > &P, const std::vector< SPoint3 > &Q, SPoint3 &p1, SPoint3 &p2)
double hausdorffDistance (const std::vector< SPoint3 > &P, const std::vector< SPoint3 > &Q)
Function Documentation
closestPoint() [1/2]
double closestPoint (const std::vector< SPoint3 > & P, const SPoint3 & p, SPoint3 & result)
Definition at line 50 of file hausdorffDistance.cpp.
closestPoint() [2/2]
static SPoint3 closestPoint (SPoint3 & p1, SPoint3 & p2, SPoint3 & q) static
Definition at line 41 of file hausdorffDistance.cpp.
Referenced by closestPoint(), and oneSidedHausdorffDistance().
hausdorffDistance()
double hausdorffDistance (const std::vector< SPoint3 > & P, const std::vector< SPoint3 > & Q)
Definition at line 121 of file hausdorffDistance.cpp.
Referenced by oneSidedHausdorffDistance().
intersect()
static double intersect (SPoint3 & q, SVector3 & n, SPoint3 & p1, SPoint3 & p2, SPoint3 & result) static
Definition at line 15 of file hausdorffDistance.cpp.
Referenced by oneSidedHausdorffDistance().
oneSidedHausdorffDistance()
double oneSidedHausdorffDistance (const std::vector< SPoint3 > & P, const std::vector< SPoint3 > & Q, SPoint3 & p1, SPoint3 & p2)
Definition at line 67 of file hausdorffDistance.cpp.
Referenced by hausdorffDistance().
projection()
static double projection (SPoint3 & p1, SPoint3 & p2, SPoint3 & q, SPoint3 & result) static
Definition at line 29 of file hausdorffDistance.cpp.
Referenced by closestPoint(), CreateOutputFile(), GMSH_AnnotatePlugin::draw(), and nodalBasis::forwardTransformation().