gmsh-TingyuanDoc: src/common/libol1.h File Reference
libol1.h File Reference
Macros
#define itg int32_t
#define utg uint32_t
#define fpn double
#define call(x) x ## _
Enumerations
enum TypTag {
LolTypVer =1, LolTypEdg, LolTypTri, LolTypQad,
LolTypTet, LolTypPyr, LolTypPri, LolTypHex,
LolNmbTyp
}
Functions
int64_t LolNewOctree (itg, fpn *, fpn *, itg, itg *, itg *, itg, itg *, itg *, itg, itg *, itg *, itg, itg *, itg *, itg, itg *, itg *, itg, itg *, itg *, itg, itg *, itg *, itg, itg)
size_t LolFreeOctree (int64_t)
itg LolGetBoundingBox (int64_t, itg, itg, itg *, fpn[3], fpn[3], itg)
itg LolGetNearest (int64_t, itg, fpn *, fpn *, fpn, itg(void *, itg), void *, itg)
itg LolIntersectSurface (int64_t, fpn *, fpn *, fpn *, fpn, itg(void *, itg), void *, itg)
itg LolProjectVertex (int64_t, fpn *, itg, itg, fpn *, itg)
Macro Definition Documentation
call
#define call (x) x ## _
Definition at line 105 of file libol1.h.
fpn
#define fpn double
Definition at line 77 of file libol1.h.
itg
#define itg int32_t
Definition at line 70 of file libol1.h.
utg
#define utg uint32_t
Definition at line 71 of file libol1.h.
Enumeration Type Documentation
TypTag
enum TypTag
Enumerator
LolTypVer
LolTypEdg
LolTypTri
LolTypQad
LolTypTet
LolTypPyr
LolTypPri
LolTypHex
LolNmbTyp
Definition at line 55 of file libol1.h.
Function Documentation
LolFreeOctree()
size_t LolFreeOctree (int64_t)
Definition at line 623 of file libol1.c.
Referenced by SurfaceProjector::clear(), lolfreeoctree(), and libOLwrapper::~libOLwrapper().
LolGetBoundingBox()
itg LolGetBoundingBox (int64_t , itg , itg , itg * , fpn [3], fpn [3], itg)
Definition at line 639 of file libol1.c.
Referenced by libOLwrapper::elementsInsideBoundingBox(), and lolgetboundingbox().
LolGetNearest()
itg LolGetNearest (int64_t , itg , fpn * , fpn * , fpn , itg(void *, itg) , void * , itg)
LolIntersectSurface()
itg LolIntersectSurface (int64_t , fpn * , fpn * , fpn * , fpn , itg(void *, itg) , void * , itg)
LolNewOctree()
int64_t LolNewOctree (itg , fpn * , fpn * , itg , itg * , itg * , itg , itg * , itg * , itg , itg * , itg * , itg , itg * , itg * , itg , itg * , itg * , itg , itg * , itg * , itg , itg * , itg * , itg , itg)
Definition at line 343 of file libol1.c.
Referenced by SurfaceProjector::initialize(), libOLwrapper::libOLwrapper(), and lolnewoctree().
LolProjectVertex()
itg LolProjectVertex (int64_t , fpn * , itg , itg , fpn * , itg)
Definition at line 930 of file libol1.c.