gmsh-TingyuanDoc: src/solver/linearSystemCSR.h File Reference
linearSystemCSR.h File Reference
#include <vector>
#include <string>
#include "GmshConfig.h"
#include "GmshMessage.h"
#include "linearSystem.h"
#include "sparsityPattern.h"
Classes
struct CSRList_T
class linearSystemCSR< scalar >
class linearSystemCSRGmm< scalar >
Typedefs
typedef int INDEX_TYPE
Functions
void CSRList_Add (CSRList_T *liste, const void *data)
int CSRList_Nbr (CSRList_T *liste)
Typedef Documentation
INDEX_TYPE
typedef int INDEX_TYPE
Definition at line 16 of file linearSystemCSR.h.
Function Documentation
CSRList_Add()
void CSRList_Add (CSRList_T * liste, const void * data)
Definition at line 86 of file linearSystemCSR.cpp.
Referenced by linearSystemCSR< scalar >::addToMatrix().
CSRList_Nbr()
int CSRList_Nbr (CSRList_T * liste)
Definition at line 94 of file linearSystemCSR.cpp.
Referenced by linearSystemCSR< scalar >::addToMatrix(), linearSystemCSR< scalar >::getMatrix(), linearSystemCSR< scalar >::getNNZ(), and linearSystemCSR< scalar >::zeroMatrix().