gmsh-TingyuanDoc: src/mesh/meshGRegionDelaunayInsertion.h File Reference
meshGRegionDelaunayInsertion.h File Reference
#include <list>
#include <set>
#include <map>
#include <stack>
#include "MTetrahedron.h"
#include "Numeric.h"
#include "BackgroundMeshTools.h"
#include "qualityMeasures.h"
#include "robustPredicates.h"
Classes
class MTet4
struct compareTet4Ptr
class MTet4Factory
Functions
double tetcircumcenter (double a[3], double b[3], double c[3], double d[3], double circumcenter[3], double *xi, double *eta, double *zeta)
void connectTets (std::list< MTet4 * > &, const std::set< MFace, MFaceLessThan > *=nullptr)
void connectTets (std::vector< MTet4 * > &, const std::set< MFace, MFaceLessThan > *=nullptr)
void delaunayMeshIn3D (std::vector< MVertex * > &, std::vector< MTetrahedron * > &, bool removeBox=false)
void insertVerticesInRegion (GRegion *gr, int maxIter, double worstTetRadiusTarget, bool _classify=true, splitQuadRecovery *sqr=nullptr)
void bowyerWatsonFrontalLayers (GRegion *gr, bool hex)
void optimizeMesh (GRegion *gr, const qmTetrahedron::Measures &qm)
Function Documentation
bowyerWatsonFrontalLayers()
void bowyerWatsonFrontalLayers (GRegion * gr, bool hex)
connectTets() [1/2]
void connectTets (std::list< MTet4 * > & , const std::set< MFace, MFaceLessThan > * = nullptr)
Definition at line 277 of file meshGRegionDelaunayInsertion.cpp.
connectTets() [2/2]
void connectTets (std::vector< MTet4 * > & , const std::set< MFace, MFaceLessThan > * = nullptr)
Definition at line 283 of file meshGRegionDelaunayInsertion.cpp.
delaunayMeshIn3D()
void delaunayMeshIn3D (std::vector< MVertex * > & , std::vector< MTetrahedron * > & , bool removeBox = false)
Definition at line 1559 of file meshGRegionDelaunayInsertion.cpp.
insertVerticesInRegion()
void insertVerticesInRegion (GRegion * gr, int maxIter, double worstTetRadiusTarget, bool _classify = true, splitQuadRecovery * sqr = nullptr)
Definition at line 1217 of file meshGRegionDelaunayInsertion.cpp.
Referenced by MeshDelaunayVolume().
optimizeMesh()
void optimizeMesh (GRegion * gr, const qmTetrahedron::Measures & qm)
Definition at line 876 of file meshGRegionDelaunayInsertion.cpp.
Referenced by optimizeMeshGRegion::operator()().
tetcircumcenter()
double tetcircumcenter (double a[3], double b[3], double c[3], double d[3], double circumcenter[3], double * xi, double * eta, double * zeta)
Definition at line 1058 of file meshGRegionDelaunayInsertion.cpp.
Referenced by MTet4::circumcenter(), and insertVerticesInRegion().