gmsh-TingyuanDoc: src/mesh/meshGFaceBipartiteLabelling.h File Reference
meshGFaceBipartiteLabelling.h File Reference
Functions
void meshGFaceQuadrangulateBipartiteLabelling (int faceTag)
Function Documentation
meshGFaceQuadrangulateBipartiteLabelling()
void meshGFaceQuadrangulateBipartiteLabelling (int faceTag)
Definition at line 358 of file meshGFaceBipartiteLabelling.cpp.
Referenced by meshGenerator(), meshGeneratorPeriodic(), and RecombineMesh().