gmsh-TingyuanDoc: src/mesh/meshPartition.h File Reference
meshPartition.h File Reference
Functions
int PartitionMesh (GModel *model, int numPart)
int UnpartitionMesh (GModel *model)
int PartitionUsingThisSplit (GModel *model, std::vector< std::pair< MElement *, int > > &elmToPartition)
int ConvertOldPartitioningToNewOne (GModel *model)
int PartitionFaceMinEdgeLength (GFace *gf, int np, double tol=1.02)
Function Documentation
ConvertOldPartitioningToNewOne()
int ConvertOldPartitioningToNewOne (GModel * model)
Definition at line 2654 of file meshPartition.cpp.
Referenced by GModel::convertOldPartitioningToNewOne().
PartitionFaceMinEdgeLength()
int PartitionFaceMinEdgeLength (GFace * gf, int np, double tol = 1.02)
Definition at line 2663 of file meshPartition.cpp.
Referenced by computeEdgeCut().
PartitionMesh()
int PartitionMesh (GModel * model, int numPart)
Definition at line 2646 of file meshPartition.cpp.
Referenced by GModel::partitionMesh().
PartitionUsingThisSplit()
int PartitionUsingThisSplit (GModel * model, std::vector< std::pair< MElement *, int > > & elmToPartition)
Definition at line 2656 of file meshPartition.cpp.
Referenced by GModel::partitionMesh(), and GMSH_SimplePartitionPlugin::run().
UnpartitionMesh()
int UnpartitionMesh (GModel * model)
Definition at line 2652 of file meshPartition.cpp.
Referenced by GModel::partitionMesh(), and GModel::unpartitionMesh().