gmsh-TingyuanDoc: src/mesh/meshRefine.cpp File Reference
meshRefine.cpp File Reference
#include "GModel.h"
#include "HighOrder.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
#include "GmshMessage.h"
#include "OS.h"
#include "meshGFaceOptimize.h"
#include "Generator.h"
#include "Context.h"
Classes
struct MVertexPtrLessThanParam
Typedefs
typedef std::map< MFace, std::vector< MVertex * >, MFaceLessThan > faceContainer
Functions
void subdivide_pyramid (MElement *element, GRegion *gr, faceContainer &faceVertices, std::vector< MHexahedron * > &dwarfs88)
static void setBLData (MVertex *v)
static bool setBLData (MElement *el)
static void Subdivide (GEdge *ge)
static void Subdivide (GFace *gf, bool splitIntoQuads, bool splitIntoHexas, faceContainer &faceVertices, bool linear)
static void Subdivide (GRegion *gr, bool splitIntoHexas, faceContainer &faceVertices)
void RefineMesh (GModel *m, bool linear, bool splitIntoQuads, bool splitIntoHexas)
void BarycentricRefineMesh (GModel *m)
static double schneiders_x (int i)
static double schneiders_y (int i)
static double schneiders_z (int i)
static int schneiders_connect (int i, int j)
Typedef Documentation
faceContainer
typedef std::map<MFace, std::vector<MVertex *>, MFaceLessThan> faceContainer
Definition at line 25 of file meshRefine.cpp.
Function Documentation
BarycentricRefineMesh()
void BarycentricRefineMesh (GModel * m)
Definition at line 507 of file meshRefine.cpp.
Referenced by GenerateMesh(), and GModel::refineMesh().
RefineMesh()
void RefineMesh (GModel * m, bool linear, bool splitIntoQuads, bool splitIntoHexas)
Definition at line 463 of file meshRefine.cpp.
Referenced by GenerateMesh(), and GModel::refineMesh().
schneiders_connect()
static int schneiders_connect (int i, int j) static
Definition at line 638 of file meshRefine.cpp.
Referenced by subdivide_pyramid().
schneiders_x()
static double schneiders_x (int i) static
Definition at line 572 of file meshRefine.cpp.
Referenced by subdivide_pyramid().
schneiders_y()
static double schneiders_y (int i) static
Definition at line 594 of file meshRefine.cpp.
Referenced by subdivide_pyramid().
schneiders_z()
static double schneiders_z (int i) static
Definition at line 616 of file meshRefine.cpp.
Referenced by subdivide_pyramid().
setBLData() [1/2]
static bool setBLData (MElement * el) static
Definition at line 60 of file meshRefine.cpp.
setBLData() [2/2]
static void setBLData (MVertex * v) static
Definition at line 42 of file meshRefine.cpp.
Referenced by setBLData(), and Subdivide().
Subdivide() [1/3]
static void Subdivide (GEdge * ge) static
Definition at line 88 of file meshRefine.cpp.
Referenced by RefineMesh().
Subdivide() [2/3]
static void Subdivide (GFace * gf, bool splitIntoQuads, bool splitIntoHexas, faceContainer & faceVertices, bool linear) static
Definition at line 113 of file meshRefine.cpp.
Subdivide() [3/3]
static void Subdivide (GRegion * gr, bool splitIntoHexas, faceContainer & faceVertices) static
Definition at line 192 of file meshRefine.cpp.
subdivide_pyramid()
void subdivide_pyramid (MElement * element, GRegion * gr, faceContainer & faceVertices, std::vector< MHexahedron * > & dwarfs88)
Definition at line 722 of file meshRefine.cpp.
Referenced by Subdivide().