gmsh-TingyuanDoc: src/mesh/meshTriangulation.h File Reference
meshTriangulation.h File Reference
#include "meshPolyMesh.h"
Functions
PolyMesh * GFaceInitialMesh (int faceTag, int recover=0, std::vector< double > *additional=nullptr)
void GFaceDelaunayRefinementOldMesher (int faceTag)
void GFaceDelaunayRefinement (int faceTag)
int GFace2PolyMesh (int faceTag, PolyMesh **pm)
int PolyMesh2GFace (PolyMesh *pm, int faceTag)
Function Documentation
GFace2PolyMesh()
int GFace2PolyMesh (int faceTag, PolyMesh ** pm)
Definition at line 195 of file meshTriangulation.cpp.
Referenced by computePointsUsingScaledCrossFieldPlanarP2().
GFaceDelaunayRefinement()
void GFaceDelaunayRefinement (int faceTag)
GFaceDelaunayRefinementOldMesher()
void GFaceDelaunayRefinementOldMesher (int faceTag)
Definition at line 596 of file meshTriangulation.cpp.
GFaceInitialMesh()
PolyMesh* GFaceInitialMesh (int faceTag, int recover = 0, std::vector< double > * additional = nullptr)
Definition at line 753 of file meshTriangulation.cpp.
Referenced by computePointsUsingScaledCrossFieldPlanarP2(), GFaceDelaunayRefinement(), GFaceDelaunayRefinementOldMesher(), and meshGenerator().
PolyMesh2GFace()
int PolyMesh2GFace (PolyMesh * pm, int faceTag)
Definition at line 88 of file meshTriangulation.cpp.
Referenced by computePointsUsingScaledCrossFieldPlanarP2().