gmsh-TingyuanDoc: src/mesh/meshOctreeLibOL.cpp File Reference
meshOctreeLibOL.cpp File Reference
#include "meshOctreeLibOL.h"
#include "GFace.h"
#include "discreteFace.h"
#include "MVertex.h"
#include "MTriangle.h"
#include "OS.h"
#include "libol1.h"
#include "robin_hood.h"
Namespaces
SurfaceProjectorUtils
Typedefs
using SurfaceProjectorUtils::vec2 = std::array< double, 2 >
using SurfaceProjectorUtils::vec3 = std::array< double, 3 >
Functions
vec3 SurfaceProjectorUtils::operator- (const vec3 &a, const vec3 &b)
vec3 SurfaceProjectorUtils::operator+ (const vec3 &a, const vec3 &b)
vec3 SurfaceProjectorUtils::operator* (const double &a, const vec3 &b)
vec3 SurfaceProjectorUtils::operator* (const vec3 &a, const double &b)
double SurfaceProjectorUtils::dot (const vec3 &a, const vec3 &b)
double SurfaceProjectorUtils::length2 (const vec3 &a)
double SurfaceProjectorUtils::maxAbs (double x, double y, double z)
double SurfaceProjectorUtils::maxAbs (const vec3 &a)
void SurfaceProjectorUtils::normalizeFast (vec3 &a)
void SurfaceProjectorUtils::normalize (vec3 &a)
double SurfaceProjectorUtils::project_point_segment_l2 (const vec3 &query, const vec3 &a, const vec3 &b, vec3 &proj, double &lambda)
double SurfaceProjectorUtils::project_point_triangle_l2 (const vec3 &query, const vec3 &p1, const vec3 &p2, const vec3 &p3, vec3 &proj, double lambda[3])
GPoint failedProjection ()
GPoint sphereProjection (GFace *gf, const double query[3], const std::array< double, 10 > &analyticalParameters)
Function Documentation
failedProjection()
GPoint failedProjection ()
Definition at line 545 of file meshOctreeLibOL.cpp.
Referenced by SurfaceProjector::closestPoint(), and sphereProjection().
sphereProjection()
GPoint sphereProjection (GFace * gf, const double query[3], const std::array< double, 10 > & analyticalParameters)
Definition at line 552 of file meshOctreeLibOL.cpp.
Referenced by SurfaceProjector::closestPoint().