gmsh-TingyuanDoc: src/mesh/meshGFace.h File Reference
meshGFace.h File Reference
#include <vector>
#include <set>
#include <list>
#include "SPoint2.h"
#include "SVector3.h"
#include "MElementOctree.h"
Classes
class meshGFace
class deMeshGFace
class orientMeshGFace
Functions
void findTransfiniteCorners (GFace *gf, std::vector< MVertex * > &corners)
int MeshTransfiniteSurface (GFace *gf)
int MeshExtrudedSurface (GFace *gf, std::set< std::pair< MVertex *, MVertex * > > *constrainedEdges=nullptr)
bool pointInsideParametricDomain (std::vector< SPoint2 > &bnd, SPoint2 &p, SPoint2 &out, int &N)
bool MeshSetTransfiniteFacesAutomatic (std::set< GFace * > &candidate_faces, double cornerAngle=2.35, bool setRecombine=true, double maxDiffRel=1., bool ignoreEmbedded=false)
Automatically set transfinite constraints on curves and faces in the candidate_faces if possible. Curves on opposide sides of rectangular faces are constrained to reiceive the same number of points.
Function Documentation
findTransfiniteCorners()
void findTransfiniteCorners (GFace * gf, std::vector< MVertex * > & corners)
Definition at line 46 of file meshGFaceTransfinite.cpp.
Referenced by MeshTransfiniteSurface().
MeshExtrudedSurface()
int MeshExtrudedSurface (GFace * gf, std::set< std::pair< MVertex *, MVertex * > > * constrainedEdges = nullptr)
Definition at line 291 of file meshGFaceExtruded.cpp.
Referenced by Mesh2DWithBoundaryLayers(), meshGFace::operator()(), and SubdivideExtrudedMesh().
MeshSetTransfiniteFacesAutomatic()
bool MeshSetTransfiniteFacesAutomatic (std::set< GFace * > & candidate_faces, double cornerAngle = 2.35, bool setRecombine = true, double maxDiffRel = 1., bool ignoreEmbedded = false)
Automatically set transfinite constraints on curves and faces in the candidate_faces if possible. Curves on opposide sides of rectangular faces are constrained to reiceive the same number of points.
Parameters
candidate_faces The faces which are candidate for transfinite
cornerAngle Threshold on the angle (viewed from face) at corners
setRecombine If true, quads will be built instead of triangles when meshing
maxDiffRel Reject transfinite constraints if the relative difference on the initial number of lines (from sizing constraints) on opposite sides is larger than the maxDiffRel
ignoreEmbedded If true, ignore embedded edges and vertices in faces
Returns
true if success
Definition at line 817 of file meshGFaceTransfinite.cpp.
Referenced by GenerateMesh().
MeshTransfiniteSurface()
int MeshTransfiniteSurface (GFace * gf)
Definition at line 166 of file meshGFaceTransfinite.cpp.
Referenced by meshGFace::operator()().
pointInsideParametricDomain()
bool pointInsideParametricDomain (std::vector< SPoint2 > & bnd, SPoint2 & p, SPoint2 & out, int & N)
Definition at line 43 of file meshGFace.cpp.
Referenced by bowyerWatsonFrontal(), and splitEdgePass().