gmsh-TingyuanDoc: src/mesh/meshGRegion.cpp File Reference
meshGRegion.cpp File Reference
#include "meshGRegion.h"
#include "Context.h"
#include "ExtrudeParams.h"
#include "GEdge.h"
#include "GFace.h"
#include "GModel.h"
#include "GRegion.h"
#include "GmshConfig.h"
#include "GmshMessage.h"
#include "MLine.h"
#include "MPyramid.h"
#include "MTetrahedron.h"
#include "MTriangle.h"
#include "OS.h"
#include "discreteEdge.h"
#include "discreteFace.h"
#include "meshGFace.h"
#include "meshGFaceOptimize.h"
#include "meshGRegionBoundaryRecovery.h"
#include "meshGRegionDelaunayInsertion.h"
#include "meshGRegionHxt.h"
#include "meshGRegionMMG.h"
#include "meshGRegionNetgen.h"
#include "meshRelocateVertex.h"
#include <stdlib.h>
#include <vector>
Functions
void MeshDelaunayVolume (std::vector< GRegion * > &regions)
bool buildFaceSearchStructure (GModel *model, fs_cont &search, bool onlyTriangles)
bool buildEdgeSearchStructure (GModel *model, es_cont &search)
GFace * findInFaceSearchStructure (MVertex *p1, MVertex *p2, MVertex *p3, const fs_cont &search)
GFace * findInFaceSearchStructure (const MFace &ff, const fs_cont &search)
GEdge * findInEdgeSearchStructure (MVertex *p1, MVertex *p2, const es_cont &search)
Function Documentation
buildEdgeSearchStructure()
bool buildEdgeSearchStructure (GModel * model, es_cont & search)
Definition at line 313 of file meshGRegion.cpp.
buildFaceSearchStructure()
bool buildFaceSearchStructure (GModel * model, fs_cont & search, bool onlyTriangles)
Definition at line 286 of file meshGRegion.cpp.
Referenced by insertVerticesInRegion(), and MakeMeshConformal().
findInEdgeSearchStructure()
GEdge* findInEdgeSearchStructure (MVertex * p1, MVertex * p2, const es_cont & search)
Definition at line 350 of file meshGRegion.cpp.
findInFaceSearchStructure() [1/2]
GFace* findInFaceSearchStructure (const MFace & ff, const fs_cont & search)
Definition at line 342 of file meshGRegion.cpp.
findInFaceSearchStructure() [2/2]
GFace* findInFaceSearchStructure (MVertex * p1, MVertex * p2, MVertex * p3, const fs_cont & search)
Definition at line 333 of file meshGRegion.cpp.
Referenced by MakeMeshConformal(), and non_recursive_classify().
MeshDelaunayVolume()
void MeshDelaunayVolume (std::vector< GRegion * > & regions)
Definition at line 95 of file meshGRegion.cpp.
Referenced by Mesh3D().