gmsh-TingyuanDoc: src/mesh/meshGFaceBDS.h File Reference
meshGFaceBDS.h File Reference
#include <map>
#include <list>
#include "BDS.h"
Functions
void refineMeshBDS (GFace *gf, BDS_Mesh &m, const int NIT, const bool computeNodalSizeField, std::map< MVertex *, BDS_Point * > *recoverMapInv=0, std::map< BDS_Point *, MVertex *, PointLessThan > *recoverMap=0, std::vector< SPoint2 > *true_boundary=0)
void modifyInitialMeshToRemoveDegeneracies (GFace *gf, BDS_Mesh &m, std::map< BDS_Point *, MVertex *, PointLessThan > *recoverMap)
void delaunayizeBDS (GFace *gf, BDS_Mesh &m, int &nb_swap)
Function Documentation
delaunayizeBDS()
void delaunayizeBDS (GFace * gf, BDS_Mesh & m, int & nb_swap)
Definition at line 236 of file meshGFaceBDS.cpp.
Referenced by meshGenerator(), and meshGeneratorPeriodic().
modifyInitialMeshToRemoveDegeneracies()
void modifyInitialMeshToRemoveDegeneracies (GFace * gf, BDS_Mesh & m, std::map< BDS_Point *, MVertex *, PointLessThan > * recoverMap)
Definition at line 690 of file meshGFaceBDS.cpp.
Referenced by meshGeneratorPeriodic().
refineMeshBDS()
void refineMeshBDS (GFace * gf, BDS_Mesh & m, const int NIT, const bool computeNodalSizeField, std::map< MVertex *, BDS_Point * > * recoverMapInv = 0, std::map< BDS_Point *, MVertex *, PointLessThan > * recoverMap = 0, std::vector< SPoint2 > * true_boundary = 0)
Definition at line 726 of file meshGFaceBDS.cpp.
Referenced by meshGenerator(), and meshGeneratorPeriodic().