gmsh-TingyuanDoc: src/mesh/meshGEdgeExtruded.cpp File Reference
meshGEdgeExtruded.cpp File Reference
#include <set>
#include "GModel.h"
#include "MLine.h"
#include "ExtrudeParams.h"
#include "GmshMessage.h"
Functions
static void createElements (GEdge *ge)
static void extrudeMesh (GVertex *from, GEdge *to)
static void copyMesh (GEdge *from, GEdge *to)
int MeshExtrudedCurve (GEdge *ge)
Function Documentation
copyMesh()
static void copyMesh (GEdge * from, GEdge * to) static
Definition at line 46 of file meshGEdgeExtruded.cpp.
Referenced by MeshExtrudedCurve().
createElements()
static void createElements (GEdge * ge) static
Definition at line 12 of file meshGEdgeExtruded.cpp.
Referenced by copyMesh(), and extrudeMesh().
extrudeMesh()
static void extrudeMesh (GVertex * from, GEdge * to) static
Definition at line 26 of file meshGEdgeExtruded.cpp.
Referenced by MeshExtrudedCurve(), scriptExtrude(), and scriptProtude().
MeshExtrudedCurve()
int MeshExtrudedCurve (GEdge * ge)
Definition at line 92 of file meshGEdgeExtruded.cpp.
Referenced by Mesh2DWithBoundaryLayers(), and meshGEdge::operator()().