gmsh-TingyuanDoc: src/mesh/meshGFaceExtruded.cpp File Reference
meshGFaceExtruded.cpp File Reference
#include <set>
#include "GmshConfig.h"
#include "GModel.h"
#include "MLine.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "ExtrudeParams.h"
#include "MVertexRTree.h"
#include "Context.h"
#include "GmshMessage.h"
Functions
static void addTriangle (MVertex *v1, MVertex *v2, MVertex *v3, GFace *to)
static void addQuadrangle (MVertex *v1, MVertex *v2, MVertex *v3, MVertex *v4, GFace *to)
static void createQuaTri (std::vector< MVertex * > &v, GFace *to, std::set< std::pair< MVertex *, MVertex * > > *constrainedEdges, MLine *source, int tri_quad_flag)
static void extrudeMesh (GEdge *from, GFace *to, MVertexRTree &pos, std::set< std::pair< MVertex *, MVertex * > > *constrainedEdges)
static void copyMesh (GFace *from, GFace *to, MVertexRTree &pos)
int MeshExtrudedSurface (GFace *gf, std::set< std::pair< MVertex *, MVertex * > > *constrainedEdges)
Function Documentation
addQuadrangle()
static void addQuadrangle (MVertex * v1, MVertex * v2, MVertex * v3, MVertex * v4, GFace * to) static
Definition at line 26 of file meshGFaceExtruded.cpp.
Referenced by copyMesh(), and createQuaTri().
addTriangle()
static void addTriangle (MVertex * v1, MVertex * v2, MVertex * v3, GFace * to) static
Definition at line 21 of file meshGFaceExtruded.cpp.
Referenced by classifyFaces(), copyMesh(), and createQuaTri().
copyMesh()
static void copyMesh (GFace * from, GFace * to, MVertexRTree & pos) static
Definition at line 177 of file meshGFaceExtruded.cpp.
Referenced by MeshExtrudedSurface().
createQuaTri()
static void createQuaTri (std::vector< MVertex * > & v, GFace * to, std::set< std::pair< MVertex *, MVertex * > > * constrainedEdges, MLine * source, int tri_quad_flag) static
Definition at line 33 of file meshGFaceExtruded.cpp.
Referenced by extrudeMesh().
extrudeMesh()
static void extrudeMesh (GEdge * from, GFace * to, MVertexRTree & pos, std::set< std::pair< MVertex *, MVertex * > > * constrainedEdges) static
Definition at line 86 of file meshGFaceExtruded.cpp.
Referenced by MeshExtrudedSurface().
MeshExtrudedSurface()
int MeshExtrudedSurface (GFace * gf, std::set< std::pair< MVertex *, MVertex * > > * constrainedEdges)
Definition at line 291 of file meshGFaceExtruded.cpp.
Referenced by Mesh2DWithBoundaryLayers(), meshGFace::operator()(), and SubdivideExtrudedMesh().