gmsh-TingyuanDoc: src/mesh/meshTriangulation.cpp File Reference
meshTriangulation.cpp File Reference
#include <utility>
#include <list>
#include <map>
#include <unordered_map>
#include "Context.h"
#include "gmsh.h"
#include "GModel.h"
#include "GFace.h"
#include "GEdge.h"
#include "MLine.h"
#include "MVertex.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "meshTriangulation.h"
#include "SBoundingBox3d.h"
#include "robustPredicates.h"
#include "meshGFaceDelaunayInsertion.h"
#include "qualityMeasures.h"
#include "Numeric.h"
#include "SPoint3.h"
Classes
struct pair_hash
struct nodeCopies
Functions
void swap (double &a, double &b)
size_t HilbertCoordinates (double x, double y, double x0, double y0, double xRed, double yRed, double xBlue, double yBlue)
int PolyMesh2GFace (PolyMesh *pm, int faceTag)
int GFace2PolyMesh (int faceTag, PolyMesh **pm)
static int delaunayEdgeCriterionPlaneIsotropic (PolyMesh::HalfEdge *he, void *)
static void faceCircumCenter (PolyMesh::HalfEdge *he, GFace *gf, double *res, double *uv)
static double faceQuality (PolyMesh::HalfEdge *he, GFace *gf)
static PolyMesh::Face * Walk (PolyMesh::Face *f, double x, double y)
static int intersect (PolyMesh::Vertex *v0, PolyMesh::Vertex *v1, PolyMesh::Vertex *b0, PolyMesh::Vertex *b1)
static int recover_edge (PolyMesh *pm, PolyMesh::Vertex *v_start, PolyMesh::Vertex *v_end)
static PolyMesh::HalfEdge * Color (PolyMesh::HalfEdge *he, int color)
void GFaceDelaunayRefinement (size_t faceTag)
void GFaceDelaunayRefinementOldMesher (int faceTag)
static void getNodeCopies (GFace *gf, std::unordered_map< size_t, nodeCopies > &copies)
void addPoints (PolyMesh *pm, std::vector< double > &pts, SBoundingBox3d &bb)
PolyMesh * GFaceInitialMesh (int faceTag, int recover, std::vector< double > *additional)
Function Documentation
addPoints()
void addPoints (PolyMesh * pm, std::vector< double > & pts, SBoundingBox3d & bb)
Definition at line 728 of file meshTriangulation.cpp.
Referenced by GFaceInitialMesh().
Color()
static PolyMesh::HalfEdge* Color (PolyMesh::HalfEdge * he, int color) static
Definition at line 515 of file meshTriangulation.cpp.
Referenced by GFaceInitialMesh().
delaunayEdgeCriterionPlaneIsotropic()
static int delaunayEdgeCriterionPlaneIsotropic (PolyMesh::HalfEdge * he, void *) static
Definition at line 288 of file meshTriangulation.cpp.
Referenced by addPoints(), GFaceDelaunayRefinement(), and GFaceInitialMesh().
faceCircumCenter()
static void faceCircumCenter (PolyMesh::HalfEdge * he, GFace * gf, double * res, double * uv) static
Definition at line 303 of file meshTriangulation.cpp.
Referenced by GFaceDelaunayRefinement().
faceQuality()
static double faceQuality (PolyMesh::HalfEdge * he, GFace * gf) static
Definition at line 318 of file meshTriangulation.cpp.
Referenced by GFaceDelaunayRefinement().
getNodeCopies()
static void getNodeCopies (GFace * gf, std::unordered_map< size_t, nodeCopies > & copies) static
Definition at line 655 of file meshTriangulation.cpp.
Referenced by GFaceInitialMesh().
GFace2PolyMesh()
int GFace2PolyMesh (int faceTag, PolyMesh ** pm)
Definition at line 195 of file meshTriangulation.cpp.
Referenced by computePointsUsingScaledCrossFieldPlanarP2().
GFaceDelaunayRefinement()
void GFaceDelaunayRefinement (size_t faceTag)
Definition at line 541 of file meshTriangulation.cpp.
GFaceDelaunayRefinementOldMesher()
void GFaceDelaunayRefinementOldMesher (int faceTag)
Definition at line 596 of file meshTriangulation.cpp.
GFaceInitialMesh()
PolyMesh* GFaceInitialMesh (int faceTag, int recover, std::vector< double > * additional)
Definition at line 753 of file meshTriangulation.cpp.
Referenced by computePointsUsingScaledCrossFieldPlanarP2(), GFaceDelaunayRefinement(), GFaceDelaunayRefinementOldMesher(), and meshGenerator().
HilbertCoordinates()
size_t HilbertCoordinates (double x, double y, double x0, double y0, double xRed, double yRed, double xBlue, double yBlue)
Definition at line 34 of file meshTriangulation.cpp.
Referenced by addPoints().
intersect()
static int intersect (PolyMesh::Vertex * v0, PolyMesh::Vertex * v1, PolyMesh::Vertex * b0, PolyMesh::Vertex * b1) static
Definition at line 416 of file meshTriangulation.cpp.
Referenced by GFaceInitialMesh(), and recover_edge().
PolyMesh2GFace()
int PolyMesh2GFace (PolyMesh * pm, int faceTag)
Definition at line 88 of file meshTriangulation.cpp.
Referenced by computePointsUsingScaledCrossFieldPlanarP2().
recover_edge()
static int recover_edge (PolyMesh * pm, PolyMesh::Vertex * v_start, PolyMesh::Vertex * v_end) static
Definition at line 432 of file meshTriangulation.cpp.
Referenced by GFaceInitialMesh().
swap()
void swap (double & a, double & b)
Definition at line 27 of file meshTriangulation.cpp.
Referenced by onelab::remoteNetworkClient::_get(), GModel::_readMSH2(), GModel::_readMSH3(), GModel::_readMSH4(), GFace::alignElementsWithMaster(), GModel::alignPeriodicBoundaries(), bezierCoeff::bezierCoeff(), MFace::computeCorrespondence(), cVecRead(), VertexArray::decodeHeader(), GModel::destroyMeshCaches(), dVecRead(), GMSH_TransformPlugin::execute(), PView::fillVertexArray(), VertexArray::fromChar(), getFaceVertices(), MTriangle::getHighOrderFace(), MQuadrangle::getHighOrderFace(), MTriangle6::getHighOrderFace(), MQuadrangle8::getHighOrderFace(), MTriangleN::getHighOrderFace(), MQuadrangle9::getHighOrderFace(), MQuadrangleN::getHighOrderFace(), HilbertCoordinates(), phase2(), PView::readMSH(), PViewDataGModel::readMSH(), readMSH4BoundingEntities(), readMSH4Elements(), readMSH4Entities(), readMSH4EntityInfo(), readMSH4GhostElements(), readMSH4Nodes(), readMSH4PeriodicNodes(), readMSH4Physicals(), GModel::readPLY(), PViewDataList::readPOS(), GModel::readSTL(), GmshSocket::ReceiveHeader(), MTriangle::reorient(), MQuadrangle::reorient(), MTriangle6::reorient(), MQuadrangle8::reorient(), MQuadrangle9::reorient(), MTriangleN::reorient(), MQuadrangleN::reorient(), reorientQuadPoints(), reorientTrianglePoints(), SubdivideExtrudedMesh(), and onelab::remoteNetworkClient::waitOnSubClients().
Walk()
static PolyMesh::Face* Walk (PolyMesh::Face * f, double x, double y) static
Definition at line 362 of file meshTriangulation.cpp.
Referenced by addPoints(), GFaceDelaunayRefinement(), and GFaceInitialMesh().