gmsh-TingyuanDoc: src/mesh/meshGEdge.h File Reference
meshGEdge.h File Reference
Classes
struct meshGEdge
struct deMeshGEdge
struct orientMeshGEdge
Functions
int MeshExtrudedCurve (GEdge *ge)
int meshGEdgeTargetNumberOfPoints (GEdge *)
Function Documentation
MeshExtrudedCurve()
int MeshExtrudedCurve (GEdge * ge)
Definition at line 92 of file meshGEdgeExtruded.cpp.
Referenced by Mesh2DWithBoundaryLayers(), and meshGEdge::operator()().
meshGEdgeTargetNumberOfPoints()
int meshGEdgeTargetNumberOfPoints (GEdge *)
Definition at line 980 of file meshGEdge.cpp.
Referenced by build_chords(), and MeshSetTransfiniteFacesAutomatic().