gmsh-TingyuanDoc: src/mesh/meshGRegionLocalMeshMod.h File Reference
meshGRegionLocalMeshMod.h File Reference
#include "meshGRegionDelaunayInsertion.h"
#include "qualityMeasures.h"
Enumerations
enum localMeshModAction { GMSH_DOIT, GMSH_EVALONLY }
Functions
int LaplaceSmoothing (GRegion *gr)
bool edgeSwap (std::vector< MTet4 * > &newTets, MTet4 *tet, int iLocalEdge, const qmTetrahedron::Measures &cr, const std::set< MFace, MFaceLessThan > &embeddedFaces)
bool faceSwap (std::vector< MTet4 * > &newTets, MTet4 *tet, int iLocalFace, const qmTetrahedron::Measures &cr, const std::set< MFace, MFaceLessThan > &embeddedFaces)
bool smoothVertex (MTet4 *t, int iLocalVertex, const qmTetrahedron::Measures &cr)
bool smoothVertexOptimize (MTet4 *t, int iVertex, const qmTetrahedron::Measures &cr)
bool collapseVertex (std::vector< MTet4 * > &newTets, MTet4 *t, int iVertex, int iTarget, const qmTetrahedron::Measures &cr, const localMeshModAction=GMSH_DOIT, double *result=nullptr)
bool edgeSplit (std::vector< MTet4 * > &newTets, MTet4 *tet, MVertex *newVertex, int iLocalEdge, const qmTetrahedron::Measures &cr)
Enumeration Type Documentation
localMeshModAction
enum localMeshModAction
Enumerator
GMSH_DOIT
GMSH_EVALONLY
Definition at line 15 of file meshGRegionLocalMeshMod.h.
Function Documentation
collapseVertex()
bool collapseVertex (std::vector< MTet4 * > & newTets, MTet4 * t, int iVertex, int iTarget, const qmTetrahedron::Measures & cr, const localMeshModAction = GMSH_DOIT, double * result = nullptr)
Definition at line 529 of file meshGRegionLocalMeshMod.cpp.
Referenced by adaptMeshGRegion::operator()().
edgeSplit()
bool edgeSplit (std::vector< MTet4 * > & newTets, MTet4 * tet, MVertex * newVertex, int iLocalEdge, const qmTetrahedron::Measures & cr)
Definition at line 355 of file meshGRegionLocalMeshMod.cpp.
edgeSwap()
bool edgeSwap (std::vector< MTet4 * > & newTets, MTet4 * tet, int iLocalEdge, const qmTetrahedron::Measures & cr, const std::set< MFace, MFaceLessThan > & embeddedFaces)
Definition at line 237 of file meshGRegionLocalMeshMod.cpp.
Referenced by adaptMeshGRegion::operator()(), and optimizeMesh().
faceSwap()
bool faceSwap (std::vector< MTet4 * > & newTets, MTet4 * tet, int iLocalFace, const qmTetrahedron::Measures & cr, const std::set< MFace, MFaceLessThan > & embeddedFaces)
Definition at line 390 of file meshGRegionLocalMeshMod.cpp.
Referenced by adaptMeshGRegion::operator()().
LaplaceSmoothing()
int LaplaceSmoothing (GRegion * gr)
Definition at line 828 of file meshGRegionLocalMeshMod.cpp.
smoothVertex()
bool smoothVertex (MTet4 * t, int iLocalVertex, const qmTetrahedron::Measures & cr)
Definition at line 624 of file meshGRegionLocalMeshMod.cpp.
Referenced by insertVerticesInRegion(), adaptMeshGRegion::operator()(), and optimizeMesh().
smoothVertexOptimize()
bool smoothVertexOptimize (MTet4 * t, int iVertex, const qmTetrahedron::Measures & cr)
Definition at line 757 of file meshGRegionLocalMeshMod.cpp.