gmsh-TingyuanDoc: src/mesh/meshRelocateVertex.h File Reference
meshRelocateVertex.h File Reference
#include <vector>
Functions
void RelocateVertices (GRegion *region, int niter, double tol=1.e-2)
void RelocateVertices (std::vector< GRegion * > &regions, int niter, double tol=1.e-2)
void RelocateVertices (GFace *, int niter, double tol=1.e-6)
void RelocateVerticesOfPyramids (GRegion *region, int niter, double tol=1.e-2)
void RelocateVerticesOfPyramids (std::vector< GRegion * > &regions, int niter, double tol=1.e-2)
Function Documentation
RelocateVertices() [1/3]
void RelocateVertices (GFace * , int niter, double tol = 1.e-6)
Definition at line 410 of file meshRelocateVertex.cpp.
Referenced by Mesh3D(), OptimizeMesh(), recombineIntoQuads(), and RelocateVertices().
RelocateVertices() [2/3]
void RelocateVertices (GRegion * region, int niter, double tol = 1.e-2)
Definition at line 432 of file meshRelocateVertex.cpp.
RelocateVertices() [3/3]
void RelocateVertices (std::vector< GRegion * > & regions, int niter, double tol = 1.e-2)
Definition at line 525 of file meshRelocateVertex.cpp.
RelocateVerticesOfPyramids() [1/2]
void RelocateVerticesOfPyramids (GRegion * region, int niter, double tol = 1.e-2)
Definition at line 451 of file meshRelocateVertex.cpp.
Referenced by MeshDelaunayVolume(), and RelocateVerticesOfPyramids().
RelocateVerticesOfPyramids() [2/2]
void RelocateVerticesOfPyramids (std::vector< GRegion * > & regions, int niter, double tol = 1.e-2)
Definition at line 517 of file meshRelocateVertex.cpp.