gmsh-TingyuanDoc: src/mesh/meshGFaceOptimize.h File Reference
meshGFaceOptimize.h File Reference
#include <map>
#include <vector>
#include "MElement.h"
#include "MEdge.h"
#include "meshGFaceDelaunayInsertion.h"
#include "STensor3.h"
Classes
struct edge_angle
struct swapquad
struct RecombineTriangle
Typedefs
typedef std::map< MVertex *, std::vector< MElement * >, MVertexPtrLessThan > v2t_cont
typedef std::map< MEdge, std::pair< MElement *, MElement * >, MEdgeLessThan > e2t_cont
Functions
template<class T >
void buildVertexToElement (std::vector< T * > const &elements, v2t_cont &adj)
template<class T >
void buildEdgeToElement (std::vector< T * > &eles, e2t_cont &adj)
void buildEdgeToTriangle (std::vector< MTriangle * > &, e2t_cont &adj)
void buildListOfEdgeAngle (e2t_cont adj, std::vector< edge_angle > &edges_detected, std::vector< edge_angle > &edges_lonly)
void buildEdgeToElements (std::vector< MElement * > &tris, e2t_cont &adj)
void laplaceSmoothing (GFace *gf, int niter=1, bool infinity_norm=false)
bool buildMeshGenerationDataStructures (GFace *gf, std::set< MTri3 *, compareTri3Ptr > &AllTris, bidimMeshData &data)
void transferDataStructure (GFace *gf, std::set< MTri3 *, compareTri3Ptr > &AllTris, bidimMeshData &DATA)
void computeEquivalences (GFace *gf, bidimMeshData &DATA)
void recombineIntoQuads (GFace *gf, bool blossom, int topologicalOptiPasses, bool nodeRepositioning, double minqual)
void quadsToTriangles (GFace *gf, double minqual)
void splitElementsInBoundaryLayerIfNeeded (GFace *gf)
Typedef Documentation
e2t_cont
typedef std::map<MEdge, std::pair<MElement *, MElement *>, MEdgeLessThan> e2t_cont
Definition at line 35 of file meshGFaceOptimize.h.
v2t_cont
typedef std::map<MVertex *, std::vector<MElement *>, MVertexPtrLessThan> v2t_cont
Definition at line 31 of file meshGFaceOptimize.h.
Function Documentation
buildEdgeToElement()
template<class T > void buildEdgeToElement (std::vector< T * > & eles, e2t_cont & adj)
Definition at line 417 of file meshGFaceOptimize.cpp.
Referenced by _recombineIntoQuads(), buildEdgeToElement(), buildEdgeToElements(), and buildEdgeToTriangle().
buildEdgeToElements()
void buildEdgeToElements (std::vector< MElement * > & tris, e2t_cont & adj)
Definition at line 449 of file meshGFaceOptimize.cpp.
Referenced by classifyFaces().
buildEdgeToTriangle()
void buildEdgeToTriangle (std::vector< MTriangle * > & , e2t_cont & adj)
Definition at line 443 of file meshGFaceOptimize.cpp.
buildListOfEdgeAngle()
void buildListOfEdgeAngle (e2t_cont adj, std::vector< edge_angle > & edges_detected, std::vector< edge_angle > & edges_lonly)
Definition at line 455 of file meshGFaceOptimize.cpp.
Referenced by classifyFaces().
buildMeshGenerationDataStructures()
bool buildMeshGenerationDataStructures (GFace * gf, std::set< MTri3 *, compareTri3Ptr > & AllTris, bidimMeshData & data)
Definition at line 174 of file meshGFaceOptimize.cpp.
Referenced by bowyerWatson(), bowyerWatsonFrontal(), bowyerWatsonFrontalLayers(), bowyerWatsonParallelograms(), and bowyerWatsonParallelogramsConstrained().
buildVertexToElement()
template<class T > void buildVertexToElement (std::vector< T * > const & elements, v2t_cont & adj)
Definition at line 38 of file meshGFaceOptimize.h.
Referenced by _removeDiamonds(), _removeTwoQuadsNodes(), laplaceSmoothing(), meshMetric::meshMetric(), RelocateVertices(), and RelocateVerticesOfPyramids().
computeEquivalences()
void computeEquivalences (GFace * gf, bidimMeshData & DATA)
Definition at line 271 of file meshGFaceOptimize.cpp.
Referenced by transferDataStructure().
laplaceSmoothing()
void laplaceSmoothing (GFace * gf, int niter = 1, bool infinity_norm = false)
Definition at line 978 of file meshGFaceOptimize.cpp.
Referenced by GModel::adaptMesh(), meshGenerator(), meshGeneratorPeriodic(), and OptimizeMesh().
quadsToTriangles()
void quadsToTriangles (GFace * gf, double minqual)
Definition at line 1374 of file meshGFaceOptimize.cpp.
Referenced by buildBackgroundMesh(), Mesh3D(), recombineIntoQuads(), and splitElementsInBoundaryLayerIfNeeded().
recombineIntoQuads()
void recombineIntoQuads (GFace * gf, bool blossom, int topologicalOptiPasses, bool nodeRepositioning, double minqual)
Definition at line 1311 of file meshGFaceOptimize.cpp.
Referenced by quadMeshRemoveHalfOfOneDMesh::finish(), meshGenerator(), meshGeneratorPeriodic(), and RecombineMesh().
splitElementsInBoundaryLayerIfNeeded()
void splitElementsInBoundaryLayerIfNeeded (GFace * gf)
Definition at line 1457 of file meshGFaceOptimize.cpp.
Referenced by bowyerWatson(), bowyerWatsonFrontal(), bowyerWatsonFrontalLayers(), bowyerWatsonParallelograms(), bowyerWatsonParallelogramsConstrained(), and meshGenerator().
transferDataStructure()
void transferDataStructure (GFace * gf, std::set< MTri3 *, compareTri3Ptr > & AllTris, bidimMeshData & DATA)
Definition at line 348 of file meshGFaceOptimize.cpp.
Referenced by bowyerWatson(), bowyerWatsonFrontal(), bowyerWatsonFrontalLayers(), bowyerWatsonParallelograms(), and bowyerWatsonParallelogramsConstrained().