gmsh-TingyuanDoc: src/mesh/meshRefine.h File Reference
meshRefine.h File Reference
Functions
void RefineMesh (GModel *m, bool linear, bool splitIntoQuads=false, bool splitIntoHexas=false)
void BarycentricRefineMesh (GModel *m)
Function Documentation
BarycentricRefineMesh()
void BarycentricRefineMesh (GModel * m)
Definition at line 507 of file meshRefine.cpp.
Referenced by GenerateMesh(), and GModel::refineMesh().
RefineMesh()
void RefineMesh (GModel * m, bool linear, bool splitIntoQuads = false, bool splitIntoHexas = false)
Definition at line 463 of file meshRefine.cpp.
Referenced by GenerateMesh(), and GModel::refineMesh().