gmsh-TingyuanDoc: src/mesh/meshGEdge.cpp File Reference
meshGEdge.cpp File Reference
#include "meshGEdge.h"
#include "BackgroundMeshTools.h"
#include "Context.h"
#include "Field.h"
#include "GEdge.h"
#include "GModel.h"
#include "GmshConfig.h"
#include "GmshMessage.h"
#include "MLine.h"
#include "Numeric.h"
#include "OS.h"
#include "STensor3.h"
#include "boundaryLayersData.h"
#include "discreteEdge.h"
Classes
struct IntPoint
struct F_LcB
struct F_Lc
struct F_Lc_aniso
struct F_Transfinite
struct F_One
Functions
static double smoothPrimitive (GEdge *ge, double alpha, std::vector< IntPoint > &Points)
static double dfbeta (double t, double beta)
static double trapezoidal (IntPoint *const P1, IntPoint *const P2)
template<typename function >
static void RecursiveIntegration (GEdge *ge, IntPoint *from, IntPoint *to, function f, std::vector< IntPoint > &Points, double Prec, int *depth)
template<typename function >
static double Integration (GEdge *ge, double t1, double t2, function f, std::vector< IntPoint > &Points, double Prec)
static SPoint3 transform (MVertex *vsource, const std::vector< double > &tfo)
static void copyMesh (GEdge *from, GEdge *to, int direction)
static void fillCorrespondingNodes (GEdge *from, GEdge *to, int direction)
static int increaseN (int N)
static void filterPoints (GEdge *ge, int nMinimumPoints)
static void createPoints (GVertex *gv, GEdge *ge, BoundaryLayerField *blf, std::vector< MVertex * > &v, const SVector3 &dir)
static void addBoundaryLayerPoints (GEdge *ge, double &t_begin, double &t_end, std::vector< MVertex * > &_addBegin, std::vector< MVertex * > &_addEnd)
int meshGEdgeProcessing (GEdge *ge, const double t_begin, double t_end, int &N, std::vector< IntPoint > &Points, double &a, int &filterMinimumN)
int meshGEdgeTargetNumberOfPoints (GEdge *ge)
Function Documentation
addBoundaryLayerPoints()
static void addBoundaryLayerPoints (GEdge * ge, double & t_begin, double & t_end, std::vector< MVertex * > & _addBegin, std::vector< MVertex * > & _addEnd) static
Definition at line 595 of file meshGEdge.cpp.
Referenced by meshGEdge::operator()().
copyMesh()
static void copyMesh (GEdge * from, GEdge * to, int direction) static
Definition at line 335 of file meshGEdge.cpp.
Referenced by meshGEdge::operator()().
createPoints()
static void createPoints (GVertex * gv, GEdge * ge, BoundaryLayerField * blf, std::vector< MVertex * > & v, const SVector3 & dir) static
Definition at line 550 of file meshGEdge.cpp.
Referenced by addBoundaryLayerPoints().
dfbeta()
static double dfbeta (double t, double beta) static
Definition at line 157 of file meshGEdge.cpp.
Referenced by F_Transfinite::operator()().
fillCorrespondingNodes()
static void fillCorrespondingNodes (GEdge * from, GEdge * to, int direction) static
Definition at line 394 of file meshGEdge.cpp.
Referenced by meshGEdge::operator()().
filterPoints()
static void filterPoints (GEdge * ge, int nMinimumPoints) static
Definition at line 461 of file meshGEdge.cpp.
Referenced by meshGEdge::operator()().
increaseN()
static int increaseN (int N) static
Definition at line 452 of file meshGEdge.cpp.
Referenced by meshGEdgeProcessing().
Integration()
template<typename function > static double Integration (GEdge * ge, double t1, double t2, function f, std::vector< IntPoint > & Points, double Prec) static
Definition at line 304 of file meshGEdge.cpp.
Referenced by meshGEdgeProcessing().
meshGEdgeProcessing()
int meshGEdgeProcessing (GEdge * ge, const double t_begin, double t_end, int & N, std::vector< IntPoint > & Points, double & a, int & filterMinimumN)
Definition at line 674 of file meshGEdge.cpp.
Referenced by meshGEdgeTargetNumberOfPoints(), and meshGEdge::operator()().
meshGEdgeTargetNumberOfPoints()
int meshGEdgeTargetNumberOfPoints (GEdge * ge)
Definition at line 980 of file meshGEdge.cpp.
Referenced by build_chords(), and MeshSetTransfiniteFacesAutomatic().
RecursiveIntegration()
template<typename function > static void RecursiveIntegration (GEdge * ge, IntPoint * from, IntPoint * to, function f, std::vector< IntPoint > & Points, double Prec, int * depth) static
Definition at line 269 of file meshGEdge.cpp.
Referenced by Integration().
smoothPrimitive()
static double smoothPrimitive (GEdge * ge, double alpha, std::vector< IntPoint > & Points) static
Definition at line 31 of file meshGEdge.cpp.
Referenced by meshGEdgeProcessing().
transform()
static SPoint3 transform (MVertex * vsource, const std::vector< double > & tfo) static
Definition at line 323 of file meshGEdge.cpp.
Referenced by copyMesh().
trapezoidal()
static double trapezoidal (IntPoint *const P1, IntPoint *const P2) static
Definition at line 263 of file meshGEdge.cpp.
Referenced by RecursiveIntegration().