gmsh-TingyuanDoc: src/mesh/meshGRegion.h File Reference
meshGRegion.h File Reference
#include <list>
#include <vector>
#include <map>
#include "MFace.h"
Classes
class meshGRegion
class meshGRegionExtruded
class optimizeMeshGRegion
class optimizeMeshGRegionNetgen
class deMeshGRegion
class splitQuadRecovery
class adaptMeshGRegion
Typedefs
typedef std::map< MFace, GFace *, MFaceLessThan > fs_cont
typedef std::multimap< MVertex *, std::pair< MLine *, GEdge * > > es_cont
Functions
void MeshDelaunayVolume (std::vector< GRegion * > &delaunay)
bool CreateAnEmptyVolumeMesh (GRegion *gr)
int MeshTransfiniteVolume (GRegion *gr)
int SubdivideExtrudedMesh (GModel *m)
void carveHole (GRegion *gr, int num, double distance, std::vector< int > &surfaces)
GFace * findInFaceSearchStructure (MVertex *p1, MVertex *p2, MVertex *p3, const fs_cont &search)
GFace * findInFaceSearchStructure (const MFace &f, const fs_cont &search)
GEdge * findInEdgeSearchStructure (MVertex *p1, MVertex *p2, const es_cont &search)
bool buildFaceSearchStructure (GModel *model, fs_cont &search, bool onlyTriangles=false)
bool buildEdgeSearchStructure (GModel *model, es_cont &search)
Typedef Documentation
es_cont
typedef std::multimap<MVertex *, std::pair<MLine *, GEdge *> > es_cont
Definition at line 61 of file meshGRegion.h.
fs_cont
typedef std::map<MFace, GFace *, MFaceLessThan> fs_cont
Definition at line 60 of file meshGRegion.h.
Function Documentation
buildEdgeSearchStructure()
bool buildEdgeSearchStructure (GModel * model, es_cont & search)
Definition at line 313 of file meshGRegion.cpp.
buildFaceSearchStructure()
bool buildFaceSearchStructure (GModel * model, fs_cont & search, bool onlyTriangles = false)
Definition at line 286 of file meshGRegion.cpp.
Referenced by insertVerticesInRegion(), and MakeMeshConformal().
carveHole()
void carveHole (GRegion * gr, int num, double distance, std::vector< int > & surfaces)
Definition at line 19 of file meshGRegionCarveHole.cpp.
Referenced by meshGRegionExtruded::operator()(), and SubdivideExtrudedMesh().
CreateAnEmptyVolumeMesh()
bool CreateAnEmptyVolumeMesh (GRegion * gr)
findInEdgeSearchStructure()
GEdge* findInEdgeSearchStructure (MVertex * p1, MVertex * p2, const es_cont & search)
Definition at line 350 of file meshGRegion.cpp.
findInFaceSearchStructure() [1/2]
GFace* findInFaceSearchStructure (const MFace & f, const fs_cont & search)
Definition at line 342 of file meshGRegion.cpp.
findInFaceSearchStructure() [2/2]
GFace* findInFaceSearchStructure (MVertex * p1, MVertex * p2, MVertex * p3, const fs_cont & search)
Definition at line 333 of file meshGRegion.cpp.
Referenced by MakeMeshConformal(), and non_recursive_classify().
MeshDelaunayVolume()
void MeshDelaunayVolume (std::vector< GRegion * > & delaunay)
Definition at line 95 of file meshGRegion.cpp.
Referenced by Mesh3D().
MeshTransfiniteVolume()
int MeshTransfiniteVolume (GRegion * gr)
Definition at line 342 of file meshGRegionTransfinite.cpp.
Referenced by meshGRegion::operator()().
SubdivideExtrudedMesh()
int SubdivideExtrudedMesh (GModel * m)
Definition at line 481 of file meshGRegionExtruded.cpp.
Referenced by Mesh3D().