gmsh-TingyuanDoc: jacobianBasedQuality Namespace Reference
jacobianBasedQuality Namespace Reference
Classes
class _coeffData
class _coeffDataICN
class _coeffDataIGE
class _coeffDataJac
struct _lessMaxB
struct _lessMinB
Functions
void minMaxJacobianDeterminant (MElement *el, double &min, double &max, const fullMatrix< double > *normals, bool debug)
double minIGEMeasure (MElement *el, bool knownValid, bool reversedOk, const fullMatrix< double > *normals, bool debug)
double minICNMeasure (MElement *el, bool knownValid, bool reversedOk, const fullMatrix< double > *normals, bool debug)
void sampleJacobianDeterminant (MElement *el, int deg, double &min, double &max, const fullMatrix< double > *normals)
void sampleIGEMeasure (MElement *el, int deg, double &min, double &max)
void sampleICNMeasure (MElement *el, int deg, double &min, double &max)
void sampleJacobianDeterminant (MElement *el, int deg, fullVector< double > &jac, const fullMatrix< double > *normals)
void sampleIGEMeasure (MElement *el, int deg, fullVector< double > &ige)
void sampleICNMeasure (MElement *el, int deg, fullVector< double > &icn)
template<typename Comp >
void _subdivideDomainsMinOrMax (std::vector< _coeffData * > &domains, double &minL, double &maxL, bool debug)
void _subdivideDomains (std::vector< _coeffData * > &domains, bool alsoMax, bool debug)
double _getMinAndDeleteDomains (std::vector< _coeffData * > &domains)
double _computeBoundRational (const fullVector< double > &numerator, const fullVector< double > &denominator, bool lower, bool positiveDenom)
void testAllMeasuresAllElements ()
void testAllMeasures (MElement *el, const fullMatrix< double > *normals)
Function Documentation
_computeBoundRational()
double jacobianBasedQuality::_computeBoundRational (const fullVector< double > & numerator, const fullVector< double > & denominator, bool lower, bool positiveDenom)
Definition at line 903 of file qualityMeasuresJacobian.cpp.
Referenced by jacobianBasedQuality::_coeffDataIGE::_computeLowerBound(), and jacobianBasedQuality::_coeffDataICN::_computeLowerBound().
_getMinAndDeleteDomains()
double jacobianBasedQuality::_getMinAndDeleteDomains (std::vector< _coeffData * > & domains)
Definition at line 879 of file qualityMeasuresJacobian.cpp.
Referenced by minICNMeasure(), and minIGEMeasure().
_subdivideDomains()
void jacobianBasedQuality::_subdivideDomains (std::vector< _coeffData * > & domains, bool alsoMax, bool debug)
Definition at line 860 of file qualityMeasuresJacobian.cpp.
Referenced by minICNMeasure(), minIGEMeasure(), and minMaxJacobianDeterminant().
_subdivideDomainsMinOrMax()
template<typename Comp > void jacobianBasedQuality::_subdivideDomainsMinOrMax (std::vector< _coeffData * > & domains, double & minL, double & maxL, bool debug)
Definition at line 830 of file qualityMeasuresJacobian.cpp.
minICNMeasure()
double jacobianBasedQuality::minICNMeasure (MElement * el, bool knownValid, bool reversedOk, const fullMatrix< double > * normals, bool debug)
Definition at line 326 of file qualityMeasuresJacobian.cpp.
Referenced by MElement::minIsotropyMeasure(), and testAllMeasures().
minIGEMeasure()
double jacobianBasedQuality::minIGEMeasure (MElement * el, bool knownValid, bool reversedOk, const fullMatrix< double > * normals, bool debug)
Definition at line 280 of file qualityMeasuresJacobian.cpp.
Referenced by MElement::minScaledJacobian(), and testAllMeasures().
minMaxJacobianDeterminant()
void jacobianBasedQuality::minMaxJacobianDeterminant (MElement * el, double & min, double & max, const fullMatrix< double > * normals, bool debug)
Definition at line 242 of file qualityMeasuresJacobian.cpp.
Referenced by MElement::getValidity(), minICNMeasure(), minIGEMeasure(), and testAllMeasures().
sampleICNMeasure() [1/2]
void jacobianBasedQuality::sampleICNMeasure (MElement * el, int deg, double & min, double & max)
Definition at line 399 of file qualityMeasuresJacobian.cpp.
Referenced by testAllMeasures().
sampleICNMeasure() [2/2]
void jacobianBasedQuality::sampleICNMeasure (MElement * el, int deg, fullVector< double > & icn)
Definition at line 458 of file qualityMeasuresJacobian.cpp.
sampleIGEMeasure() [1/2]
void jacobianBasedQuality::sampleIGEMeasure (MElement * el, int deg, double & min, double & max)
Definition at line 386 of file qualityMeasuresJacobian.cpp.
Referenced by MElement::signedInvGradErrorRange(), and testAllMeasures().
sampleIGEMeasure() [2/2]
void jacobianBasedQuality::sampleIGEMeasure (MElement * el, int deg, fullVector< double > & ige)
Definition at line 431 of file qualityMeasuresJacobian.cpp.
sampleJacobianDeterminant() [1/2]
void jacobianBasedQuality::sampleJacobianDeterminant (MElement * el, int deg, double & min, double & max, const fullMatrix< double > * normals)
Definition at line 372 of file qualityMeasuresJacobian.cpp.
Referenced by testAllMeasures().
sampleJacobianDeterminant() [2/2]
void jacobianBasedQuality::sampleJacobianDeterminant (MElement * el, int deg, fullVector< double > & jac, const fullMatrix< double > * normals)
Definition at line 412 of file qualityMeasuresJacobian.cpp.
testAllMeasures()
void jacobianBasedQuality::testAllMeasures (MElement * el, const fullMatrix< double > * normals)
Definition at line 979 of file qualityMeasuresJacobian.cpp.
Referenced by testAllMeasuresAllElements().
testAllMeasuresAllElements()
void jacobianBasedQuality::testAllMeasuresAllElements ()
Definition at line 959 of file qualityMeasuresJacobian.cpp.