gmsh-TingyuanDoc: OrthogonalPoly Namespace Reference
OrthogonalPoly Namespace Reference
Functions
double EvalLobatto (int order, double x)
double EvalDLobatto (int order, double x)
double EvalKernelFunction (int order, double x)
double EvalDKernelFunction (int order, double x)
double EvalLegendre (int order, double x)
double EvalDLegendre (int order, double x)
Function Documentation
EvalDKernelFunction()
double OrthogonalPoly::EvalDKernelFunction (int order, double x)
Definition at line 329 of file OrthogonalPoly.cpp.
Referenced by HierarchicalBasisHcurlTetra::generateCurlBasis(), HierarchicalBasisHcurlPri::generateCurlBasis(), HierarchicalBasisH1Tria::generateGradientBasis(), HierarchicalBasisH1Tetra::generateGradientBasis(), HierarchicalBasisH1Pri::generateGradientBasis(), HierarchicalBasisH1Tria::orientOneFace(), HierarchicalBasisH1Tetra::orientOneFace(), HierarchicalBasisHcurlPri::orientOneFace(), and HierarchicalBasisH1Pri::orientOneFace().
EvalDLegendre()
double OrthogonalPoly::EvalDLegendre (int order, double x)
Definition at line 465 of file OrthogonalPoly.cpp.
Referenced by HierarchicalBasisHcurlTria::generateCurlBasis(), HierarchicalBasisHcurlTetra::generateCurlBasis(), HierarchicalBasisHcurlPri::generateCurlBasis(), HierarchicalBasisHcurlTria::orientOneFace(), HierarchicalBasisHcurlTetra::orientOneFace(), and HierarchicalBasisHcurlPri::orientOneFace().
EvalDLobatto()
double OrthogonalPoly::EvalDLobatto (int order, double x)
Definition at line 127 of file OrthogonalPoly.cpp.
Referenced by HierarchicalBasisHcurlQuad::generateCurlBasis(), HierarchicalBasisHcurlBrick::generateCurlBasis(), HierarchicalBasisHcurlPri::generateCurlBasis(), HierarchicalBasisH1Line::generateGradientBasis(), HierarchicalBasisH1Quad::generateGradientBasis(), HierarchicalBasisH1Pri::generateGradientBasis(), HierarchicalBasisH1Brick::generateGradientBasis(), HierarchicalBasisHcurlQuad::orientOneFace(), HierarchicalBasisH1Quad::orientOneFace(), HierarchicalBasisHcurlBrick::orientOneFace(), HierarchicalBasisHcurlPri::orientOneFace(), and HierarchicalBasisH1Brick::orientOneFace().
EvalKernelFunction()
double OrthogonalPoly::EvalKernelFunction (int order, double x)
Definition at line 238 of file OrthogonalPoly.cpp.
Referenced by HierarchicalBasisH1Line::generateBasis(), HierarchicalBasisH1Tria::generateBasis(), HierarchicalBasisH1Tetra::generateBasis(), HierarchicalBasisH1Pri::generateBasis(), HierarchicalBasisHcurlTetra::generateCurlBasis(), HierarchicalBasisHcurlPri::generateCurlBasis(), HierarchicalBasisH1Tria::generateGradientBasis(), HierarchicalBasisH1Tetra::generateGradientBasis(), HierarchicalBasisH1Pri::generateGradientBasis(), HierarchicalBasisHcurlTetra::generateHcurlBasis(), HierarchicalBasisHcurlPri::generateHcurlBasis(), HierarchicalBasisH1Tria::orientOneFace(), HierarchicalBasisH1Tetra::orientOneFace(), HierarchicalBasisH1Pri::orientOneFace(), and HierarchicalBasisHcurlPri::orientOneFace().
EvalLegendre()
double OrthogonalPoly::EvalLegendre (int order, double x)
Definition at line 415 of file OrthogonalPoly.cpp.
Referenced by HierarchicalBasisHcurlQuad::generateCurlBasis(), HierarchicalBasisHcurlTria::generateCurlBasis(), HierarchicalBasisHcurlTetra::generateCurlBasis(), HierarchicalBasisHcurlBrick::generateCurlBasis(), HierarchicalBasisHcurlPri::generateCurlBasis(), HierarchicalBasisHcurlLine::generateHcurlBasis(), HierarchicalBasisHcurlQuad::generateHcurlBasis(), HierarchicalBasisHcurlTria::generateHcurlBasis(), HierarchicalBasisHcurlTetra::generateHcurlBasis(), HierarchicalBasisHcurlBrick::generateHcurlBasis(), HierarchicalBasisHcurlPri::generateHcurlBasis(), HierarchicalBasisHcurlQuad::orientOneFace(), HierarchicalBasisHcurlTria::orientOneFace(), HierarchicalBasisHcurlBrick::orientOneFace(), HierarchicalBasisHcurlTetra::orientOneFace(), and HierarchicalBasisHcurlPri::orientOneFace().
EvalLobatto()
double OrthogonalPoly::EvalLobatto (int order, double x)
Definition at line 9 of file OrthogonalPoly.cpp.
Referenced by HierarchicalBasisH1Quad::generateBasis(), HierarchicalBasisH1Brick::generateBasis(), HierarchicalBasisH1Pri::generateBasis(), HierarchicalBasisHcurlBrick::generateCurlBasis(), HierarchicalBasisHcurlPri::generateCurlBasis(), HierarchicalBasisH1Quad::generateGradientBasis(), HierarchicalBasisH1Pri::generateGradientBasis(), HierarchicalBasisH1Brick::generateGradientBasis(), HierarchicalBasisHcurlQuad::generateHcurlBasis(), HierarchicalBasisHcurlBrick::generateHcurlBasis(), HierarchicalBasisHcurlPri::generateHcurlBasis(), HierarchicalBasisHcurlQuad::orientOneFace(), HierarchicalBasisH1Quad::orientOneFace(), HierarchicalBasisHcurlBrick::orientOneFace(), HierarchicalBasisHcurlPri::orientOneFace(), and HierarchicalBasisH1Brick::orientOneFace().