gmsh-TingyuanDoc: picojson Namespace Reference
picojson Namespace Reference
Classes
class default_parse_context
class deny_parse_context
class input
struct last_error_t
struct null
class null_parse_context
struct serialize_str_char
class value
Typedefs
typedef value::array array
typedef value::object object
Enumerations
enum {
null_type, boolean_type, number_type, string_type,
array_type, object_type
}
enum { INDENT_WIDTH = 2 }
Functions
template<typename Iter >
void copy (const std::string &s, Iter oi)
template<typename Iter >
void serialize_str (const std::string &s, Iter oi)
template<typename Iter >
int _parse_quadhex (input< Iter > &in)
template<typename String , typename Iter >
bool _parse_codepoint (String &out, input< Iter > &in)
template<typename String , typename Iter >
bool _parse_string (String &out, input< Iter > &in)
template<typename Context , typename Iter >
bool _parse_array (Context &ctx, input< Iter > &in)
template<typename Context , typename Iter >
bool _parse_object (Context &ctx, input< Iter > &in)
template<typename Iter >
std::string _parse_number (input< Iter > &in)
template<typename Context , typename Iter >
bool _parse (Context &ctx, input< Iter > &in)
template<typename Iter >
std::string parse (value &out, Iter &pos, const Iter &last)
template<typename Context , typename Iter >
Iter _parse (Context &ctx, const Iter &first, const Iter &last, std::string *err)
template<typename Iter >
Iter parse (value &out, const Iter &first, const Iter &last, std::string *err)
std::string parse (value &out, const std::string &s)
std::string parse (value &out, std::istream &is)
void set_last_error (const std::string &s)
const std::string & get_last_error ()
bool operator== (const value &x, const value &y)
bool operator!= (const value &x, const value &y)
Typedef Documentation
array
typedef value::array picojson::array
Definition at line 194 of file picojson.h.
object
typedef value::object picojson::object
Definition at line 195 of file picojson.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
null_type
boolean_type
number_type
string_type
array_type
object_type
Definition at line 105 of file picojson.h.
anonymous enum
anonymous enum
Enumerator
INDENT_WIDTH
Definition at line 118 of file picojson.h.
Function Documentation
_parse() [1/2]
template<typename Context , typename Iter > Iter picojson::_parse (Context & ctx, const Iter & first, const Iter & last, std::string * err) inline
Definition at line 1064 of file picojson.h.
_parse() [2/2]
template<typename Context , typename Iter > bool picojson::_parse (Context & ctx, input< Iter > & in) inline
Definition at line 861 of file picojson.h.
Referenced by _parse(), parse(), picojson::default_parse_context::parse_array_item(), picojson::null_parse_context::parse_array_item(), picojson::default_parse_context::parse_object_item(), and picojson::null_parse_context::parse_object_item().
_parse_array()
template<typename Context , typename Iter > bool picojson::_parse_array (Context & ctx, input< Iter > & in) inline
Definition at line 805 of file picojson.h.
Referenced by _parse().
_parse_codepoint()
template<typename String , typename Iter > bool picojson::_parse_codepoint (String & out, input< Iter > & in) inline
Definition at line 723 of file picojson.h.
Referenced by _parse_string().
_parse_number()
template<typename Iter > std::string picojson::_parse_number (input< Iter > & in) inline
Definition at line 841 of file picojson.h.
Referenced by _parse().
_parse_object()
template<typename Context , typename Iter > bool picojson::_parse_object (Context & ctx, input< Iter > & in) inline
Definition at line 822 of file picojson.h.
Referenced by _parse().
_parse_quadhex()
template<typename Iter > int picojson::_parse_quadhex (input< Iter > & in) inline
Definition at line 702 of file picojson.h.
Referenced by _parse_codepoint().
_parse_string()
template<typename String , typename Iter > bool picojson::_parse_string (String & out, input< Iter > & in) inline
Definition at line 764 of file picojson.h.
Referenced by _parse_object(), picojson::default_parse_context::parse_string(), and picojson::null_parse_context::parse_string().
copy()
template<typename Iter > void picojson::copy (const std::string & s, Iter oi)
Definition at line 510 of file picojson.h.
Referenced by elementFactory::create(), DocRecord::FixFirst(), HierarchicalBasisHcurlTetra::generateCurlBasis(), HierarchicalBasisHcurlTetra::generateHcurlBasis(), meshMetric::meshMetric(), picojson::serialize_str_char< Iter >::operator()(), robin_hood::detail::Table< IsFlat, MaxLoadFactor100, Key, T, Hash, KeyEqual >::Cloner< M, true >::operator()(), robin_hood::detail::Table< IsFlat, MaxLoadFactor100, Key, T, Hash, KeyEqual >::Cloner< M, false >::operator()(), nanoflann::CArray< T, N >::operator=(), HierarchicalBasisHcurlTria::orientOneFace(), HierarchicalBasisH1Tria::orientOneFace(), HierarchicalBasisH1Tetra::orientOneFace(), HierarchicalBasisHcurlTetra::orientOneFace(), HierarchicalBasisH1Pri::orientOneFace(), HierarchicalBasisHcurlPri::orientOneFace(), MTriangleN::reorient(), MQuadrangleN::reorient(), ReplaceSubString(), MPyramidN::reverse(), MTetrahedronN::reverse(), MPrismN::reverse(), MHexahedronN::reverse(), and picojson::value::serialize_().
get_last_error()
const std::string& picojson::get_last_error () inline
Definition at line 1106 of file picojson.h.
operator!=()
bool picojson::operator!= (const value & x, const value & y) inline
Definition at line 1129 of file picojson.h.
operator==()
bool picojson::operator== (const value & x, const value & y) inline
Definition at line 1110 of file picojson.h.
parse() [1/4]
template<typename Iter > Iter picojson::parse (value & out, const Iter & first, const Iter & last, std::string * err) inline
Definition at line 1082 of file picojson.h.
parse() [2/4]
std::string picojson::parse (value & out, const std::string & s) inline
Definition at line 1087 of file picojson.h.
parse() [3/4]
template<typename Iter > std::string picojson::parse (value & out, Iter & pos, const Iter & last) inline
Definition at line 1058 of file picojson.h.
Referenced by onelab::number::fromJSON(), onelab::string::fromJSON(), onelab::parameterSpace::fromJSON(), operator>>(), parse(), and GMSH_SpanningTreePlugin::run().
parse() [4/4]
std::string picojson::parse (value & out, std::istream & is) inline
Definition at line 1093 of file picojson.h.
serialize_str()
template<typename Iter > void picojson::serialize_str (const std::string & s, Iter oi)
Definition at line 544 of file picojson.h.
Referenced by picojson::value::serialize_().
set_last_error()
void picojson::set_last_error (const std::string & s) inline
Definition at line 1102 of file picojson.h.
Referenced by operator>>().