gmsh-TingyuanDoc: robustPredicates Namespace Reference
robustPredicates Namespace Reference
Functions
REAL exactinit (int filter, REAL maxx, REAL maxy, REAL maxz)
int grow_expansion (int elen, REAL *e, REAL b, REAL *h)
int grow_expansion_zeroelim (int elen, REAL *e, REAL b, REAL *h)
int expansion_sum (int elen, REAL *e, int flen, REAL *f, REAL *h)
int expansion_sum_zeroelim1 (int elen, REAL *e, int flen, REAL *f, REAL *h)
int expansion_sum_zeroelim2 (int elen, REAL *e, int flen, REAL *f, REAL *h)
int fast_expansion_sum (int elen, REAL *e, int flen, REAL *f, REAL *h)
int fast_expansion_sum_zeroelim (int elen, REAL *e, int flen, REAL *f, REAL *h)
int linear_expansion_sum (int elen, REAL *e, int flen, REAL *f, REAL *h)
int linear_expansion_sum_zeroelim (int elen, REAL *e, int flen, REAL *f, REAL *h)
int scale_expansion (int elen, REAL *e, REAL b, REAL *h)
int scale_expansion_zeroelim (int elen, REAL *e, REAL b, REAL *h)
int compress (int elen, REAL *e, REAL *h)
REAL estimate (int elen, REAL *e)
REAL orient2dfast (REAL *pa, REAL *pb, REAL *pc)
REAL orient2dexact (REAL *pa, REAL *pb, REAL *pc)
REAL orient2dslow (REAL *pa, REAL *pb, REAL *pc)
REAL orient2dadapt (REAL *pa, REAL *pb, REAL *pc, REAL detsum)
REAL orient2d (REAL *pa, REAL *pb, REAL *pc)
REAL orient3dfast (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL orient3dexact (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL orient3dslow (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL orient3dadapt (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL permanent)
REAL orient3d (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL incirclefast (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL incircleexact (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL incircleslow (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL incircleadapt (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL permanent)
REAL incircle (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL inspherefast (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL *pe)
REAL insphereexact (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL *pe)
REAL insphereslow (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL *pe)
REAL insphereadapt (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL *pe, REAL permanent)
REAL insphere (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL *pe)
REAL orient4dexact (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL *pe, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL eheight)
REAL orient4dadapt (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL *pe, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL eheight, REAL permanent)
REAL orient4d (REAL *pa, REAL *pb, REAL *pc, REAL *pd, REAL *pe, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL eheight)
double exactinit (int filter, double maxx, double maxy, double maxz)
double incircle (double *pa, double *pb, double *pc, double *pd)
double insphere (double *pa, double *pb, double *pc, double *pd, double *pe)
double orient2d (double *pa, double *pb, double *pc)
double orient3d (double *pa, double *pb, double *pc, double *pd)
Variables
static REAL splitter
static REAL epsilon
static REAL resulterrbound
static REAL ccwerrboundA
static REAL ccwerrboundB
static REAL ccwerrboundC
static REAL o3derrboundA
static REAL o3derrboundB
static REAL o3derrboundC
static REAL iccerrboundA
static REAL iccerrboundB
static REAL iccerrboundC
static REAL isperrboundA
static REAL isperrboundB
static REAL isperrboundC
static int _use_inexact_arith
static int _use_static_filter
static REAL o3dstaticfilter
static REAL ispstaticfilter
Function Documentation
compress()
int robustPredicates::compress (int elen, REAL * e, REAL * h)
Definition at line 1378 of file robustPredicates.cpp.
estimate()
REAL robustPredicates::estimate (int elen, REAL * e)
Definition at line 1421 of file robustPredicates.cpp.
Referenced by incircleadapt(), insphereadapt(), orient2dadapt(), orient3dadapt(), and orient4dadapt().
exactinit() [1/2]
double robustPredicates::exactinit (int filter, double maxx, double maxy, double maxz)
exactinit() [2/2]
REAL robustPredicates::exactinit (int filter, REAL maxx, REAL maxy, REAL maxz)
Definition at line 676 of file robustPredicates.cpp.
Referenced by delaunayTriangulation(), and GmshInitialize().
expansion_sum()
int robustPredicates::expansion_sum (int elen, REAL * e, int flen, REAL * f, REAL * h)
Definition at line 844 of file robustPredicates.cpp.
expansion_sum_zeroelim1()
int robustPredicates::expansion_sum_zeroelim1 (int elen, REAL * e, int flen, REAL * f, REAL * h)
Definition at line 888 of file robustPredicates.cpp.
expansion_sum_zeroelim2()
int robustPredicates::expansion_sum_zeroelim2 (int elen, REAL * e, int flen, REAL * f, REAL * h)
Definition at line 943 of file robustPredicates.cpp.
fast_expansion_sum()
int robustPredicates::fast_expansion_sum (int elen, REAL * e, int flen, REAL * f, REAL * h)
Definition at line 995 of file robustPredicates.cpp.
fast_expansion_sum_zeroelim()
int robustPredicates::fast_expansion_sum_zeroelim (int elen, REAL * e, int flen, REAL * f, REAL * h)
Definition at line 1068 of file robustPredicates.cpp.
Referenced by incircleadapt(), incircleexact(), incircleslow(), insphereadapt(), insphereexact(), insphereslow(), orient2dadapt(), orient2dexact(), orient2dslow(), orient3dadapt(), orient3dexact(), orient3dslow(), orient4dadapt(), and orient4dexact().
grow_expansion()
int robustPredicates::grow_expansion (int elen, REAL * e, REAL b, REAL * h)
Definition at line 771 of file robustPredicates.cpp.
grow_expansion_zeroelim()
int robustPredicates::grow_expansion_zeroelim (int elen, REAL * e, REAL b, REAL * h)
Definition at line 805 of file robustPredicates.cpp.
incircle() [1/2]
double robustPredicates::incircle (double * pa, double * pb, double * pc, double * pd)
incircle() [2/2]
REAL robustPredicates::incircle (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 3245 of file robustPredicates.cpp.
Referenced by delaunayEdgeCriterionPlaneIsotropic(), inCircumCircle(), inCircumCircleXY(), and DocRecord::Qtest().
incircleadapt()
REAL robustPredicates::incircleadapt (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL permanent)
Definition at line 2673 of file robustPredicates.cpp.
Referenced by incircle().
incircleexact()
REAL robustPredicates::incircleexact (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 2419 of file robustPredicates.cpp.
incirclefast()
REAL robustPredicates::incirclefast (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 2396 of file robustPredicates.cpp.
incircleslow()
REAL robustPredicates::incircleslow (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 2517 of file robustPredicates.cpp.
insphere() [1/2]
double robustPredicates::insphere (double * pa, double * pb, double * pc, double * pd, double * pe)
insphere() [2/2]
REAL robustPredicates::insphere (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe)
Definition at line 4200 of file robustPredicates.cpp.
Referenced by MTri3::inCircumCircle(), MTet4::inCircumSphere(), tetgenmesh::insphere_s(), and inSphereTest_s().
insphereadapt()
REAL robustPredicates::insphereadapt (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe, REAL permanent)
Definition at line 3938 of file robustPredicates.cpp.
Referenced by insphere().
insphereexact()
REAL robustPredicates::insphereexact (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe)
Definition at line 3357 of file robustPredicates.cpp.
Referenced by insphereadapt().
inspherefast()
REAL robustPredicates::inspherefast (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe)
Definition at line 3314 of file robustPredicates.cpp.
insphereslow()
REAL robustPredicates::insphereslow (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe)
Definition at line 3609 of file robustPredicates.cpp.
linear_expansion_sum()
int robustPredicates::linear_expansion_sum (int elen, REAL * e, int flen, REAL * f, REAL * h)
Definition at line 1149 of file robustPredicates.cpp.
linear_expansion_sum_zeroelim()
int robustPredicates::linear_expansion_sum_zeroelim (int elen, REAL * e, int flen, REAL * f, REAL * h)
Definition at line 1209 of file robustPredicates.cpp.
orient2d() [1/2]
double robustPredicates::orient2d (double * pa, double * pb, double * pc)
orient2d() [2/2]
REAL robustPredicates::orient2d (REAL * pa, REAL * pb, REAL * pc)
Definition at line 1633 of file robustPredicates.cpp.
Referenced by check_triangle_validity_2d(), inCircumCircle(), inCircumCircleXY(), intersect(), intersection_segments_2(), DocRecord::IsLeftOf(), middlePoint(), BDS_SwapEdgeTestRecover::operator()(), orientationTest(), p1triangle_quality_metric(), pointInsideParametricDomain(), DocRecord::Qtest(), triangleValidityP1(), validityOfCavity(), and Walk().
orient2dadapt()
REAL robustPredicates::orient2dadapt (REAL * pa, REAL * pb, REAL * pc, REAL detsum)
Definition at line 1553 of file robustPredicates.cpp.
Referenced by orient2d().
orient2dexact()
REAL robustPredicates::orient2dexact (REAL * pa, REAL * pb, REAL * pc)
Definition at line 1470 of file robustPredicates.cpp.
orient2dfast()
REAL robustPredicates::orient2dfast (REAL * pa, REAL * pb, REAL * pc)
Definition at line 1459 of file robustPredicates.cpp.
orient2dslow()
REAL robustPredicates::orient2dslow (REAL * pa, REAL * pb, REAL * pc)
Definition at line 1512 of file robustPredicates.cpp.
orient3d() [1/2]
double robustPredicates::orient3d (double * pa, double * pb, double * pc, double * pd)
orient3d() [2/2]
REAL robustPredicates::orient3d (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 2321 of file robustPredicates.cpp.
Referenced by tetgenmesh::add_steinerpt_in_schoenhardtpoly(), qmTetrahedron::eta(), tetgenmesh::flipnm(), qmTetrahedron::gamma(), MTet4::getVolume(), MTri3::inCircumCircle(), MTet4::inCircumSphere(), tetgenmesh::incrementalflip(), tetgenmesh::insertpoint(), tetgenmesh::insphere_s(), inSphereTest_s(), tetgenmesh::interiorangle(), tetgenmesh::lawsonflip3d(), tetgenmesh::orient4d_s(), tetgenmesh::removefacebyflips(), Tet::setVertices(), tetgenmesh::sinsertvertex(), tetgenmesh::smoothpoint(), tetgenmesh::sscoutsegment(), starShapeness(), tetgenmesh::suppressbdrysteinerpoint(), tetcircumcenter(), tetContainsV(), tetgenmesh::tri_edge_2d(), tetgenmesh::tri_edge_tail(), tetgenmesh::tri_edge_test(), tetgenmesh::tri_tri_inter(), tetgenmesh::unifysegments(), faceXtet::visible(), and walk().
orient3dadapt()
REAL robustPredicates::orient3dadapt (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL permanent)
Definition at line 1885 of file robustPredicates.cpp.
Referenced by orient3d().
orient3dexact()
REAL robustPredicates::orient3dexact (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 1716 of file robustPredicates.cpp.
orient3dfast()
REAL robustPredicates::orient3dfast (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 1695 of file robustPredicates.cpp.
orient3dslow()
REAL robustPredicates::orient3dslow (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 1793 of file robustPredicates.cpp.
orient4d()
REAL robustPredicates::orient4d (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL eheight)
Definition at line 4739 of file robustPredicates.cpp.
Referenced by tetgenmesh::orient4d_s(), and tetgenmesh::tetprismvol().
orient4dadapt()
REAL robustPredicates::orient4dadapt (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL eheight, REAL permanent)
Definition at line 4544 of file robustPredicates.cpp.
Referenced by orient4d().
orient4dexact()
REAL robustPredicates::orient4dexact (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL eheight)
Definition at line 4330 of file robustPredicates.cpp.
Referenced by orient4dadapt().
scale_expansion()
int robustPredicates::scale_expansion (int elen, REAL * e, REAL b, REAL * h)
Definition at line 1280 of file robustPredicates.cpp.
scale_expansion_zeroelim()
int robustPredicates::scale_expansion_zeroelim (int elen, REAL * e, REAL b, REAL * h)
Definition at line 1326 of file robustPredicates.cpp.
Referenced by incircleadapt(), incircleexact(), incircleslow(), insphereadapt(), insphereexact(), insphereslow(), orient3dadapt(), orient3dexact(), orient3dslow(), orient4dadapt(), and orient4dexact().
Variable Documentation
_use_inexact_arith
int robustPredicates::_use_inexact_arith static
Definition at line 381 of file robustPredicates.cpp.
Referenced by exactinit().
_use_static_filter
int robustPredicates::_use_static_filter static
Definition at line 382 of file robustPredicates.cpp.
Referenced by exactinit(), insphere(), and orient3d().
ccwerrboundA
REAL robustPredicates::ccwerrboundA static
Definition at line 374 of file robustPredicates.cpp.
Referenced by exactinit(), and orient2d().
ccwerrboundB
REAL robustPredicates::ccwerrboundB static
Definition at line 374 of file robustPredicates.cpp.
Referenced by exactinit(), and orient2dadapt().
ccwerrboundC
REAL robustPredicates::ccwerrboundC static
Definition at line 374 of file robustPredicates.cpp.
Referenced by exactinit(), and orient2dadapt().
epsilon
REAL robustPredicates::epsilon static
Definition at line 371 of file robustPredicates.cpp.
Referenced by exactinit(), gl2psTraverseBspTree(), tetgenmesh::incircle3d(), intersectCurveSurface(), and tetgenmesh::linelineint().
iccerrboundA
REAL robustPredicates::iccerrboundA static
Definition at line 376 of file robustPredicates.cpp.
Referenced by exactinit(), and incircle().
iccerrboundB
REAL robustPredicates::iccerrboundB static
Definition at line 376 of file robustPredicates.cpp.
Referenced by exactinit(), and incircleadapt().
iccerrboundC
REAL robustPredicates::iccerrboundC static
Definition at line 376 of file robustPredicates.cpp.
Referenced by exactinit(), and incircleadapt().
isperrboundA
REAL robustPredicates::isperrboundA static
Definition at line 377 of file robustPredicates.cpp.
Referenced by exactinit(), insphere(), and orient4d().
isperrboundB
REAL robustPredicates::isperrboundB static
Definition at line 377 of file robustPredicates.cpp.
Referenced by exactinit(), insphereadapt(), and orient4dadapt().
isperrboundC
REAL robustPredicates::isperrboundC static
Definition at line 377 of file robustPredicates.cpp.
Referenced by exactinit(), insphereadapt(), and orient4dadapt().
ispstaticfilter
REAL robustPredicates::ispstaticfilter static
Definition at line 388 of file robustPredicates.cpp.
Referenced by exactinit(), and insphere().
o3derrboundA
REAL robustPredicates::o3derrboundA static
Definition at line 375 of file robustPredicates.cpp.
Referenced by exactinit(), and orient3d().
o3derrboundB
REAL robustPredicates::o3derrboundB static
Definition at line 375 of file robustPredicates.cpp.
Referenced by exactinit(), and orient3dadapt().
o3derrboundC
REAL robustPredicates::o3derrboundC static
Definition at line 375 of file robustPredicates.cpp.
Referenced by exactinit(), and orient3dadapt().
o3dstaticfilter
REAL robustPredicates::o3dstaticfilter static
Definition at line 387 of file robustPredicates.cpp.
Referenced by exactinit(), and orient3d().
resulterrbound
REAL robustPredicates::resulterrbound static
Definition at line 373 of file robustPredicates.cpp.
Referenced by exactinit(), incircleadapt(), insphereadapt(), orient2dadapt(), orient3dadapt(), and orient4dadapt().
splitter
REAL robustPredicates::splitter static
Definition at line 370 of file robustPredicates.cpp.
Referenced by exactinit().