gmsh-TingyuanDoc: JacobiPolynomials Namespace Reference
JacobiPolynomials Namespace Reference
Functions
void f (int n, double alpha, double beta, double u, double *val)
void df (int n, double alpha, double beta, double u, double *val)
double Pochhammer (double x, int n)
Function Documentation
df()
void JacobiPolynomials::df (int n, double alpha, double beta, double u, double * val)
Definition at line 157 of file orthogonalBasis.cpp.
Referenced by BergotBasis::df().
f()
void JacobiPolynomials::f (int n, double alpha, double beta, double u, double * val)
Definition at line 134 of file orthogonalBasis.cpp.
Referenced by BergotBasis::df(), df(), BergotBasis::f(), and orthogonalBasis::f().
Pochhammer()
double JacobiPolynomials::Pochhammer (double x, int n) inline
Definition at line 41 of file orthogonalBasis.h.
Referenced by f().