gmsh-TingyuanDoc: LegendrePolynomials Namespace Reference
LegendrePolynomials Namespace Reference
Functions
void f (int n, double u, double *val)
void fc (int n, double u, double *val)
void df (int n, double u, double *val)
Function Documentation
df()
void LegendrePolynomials::df (int n, double u, double * val)
Definition at line 103 of file orthogonalBasis.cpp.
Referenced by GModel::createGeometryOfDiscreteEntities(), createTopologyFromMesh3D(), BergotBasis::df(), GMSH_NearToFarFieldPlugin::execute(), xFemFunctionSpace< T >::gradf(), intrinsicDelaunayize(), GRegion::isFullyDiscrete(), GFace::isFullyDiscrete(), readMSH4Parametrizations(), readMSHEntities(), and writeMSH4Parametrizations().
f()
void LegendrePolynomials::f (int n, double u, double * val)
Definition at line 77 of file orthogonalBasis.cpp.
Referenced by _addElements(), initMeshGFace::_estimateNumLines(), initMeshGFace::_estimateNumTriangles(), _getAdditionalNodesOnBoundary(), _getEntitiesForElementTypes(), _myGetEdgeRep(), picojson::_parse(), cartesianBox< scalar >::_printElements(), cartesianBox< scalar >::_printNodes(), cartesianBox< scalar >::_printValues(), GModel::_readMSH3(), GModel::_storeElementsInEntities(), GModel::adaptMesh(), splitQuadRecovery::add(), GModel::add(), GRegion::addEmbeddedFace(), addExtrudeNormals(), GEdge::addFace(), BDS_Edge::addface(), addOutlinePolyhedron(), addPoints(), alphaShapes(), approximationError(), BDS_Face_Validity(), BGM_MeshMetric(), BGM_MeshSizeWithoutScaling(), fullVector< double >::binaryLoad(), fullMatrix< double >::binaryLoad(), fullVector< double >::binarySave(), fullMatrix< double >::binarySave(), blyr_manager::blyr_manager(), bowyerWatsonParallelograms(), buildUniqueFaces(), canWeProcessCavity(), char2float(), checkDepends(), PolyMesh::cleanf(), Color(), computeCrossField(), computeCrossFieldAndH(), computeEdgeLinearLength(), HilbertSort::ComputeGrayCode(), HilbertSortB::ComputeGrayCode(), computePointsUsingScaledCrossFieldPlanarP2(), computeQuadLayout(), computeSomeKindOfKernel(), connectMElementsByMFace(), MElement::copy(), correctLC_(), createAllEmbeddedFaces(), frameSolver2d::createDofs(), PolyMesh::createFace(), FunctionManager::createFunction(), GModel::createGeometryOfDiscreteEntities(), createTopologyFromMesh3D(), delaunayTrgl(), GModel::deleteMesh(), GEdge::delFace(), BergotBasis::df(), df(), drawArrays(), drawContext::drawBackgroundImage(), drawBarycentricDual(), drawContext::drawEllipse(), drawContext::drawEllipsoid(), drawContext::drawImage(), drawScaleValues(), drawVoronoiDual(), ensureManifoldFaces(), FunctionManager::enterFunction(), GMSH_CrackPlugin::execute(), GMSH_CurlPlugin::execute(), GMSH_DivergencePlugin::execute(), GMSH_GradientPlugin::execute(), GMSH_MeshSizeFieldViewPlugin::execute(), GMSH_ModifyComponentsPlugin::execute(), GMSH_MathEvalPlugin::execute(), GMSH_NearToFarFieldPlugin::execute(), GMSH_ShowNeighborElementsPlugin::execute(), robustPredicates::expansion_sum(), robustPredicates::expansion_sum_zeroelim1(), robustPredicates::expansion_sum_zeroelim2(), elasticitySolver::exportKb(), blyr_manager::extrude_vertex_on_both_surfaces_of_a_ridge(), BergotBasis::f(), orthogonalBasis::f(), MPrism::faceClosureEdge2edge(), MHexahedron::faces_hexa(), MPrism::faces_prism(), MPyramid::faces_pyramid(), MTetrahedron::faces_tetra(), MTrihedron::faces_trihedron(), robustPredicates::fast_expansion_sum(), robustPredicates::fast_expansion_sum_zeroelim(), fc(), extrudeInfo::fillExtrudeParams(), GMSH_CutParametricPlugin::fillXYZ(), DocRecord::FixFirst(), float2char(), Fopen(), MFaceN::frame(), getBoundaryFromMesh(), getCandidateExtrudeInfo(), MPyramid::getEdgeRep(), MPyramidN::getEdgeRep(), MQuadrangle::getFaceRep(), MHexahedron::getFaceRep(), MTrihedron::getFaceRep(), MPrism::getFaceRep(), MPyramid::getFaceRep(), getFacesOfTheModel(), MTetrahedron10::getFaceVertices(), MPrism15::getFaceVertices(), MHexahedron20::getFaceVertices(), MPrism18::getFaceVertices(), MHexahedron27::getFaceVertices(), MTetrahedron::getInnerRadius(), GModel::getMFace(), backgroundMesh::getSmoothness(), GFaceDelaunayRefinement(), GFaceDelaunayRefinementOldMesher(), GFaceInitialMesh(), gLevelsetMathEval::gLevelsetMathEval(), gLevelsetSimpleFunction::gLevelsetSimpleFunction(), gmshLineSearch(), goldenSection(), GOrientedTransfiniteFace::GOrientedTransfiniteFace(), CurvatureField::grad_norm(), GradientDescent(), tetgenmesh::hilbert_init(), HSV_to_RGB(), SurfaceProjector::initialize(), MElement::integrateCirc(), MElement::integrateFlux(), Integration(), MEdgeN::interpolate(), element::interpolateCurl(), MElement::interpolateCurl(), element::interpolateGrad(), MElement::interpolateGrad(), intrinsicDelaunayize(), isCavityCompatibleWithEmbeddedFace(), GRegion::isFullyDiscrete(), FunctionManager::leaveFunction(), robustPredicates::linear_expansion_sum(), robustPredicates::linear_expansion_sum_zeroelim(), GModel::makeDiscreteFacesSimplyConnected(), MakeMeshConformal(), DocRecord::makePosView(), MElement::maxDistToStraight(), Mesh2D(), Mesh3D(), MeshDelaunayVolume(), meshPolygon(), MeshTransfiniteVolume(), qmPrism::minNCJ(), FieldManager::newField(), newton_fd(), MFaceHash::operator()(), meshGEdge::operator()(), FuncGradDisc::operator()(), EmbeddedCompatibilityTest::operator()(), initSmoothNormalsGFace::operator()(), drawGFace::operator()(), initMeshGFace::operator()(), drawMeshGFace::operator()(), MaxEigenHessianField::operator()(), ExternalProcessField::operator()(), MinAnisoField::operator()(), IntersectAnisoField::operator()(), MinField::operator()(), MaxField::operator()(), RestrictField::operator()(), ExtendField::operator()(), topoEdge::operator<(), topoFace::operator<(), topoEdge::operator==(), topoFace::operator==(), BDS_Edge::otherFace(), outputScalarField(), MEdgeN::pnt(), MFaceN::pnt(), PolyMesh2GFace(), backgroundMesh::print(), OctreeField::Cell::print(), PolyMesh::print4debug(), DocRecord::printMedialAxis(), PrintOptionsDoc(), printSizeField(), GModel::readDIFF(), elasticitySolver::readInputFile(), GModel::readVTK(), BDS_Mesh::recover_edge_fast(), RecursiveIntegration(), GModel::remove(), gmshRegion::resetNativePtr(), GMSH_SimplePartitionPlugin::run(), saturateVector(), drawContext::select(), GRegion::set(), GFace::set(), MathEvalExpression::set_function(), MathEvalExpressionAniso::set_function(), picojson::default_parse_context::set_number(), FieldManager::setBackgroundMesh(), GRegion::setColor(), GFace::setEdge(), elasticitySolver::setEdgeDisp(), thermicSolver::setEdgeTemp(), GRegion::setFace(), thermicSolver::setFaceTemp(), setHighOrderFromExistingMesh(), thermicSolver::setLagrangeMultipliers(), elasticitySolver::setLagrangeMultipliers(), GRegion::setOrientations(), GFace::setOrientations(), GRegion::setOutwardOrientationMeshConstraint(), partitionFace::setParentEntity(), SElement::setShapeEnrichement(), SElement::setTestEnrichement(), elasticityTerm::setVector(), GEdge::setVertex(), GRegion::setVisibility(), MElement::skewness(), PViewDataGModel::smooth(), PolyMesh::split_triangle(), starShapeness(), SubdivideExtrudedMesh(), GEO_Internals::synchronize(), tetContainsV(), tetInsideCavityWithFAce(), transferSeamGEdgesVerticesToGFace(), DistanceField::update(), Walk(), walk(), GModel::writeCELUM(), cartesianBox< scalar >::writeMSH(), and writeX3DScaleValues().
fc()
void LegendrePolynomials::fc (int n, double u, double * val)
Definition at line 92 of file orthogonalBasis.cpp.
Referenced by tetgenmesh::add_steinerpt_in_segment(), tetgenmesh::carveholes(), tetgenmesh::checkflipeligibility(), tetgenmesh::flip23(), tetgenmesh::flip32(), tetgenmesh::flip41(), tetgenmesh::flipnm(), tetgenmesh::flipnm_post(), tetgenmesh::improvequalitybyflips(), tetgenmesh::incrementaldelaunay(), tetgenmesh::incrementalflip(), tetgenmesh::lawsonflip3d(), tetgenmesh::recoverdelaunay(), tetgenmesh::recoveredgebyflips(), tetgenmesh::recoverfacebyflips(), tetgenmesh::reduceedgesatvertex(), tetgenmesh::removeedgebyflips(), tetgenmesh::removefacebyflips(), tetgenmesh::removevertexbyflips(), and BoundaryLayerField::setupFor2d().