gmsh-TingyuanDoc: ElementType Namespace Reference
ElementType Namespace Reference
Functions
int getParentType (int type)
int getOrder (int type)
int getDimension (int type)
int getNumVertices (int type)
int getSerendipity (int type)
int getType (int parentType, int order, bool serendip=false)
int getPrimaryType (int type)
std::string nameOfParentType (int type, bool plural=false)
Function Documentation
getDimension()
int ElementType::getDimension (int type)
Definition at line 297 of file ElementType.cpp.
Referenced by nodalBasis::nodalBasis().
getNumVertices()
int ElementType::getNumVertices (int type)
Definition at line 456 of file ElementType.cpp.
Referenced by _relocateVertexOfPyramid(), FilterElementsCutByLevelSet::FilterElementsCutByLevelSet(), getAdditionalEntities(), getElement(), nodalBasis::getNumBubbleShapeFunctions(), groupOfElements::insert(), objective_function(), GMSH_DistancePlugin::printView(), and setHighOrderFromExistingMesh().
getOrder()
int ElementType::getOrder (int type)
Definition at line 158 of file ElementType.cpp.
Referenced by CondNumBasis::condNumOrder(), JacobianBasis::jacobianOrder(), and nodalBasis::nodalBasis().
getParentType()
int ElementType::getParentType (int type)
Definition at line 10 of file ElementType.cpp.
Referenced by checkConformity(), CondNumBasis::CondNumBasis(), CondNumBasis::condNumOrder(), BasisFactory::getGradientBasis(), CondNumBasis::getInvCondNumAndGradientsGeneral(), CondNumBasis::getInvCondNumGeneral(), BasisFactory::getJacobianBasis(), BasisFactory::getNodalBasis(), getPrimaryType(), JacobianBasis::jacobianOrder(), and nodalBasis::nodalBasis().
getPrimaryType()
int ElementType::getPrimaryType (int type)
Definition at line 877 of file ElementType.cpp.
getSerendipity()
int ElementType::getSerendipity (int type)
Definition at line 598 of file ElementType.cpp.
Referenced by MElement::getIsAssimilatedSerendipity(), MElement::getIsOnlySerendipity(), and nodalBasis::nodalBasis().
getType()
int ElementType::getType (int parentType, int order, bool serendip = false)
Definition at line 757 of file ElementType.cpp.
Referenced by _addElements(), CondNumBasis::CondNumBasis(), createTopologyFromMesh2D(), createTopologyFromMesh3D(), filterOverlappingElements(), MFaceN::frame(), ClosureGen::generate2dEdgeClosure(), ClosureGen::generate2dEdgeClosureFull(), ClosureGen::generateFaceClosureHex(), ClosureGen::generateFaceClosurePyr(), ClosureGen::getFaceClosurePrism(), ClosureGen::getFaceClosureTet(), MElement::getFunctionSpace(), MElement::getJacobianFuncSpace(), ScalarToAnyFunctionSpace< SVector3 >::getKeys(), xFemFunctionSpace< T >::getKeys(), MElement::getNodesCoordNonSerendip(), getPrimaryType(), incompleteBasis::incompleteBasis(), MElement::integrateCirc(), MElement::integrateFlux(), MEdgeN::interpolate(), JacobianBasis::JacobianBasis(), MFaceN::normal(), MEdgeN::pnt(), MFaceN::pnt(), MEdgeN::tangent(), and MFaceN::tangent().
nameOfParentType()
std::string ElementType::nameOfParentType (int type, bool plural = false)
Definition at line 882 of file ElementType.cpp.