gmsh-TingyuanDoc: ClosureGen Namespace Reference
ClosureGen Namespace Reference
Functions
double pow2 (double x)
void rotateHex (int iFace, int iRot, int iSign, double uI, double vI, double &uO, double &vO, double &wO)
void rotateHexFull (int iFace, int iRot, int iSign, double uI, double vI, double wI, double &uO, double &vO, double &wO)
void rotatePyr (int iFace, int iRot, int iSign, double uI, double vI, double &uO, double &vO, double &wO)
void generate1dVertexClosure (nodalBasis::clCont &closure, int order)
void generate1dVertexClosureFull (nodalBasis::clCont &closure, std::vector< int > &closureRef, int order)
void getFaceClosureTet (int iFace, int iSign, int iRotate, nodalBasis::closure &closure, int order)
void generate2dEdgeClosureFull (nodalBasis::clCont &closure, std::vector< int > &closureRef, int order, int nNod, bool serendip)
void addEdgeNodes (nodalBasis::clCont &closureFull, const int *edges, int order)
void generateFaceClosureTet (nodalBasis::clCont &closure, int order)
void generateFaceClosureTetFull (nodalBasis::clCont &closureFull, std::vector< int > &closureRef, int order, bool serendip)
void generateFaceClosureHex (nodalBasis::clCont &closure, int order, bool serendip, const fullMatrix< double > &points)
void generateFaceClosureHexFull (nodalBasis::clCont &closure, std::vector< int > &closureRef, int order, bool serendip, const fullMatrix< double > &points)
void fillInteriorFaceNodes (nodalBasis::closure &closure, int idx, int order, int isTriangle, int start)
void reorderFaceClosure (int iSign, int iRotate, nodalBasis::closure &closure, int idx, int order, int isTriangle)
void getFaceClosurePrism (int iFace, int iSign, int iRotate, nodalBasis::closure &closure, int order)
void generateFaceClosurePrism (nodalBasis::clCont &closure, int order)
void generateFaceClosurePrismFull (nodalBasis::clCont &closureFull, std::vector< int > &closureRef, int order)
void generateFaceClosurePyr (nodalBasis::clCont &closure, int order, bool serendip, const fullMatrix< double > &points)
void generate2dEdgeClosure (nodalBasis::clCont &closure, int order, int nNod=3)
void generateClosureOrder0 (nodalBasis::clCont &closure, int nb)
Function Documentation
addEdgeNodes()
void ClosureGen::addEdgeNodes (nodalBasis::clCont & closureFull, const int * edges, int order)
Definition at line 291 of file nodalBasis.cpp.
Referenced by generateFaceClosurePrismFull(), and generateFaceClosureTetFull().
fillInteriorFaceNodes()
void ClosureGen::fillInteriorFaceNodes (nodalBasis::closure & closure, int idx, int order, int isTriangle, int start)
Definition at line 505 of file nodalBasis.cpp.
Referenced by getFaceClosurePrism().
generate1dVertexClosure()
void ClosureGen::generate1dVertexClosure (nodalBasis::clCont & closure, int order)
Definition at line 153 of file nodalBasis.cpp.
Referenced by nodalBasis::nodalBasis().
generate1dVertexClosureFull()
void ClosureGen::generate1dVertexClosureFull (nodalBasis::clCont & closure, std::vector< int > & closureRef, int order)
Definition at line 163 of file nodalBasis.cpp.
Referenced by nodalBasis::nodalBasis().
generate2dEdgeClosure()
void ClosureGen::generate2dEdgeClosure (nodalBasis::clCont & closure, int order, int nNod = 3)
Definition at line 746 of file nodalBasis.cpp.
Referenced by nodalBasis::nodalBasis().
generate2dEdgeClosureFull()
void ClosureGen::generate2dEdgeClosureFull (nodalBasis::clCont & closure, std::vector< int > & closureRef, int order, int nNod, bool serendip)
Definition at line 251 of file nodalBasis.cpp.
Referenced by generateFaceClosureTetFull(), and nodalBasis::nodalBasis().
generateClosureOrder0()
void ClosureGen::generateClosureOrder0 (nodalBasis::clCont & closure, int nb)
Definition at line 765 of file nodalBasis.cpp.
Referenced by nodalBasis::nodalBasis().
generateFaceClosureHex()
void ClosureGen::generateFaceClosureHex (nodalBasis::clCont & closure, int order, bool serendip, const fullMatrix< double > & points)
Definition at line 434 of file nodalBasis.cpp.
Referenced by nodalBasis::nodalBasis().
generateFaceClosureHexFull()
void ClosureGen::generateFaceClosureHexFull (nodalBasis::clCont & closure, std::vector< int > & closureRef, int order, bool serendip, const fullMatrix< double > & points)
Definition at line 468 of file nodalBasis.cpp.
Referenced by nodalBasis::nodalBasis().
generateFaceClosurePrism()
void ClosureGen::generateFaceClosurePrism (nodalBasis::clCont & closure, int order)
Definition at line 618 of file nodalBasis.cpp.
Referenced by generateFaceClosurePrismFull(), and nodalBasis::nodalBasis().
generateFaceClosurePrismFull()
void ClosureGen::generateFaceClosurePrismFull (nodalBasis::clCont & closureFull, std::vector< int > & closureRef, int order)
Definition at line 632 of file nodalBasis.cpp.
Referenced by nodalBasis::nodalBasis().
generateFaceClosurePyr()
void ClosureGen::generateFaceClosurePyr (nodalBasis::clCont & closure, int order, bool serendip, const fullMatrix< double > & points)
Definition at line 704 of file nodalBasis.cpp.
Referenced by nodalBasis::nodalBasis().
generateFaceClosureTet()
void ClosureGen::generateFaceClosureTet (nodalBasis::clCont & closure, int order)
Definition at line 320 of file nodalBasis.cpp.
Referenced by generateFaceClosureTetFull(), and nodalBasis::nodalBasis().
generateFaceClosureTetFull()
void ClosureGen::generateFaceClosureTetFull (nodalBasis::clCont & closureFull, std::vector< int > & closureRef, int order, bool serendip)
Definition at line 334 of file nodalBasis.cpp.
Referenced by nodalBasis::nodalBasis().
getFaceClosurePrism()
void ClosureGen::getFaceClosurePrism (int iFace, int iSign, int iRotate, nodalBasis::closure & closure, int order)
Definition at line 552 of file nodalBasis.cpp.
Referenced by generateFaceClosurePrism().
getFaceClosureTet()
void ClosureGen::getFaceClosureTet (int iFace, int iSign, int iRotate, nodalBasis::closure & closure, int order)
Definition at line 183 of file nodalBasis.cpp.
Referenced by generateFaceClosureTet().
pow2()
double ClosureGen::pow2 (double x) inline
Definition at line 15 of file nodalBasis.cpp.
Referenced by generateFaceClosureHex(), generateFaceClosureHexFull(), and generateFaceClosurePyr().
reorderFaceClosure()
void ClosureGen::reorderFaceClosure (int iSign, int iRotate, nodalBasis::closure & closure, int idx, int order, int isTriangle)
Definition at line 520 of file nodalBasis.cpp.
Referenced by getFaceClosurePrism().
rotateHex()
void ClosureGen::rotateHex (int iFace, int iRot, int iSign, double uI, double vI, double & uO, double & vO, double & wO)
Definition at line 17 of file nodalBasis.cpp.
Referenced by generateFaceClosureHex().
rotateHexFull()
void ClosureGen::rotateHexFull (int iFace, int iRot, int iSign, double uI, double vI, double wI, double & uO, double & vO, double & wO)
Definition at line 64 of file nodalBasis.cpp.
Referenced by generateFaceClosureHexFull().
rotatePyr()
void ClosureGen::rotatePyr (int iFace, int iRot, int iSign, double uI, double vI, double & uO, double & vO, double & wO)
Definition at line 111 of file nodalBasis.cpp.
Referenced by generateFaceClosurePyr().