gmsh-TingyuanDoc: src/numeric/pointsGenerators.cpp File Reference
pointsGenerators.cpp File Reference
#include "pointsGenerators.h"
#include "GmshDefines.h"
#include "MTriangle.h"
#include "MQuadrangle.h"
#include "MTetrahedron.h"
#include "MHexahedron.h"
#include "MPrism.h"
#include "MPyramid.h"
#include "FuncSpaceData.h"
Functions
void gmshGeneratePoints (FuncSpaceData data, fullMatrix< double > &points)
fullMatrix< double > gmshGeneratePointsLine (int order)
fullMatrix< double > gmshGeneratePointsTriangle (int order, bool serendip)
fullMatrix< double > gmshGeneratePointsQuadrangle (int order, bool serendip)
fullMatrix< double > gmshGeneratePointsTetrahedron (int order, bool serendip)
fullMatrix< double > gmshGeneratePointsHexahedron (int order, bool serendip)
fullMatrix< double > gmshGeneratePointsPrism (int order, bool serendip)
fullMatrix< double > gmshGeneratePointsPyramid (int order, bool serendip)
fullMatrix< double > gmshGeneratePointsPyramidGeneral (bool pyr, int nij, int nk, bool forSerendipPoints)
void gmshGenerateMonomials (FuncSpaceData data, fullMatrix< double > &monomials)
fullMatrix< double > gmshGenerateMonomialsLine (int order, bool serendip)
fullMatrix< double > gmshGenerateMonomialsTriangle (int order, bool serendip)
fullMatrix< double > gmshGenerateMonomialsQuadrangle (int order, bool forSerendipPoints)
fullMatrix< double > gmshGenerateMonomialsQuadSerendipity (int order)
fullMatrix< double > gmshGenerateMonomialsTetrahedron (int order, bool serendip)
fullMatrix< double > gmshGenerateMonomialsPrism (int order, bool forSerendipPoints)
fullMatrix< double > gmshGenerateMonomialsPrismSerendipity (int order)
fullMatrix< double > gmshGenerateMonomialsHexahedron (int order, bool forSerendipPoints)
fullMatrix< double > gmshGenerateMonomialsHexaSerendipity (int order)
fullMatrix< double > gmshGenerateMonomialsPyramid (int order, bool forSerendipPoints)
fullMatrix< double > gmshGenerateMonomialsPyramidSerendipity (int order)
fullMatrix< double > gmshGenerateMonomialsPyramidGeneral (bool pyr, int nij, int nk, bool forSerendipPoints)
void gmshGenerateOrderedPointsLine (int order, fullVector< double > &points)
void gmshGenerateOrderedPoints (FuncSpaceData data, fullMatrix< double > &points, bool onBezierDomain)
void gmshGenerateOrderedMonomials (FuncSpaceData data, fullMatrix< double > &monomials)
Function Documentation
gmshGenerateMonomials()
void gmshGenerateMonomials (FuncSpaceData data, fullMatrix< double > & monomials)
Definition at line 138 of file pointsGenerators.cpp.
gmshGenerateMonomialsHexahedron()
fullMatrix<double> gmshGenerateMonomialsHexahedron (int order, bool forSerendipPoints)
Definition at line 583 of file pointsGenerators.cpp.
Referenced by _getIndicesReversedHex(), gmshGenerateInnerVertexPlacementHexahedron(), gmshGenerateInnerVertexPlacementHexahedronLinear(), gmshGenerateMonomials(), gmshGenerateMonomialsHexahedron(), gmshGeneratePointsHexahedron(), and polynomialBasis::polynomialBasis().
gmshGenerateMonomialsHexaSerendipity()
fullMatrix<double> gmshGenerateMonomialsHexaSerendipity (int order)
Definition at line 678 of file pointsGenerators.cpp.
Referenced by polynomialBasis::polynomialBasis().
gmshGenerateMonomialsLine()
fullMatrix<double> gmshGenerateMonomialsLine (int order, bool serendip)
Definition at line 171 of file pointsGenerators.cpp.
Referenced by gmshGenerateMonomials(), gmshGenerateMonomialsPrism(), gmshGeneratePointsLine(), and polynomialBasis::polynomialBasis().
gmshGenerateMonomialsPrism()
fullMatrix<double> gmshGenerateMonomialsPrism (int order, bool forSerendipPoints)
Definition at line 402 of file pointsGenerators.cpp.
Referenced by _getIndicesReversedPri(), gmshGenerateInnerVertexPlacementPrism(), gmshGenerateInnerVertexPlacementPrismLinear(), gmshGenerateMonomials(), gmshGeneratePointsPrism(), and polynomialBasis::polynomialBasis().
gmshGenerateMonomialsPrismSerendipity()
fullMatrix<double> gmshGenerateMonomialsPrismSerendipity (int order)
Definition at line 517 of file pointsGenerators.cpp.
Referenced by polynomialBasis::polynomialBasis().
gmshGenerateMonomialsPyramid()
fullMatrix<double> gmshGenerateMonomialsPyramid (int order, bool forSerendipPoints)
Definition at line 737 of file pointsGenerators.cpp.
Referenced by _getIndicesReversedPyr(), gmshGenerateInnerVertexPlacementPyramid(), gmshGenerateMonomialsPyramid(), gmshGenerateMonomialsPyramidGeneral(), and gmshGeneratePointsPyramid().
gmshGenerateMonomialsPyramidGeneral()
fullMatrix<double> gmshGenerateMonomialsPyramidGeneral (bool pyr, int nij, int nk, bool forSerendipPoints)
Definition at line 921 of file pointsGenerators.cpp.
Referenced by gmshGenerateMonomials(), and gmshGeneratePointsPyramidGeneral().
gmshGenerateMonomialsPyramidSerendipity()
fullMatrix<double> gmshGenerateMonomialsPyramidSerendipity (int order)
Definition at line 845 of file pointsGenerators.cpp.
gmshGenerateMonomialsQuadrangle()
fullMatrix<double> gmshGenerateMonomialsQuadrangle (int order, bool forSerendipPoints)
Definition at line 222 of file pointsGenerators.cpp.
Referenced by gmshGenerateInnerVertexPlacementQuadrangle(), gmshGenerateInnerVertexPlacementQuadrangleLinear(), gmshGenerateMonomials(), gmshGenerateMonomialsHexahedron(), gmshGenerateMonomialsPrism(), gmshGenerateMonomialsPyramid(), gmshGenerateMonomialsQuadrangle(), gmshGeneratePointsQuadrangle(), and polynomialBasis::polynomialBasis().
gmshGenerateMonomialsQuadSerendipity()
fullMatrix<double> gmshGenerateMonomialsQuadSerendipity (int order)
Definition at line 276 of file pointsGenerators.cpp.
Referenced by polynomialBasis::polynomialBasis().
gmshGenerateMonomialsTetrahedron()
fullMatrix<double> gmshGenerateMonomialsTetrahedron (int order, bool serendip)
Definition at line 317 of file pointsGenerators.cpp.
Referenced by _getIndicesReversedTet(), gmshGenerateInnerVertexPlacementTetrahedron(), gmshGenerateInnerVertexPlacementTetrahedronLinear(), gmshGenerateMonomials(), gmshGenerateMonomialsTetrahedron(), gmshGeneratePointsTetrahedron(), and polynomialBasis::polynomialBasis().
gmshGenerateMonomialsTriangle()
fullMatrix<double> gmshGenerateMonomialsTriangle (int order, bool serendip)
Definition at line 182 of file pointsGenerators.cpp.
Referenced by gmshGenerateInnerVertexPlacementTriangle(), gmshGenerateInnerVertexPlacementTriangleLinear(), gmshGenerateMonomials(), gmshGenerateMonomialsPrism(), gmshGenerateMonomialsPyramid(), gmshGenerateMonomialsTetrahedron(), gmshGenerateMonomialsTriangle(), gmshGeneratePointsTriangle(), and polynomialBasis::polynomialBasis().
gmshGenerateOrderedMonomials()
void gmshGenerateOrderedMonomials (FuncSpaceData data, fullMatrix< double > & monomials)
Definition at line 1165 of file pointsGenerators.cpp.
Referenced by gmshGenerateOrderedPoints().
gmshGenerateOrderedPoints()
void gmshGenerateOrderedPoints (FuncSpaceData data, fullMatrix< double > & points, bool onBezierDomain)
Definition at line 1080 of file pointsGenerators.cpp.
Referenced by bezierBasis::_construct(), bezierBasis::_constructPyr(), and GradientBasis::GradientBasis().
gmshGenerateOrderedPointsLine()
void gmshGenerateOrderedPointsLine (int order, fullVector< double > & points)
Definition at line 1071 of file pointsGenerators.cpp.
Referenced by bezierCoeff::_computeCoefficients(), and bezierBasis::_construct().
gmshGeneratePoints()
void gmshGeneratePoints (FuncSpaceData data, fullMatrix< double > & points)
Definition at line 18 of file pointsGenerators.cpp.
Referenced by CondNumBasis::CondNumBasis(), and JacobianBasis::JacobianBasis().
gmshGeneratePointsHexahedron()
fullMatrix<double> gmshGeneratePointsHexahedron (int order, bool serendip)
Definition at line 76 of file pointsGenerators.cpp.
Referenced by gmshGeneratePoints(), and nodalBasis::nodalBasis().
gmshGeneratePointsLine()
fullMatrix<double> gmshGeneratePointsLine (int order)
Definition at line 42 of file pointsGenerators.cpp.
Referenced by gmshGeneratePoints(), and nodalBasis::nodalBasis().
gmshGeneratePointsPrism()
fullMatrix<double> gmshGeneratePointsPrism (int order, bool serendip)
Definition at line 85 of file pointsGenerators.cpp.
Referenced by gmshGeneratePoints(), and nodalBasis::nodalBasis().
gmshGeneratePointsPyramid()
fullMatrix<double> gmshGeneratePointsPyramid (int order, bool serendip)
Definition at line 98 of file pointsGenerators.cpp.
Referenced by nodalBasis::nodalBasis().
gmshGeneratePointsPyramidGeneral()
fullMatrix<double> gmshGeneratePointsPyramidGeneral (bool pyr, int nij, int nk, bool forSerendipPoints)
Definition at line 111 of file pointsGenerators.cpp.
Referenced by gmshGeneratePoints().
gmshGeneratePointsQuadrangle()
fullMatrix<double> gmshGeneratePointsQuadrangle (int order, bool serendip)
Definition at line 59 of file pointsGenerators.cpp.
Referenced by gmshGeneratePoints(), and nodalBasis::nodalBasis().
gmshGeneratePointsTetrahedron()
fullMatrix<double> gmshGeneratePointsTetrahedron (int order, bool serendip)
Definition at line 68 of file pointsGenerators.cpp.
Referenced by gmshGeneratePoints(), and nodalBasis::nodalBasis().
gmshGeneratePointsTriangle()
fullMatrix<double> gmshGeneratePointsTriangle (int order, bool serendip)
Definition at line 51 of file pointsGenerators.cpp.
Referenced by gmshGeneratePoints(), and nodalBasis::nodalBasis().