gmsh-TingyuanDoc: src/solver/solverAlgorithms.h File Reference
solverAlgorithms.h File Reference
#include "dofManager.h"
#include "terms.h"
#include "quadratureRules.h"
#include "MVertex.h"
Classes
class FilterDof
class FilterDofTrivial
class FilterDofComponent
class FilterDofSet
Functions
template<class Iterator , class Assembler >
void Assemble (BilinearTermBase &term, FunctionSpaceBase &space, Iterator itbegin, Iterator itend, QuadratureBase &integrator, Assembler &assembler)
template<class Iterator , class Assembler >
void Assemble (BilinearTermBase &term, FunctionSpaceBase &space, Iterator itbegin, Iterator itend, QuadratureBase &integrator, Assembler &assembler, elementFilter &efilter)
template<class Assembler >
void Assemble (BilinearTermBase &term, FunctionSpaceBase &space, MElement *e, QuadratureBase &integrator, Assembler &assembler)
template<class Iterator , class Assembler >
void Assemble (BilinearTermBase &term, FunctionSpaceBase &shapeFcts, FunctionSpaceBase &testFcts, Iterator itbegin, Iterator itend, QuadratureBase &integrator, Assembler &assembler)
template<class Iterator , class Assembler >
void Assemble (LinearTermBase< double > &term, FunctionSpaceBase &space, Iterator itbegin, Iterator itend, QuadratureBase &integrator, Assembler &assembler)
template<class Iterator , class Assembler >
void Assemble (LinearTermBase< double > &term, FunctionSpaceBase &space, Iterator itbegin, Iterator itend, QuadratureBase &integrator, Assembler &assembler, elementFilter &efilter)
template<class Assembler >
void Assemble (LinearTermBase< double > &term, FunctionSpaceBase &space, MElement *e, QuadratureBase &integrator, Assembler &assembler)
template<class Iterator , class dataMat >
void Assemble (ScalarTermBase< double > &term, Iterator itbegin, Iterator itend, QuadratureBase &integrator, dataMat &val)
template<class Iterator , class dataMat >
void Assemble (ScalarTermBase< double > &term, Iterator itbegin, Iterator itend, QuadratureBase &integrator, dataMat &val, elementFilter &efilter)
template<class Iterator , class dataMat >
void Assemble (ScalarTermBase< double > &term, MElement *e, QuadratureBase &integrator, dataMat &val)
template<class Assembler >
void FixDofs (Assembler &assembler, std::vector< Dof > &dofs, std::vector< typename Assembler::dataVec > &vals)
template<class Assembler >
void FixNodalDofs (FunctionSpaceBase &space, MElement *e, Assembler &assembler, simpleFunction< typename Assembler::dataVec > &fct, FilterDof &filter)
template<class Iterator , class Assembler >
void FixNodalDofs (FunctionSpaceBase &space, Iterator itbegin, Iterator itend, Assembler &assembler, simpleFunction< typename Assembler::dataVec > &fct, FilterDof &filter)
template<class Iterator , class Assembler >
void FixVoidNodalDofs (FunctionSpaceBase &space, Iterator itbegin, Iterator itend, Assembler &assembler)
template<class Iterator , class Assembler >
void NumberDofs (FunctionSpaceBase &space, Iterator itbegin, Iterator itend, Assembler &assembler)
Function Documentation
Assemble() [1/10]
template<class Iterator , class Assembler > void Assemble (BilinearTermBase & term, FunctionSpaceBase & shapeFcts, FunctionSpaceBase & testFcts, Iterator itbegin, Iterator itend, QuadratureBase & integrator, Assembler & assembler)
Definition at line 72 of file solverAlgorithms.h.
Assemble() [2/10]
template<class Iterator , class Assembler > void Assemble (BilinearTermBase & term, FunctionSpaceBase & space, Iterator itbegin, Iterator itend, QuadratureBase & integrator, Assembler & assembler)
Definition at line 19 of file solverAlgorithms.h.
Referenced by thermicSolver::assemble(), elasticitySolver::assemble(), elasticitySolver::postSolve(), and elasticitySolver::solve().
Assemble() [3/10]
template<class Iterator , class Assembler > void Assemble (BilinearTermBase & term, FunctionSpaceBase & space, Iterator itbegin, Iterator itend, QuadratureBase & integrator, Assembler & assembler, elementFilter & efilter)
Definition at line 38 of file solverAlgorithms.h.
Assemble() [4/10]
template<class Assembler > void Assemble (BilinearTermBase & term, FunctionSpaceBase & space, MElement * e, QuadratureBase & integrator, Assembler & assembler)
Definition at line 59 of file solverAlgorithms.h.
Assemble() [5/10]
template<class Iterator , class Assembler > void Assemble (LinearTermBase< double > & term, FunctionSpaceBase & space, Iterator itbegin, Iterator itend, QuadratureBase & integrator, Assembler & assembler)
Definition at line 119 of file solverAlgorithms.h.
Assemble() [6/10]
template<class Iterator , class Assembler > void Assemble (LinearTermBase< double > & term, FunctionSpaceBase & space, Iterator itbegin, Iterator itend, QuadratureBase & integrator, Assembler & assembler, elementFilter & efilter)
Definition at line 137 of file solverAlgorithms.h.
Assemble() [7/10]
template<class Assembler > void Assemble (LinearTermBase< double > & term, FunctionSpaceBase & space, MElement * e, QuadratureBase & integrator, Assembler & assembler)
Definition at line 157 of file solverAlgorithms.h.
Assemble() [8/10]
template<class Iterator , class dataMat > void Assemble (ScalarTermBase< double > & term, Iterator itbegin, Iterator itend, QuadratureBase & integrator, dataMat & val)
Definition at line 170 of file solverAlgorithms.h.
Assemble() [9/10]
template<class Iterator , class dataMat > void Assemble (ScalarTermBase< double > & term, Iterator itbegin, Iterator itend, QuadratureBase & integrator, dataMat & val, elementFilter & efilter)
Definition at line 184 of file solverAlgorithms.h.
Assemble() [10/10]
template<class Iterator , class dataMat > void Assemble (ScalarTermBase< double > & term, MElement * e, QuadratureBase & integrator, dataMat & val)
Definition at line 200 of file solverAlgorithms.h.
FixDofs()
template<class Assembler > void FixDofs (Assembler & assembler, std::vector< Dof > & dofs, std::vector< typename Assembler::dataVec > & vals)
Definition at line 211 of file solverAlgorithms.h.
FixNodalDofs() [1/2]
template<class Iterator , class Assembler > void FixNodalDofs (FunctionSpaceBase & space, Iterator itbegin, Iterator itend, Assembler & assembler, simpleFunction< typename Assembler::dataVec > & fct, FilterDof & filter)
Definition at line 295 of file solverAlgorithms.h.
FixNodalDofs() [2/2]
template<class Assembler > void FixNodalDofs (FunctionSpaceBase & space, MElement * e, Assembler & assembler, simpleFunction< typename Assembler::dataVec > & fct, FilterDof & filter)
Definition at line 270 of file solverAlgorithms.h.
Referenced by thermicSolver::assemble(), elasticitySolver::assemble(), FixNodalDofs(), and FixVoidNodalDofs().
FixVoidNodalDofs()
template<class Iterator , class Assembler > void FixVoidNodalDofs (FunctionSpaceBase & space, Iterator itbegin, Iterator itend, Assembler & assembler)
Definition at line 305 of file solverAlgorithms.h.
Referenced by elasticitySolver::assemble().
NumberDofs()
template<class Iterator , class Assembler > void NumberDofs (FunctionSpaceBase & space, Iterator itbegin, Iterator itend, Assembler & assembler)
Definition at line 314 of file solverAlgorithms.h.
Referenced by thermicSolver::assemble(), and elasticitySolver::assemble().