gmsh-TingyuanDoc: crossField2d Struct Reference
crossField2d Struct Reference
#include <BackgroundMesh.h>
Public Member Functions
crossField2d (MVertex *, GEdge *)
crossField2d (double a)
crossField2d & operator+= (const crossField2d &)
Static Public Member Functions
static void normalizeAngle (double &angle)
Public Attributes
double _angle
Detailed Description
Definition at line 32 of file BackgroundMesh.h.
Constructor & Destructor Documentation
crossField2d() [1/2]
crossField2d::crossField2d (MVertex * v, GEdge * ge)
Definition at line 276 of file BackgroundMesh.cpp.
crossField2d() [2/2]
crossField2d::crossField2d (double a) inline
Definition at line 42 of file BackgroundMesh.h.
Member Function Documentation
normalizeAngle()
static void crossField2d::normalizeAngle (double & angle) inline static
Definition at line 34 of file BackgroundMesh.h.
Referenced by crossField2d(), backgroundMesh::getAngle(), backgroundMesh::propagateCrossField(), and backgroundMesh::propagateCrossFieldByDistance().
operator+=()
crossField2d& crossField2d::operator+= (const crossField2d &)
Member Data Documentation
_angle
double crossField2d::_angle
Definition at line 33 of file BackgroundMesh.h.
Referenced by crossField2d().
The documentation for this struct was generated from the following files:
src/mesh/BackgroundMesh.h
src/mesh/BackgroundMesh.cpp