gmsh-TingyuanDoc: Vert Struct Reference
Vert Struct Reference
Public Member Functions
void setT (Tet *t)
Tet * getT () const
std::size_t getNum () const
void setNum (std::size_t n)
double x () const
double y () const
double z () const
double lc () const
double & x ()
double & y ()
double & z ()
double & lc ()
operator double * ()
Vert (double X=0, double Y=0, double Z=0, double lc=0, int num=0)
Vert operator+ (const Vert &other)
Vert operator* (const double &other)
SPoint3 point () const
Public Attributes
unsigned char _thread
Private Attributes
double _x [3]
double _lc
std::size_t _num
Tet * _t
Detailed Description
Definition at line 36 of file delaunay3d.cpp.
Constructor & Destructor Documentation
Vert()
Vert::Vert (double X = 0, double Y = 0, double Z = 0, double lc = 0, int num = 0) inline
Definition at line 58 of file delaunay3d.cpp.
Referenced by operator*(), and operator+().
Member Function Documentation
getNum()
std::size_t Vert::getNum () const inline
Definition at line 46 of file delaunay3d.cpp.
Referenced by delaunayTriangulation().
getT()
Tet* Vert::getT () const inline
Definition at line 45 of file delaunay3d.cpp.
lc() [1/2]
double& Vert::lc () inline
Definition at line 56 of file delaunay3d.cpp.
lc() [2/2]
double Vert::lc () const inline
Definition at line 52 of file delaunay3d.cpp.
Referenced by operator+(), and Vert().
operator double *()
Vert::operator double * () inline
Definition at line 57 of file delaunay3d.cpp.
operator*()
Vert Vert::operator* (const double & other) inline
Definition at line 71 of file delaunay3d.cpp.
operator+()
Vert Vert::operator+ (const Vert & other) inline
Definition at line 66 of file delaunay3d.cpp.
point()
SPoint3 Vert::point () const inline
Definition at line 75 of file delaunay3d.cpp.
setNum()
void Vert::setNum (std::size_t n) inline
Definition at line 47 of file delaunay3d.cpp.
Referenced by delaunayTriangulation().
setT()
void Vert::setT (Tet * t) inline
Definition at line 44 of file delaunay3d.cpp.
Referenced by Tet::setVertices(), and Tet::setVerticesNoTest().
x() [1/2]
double& Vert::x () inline
Definition at line 53 of file delaunay3d.cpp.
x() [2/2]
double Vert::x () const inline
Definition at line 49 of file delaunay3d.cpp.
Referenced by HilbertSortB::Apply(), delaunayTriangulation(), initialCube(), operator*(), operator+(), and point().
y() [1/2]
double& Vert::y () inline
Definition at line 54 of file delaunay3d.cpp.
y() [2/2]
double Vert::y () const inline
Definition at line 50 of file delaunay3d.cpp.
Referenced by HilbertSortB::Apply(), delaunayTriangulation(), initialCube(), operator*(), operator+(), and point().
z() [1/2]
double& Vert::z () inline
Definition at line 55 of file delaunay3d.cpp.
z() [2/2]
double Vert::z () const inline
Definition at line 51 of file delaunay3d.cpp.
Referenced by HilbertSortB::Apply(), delaunayTriangulation(), initialCube(), operator*(), operator+(), and point().
Member Data Documentation
_lc
double Vert::_lc private
Definition at line 39 of file delaunay3d.cpp.
Referenced by lc(), operator*(), operator+(), and Vert().
_num
std::size_t Vert::_num private
Definition at line 40 of file delaunay3d.cpp.
Referenced by getNum(), and setNum().
_t
Tet* Vert::_t private
Definition at line 41 of file delaunay3d.cpp.
Referenced by getT(), and setT().
_thread
unsigned char Vert::_thread
Definition at line 48 of file delaunay3d.cpp.
_x
double Vert::_x[3] private
Definition at line 38 of file delaunay3d.cpp.
Referenced by operator double *(), Vert(), x(), y(), and z().
The documentation for this struct was generated from the following file:
src/mesh/delaunay3d.cpp