gmsh-TingyuanDoc: edgeXface Struct Reference
edgeXface Struct Reference
#include <meshGFaceDelaunayInsertion.h>
Public Member Functions
edgeXface (MTri3 *_t, int iFac)
MVertex * _v (int i) const
bool operator< (const edgeXface &other) const
bool operator== (const edgeXface &other) const
Public Attributes
MVertex * v [2]
MTri3 * t1
int i1
int ori
Detailed Description
Definition at line 177 of file meshGFaceDelaunayInsertion.h.
Constructor & Destructor Documentation
edgeXface()
edgeXface::edgeXface (MTri3 * _t, int iFac) inline
Definition at line 182 of file meshGFaceDelaunayInsertion.h.
Member Function Documentation
_v()
MVertex* edgeXface::_v (int i) const inline
Definition at line 193 of file meshGFaceDelaunayInsertion.h.
Referenced by delaunayMeshIn2D(), operator<(), operator==(), and recurFindCavityAniso().
operator<()
bool edgeXface::operator< (const edgeXface & other) const inline
Definition at line 194 of file meshGFaceDelaunayInsertion.h.
operator==()
bool edgeXface::operator== (const edgeXface & other) const inline
Definition at line 201 of file meshGFaceDelaunayInsertion.h.
Member Data Documentation
i1
int edgeXface::i1
Definition at line 180 of file meshGFaceDelaunayInsertion.h.
Referenced by connectTris(), and delaunayMeshIn2D().
ori
int edgeXface::ori
Definition at line 181 of file meshGFaceDelaunayInsertion.h.
Referenced by edgeXface().
t1
MTri3* edgeXface::t1
Definition at line 179 of file meshGFaceDelaunayInsertion.h.
Referenced by connectTris(), delaunayMeshIn2D(), and edgeXface().
v
MVertex* edgeXface::v[2]
Definition at line 178 of file meshGFaceDelaunayInsertion.h.
Referenced by _v(), and edgeXface().
The documentation for this struct was generated from the following file:
src/mesh/meshGFaceDelaunayInsertion.h