gmsh-TingyuanDoc: HilbertSort Struct Reference
HilbertSort Struct Reference
Public Member Functions
void ComputeGrayCode (int n)
int Split (MVertex **vertices, int arraysize, int GrayCode0, int GrayCode1, double BoundingBoxXmin, double BoundingBoxXmax, double BoundingBoxYmin, double BoundingBoxYmax, double BoundingBoxZmin, double BoundingBoxZmax)
void Sort (MVertex **vertices, int arraysize, int e, int d, double BoundingBoxXmin, double BoundingBoxXmax, double BoundingBoxYmin, double BoundingBoxYmax, double BoundingBoxZmin, double BoundingBoxZmax, int depth)
HilbertSort (int m=0, int l=2)
void MultiscaleSortHilbert (MVertex **vertices, int arraysize, int threshold, double ratio, int *depth)
void Apply (std::vector< MVertex * > &v)
Public Attributes
int transgc [8][3][8]
int tsb1mod3 [8]
int maxDepth
int Limit
SBoundingBox3d bbox
Detailed Description
Definition at line 9 of file HilbertCurve.cpp.
Constructor & Destructor Documentation
HilbertSort()
HilbertSort::HilbertSort (int m = 0, int l = 2) inline
Definition at line 26 of file HilbertCurve.cpp.
Member Function Documentation
Apply()
void HilbertSort::Apply (std::vector< MVertex * > & v) inline
Definition at line 45 of file HilbertCurve.cpp.
Referenced by SortHilbert().
ComputeGrayCode()
void HilbertSort::ComputeGrayCode (int n)
Definition at line 58 of file HilbertCurve.cpp.
Referenced by HilbertSort().
MultiscaleSortHilbert()
void HilbertSort::MultiscaleSortHilbert (MVertex ** vertices, int arraysize, int threshold, double ratio, int * depth) inline
Definition at line 30 of file HilbertCurve.cpp.
Referenced by Apply().
Sort()
void HilbertSort::Sort (MVertex ** vertices, int arraysize, int e, int d, double BoundingBoxXmin, double BoundingBoxXmax, double BoundingBoxYmin, double BoundingBoxYmax, double BoundingBoxZmin, double BoundingBoxZmax, int depth)
Definition at line 173 of file HilbertCurve.cpp.
Referenced by MultiscaleSortHilbert().
Split()
int HilbertSort::Split (MVertex ** vertices, int arraysize, int GrayCode0, int GrayCode1, double BoundingBoxXmin, double BoundingBoxXmax, double BoundingBoxYmin, double BoundingBoxYmax, double BoundingBoxZmin, double BoundingBoxZmax)
Definition at line 99 of file HilbertCurve.cpp.
Referenced by Sort().
Member Data Documentation
bbox
SBoundingBox3d HilbertSort::bbox
Definition at line 16 of file HilbertCurve.cpp.
Referenced by Apply(), and MultiscaleSortHilbert().
Limit
int HilbertSort::Limit
Definition at line 15 of file HilbertCurve.cpp.
Referenced by Sort().
maxDepth
int HilbertSort::maxDepth
Definition at line 14 of file HilbertCurve.cpp.
Referenced by Sort().
transgc
int HilbertSort::transgc[8][3][8]
Definition at line 12 of file HilbertCurve.cpp.
Referenced by ComputeGrayCode(), and Sort().
tsb1mod3
int HilbertSort::tsb1mod3[8]
Definition at line 13 of file HilbertCurve.cpp.
Referenced by ComputeGrayCode(), and Sort().
The documentation for this struct was generated from the following file:
src/numeric/HilbertCurve.cpp