gmsh-TingyuanDoc: edgeContainerB Struct Reference
edgeContainerB Struct Reference
Public Member Functions
edgeContainerB (std::size_t N=1000000)
std::size_t H (const MEdge &e) const
bool find (const MEdge &e) const
bool empty () const
bool addNewEdge (const MEdge &e)
Public Attributes
std::vector< std::vector< MEdge > > _hash
std::size_t _size
std::size_t _size_obj
Detailed Description
Definition at line 78 of file meshGRegionDelaunayInsertion.cpp.
Constructor & Destructor Documentation
edgeContainerB()
edgeContainerB::edgeContainerB (std::size_t N = 1000000) inline
Definition at line 82 of file meshGRegionDelaunayInsertion.cpp.
Member Function Documentation
addNewEdge()
bool edgeContainerB::addNewEdge (const MEdge & e) inline
Definition at line 101 of file meshGRegionDelaunayInsertion.cpp.
Referenced by createAllEmbeddedEdges().
empty()
bool edgeContainerB::empty () const inline
Definition at line 99 of file meshGRegionDelaunayInsertion.cpp.
Referenced by insertVerticesInRegion(), and isCavityCompatibleWithEmbeddedEdges().
find()
bool edgeContainerB::find (const MEdge & e) const inline
Definition at line 93 of file meshGRegionDelaunayInsertion.cpp.
Referenced by isCavityCompatibleWithEmbeddedEdges().
H()
std::size_t edgeContainerB::H (const MEdge & e) const inline
Definition at line 87 of file meshGRegionDelaunayInsertion.cpp.
Referenced by addNewEdge(), and find().
Member Data Documentation
_hash
std::vector<std::vector<MEdge> > edgeContainerB::_hash
Definition at line 79 of file meshGRegionDelaunayInsertion.cpp.
Referenced by addNewEdge(), find(), and H().
_size
std::size_t edgeContainerB::_size
Definition at line 80 of file meshGRegionDelaunayInsertion.cpp.
Referenced by addNewEdge(), and empty().
_size_obj
std::size_t edgeContainerB::_size_obj
Definition at line 80 of file meshGRegionDelaunayInsertion.cpp.
Referenced by H().
The documentation for this struct was generated from the following file:
src/mesh/meshGRegionDelaunayInsertion.cpp