gmsh-TingyuanDoc: GL2PSbackend Struct Reference
GL2PSbackend Struct Reference
Public Attributes
void(* printHeader)(void)
void(* printFooter)(void)
void(* beginViewport)(GLint viewport[4])
GLint(* endViewport)(void)
void(* printPrimitive)(void *data)
void(* printFinalPrimitive)(void)
const char * file_extension
const char * description
Detailed Description
Definition at line 235 of file gl2ps.cpp.
Member Data Documentation
beginViewport
void(* GL2PSbackend::beginViewport) (GLint viewport[4])
Definition at line 238 of file gl2ps.cpp.
Referenced by gl2psBeginViewport().
description
const char* GL2PSbackend::description
Definition at line 243 of file gl2ps.cpp.
Referenced by gl2psGetFormatDescription().
endViewport
GLint(* GL2PSbackend::endViewport) (void)
Definition at line 239 of file gl2ps.cpp.
Referenced by gl2psEndViewport().
file_extension
const char* GL2PSbackend::file_extension
Definition at line 242 of file gl2ps.cpp.
Referenced by gl2psGetFileExtension().
printFinalPrimitive
void(* GL2PSbackend::printFinalPrimitive) (void)
Definition at line 241 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
printFooter
void(* GL2PSbackend::printFooter) (void)
Definition at line 237 of file gl2ps.cpp.
Referenced by gl2psEndPage().
printHeader
void(* GL2PSbackend::printHeader) (void)
Definition at line 236 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
printPrimitive
void(* GL2PSbackend::printPrimitive) (void *data)
Definition at line 240 of file gl2ps.cpp.
Referenced by gl2psPrintPrimitives().
The documentation for this struct was generated from the following file:
src/graphics/gl2ps.cpp