gmsh-TingyuanDoc: PointCloudAdaptor< Derived > Struct Template Reference
PointCloudAdaptor< Derived > Struct Template Reference
Public Member Functions
PointCloudAdaptor (const Derived &obj_)
const Derived & derived () const
size_t kdtree_get_point_count () const
double kdtree_distance (const double *p1, const size_t idx_p2, size_t) const
double kdtree_get_pt (const size_t idx, int dim) const
template<class BBOX >
bool kdtree_get_bbox (BBOX &) const
Public Attributes
const Derived & obj
Detailed Description
template<typename Derived>
struct PointCloudAdaptor< Derived >
Definition at line 2420 of file Field.cpp.
Constructor & Destructor Documentation
PointCloudAdaptor()
template<typename Derived > PointCloudAdaptor< Derived >::PointCloudAdaptor (const Derived & obj_) inline
Definition at line 2422 of file Field.cpp.
Member Function Documentation
derived()
template<typename Derived > const Derived& PointCloudAdaptor< Derived >::derived () const inline
Definition at line 2423 of file Field.cpp.
Referenced by PointCloudAdaptor< Derived >::kdtree_distance(), PointCloudAdaptor< Derived >::kdtree_get_point_count(), and PointCloudAdaptor< Derived >::kdtree_get_pt().
kdtree_distance()
template<typename Derived > double PointCloudAdaptor< Derived >::kdtree_distance (const double * p1, const size_t idx_p2, size_t) const inline
Definition at line 2425 of file Field.cpp.
kdtree_get_bbox()
template<typename Derived > template<class BBOX > bool PointCloudAdaptor< Derived >::kdtree_get_bbox (BBOX &) const inline
Definition at line 2442 of file Field.cpp.
kdtree_get_point_count()
template<typename Derived > size_t PointCloudAdaptor< Derived >::kdtree_get_point_count () const inline
Definition at line 2424 of file Field.cpp.
kdtree_get_pt()
template<typename Derived > double PointCloudAdaptor< Derived >::kdtree_get_pt (const size_t idx, int dim) const inline
Definition at line 2433 of file Field.cpp.
Member Data Documentation
obj
template<typename Derived > const Derived& PointCloudAdaptor< Derived >::obj
Definition at line 2421 of file Field.cpp.
Referenced by PointCloudAdaptor< Derived >::derived().
The documentation for this struct was generated from the following file:
src/mesh/Field.cpp