gmsh-TingyuanDoc: HilbertSortB Struct Reference
HilbertSortB Struct Reference
Public Member Functions
void ComputeGrayCode (int n)
int Split (Vert **vertices, int arraysize, int GrayCode0, int GrayCode1, double BoundingBoxXmin, double BoundingBoxXmax, double BoundingBoxYmin, double BoundingBoxYmax, double BoundingBoxZmin, double BoundingBoxZmax)
void Sort (Vert **vertices, int arraysize, int e, int d, double BoundingBoxXmin, double BoundingBoxXmax, double BoundingBoxYmin, double BoundingBoxYmax, double BoundingBoxZmin, double BoundingBoxZmax, int depth)
HilbertSortB (int m=0, int l=2)
void MultiscaleSortHilbert (Vert **vertices, int arraysize, int threshold, double ratio, int *depth, std::vector< int > &indices)
void Apply (std::vector< Vert * > &v, std::vector< int > &indices)
Public Attributes
int transgc [8][3][8]
int tsb1mod3 [8]
int maxDepth
int Limit
SBoundingBox3d bbox
Detailed Description
Definition at line 330 of file delaunay3d.cpp.
Constructor & Destructor Documentation
HilbertSortB()
HilbertSortB::HilbertSortB (int m = 0, int l = 2) inline
Definition at line 347 of file delaunay3d.cpp.
Member Function Documentation
Apply()
void HilbertSortB::Apply (std::vector< Vert * > & v, std::vector< int > & indices) inline
Definition at line 366 of file delaunay3d.cpp.
Referenced by SortHilbert().
ComputeGrayCode()
void HilbertSortB::ComputeGrayCode (int n)
Definition at line 383 of file delaunay3d.cpp.
Referenced by HilbertSortB().
MultiscaleSortHilbert()
void HilbertSortB::MultiscaleSortHilbert (Vert ** vertices, int arraysize, int threshold, double ratio, int * depth, std::vector< int > & indices) inline
Definition at line 351 of file delaunay3d.cpp.
Referenced by Apply().
Sort()
void HilbertSortB::Sort (Vert ** vertices, int arraysize, int e, int d, double BoundingBoxXmin, double BoundingBoxXmax, double BoundingBoxYmin, double BoundingBoxYmax, double BoundingBoxZmin, double BoundingBoxZmax, int depth)
Definition at line 496 of file delaunay3d.cpp.
Referenced by MultiscaleSortHilbert().
Split()
int HilbertSortB::Split (Vert ** vertices, int arraysize, int GrayCode0, int GrayCode1, double BoundingBoxXmin, double BoundingBoxXmax, double BoundingBoxYmin, double BoundingBoxYmax, double BoundingBoxZmin, double BoundingBoxZmax)
Definition at line 424 of file delaunay3d.cpp.
Referenced by Sort().
Member Data Documentation
bbox
SBoundingBox3d HilbertSortB::bbox
Definition at line 337 of file delaunay3d.cpp.
Referenced by Apply(), and MultiscaleSortHilbert().
Limit
int HilbertSortB::Limit
Definition at line 336 of file delaunay3d.cpp.
Referenced by Sort().
maxDepth
int HilbertSortB::maxDepth
Definition at line 335 of file delaunay3d.cpp.
Referenced by Sort().
transgc
int HilbertSortB::transgc[8][3][8]
Definition at line 333 of file delaunay3d.cpp.
Referenced by ComputeGrayCode(), and Sort().
tsb1mod3
int HilbertSortB::tsb1mod3[8]
Definition at line 334 of file delaunay3d.cpp.
Referenced by ComputeGrayCode(), and Sort().
The documentation for this struct was generated from the following file:
src/mesh/delaunay3d.cpp