gmsh-TingyuanDoc: Tet Struct Reference
Tet Struct Reference
Public Member Functions
Tet ()
int setVerticesNoTest (Vert *v0, Vert *v1, Vert *v2, Vert *v3)
int setVertices (Vert *v0, Vert *v1, Vert *v2, Vert *v3)
Tet (Vert *v0, Vert *v1, Vert *v2, Vert *v3)
void setAllDeleted ()
void unset (int thread, int iPnt)
void set (int thread, int iPnt)
CHECKTYPE isSet (int thread, int iPnt) const
Face getFace (int k) const
Vert * getOppositeVertex (int k) const
bool inSphere (Vert *vd, int thread)
Public Attributes
Tet * T [4]
Vert * V [4]
CHECKTYPE _bitset [MAX_NUM_THREADS_]
bool _modified
Detailed Description
Definition at line 179 of file delaunay3d.cpp.
Constructor & Destructor Documentation
Tet() [1/2]
Tet::Tet () inline
Definition at line 185 of file delaunay3d.cpp.
Tet() [2/2]
Tet::Tet (Vert * v0, Vert * v1, Vert * v2, Vert * v3) inline
Definition at line 225 of file delaunay3d.cpp.
Member Function Documentation
getFace()
Face Tet::getFace (int k) const inline
Definition at line 241 of file delaunay3d.cpp.
Referenced by buildDelaunayBall(), computeAdjacencies(), delaunayCavity2(), delaunayTrgl(), tetInsideCavityWithFAce(), and walk().
getOppositeVertex()
Vert* Tet::getOppositeVertex (int k) const inline
Definition at line 246 of file delaunay3d.cpp.
inSphere()
bool Tet::inSphere (Vert * vd, int thread) inline
Definition at line 251 of file delaunay3d.cpp.
Referenced by delaunayCavity2(), and walk().
isSet()
CHECKTYPE Tet::isSet (int thread, int iPnt) const inline
Definition at line 237 of file delaunay3d.cpp.
Referenced by delaunayCavity2().
set()
void Tet::set (int thread, int iPnt) inline
Definition at line 236 of file delaunay3d.cpp.
Referenced by delaunayCavity2().
setAllDeleted()
void Tet::setAllDeleted () inline
Definition at line 231 of file delaunay3d.cpp.
Referenced by Tet().
setVertices()
int Tet::setVertices (Vert * v0, Vert * v1, Vert * v2, Vert * v3) inline
Definition at line 202 of file delaunay3d.cpp.
Referenced by initialCube(), and Tet().
setVerticesNoTest()
int Tet::setVerticesNoTest (Vert * v0, Vert * v1, Vert * v2, Vert * v3) inline
Definition at line 191 of file delaunay3d.cpp.
Referenced by delaunayTrgl().
unset()
void Tet::unset (int thread, int iPnt) inline
Definition at line 235 of file delaunay3d.cpp.
Member Data Documentation
_bitset
CHECKTYPE Tet::_bitset[MAX_NUM_THREADS_]
Definition at line 182 of file delaunay3d.cpp.
Referenced by isSet(), set(), setAllDeleted(), and unset().
_modified
bool Tet::_modified
Definition at line 183 of file delaunay3d.cpp.
Referenced by setVertices(), and setVerticesNoTest().
T
Tet* Tet::T[4]
Definition at line 180 of file delaunay3d.cpp.
Referenced by buildDelaunayBall(), computeAdjacencies(), delaunayCavity2(), delaunayTrgl(), removeIsolatedTets(), Tet(), and walk().
V
Vert* Tet::V[4]
Definition at line 181 of file delaunay3d.cpp.
Referenced by delaunayTriangulation(), getFace(), getOppositeVertex(), inSphere(), randomTet(), setVertices(), setVerticesNoTest(), and Tet().
The documentation for this struct was generated from the following file:
src/mesh/delaunay3d.cpp