gmsh-TingyuanDoc: dofTraits< T > Struct Template Reference
dofTraits< T > Struct Template Reference
#include <dofManager.h>
Public Types
typedef T VecType
typedef T MatType
Static Public Member Functions
static void gemm (VecType &r, const MatType &m, const VecType &v, double alpha, double beta)
Detailed Description
template<class T>
struct dofTraits< T >
Definition at line 50 of file dofManager.h.
Member Typedef Documentation
MatType
template<class T > typedef T dofTraits< T >::MatType
Definition at line 52 of file dofManager.h.
VecType
template<class T > typedef T dofTraits< T >::VecType
Definition at line 51 of file dofManager.h.
Member Function Documentation
gemm()
template<class T > static void dofTraits< T >::gemm (VecType & r, const MatType & m, const VecType & v, double alpha, double beta) inline static
Definition at line 53 of file dofManager.h.
Referenced by dofManager< double >::assemble(), dofManager< double >::assembleLinConst(), and dofManager< double >::getDofValue().
The documentation for this struct was generated from the following file:
src/solver/dofManager.h