gmsh-TingyuanDoc: SPoint3CloudAdaptor< Derived > Struct Template Reference
SPoint3CloudAdaptor< Derived > Struct Template Reference
#include <SPoint3KDTree.h>
Public Member Functions
SPoint3CloudAdaptor (const Derived &obj_)
const Derived & derived () const
size_t kdtree_get_point_count () const
double kdtree_distance (const double *p1, const size_t idx_p2, size_t) const
double kdtree_get_pt (const size_t idx, int dim) const
template<class BBOX >
bool kdtree_get_bbox (BBOX &) const
Public Attributes
const Derived & obj
Detailed Description
template<typename Derived>
struct SPoint3CloudAdaptor< Derived >
Definition at line 16 of file SPoint3KDTree.h.
Constructor & Destructor Documentation
SPoint3CloudAdaptor()
template<typename Derived > SPoint3CloudAdaptor< Derived >::SPoint3CloudAdaptor (const Derived & obj_) inline
Definition at line 18 of file SPoint3KDTree.h.
Member Function Documentation
derived()
template<typename Derived > const Derived& SPoint3CloudAdaptor< Derived >::derived () const inline
Definition at line 19 of file SPoint3KDTree.h.
Referenced by SPoint3CloudAdaptor< SPoint3Cloud >::kdtree_distance(), SPoint3CloudAdaptor< SPoint3Cloud >::kdtree_get_point_count(), and SPoint3CloudAdaptor< SPoint3Cloud >::kdtree_get_pt().
kdtree_distance()
template<typename Derived > double SPoint3CloudAdaptor< Derived >::kdtree_distance (const double * p1, const size_t idx_p2, size_t) const inline
Definition at line 21 of file SPoint3KDTree.h.
kdtree_get_bbox()
template<typename Derived > template<class BBOX > bool SPoint3CloudAdaptor< Derived >::kdtree_get_bbox (BBOX &) const inline
Definition at line 38 of file SPoint3KDTree.h.
kdtree_get_point_count()
template<typename Derived > size_t SPoint3CloudAdaptor< Derived >::kdtree_get_point_count () const inline
Definition at line 20 of file SPoint3KDTree.h.
kdtree_get_pt()
template<typename Derived > double SPoint3CloudAdaptor< Derived >::kdtree_get_pt (const size_t idx, int dim) const inline
Definition at line 29 of file SPoint3KDTree.h.
Member Data Documentation
obj
template<typename Derived > const Derived& SPoint3CloudAdaptor< Derived >::obj
Definition at line 17 of file SPoint3KDTree.h.
Referenced by SPoint3CloudAdaptor< SPoint3Cloud >::derived().
The documentation for this struct was generated from the following file:
src/geo/SPoint3KDTree.h