gmsh-TingyuanDoc: StringXColor Struct Reference
StringXColor Struct Reference
#include <Options.h>
Public Attributes
int level
const char * str
unsigned int(* function)(int num, int action, unsigned int val)
unsigned char def1 [4]
unsigned char def2 [4]
unsigned char def3 [4]
unsigned char def4 [4]
const char * help
Detailed Description
Definition at line 926 of file Options.h.
Member Data Documentation
def1
unsigned char StringXColor::def1[4]
Definition at line 933 of file Options.h.
def2
unsigned char StringXColor::def2[4]
Definition at line 933 of file Options.h.
def3
unsigned char StringXColor::def3[4]
Definition at line 933 of file Options.h.
def4
unsigned char StringXColor::def4[4]
Definition at line 933 of file Options.h.
function
unsigned int(* StringXColor::function) (int num, int action, unsigned int val)
Definition at line 929 of file Options.h.
Referenced by ColorOption(), SetColorOptionsGUI(), and SetDefaultColorOptions().
help
const char* StringXColor::help
Definition at line 934 of file Options.h.
level
int StringXColor::level
Definition at line 927 of file Options.h.
str
const char* StringXColor::str
Definition at line 928 of file Options.h.
The documentation for this struct was generated from the following file:
src/common/Options.h