gmsh-TingyuanDoc: src/mesh/tetgenBR.h File Reference
tetgenBR.h File Reference
Classes
class tetgenbehavior
class tetgenmesh
class tetgenmesh::triface
class tetgenmesh::face
class tetgenmesh::arraypool
class tetgenmesh::memorypool
class tetgenmesh::badface
class tetgenmesh::insertvertexflags
class tetgenmesh::flipconstraints
class tetgenmesh::optparameters
class selfint_event
Macros
#define fastlookup(pool, index)
#define fsymself(t)
#define fnextself(t)
#define setvertices(t, torg, tdest, tapex, toppo)
#define setshvertices(s, pa, pb, pc)
#define issubface(t) ((t).tet[9] && ((t).tet[9])[(t).ver & 3])
#define isshtet(s) ((s).sh[9 + ((s).shver & 1)])
#define isshsubseg(s) ((s).sh[6 + ((s).shver >> 1)])
#define issubseg(t) ((t).tet[8] && ((t).tet[8])[ver2edge[(t).ver]])
Functions
void terminatetetgen (tetgenmesh *m, int x)
Variables
static selfint_event sevent
Macro Definition Documentation
fastlookup
#define fastlookup (pool, index)
Value:
  (void *)((pool)->toparray[(index) >> (pool)->log2objectsperblock] +          \
           ((index) & (pool)->objectsperblockmark) * (pool)->objectbytes)
Definition at line 459 of file tetgenBR.h.
fnextself
#define fnextself (t)
Value:
  t1ver = (t).ver;                                                             \
  decode((t).tet[facepivot1[(t).ver]], (t));                                   \
  (t).ver = facepivot2[t1ver][(t).ver]
Definition at line 1723 of file tetgenBR.h.
fsymself
#define fsymself (t)
Value:
  t1ver = (t).ver;                                                             \
  decode((t).tet[(t).ver & 3], (t));                                           \
  (t).ver = fsymtbl[t1ver][(t).ver]
Definition at line 1708 of file tetgenBR.h.
isshsubseg
#define isshsubseg (s) ((s).sh[6 + ((s).shver >> 1)])
Definition at line 2336 of file tetgenBR.h.
isshtet
#define isshtet (s) ((s).sh[9 + ((s).shver & 1)])
Definition at line 2286 of file tetgenBR.h.
issubface
#define issubface (t) ((t).tet[9] && ((t).tet[9])[(t).ver & 3])
Definition at line 2271 of file tetgenBR.h.
issubseg
#define issubseg (t) ((t).tet[8] && ((t).tet[8])[ver2edge[(t).ver]])
Definition at line 2384 of file tetgenBR.h.
setshvertices
#define setshvertices (s, pa, pb, pc)
Value:
  setsorg(s, pa);                                                              \
  setsdest(s, pb);                                                             \
  setsapex(s, pc)
Definition at line 2070 of file tetgenBR.h.
setvertices
#define setvertices (t, torg, tdest, tapex, toppo)
Value:
  (t).tet[orgpivot[(t).ver]] = (tetrahedron)(torg);                            \
  (t).tet[destpivot[(t).ver]] = (tetrahedron)(tdest);                          \
  (t).tet[apexpivot[(t).ver]] = (tetrahedron)(tapex);                          \
  (t).tet[oppopivot[(t).ver]] = (tetrahedron)(toppo)
Definition at line 1771 of file tetgenBR.h.
Function Documentation
terminatetetgen()
void terminatetetgen (tetgenmesh * m, int x) inline
Definition at line 1539 of file tetgenBR.h.
Referenced by tetgenmesh::addsteiner4recoversegment(), tetgenmesh::memorypool::alloc(), tetgenmesh::flip32(), tetgenmesh::flipnm(), tetgenmesh::incrementaldelaunay(), tetgenmesh::incrementalflip(), tetgenmesh::initializepools(), tetgenmesh::insertpoint(), tetgenmesh::insphere_s(), tetgenmesh::lawsonflip3d(), tetgenmesh::orient4d_s(), tetgenmesh::memorypool::poolinit(), tetgenmesh::recoveredgebyflips(), tetgenmesh::recoverfacebyflips(), tetgenmesh::recoversubfaces(), tetgenmesh::removeedgebyflips(), tetgenmesh::report_overlapping_facets(), tetgenmesh::report_selfint_edge(), tetgenmesh::report_selfint_face(), and tetgenmesh::smoothpoint().
Variable Documentation
sevent
selfint_event sevent static
Definition at line 1537 of file tetgenBR.h.
Referenced by tetgenmesh::report_overlapping_facets(), tetgenmesh::report_selfint_edge(), and tetgenmesh::report_selfint_face().